// Lode funziona anche senza rete: prima prova la rete (così gli aggiornamenti arrivano subito), se manca usa la copia in cache.
const CACHE = 'lode-v19';
const FILE = ['./', 'index.html', 'manifest.webmanifest', 'css/stile.css', 'css/lode.css', 'js/inizio.js', 'js/app.js', 'js/librerie.js', 'js/fornitori.js', 'js/pagina.js', 'js/lode.js', 'js/dati.js', 'js/motore.js', 'js/comandi.js', 'js/focus.js', 'js/voce.js', 'js/ai.js', 'js/mascotte.js', 'js/markdown.js', 'js/vault.js', 'js/giochi.js', 'js/formule.js', 'js/trascrizione.js', 'js/orecchio.js', 'js/file.js', 'js/sbobina.js', 'js/allenatore.js', 'js/programma.js', 'js/crocette.js', 'js/computer.js', 'js/errori.js', 'js/anki.js', 'js/tasca.js', 'js/temi.js', 'js/codice/albero.js', 'js/codice/modelli.js', 'js/codice/stampa.js', 'js/codice/progetto.js', 'js/codice/diario.js', 'js/codice/glossario.js', 'fonts/Geist-Variable.woff2', 'fonts/GeistMono-Variable.woff2', 'icone/icona.svg', 'js/ore.js', 'js/prova.js', 'js/codice/discussione.js', 'js/lingua.js', 'js/lingue/indice.js', 'js/lingue/it/comune.js', 'js/lingue/en/comune.js', 'js/lingue/es/comune.js', 'js/lingue/fr/comune.js', 'js/lingue/de/comune.js', 'js/lingue/pt/comune.js', 'js/lingue/it/barra1.js', 'js/lingue/it/barra2.js', 'js/lingue/it/barra3.js', 'js/lingue/it/errori.js', 'js/lingue/it/modelli.js', 'js/lingue/it/albero.js', 'js/lingue/it/stampa.js', 'js/lingue/it/progetto.js', 'js/lingue/it/diario.js', 'js/lingue/it/discussione.js', 'js/lingue/it/glossario.js', 'js/lingue/it/pagina.js', 'js/lingue/it/benvenuto.js', 'js/lingue/it/allenatore.js', 'js/lingue/it/sync.js', 'js/lingue/it/vault.js', 'js/lingue/it/anki.js', 'js/lingue/it/ai.js', 'js/lingue/it/programma.js', 'js/lingue/it/crocette.js', 'js/lingue/it/temi.js', 'js/lingue/it/tasca.js', 'js/lingue/it/prova.js', 'js/lingue/it/ore.js', 'js/lingue/it/computer.js', 'js/lingue/it/trascrizione.js', 'js/lingue/it/file.js', 'js/lingue/it/sbobina.js', 'js/lingue/it/focus.js', 'js/lingue/it/voce.js', 'js/lingue/it/desktop.js', 'js/comandi/comune.js', 'js/comandi/it.js', 'js/comandi/en.js', 'js/comandi/pt.js', 'js/sistemi.js', 'js/lingue/it/sistemi.js', 'js/lingue/en/sistemi.js', 'js/lingue/es/sistemi.js', 'js/lingue/fr/sistemi.js', 'js/lingue/de/sistemi.js', 'js/lingue/pt/sistemi.js'];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILE)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(k => Promise.all(k.filter(x => x !== CACHE).map(x => caches.delete(x)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;   // l'API di Claude e le librerie da jsDelivr (versione esatta, js/librerie.js) passano dritte
  e.respondWith(fetch(e.request).then(x => { if (x.ok) { const copia = x.clone(); caches.open(CACHE).then(c => c.put(e.request, copia)); } return x; }).catch(() => caches.match(e.request, { ignoreSearch: true }).then(r => r || caches.match('index.html'))));
});
