// La barra (js/lode.js, primera parte: píldora, panel, inicio, herramientas, repaso, horario, transcripción, archivos), en español.
export default {
  // las teclas para hablar y los números escritos con letras («Tres tarjetas para repasar»)
  'barra1.tasti-mac': '⌥ Espacio',
  'barra1.tasti': 'Ctrl ⇧ Espacio',
  'barra1.numeri': ['Ninguna', 'Una', 'Dos', 'Tres', 'Cuatro', 'Cinco', 'Seis', 'Siete', 'Ocho', 'Nueve', 'Diez'],
  // el saludo y la frase arriba del panel
  'barra1.saluto-notte': '¿Todavía despierto?',
  'barra1.saluto-mattina': 'Buenos días',
  'barra1.saluto-pomeriggio': 'Buenas tardes',
  'barra1.saluto-sera': 'Buenas noches',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': 'Hoy tienes {nome}. ¡Mucha suerte!',
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} tarjeta para repasar.', other: '{quante} tarjetas para repasar.' },
  'barra1.niente-in-sospeso': 'Hoy no tienes nada pendiente.',
  'barra1.dimmi-esame': 'Dime tu próximo examen y te preparo el plan.',
  // la concha: campo, pie, archivos arrastrados
  'barra1.aria-lode': 'Lode, asistente de estudio',
  'barra1.aria-torna-home': 'Volver al inicio de Lode',
  'barra1.indietro': 'Atrás',
  'barra1.aria-campo': 'Pregunta o escribe un comando',
  'barra1.campo': 'Pregunta o escribe un comando…',
  'barra1.ti-ascolto': 'Te escucho',
  'barra1.esc-annulla': 'Esc cancela',
  'barra1.un-attimo': 'Un momento…',
  'barra1.aria-parla': 'Habla (o mantén pulsado {tasti})',
  'barra1.tieni-premuto': 'Mantén pulsado para hablar <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'Los datos se quedan en este ordenador',
  'barra1.lascia-file': 'Suelta aquí el archivo',
  'barra1.lascia-file-cosa': 'PDF, diapositivas, apuntes, fotos de la pizarra: Lode los convierte en tarjetas de repaso',
  'barra1.dopo': 'Luego',
  // «Hoy»: las líneas del inicio
  'barra1.di-stamattina': 'de esta mañana',
  'barra1.di-oggi': 'de hoy',
  'barra1.di-ieri': 'de ayer',
  'barra1.di-giorno': 'del {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} definición de {corso} {quando}', other: '{n} definiciones de {corso} {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} definición de las últimas clases', other: '{n} definiciones de las últimas clases' },
  'barra1.sync-bloccata': 'Lode funciona con los datos de este ordenador: los cambios esperan en el diario.',
  'barra1.sblocca': 'Desbloquear',
  'barra1.sync-sparita': 'La carpeta de Lode en el vault ya no está',
  'barra1.sync-sparita-dett': '¿La has movido o borrado? Los datos de este ordenador están a salvo en su diario.',
  'barra1.vedi': 'Ver',
  'barra1.sync-spostamento': 'El traslado a la carpeta en la nube se interrumpió',
  'barra1.sync-spostamento-dett': 'El vault de antes está intacto: sigo desde donde lo dejé.',
  'barra1.riprendi': 'Seguir',
  'barra1.detto-sincronizza': 'Sincroniza entre ordenadores',
  'barra1.dati-altrove': 'Este vault se sincroniza con Lode en otro ordenador',
  'barra1.dati-altrove-dett': 'Los datos están en el diario de Lode 2: elige «Ya uso Lode en otro ordenador» para verlos aquí. Los cambios de ahora van a un archivo aparte, no encima de los datos.',
  'barra1.uso-gia-lode': 'Ya uso Lode',
  'barra1.detto-uso-gia-lode': 'Ya uso Lode en otro ordenador',
  'barra1.dati-fermo': 'No se puede leer el diario de Lode en este ordenador',
  'barra1.dati-fermo-dett': 'No se ha borrado nada: la carpeta de datos de Lode no responde (¿disco lleno o averiado?).',
  'barra1.riprova': 'Reintentar',
  'barra1.dati-illeggibili': 'No puedo leer tus datos',
  'barra1.dati-illeggibili-dett': 'Exámenes, notas y tarjetas están a salvo, pero la carpeta no responde (OneDrive sin conexión o archivo bloqueado). Los cambios de ahora van a un archivo aparte; lo vuelvo a intentar yo solo.',
  'barra1.lezione-alle': '{corso} a las {ora}',
  'barra1.lezione-aula-tra': 'Aula {aula} · en {n} min',
  'barra1.lezione-tra': 'en {n} min',
  'barra1.appunti': 'Apuntes',
  'barra1.orario': 'Horario',
  'barra1.completa-lode': 'Completa Lode',
  'barra1.completa-tutti-e-due': 'Obsidian y el cerebro local: un clic, gratis',
  'barra1.completa-obsidian': 'Obsidian: un clic, gratis',
  'barra1.completa-cervello': 'el cerebro local: un clic, gratis',
  'barra1.prepara': 'Preparar',
  'barra1.detto-prepara-lode': 'Prepara Lode',
  'barra1.chiudi-lezione-di': 'Cierra la clase de {corso}',
  'barra1.chiudi-lezione-dett': '{n} palabras de apuntes · saco definiciones y ★',
  'barra1.chiudi': 'Cerrar',
  'barra1.detto-chiudi-lezione': 'Cierra la clase',
  'barra1.gioco-due-minuti': 'Juego de dos minutos',
  'barra1.gioca': 'Jugar',
  'barra1.esame-ore-oggi': '{data} · {ore} h hoy para ir al día',
  'barra1.esame-in-pari': '{data} · hoy vas al día',
  'barra1.focus': 'Focus',
  'barra1.ripasso': 'Repaso',
  'barra1.ripasso-carte-min': { one: '{n} tarjeta · unos {min} min', other: '{n} tarjetas · unos {min} min' },
  'barra1.inizia': 'Empezar',
  'barra1.studio-oggi': '{ore} de estudio hoy',
  'barra1.non-hai-studiato': 'Hoy todavía no has estudiado',
  'barra1.giorni-di-fila': { one: '{n} día seguido', other: '{n} días seguidos' },
  'barra1.bastano-25': 'Con 25 minutos empiezas una racha',
  'barra1.libretto': 'Notas',
  // en clase, Repite, la transcripción, el inicio
  'barra1.in-aula': 'En clase · {corso}',
  'barra1.aula-finisce-tra': 'aula {aula} · termina en {n} min',
  'barra1.finisce-tra': 'termina en {n} min',
  'barra1.cattura-stella': '★ De examen',
  'barra1.cattura-definizione': 'Definición',
  'barra1.cattura-domanda': 'Pregunta',
  'barra1.cose-segnate': { one: '{quante} cosa marcada de examen hoy.', other: '{quante} cosas marcadas de examen hoy.' },
  'barra1.ripeti-attivo-memoria': 'Repite activo · solo en memoria, nunca en el disco',
  'barra1.ripeti': 'Repite',
  'barra1.spegni': 'Apagar',
  'barra1.ripeti-spento-invito': '<b>Repite 60 s</b> · ¿te perdiste una frase? Lode te la repite. No se guarda nada.',
  'barra1.trascrivi-lezione': 'Transcribe la clase',
  'barra1.trascrivi-lezione-dett': 'Todo lo que dice el profe, fórmulas incluidas, en la nota de Obsidian · {tasti}',
  'barra1.trascrizione-in-pausa': 'En pausa · {min} min · {parole} palabras',
  'barra1.trascrizione-in-corso': 'Transcribiendo · {min} min · {parole} palabras',
  'barra1.prima-riga': 'Escuchando: la primera línea llega en unos veinte segundos.',
  'barra1.pausa': 'Pausa',
  'barra1.fine': 'Fin',
  'barra1.oggi': 'Hoy',
  'barra1.cfu-di': '{fatti} de {tot} créditos',
  'barra1.inizia-da-qui': 'Empieza por aquí',
  'barra1.inizia-da-qui-dett': 'Escribe «clase cálculo 2 lunes 9-11 aula 7», o prueba los datos de ejemplo',
  'barra1.esempio': 'Ejemplo',
  // las herramientas y la cabecera del panel
  'barra1.strumento-gioco': 'Juego',
  'barra1.strumento-codice': 'Código',
  'barra1.strumento-note': 'Notas',
  'barra1.strumento-interrogami': 'Pregúntame',
  'barra1.strumento-esami': 'Exámenes',
  'barra1.sei-a-lezione': 'Estás en clase de {corso}. Toma apuntes tranquilo: yo me encargo de que no se pierda nada.',
  'barra1.testa-media': 'media {media}',
  'barra1.testa-serie': { one: 'racha de {n} día', other: 'racha de {n} días' },
  // la píldora
  'barra1.ripeti-attivo-titolo': 'Repite activo: el último minuto y medio, solo en memoria',
  'barra1.in-pausa': 'en pausa',
  'barra1.pausa-minuscolo': 'descanso',
  'barra1.aria-timer': '{cosa}: quedan {resta}',
  'barra1.prova-generale': 'Simulacro de examen',
  'barra1.focus-su': 'Focus en {nome}',
  'barra1.aria-ripeti-acceso': '. Repite: micrófono encendido',
  'barra1.pillola-trascrizione-in-pausa': 'transcripción en pausa · {parole} palabras',
  'barra1.pillola-trascrivo': 'transcribiendo · {parole} palabras',
  'barra1.fine-tra': 'termina en {n} min',
  'barra1.pillola-aula-tra': 'aula {aula} · en {n} min',
  'barra1.microfono-acceso': 'micrófono encendido',
  'barra1.due-minuti': '2 minutos',
  'barra1.pillola-tra-giorni': 'en {n} d',
  // la píldora en español distingue una tarjeta de varias
  'barra1.pillola-carte': { one: '{n} tarjeta', other: '{n} tarjetas' },
  'barra1.pillola-da-ripassare': { one: 'tarjeta para repasar', other: 'tarjetas para repasar' },
  'barra1.passa-qui-sopra': 'pasa el ratón por aquí',
  'barra1.aria-pillola': 'Lode: {testo}{ripeti}. Pasa el ratón por encima o pulsa {tasti}.',
  // la conversación, «Hecho.», «Confirmar / Cancelar»
  'barra1.altre-righe': { one: '{n} línea', other: '{n} líneas' },
  'barra1.altro': 'más',
  'barra1.fatto': 'Hecho.',
  'barra1.annulla': 'Cancelar',
  'barra1.annullato-minuscolo': 'cancelado',
  'barra1.confermi': '¿Confirmas?',
  'barra1.conferma': 'Confirmar',
  'barra1.scrivi-si': 'También puedes escribir «sí».',
  'barra1.annullato': 'Cancelado.',
  'barra1.niente-cambiato': 'No he cambiado nada.',
  // Focus
  'barra1.durata': 'Duración',
  'barra1.min': 'min',
  'barra1.su-che-cosa': 'Sobre qué',
  'barra1.studio-libero': 'Estudio libre',
  'barra1.pausa-alla-fine': 'Descanso de {n} minutos al final. Las horas cuentan en el plan del examen.',
  'barra1.sintesi-focus': 'focus',
  'barra1.focus-di-min': 'Focus de {min} minutos.',
  'barra1.focus-di-min-su': 'Focus de {min} minutos en {nome}.',
  'barra1.ci-vediamo': 'Nos vemos en el descanso.',
  'barra1.sintesi-focus-min': 'focus {min} min',
  // Notas e «¿y si saco…?»
  'barra1.media-ponderata': 'Media ponderada',
  'barra1.aritmetica-esami': 'aritmética {media} · {n} exámenes',
  'barra1.nessun-voto': 'todavía sin notas',
  'barra1.base-di-laurea': 'Nota base de grado',
  'barra1.serve-gia': 'Para llegar a <b>{obiettivo}</b> te basta con aprobar los exámenes que quedan.',
  'barra1.serve-media': 'Para llegar a <b>{obiettivo}</b> necesitas una media de <b>{voto}</b> en los {cfu} créditos que faltan.',
  'barra1.serve-impossibile': 'Llegar a <b>{obiettivo}</b> ya no es posible: apunta a {punta}.',
  'barra1.e-se': '¿Y si…?',
  'barra1.esame': 'Examen',
  'barra1.voto': 'Nota',
  'barra1.simula-esito': 'Media <b>{media}</b> <span class="{classe}">{delta}</span> · base <b>{base}</b>',
  'barra1.sintesi-media-base': 'media {media}, base {base}',
  'barra1.sintesi-libretto-vuoto': 'expediente vacío',
  'barra1.simula-non-trovo': 'No encuentro **{nome}** entre tus exámenes. Añádelo con «examen {nome} 6 créditos».',
  'barra1.simula-primo': 'Con un {voto} en **{nome}** tu media empezaría en **{voto}**: base **{base}**.',
  'barra1.simula-primo-lode': 'Con un {voto} con matrícula en **{nome}** tu media empezaría en **{voto}**: base **{base}**.',
  'barra1.simula': 'Con un **{voto}** en {nome} la media pasa de {prima} a **{dopo}** ({delta}): nota base de grado **{base}**.',
  'barra1.simula-lode': 'Con un **{voto} con matrícula** en {nome} la media pasa de {prima} a **{dopo}** ({delta}): nota base de grado **{base}**.',
  'barra1.sintesi-media': 'media {media}',
  // Exámenes
  'barra1.incolla-programma': 'Pega el temario: te preparo el plan por temas',
  'barra1.giorno-cuscinetto': 'día de reserva',
  'barra1.ripasso-generale': 'repaso general',
  'barra1.niente-di-nuovo': 'nada nuevo',
  'barra1.pronto': '{n}% listo',
  'barra1.prossimi-appelli': 'Próximos exámenes · {n}',
  'barra1.esame-riga': '{data} · {cfu} créditos · {fatte} de {tot} h',
  'barra1.ore-oggi': '{ore} h hoy',
  'barra1.giorni-parola': { one: 'día', other: 'días' },
  'barra1.nessun-appello': 'Ningún examen en el calendario.',
  'barra1.senza-data': 'Sin fecha: {nomi}.',
  'barra1.nuovo-esame': 'Nuevo examen',
  'barra1.nome-esame': 'Nombre del examen',
  'barra1.cfu': 'Créditos',
  'barra1.data-appello': 'Fecha del examen',
  'barra1.aggiungi': 'Añadir',
  'barra1.programma-di': 'Temario de {nome}',
  'barra1.esame-aggiunto': '{nome} añadido.',
  'barra1.senza-data-nota': 'sin fecha',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': 'ningún examen',
  // Repaso
  'barra1.ripasso-di': 'Repaso · {nome}',
  'barra1.niente-da-ripassare': 'Hoy no hay nada que repasar. La próxima tarjeta vuelve {quando}.',
  'barra1.nessuna-carta': 'Todavía no hay tarjetas. Escribe «tarjeta: pregunta = respuesta», o arrastra aquí un PDF.',
  'barra1.risposta': 'Respuesta',
  'barra1.aggiungi-carta': 'Añadir tarjeta',
  'barra1.carta-aggiunta': 'Tarjeta añadida.',
  'barra1.torna-oggi': 'Vuelve hoy mismo al repaso.',
  'barra1.sintesi-niente-da-ripassare': 'nada que repasar',
  'barra1.mostra-risposta': 'Ver respuesta <kbd>Espacio</kbd>',
  'barra1.x-di-y': '{x} de {y}',
  'barra1.ripasso-finito': { one: 'Repaso terminado: {n} tarjeta en {min} min.', other: 'Repaso terminado: {n} tarjetas en {min} min.' },
  'barra1.difficili-domani': 'Las difíciles vuelven mañana.',
  'barra1.sintesi-carte-ripassate': { one: '{n} tarjeta repasada', other: '{n} tarjetas repasadas' },
  'barra1.sintesi-ripasso-di': { one: 'repaso de {n} tarjeta', other: 'repaso de {n} tarjetas' },
  // los comandos para probar
  'barra1.prova-a-scrivere': 'Prueba a escribir',
  'barra1.aiuto-senza-ai': 'Con el cerebro local (gratis) o tu IA (escribe «IA») también puedes pedir explicaciones, crear tarjetas con los PDF y hacer que te pregunten.',
  'barra1.sintesi-comandi': 'comandos',
  // Horario
  'barra1.orario-lezioni': { one: 'Horario · {n} clase a la semana', other: 'Horario · {n} clases a la semana' },
  'barra1.corso-aula': '{corso} · aula {aula}',
  'barra1.punto-aula': ' · aula {aula}',
  'barra1.togli': 'Quitar {nome}',
  'barra1.corso': 'Asignatura',
  'barra1.giorni': 'Días',
  'barra1.inizio': 'Inicio',
  'barra1.aula': 'Aula',
  'barra1.orario-nel-vault': 'El horario también está en el vault, en «Orario.md»: puedes cambiarlo desde Obsidian.',
  'barra1.orario-oppure-scrivi': 'O escribe: «clase cálculo 2 lunes y miércoles 9-11 aula 7».',
  'barra1.in-orario': '{corso} en el horario.',
  'barra1.sintesi-lezioni-settimana': { one: '{n} clase a la semana', other: '{n} clases a la semana' },
  // el plan para quien trabaja
  'barra1.ore-regola': { one: '{n} hora', other: '{n} horas' },
  'barra1.la-tua-settimana': 'Tu semana',
  'barra1.detto-piano-settimana': 'Plan de la semana',
  'barra1.lavori': 'Trabajas {turni}.',
  'barra1.lavori-nota': 'Lo quito de las horas de estudio, con media hora para el trayecto. Los días que trabajas estudias como máximo {tetto}: lo cambias con «los días que trabajo estudio como máximo {altro} horas».',
  'barra1.turni-cambiati': 'Turnos cambiados.',
  'barra1.turni-salvati': 'Turnos guardados.',
  'barra1.sintesi-lavoro': 'trabajo {turni}',
  'barra1.turni-tolti': 'Turnos quitados.',
  'barra1.turni-tolti-nota': 'El plan vuelve a contar todo tu día de estudio.',
  'barra1.giorno-non-lavori': '{giorno} no trabajas.',
  'barra1.ore-libere': 'Esas horas vuelven a quedar libres para estudiar.',
  'barra1.giorno-lavori-anche': '{giorno} también trabajas de {da} a {a}.',
  'barra1.solo-quel-giorno': 'Solo ese día: lo quito de las horas de estudio.',
  'barra1.tetto': 'Los días que trabajas estudias como máximo {tetto}.',
  'barra1.tetto-nota': 'El plan se rehace con este límite.',
  'barra1.studi-dalle': 'Estudias de {da} a {a}.',
  'barra1.studi-dalle-nota': 'El plan usa solo estas horas, menos clases y trabajo.',
  'barra1.togli-scelta': 'Quitar: {scelta}',
  'barra1.niente-nel-piano': 'nada en el plan',
  'barra1.settimana-lavori': 'Trabajas {turni}: lo quito de las horas de estudio, con media hora para el trayecto. Los días que trabajas estudias como máximo {tetto}.',
  'barra1.settimana-se-lavori': 'Si trabajas, dímelo: «trabajo lunes, miércoles y viernes de 14 a 19».',
  'barra1.settimana-un-esame': 'Con un solo examen y sin trabajo, el plan es el del temario.',
  'barra1.settimana-stime': 'Las horas son estimaciones: un tema nuevo, más o menos 1 h; un repaso, unos 30 min.',
  'barra1.sintesi-la-tua-settimana': 'tu semana',
  // la captura rápida en clase
  'barra1.cattura-stella-campo': '¿Qué dijo el profe que entra en el examen?',
  'barra1.cattura-definizione-campo': 'Término: definición',
  'barra1.cattura-domanda-campo': 'La pregunta para el profe',
  'barra1.scrivila-cosi': 'Escríbela así: **término: definición**.',
  'barra1.errore-vault': 'No puedo escribir en el vault: {errore}',
  'barra1.dove-sparsi': 'en los apuntes sueltos de hoy',
  'barra1.dove-in': 'en {corso}',
  'barra1.segnato-dove': '★ Apuntado {dove}.',
  'barra1.definizione-dove': '«{termine}» {dove}.',
  'barra1.domanda-dove': 'Pregunta guardada {dove}.',
  // transcribir: en clase, desde el ordenador, desde una grabación
  'barra1.videolezioni-app': 'La transcripción de las videoclases está en la **app de escritorio** de Lode: escucha el audio del ordenador y escribe en la nota de Obsidian de la clase.',
  'barra1.sto-gia-trascrivendo': 'Ya estoy transcribiendo.',
  'barra1.parole-finora': { one: '{n} palabra hasta ahora.', other: '{n} palabras hasta ahora.' },
  'barra1.lezione-dal-computer': 'Clase desde el ordenador',
  'barra1.computer-spiega': 'Pon la videoclase (en la plataforma de tu universidad, en Teams, Zoom o donde la sigas): escucho el audio que sale del ordenador y la escribo en la nota de la clase, fórmulas incluidas.',
  'barra1.nome-del-corso': 'Nombre de la asignatura',
  'barra1.computer-patto': 'Solo para que estudies tú: no descargo el vídeo ni subo nada a internet, el audio no se guarda y en la nota solo va el texto. Las clases son de los profesores: no compartas la transcripción si el reglamento de tu universidad no lo permite.',
  'barra1.computer-mac': 'La primera vez el Mac te pide permiso para grabar el audio del sistema.',
  'barra1.computer-windows': 'En Windows oyes el audio como siempre: yo también lo escucho.',
  'barra1.computer-linux': 'En Linux escucho el «monitor» de la salida de audio.',
  'barra1.detto-trascrivi-videolezione': 'Transcribe la videoclase de {corso}',
  'barra1.sintesi-lezione-dal-computer': 'clase desde el ordenador',
  'barra1.computer-permesso-mac': 'El Mac no me da el audio del ordenador: en **Ajustes del Sistema › Privacidad y seguridad › Grabación de audio de pantalla y del sistema** activa Lode y vuelve a intentarlo (a veces hay que volver a abrir Lode).',
  'barra1.computer-permesso': 'El sistema no me da el audio del ordenador: vuelve a intentarlo y acepta la petición para compartir.',
  'barra1.computer-non-sento-mac': 'No puedo escuchar el audio del ordenador (necesitas macOS 14.2 o más reciente). {errore}',
  'barra1.computer-non-sento-windows': 'No puedo escuchar el audio del ordenador. {errore}',
  'barra1.computer-non-sento-linux': 'No puedo escuchar el audio del ordenador (necesitas PulseAudio o PipeWire). {errore}',
  'barra1.computer-muto': 'No oigo nada del ordenador. ¿Ya empezó la videoclase, con el volumen subido?',
  'barra1.computer-muto-mac': 'No oigo nada del ordenador. ¿Ya empezó la videoclase, con el volumen subido? Si es así, el Mac no me está dando el audio: **Ajustes del Sistema › Privacidad y seguridad › Grabación de audio de pantalla y del sistema**, activa Lode y vuelve a intentarlo.',
  'barra1.trascrizione-app': 'La transcripción de las clases está en la **app de escritorio** de Lode: escribe directamente en la nota de Obsidian de la clase.',
  'barra1.computer-aggiorna': 'Esta versión no puede escuchar el audio del ordenador: actualiza Lode.',
  'barra1.preparo-voce': 'Preparando la voz…',
  'barra1.trascrivo-file': 'Transcribo «{file}» en la clase de {corso}.',
  'barra1.puoi-chiudere': 'Puedes cerrar el panel: te aviso al final.',
  'barra1.sintesi-registrazione': 'grabación en transcripción',
  'barra1.ascolto-computer': 'Escucho el audio del ordenador para {corso}.',
  'barra1.ascolto-computer-nota': 'Pon la videoclase: las líneas llegan a la nota cada 20-30 segundos. Cuando termine, escribe «fin de clase».',
  'barra1.apri-in-obsidian': 'Abrir en Obsidian',
  'barra1.sintesi-videolezione': 'videoclase en transcripción',
  'barra1.avviso-videolezione': 'Escuchando la videoclase',
  'barra1.trascrivo-sparsi': 'Transcribo en los apuntes sueltos.',
  'barra1.trascrivo-lezione-di': 'Transcribo la clase de {corso}.',
  'barra1.righe-ogni': 'Las líneas llegan a la nota cada 20-30 segundos.',
  'barra1.sintesi-trascrizione-avviata': 'transcripción empezada',
  'barra1.avviso-trascrivo': 'Transcribiendo la clase',
  'barra1.errore-trascrivere': 'No puedo transcribir: {errore}',
  'barra1.non-sto-trascrivendo': 'No estoy transcribiendo nada.',
  'barra1.ultimi-secondi': 'Transcribiendo los últimos segundos…',
  'barra1.lezione-trascritta': 'Clase transcrita: {parole} palabras.',
  'barra1.righe-sospese': { one: '{n} línea todavía no está en la nota (la carpeta no responde): la escribo en cuanto pueda, no me cierres.', other: '{n} líneas todavía no están en la nota (la carpeta no responde): las escribo en cuanto pueda, no me cierres.' },
  'barra1.tutto-nella-nota': 'Está todo en la nota.',
  'barra1.riordina': 'Pasar a limpio',
  'barra1.detto-riordina': 'Pasa a limpio la clase',
  'barra1.condividi': 'Compartir',
  'barra1.detto-condividi': 'Comparte la transcripción',
  'barra1.sintesi-parole-trascritte': { one: '{n} palabra transcrita', other: '{n} palabras transcritas' },
  'barra1.con-cervello-locale': 'Con el **cerebro local** (desde «Prepara Lode») la transcripción se convierte en apuntes limpios, definiciones y ★ con un clic.',
  // pasar a limpio la clase con la IA
  'barra1.non-trovo-trascrizione-di': 'No encuentro ninguna transcripción de **{corso}**.',
  'barra1.non-trovo-trascrizione': 'No encuentro ninguna clase transcrita. En clase pulsa **Transcribe la clase**.',
  'barra1.riordinare-serve-ai': 'Para pasar a limpio hace falta la IA: instala el **cerebro local** desde «Prepara Lode» (gratis, sin conexión) o conecta tu IA: escribe «IA».',
  'barra1.riordino': 'Pasando a limpio {corso}…',
  'barra1.riordino-per-cento': 'Pasando a limpio {corso}… {n}%',
  'barra1.errore-riordinare': 'No he podido pasarlo a limpio: {errore}',
  'barra1.salvare-riordinati': '¿Guardar los apuntes en limpio de {corso}?',
  'barra1.riordinati-nota': 'Van a la nota, en «Appunti riordinati da Lode», debajo de la transcripción (que se queda). Los ha escrito {motore}: revísalos.',
  'barra1.appunti-salvati': 'Apuntes guardados en la nota.',
  'barra1.sintesi-lezione-riordinata': 'clase pasada a limpio',
  'barra1.detto-definizioni-lezione': 'Definiciones de la clase',
  // «Repite» y el permiso para escuchar la clase
  'barra1.ascoltare-lezione': '¿Escuchar la clase?',
  'barra1.consenso-ripeti': 'guardo en memoria solo el último minuto y medio, nunca en el disco',
  'barra1.trascrivi': 'Transcribir',
  'barra1.consenso-trascrivi': 'escribo la clase en la nota, el audio no se guarda',
  'barra1.dove': 'Dónde',
  'barra1.consenso-dove': 'todo en el ordenador, nada en internet',
  'barra1.consenso-nota': 'Grabar una clase depende del reglamento de tu universidad y del profesor: pregunta antes.',
  'barra1.solo-la-prima-volta': 'Solo te lo pregunto la primera vez.',
  'barra1.d-accordo': 'De acuerdo.',
  'barra1.ripeti-app': '«Repite» está en la **app de escritorio** de Lode.',
  'barra1.ripeti-e-attivo': 'Repite está activo.',
  'barra1.ripeti-attivo-nota': 'Guardo en memoria el último minuto y medio, nunca en el disco. ¿Te perdiste algo? {tasti} o «repite».',
  'barra1.ripeti-attivo-nota-fuori': 'Guardo en memoria el último minuto y medio, nunca en el disco. ¿Te perdiste algo? {tasti} o «repite». Fuera del horario de clase me quedo encendido como máximo 3 horas.',
  'barra1.detto-spegni-ripeti': 'Apaga Repite',
  'barra1.sintesi-ripeti-attivo': 'repite activo',
  'barra1.ripeti-spento': 'Repite apagado.',
  'barra1.microfono-resta': 'El micrófono sigue encendido para la transcripción, hasta que la cierres.',
  'barra1.microfono-chiuso': 'El micrófono está cerrado.',
  'barra1.non-si-accende-piu': ' En clase ya no se enciende solo: lo vuelves a encender con {tasti}.',
  'barra1.ripeti-e-spento': 'Repite está apagado.',
  'barra1.ripeti-e-spento-nota': 'Repite te escribe lo que dijo el profe en los últimos 60 segundos: lo enciendes aquí o con {tasti}. Si querías otra cosa, pídemela con tus palabras.',
  'barra1.accendi': 'Encender',
  'barra1.detto-accendi-ripeti': 'Enciende Repite',
  'barra1.sintesi-ripeti-spento': 'repite apagado',
  'barra1.ascolto-da-un-attimo': 'Acabo de empezar a escuchar: todavía no tengo nada que repetirte.',
  'barra1.riascolto': { one: 'Vuelvo a escuchar el último segundo…', other: 'Vuelvo a escuchar los últimos {n} segundos…' },
  'barra1.errore-riascoltare': 'No he podido volver a escuchar: {errore}',
  'barra1.niente-sentito': 'En los últimos 60 segundos no he oído hablar a nadie.',
  'barra1.ultimi-secondi-ora': { one: 'El último segundo · {ora}', other: 'Los últimos {n} segundos · {ora}' },
  'barra1.agli-appunti': 'A los apuntes',
  'barra1.copia': 'Copiar',
  'barra1.copiato': 'Copiado',
  'barra1.negli-appunti-di': 'En los apuntes de {corso}.',
  // compartir la transcripción
  'barra1.sbobine-app': 'Las transcripciones se comparten desde la **app de escritorio**.',
  'barra1.non-trovo-lezione-di': 'No encuentro ninguna clase de **{corso}** para compartir.',
  'barra1.non-trovo-lezione': 'No encuentro ninguna clase para compartir: primero transcríbela o pásala a limpio.',
  'barra1.preparo-sbobina': 'Preparando la transcripción…',
  'barra1.sbobina-pronta': 'Transcripción de {corso} lista.',
  'barra1.scegli-dove': 'Elige dónde mandarla: AirDrop, Mensajes, Mail…',
  'barra1.nella-cartella-sbobine': 'Está en la carpeta «Sbobine» del vault.',
  'barra1.mostra': 'Mostrar',
  'barra1.sintesi-sbobina-condivisa': 'transcripción compartida',
  'barra1.errore-sbobina': 'No puedo preparar la transcripción: {errore}',
  // las tarjetas para Anki
  'barra1.anki-non-trovo-di': 'No encuentro tarjetas ni definiciones de **{corso}** para exportar.',
  'barra1.anki-non-trovo': 'Todavía no tengo tarjetas ni definiciones para exportar: apunta alguna definición en clase («def: gradiente = …») o crea tarjetas con un PDF.',
  'barra1.anki-carte-mazzi': { one: '{n} tarjeta para Anki, {mazzi} mazos.', other: '{n} tarjetas para Anki, {mazzi} mazos.' },
  'barra1.anki-carte-mazzo': { one: '{n} tarjeta para Anki en el mazo {mazzo}.', other: '{n} tarjetas para Anki en el mazo {mazzo}.' },
  'barra1.anki-doppioni': { one: ' {n} duplicada omitida.', other: ' {n} duplicadas omitidas.' },
  'barra1.anki-importa-download': 'En Anki: Archivo › Importar, elige «{file}» (está en descargas) y como tipo de nota «Básico» («Basic» en inglés).',
  'barra1.anki-importa-vault': 'En Anki: Archivo › Importar, elige «{file}» en el vault y como tipo de nota «Básico» («Basic» en inglés).',
  'barra1.scarica': 'Descargar',
  'barra1.sintesi-anki': 'tarjetas para Anki',
  'barra1.errore-mostrare': 'No puedo mostrar el archivo: {errore}',
  'barra1.errore-anki': 'No puedo guardar el archivo para Anki: {errore}',
  // los archivos que se sueltan en la píldora
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'diapositivas de PowerPoint',
  'barra1.tipo-word': 'documento de Word',
  'barra1.tipo-testo': 'texto',
  'barra1.tipo-sbobina': 'transcripción de Lode',
  'barra1.tipo-carte': 'tarjetas (Anki/CSV)',
  'barra1.tipo-foto': 'foto',
  'barra1.tipo-audio': 'grabación de audio',
  'barra1.tipo-altro': 'archivo',
  'barra1.uno-alla-volta': { one: 'De uno en uno: empiezo por **{nome}**, luego suelta el otro.', other: 'De uno en uno: empiezo por **{nome}**, luego suelta los otros {n}.' },
  'barra1.errore-leggere-file': 'No puedo leer el archivo: {errore}',
  'barra1.serve-ai': 'necesitas el cerebro local o tu IA',
  'barra1.serve-app': 'en la app de escritorio',
  'barra1.op-sbobina': 'Añadir a mi vault',
  'barra1.op-sbobina-d': 'Se convierte en una clase en tu Obsidian: las definiciones y las ★ entran en los juegos',
  'barra1.op-allega-soltanto': 'Solo adjuntar',
  'barra1.op-allega-soltanto-d': 'Guardo el archivo en los adjuntos de la clase',
  'barra1.op-importa-carte': 'Importar las tarjetas',
  'barra1.op-importa-carte-d': 'Una por línea: pregunta, luego Tab, «;» o « = », luego respuesta',
  'barra1.op-audio': 'Transcribir la grabación',
  'barra1.op-audio-d': 'Toda la clase en apuntes, fórmulas incluidas, en la nota de la clase',
  'barra1.op-allega': 'Adjuntar a la clase',
  'barra1.op-allega-audio-d': 'Guardo el audio en los adjuntos, con el enlace en la nota',
  'barra1.op-lavagna': 'Pasar a apuntes',
  'barra1.op-lavagna-d': 'Texto y fórmulas en LaTeX, en la nota de la clase',
  'barra1.op-carte': 'Tarjetas de repaso',
  'barra1.op-carte-foto-d': 'Las preguntas que harían en el examen',
  'barra1.op-allega-foto-d': 'La foto en la nota de la clase',
  'barra1.op-carte-d': 'Preguntas y respuestas para el repaso espaciado',
  'barra1.op-riassunto': 'Resumen en Obsidian',
  'barra1.op-riassunto-d': 'Apuntes ordenados con fórmulas, en una nota nueva',
  'barra1.op-definizioni': 'Definiciones para los juegos',
  'barra1.op-definizioni-d': 'Las añado a la clase: se convierten en juegos de memoria',
  'barra1.op-orale': 'Pregúntame sobre esto',
  'barra1.op-orale-d': 'Un profe de oral con preguntas sobre este material',
  'barra1.op-allega-d': 'Guardo el archivo con el enlace en la nota',
  'barra1.op-crocette': 'Test',
  'barra1.op-crocette-d': 'Preguntas con 4 respuestas, como en el escrito: práctica o simulación de examen',
  'barra1.op-temi': 'Exámenes anteriores',
  'barra1.op-temi-d': 'Los ejercicios de un examen viejo, separados por tema, uno al día en el plan',
  'barra1.op-programma': 'Es el temario',
  'barra1.op-programma-d': 'Lo divido en temas y te preparo el plan hasta el examen',
  'barra1.op-domande': 'Preguntas de exámenes pasados',
  'barra1.op-domande-d': 'Las pongo debajo de sus temas: los que más salen suben en el plan',
};
