// Textos de la barra, tercera parte (español): repaso de bolsillo, Moodle, test, exámenes anteriores, simulacro de
// examen, temario, «te lo explico yo», envío, archivos, voz, atajos y avisos de la app (js/lode.js).
export default {
  // Repaso de bolsillo
  'barra3.tasca-solo-app': 'El repaso de bolsillo va en la app: necesita el vault de Obsidian.',
  'barra3.tasca-spenta': 'Repaso de bolsillo solo cuando lo pidas.',
  'barra3.tasca-spenta-nota': 'La nota {nota} se queda en el vault: escribe «repaso de bolsillo» para actualizarla.',
  'barra3.tasca-spenta-sintesi': 'repaso de bolsillo apagado',
  'barra3.tasca-preparo': 'Preparando la nota…',
  'barra3.tasca-errore': 'No puedo leer o escribir la nota {nota}: {errore}',
  'barra3.tasca-estranea': 'En el vault ya hay una nota **{nota}** que no ha escrito Lode: no la toco. Cámbiale el nombre y vuelve a intentarlo.',
  'barra3.tasca-segnata-sapevi': 'He apuntado la tarjeta que hiciste en el móvil: te la sabías.',
  'barra3.tasca-segnata-non-sapevi': 'He apuntado la tarjeta que hiciste en el móvil: no te la sabías.',
  'barra3.tasca-segnate': 'He apuntado {n} tarjetas que hiciste en el móvil: te sabías {sapevo}, {no} no.',
  'barra3.tasca-gia': { one: 'Una tarjeta ya la habías repasado en el ordenador: no la apunto dos veces.', other: '{n} tarjetas ya las habías repasado en el ordenador: no las apunto dos veces.' },
  'barra3.tasca-vecchia': 'La nota del móvil es de una vuelta antigua: no apunto nada.',
  'barra3.tasca-cambiata': 'La nota todavía está cambiando: Obsidian la está sincronizando. No la reescribo ahora, vuelve a intentarlo en un minuto.',
  'barra3.tasca-domani': { one: 'En la nota {nota} hay {n} tarjeta para mañana.', other: 'En la nota {nota} hay {n} tarjetas para mañana.' },
  'barra3.tasca-domani-niente': 'Mañana no tienes tarjetas que repasar: lo dice la nota {nota}.',
  'barra3.tasca-titolo': 'Repaso de bolsillo',
  'barra3.tasca-aspetta': 'Espera a que el móvil termine de sincronizar y vuelve a intentarlo. Si la nota buena no llega, reescríbela: las marcas de esa copia no las apunto.',
  'barra3.apri-nota': 'Abrir la nota',
  'barra3.riscrivi-nota': 'Reescribir la nota',
  'barra3.tasca-solo-quando': 'Solo cuando lo pida',
  'barra3.tasca-ogni-sera': 'Cada noche',
  'barra3.tasca-sera-accesa': 'Cada noche después de las 19 la reescribo sola, si Lode está abierto.',
  'barra3.tasca-sera-spenta': 'Solo la reescribo cuando me lo pidas.',
  'barra3.tasca-come-arriva': 'Funciona si el vault llega al móvil (iCloud, Obsidian Sync, Syncthing). Lode no usa la red: la nota la lleva el servicio que ya usas.',
  'barra3.non-apro-nota': 'No puedo abrir la nota: {errore}',
  'barra3.tasca-riscrivi-detto': 'Reescribe la nota {nota}',
  'barra3.tasca-sintesi': 'repaso de bolsillo',

  // Moodle
  'barra3.moodle-solo-app': 'La conexión con Moodle está en la **app de escritorio** de Lode.',
  'barra3.moodle-non-risponde': 'Moodle no responde: {errore}',
  'barra3.moodle-non-collegato': 'Moodle no está conectado.',
  'barra3.moodle-scollegato': 'Moodle desconectado.',
  'barra3.moodle-scollegato-nota': 'El token se ha borrado de este ordenador. Los archivos ya descargados se quedan en tu vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} curso seguido: {corsi}', other: '{n} cursos seguidos: {corsi}' },
  'barra3.file-nuovi': 'Archivos nuevos',
  'barra3.scadenze': 'Entregas',
  'barra3.corsi': 'Cursos',
  'barra3.scollega': 'Desconectar',
  'barra3.moodle-senza-portachiavi': 'Este ordenador no tiene llavero: la conexión dura hasta que cierres Lode.',
  'barra3.moodle-novita-detto': 'Novedades de Moodle',
  'barra3.moodle-corsi-detto': 'Cursos de Moodle',
  'barra3.moodle-scollega-detto': 'Desconecta Moodle',
  'barra3.moodle-collega': 'Conectar Moodle',
  'barra3.moodle-collega-intro': 'La plataforma de cursos de tu universidad (campus virtual, aula virtual, e-learning…): Lode trae los archivos nuevos y las entregas de los cursos que elijas. Solo lectura: no entrega nada ni escribe nada.',
  'barra3.moodle-indirizzo-esempio': 'Dirección, por ejemplo campusvirtual.ucm.es',
  'barra3.moodle-indirizzo': 'Dirección de Moodle',
  'barra3.continua': 'Continuar',
  'barra3.moodle-collega-nota': 'Entras como en la app oficial de Moodle. La conexión se guarda cifrada en este ordenador, nunca en el vault; con «desconecta moodle» la quitas.',
  'barra3.moodle-cerco': 'Buscando el sitio…',
  'barra3.moodle-non-indirizzo': 'Esto no parece una dirección.',
  'barra3.moodle-non-trovo': 'No encuentro un Moodle con la app activada en esta dirección ({motivo}). Copia la dirección de la barra del navegador cuando estés en la página de tus cursos.',
  'barra3.moodle-accesso-annullato': 'Acceso cancelado.',
  'barra3.moodle-accesso-fallito': 'No se pudo entrar: {motivo}.',
  'barra3.moodle-entra-sso': '<b>{nome}</b> · se entra con el acceso de la universidad (tu usuario institucional), en una ventana de Lode.',
  'barra3.accedi': 'Entrar',
  'barra3.moodle-accedi-finestra': 'Entra en la ventana que se ha abierto…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · acceso con usuario y contraseña de Moodle.',
  'barra3.utente': 'Usuario',
  'barra3.password': 'Contraseña',
  'barra3.moodle-password-nota': 'La contraseña solo va a Moodle: Lode no la guarda.',
  'barra3.moodle-collega-sintesi': 'conecta Moodle',
  'barra3.moodle-leggo-corsi': 'Leyendo tus cursos…',
  'barra3.moodle-corsi-errore': 'No puedo leer los cursos: {errore}',
  'barra3.moodle-nessun-corso': 'En Moodle no estás inscrito en ningún curso.',
  'barra3.moodle-corsi-titolo': 'Cursos de Moodle · {sito}',
  'barra3.moodle-scegli-corsi': 'Elige cuáles seguir y con qué asignatura de Lode: sus archivos nuevos llegan aquí.',
  'barra3.concluso': 'terminado',
  'barra3.moodle-corso-per': 'Asignatura de Lode para {nome}',
  'barra3.non-seguire': 'No seguir',
  'barra3.moodle-con-nome': 'Con el nombre de Moodle',
  'barra3.salva': 'Guardar',
  'barra3.moodle-seguo': { one: 'Sigo {n} curso en Moodle.', other: 'Sigo {n} cursos en Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Ningún curso seguido.',
  'barra3.moodle-ti-avviso': 'Te aviso cuando lleguen archivos nuevos.',
  'barra3.moodle-corsi-sintesi': 'cursos de Moodle',
  'barra3.moodle-guardo': 'Mirando los archivos en Moodle…',
  'barra3.moodle-non-leggo': 'No puedo leer {corsi}: {errore}.',
  'barra3.moodle-nessun-file': 'En los cursos que sigues todavía no hay archivos.',
  'barra3.moodle-piu-recenti': 'los archivos más recientes',
  'barra3.moodle-file-nuovi': { one: '{n} archivo nuevo', other: '{n} archivos nuevos' },
  'barra3.moodle-niente-nuovo': 'nada nuevo, los últimos archivos',
  'barra3.nuovo': 'nuevo',
  'barra3.apri': 'Abrir',
  'barra3.moodle-apri-nota': '«Abrir» lo lleva a Lode como si lo hubieras arrastrado: tarjetas, resumen, temario, test.',
  'barra3.scarico': 'Descargando…',
  'barra3.non-riesco': 'No puedo',
  'barra3.aperto': 'Abierto',
  'barra3.moodle-file-da': '{nome} de Moodle',
  'barra3.file-illeggibile': 'No puedo leer el archivo: {errore}',
  'barra3.moodle-sintesi-nuovi': 'Moodle: {n} archivos nuevos',
  'barra3.moodle-nessuna-scadenza': 'No hay entregas en Moodle en las próximas semanas.',
  'barra3.moodle-scadenze-titolo': 'Entregas en Moodle',
  'barra3.scadenze-sintesi': '{n} entregas',
  'barra3.guarda': 'Ver',

  // test
  'barra3.non-trovo-esame': 'No encuentro el examen **{nome}**.',
  'barra3.il-tuo-materiale': 'tu material',
  'barra3.quiz-poco-materiale': 'Para un test de **{nome}** necesito más material: arrastra los apuntes del curso o las diapositivas (elige «Test»), o crea algunas tarjetas.',
  'barra3.quiz-senza-ai': 'Para el test sin IA necesito al menos 4 tarjetas o 4 definiciones de **{nome}**. Con la IA (escribe «IA») también lo hago con los apuntes del curso.',
  'barra3.quiz-fonte-dispensa-nome': 'Preguntas sacadas de «{nome}».',
  'barra3.quiz-fonte-dispensa': 'Preguntas sacadas del material del curso.',
  'barra3.quiz-fonte-ai': 'Preguntas de tus tarjetas, definiciones y preguntas de examen.',
  'barra3.quiz-fonte-carte-definizioni': 'Preguntas de tus tarjetas y definiciones.',
  'barra3.quiz-fonte-carte': 'Preguntas de tus tarjetas.',
  'barra3.quiz-fonte-definizioni': 'Preguntas de tus definiciones.',
  'barra3.quiz-le-scrive': 'Las escribe {motore}: me quedo solo con las que el material demuestra.',
  'barra3.quiz-sbagliate-altre': 'Las respuestas incorrectas son las de otras tarjetas de la asignatura.',
  'barra3.quiz-titolo': 'Test · {nome}',
  'barra3.quiz-allenamento': 'Práctica · {n} preguntas',
  'barra3.quiz-allenamento-sotto': 'La corrección al momento, con la explicación',
  'barra3.quiz-simulazione': 'Simulación de examen · {n} preguntas en {n} minutos',
  'barra3.quiz-simulazione-sotto': 'Como en el escrito: el tiempo corre, la corrección al final, la nota sobre 30',
  'barra3.quiz-simulazione-detto': 'Simulación de examen · {nome}',
  'barra3.quiz-detto': 'Test · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulación · {nome}',
  'barra3.quiz-preparo': 'Preparando las preguntas… {fatte} de {n}',
  'barra3.quiz-errore': 'No puedo preparar las preguntas: {errore}',
  'barra3.quiz-niente': 'No he podido preparar preguntas fiables con este material.',
  'barra3.quiz-sintesi': 'test de {nome}',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} de {n}',
  'barra3.x-di-n': '{x} de {n}',
  'barra3.quiz-domanda-n': 'Pregunta {x} de {n}',
  'barra3.indietro': 'Atrás',
  'barra3.salta': 'Saltar',
  'barra3.lascia-vuota': 'Dejar en blanco',
  'barra3.consegna': 'Entregar',
  'barra3.quiz-giusta-e': 'La respuesta correcta es la {lettera}.',
  'barra3.avanti': 'Siguiente',
  'barra3.risultato': 'Resultado',
  'barra3.tasto-invio': 'Intro',
  'barra3.quiz-voto': 'Nota: <em>{voto}</em>',
  'barra3.tempo-scaduto': 'se acabó el tiempo',
  'barra3.quiz-tutte-giuste': 'Todas bien.',
  'barra3.quiz-da-rivedere': { one: '{n} para revisar.', other: '{n} para revisar.' },
  'barra3.quiz-scartate': { one: '{n} pregunta descartada porque el material no la demostraba', other: '{n} preguntas descartadas porque el material no las demostraba' },
  'barra3.da-rivedere': 'Para revisar',
  'barra3.lasciata-vuota': 'En blanco',
  'barra3.hai-scelto': 'Elegiste: {x}',
  'barra3.giusta-era': 'Correcta: {x}',
  'barra3.quiz-sbagliate-carte': 'Las incorrectas se convierten en tarjetas',
  'barra3.quiz-un-altro': 'Otro test',
  'barra3.quiz-punti': 'Una respuesta correcta vale 1 punto; incorrecta o en blanco, 0.',
  'barra3.quiz-regole-vere': 'El escrito de verdad puede tener otras reglas (penalización por las incorrectas, mínimos): esto es un entrenamiento.',
  'barra3.quiz-carte-aggiunte': { one: '{n} tarjeta añadida: vuelve hoy en el repaso', other: '{n} tarjetas añadidas: vuelven hoy en el repaso' },
  'barra3.quiz-sintesi-esito': 'test de {nome}: {giuste} de {n}',

  // exámenes anteriores
  'barra3.tema-del': 'del {data}',
  'barra3.tema-di': 'de «{fonte}»',
  'barra3.tema-es': 'ej. {es}',
  'barra3.tema-es-da': 'ej. {es} {da}',
  'barra3.tema-circa': 'unos {min} min en papel',
  'barra3.leggo-file': 'Leyendo {nome}…',
  'barra3.cmd-temi-di': '«exámenes anteriores de {nome}:»',
  'barra3.cmd-temi': '«exámenes anteriores:»',
  'barra3.temi-scansione': 'Este PDF parece un escaneo: sin IA no leo las imágenes. Pega el texto de los ejercicios con {cmd} y el texto debajo.',
  'barra3.temi-illeggibile': 'No puedo leer el texto de este archivo. Pégalo con {cmd} y el texto debajo.',
  'barra3.aggiungi-prima-esame': 'Primero añade el examen, por ejemplo: «examen cálculo 2 el 15 de enero 9 créditos».',
  'barra3.non-trovo-esame-aggiungi': 'No encuentro el examen **{nome}**. Añádelo primero, por ejemplo: «examen {nome} el 15 de enero 9 créditos».',
  'barra3.aggiungi-esame-compito': 'Primero añade un examen, por ejemplo: «examen cálculo 2 el 15 de enero 9 créditos». Después pega un examen viejo.',
  'barra3.prova-invito': '¿Quieres hacer un examen entero, con el tiempo de verdad?',
  'barra3.prova-generale': 'Simulacro de examen',
  'barra3.prova-generale-di': 'Simulacro de examen de {nome}',
  'barra3.temi-titolo': 'Exámenes anteriores · {nome}',
  'barra3.temi-nessuno-oggi': 'Hoy no te toca ningún ejercicio.',
  'barra3.temi-prossimo': 'El próximo vuelve {data}.',
  'barra3.temi-vuoto': 'Pega el texto de un examen viejo (los que circulan en el grupo de clase o en la web del profe), o arrastra el PDF. Lo divido en ejercicios, los pongo bajo sus temas y cada día te propongo uno.',
  'barra3.temi-segnaposto': 'Problema 1. Calcular…&#10;Problema 2. Estudiar…',
  'barra3.temi-testo-compito': 'Texto del examen',
  'barra3.temi-dividi': 'Dividir en ejercicios',
  'barra3.temi-di': 'Exámenes anteriores de {nome}',
  'barra3.temi-di-sintesi': 'exámenes anteriores de {nome}',
  'barra3.temi-nessun-esercizio': 'No he encontrado ejercicios en este texto.',
  'barra3.temi-compito-del': 'examen {data}',
  'barra3.temi-un-pezzo': 'No he encontrado «Problema 1», «Problema 2»… Si el examen tiene varios ejercicios, márcalos así y vuelve a pegarlo.',
  'barra3.temi-senza-programma': 'Para {nome} todavía no hay temario: los guardo sin tema.',
  'barra3.temi-metti': 'Ponerlos en el plan',
  'barra3.temi-es': 'Ej. {n}',
  'barra3.temi-con-soluzione': 'con la solución del profe',
  'barra3.temi-argomento-di': 'Tema del ejercicio {n}',
  'barra3.temi-che-argomento': '¿De qué tema es?',
  'barra3.temi-unisci': 'Unir al anterior',
  'barra3.togli': 'Quitar',
  'barra3.temi-nel-piano': { one: '{n} ejercicio en el plan.', other: '{n} ejercicios en el plan.' },
  'barra3.temi-nel-piano-arg': { one: '{n} ejercicio en el plan: {con} con su tema, {senza} sin él.', other: '{n} ejercicios en el plan: {con} con su tema, {senza} sin él.' },
  'barra3.temi-senza-programma-nota': 'Sin temario no sé dónde ponerlos: pega el temario de {nome} y los coloco.',
  'barra3.temi-doppi': { one: '{n} ya estaba.', other: '{n} ya estaban.' },
  'barra3.temi-ogni-giorno': 'Cada día, uno sobre los temas del plan.',
  'barra3.programma': 'Temario',
  'barra3.fanne-uno': 'Haz uno',
  'barra3.esercizio-di': 'Ejercicio de {nome}',
  'barra3.temi-gia': 'Estos ejercicios ya estaban.',
  'barra3.temi-sintesi-n': { one: 'exámenes anteriores de {nome}: {n} ejercicio', other: 'exámenes anteriores de {nome}: {n} ejercicios' },
  'barra3.tema-titolo': 'Ejercicio · {nome}',
  'barra3.tema-fallo': 'Hazlo en papel, sin mirar los apuntes. Cuando termines:',
  'barra3.giusto': 'Bien',
  'barra3.sbagliato': 'Mal',
  'barra3.non-sapevo': 'No sabía por dónde empezar',
  'barra3.tema-voto-tuo': 'La nota te la pones tú: Lode no corrige el ejercicio.',
  'barra3.tema-torna': { one: 'Vuelve en {n} día.', other: 'Vuelve en {n} días.' },
  'barra3.tema-guarda-soluzione': 'Mira la solución y vuelve a hacerlo desde cero, no te limites a releerla.',
  'barra3.tema-rileggi': 'Relee el tema y vuelve a hacerlo desde cero, sin mirar.',
  'barra3.tema-prima-rileggi-arg': 'Primero relee el tema: {arg}.',
  'barra3.tema-prima-rileggi': 'Primero relee el tema.',
  'barra3.tema-vedi-soluzione': 'Ver la solución del profe',
  'barra3.tema-altro': 'Otro ejercicio',
  'barra3.esercizio-di-esito': 'ejercicio de {nome}: {esito}',
  'barra3.esercizio-di-sintesi': 'ejercicio de {nome}',

  // simulacro de examen
  'barra3.prova-prima-compiti': 'Primero pega o arrastra los exámenes viejos: «exámenes anteriores de {nome}: …».',
  'barra3.prova-compito-del': 'Examen del {data}',
  'barra3.prova-scelti': 'Ejercicios elegidos por ti',
  'barra3.prova-compito-fonte': 'Examen «{fonte}»',
  'barra3.prova-compito-incollato': 'Examen pegado',
  'barra3.n-esercizi': { one: '{n} ejercicio', other: '{n} ejercicios' },
  'barra3.n-punti': '{punti} puntos',
  'barra3.prova-titolo': 'Simulacro de examen · {nome}',
  'barra3.prova-quanto-dura': '¿Cuánto dura?',
  'barra3.prova-minuti-aria': 'Cuántos minutos dura el examen',
  'barra3.minuti': 'minutos',
  'barra3.prova-altro-compito': 'Otro examen',
  'barra3.prova-gia-fatto': 'ya hecho el {data}',
  'barra3.comincio': 'Empiezo',
  'barra3.prova-su-carta': 'En papel, sin apuntes, como en el examen. Las soluciones las ves al final.',
  'barra3.prova-durata-letta': 'Lo he leído en el examen.',
  'barra3.prova-di-solito': 'Normalmente 2 horas.',
  'barra3.prova-sintesi': 'simulacro de examen de {nome}',
  'barra3.prova-scegli': 'No encuentro un examen entero: elige tú los ejercicios.',
  'barra3.prova-scegli-nota': '120 minutos, en papel, sin apuntes. Las soluciones las ves al final.',
  'barra3.prova-ferma-pausa': 'Hay un descanso en marcha: ¿lo paro y empiezo el simulacro?',
  'barra3.prova-ferma-focus': 'Hay un focus en marcha: ¿lo paro y empiezo el simulacro?',
  'barra3.si-parti': 'Sí, empieza',
  'barra3.no': 'No',
  'barra3.prova-durata-fino': '{min} minutos, hasta las {ora}',
  'barra3.esercizio-n': 'Ejercicio {n}',
  'barra3.prova-passo': 'Paso al siguiente',
  'barra3.consegno': 'Entrego',
  'barra3.lascio-perdere': 'Lo dejo',
  'barra3.prova-nota-tempo': 'El tiempo corre en la píldora. «Paso al siguiente» es opcional: apunta cuánto tiempo pasas en cada ejercicio.',
  'barra3.prova-lascio-chiede': '¿Lo dejas? No apunto nada: ni los ejercicios ni el examen.',
  'barra3.si-lascio': 'Sí, lo dejo',
  'barra3.no-continuo': 'No, sigo',
  'barra3.prova-lasciata': 'Dejado: no he apuntado nada. Cuando quieras repetirlo, escribe «simulacro de examen de {nome}».',
  'barra3.prova-consegnato': 'Entregado. Coge la hoja y, para cada ejercicio, dime tú cómo te fue.',
  'barra3.prova-come-andato': 'Cómo te fue el ejercicio {n}',
  'barra3.prova-esito-tuo': 'Lode no corrige: el resultado lo eliges tú.',
  'barra3.prova-sintesi-esito': 'simulacro de examen de {nome}: {fatti} de {n}',
  'barra3.prova-sintesi-come': 'simulacro de examen de {nome}: cómo fue',

  // temario
  'barra3.aggiungi-esame-programma': 'Primero añade un examen, por ejemplo: «examen cálculo 2 el 15 de enero 9 créditos». Después pega su temario.',
  'barra3.programma-titolo': 'Temario · {nome}',
  'barra3.programma-vuoto': 'Pega el temario de la asignatura (de la página del curso o del PDF), o arrastra aquí el archivo. Lo divido en temas, te enseño lo que ya sabes y te preparo el plan hasta el examen.',
  'barra3.programma-segnaposto': '1. Límites y continuidad&#10;2. Derivadas: definición, reglas, teoremas de Rolle y Lagrange&#10;…',
  'barra3.programma-del-corso': 'Temario de la asignatura',
  'barra3.programma-leggi': 'Leer el temario',
  'barra3.programma-di': 'Temario de {nome}',
  'barra3.programma-da-moodle': 'Tráelo de Moodle',
  'barra3.programma-moodle-vuota': 'En Moodle la descripción está vacía',
  'barra3.programma-di-moodle': 'Temario de {nome} desde Moodle',
  'barra3.programma-sintesi': 'temario de {nome}',
  'barra3.programma-leggo': 'Leyendo el temario…',
  'barra3.programma-niente': 'No consigo sacar los temas de este texto. Pégalos uno por línea, mejor numerados.',
  'barra3.programma-salvo': { one: '{n} tema para {nome}: ¿lo guardo?', other: '{n} temas para {nome}: ¿los guardo?' },
  'barra3.programma-letti-da': 'Los ha leído {motore}: comprueba que estén todos.',
  'barra3.programma-se-non-torna': 'Si algo no cuadra, vuelve a pegar el temario corregido.',
  'barra3.programma-stesso-nome': 'Los temas con el mismo nombre conservan preguntas y resultados.',
  'barra3.programma-cuscinetto': 'Hoy es el día de reserva: ponte al día con lo que se ha quedado atrás, o descansa.',
  'barra3.programma-ultimo': 'Último día: repaso general. Las preguntas de examen y los puntos débiles: {cosa}.',
  'barra3.tutto-il-programma': 'todo el temario',
  'barra3.studia': 'Estudiar',
  'barra3.ripassa': 'Repasar',
  'barra3.cuscinetto': 'reserva',
  'barra3.ripasso-generale': 'repaso general',
  'barra3.percento-pronto': '{p}% listo',
  'barra3.oggi': 'Hoy',
  'barra3.esercizio-di-oggi': 'Ejercicio de hoy',
  'barra3.fallo-adesso': 'Hazlo ahora',
  'barra3.interrogami-questi': 'Pregúntame sobre estos',
  'barra3.focus': 'Focus',
  'barra3.da-rivedere-piccolo': 'para revisar',
  'barra3.uscita-volte': { one: 'salió {n} vez', other: 'salió {n} veces' },
  'barra3.fatto-oggi': 'hecho hoy',
  'barra3.lo-spiego-io': 'Lo explico yo',
  'barra3.interrogami': 'Pregúntame',
  'barra3.prossimi-giorni': 'Los próximos días',
  'barra3.senza-data-appello': '(sin fecha de examen: plan de dos semanas)',
  'barra3.domande-appelli': 'Preguntas de exámenes pasados',
  'barra3.n-senza-argomento': { one: '{n} sin tema', other: '{n} sin tema' },
  'barra3.domande-segnaposto': 'Una por línea: las que circulan en el grupo de clase',
  'barra3.domande-uscite': 'Preguntas de examen',
  'barra3.aggiungi': 'Añadir',
  'barra3.domande-senza-argomento': 'No sé de qué tema son: {lista}',
  'barra3.programma-nota': 'El plan se rehace cada día según lo que sabes: apuntes, tarjetas, repaso y orales. Primero los temas débiles y los que más salen; cada tema nuevo vuelve a los pocos días.',
  'barra3.interrogami-oggi': 'Pregúntame sobre los temas de hoy',
  'barra3.interrogami-su': 'Pregúntame sobre {x}',
  'barra3.te-lo-spiego-su': 'Te lo explico yo: {x}',
  'barra3.programma-sintesi-pronto': 'temario de {nome}: {p}% listo',
  'barra3.domande-nessuna': 'No he encontrado preguntas: escribe una por línea.',
  'barra3.domande-salvate': { one: '{n} pregunta guardada.', other: '{n} preguntas guardadas.' },
  'barra3.domande-incolla-programma': 'Pega también el temario: las pongo bajo sus temas.',
  'barra3.domande-aggiunte': { one: '{n} pregunta añadida.', other: '{n} preguntas añadidas.' },
  'barra3.domande-senza': { one: '{n} sin tema: no entiendo de cuál habla.', other: '{n} sin tema: no entiendo de cuál hablan.' },
  'barra3.domande-salgono': 'Los temas que más salen suben en el plan.',
  'barra3.domande-uscite-sintesi': 'preguntas de examen',

  // te lo explico yo y el oral sobre el temario
  'barra3.spiego-titolo': 'Te lo explico yo · {nome}',
  'barra3.spiego-istruzioni': 'Explícalo como si estuvieras en el oral, con tus palabras: escribe aquí debajo o mantén pulsado {tasti} y habla. Cuando termines, envía.',
  'barra3.spiego-risponde': 'Te responde {motore}, usando tus apuntes.',
  'barra3.spiego-controllo': { one: 'Compruebo {n} punto sacado del temario y de tus apuntes: no te lo enseño antes.', other: 'Compruebo {n} puntos sacados del temario y de tus apuntes: no te los enseño antes.' },
  'barra3.spiego-senza-appunti': 'Para este tema no tengo apuntes: sin IA solo puedo apuntar que lo has repasado.',
  'barra3.spiego-esci': 'Escribe «salir» para dejarlo.',
  'barra3.spiego-segnaposto': 'Tu explicación…',
  'barra3.spiego-sintesi': 'explico {x}',
  'barra3.chiedi-o-scrivi': 'Pregunta o escribe un comando…',
  'barra3.spiego-ascolto': 'Escuchando la explicación…',
  'barra3.mancava': 'Faltaba: {cosa}',
  'barra3.spiego-errore': 'Ahora no puedo valorarla: {errore}',
  'barra3.spiego-segnato': 'Apuntado: has repasado {x}.',
  'barra3.spiego-controllo-vero': 'Para una comprobación de verdad hacen falta apuntes de este tema, o la IA.',
  'barra3.punti-su': '{x} puntos de {n}',
  'barra3.spiego-parole-chiave': 'Compruebo las palabras clave, no el razonamiento: si un punto lo has dicho con otras palabras, vale igual.',
  'barra3.spiego-sicuro': 'Tema marcado como dominado.',
  'barra3.spiego-cerchio-vuoto': 'Los del círculo vacío: reléelos y vuelve a intentarlo en un par de días.',
  'barra3.orale-niente': 'Hoy en el plan no hay nada que preguntar.',
  'barra3.orale-contesto': 'Oral · <b>{nome}</b> · {cosa}',
  'barra3.n-argomenti': { one: '{n} tema', other: '{n} temas' },
  'barra3.esci': 'Salir',
  'barra3.orale-sintesi': 'oral de {nome} sobre el temario',

  // enviar, archivos, voz
  'barra3.crea-carte-da-file': 'Crea las tarjetas de repaso con este archivo.',
  'barra3.niente-spiegazione': 'Vale, sin explicación.',
  'barra3.non-so-senza-ai': 'Esto todavía no sé hacerlo sin IA. Esto es lo que entiendo:',
  'barra3.foto': 'foto',
  'barra3.togli-file': 'Quitar {nome}',
  'barra3.allegati-con-ai': 'Intro: hago tarjetas. O pide otra cosa…',
  'barra3.allegati-senza-ai': 'Intro: importo las tarjetas (CSV, TSV, texto)',
  'barra3.importa-solo-testo': 'Sin IA solo leo archivos de texto con una tarjeta por línea (pregunta, luego Tab o «;» o « = », luego respuesta), como la exportación de Anki. Para PDF y fotos necesitas el cerebro local o tu IA (escribe «IA»).',
  'barra3.importa-carte': { one: '¿Importar {n} tarjeta?', other: '¿Importar {n} tarjetas?' },
  'barra3.e-altre': { one: 'y {n} más', other: 'y {n} más' },
  'barra3.importa-in': 'Las pongo en {nome}: lo cambias desde la página.',
  'barra3.carte-importate': { one: '{n} tarjeta importada.', other: '{n} tarjetas importadas.' },
  'barra3.ripassa-ora': 'Repasar ahora',
  'barra3.ti-ascolto': 'Te escucho',
  'barra3.ti-ascolto-preparo': 'Te escucho · preparando la voz…',
  'barra3.ti-ascolto-preparo-p': 'Te escucho · preparando la voz {p}%',
  'barra3.voce-pronta': '{voce} en local · mantén pulsado {tasti} y habla',
  'barra3.scarico-voce': 'Descargando {voce} · {p}%',
  'barra3.voce-ripiego': 'Parakeet no arranca: preparo Whisper',
  'barra3.preparo-voce': 'Preparando la voz',

  // conexiones, atajos y avisos
  'barra3.piu-tardi': 'Vale, más tarde',
  'barra3.trascrivi-lezione': 'Transcribe la clase',
  'barra3.fine-trascrizione': 'Fin de la transcripción',
  'barra3.ripeti': 'Repite',
  'barra3.spegni-ripeti': 'Apaga Repite',
  'barra3.accendi-ripeti': 'Enciende Repite',
  'barra3.gioca': 'Jugar',
  'barra3.pausa': 'Pausa',
  'barra3.focus-fatto': { one: '{n} minuto hecho · descanso', other: '{n} minutos hechos · descanso' },
  'barra3.tempo-scaduto-consegna': 'Se acabó el tiempo · entrega',
  'barra3.pausa-finita': 'Descanso terminado · ¿seguimos?',
  'barra3.ripeti-spento': 'Repite apagado después de 3 horas',
  'barra3.lode-pronta': 'Lode {versione} está listo',
  'barra3.lode-uscita': 'Ha salido Lode {versione}',
  'barra3.sync-in-pausa': 'Sincronización en pausa · escribe la contraseña',
  'barra3.cervello-locale': 'Cerebro local',
  'barra3.ripassa-esame': 'Repasar {nome}',
  'barra3.ripasso': 'Repaso',
  'barra3.libretto': 'Notas',
};
