// Textos de la barra, segunda parte (español): archivos que se sueltan en la barra, propuestas del entrenador, tu IA,
// «Prepara Lode» y actualizaciones, sincronización, notas, cierre de la clase, juegos, comandos locales, errores
// explicados y diario, herramientas de la IA, oral, agentes de programación (js/lode.js).
export default {
  'barra2.file-non-so-usare': 'Esto no sé usarlo: {motivo}.',
  'barra2.peso-kb': '{n} KB',
  'barra2.peso-mb': '{n} MB',
  'barra2.cosa-ne-faccio': '¿Qué hago con esto?',
  'barra2.per': 'Para',
  'barra2.corso': 'Asignatura',
  'barra2.data-lezione': 'Fecha de la clase',
  'barra2.non-andata': 'No ha salido bien: {errore}',
  'barra2.sintesi-cosa-ne-faccio': '{nome}: ¿qué hago con esto?',
  'barra2.allegato-lezione': 'Adjuntado a la clase de {corso}.',
  'barra2.apri': 'Abrir',
  'barra2.sbobina-nel-vault': 'Transcripción de {corso} en tu vault.',
  'barra2.sbobina-nota-da': '{data} · de {da}',
  'barra2.sbobina-ricevuta': 'transcripción recibida',
  'barra2.nessuna-riga-carte': 'No he encontrado líneas «pregunta, respuesta» en este archivo.',
  'barra2.apro-registrazione': 'Abriendo la grabación…',
  'barra2.leggo-foto': 'Leyendo la foto…',
  'barra2.lavagna-titolo': '¿Ponerlo en los apuntes de {corso}?',
  'barra2.lavagna-nota': 'Junto con la foto, en la nota de la clase de hoy. Revísala: la ha transcrito {motore}.',
  'barra2.lavagna-fatta': 'Pizarra en los apuntes.',
  'barra2.leggo-file': 'Leyendo {nome}…',
  'barra2.file-senza-testo': 'No puedo leer el texto de este archivo.',
  'barra2.file-senza-testo-incolla': 'No puedo leer el texto de este archivo: pégalo en el campo.',
  'barra2.prima-esame': 'Primero añade el examen, por ejemplo: «examen cálculo 2 el 15 de enero 9 créditos».',
  'barra2.scrivo-carte': 'Escribiendo las tarjetas…',
  'barra2.file-senza-carte': 'De este archivo no he sacado tarjetas.',
  'barra2.riassumo': 'Resumiendo {nome}… {p}%',
  'barra2.riassunto-titolo': '¿Guardar el resumen en Obsidian?',
  'barra2.riassunto-nota': 'Nota nueva en {cartella}, con el archivo original adjunto.',
  'barra2.riassunto-salvato': 'Resumen guardado.',
  'barra2.stelle-titolo': '★ De examen · {esame}',
  'barra2.ora-un-gioco': 'Ahora un juego',
  'barra2.gioca': 'Jugar',
  'barra2.la-tua-ai': 'Tu IA',
  'barra2.ai-locale-attivo': 'Ahora Lode usa el <b>cerebro local</b>: gratis, sin conexión, los apuntes se quedan aquí.',
  'barra2.ai-locale-da-installare': 'El <b>cerebro local</b> gratis se instala desde «Prepara Lode».',
  'barra2.ai-chiave-spiegazione': 'Si quieres una IA más potente, conecta tu clave: pagas directamente al servicio, por uso (normalmente unos céntimos por sesión). Lode no ve ni cobra nada; la clave se queda en este ordenador.',
  'barra2.ai-nome-collegata': '{nome} · conectada',
  'barra2.chiave-api': 'Clave de API',
  'barra2.collega': 'Conectar',
  'barra2.modello': 'Modelo',
  'barra2.ai-solo-spiegazioni': 'Apuntes y clases se quedan en el ordenador: tu IA solo para explicaciones y oral',
  'barra2.usa-solo-locale': 'Usar solo el cerebro local',
  'barra2.chiave-di': 'Clave de {nome}',
  'barra2.incolla-chiave': 'pega la clave',
  'barra2.si-crea-su': 'Se crea en <b>{sito}</b>.',
  'barra2.provo-chiave': 'Probando la clave…',
  'barra2.ai-collegata': '{nome} conectada.',
  'barra2.ai-modello': 'Modelo {modello}.',
  'barra2.ai-appunti-restano': 'Los apuntes se quedan en el ordenador.',
  'barra2.ai-usano-tua': 'Explicaciones, oral, tarjetas y pasar a limpio usan tu IA.',
  'barra2.sintesi-ai-collegata': 'IA conectada',
  'barra2.chiave-non-valida': 'La clave no es válida.',
  'barra2.servizio-irraggiungibile': 'No consigo llegar al servicio: ¿tienes conexión?',
  'barra2.solo-locale-fatto': 'Lode usa solo el cerebro local.',
  'barra2.ai-scollegata-sito': 'He borrado la clave de este ordenador. En tu cuenta de {nome} sigue valiendo: si ya no la necesitas, revócala también allí ({sito}).',
  'barra2.ai-scollegata-nome': 'He borrado la clave de este ordenador. En tu cuenta de {nome} sigue valiendo: si ya no la necesitas, revócala también allí.',
  'barra2.ai-scollegata': 'He borrado la clave de este ordenador. En tu cuenta sigue valiendo: si ya no la necesitas, revócala también allí.',
  'barra2.sintesi-la-tua-ai': 'tu IA',
  'barra2.agg-pronta': 'Lode {versione} está listo',
  'barra2.agg-si-installa': 'Se instala solo cuando cierras Lode',
  'barra2.riavvia-ora': 'Reiniciar ahora',
  'barra2.agg-uscita': 'Ha salido Lode {versione}',
  'barra2.agg-scarica-dmg': 'Descarga el .dmg y arrastra Lode a Aplicaciones',
  'barra2.agg-scarica-github': 'Descarga la versión nueva desde GitHub',
  'barra2.scarica': 'Descargar',
  'barra2.agg-spenti': 'Lode {versione} · apagadas: las versiones nuevas están en GitHub, en la página Releases',
  'barra2.agg-scarico': 'Descargando Lode {versione} · {p}%',
  'barra2.agg-pronta-riga': 'Lode {versione} está listo · se instala solo cuando cierras Lode',
  'barra2.agg-uscita-mac': 'Ha salido Lode {versione} · descarga el .dmg y arrastra Lode a Aplicaciones',
  'barra2.agg-uscita-github': 'Ha salido Lode {versione} · descárgalo desde GitHub',
  'barra2.agg-manuale': 'Lode {versione} · te aviso cuando salga una nueva (desde GitHub, cada 6 horas)',
  'barra2.agg-automatici': 'Lode {versione} · se actualiza solo desde GitHub, lo comprueba cada 6 horas',
  'barra2.spegni': 'Apagar',
  'barra2.accendi': 'Encender',
  'barra2.prep-solo-app': 'Obsidian y el cerebro local se instalan desde la **app de escritorio** de Lode.',
  'barra2.prepara-lode': 'Prepara Lode',
  'barra2.il-tuo-vault': 'Tu vault',
  'barra2.prep-vault-dett': '{percorso} · Home, asignaturas, clases, glosario',
  'barra2.obs-installato': 'Instalado y conectado al vault',
  'barra2.obs-da-installare': 'Gratis para uso personal · instalador oficial desde GitHub, unos 230 MB',
  'barra2.installa': 'Instalar',
  'barra2.cervello-locale': 'Cerebro local',
  'barra2.cervello-pronto-dett': '{modello} · funciona en el ordenador, sin internet',
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · unos {gb} GB',
  'barra2.pronto': 'listo',
  'barra2.voce': 'Voz',
  'barra2.voce-pronta-dett': '{voce} en local · mantén pulsado {tasti} y habla',
  'barra2.voce-da-preparare': '{descrizione}, en local, en español · unos {peso} MB, una sola vez',
  'barra2.pronta': 'lista',
  'barra2.prepara': 'Preparar',
  'barra2.facoltativa': 'opcional',
  'barra2.tua-ai-collegata-dett': '{nome} conectada · pagas tú por uso, directamente al servicio',
  'barra2.tua-ai-da-collegare': 'Claude, ChatGPT, Gemini, Mistral…: más potente, por uso con tu clave',
  'barra2.cambia': 'Cambiar',
  'barra2.sincronizza-computer': 'Sincroniza entre tus ordenadores',
  'barra2.sperimentale': 'experimental',
  'barra2.sblocca': 'Desbloquear',
  'barra2.gestisci': 'Gestionar',
  'barra2.attiva': 'Activar',
  'barra2.uso-gia-altrove': 'Ya uso Lode en otro ordenador',
  'barra2.collega-dett': 'Conecta este ordenador al vault que ya tienes en la carpeta en la nube',
  'barra2.aggiornamenti': 'Actualizaciones',
  'barra2.prep-nota': 'El cerebro local es gratis y funciona sin conexión: saca definiciones, crea tarjetas, explica y te pregunta. Tu IA es un extra opcional: Lode no ve ni cobra nada.',
  'barra2.detto-mia-ai': 'Mi IA',
  'barra2.detto-sincronizza': 'Sincroniza entre ordenadores',
  'barra2.scarico-voce': 'Descargando {voce}…',
  'barra2.sintesi-prepara': 'prepara Lode',
  'barra2.installare-obsidian': '¿Instalar Obsidian?',
  'barra2.da': 'Desde',
  'barra2.github-obsidian': 'github.com/obsidianmd (oficial)',
  'barra2.peso': 'Tamaño',
  'barra2.circa-230-mb': 'unos 230 MB',
  'barra2.dove': 'Dónde',
  'barra2.applicazioni': 'Aplicaciones',
  'barra2.il-tuo-utente': 'tu usuario',
  'barra2.obs-nota': 'Obsidian es gratis para uso personal. Se abre ya en tu vault, en la Home.',
  'barra2.installare-nome': '¿Instalar {nome}?',
  'barra2.installare-cervello': '¿Instalar el cerebro local?',
  'barra2.cosa': 'Qué',
  'barra2.ollama-motore': 'Ollama (motor) + {nome}',
  'barra2.circa-gb': 'unos {gb} GB',
  'barra2.perche': 'Por qué',
  'barra2.cervello-nota': 'Se descarga una sola vez. Después funciona sin internet y sin claves.',
  'barra2.solo-clic': 'Solo se confirma con un clic.',
  'barra2.avviato': 'En marcha.',
  'barra2.continuo-da-solo': 'Puedes cerrar el panel: sigo yo solo.',
  'barra2.obsidian-pronto': 'Obsidian está listo',
  'barra2.cervello-pronto': 'Cerebro local listo',
  'barra2.sync-piede-cifrati': 'Cifrados, sincronizados con {servizio}',
  'barra2.sync-piede': 'Sincronizados con {servizio}',
  'barra2.la-tua-cartella-cloud': 'tu carpeta en la nube',
  'barra2.dati-restano-qui': 'Los datos se quedan en este ordenador',
  'barra2.portachiavi-mac': 'La contraseña se recuerda en este ordenador (en el Llavero).',
  'barra2.portachiavi-windows': 'La contraseña se recuerda en este ordenador (protegida por tu cuenta de Windows).',
  'barra2.portachiavi-sistema': 'La contraseña se recuerda en este ordenador (en el llavero del sistema).',
  'barra2.senza-portachiavi': 'Este ordenador no tiene un llavero seguro: Lode te pedirá la contraseña cada vez que arranque.',
  'barra2.sync-solo-app': 'La sincronización entre ordenadores está en la **app de escritorio** de Lode.',
  'barra2.sync-stato-illeggibile': 'No puedo leer el estado de la sincronización.',
  'barra2.sync-altro-computer': 'En el otro ordenador abre Lode y elige «Ya uso Lode en otro ordenador», luego el vault «{vault}» en {servizio}.',
  'barra2.la-cartella-cloud': 'la carpeta en la nube',
  'barra2.sync-non-accesa': 'La sincronización no está activada: los datos de Lode se quedan en este ordenador.',
  'barra2.sync-titolo-altro': 'Ya uso Lode en otro ordenador · experimental',
  'barra2.sync-titolo': 'Sincroniza entre tus ordenadores · experimental',
  'barra2.sync-sperimentale': '<b>Experimental.</b> {testo}',
  'barra2.sync-cartella-cloud': 'Uso la carpeta en la nube que ya tienes: sin cuenta, sin servidor de Lode. Copio el vault allí y paso a la copia; la carpeta de antes se queda donde está. {prima}',
  'barra2.sync-interrotto': '<b>El traslado a {servizio} se interrumpió.</b> El vault de antes está intacto: elige otra vez la carpeta y sigo desde donde lo dejé.',
  'barra2.cartella-cloud': 'carpeta en la nube',
  'barra2.sync-interrotto-pw': 'Había empezado con la contraseña: te pediré que la escribas otra vez.',
  'barra2.vault-gia-qui': 'el vault ya está aquí: nada que mover',
  'barra2.altra-cartella': 'Otra carpeta…',
  'barra2.altra-cartella-dett': 'Syncthing, una carpeta de red',
  'barra2.nessuna-cartella-cloud': 'No encuentro iCloud Drive, OneDrive, Dropbox ni Google Drive en este ordenador: elige tú la carpeta que se sincroniza.',
  'barra2.scegli-vault-cloud': 'Elige el vault en la carpeta en la nube',
  'barra2.gia-sincronizzato': '{servizio} · ya sincronizado',
  'barra2.scegli-vault': 'Elegir el vault…',
  'barra2.scegli-vault-dett': 'la carpeta «Lode» en tu carpeta en la nube',
  'barra2.vault-resta': 'El vault que hay ahora en este ordenador se queda donde está, intacto.',
  'barra2.vault-resta-altro': 'Si Lode ya tiene aquí exámenes, notas o tarjetas, los llevo al grupo como «Datos de otro primer inicio»: los importas tú, nada sustituye los datos de los otros ordenadores.',
  'barra2.la-cartella-che-scegli': 'la carpeta que elijas',
  'barra2.sintesi-uso-gia-altrove': 'ya uso Lode en otro sitio',
  'barra2.sintesi-sincronizza': 'sincroniza',
  'barra2.sincronizzare-con': '¿Sincronizar con {servizio}?',
  'barra2.vault': 'Vault',
  'barra2.vault-resta-cloud': 'se queda donde está: ya está en la carpeta en la nube',
  'barra2.cartella-lode-in': 'una carpeta «Lode» en {servizio}',
  'barra2.prima': 'Antes',
  'barra2.dati-json-cronologia': 'el dati.json de antes queda en el historial del servicio',
  'barra2.vault-adesso-resta': 'el vault de ahora se queda donde está, intacto',
  'barra2.dati-di-lode': 'Datos de Lode',
  'barra2.un-diario-per-computer': 'un diario por ordenador: sin conflictos, no se pierde nada',
  'barra2.proteggi-con-password': 'Protege los datos de Lode con una contraseña',
  'barra2.password-almeno-8': 'Contraseña (al menos 8 caracteres)',
  'barra2.password': 'Contraseña',
  'barra2.ripetila': 'Repítela',
  'barra2.ripeti-password': 'Repite la contraseña',
  'barra2.cifrati-in-chiaro-anche': '<b>Cifrados:</b> {cifrati}. <b>En claro en la carpeta en la nube</b>, también con la contraseña:',
  'barra2.sync-nota-password': 'La contraseña también se puede añadir después («Proteger con una contraseña») o cambiar («Cambiar contraseña»). En los otros ordenadores: «Ya uso Lode en otro ordenador». {prima}',
  'barra2.spostamento-con-password': 'El traslado había empezado con la contraseña: escríbela otra vez.',
  'barra2.almeno-8': 'Al menos 8 caracteres.',
  'barra2.password-diverse': 'Las dos contraseñas no coinciden.',
  'barra2.preparo': 'Preparando…',
  'barra2.sincronizzato-con': 'Sincronizado con {servizio}.',
  'barra2.vault-era-gia-cloud': 'El vault ya estaba en la carpeta en la nube: desde ahora cada ordenador escribe solo su diario.',
  'barra2.cartella-prima-resta': 'La carpeta de antes («{da}») se queda donde estaba: bórrala tú cuando quieras. En los otros ordenadores: «Ya uso Lode en otro ordenador».',
  'barra2.vault-gia-in-servizio': 'En {servizio} ya hay un vault de Lode sincronizado.',
  'barra2.usa-uso-gia': 'Usa «Ya uso Lode en otro ordenador» para conectarte a ese.',
  'barra2.annullato': 'Cancelado.',
  'barra2.niente-cambiato': 'No he cambiado nada.',
  'barra2.scrivi-password': 'Escribe la contraseña.',
  'barra2.non-ancora': 'Todavía no.',
  'barra2.non-andata-vault-intatto': 'No ha salido bien: {errore}. El vault de antes está intacto.',
  'barra2.collegato-vault-in': 'Conectado al vault en {servizio}.',
  'barra2.dati-protetti-password': 'Los datos de Lode están protegidos con una contraseña: escríbela para recibirlos.',
  'barra2.ricevo-dati': 'Recibiendo los datos de los otros ordenadores: llegan solos. Ya puedes usar Lode.',
  'barra2.dati-importati-altrove': 'Los datos que tenías en este ordenador ({n} registros) están en «Datos de otro primer inicio», en la ficha «Sincroniza»: impórtalos desde allí. El archivo de antes se queda en el vault «{vault}».',
  'barra2.cartella-inusabile': 'No puedo usar esa carpeta.',
  'barra2.diario-illeggibile': 'No se puede leer el diario de Lode en este ordenador',
  'barra2.diario-illeggibile-nota': 'No se ha borrado nada: la carpeta de datos de Lode no responde (¿disco lleno o averiado?). Los cambios de ahora van a un archivo aparte.',
  'barra2.riprova': 'Reintentar',
  'barra2.vault-sparito': 'Los datos de Lode de este ordenador están a salvo en su diario. Si has movido el vault, elige la carpeta donde lo pusiste.',
  'barra2.trova-vault': 'Buscar el vault',
  'barra2.lode-vecchia-campi': { one: '<b>De un Lode antiguo:</b> {n} campo distinto de los de ahora. No cambia nada solo: la copia del archivo está en la carpeta de datos de Lode (sync/copie).', other: '<b>De un Lode antiguo:</b> {n} campos distintos de los de ahora. No cambian nada solos: la copia del archivo está en la carpeta de datos de Lode (sync/copie).' },
  'barra2.aggiunte': { one: '<b>Datos de otro primer inicio o de un Lode antiguo:</b> {n} registro (exámenes, tarjetas, sesiones…) que el diario no tiene. No entra solo.', other: '<b>Datos de otro primer inicio o de un Lode antiguo:</b> {n} registros (exámenes, tarjetas, sesiones…) que el diario no tiene. No entran solos.' },
  'barra2.importa-aggiunte': 'Importar lo añadido',
  'barra2.password-dati-lode': 'Contraseña de los datos de Lode',
  'barra2.intanto-funziona': 'Mientras tanto Lode funciona con los datos de este ordenador: los cambios esperan en el diario. {portachiavi}',
  'barra2.ho-dimenticato-password': 'He olvidado la contraseña',
  'barra2.dimentica-password-qui': 'Olvidar la contraseña aquí',
  'barra2.cifrati-in-chiaro': '<b>Cifrados:</b> {cifrati}. <b>En claro en la carpeta en la nube:</b>',
  'barra2.cambia-password': 'Cambiar contraseña',
  'barra2.senza-password': 'Sin contraseña: quien pueda leer tu carpeta en la nube también puede leer los datos de Lode, como ya pasa con los apuntes.',
  'barra2.proteggi-password': 'Proteger con una contraseña',
  'barra2.recuperi': 'Los cambios que el diario no pudo recoger están en {n} archivos «recupero-…json» (el último: «{file}»), en la carpeta de datos de Lode: no los he tirado.',
  'barra2.recupero': 'Los cambios que el diario no pudo recoger están en el archivo «{file}», en la carpeta de datos de Lode: no los he tirado.',
  'barra2.smetti-qui': 'Dejar de sincronizar en este ordenador',
  'barra2.importati-record': { one: '{n} registro importado.', other: '{n} registros importados.' },
  'barra2.ora-su-tutti': 'Ahora están en todos los ordenadores.',
  'barra2.non-andata-punto': 'No ha salido bien.',
  'barra2.controllo': 'Comprobando…',
  'barra2.sbloccata': 'Desbloqueada.',
  'barra2.password-ricordata': 'La contraseña se recuerda en este ordenador.',
  'barra2.chiedero-prossimo-avvio': 'Te la pediré la próxima vez que arranque.',
  'barra2.password-nuova-almeno-8': 'Contraseña nueva (al menos 8 caracteres)',
  'barra2.password-nuova': 'Contraseña nueva',
  'barra2.password-nuova-pronta': 'Contraseña nueva lista.',
  'barra2.altri-chiederanno': 'Los otros ordenadores te la pedirán una vez.',
  'barra2.cambiare-password': '¿Cambiar la contraseña?',
  'barra2.rifa-password-nuova': 'Lode rehace los datos de Lode en la carpeta en la nube con la contraseña nueva. {testo}',
  'barra2.scegliere-password-nuova': '¿Elegir una contraseña nueva?',
  'barra2.proteggere-password': '¿Proteger los datos de Lode con una contraseña?',
  'barra2.rifa-cifrati': 'Lode rehace los datos de Lode en la carpeta en la nube, cifrados con la contraseña. Los otros ordenadores te la pedirán. {testo}',
  'barra2.password-dimenticata': 'Contraseña olvidada en este ordenador.',
  'barra2.chiedero-di-nuovo': 'Te la pediré otra vez.',
  'barra2.smettere-qui': '¿Dejar de sincronizar en este ordenador?',
  'barra2.vault-copiato-fuori': 'copiado en una carpeta fuera de la carpeta en la nube, que eliges tú',
  'barra2.tutti-dati': 'todos, también los de los otros ordenadores hasta hoy',
  'barra2.gli-altri-computer': 'Los otros ordenadores',
  'barra2.continuano-sincronizzarsi': 'siguen sincronizándose entre ellos',
  'barra2.smesso-qui': 'Sincronización detenida en este ordenador.',
  'barra2.smesso-nota': 'El vault ahora está fuera de la carpeta en la nube. Para dejarlo en todos, hazlo en cada ordenador.',
  'barra2.sintesi-smessa': 'sincronización detenida aquí',
  'barra2.ultima-lezione': 'Última clase',
  'barra2.lezione-di': 'Clase de {corso}',
  'barra2.cosa-sa-lode': 'Lo que Lode sabe de mí',
  'barra2.vai-a-note': { one: 'Ir a… · {n} nota', other: 'Ir a… · {n} notas' },
  'barra2.radice-vault': 'vault',
  'barra2.oggi': 'hoy',
  'barra2.cerca-nota-segnaposto': 'Busca una nota: asignatura, clase, fecha…',
  'barra2.cerca-nota': 'Buscar una nota',
  'barra2.nessuna-nota': 'No he encontrado ninguna nota.',
  'barra2.sintesi-cerco': 'busco «{q}»',
  'barra2.sintesi-note': 'notas',
  'barra2.niente-appunti-di': 'No encuentro apuntes de **{corso}** de los últimos días.',
  'barra2.niente-appunti': 'No encuentro ninguna clase con suficientes apuntes: escríbelos en la sección «{sezione}» de la nota.',
  'barra2.appunti-serve-ai': 'Para leer los apuntes hace falta la IA: instala el **cerebro local** (gratis, funciona sin conexión) desde «Prepara Lode», o conecta tu IA: escribe «IA».',
  'barra2.leggo-appunti-di': 'Leyendo los apuntes de {corso}…',
  'barra2.appunti-illeggibili': 'No he podido leer los apuntes: {errore}',
  'barra2.nessuna-definizione-nuova': 'En los apuntes no he encontrado definiciones nuevas. Intenta escribirlas completas, aunque sean cortas.',
  'barra2.aggiungere-a': '¿Añadir a {corso} · {data}?',
  'barra2.chiudi-nota': { one: '{n} definición en la nota de la clase. Comprueba que esté bien: la ha escrito {motore}.', other: '{n} definiciones en la nota de la clase. Comprueba que estén bien: las ha escrito {motore}.' },
  'barra2.chiudi-nota-stelle': { one: '{n} definición y {stelle} ★ en la nota de la clase. Comprueba que estén bien: las ha escrito {motore}.', other: '{n} definiciones y {stelle} ★ en la nota de la clase. Comprueba que estén bien: las ha escrito {motore}.' },
  'barra2.lezione-chiusa': 'Clase cerrada.',
  'barra2.definizioni-pronte': { one: '{n} definición lista para los juegos.', other: '{n} definiciones listas para los juegos.' },
  'barra2.sintesi-definizioni': { one: '{n} definición', other: '{n} definiciones' },
  'barra2.appunti-sparsi-oggi': 'los apuntes sueltos de hoy',
  'barra2.la-nota-di': 'la nota de {corso}',
  'barra2.apro-in-obsidian': 'Abro {nome} en Obsidian.',
  'barra2.apro-se-non-trova': 'Abro {nome}. Si Obsidian no encuentra el vault, la primera vez haz **Abrir carpeta como vault** y elige la carpeta «{percorso}»: después se queda conectado.',
  'barra2.aperto-editor': 'He abierto {nome} con el editor del sistema. Con **Obsidian** (gratis, obsidian.md) el vault «{percorso}» ya está listo: carpetas, plantillas, horario y tu memoria.',
  'barra2.nota-non-si-apre': 'No puedo abrir la nota: {errore}',
  'barra2.appunti-solo-app': 'Los apuntes en Obsidian están en la **app de escritorio** de Lode: allí cada clase se convierte en una nota de tu vault, con las ★ y las definiciones que marcas desde la barra.',
  'barra2.gioco-sai-gia-di': 'Las definiciones de {corso} de hoy ya te las sabes: vuelven cuando estés a punto de olvidarlas.',
  'barra2.gioco-sai-gia': 'Las definiciones de hoy ya te las sabes: vuelven cuando estés a punto de olvidarlas.',
  'barra2.gioco-nessuna-di': 'Todavía no hay definiciones de {corso}. En clase pulsa **Definición** (o escribe «def: término = definición»), o escríbelas en Obsidian en la sección «{sezione}» de la clase.',
  'barra2.gioco-nessuna': 'Todavía no hay definiciones. En clase pulsa **Definición** (o escribe «def: término = definición»), o escríbelas en Obsidian en la sección «{sezione}» de la clase.',
  'barra2.gioco-di': 'Juego · {corso}',
  'barra2.ultime-lezioni': 'últimas clases',
  'barra2.manche-di': '{i} de {n}',
  'barra2.abbina': 'Une cada término con su definición.',
  'barra2.chi-sono': '¿Quién soy?',
  'barra2.completa': '{termine}: completa la definición.',
  'barra2.parola-mancante': 'Palabra que falta',
  'barra2.controlla-invio': 'Comprobar <kbd>Intro</kbd>',
  'barra2.non-la-so': 'No me la sé',
  'barra2.te-la-ricordi': '¿Te acuerdas?',
  'barra2.mostra-spazio': 'Mostrar <kbd>Espacio</kbd>',
  'barra2.non-la-sapevo': 'No me la sabía <kbd>1</kbd>',
  'barra2.la-sapevo': 'Me la sabía <kbd>2</kbd>',
  'barra2.tutte-giuste': 'Todas bien. Estas se quedan.',
  'barra2.da-rinforzare': 'Por reforzar: {elenco}. Vuelven mañana.',
  'barra2.secondi': { one: '{n} segundo', other: '{n} segundos' },
  'barra2.minuti': '{n} min',
  'barra2.sintesi-punti': '{punti} de {tot}',
  'barra2.ancora-una': 'Otra más',
  'barra2.gioca-ancora': 'Jugar otra vez',
  'barra2.sintesi-gioco': 'juego',
  'barra2.pausa-finita': 'Descanso terminado.',
  'barra2.fermato-dopo': 'Parado después de {tempo}.',
  'barra2.prova-resta-aperta': 'El simulacro sigue abierto: escribe «simulacro de examen» para entregarlo.',
  'barra2.li-conto': 'Los cuento en las horas de estudio.',
  'barra2.sintesi-timer-fermato': 'temporizador parado',
  'barra2.nessun-timer': 'No hay ningún temporizador en marcha.',
  'barra2.timer-in-pausa': 'Temporizador en pausa.',
  'barra2.scrivi-riprendi': 'Escribe «sigue» cuando vuelvas.',
  'barra2.si-riparte': 'Seguimos.',
  'barra2.focus-esame-sconosciuto': 'No encuentro **{nome}** entre tus exámenes. ¿Empiezo estudio libre? Escribe «focus {min}».',
  'barra2.di-quale-esame': '¿De qué examen?',
  'barra2.idoneita-registrata': '{nome}: apto registrado.',
  'barra2.voto-in': '{voto} en {nome}.',
  'barra2.voto-lode-in': '{voto} con matrícula en {nome}.',
  'barra2.nuovo-esame-6-cfu': 'Examen nuevo de 6 créditos: corrige los créditos en tus notas.',
  'barra2.media-diff': 'Media {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome}: {voto}',
  'barra2.idoneita': 'apto',
  'barra2.trenta-e-lode': 'Matrícula de honor. Esto se celebra.',
  'barra2.bel-colpo': 'Buen golpe. Hoy respira, mañana seguimos.',
  'barra2.esame-aggiornato': '{nome} actualizado.',
  'barra2.esame-aggiunto': '{nome} añadido.',
  'barra2.esame-nota': '{quando} · {cfu} créditos',
  'barra2.esame-nota-cambiali': '{quando} · {cfu} créditos (cámbialos si son más)',
  'barra2.senza-data': 'sin fecha',
  'barra2.piano-ore': 'Para llegar preparado: unas **{h} h al día** ({tot} h en total).',
  'barra2.proposte-spente-riaccendi': 'Las propuestas están apagadas: las vuelves a encender con «propuestas normales».',
  'barra2.proposte-da-adesso': 'Desde ahora, cuando estés en el ordenador y libre, te propongo juegos, repasos y preguntas de {nome}.',
  'barra2.proposte-da-adesso-vicino': 'Desde ahora, cuando estés en el ordenador y libre, te propongo juegos, repasos y preguntas de {nome}, cada vez más a menudo según se acerque.',
  'barra2.carta-aggiunta': 'Tarjeta añadida.',
  'barra2.senza-esame': 'sin examen',
  'barra2.esame-sconosciuto': 'No encuentro **{nome}** entre tus exámenes.',
  'barra2.spiego-senza-programma': 'Primero pega el temario de un examen («temario de cálculo 2»): después me explicas sus temas y te digo qué te has saltado.',
  'barra2.argomento-sconosciuto': 'No encuentro **{q}** en los temarios de tus exámenes.',
  'barra2.esame-non-trovato': 'No encuentro el examen **{nome}**.',
  'barra2.domande-di-quale-esame': '¿De qué examen? Por ejemplo: «preguntas de examen de cálculo 2: …».',
  'barra2.nella-nota-lezione': 'En la nota de la clase.',
  'barra2.in-orario': '{corso} en el horario.',
  'barra2.aula': 'aula {aula}',
  'barra2.sintesi-in-orario': '{corso} en el horario',
  'barra2.orario-spiegazione': 'Cuando estás en clase la barra lo sabe: se abre en la captura rápida (★ de examen, definiciones, preguntas) y en casa te propone dos minutos de juego sobre lo que acabas de ver.',
  'barra2.proposte-spente': 'Propuestas apagadas.',
  'barra2.proposte-poche': 'Pocas propuestas.',
  'barra2.proposte-normali': 'Propuestas normales.',
  'barra2.proposte-frequenti': 'Propuestas frecuentes.',
  'barra2.riaccendi-quando-vuoi': 'Las vuelves a encender cuando quieras.',
  'barra2.proposte-mai-quando': 'Nunca en clase, en el trabajo, en focus ni en las horas de silencio.',
  'barra2.niente-da-proporre': 'Por ahora no tengo nada que proponerte: añade un examen con la fecha, o apunta alguna definición en clase.',
  'barra2.trascrizione-in-pausa': 'Transcripción en pausa.',
  'barra2.scrivi-riprendi-trascrizione': 'Escribe «reanuda la transcripción» cuando vuelva a empezar.',
  'barra2.riprendo-trascrivere': 'Vuelvo a transcribir.',
  'barra2.err-valutato': 'Proyecto evaluado: la corrección no te la enseño.',
  'barra2.errore-spiegato': 'Error explicado',
  'barra2.correzione-vista': 'corrección vista',
  'barra2.copia-errore': 'Copia el error de la terminal (o del IDE) y vuelve a escribir «explícame el error».',
  'barra2.incolla-errore': 'Pega el error después de los dos puntos: «explícame el error: …».',
  'barra2.nessun-errore-nel-testo': 'En este texto no encuentro un error del compilador ni del programa. Cópialo todo, desde la línea con el nombre del archivo, y vuelve a intentarlo.',
  'barra2.segui-valutato': 'Sigues un proyecto evaluado: la corrección no te la enseño.',
  'barra2.diario-solo-app': 'El diario está en el vault: necesitas la **app de escritorio** de Lode.',
  'barra2.progetto-sconosciuto': 'No encuentro ningún proyecto que se llame «{nome}».',
  'barra2.nessun-progetto-segui': 'Todavía no sigo ningún proyecto. Escribe **sigue el proyecto** y elige la carpeta de la práctica.',
  'barra2.diario-spento-per': 'Para **{progetto}** el diario está apagado: en el vault no escribo nada. Lo vuelves a encender con «activa el diario de {progetto}».',
  'barra2.diario-non-si-apre': 'No puedo abrir el diario: {errore}',
  'barra2.diario-di': 'Diario de {progetto}.',
  'barra2.aperto-editor-sistema': 'Abierto con el editor del sistema: con Obsidian es más cómodo.',
  'barra2.aperto-in-obsidian': '{file} · abierto en Obsidian.',
  'barra2.sintesi-diario-di': 'diario de {progetto}',
  'barra2.nessun-progetto': 'Todavía no sigo ningún proyecto.',
  'barra2.diario-acceso': 'Diario de {nome} encendido.',
  'barra2.diario-acceso-nota': 'Escribo en el vault lo que veo: qué cambia y las pruebas. No sé quién escribe las líneas.',
  'barra2.diario-spento': 'Diario de {nome} apagado.',
  'barra2.diario-spento-nota': 'Desde ahora no escribo nada de este proyecto en el vault. Las notas ya escritas se quedan: puedes quitarlas desde Obsidian.',
  'barra2.focus-di-minuti': 'Focus de {min} minutos.',
  'barra2.focus-di-minuti-su': 'Focus de {min} minutos en {nome}.',
  'barra2.salvare-carte': { one: '¿Guardar {n} tarjeta?', other: '¿Guardar {n} tarjetas?' },
  'barra2.salvare-carte-di': { one: '¿Guardar {n} tarjeta de {nome}?', other: '¿Guardar {n} tarjetas de {nome}?' },
  'barra2.entrano-ripasso': 'Entran en el repaso de hoy.',
  'barra2.carte-salvate': { one: '{n} tarjeta guardada.', other: '{n} tarjetas guardadas.' },
  'barra2.ripassa-ora': 'Repasar ahora',
  'barra2.sintesi-carte': { one: '{n} tarjeta', other: '{n} tarjetas' },
  'barra2.aggiungere-esame': '¿Añadir {nome}?',
  'barra2.esame': 'Examen',
  'barra2.cfu': 'Créditos',
  'barra2.appello': 'Fecha',
  'barra2.registrare-voto': '¿Apuntar un {voto}?',
  'barra2.registrare-voto-lode': '¿Apuntar un {voto} con matrícula?',
  'barra2.esame-nuovo-6-cfu': '{nome} (nuevo, 6 créditos)',
  'barra2.voto': 'Nota',
  'barra2.voto-e-lode': '{voto} con matrícula',
  'barra2.voto-registrato': 'Nota apuntada.',
  'barra2.media': 'Media {media}',
  'barra2.leggo-il-file': 'Leyendo el archivo…',
  'barra2.prof-ci-pensa': 'El profe se lo está pensando…',
  'barra2.un-attimo': 'Un momento…',
  'barra2.file-senza-carte-locale': 'De este archivo no he sacado tarjetas: si es un PDF, el modelo local no lo lee. Prueba con una foto de las páginas o con el texto.',
  'barra2.file-illeggibile': 'No he podido leer el archivo: {errore}',
  'barra2.chiave-non-valida-ricollega': 'La clave no es válida: vuelve a conectarla escribiendo «IA».',
  'barra2.troppe-richieste': 'Demasiadas peticiones en poco tiempo: vuelve a intentarlo en un minuto.',
  'barra2.sovraccarico': '{motore} está saturado en este momento: vuelve a intentarlo en un rato.',
  'barra2.manca-rete': 'Parece que no hay conexión.',
  'barra2.qualcosa-non-andato': 'Algo ha fallado: {errore}',
  'barra2.orale-serve-ai-app': 'Para el oral hace falta la IA: instala el **cerebro local** desde «Prepara Lode» (gratis, sin conexión) o conecta tu IA (escribe «IA»). Mientras tanto puedes hacer el **repaso** de las tarjetas.',
  'barra2.orale-serve-ai-web': 'Para el oral hace falta la IA: añade tu clave de Claude en **Ajustes** (cuesta unos céntimos por sesión). Mientras tanto puedes hacer el **repaso** de las tarjetas.',
  'barra2.orale-esame-sconosciuto': 'No encuentro **{nome}**: te pregunto igualmente sobre eso.',
  'barra2.su-quale-esame': '¿Sobre qué examen?',
  'barra2.aggiungi-prima-esame': 'Primero añade un examen.',
  'barra2.interrogami-su': 'Pregúntame sobre {nome}',
  'barra2.orale-di-contesto': 'Oral · <b>{nome}</b>',
  'barra2.esci': 'Salir',
  'barra2.sintesi-orale-di': 'oral de {nome}',
  'barra2.domanda-n-di': '**Pregunta {n} de {max}.** {domanda}',
  'barra2.prof-non-risponde': 'El profe no responde: {errore}',
  'barra2.prof-ascolta': 'El profe escucha…',
  'barra2.orale-mancava': 'Faltaba: {cosa}',
  'barra2.era-giusta': 'Estaba bien',
  'barra2.segnata-giusta': 'Marcada como bien',
  'barra2.prof-scrive-voto': 'El profe escribe la nota…',
  'barra2.orale-titolo': { one: 'Oral · {nome} · {n} pregunta', other: 'Oral · {nome} · {n} preguntas' },
  'barra2.da-ripassare': 'Para repasar',
  'barra2.orale-calcolo': 'La nota la calcula Lode con tus respuestas (bien 3 puntos, a medias 2).',
  'barra2.orale-calcolo-contestate': { one: 'La nota la calcula Lode con tus respuestas (bien 3 puntos, a medias 2), contando la respuesta que marcaste como bien.', other: 'La nota la calcula Lode con tus respuestas (bien 3 puntos, a medias 2), contando las respuestas que marcaste como bien.' },
  'barra2.orale-giudizi-locale': 'Las valoraciones son la opinión del modelo local: puede equivocarse. Es un entrenamiento, no una predicción.',
  'barra2.orale-giudizi-ai': 'Las valoraciones son la opinión de la IA. Es un entrenamiento, no una predicción.',
  'barra2.sintesi-orale-voto': 'oral de {nome}: {voto}',
  'barra2.orale-chiuso': 'Oral terminado.',
  'barra2.ripassa-esitato': 'Repasa las preguntas en las que dudaste.',
  'barra2.agenti-solo-app': 'El puente con los agentes está en la **app de escritorio** de Lode.',
  'barra2.ponte-non-risponde': 'El puente no responde: {errore}',
  'barra2.agente-sconosciuto': 'Todavía no sé conectarme a **{agente}**. Escribe «agentes» para ver los que conozco.',
  'barra2.agenti-titolo': 'Agentes de programación',
  'barra2.agenti-spiegazione': 'Conecta el agente que usas para las prácticas: al final de cada turno Lode te dice qué ha tocado de verdad en los proyectos que sigues, si ha lanzado las pruebas después del último cambio y si ha cambiado las pruebas mientras fallaban.',
  'barra2.ag-collegato-eventi': { one: 'conectado · {n} evento, a las {ora}', other: 'conectado · {n} eventos, el último a las {ora}' },
  'barra2.ag-collegato-nessuno': 'conectado · todavía sin eventos',
  'barra2.ag-trovato': 'encontrado en este ordenador',
  'barra2.ag-non-trovato': 'no encontrado',
  'barra2.scollega': 'Desconectar',
  'barra2.agenti-nota': 'Solo lectura: Lode no responde a los agentes, no decide nada y no amplía sus permisos. Antes de escribir en su configuración te enseña las líneas exactas. Los eventos solo cuentan en los proyectos que sigues («sigue el proyecto»), los demás se descartan; lo que le escribes al agente no se guarda.',
  'barra2.sintesi-agenti': 'agentes',
  'barra2.niente-toccato': 'De acuerdo, no he tocado nada.',
  'barra2.ag-scollegato': '{nome} desconectado.',
  'barra2.ag-gia-collegato': '{nome} ya estaba conectado.',
  'barra2.ag-collegato': '{nome} conectado.',
  'barra2.ag-tolte-righe': 'Solo he quitado mis líneas.',
  'barra2.ag-poi-segui': 'Después sigue el proyecto de la práctica («sigue el proyecto»).',
  'barra2.l-agente': 'El agente',
  'barra2.ag-finito-test-dopo': { one: 'ha terminado: {n} archivo, tests ejecutados después del último cambio', other: 'ha terminado: {n} archivos, tests ejecutados después del último cambio' },
  'barra2.ag-finito-test-prima': { one: 'ha terminado: {n} archivo, sin volver a ejecutar los tests', other: 'ha terminado: {n} archivos, sin volver a ejecutar los tests' },
  'barra2.ag-finito-senza-test': { one: 'ha terminado: {n} archivo, ningún test', other: 'ha terminado: {n} archivos, ningún test' },
  'barra2.guarda': 'Ver',
  'barra2.nessun-turno': 'Todavía no hay ningún turno de un agente en los proyectos que sigues. Escribe «agentes» para conectar uno.',
  'barra2.esito-non-noto': 'resultado desconocido',
  'barra2.riuscito': 'salió bien',
  'barra2.fallito-codice': 'falló (código {codice})',
  'barra2.alle': 'a las {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> archivo tocado: {elenco}.', other: '<b>{n}</b> archivos tocados: {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> archivos tocados.',
  'barra2.comandi': { one: '{n} comando', other: '{n} comandos' },
  'barra2.test-lanciati-dopo': { one: 'pruebas lanzadas {n} vez, la última <code>{comando}</code> {esito}, después del último cambio', other: 'pruebas lanzadas {n} veces, la última <code>{comando}</code> {esito}, después del último cambio' },
  'barra2.test-lanciati-prima': { one: 'pruebas lanzadas {n} vez, la última <code>{comando}</code> {esito}, <b>antes</b> del último cambio', other: 'pruebas lanzadas {n} veces, la última <code>{comando}</code> {esito}, <b>antes</b> del último cambio' },
  'barra2.nessun-test-lanciato': 'ninguna prueba lanzada',
  'barra2.cosa-cambiato': 'Qué ha cambiado',
  'barra2.prova-tu': 'Pruébalo tú',
  'barra2.preparati-discussione': 'Prepárate para la defensa',
  'barra2.parole-agente': 'Lo que dice el agente son palabras: las pruebas solo las ha lanzado de verdad si las ves aquí. Las reglas son fijas: si no encuentran nada, no es una garantía.',
  'barra2.prova-il-progetto': 'Prueba el proyecto',
  'barra2.sintesi-turno': { one: '{chi}: {n} archivo', other: '{chi}: {n} archivos' },
};
