// Textos de la bienvenida (español): los pasos obligatorios (nombre, instalaciones) y la configuración rápida
// (carrera, expediente, exámenes, horario, hábitos), más la conexión con un Lode que ya está en otro ordenador.
export default {
  // el marco
  'benvenuto.tasti-mac': '⌥ Espacio',
  'benvenuto.tasti-altri': 'Ctrl ⇧ Espacio',
  'benvenuto.avanti': 'Siguiente',
  'benvenuto.indietro': 'Atrás',
  'benvenuto.salta': 'Saltar',
  'benvenuto.obbligatorio': 'Obligatorio',
  'benvenuto.facoltativo': 'Opcional · configuración rápida',
  // hola
  'benvenuto.ciao-titolo': 'Hola.<br>Soy Lode.',
  'benvenuto.ciao-sotto': 'Vivo en una pequeña barra arriba de la pantalla. En clase no dejo que te pierdas nada, en casa te entreno en lo que estás a punto de olvidar, y lo guardo todo en tu Obsidian.',
  'benvenuto.ciao-nota': 'Primero tres cosas necesarias (dos minutos, más las descargas). Después, si quieres, la configuración rápida.',
  'benvenuto.altro-computer': 'Ya uso Lode en otro ordenador',
  'benvenuto.sperimentale': '(experimental)',
  'benvenuto.iniziamo': 'Empecemos',
  // otro ordenador
  'benvenuto.scegli-vault-cloud': 'Elige el vault de Lode en tu carpeta en la nube (iCloud Drive, OneDrive, Dropbox, Google Drive).',
  'benvenuto.scegli-vault': 'Elegir el vault…',
  'benvenuto.password-dati': 'La contraseña de los datos de Lode, si pusiste una',
  'benvenuto.collego': 'Conectando…',
  'benvenuto.cartella-no': 'No puedo usar esa carpeta.',
  'benvenuto.ricevo-dati': 'Recibiendo los datos de los otros ordenadores… Ya puedes usar Lode: llegan solos.',
  'benvenuto.inizia': 'Empezar',
  'benvenuto.password-sbagliata': 'Contraseña incorrecta: vuelve a intentarlo.',
  'benvenuto.password-serve': 'Los datos de Lode están protegidos con una contraseña: escríbela aquí arriba.',
  // nombre
  'benvenuto.nome-titolo': '¿Cómo te llamas?',
  'benvenuto.nome-sotto': 'Solo para saludarte. Se queda en tu ordenador.',
  'benvenuto.nome-segnaposto': 'Tu nombre',
  'benvenuto.togli-esempio': 'Quitar los datos de ejemplo de «Giulia» (exámenes, notas, tarjetas y horas de estudio de mentira). Lo que has añadido tú se queda.',
  // instalaciones
  'benvenuto.web-titolo': 'El Lode completo vive en la app.',
  'benvenuto.web-sotto': 'En el navegador tienes expediente, temporizador, repaso y juegos. Obsidian, la IA en el ordenador, la voz y la transcripción de las clases están en la app de escritorio.',
  'benvenuto.installa-titolo': 'Preparemos tu ordenador.',
  'benvenuto.installa-sotto': 'Tres instalaciones, una sola vez. Después Lode funciona también sin internet, y nada tuyo sale del ordenador.',
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'donde viven tus apuntes: un vault ya listo',
  'benvenuto.cervello': 'El cerebro local',
  'benvenuto.cervello-cosa': 'Ollama y Qwen3.5: lee los apuntes, crea tarjetas y definiciones, explica y te pregunta',
  'benvenuto.voce': 'La voz',
  'benvenuto.voce-cosa': '{voce}: comandos por voz, «Repite» y transcripción de las clases',
  'benvenuto.peso-gb': '{n} GB',
  'benvenuto.peso-mb': '{n} MB',
  'benvenuto.installa-nota': 'Obsidian es gratis para uso personal y viene de su web oficial. El cerebro local se elige según la memoria del ordenador.',
  'benvenuto.installa-tutto': 'Instalar todo',
  'benvenuto.gia-installato': 'Ya instalado',
  'benvenuto.modello-pronto': '{modello} ya está listo',
  'benvenuto.gia-pronta': 'Ya lista',
  'benvenuto.voce-pronta': '{voce} está listo',
  'benvenuto.scarico-voce-pct': 'Descargando la voz · {p}%',
  'benvenuto.tutto-pronto': 'Obsidian, el cerebro local y la voz están listos.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'el cerebro local',
  'benvenuto.scarico-voce': 'la voz',
  'benvenuto.scarico-pct': '{cosa} {p}%',
  'benvenuto.scarico-continua-voce': 'Todavía estoy descargando: {cosa}. Sigue solo, también con la ventana cerrada; la voz vuelve a la barra en cuanto abras Lode.',
  'benvenuto.scarico-continua': 'Todavía estoy descargando: {cosa}. Sigue solo, también con la ventana cerrada.',
  'benvenuto.scarico-solo-voce': 'Todavía estoy descargando: {cosa}. La voz vuelve a la barra en cuanto abras Lode.',
  // configuración rápida
  'benvenuto.veloce-titolo': '{nome}, ¿quieres la configuración rápida?',
  'benvenuto.veloce-sotto': 'Cuéntame universidad, exámenes y horarios: desde mañana Lode sabe cuándo estás en clase, cuánto te falta para terminar la carrera y qué repasar antes de cada examen.',
  'benvenuto.veloce-lista': ['Universidad y carrera', 'Tu expediente, pegado desde el portal de la universidad o escrito a mano', 'Los exámenes que te quedan, con las fechas', 'El horario de clases, también desde el calendario de la universidad (.ics)', 'Cómo y cuándo estudias'],
  'benvenuto.veloce-nota': 'Todo opcional, todo se puede cambiar después. Nada va a internet.',
  'benvenuto.facciamolo': 'Vamos',
  // carrera
  'benvenuto.corso-titolo': '¿Dónde estudias?',
  'benvenuto.ateneo': 'Universidad',
  'benvenuto.ateneo-segnaposto': 'Empieza a escribir…',
  'benvenuto.corso': 'Carrera',
  'benvenuto.corso-segnaposto': 'Ingeniería informática',
  'benvenuto.tipo': 'Tipo',
  'benvenuto.tipo-180': 'Grado de 3 años · 180 créditos',
  'benvenuto.tipo-120': 'Máster · 120 créditos',
  'benvenuto.tipo-300': 'Ciclo único · 300 créditos',
  'benvenuto.tipo-360': 'Ciclo único · 360 créditos',
  'benvenuto.anno': 'Curso',
  'benvenuto.anni': ['1.º', '2.º', '3.º', '4.º', '5.º', '6.º', 'Fuera de plazo'],
  'benvenuto.lode-vale': 'La matrícula vale',
  'benvenuto.lode-nota': 'Depende del reglamento: si dudas, 30',
  // expediente
  'benvenuto.libretto-titolo': 'Los exámenes que ya has aprobado',
  'benvenuto.libretto-sotto': 'Abre tu expediente en el portal de la universidad (Esse3, Infostud…), selecciona todo, copia y pégalo aquí. Yo me encargo. O escríbelos uno por línea: «Cálculo 1, 9 créditos, 28».',
  'benvenuto.libretto-segnaposto': 'Pega aquí tu expediente…',
  'benvenuto.leggi-libretto': 'Leer el expediente',
  'benvenuto.leggo-libretto': 'Leyendo el expediente…',
  'benvenuto.leggo': 'Leyendo…',
  'benvenuto.esami-trovati': 'Exámenes encontrados: {n}. Revisa y confirma.',
  'benvenuto.esami-non-trovati': 'No he encontrado exámenes: intenta escribirlos uno por línea.',
  'benvenuto.col-esame': 'Examen',
  'benvenuto.col-cfu': 'Créditos',
  'benvenuto.col-voto': 'Nota',
  'benvenuto.col-data': 'Fecha',
  'benvenuto.importa': 'Importar',
  'benvenuto.idoneo': 'apto',
  'benvenuto.voto-lode': '{voto} MH',
  // exámenes pendientes
  'benvenuto.esame': 'Examen',
  'benvenuto.cfu': 'Créditos',
  'benvenuto.data-appello': 'Fecha del examen',
  'benvenuto.togli': 'Quitar',
  'benvenuto.esami-titolo': 'Los exámenes que te quedan',
  'benvenuto.esami-sotto': 'Con la fecha del examen, si la sabes. Con eso Lode calcula cuántas horas necesitas cada día y te propone repasos y juegos cuando tienes un momento.',
  'benvenuto.altro-esame': '+ Otro examen',
  // horario
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · aula {aula}',
  'benvenuto.nessuna-lezione': 'Todavía no hay clases.',
  'benvenuto.orario-titolo': 'El horario de clases',
  'benvenuto.orario-sotto': 'Así Lode sabe cuándo estás en clase: la barra se prepara para la clase, «Repite» y la transcripción están a una tecla, y en casa te entrena en lo que acabas de oír.',
  'benvenuto.scrivila': 'Escríbelo como lo dirías',
  'benvenuto.frase-segnaposto': 'cálculo 2 lunes y miércoles 9-11 aula 7',
  'benvenuto.aggiungi': 'Añadir',
  'benvenuto.importa-ics': 'Importar el calendario (.ics)',
  'benvenuto.incolla-orario': 'O pega el horario desde la web de la universidad',
  'benvenuto.orario-segnaposto': 'Pega aquí la tabla del horario…',
  'benvenuto.leggi-orario': 'Leer el horario',
  'benvenuto.frase-aiuto': 'Escribe asignatura, días y horas: «física lunes 14-16 aula B2».',
  'benvenuto.lezioni-calendario': 'Clases desde el calendario: {n}.',
  'benvenuto.calendario-vuoto': 'En el calendario no he encontrado clases semanales.',
  'benvenuto.leggo-orario': 'Leyendo el horario…',
  'benvenuto.lezioni-trovate': 'Clases encontradas: {n}.',
  'benvenuto.lezioni-non-trovate': 'No he encontrado clases: intenta escribirlas una a una.',
  // hábitos
  'benvenuto.abitudini-titolo': '¿Cómo estudias?',
  'benvenuto.abitudini-sotto': 'Lode te propone repasos, juegos y preguntas rápidas en momentos al azar del día, cuando estás en el ordenador. Dime cada cuánto y cuándo dejarte en paz.',
  'benvenuto.quando-meglio': 'Cuándo estudias mejor',
  'benvenuto.mattina': 'Mañana',
  'benvenuto.pomeriggio': 'Tarde',
  'benvenuto.sera': 'Noche',
  'benvenuto.notte': 'Madrugada',
  'benvenuto.proposte': 'Propuestas de Lode',
  'benvenuto.scelta-mai': 'Nunca',
  'benvenuto.scelta-poco': 'Pocas',
  'benvenuto.scelta-normale': 'Normales',
  'benvenuto.scelta-spesso': 'Muchas',
  'benvenuto.proposte-nota': 'Cuanto más cerca el examen, más a menudo. Nunca durante clases, focus o de noche.',
  'benvenuto.silenzio-dalle': 'Silencio de',
  'benvenuto.silenzio-alle': 'a',
  'benvenuto.focus': 'Focus',
  'benvenuto.minuti': '{n} min',
  'benvenuto.ripeti-in-aula': 'En clase activa «Repite» solo (el último minuto y medio, solo en memoria). Pregunta al profe si se puede grabar.',
  // fin
  'benvenuto.fine-titolo': 'Listo, {nome}.',
  'benvenuto.fine-sotto': 'Lode ahora vive arriba de la pantalla. Pasa el cursor por encima para abrirla, mantén pulsado <b>{tasti}</b> para hablarle, arrastra encima un PDF o una foto de la pizarra.',
  'benvenuto.fine-esami': 'Exámenes en tu expediente: {fatti}; te quedan {dare}',
  'benvenuto.fine-esami-prossimo': 'Exámenes en tu expediente: {fatti}; te quedan {dare} · el próximo es {nome}',
  'benvenuto.fine-lezioni': 'Clases a la semana en tu horario: {n}',
  'benvenuto.fine-proposte': 'Propuestas: {quante}',
  'benvenuto.quante-mai': 'nunca',
  'benvenuto.quante-poco': 'pocas',
  'benvenuto.quante-normale': 'normales',
  'benvenuto.quante-spesso': 'muchas',
  'benvenuto.apri-lode': 'Abrir Lode',
};
