// Textos de la app de escritorio (español): ventanas del sistema, menú del icono, notificaciones y mensajes del
// proceso principal (desktop/*.mjs) que llegan al estudiante.
export default {
  // main.mjs: ventanas del sistema
  'desktop.non-ci-sono-riuscito': 'No lo he conseguido.',
  'desktop.benvenuto-in-lode': 'Bienvenido a Lode',
  'desktop.dove-tenere-il-vault': 'Dónde guardar el vault',
  'desktop.usa-questa-cartella': 'Usar esta carpeta',
  'desktop.non-e-andata': 'No ha funcionado.',
  'desktop.vault-con-sincronizzazione': 'Con la sincronización, el vault se cambia desde «Sincroniza entre tus ordenadores»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Dejar de sincronizar en este ordenador» saca el vault de la carpeta de la nube.',
  'desktop.scegli-il-vault': 'Elige el vault de Obsidian',
  'desktop.usa-questo-vault': 'Usar este vault',
  'desktop.cartella-non-usabile': 'Lode no puede usar la carpeta {cartella}',
  'desktop.cartella-protetta-windows': 'Probablemente Windows la protege (Seguridad de Windows › Protección contra ransomware › Acceso controlado a carpetas) o el antivirus bloquea Lode. Permite Lode o elige otra carpeta.',
  'desktop.scegli-altra-cartella': 'Elegir otra carpeta',
  'desktop.riprova': 'Reintentar',
  'desktop.non-ora': 'Ahora no',
  'desktop.obsidian-pronto': 'Obsidian está listo con tu vault',
  'desktop.modello-pronto': '{modello} está listo',
  'desktop.ponte-non-partito': 'El puente con los agentes no ha arrancado: reinicia Lode.',
  'desktop.agente-togliere': '¿Quitar Lode de la configuración de {agente}?',
  'desktop.agente-collegare': '¿Conectar {agente} a Lode?',
  'desktop.agente-toglie-righe': 'Lode quita solo sus líneas en:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode añade solo sus líneas, el resto queda como está en:\n{file}',
  'desktop.agente-manda-eventi': '{agente} enviará a Lode, en este ordenador, los eventos de las sesiones (archivos tocados, comandos, fin del turno). Lode no responde ni decide nada. ',
  'desktop.agente-file-com-era': 'El archivo como estaba queda en {file}.',
  'desktop.togli': 'Quitar',
  'desktop.collega': 'Conectar',
  'desktop.annulla': 'Cancelar',
  // main.mjs: el menú del icono
  'desktop.menu-avvisami-versioni': 'Avisarme de las versiones nuevas',
  'desktop.menu-aggiornamenti-automatici': 'Actualizaciones automáticas',
  'desktop.menu-riavvia-con': 'Reiniciar con Lode {versione}',
  'desktop.menu-scarica': 'Descargar Lode {versione}…',
  'desktop.menu-apri': 'Abrir Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Espacio',
  'desktop.tasti-apri': 'Ctrl+Mayús+Espacio',
  'desktop.menu-quadro': 'El panel: notas, exámenes, repaso',
  'desktop.menu-rifai-configurazione': 'Volver a configurar…',
  'desktop.menu-apri-vault-obsidian': 'Abrir el vault en Obsidian',
  'desktop.menu-mostra-vault': 'Mostrar el vault en la carpeta',
  'desktop.menu-altro-vault': 'Usar otro vault…',
  'desktop.menu-avvio-accensione': 'Abrir Lode al encender el ordenador',
  'desktop.menu-icona-mac': 'Icono de Lode en Aplicaciones',
  'desktop.menu-icona-win': 'Icono de Lode en el menú Inicio y en el escritorio',
  'desktop.menu-icona-linux': 'Icono de Lode en el menú de aplicaciones',
  'desktop.menu-esci': 'Salir de Lode',
  // sincronizza.mjs: la sincronización entre ordenadores
  'desktop.sync-file-occupato': 'Otro programa está usando un archivo: ciérralo y vuelve a intentarlo. El vault de antes está intacto.',
  'desktop.sync-file-occupato-nome': 'Otro programa está usando un archivo ({file}): ciérralo y vuelve a intentarlo. El vault de antes está intacto.',
  'desktop.sync-disco-pieno': 'El disco de la carpeta de la nube está lleno. El vault de antes está intacto.',
  'desktop.sync-permesso': 'Lode no tiene permiso para leer o escribir un archivo. El vault de antes está intacto.',
  'desktop.sync-permesso-nome': 'Lode no tiene permiso para leer o escribir un archivo ({file}). El vault de antes está intacto.',
  'desktop.sync-copia-diversa': 'La copia de {file} no ha salido igual: vuelve a intentarlo. El vault de antes está intacto.',
  'desktop.sync-copia-non-riuscita': 'La copia del vault no ha funcionado: vuelve a intentarlo. El vault de antes está intacto.',
  'desktop.sync-sto-accendendo': 'Ya estoy activando la sincronización: espera a que termine.',
  'desktop.sync-cartella-titolo': 'La carpeta que se sincroniza',
  'desktop.sync-sincronizza-qui': 'Sincronizar aquí',
  'desktop.sync-spostamento-con-password': 'El traslado había empezado con la contraseña: escríbela otra vez.',
  'desktop.sync-dati-occupati': 'Otro programa está usando el archivo de datos de Lode (¿un antivirus?): vuelve a intentarlo en un rato.',
  'desktop.sync-diario-illeggibile': 'El registro de Lode en este ordenador no se puede leer.',
  'desktop.sync-controllo-altro-computer': 'Compruebo si otro ordenador ya sincroniza este vault…',
  'desktop.sync-aspetto-dati': 'Espero a que los datos de Lode lleguen desde la nube (el archivo de datos todavía no se puede leer): vuelve a intentarlo en un rato.',
  'desktop.sync-altra-password': 'En este vault la sincronización ya está activada con otra contraseña: escribe esa.',
  'desktop.sync-gia-con-password': 'En este vault la sincronización ya está activada con contraseña: escríbela.',
  'desktop.sync-non-accendo': 'No puedo activar la sincronización aquí.',
  'desktop.sync-cartella-dentro-vault': 'Esta carpeta está dentro del vault: elige una de fuera, por ejemplo la carpeta de iCloud Drive, OneDrive o Dropbox.',
  'desktop.sync-dati-non-ancora': 'Los datos de Lode todavía no se pueden leer (¿carpeta no disponible?): vuelve a intentarlo en un rato.',
  'desktop.sync-copio-vault': 'Copiando el vault…',
  'desktop.sync-copio-vault-file': 'Copiando el vault… {n} archivos',
  'desktop.sync-cifro-pubblico': 'Cifrando y publicando los datos de Lode…',
  'desktop.sync-pubblico': 'Publicando los datos de Lode…',
  'desktop.sync-non-creo-dati': 'No puedo crear los datos de Lode en la carpeta de la nube. El vault de antes está intacto.',
  'desktop.sync-vault-nel-cloud': 'El vault de Lode en la carpeta de la nube',
  'desktop.sync-non-e-vault-sincronizzato': 'En esta carpeta no hay un vault de Lode sincronizado: elige la carpeta «Lode» dentro de la carpeta de la nube (en el otro ordenador: «Sincroniza entre tus ordenadores»).',
  'desktop.sync-diario-altro-vault': 'En este ordenador Lode ya usa el registro de otro vault: primero «Dejar de sincronizar en este ordenador».',
  'desktop.sync-password-sbagliata-di-nuovo': 'Contraseña incorrecta: escríbela otra vez.',
  'desktop.sync-password-vecchia': 'Esta es la contraseña de antes: en otro ordenador ha cambiado, escribe la nueva.',
  'desktop.sync-lode-piu-nuova': 'Este vault lo protegió una versión más nueva de Lode: actualízala.',
  'desktop.sync-gruppo-manomesso': 'La contraseña es correcta, pero el archivo del grupo en la carpeta de la nube se cambió desde fuera: no lo uso. Revisa la carpeta de la nube.',
  'desktop.sync-gruppo-in-chiaro': 'El grupo en la carpeta de la nube no está cifrado: en el otro ordenador la sincronización está sin contraseña, o el archivo del grupo ha sido manipulado. Si en el otro ordenador no pusiste contraseña, vuelve a intentarlo sin ella.',
  'desktop.sync-password-sbagliata': 'Contraseña incorrecta.',
  'desktop.sync-adesso-non-si-puo': 'Ahora no se puede.',
  'desktop.sync-cartella-in-cloud': 'Esta carpeta está en una carpeta de la nube: para sincronizar usa «Sincroniza entre tus ordenadores».',
  'desktop.sync-fuori-dal-vault': 'Elige una carpeta fuera del vault actual.',
  'desktop.sync-non-sposto-dati': 'No puedo mover los datos de Lode a esa carpeta. El vault de antes está intacto.',
  'desktop.sync-riprova-tra-poco': 'Ahora no se puede: vuelve a intentarlo en un rato.',
  'desktop.sync-password-corta': 'La contraseña debe tener al menos 8 caracteres.',
  'desktop.sync-diario-illeggibile-riprova': 'El registro de Lode en este ordenador no se puede leer: primero «Reintentar».',
  'desktop.sync-non-accesa': 'En este ordenador la sincronización no está activada.',
  'desktop.sync-vault-spostato-scegli': 'El vault ya no está donde Lode lo buscaba: si lo moviste, usa «Buscar el vault» y elige la carpeta nueva.',
  'desktop.sync-dove-fuori-cloud': 'Dónde guardar el vault, fuera de la carpeta de la nube',
  'desktop.sync-tieni-qui': 'Guardar aquí el vault',
  'desktop.sync-fuori-dal-cloud': 'Elige una carpeta fuera de la carpeta de la nube.',
  'desktop.sync-vault-spostato': 'El vault ya no está donde Lode lo buscaba: si lo moviste, usa «Buscar el vault».',
  'desktop.sync-cambio-in-arrivo': 'Los últimos cambios de este ordenador todavía no están en la carpeta de la nube (está llegando un cambio de los otros ordenadores): vuelve a intentarlo en un rato.',
  'desktop.sync-smetti-serve-password': 'Los cambios hechos en pausa se quedarían solo en este ordenador: escribe la contraseña antes de dejarlo (o «He olvidado la contraseña»).',
  'desktop.sync-note-non-scaricate': 'Algunas notas no están descargadas en este ordenador ({note}): ábrelas o descárgalas desde el servicio de la nube y vuelve a intentarlo.',
  'desktop.sync-note-non-scaricate-altre': 'Algunas notas no están descargadas en este ordenador ({note} y {n} más): ábrelas o descárgalas desde el servicio de la nube y vuelve a intentarlo.',
  'desktop.sync-copio-fuori-cloud': 'Copiando el vault fuera de la carpeta de la nube…',
  // progetto.mjs: «sigue el proyecto», el resumen «Hecho. En pocas palabras» y la confirmación de los comandos
  'desktop.progetto-elenco': '{primi} y {ultimo}',
  'desktop.progetto-elenco-altre': '{primi} y {n} más',
  'desktop.progetto-elenco-altri': '{primi} y {n} más',
  'desktop.progetto-righe-piu-meno': { one: '{n} línea más y {meno} menos', other: '{n} líneas más y {meno} menos' },
  'desktop.progetto-righe-piu': { one: '{n} línea más', other: '{n} líneas más' },
  'desktop.progetto-righe-meno': { one: '{n} línea menos', other: '{n} líneas menos' },
  'desktop.progetto-solo-spazi': 'solo espacios o saltos de línea',
  'desktop.progetto-file-nuovo': { one: 'archivo nuevo ({n} línea)', other: 'archivo nuevo ({n} líneas)' },
  'desktop.progetto-file-tolto': 'eliminado',
  'desktop.progetto-funzioni-nuove': { one: 'nueva función {elenco}', other: 'nuevas funciones {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'cambiada {elenco}', other: 'cambiadas {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'eliminada {elenco}', other: 'eliminadas {elenco}' },
  'desktop.progetto-file': '{file}: {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'Nuevo {elenco}.', other: 'Nuevos {elenco}.' },
  'desktop.progetto-esito-compila': 'compila',
  'desktop.progetto-esito-non-compila': 'no compila',
  'desktop.progetto-esito-sintassi-a-posto': 'sintaxis correcta',
  'desktop.progetto-esito-errore-di-sintassi': 'error de sintaxis',
  'desktop.progetto-esito-make-riuscito': 'make correcto',
  'desktop.progetto-esito-make-non-riuscito': 'make falló',
  'desktop.progetto-prove-su': { one: '{n} prueba de {tot}', other: '{n} pruebas de {tot}' },
  'desktop.progetto-prova-non-partita': 'la prueba no arrancó',
  'desktop.progetto-inizio-alle': { one: 'A las {ora} cambió {n} archivo (+{piu} −{meno}).', other: 'A las {ora} cambiaron {n} archivos (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'De {da} a {a} cambió {n} archivo (+{piu} −{meno}).', other: 'De {da} a {a} cambiaron {n} archivos (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**¿Probado?** Sí: es el código que se probó a las {ora} ({esito}).',
  'desktop.progetto-provato-no-codice': '**¿Probado?** No, pero aquí solo cambiaron archivos que no son código.',
  'desktop.progetto-provato-no': '**¿Probado?** No: después del último cambio ({ora}) nadie ha compilado con Lode.',
  'desktop.progetto-nota-chi': 'No sé quién escribió estas líneas.',
  'desktop.progetto-altri-file': 'Y {n} archivos más.',
  'desktop.progetto-nessuna-cartella': 'No he recibido ninguna carpeta.',
  'desktop.progetto-non-trovo-cartella': 'No encuentro esta carpeta.',
  'desktop.progetto-cartella-non-file': 'Elige una carpeta, no un archivo.',
  'desktop.progetto-radice-disco': 'Esta es la raíz del disco: elige solo la carpeta del proyecto (por ejemplo lab3).',
  'desktop.progetto-tutta-la-home': 'Esta carpeta contiene toda tu carpeta de usuario: elige solo la carpeta del proyecto.',
  'desktop.progetto-e-il-vault': 'Este es el vault de Lode (o lo contiene): elige la carpeta del proyecto.',
  'desktop.progetto-dati-di-lode': 'Esta es la carpeta donde Lode guarda sus datos: elige la del proyecto.',
  'desktop.progetto-troppi-progetti': 'Ya sigo {n} proyectos: deja de seguir uno («deja de seguir …») y vuelve a intentarlo.',
  'desktop.progetto-cartella-illeggibile': 'No puedo leer esta carpeta.',
  'desktop.progetto-troppi-file': 'Aquí hay más de {n} archivos: elige solo la carpeta del proyecto (por ejemplo lab3).',
  'desktop.progetto-non-seguo': 'No sigo este proyecto.',
  'desktop.progetto-versione-scaduta': 'Esa versión ya no está: Lode guarda las versiones 30 días.',
  'desktop.progetto-file-non-seguito': 'Este archivo no está entre los que sigo.',
  'desktop.progetto-file-illeggibile': 'No puedo leer el archivo.',
  'desktop.progetto-poi-per-ogni-prova': 'Después, para cada prueba .in → .out:\n{comandi}',
  'desktop.progetto-senza-prove': 'No ejecuto el programa: no hay pruebas .in/.out.',
  'desktop.progetto-resto-non-mostro': '(el resto no lo muestro)',
  'desktop.progetto-smesso-durante-prova': 'Dejé de seguir el proyecto durante la prueba.',
  'desktop.progetto-scegli-cartella': 'Elige la carpeta del proyecto',
  'desktop.progetto-segui-cartella': 'Seguir esta carpeta',
  'desktop.progetto-scegli-di-nuovo': 'Elige otra vez la carpeta («sigue el proyecto»).',
  'desktop.progetto-conferma-aperta': 'Ya hay una ventana de confirmación abierta: responde primero a esa.',
  'desktop.progetto-eseguira': 'Lode ejecutará este comando en la carpeta {cartella}.',
  'desktop.progetto-come-terminale': 'Es como ejecutarlo desde la terminal: el programa corre en tu ordenador.',
  'desktop.progetto-esegui-sempre': 'Ejecutar siempre para este proyecto',
  // esegui.mjs: probar el código del proyecto
  'desktop.esegui-riapri': 'Si acabas de añadirlo al PATH, sal de Lode (desde el menú) y vuelve a abrirla.',
  'desktop.esegui-manca-c-win': 'No encuentro un compilador de C. Instala MSYS2 (msys2.org), abre «MSYS2 UCRT64» y escribe `pacman -S mingw-w64-ucrt-x86_64-gcc`: Lode lo encuentra sola en C:\\msys64\\ucrt64\\bin. Como alternativa, WinLibs (winlibs.com) o WSL. Lode no descarga nada por ti.',
  'desktop.esegui-manca-c-mac': 'No encuentro un compilador de C. Abre la Terminal y escribe `xcode-select --install`: instala el clang de Apple. Luego vuelve a intentarlo.',
  'desktop.esegui-manca-c-linux': 'No encuentro un compilador de C. Instala gcc (por ejemplo `sudo apt install build-essential`) y vuelve a intentarlo.',
  'desktop.esegui-manca-python-win': 'No encuentro Python 3. Instálalo desde python.org (marca «Add python.exe to PATH») o desde Microsoft Store, y vuelve a intentarlo.',
  'desktop.esegui-manca-python': 'No encuentro Python 3. Instálalo (python.org, o con el gestor de paquetes) y vuelve a intentarlo.',
  'desktop.esegui-manca-java': 'No encuentro un JDK (javac y java). Instala uno, por ejemplo Temurin desde adoptium.net, y vuelve a intentarlo.',
  'desktop.esegui-manca-make-win': 'Hay un Makefile pero no encuentro make. Con MSYS2, en «MSYS2 UCRT64»: `pacman -S mingw-w64-ucrt-x86_64-make`. O quita el Makefile y Lode compila sola los archivos .c.',
  'desktop.esegui-manca-make': 'Hay un Makefile pero no encuentro make. Instálalo (en el Mac: `xcode-select --install`) y vuelve a intentarlo.',
  'desktop.esegui-manca-programma': 'Falta un programa para probar el código.',
  'desktop.esegui-senza-prove': 'No encuentro pruebas .in/.out: solo compilo, no ejecuto el programa.',
  'desktop.esegui-make-prove': 'Con el Makefile no ejecuto las {n} pruebas .in/.out: no sé qué programa crea.',
  'desktop.esegui-poi-prove': { one: 'luego la prueba (archivo .in → .out esperado)', other: 'luego las {n} pruebas (archivo .in → .out esperado)' },
  'desktop.esegui-poi-prove-in': { one: 'luego la prueba en {cartella}/ (archivo .in → .out esperado)', other: 'luego las {n} pruebas en {cartella}/ (archivo .in → .out esperado)' },
  'desktop.esegui-senza-programma': '{prove}; {n} sin un programa claro',
  'desktop.esegui-make-leggi': 'make ejecuta los comandos escritos en el Makefile: léelo antes de confirmar.',
  'desktop.esegui-make-assente': 'Hay un Makefile pero no encuentro make: compilo yo los archivos .c.',
  'desktop.esegui-niente-codice': 'No encuentro código C, Python o Java que probar en esta carpeta.',
  'desktop.esegui-virgolette': 'Las comillas no están cerradas.',
  'desktop.esegui-invisibili': 'En el comando hay caracteres invisibles (saltos de línea, de control o de dirección del texto): vuelve a escribirlo a mano.',
  'desktop.esegui-comando-vuoto': 'El comando está vacío.',
  'desktop.esegui-comando-illeggibile': 'El comando no se puede leer.',
  'desktop.esegui-non-trovo-programma': 'No encuentro el programa «{programma}».',
  'desktop.esegui-bat': 'Los archivos .bat y .cmd no los ejecuto: escribe el comando que contienen.',
  'desktop.esegui-compilazione-lenta': 'La compilación no terminó en {n} segundos.',
  'desktop.esegui-prova-senza-programma': 'no sé a qué programa corresponde',
  'desktop.esegui-programma-non-creato': 'El comando no creó el programa que hay que probar.',
  'desktop.esegui-prova-illeggibile': 'no puedo leer los archivos de la prueba',
  // moodle.mjs: Moodle solo lectura
  'desktop.moodle-risponde': 'Moodle responde {stato}',
  'desktop.moodle-errore': 'error de Moodle',
  'desktop.moodle-sito-risponde': 'el sitio responde {stato}',
  'desktop.moodle-non-e-moodle': 'no es un Moodle, o el servicio para apps está desactivado',
  'desktop.moodle-non-collegato': 'Moodle no está conectado',
  'desktop.moodle-accesso-non-riuscito': 'no se pudo iniciar sesión',
  'desktop.moodle-accedi-a': 'Inicia sesión en {sito}',
  'desktop.moodle-risposta-non-valida': 'respuesta de Moodle no válida',
  'desktop.moodle-tempo-scaduto': 'tiempo agotado',
  'desktop.moodle-file-non-trovato': 'archivo no encontrado',
  'desktop.moodle-file-troppo-grande': 'archivo demasiado grande',
  'desktop.moodle-file-non-su-moodle': 'el archivo no está en Moodle',
  // installa.mjs: Obsidian y el cerebro local (Ollama)
  'desktop.installa-download-non-riuscito': 'la descarga no funcionó ({stato})',
  'desktop.installa-non-firmato': 'El instalador de {nome} no tiene la firma oficial de {nome}, así que no lo he instalado. Vuelve a intentarlo más tarde, o descárgalo tú desde el sitio oficial.',
  'desktop.installa-versione-obsidian': 'versión de Obsidian desconocida',
  'desktop.installa-scarico-obsidian': 'Descargando Obsidian {versione}',
  'desktop.installa-scarico-obsidian-mb': 'Descargando Obsidian {versione} · {mb} MB',
  'desktop.installa-installo-obsidian': 'Instalando Obsidian',
  'desktop.installa-obsidian-installato': 'Obsidian {versione} instalado',
  'desktop.installa-perche-4b': 'rápido incluso sin tarjeta gráfica: definiciones, tarjetas, juegos y oral',
  'desktop.installa-perche-35b': 'el mejor, y rápido como un modelo pequeño, para ordenadores con mucha memoria',
  'desktop.installa-perche-9b': 'explica bien y aguanta el oral',
  'desktop.installa-perche-memoria': 'para {gb} GB de memoria: definiciones, tarjetas, juegos y oral',
  'desktop.installa-ollama-non-avviato': 'Ollama no ha arrancado',
  'desktop.installa-ollama-linux': 'En Linux instala Ollama desde ollama.com con su script y luego vuelve aquí.',
  'desktop.installa-scarico-ollama-mb': 'Descargando Ollama · {mb} MB',
  'desktop.installa-installo-ollama': 'Instalando Ollama',
  'desktop.installa-avvio-ollama': 'Iniciando Ollama',
  'desktop.installa-ollama-non-risponde': 'Ollama no responde',
  'desktop.installa-scarico-modello': 'Descargando {nome} · {fatti} de {totale} GB',
  'desktop.installa-modello-pronto': '{nome} listo',
  'desktop.installa-modello-assente': 'El modelo {modello} no está instalado',
  'desktop.installa-modello-non-risponde': 'El modelo local no responde',
  // aggiorna.mjs: las versiones nuevas de Lode
  'desktop.aggiorna-github-risponde': 'GitHub responde {stato}',
  'desktop.aggiorna-non-installato': 'La actualización no se ha instalado. Vuelve a intentarlo, o cierra Lode: se instala al salir.',
  'desktop.aggiorna-non-installato-perche': 'La actualización no se ha instalado: {motivo}. Vuelve a intentarlo, o cierra Lode: se instala al salir.',
  'desktop.aggiorna-niente-pronto': 'No hay ninguna actualización lista para instalar.',
  'desktop.aggiorna-dove-scaricare': 'Todavía no sé de dónde descargarla: vuelve a intentarlo en un rato.',
  // voce-onnx.mjs y voce-onnx-motore.mjs: la voz Parakeet ONNX
  'desktop.voce-modello-illeggibile': 'No puedo leer el modelo de voz: vuelve a intentarlo en un rato.',
  'desktop.voce-spazio': 'Para la voz Parakeet hacen falta unos {serve} MB libres en el disco, y hay {liberi}.',
  'desktop.voce-rete': 'No puedo descargar la voz: revisa la conexión y vuelve a intentarlo. ({dettaglio})',
  'desktop.voce-rete-stato': 'No puedo descargar la voz ({stato}): vuelve a intentarlo más tarde.',
  'desktop.voce-file-troppo-grande': 'El archivo de voz es más grande de lo previsto.',
  'desktop.voce-interrotto': 'La descarga de la voz se interrumpió: la próxima vez sigue desde aquí. ({dettaglio})',
  'desktop.voce-impronta': 'El archivo de voz «{file}» no es el correcto (huella SHA256 distinta): lo he borrado.',
  'desktop.voce-addon': 'El programa de voz (sherpa-onnx) no se carga en este ordenador.',
  'desktop.voce-modello-rovinato': 'El modelo de Parakeet no se carga (quizá un archivo está dañado).',
  'desktop.voce-pezzo-non-trascritto': 'Parakeet no ha podido transcribir este fragmento.',
  'desktop.voce-motore-chiuso': 'El motor de voz se cerró de repente.',
  'desktop.voce-motore-chiuso-codice': 'El motor de voz se cerró de repente ({codice}).',
  'desktop.voce-motore-non-risponde': 'El motor de voz no responde.',
  // agenti-collegamenti.mjs: la conexión con los agentes de programación
  'desktop.agenti-claude-eventi': ['prompts', 'cambios y comandos', 'fin del turno', 'notificaciones'],
  'desktop.agenti-claude-nota': 'Los hooks valen desde la próxima sesión (o revísalos en /hooks).',
  'desktop.agenti-codex-eventi': ['prompts', 'cambios (apply_patch) y comandos', 'fin del turno'],
  'desktop.agenti-codex-nota': 'En la próxima sesión Codex te pide que apruebes los hooks nuevos: hazlo con /hooks.',
  'desktop.agenti-gemini-eventi': ['prompts', 'herramientas (archivos y comandos)', 'fin de la respuesta', 'notificaciones'],
  'desktop.agenti-gemini-nota': 'Vale desde la próxima sesión de Gemini CLI.',
  'desktop.agenti-cursor-eventi': ['prompts', 'archivos modificados', 'comandos', 'respuesta del agente'],
  'desktop.agenti-cursor-nota': 'Reinicia Cursor para que lea los hooks. Cursor no dice el código de salida de los comandos: se ven los tests ejecutados, pero no el resultado.',
  'desktop.agenti-copilot-eventi': ['prompts', 'herramientas (archivos y comandos)', 'fin del turno', 'notificaciones'],
  'desktop.agenti-copilot-nota': 'Un solo archivo de Lode en ~/.copilot/hooks: vale desde la próxima sesión. Copilot no envía el último mensaje del agente.',
  'desktop.agenti-windsurf-eventi': ['prompts', 'código escrito', 'comandos', 'respuesta de Cascade'],
  'desktop.agenti-windsurf-nota': 'Vale desde la próxima conversación de Cascade. Windsurf no dice el código de salida de los comandos.',
  'desktop.agenti-qwen-eventi': ['prompts', 'herramientas (archivos y comandos)', 'fin del turno', 'notificaciones'],
  'desktop.agenti-qwen-nota': 'Vale desde la próxima sesión de Qwen Code.',
  'desktop.agenti-opencode-eventi': ['archivos modificados', 'comandos', 'fin del turno'],
  'desktop.agenti-opencode-nota': 'Un plugin de Lode en ~/.config/opencode/plugins: vale desde el próximo arranque de OpenCode. Solo lee: no toca las respuestas.',
  'desktop.agenti-kilo-eventi': ['archivos modificados', 'comandos', 'fin del turno'],
  'desktop.agenti-kilo-nota': 'El plugin es el de OpenCode (Kilo es un fork): vale desde el próximo arranque. El formato de los eventos está por comprobar en tu versión.',
  'desktop.agenti-aider-eventi': ['fin de la respuesta (sin detalles)'],
  'desktop.agenti-aider-nota': 'Aider solo avisa de que ha terminado de responder, sin decir qué ha tocado: los archivos cambiados los ve «sigue el proyecto».',
  'desktop.agenti-non-json': 'no es un objeto JSON',
  'desktop.agenti-file-non-di-lode': 'ya hay un archivo con este nombre que no es de Lode',
  'desktop.agenti-notifiche-aider': 'ya están las notificaciones de Aider: Lode no las sobrescribe',
  'desktop.agenti-file-illeggibile': '{file} no se puede leer ({motivo}): no lo toco. Arréglalo o conecta a mano.',
  'desktop.agenti-altre-righe': 'y {n} líneas más',
  'desktop.agenti-test-non-rilanciati': 'Dice que los tests pasan, pero después de su último cambio no los ha vuelto a ejecutar.',
  'desktop.agenti-test-non-lanciati': 'Dice que los tests pasan, pero en este turno no lo he visto ejecutarlos.',
  'desktop.agenti-test-toccati': 'Ha modificado los tests ({file}) mientras fallaban: comprueba que no los haya hecho más fáciles.',
  // collegamento.mjs: Lode iniciada desde el código (icono, arranque al encender, permisos del Mac)
  'desktop.permesso-audio-computer': 'Lode escucha el audio del ordenador solo cuando transcribes una videoclase. El audio nunca se queda en el ordenador: en la nota va solo el texto.',
  'desktop.permesso-microfono': 'Lode usa el micrófono cuando le hablas, para «Repite» en clase y para transcribir las clases que elijas. El audio nunca se queda en el ordenador.',
  'desktop.icona-non-creata': 'no puedo crear {file}',
};
