// El registro en el vault (español): las líneas del diario del proyecto, la tabla «Cosa so davvero» y la
// sección «Informatica» de Lode/Memoria.md. Los títulos de las secciones («## Cosa ho capito», «## Cosa so davvero», «## Informatica»),
// las propiedades y las marcas %% lode:… %% NO están aquí: son nombres del vault, que el código vuelve a buscar.
export default {
  'diario.concetto-for': 'Bucle for',
  'diario.concetto-while': 'Bucle while',
  'diario.concetto-do-while': 'Bucle do-while',
  'diario.concetto-ritroso': 'Cuenta atrás',
  'diario.concetto-array': 'Arrays',
  'diario.concetto-divisione-intera': 'División entera',
  'diario.concetto-resto': 'Resto con negativos',
  'diario.concetto-cast': 'Cast a double',
  'diario.concetto-incremento': 'i++ y ++i',
  'diario.concetto-switch': 'switch y break',
  'diario.concetto-cortocircuito': '&& y || en cortocircuito',
  'diario.concetto-else-pendente': 'else colgante',
  'diario.concetto-puntatori': 'Paso por referencia (punteros)',
  'diario.concetto-parametri': 'Paso por valor',
  'diario.concetto-visibilita': 'Variables dentro de bloques',
  'diario.concetto-char': 'char y códigos ASCII',
  'diario.concetto-ricorsione': 'Recursividad',
  'diario.concetto-annidati': 'Bucles anidados',
  'diario.concetto-break-continue': 'break y continue',
  'diario.concetto-ternario': 'Operador ternario',
  'diario.concetto-printf': 'printf y formatos',
  'diario.elenco-e': '{prima} y {ultimo}',
  'diario.errore-titolo': '«{titolo}»',
  'diario.errore-generico': 'error',
  'diario.passo-dove': '«dónde mirar»',
  'diario.passo-cosa': '«qué significa»',
  'diario.passi-visti': { one: 'visto {passi}', other: 'vistos {passi}' },
  'diario.funzione-nuova': 'nueva {nome}',
  'diario.funzione-nuova-in': 'nueva {nome} en {file}',
  'diario.funzione-cambiata': 'cambiada {nome}',
  'diario.funzione-cambiata-in': 'cambiada {nome} en {file}',
  'diario.funzione-tolta': 'eliminada {nome}',
  'diario.funzione-tolta-in': 'eliminada {nome} en {file}',
  'diario.file-nuovo': 'nuevo {file}',
  'diario.file-tolto': 'eliminado {file}',
  'diario.cambiati-file': { one: '{n} archivo cambiado', other: '{n} archivos cambiados' },
  'diario.cambiato-codice': 'Código cambiado',
  'diario.altre-modifiche': { one: 'y {n} cambio más', other: 'y {n} cambios más' },
  'diario.chi-ha-scritto': 'quién lo escribió: no lo sé',
  'diario.cambiato-durante': 'el código cambió durante la prueba',
  'diario.prova-non-compila': 'Prueba: ✗ no compila',
  'diario.prova-non-compila-errore': 'Prueba: ✗ no compila, {errore}',
  'diario.prova-non-partita': 'Prueba: no arrancó',
  'diario.prova-ok': 'Prueba: ✓ compila · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} pruebas',
  'diario.nessun-caso': 'ningún caso de prueba',
  'diario.ma-cambiato': 'pero el código cambió durante la prueba',
  'diario.codice-provato': 'código probado',
  'diario.prova-ko': 'Prueba: ✗ compila · {ok}/{tot} pruebas',
  'diario.n-prove': { one: '{n} prueba', other: '{n} pruebas' },
  'diario.nessuna-prova': 'ninguna prueba',
  'diario.errori-risolti': { one: '{n} error resuelto', other: '{n} errores resueltos' },
  'diario.n-errori': { one: '{n} error', other: '{n} errores' },
  'diario.n-risolti': { one: '{n} resuelto', other: '{n} resueltos' },
  'diario.correzioni-viste': 'correcciones vistas: {n}',
  'diario.oggi': 'Hoy: {parti}',
  'diario.ultima-non-provata': 'último cambio sin probar',
  'diario.smette': 'Lode deja de seguir {progetto}',
  'diario.segue': 'Lode sigue {progetto}',
  'diario.errore': 'Error: {errore}',
  'diario.correzione-vista': 'Corrección vista: {errore}',
  'diario.spiegate': 'Explicadas: {spiegate} de {totale}',
  'diario.spiegate-rivedere': 'Explicadas: {spiegate} de {totale}; para revisar: {nomi}',
  'diario.ieri': 'ayer',
  'diario.giorni-fa': { one: 'hace {n} día', other: 'hace {n} días' },
  'diario.stato-da-rifare': 'para repetir',
  'diario.stato-sicuro': 'seguro',
  'diario.stato-mai-fatto': 'nunca hecho',
  'diario.diari-dei-progetti': 'Diarios de los proyectos:',
  'diario.tabella-nota': 'Cuentas de Lode sobre los ejercicios «¿Qué imprime?», sin IA. «Para repetir» quiere decir que toca repasarlo.',
  'diario.tabella-testa': '| Tema | Ejercicios | A la primera | Última vez | Estado |',
  'diario.nessun-esercizio': 'Todavía ningún ejercicio. Escribe «qué imprime» en la barra: son 5 preguntas de un minuto.',
  'diario.errori-frequenti': 'Errores que más te encuentras: {errori}.',
  'diario.sbagli-spesso': 'Fallas a menudo: {sbagli}.',
  'diario.memoria-stampa': { one: '«¿Qué imprime?»: {n} ejercicio, {giuste}% correctos a la primera.', other: '«¿Qué imprime?»: {n} ejercicios, {giuste}% correctos a la primera.' },
  'diario.da-rifare': 'Para repetir: {argomenti}.',
};
