// «Listo para la defensa» (español): los estados de las funciones, los puntos encontrados en el código y la tarjeta.
// Las palabras que reconocen la explicación del estudiante (controlla() en js/codice/discussione.js) NO están aquí.
export default {
  'discussione.data-breve': '{g}/{m}',
  'discussione.stato-agente': 'cambió mientras trabajaba el agente · nunca explicada',
  'discussione.stato-mai': 'nunca explicada',
  'discussione.stato-cambiata': 'cambió después de la última vez que la explicaste',
  'discussione.stato-rivedere': { one: 'para revisar · te saltaste un punto', other: 'para revisar · te saltaste {n} puntos' },
  'discussione.stato-spiegata': 'explicada el {data}',
  'discussione.spiegata-adesso': 'explicada ahora',
  'discussione.punto-parametri-breve': 'los parámetros',
  'discussione.punto-parametri': 'los parámetros ({nomi})',
  'discussione.punto-niente': 'que no recibe nada',
  'discussione.punto-chiama': 'que llama a `{nome}`',
  'discussione.punto-ciclo-breve': 'el bucle',
  'discussione.punto-ciclo': 'que hay un bucle',
  'discussione.punto-ricorsiva-breve': 'que es recursiva',
  'discussione.punto-ricorsiva': 'que es recursiva: se llama a sí misma',
  'discussione.punto-restituisce-breve': 'qué devuelve',
  'discussione.punto-restituisce-niente': 'que no devuelve nada',
  'discussione.punto-restituisce-valore': 'que devuelve un valor',
  'discussione.punto-restituisce-tipo': 'que devuelve un `{tipo}`',
  'discussione.file-non-arrivato': 'el archivo no llegó',
  'discussione.nota': 'Lode no sabe quién escribió las líneas: «mientras trabajaba el agente» quiere decir que el archivo cambió durante uno de sus turnos. Lode no te explica el código: solo comprueba que tú lo sepas explicar.',
  'discussione.hai-detto': 'Dijiste: {punti}.',
  'discussione.nessun-punto': 'No encuentro ninguno de los puntos que veo en el código.',
  'discussione.hai-saltato': 'Te saltaste: {punti}.',
  'discussione.tutti-i-punti': 'Tocaste todos los puntos que encuentro en el código.',
  'discussione.la-so-spiegare': 'La sé explicar',
  'discussione.proviamo': 'Probemos',
  'discussione.titolo': 'Listo para la defensa',
  'discussione.intro': 'Las funciones que cambiaron desde que sigues el proyecto. Primero las que cambiaron mientras trabajaba un agente y que nunca explicaste.',
  'discussione.diario-spento': 'Diario apagado: no apunto nada.',
  'discussione.spiegate': 'Explicadas: {spiegate} de {totale}',
  'discussione.nessuna-funzione': 'No veo funciones que hayan cambiado en {nome} desde que lo sigues. Cuando cambien, las encontrarás aquí.',
  'discussione.lingua-sconosciuta': 'Para este lenguaje no sé comprobar: marca tú si la sabes explicar.',
  'discussione.leggo-il-file': 'Leyendo el archivo…',
  'discussione.file-lungo': '{file} tiene {n} líneas: con más de 2000 no lo leo. Marca tú si la sabes explicar.',
  'discussione.non-riesco-leggere': 'No puedo leer {file}: {errore}',
  'discussione.non-trovo-piu': 'Ya no encuentro <code>{nome}</code> en {file}: quizá la renombraste o la quitaste.',
  'discussione.togli': 'Quitar de la lista',
  'discussione.spiegala': '<code>{firma}</code> · {file}, línea {riga}. Explícala como en la defensa: qué recibe, qué devuelve, cómo funciona. El código te lo enseño después.',
  'discussione.aria-spiegazione': 'Tu explicación de {nome}',
  'discussione.ho-finito': 'He terminado',
  'discussione.alla-buona': 'Los puntos los busca el código, a grandes rasgos: no dice si la explicación es correcta.',
};
