// Los errores del compilador y de los programas (js/errori.js), en español.
// Las claves «errori.<entrada>.<campo>» son los textos de cada entrada del diccionario: etiqueta, breve, frase, dónde, qué, concepto.
// Los mensajes del compilador citados se quedan en inglés, como los imprime el compilador.
export default {
  'errori.for-punto-e-virgola.etichetta': 'el `for` con comas',
  'errori.for-punto-e-virgola.frase': 'las tres partes del `for` se separan con `;`',
  'errori.for-punto-e-virgola.dove': `Mira el \`for\` {allaRiga}: entre los paréntesis tiene que haber dos \`;\`.`,
  'errori.for-punto-e-virgola.cosa': 'El `for` tiene tres partes: inicio, condición y paso, como en `for (i = 0; i < n; i++)`. Se separan con `;`, no con `,`. Con comas el compilador ve una sola parte.',
  'errori.for-punto-e-virgola.concetto': 'bucle for',
  'errori.punto-e-virgola.etichetta': 'falta `;`',
  'errori.punto-e-virgola.breve': 'falta ;',
  'errori.punto-e-virgola.frase': 'falta un `;`',
  'errori.punto-e-virgola.dove': `Mira el final de la línea {riga}, la de antes de la {riga2}: ahí falta el \`;\`. El compilador solo se da cuenta cuando lee la línea siguiente.`,
  'errori.punto-e-virgola.dove-2': `Mira el final de la línea {riga}{colonna}: ahí falta el \`;\`.`,
  'errori.punto-e-virgola.dove-3': `Mira el final de la línea {riga} y el de la línea anterior: a veces el compilador solo se da cuenta en la línea siguiente.`,
  'errori.punto-e-virgola.dove-4': 'Mira el final de las instrucciones cerca del punto indicado.',
  'errori.punto-e-virgola.cosa': `En {L} cada instrucción termina con \`;\`, como una frase termina con un punto. Sin él, el compilador pega la instrucción a la siguiente y ya no entiende qué querías decir. Por eso a veces el error aparece en la línea siguiente.`,
  'errori.punto-e-virgola.concetto': 'final de las instrucciones',
  'errori.include-mancante.etichetta': 'falta un `#include`',
  'errori.include-mancante.breve': `falta #include{h}`,
  'errori.include-mancante.frase-2': 'esta función',
  'errori.include-mancante.frase': `para usar {nome} falta \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'esta función',
  'errori.include-mancante.frase-3': `para usar {nome} falta un \`#include\``,
  'errori.include-mancante.dove-2': `: falta la de \`<{h}>\``,
  'errori.include-mancante.dove': `Mira arriba del todo en el archivo, donde están las líneas \`#include\`{h}.`,
  'errori.include-mancante.cosa': '`bool`, `true` y `false` no vienen de serie en C: llegan con `{h}`.',
  'errori.include-mancante.cosa-3': 'Este nombre',
  'errori.include-mancante.cosa-4': `, es decir, \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome} no lo escribes tú: está en la biblioteca estándar de C. Para usarlo tienes que incluir el archivo que lo describe (el header){h}. Sin \`#include\` el compilador no sabe que existe ni cómo se usa.`,
  'errori.include-mancante.cosa-5': ' Con `math.h`, en Linux añade también `-lm` al final del comando de compilación.',
  'errori.include-mancante.concetto': 'bibliotecas e #include',
  'errori.funzione-non-dichiarata.etichetta': 'función no declarada',
  'errori.funzione-non-dichiarata.breve-2': 'función',
  'errori.funzione-non-dichiarata.breve': `{nome} no declarada`,
  'errori.funzione-non-dichiarata.frase': `usas la función {nome} antes de declararla`,
  'errori.funzione-non-dichiarata.dove': `Busca dónde escribes la función {nome}: si está debajo de la línea {riga}, ahí el compilador todavía no la conoce. Comprueba también que el nombre esté escrito exactamente igual.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Busca dónde escribes la función {nome}: si está debajo de la línea del error, ahí el compilador todavía no la conoce. Comprueba también que el nombre esté escrito exactamente igual.`,
  'errori.funzione-non-dichiarata.cosa': 'El compilador lee el archivo de arriba abajo. Si llamas a una función que todavía no ha visto, no sabe qué parámetros quiere ni qué devuelve: los compiladores recientes se detienen, los más antiguos intentan adivinar y a menudo se equivocan. Mueve la función encima de `main`, o escribe encima de `main` su prototipo: la primera línea de la función seguida de `;`.',
  'errori.funzione-non-dichiarata.concetto': 'prototipos de las funciones',
  'errori.non-dichiarato.etichetta': 'nombre no declarado',
  'errori.non-dichiarato.breve-2': 'nombre',
  'errori.non-dichiarato.breve': `{nome} no declarado`,
  'errori.non-dichiarato.frase': `usas {nome} pero no está declarado`,
  'errori.non-dichiarato.frase-2': 'usas un nombre que no está declarado',
  'errori.non-dichiarato.dove': `El compilador propone {s}: comprueba si querías escribir eso. `,
  'errori.non-dichiarato.dove-3': 'este nombre',
  'errori.non-dichiarato.dove-2': `Busca dónde declaras {nome}: quizá tiene otro nombre (una letra distinta, mayúsculas y minúsculas), o está declarado dentro de otro bloque \`{ }\`.`,
  'errori.non-dichiarato.cosa': 'El método que llamas no existe con ese nombre y con esos tipos de argumentos. Comprueba cómo está escrito y que esté en la clase correcta. ',
  'errori.non-dichiarato.cosa-2': 'Antes de usar una variable tienes que declararla, es decir, escribir su tipo y su nombre (por ejemplo `int cuenta = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'Una variable declarada dentro de `{ }` solo existe ahí dentro: fuera del bloque el compilador ya no la ve. También cuenta el orden: la declaración tiene que estar encima de la línea que la usa.',
  'errori.non-dichiarato.concetto': 'declaración y ámbito de las variables',
  'errori.formato.etichetta': 'formato de printf o scanf incorrecto',
  'errori.formato.frase': `el formato espera un {atteso} pero pasas un {dato}`,
  'errori.formato.frase-2': 'el formato no corresponde al valor que pasas',
  'errori.formato.dove': `Mira la línea {riga}: compara cada \`%\` de la cadena con el valor en la misma posición.`,
  'errori.formato.dove-senza-riga': `Mira la línea indicada: compara cada \`%\` de la cadena con el valor en la misma posición.`,
  'errori.formato.cosa': 'En `scanf` cada `%` espera la dirección de una variable del tipo correcto: `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → array de `char`. Si el tipo no corresponde, el valor leído se guarda mal.',
  'errori.formato.cosa-2': ` Para un {dato} en \`scanf\` se usa {p}.`,
  'errori.formato.cosa-3': '`printf` no sabe de qué tipo son los valores: se fía de la cadena de formato. `%d` es para los `int`, `%f` para los `double`, `%c` para los `char`, `%s` para las cadenas. Si el formato no corresponde al valor, imprime números sin sentido.',
  'errori.formato.cosa-4': ' Para un `unsigned long` se usa `%lu`; si es el resultado de `strlen` o `sizeof` (un `size_t`) se usa `%zu`.',
  'errori.formato.cosa-5': ` Para un {dato} en \`printf\` se usa {p}.`,
  'errori.formato.concetto': 'printf, scanf y los formatos',
  'errori.scanf-e-commerciale.etichetta': 'falta `&` en scanf',
  'errori.scanf-e-commerciale.breve': 'falta & en scanf',
  'errori.scanf-e-commerciale.frase': '`scanf` necesita la dirección de la variable: falta `&`',
  'errori.scanf-e-commerciale.dove': `Mira el \`scanf\` {allaRiga}: hay una variable sin \`&\` delante.`,
  'errori.scanf-e-commerciale.cosa': '`scanf` tiene que escribir dentro de tu variable, así que necesita saber dónde está en memoria: su dirección, que se obtiene con `&`. Se escribe `scanf("%d", &n);`. Los arrays de `char` (las cadenas) son la excepción: su nombre ya es una dirección, así que sin `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf y direcciones',
  'errori.return-mancante.etichetta': 'falta el `return`',
  'errori.return-mancante.breve': 'falta el return',
  'errori.return-mancante.frase-2': `la función {nome}`,
  'errori.return-mancante.frase-3': 'la función',
  'errori.return-mancante.frase-4': 'en algunos casos ',
  'errori.return-mancante.frase': `{p} {sigla}llega al final sin \`return\``,
  'errori.return-mancante.dove': `Mira la \`}\` {allaRiga}: es el final de la función{p}. Sigue cada camino posible (cada \`if\` y \`else\`) y comprueba que termine con un \`return\`.`,
  'errori.return-mancante.cosa-2': ` (aquí devuelve {tipo})`,
  'errori.return-mancante.cosa': `Una función que no es \`void\`{tipo} promete devolver un valor. Si llega a la \`}\` final sin \`return\`, quien la llama recibe un valor basura. Pasa a menudo con un \`if\` que tiene su \`return\` pero sin un \`else\`.`,
  'errori.return-mancante.concetto': 'return en las funciones',
  'errori.assegnamento-in-condizione.etichetta': '`=` en lugar de `==`',
  'errori.assegnamento-in-condizione.breve': '= en lugar de ==',
  'errori.assegnamento-in-condizione.frase': 'en la condición hay `=` (asigna) en lugar de `==` (compara)',
  'errori.assegnamento-in-condizione.dove': `Mira la condición {allaRiga}{colonna}.`,
  'errori.assegnamento-in-condizione.cosa': '`=` guarda un valor en la variable; `==` comprueba si dos valores son iguales. `if (x = 5)` asigna 5 a `x` y siempre es verdadero, porque 5 no es cero. Para comparar hace falta `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'asignación y comparación',
  'errori.confronto-stringhe.etichetta': 'cadenas comparadas con `==`',
  'errori.confronto-stringhe.frase': 'comparas cadenas con `==`',
  'errori.confronto-stringhe.dove': `Mira la comparación {allaRiga}.`,
  'errori.confronto-stringhe.cosa': 'En C, `==` entre dos cadenas compara las direcciones, no las letras: casi siempre da falso aunque el texto sea igual. Para comparar el texto se usa `strcmp(a, b) == 0`, de `{h}`. Si en cambio querías un solo carácter, escríbelo entre comillas simples: `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'cadenas en C',
  'errori.puntatore-intero.etichetta': 'comparación entre puntero y entero',
  'errori.puntatore-intero.frase': 'comparas una dirección (un puntero) con un número o un carácter',
  'errori.puntatore-intero.dove': `Mira los dos lados de la comparación {allaRiga}.`,
  'errori.puntatore-intero.cosa': 'En un lado hay un puntero (una dirección, por ejemplo una cadena), en el otro un número o un carácter. Un error típico: `"a"` entre comillas dobles es una cadena, `\'a\'` entre comillas simples es un carácter. Para comprobar un carácter escribe `s[0] == \'a\'`; para comparar dos cadenas usa `strcmp`.',
  'errori.puntatore-intero.concetto': 'caracteres, cadenas y punteros',
  'errori.puntatori-incompatibili.etichetta': 'punteros de distinto tipo',
  'errori.puntatori-incompatibili.frase': `usas un {dato} donde hace falta un {atteso}`,
  'errori.puntatori-incompatibili.frase-2': 'usas un puntero de un tipo donde hace falta otro',
  'errori.puntatori-incompatibili.dove': `Mira la línea {riga}: compara el tipo de lo que pasas (o asignas) con el tipo que hace falta.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Mira la línea indicada: compara el tipo de lo que pasas (o asignas) con el tipo que hace falta.`,
  'errori.puntatori-incompatibili.cosa': 'Un puntero lleva consigo el tipo de aquello a lo que apunta: un `int *` apunta a enteros, un `char *` a caracteres. Usar uno en lugar del otro suele querer decir que te equivocaste de variable, o de tipo en la declaración o en el parámetro de la función.',
  'errori.puntatori-incompatibili.concetto': 'punteros',
  'errori.intero-puntatore.etichetta': 'número y dirección mezclados',
  'errori.intero-puntatore.frase': 'mezclas un número y una dirección (un puntero)',
  'errori.intero-puntatore.dove': `Mira la línea {riga}: en un lado hay un puntero, en el otro un valor normal.`,
  'errori.intero-puntatore.dove-senza-riga': `Mira la línea indicada: en un lado hay un puntero, en el otro un valor normal.`,
  'errori.intero-puntatore.cosa': 'Un puntero contiene una dirección de memoria, no un número cualquiera. Si quieres la dirección de una variable escribe `&x`; si quieres el valor al que apunta un puntero escribe `*p`.',
  'errori.intero-puntatore.cosa-2': ' Aquí el compilador sugiere `&`.',
  'errori.intero-puntatore.cosa-3': ' Aquí el compilador sugiere `*`.',
  'errori.intero-puntatore.cosa-4': ' Cuidado: `"a"` entre comillas dobles es una cadena; un carácter se escribe entre comillas simples: `\'a\'`.',
  'errori.intero-puntatore.concetto': 'punteros',
  'errori.variabile-non-usata.etichetta': 'variable sin usar',
  'errori.variabile-non-usata.breve-2': 'variable',
  'errori.variabile-non-usata.breve': `{nome} sin usar`,
  'errori.variabile-non-usata.frase-2': 'una variable',
  'errori.variabile-non-usata.frase': `{nome} está declarada pero nunca la usas`,
  'errori.variabile-non-usata.dove': `Mira la declaración {allaRiga}.`,
  'errori.variabile-non-usata.cosa': 'Es solo un aviso: el programa compila igual. Pero a menudo quiere decir que olvidaste usarla, o que en su lugar usas por error otra variable con un nombre parecido. Si no hace falta, quítala.',
  'errori.variabile-non-usata.concetto': 'variables',
  'errori.parametro-non-usato.etichetta': 'parámetro sin usar',
  'errori.parametro-non-usato.frase': `el parámetro {nome} nunca se usa`,
  'errori.parametro-non-usato.dove': `Mira la primera línea de la función {allaRiga}.`,
  'errori.parametro-non-usato.cosa': 'La función recibe este valor pero no lo usa. A veces está bien (por ejemplo `argc` y `argv` en `main`); otras veces quiere decir que en su lugar usas otra variable.',
  'errori.parametro-non-usato.concetto': 'parámetros de las funciones',
  'errori.non-inizializzata.etichetta': 'variable sin valor',
  'errori.non-inizializzata.breve-2': 'variable',
  'errori.non-inizializzata.breve': `{nome} sin valor`,
  'errori.non-inizializzata.frase-2': 'una variable',
  'errori.non-inizializzata.frase': `usas {nome} antes de darle un valor`,
  'errori.non-inizializzata.dove-2': 'esta variable',
  'errori.non-inizializzata.dove-3': ` (línea {dichiarata})`,
  'errori.non-inizializzata.dove': `Mira {laRiga}, luego sube hasta la declaración de {nome}{dichiarata}: ¿hay algún camino en el que nunca recibe un valor?`,
  'errori.non-inizializzata.cosa': 'En Java una variable local tiene que recibir un valor antes de leerla, en todos los caminos posibles (también cuando un `if` es falso). Dale un valor inicial en la declaración, por ejemplo `int suma = 0;`.',
  'errori.non-inizializzata.cosa-2': 'Una variable local recién declarada contiene un valor basura, el que quedó en memoria. Antes de leerla tienes que darle un valor, por ejemplo `int suma = 0;`. Pasa mucho con las sumas y los contadores.',
  'errori.non-inizializzata.concetto': 'inicialización de las variables',
  'errori.riferimento-non-definito.etichetta': 'función nunca definida (enlazador)',
  'errori.riferimento-non-definito.breve': 'falta main',
  'errori.riferimento-non-definito.breve-3': 'función',
  'errori.riferimento-non-definito.breve-2': `{nome} no definida`,
  'errori.riferimento-non-definito.frase': 'falta la función `main`',
  'errori.riferimento-non-definito.frase-2': `no se encuentra {nome}: falta \`-lm\` en el comando`,
  'errori.riferimento-non-definito.frase-4': 'una función',
  'errori.riferimento-non-definito.frase-3': `{nome} se usa pero no encuentro dónde está escrita`,
  'errori.riferimento-non-definito.dove': 'Comprueba que uno de los archivos tenga `int main(void)` (o `int main(int argc, char *argv[])`) escrito exactamente así, y que ese archivo esté en el comando de compilación.',
  'errori.riferimento-non-definito.dove-2': 'Mira el comando de compilación: al final hace falta `-lm`.',
  'errori.riferimento-non-definito.dove-4': 'esta función',
  'errori.riferimento-non-definito.dove-3': `El enlazador (linker) no indica una línea. Busca en el proyecto el cuerpo de {nome}, es decir, la versión con las \`{ }\`: el nombre tiene que ser idéntico (mayúsculas incluidas) y el archivo que la contiene tiene que estar en el comando de compilación.`,
  'errori.riferimento-non-definito.cosa': 'Todo programa en C empieza por `main`. Si falta, o está escrita con otro nombre (`Main`, `mian`), no hay un punto desde el que empezar. En Windows el mensaje a veces habla de `WinMain`: es el mismo problema.',
  'errori.riferimento-non-definito.cosa-2': 'Las funciones de `{h}` están en una biblioteca aparte. En Linux (y a veces con MinGW) hay que añadir `-lm` al final del comando: `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'La compilación tiene dos fases: primero cada archivo `.c` se traduce por separado, luego el enlazador (linker) los une. El prototipo le dice al compilador que la función existe, pero el enlazador no ha encontrado su cuerpo en ninguna parte. Normalmente el nombre está escrito distinto, falta un archivo en el comando o la función nunca se escribió.',
  'errori.riferimento-non-definito.concetto': 'compilación y enlazador',
  'errori.definizione-multipla.etichetta': 'definido dos veces (enlazador)',
  'errori.definizione-multipla.breve-2': 'nombre',
  'errori.definizione-multipla.breve': `{nome} definido dos veces`,
  'errori.definizione-multipla.frase-2': 'un nombre',
  'errori.definizione-multipla.frase': `{nome} está definido dos veces en el programa`,
  'errori.definizione-multipla.dove-2': 'este nombre',
  'errori.definizione-multipla.dove': `Busca {nome} en todos los archivos del proyecto. A menudo es una variable o una función escrita dentro de un archivo \`.h\` incluido por varios archivos \`.c\`, o un archivo \`.c\` incluido con \`#include\`.`,
  'errori.definizione-multipla.cosa': 'Cada función y cada variable global tiene que tener una sola definición en todo el programa. En los archivos `.h` van solo los prototipos (y las variables con `extern`); los cuerpos de las funciones van en los `.c`. Un archivo `.c` no se incluye con `#include`.',
  'errori.definizione-multipla.concetto': 'archivos .h y .c',
  'errori.tipi-in-conflitto.etichetta': 'declaraciones distintas',
  'errori.tipi-in-conflitto.frase-2': 'una función',
  'errori.tipi-in-conflitto.frase': `{nome} está declarada de dos formas distintas`,
  'errori.tipi-in-conflitto.dove-3': ` (línea {prima})`,
  'errori.tipi-in-conflitto.dove': `Compara la línea {riga} con la declaración anterior{prima}: el tipo devuelto y los parámetros tienen que ser idénticos.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Compara la línea indicada con la declaración anterior{prima}: el tipo devuelto y los parámetros tienen que ser idénticos.`,
  'errori.tipi-in-conflitto.dove-5': 'la función',
  'errori.tipi-in-conflitto.dove-4': ` Aquí la primera declaración es implícita: llamaste a {nome} antes de declararla. Pon el prototipo encima de \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'El prototipo (la línea con `;`, normalmente arriba o en un `.h`) y la función de verdad tienen que decir lo mismo: mismo tipo devuelto, mismos tipos de parámetros, en el mismo orden.',
  'errori.tipi-in-conflitto.concetto': 'prototipos de las funciones',
  'errori.argomenti.etichetta': 'número de argumentos incorrecto',
  'errori.argomenti.frase': ` ({h} en lugar de {e})`,
  'errori.argomenti.frase-2': `pasas menos argumentos de los que la función espera{quanti}`,
  'errori.argomenti.frase-3': `pasas más argumentos de los que la función espera{quanti}`,
  'errori.argomenti.frase-5': 'esta función',
  'errori.argomenti.frase-4': `la llamada a {nome} no corresponde a sus parámetros`,
  'errori.argomenti.dove-2': ` (línea {dich})`,
  'errori.argomenti.dove': `Compara la llamada {allaRiga} con la primera línea de la función{nome}{dich}: cuenta los argumentos y mira sus tipos.`,
  'errori.argomenti.cosa': 'Una función se llama con tantos argumentos como parámetros tiene, en el mismo orden. Si la función es `int suma(int a, int b)`, la llamada es `suma(x, y)`.',
  'errori.argomenti.concetto': 'parámetros de las funciones',
  'errori.graffa.etichetta': 'falta una llave',
  'errori.graffa.frase': 'sobra una `}`',
  'errori.graffa.frase-2': 'falta una `}`',
  'errori.graffa.dove': `Mira la \`}\` {allaRiga}: cierra un bloque que ya estaba cerrado. Cuenta las \`{\` y las \`}\` de arriba.`,
  'errori.graffa.dove-3': ` (línea {riga})`,
  'errori.graffa.dove-4': ` La \`{\` que quedó abierta está en la línea {aperta}.`,
  'errori.graffa.dove-2': `El compilador solo se da cuenta al final{riga}, pero la llave falta antes.{aperta} Cuenta las \`{\` y las \`}\` de cada función, de cada \`if\` y de cada bucle.`,
  'errori.graffa.cosa': 'Cada `{` abre un bloque y cada `}` lo cierra: tienen que estar emparejadas. Con el código bien sangrado (cada bloque un poco a la derecha) la llave que falta se ve enseguida.',
  'errori.graffa.concetto': 'bloques y llaves',
  'errori.parentesi.etichetta': 'falta un paréntesis',
  'errori.parentesi.frase': 'falta un `)`',
  'errori.parentesi.dove-2': `, columna {apertaCol}`,
  'errori.parentesi.dove': `El \`(\` que quedó abierto está en la línea {aperta}{apertaCol}: su \`)\` falta antes del punto señalado {allaRiga}.`,
  'errori.parentesi.dove-3': `Mira la línea {riga} y cuenta los \`(\` y los \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Mira la línea indicada y cuenta los \`(\` y los \`)\`.`,
  'errori.parentesi.cosa': 'Cada `(` tiene que tener su `)`. En las condiciones largas y en las llamadas dentro de otras llamadas es fácil perder uno: cuéntalos de izquierda a derecha.',
  'errori.parentesi.concetto': 'paréntesis',
  'errori.espressione-attesa.etichetta': 'falta un valor',
  'errori.espressione-attesa.frase': 'el compilador esperaba un valor y no lo encontró',
  'errori.espressione-attesa.dove': `Mira {laRiga}{colonna}: ahí falta algo (un número, una variable) o sobra un símbolo. También pasa con comillas sin cerrar en la misma línea.`,
  'errori.espressione-attesa.cosa': 'Después de un `=`, de un operador como `+` o de una coma, el compilador espera un valor. Si encuentra enseguida `;`, `)` u otro símbolo, se detiene.',
  'errori.espressione-attesa.concetto': 'expresiones',
  'errori.ridefinizione.etichetta': 'declarado dos veces',
  'errori.ridefinizione.breve-2': 'nombre',
  'errori.ridefinizione.breve': `{nome} declarado dos veces`,
  'errori.ridefinizione.frase-2': 'un nombre',
  'errori.ridefinizione.frase': `{nome} está declarado dos veces`,
  'errori.ridefinizione.dove': `Las dos declaraciones están en la línea {prima} y en la línea {riga}.`,
  'errori.ridefinizione.dove-4': 'este nombre',
  'errori.ridefinizione.dove-2': `Busca encima de la línea {riga} otra declaración de {nome}.`,
  'errori.ridefinizione.dove-2-senza-riga': `Busca encima de la línea indicada otra declaración de {nome}.`,
  'errori.ridefinizione.cosa': 'En el mismo bloque un nombre se declara una sola vez. Si solo quieres cambiar el valor, escribe `x = 2;` sin el tipo delante.',
  'errori.ridefinizione.concetto': 'declaración de las variables',
  'errori.non-array.etichetta': '`[ ]` sobre algo que no es un array',
  'errori.non-array.frase': 'usas `[ ]` sobre algo que no es un array',
  'errori.non-array.dove': `Mira los corchetes {allaRiga}{colonna}.`,
  'errori.non-array.cosa': 'Los corchetes sirven para tomar un elemento de un array (o de un puntero). Una variable simple, como un `int`, no tiene elementos. Quizá querías usar otra variable, o declararla como array, por ejemplo `int v[10];`.',
  'errori.non-array.concetto': 'arrays',
  'errori.freccia-punto.etichetta': '`.` y `->` intercambiados',
  'errori.freccia-punto.frase': 'con una estructura (no un puntero) se usa `.`, no `->`',
  'errori.freccia-punto.frase-2': 'con un puntero a estructura se usa `->`, no `.`',
  'errori.freccia-punto.frase-3': 'el campo de la estructura se toma de forma incorrecta',
  'errori.freccia-punto.dove': `Mira {laRiga}{colonna}: comprueba cómo está declarada la variable antes del punto o de la flecha.`,
  'errori.freccia-punto.cosa': 'Si tienes la estructura misma (`struct nodo n`), el campo se toma con el punto: `n.val`. Si tienes un puntero a la estructura (`struct nodo *p`), se usa la flecha: `p->val`, que quiere decir `(*p).val`.',
  'errori.freccia-punto.concetto': 'estructuras y punteros',
  'errori.membro-inesistente.etichetta': 'campo que no existe',
  'errori.membro-inesistente.frase-2': 'la estructura',
  'errori.membro-inesistente.frase': `{p} no tiene un campo {m}`,
  'errori.membro-inesistente.frase-3': 'la estructura no tiene este campo',
  'errori.membro-inesistente.dove-2': ` con {m}`,
  'errori.membro-inesistente.dove': `Mira la definición de la estructura{p} y compara los nombres de los campos{m}.`,
  'errori.membro-inesistente.cosa': 'Los campos de una estructura son los que están escritos en su definición, con esos nombres exactos. Un nombre distinto, aunque sea por una sola letra, es otro campo.',
  'errori.membro-inesistente.concetto': 'estructuras',
  'errori.header-non-trovato.etichetta': 'header no encontrado',
  'errori.header-non-trovato.frase-2': 'incluido',
  'errori.header-non-trovato.frase': `no encuentro el archivo {h}`,
  'errori.header-non-trovato.dove': `Mira la línea \`#include\` {allaRiga}.`,
  'errori.header-non-trovato.dove-2': ` Quizá querías {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` solo existe con algunos compiladores antiguos para Windows (Turbo C, Dev-C++): no forma parte del C estándar.',
  'errori.header-non-trovato.cosa': 'Con `#include {sistema}` el compilador busca el archivo entre los del sistema; con `#include {progetto}` lo busca primero en la carpeta del proyecto. Si el nombre está mal aunque sea por una letra, no lo encuentra y se detiene enseguida.',
  'errori.header-non-trovato.concetto': 'bibliotecas e #include',
  'errori.file-sorgente-mancante.etichetta': 'archivo no encontrado',
  'errori.file-sorgente-mancante.frase-2': 'indicado',
  'errori.file-sorgente-mancante.frase': `el compilador no encuentra el archivo {h}`,
  'errori.file-sorgente-mancante.dove': 'Mira el comando de compilación y los nombres de los archivos de la carpeta.',
  'errori.file-sorgente-mancante.cosa': 'El comando nombra un archivo que no está en la carpeta. Comprueba el nombre (mayúsculas, extensión `.c`) y que el comando se ejecute desde la carpeta correcta.',
  'errori.file-sorgente-mancante.concetto': 'compilación',
  'errori.non-assegnabile.etichetta': 'asignación imposible',
  'errori.non-assegnabile.frase': 'no puedes copiar un array (o una cadena) con `=`',
  'errori.non-assegnabile.frase-2': 'a la izquierda de `=` hay algo que no es una variable',
  'errori.non-assegnabile.dove': `Mira lo que está a la izquierda de \`=\` {allaRiga}.`,
  'errori.non-assegnabile.cosa': 'Un array no se copia con `=`. Para una cadena usa `strcpy(destino, "texto");` de `{h}`, o dale el valor al declararla: `char nombre[10] = "texto";`.',
  'errori.non-assegnabile.cosa-2': 'A la izquierda de `=` tiene que haber un sitio donde guardar el valor: una variable, un elemento de array, un campo. No un cálculo como `a + 1`. Si querías comparar, hace falta `==`.',
  'errori.non-assegnabile.concetto': 'asignación',
  'errori.tipo-sconosciuto.etichetta': 'tipo desconocido',
  'errori.tipo-sconosciuto.frase-2': 'este nombre',
  'errori.tipo-sconosciuto.frase': `{nome} no es un tipo que el compilador conozca`,
  'errori.tipo-sconosciuto.dove-2': 'el tipo',
  'errori.tipo-sconosciuto.dove': `Mira {laRiga} y busca más arriba dónde defines {nome}.`,
  'errori.tipo-sconosciuto.cosa': 'En C el tipo `string` no existe (existe en C++ y en otros lenguajes). Una cadena en C es un array de `char`: `char s[50];` o `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Antes de usar un tipo como `Nodo` hay que definirlo, por ejemplo con `typedef struct nodo Nodo;`, encima de la línea que lo usa. Comprueba también mayúsculas y minúsculas.',
  'errori.tipo-sconosciuto.concetto': 'tipos y typedef',
  'errori.virgolette.etichetta': 'cadena sin cerrar',
  'errori.virgolette.frase': 'una cadena no está cerrada: falta `"`',
  'errori.virgolette.dove': `Mira {laRiga}{colonna}: ahí empieza la cadena. Busca dónde debería terminar.`,
  'errori.virgolette.cosa': 'Una cadena empieza y termina con `"` en la misma línea. Si falta la de cierre, el compilador toma como cadena todo el resto de la línea y luego se pierde: por eso los errores que vienen después a menudo desaparecen solos.',
  'errori.virgolette.concetto': 'cadenas',
  'errori.if-vuoto.etichetta': '`;` después de la condición',
  'errori.if-vuoto.frase': `hay un \`;\` justo después de \`{kw}\``,
  'errori.if-vuoto.frase-2': `hay un \`;\` justo después de la condición {if}`,
  'errori.if-vuoto.dove': `Mira la línea {riga}: justo después de \`{kw}\` hay un \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Mira la línea indicada: justo después de \`{kw}\` hay un \`;\`.`,
  'errori.if-vuoto.dove-3': `Mira el final de la línea {riga}: después del \`)\` de la condición hay un \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Mira el final de la línea indicada: después del \`)\` de la condición hay un \`;\`.`,
  'errori.if-vuoto.cosa': 'El `;` justo después de `else` es una instrucción vacía: el `else` controla solo esa. El bloque `{ }` de abajo se ejecuta siempre, también cuando la condición del `if` es verdadera.',
  'errori.if-vuoto.cosa-2': 'El `;` justo después de `do` es una instrucción vacía: el bucle repite solo esa. El bloque `{ }` de abajo no forma parte del bucle.',
  'errori.if-vuoto.cosa-3': 'El `;` justo después de `if (...)` es una instrucción vacía: el `if` controla solo esa. El bloque `{ }` de abajo se ejecuta siempre, sea cual sea la condición. Con `while` es peor: el bucle puede no terminar nunca.',
  'errori.if-vuoto.concetto': 'if y bucles',
  'errori.confronto-inutile.etichetta': 'instrucción que no hace nada',
  'errori.confronto-inutile.frase': 'hay un `==` que no hace nada: quizá querías `=`',
  'errori.confronto-inutile.frase-2': 'esta instrucción no hace nada',
  'errori.confronto-inutile.dove': `Mira {laRiga}{colonna}.`,
  'errori.confronto-inutile.cosa': 'Una comparación sola (`x == 4;`) calcula verdadero o falso y tira el resultado. Si querías darle un valor a la variable hace falta un solo `=`: `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'Un cálculo que no se guarda en una variable, ni se imprime, ni se usa en una condición, se tira. Quizá falta un `=` o una llamada a una función.',
  'errori.confronto-inutile.concetto': 'asignación y comparación',
  'errori.indirizzo-locale.etichetta': 'dirección de una variable local',
  'errori.indirizzo-locale.frase-2': 'una variable local',
  'errori.indirizzo-locale.frase': `devuelves la dirección de {nome}, que desaparece cuando la función termina`,
  'errori.indirizzo-locale.dove': `Mira el \`return\` {allaRiga}.`,
  'errori.indirizzo-locale.cosa': 'Las variables locales solo viven mientras la función se está ejecutando. Devolver su dirección es darle a quien llama un sitio de memoria que ya no existe. Si tienes que devolver un array, créalo con `malloc` (y luego acuérdate de `free`), o haz que te lo pasen como parámetro.',
  'errori.indirizzo-locale.concetto': 'memoria y funciones',
  'errori.segni-diversi.etichetta': 'números con y sin signo',
  'errori.segni-diversi.frase': 'comparas un número con signo y uno sin signo',
  'errori.segni-diversi.dove': `Mira la comparación {allaRiga}.`,
  'errori.segni-diversi.cosa': 'Funciones como `strlen` devuelven un número sin signo (`size_t`). Compararlo con un `int` suele funcionar, pero si el `int` es negativo la comparación falla. Es un aviso: puedes declarar el índice como `size_t`, o guardar la longitud en un `int` antes del bucle.',
  'errori.segni-diversi.concetto': 'tipos enteros',
  'errori.return-void.etichetta': '`return` y `void` en conflicto',
  'errori.return-void.frase': '`return;` sin valor en una función que tiene que devolver uno',
  'errori.return-void.frase-2': 'una función `void` no puede devolver un valor',
  'errori.return-void.dove': `Mira el \`return\` {allaRiga} y la primera línea de la función.`,
  'errori.return-void.cosa': '`void` quiere decir que la función no devuelve nada: ahí solo se escribe `return;` (o nada). Si la función tiene que dar un resultado, en lugar de `void` va el tipo correcto, por ejemplo `int`, y cada `return` tiene que llevar un valor.',
  'errori.return-void.concetto': 'return en las funciones',
  'errori.main-int.etichetta': '`main` no es `int`',
  'errori.main-int.frase': '`main` tiene que devolver `int`',
  'errori.main-int.dove-2': ` (línea {riga})`,
  'errori.main-int.dove': `Mira la línea de \`main\`{riga}.`,
  'errori.main-int.cosa': 'El estándar de C pide `int main(void)`, y al final `return 0;` para decir «todo bien». `void main` solo lo aceptan algunos compiladores antiguos.',
  'errori.main-int.concetto': 'la función main',
  'errori.fuori-array.etichetta': 'índice fuera del array',
  'errori.fuori-array.frase': `usas el índice {i}, pero el array no llega hasta ahí`,
  'errori.fuori-array.frase-2': 'usas un índice fuera del array',
  'errori.fuori-array.dove-2': ` y la declaración del array en la línea {riga}`,
  'errori.fuori-array.dove': `Mira {laRiga}{riga}.`,
  'errori.fuori-array.cosa': 'Un array de N elementos tiene índices de `0` a `N-1`: con `int v[5]` el último es `v[4]`, y `v[5]` ya está fuera. Pasa mucho con un bucle `for (i = 0; i <= 5; i++)` en lugar de `i < 5`.',
  'errori.fuori-array.concetto': 'arrays e índices',
  'errori.argomenti-formato.etichetta': 'los `%` y los valores no cuadran',
  'errori.argomenti-formato.frase': 'en la cadena hay más `%` que valores',
  'errori.argomenti-formato.frase-2': 'pasas más valores que `%` hay en la cadena',
  'errori.argomenti-formato.dove': `Mira la cadena {allaRiga} y cuenta los \`%\` y los valores después de la coma.`,
  'errori.argomenti-formato.cosa': 'Cada `%d`, `%f`, `%c`… en la cadena de `printf` (o `scanf`) toma el valor siguiente, en orden. El número de `%` y el número de valores después de la cadena tienen que ser iguales.',
  'errori.argomenti-formato.concetto': 'printf y los formatos',
  'errori.divisione-zero.etichetta': 'división entre cero',
  'errori.divisione-zero.frase': 'divides entre cero',
  'errori.divisione-zero.dove': `Mira la división {allaRiga}.`,
  'errori.divisione-zero.cosa': 'Dividir un entero entre cero no tiene resultado: normalmente el programa se bloquea. Antes de dividir comprueba que el divisor no sea cero, por ejemplo con `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'división',
  'errori.troppi-inizializzatori.etichetta': 'demasiados valores en el array',
  'errori.troppi-inizializzatori.frase': 'pones más valores de los que caben en el array',
  'errori.troppi-inizializzatori.dove': `Mira la declaración {allaRiga}: compara el tamaño entre \`[ ]\` con cuántos valores hay entre \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'Si un array tiene sitio para 2 valores y entre las llaves escribes 3, el tercero se descarta. Aumenta el tamaño o quita valores. También puedes dejar los corchetes vacíos, `int v[] = {1, 2, 3};`, y el compilador cuenta solo.',
  'errori.troppi-inizializzatori.concetto': 'arrays',
  'errori.operandi.etichetta': 'operación imposible entre estos tipos',
  'errori.operandi.frase': `la operación no se puede hacer entre {a} y {b}`,
  'errori.operandi.frase-2': 'la operación no se puede hacer entre estos dos tipos',
  'errori.operandi.dove': `Mira el operador {allaRiga}{colonna} y los tipos de los dos lados.`,
  'errori.operandi.cosa': 'Los operadores como `&&`, `+` o `<` piden tipos concretos: `&&` trabaja con `boolean`, `<` con números. Las cadenas no se comparan con `<`: se usa `compareTo`, y para la igualdad `equals`.',
  'errori.operandi.cosa-2': 'Los operadores como `+`, `-` y `<` funcionan con números (y algunos con punteros). Dos estructuras no se suman ni se comparan directamente: trabaja con sus campos, por ejemplo `a.x + b.x`. Las cadenas en C no se unen con `+`: se usa `strcat`.',
  'errori.operandi.concetto': 'tipos y operadores',
  'errori.carattere-strano.etichetta': 'carácter raro en el código',
  'errori.carattere-strano.frase': 'en el código hay un carácter raro',
  'errori.carattere-strano.dove': `Mira {laRiga}{colonna}.`,
  'errori.carattere-strano.cosa': 'A menudo es un carácter copiado de un PDF o de una página web: comillas curvas `“ ”`, un apóstrofo curvo, un espacio especial o un guion largo. A simple vista parecen iguales, pero para el compilador no lo son. Vuelve a escribir la línea a mano.',
  'errori.carattere-strano.concetto': 'caracteres en el código',
  'errori.non-sicura.etichetta': 'Visual Studio y las funciones «no seguras»',
  'errori.non-sicura.frase-2': 'esta función',
  'errori.non-sicura.frase': `Visual Studio no acepta {nome}: la considera no segura`,
  'errori.non-sicura.dove': 'No hay nada mal en tu C: es una regla de Visual Studio.',
  'errori.non-sicura.cosa': 'Visual Studio señala `scanf`, `strcpy` y similares porque, mal usadas, pueden escribir más allá del final de un array. El C estándar las permite y las asignaturas las usan. Para quitar el aviso escribe `#define _CRT_SECURE_NO_WARNINGS` como primerísima línea del archivo, antes de los `#include`. Si el profe prefiere `scanf_s`, haz caso al profe.',
  'errori.non-sicura.concetto': 'compiladores distintos',
  'errori.ricorsione-infinita.etichetta': 'recursión sin fin',
  'errori.ricorsione-infinita.frase': 'la función se llama siempre a sí misma: nunca se detiene',
  'errori.ricorsione-infinita.dove': `Mira la función{p} {allaRiga}: busca el caso base, es decir, un \`if\` que devuelve un valor sin volver a llamar a la función.`,
  'errori.ricorsione-infinita.cosa': 'Una función recursiva tiene que tener un caso base, y cada llamada tiene que acercarse a ese caso (por ejemplo con `n - 1`). Aquí todos los caminos llevan a otra llamada: el programa llenará la memoria y se detendrá.',
  'errori.ricorsione-infinita.concetto': 'recursividad',
  'errori.sintassi.etichetta': 'código escrito de una forma que el compilador no entiende',
  'errori.sintassi.frase': 'el compilador no entiende cómo sigue el código aquí',
  'errori.sintassi.dove': `Mira {laRiga} y la anterior: a menudo el problema real está justo encima, por ejemplo un \`;\` de más después de la primera línea de una función, una \`}\` de más o un paréntesis sin cerrar.`,
  'errori.sintassi.cosa': 'El compilador lee el código siguiendo reglas precisas, como la gramática de un idioma. Aquí ha encontrado algo que en ese punto no puede estar. El mensaje original dice qué esperaba.',
  'errori.sintassi.concetto': 'sintaxis',
  'errori.java-tipi.etichetta': 'tipos incompatibles (Java)',
  'errori.java-tipi.frase': `de {dato} a {atteso} se pueden perder datos`,
  'errori.java-tipi.frase-2': `{dato} no se puede usar donde hace falta {atteso}`,
  'errori.java-tipi.frase-3': 'el valor no tiene el tipo que hace falta',
  'errori.java-tipi.dove': `Mira {laRiga}{colonna}: compara el tipo de la variable con el del valor.`,
  'errori.java-tipi.cosa': 'En Java cada variable tiene un tipo y el compilador comprueba que los valores correspondan. De `double` a `int` se pierden los decimales, así que hay que decirlo explícitamente con un cast: `(int) x`. Un `String` no se convierte en número solo: se usa `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'tipos en Java',
  'errori.java-import.etichetta': 'falta un `import` (Java)',
  'errori.java-import.frase-2': 'esta clase',
  'errori.java-import.frase': `para usar {nome} falta un \`import\``,
  'errori.java-import.dove': 'Mira arriba del todo en el archivo, encima de la clase, donde están las líneas `import`.',
  'errori.java-import.cosa-2': 'Esta clase',
  'errori.java-import.cosa-3': `, es decir, \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} está en un paquete de la biblioteca de Java: para usarla hace falta el \`import\` arriba del todo en el archivo{nome2}. Comprueba también mayúsculas y minúsculas.`,
  'errori.java-import.concetto': 'import en Java',
  'errori.java-nome-file.etichetta': 'nombre del archivo y de la clase distintos',
  'errori.java-nome-file.frase-2': 'pública',
  'errori.java-nome-file.frase-3': 'Clase',
  'errori.java-nome-file.frase': `la clase {nome} tiene que estar en el archivo {nome2}`,
  'errori.java-nome-file.dove': 'Mira el nombre del archivo y la línea `public class`.',
  'errori.java-nome-file.cosa': 'En Java una clase `public` tiene que estar en un archivo con el mismo nombre, mayúsculas incluidas: `public class Main` va en `Main.java`. Renombra el archivo o la clase.',
  'errori.java-nome-file.concetto': 'clases y archivos en Java',
  'errori.java-statico.etichetta': 'no static usado desde static',
  'errori.java-statico.frase-2': 'este nombre',
  'errori.java-statico.frase': `{nome} no es \`static\`, pero lo usas desde un método \`static\``,
  'errori.java-statico.dove-2': 'ese nombre',
  'errori.java-statico.dove': `Mira {laRiga} y la declaración de {nome}.`,
  'errori.java-statico.cosa': '`main` es `static`: pertenece a la clase, no a un objeto. Desde ahí solo puedes usar métodos y variables `static`, o crear antes un objeto con `new` y usar ese. En los ejercicios con una sola clase, a menudo al método le falta `static`.',
  'errori.java-statico.concetto': 'static en Java',
  'errori.java-irraggiungibile.etichetta': 'instrucción que nunca se ejecuta',
  'errori.java-irraggiungibile.frase': 'esta instrucción nunca se ejecutará',
  'errori.java-irraggiungibile.dove': `Mira {laRiga} y la línea anterior.`,
  'errori.java-irraggiungibile.cosa': 'Antes de esta línea hay un `return`, un `break`, un `continue` o un bucle que no termina: desde ahí el programa nunca llega aquí. Quítala o muévela antes.',
  'errori.java-irraggiungibile.concetto': 'flujo del programa',
  'errori.java-indice.etichetta': 'índice fuera (Java)',
  'errori.java-indice.frase': `usas el índice {i}, pero la longitud es {l}`,
  'errori.java-indice.frase-2': 'lees una posición que el array (o la cadena) no tiene',
  'errori.java-indice.cosa': 'Los índices empiezan en 0: con longitud 5 van de 0 a 4. Revisa la condición del bucle: a menudo hay `<=` donde hace falta `<`, o se usa `length` como índice.',
  'errori.java-indice.concetto': 'arrays e índices',
  'errori.java-null.etichetta': 'objeto null (Java)',
  'errori.java-null.frase': 'usas un objeto que vale `null`',
  'errori.java-null.cosa': 'El objeto nunca se creó con `new`, o un método devolvió `null`. Las versiones recientes de Java escriben en el mensaje qué variable era `null`.',
  'errori.java-null.concetto': 'objetos y null',
  'errori.java-divisione-zero.etichetta': 'división entre cero (Java)',
  'errori.java-divisione-zero.frase': 'divides un entero entre cero',
  'errori.java-divisione-zero.cosa': 'Dividir un entero entre cero (también con `%`) no tiene resultado y Java se detiene. Antes de la división comprueba el divisor, por ejemplo con `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'división',
  'errori.java-input.etichetta': 'entrada que no es un número (Java)',
  'errori.java-input.frase': `{v} no es un número`,
  'errori.java-input.frase-2': 'el programa esperaba un número y leyó otra cosa',
  'errori.java-input.cosa': 'El programa quería un número y encontró otra cosa: letras, espacios, una línea vacía, o una coma en lugar del punto. Revisa lo que escribes como entrada, o el archivo `.in` de la prueba.',
  'errori.java-input.concetto': 'entrada',
  'errori.java-stack.etichetta': 'recursión sin fin (Java)',
  'errori.java-stack.frase': 'el método se llama a sí mismo demasiadas veces',
  'errori.java-stack.cosa': 'Todo método recursivo necesita un caso base: una condición en la que devuelve un valor sin volver a llamarse. Y cada llamada tiene que acercarse al caso base.',
  'errori.java-stack.concetto': 'recursividad',
  'errori.py-uguale.etichetta': '`=` en lugar de `==`',
  'errori.py-uguale.breve': '= en lugar de ==',
  'errori.py-uguale.frase': 'en la condición hay `=` en lugar de `==`',
  'errori.py-uguale.dove': `Mira la condición {allaRiga}.`,
  'errori.py-uguale.cosa': '`=` guarda un valor en una variable; `==` comprueba si dos valores son iguales. En una condición (`if`, `elif`, `while`) hace falta `==`: `if x == 5:`.',
  'errori.py-uguale.concetto': 'asignación y comparación',
  'errori.py-due-punti.etichetta': 'faltan los `:`',
  'errori.py-due-punti.frase': 'faltan los `:` al final de la línea',
  'errori.py-due-punti.dove': `Mira el final de la línea {riga}.`,
  'errori.py-due-punti.dove-senza-riga': `Mira el final de la línea indicada.`,
  'errori.py-due-punti.cosa': 'En Python `if`, `elif`, `else`, `for`, `while`, `def` y `class` terminan con `:`. Los dos puntos dicen «ahora empieza el bloque», que se escribe debajo, con sangría.',
  'errori.py-due-punti.concetto': 'bloques en Python',
  'errori.py-parentesi.etichetta': 'paréntesis sin cerrar',
  'errori.py-parentesi.frase': `hay un {c} que no cierra nada`,
  'errori.py-parentesi.frase-2': `hay un {p} sin cerrar`,
  'errori.py-parentesi.dove': `Mira {laRiga}: cuenta los paréntesis abiertos y cerrados. Si la línea parece correcta, mira la anterior.`,
  'errori.py-parentesi.cosa': 'Cada `(`, `[` y `{` tiene que tener su cierre del mismo tipo. Si falta uno, Python sigue leyendo las líneas siguientes como si fueran la misma instrucción.',
  'errori.py-parentesi.concetto': 'paréntesis',
  'errori.py-stringa.etichetta': 'cadena sin cerrar',
  'errori.py-stringa.frase': 'una cadena no está cerrada',
  'errori.py-stringa.dove': `Mira {laRiga}: la cadena empieza ahí. Busca dónde falta la comilla de cierre.`,
  'errori.py-stringa.cosa': 'Una cadena empieza y termina con el mismo tipo de comillas, `"` o `\'`, en la misma línea. Si dentro del texto hay un apóstrofo, usa comillas dobles: `"it\'s"`.',
  'errori.py-stringa.concetto': 'cadenas',
  'errori.py-print.etichetta': '`print` sin paréntesis',
  'errori.py-print.frase': '`print` necesita paréntesis',
  'errori.py-print.dove': `Mira {laRiga}.`,
  'errori.py-print.cosa': 'En Python 3 `print` es una función: se escribe `print("hola")`. La forma sin paréntesis era de Python 2, que todavía aparece en ejemplos viejos de internet.',
  'errori.py-print.concetto': 'funciones',
  'errori.py-indentazione.etichetta': 'sangría incorrecta',
  'errori.py-indentazione.frase': 'falta la sangría después de los dos puntos',
  'errori.py-indentazione.frase-2': 'sobra sangría',
  'errori.py-indentazione.frase-3': 'la sangría no cuadra con las líneas de arriba',
  'errori.py-indentazione.frase-4': 'mezclas tabuladores y espacios en la sangría',
  'errori.py-indentazione.frase-5': 'la sangría de la línea es incorrecta',
  'errori.py-indentazione.dove-2': ` El \`{kw}\` está en la línea {l}.`,
  'errori.py-indentazione.dove': `Mira {laRiga} y la de arriba: compara los espacios al principio de la línea.{kw}`,
  'errori.py-indentazione.cosa': 'En Python la sangría (los espacios al principio de la línea) forma parte del código: dice qué líneas están dentro de un `if`, un `for` o una `def`. Después de los `:` la línea de abajo tiene que llevar sangría, y las líneas del mismo bloque tienen que llevar la misma. Usa siempre 4 espacios, sin mezclarlos con tabuladores.',
  'errori.py-indentazione.concetto': 'bloques en Python',
  'errori.py-sintassi.etichetta': 'línea que Python no sabe leer',
  'errori.py-sintassi.frase': 'quizá falta una coma',
  'errori.py-sintassi.frase-2': 'Python no consigue leer esta línea',
  'errori.py-sintassi.dove': `Mira {laRiga}: el signo \`^\` debajo de la línea indica dónde se dio cuenta Python del problema. A menudo el error real está justo antes, incluso en la línea de arriba (un paréntesis o una comilla sin cerrar).`,
  'errori.py-sintassi.cosa': 'Entre dos valores de una lista, de una tupla o de los argumentos de una función hace falta una coma: `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'Python lee el código siguiendo reglas precisas, como la gramática de un idioma. Aquí ha encontrado algo que en ese punto no puede estar. El mensaje original, después de `SyntaxError:`, dice qué no cuadra.',
  'errori.py-sintassi.concetto': 'sintaxis',
  'errori.py-nome.etichetta': 'nombre que no existe',
  'errori.py-nome.breve-2': 'nombre',
  'errori.py-nome.breve': `{nome} no definido`,
  'errori.py-nome.frase-2': 'este nombre',
  'errori.py-nome.frase': `{nome} todavía no existe cuando Python llega a la línea {riga}`,
  'errori.py-nome.frase-senza-riga': `{nome} todavía no existe cuando Python llega a la línea indicada`,
  'errori.py-nome.dove': `Python propone {s}: comprueba si querías escribir eso. `,
  'errori.py-nome.dove-3': 'este nombre',
  'errori.py-nome.dove-2': `Busca dónde le das un valor a {nome}: tiene que estar encima de esta línea y escrito igual, mayúsculas incluidas. Si es una función, la \`def\` tiene que ir antes de la llamada.`,
  'errori.py-nome.cosa': 'En Python un nombre solo existe después de darle un valor (`x = ...`), después de su `def` o después del `import`. Las variables creadas dentro de una función no existen fuera.',
  'errori.py-nome.cosa-2': ' Cuidado: en Python se escribe `True`, `False` y `None`, con mayúscula.',
  'errori.py-nome.cosa-3': ` Si {nome} tenía que ser un texto, faltan las comillas: {nome2}.`,
  'errori.py-nome.concetto': 'variables en Python',
  'errori.py-locale.etichetta': 'variable local sin valor',
  'errori.py-locale.frase-2': 'una variable',
  'errori.py-locale.frase': `usas {nome} dentro de la función antes de darle un valor`,
  'errori.py-locale.dove-2': 'la variable',
  'errori.py-locale.dove': `Mira {laRiga} y busca, en la misma función, dónde asignas {nome}.`,
  'errori.py-locale.cosa': 'Si dentro de una función le asignas un valor a una variable, para Python esa variable pasa a ser local en toda la función, también en las líneas anteriores. Así ya no lee la variable con el mismo nombre que está fuera. Mejor pasar el valor como parámetro y devolver el resultado con `return`.',
  'errori.py-locale.concetto': 'funciones y variables locales',
  'errori.py-tipo-concatena.etichetta': 'texto y número mezclados',
  'errori.py-tipo-concatena.frase': 'mezclas un texto (`str`) y un número',
  'errori.py-tipo-concatena.frase-2': `la operación no se puede hacer entre {a} y {b}`,
  'errori.py-tipo-concatena.dove': `Mira {laRiga}: ¿de qué tipo es cada valor junto al operador?`,
  'errori.py-tipo-concatena.cosa': 'Para Python `"5"` (texto) y `5` (número) son cosas distintas. Para unir texto y número convierte el número: `"Total: " + str(x)`, o usa una f-string: `f"Total: {x}"`. Si el valor viene de `input()`, recuerda que `input()` siempre devuelve texto: para hacer cuentas hace falta `int(input())` o `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'tipos en Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` mal usados',
  'errori.py-tipo-indice.frase': 'el índice tiene que ser un número entero',
  'errori.py-tipo-indice.frase-2': `un valor \`{immut}\` no se puede modificar`,
  'errori.py-tipo-indice.frase-3': 'usas `[ ]` sobre un valor `None`',
  'errori.py-tipo-indice.frase-4': `usas \`[ ]\` sobre un valor de tipo {p}, que no tiene elementos`,
  'errori.py-tipo-indice.dove': `Mira los corchetes {allaRiga}.`,
  'errori.py-tipo-indice.cosa': 'Con `v[i]` la `i` tiene que ser un `int`. Si viene de `input()` es texto: conviértela con `int()`. Si sale de una división con `/` es un `float`: usa `//`.',
  'errori.py-tipo-indice.cosa-2': 'Las cadenas y las tuplas en Python no se cambian: se crea un valor nuevo, por ejemplo `s = "C" + s[1:]`. Si necesitas modificar los elementos, usa una lista.',
  'errori.py-tipo-indice.cosa-3': 'Los corchetes `[ ]` sirven para listas, cadenas, diccionarios y tuplas. Un número no tiene elementos. Si el tipo es `NoneType`, la variable vale `None`: a menudo es el resultado de una función sin `return`.',
  'errori.py-tipo-indice.concetto': 'listas e índices',
  'errori.py-tipo-argomenti.etichetta': 'número de argumentos incorrecto',
  'errori.py-tipo-argomenti.frase-2': 'la función',
  'errori.py-tipo-argomenti.frase': `{p} se llama con un número incorrecto de argumentos`,
  'errori.py-tipo-argomenti.dove': `Compara la llamada {allaRiga} con la línea \`def\` de la función.`,
  'errori.py-tipo-argomenti.cosa': 'Una función se llama con tantos argumentos como parámetros tiene su `def`. En los métodos de una clase el primer parámetro es `self` y Python lo pasa solo: si dice «takes 1 positional argument but 2 were given», quizá falta `self` en la `def`.',
  'errori.py-tipo-argomenti.concetto': 'funciones y parámetros',
  'errori.py-non-iterabile.etichetta': '`for` sobre un número',
  'errori.py-non-iterabile.frase': `intentas recorrer un valor de tipo {p}, que no tiene elementos`,
  'errori.py-non-iterabile.dove': `Mira {laRiga}: ¿qué hay después de \`in\`?`,
  'errori.py-non-iterabile.cosa': 'El `for` recorre los elementos de una lista, de una cadena o de un `range`. Un número no tiene elementos: para repetir n veces se escribe `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'bucles for',
  'errori.py-non-chiamabile.etichetta': '`( )` después de algo que no es una función',
  'errori.py-non-chiamabile.frase': `pones \`( )\` después de un valor de tipo {p}, que no es una función`,
  'errori.py-non-chiamabile.dove': `Mira {laRiga}: ¿qué hay justo antes de los paréntesis?`,
  'errori.py-non-chiamabile.cosa': 'Los paréntesis después de un nombre quieren decir «llama a esta función». A menudo una variable tiene el mismo nombre que una función (por ejemplo `sum = 0` y luego `sum(v)`), o falta un operador: `2(x + 1)` en lugar de `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'funciones',
  'errori.py-tipo.etichetta': 'tipo incorrecto',
  'errori.py-tipo.frase': 'una operación recibe un valor del tipo incorrecto',
  'errori.py-tipo.dove': `Mira {laRiga}: ¿de qué tipo son los valores usados? Puedes imprimirlos con \`print(type(x))\`.`,
  'errori.py-tipo.cosa': 'Cada valor en Python tiene un tipo (`int`, `str`, `list`…) y cada operación acepta solo ciertos tipos. El mensaje original dice qué tipos encontró.',
  'errori.py-tipo.concetto': 'tipos en Python',
  'errori.py-indice.etichetta': 'posición que no existe',
  'errori.py-indice.frase': 'sacas un elemento de una lista vacía',
  'errori.py-indice.frase-stringa': 'estás leyendo una posición que la cadena no tiene',
  'errori.py-indice.frase-tupla': 'estás leyendo una posición que la tupla no tiene',
  'errori.py-indice.frase-lista': 'estás leyendo una posición que la lista no tiene',
  'errori.py-indice.dove': `Mira {laRiga}: ¿cuánto vale el índice en ese momento, y cuántos elementos hay?`,
  'errori.py-indice.cosa': 'Una lista de n elementos tiene las posiciones de `0` a `n-1`: con 3 elementos la última es `v[2]`. Pasa mucho con `range(len(v) + 1)` o con un bucle que da un paso de más. Una lista vacía no tiene ninguna posición: también `v[0]` es un error.',
  'errori.py-indice.concetto': 'listas e índices',
  'errori.py-chiave.etichetta': 'clave que no está',
  'errori.py-chiave.frase': `la clave {k} no está en el diccionario`,
  'errori.py-chiave.frase-2': 'la clave no está en el diccionario',
  'errori.py-chiave.dove': `Mira {laRiga}: ¿cómo está escrita la clave, y cómo están escritas las del diccionario?`,
  'errori.py-chiave.cosa': 'Con `d[k]` la clave tiene que existir ya. Comprueba cómo está escrita (mayúsculas, espacios, número o texto). Para comprobarlo antes: `if k in d:`. Para tener un valor de reserva: `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'diccionarios',
  'errori.py-valore.etichetta': 'valor incorrecto',
  'errori.py-valore.frase': `{v} no se puede convertir en un número`,
  'errori.py-valore.frase-2': 'las variables a la izquierda de `=` no son tantas como los valores',
  'errori.py-valore.frase-3': 'una función matemática recibe un valor que no acepta',
  'errori.py-valore.frase-4': 'el tipo es correcto pero el valor no',
  'errori.py-valore.dove': `Mira {laRiga}: ¿qué valor llega ahí de verdad? Puedes imprimirlo con \`print(repr(x))\`.`,
  'errori.py-valore.cosa': '`int()` convierte en número solo un texto hecho de cifras. Espacios en medio, letras, el texto vacío o un número con coma (`"2,5"`) no sirven. Para los decimales hace falta `float()` y el punto: `"2.5"`. Si lees de `input()` o de un archivo, comprueba qué llega de verdad.',
  'errori.py-valore.cosa-2': 'Con `a, b = valores` el número de variables a la izquierda tiene que ser igual al número de valores a la derecha. A menudo `split()` devuelve más (o menos) trozos de los que esperabas.',
  'errori.py-valore.cosa-3': 'Funciones como `math.sqrt` y `math.log` no aceptan todos los números: nada de raíz de un negativo, nada de logaritmo de cero. Comprueba el valor antes de la llamada.',
  'errori.py-valore.cosa-4': 'El valor tiene el tipo correcto pero no sirve para esa operación. El mensaje original dice qué valor no servía.',
  'errori.py-valore.concetto': 'conversiones y entrada',
  'errori.py-divisione-zero.etichetta': 'división entre cero',
  'errori.py-divisione-zero.frase': 'divides entre cero',
  'errori.py-divisione-zero.dove': `Mira {laRiga}: ¿qué divisor vale 0 en ese momento? A menudo es el \`len()\` de una lista vacía o un contador que se quedó en 0.`,
  'errori.py-divisione-zero.cosa': 'Dividir entre cero no tiene resultado, así que Python se detiene. También vale para `//` y `%`. Antes de la división comprueba el divisor: `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'división',
  'errori.py-attributo.etichetta': 'método o atributo que no existe',
  'errori.py-attributo.frase': `la variable vale \`None\`, así que no tiene {a}`,
  'errori.py-attributo.frase-2': `el módulo {mod} no tiene {a}`,
  'errori.py-attributo.frase-3': `un valor de tipo {p} no tiene {a}`,
  'errori.py-attributo.frase-4': 'ese valor no tiene este atributo',
  'errori.py-attributo.dove': `Mira {laRiga}: ¿qué hay antes del punto, y de qué tipo es?`,
  'errori.py-attributo.cosa': 'Un valor `None` suele venir de una función sin `return`, o de métodos como `v.sort()` que cambian la lista y devuelven `None` (así que `v = v.sort()` pierde la lista).',
  'errori.py-attributo.cosa-2': 'Comprueba cómo está escrito el nombre. Si tu archivo se llama como el módulo (por ejemplo `random.py` o `math.py`), Python importa tu archivo en lugar del módulo de verdad: renómbralo.',
  'errori.py-attributo.cosa-3': 'Cada tipo tiene sus métodos: las listas tienen `append`, `pop`, `sort`; las cadenas tienen `upper`, `split`, `strip`. Comprueba el nombre del método y el tipo de la variable.',
  'errori.py-attributo.concetto': 'métodos y tipos',
  'errori.py-ricorsione.etichetta': 'recursión sin fin',
  'errori.py-ricorsione.frase': 'la función se llama a sí misma demasiadas veces',
  'errori.py-ricorsione.dove': `Mira la función{funzione} {allaRiga}: ¿dónde está el caso base, y cada llamada se acerca a él?`,
  'errori.py-ricorsione.cosa': 'Toda función recursiva necesita un caso base: una condición en la que devuelve un valor sin volver a llamarse. Y cada llamada tiene que acercarse al caso base (por ejemplo `n - 1`, no `n + 1`). Python se detiene después de unas 1000 llamadas una dentro de otra.',
  'errori.py-ricorsione.concetto': 'recursividad',
  'errori.py-modulo.etichetta': 'módulo que no está',
  'errori.py-modulo.frase': `en el módulo {m} no está {nome}`,
  'errori.py-modulo.frase-2': `el módulo {m} no está`,
  'errori.py-modulo.frase-3': 'un módulo no se puede importar',
  'errori.py-modulo.dove': `Mira la línea \`import\` {allaRiga}.`,
  'errori.py-modulo.cosa': 'O el nombre está mal escrito, o el módulo no está instalado para este Python. Los módulos externos (por ejemplo `numpy`) se instalan con `python3 -m pip install nombre` (en Windows `py -m pip install nombre`). Si el módulo es un archivo tuyo, tiene que estar en la misma carpeta y llamarse `nombre.py`.',
  'errori.py-modulo.concetto': 'módulos e import',
  'errori.py-file.etichetta': 'archivo no encontrado',
  'errori.py-file.frase': `no encuentro el archivo {p}`,
  'errori.py-file.dove': `Mira el \`open\` {allaRiga}.`,
  'errori.py-file.cosa': 'Python busca el archivo a partir de la carpeta desde la que ejecutas el programa, no desde la del script. Comprueba el nombre, la extensión (Windows a veces la oculta) y la carpeta.',
  'errori.py-file.concetto': 'archivos',
  'errori.py-input-finito.etichetta': 'entrada terminada',
  'errori.py-input-finito.frase': 'el programa pide una entrada que no llega',
  'errori.py-input-finito.dove': `Mira el \`input()\` {allaRiga}.`,
  'errori.py-input-finito.cosa': '`input()` esperaba una línea, pero la entrada ya se había terminado. En las pruebas con archivos `.in` comprueba que el archivo tenga tantas líneas como `input()` haya.',
  'errori.py-input-finito.concetto': 'entrada',
  'errori.esec-memoria.etichetta': 'memoria que no es suya (segmentation fault)',
  'errori.esec-memoria.breve': 'memoria ajena',
  'errori.esec-memoria.frase': 'el programa ha usado memoria que no es suya',
  'errori.esec-memoria.cosa': 'Aquí el puntero valía `NULL`. ',
  'errori.esec-memoria.cosa-2': 'A menudo es un puntero `NULL` (`p->next` con `p` que vale `NULL`), un índice fuera del array o una recursión sin fin. El sistema detiene el programa para proteger el resto de la memoria.',
  'errori.esec-memoria.cosa-3': ` En Windows este error tiene el código {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'punteros y memoria',
  'errori.esec-divisione-zero.etichetta': 'división entera entre cero',
  'errori.esec-divisione-zero.frase': 'el programa ha dividido un entero entre cero',
  'errori.esec-divisione-zero.cosa': 'Un entero dividido entre cero (también con `%`) no tiene resultado y el sistema detiene el programa. El nombre «floating point exception» engaña: pasa justamente con los enteros. Revisa los divisores, por ejemplo un contador que todavía vale 0.',
  'errori.esec-divisione-zero.concetto': 'división',
  'errori.esec-stack.etichetta': 'pila de llamadas llena (stack overflow)',
  'errori.esec-stack.frase': 'la pila de llamadas está llena: quizá una recursión sin fin',
  'errori.esec-stack.cosa': 'Cada llamada a una función ocupa un poco de memoria en la pila (el stack). Una función recursiva sin caso base, o con un caso base al que nunca llega, la llena. También puede bastar un array local enorme: en ese caso usa `malloc`.',
  'errori.esec-stack.concetto': 'recursividad',
  'errori.esec-fuori-array.etichetta': 'escritura fuera de un array',
  'errori.esec-fuori-array.frase': 'el programa ha leído o escrito fuera de un array',
  'errori.esec-fuori-array.frase-letto': 'el programa ha leído fuera de un array',
  'errori.esec-fuori-array.frase-scritto': 'el programa ha escrito fuera de un array',
  'errori.esec-fuori-array.cosa': 'Un array de N elementos va de `0` a `N-1`. Revisa las condiciones de los bucles (`<` y no `<=`), las cadenas sin sitio para el `\'\\0\'` final y los `malloc` con el tamaño correcto (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'arrays e índices',
  'errori.esec-heap.etichetta': 'malloc y free mal usados',
  'errori.esec-heap.frase': 'la memoria pedida con `malloc` se ha usado mal',
  'errori.esec-heap.cosa': 'Pasa cuando liberas dos veces la misma memoria (`free` dos veces), cuando usas un puntero después de `free`, o cuando escribes más allá del final de un bloque pedido con `malloc`. Después de `free(p);` ayuda escribir `p = NULL;`.',
  'errori.esec-heap.concetto': 'memoria dinámica',
  'errori.esec-memoria-persa.etichetta': 'memoria nunca liberada',
  'errori.esec-memoria-persa.frase': 'el programa pide memoria con `malloc` y no la libera',
  'errori.esec-memoria-persa.cosa': 'Cada `malloc` (o `calloc`) tiene que tener su `free` cuando la memoria ya no hace falta. En las listas hay que liberar cada nodo, uno a uno, antes de perder el puntero.',
  'errori.esec-memoria-persa.concetto': 'memoria dinámica',
  'errori.esec-non-inizializzata.etichetta': 'valor nunca inicializado',
  'errori.esec-non-inizializzata.frase': 'el programa usa un valor que nunca se ha inicializado',
  'errori.esec-non-inizializzata.cosa': 'Una variable local (o la memoria pedida con `malloc`) contiene valores basura hasta que le das un valor. Inicialízala antes de leerla.',
  'errori.esec-non-inizializzata.concetto': 'inicialización de las variables',
  'errori.esec-asserzione.etichetta': 'assert fallido',
  'errori.esec-asserzione.frase': `un \`assert\` ha fallado: {cond} era falsa`,
  'errori.esec-asserzione.frase-2': 'un `assert` ha fallado',
  'errori.esec-asserzione.cosa': '`assert(condición)` detiene el programa si la condición es falsa. Quien lo escribió (tú o el profe) dice: «aquí esto tiene que ser siempre verdad». El problema real está antes: busca dónde el valor se volvió incorrecto.',
  'errori.esec-asserzione.concetto': 'assert y comprobaciones',
  'errori.esec-abort.etichetta': 'programa interrumpido (abort)',
  'errori.esec-abort.frase': 'el programa se ha interrumpido solo (abort)',
  'errori.esec-abort.cosa': 'Normalmente lo pide la biblioteca cuando encuentra un problema grave: un `assert` fallido, un `free` incorrecto, memoria dañada. Mira las líneas impresas justo antes: a menudo dicen el motivo.',
  'errori.esec-abort.concetto': 'memoria dinámica',
  'errori.esec-overflow.etichetta': 'entero demasiado grande',
  'errori.esec-overflow.frase': 'un entero se ha hecho demasiado grande',
  'errori.esec-overflow.cosa': 'Un `int` llega hasta 2147483647. Por encima, el resultado es incorrecto. Pasa con factoriales y potencias: usa `long long` (con `%lld` en `printf`), o revisa las cuentas.',
  'errori.esec-overflow.concetto': 'tipos enteros',
  'errori.esec-tempo.etichetta': 'tiempo agotado',
  'errori.esec-tempo.frase': 'el programa no terminó a tiempo',
  'errori.esec-tempo.cosa': 'Quizá hay un bucle que no termina: la condición nunca se vuelve falsa, o la variable del bucle no cambia. O el programa espera una entrada (`scanf`, `input()`) que no llega.',
  'errori.esec-tempo.concetto': 'bucles',
  'errori.esec-segnale.etichetta': 'programa detenido por el sistema',
  'errori.esec-segnale.frase': `el sistema ha detenido el programa{segnale}`,
  'errori.esec-segnale.cosa': 'El sistema detuvo el programa mientras se ejecutaba. Lode no puede decir más a partir de esta señal: mira las últimas líneas impresas y las líneas cambiadas hace poco.',
  'errori.esec-segnale.concetto': 'ejecución',
  // ---- fuera del diccionario: lugares, recuentos, pasos, correcciones, tarjeta ----
  'errori.tempo-scaduto': 'Tiempo agotado',
  'errori.segnale': 'Señal {sig}',
  'errori.codice-uscita': `Código de salida {codice}`,
  'errori.codice-uscita-windows': `Código de salida {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'otro error', other: '{n} errores más' },
  'errori.avvisi': { one: '1 aviso', other: '{n} avisos' },
  'errori.conto': 'y {cosa}',
  'errori.conto-errori-e-avvisi': 'y {errori} y {avvisi}',
  'errori.un-nome': 'un nombre',
  'errori.alla-riga': 'en la línea {n}',
  'errori.nel-punto-indicato': 'en el punto indicado',
  'errori.la-riga': 'la línea {n}',
  'errori.il-punto-indicato': 'el punto indicado',
  'errori.colonna': ', columna {n}',
  'errori.del-if': 'del `if`',
  'errori.del-while': 'del `while`',
  'errori.del-for': 'del `for`',
  'errori.sconosciuto': 'error desconocido',
  'errori.errore': 'error',
  'errori.nella-funzione': ', en la función {funzione}',
  'errori.di-file': ' de {file}',
  'errori.fermato-alla-riga': 'El programa se detuvo en la línea {riga}{file}{funzione}.',
  'errori.poi-guarda-cambiate': ` Luego mira las líneas cambiadas después de la última prueba que salió bien: {righe}.`,
  'errori.guarda-prima-cambiate': `Mira primero las líneas cambiadas después de la última prueba que salió bien: {righe}.`,
  'errori.sistema-senza-riga': 'El sistema no dice la línea. Añade algún `printf` para ver hasta dónde llega el programa; en Mac y Linux también puedes compilar con `-g -fsanitize=address` para tener archivo y línea.',
  'errori.messaggio-senza-riga': 'El mensaje no dice la línea: mira las últimas líneas que imprimió el programa.',
  'errori.cambiate-e-altre': { one: '{righe} y {n} más', other: '{righe} y {n} más' },
  'errori.correggi-punto': `Añade \`;\` al final de la instrucción: en la línea {riga} o en la anterior.`,
  'errori.correggi-punto-senza-riga': 'Añade `;` al final de la instrucción.',
  'errori.correggi-punto-fine': `Al final de la línea {riga} añade \`;\`:`,
  'errori.correggi-punto-dentro': `En la línea {riga}, en el punto indicado, añade \`;\`:`,
  'errori.correggi-include-in-cima': 'Arriba del todo en el archivo, junto a los otros `#include`, añade:',
  'errori.correggi-include-dopo': 'Después de la línea {riga} añade:',
  'errori.correggi-include-primo': 'Arriba del todo en el archivo añade:',
  'errori.correggi-uguale': 'En la condición cambia `=` por `==`.',
  'errori.correggi-uguale-riga': `En la línea {riga} cambia \`=\` por \`==\`:`,
  'errori.correggi-return': `Antes de la \`}\` que cierra {nome} añade un \`return\` con el valor correcto para los casos que quedaron fuera. Qué valor, lo decides tú: depende de lo que tenga que calcular la función.`,
  'errori.correggi-return-senza-nome': `Antes de la \`}\` que cierra la función añade un \`return\` con el valor correcto para los casos que quedaron fuera. Qué valor, lo decides tú: depende de lo que tenga que calcular la función.`,
  'errori.generico.dove-linker': 'El enlazador (linker) no indica una línea: busca en el proyecto el nombre citado en el mensaje, y comprueba que todos los archivos `.c` estén en el comando de compilación.',
  'errori.generico.dove-senza-riga': 'El mensaje no indica una línea: lee el texto original aquí abajo.',
  'errori.generico.dove-python': '{L} se detuvo {allaRiga}{file}. Si ahí todo parece correcto, mira la línea anterior.',
  'errori.generico.dove': 'Mira {laRiga}{colonna}{file}. Si ahí todo parece correcto, mira también la línea anterior: a menudo el compilador se da cuenta de un problema solo después.',
  'errori.generico.eccezione-leggendo': '{eccezione} es el tipo de error que {L} encontró mientras leía el programa. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} es el tipo de error que {L} encontró mientras ejecutaba el programa. ',
  'errori.generico.cosa': 'Lode todavía no tiene una explicación para este mensaje. El texto original está aquí abajo: lee las palabras entre comillas, normalmente son el nombre o el tipo que da problemas.',
  'errori.catena': ' Llegaste así: {passi}.',
  'errori.catena-passo': 'línea {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, línea {riga}',
  'errori.luogo-riga': 'línea {riga}',
  'errori.con-eccezione': '{eccezione}: {frase}',
  'errori.intestazione': '**{luogo}**: {frase}',
  'errori.intestazione-eccezione': '**{luogo}** · {frase}',
  'errori.per-diario': '{dove}«{breve}»',
  'errori.non-lo-conosco': 'este error todavía no lo conozco',
  'errori.parola-avviso': 'aviso',
  'errori.e-un-avviso': `Es un aviso: el programa compila igual, pero tal como está probablemente no hace lo que quieres. {cosa}`,
  'errori.passo-dove': 'Dónde mirar',
  'errori.passo-cosa': 'Qué significa',
  'errori.passo-correzione': 'Enséñame la corrección',
  'errori.file-cambiato': 'El archivo ha cambiado desde entonces: puede que los números de línea no cuadren.',
  'errori.tipo-errore': 'Error',
  'errori.tipo-avviso': 'Aviso',
  'errori.tipo-linker': 'Error del enlazador',
  'errori.tipo-esecuzione': 'Se detuvo',
  'errori.segnaposto-valore': '‹valor›',
  'errori.correzione-vista': 'corrección vista',
  'errori.messaggio-originale': 'Mensaje original',
};
