// Datos de ejemplo (esempio() en js/dati.js) y las palabras que imprimen los programas de «Cosa stampa?». Misma forma que it/esempio.js.
export default {
  'esempio.nome': 'Lucía',
  'esempio.corso': 'Ingeniería Informática',
  'esempio.esami': ['Cálculo I', 'Fundamentos de Programación', 'Álgebra Lineal', 'Física I', 'Inglés B2', 'Programación Orientada a Objetos', 'Cálculo II', 'Bases de Datos', 'Física II'],
  'esempio.aule': ['1.2', 'Lab. 3', 'Salón de Actos'],
  'esempio.carte': [
    ['¿Qué es el gradiente de f(x, y)?', 'El vector de las derivadas parciales (∂f/∂x, ∂f/∂y): apunta en la dirección de máximo crecimiento.'],
    ['Enuncia el teorema de Schwarz', 'Si las derivadas segundas cruzadas son continuas en un entorno, entonces f_xy = f_yx.'],
    ['Condición de punto crítico', 'El gradiente se anula: ∇f(x₀) = 0.'],
    ['¿Cómo se clasifica un punto crítico?', 'Con la matriz hessiana: definida positiva → mínimo, definida negativa → máximo, indefinida → punto de silla.'],
    ['¿Qué es una integral doble sobre un dominio normal?', 'Una integral iterada: primero en la variable «interior», con límites que dependen de la otra, y luego en la otra.'],
    ['Teorema de Green: enunciado', 'La integral de línea sobre ∂D de P dx + Q dy es igual a la integral doble sobre D de (∂Q/∂x − ∂P/∂y).'],
    ['Forma diferencial exacta: definición', 'ω es exacta si existe una función U (un potencial) con dU = ω.'],
    ['Serie geométrica: ¿cuándo converge?', 'Para |q| < 1, con suma 1/(1 − q).'],
    ['¿Qué es una clave primaria?', 'Un conjunto mínimo de atributos que identifica de forma única cada tupla de una relación.'],
    ['Diferencia entre LEFT JOIN e INNER JOIN', 'El LEFT JOIN conserva todas las filas de la tabla de la izquierda, aunque no tengan correspondencia (con NULL); el INNER solo los pares que coinciden.'],
    ['¿Qué garantiza la tercera forma normal?', 'Que cada atributo no clave dependa de la clave, de toda la clave y de nada más que la clave (sin dependencias transitivas).'],
  ],
  'esempio.domande': ['¿Por qué el teorema de Schwarz necesita que las derivadas cruzadas sean continuas?'],
  'esempio.stelle': ['El teorema de Green cae siempre en el examen, con la demostración', 'Clasificar los puntos críticos con la hessiana: ejercicio fijo'],
  'esempio.stelle-basi': ['Normalización hasta FNBC: siempre cae en el examen escrito'],
  'esempio.definizioni': [
    ['Gradiente', 'El vector de las derivadas parciales de f: apunta en la dirección de máximo crecimiento.'],
    ['Punto crítico', 'Un punto en el que el gradiente de la función se anula.'],
    ['Matriz hessiana', 'La matriz cuadrada de las derivadas parciales segundas de una función.'],
    ['Punto de silla', 'Un punto crítico que no es ni máximo ni mínimo local: la hessiana es indefinida.'],
    ['Teorema de Green', 'Relaciona la integral de línea a lo largo del borde de un dominio con la integral doble sobre el dominio.'],
    ['Forma diferencial exacta', 'Una forma que admite un potencial, es decir, es la diferencial de una función.'],
  ],
  'esempio.definizioni-basi': [
    ['Clave primaria', 'Un conjunto mínimo de atributos que identifica de forma única cada tupla.'],
    ['Clave foránea', 'Un atributo que hace referencia a la clave primaria de otra relación.'],
    ['Dependencia funcional', 'Una restricción por la que el valor de un conjunto de atributos determina el de otro.'],
    ['Forma normal de Boyce-Codd', 'Toda dependencia funcional no trivial tiene una superclave a la izquierda.'],
  ],
  'esempio.switch-parole': ['uno', 'dos', 'tres', 'cuatro'],
  'esempio.switch-altro': 'otro',
  'esempio.si': 'sí',
  'esempio.no': 'no',
  'esempio.hai-scritto': 'Escribiste `{s}`',
};
