// «Cosas nuevas», el diccionario fijo de la biblioteca estándar (español): para cada entrada, la pregunta de oral
// y la respuesta. Los nombres de las funciones y las reglas que las buscan en el código siguen en js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': '¿Qué contiene la memoria que acaba de devolver malloc?',
  'glossario.malloc.risposta': 'Valores basura: malloc no la pone a cero. Si no hay memoria devuelve NULL, así que hay que comprobarlo antes de usarla.',
  'glossario.calloc.domanda': '¿Qué diferencia hay entre calloc(n, size) y malloc(n * size)?',
  'glossario.calloc.risposta': 'calloc pone a cero todos los bytes, malloc deja valores basura. Si no hay memoria, las dos devuelven NULL.',
  'glossario.realloc.domanda': '¿Qué hace realloc si falla?',
  'glossario.realloc.risposta': 'Devuelve NULL y el bloque viejo sigue siendo válido: hay que liberarlo aparte. Por eso se escribe p2 = realloc(p, n) y no p = realloc(p, n).',
  'glossario.free.domanda': '¿Qué pasa si usas un puntero después de free?',
  'glossario.free.risposta': 'Es comportamiento indefinido: esa memoria ya no es tuya. Liberarla dos veces también lo es. En cambio, free(NULL) no hace nada.',
  'glossario.strtok.domanda': '¿Por qué strtok no se puede usar sobre un literal de cadena?',
  'glossario.strtok.risposta': 'Porque escribe en la cadena: en lugar de cada separador pone \'\\0\'. Desde la segunda llamada se pasa NULL y strtok sigue desde el punto que recuerda.',
  'glossario.strcpy.domanda': '¿Qué comprueba strcpy sobre el tamaño del destino?',
  'glossario.strcpy.risposta': 'Nada: copia hasta el \'\\0\' incluido. Si el destino es demasiado pequeño, escribe más allá del final del array, y es comportamiento indefinido.',
  'glossario.strncpy.domanda': '¿strncpy(d, s, n) pone siempre el \'\\0\' final?',
  'glossario.strncpy.risposta': 'No: si s tiene n caracteres o más, en d no hay ningún \'\\0\'. Si s es más corta, rellena el resto con ceros.',
  'glossario.strcmp.domanda': '¿Qué devuelve strcmp si las dos cadenas son iguales?',
  'glossario.strcmp.risposta': '0. Un número negativo si la primera va antes, positivo si va después: por eso if (strcmp(a, b)) quiere decir «son distintas».',
  'glossario.strlen.domanda': '¿strlen cuenta también el \'\\0\' final?',
  'glossario.strlen.risposta': 'No: cuenta los caracteres antes del \'\\0\'. Para copiar la cadena hacen falta strlen(s) + 1 bytes.',
  'glossario.strcat.domanda': '¿Qué hace falta para que strcat(d, s) funcione?',
  'glossario.strcat.risposta': 'd tiene que contener ya una cadena con su \'\\0\' y tener sitio para las dos, más el \'\\0\'. strcat no comprueba el espacio.',
  'glossario.memcpy.domanda': '¿Se puede usar memcpy si origen y destino se solapan?',
  'glossario.memcpy.risposta': 'No, es comportamiento indefinido. En ese caso se usa memmove.',
  'glossario.memset.domanda': '¿memset(v, 1, n * sizeof(int)) pone a 1 los int de v?',
  'glossario.memset.risposta': 'No: memset escribe el mismo valor en cada byte, así que cada int de 32 bits vale 16843009. Para poner a cero sí sirve: memset(v, 0, …).',
  'glossario.sizeof.domanda': '¿Cuánto vale sizeof(v) si v es un parámetro int v[]?',
  'glossario.sizeof.risposta': 'El tamaño de un puntero, no del array: como parámetro, int v[] es int *v. Por eso la longitud se pasa aparte.',
  'glossario.fgets.domanda': '¿Qué deja fgets al final de la línea leída?',
  'glossario.fgets.risposta': 'El salto de línea, si cabía, y luego el \'\\0\': con fgets(s, n, f) lee como máximo n - 1 caracteres. Al final del archivo devuelve NULL.',
  'glossario.scanf.domanda': '¿Qué devuelve scanf?',
  'glossario.scanf.risposta': 'Cuántos valores ha leído y asignado, o EOF si la entrada se acaba antes. Si no lo compruebas, una letra en lugar de un número pasa en silencio.',
  'glossario.sscanf.domanda': '¿Qué diferencia hay entre scanf y sscanf?',
  'glossario.sscanf.risposta': 'sscanf lee de una cadena en lugar de la entrada. Se usa mucho después de fgets: primero lees la línea entera, luego la descompones.',
  'glossario.fopen.domanda': '¿Qué devuelve fopen si el archivo no se abre?',
  'glossario.fopen.risposta': 'NULL: hay que comprobarlo antes de leer o escribir. Cuidado: con "w" un archivo que ya existe se vacía al instante.',
  'glossario.fclose.domanda': '¿Qué hace fclose en un archivo en el que has escrito?',
  'glossario.fclose.risposta': 'Escribe en el archivo lo que aún está en el búfer y libera el FILE. Después de fclose ese puntero ya no se usa.',
  'glossario.fprintf.domanda': '¿Qué diferencia hay entre fprintf(stderr, ...) y printf(...)?',
  'glossario.fprintf.risposta': 'printf escribe en stdout, fprintf en el flujo que le pases. stderr normalmente no tiene búfer y no acaba en el archivo si rediriges la salida con >.',
  'glossario.atoi.domanda': '¿Qué devuelve atoi("hola")?',
  'glossario.atoi.risposta': '0, sin ninguna señal de error: no distingues "0" de un texto incorrecto. Para comprobarlo se usa strtol.',
  'glossario.strtol.domanda': '¿Para qué sirve el segundo argumento de strtol?',
  'glossario.strtol.risposta': 'Es un char ** donde strtol pone el punto en el que se detuvo: si coincide con el inicio, no ha leído cifras. El tercer argumento es la base.',
  'glossario.qsort.domanda': '¿Qué tiene que devolver la función de comparación de qsort?',
  'glossario.qsort.risposta': 'Un int negativo, cero o positivo si el primer elemento va antes, es igual o va después. Recibe dos const void * que hay que convertir al tipo correcto.',
  'glossario.exit.domanda': '¿Qué diferencia hay entre exit(1) y return 1 dentro de main?',
  'glossario.exit.risposta': 'Dentro de main hacen lo mismo. Pero exit termina el programa desde cualquier función, después de vaciar y cerrar los archivos abiertos.',
  'glossario.assert.domanda': '¿Qué hace assert(x) si x es falso?',
  'glossario.assert.risposta': 'Escribe en stderr la condición, el archivo y la línea, y luego detiene el programa con abort. Con -DNDEBUG los assert desaparecen: dentro no va código necesario.',
  'glossario.static-locale.domanda': '¿Qué cambia si una variable dentro de una función es static?',
  'glossario.static-locale.risposta': 'Se inicializa una sola vez y conserva el valor de una llamada a otra. Si no la inicializas, empieza en 0.',
  'glossario.computeifabsent.domanda': '¿Qué hace map.computeIfAbsent(k, x -> new ArrayList<>())?',
  'glossario.computeifabsent.risposta': 'Si k no está, crea la lista, la mete en el mapa y la devuelve. Si ya está, devuelve esa. Así después puedes hacer .add sin comprobaciones.',
  'glossario.getordefault.domanda': '¿Qué devuelve map.getOrDefault(k, 0) si k no está?',
  'glossario.getordefault.risposta': '0, y el mapa no cambia: k no se añade.',
  'glossario.putifabsent.domanda': '¿Qué devuelve map.putIfAbsent(k, v)?',
  'glossario.putifabsent.risposta': 'El valor que ya había, y entonces el mapa no cambia. Si k no estaba, pone v y devuelve null.',
  'glossario.list-remove.domanda': 'En una List<Integer> con [5, 7, 9], ¿qué hace list.remove(1)?',
  'glossario.list-remove.risposta': 'Quita el elemento en la posición 1, es decir 7: con un int se elige remove(int índice). Para quitar el valor 1 hace falta list.remove(Integer.valueOf(1)).',
  'glossario.equals.domanda': '¿Qué diferencia hay entre == y equals con dos String?',
  'glossario.equals.risposta': '== comprueba si son el mismo objeto, equals si tienen los mismos caracteres. Dos cadenas iguales pueden ser dos objetos distintos.',
  'glossario.hashcode.domanda': 'Si redefines equals, ¿qué tienes que hacer con hashCode?',
  'glossario.hashcode.risposta': 'Redefinirlo también: objetos iguales según equals tienen que tener el mismo hashCode. Si no, HashMap y HashSet no los encuentran.',
  'glossario.collections-sort.domanda': '¿Collections.sort es estable?',
  'glossario.collections-sort.risposta': 'Sí: los elementos iguales según la comparación mantienen el orden de antes. Ordena la lista en el sitio y no devuelve nada.',
  'glossario.comparator-comparing.domanda': '¿Qué hace Comparator.comparing(Studente::getVoto).reversed()?',
  'glossario.comparator-comparing.risposta': 'Compara a los estudiantes por nota, al revés: de la más alta a la más baja. Con thenComparing añades un segundo criterio cuando la nota es igual.',
  'glossario.optional.domanda': '¿Por qué no se llama a get() sobre un Optional sin comprobar?',
  'glossario.optional.risposta': 'Si está vacío, get() lanza NoSuchElementException. Se usa orElse, orElseGet o isPresent.',
  'glossario.stream.domanda': '¿Qué pasa si en un stream llamas solo a map y filter, sin collect?',
  'glossario.stream.risposta': 'Nada: map y filter son perezosas. El trabajo empieza solo con una operación final como collect, forEach o count. Y un stream se usa una sola vez.',
  'glossario.stringbuilder.domanda': '¿Por qué en un bucle se usa StringBuilder en lugar de s = s + x?',
  'glossario.stringbuilder.risposta': 'Un String nunca cambia: cada + crea uno nuevo y lo copia todo. StringBuilder añade al final del mismo objeto, y toString() da el resultado.',
  'glossario.integer-parseint.domanda': '¿Qué pasa con Integer.parseInt("12a")?',
  'glossario.integer-parseint.risposta': 'Lanza NumberFormatException. También " 12" con el espacio la lanza: antes se usa trim().',
  'glossario.scanner-nextint.domanda': '¿Por qué un nextLine() justo después de nextInt() devuelve una línea vacía?',
  'glossario.scanner-nextint.risposta': 'nextInt lee el número pero deja ahí el salto de línea. nextLine lee hasta ese salto y devuelve "". Se hace un nextLine() de más para descartarlo.',
  'glossario.try-with-resources.domanda': '¿Qué hace try (Scanner in = new Scanner(f)) { ... }?',
  'glossario.try-with-resources.risposta': 'Cierra solo el recurso al final del bloque, aunque llegue una excepción. Funciona con las clases que implementan AutoCloseable.',
  'glossario.instanceof.domanda': '¿Qué devuelve x instanceof String si x es null?',
  'glossario.instanceof.risposta': 'false, sin excepciones. Desde Java 16 puedes escribir x instanceof String s y usar s enseguida.',
  'glossario.arrays-aslist.domanda': '¿Qué pasa si haces add sobre la lista de Arrays.asList?',
  'glossario.arrays-aslist.risposta': 'Lanza UnsupportedOperationException: la lista tiene tamaño fijo y está ligada al array. En cambio set funciona, y cambia también el array.',
  'glossario.iterator-remove.domanda': '¿Cómo quitas elementos de una lista mientras la recorres?',
  'glossario.iterator-remove.risposta': 'Con un Iterator e it.remove(), o con removeIf. Con list.remove dentro de un for-each normalmente llega ConcurrentModificationException.',
  'glossario.substring.domanda': '¿Qué devuelve "clase".substring(1, 4)?',
  'glossario.substring.risposta': '"las": los caracteres de la posición 1 a la 3. El segundo índice queda excluido, y la cadena original no cambia.',
  'glossario.compareto.domanda': '¿Qué devuelve a.compareTo(b)?',
  'glossario.compareto.risposta': 'Un número negativo si a va antes que b, cero si son iguales, positivo si va después. No tiene por qué ser -1 o 1: cuenta el signo.',
  'glossario.list-comprehension.domanda': '¿Qué construye [x * 2 for x in v if x > 0]?',
  'glossario.list-comprehension.risposta': 'Una lista nueva con el doble de solo los elementos positivos de v. Es un for con if y append escrito en una línea; v no cambia.',
  'glossario.list-comprehension-annidata.domanda': 'En [x for riga in m for x in riga], ¿qué for es el externo?',
  'glossario.list-comprehension-annidata.risposta': 'El primero: los for se leen en el orden en que los escribirías uno dentro de otro. El resultado es m aplanada en una sola lista.',
  'glossario.lambda.domanda': '¿Qué puede contener una lambda en Python?',
  'glossario.lambda.risposta': 'Una sola expresión, que se convierte en el valor devuelto. Nada de instrucciones como return, for o una asignación normal.',
  'glossario.sorted-con-key.domanda': '¿Qué hace sorted(v, key=len)?',
  'glossario.sorted-con-key.risposta': 'Devuelve una lista nueva ordenada por longitud; v se queda como está. Con la misma longitud se mantiene el orden original: la ordenación es estable.',
  'glossario.enumerate.domanda': '¿Qué da enumerate(v)?',
  'glossario.enumerate.risposta': 'Los pares (índice, elemento), con el índice empezando en 0. Con enumerate(v, 1) empieza en 1.',
  'glossario.zip.domanda': '¿Qué hace zip si las listas tienen longitudes distintas?',
  'glossario.zip.risposta': 'Se detiene en la más corta: los elementos de más se pierden sin error. Desde Python 3.10, con strict=True da error.',
  'glossario.dict-get.domanda': '¿Qué diferencia hay entre d[k] y d.get(k)?',
  'glossario.dict-get.risposta': 'd[k] lanza KeyError si falta k, d.get(k) devuelve None, o el segundo argumento si lo pasas. get no añade k.',
  'glossario.setdefault.domanda': '¿Qué hace d.setdefault(k, [])?',
  'glossario.setdefault.risposta': 'Si falta k, la añade con [] y devuelve esa lista. Si ya está, devuelve el valor que hay. La [] se crea igualmente en cada llamada.',
  'glossario.defaultdict.domanda': '¿Qué pasa si lees una clave que falta en un defaultdict(list)?',
  'glossario.defaultdict.risposta': 'La crea con una lista vacía y la devuelve, sin KeyError. Cuidado: con solo leer d[k] ya se añade k.',
  'glossario.counter.domanda': '¿Qué devuelve un Counter para una clave que nunca ha visto?',
  'glossario.counter.risposta': '0, sin KeyError y sin añadirla. most_common(n) da las n más frecuentes.',
  'glossario.with-open.domanda': '¿Por qué se escribe with open(nombre) as f?',
  'glossario.with-open.risposta': 'El archivo se cierra solo al salir del bloque, aunque llegue una excepción. Sin with tienes que llamar a f.close().',
  'glossario.yield.domanda': '¿Qué devuelve una función que contiene yield?',
  'glossario.yield.risposta': 'Un generador. El cuerpo arranca solo cuando pides el primer valor, con next o con un for, y se detiene en cada yield. Se recorre una sola vez.',
  'glossario.args-e-kwargs.domanda': 'En def f(*args, **kwargs), ¿qué son args y kwargs?',
  'glossario.args-e-kwargs.risposta': 'args es una tupla con los argumentos posicionales de más, kwargs un diccionario con los que se pasan por nombre.',
  'glossario.rovescia.domanda': '¿Qué da v[::-1]?',
  'glossario.rovescia.risposta': 'Una copia de v al revés: funciona con listas, cadenas y tuplas. v no cambia.',
  'glossario.is-e-uguale.domanda': '¿Qué diferencia hay entre is y ==?',
  'glossario.is-e-uguale.risposta': '== compara los valores, is comprueba si son el mismo objeto. is se usa con None; con números y cadenas se usa ==.',
  'glossario.default-mutabile.domanda': '¿Por qué def f(x, v=[]) es una trampa?',
  'glossario.default-mutabile.risposta': 'La lista por defecto se crea una sola vez, cuando se define f: cada llamada ve los cambios de las anteriores. Se escribe v=None y dentro se crea la lista.',
  'glossario.f-string.domanda': '¿Qué imprime print(f"{x:.2f}") si x vale 3.14159?',
  'glossario.f-string.risposta': '3.14: después de los dos puntos va el formato, y .2f quiere decir dos cifras decimales, redondeadas.',
  'glossario.extend.domanda': '¿Qué diferencia hay entre v.append(w) y v.extend(w)?',
  'glossario.extend.risposta': 'append añade w como un solo elemento, aunque sea una lista. extend añade uno a uno los elementos de w. Los dos cambian v y devuelven None.',
  'glossario.split.domanda': '¿Qué diferencia hay entre s.split() y s.split(" ")?',
  'glossario.split.risposta': 'Sin argumentos divide por cualquier espacio en blanco, aunque haya varios seguidos, y se salta las partes vacías. Con " " cada espacio separa: dos espacios seguidos dan una cadena vacía.',
  'glossario.da-riga': 'De: {file}, línea {riga}',
};
