// «Quiero hacer…» (js/guida.js y la guía de la barra, js/lode.js): las fichas de la guía paso a paso y las recetas escritas
// a mano para cuando no hay IA. Cada paso de una receta es una lista de cuatro textos: [título, qué se hace (2-4 frases
// sencillas), cuándo está hecho, una ayuda para quien no lo consigue]. El número de pasos de cada receta está en RICETTE de js/guida.js.
export default {
  'guida.serve-per': 'Para «{cosa}» necesitas:',
  'guida.nessuna-app': 'No he encontrado apps adecuadas en el ordenador. No pasa nada: cuando haga falta, el paso te dice qué instalar.',
  'guida.apri': 'Abrir',
  'guida.apri-tutte': 'Abrir todas',
  'guida.aperta': 'Abierta: {app}.',
  'guida.non-aperta': 'No he podido abrir {app}.',
  'guida.cominciamo': 'Empecemos',
  'guida.preparo': 'Preparo el plan',
  'guida.piano-ai': 'Plan escrito con {motore}: si un paso no te va bien, sáltalo.',
  'guida.piano-ricetta': 'Plan de Lode, sin IA.',
  'guida.piano-generico': 'Para esto no tengo una receta: te propongo un plan general, para adaptar.',
  'guida.piano-ripiego': 'La IA no ha dado un plan válido: uso el de Lode.',
  'guida.passo-di': 'Paso {i} de {tot}',
  'guida.fatto-quando': 'Hecho cuando: {quando}',
  'guida.ti-serve': 'Necesitas: {app}',
  'guida.fatto-avanti': 'Hecho, siguiente',
  'guida.non-ci-riesco': 'No me sale',
  'guida.indietro': 'Atrás',
  'guida.basta': 'Basta',
  'guida.un-aiuto': 'Una ayuda',
  'guida.piu-piccolo': 'Más pequeño, un trozo cada vez:',
  'guida.ci-penso': 'Lo pienso',
  'guida.fallo-con': 'Hazlo con {agente}',
  'guida.scegli-cartella': 'Primero elige la carpeta en la que trabajar.',
  'guida.cartella': 'Elige la carpeta',
  'guida.testo-agente': 'Este es el texto que le llega a {agente}, en la carpeta «{cartella}». Puedes cambiarlo.',
  'guida.nota-agente': 'Se abre una ventana de la Terminal con {agente}: usa tu suscripción, sin ninguna clave. Lee lo que hace antes de decir que sí.',
  'guida.agente-aperto': 'He abierto la Terminal con {agente}.',
  'guida.agente-segue': 'Lode vigila la carpeta: cuando {agente} termine, te lo digo aquí.',
  'guida.agente-errore': 'La Terminal no se ha abierto: {errore}',
  'guida.agente-finito': '{agente} ha terminado: revisa el resultado y pulsa Hecho.',
  'guida.prompt-agente': 'Estoy haciendo esto: {obiettivo}. Ahora el paso es «{passo}»: {cosa} Haz solo este paso, explícame con palabras sencillas lo que haces y párate al final.',
  'guida.fine-titolo': '¡Todo hecho!',
  'guida.fine-testo': { one: '{titolo}: el paso está hecho. Buen trabajo.', other: '{titolo}: {n} pasos de {n}, todos hechos. Buen trabajo.' },
  'guida.chiusa': 'Guía puesta a un lado',
  'guida.chiusa-nota': 'Cuando quieras seguir, escribe «retomar la guía».',
  'guida.ripresa': 'Sigo donde lo dejaste.',
  'guida.nessuna': 'No tienes una guía a medias. Prueba a escribir «quiero hacer una presentación».',
  'guida.proposta-titolo': 'A medias: {titolo}',
  'guida.proposta-testo': 'Vas por el paso {i} de {tot}.',
  'guida.proposta-bottone': 'Retomar',
  'guida.nel-vault': 'La lista de pasos también está en el vault: {nota}.',
  // la nota en el vault (en el idioma del vault)
  'guida.nota-file': 'Paso a paso',
  'guida.nota-intro': 'La guía de Lode. Lode marca un paso cuando pulsas «Hecho, siguiente» en la barra.',
  'guida.nota-quando': 'Hecho cuando',
  'guida.linguaggio': 'tu lenguaje',

  // las recetas: [título, qué se hace, hecho cuando, ayuda]
  'guida.r-tesi-1': ['Entiende qué te piden', 'Vuelve a leer el enunciado o habla con tu tutor. Escribe en una línea la pregunta a la que responde tu trabajo. Apunta la fecha de entrega y cuántas páginas hacen falta.', 'tienes una frase con la pregunta y la fecha de entrega', 'Si no sabes por dónde empezar, escribe tres preguntas sobre el tema que te dan curiosidad y elige la que tenga más material.'],
  'guida.r-tesi-2': ['Reúne las fuentes', 'Busca 5-10 fuentes serias: libros, artículos, apuntes del curso. Guárdalas todas en un solo sitio, con autor y año. De cada una escribe dos líneas sobre para qué la necesitas.', 'tienes una lista de fuentes con dos líneas cada una', 'Empieza por la bibliografía de un buen artículo: te lleva a otras fuentes que alguien ya ha elegido.'],
  'guida.r-tesi-3': ['Haz el índice', 'Escribe los títulos de los capítulos y, debajo de cada uno, tres o cuatro puntos. No hace falta que sea perfecto. El índice es el mapa: lo cambiarás mientras escribes.', 'tienes un índice con los puntos de cada capítulo', 'Usa el esquema clásico: introducción, lo que ya se sabe, lo que has hecho tú, resultados, conclusiones.'],
  'guida.r-tesi-4': ['Escribe el primer borrador', 'Escribe un capítulo cada vez, sin corregir. Mejor una página fea que una página vacía. Pon las citas enseguida, así no las pierdes.', 'cada capítulo tiene un texto, aunque sea feo', 'Haz sesiones cortas: «focus 25» y escribe solo un párrafo.'],
  'guida.r-tesi-5': ['Relee y arregla', 'Lee todo en voz alta: las frases largas se notan. Comprueba que cada capítulo responde a la pregunta inicial. Arregla las citas y la bibliografía.', 'has releído todo una vez, de principio a fin', 'Imprímelo o cambia la letra: en las mismas hojas el ojo se salta los errores.'],
  'guida.r-tesi-6': ['Entrega', 'Exporta a PDF y revisa las páginas una por una. Sigue las normas del formato que piden. Envía el archivo y guarda una copia.', 'el archivo está entregado y tienes una copia', 'Lee las normas de formato del departamento antes de exportar: márgenes, letra, portada.'],

  'guida.r-sito-1': ['Decide qué debe hacer la web', 'Escribe quién la va a mirar y qué debe encontrar. Haz la lista de páginas: por ejemplo Inicio, Quién soy, Proyectos, Contacto. Dibuja en una hoja la página principal.', 'tienes la lista de páginas y un boceto', 'Mira tres webs parecidas que te gusten y apunta qué tienen en común.'],
  'guida.r-sito-2': ['Prepara la carpeta', 'Crea una carpeta para la web y ábrela en el editor. Dentro crea index.html y style.css. Escribe una página con solo un título y ábrela en el navegador.', 'el navegador muestra tu título', 'En el archivo index.html basta con escribir la etiqueta h1 con tu nombre: guarda y recarga la página.'],
  'guida.r-sito-3': ['Escribe la estructura', 'Pon en HTML las partes de la página: cabecera, secciones, pie. Usa títulos y párrafos de verdad, sin estilo por ahora. Añade las otras páginas y los enlaces entre ellas.', 'todas las páginas están y los enlaces funcionan', 'Una página cada vez: copia index.html, cambia el texto y enlaza con una etiqueta a.'],
  'guida.r-sito-4': ['Dale estilo', 'En el CSS elige una letra, dos colores y los márgenes. Haz que se lea bien también en el móvil. Compruébalo con las herramientas del navegador.', 'la web se lee bien en el ordenador y en el móvil', 'Empieza con pocas reglas: font-family, max-width para el texto, un poco de padding.'],
  'guida.r-sito-5': ['Ponla en línea', 'Elige un servicio gratuito para webs estáticas, por ejemplo GitHub Pages o Netlify. Sube la carpeta y abre la dirección que te den. Mándasela a un amigo y pregúntale qué no entiende.', 'la web se abre desde una dirección pública', 'Con GitHub Pages: crea un repositorio, sube los archivos y activa Pages en los ajustes.'],

  'guida.r-codice-1': ['Entiende el problema', 'Vuelve a leer el enunciado y escribe con palabras qué entra y qué sale del programa. Prepara dos o tres ejemplos con el resultado correcto. Así sabrás cuándo funciona.', 'tienes dos o tres ejemplos de entrada y salida', 'Haz un ejemplo pequeñísimo a mano, en una hoja, paso a paso.'],
  'guida.r-codice-2': ['Prepara el entorno', 'Crea una carpeta para el proyecto y ábrela en el editor. Comprueba que {linguaggio} funciona: escribe un programa que imprima una línea y ejecútalo.', 'el programa de prueba imprime su línea', 'Si no se encuentra el comando, el programa no está instalado o no está en el PATH: busca la guía oficial para tu sistema.'],
  'guida.r-codice-3': ['Escribe la primera versión', 'Escribe en {linguaggio} la versión más sencilla que resuelva el primer ejemplo. Sin casos especiales por ahora. Ejecuta el programa a menudo, tras pocas líneas.', 'el primer ejemplo da el resultado correcto', 'Divídelo en funciones pequeñas: una lee, otra calcula, otra imprime.'],
  'guida.r-codice-4': ['Prueba todos los casos', 'Prueba los otros ejemplos y los casos límite: vacío, un solo elemento, números grandes. Cuando algo falle, lee el error e imprime los valores a mitad. Corrige un error cada vez.', 'todos los ejemplos dan el resultado correcto', 'Copia el error y escribe «explícame el error»: te lo explico paso a paso.'],
  'guida.r-codice-5': ['Limpia y entrega', 'Pon nombres claros a las variables y quita las impresiones de prueba. Añade dos líneas que expliquen cómo se ejecuta. Vuelve a leer el enunciado y comprueba que has hecho todo.', 'el código está limpio y se cumple lo que pedían', 'Explica el código en voz alta, línea por línea: donde te atascas, hay algo que arreglar.'],

  'guida.r-presentazione-1': ['Decide el mensaje', 'Escribe en una frase qué debe recordar quien te escuche. Mira cuánto tiempo tienes: más o menos una diapositiva por minuto. Elige tres puntos, no más.', 'tienes la frase del mensaje y tres puntos', 'Imagina que se lo cuentas a un amigo en un minuto: lo que dices es el mensaje.'],
  'guida.r-presentazione-2': ['Haz el guion', 'Escribe un título para cada diapositiva, en orden. Primero la apertura, luego los tres puntos, luego el cierre. Sin diseño por ahora.', 'tienes una lista de títulos, uno por diapositiva', 'Usa notas adhesivas o una lista: mover las ideas es más fácil antes de abrir el programa.'],
  'guida.r-presentazione-3': ['Rellena las diapositivas', 'Una idea por diapositiva, pocas palabras, imágenes grandes. El texto largo lo dices tú, no lo escribes. Usa el mismo estilo en todas.', 'cada diapositiva tiene su contenido', 'Si una diapositiva tiene más de seis líneas, divídela en dos.'],
  'guida.r-presentazione-4': ['Practica en voz alta', 'Repite toda la presentación con el cronómetro. Apunta dónde te atascas y dónde te alargas. Corta lo que no haga falta para el mensaje.', 'la has repetido en el tiempo justo', 'Grábate con el móvil y escúchate una vez.'],
  'guida.r-presentazione-5': ['Prepara el día', 'Exporta también a PDF, por si el programa no está. Lleva el archivo en un pendrive o en la nube. Prepara una respuesta para dos preguntas probables.', 'tienes el PDF de reserva y las dos respuestas', 'Llega unos minutos antes y prueba el proyector.'],

  'guida.r-video-1': ['Escribe qué cuentas', 'Decide en una frase de qué trata el vídeo y cuánto dura. Escribe el guion de las escenas. Si hablas, escribe el texto y léelo en voz alta.', 'tienes el guion y el texto', 'Un vídeo corto funciona mejor: empieza con uno de un minuto.'],
  'guida.r-video-2': ['Graba', 'Graba las escenas del guion, cada una varias veces. Cuida la luz y sobre todo el audio: un micrófono cerca importa más que la cámara. Mantén el móvil quieto y en horizontal, si no es para redes sociales.', 'tienes todas las escenas grabadas', 'Graba en un sitio silencioso, con una ventana delante de ti y no detrás.'],
  'guida.r-video-3': ['Monta', 'Importa los archivos al programa de edición. Pon las escenas en orden y corta las pausas y los errores. Míralo todo una vez sin parar.', 'el vídeo se ve de principio a fin', 'Corta más de lo que piensas: un segundo de más se nota.'],
  'guida.r-video-4': ['Pule', 'Ajusta el volumen, añade los títulos y, si hace falta, música baja. Usa música libre de derechos. Añade subtítulos si alguien lo va a ver sin sonido.', 'audio, títulos y subtítulos están listos', 'Escucha con auriculares: se notan los saltos de volumen.'],
  'guida.r-video-5': ['Exporta y entrega', 'Exporta en MP4, 1080p, que sirve casi en todas partes. Mira el archivo exportado hasta el final. Súbelo o entrégalo y guarda el proyecto.', 'el archivo está entregado y lo has visto entero', 'Si el archivo es demasiado grande, exporta con un bitrate más bajo.'],

  'guida.r-dati-1': ['Escribe la pregunta', 'Escribe en una línea qué quieres descubrir con los datos. Decide qué gráfico respondería: una evolución, una comparación, una distribución. Así sabes qué buscar.', 'tienes la pregunta y el tipo de gráfico', 'Completa la frase: cuando cambia una cosa, ¿cambia también la otra?'],
  'guida.r-dati-2': ['Prepara los datos', 'Abre los datos en una hoja de cálculo. Una fila por observación, una columna por variable, con un nombre claro. Quita las filas vacías y los duplicados.', 'la tabla está limpia, con sus encabezados', 'Trabaja sobre una copia: guarda siempre el archivo original.'],
  'guida.r-dati-3': ['Mira los números', 'Calcula en cada columna la media, el mínimo y el máximo. Busca los valores raros: ¿erratas o casos reales? Apunta lo que notes.', 'tienes los números de resumen y las notas', 'Ordena la columna: los valores raros acaban arriba o abajo.'],
  'guida.r-dati-4': ['Haz el gráfico', 'Crea el gráfico que responde a la pregunta. Pon el título, el nombre de los ejes y las unidades. Quita todo lo que no sirva para leerlo.', 'el gráfico se entiende sin explicaciones', 'Líneas para la evolución en el tiempo, barras para comparar, histograma para la distribución.'],
  'guida.r-dati-5': ['Escribe lo que dice', 'Debajo del gráfico escribe dos o tres frases: qué se ve y qué significa. Di también lo que los datos no pueden decir. Guarda el gráfico como imagen.', 'tienes el gráfico guardado y las frases', 'Separa lo que ves de tu explicación: primero los hechos, luego la idea.'],

  'guida.r-esame-1': ['Ordena el temario', 'Coge el temario del curso y pégalo en Lode con «temario». Tendrás el mapa de los temas. Marca los que ya sabes.', 'el temario está en Lode', 'Si no encuentras el temario, mira la página de la asignatura o pregunta a tus compañeros.'],
  'guida.r-esame-2': ['Haz un plan', 'Cuenta los días que faltan y reparte los temas. Deja los últimos días para repasar. Mete el plan en el calendario.', 'cada tema tiene su día', 'Escribe «plan de la semana» y Lode te enseña tus horas libres de verdad.'],
  'guida.r-esame-3': ['Estudia un tema al día', 'Haz sesiones cortas con el temporizador, por ejemplo «focus 50». Al final de cada tema haz tarjetas con lo que hay que recordar. Repásalas cada día con «repasa».', 'has estudiado todos los temas al menos una vez', 'Explica el tema en voz alta como si fueras el profe: donde te atascas, vuelve a leer.'],
  'guida.r-esame-4': ['Ponte a prueba', 'Haz el «test» o pídeme preguntas con «pregúntame». Marca las preguntas falladas y vuelve a estudiarlas. Repite hasta que las sepas.', 'respondes bien a la mayoría de las preguntas', 'Empieza por los temas que menos sabes: ahí se gana más.'],
  'guida.r-esame-5': ['Haz una prueba de verdad', 'Dos o tres días antes haz el «simulacro de examen» con un examen viejo y el tiempo real. Corrígelo y repasa los errores. El día antes, duerme.', 'has hecho un examen entero en el tiempo', 'Si no tienes exámenes viejos, pídelos a tus compañeros o en el grupo de la asignatura.'],

  'guida.r-generico-1': ['Escribe el resultado', 'Escribe en una frase cómo será la cosa terminada. Cuanto más concreta, mejor. Apunta también para cuándo la necesitas.', 'tienes la frase del resultado y la fecha', 'Imagina que se la enseñas a alguien: ¿qué ve?'],
  'guida.r-generico-2': ['Busca lo que necesitas', 'Haz la lista de lo que necesitas: programas, materiales, personas con quien hablar. Mira cómo lo ha hecho otra persona, por ejemplo en un vídeo o en una guía.', 'tienes la lista de lo que necesitas', 'Busca el nombre de la cosa con «tutorial» o «guía para principiantes».'],
  'guida.r-generico-3': ['Da un primer paso pequeño', 'Elige lo más pequeño que puedes hacer ahora, en 20 minutos. Hazlo enseguida, aunque no sea perfecto. Lo demás sale más fácil.', 'has hecho el primer trozo', 'Si 20 minutos son muchos, haz 5 minutos: basta con empezar.'],
  'guida.r-generico-4': ['Sigue adelante y comprueba', 'Divide el resto en trozos de una sesión y hazlos uno a uno. Después de cada trozo compara con el resultado que escribiste. Pide una opinión antes del final.', 'el resultado es como lo habías escrito', 'Si te atascas, vuelve al trozo anterior y hazlo más pequeño.'],
};
