// Tu expediente con sistemas de notas distintos del italiano (español): «cuánto me hace falta», «y si saco», créditos,
// nota final, el expediente pegado (js/libretto.js, js/lode.js, js/pagina.js, js/benvenuto.js).
export default {
  'libretto.crediti-di': '{fatti} de {tot} {crediti}',
  'libretto.serve-gia': 'Para llegar a <b>{obiettivo}</b> te basta aprobar lo que te queda.',
  'libretto.serve-media': 'Para llegar a <b>{obiettivo}</b> necesitas una media de <b>{voto}</b> en los {cfu} {crediti} que te faltan.',
  'libretto.serve-impossibile': 'Ya no puedes llegar a <b>{obiettivo}</b>: apunta a {punta}.',
  'libretto.obiettivo-fuori': 'Con el sistema {sistema} el objetivo va de {da} a {a}.',
  'libretto.simula-esito': 'Media <b>{media}</b> <span class="{classe}">{delta}</span> · {finale} <b>{valore}</b>',
  'libretto.simula': 'Con un **{voto}** en {nome} la media pasa de {prima} a **{dopo}** ({delta}): {finale} **{valore}**.',
  'libretto.simula-primo': 'Con un {voto} en **{nome}** tu media empezaría en **{media}**: {finale} **{valore}**.',
  'libretto.sintesi-media-finale': 'media {media}, {finale} {valore}',
  'libretto.non-valido': 'Con el sistema {sistema} no existe la nota {voto}.',
  'libretto.non-superato': 'Un {voto} en {nome} no es un aprobado (necesitas {sufficienza}): no lo apunto en tu expediente.',
  'libretto.nuovo-esame': 'Asignatura nueva de {n} {crediti}: corrígelos en tu expediente.',
  'libretto.formula': 'media ponderada por {crediti}',
  'libretto.piede-esami': { one: '{n} asignatura · {cfu} {crediti}', other: '{n} asignaturas · {cfu} {crediti}' },
  'libretto.piede-media': 'media <b>{media}</b> · {finale} <b>{valore}</b>',
  'libretto.campo-voto-nota': 'como en tu expediente ({esempio}); vacío si aún no la has hecho',
  'libretto.voto-non-letto': 'No entiendo la nota «{voto}»: escríbela como en tu expediente, por ejemplo {esempio}.',
  'libretto.incolla-sotto': 'Abre tu expediente en la web de la universidad, selecciona todo, copia y pégalo aquí: una línea por asignatura, con nombre, créditos y nota. O escríbelas tú, por ejemplo «{esempio}».',
  'libretto.alla-laurea': '{n} {crediti} para terminar la carrera',
  'libretto.campo-crediti': 'Créditos ({crediti})',
  'libretto.libretto-vuoto': 'Aún no hay asignaturas. Escribe en la barra <kbd>saqué un {voto} en física</kbd>.',
  'libretto.riga-esempio': '{nome}, {n} {crediti}, {voto}',
  'libretto.esame-esempio': 'Cálculo 1',
};
