// Las preguntas de «¿Qué imprime?» (js/codice/modelli.js), en español.
// Claves: modelli.<modelo>.cosa / .concetto / .frase-N (las frases de los mutantes, en orden), modelli.<modelo>.<lenguaje>.… para
// lo que cambia en Python y Java; modelli.concetti.* y modelli.errori.* son los nombres de los temas y de los errores.
export default {
  'modelli.hai-scelto': 'Elegiste `{s}`',
  'modelli.niente': '(nada)',
  'modelli.concetti.for': 'Bucle for',
  'modelli.concetti.while': 'Bucle while',
  'modelli.concetti.do-while': 'Bucle do-while',
  'modelli.concetti.ritroso': 'Cuenta atrás',
  'modelli.concetti.array': 'Arrays',
  'modelli.concetti.divisione-intera': 'División entera',
  'modelli.concetti.resto': 'Resto con negativos',
  'modelli.concetti.cast': 'Cast a double',
  'modelli.concetti.incremento': 'i++ y ++i',
  'modelli.concetti.assegnamento': 'Asignaciones compuestas (+=)',
  'modelli.concetti.switch': 'switch y break',
  'modelli.concetti.cortocircuito': '&& y || en cortocircuito',
  'modelli.concetti.else-pendente': 'else colgante',
  'modelli.concetti.puntatori': 'Paso por referencia (punteros)',
  'modelli.concetti.parametri': 'Paso por valor',
  'modelli.concetti.visibilita': 'Variables dentro de bloques',
  'modelli.concetti.char': 'char y códigos ASCII',
  'modelli.concetti.ricorsione': 'Recursividad',
  'modelli.concetti.annidati': 'Bucles anidados',
  'modelli.concetti.break-continue': 'break y continue',
  'modelli.concetti.ternario': 'Operador ternario',
  'modelli.errori.fuori-di-uno': 'error por uno',
  'modelli.errori.divisione-intera': 'división entera',
  'modelli.errori.post-vs-pre': 'i++ y ++i',
  'modelli.errori.break-dimenticato': 'break olvidado',
  'modelli.errori.copia-del-parametro': 'copia del parámetro',
  'modelli.errori.cortocircuito': 'cortocircuito',
  'modelli.errori.resto-col-segno': 'resto con signo',
  'modelli.errori.piu-uguale': '+= y =',
  'modelli.errori.maggiore-o-uguale': '> y >=',
  'modelli.errori.indice-valore': 'índice y valor',
  'modelli.errori.sovrascrittura': 'primero y último',
  'modelli.errori.else-pendente': 'else colgante',
  'modelli.errori.variabile-nascosta': 'variable oculta',
  'modelli.errori.carattere-codice': 'carácter y código',
  'modelli.errori.caso-base': 'caso base',
  'modelli.errori.passo-del-ciclo': 'cuándo se aplica el paso del bucle',
  'modelli.errori.ricorsione': 'recursividad',
  'modelli.errori.cicli-annidati': 'bucles anidados',
  'modelli.errori.break-continue': 'break y continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'ternario al revés',
  'modelli.errori.scambi-in-fila': 'intercambios seguidos',
  'modelli.for-minore.cosa': 'este for',
  'modelli.for-minore.concetto': 'Con `i < n` la última vuelta tiene i = n - 1: el valor n nunca se imprime.',
  'modelli.for-minore.frase': `{hai}: es lo que imprimiría con \`i <= {b}\`. Aquí el bucle se detiene antes.`,
  'modelli.for-minore.frase-2': `{hai}: es como si \`i++\` se aplicara antes de la primera vuelta. El incremento llega al final de cada vuelta: la primera vuelta tiene i = {a}.`,
  'modelli.for-minore.frase-3': `{hai}: te paraste una vuelta antes. Con \`i < {b}\` la última vuelta tiene i = {b2}.`,
  'modelli.for-passo.cosa': 'este for',
  'modelli.for-passo.concetto': 'Con `<=` el bucle hace también la vuelta en la que i es igual al límite.',
  'modelli.for-passo.frase': `{hai}: es lo que imprimiría con \`i < {b}\`. Con \`<=\` también se imprime {b}.`,
  'modelli.for-passo.frase-2': `{hai}: \`i += {s}\` no se aplica antes de la primera vuelta. La primera vuelta tiene i = {a}.`,
  'modelli.for-indietro.cosa': 'esta cuenta atrás',
  'modelli.for-indietro.concetto': 'El bucle gira mientras la condición es verdadera: con `i > L` el valor L no se imprime.',
  'modelli.for-indietro.frase': `{hai}: es lo que imprimiría con \`i >= {l}\`. Con \`i > {l}\` la última vuelta tiene i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai}: \`i--\` llega al final de la vuelta, no antes. La primera vuelta imprime {n}.`,
  'modelli.for-indietro.frase-3': `{hai}: te paraste una vuelta antes. También i = {l} cumple \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'este while',
  'modelli.while-somma.concetto': 'El while sale cuando la condición se vuelve falsa: después de `while (i < n)` la variable i vale n.',
  'modelli.while-somma.frase': `{hai}: es lo que imprimiría con \`i <= {n}\`. Aquí el bucle da una vuelta menos.`,
  'modelli.while-somma.frase-2': `{hai}: es como si \`i++\` fuera antes de \`s += i\`. Aquí s suma i y solo después i crece.`,
  'modelli.while-somma.frase-3': `{hai}: después del bucle i no vale {n}. El while sale justo cuando i llega a {n2}.`,
  'modelli.while-dimezza.cosa': 'este while',
  'modelli.while-dimezza.concetto': 'Entre dos int `/` trunca: 7 / 2 da 3, y dividiendo entre 2 se llega a 1 sin decimales.',
  'modelli.while-dimezza.frase': `{hai}: es lo que pasaría si n fuera un double. n es un int: \`n /= 2\` descarta la parte decimal.`,
  'modelli.while-dimezza.frase-2': `{hai}: es lo que imprimiría con \`n >= 1\`. El bucle se detiene en cuanto n llega a 1.`,
  'modelli.while-post.cosa': 'este while con i++',
  'modelli.while-post.concetto': '`i++ < n` compara el valor viejo y luego incrementa: dentro del bucle i ya ha crecido.',
  'modelli.while-post.frase': `{hai}: es lo que imprimiría con \`++i\`. Con \`i++\` la comparación usa el valor de antes.`,
  'modelli.while-post.frase-2': `{hai}: cuando se ejecuta printf, la comparación ya ha incrementado i.`,
  'modelli.while-post.frase-3': `{hai}: también la última comparación, la falsa, incrementa i. Al final i vale {n}.`,
  'modelli.array-somma.cosa': 'esta suma',
  'modelli.array-somma.concetto': 'Los índices de un array de n elementos van de 0 a n - 1.',
  'modelli.array-somma.frase': `{hai}: te saltaste \`v[0]\`. El primer elemento tiene índice 0.`,
  'modelli.array-somma.frase-2': `{hai}: dejaste fuera el último. Con \`i < {k}\` la última vuelta lee \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai}: es el último elemento, como si hubiera \`s = v[i]\`. \`+=\` suma, no sustituye.`,
  'modelli.array-massimo.cosa': 'este máximo',
  'modelli.array-massimo.concetto': 'p es un índice: cuenta desde 0. Con `>` se queda la primera posición del máximo.',
  'modelli.array-massimo.frase': `{hai}: contaste las posiciones desde 1. En {linguaggio} el primer elemento tiene índice 0.`,
  'modelli.array-massimo.frase-2': `{hai}: es lo que haría \`>=\`. Con \`>\` un máximo igual no mueve p: se queda el primero.`,
  'modelli.array-massimo.frase-3': `{hai}: dejaste fuera el último elemento. También se compara.`,
  'modelli.array-ultimo.cosa': 'esta búsqueda',
  'modelli.array-ultimo.concetto': 'El bucle no se detiene cuando encuentra x: p se sobrescribe y queda la última posición.',
  'modelli.array-ultimo.frase': `{hai}: es la primera posición. El bucle no se detiene: cada vez que encuentra x reescribe p.`,
  'modelli.array-ultimo.frase-2': `{hai}: contaste las posiciones desde 1. En {linguaggio} el primer elemento tiene índice 0.`,
  'modelli.array-ultimo.frase-3': `{hai}: es el valor buscado, no su posición. p es un índice.`,
  'modelli.media-array.cosa': 'esta media',
  'modelli.media-array.concetto': '`s / n` entre int trunca. `(double)s / n` convierte primero y divide con decimales.',
  'modelli.media-array.frase': `{hai}: \`s / {k}\` es una división entre dos int: la parte decimal se pierde.`,
  'modelli.media-array.frase-2': `{hai}: el cast \`(double)s\` ocurre antes de la división, así que la división conserva los decimales.`,
  'modelli.media-array.frase-3': `{hai}: la división entre int no redondea, trunca.`,
  'modelli.divisione-double.cosa': 'esta división',
  'modelli.divisione-double.concetto': 'El tipo del resultado no cuenta: `a / b` entre int trunca aunque acabe en un double.',
  'modelli.divisione-double.frase': `{hai}: \`a / b\` se calcula entre int, antes de acabar en m. El double recibe un número ya truncado.`,
  'modelli.divisione-double.frase-2': `{hai}: la división entre int no redondea, trunca hacia cero.`,
  'modelli.cast-prima-dopo.cosa': 'estos dos cast',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` divide entre int y luego convierte. `(double)s / n` convierte y luego divide.',
  'modelli.cast-prima-dopo.frase': `{hai}: en \`(double)(s / n)\` los paréntesis hacen que se divida antes, entre int. El cast llega después.`,
  'modelli.cast-prima-dopo.frase-2': `{hai}: en \`(double)s / n\` el cast vale solo para s, y la división conserva los decimales.`,
  'modelli.cast-prima-dopo.frase-3': `{hai}: los intercambiaste. Los paréntesis deciden si el cast llega antes o después de la división.`,
  'modelli.diviso-due.cosa': 'esta división entre 2',
  'modelli.diviso-due.concetto': 'Basta un double en la cuenta: `a / 2.0` conserva los decimales, `a / 2` no.',
  'modelli.diviso-due.frase': `{hai}: \`a / 2\` es entre dos int: trunca y da un int, que %d imprime sin decimales.`,
  'modelli.diviso-due.frase-2': `{hai}: \`2.0\` es un double, así que \`a / 2.0\` conserva los decimales.`,
  'modelli.diviso-due.frase-3': `{hai}: \`a / 2\` no redondea: trunca hacia cero.`,
  'modelli.resto-negativi.cosa': 'este resto',
  'modelli.resto-negativi.concetto': `En {linguaggio} la división trunca hacia cero y el resto tiene el signo del dividendo: -7 % 3 da -1.`,
  'modelli.resto-negativi.frase': `{hai}: así lo hace Python, que redondea hacia abajo. En {linguaggio} se trunca hacia cero.`,
  'modelli.resto-negativi.frase-2': `{hai}: en {linguaggio} el resto no siempre es positivo. Tiene el signo del dividendo, es decir, de a.`,
  'modelli.resto-negativi.frase-3': `{hai}: la división entre int trunca hacia cero, no hacia abajo.`,
  'modelli.post-pre.cosa': 'estos incrementos',
  'modelli.post-pre.concetto': '`x = i--` usa el valor de antes y luego decrementa; `y = --i` decrementa y luego usa el valor nuevo.',
  'modelli.post-pre.concetto-2': '`x = i++` usa el valor de antes y luego incrementa; `y = ++i` incrementa y luego usa el valor nuevo.',
  'modelli.post-pre.frase': `{hai}: con \`x = i{op}\` x toma el valor de antes, luego i cambia.`,
  'modelli.post-pre.frase-2': `{hai}: con \`y = {op}i\` primero cambia i, luego y toma el valor nuevo.`,
  'modelli.post-pre.frase-3': `{hai}: los intercambiaste. El signo detrás (\`i{op}\`) usa el valor de antes, el de delante (\`{op}i\`) el valor nuevo.`,
  'modelli.piu-uguale.cosa': 'este +=',
  'modelli.piu-uguale.concetto': '`s += x` quiere decir `s = s + x`: suma al valor que había.',
  'modelli.piu-uguale.frase': `{hai}: es solo la última vuelta, como si hubiera \`=\`. \`+=\` suma cada vez.`,
  'modelli.piu-uguale.frase-2': `{hai}: con \`<=\` también i = {n} da su vuelta.`,
  'modelli.piu-uguale.frase-3': `{hai}: olvidaste el valor inicial. s empieza en {a}.`,
  'modelli.switch.cosa': 'este switch',
  'modelli.switch.concetto': 'Sin break la ejecución cae en el case de abajo y sigue hasta el primer break o hasta el final.',
  'modelli.switch.frase': `{hai}: es como si cada case tuviera su break. Sin break se sigue en el case de abajo.`,
  'modelli.switch.frase-2': `{hai}: te saltaste el break. Ahí el switch se detiene.`,
  'modelli.switch.frase-3': `{hai}: default no se ejecuta siempre. Se ejecuta si ningún case coincide, o si llegas cayendo desde un case sin break.`,
  'modelli.cortocircuito.cosa': 'este if con || y &&',
  'modelli.cortocircuito.concetto': 'Si la primera parte basta para decidir (verdadera con ||, falsa con &&), la segunda no se ejecuta.',
  'modelli.cortocircuito.frase': `{hai}: \`++n\` no se ejecuta. Con \`{op}\` la primera parte ya basta para decidir, y n se queda en 0.`,
  'modelli.cortocircuito.frase-3': '|| pide que al menos una parte sea verdadera',
  'modelli.cortocircuito.frase-4': '&& pide que las dos partes sean verdaderas',
  'modelli.cortocircuito.frase-2': `{hai}: leíste \`{op}\`. {op2}.`,
  'modelli.else-pendente.cosa': 'este else',
  'modelli.else-pendente.concetto': 'El else va con el if más cercano que no tenga ya un else, sea cual sea la sangría.',
  'modelli.else-pendente.frase': `{hai}: seguiste la sangría. Pero el else va con el if más cercano, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai}: con \`i < {n}\` la última vuelta tiene i = {n2}.`,
  'modelli.swap-valore.cosa': 'este intercambio',
  'modelli.swap-valore.concetto': 'Una función recibe copias de los valores: intercambiar a y b no toca x e y.',
  'modelli.swap-valore.frase': `{hai}: a y b son copias de x e y. El intercambio se queda dentro de la función.`,
  'modelli.swap-valore.frase-2': `{hai}: dentro de la función el intercambio ocurre de verdad. Se intercambian las copias, no x e y.`,
  'modelli.swap-indirizzo.cosa': 'estos intercambios con punteros',
  'modelli.swap-indirizzo.concetto': 'Con `&x` la función recibe la dirección: `*a = …` cambia la propia x. Los intercambios ocurren uno tras otro.',
  'modelli.swap-indirizzo.frase': `{hai}: aquí no son copias. \`&x\` pasa la dirección, y \`*a\` escribe directamente en x.`,
  'modelli.swap-indirizzo.frase-2': `{hai}: los intercambios van en orden. Primero x con y, luego la y nueva con z.`,
  'modelli.swap-indirizzo.frase-3': `{hai}: el segundo intercambio ve la y ya cambiada por el primero.`,
  'modelli.valore-e-indirizzo.cosa': 'esta función',
  'modelli.valore-e-indirizzo.concetto': 'a es una copia de x; b es la dirección de y: solo `*b = …` cambia la variable de main.',
  'modelli.valore-e-indirizzo.frase': `{hai}: a es una copia de x. Cambiar a no cambia x.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai}: b no es una copia, es la dirección de y. \`*b = …\` cambia y.`,
  'modelli.array-in-funzione.cosa': 'este array pasado a una función',
  'modelli.array-in-funzione.concetto': 'Un array se pasa por dirección: la función cambia el propio a. Un int, en cambio, se pasa como copia.',
  'modelli.array-in-funzione.frase': `{hai}: un array no se copia. La función trabaja sobre los mismos elementos de a.`,
  'modelli.array-in-funzione.frase-2': `{hai}: n en cambio es una copia. El \`n--\` de la función no toca la n de main.`,
  'modelli.blocco-ombra.cosa': 'estas dos x',
  'modelli.blocco-ombra.concetto': 'La x declarada en el bloque es otra variable: oculta la de fuera y desaparece en la }.',
  'modelli.blocco-ombra.frase': `{hai}: \`int x = {b}\` dentro de las llaves crea una x nueva. Fuera, x sigue valiendo {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai}: dentro del bloque la x más cercana es la interna. y usa esa.`,
  'modelli.char-ascii.cosa': 'estos char',
  'modelli.char-ascii.concetto': 'Un char es un número: \'a\' vale 97. %c imprime la letra, %d el código. Mayúscula = minúscula - 32.',
  'modelli.char-ascii.frase': `{hai}: %d no da la posición en el alfabeto. Da el código ASCII: 'a' vale 97.`,
  'modelli.char-ascii.frase-2': `{hai}: %d imprime el número del carácter, no la letra.`,
  'modelli.char-ascii.frase-3': `{hai}: d es un char y %c lo imprime como letra, la mayúscula.`,
  'modelli.fattoriale.cosa': 'esta recursión',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), y el caso base detiene la bajada en 1.',
  'modelli.fattoriale.frase': `{hai}: es fatt({n}). Diste un paso de menos: se multiplica desde {n2} hasta 1.`,
  'modelli.fattoriale.frase-2': `{hai}: es fatt({n}). Diste un paso de más: se empieza desde {n2}.`,
  'modelli.fattoriale.frase-3': `{hai}: te paraste en la primera llamada. fatt(n - 1) se sigue llamando hasta el caso base.`,
  'modelli.somma-cifre.cosa': 'esta recursión',
  'modelli.somma-cifre.concetto': 'n % 10 es la última cifra, n / 10 quita la última cifra. El caso base devuelve la cifra que queda.',
  'modelli.somma-cifre.frase': `{hai}: perdiste la primera cifra. El caso base devuelve n, no 0.`,
  'modelli.somma-cifre.frase-2': `{hai}: es el número de cifras. Aquí cada llamada suma \`n % 10\`, la cifra, no 1.`,
  'modelli.somma-cifre.frase-3': `{hai}: es solo la última cifra. El valor devuelto se suma al de la llamada siguiente.`,
  'modelli.ricorsione-ordine.cosa': 'esta recursión',
  'modelli.ricorsione-ordine.concetto': 'printf va después de la llamada: se imprime a la vuelta, así que del más pequeño al más grande.',
  'modelli.ricorsione-ordine.frase': `{hai}: sería así con printf antes de la llamada. Aquí se imprime a la vuelta.`,
  'modelli.ricorsione-ordine.frase-2': `{hai}: con n = 0 la función sale enseguida, sin imprimir.`,
  'modelli.annidati-conta.cosa': 'estos bucles anidados',
  'modelli.annidati-conta.concetto': 'El bucle interno vuelve a empezar en cada vuelta del externo: aquí da i vueltas, es decir 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai}: es lo que daría \`j <= i\`. Con \`j < i\` la primera vuelta (i = 0) no cuenta nada.`,
  'modelli.annidati-conta.frase-2': `{hai}: el bucle interno no da siempre {n} vueltas: da i vueltas.`,
  'modelli.annidati-stelle.cosa': 'estas estrellas',
  'modelli.annidati-stelle.concetto': 'Para cada fila i el bucle interno imprime los símbolos, luego `\\n` salta de línea.',
  'modelli.annidati-stelle.frase': `{hai}: un símbolo de más por fila. j empieza en 0 y con \`j < i\` da i vueltas.`,
  'modelli.annidati-stelle.frase-2': `{hai}: el bucle interno depende de i: no imprime siempre {n} símbolos.`,
  'modelli.annidati-stelle.frase-3': `{hai}: falta la última fila. Con \`i <= {n}\` también se imprime la fila {n}.`,
  'modelli.break-continue.cosa': 'este break y este continue',
  'modelli.break-continue.concetto': `\`continue\` salta a la vuelta siguiente; \`break\` sale del bucle, y el {l} de esa vuelta no llega.`,
  'modelli.break-continue.frase': `{hai}: \`continue\` no sale del bucle: solo salta la vuelta con i = {a}.`,
  'modelli.break-continue.frase-2': `{hai}: \`break\` no salta una vuelta: sale del bucle cuando i vale {b}.`,
  'modelli.break-continue.frase-3': `{hai}: el break llega antes del {l}: {b} no se imprime.`,
  'modelli.do-while.cosa': 'este do-while',
  'modelli.do-while.concetto': 'El do-while comprueba la condición al final de cada vuelta: el cuerpo se ejecuta siempre al menos una vez.',
  'modelli.do-while.frase': `{hai}: es lo que haría un while. El do-while ejecuta el cuerpo antes de comprobar.`,
  'modelli.do-while.frase-3': 'El do-while no añade una vuelta: comprueba la condición al final de cada vuelta.',
  'modelli.do-while.frase-4': 'Después de la primera vuelta la condición ya es falsa.',
  'modelli.do-while.frase-2': `{hai}: una vuelta de más. {vero}`,
  'modelli.do-while.frase-5': `{hai}: es lo que daría \`i {op}= {b}\`. Con \`i {op} {b}\`, cuando i llega a {b} el bucle se detiene.`,
  'modelli.do-while.frase-6': `{hai}: imprimiste i como estaba antes de la última vuelta. También la última vuelta cambia i: la comprobación llega después.`,
  'modelli.ternario.cosa': 'estos ternarios',
  'modelli.ternario.concetto': '`c ? x : y` vale x si c es verdadera, y si es falsa.',
  'modelli.ternario.frase-m-vera': `{hai}: para m tomaste la rama equivocada. \`a > b\` es verdadera, así que vale lo que va después de \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai}: para m tomaste la rama equivocada. \`a > b\` es falsa, así que vale lo que va después de \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai}: para d tomaste la rama equivocada. \`a < b\` es verdadera, así que vale lo que va después de \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai}: para d tomaste la rama equivocada. \`a < b\` es falsa, así que vale lo que va después de \`:\`.`,
  'modelli.ternario.frase-7': `{hai}: leíste los dos ternarios al revés. Verdadero → el valor después de \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` se detiene antes de {b2}: la última vuelta tiene i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai}: es lo que imprimiría \`{b}\`. range se detiene antes del segundo número.`,
  'modelli.for-minore.python.frase-2': `{hai}: te saltaste la primera vuelta. range empieza justo en {a}.`,
  'modelli.for-minore.python.frase-3': `{hai}: te paraste una vuelta antes. \`{b}\` llega hasta {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` va de {s2} en {s2} y se detiene antes de {b}: también se imprime {b2}.`,
  'modelli.for-passo.python.frase': `{hai}: es lo que imprimiría \`{s}\`. Aquí el segundo número es {b}, así que también se imprime {b2}.`,
  'modelli.for-passo.python.frase-2': `{hai}: range empieza en {a}, no en {s}. El paso se suma después de la primera vuelta.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` cuenta hacia atrás y se detiene antes de {l}: {l} no se imprime.`,
  'modelli.for-indietro.python.frase': `{hai}: imprimiste también {l}. range se detiene antes: la última vuelta tiene i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai}: range empieza justo en {n}: la primera vuelta imprime {n}.`,
  'modelli.for-indietro.python.frase-3': `{hai}: te paraste una vuelta antes. También se imprime {l}.`,
  'modelli.while-somma.python.concetto': 'El while sale cuando la condición se vuelve falsa: después de `while i < n` la variable i vale n.',
  'modelli.while-somma.python.frase': `{hai}: es como si \`i += 1\` fuera antes de \`s += i\`. Aquí s suma i y solo después i crece.`,
  'modelli.while-dimezza.python.concetto': '`//` es la división entera: 7 // 2 da 3, y dividiendo entre 2 se llega a 1 sin decimales.',
  'modelli.while-dimezza.python.frase': `{hai}: conservaste los decimales, como haría \`n /= 2\`. \`n //= 2\` es la división entera: descarta la parte decimal.`,
  'modelli.array-somma.python.frase': `{hai}: dejaste fuera el último. \`range({k})\` llega hasta {k2}: la última vuelta lee \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` es la división entera; `/` en Python conserva siempre los decimales, también entre dos int.',
  'modelli.media-array.python.frase': `{hai}: \`s // {k}\` es la división entera: la parte decimal se pierde.`,
  'modelli.media-array.python.frase-2': `{hai}: en Python \`/\` conserva los decimales, no trunca como \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai}: \`//\` no redondea al más cercano: va hacia abajo.`,
  'modelli.media-array.java.frase': `{hai}: \`s / {k}\` es entre dos int: en Java (como en C, no como en Python) la división sigue siendo entera y la parte decimal se pierde.`,
  'modelli.divisione-double.java.frase': `{hai}: \`a / b\` se calcula entre int, antes de acabar en m. En Java, como en C, la división entre dos int trunca: el double recibe un número ya truncado.`,
  'modelli.diviso-due.python.concetto': 'En Python `//` es la división entera y `/` conserva siempre los decimales, también entre dos int.',
  'modelli.diviso-due.python.frase': `{hai}: \`a // 2\` es la división entera: da un int, sin decimales.`,
  'modelli.diviso-due.python.frase-2': `{hai}: en Python \`/\` no trunca como en C o en Java: también \`a / 2\` conserva los decimales.`,
  'modelli.diviso-due.python.frase-3': `{hai}: \`a // 2\` no redondea al más cercano: va hacia abajo.`,
  'modelli.resto-negativi.python.concetto': 'En Python `//` va hacia abajo y el resto tiene el signo del divisor: -7 // 3 da -3 y -7 % 3 da 2.',
  'modelli.resto-negativi.python.frase': `{hai}: así lo hacen C y Java, que truncan hacia cero. En Python \`//\` va hacia abajo.`,
  'modelli.resto-negativi.python.frase-2': `{hai}: en Python el resto tiene el signo del divisor, es decir, de b, no del dividendo.`,
  'modelli.resto-negativi.python.frase-3': `{hai}: \`//\` redondea hacia abajo, no hacia cero.`,
  'modelli.piu-uguale.python.frase': `{hai}: \`range(1, {n})\` llega hasta {n2}: también i = {n2} da su vuelta.`,
  'modelli.swap-valore.python.concetto': 'La función recibe los valores: reasignar a y b dentro de la función no toca x e y.',
  'modelli.swap-valore.python.frase': `{hai}: a y b son nombres de la función. Reasignarlos no cambia x e y.`,
  'modelli.swap-valore.python.frase-2': `{hai}: dentro de la función el intercambio ocurre de verdad. Se intercambian a y b, no x e y.`,
  'modelli.array-in-funzione.python.concetto': 'La lista pasa a la función tal cual: `v[n] *= …` cambia la propia a. n en cambio es un nombre de la función: `n -= 1` no toca la n de fuera.',
  'modelli.array-in-funzione.python.frase': `{hai}: una lista no se copia. La función trabaja sobre los mismos elementos de a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai}: n en cambio no. El \`n -= 1\` de la función no toca la n de fuera.`,
  'modelli.array-in-funzione.java.concetto': 'Un array se pasa como referencia: la función cambia el propio a. Un int, en cambio, se pasa como copia.',
  'modelli.somma-cifre.python.concetto': '`n % 10` es la última cifra, `n // 10` quita la última cifra. El caso base devuelve la cifra que queda.',
  'modelli.ricorsione-ordine.python.concetto': 'print va después de la llamada: se imprime a la vuelta, así que del más pequeño al más grande.',
  'modelli.ricorsione-ordine.python.frase': `{hai}: sería así con print antes de la llamada. Aquí se imprime a la vuelta.`,
  'modelli.annidati-conta.python.concetto': 'El bucle interno vuelve a empezar en cada vuelta del externo: `range(i)` da i vueltas, es decir 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai}: es lo que daría \`range(i + 1)\`. Con i = 0, \`range(i)\` no da ninguna vuelta.`,
  'modelli.annidati-stelle.python.concetto': 'Para cada fila i el bucle interno imprime los símbolos, luego `print()` salta de línea.',
  'modelli.annidati-stelle.python.frase': `{hai}: un símbolo de más por fila. \`range(i)\` da i vueltas, no i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai}: falta la última fila. \`range(1, {n})\` llega hasta {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'Para cada fila i el bucle interno imprime los símbolos, luego `println()` salta de línea.',
};
