// El plan para quien trabaja (js/ore.js): los tiempos «unos…», las líneas de la semana, lo que no cabe y las opciones.
export default {
  'ore.circa-min': 'unos {m} min',
  'ore.circa-ore': { one: 'más o menos {n} hora', other: 'unas {n} horas' },
  'ore.circa-h': 'unas {h} h',
  'ore.circa-h-min': 'unas {h} h {m}',
  'ore.opzione-cuscinetto': 'Uso también los días de reserva',
  'ore.opzione-un-ripasso': 'Un solo repaso para los temas nuevos, no dos',
  'ore.opzione-tetto': 'Los días que trabajo estudio 3 horas, no 2',
  'ore.giorni-brevi': ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  'ore.libere': '{circa} libres',
  'ore.niente-ore-libere': 'sin horas libres',
  'ore.giorno': '{g} {n}',
  'ore.lavoro': 'trabajo {turni}',
  'ore.voce-tema': 'ejercicio de examen ({circa})',
  'ore.argomento': 'tema',
  'ore.voce-generale': 'repaso general ({circa})',
  'ore.esame': 'Examen',
  'ore.voce-cuscinetto': '{nome}: día de reserva, para ponerte al día',
  'ore.oggi-niente': 'Hoy no tienes horas libres para estudiar{lav}.',
  'ore.oggi-hai': 'Hoy tienes {liberi}{lav}: {lista}.',
  'ore.oggi-hai-vuoto': 'Hoy tienes {liberi}{lav}. En el plan no hay nada para hoy.',
  'ore.per-esame': '{circa} para {nome}',
  'ore.un-esame': 'un examen',
  'ore.mancano': 'Hasta el examen de {nome} te faltan {circa}.',
  'ore.questo-esame': 'este examen',
  'ore.recuperi': '{testo} · recuperas {circa}',
  'ore.ripiego': 'Con las horas que tienes no cabe todo. Puedes escribirme más horas de estudio («estudio de 9 a 21») o pensar en la convocatoria siguiente: tú decides.',
  'ore.mancano-ancora': 'Todavía te faltan {circa}.',
  'ore.ora-ci-sta': 'Ahora cabe.',
};
