// Textos de la página bajo la barra (español): saludo, números de la carrera, fichas de los exámenes, expediente,
// mazos, ventanas del examen y de los ajustes, copia de seguridad.
export default {
  // saludo y línea de abajo
  'pagina.saluto-notte': '¿Todavía despierto?',
  'pagina.saluto-mattina': 'Buenos días',
  'pagina.saluto-pomeriggio': 'Buenas tardes',
  'pagina.saluto-sera': 'Buenas noches',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} tarjeta para repasar', other: '{n} tarjetas para repasar' },
  'pagina.sotto-serie': { one: '{n} día seguido', other: '{n} días seguidos' },
  'pagina.sotto-niente': 'Hoy no tienes nada pendiente.',
  'pagina.sotto-vuoto': 'Tus notas, tu plan de estudio y el repaso. Todo aquí, todo tuyo.',
  // cabecera
  'pagina.sottotitolo': 'asistente de estudio',
  'pagina.esporta': 'Exportar',
  'pagina.impostazioni': 'Ajustes',
  'pagina.suggerimento': 'Pasa el cursor por la barra de arriba, pulsa <kbd>/</kbd> para escribir o mantén pulsado <kbd>{tasti}</kbd> para hablar.',
  // los números
  'pagina.media-ponderata': 'Media ponderada',
  'pagina.media-dettaglio': { one: 'aritmética {media} · {n} nota', other: 'aritmética {media} · {n} notas' },
  'pagina.primo-voto': 'apunta tu primera nota desde la barra',
  'pagina.base-laurea': 'Nota base de grado',
  'pagina.base-formula': 'media × 110 / 30',
  'pagina.crediti': 'Créditos',
  'pagina.cfu-alla-laurea': '{n} créditos para terminar la carrera',
  'pagina.questa-settimana': 'Esta semana',
  'pagina.minuti-settimana': 'Minutos de estudio en los últimos 7 días',
  'pagina.giorno-ore': '{giorno}: {ore}',
  'pagina.iniziali-giorni': ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
  // exámenes
  'pagina.prossimi-esami': 'Próximos exámenes',
  'pagina.nuovo-esame': 'Nuevo examen',
  'pagina.vuoto-scrivi': 'Escribe en la barra de arriba:',
  'pagina.vuoto-comando': 'examen cálculo 2 el 15 de enero 9 créditos',
  'pagina.vuoto-oppure': 'o {bottone}',
  'pagina.prova-esempio': 'prueba con los datos de ejemplo',
  'pagina.programma-aggiungi': '+ Temario',
  'pagina.giorno-cuscinetto': 'día de reserva',
  'pagina.ripasso-generale': 'repaso general',
  'pagina.niente-di-nuovo': 'nada nuevo',
  'pagina.programma-pronto': '<b>{pct}% del temario</b> · hoy: {oggi}',
  'pagina.data-da-decidere': 'Fecha por decidir',
  'pagina.quando-cfu': '{quando} · {cfu} créditos',
  'pagina.giorni-maiuscolo': { one: 'DÍA', other: 'DÍAS' },
  'pagina.ore-studiate': '{fatte} de {tot} h estudiadas',
  'pagina.ore-oggi': '<b>{h} h</b> hoy',
  'pagina.oggi-in-pari': 'hoy al día',
  'pagina.focus': 'Focus',
  'pagina.ripassa': 'Repasar',
  'pagina.ripassa-n': 'Repasar {n}',
  'pagina.interrogami': 'Pregúntame',
  'pagina.modifica-segna-voto': 'Editar · Apuntar nota',
  // expediente y repaso
  'pagina.libretto': 'Expediente',
  'pagina.segna-voto': 'Apuntar una nota',
  'pagina.ripasso': 'Repaso',
  'pagina.da-file': 'Desde archivo',
  'pagina.libretto-vuoto': 'Ningún examen hecho. Escribe en la barra <kbd>saqué un 28 en física</kbd>.',
  'pagina.col-esame': 'Examen',
  'pagina.col-cfu': 'Créditos',
  'pagina.col-voto': 'Nota',
  'pagina.col-data': 'Fecha',
  'pagina.idoneo': 'apto',
  'pagina.voto-lode': '{voto} MH',
  'pagina.modifica-esame': 'Editar {nome}',
  'pagina.libretto-esami': '{n} exámenes · {cfu} créditos',
  'pagina.libretto-media': 'media <b>{media}</b> · base <b>{base}</b>',
  'pagina.mazzi-vuoto': 'Todavía no hay tarjetas. Escribe <kbd>tarjeta: pregunta = respuesta</kbd> o arrastra un PDF a la ventana.',
  'pagina.esame-tolto': 'Examen quitado',
  'pagina.senza-esame': 'Sin examen',
  'pagina.n-carte': { one: '{n} tarjeta', other: '{n} tarjetas' },
  'pagina.da-ripassare-oggi': 'para repasar hoy',
  'pagina.piede': 'Lode es open source (MIT). Tus datos se quedan en este navegador: sin cuenta, sin servidor.',
  'pagina.importa-backup': 'Importar una copia de seguridad',
  // ventana del examen
  'pagina.esame-correggi': 'Corrige los datos o apunta la nota.',
  'pagina.esame-aiuto': 'También puedes escribirlo en la barra: «examen física 2 el 20 de febrero 6 créditos».',
  'pagina.campo-nome': 'Nombre',
  'pagina.esempio-esame': 'Cálculo 2',
  'pagina.campo-cfu': 'Créditos',
  'pagina.campo-data': 'Fecha',
  'pagina.campo-data-appello': 'Fecha del examen',
  'pagina.campo-voto': 'Nota',
  'pagina.campo-voto-nota': 'vacío si todavía no lo has hecho',
  'pagina.trenta-e-lode': '30 con matrícula',
  'pagina.idoneita': 'Apto/No apto',
  'pagina.campo-ore': 'Horas de estudio previstas',
  'pagina.campo-ore-nota': 'para el plan',
  'pagina.ore-segnaposto': '10 × créditos',
  'pagina.elimina': 'Eliminar',
  'pagina.annulla': 'Cancelar',
  'pagina.salva': 'Guardar',
  'pagina.conferma-elimina': '¿Eliminar {nome}? Sus horas y sus tarjetas se quedan, sin examen.',
  'pagina.esame-eliminato': 'Examen eliminado',
  'pagina.salvato': 'Guardado',
  'pagina.esame-aggiunto': 'Examen añadido',
  // ventana de ajustes
  'pagina.impostazioni-aiuto': 'Todo se queda en este ordenador. La clave de tu IA solo va al servicio que elijas.',
  'pagina.campo-tuo-nome': 'Tu nombre',
  'pagina.esempio-nome': 'Lucía',
  'pagina.campo-corso': 'Carrera',
  'pagina.esempio-corso': 'Ingeniería informática',
  'pagina.campo-cfu-laurea': 'Créditos de la carrera',
  'pagina.campo-lode-vale': 'La matrícula vale',
  'pagina.campo-focus': 'Focus (minutos)',
  'pagina.campo-pausa': 'Descanso (minutos)',
  'pagina.rintocco': 'Campanada al final del focus',
  'pagina.aspetto-chiaro': 'Tema claro',
  'pagina.campo-ai': 'Tu IA',
  'pagina.campo-ai-nota': 'opcional, de pago por uso: el servicio lo pagas tú',
  'pagina.solo-locale': 'Solo el cerebro local (gratis)',
  'pagina.campo-chiave': 'Clave',
  'pagina.campo-chiave-nota': 'se crea en la web del servicio',
  'pagina.chiave-segnaposto': 'pega la clave',
  'pagina.voce-alta': 'Leer las respuestas en voz alta',
  'pagina.ai-attiva': 'IA <b>activa</b>: {nome}.',
  'pagina.senza-chiave': 'Sin clave Lode funciona igual: comandos, temporizador, expediente y repaso son todos locales; en la app también está el cerebro local gratis.',
  'pagina.cancella-tutto': 'Borrar todo',
  'pagina.conferma-azzera': '¿Borrar todos los datos de Lode de este navegador? Mejor exportarlos antes.',
  'pagina.dati-cancellati-chiave': 'Datos borrados, también la clave de {nome}: revócala también en tu cuenta ({sito})',
  'pagina.dati-cancellati': 'Datos borrados',
  'pagina.chiave-cancellata': 'Clave de {nome} borrada de aquí: revócala también en tu cuenta ({sito})',
  'pagina.impostazioni-salvate': 'Ajustes guardados',
  'pagina.ai-collegata': '{nome} conectada',
  'pagina.ai-collegata-modello': '{nome} conectada · {modello}',
  'pagina.chiave-non-valida': 'La clave no es válida',
  'pagina.chiave-non-verificabile': 'Ahora no puedo comprobar la clave',
  // copia de seguridad y datos de ejemplo
  'pagina.backup-scaricato': 'Copia de seguridad descargada',
  'pagina.conferma-importa': '¿Cambiar los datos actuales por esta copia de seguridad?',
  'pagina.backup-importato': 'Copia de seguridad importada',
  'pagina.non-backup': 'Este archivo no es una copia de seguridad de Lode',
  'pagina.conferma-esempio': '¿Cargar los datos de ejemplo en lugar de los tuyos?',
  'pagina.esempio-caricato': 'Datos de ejemplo cargados: pasa el cursor por la barra de arriba',
};
