// DA TRADURRE (es): per ora è la copia del catalogo italiano, messa dalla fase di estrazione perché la barra e
// test/lingue.mjs trovino tutte le chiavi. La fase di traduzione sostituisce i testi (stesse chiavi, parametri e tag).
// «Segui il progetto» nella barra (italiano, lingua di partenza): pillola, schede «Seguo…?», «Cosa sta cambiando»,
// «Fatto. In parole semplici», «Provato?» e «Cose nuove».
export default {
  'progetto.solo-app': 'Seguire un progetto si può solo nell\'app desktop di Lode.',
  'progetto.provo': 'provo…',
  'progetto.file-cambiati': '{n} file +{piu} −{meno}',
  'progetto.fatto-non-provato': 'fatto · non provato',
  'progetto.oggi-non-provato': '{nome}: non provato',
  'progetto.oggi-esito': '{nome}: {breve}',
  'progetto.oggi-sta-cambiando': '{nome}: sta cambiando',
  'progetto.ultima-prova-alle': 'L\'ultima prova, alle {ora}',
  'progetto.vedi': 'Vedi',
  'progetto.esito': 'Esito',
  'progetto.prova': 'Prova',
  'progetto.provato': 'Provato?',
  'progetto.cosa-e-cambiato': 'Cosa è cambiato',
  'progetto.cosa-sta-cambiando': 'Cosa sta cambiando',
  'progetto.serve-seguito': 'Serve un progetto seguito nell\'app: scrivi «segui progetto».',
  'progetto.non-seguo-nome': 'Non seguo nessun progetto che si chiama «{nome}».',
  'progetto.non-seguo-niente': 'Non seguo nessun progetto. Scrivi **segui progetto** e scegli la cartella del laboratorio.',
  'progetto.capito-testo': 'Lode guarda i file e verifica se il codice è provato: non scrive codice al posto tuo. Se usi un agente o un\'AI, cosa è permesso lo decide il tuo corso: chiedi al docente. Il diario è un registro per te, non una prova per il prof: è quello che Lode ha visto, e non sa chi ha scritto le righe. Per una consegna valutata segna il progetto come "valutato": Lode ti dirà dove guardare e cosa vuol dire un errore, ma non ti mostrerà la correzione.',
  'progetto.prima-di-cominciare': 'Prima di cominciare',
  'progetto.ho-capito': 'Ho capito',
  'progetto.solo-app-desktop': 'Seguire un progetto si può solo nell\'**app desktop** di Lode: lì guardo la cartella del tuo laboratorio.',
  'progetto.va-bene-non-seguo': 'Va bene, non seguo niente.',
  'progetto.seguo-gia': 'Seguo già **{nome}**.',
  'progetto.seguo-domanda': 'Seguo <b>{nome}</b>?',
  'progetto.seguo-aria': 'Seguo {nome}?',
  'progetto.seguo-spiega': 'Guardo i file e tengo le versioni nella cartella di Lode: io nella tua cartella non scrivo. I comandi che confermi (per esempio make) sì, come dal terminale. Non so chi scrive le righe (tu, un agente o un copia-incolla): ti dico cosa è cambiato e se l\'hai provato.',
  'progetto.nota-windows': 'Mentre la seguo, Windows non ti lascia rinominare o spostare la cartella: prima scrivi «smetti di seguire».',
  'progetto.corso': 'Corso',
  'progetto.nessun-corso': 'Nessun corso',
  'progetto.valutato': 'Progetto valutato (consegna)',
  'progetto.valutato-spiega': 'Ti dico dove guardare, ma niente correzioni pronte',
  'progetto.no-diario': 'Non scrivere il diario di questo progetto',
  'progetto.no-diario-spiega': 'Nel vault non finiscono nomi di file né di funzioni',
  'progetto.n-file': { one: '{n} file', other: '{n} file' },
  'progetto.segui': 'Segui',
  'progetto.annulla': 'Annulla',
  'progetto.annullato': 'Annullato.',
  'progetto.non-seguo-niente-nota': 'Non seguo niente.',
  'progetto.seguo-fatto': 'Seguo {nome}.',
  'progetto.seguo-fatto-nota': 'Ti dico cosa cambia e se l\'hai provato. Le versioni le tengo nella cartella di Lode.',
  'progetto.seguo-sintesi': 'seguo {nome}',
  'progetto.smetto-domanda': 'Smetto di seguire <b>{nome}</b>?',
  'progetto.smetto-spiega': 'Tolgo le copie che ho tenuto nella cartella di Lode. I tuoi file non li tocco.',
  'progetto.smetti-di-seguire': 'Smetti di seguire',
  'progetto.continuo-a-seguire': 'Continuo a seguire {nome}.',
  'progetto.non-seguo-piu': 'Non seguo più {nome}.',
  'progetto.non-seguo-piu-nota': 'Le copie di Lode sono andate. I tuoi file non li ho toccati.',
  'progetto.smesso-sintesi': 'smesso {nome}',
  'progetto.etichetta-nuovo': 'nuovo',
  'progetto.etichetta-tolto': 'tolto',
  'progetto.etichetta-grande': 'file grande: solo i conteggi',
  'progetto.etichetta-spazi': 'solo spazi o a capo',
  'progetto.etichetta-cambiato': 'cambiato',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Chiudi',
  'progetto.diff-grande': 'File grande (+{piu} −{meno}): il dettaglio non lo mostro.',
  'progetto.diff-solo-spazi': 'Cambiano solo spazi in fondo alle righe o gli a capo.',
  'progetto.diff-aria': 'Modifiche a {file}',
  'progetto.diff-tagliato': '… il resto non lo mostro',
  'progetto.niente-di-diverso': 'Niente di diverso.',
  'progetto.niente-di-nuovo': 'Niente di nuovo.',
  'progetto.niente-di-nuovo-dalle': 'Niente di nuovo dalle {ora}.',
  'progetto.nome-dalle': '{nome} dalle {ora}',
  'progetto.prova-adesso': 'Prova adesso',
  'progetto.visto': 'Visto',
  'progetto.provato-breve': 'provato',
  'progetto.prova-il-progetto': 'Prova il progetto',
  'progetto.visto-fatto': 'Visto.',
  'progetto.visto-nota': 'Da qui in poi ti mostro solo le modifiche nuove.',
  'progetto.visto-sintesi': 'visto',
  'progetto.fatto-titolo': 'Fatto. In parole semplici',
  'progetto.vedi-le-modifiche': 'Vedi le modifiche',
  'progetto.modifiche-tratto': 'Modifiche · {da}–{a}',
  'progetto.provato-si': '**Sì**: il codice di {nome} è quello provato alle {ora} ({breve}).',
  'progetto.provato-no-cambiato': '<b>No</b>: dopo l\'ultima prova ({ora}) il codice di {nome} è cambiato.',
  'progetto.provato-no-cambiato-alle': '<b>No</b>: dopo l\'ultima prova ({ora}) il codice di {nome} è cambiato, l\'ultima volta alle {ultima}.',
  'progetto.provato-no-mai': '<b>No</b>: {nome} con Lode non l\'hai ancora provato.',
  'progetto.provato-nota': 'Non so chi ha scritto le righe: so solo se il codice di adesso è passato da una prova.',
  'progetto.comando-manca': 'Per provare {nome} manca {cosa}',
  'progetto.comando-come': 'Come provo {nome}?',
  'progetto.comando-lancia': 'Adesso ci sono prove .in/.out: per lanciare il programma mi serve un nuovo sì.',
  'progetto.comando-cambiato': 'I file del progetto sono cambiati: il comando di prima non basta più.',
  'progetto.comando-userei': 'Per provare userei <code>{comando}</code>',
  'progetto.comando-nota': 'Eseguo solo il comando che confermi nella finestra del sistema, mai uno proposto da un agente. Non è una sandbox: il programma gira sul tuo computer, come dal terminale, e può scrivere file nella tua cartella.',
  'progetto.riprova': 'Riprova',
  'progetto.usa-questo': 'Usa questo',
  'progetto.scrivo-io': 'Scrivo io il comando',
  'progetto.cambia': 'Cambia',
  'progetto.comando-aria': 'Comando per provare',
  'progetto.usa-questo-comando': 'Usa questo comando',
  'progetto.non-eseguo': 'Non eseguo niente.',
  'progetto.non-confermato': 'Il comando non l\'hai confermato.',
  'progetto.comando-confermato': 'Comando confermato.',
  'progetto.comando-confermato-nota': 'Per questo progetto lo uso sempre, finché i file non cambiano forma.',
  'progetto.comando-confermato-sintesi': 'comando confermato',
  'progetto.uscita-caso': '— prova {caso} —',
  'progetto.non-seguo-questo': 'Non seguo questo progetto.',
  'progetto.sto-gia-provando': 'Sto già provando questo progetto: un attimo.',
  'progetto.niente': 'niente',
  'progetto.riga-vuota': 'una riga vuota',
  'progetto.caso-ok': 'Prova {caso}',
  'progetto.caso-ok-codice': 'Prova {caso} · passa, ma il programma esce con il codice {codice}',
  'progetto.caso-errore': 'Prova {caso}: {errore}',
  'progetto.caso-scaduto': 'Prova {caso}: non è finita in tempo. Un ciclo che non si ferma, o il programma aspetta altro input?',
  'progetto.caso-troncato': 'Prova {caso}: ha scritto troppo (oltre 200 KB) e l\'ho fermata.',
  'progetto.caso-crash': 'Prova {caso}: il programma si è fermato con un errore.',
  'progetto.caso-crash-segnale': 'Prova {caso}: il programma si è fermato con un errore ({segnale}).',
  'progetto.caso-crash-codice': 'Prova {caso}: il programma si è fermato con un errore (codice {codice}).',
  'progetto.caso-diverso': 'Prova {caso} · riga {riga}: atteso {atteso}, ottenuto {ottenuto}',
  'progetto.sintassi-ok': 'La sintassi è a posto',
  'progetto.sintassi-errore': 'Errore di sintassi',
  'progetto.make-ok': 'make è andato',
  'progetto.make-errore': 'make non è andato',
  'progetto.compila': 'Compila',
  'progetto.non-compila': 'Non compila',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si} e passa la prova.', other: '{si} e passa tutte le {n} prove.' },
  'progetto.esito-senza-prove': '{si}. Non ci sono prove .in/.out: il programma non l\'ho lanciato.',
  'progetto.esito-non-passano': { one: 'Una prova non passa su {tot}.', other: '{n} prove non passano su {tot}.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no}: {file}.',
  'progetto.non-compila-file-riga': '{no}: {file}, riga {riga}.',
  'progetto.non-partita': 'La prova non è partita.',
  'progetto.passano': 'Passano: {nomi}',
  'progetto.saltate': { one: 'Una prova saltata: {motivo}.', other: '{n} prove saltate: {motivo}.' },
  'progetto.avvisi': { one: '{n} avviso del compilatore.', other: '{n} avvisi del compilatore.' },
  'progetto.cambiato-durante': '<b>Il codice è cambiato mentre provavo: rifaccio?</b>',
  'progetto.rifai': 'Rifai',
  'progetto.prova-di-nuovo': 'Prova di nuovo',
  'progetto.nota-cose-nuove': 'Dal dizionario di Lode: solo funzioni della libreria standard. Non vede le idee, solo i nomi.',
  'progetto.file-riga': '{file}, riga {riga}',
  'progetto.domanda-orale': 'Domanda da orale:',
  'progetto.risposta': 'Risposta',
  'progetto.cose-nuove': 'Cose nuove: {nomi}',
  'progetto.mettila-nel-ripasso': 'Mettila nel ripasso',
  'progetto.la-so-gia': 'La so già',
  'progetto.nel-ripasso': 'Nel ripasso.',
  'progetto.la-sai-gia': 'la sai già',
};
