// «Sigue el proyecto» en la barra (español): píldora, tarjetas «¿Sigo…?», «Qué está cambiando»,
// «Hecho. En pocas palabras», «¿Probado?» y «Cosas nuevas».
export default {
  'progetto.solo-app': 'Seguir un proyecto solo se puede en la app de escritorio de Lode.',
  'progetto.provo': 'probando…',
  'progetto.file-cambiati': '{n} arch. +{piu} −{meno}',
  'progetto.fatto-non-provato': 'hecho · sin probar',
  'progetto.oggi-non-provato': '{nome}: sin probar',
  'progetto.oggi-esito': '{nome}: {breve}',
  'progetto.oggi-sta-cambiando': '{nome}: está cambiando',
  'progetto.ultima-prova-alle': 'La última prueba, a las {ora}',
  'progetto.vedi': 'Ver',
  'progetto.esito': 'Resultado',
  'progetto.prova': 'Probar',
  'progetto.provato': '¿Probado?',
  'progetto.cosa-e-cambiato': 'Qué ha cambiado',
  'progetto.cosa-sta-cambiando': 'Qué está cambiando',
  'progetto.serve-seguito': 'Hace falta un proyecto seguido en la app: escribe «sigue el proyecto».',
  'progetto.non-seguo-nome': 'No sigo ningún proyecto que se llame «{nome}».',
  'progetto.non-seguo-niente': 'No sigo ningún proyecto. Escribe **sigue el proyecto** y elige la carpeta de la práctica.',
  'progetto.capito-testo': 'Lode mira los archivos y comprueba si el código está probado: no escribe código por ti. Si usas un agente o una IA, lo que está permitido lo decide tu asignatura: pregúntale al profe. El diario es un registro para ti, no una prueba para el profe: es lo que Lode ha visto, y no sabe quién escribió las líneas. Para una entrega evaluada, marca el proyecto como "evaluado": Lode te dirá dónde mirar y qué significa un error, pero no te enseñará la corrección.',
  'progetto.prima-di-cominciare': 'Antes de empezar',
  'progetto.ho-capito': 'Entendido',
  'progetto.solo-app-desktop': 'Seguir un proyecto solo se puede en la **app de escritorio** de Lode: allí miro la carpeta de tu práctica.',
  'progetto.va-bene-non-seguo': 'Vale, no sigo nada.',
  'progetto.seguo-gia': 'Ya sigo **{nome}**.',
  'progetto.seguo-domanda': '¿Sigo <b>{nome}</b>?',
  'progetto.seguo-aria': '¿Sigo {nome}?',
  'progetto.seguo-spiega': 'Miro los archivos y guardo las versiones en la carpeta de Lode: en tu carpeta yo no escribo. Los comandos que confirmes (por ejemplo make) sí, como desde la terminal. No sé quién escribe las líneas (tú, un agente o un copia y pega): te digo qué ha cambiado y si lo has probado.',
  'progetto.nota-windows': 'Mientras la sigo, Windows no te deja renombrar ni mover la carpeta: antes escribe «deja de seguir».',
  'progetto.corso': 'Asignatura',
  'progetto.nessun-corso': 'Ninguna asignatura',
  'progetto.valutato': 'Proyecto evaluado (entrega)',
  'progetto.valutato-spiega': 'Te digo dónde mirar, pero nada de correcciones listas',
  'progetto.no-diario': 'No escribir el diario de este proyecto',
  'progetto.no-diario-spiega': 'En el vault no acaban nombres de archivos ni de funciones',
  'progetto.n-file': { one: '{n} archivo', other: '{n} archivos' },
  'progetto.segui': 'Seguir',
  'progetto.annulla': 'Cancelar',
  'progetto.annullato': 'Cancelado.',
  'progetto.non-seguo-niente-nota': 'No sigo nada.',
  'progetto.seguo-fatto': 'Sigo {nome}.',
  'progetto.seguo-fatto-nota': 'Te digo qué cambia y si lo has probado. Las versiones las guardo en la carpeta de Lode.',
  'progetto.seguo-sintesi': 'sigo {nome}',
  'progetto.smetto-domanda': '¿Dejo de seguir <b>{nome}</b>?',
  'progetto.smetto-spiega': 'Borro las copias que guardé en la carpeta de Lode. Tus archivos no los toco.',
  'progetto.smetti-di-seguire': 'Dejar de seguir',
  'progetto.continuo-a-seguire': 'Sigo con {nome}.',
  'progetto.non-seguo-piu': 'Ya no sigo {nome}.',
  'progetto.non-seguo-piu-nota': 'Las copias de Lode ya no están. Tus archivos no los he tocado.',
  'progetto.smesso-sintesi': 'dejé {nome}',
  'progetto.etichetta-nuovo': 'nuevo',
  'progetto.etichetta-tolto': 'eliminado',
  'progetto.etichetta-grande': 'archivo grande: solo los recuentos',
  'progetto.etichetta-spazi': 'solo espacios o saltos de línea',
  'progetto.etichetta-cambiato': 'cambiado',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Cerrar',
  'progetto.diff-grande': 'Archivo grande (+{piu} −{meno}): el detalle no lo muestro.',
  'progetto.diff-solo-spazi': 'Solo cambian espacios al final de las líneas o los saltos de línea.',
  'progetto.diff-aria': 'Cambios en {file}',
  'progetto.diff-tagliato': '… el resto no lo muestro',
  'progetto.niente-di-diverso': 'Nada distinto.',
  'progetto.niente-di-nuovo': 'Nada nuevo.',
  'progetto.niente-di-nuovo-dalle': 'Nada nuevo desde las {ora}.',
  'progetto.nome-dalle': '{nome} desde las {ora}',
  'progetto.prova-adesso': 'Probar ahora',
  'progetto.visto': 'Visto',
  'progetto.provato-breve': 'probado',
  'progetto.prova-il-progetto': 'Probar el proyecto',
  'progetto.visto-fatto': 'Visto.',
  'progetto.visto-nota': 'A partir de ahora solo te enseño los cambios nuevos.',
  'progetto.visto-sintesi': 'visto',
  'progetto.fatto-titolo': 'Hecho. En pocas palabras',
  'progetto.vedi-le-modifiche': 'Ver los cambios',
  'progetto.modifiche-tratto': 'Cambios · {da}–{a}',
  'progetto.provato-si': '**Sí**: el código de {nome} es el que se probó a las {ora} ({breve}).',
  'progetto.provato-no-cambiato': '<b>No</b>: después de la última prueba ({ora}) el código de {nome} cambió.',
  'progetto.provato-no-cambiato-alle': '<b>No</b>: después de la última prueba ({ora}) el código de {nome} cambió, la última vez a las {ultima}.',
  'progetto.provato-no-mai': '<b>No</b>: todavía no has probado {nome} con Lode.',
  'progetto.provato-nota': 'No sé quién escribió las líneas: solo sé si el código de ahora ha pasado por una prueba.',
  'progetto.comando-manca': 'Para probar {nome} falta {cosa}',
  'progetto.comando-come': '¿Cómo pruebo {nome}?',
  'progetto.comando-lancia': 'Ahora hay pruebas .in/.out: para ejecutar el programa necesito otro sí.',
  'progetto.comando-cambiato': 'Los archivos del proyecto cambiaron: el comando de antes ya no basta.',
  'progetto.comando-userei': 'Para probar usaría <code>{comando}</code>',
  'progetto.comando-nota': 'Solo ejecuto el comando que confirmes en la ventana del sistema, nunca uno propuesto por un agente. No es un sandbox: el programa corre en tu ordenador, como desde la terminal, y puede escribir archivos en tu carpeta.',
  'progetto.riprova': 'Reintentar',
  'progetto.usa-questo': 'Usar este',
  'progetto.scrivo-io': 'Escribo yo el comando',
  'progetto.cambia': 'Cambiar',
  'progetto.comando-aria': 'Comando para probar',
  'progetto.usa-questo-comando': 'Usar este comando',
  'progetto.non-eseguo': 'No ejecuto nada.',
  'progetto.non-confermato': 'No has confirmado el comando.',
  'progetto.comando-confermato': 'Comando confirmado.',
  'progetto.comando-confermato-nota': 'Para este proyecto lo uso siempre, mientras los archivos no cambien de forma.',
  'progetto.comando-confermato-sintesi': 'comando confirmado',
  'progetto.uscita-caso': '— prueba {caso} —',
  'progetto.non-seguo-questo': 'No sigo este proyecto.',
  'progetto.sto-gia-provando': 'Ya estoy probando este proyecto: un momento.',
  'progetto.niente': 'nada',
  'progetto.riga-vuota': 'una línea vacía',
  'progetto.caso-ok': 'Prueba {caso}',
  'progetto.caso-ok-codice': 'Prueba {caso} · pasa, pero el programa sale con el código {codice}',
  'progetto.caso-errore': 'Prueba {caso}: {errore}',
  'progetto.caso-scaduto': 'Prueba {caso}: no terminó a tiempo. ¿Un bucle que no se detiene, o el programa espera más entrada?',
  'progetto.caso-troncato': 'Prueba {caso}: escribió demasiado (más de 200 KB) y la detuve.',
  'progetto.caso-crash': 'Prueba {caso}: el programa se detuvo con un error.',
  'progetto.caso-crash-segnale': 'Prueba {caso}: el programa se detuvo con un error ({segnale}).',
  'progetto.caso-crash-codice': 'Prueba {caso}: el programa se detuvo con un error (código {codice}).',
  'progetto.caso-diverso': 'Prueba {caso} · línea {riga}: se esperaba {atteso}, salió {ottenuto}',
  'progetto.sintassi-ok': 'La sintaxis está bien',
  'progetto.sintassi-errore': 'Error de sintaxis',
  'progetto.make-ok': 'make funcionó',
  'progetto.make-errore': 'make falló',
  'progetto.compila': 'Compila',
  'progetto.non-compila': 'No compila',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si} y pasa la prueba.', other: '{si} y pasa las {n} pruebas.' },
  'progetto.esito-senza-prove': '{si}. No hay pruebas .in/.out: el programa no lo he ejecutado.',
  'progetto.esito-non-passano': { one: 'Una prueba de {tot} no pasa.', other: '{n} pruebas de {tot} no pasan.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no}: {file}.',
  'progetto.non-compila-file-riga': '{no}: {file}, línea {riga}.',
  'progetto.non-partita': 'La prueba no arrancó.',
  'progetto.passano': 'Pasan: {nomi}',
  'progetto.saltate': { one: 'Una prueba omitida: {motivo}.', other: '{n} pruebas omitidas: {motivo}.' },
  'progetto.avvisi': { one: '{n} aviso del compilador.', other: '{n} avisos del compilador.' },
  'progetto.cambiato-durante': '<b>El código cambió mientras probaba: ¿lo repito?</b>',
  'progetto.rifai': 'Repetir',
  'progetto.prova-di-nuovo': 'Probar de nuevo',
  'progetto.nota-cose-nuove': 'Del diccionario de Lode: solo funciones de la biblioteca estándar. No ve las ideas, solo los nombres.',
  'progetto.file-riga': '{file}, línea {riga}',
  'progetto.domanda-orale': 'Pregunta de oral:',
  'progetto.risposta': 'Respuesta',
  'progetto.cose-nuove': 'Cosas nuevas: {nomi}',
  'progetto.mettila-nel-ripasso': 'Añadir al repaso',
  'progetto.la-so-gia': 'Ya la sé',
  'progetto.nel-ripasso': 'En el repaso.',
  'progetto.la-sai-gia': 'ya la sabes',
};
