// Sistemas de calificación (español): nombres, créditos, nota final, mentions y clases (js/sistemi.js).
export default {
  'sistemi.scelta': 'Sistema de calificación',
  'sistemi.nome.it': 'Italia · 18–30 cum laude',
  'sistemi.nome.es': 'España · 0–10',
  'sistemi.nome.fr': 'Francia · 0–20',
  'sistemi.nome.de': 'Alemania · 1,0–5,0',
  'sistemi.nome.pt': 'Portugal · 0–20',
  'sistemi.nome.br': 'Brasil · 0–10',
  'sistemi.nome.uk': 'Reino Unido · 0–100 %',
  'sistemi.nome.us': 'Estados Unidos · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'créditos',
  'sistemi.crediti.uk': 'créditos',
  'sistemi.crediti.us': 'horas de crédito',
  'sistemi.ponderata': 'Media ponderada',
  'sistemi.finale.it': 'Base de graduación (sobre 110)',
  'sistemi.finale.es': 'Nota media del expediente',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Nota final (Gesamtnote)',
  'sistemi.finale.pt': 'Média final',
  'sistemi.finale.br': 'Coeficiente de rendimiento (CR)',
  'sistemi.finale.uk': 'Clase de titulación',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'sin mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Suspenso',
  'sistemi.idoneo': 'apto',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
