// «¿Qué imprime?», la tarjeta de los ejercicios (español).
export default {
  'stampa.titolo': '¿Qué imprime?',
  'stampa.anteprima': '¿Qué imprime {cosa}?',
  'stampa.risposta-assente': 'Esa respuesta no está entre las opciones.',
  'stampa.hai-scritto-altro': 'Escribiste `{uscita}`: no es lo que imprime.',
  'stampa.nessuna-risposta': 'Sin respuesta.',
  'stampa.aria-codice': 'Código {lingua}',
  'stampa.non-riesco': 'Hoy no consigo preparar las preguntas de {lingua}. Vuelve a intentarlo en un rato.',
  'stampa.conto': '{i} de {n}',
  'stampa.scrivi-uscita': 'Escribe la salida exacta',
  'stampa.scegli-uscita': 'Elige la salida · teclas 1-4',
  'stampa.aria-campo': 'Qué imprime el programa',
  'stampa.segnaposto': 'Escribe lo que imprime',
  'stampa.controlla': 'Comprobar <kbd>Intro</kbd>',
  'stampa.piu-righe': '¿Varias líneas? Sepáralas con un espacio.',
  'stampa.aria-risposta': 'Respuesta {n}: {uscita}',
  'stampa.giusto': 'Correcto · calculado por Lode',
  'stampa.stampa-giusta': 'Imprime <code>{uscita}</code>.',
  'stampa.avanti': 'Siguiente <kbd>Intro</kbd>',
  'stampa.com-e-andata': 'Mira cómo te fue <kbd>Intro</kbd>',
  'stampa.tutte-giuste': 'Todas bien. Las respuestas las calculó Lode.',
  'stampa.da-rinforzare': 'Para reforzar: {nomi}. Vuelve mañana.',
  'stampa.secondi': { one: '{n} segundo', other: '{n} segundos' },
  'stampa.ancora-una': 'Otra más',
  'stampa.sintesi': '¿Qué imprime? {punti} de {tot}',
};
