// Textos de la sincronización entre ordenadores (español): qué va cifrado y qué queda en claro, la línea de estado y los
// avisos (docs/SINCRONIZZAZIONE.md §10.7 y §12). El README dice lo mismo: ver js/sync-testi.js.
export default {
  'sync.cifrati': 'los datos de Lode en el diario (exámenes, notas, tarjetas y repasos, sesiones, perfil, ajustes): no las páginas para Obsidian que Lode saca de ellos, aquí abajo',
  'sync.in-chiaro': [
    'apuntes, «Sbobine», archivos para Anki, diarios de los proyectos',
    'Orario.md con las aulas',
    'las páginas que Lode escribe para Obsidian, sacadas justo de esos datos: «Esami» (notas, media, créditos y horas estudiadas por examen), «Memoria» (horas de estudio del mes, en qué franja del día estudias, la racha de días, las definiciones falladas y cuántas veces), «Home» (la próxima convocatoria, cuántas tarjetas hay para repasar), «Corsi», «Glossario»',
    'nombres, tamaños y horas de los archivos (cuándo estudias)',
    'cuántos ordenadores hay, cuántos archivos escribe cada uno y cuántas acciones hay en cada archivo (un archivo por día)',
    'el archivo del grupo (sal y comprobación de la contraseña, cuándo se creó y desde qué ordenador, la huella del dati.json anterior)',
    'cuándo cambió la contraseña',
    'el dati.json mínimo que dice «Actualiza Lode»',
  ],
  'sync.sul-computer': 'En el ordenador el diario de Lode queda en claro, protegido solo por tu cuenta del sistema.',
  'sync.cronologia': 'En el historial del servicio en la nube queda lo que pasó en claro antes de la contraseña.',
  'sync.dimenticata': 'Si olvidas la contraseña no se pierde nada: cada ordenador tiene sus datos en el disco. Con «He olvidado la contraseña» eliges una nueva, y los otros ordenadores te la pedirán.',
  'sync.nuova-password': 'Elige una contraseña nueva. Los otros ordenadores te la pedirán. No se pierde ningún dato: cada ordenador tiene los suyos en el disco.',
  'sync.smetti': 'Lode copiará el vault a una carpeta fuera de {servizio} y usará esa. Los otros ordenadores siguen sincronizándose entre ellos. Para dejarlo en todos, hazlo en cada ordenador.',
  'sync.la-cartella-cloud': 'la carpeta en la nube',
  'sync.prima': 'Antes de sincronizar, actualiza Lode en todos los ordenadores.',
  'sync.sperimentale': 'Es nueva y experimental: probada a fondo con un simulador de varios ordenadores y una nube traviesa, pero todavía no por muchos estudiantes. Antes de activarla, Lode guarda una copia de todo: el vault de ahora se queda donde está, intacto, y los datos de Lode van también a la carpeta «copie» de los datos de Lode. Si algo no cuadra, cuéntanoslo en GitHub (Issues de W1kicartel/Lode).',
  // la línea de estado
  'sync.spenta': 'Apagada · exámenes, notas y tarjetas se quedan en este ordenador',
  'sync.fermo': 'No se puede leer el diario de Lode en este ordenador.',
  'sync.solo-qui': 'Solo en este ordenador · sin sincronizar',
  'sync.la-tua-cartella': 'tu carpeta en la nube',
  'sync.stato-password': 'En pausa: escribe la contraseña para sincronizar.',
  'sync.rigenerato-altra': 'En otro ordenador se eligió otra contraseña al mismo tiempo: escribe esa.',
  'sync.rigenerato': 'En otro ordenador cambió la contraseña: escribe la nueva para sincronizar.',
  'sync.sparito': 'La carpeta de Lode en el vault ya no está: ¿la has movido o borrado?',
  'sync.in-arrivo': 'Recibiendo los datos de los otros ordenadores… ({dove})',
  'sync.da-migrare': 'Esperando los datos de la nube…',
  'sync.scrittura': 'El disco está lleno (o no se puede escribir): los últimos cambios esperan y lo vuelvo a intentar yo solo.',
  'sync.versione': 'Sincronizado con {dove} · otro ordenador tiene un Lode más nuevo: actualízalo',
  'sync.in-pari': 'Sincronizado con {dove}',
  'sync.in-pari-cifrato': 'Sincronizado con {dove} · cifrado',
  'sync.in-pari-ora': 'Sincronizado con {dove} · comprobado a las {ora}',
  'sync.in-pari-cifrato-ora': 'Sincronizado con {dove} · cifrado · comprobado a las {ora}',
  'sync.altro-stato': 'Sincronización: {stato}',
  'sync.in-avvio': 'arrancando',
  // los avisos
  'sync.avviso-clone': 'Este ordenador parece una copia de otro: desde ahora tiene un nombre nuevo. No se ha perdido nada.',
  'sync.avviso-orologio': 'El reloj de otro ordenador parece ir muy adelantado: revisa la fecha y la hora.',
  'sync.avviso-rovinato-mio': 'Un archivo de Lode de este ordenador en la carpeta en la nube estaba dañado o manipulado: lo he apartado y lo he rehecho desde el diario.',
  'sync.avviso-rovinato-altro': 'Un archivo de Lode de otro ordenador está dañado o manipulado: me lo salto hasta que se pueda leer.',
  'sync.avviso-scrittura': 'El disco está lleno o no se puede escribir: los últimos cambios todavía no están en el diario. Lo vuelvo a intentar cada cierto tiempo y cuando cierres Lode.',
  'sync.avviso-recupero': 'No se podía escribir el diario: los cambios de ese momento están en un archivo aparte en la carpeta de datos de Lode.',
  'sync.avviso-portachiavi': 'El Llavero no ha dado la contraseña de Lode (permiso denegado, o Lode actualizado): escríbela otra vez.',
  'sync.avviso-gruppi-doppi': 'En la carpeta en la nube hay dos grupos de Lode, uno cifrado y otro no: no los uno yo solo.',
  'sync.avviso-lode-vecchia': 'Una versión antigua de Lode escribió datos en .lode/dati.json: actualízala. No entran solos: hay una copia en la carpeta de datos de Lode, y los registros nuevos se importan con «Importar lo añadido».',
  'sync.avviso-altra-password': 'En otro ordenador se eligió otra contraseña al mismo tiempo: escribe esa.',
  'sync.avviso-manomesso': 'El archivo del grupo de Lode en la carpeta en la nube se cambió desde fuera (no cuadra con la contraseña): no lo uso. Revisa la carpeta en la nube.',
  'sync.avviso-gruppo-chiaro': 'El archivo del grupo de Lode dice «sin contraseña» pero los datos de los otros ordenadores están cifrados: ¿lo han manipulado? No publico nada hasta que vuelva a estar bien.',
  'sync.avviso-parametri': 'Este vault lo protegió un Lode más nuevo: actualízalo.',
};
