// Nombres del vault (js/nomi.js), español: carpetas, notas, secciones y palabras que Lode escribe en un vault nuevo y relee.
export default {
  // cartelle (create una volta, alla nascita del vault: poi restano quelle)
  'vaultnomi.cartella-lezioni': 'Clases',
  'vaultnomi.cartella-corsi': 'Asignaturas',
  'vaultnomi.cartella-sbobine': 'Transcripciones',
  'vaultnomi.cartella-anki': 'Anki',
  'vaultnomi.cartella-allegati': 'Adjuntos',
  'vaultnomi.cartella-materiali': 'Materiales',
  'vaultnomi.cartella-progetti': 'Proyectos',
  'vaultnomi.cartella-modelli': 'Plantillas',
  'vaultnomi.cartella-inbox': 'Entrada',
  // i «corsi» che Lode inventa quando non ce n'è uno (diventano cartelle e note)
  'vaultnomi.corso-sparsi': 'Notas sueltas',
  'vaultnomi.corso-videolezioni': 'Videoclases',
  'vaultnomi.corso-varie': 'Varios',
  // note (senza «.md»)
  'vaultnomi.nota-home': 'Inicio',
  'vaultnomi.nota-orario': 'Horario',
  'vaultnomi.nota-esami': 'Exámenes',
  'vaultnomi.nota-glossario': 'Glosario',
  'vaultnomi.nota-benvenuto': 'Bienvenida',
  'vaultnomi.nota-memoria': 'Memoria',
  'vaultnomi.nota-tasca': 'Repaso de bolsillo',
  'vaultnomi.modello-lezione': 'Clase',
  'vaultnomi.modello-esame': 'Examen',
  'vaultnomi.modello-ripasso': 'Repaso',
  // titoli delle sezioni che Lode scrive e rilegge
  'vaultnomi.sezione-appunti': 'Apuntes',
  'vaultnomi.sezione-stella': '★ Para el examen',
  'vaultnomi.sezione-definizioni': 'Definiciones',
  'vaultnomi.sezione-domande': 'Preguntas para el profe',
  'vaultnomi.sezione-trascrizione': 'Transcripción',
  'vaultnomi.sezione-riordinati': 'Apuntes ordenados por Lode',
  'vaultnomi.titolo-note-per-lode': 'Notas para Lode',
  'vaultnomi.titolo-cosa-ho-capito': 'Lo que he entendido',
  'vaultnomi.titolo-cosa-so-davvero': 'Lo que de verdad sé',
  'vaultnomi.titolo-informatica': 'Informática',
  'vaultnomi.titolo-ripasso-in-tasca': 'Repaso de bolsillo',
  'vaultnomi.titolo-orario': 'Horario de clases',
  'vaultnomi.titolo-lezioni': 'Clases',
  'vaultnomi.titolo-stelle-ultime': '★ Para el examen, lo último',
  // il ripasso in tasca: il titolo della risposta e le due caselle (il giro le rilegge)
  'vaultnomi.parola-risposta': 'Respuesta',
  'vaultnomi.parola-sapevo': 'lo sabía',
  'vaultnomi.parola-non-sapevo': 'no lo sabía',
  // la nota dell'orario: colonne, giorni (domenica per primo) e la riga che spiega
  'vaultnomi.orario-colonne': ['Asignatura', 'Días', 'Inicio', 'Fin', 'Aula'],
  'vaultnomi.giorni-brevi': ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
  'vaultnomi.orario-spiega': 'Lode lo lee para saber cuándo estás en clase. Puedes cambiarlo aquí o desde la barra («clase cálculo 2 lunes y miércoles 9-11 aula 7»).',
  // i commenti dentro le note nuove
  'vaultnomi.commento-definizioni': 'Una por línea: - **Término**: definición. Lode hace con ellas juegos de memoria y tarjetas.',
  'vaultnomi.commento-corso': 'Escribe arriba o abajo: el recuadro de Lode (clases, ★, examen) se actualiza solo y el resto no lo toca.',
  'vaultnomi.commento-cosa-ho-capito': 'Esta parte es tuya: Lode nunca la toca. Lo que has entendido hoy, lo que todavía no te cuadra.',
  'vaultnomi.segnalibro-memoria': 'Lo que Lode sabe de mí',
  // i modelli di Obsidian e le note che nascono col vault
  'vaultnomi.esame-programma': 'Temario',
  'vaultnomi.esame-domande': 'Preguntas que siempre caen',
  'vaultnomi.esame-domande-commento': 'Las que oyes a los compañeros o encuentras en exámenes antiguos. Lode las usa para preguntarte.',
  'vaultnomi.esame-esercizi': 'Ejercicios tipo',
  'vaultnomi.esame-manca': 'Lo que me falta',
  'vaultnomi.ripasso-tre-righe': 'En tres líneas',
  'vaultnomi.ripasso-commento-definizioni': '- **Término**: definición. Acaban en los juegos de Lode.',
  'vaultnomi.ripasso-collegamenti': 'Enlaces',
  'vaultnomi.ripasso-commento-collegamenti': 'Las clases y los conceptos relacionados: [[...]]',
  'vaultnomi.memoria-titolo': 'Lo que sé de ti',
  'vaultnomi.memoria-commento': 'Esta nota la escribe Lode después de cada juego. La sección «{sezione}» es tuya: la leo cada vez que uso la IA.',
  'vaultnomi.memoria-in-breve': 'En resumen',
  'vaultnomi.memoria-ancora-niente': 'Todavía nada: apunta algunas definiciones en clase y juega una partida.',
  'vaultnomi.memoria-note-commento': 'Escribe aquí cómo quieres que te ayude: «explícamelo con ejemplos prácticos», «frases cortas», «el oral de Cálculo es muy teórico».',
  'vaultnomi.benvenuto-firma': 'lo ha preparado **Lode**',
  'vaultnomi.benvenuto-testo': '# Bienvenido a tu vault\n\nEste vault {firma}, el asistente que vive en la parte de arriba de la pantalla. Es un vault normal de Obsidian: las notas son tuyas, en Markdown, y se quedan en este ordenador.\n\n## Cómo trabajan juntos\n- **En clase** Lode sabe cuándo estás en clase (por el [[{orario}]]) y tiene lista la nota de la clase en `{lezioni}/<asignatura>/`. Desde la barra apuntas al vuelo:\n  - **{stella}** (⌃⌥S): lo que el profe ha dicho que preguntará;\n  - **Definición** (⌃⌥D): «término: definición»;\n  - **Pregunta** (⌃⌥Q): para hacerle al profe.\n- **Los apuntes** los escribes aquí, en Obsidian, como siempre. Las definiciones que pones en la sección «{definizioni}» (`- **Término**: definición`) o escritas como `Término :: definición` Lode las encuentra solo.\n- **En casa** la barra te propone dos minutos de juego con las definiciones de la última clase, justo cuando están a punto de escaparse.\n- **[[{memoria}]]** (en `{lode}/`) es lo que Lode ha aprendido de ti: definiciones seguras, por reforzar, cómo estudias. En la sección «{notePerLode}» puedes decirle cómo quieres que te ayude.\n\n## Atajos\n| | Mac | Windows |\n|---|---|---|\n| Abrir Lode y escribir | ⌥ Espacio | Ctrl ⇧ Espacio |\n| {stella} | ⌃⌥ S | Ctrl Alt S |\n| Definición | ⌃⌥ D | Ctrl Alt D |\n| Pregunta para el profe | ⌃⌥ Q | Ctrl Alt Q |\n| Juego de memoria | ⌃⌥ G | Ctrl Alt G |\n',
  // frasi della barra che citano un nome del vault: il nome arriva dal vault, non dalla lingua della barra
  'vaultnomi.frase-orario-nel-vault': 'El horario también está en el vault, en «{nota}»: puedes cambiarlo desde Obsidian.',
  'vaultnomi.frase-nella-cartella': 'Está en la carpeta {cartella} del vault.',
  'vaultnomi.frase-riordinati-nota': 'Van a la nota, en «{sezione}», debajo de la transcripción (que se queda). Los ha escrito {motore}: revísalos.',
};
