// Textos de las páginas que Lode escribe en el vault para el estudiante (español): Home, Exámenes, Glosario, las páginas
// de las asignaturas y la Memoria. No están los nombres de notas, carpetas, secciones y claves que el código vuelve a
// leer: esos siguen como están en el código (serán la tabla NOMI).
export default {
  // la memoria
  'vault.prop-gioco': 'juegos',
  'vault.prop-ripasso': 'repaso de tarjetas',
  'vault.prop-stelle': 'releer las ★',
  'vault.prop-orale': 'preguntas rápidas',
  'vault.prop-focus': 'focus',
  'vault.prop-stampa': 'qué imprime',
  'vault.prop-voce': '{nome} ({si} de {tot})',
  'vault.memoria-proposte': 'De las propuestas de Lode, sobre todo aceptas: {elenco}.',
  'vault.memoria-titolo': 'Lo que sé de ti',
  'vault.memoria-commento': 'Esta nota la escribe Lode. Puedes leerla y también corregirla: la sección «{sezione}» la leo cada vez que uso la IA.',
  'vault.titolo-in-breve': 'En resumen',
  'vault.memoria-lezioni': { one: '{n} clase con apuntes', other: '{n} clases con apuntes' },
  'vault.memoria-definizioni': { one: '{n} definición', other: '{n} definiciones' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni}: **{sicure} dominadas**, {deboli} por reforzar, {mai} sin jugar todavía.',
  'vault.memoria-serie': { one: 'Racha de estudio: {n} día seguido. Este mes: {h} h.', other: 'Racha de estudio: {n} días seguidos. Este mes: {h} h.' },
  'vault.memoria-fascia': 'Estudias sobre todo por la **{fascia}**.',
  'vault.fascia-mattina': 'mañana',
  'vault.fascia-pomeriggio': 'tarde',
  'vault.fascia-sera': 'noche',
  'vault.titolo-da-rinforzare': 'Por reforzar',
  'vault.sbagliata': { one: 'fallada {n} vez de {tot}', other: 'fallada {n} veces de {tot}' },
  'vault.niente-per-ora': 'Nada, por ahora.',
  'vault.titolo-sicure': 'Dominadas',
  'vault.sicure-vuoto': 'Ninguna todavía: juega alguna partida.',
  'vault.ancora-nessuna': 'Ninguna todavía.',
  'vault.note-commento': 'Escribe aquí cómo quieres que te ayude: «explícamelo con ejemplos prácticos», «soy disléxico, frases cortas», «el oral de Cálculo es con García, muy teórico».',
  // Home
  'vault.home-carte': { one: '{n} tarjeta para repasar', other: '{n} tarjetas para repasar' },
  'vault.alias-memoria': 'Lo que Lode sabe de mí',
  'vault.alias-benvenuto': 'Cómo funciona',
  'vault.titolo-oggi': 'Hoy',
  'vault.aula': 'aula {aula}',
  'vault.niente-lezioni-oggi': 'Hoy no hay clases.',
  'vault.titolo-corsi': 'Asignaturas',
  'vault.n-lezioni': { one: '{n} clase', other: '{n} clases' },
  'vault.idoneo': 'apto',
  'vault.voto-e-lode': '{voto} con matrícula',
  'vault.appello': 'examen el {data}',
  'vault.corsi-vuoto': 'Añade el horario desde la barra: «clase cálculo 2 lunes y miércoles 9-11 aula 7».',
  'vault.titolo-ultime-lezioni': 'Últimas clases',
  'vault.definizioni-n': { one: '{n} definición', other: '{n} definiciones' },
  'vault.titolo-carriera': 'Carrera',
  'vault.carriera': 'Media **{media}** · nota base de grado **{base}**/110 · {cfu} de {tot} créditos → {esami}',
  // Esami
  'vault.titolo-prossimi-appelli': 'Próximos exámenes',
  'vault.tabella-appelli': '| Examen | Fecha | En | Créditos | Horas estudiadas |',
  'vault.ore-di': '{fatte} de {tot} h',
  'vault.nessun-appello': 'Ningún examen apuntado.',
  'vault.senza-data': 'Sin fecha: {elenco}.',
  'vault.titolo-libretto': 'Expediente',
  'vault.tabella-libretto': '| Examen | Créditos | Nota | Fecha |',
  'vault.voto-l': '{voto} MH',
  'vault.libretto-piede': 'Media ponderada **{media}** · nota base de grado **{base}**/110 · {cfu} de {tot} créditos',
  'vault.libretto-vuoto': 'Todavía no has hecho ningún examen.',
  // Glossario
  'vault.n-definizioni': { one: '{n} definición', other: '{n} definiciones' },
  'vault.da-rinforzare': '*por reforzar*',
  'vault.glossario-vuoto': 'Las definiciones de las clases aparecen aquí, en orden alfabético, separadas por asignatura.',
  // la pagina del corso
  'vault.corso-cfu': '**{cfu} créditos**',
  'vault.corso-voto': 'nota {voto}',
  'vault.corso-voto-lode': 'nota {voto} con matrícula',
  'vault.corso-appello': { one: 'examen el **{data}** (en {n} día) · {fatte} de {tot} h estudiadas', other: 'examen el **{data}** (en {n} días) · {fatte} de {tot} h estudiadas' },
  'vault.corso-lezioni': 'Clases: {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} aula {aula}',
  'vault.lezioni-vuoto': 'Ninguna todavía: la primera aparece cuando apuntas algo en clase.',
};
