// I comandi in tedesco per il banco (test/comandi-lingue.mjs): le stesse azioni dei casi italiani (test/comandi/it.mjs),
// dette come le direbbe uno studente in Germania, Austria o Svizzera (informale, di fretta, anche senza dieresi), con lo
// stesso risultato. Gli esami sono quelli tedeschi del libretto del banco (Mathe 2, Physik 2, Datenbanken, Privatrecht,
// Englisch B2).
import { E, prossimo, giornoDetto, giorno, prossimoGiorno } from './aiuto.mjs';

const ERR = "liste.c:42:5: error: 'knoten' undeclared";
export const CASI = [
  // informatica: l'errore incollato e «Projekt verfolgen»
  ['erklär den Fehler', { tipo: 'errore', testo: null }],
  ['Erkläre mir diesen Fehler.', { tipo: 'errore', testo: null }],
  ['was bedeutet der Fehler?', { tipo: 'errore', testo: null }],
  ['erklaer den fehler', { tipo: 'errore', testo: null }],
  [`erklär den Fehler: ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`erklär mir die Fehlermeldung ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['Projekt verfolgen', { tipo: 'progetto', azione: 'segui' }],
  ['Verfolge das Projekt.', { tipo: 'progetto', azione: 'segui' }],
  ['was hat sich geändert', { tipo: 'progetto', azione: 'cambiato' }],
  ['Änderungen zeigen', { tipo: 'progetto', azione: 'cambiato' }],
  ['was hat sich geaendert?', { tipo: 'progetto', azione: 'cambiato' }],
  ['getestet?', { tipo: 'progetto', azione: 'provato' }],
  ['hab ichs getestet', { tipo: 'progetto', azione: 'provato' }],
  ['Projekt testen', { tipo: 'progetto', azione: 'prova' }],
  ['Code testen', { tipo: 'progetto', azione: 'prova' }],
  ['kompilier den Code', { tipo: 'progetto', azione: 'prova' }],
  ['hör auf lab3 zu verfolgen', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['lab3 nicht mehr verfolgen', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['bereite mich auf die Abnahme von lab3 vor', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  ['Testat für lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  ['ich bin bereit für die Verteidigung von lab4', { tipo: 'progetto', azione: 'discussione', nome: 'lab4' }],
  // la lingua della barra
  ['Sprache Englisch', { tipo: 'lingua', codice: 'en' }],
  ['stell die Sprache auf Italienisch', { tipo: 'lingua', codice: 'it' }],
  ['auf Spanisch umstellen', { tipo: 'lingua', codice: 'es' }],
  ['Sprache: français', { tipo: 'lingua', codice: 'fr' }],
  ['Sprache Französisch', { tipo: 'lingua', codice: 'fr' }],
  ['wechsel zu portugiesisch', { tipo: 'lingua', codice: 'pt' }],
  ['auf Deutsch bitte', { tipo: 'lingua', codice: 'de' }],
  // il timer
  ['Hilfe', { tipo: 'aiuto' }],
  ['was kannst du', { tipo: 'aiuto' }],
  ['Befehle', { tipo: 'aiuto' }],
  ['stopp', { tipo: 'ferma' }],
  ['Timer stoppen', { tipo: 'ferma' }],
  ['genug', { tipo: 'ferma' }],
  ['hör auf mit dem Pomodoro', { tipo: 'ferma' }],
  ['Pause', { tipo: 'sospendi' }],
  ['Timer pausieren', { tipo: 'sospendi' }],
  ['warte kurz', { tipo: 'sospendi' }],
  ['weiter', { tipo: 'riprendi' }],
  ['mach weiter', { tipo: 'riprendi' }],
  ['fortsetzen', { tipo: 'riprendi' }],
  // Anki e il ripasso in tasca
  ['nach Anki exportieren', { tipo: 'anki', corso: null }],
  ['Nach Anki exportieren.', { tipo: 'anki', corso: null }],
  ['exportier meine Physik 2 Karten nach Anki', { tipo: 'anki', corso: 'physik 2' }],
  ['Karten von Mathe 2 nach Anki exportieren', { tipo: 'anki', corso: 'mathe 2' }],
  ['Anki Physik 2', { tipo: 'anki', corso: 'physik 2' }],
  ['Karten fürs Handy', { tipo: 'tasca' }],
  ['Karten fuers Handy jeden Abend', { tipo: 'tasca', sera: true }],
  ['Karten fürs Handy nur wenn ich frage', { tipo: 'tasca', sera: false }],
  ['schalt die Taschenwiederholung aus', { tipo: 'tasca', sera: false }],
  // il programma, le domande e i temi d'esame, la prova generale
  ['Prüfungsstoff für Mathe 2', { tipo: 'programma', esame: E('Mathe 2'), nomeDetto: 'mathe 2', testo: '' }],
  ['Stoffplan', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['Mathe 2 Prüfungsstoff:\n1. Grenzwerte\n2. Ableitungen', { tipo: 'programma', esame: E('Mathe 2'), nomeDetto: 'mathe 2', testo: '1. Grenzwerte\n2. Ableitungen' }],
  ['Pruefungsstoff Physik zwei', { tipo: 'programma', esame: E('Physik 2'), nomeDetto: 'physik 2', testo: '' }],
  ['lass mich erklären: Green', { tipo: 'spiego', q: 'green' }],
  ['ich erklär dir die Potenzreihen.', { tipo: 'spiego', q: 'potenzreihen' }],
  ['lass mich erklären', { tipo: 'spiego', q: '' }],
  ['lass mich dir die Taylorreihe erklären', { tipo: 'spiego', q: 'taylorreihe' }],
  ['Prüfungsfragen für Mathe 2: Satz von Green?', { tipo: 'domande', esame: E('Mathe 2'), nomeDetto: 'mathe 2', testo: 'Satz von Green?' }],
  ['Gedächtnisprotokolle Datenbanken\nNormalformen?', { tipo: 'domande', esame: E('Datenbanken'), nomeDetto: 'datenbanken', testo: 'Normalformen?' }],
  ['Klausurfragen', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ['Altklausuren für Mathe 2: Aufgabe 1. Bestimme den Grenzwert', { tipo: 'temi', esame: E('Mathe 2'), nomeDetto: 'mathe 2', testo: 'Aufgabe 1. Bestimme den Grenzwert' }],
  ['alte Klausuren von Physik 2', { tipo: 'temi', esame: E('Physik 2'), nomeDetto: 'physik 2', testo: '' }],
  ['gib mir eine Aufgabe', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ['Aufgabe für Mathe 2', { tipo: 'temi', esame: E('Mathe 2'), nomeDetto: 'mathe 2', testo: '' }],
  ['Probeklausur für Mathe 2', { tipo: 'prova', esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['ganze Altklausur für Physik 2', { tipo: 'prova', esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['lass mich eine Probeklausur schreiben', { tipo: 'prova', esame: null, nomeDetto: '' }],
  // in aula
  ['★ der Satz von Green kommt immer dran', { tipo: 'stella', testo: 'der Satz von Green kommt immer dran' }],
  ['wichtig: Reihen', { tipo: 'stella', testo: 'Reihen' }],
  ['klausurrelevant: Satz von Green', { tipo: 'stella', testo: 'Satz von Green' }],
  ['Prüfung: Kettenregel', { tipo: 'stella', testo: 'Kettenregel' }],
  ['def: Gradient = Vektor der partiellen Ableitungen', { tipo: 'definizione', termine: 'Gradient', testo: 'Vektor der partiellen Ableitungen' }],
  ['Definition Nukleophil bedeutet elektronenreiches Teilchen.', { tipo: 'definizione', termine: 'Nukleophil', testo: 'elektronenreiches Teilchen' }],
  ['definiere Homomorphismus: strukturerhaltende Abbildung', { tipo: 'definizione', termine: 'Homomorphismus', testo: 'strukturerhaltende Abbildung' }],
  ['Frage an den Prof warum brauchen wir Stetigkeit?', { tipo: 'domanda', testo: 'warum brauchen wir Stetigkeit?' }],
  ['? warum konvergiert das', { tipo: 'domanda', testo: 'warum konvergiert das' }],
  ['Frage: was ist mit Reihen?', { tipo: 'domanda', testo: 'was ist mit Reihen?' }],
  // l'orario, il lavoro, le ore libere
  ['Vorlesung Mathe 2 Montag und Mittwoch 9-11 Raum 7', { tipo: 'orario', corso: 'Mathe 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['VL Physik 2 freitags von 14 bis 16 Uhr', { tipo: 'orario', corso: 'Physik 2', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['Kurs Privatrecht Di 10-12 Hörsaal B', { tipo: 'orario', corso: 'Privatrecht', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ['Seminar Neuere Geschichte dienstags 14-16 Uhr Raum 0.07', { tipo: 'orario', corso: 'Neuere geschichte', giorni: [2], inizio: '14:00', fine: '16:00', aula: '0.07' }],
  ['Übung Bürgerliches Recht Do 8:15-9:45', { tipo: 'orario', corso: 'Bürgerliches recht', giorni: [4], inizio: '08:15', fine: '09:45', aula: '' }],
  ['Stundenplan', { tipo: 'vediOrario' }],
  ['meine Vorlesungen', { tipo: 'vediOrario' }],
  ['wann hab ich Vorlesung', { tipo: 'vediOrario' }],
  ['ich arbeite Montag Mittwoch Freitag 14-19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['ich arbeite montags 9-13 und mittwochs 15-19 Uhr', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['ich jobbe Sa 10-16 im Café', { tipo: 'lavoro', azione: 'aggiungi', giorni: [6], inizio: '10:00', fine: '16:00' }],
  ['meine Schichten sind Samstag 18-23', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ['ich arbeite nicht mehr', { tipo: 'lavoro', azione: 'togli' }],
  ['wann arbeite ich', { tipo: 'lavoro', azione: 'vedi' }],
  ['Donnerstag arbeite ich nicht', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['ich arbeite am Donnerstag nicht', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['am Samstag arbeite ich zusätzlich 18-23', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ['an Arbeitstagen lerne ich höchstens 2 Stunden', { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ['ich lerne von 10 bis 22', { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['ich lerne zwischen 9 und 18 Uhr', { tipo: 'lavoro', azione: 'finestra', da: '09:00', a: '18:00' }],
  ['Wochenplan', { tipo: 'ore' }],
  ['meine freie Zeit', { tipo: 'ore' }],
  ['wie viel Zeit hab ich zum Lernen', { tipo: 'ore' }],
  // «Was gibt das aus?», giochi, appunti, trascrizione
  ['was gibt das aus', { tipo: 'stampa' }],
  ['Aufgaben in C', { tipo: 'stampa' }],
  ['was gibt das in Python aus', { tipo: 'stampa', lingua: 'python' }],
  ['trainier mich in Java', { tipo: 'stampa', lingua: 'java' }],
  ['spielen', { tipo: 'gioco', corso: null }],
  ['spiel Mathe 2', { tipo: 'gioco', corso: 'mathe 2' }],
  ['lass uns Physik 2 spielen', { tipo: 'gioco', corso: 'physik 2' }],
  ['trainier mich', { tipo: 'gioco', corso: null }],
  ['Notizen', { tipo: 'appunti' }],
  ['öffne meine Notizen', { tipo: 'appunti' }],
  ['Notizen von heute', { tipo: 'appunti' }],
  ['Vorlesung transkribieren', { tipo: 'trascrivi' }],
  ['starte die Transkription', { tipo: 'trascrivi' }],
  ['transkribier die Vorlesung', { tipo: 'trascrivi' }],
  ['Videovorlesung Privatrecht transkribieren', { tipo: 'trascrivi', sorgente: 'computer', corso: 'privatrecht' }],
  ['transkribiere die Videovorlesung von Mathe 2', { tipo: 'trascrivi', sorgente: 'computer', corso: 'mathe 2' }],
  ['Vorlesung vom Computer', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['nochmal', { tipo: 'ripeti', sec: 60 }],
  ['wiederhol die letzten 30 Sekunden', { tipo: 'ripeti', sec: 30 }],
  ['was hat der Prof gesagt', { tipo: 'ripeti', sec: 60 }],
  ['nochmal ausschalten', { tipo: 'spegniRipeti' }],
  ['schalt das Wiederholen aus', { tipo: 'spegniRipeti' }],
  ['Wiederholen deaktivieren', { tipo: 'spegniRipeti' }],
  ['Vorschläge oft', { tipo: 'proposte', livello: 'spesso' }],
  ['Vorschläge ausschalten', { tipo: 'proposte', livello: 'mai' }],
  ['Vorschlaege selten', { tipo: 'proposte', livello: 'poco' }],
  ['Vorschläge normal', { tipo: 'proposte', livello: 'normale' }],
  ['schlag mir was vor', { tipo: 'proponi' }],
  ['was soll ich jetzt machen', { tipo: 'proponi' }],
  ['was soll ich wiederholen', { tipo: 'proponi' }],
  ['Mitschrift teilen', { tipo: 'condividi', corso: null }],
  ['schick die Vorlesung an meine Kommilitonen', { tipo: 'condividi', corso: null }],
  ['teil die Vorlesung von Physik 2', { tipo: 'condividi', corso: 'physik 2' }],
  ['Transkription beenden', { tipo: 'fineTrascrizione' }],
  ['die Vorlesung ist vorbei', { tipo: 'fineTrascrizione' }],
  ['Ende der Vorlesung', { tipo: 'fineTrascrizione' }],
  ['Transkription pausieren', { tipo: 'pausaTrascrizione' }],
  ['pausier die Aufnahme', { tipo: 'pausaTrascrizione' }],
  ['halt die Aufnahme an', { tipo: 'pausaTrascrizione' }],
  ['Transkription fortsetzen', { tipo: 'riprendiTrascrizione' }],
  ['setz die Aufnahme fort', { tipo: 'riprendiTrascrizione' }],
  ['mach mit der Aufnahme weiter', { tipo: 'riprendiTrascrizione' }],
  ['Vorlesung aufräumen', { tipo: 'riordina', corso: null }],
  ['räum meine Notizen von Physik 2 auf', { tipo: 'riordina', corso: 'physik 2' }],
  ['Transkript aufraeumen', { tipo: 'riordina', corso: null }],
  ['Vorlesung abschließen', { tipo: 'chiudiLezione', corso: null }],
  ['schließ die Vorlesung von Mathe 2 ab', { tipo: 'chiudiLezione', corso: 'mathe 2' }],
  ['Definitionen rausziehen', { tipo: 'chiudiLezione', corso: null }],
  // la tua AI, la sincronizzazione, Obsidian, il diario
  ['KI', { tipo: 'ai', fornitore: null }],
  ['verbinde ChatGPT', { tipo: 'ai', fornitore: 'openai' }],
  ['nimm Gemini', { tipo: 'ai', fornitore: 'google' }],
  ['mein API-Schlüssel', { tipo: 'ai', fornitore: null }],
  ['Sync', { tipo: 'sincronizza', cosa: null }],
  ['zwischen Computern synchronisieren', { tipo: 'sincronizza', cosa: null }],
  ['Sync ausschalten', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['Sync auf diesem Rechner stoppen', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['Passwort ändern', { tipo: 'sincronizza', cosa: 'password' }],
  ['ich hab mein Passwort vergessen', { tipo: 'sincronizza', cosa: 'password' }],
  ['entsperren', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['anderen Rechner verbinden', { tipo: 'sincronizza', cosa: 'altro' }],
  ['ich nutze Lode schon auf einem anderen Laptop', { tipo: 'sincronizza', cosa: 'collega' }],
  ['Obsidian einrichten', { tipo: 'prepara', cosa: 'obsidian' }],
  ['installier das Modell', { tipo: 'prepara', cosa: 'cervello' }],
  ['einrichten', { tipo: 'prepara', cosa: null }],
  ['schalt das Tagebuch aus', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['Tagebuch von lab3 einschalten', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ['schreib kein Projekttagebuch für lab3', { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['Projekttagebuch', { tipo: 'diario', progetto: null }],
  ['öffne das Projekttagebuch lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['Tagebuch des Projekts', { tipo: 'diario', progetto: null }],
  ['öffne Glossar', { tipo: 'naviga', q: 'glossar' }],
  ['Glossar öffnen', { tipo: 'naviga', q: 'glossar' }],
  ['geh zu Home', { tipo: 'naviga', q: 'home' }],
  ['Startseite', { tipo: 'naviga', q: 'home' }],
  ['Seiten', { tipo: 'naviga', q: '' }],
  ['zeig mir meine Noten', { tipo: 'libretto' }],
  // carte, voti, esami
  ['Karte: Satz von Green = Aussage', { tipo: 'carta', esame: null, fronte: 'Satz von Green', retro: 'Aussage' }],
  ['Karteikarte für Mathe 2: Gradient -> Vektor', { tipo: 'carta', esame: E('Mathe 2'), fronte: 'Gradient', retro: 'Vektor' }],
  ['Kärtchen: Schwarz | gemischte Ableitungen', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'gemischte Ableitungen' }],
  ['was wenn ich 30 in Mathe 2 bekomme', { tipo: 'simula', voto: 30, lode: false, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['und wenn ich in Physik 2 ne 28 schreibe', { tipo: 'simula', voto: 28, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['was wäre, wenn ich dreißig mit Lode in Datenbanken krieg', { tipo: 'simula', voto: 30, lode: true, esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['ich hab 28 in Physik 2', { tipo: 'voto', voto: 28, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['30 cum laude in Mathe 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['Ich habe achtundzwanzig in Physik 2 bekommen.', { tipo: 'voto', voto: 28, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['hab in Datenbanken ne 27 geschrieben', { tipo: 'voto', voto: 27, lode: false, esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['ich hab Englisch bestanden', { tipo: 'idoneita', esame: E('Englisch B2'), nomeDetto: 'englisch' }],
  ['Englisch geschafft', { tipo: 'idoneita', esame: E('Englisch B2'), nomeDetto: 'englisch' }],
  ['hab die Prüfung in Englisch bestanden', { tipo: 'idoneita', esame: E('Englisch B2'), nomeDetto: 'englisch' }],
  ['Fokus 50 auf Mathe 2', { tipo: 'focus', min: 50, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['lerne Datenbanken eine Stunde', { tipo: 'focus', min: 60, esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['Fokus fünfzig Minuten Physik zwei.', { tipo: 'focus', min: 50, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['starte einen 25-Minuten-Pomodoro für Mathe 2', { tipo: 'focus', min: 25, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['ne halbe Stunde Physik 2 pauken', { tipo: 'focus', min: 30, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['1h30 Fokus auf Datenbanken', { tipo: 'focus', min: 90, esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['Fokus', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['Prüfung Datenbanken am 15. Januar 9 ECTS', { tipo: 'esame', nome: 'datenbanken', cfu: 9, data: prossimo(15, 0), esistente: E('Datenbanken') }],
  ['Klausur Physik 2 am 3.2. mit 6 LP', { tipo: 'esame', nome: 'physik 2', cfu: 6, data: prossimo(3, 1), esistente: E('Physik 2') }],
  ['die Prüfung in Mathe 2 ist am 15. Jänner', { tipo: 'esame', nome: 'Mathe 2', cfu: null, data: prossimo(15, 0), esistente: E('Mathe 2') }],
  ['ich schreibe Mathe 2 am 13. Oktober', { tipo: 'esame', nome: 'Mathe 2', cfu: null, data: prossimo(13, 9), esistente: E('Mathe 2') }],
  ['Mathe 2 wurde auf den 20. Januar verschoben', { tipo: 'esame', nome: 'Mathe 2', cfu: null, data: prossimo(20, 0), esistente: E('Mathe 2') }],
  ['neue Prüfung Neuere Geschichte', { tipo: 'esame', nome: 'neuere geschichte', cfu: null, data: null, esistente: null }],
  ['Prüfung Bürgerliches Recht am 2. März', { tipo: 'esame', nome: 'bürgerliches recht', cfu: null, data: prossimo(2, 2), esistente: null }],
  ['was brauche ich für 110', { tipo: 'serve', base: 110 }],
  ['was brauch ich für hundertzehn', { tipo: 'serve', base: 110 }],
  ['welchen Schnitt brauche ich für 105', { tipo: 'serve', base: 105 }],
  ['Schnitt', { tipo: 'libretto' }],
  ['meine Noten', { tipo: 'libretto' }],
  ['wie viele ECTS hab ich', { tipo: 'libretto' }],
  ['Mathe 2 wiederholen', { tipo: 'ripasso', esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['Karten', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['lass uns Physik 2 wiederholen', { tipo: 'ripasso', esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['Wiederholung Datenbanken', { tipo: 'ripasso', esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  // gli agenti, Moodle, orale e crocette
  ['Agenten', { tipo: 'agenti', agente: null }],
  ['verbinde Claude Code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['Cursor trennen', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['die Agenten verbinden', { tipo: 'agenti', agente: null, togli: false }],
  ['was hat der Agent gemacht', { tipo: 'turnoAgente' }],
  ['was hat Claude Code gemacht', { tipo: 'turnoAgente' }],
  ['letzter Zug', { tipo: 'turnoAgente' }],
  ['Moodle verbinden', { tipo: 'moodle', cosa: null }],
  ["was gibt's Neues auf Moodle", { tipo: 'moodle', cosa: 'novita' }],
  ['Abgaben', { tipo: 'moodle', cosa: 'scadenze' }],
  ['Moodle trennen', { tipo: 'moodle', cosa: 'scollega' }],
  ['Kurse auf Moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ['Quiz zu Mathe 2', { tipo: 'crocette', esame: E('Mathe 2'), nomeDetto: 'mathe 2', simulazione: false }],
  ['Klausur simulieren für Mathe 2', { tipo: 'crocette', esame: E('Mathe 2'), nomeDetto: 'mathe 2', simulazione: true }],
  ['Prüfungssimulation für Mathe 2', { tipo: 'crocette', esame: E('Mathe 2'), nomeDetto: 'mathe 2', simulazione: true }],
  ['Multiple Choice', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['Kreuzerltest Privatrecht', { tipo: 'crocette', esame: E('Privatrecht'), nomeDetto: 'privatrecht', simulazione: false }],
  ['frag mich zu Datenbanken ab', { tipo: 'orale', esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['mündliche Prüfung für Physik 2 simulieren', { tipo: 'orale', esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['frag mich ab', { tipo: 'orale', esame: null, nomeDetto: '' }],
  ['Prüfungen', { tipo: 'esami' }],
  ['meine Klausuren', { tipo: 'esami' }],
  ['nächste Prüfungen', { tipo: 'esami' }],
  ['heute', { tipo: 'oggi' }],
  ['Plan', { tipo: 'oggi' }],
  ['was soll ich heute lernen', { tipo: 'oggi' }],
  ['Mathe 2', { tipo: 'apriEsame', esame: E('Mathe 2') }],
  ['Datenbanken', { tipo: 'apriEsame', esame: E('Datenbanken') }],
  ['Physik', { tipo: 'apriEsame', esame: E('Physik 2') }],
  // dalla verifica: l'ordine tedesco (la data in testa, «mit 27 bestanden»), gli avverbi, «nächste Woche», la data in mezzo
  ['Pruefung Datenbanken naechste Woche', { tipo: 'esame', nome: 'datenbanken', cfu: null, data: giorno(7), esistente: E('Datenbanken') }],
  ['Klausur am 12.2. in Mathe 2', { tipo: 'esame', nome: 'mathe 2', cfu: null, data: prossimo(12, 1), esistente: E('Mathe 2') }],
  ['Am Freitag hab ich Klausur in Physik 2', { tipo: 'esame', nome: 'Physik 2', cfu: null, data: prossimoGiorno(5), esistente: E('Physik 2') }],
  ['Morgen schreib ich Datenbanken', { tipo: 'esame', nome: 'Datenbanken', cfu: null, data: giorno(1), esistente: E('Datenbanken') }],
  ['übermorgen Prüfung Mathe 2', { tipo: 'esame', nome: 'Mathe 2', cfu: null, data: giorno(2), esistente: E('Mathe 2') }],
  ['Morgen ist Mathe 2 Klausur', { tipo: 'esame', nome: 'Mathe 2', cfu: null, data: giorno(1), esistente: E('Mathe 2') }],
  ['nächsten Dienstag Klausur Statistik', { tipo: 'esame', nome: 'statistik', cfu: null, data: prossimoGiorno(2), esistente: null }],
  ['ich hab Physik 2 mit 27 bestanden', { tipo: 'voto', voto: 27, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['Physik 2 hab ich mit 27 bestanden', { tipo: 'voto', voto: 27, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['Mathe 2 bestanden mit 30 mit Lode', { tipo: 'voto', voto: 30, lode: true, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['lerne gerade für Physik 2', { tipo: 'focus', min: null, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['pauken für Mathe 2', { tipo: 'focus', min: null, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['mal Pause', { tipo: 'sospendi' }],
  ['hab 28 im Schnitt', { tipo: 'libretto' }],
  ['focus 50 on Physik 2', { tipo: 'focus', min: 50, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['ich erklär dir jetzt Integrale', { tipo: 'spiego', q: 'integrale' }],
  ['Videovorlesung transkribieren', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['stell die Sprache auf Japanisch', { tipo: 'lingua', codice: null }],
  // i voti tedeschi (1,0-5,0) e degli altri sistemi: il numero detto; l'obiettivo anche a parole («Bestnote»)
  ['ich hab ne 1,7 in Mathe 2', { tipo: 'voto', voto: 1.7, lode: false, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['ich habe eine 2,3 in Physik 2 bekommen', { tipo: 'voto', voto: 2.3, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['1,3 in Datenbanken', { tipo: 'voto', voto: 1.3, lode: false, esame: E('Datenbanken'), nomeDetto: 'datenbanken' }],
  ['Physik 2 mit 1,7 bestanden', { tipo: 'voto', voto: 1.7, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['hab in Mathe 2 ne 2 geschrieben', { tipo: 'voto', voto: 2, lode: false, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['was wenn ich ne 1,3 in Mathe 2 bekomme', { tipo: 'simula', voto: 1.3, lode: false, esame: E('Mathe 2'), nomeDetto: 'mathe 2' }],
  ['und wenn ich in Physik 2 ne 1,0 schreibe', { tipo: 'simula', voto: 1, lode: false, esame: E('Physik 2'), nomeDetto: 'physik 2' }],
  ['was brauche ich für 2,0', { tipo: 'serve', base: 2 }],
  ['welchen Schnitt brauch ich für 1,5', { tipo: 'serve', base: 1.5 }],
  ['was brauche ich für die Bestnote', { tipo: 'serve', base: 1 }],
  // il guardaroba (js/guardaroba.js): mettere, togliere, aprire la scelta
  ['setz die Krone auf', { tipo: 'accessorio', id: 'corona' }],
  ['Setz den Doktorhut auf.', { tipo: 'accessorio', id: 'tocco' }],
  ['zieh die Bommelmütze an', { tipo: 'accessorio', id: 'berretto' }],
  ['trag die runde Brille', { tipo: 'accessorio', id: 'occhiali' }],
  ['nimm den Hut ab', { tipo: 'accessorio', id: null }],
  ['Hut ab', { tipo: 'accessorio', id: null }],
  ['Kleiderschrank', { tipo: 'accessorio', apri: true }],
  ['öffne den Kleiderschrank', { tipo: 'accessorio', apri: true }],
];

// frasi che non sono comandi: restano all'AI
export const NON = [
  // una cifra sola senza verbo né articolo non è un voto; «die Prüfung» non dice quale
  'ich hab in Physik 2',

  'erklär mir den Satz von Stokes',
  'was bedeutet Standardfehler',
  'erklär den relativen Fehler',
  'wie funktioniert Anki',
  'Anki herunterladen',
  'wie importiere ich meine Karten in Anki',
  'kompilier den Physik-Bericht',
  'hallo',
  "wie geht's?",
  'was ist der Unterschied zwischen Grenzwert und Ableitung?',
  'warum konvergiert die Reihe',
  'erzähl mir einen Witz',
  'ich liebe diese App',
  'kannst du mir Rekursion erklären',
  'danke dir',
  'was ist ein Homomorphismus',
  'fass Kapitel drei für mich zusammen',
  'wie lerne ich am besten für die Klausur',
  'lerne ich zu viel?',
  'zeig mir wie man partiell integriert',
  'wie berechnet man den gewichteten Durchschnitt',
  'ich muss noch so viel lernen',
  'Fokus ist wichtig',
  'Lernen macht Spaß',
  'Spiel mir das Lied vom Tod',
  'Karten spielen ist lustig',
  'zeig mir ein Beispiel für eine Ableitung',
  'ich arbeite montags an meiner Bachelorarbeit 9-13',
  'Was heißt cum laude?',
  'Wann ist die Prüfung?',
  'die Klausur wurde verschoben',
  'morgen ist die Prüfung schwer',
  'Morgen hab ich Physik 2',
  'morgen ist die Klausur',
  'Lernen macht keinen Spaß',
  'Die Karten sind falsch',
  'ich hab die Prüfung mit 1,3 bestanden',
  'mal sehen',
  // frasi tedesche con parole anche inglesi: non passano all'inglese (nonInglese)
  'Training ist anstrengend',
  'Pomodoro ist eine Technik',
  'Timer ist kaputt',
  'Plan mir die Woche',
  'Was ist der Unterschied zwischen ECTS und LP?',
  // il guardaroba: altri vestiti e altri «metti» non sono accessori
  'zieh die Jacke aus',
  'setz mir einen Termin für Analysis auf die Liste',
];
