// I comandi in inglese per il banco (test/comandi-lingue.mjs): le stesse azioni dei casi italiani (test/comandi/it.mjs),
// dette come le direbbe uno studente inglese o americano, con lo stesso risultato. Gli esami sono quelli inglesi del libretto
// del banco (Calculus 2, Physics 2, Databases, Private law, English B2).
import { E, prossimo, giornoDetto } from './aiuto.mjs';

const ERR = "list.c:42:5: error: 'node' undeclared";
export const CASI = [
  ['explain the error', { tipo: 'errore', testo: null }],
  ['Explain this error.', { tipo: 'errore', testo: null }],
  ['what does this error mean?', { tipo: 'errore', testo: null }],
  [`explain the error: ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`explain the error ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['follow project', { tipo: 'progetto', azione: 'segui' }],
  ['Follow the project.', { tipo: 'progetto', azione: 'segui' }],
  ["what's changed", { tipo: 'progetto', azione: 'cambiato' }],
  ['tested?', { tipo: 'progetto', azione: 'provato' }],
  ['test the project', { tipo: 'progetto', azione: 'prova' }],
  ['compile the code', { tipo: 'progetto', azione: 'prova' }],
  ['stop following lab3', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['prepare me for the discussion of lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  ['language italian', { tipo: 'lingua', codice: 'it' }],
  ['switch to German', { tipo: 'lingua', codice: 'de' }],
  ['change language to Spanish', { tipo: 'lingua', codice: 'es' }],
  ['language: français', { tipo: 'lingua', codice: 'fr' }],
  ['Language Portuguese.', { tipo: 'lingua', codice: 'pt' }],
  ['set the language to english', { tipo: 'lingua', codice: 'en' }],
  ['help', { tipo: 'aiuto' }],
  ['what can you do', { tipo: 'aiuto' }],
  ['commands', { tipo: 'aiuto' }],
  ['stop', { tipo: 'ferma' }],
  ['stop the timer', { tipo: 'ferma' }],
  ['end session', { tipo: 'ferma' }],
  ['pause', { tipo: 'sospendi' }],
  ['pause the timer', { tipo: 'sospendi' }],
  ['hold on', { tipo: 'sospendi' }],
  ['resume', { tipo: 'riprendi' }],
  ['continue', { tipo: 'riprendi' }],
  ['keep going', { tipo: 'riprendi' }],
  ['export to anki', { tipo: 'anki', corso: null }],
  ['Export to Anki.', { tipo: 'anki', corso: null }],
  ['export my calculus 2 cards to anki', { tipo: 'anki', corso: 'calculus 2' }],
  ['anki physics 2', { tipo: 'anki', corso: 'physics 2' }],
  ['pocket review', { tipo: 'tasca' }],
  ['pocket review every evening', { tipo: 'tasca', sera: true }],
  ['turn off the pocket review', { tipo: 'tasca', sera: false }],
  ['syllabus for calculus 2', { tipo: 'programma', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: '' }],
  ['syllabus', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['calculus 2 syllabus:\n1. Limits\n2. Derivatives', { tipo: 'programma', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: '1. Limits\n2. Derivatives' }],
  ['let me explain: green', { tipo: 'spiego', q: 'green' }],
  ["I'll explain power series.", { tipo: 'spiego', q: 'power series' }],
  ['let me explain', { tipo: 'spiego', q: '' }],
  ["past exam questions for calculus 2: Green's theorem?", { tipo: 'domande', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: "Green's theorem?" }],
  ['exam questions calculus 2\nGreen?', { tipo: 'domande', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: 'Green?' }],
  ['past exam questions', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ['past papers for calculus 2: Exercise 1. Find the limit', { tipo: 'temi', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: 'Exercise 1. Find the limit' }],
  ['old exams for physics 2', { tipo: 'temi', esame: E('Physics 2'), nomeDetto: 'physics 2', testo: '' }],
  ['give me an exercise', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ['exercise for calculus 2', { tipo: 'temi', esame: E('Calculus 2'), nomeDetto: 'calculus 2', testo: '' }],
  ['mock exam for calculus 2', { tipo: 'prova', esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['full past paper for physics 2', { tipo: 'prova', esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['let me do a mock exam', { tipo: 'prova', esame: null, nomeDetto: '' }],
  ['★ he always asks about it', { tipo: 'stella', testo: 'he always asks about it' }],
  ["exam: Green's theorem", { tipo: 'stella', testo: "Green's theorem" }],
  ['important: series', { tipo: 'stella', testo: 'series' }],
  ['def: gradient = vector of partial derivatives', { tipo: 'definizione', termine: 'gradient', testo: 'vector of partial derivatives' }],
  ['definition nucleophile means electron-rich species.', { tipo: 'definizione', termine: 'nucleophile', testo: 'electron-rich species' }],
  ['define homomorphism: map that preserves the operations', { tipo: 'definizione', termine: 'homomorphism', testo: 'map that preserves the operations' }],
  ['Question for the professor why do we need continuity?', { tipo: 'domanda', testo: 'why do we need continuity?' }],
  ['? why does it converge', { tipo: 'domanda', testo: 'why does it converge' }],
  ['ask the prof: what about series?', { tipo: 'domanda', testo: 'what about series?' }],
  ['lecture calculus 2 monday and wednesday 9-11 room 7', { tipo: 'orario', corso: 'Calculus 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['class physics 2 friday from 2 to 4pm', { tipo: 'orario', corso: 'Physics 2', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['course private law tuesday 10-12 room b', { tipo: 'orario', corso: 'Private law', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ['timetable', { tipo: 'vediOrario' }],
  ['my classes', { tipo: 'vediOrario' }],
  ['when do I have class', { tipo: 'vediOrario' }],
  ['I work monday wednesday friday 2-7pm', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['I work monday 9-1pm and wednesday 3-7pm', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['my shifts are saturday 6pm-11pm', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ["I don't work anymore", { tipo: 'lavoro', azione: 'togli' }],
  ['when do I work', { tipo: 'lavoro', azione: 'vedi' }],
  ["I'm not working on thursday", { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['on saturday I also work 6-11pm', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ['on work days I study at most 2 hours', { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ['I study from 10 to 22', { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['weekly plan', { tipo: 'ore' }],
  ['my free time', { tipo: 'ore' }],
  ['how much time do I have', { tipo: 'ore' }],
  ['what does it print', { tipo: 'stampa' }],
  ['exercises in C', { tipo: 'stampa' }],
  ['what does it print in python', { tipo: 'stampa', lingua: 'python' }],
  ['train me on java', { tipo: 'stampa', lingua: 'java' }],
  ['play', { tipo: 'gioco', corso: null }],
  ['play calculus 2', { tipo: 'gioco', corso: 'calculus 2' }],
  ['train me', { tipo: 'gioco', corso: null }],
  ['notes', { tipo: 'appunti' }],
  ['open my notes', { tipo: 'appunti' }],
  ["today's notes", { tipo: 'appunti' }],
  ['transcribe the lecture', { tipo: 'trascrivi' }],
  ['start the transcription', { tipo: 'trascrivi' }],
  ['transcribe the video lecture of private law', { tipo: 'trascrivi', sorgente: 'computer', corso: 'private law' }],
  ['lecture from the computer', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['repeat', { tipo: 'ripeti', sec: 60 }],
  ['repeat the last 30 seconds', { tipo: 'ripeti', sec: 30 }],
  ['what did the prof say', { tipo: 'ripeti', sec: 60 }],
  ['turn off repeat', { tipo: 'spegniRipeti' }],
  ['disable the repeat', { tipo: 'spegniRipeti' }],
  ['stop repeat', { tipo: 'spegniRipeti' }],
  ['suggestions frequent', { tipo: 'proposte', livello: 'spesso' }],
  ['turn off suggestions', { tipo: 'proposte', livello: 'mai' }],
  ['suggestions few', { tipo: 'proposte', livello: 'poco' }],
  ['suggestions normal', { tipo: 'proposte', livello: 'normale' }],
  ['suggest something', { tipo: 'proponi' }],
  ['what should I do now', { tipo: 'proponi' }],
  ['what should I review', { tipo: 'proponi' }],
  ['share the transcript', { tipo: 'condividi', corso: null }],
  ['send the lecture to my classmates', { tipo: 'condividi', corso: null }],
  ['share the lecture of physics 2', { tipo: 'condividi', corso: 'physics 2' }],
  ['stop the transcription', { tipo: 'fineTrascrizione' }],
  ['the lecture is over', { tipo: 'fineTrascrizione' }],
  ['end of lecture', { tipo: 'fineTrascrizione' }],
  ['pause transcription', { tipo: 'pausaTrascrizione' }],
  ['pause the recording', { tipo: 'pausaTrascrizione' }],
  ['pause the transcription', { tipo: 'pausaTrascrizione' }],
  ['resume the transcription', { tipo: 'riprendiTrascrizione' }],
  ['continue the recording', { tipo: 'riprendiTrascrizione' }],
  ['resume recording', { tipo: 'riprendiTrascrizione' }],
  ['tidy up the lecture', { tipo: 'riordina', corso: null }],
  ['clean up my notes of physics 2', { tipo: 'riordina', corso: 'physics 2' }],
  ['reorganise the transcript', { tipo: 'riordina', corso: null }],
  ['close lecture', { tipo: 'chiudiLezione', corso: null }],
  ['close the lecture of calculus 2', { tipo: 'chiudiLezione', corso: 'calculus 2' }],
  ['extract the definitions', { tipo: 'chiudiLezione', corso: null }],
  ['AI', { tipo: 'ai', fornitore: null }],
  ['connect chatgpt', { tipo: 'ai', fornitore: 'openai' }],
  ['use gemini', { tipo: 'ai', fornitore: 'google' }],
  ['sync', { tipo: 'sincronizza', cosa: null }],
  ['sync between computers', { tipo: 'sincronizza', cosa: null }],
  ['stop syncing', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['change password', { tipo: 'sincronizza', cosa: 'password' }],
  ['unlock', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['connect another computer', { tipo: 'sincronizza', cosa: 'altro' }],
  ['I already use Lode on another computer', { tipo: 'sincronizza', cosa: 'collega' }],
  ['set up obsidian', { tipo: 'prepara', cosa: 'obsidian' }],
  ['install the model', { tipo: 'prepara', cosa: 'cervello' }],
  ['configure', { tipo: 'prepara', cosa: null }],
  ['turn off the diary', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['turn on the diary of lab3', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ["don't write the project diary for lab3", { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['project diary', { tipo: 'diario', progetto: null }],
  ['open the project diary lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['diary of the project', { tipo: 'diario', progetto: null }],
  ['open glossary', { tipo: 'naviga', q: 'glossary' }],
  ['go to home', { tipo: 'naviga', q: 'home' }],
  ['home', { tipo: 'naviga', q: 'home' }],
  ['pages', { tipo: 'naviga', q: '' }],
  ["card: Green's theorem = statement", { tipo: 'carta', esame: null, fronte: "Green's theorem", retro: 'statement' }],
  ['card for calculus 2: gradient -> vector', { tipo: 'carta', esame: E('Calculus 2'), fronte: 'gradient', retro: 'vector' }],
  ['flashcard: Schwarz | mixed derivatives', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'mixed derivatives' }],
  ['what if I get 30 in calculus 2', { tipo: 'simula', voto: 30, lode: false, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['and what if I get 28 in physics 2', { tipo: 'simula', voto: 28, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['what if I get thirty cum laude in databases', { tipo: 'simula', voto: 30, lode: true, esame: E('Databases'), nomeDetto: 'databases' }],
  ['I got 28 in physics 2', { tipo: 'voto', voto: 28, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['30 cum laude in calculus 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['I got twenty-eight in physics 2.', { tipo: 'voto', voto: 28, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['I passed english', { tipo: 'idoneita', esame: E('English B2'), nomeDetto: 'english' }],
  ['I got through english', { tipo: 'idoneita', esame: E('English B2'), nomeDetto: 'english' }],
  ['passed the test in english', { tipo: 'idoneita', esame: E('English B2'), nomeDetto: 'english' }],
  ['focus 50 on calculus 2', { tipo: 'focus', min: 50, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['study databases for an hour', { tipo: 'focus', min: 60, esame: E('Databases'), nomeDetto: 'databases' }],
  ['Focus fifty minutes on physics two.', { tipo: 'focus', min: 50, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['focus', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['exam databases on 15 January 9 credits', { tipo: 'esame', nome: 'databases', cfu: 9, data: prossimo(15, 0), esistente: E('Databases') }],
  ['I have the exam for calculus 2 on January 15th', { tipo: 'esame', nome: 'Calculus 2', cfu: null, data: prossimo(15, 0), esistente: E('Calculus 2') }],
  ['calculus 2 moved to 20 January', { tipo: 'esame', nome: 'Calculus 2', cfu: null, data: prossimo(20, 0), esistente: E('Calculus 2') }],
  ['add exam modern history', { tipo: 'esame', nome: 'modern history', cfu: null, data: null, esistente: null }],
  ['what do I need for 110', { tipo: 'serve', base: 110 }],
  ['what do I need for a hundred and ten', { tipo: 'serve', base: 110 }],
  ['what average do I need to start from 105', { tipo: 'serve', base: 105 }],
  ['average', { tipo: 'libretto' }],
  ['my grades', { tipo: 'libretto' }],
  ['how many credits do I have', { tipo: 'libretto' }],
  ['review calculus 2', { tipo: 'ripasso', esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['cards', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ["let's review physics 2", { tipo: 'ripasso', esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['agents', { tipo: 'agenti', agente: null }],
  ['connect claude code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['disconnect cursor', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['connect the agents', { tipo: 'agenti', agente: null, togli: false }],
  ['what did the agent do', { tipo: 'turnoAgente' }],
  ['what has claude code done', { tipo: 'turnoAgente' }],
  ['last turn', { tipo: 'turnoAgente' }],
  ['connect moodle', { tipo: 'moodle', cosa: null }],
  ["what's new on moodle", { tipo: 'moodle', cosa: 'novita' }],
  ['deadlines', { tipo: 'moodle', cosa: 'scadenze' }],
  ['disconnect moodle', { tipo: 'moodle', cosa: 'scollega' }],
  ['courses on moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ['quiz on calculus 2', { tipo: 'crocette', esame: E('Calculus 2'), nomeDetto: 'calculus 2', simulazione: false }],
  ['exam simulation for calculus 2', { tipo: 'crocette', esame: E('Calculus 2'), nomeDetto: 'calculus 2', simulazione: true }],
  ['multiple choice', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['quiz me on databases', { tipo: 'orale', esame: E('Databases'), nomeDetto: 'databases' }],
  ['simulate the oral exam for physics 2', { tipo: 'orale', esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['quiz me', { tipo: 'orale', esame: null, nomeDetto: '' }],
  ['exams', { tipo: 'esami' }],
  ['my exams', { tipo: 'esami' }],
  ['upcoming exams', { tipo: 'esami' }],
  ['today', { tipo: 'oggi' }],
  ['plan', { tipo: 'oggi' }],
  ['what should I study today', { tipo: 'oggi' }],
  ['calculus 2', { tipo: 'apriEsame', esame: E('Calculus 2') }],
  ['databases', { tipo: 'apriEsame', esame: E('Databases') }],
  ['physics', { tipo: 'apriEsame', esame: E('Physics 2') }],
  // dalla verifica: frasi scritte come le scrive uno studente, con i refusi più comuni
  ['Focus for 45 minutes on databases', { tipo: 'focus', min: 45, esame: E('Databases'), nomeDetto: 'databases' }],
  ['lets focus 30 min on physics 2', { tipo: 'focus', min: 30, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['focus fourty five on physics 2', { tipo: 'focus', min: 45, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['study with me', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['play with me', { tipo: 'gioco', corso: null }],
  ['reveiw calculus 2', { tipo: 'ripasso', esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['langauge italian', { tipo: 'lingua', codice: 'it' }],
  ['I work monday to friday 9-5', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 2, 3, 4, 5], inizio: '09:00', fine: '17:00' }],
  ['I work mon-fri 9am-5pm', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 2, 3, 4, 5], inizio: '09:00', fine: '17:00' }],
  ['my shifts are fri to sun 10-2', { tipo: 'lavoro', azione: 'sostituisci', giorni: [0, 5, 6], inizio: '10:00', fine: '14:00' }],
  ['I work saturday 22-2', { tipo: 'lavoro', azione: 'aggiungi', giorni: [6], inizio: '22:00', fine: '24:00' }],
  ['I study from 9 to 5', { tipo: 'lavoro', azione: 'finestra', da: '09:00', a: '17:00' }],
  ['lecture physics 2 tue-thu 10-12 room 4', { tipo: 'orario', corso: 'Physics 2', giorni: [2, 3, 4], inizio: '10:00', fine: '12:00', aula: '4' }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['switch to Japanese', { tipo: 'lingua', codice: null }],
  // i voti degli altri sistemi: il numero detto (8.5, 1.7, 72 %), le lettere come punteggio GPA, gli obiettivi a parole
  // (docs/LINGUE.md, «I voti»: se il sistema scelto li ha lo decide js/libretto.js)
  ['I got 72 in physics 2', { tipo: 'voto', voto: 72, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['I got 72% in physics 2', { tipo: 'voto', voto: 72, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['I got 8.5 in databases', { tipo: 'voto', voto: 8.5, lode: false, esame: E('Databases'), nomeDetto: 'databases' }],
  ['I got an A- in calculus 2', { tipo: 'voto', voto: 3.7, lode: false, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['I got a B+ in databases', { tipo: 'voto', voto: 3.3, lode: false, esame: E('Databases'), nomeDetto: 'databases' }],
  ['what if I get 1.7 in calculus 2', { tipo: 'simula', voto: 1.7, lode: false, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['what if I get an A in calculus 2', { tipo: 'simula', voto: 4, lode: false, esame: E('Calculus 2'), nomeDetto: 'calculus 2' }],
  ['what if I get 80 in physics 2', { tipo: 'simula', voto: 80, lode: false, esame: E('Physics 2'), nomeDetto: 'physics 2' }],
  ['what do I need for a first', { tipo: 'serve', base: 70 }],
  ['What do I need to get a 2:1?', { tipo: 'serve', base: 60 }],
  ['what do I need for first class honours', { tipo: 'serve', base: 70 }],
  ['what do I need for a 2:2', { tipo: 'serve', base: 50 }],
  ['what do I need for 2.0', { tipo: 'serve', base: 2 }],
  ['what GPA do I need for 3.5', { tipo: 'serve', base: 3.5 }],
  ['what do I need for summa cum laude', { tipo: 'serve', base: 3.9 }],
  ['what do I need for 110 cum laude', { tipo: 'serve', base: 110 }],
  // il guardaroba (js/guardaroba.js): mettere, togliere, aprire la scelta
  ['put on the crown', { tipo: 'accessorio', id: 'corona' }],
  ['Wear the mortarboard.', { tipo: 'accessorio', id: 'tocco' }],
  ["put on the wizard's hat", { tipo: 'accessorio', id: 'mago' }],
  ['put the headphones on', { tipo: 'accessorio', id: 'cuffie' }],
  ['take off the hat', { tipo: 'accessorio', id: null }],
  ['remove the glasses', { tipo: 'accessorio', id: null }],
  ['wardrobe', { tipo: 'accessorio', apri: true }],
  ['open the wardrobe', { tipo: 'accessorio', apri: true }],
];

// frasi che non sono comandi: restano all'AI
export const NON = [
  // senza verbo, una cifra sola non è un voto
  '2 in physics is hard',

  // dalla verifica: «an» non è Analisi, «studying» non è sempre un timer, «today»/«my exams» solo da soli
  'I have an exam tomorrow',
  'i have a test tomorrow',
  'i have my exam next friday',
  'studying is hard',
  'study tips for finals',
  'focus mode doesn\'t work',
  'session expired',
  'timer app recommendations',
  'today I learned about integrals',
  'my exams are stressing me out',
  'exam anxiety tips',
  "explain Stokes' theorem",
  'what does standard error mean',
  'explain the relative error',
  'anki how does it work',
  'download anki',
  'how do I import my cards into anki',
  'compile the physics report',
  'hi',
  'how are you?',
  'what is the difference between a limit and a derivative?',
  'why does the series converge',
  'tell me a joke',
  'I love this app',
  'can you help me understand recursion',
  'thanks a lot',
  'what is a homomorphism',
  'summarise chapter three for me',
  // il guardaroba: altri vestiti e altri «metti» non sono accessori
  'take off your coat',
  'put on some music while I study',
];
