// I comandi in spagnolo per il banco (test/comandi-lingue.mjs): le stesse azioni dei casi italiani (test/comandi/it.mjs),
// dette come le direbbe uno studente di Spagna o dell'America Latina (registro informale, spesso senza accenti), con lo
// stesso risultato. Gli esami sono quelli spagnoli del libretto del banco (Cálculo 2, Bases de datos, Derecho privado,
// Inglés B2) e «física 2», che è Fisica 2.
import { E, prossimo, giornoDetto } from './aiuto.mjs';

const ERR = "lista.c:42:5: error: 'nodo' undeclared";
export const CASI = [
  // «voglio fare…» e la guida passo passo (conVoglio in js/comandi/comune.js): i comandi di sempre restano loro
  ['quiero hacer una web', { tipo: 'voglio', q: 'una web' }],
  ['¿cómo hago para editar un vídeo?', { tipo: 'voglio', q: 'editar un vídeo' }],
  ['ayúdame a escribir la tesis', { tipo: 'voglio', q: 'escribir la tesis' }],
  ['tengo que hacer una presentación', { tipo: 'voglio', q: 'una presentación' }],
  ['retomar la guía', { tipo: 'guida' }],
  ['continúa la guía', { tipo: 'guida' }],
  ['¿dónde me quedé?', { tipo: 'guida' }],
  ['quiero repasar', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  // informática: el error pegado y «sigue el proyecto»
  ['explícame el error', { tipo: 'errore', testo: null }],
  ['Explícame este error.', { tipo: 'errore', testo: null }],
  ['¿qué significa este error?', { tipo: 'errore', testo: null }],
  ['explicame el error que me sale', { tipo: 'errore', testo: null }],
  [`explícame el error: ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`explicame el error ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['sigue el proyecto', { tipo: 'progetto', azione: 'segui' }],
  ['Vigila el proyecto.', { tipo: 'progetto', azione: 'segui' }],
  ['¿qué ha cambiado?', { tipo: 'progetto', azione: 'cambiato' }],
  ['¿probado?', { tipo: 'progetto', azione: 'provato' }],
  ['prueba el proyecto', { tipo: 'progetto', azione: 'prova' }],
  ['compila el código', { tipo: 'progetto', azione: 'prova' }],
  ['corre el programa', { tipo: 'progetto', azione: 'prova' }],
  ['deja de seguir lab3', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['prepárame para la defensa de lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  // el idioma
  ['idioma inglés', { tipo: 'lingua', codice: 'en' }],
  ['cambia el idioma a italiano', { tipo: 'lingua', codice: 'it' }],
  ['pásate al alemán', { tipo: 'lingua', codice: 'de' }],
  ['idioma: français', { tipo: 'lingua', codice: 'fr' }],
  ['Ponlo en portugués.', { tipo: 'lingua', codice: 'pt' }],
  ['idioma espanol', { tipo: 'lingua', codice: 'es' }],
  ['háblame en castellano', { tipo: 'lingua', codice: 'es' }],
  // el temporizador
  ['ayuda', { tipo: 'aiuto' }],
  ['¿qué puedes hacer?', { tipo: 'aiuto' }],
  ['comandos', { tipo: 'aiuto' }],
  ['para', { tipo: 'ferma' }],
  ['para el temporizador', { tipo: 'ferma' }],
  ['basta', { tipo: 'ferma' }],
  ['termina la sesión', { tipo: 'ferma' }],
  ['pausa', { tipo: 'sospendi' }],
  ['ponlo en pausa', { tipo: 'sospendi' }],
  ['pausa el timer', { tipo: 'sospendi' }],
  ['sigue', { tipo: 'riprendi' }],
  ['reanuda el temporizador', { tipo: 'riprendi' }],
  ['continúa', { tipo: 'riprendi' }],
  // Anki y el repaso de bolsillo
  ['exporta a anki', { tipo: 'anki', corso: null }],
  ['Exportar a Anki.', { tipo: 'anki', corso: null }],
  ['exporta las tarjetas de cálculo 2 a anki', { tipo: 'anki', corso: 'cálculo 2' }],
  ['anki física 2', { tipo: 'anki', corso: 'física 2' }],
  ['pasame todas las tarjetas a anki porfa', { tipo: 'anki', corso: null }],
  ['repaso de bolsillo', { tipo: 'tasca' }],
  ['repaso de bolsillo cada noche', { tipo: 'tasca', sera: true }],
  ['apaga el repaso de bolsillo', { tipo: 'tasca', sera: false }],
  ['tarjetas en el celular solo cuando lo pida', { tipo: 'tasca', sera: false }],
  // temario, «te lo explico yo», preguntas de examen, exámenes anteriores, simulacro
  ['temario de cálculo 2', { tipo: 'programma', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '' }],
  ['temario', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['temario cálculo 2:\n1. Límites\n2. Derivadas', { tipo: 'programma', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '1. Límites\n2. Derivadas' }],
  ['programa de la asignatura de bases de datos', { tipo: 'programma', esame: E('Bases de datos'), nomeDetto: 'bases de datos', testo: '' }],
  ['te lo explico yo: green', { tipo: 'spiego', q: 'green' }],
  ['Te explico las series de potencias.', { tipo: 'spiego', q: 'series de potencias' }],
  ['lo explico yo', { tipo: 'spiego', q: '' }],
  ['déjame explicarte la integral de Riemann', { tipo: 'spiego', q: 'integral de riemann' }],
  ['preguntas de examen de cálculo 2: ¿teorema de Green?', { tipo: 'domande', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '¿teorema de Green?' }],
  ['preguntas que salieron en cálculo 2\nGreen?', { tipo: 'domande', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: 'Green?' }],
  ['preguntas de examen', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ['exámenes anteriores de cálculo 2: Ejercicio 1. Calcular el límite', { tipo: 'temi', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: 'Ejercicio 1. Calcular el límite' }],
  ['parciales viejos de física 2', { tipo: 'temi', esame: E('Fisica 2'), nomeDetto: 'física 2', testo: '' }],
  ['dame un ejercicio', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ['ejercicio de cálculo 2', { tipo: 'temi', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '' }],
  ['simulacro de examen de cálculo 2', { tipo: 'prova', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['examen completo de física 2', { tipo: 'prova', esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['hazme un simulacro', { tipo: 'prova', esame: null, nomeDetto: '' }],
  // en clase
  ['★ el teorema lo pregunta siempre', { tipo: 'stella', testo: 'el teorema lo pregunta siempre' }],
  ['entra en el examen: teorema de Green', { tipo: 'stella', testo: 'teorema de Green' }],
  ['importante: las series', { tipo: 'stella', testo: 'las series' }],
  ['ojo: esto cae seguro', { tipo: 'stella', testo: 'esto cae seguro' }],
  ['def: gradiente = vector de las derivadas parciales', { tipo: 'definizione', termine: 'gradiente', testo: 'vector de las derivadas parciales' }],
  ['definición nucleófilo significa especie rica en electrones.', { tipo: 'definizione', termine: 'nucleófilo', testo: 'especie rica en electrones' }],
  ['define homomorfismo: función que conserva las operaciones', { tipo: 'definizione', termine: 'homomorfismo', testo: 'función que conserva las operaciones' }],
  ['Pregunta para el profe ¿por qué hace falta la continuidad?', { tipo: 'domanda', testo: '¿por qué hace falta la continuidad?' }],
  ['? por qué converge', { tipo: 'domanda', testo: 'por qué converge' }],
  ['pregúntale al profe: ¿y las series?', { tipo: 'domanda', testo: '¿y las series?' }],
  // horario y trabajo (js/ore.js)
  ['clase cálculo 2 lunes y miércoles 9-11 aula 7', { tipo: 'orario', corso: 'Cálculo 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['clase de física 2 viernes de 14 a 16', { tipo: 'orario', corso: 'Fisica 2', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['asignatura derecho privado martes 10-12 aula b', { tipo: 'orario', corso: 'Derecho privado', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ['clase de química orgánica los jueves de las 2 a las 4 de la tarde', { tipo: 'orario', corso: 'Química orgánica', giorni: [4], inizio: '14:00', fine: '16:00', aula: '' }],
  ['horario', { tipo: 'vediOrario' }],
  ['mis clases', { tipo: 'vediOrario' }],
  ['¿cuándo tengo clase?', { tipo: 'vediOrario' }],
  ['trabajo lunes, miércoles y viernes de 14 a 19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['trabajo el lunes de 9 a 13 y el miércoles de 15 a 19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['curro de lunes a viernes de 9 a 14', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 2, 3, 4, 5], inizio: '09:00', fine: '14:00' }],
  ['mis turnos son el sábado de 18 a 23', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ['ya no trabajo', { tipo: 'lavoro', azione: 'togli' }],
  ['¿cuándo trabajo?', { tipo: 'lavoro', azione: 'vedi' }],
  ['el jueves no trabajo', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['el sábado también trabajo de 18 a 23', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ['los días que trabajo estudio como máximo 2 horas', { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ['estudio de 10 a 22', { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['plan de la semana', { tipo: 'ore' }],
  ['mis horas libres', { tipo: 'ore' }],
  ['¿cuánto tiempo tengo?', { tipo: 'ore' }],
  // «¿Qué imprime?» y el juego
  ['¿qué imprime?', { tipo: 'stampa' }],
  ['ejercicios de C', { tipo: 'stampa' }],
  ['qué imprime en python', { tipo: 'stampa', lingua: 'python' }],
  ['entréname en java', { tipo: 'stampa', lingua: 'java' }],
  ['juega', { tipo: 'gioco', corso: null }],
  ['juega cálculo 2', { tipo: 'gioco', corso: 'cálculo 2' }],
  ['entréname', { tipo: 'gioco', corso: null }],
  ['vamos a jugar con física 2', { tipo: 'gioco', corso: 'física 2' }],
  // apuntes, transcripción, clase
  ['apuntes', { tipo: 'appunti' }],
  ['abre mis apuntes', { tipo: 'appunti' }],
  ['nota de hoy', { tipo: 'appunti' }],
  ['transcribe la clase', { tipo: 'trascrivi' }],
  ['empieza a transcribir', { tipo: 'trascrivi' }],
  ['transcribe la videoclase de derecho privado', { tipo: 'trascrivi', sorgente: 'computer', corso: 'derecho privado' }],
  ['clase desde la compu', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['repite', { tipo: 'ripeti', sec: 60 }],
  ['repite los últimos 30 segundos', { tipo: 'ripeti', sec: 30 }],
  ['¿qué dijo el profe?', { tipo: 'ripeti', sec: 60 }],
  ['no lo pillé', { tipo: 'ripeti', sec: 60 }],
  ['apaga repite', { tipo: 'spegniRipeti' }],
  ['desactiva el repite', { tipo: 'spegniRipeti' }],
  ['quita repetir', { tipo: 'spegniRipeti' }],
  ['sugerencias frecuentes', { tipo: 'proposte', livello: 'spesso' }],
  ['apaga las sugerencias', { tipo: 'proposte', livello: 'mai' }],
  ['propuestas pocas', { tipo: 'proposte', livello: 'poco' }],
  ['sugerencias normales', { tipo: 'proposte', livello: 'normale' }],
  ['proponme algo', { tipo: 'proponi' }],
  ['¿qué hago ahora?', { tipo: 'proponi' }],
  ['qué repaso', { tipo: 'proponi' }],
  ['comparte la transcripción', { tipo: 'condividi', corso: null }],
  ['manda la clase a mis compañeros', { tipo: 'condividi', corso: null }],
  ['comparte la clase de física 2', { tipo: 'condividi', corso: 'física 2' }],
  ['fin de la clase', { tipo: 'fineTrascrizione' }],
  ['la clase terminó', { tipo: 'fineTrascrizione' }],
  ['para la grabación', { tipo: 'fineTrascrizione' }],
  ['pausa la transcripción', { tipo: 'pausaTrascrizione' }],
  ['pon en pausa la grabación', { tipo: 'pausaTrascrizione' }],
  ['pausa transcripcion', { tipo: 'pausaTrascrizione' }],
  ['reanuda la transcripción', { tipo: 'riprendiTrascrizione' }],
  ['retoma la grabación', { tipo: 'riprendiTrascrizione' }],
  ['continúa la grabación', { tipo: 'riprendiTrascrizione' }],
  ['pasa a limpio la clase', { tipo: 'riordina', corso: null }],
  ['ordena los apuntes de física 2', { tipo: 'riordina', corso: 'física 2' }],
  ['organiza la transcripción', { tipo: 'riordina', corso: null }],
  ['cierra la clase', { tipo: 'chiudiLezione', corso: null }],
  ['cierra la clase de cálculo 2', { tipo: 'chiudiLezione', corso: 'cálculo 2' }],
  ['extrae las definiciones', { tipo: 'chiudiLezione', corso: null }],
  // tu IA, la sincronización, prepara
  ['IA', { tipo: 'ai', fornitore: null }],
  ['conecta chatgpt', { tipo: 'ai', fornitore: 'openai' }],
  ['usa gemini', { tipo: 'ai', fornitore: 'google' }],
  ['mi clave api', { tipo: 'ai', fornitore: null }],
  ['sincroniza', { tipo: 'sincronizza', cosa: null }],
  ['sincroniza entre ordenadores', { tipo: 'sincronizza', cosa: null }],
  ['deja de sincronizar', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['cambia la contraseña', { tipo: 'sincronizza', cosa: 'password' }],
  ['olvidé mi contraseña', { tipo: 'sincronizza', cosa: 'password' }],
  ['desbloquea', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['conecta otra computadora', { tipo: 'sincronizza', cosa: 'altro' }],
  ['ya uso Lode en otro ordenador', { tipo: 'sincronizza', cosa: 'collega' }],
  ['prepara obsidian', { tipo: 'prepara', cosa: 'obsidian' }],
  ['instala el modelo', { tipo: 'prepara', cosa: 'cervello' }],
  ['configura', { tipo: 'prepara', cosa: null }],
  // el diario del proyecto, las páginas del vault
  ['apaga el diario', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['enciende el diario de lab3', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ['no escribas el diario del proyecto lab3', { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['diario del proyecto', { tipo: 'diario', progetto: null }],
  ['abre el diario del proyecto lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['diario de proyecto', { tipo: 'diario', progetto: null }],
  ['abre glosario', { tipo: 'naviga', q: 'glosario' }],
  ['ve a inicio', { tipo: 'naviga', q: 'inicio' }],
  ['inicio', { tipo: 'naviga', q: 'home' }],
  ['páginas', { tipo: 'naviga', q: '' }],
  // tarjetas, notas, simulación, exámenes, «qué necesito», expediente, repaso
  ['tarjeta: teorema de Green = enunciado', { tipo: 'carta', esame: null, fronte: 'teorema de Green', retro: 'enunciado' }],
  ['tarjeta de cálculo 2: gradiente -> vector', { tipo: 'carta', esame: E('Cálculo 2'), fronte: 'gradiente', retro: 'vector' }],
  ['flashcard: Schwarz | derivadas cruzadas', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'derivadas cruzadas' }],
  ['ficha para física 2: dos cargas = se repelen', { tipo: 'carta', esame: E('Fisica 2'), fronte: 'dos cargas', retro: 'se repelen' }],
  ['y si saco un 30 en cálculo 2', { tipo: 'simula', voto: 30, lode: false, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['¿y si saco un 28 en física 2?', { tipo: 'simula', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['si saco treinta con matrícula en bases de datos', { tipo: 'simula', voto: 30, lode: true, esame: E('Bases de datos'), nomeDetto: 'bases de datos' }],
  ['y si saco un 9 en calculo 2', { tipo: 'simula', voto: 9, lode: false, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['saqué un 28 en física 2', { tipo: 'voto', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['30 con matrícula en cálculo 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['Saqué veintiocho en física dos.', { tipo: 'voto', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['me pusieron un 8,5 en bases de datos', { tipo: 'voto', voto: 8.5, lode: false, esame: E('Bases de datos'), nomeDetto: 'bases de datos' }],
  ['aprobé derecho privado con un 7', { tipo: 'voto', voto: 7, lode: false, esame: E('Derecho privado'), nomeDetto: 'derecho privado' }],
  ['saque un 10 con matricula de honor en calculo 2', { tipo: 'voto', voto: 10, lode: true, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['aprobé inglés', { tipo: 'idoneita', esame: E('Inglés B2'), nomeDetto: 'inglés' }],
  ['pase ingles', { tipo: 'idoneita', esame: E('Inglés B2'), nomeDetto: 'ingles' }],
  ['he superado el examen de inglés', { tipo: 'idoneita', esame: E('Inglés B2'), nomeDetto: 'inglés' }],
  ['focus 50 en cálculo 2', { tipo: 'focus', min: 50, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['estudia bases de datos durante una hora', { tipo: 'focus', min: 60, esame: E('Bases de datos'), nomeDetto: 'bases de datos' }],
  ['Focus cincuenta minutos en física dos.', { tipo: 'focus', min: 50, esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['un pomodoro de 25 minutos de derecho privado', { tipo: 'focus', min: 25, esame: E('Derecho privado'), nomeDetto: 'derecho privado' }],
  ['pomodoro de 25 en bases de datos', { tipo: 'focus', min: 25, esame: E('Bases de datos'), nomeDetto: 'bases de datos' }],
  ['focus', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['examen bases de datos el 15 de enero 9 créditos', { tipo: 'esame', nome: 'bases de datos', cfu: 9, data: prossimo(15, 0), esistente: E('Bases de datos') }],
  ['tengo el examen de cálculo 2 el 15 de enero', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(15, 0), esistente: E('Cálculo 2') }],
  ['cálculo 2 se ha movido al 20 de enero', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(20, 0), esistente: E('Cálculo 2') }],
  ['el parcial de derecho privado es el 3 de febrero', { tipo: 'esame', nome: 'Derecho privado', cfu: null, data: prossimo(3, 1), esistente: E('Derecho privado') }],
  ['examen final de análisis matemático el 10/02', { tipo: 'esame', nome: 'análisis matemático', cfu: null, data: prossimo(10, 1), esistente: null }],
  ['añade examen historia contemporánea', { tipo: 'esame', nome: 'historia contemporánea', cfu: null, data: null, esistente: null }],
  ['examen de estadística el 1 de septiembre de 6 ects', { tipo: 'esame', nome: 'estadística', cfu: 6, data: prossimo(1, 8), esistente: null }],
  ['qué necesito para 110', { tipo: 'serve', base: 110 }],
  ['¿qué necesito para ciento diez?', { tipo: 'serve', base: 110 }],
  ['qué media necesito para un 105', { tipo: 'serve', base: 105 }],
  ['¿qué nota me hace falta para un 8?', { tipo: 'serve', base: 8 }],
  ['media', { tipo: 'libretto' }],
  ['mis notas', { tipo: 'libretto' }],
  ['¿cuántos créditos tengo?', { tipo: 'libretto' }],
  ['promedio', { tipo: 'libretto' }],
  ['repasa cálculo 2', { tipo: 'ripasso', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['las tarjetas', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['vamos a repasar física 2', { tipo: 'ripasso', esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  // agentes, Moodle, test, oral
  ['agentes', { tipo: 'agenti', agente: null }],
  ['conecta claude code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['desconecta cursor', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['conecta los agentes', { tipo: 'agenti', agente: null, togli: false }],
  ['¿qué ha hecho el agente?', { tipo: 'turnoAgente' }],
  ['qué hizo claude code', { tipo: 'turnoAgente' }],
  ['último turno', { tipo: 'turnoAgente' }],
  ['conecta moodle', { tipo: 'moodle', cosa: null }],
  ['novedades de moodle', { tipo: 'moodle', cosa: 'novita' }],
  ['entregas', { tipo: 'moodle', cosa: 'scadenze' }],
  ['¿qué tengo que entregar?', { tipo: 'moodle', cosa: 'scadenze' }],
  ['desconecta moodle', { tipo: 'moodle', cosa: 'scollega' }],
  ['cursos de moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ['campus virtual', { tipo: 'moodle', cosa: null }],
  ['test de cálculo 2', { tipo: 'crocette', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', simulazione: false }],
  ['simulación de examen de cálculo 2', { tipo: 'crocette', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', simulazione: true }],
  ['preguntas tipo test', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['pregúntame sobre bases de datos', { tipo: 'orale', esame: E('Bases de datos'), nomeDetto: 'bases de datos' }],
  ['simula el oral de física 2', { tipo: 'orale', esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['examíname', { tipo: 'orale', esame: null, nomeDetto: '' }],
  // exámenes, hoy, el nombre de un examen solo
  ['exámenes', { tipo: 'esami' }],
  ['mis exámenes', { tipo: 'esami' }],
  ['próximos exámenes', { tipo: 'esami' }],
  ['hoy', { tipo: 'oggi' }],
  ['plan', { tipo: 'oggi' }],
  ['¿qué estudio hoy?', { tipo: 'oggi' }],
  ['cálculo 2', { tipo: 'apriEsame', esame: E('Cálculo 2') }],
  ['bases de datos', { tipo: 'apriEsame', esame: E('Bases de datos') }],
  ['calculo', { tipo: 'apriEsame', esame: E('Cálculo 2') }],
  // dalla verifica: «voy a estudiar …», i suspensos fuori, «final de …» senza articolo, il corso del juego, «cambiar a …»
  ['voy a estudiar 30 min de calculo 2', { tipo: 'focus', min: 30, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['me pongo a estudiar fisica 2', { tipo: 'focus', min: null, esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['estudiar 2 horas de algo nuevo', { tipo: 'focus', min: 120, esame: null, nomeDetto: 'algo nuevo' }],
  ['saque un 5 en calculo 2', { tipo: 'voto', voto: 5, lode: false, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['saqué un ocho en física dos', { tipo: 'voto', voto: 8, lode: false, esame: E('Fisica 2'), nomeDetto: 'física 2' }],
  ['final de analisis el 3 de marzo', { tipo: 'esame', nome: 'analisis', cfu: null, data: prossimo(3, 2), esistente: null }],
  ['la prueba de calculo 2 es el 3 de marzo', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(3, 2), esistente: E('Cálculo 2') }],
  ['juego de definiciones de calculo 2', { tipo: 'gioco', corso: 'calculo 2' }],
  ['cambiar a ingles', { tipo: 'lingua', codice: 'en' }],
  ['cual es mi media', { tipo: 'libretto' }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['cambia el idioma a japonés', { tipo: 'lingua', codice: null }],
];

// frasi che non sono comandi: restano all'AI (in spagnolo e anche per l'inglese di riserva)
export const NON = [
  'explícame el teorema de Stokes',
  '¿qué significa error estándar?',
  'explícame el error relativo',
  'anki cómo funciona',
  'descarga anki',
  '¿cómo importo las tarjetas en anki?',
  'compila el informe de física',
  'hola',
  '¿cómo estás?',
  '¿qué diferencia hay entre límite y derivada?',
  '¿por qué converge la serie?',
  'cuéntame un chiste',
  'me encanta esta app',
  '¿me ayudas a entender la recursión?',
  'muchas gracias',
  '¿qué es un homomorfismo?',
  'define qué es un homomorfismo',
  'resúmeme el capítulo 3',
  'estudio derecho en Madrid',
  'prepara un resumen del tema 4',
  'tengo media hora libre, ¿qué me recomiendas leer?',
  'programa que imprima hola mundo en python',
  'saqué buena nota',
  'mañana por la mañana tengo dentista',
  '¿qué es la media ponderada?',
  'test de Turing',
  'mañana no tengo clase',
  // dalla verifica: «estudiar» con la carrera o un posto, i suspensos, «final»/«prueba» di tutti i giorni, la media in statistica
  'estudiar medicina en madrid',
  'estudiar en el extranjero',
  'estudia conmigo',
  'estudiar o trabajar',
  'voy a estudiar medicina',
  'me saque un 3 en derecho privado',
  'y si saco un 4,5 en calculo 2',
  'el final de la serie es el lunes',
  'final de la temporada el 3 de marzo',
  'la prueba de manejo es el martes',
  'media y varianza de la binomial',
  'la media de una normal',
];
// gli esami spagnoli del libretto del banco, solo nel giro dello spagnolo (con «Inglés B2» nel libretto comune, «inglês» in
// portoghese troverebbe l'esame spagnolo)
export const ESAMI = [['Cálculo 1', 9, 27], ['Cálculo 2', 9], ['Bases de datos', 9], ['Derecho privado', 9], ['Inglés B2', 3, null, true]];
