// I comandi in francese per il banco (test/comandi-lingue.mjs): le stesse azioni dei casi italiani (test/comandi/it.mjs),
// dette come le direbbe uno studente in Francia, Belgio, Svizzera o Québec (informale, abbreviazioni, spesso senza accenti),
// con lo stesso risultato. Gli esami sono quelli francesi del libretto del banco (Analyse 2, Physique 2, Bases de données,
// Droit privé, Anglais B2).
import { E, prossimo, giornoDetto, prossimoGiorno, giorno } from './aiuto.mjs';

const ERR = "liste.c:42:5: error: 'noeud' undeclared";
export const CASI = [
  // informatica: l'errore incollato e «Segui il progetto»
  ["explique-moi l'erreur", { tipo: 'errore', testo: null }],
  ['Explique-moi cette erreur.', { tipo: 'errore', testo: null }],
  ["c'est quoi cette erreur ?", { tipo: 'errore', testo: null }],
  ["explique l erreur du compilateur", { tipo: 'errore', testo: null }],
  [`explique-moi l'erreur : ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`explique l'erreur ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['suis le projet', { tipo: 'progetto', azione: 'segui' }],
  ['Suis le projet.', { tipo: 'progetto', azione: 'segui' }],
  ['surveille mon projet', { tipo: 'progetto', azione: 'segui' }],
  ["qu'est-ce qui a changé ?", { tipo: 'progetto', azione: 'cambiato' }],
  ['montre les modifs', { tipo: 'progetto', azione: 'cambiato' }],
  ['testé ?', { tipo: 'progetto', azione: 'provato' }],
  ["j'ai testé ?", { tipo: 'progetto', azione: 'provato' }],
  ['teste le projet', { tipo: 'progetto', azione: 'prova' }],
  ['compile le code', { tipo: 'progetto', azione: 'prova' }],
  ['lance les tests', { tipo: 'progetto', azione: 'prova' }],
  ['arrête de suivre lab3', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['ne suis plus le projet tp2', { tipo: 'progetto', azione: 'smetti', nome: 'tp2' }],
  ['prépare-moi à la soutenance de lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  ['prepare moi pour la discussion du tp2', { tipo: 'progetto', azione: 'discussione', nome: 'tp2' }],
  ['soutenance du projet lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  // la lingua della barra
  ['langue anglais', { tipo: 'lingua', codice: 'en' }],
  ['change la langue en espagnol', { tipo: 'lingua', codice: 'es' }],
  ["passe à l'allemand", { tipo: 'lingua', codice: 'de' }],
  ['langue : italiano', { tipo: 'lingua', codice: 'it' }],
  ['Langue portugais.', { tipo: 'lingua', codice: 'pt' }],
  ['mets lode en francais', { tipo: 'lingua', codice: 'fr' }],
  ['langue: english', { tipo: 'lingua', codice: 'en' }],
  // il minuteur
  ['aide', { tipo: 'aiuto' }],
  ["qu'est-ce que tu sais faire ?", { tipo: 'aiuto' }],
  ['tu sais faire quoi', { tipo: 'aiuto' }],
  ['commandes', { tipo: 'aiuto' }],
  ['stop', { tipo: 'ferma' }],
  ['arrête le minuteur', { tipo: 'ferma' }],
  ['ça suffit', { tipo: 'ferma' }],
  ['termine la session', { tipo: 'ferma' }],
  ['pause', { tipo: 'sospendi' }],
  ['mets en pause', { tipo: 'sospendi' }],
  ['mets le chrono en pause', { tipo: 'sospendi' }],
  ['reprends', { tipo: 'riprendi' }],
  ['on continue', { tipo: 'riprendi' }],
  ["c'est reparti", { tipo: 'riprendi' }],
  // Anki e le révisions de poche
  ['exporte vers anki', { tipo: 'anki', corso: null }],
  ['Exporte vers Anki.', { tipo: 'anki', corso: null }],
  ["exporte mes cartes d'analyse 2 vers anki", { tipo: 'anki', corso: 'analyse 2' }],
  ['anki physique 2', { tipo: 'anki', corso: 'physique 2' }],
  ['révisions de poche', { tipo: 'tasca' }],
  ['revision de poche tous les soirs', { tipo: 'tasca', sera: true }],
  ['désactive la révision de poche', { tipo: 'tasca', sera: false }],
  ['revisions de poche seulement quand je demande', { tipo: 'tasca', sera: false }],
  // programme, «je t'explique», questions tombées, annales, examen blanc
  ["programme d'analyse 2", { tipo: 'programma', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: '' }],
  ['programme', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['programme analyse 2 :\n1. Limites\n2. Dérivées', { tipo: 'programma', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: '1. Limites\n2. Dérivées' }],
  ['le programme de physique deux', { tipo: 'programma', esame: E('Physique 2'), nomeDetto: 'physique 2', testo: '' }],
  ["je t'explique : green", { tipo: 'spiego', q: 'green' }],
  ['Laisse-moi expliquer les séries entières.', { tipo: 'spiego', q: 'séries entières' }],
  ["je vais t'expliquer", { tipo: 'spiego', q: '' }],
  ['questions tombées en analyse 2 : théorème de Green ?', { tipo: 'domande', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: 'théorème de Green ?' }],
  ["questions d'examen analyse 2\nGreen ?", { tipo: 'domande', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: 'Green ?' }],
  ['questions tombées', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ["annales d'analyse 2 : Exercice 1. Calculer la limite", { tipo: 'temi', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: 'Exercice 1. Calculer la limite' }],
  ['anciens sujets de physique 2', { tipo: 'temi', esame: E('Physique 2'), nomeDetto: 'physique 2', testo: '' }],
  ['donne-moi un exo', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ["exercice d'analyse 2", { tipo: 'temi', esame: E('Analyse 2'), nomeDetto: 'analyse 2', testo: '' }],
  ["examen blanc d'analyse 2", { tipo: 'prova', esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['partiel blanc de physique 2', { tipo: 'prova', esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['fais-moi faire un examen blanc', { tipo: 'prova', esame: null, nomeDetto: '' }],
  // en cours
  ['★ il le demande toujours', { tipo: 'stella', testo: 'il le demande toujours' }],
  ["à l'exam : théorème de Green", { tipo: 'stella', testo: 'théorème de Green' }],
  ['important : les séries', { tipo: 'stella', testo: 'les séries' }],
  ['déf : gradient = vecteur des dérivées partielles', { tipo: 'definizione', termine: 'gradient', testo: 'vecteur des dérivées partielles' }],
  ['définition nucléophile égale espèce riche en électrons.', { tipo: 'definizione', termine: 'nucléophile', testo: 'espèce riche en électrons' }],
  ['definis homomorphisme : application qui conserve les operations', { tipo: 'definizione', termine: 'homomorphisme', testo: 'application qui conserve les operations' }],
  ['Question pour le prof pourquoi la continuité ?', { tipo: 'domanda', testo: 'pourquoi la continuité ?' }],
  ['? pourquoi ça converge', { tipo: 'domanda', testo: 'pourquoi ça converge' }],
  ['demande au prof : et les séries ?', { tipo: 'domanda', testo: 'et les séries ?' }],
  // emploi du temps e boulot (js/ore.js)
  ['cours analyse 2 lundi et mercredi 9h-11h salle 7', { tipo: 'orario', corso: 'Analyse 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['cours de physique 2 vendredi de 14h à 16h', { tipo: 'orario', corso: 'Physique 2', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['TD droit privé mardi 10h-12h salle b', { tipo: 'orario', corso: 'Droit privé', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ["cm d'économie jeudi 8h30-10h amphi A", { tipo: 'orario', corso: 'Économie', giorni: [4], inizio: '08:30', fine: '10:00', aula: 'A' }],
  ['emploi du temps', { tipo: 'vediOrario' }],
  ['mon edt', { tipo: 'vediOrario' }],
  ["quand j'ai cours", { tipo: 'vediOrario' }],
  ['je bosse lundi mercredi vendredi 14h-19h', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['je travaille le lundi de 9h à 13h et le mercredi de 15h à 19h', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['mes horaires sont samedi 18h-23h', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ['je ne travaille plus', { tipo: 'lavoro', azione: 'togli' }],
  ['quand est-ce que je bosse', { tipo: 'lavoro', azione: 'vedi' }],
  ['jeudi je ne travaille pas', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['je bosse pas samedi', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), no: true }],
  ['samedi je bosse aussi 18h-23h', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ["les jours de boulot j'étudie au maximum 2 heures", { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ["j'étudie de 10h à 22h", { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['planning de la semaine', { tipo: 'ore' }],
  ['mon temps libre', { tipo: 'ore' }],
  ["combien de temps j'ai", { tipo: 'ore' }],
  // «Qu'est-ce que ça affiche ?» e il gioco
  ["qu'est-ce que ça affiche", { tipo: 'stampa' }],
  ['exercices en C', { tipo: 'stampa' }],
  ["qu'est-ce que ça affiche en python", { tipo: 'stampa', lingua: 'python' }],
  ['entraîne-moi en java', { tipo: 'stampa', lingua: 'java' }],
  ['joue', { tipo: 'gioco', corso: null }],
  ['on joue analyse 2', { tipo: 'gioco', corso: 'analyse 2' }],
  ['entraine-moi', { tipo: 'gioco', corso: null }],
  // notes, transcription, cours
  ['notes', { tipo: 'appunti' }],
  ['ouvre mes notes', { tipo: 'appunti' }],
  ['notes du jour', { tipo: 'appunti' }],
  ['transcris le cours', { tipo: 'trascrivi' }],
  ['lance la transcription', { tipo: 'trascrivi' }],
  ['transcris la visio de droit privé', { tipo: 'trascrivi', sorgente: 'computer', corso: 'droit privé' }],
  ["cours depuis l'ordi", { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['répète', { tipo: 'ripeti', sec: 60 }],
  ['repete les 30 dernieres secondes', { tipo: 'ripeti', sec: 30 }],
  ["qu'est-ce qu'il a dit", { tipo: 'ripeti', sec: 60 }],
  ['le prof a dit quoi', { tipo: 'ripeti', sec: 60 }],
  ['désactive répète', { tipo: 'spegniRipeti' }],
  ['coupe la répétition', { tipo: 'spegniRipeti' }],
  ['stop repete', { tipo: 'spegniRipeti' }],
  ['suggestions fréquentes', { tipo: 'proposte', livello: 'spesso' }],
  ['désactive les suggestions', { tipo: 'proposte', livello: 'mai' }],
  ['suggestions rares', { tipo: 'proposte', livello: 'poco' }],
  ['suggestions normales', { tipo: 'proposte', livello: 'normale' }],
  ['propose-moi quelque chose', { tipo: 'proponi' }],
  ['je fais quoi maintenant', { tipo: 'proponi' }],
  ['je révise quoi', { tipo: 'proponi' }],
  ['partage la transcription', { tipo: 'condividi', corso: null }],
  ['envoie le cours aux potes', { tipo: 'condividi', corso: null }],
  ['partage le cours de physique 2', { tipo: 'condividi', corso: 'physique 2' }],
  ['fin de la transcription', { tipo: 'fineTrascrizione' }],
  ['le cours est fini', { tipo: 'fineTrascrizione' }],
  ["arrête l'enregistrement", { tipo: 'fineTrascrizione' }],
  ['pause transcription', { tipo: 'pausaTrascrizione' }],
  ["mets l'enregistrement en pause", { tipo: 'pausaTrascrizione' }],
  ['pause la transcription', { tipo: 'pausaTrascrizione' }],
  ['reprends la transcription', { tipo: 'riprendiTrascrizione' }],
  ["reprendre l'enregistrement", { tipo: 'riprendiTrascrizione' }],
  ['relance la transcription', { tipo: 'riprendiTrascrizione' }],
  ['mets au propre le cours', { tipo: 'riordina', corso: null }],
  ['remets au propre mes notes de physique 2', { tipo: 'riordina', corso: 'physique 2' }],
  ['réorganise la transcription', { tipo: 'riordina', corso: null }],
  ['ferme le cours', { tipo: 'chiudiLezione', corso: null }],
  ["ferme le cours d'analyse 2", { tipo: 'chiudiLezione', corso: 'analyse 2' }],
  ['extrais les définitions', { tipo: 'chiudiLezione', corso: null }],
  // l'IA, la synchro, préparer
  ['IA', { tipo: 'ai', fornitore: null }],
  ['connecte chatgpt', { tipo: 'ai', fornitore: 'openai' }],
  ['utilise gemini', { tipo: 'ai', fornitore: 'google' }],
  ['ma clé', { tipo: 'ai', fornitore: null }],
  ['synchro', { tipo: 'sincronizza', cosa: null }],
  ['synchronise entre les ordis', { tipo: 'sincronizza', cosa: null }],
  ['arrête la synchro', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['change le mot de passe', { tipo: 'sincronizza', cosa: 'password' }],
  ["j'ai oublié mon mdp", { tipo: 'sincronizza', cosa: 'password' }],
  ['déverrouille', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['connecte un autre ordi', { tipo: 'sincronizza', cosa: 'altro' }],
  ["j'utilise déjà Lode sur un autre ordi", { tipo: 'sincronizza', cosa: 'collega' }],
  ['installe obsidian', { tipo: 'prepara', cosa: 'obsidian' }],
  ['installe le modèle', { tipo: 'prepara', cosa: 'cervello' }],
  ['configure', { tipo: 'prepara', cosa: null }],
  // il journal del progetto, le pagine del vault
  ['désactive le journal', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['active le journal de lab3', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ["n'écris pas le journal du projet lab3", { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['journal du projet', { tipo: 'diario', progetto: null }],
  ['ouvre le journal du projet lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['journal de projet', { tipo: 'diario', progetto: null }],
  ['ouvre glossaire', { tipo: 'naviga', q: 'glossaire' }],
  ["va à l'accueil", { tipo: 'naviga', q: 'home' }],
  ['accueil', { tipo: 'naviga', q: 'home' }],
  ['pages', { tipo: 'naviga', q: '' }],
  // cartes, notes, simulation, examens, «il me faut combien», relevé, révisions
  ['carte : théorème de Green = énoncé', { tipo: 'carta', esame: null, fronte: 'théorème de Green', retro: 'énoncé' }],
  ["carte d'analyse 2 : gradient -> vecteur", { tipo: 'carta', esame: E('Analyse 2'), fronte: 'gradient', retro: 'vecteur' }],
  ['flashcard: Schwarz | dérivées mixtes', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'dérivées mixtes' }],
  ["et si j'ai 30 en analyse 2", { tipo: 'simula', voto: 30, lode: false, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['si je prends 28 en physique 2', { tipo: 'simula', voto: 28, lode: false, esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ["si j'ai trente avec les félicitations en bases de données", { tipo: 'simula', voto: 30, lode: true, esame: E('Bases de données'), nomeDetto: 'bases de données' }],
  ["et si je chope 14,5 en droit privé", { tipo: 'simula', voto: 14.5, lode: false, esame: E('Droit privé'), nomeDetto: 'droit privé' }],
  ["j'ai eu 28 en physique 2", { tipo: 'voto', voto: 28, lode: false, esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['30 e lode en analyse 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ["J'ai eu vingt-huit en physique 2.", { tipo: 'voto', voto: 28, lode: false, esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ["j'ai eu 15/20 en analyse 2", { tipo: 'voto', voto: 15, lode: false, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ["j'ai chopé douze au partiel de droit privé", { tipo: 'voto', voto: 12, lode: false, esame: E('Droit privé'), nomeDetto: 'droit privé' }],
  ["j'ai validé anglais", { tipo: 'idoneita', esame: E('Anglais B2'), nomeDetto: 'anglais' }],
  ["j'ai réussi l'UE d'anglais", { tipo: 'idoneita', esame: E('Anglais B2'), nomeDetto: 'anglais' }],
  ["j'ai eu l'anglais", { tipo: 'idoneita', esame: E('Anglais B2'), nomeDetto: 'anglais' }],
  ['focus 50 sur analyse 2', { tipo: 'focus', min: 50, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['bosse les bases de données pendant une heure', { tipo: 'focus', min: 60, esame: E('Bases de données'), nomeDetto: 'bases de données' }],
  ['Focus cinquante minutes sur physique deux.', { tipo: 'focus', min: 50, esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['lance un pomodoro de 25 minutes sur analyse 2', { tipo: 'focus', min: 25, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['focus 1h30 sur droit privé', { tipo: 'focus', min: 90, esame: E('Droit privé'), nomeDetto: 'droit privé' }],
  ['focus', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['examen bases de données le 15 janvier 9 ects', { tipo: 'esame', nome: 'bases de données', cfu: 9, data: prossimo(15, 0), esistente: E('Bases de données') }],
  ["j'ai l'exam d'analyse 2 le 15 janvier", { tipo: 'esame', nome: 'Analyse 2', cfu: null, data: prossimo(15, 0), esistente: E('Analyse 2') }],
  ['analyse 2 reporté au 20 janvier', { tipo: 'esame', nome: 'Analyse 2', cfu: null, data: prossimo(20, 0), esistente: E('Analyse 2') }],
  ["le partiel de physique 2 c'est le 1er février", { tipo: 'esame', nome: 'Physique 2', cfu: null, data: prossimo(1, 1), esistente: E('Physique 2') }],
  ["l'intra de physique 2 est le 20 octobre", { tipo: 'esame', nome: 'Physique 2', cfu: null, data: prossimo(20, 9), esistente: E('Physique 2') }],
  ["l'exam de droit privé est demain", { tipo: 'esame', nome: 'Droit privé', cfu: null, data: giorno(1), esistente: E('Droit privé') }],
  ["j'ai le partiel d'analyse 2 lundi", { tipo: 'esame', nome: 'Analyse 2', cfu: null, data: prossimoGiorno(1), esistente: E('Analyse 2') }],
  ["ajoute l'examen histoire contemporaine", { tipo: 'esame', nome: 'histoire contemporaine', cfu: null, data: null, esistente: null }],
  ['nouvel examen économie 6 crédits', { tipo: 'esame', nome: 'économie', cfu: 6, data: null, esistente: null }],
  ['il me faut combien pour 110', { tipo: 'serve', base: 110 }],
  ['il me faut combien pour cent dix', { tipo: 'serve', base: 110 }],
  ['quelle moyenne il me faut pour partir de 105', { tipo: 'serve', base: 105 }],
  ['il me faut combien pour avoir 14 de moyenne', { tipo: 'serve', base: 14 }],
  ["qu'est-ce qu'il me faut pour la mention très bien", { tipo: 'serve', base: 16 }],
  ['moyenne', { tipo: 'libretto' }],
  ['ma moyenne', { tipo: 'libretto' }],
  ['mes notes', { tipo: 'libretto' }],
  ["combien de crédits j'ai", { tipo: 'libretto' }],
  ['révise analyse 2', { tipo: 'ripasso', esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['les cartes', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['fais-moi réviser physique 2', { tipo: 'ripasso', esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['revisions', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  // agents, Moodle, QCM, oral
  ['agents', { tipo: 'agenti', agente: null }],
  ['connecte claude code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['déconnecte cursor', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['connecte les agents', { tipo: 'agenti', agente: null, togli: false }],
  ["qu'a fait l'agent", { tipo: 'turnoAgente' }],
  ["qu'est-ce qu'a fait claude code", { tipo: 'turnoAgente' }],
  ['dernier tour', { tipo: 'turnoAgente' }],
  ['connecte moodle', { tipo: 'moodle', cosa: null }],
  ['quoi de neuf sur moodle', { tipo: 'moodle', cosa: 'novita' }],
  ['échéances', { tipo: 'moodle', cosa: 'scadenze' }],
  ['mes remises sur moodle', { tipo: 'moodle', cosa: 'scadenze' }],
  ["qu'est-ce que j'ai à rendre", { tipo: 'moodle', cosa: 'scadenze' }],
  ['déconnecte moodle', { tipo: 'moodle', cosa: 'scollega' }],
  ['cours sur moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ["QCM d'analyse 2", { tipo: 'crocette', esame: E('Analyse 2'), nomeDetto: 'analyse 2', simulazione: false }],
  ["simulation d'examen d'analyse 2", { tipo: 'crocette', esame: E('Analyse 2'), nomeDetto: 'analyse 2', simulazione: true }],
  ['quiz', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['interroge-moi sur bases de données', { tipo: 'orale', esame: E('Bases de données'), nomeDetto: 'bases de données' }],
  ["simule l'oral de physique 2", { tipo: 'orale', esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['interroge-moi', { tipo: 'orale', esame: null, nomeDetto: '' }],
  // examens, aujourd'hui, il nome di un esame da solo
  ['examens', { tipo: 'esami' }],
  ['mes partiels', { tipo: 'esami' }],
  ['prochains examens', { tipo: 'esami' }],
  ["aujourd'hui", { tipo: 'oggi' }],
  ['plan', { tipo: 'oggi' }],
  ["qu'est-ce que je révise aujourd'hui", { tipo: 'oggi' }],
  ['analyse 2', { tipo: 'apriEsame', esame: E('Analyse 2') }],
  ['bases de données', { tipo: 'apriEsame', esame: E('Bases de données') }],
  ['physique', { tipo: 'apriEsame', esame: E('Physique 2') }],
  // dalla verifica: l'apostrofo dimenticato («jai», «j ai»), «parle moi» senza trattino, un nome vero dopo «joue», «révise»
  ['jai eu 14 en analyse 2', { tipo: 'voto', voto: 14, lode: false, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['j ai eu 15 en physique 2', { tipo: 'voto', voto: 15, lode: false, esame: E('Physique 2'), nomeDetto: 'physique 2' }],
  ['et si jai 13 en analyse 2', { tipo: 'simula', voto: 13, lode: false, esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ['jai le partiel de physique 2 lundi', { tipo: 'esame', nome: 'Physique 2', cfu: null, data: prossimoGiorno(1), esistente: E('Physique 2') }],
  ['parle moi en espagnol', { tipo: 'lingua', codice: 'es' }],
  ['joue sur analyse 2', { tipo: 'gioco', corso: 'analyse 2' }],
  ['revise analyse 2', { tipo: 'ripasso', esame: E('Analyse 2'), nomeDetto: 'analyse 2' }],
  ["j'ai validé l'anglais B2", { tipo: 'idoneita', esame: E('Anglais B2'), nomeDetto: 'anglais b2' }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['passe en japonais', { tipo: 'lingua', codice: null }],
  // il guardaroba (js/guardaroba.js): mettere, togliere, aprire la scelta
  ['mets la couronne', { tipo: 'accessorio', id: 'corona' }],
  ['Mets la toque.', { tipo: 'accessorio', id: 'tocco' }],
  ['mets le nœud', { tipo: 'accessorio', id: 'fiocco' }],
  ["porte l'auréole", { tipo: 'accessorio', id: 'aureola' }],
  ['enlève le chapeau', { tipo: 'accessorio', id: null }],
  ['retire tes lunettes', { tipo: 'accessorio', id: null }],
  ['garde-robe', { tipo: 'accessorio', apri: true }],
  ['ouvre la garde-robe', { tipo: 'accessorio', apri: true }],
];

// frasi che non sono comandi: restano all'AI (né il francese né l'inglese di riserva le prendono)
export const NON = [
  'explique-moi le théorème de Stokes',
  "c'est quoi l'erreur type",
  "explique-moi l'erreur relative",
  'que veut dire erreur absolue en physique',
  'anki comment ça marche',
  'télécharger anki',
  "comment j'importe mes cartes dans anki",
  'compile le rapport de physique',
  'salut',
  'ça va ?',
  'quelle est la différence entre une limite et une dérivée ?',
  'pourquoi la série converge',
  'raconte-moi une blague',
  'merci beaucoup',
  "c'est quoi un homomorphisme",
  'résume-moi le chapitre trois',
  'quoi de neuf ?',
  'je comprends rien au programme de physique',
  'prépare-moi un exposé sur la révolution française',
  "c'est quoi la moyenne pondérée",
  'soutenance de mémoire',
  "j'ai pas compris",
  // frasi francesi che cominciano con una parola inglese, o scritte senza accenti come una inglese: l'inglese di riserva non le
  // deve prendere (vanno all'AI)
  'prepare-moi un expose sur la revolution',
  'plan de dissertation sur la liberte',
  "today c'est la galère",
  'open la page de physique',
  'review du code de lab3',
  'play avec moi',
  // dalla verifica: un esame senza nome, e quello che dopo «révise», «joue», «programme» è un commento, non un corso
  "j'ai un partiel demain",
  "J'ai un exam lundi",
  "j'ai l'examen demain",
  "réviser c'est chiant",
  'je révise jamais assez',
  'jouer au foot ce soir ?',
  'joue avec moi',
  'programme télé ce soir',
  'jai pas compris le cours',
  "c'est quoi une moyenne pondérée ?",
  "j'ai validé analyse 2",
  // il guardaroba: altri vestiti e altri «metti» non sono accessori
  'enlève ton manteau',
  'mets la musique pendant que je révise',
];

// l'inglese di riserva con la barra in francese: le frasi inglesi restano comandi, anche con il nome francese di un esame del
// libretto
export const RISERVA = [
  ['review bases de données', { tipo: 'ripasso', esame: E('Bases de données'), nomeDetto: 'bases de données' }],
  ['review databases', { tipo: 'ripasso', esame: E('Databases'), nomeDetto: 'databases' }],
  ['today', { tipo: 'oggi' }],
  ['quiz me', { tipo: 'orale', esame: null, nomeDetto: '' }],
  ['language english', { tipo: 'lingua', codice: 'en' }],
  ['flashcard: théorème de Green = la circulation est le flux du rotationnel', { tipo: 'carta', esame: null, fronte: 'théorème de Green', retro: 'la circulation est le flux du rotationnel' }],
];
