// I comandi in italiano: la tabella di riferimento del banco (test/comandi-lingue.mjs). Ogni altra lingua ha almeno 3 frasi
// per ogni tipo di questa tabella, e i suoi risultati hanno gli stessi campi di questi.
// Frasi prese dalle prove di sempre (test/unita.mjs, ore.mjs, tasca.mjs, temi.mjs, prova.mjs) e da ESEMPI.
import { E, prossimo, giornoDetto } from './aiuto.mjs';

const ERR = "lista.c:42:5: error: 'nodo' undeclared";
export const CASI = [
  // «voglio fare…» e la guida passo passo (conVoglio in js/comandi/comune.js): i comandi di sempre restano loro
  ['voglio fare un sito', { tipo: 'voglio', q: 'un sito' }],
  ['Voglio fare una presentazione.', { tipo: 'voglio', q: 'una presentazione' }],
  ['come faccio a montare un video?', { tipo: 'voglio', q: 'montare un video' }],
  ['aiutami a scrivere la tesi', { tipo: 'voglio', q: 'scrivere la tesi' }],
  ["devo fare un'analisi dei dati", { tipo: 'voglio', q: "un'analisi dei dati" }],
  ['vorrei imparare python', { tipo: 'voglio', q: 'imparare python' }],
  ['voglio fare un grafico della media', { tipo: 'voglio', q: 'un grafico della media' }],
  ['riprendi la guida', { tipo: 'guida' }],
  ['continua la guida', { tipo: 'guida' }],
  ['a che passo ero?', { tipo: 'guida' }],
  ['voglio fare la prova generale', { tipo: 'prova', esame: null, nomeDetto: '' }],
  ['voglio ripassare', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['voglio spiegare', { tipo: 'spiego', q: '' }],
  ['voglio fare un quiz', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  // informatica: l'errore incollato e «Segui il progetto» (js/codice/progetto.js)
  ["spiegami l'errore", { tipo: 'errore', testo: null }],
  ['Spiegami questo errore.', { tipo: 'errore', testo: null }],
  [`spiegami l'errore: ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`spiegami l'errore ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['segui progetto', { tipo: 'progetto', azione: 'segui' }],
  ['Segui il progetto.', { tipo: 'progetto', azione: 'segui' }],
  ['cosa è cambiato', { tipo: 'progetto', azione: 'cambiato' }],
  ['provato?', { tipo: 'progetto', azione: 'provato' }],
  ['prova il progetto', { tipo: 'progetto', azione: 'prova' }],
  ['compila il codice', { tipo: 'progetto', azione: 'prova' }],
  ['smetti di seguire lab3', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['preparami alla discussione di lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  // la lingua della barra
  ['lingua inglese', { tipo: 'lingua', codice: 'en' }],
  ['cambia lingua in spagnolo', { tipo: 'lingua', codice: 'es' }],
  ['passa al tedesco', { tipo: 'lingua', codice: 'de' }],
  ['lingua: français', { tipo: 'lingua', codice: 'fr' }],
  ['Lingua portoghese.', { tipo: 'lingua', codice: 'pt' }],
  ['lingua italiano', { tipo: 'lingua', codice: 'it' }],
  // il timer
  ['aiuto', { tipo: 'aiuto' }],
  ['cosa sai fare', { tipo: 'aiuto' }],
  ['comandi', { tipo: 'aiuto' }],
  ['stop', { tipo: 'ferma' }],
  ['ferma il timer', { tipo: 'ferma' }],
  ['basta', { tipo: 'ferma' }],
  ['sospendi', { tipo: 'sospendi' }],
  ['metti in pausa', { tipo: 'sospendi' }],
  ['pausa timer', { tipo: 'sospendi' }],
  ['riprendi', { tipo: 'riprendi' }],
  ['continua', { tipo: 'riprendi' }],
  ['vai avanti', { tipo: 'riprendi' }],
  // Anki e il ripasso in tasca
  ['esporta per anki', { tipo: 'anki', corso: null }],
  ['Esporta per Anki.', { tipo: 'anki', corso: null }],
  ['esporta le carte di analisi 2 per anki', { tipo: 'anki', corso: 'analisi 2' }],
  ['anki fisica 2', { tipo: 'anki', corso: 'fisica 2' }],
  ['ripasso in tasca', { tipo: 'tasca' }],
  ['ripasso in tasca ogni sera', { tipo: 'tasca', sera: true }],
  ['spegni il ripasso in tasca', { tipo: 'tasca', sera: false }],
  // programma, «te lo spiego io», domande uscite, temi d'esame, prova generale
  ['programma di analisi 2', { tipo: 'programma', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: '' }],
  ['programma', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['programma analisi 2:\n1. Limiti\n2. Derivate', { tipo: 'programma', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: '1. Limiti\n2. Derivate' }],
  ['te lo spiego io: green', { tipo: 'spiego', q: 'green' }],
  ['Spiego le serie di potenze.', { tipo: 'spiego', q: 'le serie di potenze' }],
  ['lo spiego io', { tipo: 'spiego', q: '' }],
  ['domande uscite di analisi 2: teorema di Green?', { tipo: 'domande', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: 'teorema di Green?' }],
  ["domande d'esame analisi 2\nGreen?", { tipo: 'domande', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: 'Green?' }],
  ['domande uscite', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ["temi d'esame di analisi 2: Esercizio 1. Calcolare il limite", { tipo: 'temi', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: 'Esercizio 1. Calcolare il limite' }],
  ['compiti vecchi di fisica 2', { tipo: 'temi', esame: E('Fisica 2'), nomeDetto: 'fisica 2', testo: '' }],
  ['fammi fare un esercizio', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ['esercizio di analisi 2', { tipo: 'temi', esame: E('Analisi 2'), nomeDetto: 'analisi 2', testo: '' }],
  ['prova generale di analisi 2', { tipo: 'prova', esame: E('Analisi 2'), nomeDetto: 'analisi 2' }],
  ['compito intero di fisica 2', { tipo: 'prova', esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['fammi fare un compito intero', { tipo: 'prova', esame: null, nomeDetto: '' }],
  // in aula
  ['★ il teorema lo chiede sempre', { tipo: 'stella', testo: 'il teorema lo chiede sempre' }],
  ['da esame: teorema di Green', { tipo: 'stella', testo: 'teorema di Green' }],
  ['importante: le serie', { tipo: 'stella', testo: 'le serie' }],
  ['def: gradiente = vettore delle derivate parziali', { tipo: 'definizione', termine: 'gradiente', testo: 'vettore delle derivate parziali' }],
  ['definizione nucleofilo uguale specie ricca di elettroni.', { tipo: 'definizione', termine: 'nucleofilo', testo: 'specie ricca di elettroni' }],
  ['definisci omomorfismo: funzione che conserva le operazioni', { tipo: 'definizione', termine: 'omomorfismo', testo: 'funzione che conserva le operazioni' }],
  ['Domanda per il prof perché serve la continuità?', { tipo: 'domanda', testo: 'perché serve la continuità?' }],
  ['? perché converge', { tipo: 'domanda', testo: 'perché converge' }],
  ['chiedi al prof: e le serie?', { tipo: 'domanda', testo: 'e le serie?' }],
  // orario e lavoro (js/ore.js)
  ['lezione analisi 2 lunedì e mercoledì 9-11 aula 7', { tipo: 'orario', corso: 'Analisi 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['lezione di fisica 2 venerdì dalle 14 alle 16', { tipo: 'orario', corso: 'Fisica 2', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['corso diritto privato martedì 10-12 aula b', { tipo: 'orario', corso: 'Diritto privato', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ['orario', { tipo: 'vediOrario' }],
  ['le mie lezioni', { tipo: 'vediOrario' }],
  ['quando ho lezione', { tipo: 'vediOrario' }],
  ['lavoro lunedì mercoledì venerdì 14-19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['lavoro lunedì 9-13 e mercoledì 15-19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['i miei turni sono sabato 18-23', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ['non lavoro più', { tipo: 'lavoro', azione: 'togli' }],
  ['quando lavoro', { tipo: 'lavoro', azione: 'vedi' }],
  ['giovedì non lavoro', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['sabato lavoro anche 18-23', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ['nei giorni di lavoro studio al massimo 2 ore', { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ['studio dalle 10 alle 22', { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['piano della settimana', { tipo: 'ore' }],
  ['le mie ore libere', { tipo: 'ore' }],
  ['quanto tempo ho', { tipo: 'ore' }],
  // «Cosa stampa?» e il gioco
  ['cosa stampa', { tipo: 'stampa' }],
  ['esercizi di C', { tipo: 'stampa' }],
  ['cosa stampa python', { tipo: 'stampa', lingua: 'python' }],
  ['allenami su java', { tipo: 'stampa', lingua: 'java' }],
  ['gioca', { tipo: 'gioco', corso: null }],
  ['gioca analisi 2', { tipo: 'gioco', corso: 'analisi 2' }],
  ['allenami', { tipo: 'gioco', corso: null }],
  // appunti, trascrizione, lezione
  ['appunti', { tipo: 'appunti' }],
  ['apri gli appunti', { tipo: 'appunti' }],
  ['nota di oggi', { tipo: 'appunti' }],
  ['trascrivi la lezione', { tipo: 'trascrivi' }],
  ['avvia la trascrizione', { tipo: 'trascrivi' }],
  ['trascrivi la videolezione di diritto privato', { tipo: 'trascrivi', sorgente: 'computer', corso: 'diritto privato' }],
  ['lezione dal computer', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['ripeti', { tipo: 'ripeti', sec: 60 }],
  ['ripeti gli ultimi 30 secondi', { tipo: 'ripeti', sec: 30 }],
  ['cosa ha detto il prof', { tipo: 'ripeti', sec: 60 }],
  ['spegni ripeti', { tipo: 'spegniRipeti' }],
  ['disattiva il ripeti', { tipo: 'spegniRipeti' }],
  ['basta ripeti', { tipo: 'spegniRipeti' }],
  ['proposte frequenti', { tipo: 'proposte', livello: 'spesso' }],
  ['spegni le proposte', { tipo: 'proposte', livello: 'mai' }],
  ['proposte poche', { tipo: 'proposte', livello: 'poco' }],
  ['proposte normali', { tipo: 'proposte', livello: 'normale' }],
  ['proponimi qualcosa', { tipo: 'proponi' }],
  ['cosa faccio adesso', { tipo: 'proponi' }],
  ['che ripasso', { tipo: 'proponi' }],
  ['condividi la sbobina', { tipo: 'condividi', corso: null }],
  ['manda la lezione ai compagni', { tipo: 'condividi', corso: null }],
  ['condividi la lezione di fisica 2', { tipo: 'condividi', corso: 'fisica 2' }],
  ['fine trascrizione', { tipo: 'fineTrascrizione' }],
  ['la lezione è finita', { tipo: 'fineTrascrizione' }],
  ['ferma la registrazione', { tipo: 'fineTrascrizione' }],
  ['pausa trascrizione', { tipo: 'pausaTrascrizione' }],
  ['sospendi la registrazione', { tipo: 'pausaTrascrizione' }],
  ['pausa la trascrizione', { tipo: 'pausaTrascrizione' }],
  ['riprendi la trascrizione', { tipo: 'riprendiTrascrizione' }],
  ['riprendi registrazione', { tipo: 'riprendiTrascrizione' }],
  ['riprendi la registrazione', { tipo: 'riprendiTrascrizione' }],
  ['riordina la lezione', { tipo: 'riordina', corso: null }],
  ['sistema gli appunti di fisica 2', { tipo: 'riordina', corso: 'fisica 2' }],
  ['riordina la trascrizione', { tipo: 'riordina', corso: null }],
  ['chiudi lezione', { tipo: 'chiudiLezione', corso: null }],
  ['chiudi la lezione di analisi 2', { tipo: 'chiudiLezione', corso: 'analisi 2' }],
  ['estrai le definizioni', { tipo: 'chiudiLezione', corso: null }],
  // la tua AI, la sincronizzazione, prepara
  ['AI', { tipo: 'ai', fornitore: null }],
  ['collega chatgpt', { tipo: 'ai', fornitore: 'openai' }],
  ['usa gemini', { tipo: 'ai', fornitore: 'google' }],
  ['sincronizza', { tipo: 'sincronizza', cosa: null }],
  ['sincronizza fra i computer', { tipo: 'sincronizza', cosa: null }],
  ['smetti di sincronizzare', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['cambia password', { tipo: 'sincronizza', cosa: 'password' }],
  ['sblocca', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['collega un altro computer', { tipo: 'sincronizza', cosa: 'altro' }],
  ['uso già Lode su un altro computer', { tipo: 'sincronizza', cosa: 'collega' }],
  ['prepara obsidian', { tipo: 'prepara', cosa: 'obsidian' }],
  ['installa il modello', { tipo: 'prepara', cosa: 'cervello' }],
  ['configura', { tipo: 'prepara', cosa: null }],
  // il diario del progetto, le pagine del vault
  ['spegni il diario', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['accendi il diario di lab3', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ['non scrivere il diario del progetto lab3', { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['diario del progetto', { tipo: 'diario', progetto: null }],
  ['apri il diario del progetto lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['diario di progetto', { tipo: 'diario', progetto: null }],
  ['apri glossario', { tipo: 'naviga', q: 'glossario' }],
  ['vai a home', { tipo: 'naviga', q: 'home' }],
  ['home', { tipo: 'naviga', q: 'home' }],
  ['note', { tipo: 'naviga', q: '' }],
  // carte, voti, simulazione, esami, «quanto mi serve», libretto, ripasso
  ['carta: teorema di Green = enunciato', { tipo: 'carta', esame: null, fronte: 'teorema di Green', retro: 'enunciato' }],
  ['carta di analisi 2: gradiente -> vettore', { tipo: 'carta', esame: E('Analisi 2'), fronte: 'gradiente', retro: 'vettore' }],
  ['flashcard: Schwarz | derivate miste', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'derivate miste' }],
  ['se prendo 30 in analisi 2', { tipo: 'simula', voto: 30, lode: false, esame: E('Analisi 2'), nomeDetto: 'analisi 2' }],
  ['e se prendo 28 in fisica 2', { tipo: 'simula', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['se prendo trenta e lode in basi di dati', { tipo: 'simula', voto: 30, lode: true, esame: E('Basi di dati'), nomeDetto: 'basi di dati' }],
  ['ho preso 28 in fisica 2', { tipo: 'voto', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['30 e lode ad analisi 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Analisi 2'), nomeDetto: 'analisi 2' }],
  ['Ho priso ventotto in fisica 2.', { tipo: 'voto', voto: 28, lode: false, esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['ho passato inglese', { tipo: 'idoneita', esame: E('Lingua inglese B2'), nomeDetto: 'inglese' }],
  ['superato lingua inglese', { tipo: 'idoneita', esame: E('Lingua inglese B2'), nomeDetto: 'lingua inglese' }],
  ["ho preso l'idoneità di inglese", { tipo: 'idoneita', esame: E('Lingua inglese B2'), nomeDetto: 'inglese' }],
  ['focus 50 su analisi 2', { tipo: 'focus', min: 50, esame: E('Analisi 2'), nomeDetto: 'analisi 2' }],
  ["studia basi di dati per un'ora", { tipo: 'focus', min: 60, esame: E('Basi di dati'), nomeDetto: 'basi di dati' }],
  ['Focus cinquanta minuti su fisica due.', { tipo: 'focus', min: 50, esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['focus', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['esame basi di dati il 15 gennaio 9 cfu', { tipo: 'esame', nome: 'basi di dati', cfu: 9, data: prossimo(15, 0), esistente: E('Basi di dati') }],
  ["ho l'esame di analisi 2 il 15 gennaio", { tipo: 'esame', nome: 'Analisi 2', cfu: null, data: prossimo(15, 0), esistente: E('Analisi 2') }],
  ['analisi 2 spostato al 20 gennaio', { tipo: 'esame', nome: 'Analisi 2', cfu: null, data: prossimo(20, 0), esistente: E('Analisi 2') }],
  ['aggiungi esame storia contemporanea', { tipo: 'esame', nome: 'storia contemporanea', cfu: null, data: null, esistente: null }],
  ['quanto mi serve per 110', { tipo: 'serve', base: 110 }],
  ['quanto mi serve per centodieci', { tipo: 'serve', base: 110 }],
  ['che media mi serve per partire da 105', { tipo: 'serve', base: 105 }],
  ['media', { tipo: 'libretto' }],
  ['libretto', { tipo: 'libretto' }],
  ['quanti crediti ho', { tipo: 'libretto' }],
  ['ripassa analisi 2', { tipo: 'ripasso', esame: E('Analisi 2'), nomeDetto: 'analisi 2' }],
  ['le carte', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['fammi ripassare fisica 2', { tipo: 'ripasso', esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  // agenti, Moodle, quiz, orale
  ['agenti', { tipo: 'agenti', agente: null }],
  ['collega claude code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['scollega cursor', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['collega gli agenti', { tipo: 'agenti', agente: null, togli: false }],
  ["cosa ha fatto l'agente", { tipo: 'turnoAgente' }],
  ['cosa ha fatto claude code', { tipo: 'turnoAgente' }],
  ['ultimo turno', { tipo: 'turnoAgente' }],
  ['collega moodle', { tipo: 'moodle', cosa: null }],
  ['novità da moodle', { tipo: 'moodle', cosa: 'novita' }],
  ['scadenze', { tipo: 'moodle', cosa: 'scadenze' }],
  ['scollega moodle', { tipo: 'moodle', cosa: 'scollega' }],
  ['corsi di moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ['quiz di analisi 2', { tipo: 'crocette', esame: E('Analisi 2'), nomeDetto: 'analisi 2', simulazione: false }],
  ["simulazione d'esame di analisi 2", { tipo: 'crocette', esame: E('Analisi 2'), nomeDetto: 'analisi 2', simulazione: true }],
  ['crocette', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['interrogami su basi di dati', { tipo: 'orale', esame: E('Basi di dati'), nomeDetto: 'basi di dati' }],
  ["simula l'orale di fisica 2", { tipo: 'orale', esame: E('Fisica 2'), nomeDetto: 'fisica 2' }],
  ['interrogami', { tipo: 'orale', esame: null, nomeDetto: '' }],
  // esami, oggi, il nome di un esame da solo
  ['esami', { tipo: 'esami' }],
  ['i miei esami', { tipo: 'esami' }],
  ['prossimi esami', { tipo: 'esami' }],
  ['oggi', { tipo: 'oggi' }],
  ['piano', { tipo: 'oggi' }],
  ['cosa studio oggi', { tipo: 'oggi' }],
  ['analisi 2', { tipo: 'apriEsame', esame: E('Analisi 2') }],
  ['basi di dati', { tipo: 'apriEsame', esame: E('Basi di dati') }],
  ['fisica', { tipo: 'apriEsame', esame: E('Fisica 2') }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['cambia lingua in giapponese', { tipo: 'lingua', codice: null }],
  // il guardaroba (js/guardaroba.js): mettere, togliere, aprire la scelta
  ['metti la corona', { tipo: 'accessorio', id: 'corona' }],
  ['Metti il tocco.', { tipo: 'accessorio', id: 'tocco' }],
  ["mettiti la corona d'alloro", { tipo: 'accessorio', id: 'alloro' }],
  ['indossa gli occhiali', { tipo: 'accessorio', id: 'occhiali' }],
  ['metti il cappello a cilindro', { tipo: 'accessorio', id: 'cilindro' }],
  ['togli il cappello', { tipo: 'accessorio', id: null }],
  ['togli le cuffie', { tipo: 'accessorio', id: null }],
  ['guardaroba', { tipo: 'accessorio', apri: true }],
  ['apri il guardaroba', { tipo: 'accessorio', apri: true }],
];

// frasi che non sono comandi: restano all'AI
export const NON = [
  'spiegami il teorema di Stokes',
  'cosa vuol dire errore standard',
  "spiegami l'errore relativo",
  'che vuol dire errore assoluto in fisica',
  'anki come si usa',
  'anki funziona con lode?',
  'scarica anki',
  'come importo le carte in anki',
  'compila la relazione di fisica',
  'compila il modulo Erasmus',
  'ho preso vettuto in',
  'ciao',
  'come stai?',
  'qual è la differenza tra limite e derivata?',
  'grazie mille',
  // frasi italiane che cominciano con una parola inglese: l'inglese di riserva non le deve prendere (vanno all'AI, come prima)
  'today è una giornata storta',
  'open la pagina di fisica',
  'my exams sono troppi',
  'play con me',
  'cards per analisi 2',
  'review del codice di lab3',
  // il guardaroba: altri vestiti e altri «metti» non sono accessori
  'togli il cappotto',
  'metti la corona di spine nel riassunto di storia',
];

// l'inglese di riserva con la barra in italiano: le frasi inglesi restano comandi, anche con il nome italiano di un esame del
// libretto o con una carta in italiano (il banco le prova solo con LODE_LINGUA=it)
export const RISERVA = [
  ['review basi di dati', { tipo: 'ripasso', esame: E('Basi di dati'), nomeDetto: 'basi di dati' }],
  ['flashcard: teorema di Green = la circuitazione è il flusso del rotore', { tipo: 'carta', esame: null, fronte: 'teorema di Green', retro: 'la circuitazione è il flusso del rotore' }],
  ['today', { tipo: 'oggi' }],
  ['study with me', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['language english', { tipo: 'lingua', codice: 'en' }],
];
