// I comandi in portoghese per il banco (test/comandi-lingue.mjs): le stesse azioni dei casi italiani (test/comandi/it.mjs),
// dette come le direbbe uno studente del Portogallo o del Brasile (anche di fretta, senza accenti), con lo stesso risultato.
// Gli esami sono quelli portoghesi qui sotto (ESAMI: il banco li aggiunge al libretto solo nel giro del portoghese).
import { E, prossimo, giornoDetto, giorno } from './aiuto.mjs';

// il libretto portoghese del banco: [nome, cfu, voto (fatto), idoneità]. Nomi che non si confondono con quelli italiani e
// inglesi (Física 2 sarebbe uguale a Fisica 2)
export const ESAMI = [
  ['Cálculo 2', 9], ['Bases de dados', 6], ['Direito civil', 9], ['Mecânica', 6], ['Álgebra linear', 6, 27], ['Inglês técnico', 3, null, true],
];

const ERR = "lista.c:42:5: error: 'no' undeclared";
export const CASI = [
  // «voglio fare…» e la guida passo passo (conVoglio in js/comandi/comune.js): i comandi di sempre restano loro
  ['quero fazer um site', { tipo: 'voglio', q: 'um site' }],
  ['como faço para editar um vídeo?', { tipo: 'voglio', q: 'editar um vídeo' }],
  ['me ajuda a escrever o TCC', { tipo: 'voglio', q: 'escrever o TCC' }],
  ['preciso fazer uma apresentação', { tipo: 'voglio', q: 'uma apresentação' }],
  ['retomar o guia', { tipo: 'guida' }],
  ['continua o guia', { tipo: 'guida' }],
  ['onde parei?', { tipo: 'guida' }],
  // informatica: l'errore incollato e «Segui il progetto»
  ['explica o erro', { tipo: 'errore', testo: null }],
  ['Explica-me este erro.', { tipo: 'errore', testo: null }],
  ['o que significa este erro?', { tipo: 'errore', testo: null }],
  ['me explica esse erro', { tipo: 'errore', testo: null }],
  [`explica o erro: ${ERR}`, { tipo: 'errore', testo: ERR }],
  [`explica o erro ${ERR}`, { tipo: 'errore', testo: ERR }],
  ['segue o projeto', { tipo: 'progetto', azione: 'segui' }],
  ['Segue o projeto.', { tipo: 'progetto', azione: 'segui' }],
  ['o que mudou', { tipo: 'progetto', azione: 'cambiato' }],
  ['testado?', { tipo: 'progetto', azione: 'provato' }],
  ['testa o projeto', { tipo: 'progetto', azione: 'prova' }],
  ['compila o código', { tipo: 'progetto', azione: 'prova' }],
  ['roda o codigo', { tipo: 'progetto', azione: 'prova' }],
  ['para de seguir lab3', { tipo: 'progetto', azione: 'smetti', nome: 'lab3' }],
  ['prepara-me para a discussão do lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  ['me prepara pra defesa do lab3', { tipo: 'progetto', azione: 'discussione', nome: 'lab3' }],
  // la lingua della barra
  ['idioma inglês', { tipo: 'lingua', codice: 'en' }],
  ['muda a língua para espanhol', { tipo: 'lingua', codice: 'es' }],
  ['passa para alemão', { tipo: 'lingua', codice: 'de' }],
  ['idioma: français', { tipo: 'lingua', codice: 'fr' }],
  ['Língua portuguesa.', { tipo: 'lingua', codice: 'pt' }],
  ['muda o idioma pra italiano', { tipo: 'lingua', codice: 'it' }],
  ['lingua ingles', { tipo: 'lingua', codice: 'en' }],
  // il timer
  ['ajuda', { tipo: 'aiuto' }],
  ['o que sabes fazer', { tipo: 'aiuto' }],
  ['o que você consegue fazer?', { tipo: 'aiuto' }],
  ['comandos', { tipo: 'aiuto' }],
  ['me ajuda', { tipo: 'aiuto' }],
  ['para', { tipo: 'ferma' }],
  ['para o timer', { tipo: 'ferma' }],
  ['chega', { tipo: 'ferma' }],
  ['pausa', { tipo: 'sospendi' }],
  ['pausa o temporizador', { tipo: 'sospendi' }],
  ['espera aí', { tipo: 'sospendi' }],
  ['continua', { tipo: 'riprendi' }],
  ['retoma', { tipo: 'riprendi' }],
  ['vamos lá', { tipo: 'riprendi' }],
  // Anki e revisão de bolso
  ['exporta para o anki', { tipo: 'anki', corso: null }],
  ['Exporta pro Anki.', { tipo: 'anki', corso: null }],
  ['exporta os cartões de cálculo 2 para o anki', { tipo: 'anki', corso: 'cálculo 2' }],
  ['anki mecânica', { tipo: 'anki', corso: 'mecânica' }],
  ['revisão de bolso', { tipo: 'tasca' }],
  ['revisao de bolso todas as noites', { tipo: 'tasca', sera: true }],
  ['desliga a revisão de bolso', { tipo: 'tasca', sera: false }],
  ['cartões no telemóvel só quando eu pedir', { tipo: 'tasca', sera: false }],
  ['cartões no celular', { tipo: 'tasca' }],
  ['revisão de bolso no celular', { tipo: 'tasca' }],
  ['faz a revisão de bolso no telemóvel todas as noites', { tipo: 'tasca', sera: true }],
  // programma, spiego, domande uscite, temi, prova generale
  ['programa de cálculo 2', { tipo: 'programma', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '' }],
  ['programa', { tipo: 'programma', esame: null, nomeDetto: '', testo: '' }],
  ['ementa de cálculo 2:\n1. Limites\n2. Derivadas', { tipo: 'programma', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: '1. Limites\n2. Derivadas' }],
  ['deixa-me explicar: green', { tipo: 'spiego', q: 'green' }],
  ['eu explico as séries de potências.', { tipo: 'spiego', q: 'séries de potências' }],
  ['vou explicar', { tipo: 'spiego', q: '' }],
  ['perguntas de exame de cálculo 2: Teorema de Green?', { tipo: 'domande', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: 'Teorema de Green?' }],
  ['perguntas que saíram em mecânica\nGreen?', { tipo: 'domande', esame: E('Mecânica'), nomeDetto: 'mecânica', testo: 'Green?' }],
  ['perguntas dos exames anteriores', { tipo: 'domande', esame: null, nomeDetto: '', testo: '' }],
  ['perguntas de prova de cálculo 2: Teorema de Green?', { tipo: 'domande', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: 'Teorema de Green?' }],
  ['exames antigos de cálculo 2: Exercício 1. Calcula o limite', { tipo: 'temi', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', testo: 'Exercício 1. Calcula o limite' }],
  ['provas antigas de mecânica', { tipo: 'temi', esame: E('Mecânica'), nomeDetto: 'mecânica', testo: '' }],
  ['dá-me um exercício', { tipo: 'temi', esame: null, nomeDetto: '', testo: '' }],
  ['exercicio de calculo 2', { tipo: 'temi', esame: E('Cálculo 2'), nomeDetto: 'calculo 2', testo: '' }],
  ['exame completo de cálculo 2', { tipo: 'prova', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['simulado de mecânica', { tipo: 'prova', esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['quero fazer um exame completo', { tipo: 'prova', esame: null, nomeDetto: '' }],
  // em aula
  ['★ ele pergunta sempre isto', { tipo: 'stella', testo: 'ele pergunta sempre isto' }],
  ['exame: teorema de Green', { tipo: 'stella', testo: 'teorema de Green' }],
  ['importante: séries', { tipo: 'stella', testo: 'séries' }],
  ['isto cai na prova: séries de Fourier', { tipo: 'stella', testo: 'séries de Fourier' }],
  ['def: gradiente = vetor das derivadas parciais', { tipo: 'definizione', termine: 'gradiente', testo: 'vetor das derivadas parciais' }],
  ['definição nucleófilo significa espécie rica em eletrões.', { tipo: 'definizione', termine: 'nucleófilo', testo: 'espécie rica em eletrões' }],
  ['define homomorfismo: aplicação que preserva as operações', { tipo: 'definizione', termine: 'homomorfismo', testo: 'aplicação que preserva as operações' }],
  ['definicao limite é o valor de que a função se aproxima', { tipo: 'definizione', termine: 'limite', testo: 'o valor de que a função se aproxima' }],
  ['Pergunta para o prof: porque é preciso a continuidade?', { tipo: 'domanda', testo: 'porque é preciso a continuidade?' }],
  ['? porque converge', { tipo: 'domanda', testo: 'porque converge' }],
  ['dúvida: e as séries?', { tipo: 'domanda', testo: 'e as séries?' }],
  // orario e lavoro
  ['aula cálculo 2 segunda e quarta 9-11 sala 7', { tipo: 'orario', corso: 'Cálculo 2', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '7' }],
  ['aula de mecânica sexta das 14h às 16h', { tipo: 'orario', corso: 'Mecânica', giorni: [5], inizio: '14:00', fine: '16:00', aula: '' }],
  ['cadeira direito civil terça 10-12 sala b', { tipo: 'orario', corso: 'Direito civil', giorni: [2], inizio: '10:00', fine: '12:00', aula: 'B' }],
  ['aula de álgebra linear 2ª e 4ª das 9 às 11 no anfiteatro 3', { tipo: 'orario', corso: 'Álgebra linear', giorni: [1, 3], inizio: '09:00', fine: '11:00', aula: '3' }],
  ['aula de economia terca-feira 8h30-10h', { tipo: 'orario', corso: 'Economia', giorni: [2], inizio: '08:30', fine: '10:00', aula: '' }],
  ['horário', { tipo: 'vediOrario' }],
  ['as minhas aulas', { tipo: 'vediOrario' }],
  ['quando tenho aula', { tipo: 'vediOrario' }],
  ['trabalho segunda quarta sexta 14-19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1, 3, 5], inizio: '14:00', fine: '19:00' }],
  ['trabalho segunda das 9 às 13 e quarta das 15 às 19', { tipo: 'lavoro', azione: 'aggiungi', giorni: [1], inizio: '09:00', fine: '13:00', turni: [{ giorni: [1], inizio: '09:00', fine: '13:00' }, { giorni: [3], inizio: '15:00', fine: '19:00' }] }],
  ['os meus turnos são sábado 18h-23h', { tipo: 'lavoro', azione: 'sostituisci', giorni: [6], inizio: '18:00', fine: '23:00' }],
  ['trabalho no bar sexta e sábado das 20 às 2', { tipo: 'lavoro', azione: 'aggiungi', giorni: [5, 6], inizio: '20:00', fine: '24:00' }],
  ['já não trabalho', { tipo: 'lavoro', azione: 'togli' }],
  ['quando trabalho', { tipo: 'lavoro', azione: 'vedi' }],
  ['quinta não trabalho', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(4), no: true }],
  ['nao vou trabalhar na sexta-feira', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(5), no: true }],
  ['no sábado também trabalho das 18 às 23', { tipo: 'lavoro', azione: 'eccezione', data: giornoDetto(6), inizio: '18:00', fine: '23:00' }],
  ['nos dias de trabalho estudo no máximo 2 horas', { tipo: 'lavoro', azione: 'tetto', min: 120 }],
  ['estudo das 10 às 22', { tipo: 'lavoro', azione: 'finestra', da: '10:00', a: '22:00' }],
  ['estudo entre as 9 e as 18', { tipo: 'lavoro', azione: 'finestra', da: '09:00', a: '18:00' }],
  ['plano da semana', { tipo: 'ore' }],
  ['o meu tempo livre', { tipo: 'ore' }],
  ['quanto tempo tenho para estudar', { tipo: 'ore' }],
  // «o que imprime», jogo, apontamentos, transcrição
  ['o que imprime', { tipo: 'stampa' }],
  ['exercícios de C', { tipo: 'stampa' }],
  ['o que imprime em python', { tipo: 'stampa', lingua: 'python' }],
  ['treina-me em java', { tipo: 'stampa', lingua: 'java' }],
  ['jogar', { tipo: 'gioco', corso: null }],
  ['jogar cálculo 2', { tipo: 'gioco', corso: 'cálculo 2' }],
  ['bora jogar', { tipo: 'gioco', corso: null }],
  ['apontamentos', { tipo: 'appunti' }],
  ['abre os meus apontamentos', { tipo: 'appunti' }],
  ['anotações da aula', { tipo: 'appunti' }],
  ['transcreve a aula', { tipo: 'trascrivi' }],
  ['começa a transcrição', { tipo: 'trascrivi' }],
  ['grava a aula', { tipo: 'trascrivi' }],
  ['transcreve a videoaula de direito civil', { tipo: 'trascrivi', sorgente: 'computer', corso: 'direito civil' }],
  ['aula do computador', { tipo: 'trascrivi', sorgente: 'computer', corso: null }],
  ['repete', { tipo: 'ripeti', sec: 60 }],
  ['repete os últimos 30 segundos', { tipo: 'ripeti', sec: 30 }],
  ['o que é que o professor disse', { tipo: 'ripeti', sec: 60 }],
  ['desliga o repete', { tipo: 'spegniRipeti' }],
  ['desativa o repetir', { tipo: 'spegniRipeti' }],
  ['chega de repetir', { tipo: 'spegniRipeti' }],
  ['sugestões frequentes', { tipo: 'proposte', livello: 'spesso' }],
  ['desliga as sugestões', { tipo: 'proposte', livello: 'mai' }],
  ['poucas sugestões', { tipo: 'proposte', livello: 'poco' }],
  ['sugestoes normais', { tipo: 'proposte', livello: 'normale' }],
  ['sugere-me algo', { tipo: 'proponi' }],
  ['o que devo fazer agora', { tipo: 'proponi' }],
  ['o que devo rever', { tipo: 'proponi' }],
  ['partilha a transcrição', { tipo: 'condividi', corso: null }],
  ['manda a aula aos colegas', { tipo: 'condividi', corso: null }],
  ['compartilha a aula de mecânica', { tipo: 'condividi', corso: 'mecânica' }],
  ['para a transcrição', { tipo: 'fineTrascrizione' }],
  ['a aula acabou', { tipo: 'fineTrascrizione' }],
  ['fim da aula', { tipo: 'fineTrascrizione' }],
  ['para de gravar', { tipo: 'fineTrascrizione' }],
  ['pausa a transcrição', { tipo: 'pausaTrascrizione' }],
  ['pausa a gravação', { tipo: 'pausaTrascrizione' }],
  ['suspende a gravacao', { tipo: 'pausaTrascrizione' }],
  ['retoma a transcrição', { tipo: 'riprendiTrascrizione' }],
  ['continua a gravação', { tipo: 'riprendiTrascrizione' }],
  ['continuar a transcricao', { tipo: 'riprendiTrascrizione' }],
  ['arruma a aula', { tipo: 'riordina', corso: null }],
  ['organiza os apontamentos de mecânica', { tipo: 'riordina', corso: 'mecânica' }],
  ['passa a limpo a transcrição', { tipo: 'riordina', corso: null }],
  ['fecha a aula', { tipo: 'chiudiLezione', corso: null }],
  ['fecha a aula de cálculo 2', { tipo: 'chiudiLezione', corso: 'cálculo 2' }],
  ['extrai as definições', { tipo: 'chiudiLezione', corso: null }],
  // a IA, a sincronização, preparar, o diário, navegar
  ['IA', { tipo: 'ai', fornitore: null }],
  ['conecta o chatgpt', { tipo: 'ai', fornitore: 'openai' }],
  ['usa o gemini', { tipo: 'ai', fornitore: 'google' }],
  ['a minha chave', { tipo: 'ai', fornitore: null }],
  ['sincroniza', { tipo: 'sincronizza', cosa: null }],
  ['sincroniza entre computadores', { tipo: 'sincronizza', cosa: null }],
  ['para de sincronizar', { tipo: 'sincronizza', cosa: 'smetti' }],
  ['mudar a senha', { tipo: 'sincronizza', cosa: 'password' }],
  ['esqueci-me da palavra-passe', { tipo: 'sincronizza', cosa: 'password' }],
  ['desbloqueia', { tipo: 'sincronizza', cosa: 'sblocca' }],
  ['liga outro computador', { tipo: 'sincronizza', cosa: 'altro' }],
  ['já uso o Lode noutro computador', { tipo: 'sincronizza', cosa: 'collega' }],
  ['configura o obsidian', { tipo: 'prepara', cosa: 'obsidian' }],
  ['instala o modelo', { tipo: 'prepara', cosa: 'cervello' }],
  ['configura', { tipo: 'prepara', cosa: null }],
  ['desliga o diário', { tipo: 'diarioOpz', diario: false, progetto: null }],
  ['liga o diário do lab3', { tipo: 'diarioOpz', diario: true, progetto: 'lab3' }],
  ['não escrevas o diário do projeto para o lab3', { tipo: 'diarioOpz', diario: false, progetto: 'lab3' }],
  ['diário do projeto', { tipo: 'diario', progetto: null }],
  ['abre o diário do projeto lab3', { tipo: 'diario', progetto: 'lab3' }],
  ['diario de projeto', { tipo: 'diario', progetto: null }],
  ['abre o glossário', { tipo: 'naviga', q: 'glossário' }],
  ['vai para a home', { tipo: 'naviga', q: 'home' }],
  ['início', { tipo: 'naviga', q: 'home' }],
  ['páginas', { tipo: 'naviga', q: '' }],
  // cartões, notas, simulação, exames, média
  ['cartão: teorema de Green = enunciado', { tipo: 'carta', esame: null, fronte: 'teorema de Green', retro: 'enunciado' }],
  ['cartão de cálculo 2: gradiente -> vetor', { tipo: 'carta', esame: E('Cálculo 2'), fronte: 'gradiente', retro: 'vetor' }],
  ['flashcard: Schwarz | derivadas mistas', { tipo: 'carta', esame: null, fronte: 'Schwarz', retro: 'derivadas mistas' }],
  ['e se eu tirar 30 em cálculo 2', { tipo: 'simula', voto: 30, lode: false, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['e se tirar 28 a mecânica', { tipo: 'simula', voto: 28, lode: false, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['se eu tirar trinta com louvor em bases de dados', { tipo: 'simula', voto: 30, lode: true, esame: E('Bases de dados'), nomeDetto: 'bases de dados' }],
  ['tirei 28 em mecânica', { tipo: 'voto', voto: 28, lode: false, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['30 com louvor em cálculo 2', { tipo: 'voto', voto: 30, lode: true, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['Tive vinte e oito a mecânica.', { tipo: 'voto', voto: 28, lode: false, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['passei a inglês', { tipo: 'idoneita', esame: E('Inglês técnico'), nomeDetto: 'inglês' }],
  ['fiquei aprovado em inglês técnico', { tipo: 'idoneita', esame: E('Inglês técnico'), nomeDetto: 'inglês técnico' }],
  ['passei no exame de ingles', { tipo: 'idoneita', esame: E('Inglês técnico'), nomeDetto: 'ingles' }],
  ['foco 50 em cálculo 2', { tipo: 'focus', min: 50, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['estudar bases de dados durante uma hora', { tipo: 'focus', min: 60, esame: E('Bases de dados'), nomeDetto: 'bases de dados' }],
  ['Foco cinquenta minutos em mecânica.', { tipo: 'focus', min: 50, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['um pomodoro de 25 minutos em calculo dois', { tipo: 'focus', min: 25, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['foca 25 em calculo 2', { tipo: 'focus', min: 25, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['foco', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['exame de bases de dados a 15 de janeiro 9 ects', { tipo: 'esame', nome: 'bases de dados', cfu: 9, data: prossimo(15, 0), esistente: E('Bases de dados') }],
  ['o exame de cálculo 2 é dia 15 de janeiro', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(15, 0), esistente: E('Cálculo 2') }],
  ['tenho o exame de cálculo 2 no dia 15 de jan', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(15, 0), esistente: E('Cálculo 2') }],
  ['cálculo 2 foi adiado para 20 de janeiro', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(20, 0), esistente: E('Cálculo 2') }],
  ['adiciona exame história moderna', { tipo: 'esame', nome: 'história moderna', cfu: null, data: null, esistente: null }],
  ['marca exame de física quântica a 12/06 6 ects', { tipo: 'esame', nome: 'física quântica', cfu: 6, data: prossimo(12, 5), esistente: null }],
  ['prova de termodinâmica dia 3 de fevereiro 6 créditos', { tipo: 'esame', nome: 'termodinâmica', cfu: 6, data: prossimo(3, 1), esistente: null }],
  // dalla verifica: i nomi che cominciano con «me», «que», «qual» (mecânica, química, qualidade) sono esami; senza accenti
  // «e» può essere «e» (and), non solo «é»; «hj» è «hoje»
  ['exame de mecanica dia 20 de fevereiro', { tipo: 'esame', nome: 'mecanica', cfu: null, data: prossimo(20, 1), esistente: E('Mecânica') }],
  ['exame de mecânica em 2 semanas', { tipo: 'esame', nome: 'mecânica', cfu: null, data: giorno(14), esistente: E('Mecânica') }],
  ['exame de química orgânica a 12 de janeiro', { tipo: 'esame', nome: 'química orgânica', cfu: null, data: prossimo(12, 0), esistente: null }],
  ['prova de qualidade de software dia 3 de dezembro 6 ects', { tipo: 'esame', nome: 'qualidade de software', cfu: 6, data: prossimo(3, 11), esistente: null }],
  ['exame de medicina legal 10/01', { tipo: 'esame', nome: 'medicina legal', cfu: null, data: prossimo(10, 0), esistente: null }],
  ['exame de bases de dados e redes a 3 de fevereiro', { tipo: 'esame', nome: 'bases de dados e redes', cfu: null, data: prossimo(3, 1), esistente: null }],
  ['o exame de calculo 2 e a 15/01', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(15, 0), esistente: E('Cálculo 2') }],
  ['exame de mecanica hj', { tipo: 'esame', nome: 'mecanica', cfu: null, data: giorno(0), esistente: E('Mecânica') }],
  ['tenho calculo 2 no dia 13 de outubro', { tipo: 'esame', nome: 'Cálculo 2', cfu: null, data: prossimo(13, 9), esistente: E('Cálculo 2') }],
  ['tirei nota 28 em calculo 2', { tipo: 'voto', voto: 28, lode: false, esame: E('Cálculo 2'), nomeDetto: 'calculo 2' }],
  ['tive a nota 27 a mecanica', { tipo: 'voto', voto: 27, lode: false, esame: E('Mecânica'), nomeDetto: 'mecanica' }],
  ['revisar mecanica hj', { tipo: 'ripasso', esame: E('Mecânica'), nomeDetto: 'mecanica' }],
  ['comeca o foco', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['quanto preciso para 110', { tipo: 'serve', base: 110 }],
  ['de quanto preciso para cento e dez', { tipo: 'serve', base: 110 }],
  ['que média preciso para começar com 105', { tipo: 'serve', base: 105 }],
  ['média', { tipo: 'libretto' }],
  ['as minhas notas', { tipo: 'libretto' }],
  ['quantos créditos tenho', { tipo: 'libretto' }],
  ['rever cálculo 2', { tipo: 'ripasso', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['cartões', { tipo: 'ripasso', esame: null, nomeDetto: '' }],
  ['vamos revisar mecânica', { tipo: 'ripasso', esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  // agentes, Moodle, oral, quiz
  ['agentes', { tipo: 'agenti', agente: null }],
  ['conecta o claude code', { tipo: 'agenti', agente: 'claude', togli: false }],
  ['desliga o cursor', { tipo: 'agenti', agente: 'cursor', togli: true }],
  ['conecta os agentes', { tipo: 'agenti', agente: null, togli: false }],
  ['o que fez o agente', { tipo: 'turnoAgente' }],
  ['o que andou a fazer o claude code', { tipo: 'turnoAgente' }],
  ['último turno', { tipo: 'turnoAgente' }],
  ['conecta o moodle', { tipo: 'moodle', cosa: null }],
  ['novidades no moodle', { tipo: 'moodle', cosa: 'novita' }],
  ['prazos', { tipo: 'moodle', cosa: 'scadenze' }],
  ['desconecta o moodle', { tipo: 'moodle', cosa: 'scollega' }],
  ['cadeiras no moodle', { tipo: 'moodle', cosa: 'corsi' }],
  ['quiz de cálculo 2', { tipo: 'crocette', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2', simulazione: false }],
  ['simulação de exame de direito civil', { tipo: 'crocette', esame: E('Direito civil'), nomeDetto: 'direito civil', simulazione: true }],
  ['escolha múltipla', { tipo: 'crocette', esame: null, nomeDetto: '', simulazione: false }],
  ['faz-me perguntas sobre bases de dados', { tipo: 'orale', esame: E('Bases de dados'), nomeDetto: 'bases de dados' }],
  ['simula a oral de mecânica', { tipo: 'orale', esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['me testa', { tipo: 'orale', esame: null, nomeDetto: '' }],
  ['exames', { tipo: 'esami' }],
  ['os meus exames', { tipo: 'esami' }],
  ['próximos exames', { tipo: 'esami' }],
  ['hoje', { tipo: 'oggi' }],
  ['plano', { tipo: 'oggi' }],
  ['o que devo estudar hoje', { tipo: 'oggi' }],
  ['cálculo 2', { tipo: 'apriEsame', esame: E('Cálculo 2') }],
  ['bases de dados', { tipo: 'apriEsame', esame: E('Bases de dados') }],
  ['mecanica', { tipo: 'apriEsame', esame: E('Mecânica') }],
  // una lingua che Lode non parla, detta in una delle sei lingue: codice null (la barra dice quali conosce)
  ['lingua giapponese', { tipo: 'lingua', codice: null }],
  ['language japanese', { tipo: 'lingua', codice: null }],
  ['idioma japonés', { tipo: 'lingua', codice: null }],
  ['langue japonaise', { tipo: 'lingua', codice: null }],
  ['Sprache Japanisch', { tipo: 'lingua', codice: null }],
  ['idioma japonês', { tipo: 'lingua', codice: null }],
  ['muda a língua para japonês', { tipo: 'lingua', codice: null }],
  // as notas do Brasil (0-10) e dos outros sistemas: o número dito (se o sistema tem, decide js/libretto.js)
  ['tirei 8,5 em mecânica', { tipo: 'voto', voto: 8.5, lode: false, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['tirei 7 em cálculo 2', { tipo: 'voto', voto: 7, lode: false, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['tirei nota 10 em bases de dados', { tipo: 'voto', voto: 10, lode: false, esame: E('Bases de dados'), nomeDetto: 'bases de dados' }],
  ['9,5 em direito civil', { tipo: 'voto', voto: 9.5, lode: false, esame: E('Direito civil'), nomeDetto: 'direito civil' }],
  ['e se eu tirar 9 em cálculo 2', { tipo: 'simula', voto: 9, lode: false, esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['e se eu tirar 8,5 em mecânica', { tipo: 'simula', voto: 8.5, lode: false, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['quanto preciso para 7', { tipo: 'serve', base: 7 }],
  ['que média preciso para 8,5', { tipo: 'serve', base: 8.5 }],
  ['quanto preciso para 14', { tipo: 'serve', base: 14 }],
];

// frasi che non sono comandi: restano all'AI
export const NON = [
  // uma cifra só, sem verbo, não é uma nota
  '2 em mecânica',

  'explica o teorema de Stokes',
  'o que significa erro padrão',
  'explica o erro relativo',
  'anki como funciona',
  'baixar o anki',
  'como importo os cartões no anki',
  'compila o relatório de física',
  'olá',
  'tudo bem?',
  'qual é a diferença entre limite e derivada?',
  'porque é que a série converge',
  'conta-me uma piada',
  'adoro esta app',
  'podes ajudar-me a perceber a recursividade',
  'muito obrigado',
  'o que é um homomorfismo',
  'faz-me um resumo do capítulo três',
  'o que é a média ponderada?',
  'prepara-me um resumo de mecânica',
  'quanto é vinte e oito vezes três',
  'qual é a capital de Portugal',
  'resume a aula de ontem em cinco pontos',
  'estudar é difícil',
  'programa em python que soma dois números',
  'tenho exame amanhã e estou nervoso',
  'tive 15 a mecânica e estou triste',
  'me ajuda a entender integrais',
  // dalla verifica: una data senza mese non si legge, e non diventa il nome «mecanica e dia 5»
  'o exame de mecânica é dia 5',
  'o exame de mecanica e dia 5',
  'exame de quando eu era pequeno',
  'segunda chamada de cálculo 2',
  'tenho 20 anos',
  'estou cansado hoje',
  'amanhã tenho aula',
  'quero estudar mais',
  // frasi portoghesi che cominciano con una parola inglese: l'inglese di riserva non le deve prendere (vanno all'AI)
  'today está a ser um dia mau',
  'open a página de física',
  'my exams são demasiados',
  'play com os amigos',
  'cards para economia',
  'review de um texto meu',
];

// l'inglese di riserva con la barra in portoghese: le frasi inglesi restano comandi, anche con il nome portoghese di un esame
// del libretto (il banco le prova solo con LODE_LINGUA=pt)
export const RISERVA = [
  ['review cálculo 2', { tipo: 'ripasso', esame: E('Cálculo 2'), nomeDetto: 'cálculo 2' }],
  ['focus 50 on mecânica', { tipo: 'focus', min: 50, esame: E('Mecânica'), nomeDetto: 'mecânica' }],
  ['today', { tipo: 'oggi' }],
  ['study with me', { tipo: 'focus', min: null, esame: null, nomeDetto: '' }],
  ['language english', { tipo: 'lingua', codice: 'en' }],
];
