// Textos da barra, segunda parte (português do Brasil): arquivos soltos na barra, sugestões do treinador, a sua IA,
// «Preparar o Lode» e atualizações, sincronização, notas, fechamento da aula, jogos, comandos locais, erros explicados
// e diário, ferramentas da IA, prova oral, agentes de programação (js/lode.js).
export default {
  'barra2.file-non-so-usare': 'Isso eu não sei usar: {motivo}.',
  'barra2.peso-kb': '{n} KB',
  'barra2.peso-mb': '{n} MB',
  'barra2.cosa-ne-faccio': 'O que eu faço com isso?',
  'barra2.per': 'Para',
  'barra2.corso': 'Disciplina',
  'barra2.data-lezione': 'Data da aula',
  'barra2.non-andata': 'Não deu certo: {errore}',
  'barra2.sintesi-cosa-ne-faccio': '{nome}: o que eu faço com isso?',
  'barra2.allegato-lezione': 'Anexado à aula de {corso}.',
  'barra2.apri': 'Abrir',
  'barra2.sbobina-nel-vault': 'Transcrição de {corso} no seu vault.',
  'barra2.sbobina-nota-da': '{data} · de {da}',
  'barra2.sbobina-ricevuta': 'transcrição recebida',
  'barra2.nessuna-riga-carte': 'Não encontrei linhas «pergunta, resposta» neste arquivo.',
  'barra2.apro-registrazione': 'Abrindo a gravação…',
  'barra2.leggo-foto': 'Lendo a foto…',
  'barra2.lavagna-titolo': 'Colocar nas anotações de {corso}?',
  'barra2.lavagna-nota': 'Junto com a foto, na nota da aula de hoje. Releia: quem transcreveu foi {motore}.',
  'barra2.lavagna-fatta': 'Quadro nas anotações.',
  'barra2.leggo-file': 'Lendo {nome}…',
  'barra2.file-senza-testo': 'Não consigo ler o texto deste arquivo.',
  'barra2.file-senza-testo-incolla': 'Não consigo ler o texto deste arquivo: cole no campo.',
  'barra2.prima-esame': 'Primeiro adicione a prova, por exemplo: «prova de cálculo 2 dia 15 de janeiro 4 créditos».',
  'barra2.scrivo-carte': 'Escrevendo os cartões…',
  'barra2.file-senza-carte': 'Não consegui tirar cartões deste arquivo.',
  'barra2.riassumo': 'Resumindo {nome}… {p}%',
  'barra2.riassunto-titolo': 'Salvar o resumo no Obsidian?',
  'barra2.riassunto-nota': 'Nota nova em {cartella}, com o arquivo original anexado.',
  'barra2.riassunto-salvato': 'Resumo salvo.',
  'barra2.stelle-titolo': '★ Cai na prova · {esame}',
  'barra2.ora-un-gioco': 'Agora um jogo',
  'barra2.gioca': 'Jogar',
  'barra2.la-tua-ai': 'Sua IA',
  'barra2.ai-locale-attivo': 'Agora o Lode usa o <b>cérebro local</b>: grátis, offline, as anotações ficam aqui.',
  'barra2.ai-locale-da-installare': 'O <b>cérebro local</b> grátis é instalado em «Preparar o Lode».',
  'barra2.ai-chiave-spiegazione': 'Se quiser uma IA mais potente, conecte a sua chave: você paga direto ao serviço, pelo uso (normalmente poucos centavos por sessão). O Lode não vê nem recebe nada; a chave fica neste computador.',
  'barra2.ai-nome-collegata': '{nome} · conectada',
  'barra2.chiave-api': 'Chave de API',
  'barra2.collega': 'Conectar',
  'barra2.modello': 'Modelo',
  'barra2.ai-solo-spiegazioni': 'Anotações e aulas ficam no computador: sua IA só para explicações e prova oral',
  'barra2.usa-solo-locale': 'Usar só o cérebro local',
  'barra2.chiave-di': 'Chave de {nome}',
  'barra2.incolla-chiave': 'cole a chave',
  'barra2.si-crea-su': 'É criada em <b>{sito}</b>.',
  'barra2.provo-chiave': 'Testando a chave…',
  'barra2.ai-collegata': '{nome} conectada.',
  'barra2.ai-modello': 'Modelo {modello}.',
  'barra2.ai-appunti-restano': 'As anotações ficam no computador.',
  'barra2.ai-usano-tua': 'Explicações, prova oral, cartões e organização usam a sua IA.',
  'barra2.sintesi-ai-collegata': 'IA conectada',
  'barra2.chiave-non-valida': 'A chave não é válida.',
  'barra2.servizio-irraggiungibile': 'Não consigo acessar o serviço: tem internet?',
  'barra2.solo-locale-fatto': 'O Lode usa só o cérebro local.',
  'barra2.ai-scollegata-sito': 'Apaguei a chave deste computador. Na sua conta {nome} ela ainda vale: se não precisar mais, revogue lá também ({sito}).',
  'barra2.ai-scollegata-nome': 'Apaguei a chave deste computador. Na sua conta {nome} ela ainda vale: se não precisar mais, revogue lá também.',
  'barra2.ai-scollegata': 'Apaguei a chave deste computador. Na sua conta ela ainda vale: se não precisar mais, revogue lá também.',
  'barra2.sintesi-la-tua-ai': 'sua IA',
  'barra2.agg-pronta': 'O Lode {versione} está pronto',
  'barra2.agg-si-installa': 'Ele se instala sozinho quando você fechar o Lode',
  'barra2.riavvia-ora': 'Reiniciar agora',
  'barra2.agg-uscita': 'Saiu o Lode {versione}',
  'barra2.agg-scarica-dmg': 'Baixe o .dmg e arraste o Lode para Aplicativos',
  'barra2.agg-scarica-github': 'Baixe a versão nova no GitHub',
  'barra2.scarica': 'Baixar',
  'barra2.agg-spenti': 'Lode {versione} · desligadas: as versões novas estão no GitHub, na página Releases',
  'barra2.agg-scarico': 'Baixando o Lode {versione} · {p}%',
  'barra2.agg-pronta-riga': 'O Lode {versione} está pronto · ele se instala sozinho quando você fechar o Lode',
  'barra2.agg-uscita-mac': 'Saiu o Lode {versione} · baixe o .dmg e arraste o Lode para Aplicativos',
  'barra2.agg-uscita-github': 'Saiu o Lode {versione} · baixe no GitHub',
  'barra2.agg-manuale': 'Lode {versione} · eu aviso quando sair uma nova (pelo GitHub, a cada 6 horas)',
  'barra2.agg-automatici': 'Lode {versione} · se atualiza sozinho pelo GitHub, verifica a cada 6 horas',
  'barra2.spegni': 'Desligar',
  'barra2.accendi': 'Ligar',
  'barra2.prep-solo-app': 'O Obsidian e o cérebro local são instalados pelo **app para desktop** do Lode.',
  'barra2.prepara-lode': 'Preparar o Lode',
  'barra2.il-tuo-vault': 'Seu vault',
  'barra2.prep-vault-dett': '{percorso} · Home, disciplinas, aulas, glossário',
  'barra2.obs-installato': 'Instalado e conectado ao vault',
  'barra2.obs-da-installare': 'Grátis para uso pessoal · instalador oficial do GitHub, cerca de 230 MB',
  'barra2.installa': 'Instalar',
  'barra2.cervello-locale': 'Cérebro local',
  'barra2.cervello-pronto-dett': '{modello} · roda no computador, sem internet',
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · cerca de {gb} GB',
  'barra2.pronto': 'pronto',
  'barra2.voce': 'Voz',
  'barra2.voce-pronta-dett': '{voce} local · segure {tasti} e fale',
  'barra2.voce-da-preparare': '{descrizione}, local, em português · cerca de {peso} MB, uma vez só',
  'barra2.pronta': 'pronta',
  'barra2.prepara': 'Preparar',
  'barra2.facoltativa': 'opcional',
  'barra2.tua-ai-collegata-dett': '{nome} conectada · quem paga o uso é você, direto ao serviço',
  'barra2.tua-ai-da-collegare': 'Claude, ChatGPT, Gemini, Mistral…: mais potente, paga por uso com a sua chave',
  'barra2.cambia': 'Trocar',
  'barra2.sincronizza-computer': 'Sincronizar entre seus computadores',
  'barra2.sperimentale': 'experimental',
  'barra2.sblocca': 'Desbloquear',
  'barra2.gestisci': 'Gerenciar',
  'barra2.attiva': 'Ativar',
  'barra2.uso-gia-altrove': 'Já uso o Lode em outro computador',
  'barra2.collega-dett': 'Conecte este computador ao vault que você já tem na pasta da nuvem',
  'barra2.aggiornamenti': 'Atualizações',
  'barra2.prep-nota': 'O cérebro local é grátis e funciona offline: extrai definições, cria cartões, explica e faz perguntas. A sua IA é um reforço opcional: o Lode não vê nem recebe nada.',
  'barra2.detto-mia-ai': 'Minha IA',
  'barra2.detto-sincronizza': 'Sincronizar entre computadores',
  'barra2.scarico-voce': 'Baixando {voce}…',
  'barra2.sintesi-prepara': 'preparar o Lode',
  'barra2.installare-obsidian': 'Instalar o Obsidian?',
  'barra2.da': 'De',
  'barra2.github-obsidian': 'github.com/obsidianmd (oficial)',
  'barra2.peso': 'Tamanho',
  'barra2.circa-230-mb': 'cerca de 230 MB',
  'barra2.dove': 'Onde',
  'barra2.applicazioni': 'Aplicativos',
  'barra2.il-tuo-utente': 'seu usuário',
  'barra2.obs-nota': 'O Obsidian é grátis para uso pessoal. Ele já abre no seu vault, na Home.',
  'barra2.installare-nome': 'Instalar {nome}?',
  'barra2.installare-cervello': 'Instalar o cérebro local?',
  'barra2.cosa': 'O quê',
  'barra2.ollama-motore': 'Ollama (motor) + {nome}',
  'barra2.circa-gb': 'cerca de {gb} GB',
  'barra2.perche': 'Por quê',
  'barra2.cervello-nota': 'É baixado uma vez só. Depois funciona sem internet e sem chaves.',
  'barra2.solo-clic': 'Só se confirma com o clique.',
  'barra2.avviato': 'Iniciado.',
  'barra2.continuo-da-solo': 'Pode fechar o painel: eu continuo sozinho.',
  'barra2.obsidian-pronto': 'O Obsidian está pronto',
  'barra2.cervello-pronto': 'Cérebro local pronto',
  'barra2.sync-piede-cifrati': 'Criptografados, sincronizados com {servizio}',
  'barra2.sync-piede': 'Sincronizados com {servizio}',
  'barra2.la-tua-cartella-cloud': 'sua pasta da nuvem',
  'barra2.dati-restano-qui': 'Os dados ficam neste computador',
  'barra2.portachiavi-mac': 'A senha fica guardada neste computador (nas Chaves).',
  'barra2.portachiavi-windows': 'A senha fica guardada neste computador (protegida pela sua conta do Windows).',
  'barra2.portachiavi-sistema': 'A senha fica guardada neste computador (no chaveiro do sistema).',
  'barra2.senza-portachiavi': 'Este computador não tem um chaveiro seguro: o Lode vai pedir a senha toda vez que iniciar.',
  'barra2.sync-solo-app': 'A sincronização entre computadores está no **app para desktop** do Lode.',
  'barra2.sync-stato-illeggibile': 'Não consigo ler o estado da sincronização.',
  'barra2.sync-altro-computer': 'No outro computador, abra o Lode e escolha «Já uso o Lode em outro computador», depois o vault «{vault}» em {servizio}.',
  'barra2.la-cartella-cloud': 'a pasta da nuvem',
  'barra2.sync-non-accesa': 'A sincronização não está ligada: os dados do Lode ficam neste computador.',
  'barra2.sync-titolo-altro': 'Já uso o Lode em outro computador · experimental',
  'barra2.sync-titolo': 'Sincronizar entre seus computadores · experimental',
  'barra2.sync-sperimentale': '<b>Experimental.</b> {testo}',
  'barra2.sync-cartella-cloud': 'Uso a pasta da nuvem que você já tem: sem conta, sem servidor do Lode. Copio o vault para lá e passo a usar a cópia; a pasta anterior fica onde está. {prima}',
  'barra2.sync-interrotto': '<b>A mudança para {servizio} foi interrompida.</b> O vault anterior está intacto: escolha a pasta de novo e eu continuo de onde parei.',
  'barra2.cartella-cloud': 'pasta da nuvem',
  'barra2.sync-interrotto-pw': 'Tinha começado com a senha: vou pedir para você digitar de novo.',
  'barra2.vault-gia-qui': 'o vault já está aqui: nada para mover',
  'barra2.altra-cartella': 'Outra pasta…',
  'barra2.altra-cartella-dett': 'Syncthing, uma pasta de rede',
  'barra2.nessuna-cartella-cloud': 'Não encontro iCloud Drive, OneDrive, Dropbox ou Google Drive neste computador: escolha você a pasta que sincroniza.',
  'barra2.scegli-vault-cloud': 'Escolha o vault na pasta da nuvem',
  'barra2.gia-sincronizzato': '{servizio} · já sincronizado',
  'barra2.scegli-vault': 'Escolher o vault…',
  'barra2.scegli-vault-dett': 'a pasta «Lode» na sua pasta da nuvem',
  'barra2.vault-resta': 'O vault que está agora neste computador fica onde está, intacto.',
  'barra2.vault-resta-altro': 'Se o Lode aqui já tem provas, notas ou cartões, levo tudo para o grupo como «Dados de outra primeira instalação»: quem importa é você, nada substitui os dados dos outros computadores.',
  'barra2.la-cartella-che-scegli': 'a pasta que você escolher',
  'barra2.sintesi-uso-gia-altrove': 'já uso o Lode em outro lugar',
  'barra2.sintesi-sincronizza': 'sincronizar',
  'barra2.sincronizzare-con': 'Sincronizar com {servizio}?',
  'barra2.vault': 'Vault',
  'barra2.vault-resta-cloud': 'fica onde está: já está na pasta da nuvem',
  'barra2.cartella-lode-in': 'uma pasta «Lode» em {servizio}',
  'barra2.prima': 'Antes',
  'barra2.dati-json-cronologia': 'o dati.json anterior fica no histórico do serviço',
  'barra2.vault-adesso-resta': 'o vault de agora fica onde está, intacto',
  'barra2.dati-di-lode': 'Dados do Lode',
  'barra2.un-diario-per-computer': 'um diário por computador: sem conflitos, nada se perde',
  'barra2.proteggi-con-password': 'Proteger os dados do Lode com uma senha',
  'barra2.password-almeno-8': 'Senha (pelo menos 8 caracteres)',
  'barra2.password': 'Senha',
  'barra2.ripetila': 'Repita',
  'barra2.ripeti-password': 'Repita a senha',
  'barra2.cifrati-in-chiaro-anche': '<b>Criptografados:</b> {cifrati}. <b>Abertos na pasta da nuvem</b>, mesmo com a senha:',
  'barra2.sync-nota-password': 'A senha também pode ser adicionada depois («Proteger com uma senha»), ou trocada («Trocar senha»). Nos outros computadores: «Já uso o Lode em outro computador». {prima}',
  'barra2.spostamento-con-password': 'A mudança tinha começado com a senha: digite de novo.',
  'barra2.almeno-8': 'Pelo menos 8 caracteres.',
  'barra2.password-diverse': 'As duas senhas não são iguais.',
  'barra2.preparo': 'Preparando…',
  'barra2.sincronizzato-con': 'Sincronizado com {servizio}.',
  'barra2.vault-era-gia-cloud': 'O vault já estava na pasta da nuvem: a partir de agora cada computador escreve só o seu diário.',
  'barra2.cartella-prima-resta': 'A pasta anterior («{da}») fica onde estava: apague quando quiser. Nos outros computadores: «Já uso o Lode em outro computador».',
  'barra2.vault-gia-in-servizio': 'Em {servizio} já existe um vault do Lode sincronizado.',
  'barra2.usa-uso-gia': 'Use «Já uso o Lode em outro computador» para se conectar a ele.',
  'barra2.annullato': 'Cancelado.',
  'barra2.niente-cambiato': 'Não mudei nada.',
  'barra2.scrivi-password': 'Digite a senha.',
  'barra2.non-ancora': 'Ainda não.',
  'barra2.non-andata-vault-intatto': 'Não deu certo: {errore}. O vault anterior está intacto.',
  'barra2.collegato-vault-in': 'Conectado ao vault em {servizio}.',
  'barra2.dati-protetti-password': 'Os dados do Lode estão protegidos por uma senha: digite para receber.',
  'barra2.ricevo-dati': 'Recebendo os dados dos outros computadores: eles chegam sozinhos. O Lode já pode ser usado.',
  'barra2.dati-importati-altrove': 'Os dados que você tinha neste computador ({n} registros) estão em «Dados de outra primeira instalação», na aba «Sincronizar»: importe por lá. O arquivo anterior fica no vault «{vault}».',
  'barra2.cartella-inusabile': 'Não consigo usar essa pasta.',
  'barra2.diario-illeggibile': 'O diário do Lode neste computador não pode ser lido',
  'barra2.diario-illeggibile-nota': 'Nada foi apagado: a pasta de dados do Lode não responde (disco cheio ou com defeito?). As alterações de agora vão para um arquivo separado.',
  'barra2.riprova': 'Tentar de novo',
  'barra2.vault-sparito': 'Os dados do Lode deste computador estão seguros no diário dele. Se você moveu o vault, escolha a pasta onde colocou.',
  'barra2.trova-vault': 'Encontrar o vault',
  'barra2.lode-vecchia-campi': { one: '<b>De um Lode antigo:</b> {n} campo diferente dos de agora. Ele não muda nada sozinho: a cópia do arquivo está na pasta de dados do Lode (sync/copie).', other: '<b>De um Lode antigo:</b> {n} campos diferentes dos de agora. Eles não mudam nada sozinhos: a cópia do arquivo está na pasta de dados do Lode (sync/copie).' },
  'barra2.aggiunte': { one: '<b>Dados de outra primeira instalação ou de um Lode antigo:</b> {n} registro (provas, cartões, sessões…) que o diário não tem. Não entra sozinho.', other: '<b>Dados de outra primeira instalação ou de um Lode antigo:</b> {n} registros (provas, cartões, sessões…) que o diário não tem. Não entram sozinhos.' },
  'barra2.importa-aggiunte': 'Importar os acréscimos',
  'barra2.password-dati-lode': 'Senha dos dados do Lode',
  'barra2.intanto-funziona': 'Enquanto isso, o Lode funciona com os dados deste computador: as alterações esperam no diário. {portachiavi}',
  'barra2.ho-dimenticato-password': 'Esqueci a senha',
  'barra2.dimentica-password-qui': 'Esquecer a senha aqui',
  'barra2.cifrati-in-chiaro': '<b>Criptografados:</b> {cifrati}. <b>Abertos na pasta da nuvem:</b>',
  'barra2.cambia-password': 'Trocar senha',
  'barra2.senza-password': 'Sem senha: quem pode ler sua pasta da nuvem também pode ler os dados do Lode, como já acontece com as anotações.',
  'barra2.proteggi-password': 'Proteger com uma senha',
  'barra2.recuperi': 'As alterações que o diário não conseguiu receber estão em {n} arquivos «recupero-…json» (o último: «{file}»), na pasta de dados do Lode: não joguei fora.',
  'barra2.recupero': 'As alterações que o diário não conseguiu receber estão no arquivo «{file}», na pasta de dados do Lode: não joguei fora.',
  'barra2.smetti-qui': 'Parar neste computador',
  'barra2.importati-record': { one: '{n} registro importado.', other: '{n} registros importados.' },
  'barra2.ora-su-tutti': 'Agora estão em todos os computadores.',
  'barra2.non-andata-punto': 'Não deu certo.',
  'barra2.controllo': 'Verificando…',
  'barra2.sbloccata': 'Desbloqueada.',
  'barra2.password-ricordata': 'A senha está guardada neste computador.',
  'barra2.chiedero-prossimo-avvio': 'Vou pedir na próxima vez que o Lode iniciar.',
  'barra2.password-nuova-almeno-8': 'Senha nova (pelo menos 8 caracteres)',
  'barra2.password-nuova': 'Senha nova',
  'barra2.password-nuova-pronta': 'Senha nova pronta.',
  'barra2.altri-chiederanno': 'Os outros computadores vão pedir uma vez.',
  'barra2.cambiare-password': 'Trocar a senha?',
  'barra2.rifa-password-nuova': 'O Lode refaz os dados do Lode na pasta da nuvem com a senha nova. {testo}',
  'barra2.scegliere-password-nuova': 'Escolher uma senha nova?',
  'barra2.proteggere-password': 'Proteger os dados do Lode com uma senha?',
  'barra2.rifa-cifrati': 'O Lode refaz os dados do Lode na pasta da nuvem, criptografados com a senha. Os outros computadores vão pedir ela. {testo}',
  'barra2.password-dimenticata': 'Senha esquecida neste computador.',
  'barra2.chiedero-di-nuovo': 'Vou pedir de novo.',
  'barra2.smettere-qui': 'Parar neste computador?',
  'barra2.vault-copiato-fuori': 'copiado para uma pasta fora da pasta da nuvem, que você escolhe',
  'barra2.tutti-dati': 'todos, inclusive os dos outros computadores até hoje',
  'barra2.gli-altri-computer': 'Os outros computadores',
  'barra2.continuano-sincronizzarsi': 'continuam sincronizando entre si',
  'barra2.smesso-qui': 'Parado neste computador.',
  'barra2.smesso-nota': 'O vault agora está fora da pasta da nuvem. Para parar em todos, faça isso em cada computador.',
  'barra2.sintesi-smessa': 'sincronização parada aqui',
  'barra2.ultima-lezione': 'Última aula',
  'barra2.lezione-di': 'Aula de {corso}',
  'barra2.cosa-sa-lode': 'O que o Lode sabe de mim',
  'barra2.vai-a-note': { one: 'Ir para… · {n} nota', other: 'Ir para… · {n} notas' },
  'barra2.radice-vault': 'vault',
  'barra2.oggi': 'hoje',
  'barra2.cerca-nota-segnaposto': 'Procure uma nota: disciplina, aula, data…',
  'barra2.cerca-nota': 'Procurar uma nota',
  'barra2.nessuna-nota': 'Nenhuma nota encontrada.',
  'barra2.sintesi-cerco': 'procurando «{q}»',
  'barra2.sintesi-note': 'notas',
  'barra2.niente-appunti-di': 'Não encontro anotações de **{corso}** nos últimos dias.',
  'barra2.niente-appunti': 'Não encontro uma aula com anotações suficientes: escreva na seção «{sezione}» da nota.',
  'barra2.appunti-serve-ai': 'Para ler as anotações, precisa da IA: instale o **cérebro local** (grátis, funciona offline) em «Preparar o Lode», ou conecte a sua IA: escreva «IA».',
  'barra2.leggo-appunti-di': 'Lendo as anotações de {corso}…',
  'barra2.appunti-illeggibili': 'Não consegui ler as anotações: {errore}',
  'barra2.nessuna-definizione-nuova': 'Não encontrei definições novas nas anotações. Tente escrever por extenso, mesmo curtas.',
  'barra2.aggiungere-a': 'Adicionar a {corso} · {data}?',
  'barra2.chiudi-nota': { one: '{n} definição na nota da aula. Confira se está certa: quem escreveu foi {motore}.', other: '{n} definições na nota da aula. Confira se estão certas: quem escreveu foi {motore}.' },
  'barra2.chiudi-nota-stelle': { one: '{n} definição e {stelle} ★ na nota da aula. Confira se está tudo certo: quem escreveu foi {motore}.', other: '{n} definições e {stelle} ★ na nota da aula. Confira se está tudo certo: quem escreveu foi {motore}.' },
  'barra2.lezione-chiusa': 'Aula fechada.',
  'barra2.definizioni-pronte': { one: '{n} definição pronta para os jogos.', other: '{n} definições prontas para os jogos.' },
  'barra2.sintesi-definizioni': { one: '{n} definição', other: '{n} definições' },
  'barra2.appunti-sparsi-oggi': 'as anotações soltas de hoje',
  'barra2.la-nota-di': 'a nota de {corso}',
  'barra2.apro-in-obsidian': 'Abrindo {nome} no Obsidian.',
  'barra2.apro-se-non-trova': 'Abrindo {nome}. Se o Obsidian não encontrar o vault, na primeira vez use **Abrir pasta como cofre** e escolha a pasta «{percorso}»: depois fica conectado.',
  'barra2.aperto-editor': 'Abri {nome} com o editor do sistema. Com o **Obsidian** (grátis, obsidian.md) o vault «{percorso}» já está pronto: pastas, modelos, horário e a sua memória.',
  'barra2.nota-non-si-apre': 'Não consigo abrir a nota: {errore}',
  'barra2.appunti-solo-app': 'As anotações no Obsidian estão no **app para desktop** do Lode: lá cada aula vira uma nota do seu vault, com as ★ e as definições que você marca pela barra.',
  'barra2.gioco-sai-gia-di': 'As definições de {corso} de hoje você já sabe: elas voltam quando estiverem quase escapando.',
  'barra2.gioco-sai-gia': 'As definições de hoje você já sabe: elas voltam quando estiverem quase escapando.',
  'barra2.gioco-nessuna-di': 'Nenhuma definição de {corso} ainda. Na aula, aperte **Definição** (ou escreva «def: termo = definição»), ou escreva no Obsidian na seção «{sezione}» da aula.',
  'barra2.gioco-nessuna': 'Nenhuma definição ainda. Na aula, aperte **Definição** (ou escreva «def: termo = definição»), ou escreva no Obsidian na seção «{sezione}» da aula.',
  'barra2.gioco-di': 'Jogo · {corso}',
  'barra2.ultime-lezioni': 'últimas aulas',
  'barra2.manche-di': '{i} de {n}',
  'barra2.abbina': 'Ligue cada termo à sua definição.',
  'barra2.chi-sono': 'Quem sou eu?',
  'barra2.completa': '{termine}: complete a definição.',
  'barra2.parola-mancante': 'Palavra que falta',
  'barra2.controlla-invio': 'Conferir <kbd>Enter</kbd>',
  'barra2.non-la-so': 'Não sei',
  'barra2.te-la-ricordi': 'Você lembra?',
  'barra2.mostra-spazio': 'Mostrar <kbd>Espaço</kbd>',
  'barra2.non-la-sapevo': 'Não sabia <kbd>1</kbd>',
  'barra2.la-sapevo': 'Sabia <kbd>2</kbd>',
  'barra2.tutte-giuste': 'Todas certas. Essas ficaram.',
  'barra2.da-rinforzare': 'Para reforçar: {elenco}. Voltam amanhã.',
  'barra2.secondi': { one: '{n} segundo', other: '{n} segundos' },
  'barra2.minuti': '{n} min',
  'barra2.sintesi-punti': '{punti} de {tot}',
  'barra2.ancora-una': 'Mais uma',
  'barra2.gioca-ancora': 'Jogar de novo',
  'barra2.sintesi-gioco': 'jogo',
  'barra2.pausa-finita': 'Fim da pausa.',
  'barra2.fermato-dopo': 'Parado depois de {tempo}.',
  'barra2.prova-resta-aperta': 'O simulado continua aberto: escreva «simulado» para entregar.',
  'barra2.li-conto': 'Conto nas horas de estudo.',
  'barra2.sintesi-timer-fermato': 'timer parado',
  'barra2.nessun-timer': 'Não tem nenhum timer ligado.',
  'barra2.timer-in-pausa': 'Timer em pausa.',
  'barra2.scrivi-riprendi': 'Escreva «continua» quando voltar.',
  'barra2.si-riparte': 'Bora de novo.',
  'barra2.focus-esame-sconosciuto': 'Não encontro **{nome}** nas suas provas. Começo um estudo livre? Escreva «foco {min}».',
  'barra2.di-quale-esame': 'De qual prova?',
  'barra2.idoneita-registrata': '{nome}: aprovação registrada.',
  'barra2.voto-in': '{voto} em {nome}.',
  'barra2.voto-lode-in': '{voto} com louvor em {nome}.',
  'barra2.nuovo-esame-6-cfu': 'Prova nova de 6 créditos: corrija os créditos no histórico.',
  'barra2.media-diff': 'Média {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome}: {voto}',
  'barra2.idoneita': 'aprovado sem nota',
  'barra2.trenta-e-lode': 'Trinta com louvor. Essa merece comemoração.',
  'barra2.bel-colpo': 'Mandou bem. Hoje respira, amanhã a gente volta.',
  'barra2.esame-aggiornato': '{nome} atualizada.',
  'barra2.esame-aggiunto': '{nome} adicionada.',
  'barra2.esame-nota': '{quando} · {cfu} créditos',
  'barra2.esame-nota-cambiali': '{quando} · {cfu} créditos (mude se forem mais)',
  'barra2.senza-data': 'sem data',
  'barra2.piano-ore': 'Para chegar pronto: cerca de **{h} h por dia** ({tot} h no total).',
  'barra2.proposte-spente-riaccendi': 'As sugestões estão desligadas: ligue de novo com «sugestões normais».',
  'barra2.proposte-da-adesso': 'A partir de agora, quando você estiver no computador e livre, vou sugerir jogos, revisões e perguntas sobre {nome}.',
  'barra2.proposte-da-adesso-vicino': 'A partir de agora, quando você estiver no computador e livre, vou sugerir jogos, revisões e perguntas sobre {nome}, cada vez mais à medida que a data chega.',
  'barra2.carta-aggiunta': 'Cartão adicionado.',
  'barra2.senza-esame': 'sem prova',
  'barra2.esame-sconosciuto': 'Não encontro **{nome}** nas suas provas.',
  'barra2.spiego-senza-programma': 'Primeiro cole a ementa de uma prova («ementa de cálculo 2»): depois você me explica os tópicos e eu digo o que você deixou de fora.',
  'barra2.argomento-sconosciuto': 'Não encontro **{q}** nas ementas das suas provas.',
  'barra2.esame-non-trovato': 'Não encontro a prova **{nome}**.',
  'barra2.domande-di-quale-esame': 'De qual prova? Por exemplo: «perguntas que caíram na prova de cálculo 2: …».',
  'barra2.nella-nota-lezione': 'Na nota da aula.',
  'barra2.in-orario': '{corso} no horário.',
  'barra2.aula': 'sala {aula}',
  'barra2.sintesi-in-orario': '{corso} no horário',
  'barra2.orario-spiegazione': 'Quando você está em aula a barra sabe: ela abre na captura rápida (★ cai na prova, definições, perguntas) e em casa sugere dois minutos de jogo sobre o que você acabou de ver.',
  'barra2.proposte-spente': 'Sugestões desligadas.',
  'barra2.proposte-poche': 'Poucas sugestões.',
  'barra2.proposte-normali': 'Sugestões normais.',
  'barra2.proposte-frequenti': 'Sugestões frequentes.',
  'barra2.riaccendi-quando-vuoi': 'Ligue de novo quando quiser.',
  'barra2.proposte-mai-quando': 'Nunca na aula, no trabalho, no foco ou nas horas de silêncio.',
  'barra2.niente-da-proporre': 'Por enquanto não tenho nada para sugerir: adicione uma prova com a data, ou marque algumas definições na aula.',
  'barra2.trascrizione-in-pausa': 'Transcrição em pausa.',
  'barra2.scrivi-riprendi-trascrizione': 'Escreva «continua a transcrição» quando recomeçar.',
  'barra2.riprendo-trascrivere': 'Voltando a transcrever.',
  'barra2.err-valutato': 'Projeto avaliado: a correção eu não mostro.',
  'barra2.errore-spiegato': 'Erro explicado',
  'barra2.correzione-vista': 'correção vista',
  'barra2.copia-errore': 'Copie o erro do terminal (ou da IDE) e escreva de novo «explica o erro».',
  'barra2.incolla-errore': 'Cole o erro depois dos dois-pontos: «explica o erro: …».',
  'barra2.nessun-errore-nel-testo': 'Neste texto não encontro um erro do compilador ou do programa. Copie tudo, a partir da linha com o nome do arquivo, e tente de novo.',
  'barra2.segui-valutato': 'Você está seguindo um projeto avaliado: a correção eu não mostro.',
  'barra2.diario-solo-app': 'O diário fica no vault: precisa do **app para desktop** do Lode.',
  'barra2.progetto-sconosciuto': 'Não encontro um projeto chamado «{nome}».',
  'barra2.nessun-progetto-segui': 'Ainda não estou seguindo nenhum projeto. Escreva **segue o projeto** e escolha a pasta do laboratório.',
  'barra2.diario-spento-per': 'Para **{progetto}** o diário está desligado: não escrevo nada no vault. Ligue de novo com «liga o diário de {progetto}».',
  'barra2.diario-non-si-apre': 'Não consigo abrir o diário: {errore}',
  'barra2.diario-di': 'Diário de {progetto}.',
  'barra2.aperto-editor-sistema': 'Aberto com o editor do sistema: com o Obsidian é mais prático.',
  'barra2.aperto-in-obsidian': '{file} · aberto no Obsidian.',
  'barra2.sintesi-diario-di': 'diário de {progetto}',
  'barra2.nessun-progetto': 'Ainda não estou seguindo nenhum projeto.',
  'barra2.diario-acceso': 'Diário de {nome} ligado.',
  'barra2.diario-acceso-nota': 'Escrevo no vault o que eu vejo: o que muda e os testes. Não sei quem escreve as linhas.',
  'barra2.diario-spento': 'Diário de {nome} desligado.',
  'barra2.diario-spento-nota': 'A partir de agora não escrevo nada deste projeto no vault. As notas já escritas ficam: você pode tirar pelo Obsidian.',
  'barra2.focus-di-minuti': 'Foco de {min} minutos.',
  'barra2.focus-di-minuti-su': 'Foco de {min} minutos em {nome}.',
  'barra2.salvare-carte': { one: 'Salvar {n} cartão?', other: 'Salvar {n} cartões?' },
  'barra2.salvare-carte-di': { one: 'Salvar {n} cartão de {nome}?', other: 'Salvar {n} cartões de {nome}?' },
  'barra2.entrano-ripasso': 'Eles entram na revisão de hoje.',
  'barra2.carte-salvate': { one: '{n} cartão salvo.', other: '{n} cartões salvos.' },
  'barra2.ripassa-ora': 'Revisar agora',
  'barra2.sintesi-carte': { one: '{n} cartão', other: '{n} cartões' },
  'barra2.aggiungere-esame': 'Adicionar {nome}?',
  'barra2.esame': 'Prova',
  'barra2.cfu': 'Créditos',
  'barra2.appello': 'Data',
  'barra2.registrare-voto': 'Registrar {voto}?',
  'barra2.registrare-voto-lode': 'Registrar {voto} com louvor?',
  'barra2.esame-nuovo-6-cfu': '{nome} (nova, 6 créditos)',
  'barra2.voto': 'Nota',
  'barra2.voto-e-lode': '{voto} com louvor',
  'barra2.voto-registrato': 'Nota registrada.',
  'barra2.media': 'Média {media}',
  'barra2.leggo-il-file': 'Lendo o arquivo…',
  'barra2.prof-ci-pensa': 'O professor está pensando…',
  'barra2.un-attimo': 'Só um instante…',
  'barra2.file-senza-carte-locale': 'Não consegui tirar cartões deste arquivo: se for um PDF, o modelo local não lê. Tente com uma foto das páginas ou com o texto.',
  'barra2.file-illeggibile': 'Não consegui ler o arquivo: {errore}',
  'barra2.chiave-non-valida-ricollega': 'A chave não é válida: conecte de novo escrevendo «IA».',
  'barra2.troppe-richieste': 'Pedidos demais em pouco tempo: tente de novo daqui a um minuto.',
  'barra2.sovraccarico': '{motore} está sobrecarregado agora: tente de novo daqui a pouco.',
  'barra2.manca-rete': 'Parece que está sem internet.',
  'barra2.qualcosa-non-andato': 'Algo deu errado: {errore}',
  'barra2.orale-serve-ai-app': 'Para a prova oral, precisa da IA: instale o **cérebro local** em «Preparar o Lode» (grátis, offline) ou conecte a sua IA (escreva «IA»). Enquanto isso, você pode fazer a **revisão** dos cartões.',
  'barra2.orale-serve-ai-web': 'Para a prova oral, precisa da IA: adicione sua chave do Claude em **Configurações** (custa poucos centavos por sessão). Enquanto isso, você pode fazer a **revisão** dos cartões.',
  'barra2.orale-esame-sconosciuto': 'Não encontro **{nome}**: vou testar você sobre isso mesmo assim.',
  'barra2.su-quale-esame': 'Sobre qual prova?',
  'barra2.aggiungi-prima-esame': 'Primeiro adicione uma prova.',
  'barra2.interrogami-su': 'Me testa sobre {nome}',
  'barra2.orale-di-contesto': 'Prova oral · <b>{nome}</b>',
  'barra2.esci': 'Sair',
  'barra2.sintesi-orale-di': 'prova oral de {nome}',
  'barra2.domanda-n-di': '**Pergunta {n} de {max}.** {domanda}',
  'barra2.prof-non-risponde': 'O professor não responde: {errore}',
  'barra2.prof-ascolta': 'O professor está ouvindo…',
  'barra2.orale-mancava': 'Faltou: {cosa}',
  'barra2.era-giusta': 'Estava certa',
  'barra2.segnata-giusta': 'Marcada como certa',
  'barra2.prof-scrive-voto': 'O professor está dando a nota…',
  'barra2.orale-titolo': { one: 'Prova oral · {nome} · {n} pergunta', other: 'Prova oral · {nome} · {n} perguntas' },
  'barra2.da-ripassare': 'Para revisar',
  'barra2.orale-calcolo': 'A nota é calculada pelo Lode a partir das suas respostas (certa 3 pontos, parcial 2).',
  'barra2.orale-calcolo-contestate': { one: 'A nota é calculada pelo Lode a partir das suas respostas (certa 3 pontos, parcial 2), contando a resposta que você marcou como certa.', other: 'A nota é calculada pelo Lode a partir das suas respostas (certa 3 pontos, parcial 2), contando as respostas que você marcou como certas.' },
  'barra2.orale-giudizi-locale': 'As avaliações são a opinião do modelo local: ele pode errar. É um treino, não uma previsão.',
  'barra2.orale-giudizi-ai': 'As avaliações são a opinião da IA. É um treino, não uma previsão.',
  'barra2.sintesi-orale-voto': 'prova oral de {nome}: {voto}',
  'barra2.orale-chiuso': 'Prova oral encerrada.',
  'barra2.ripassa-esitato': 'Revise as perguntas em que você hesitou.',
  'barra2.agenti-solo-app': 'A ponte com os agentes está no **app para desktop** do Lode.',
  'barra2.ponte-non-risponde': 'A ponte não responde: {errore}',
  'barra2.agente-sconosciuto': 'Ainda não sei me conectar ao **{agente}**. Escreva «agentes» para ver os que eu conheço.',
  'barra2.agenti-titolo': 'Agentes de programação',
  'barra2.agenti-spiegazione': 'Conecte o agente que você usa nos laboratórios: no fim de cada rodada o Lode diz o que ele mexeu de verdade nos projetos que você segue, se rodou os testes depois da última alteração e se mudou os testes enquanto eles falhavam.',
  'barra2.ag-collegato-eventi': { one: 'conectado · {n} evento, às {ora}', other: 'conectado · {n} eventos, o último às {ora}' },
  'barra2.ag-collegato-nessuno': 'conectado · nenhum evento ainda',
  'barra2.ag-trovato': 'encontrado neste computador',
  'barra2.ag-non-trovato': 'não encontrado',
  'barra2.scollega': 'Desconectar',
  'barra2.agenti-nota': 'Só leitura: o Lode não responde aos agentes, não decide nada e não amplia as permissões deles. Antes de escrever na configuração deles, ele mostra as linhas exatas. Os eventos só contam nos projetos que você segue («segue o projeto»), os outros vão para o lixo; o texto que você escreve para o agente não é salvo.',
  'barra2.sintesi-agenti': 'agentes',
  'barra2.niente-toccato': 'Tudo bem, não mexi em nada.',
  'barra2.ag-scollegato': '{nome} desconectado.',
  'barra2.ag-gia-collegato': '{nome} já estava conectado.',
  'barra2.ag-collegato': '{nome} conectado.',
  'barra2.ag-tolte-righe': 'Tirei só as minhas linhas.',
  'barra2.ag-poi-segui': 'Depois siga o projeto do laboratório («segue o projeto»).',
  'barra2.l-agente': 'O agente',
  'barra2.ag-finito-test-dopo': { one: 'terminou: {n} arquivo, testes rodados depois da última alteração', other: 'terminou: {n} arquivos, testes rodados depois da última alteração' },
  'barra2.ag-finito-test-prima': { one: 'terminou: {n} arquivo, testes não rodados de novo', other: 'terminou: {n} arquivos, testes não rodados de novo' },
  'barra2.ag-finito-senza-test': { one: 'terminou: {n} arquivo, nenhum teste', other: 'terminou: {n} arquivos, nenhum teste' },
  'barra2.guarda': 'Ver',
  'barra2.nessun-turno': 'Ainda nenhuma rodada de agente nos projetos que você segue. Escreva «agentes» para conectar um.',
  'barra2.esito-non-noto': 'resultado desconhecido',
  'barra2.riuscito': 'passou',
  'barra2.fallito-codice': 'falhou (código {codice})',
  'barra2.alle': 'às {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> arquivo alterado: {elenco}.', other: '<b>{n}</b> arquivos alterados: {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> arquivos alterados.',
  'barra2.comandi': { one: '{n} comando', other: '{n} comandos' },
  'barra2.test-lanciati-dopo': { one: 'testes rodados {n} vez, a última <code>{comando}</code> {esito}, depois da última alteração', other: 'testes rodados {n} vezes, a última <code>{comando}</code> {esito}, depois da última alteração' },
  'barra2.test-lanciati-prima': { one: 'testes rodados {n} vez, a última <code>{comando}</code> {esito}, <b>antes</b> da última alteração', other: 'testes rodados {n} vezes, a última <code>{comando}</code> {esito}, <b>antes</b> da última alteração' },
  'barra2.nessun-test-lanciato': 'nenhum teste rodado',
  'barra2.cosa-cambiato': 'O que mudou',
  'barra2.prova-tu': 'Teste você',
  'barra2.preparati-discussione': 'Prepare-se para a apresentação',
  'barra2.parole-agente': 'O que o agente diz são palavras: ele só rodou os testes de verdade se você vê eles aqui. As regras são fixas: se não acharem nada, não é garantia.',
  'barra2.prova-il-progetto': 'Testar o projeto',
  'barra2.sintesi-turno': { one: '{chi}: {n} arquivo', other: '{chi}: {n} arquivos' },
};
