// A barra (js/lode.js, primeira parte: pílula, painel, home, ferramentas, revisão, horário, transcrição, arquivos), em português do Brasil.
export default {
  // as teclas para falar e os números escritos por extenso («Três cartões para revisar»)
  'barra1.tasti-mac': '⌥ Espaço',
  'barra1.tasti': 'Ctrl ⇧ Espaço',
  'barra1.numeri': ['Nenhum', 'Um', 'Dois', 'Três', 'Quatro', 'Cinco', 'Seis', 'Sete', 'Oito', 'Nove', 'Dez'],
  // a saudação e a frase no topo do painel
  'barra1.saluto-notte': 'Ainda acordado',
  'barra1.saluto-mattina': 'Bom dia',
  'barra1.saluto-pomeriggio': 'Boa tarde',
  'barra1.saluto-sera': 'Boa noite',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': 'Hoje tem {nome}. Boa prova!',
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} cartão para revisar.', other: '{quante} cartões para revisar.' },
  'barra1.niente-in-sospeso': 'Nada pendente hoje.',
  'barra1.dimmi-esame': 'Me diz sua próxima prova e eu preparo o plano.',
  // a concha: campo, rodapé, arquivos arrastados
  'barra1.aria-lode': 'Lode, assistente de estudo',
  'barra1.aria-torna-home': 'Voltar para a home do Lode',
  'barra1.indietro': 'Voltar',
  'barra1.aria-campo': 'Pergunte ou escreva um comando',
  'barra1.campo': 'Pergunte ou escreva um comando…',
  'barra1.ti-ascolto': 'Estou ouvindo',
  'barra1.esc-annulla': 'Esc cancela',
  'barra1.un-attimo': 'Só um instante…',
  'barra1.aria-parla': 'Fale (ou segure {tasti})',
  'barra1.tieni-premuto': 'Segure para falar <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'Os dados ficam neste computador',
  'barra1.lascia-file': 'Solte o arquivo aqui',
  'barra1.lascia-file-cosa': 'PDF, slides, anotações, foto do quadro: o Lode transforma em cartões de revisão',
  'barra1.dopo': 'Depois',
  // «Hoje»: as linhas da home
  'barra1.di-stamattina': 'de hoje de manhã',
  'barra1.di-oggi': 'de hoje',
  'barra1.di-ieri': 'de ontem',
  'barra1.di-giorno': 'de {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} definição de {corso} {quando}', other: '{n} definições de {corso} {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} definição das últimas aulas', other: '{n} definições das últimas aulas' },
  'barra1.sync-bloccata': 'O Lode está funcionando com os dados deste computador: as alterações esperam no diário.',
  'barra1.sblocca': 'Desbloquear',
  'barra1.sync-sparita': 'A pasta do Lode no vault sumiu',
  'barra1.sync-sparita-dett': 'Foi movida ou apagada? Os dados deste computador estão seguros no diário dele.',
  'barra1.vedi': 'Ver',
  'barra1.sync-spostamento': 'A mudança para a pasta da nuvem foi interrompida',
  'barra1.sync-spostamento-dett': 'O vault anterior está intacto: continuo de onde parei.',
  'barra1.riprendi': 'Continuar',
  'barra1.detto-sincronizza': 'Sincronizar entre computadores',
  'barra1.dati-altrove': 'Este vault sincroniza com o Lode em outro computador',
  'barra1.dati-altrove-dett': 'Os dados estão no diário do Lode 2: escolha «Já uso o Lode em outro computador» para ver eles aqui. As alterações de agora vão para um arquivo separado, não por cima dos dados.',
  'barra1.uso-gia-lode': 'Já uso o Lode',
  'barra1.detto-uso-gia-lode': 'Já uso o Lode em outro computador',
  'barra1.dati-fermo': 'O diário do Lode neste computador não pode ser lido',
  'barra1.dati-fermo-dett': 'Nada foi apagado: a pasta de dados do Lode não responde (disco cheio ou com defeito?).',
  'barra1.riprova': 'Tentar de novo',
  'barra1.dati-illeggibili': 'Não consigo ler seus dados',
  'barra1.dati-illeggibili-dett': 'Provas, notas e cartões estão seguros, mas a pasta não responde (OneDrive offline ou arquivo bloqueado). As alterações de agora vão para um arquivo separado; tento de novo sozinho.',
  'barra1.lezione-alle': '{corso} às {ora}',
  'barra1.lezione-aula-tra': 'Sala {aula} · daqui a {n} min',
  'barra1.lezione-tra': 'daqui a {n} min',
  'barra1.appunti': 'Anotações',
  'barra1.orario': 'Horário',
  'barra1.completa-lode': 'Complete o Lode',
  'barra1.completa-tutti-e-due': 'Obsidian e o cérebro local: um clique, grátis',
  'barra1.completa-obsidian': 'Obsidian: um clique, grátis',
  'barra1.completa-cervello': 'o cérebro local: um clique, grátis',
  'barra1.prepara': 'Preparar',
  'barra1.detto-prepara-lode': 'Preparar o Lode',
  'barra1.chiudi-lezione-di': 'Fechar a aula de {corso}',
  'barra1.chiudi-lezione-dett': '{n} palavras de anotações · extraio definições e ★',
  'barra1.chiudi': 'Fechar',
  'barra1.detto-chiudi-lezione': 'Fechar aula',
  'barra1.gioco-due-minuti': 'Jogo de dois minutos',
  'barra1.gioca': 'Jogar',
  'barra1.esame-ore-oggi': '{data} · {ore} h hoje para ficar em dia',
  'barra1.esame-in-pari': '{data} · hoje você está em dia',
  'barra1.focus': 'Foco',
  'barra1.ripasso': 'Revisão',
  'barra1.ripasso-carte-min': { one: '{n} cartão · cerca de {min} min', other: '{n} cartões · cerca de {min} min' },
  'barra1.inizia': 'Começar',
  'barra1.studio-oggi': '{ore} de estudo hoje',
  'barra1.non-hai-studiato': 'Você ainda não estudou hoje',
  'barra1.giorni-di-fila': { one: '{n} dia seguido', other: '{n} dias seguidos' },
  'barra1.bastano-25': '25 minutos bastam para começar uma sequência',
  'barra1.libretto': 'Histórico',
  // em aula, Repete, a transcrição, a home
  'barra1.in-aula': 'Em aula · {corso}',
  'barra1.aula-finisce-tra': 'sala {aula} · termina daqui a {n} min',
  'barra1.finisce-tra': 'termina daqui a {n} min',
  'barra1.cattura-stella': '★ Cai na prova',
  'barra1.cattura-definizione': 'Definição',
  'barra1.cattura-domanda': 'Pergunta',
  'barra1.cose-segnate': { one: '{quante} coisa marcada para a prova hoje.', other: '{quante} coisas marcadas para a prova hoje.' },
  'barra1.ripeti-attivo-memoria': 'Repete ativo · só na memória, nunca no disco',
  'barra1.ripeti': 'Repete',
  'barra1.spegni': 'Desligar',
  'barra1.ripeti-spento-invito': '<b>Repete 60 s</b> · perdeu uma frase? O Lode repete para você. Nada é salvo.',
  'barra1.trascrivi-lezione': 'Transcrever a aula',
  'barra1.trascrivi-lezione-dett': 'Tudo o que o professor fala, fórmulas incluídas, na nota do Obsidian · {tasti}',
  'barra1.trascrizione-in-pausa': 'Em pausa · {min} min · {parole} palavras',
  'barra1.trascrizione-in-corso': 'Transcrevendo · {min} min · {parole} palavras',
  'barra1.prima-riga': 'Ouvindo: a primeira linha chega em uns vinte segundos.',
  'barra1.pausa': 'Pausa',
  'barra1.fine': 'Fim',
  'barra1.oggi': 'Hoje',
  'barra1.cfu-di': '{fatti} de {tot} créditos',
  'barra1.inizia-da-qui': 'Comece por aqui',
  'barra1.inizia-da-qui-dett': 'Escreva «aula cálculo 2 segunda 9-11 sala 7», ou teste os dados de exemplo',
  'barra1.esempio': 'Exemplo',
  // as ferramentas e o topo do painel
  'barra1.strumento-gioco': 'Jogo',
  'barra1.strumento-codice': 'Código',
  'barra1.strumento-note': 'Notas',
  'barra1.strumento-interrogami': 'Me testa',
  'barra1.strumento-esami': 'Provas',
  'barra1.sei-a-lezione': 'Você está na aula de {corso}. Faça suas anotações tranquilo: eu cuido para não perder nada.',
  'barra1.testa-media': 'média {media}',
  'barra1.testa-serie': { one: 'sequência de {n} dia', other: 'sequência de {n} dias' },
  // a pílula
  'barra1.ripeti-attivo-titolo': 'Repete ativo: o último minuto e meio, só na memória',
  'barra1.in-pausa': 'em pausa',
  'barra1.pausa-minuscolo': 'pausa',
  'barra1.aria-timer': '{cosa}: faltam {resta}',
  'barra1.prova-generale': 'Simulado',
  'barra1.focus-su': 'Foco em {nome}',
  'barra1.aria-ripeti-acceso': '. Repete: microfone ligado',
  'barra1.pillola-trascrizione-in-pausa': 'transcrição em pausa · {parole} palavras',
  'barra1.pillola-trascrivo': 'transcrevendo · {parole} palavras',
  'barra1.fine-tra': 'termina em {n} min',
  'barra1.pillola-aula-tra': 'sala {aula} · em {n} min',
  'barra1.microfono-acceso': 'microfone ligado',
  'barra1.due-minuti': '2 minutos',
  'barra1.pillola-tra-giorni': 'em {n} d',
  // em italiano a pílula diz «carte» mesmo com um cartão só; em português, singular e plural certos
  'barra1.pillola-carte': { one: '{n} cartão', other: '{n} cartões' },
  'barra1.pillola-da-ripassare': { one: 'cartão para revisar', other: 'cartões para revisar' },
  'barra1.passa-qui-sopra': 'passe o mouse aqui',
  'barra1.aria-pillola': 'Lode: {testo}{ripeti}. Passe o mouse por cima ou aperte {tasti}.',
  // a conversa, «Pronto.», «Confirmar / Cancelar»
  'barra1.altre-righe': { one: '{n} linha', other: '{n} linhas' },
  'barra1.altro': 'mais',
  'barra1.fatto': 'Pronto.',
  'barra1.annulla': 'Cancelar',
  'barra1.annullato-minuscolo': 'cancelado',
  'barra1.confermi': 'Confirma?',
  'barra1.conferma': 'Confirmar',
  'barra1.scrivi-si': 'Você também pode escrever «sim».',
  'barra1.annullato': 'Cancelado.',
  'barra1.niente-cambiato': 'Não mudei nada.',
  // Foco
  'barra1.durata': 'Duração',
  'barra1.min': 'min',
  'barra1.su-che-cosa': 'Em quê',
  'barra1.studio-libero': 'Estudo livre',
  'barra1.pausa-alla-fine': 'Pausa de {n} minutos no fim. As horas contam no plano da prova.',
  'barra1.sintesi-focus': 'foco',
  'barra1.focus-di-min': 'Foco de {min} minutos.',
  'barra1.focus-di-min-su': 'Foco de {min} minutos em {nome}.',
  'barra1.ci-vediamo': 'Até a pausa.',
  'barra1.sintesi-focus-min': 'foco {min} min',
  // Histórico e «e se eu tirar…»
  'barra1.media-ponderata': 'Média ponderada',
  'barra1.aritmetica-esami': 'aritmética {media} · {n} provas',
  'barra1.nessun-voto': 'nenhuma nota ainda',
  'barra1.base-di-laurea': 'Base de formatura',
  'barra1.serve-gia': 'Para começar com <b>{obiettivo}</b> basta passar nas provas que faltam.',
  'barra1.serve-media': 'Para começar com <b>{obiettivo}</b> você precisa de média <b>{voto}</b> nos {cfu} créditos que faltam.',
  'barra1.serve-impossibile': 'Começar com <b>{obiettivo}</b> não é mais possível: mire em {punta}.',
  'barra1.e-se': 'E se…',
  'barra1.esame': 'Prova',
  'barra1.voto': 'Nota',
  'barra1.simula-esito': 'Média <b>{media}</b> <span class="{classe}">{delta}</span> · base <b>{base}</b>',
  'barra1.sintesi-media-base': 'média {media}, base {base}',
  'barra1.sintesi-libretto-vuoto': 'histórico vazio',
  'barra1.simula-non-trovo': 'Não encontro **{nome}** nas suas provas. Adicione com «prova {nome} 6 créditos».',
  'barra1.simula-primo': 'Com {voto} em **{nome}** sua média começaria em **{voto}**: base **{base}**.',
  'barra1.simula-primo-lode': 'Com {voto} com louvor em **{nome}** sua média começaria em **{voto}**: base **{base}**.',
  'barra1.simula': 'Com **{voto}** em {nome} a média vai de {prima} para **{dopo}** ({delta}): base de formatura **{base}**.',
  'barra1.simula-lode': 'Com **{voto} com louvor** em {nome} a média vai de {prima} para **{dopo}** ({delta}): base de formatura **{base}**.',
  'barra1.sintesi-media': 'média {media}',
  // Provas
  'barra1.incolla-programma': 'Cole a ementa: eu preparo o plano por tópicos',
  'barra1.giorno-cuscinetto': 'dia de folga',
  'barra1.ripasso-generale': 'revisão geral',
  'barra1.niente-di-nuovo': 'nada de novo',
  'barra1.pronto': '{n}% pronto',
  'barra1.prossimi-appelli': 'Próximas provas · {n}',
  'barra1.esame-riga': '{data} · {cfu} créditos · {fatte} de {tot} h',
  'barra1.ore-oggi': '{ore} h hoje',
  'barra1.giorni-parola': { one: 'dia', other: 'dias' },
  'barra1.nessun-appello': 'Nenhuma prova no calendário.',
  'barra1.senza-data': 'Sem data: {nomi}.',
  'barra1.nuovo-esame': 'Nova prova',
  'barra1.nome-esame': 'Nome da prova',
  'barra1.cfu': 'Créditos',
  'barra1.data-appello': 'Data da prova',
  'barra1.aggiungi': 'Adicionar',
  'barra1.programma-di': 'Ementa de {nome}',
  'barra1.esame-aggiunto': '{nome} adicionada.',
  'barra1.senza-data-nota': 'sem data',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': 'nenhuma prova',
  // Revisão
  'barra1.ripasso-di': 'Revisão · {nome}',
  'barra1.niente-da-ripassare': 'Nada para revisar hoje. O próximo cartão volta {quando}.',
  'barra1.nessuna-carta': 'Nenhum cartão ainda. Escreva «cartão: pergunta = resposta», ou arraste um PDF para cá.',
  'barra1.risposta': 'Resposta',
  'barra1.aggiungi-carta': 'Adicionar cartão',
  'barra1.carta-aggiunta': 'Cartão adicionado.',
  'barra1.torna-oggi': 'Ele volta hoje mesmo na revisão.',
  'barra1.sintesi-niente-da-ripassare': 'nada para revisar',
  'barra1.mostra-risposta': 'Mostrar resposta <kbd>Espaço</kbd>',
  'barra1.x-di-y': '{x} de {y}',
  'barra1.ripasso-finito': { one: 'Revisão concluída: {n} cartão em {min} min.', other: 'Revisão concluída: {n} cartões em {min} min.' },
  'barra1.difficili-domani': 'Os difíceis voltam amanhã.',
  'barra1.sintesi-carte-ripassate': { one: '{n} cartão revisado', other: '{n} cartões revisados' },
  'barra1.sintesi-ripasso-di': { one: 'revisão de {n} cartão', other: 'revisão de {n} cartões' },
  // os comandos para testar
  'barra1.prova-a-scrivere': 'Tente escrever',
  'barra1.aiuto-senza-ai': 'Com o cérebro local (grátis) ou a sua IA (escreva «IA») você também pode pedir explicações, criar cartões a partir de PDFs e treinar para a prova oral.',
  'barra1.sintesi-comandi': 'comandos',
  // Horário
  'barra1.orario-lezioni': { one: 'Horário · {n} aula por semana', other: 'Horário · {n} aulas por semana' },
  'barra1.corso-aula': '{corso} · sala {aula}',
  'barra1.punto-aula': ' · sala {aula}',
  'barra1.togli': 'Tirar {nome}',
  'barra1.corso': 'Disciplina',
  'barra1.giorni': 'Dias',
  'barra1.inizio': 'Início',
  'barra1.aula': 'Sala',
  'barra1.orario-nel-vault': 'O horário também está no vault, em «Orario.md»: você pode mudar pelo Obsidian.',
  'barra1.orario-oppure-scrivi': 'Ou escreva: «aula cálculo 2 segunda e quarta 9-11 sala 7».',
  'barra1.in-orario': '{corso} no horário.',
  'barra1.sintesi-lezioni-settimana': { one: '{n} aula por semana', other: '{n} aulas por semana' },
  // o plano para quem trabalha
  'barra1.ore-regola': { one: '{n} hora', other: '{n} horas' },
  'barra1.la-tua-settimana': 'Sua semana',
  'barra1.detto-piano-settimana': 'Plano da semana',
  'barra1.lavori': 'Você trabalha {turni}.',
  'barra1.lavori-nota': 'Tiro isso das horas de estudo, com meia hora para o trajeto. Nos dias de trabalho você estuda no máximo {tetto}: mude com «nos dias de trabalho estudo no máximo {altro} horas».',
  'barra1.turni-cambiati': 'Turnos alterados.',
  'barra1.turni-salvati': 'Turnos salvos.',
  'barra1.sintesi-lavoro': 'trabalho {turni}',
  'barra1.turni-tolti': 'Turnos removidos.',
  'barra1.turni-tolti-nota': 'O plano volta a contar o seu dia inteiro de estudo.',
  'barra1.giorno-non-lavori': '{giorno} você não trabalha.',
  'barra1.ore-libere': 'Essas horas voltam a ficar livres para estudar.',
  'barra1.giorno-lavori-anche': '{giorno} você também trabalha {da}–{a}.',
  'barra1.solo-quel-giorno': 'Só nesse dia: tiro das horas de estudo.',
  'barra1.tetto': 'Nos dias de trabalho você estuda no máximo {tetto}.',
  'barra1.tetto-nota': 'O plano é refeito com esse limite.',
  'barra1.studi-dalle': 'Você estuda das {da} às {a}.',
  'barra1.studi-dalle-nota': 'O plano usa só essas horas, menos aulas e trabalho.',
  'barra1.togli-scelta': 'Desfazer: {scelta}',
  'barra1.niente-nel-piano': 'nada no plano',
  'barra1.settimana-lavori': 'Você trabalha {turni}: tiro isso das horas de estudo, com meia hora para o trajeto. Nos dias de trabalho você estuda no máximo {tetto}.',
  'barra1.settimana-se-lavori': 'Se você trabalha, me conta: «trabalho segunda quarta sexta 14-19».',
  'barra1.settimana-un-esame': 'Com uma prova só e sem trabalho, o plano é o da ementa.',
  'barra1.settimana-stime': 'As horas são estimativas: um tópico novo cerca de 1 h, uma revisão cerca de 30 min.',
  'barra1.sintesi-la-tua-settimana': 'sua semana',
  // a captura rápida em aula
  'barra1.cattura-stella-campo': 'O que o professor disse que vai cair na prova?',
  'barra1.cattura-definizione-campo': 'Termo: definição',
  'barra1.cattura-domanda-campo': 'A pergunta para fazer ao professor',
  'barra1.scrivila-cosi': 'Escreva assim: **termo: definição**.',
  'barra1.errore-vault': 'Não consigo escrever no vault: {errore}',
  'barra1.dove-sparsi': 'nas anotações soltas de hoje',
  'barra1.dove-in': 'em {corso}',
  'barra1.segnato-dove': '★ Marcado {dove}.',
  'barra1.definizione-dove': '«{termine}» {dove}.',
  'barra1.domanda-dove': 'Pergunta salva {dove}.',
  // transcrever: em aula, do computador, de uma gravação
  'barra1.videolezioni-app': 'A transcrição das videoaulas está no **app para desktop** do Lode: ele ouve o áudio do computador e escreve na nota do Obsidian da aula.',
  'barra1.sto-gia-trascrivendo': 'Já estou transcrevendo.',
  'barra1.parole-finora': { one: '{n} palavra até agora.', other: '{n} palavras até agora.' },
  'barra1.lezione-dal-computer': 'Aula do computador',
  'barra1.computer-spiega': 'Comece a videoaula (na plataforma da sua universidade, no Teams, no Zoom ou onde você assiste): eu ouço o áudio que sai do computador e escrevo na nota da aula, fórmulas incluídas.',
  'barra1.nome-del-corso': 'Nome da disciplina',
  'barra1.computer-patto': 'Só para você estudar: não baixo o vídeo e não envio nada para a internet, o áudio não é salvo e na nota vai só o texto. As aulas são dos professores: não compartilhe a transcrição se o regulamento da sua universidade não permitir.',
  'barra1.computer-mac': 'Na primeira vez, o Mac pede permissão para gravar o áudio do sistema.',
  'barra1.computer-windows': 'No Windows você continua ouvindo o áudio normalmente: eu também ouço.',
  'barra1.computer-linux': 'No Linux eu ouço o «monitor» da saída de áudio.',
  'barra1.detto-trascrivi-videolezione': 'Transcrever a videoaula de {corso}',
  'barra1.sintesi-lezione-dal-computer': 'aula do computador',
  'barra1.computer-permesso-mac': 'O Mac não está me dando o áudio do computador: em **Ajustes do Sistema › Privacidade e Segurança › Gravação de Áudio da Tela e do Sistema**, ative o Lode e tente de novo (às vezes é preciso reabrir o Lode).',
  'barra1.computer-permesso': 'O sistema não está me dando o áudio do computador: tente de novo e confirme o pedido de compartilhamento.',
  'barra1.computer-non-sento-mac': 'Não consigo ouvir o áudio do computador (precisa do macOS 14.2 ou mais recente). {errore}',
  'barra1.computer-non-sento-windows': 'Não consigo ouvir o áudio do computador. {errore}',
  'barra1.computer-non-sento-linux': 'Não consigo ouvir o áudio do computador (precisa do PulseAudio ou do PipeWire). {errore}',
  'barra1.computer-muto': 'Não estou ouvindo nada do computador. A videoaula começou, com o volume alto?',
  'barra1.computer-muto-mac': 'Não estou ouvindo nada do computador. A videoaula começou, com o volume alto? Se sim, o Mac não está me dando o áudio: **Ajustes do Sistema › Privacidade e Segurança › Gravação de Áudio da Tela e do Sistema**, ative o Lode e tente de novo.',
  'barra1.trascrizione-app': 'A transcrição das aulas está no **app para desktop** do Lode: ele escreve direto na nota do Obsidian da aula.',
  'barra1.computer-aggiorna': 'Esta versão não consegue ouvir o áudio do computador: atualize o Lode.',
  'barra1.preparo-voce': 'Preparando a voz…',
  'barra1.trascrivo-file': 'Transcrevendo «{file}» na aula de {corso}.',
  'barra1.puoi-chiudere': 'Pode fechar o painel: eu aviso no fim.',
  'barra1.sintesi-registrazione': 'gravação sendo transcrita',
  'barra1.ascolto-computer': 'Ouvindo o áudio do computador para {corso}.',
  'barra1.ascolto-computer-nota': 'Comece a videoaula: as linhas chegam na nota a cada 20-30 segundos. Quando terminar, escreva «fim da aula».',
  'barra1.apri-in-obsidian': 'Abrir no Obsidian',
  'barra1.sintesi-videolezione': 'videoaula sendo transcrita',
  'barra1.avviso-videolezione': 'Ouvindo a videoaula',
  'barra1.trascrivo-sparsi': 'Transcrevendo nas anotações soltas.',
  'barra1.trascrivo-lezione-di': 'Transcrevendo a aula de {corso}.',
  'barra1.righe-ogni': 'As linhas chegam na nota a cada 20-30 segundos.',
  'barra1.sintesi-trascrizione-avviata': 'transcrição iniciada',
  'barra1.avviso-trascrivo': 'Transcrevendo a aula',
  'barra1.errore-trascrivere': 'Não consigo transcrever: {errore}',
  'barra1.non-sto-trascrivendo': 'Não estou transcrevendo nada.',
  'barra1.ultimi-secondi': 'Transcrevendo os últimos segundos…',
  'barra1.lezione-trascritta': 'Aula transcrita: {parole} palavras.',
  'barra1.righe-sospese': { one: '{n} linha ainda não está na nota (a pasta não responde): escrevo assim que puder, me deixe aberto.', other: '{n} linhas ainda não estão na nota (a pasta não responde): escrevo assim que puder, me deixe aberto.' },
  'barra1.tutto-nella-nota': 'Está tudo na nota.',
  'barra1.riordina': 'Organizar',
  'barra1.detto-riordina': 'Organizar a aula',
  'barra1.condividi': 'Compartilhar',
  'barra1.detto-condividi': 'Compartilhar a transcrição',
  'barra1.sintesi-parole-trascritte': { one: '{n} palavra transcrita', other: '{n} palavras transcritas' },
  'barra1.con-cervello-locale': 'Com o **cérebro local** (em «Preparar o Lode»), a transcrição vira anotações organizadas, definições e ★ com um clique.',
  // organizar a aula com a IA
  'barra1.non-trovo-trascrizione-di': 'Não encontro uma transcrição de **{corso}**.',
  'barra1.non-trovo-trascrizione': 'Não encontro uma aula transcrita. Na aula, aperte **Transcrever a aula**.',
  'barra1.riordinare-serve-ai': 'Para organizar, precisa da IA: instale o **cérebro local** em «Preparar o Lode» (grátis, offline) ou conecte a sua IA: escreva «IA».',
  'barra1.riordino': 'Organizando {corso}…',
  'barra1.riordino-per-cento': 'Organizando {corso}… {n}%',
  'barra1.errore-riordinare': 'Não consegui organizar: {errore}',
  'barra1.salvare-riordinati': 'Salvar as anotações organizadas de {corso}?',
  'barra1.riordinati-nota': 'Elas vão para a nota, em «Appunti riordinati da Lode», embaixo da transcrição (que continua lá). Quem escreveu foi {motore}: releia.',
  'barra1.appunti-salvati': 'Anotações salvas na nota.',
  'barra1.sintesi-lezione-riordinata': 'aula organizada',
  'barra1.detto-definizioni-lezione': 'Definições da aula',
  // «Repete» e a permissão para ouvir a aula
  'barra1.ascoltare-lezione': 'Ouvir a aula?',
  'barra1.consenso-ripeti': 'guardo na memória só o último minuto e meio, nunca no disco',
  'barra1.trascrivi': 'Transcrever',
  'barra1.consenso-trascrivi': 'escrevo a aula na nota, o áudio não é salvo',
  'barra1.dove': 'Onde',
  'barra1.consenso-dove': 'tudo no computador, nada na internet',
  'barra1.consenso-nota': 'Gravar uma aula depende do regulamento da sua universidade e do professor: pergunte antes.',
  'barra1.solo-la-prima-volta': 'Só pergunto na primeira vez.',
  'barra1.d-accordo': 'Combinado.',
  'barra1.ripeti-app': 'O «Repete» está no **app para desktop** do Lode.',
  'barra1.ripeti-e-attivo': 'O Repete está ativo.',
  'barra1.ripeti-attivo-nota': 'Guardo na memória o último minuto e meio, nunca no disco. Perdeu alguma coisa? {tasti} ou «repete».',
  'barra1.ripeti-attivo-nota-fuori': 'Guardo na memória o último minuto e meio, nunca no disco. Perdeu alguma coisa? {tasti} ou «repete». Fora do horário de aula fico ligado no máximo 3 horas.',
  'barra1.detto-spegni-ripeti': 'Desligar o Repete',
  'barra1.sintesi-ripeti-attivo': 'repete ativo',
  'barra1.ripeti-spento': 'Repete desligado.',
  'barra1.microfono-resta': 'O microfone continua ligado para a transcrição, até você encerrar.',
  'barra1.microfono-chiuso': 'O microfone está desligado.',
  'barra1.non-si-accende-piu': ' Na aula ele não liga mais sozinho: ligue de novo com {tasti}.',
  'barra1.ripeti-e-spento': 'O Repete está desligado.',
  'barra1.ripeti-e-spento-nota': 'O Repete escreve o que o professor disse nos últimos 60 segundos: ligue aqui ou com {tasti}. Se você queria outra coisa, me peça com suas palavras.',
  'barra1.accendi': 'Ligar',
  'barra1.detto-accendi-ripeti': 'Ligar o Repete',
  'barra1.sintesi-ripeti-spento': 'repete desligado',
  'barra1.ascolto-da-un-attimo': 'Comecei a ouvir agora: ainda não tenho nada para repetir.',
  'barra1.riascolto': { one: 'Ouvindo de novo o último {n} segundo…', other: 'Ouvindo de novo os últimos {n} segundos…' },
  'barra1.errore-riascoltare': 'Não consegui ouvir de novo: {errore}',
  'barra1.niente-sentito': 'Nos últimos 60 segundos não ouvi ninguém falar.',
  'barra1.ultimi-secondi-ora': { one: 'O último {n} segundo · {ora}', other: 'Os últimos {n} segundos · {ora}' },
  'barra1.agli-appunti': 'Para as anotações',
  'barra1.copia': 'Copiar',
  'barra1.copiato': 'Copiado',
  'barra1.negli-appunti-di': 'Nas anotações de {corso}.',
  // compartilhar a transcrição
  'barra1.sbobine-app': 'As transcrições são compartilhadas pelo **app para desktop**.',
  'barra1.non-trovo-lezione-di': 'Não encontro uma aula de **{corso}** para compartilhar.',
  'barra1.non-trovo-lezione': 'Não encontro uma aula para compartilhar: primeiro transcreva ou organize.',
  'barra1.preparo-sbobina': 'Preparando a transcrição…',
  'barra1.sbobina-pronta': 'Transcrição de {corso} pronta.',
  'barra1.scegli-dove': 'Escolha para onde mandar: AirDrop, Mensagens, Mail…',
  'barra1.nella-cartella-sbobine': 'Está na pasta «Sbobine» do vault.',
  'barra1.mostra': 'Mostrar',
  'barra1.sintesi-sbobina-condivisa': 'transcrição compartilhada',
  'barra1.errore-sbobina': 'Não consigo preparar a transcrição: {errore}',
  // os cartões para o Anki
  'barra1.anki-non-trovo-di': 'Não encontro cartões nem definições de **{corso}** para exportar.',
  'barra1.anki-non-trovo': 'Ainda não tenho cartões nem definições para exportar: marque algumas definições na aula («def: gradiente = …») ou crie cartões a partir de um PDF.',
  'barra1.anki-carte-mazzi': { one: '{n} cartão para o Anki, {mazzi} baralhos.', other: '{n} cartões para o Anki, {mazzi} baralhos.' },
  'barra1.anki-carte-mazzo': { one: '{n} cartão para o Anki no baralho {mazzo}.', other: '{n} cartões para o Anki no baralho {mazzo}.' },
  'barra1.anki-doppioni': { one: ' {n} repetido ignorado.', other: ' {n} repetidos ignorados.' },
  'barra1.anki-importa-download': 'No Anki: Arquivo › Importar, escolha «{file}» (está nos downloads) e como tipo de nota «Básico» («Basic» em inglês).',
  'barra1.anki-importa-vault': 'No Anki: Arquivo › Importar, escolha «{file}» no vault e como tipo de nota «Básico» («Basic» em inglês).',
  'barra1.scarica': 'Baixar',
  'barra1.sintesi-anki': 'cartões para o Anki',
  'barra1.errore-mostrare': 'Não consigo mostrar o arquivo: {errore}',
  'barra1.errore-anki': 'Não consigo salvar o arquivo para o Anki: {errore}',
  // os arquivos soltos na pílula
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'slides do PowerPoint',
  'barra1.tipo-word': 'documento do Word',
  'barra1.tipo-testo': 'texto',
  'barra1.tipo-sbobina': 'transcrição do Lode',
  'barra1.tipo-carte': 'cartões (Anki/CSV)',
  'barra1.tipo-foto': 'foto',
  'barra1.tipo-audio': 'gravação de áudio',
  'barra1.tipo-altro': 'arquivo',
  'barra1.uno-alla-volta': { one: 'Um de cada vez: começo por **{nome}**, depois solte o outro.', other: 'Um de cada vez: começo por **{nome}**, depois solte os outros {n}.' },
  'barra1.errore-leggere-file': 'Não consigo ler o arquivo: {errore}',
  'barra1.serve-ai': 'precisa do cérebro local ou da sua IA',
  'barra1.serve-app': 'no app para desktop',
  'barra1.op-sbobina': 'Adicionar ao meu vault',
  'barra1.op-sbobina-d': 'Vira uma aula no seu Obsidian: definições e ★ entram nos jogos',
  'barra1.op-allega-soltanto': 'Só anexar',
  'barra1.op-allega-soltanto-d': 'Salvo o arquivo nos anexos da aula',
  'barra1.op-importa-carte': 'Importar os cartões',
  'barra1.op-importa-carte-d': 'Um por linha: pergunta, depois Tab, «;» ou « = », depois resposta',
  'barra1.op-audio': 'Transcrever a gravação',
  'barra1.op-audio-d': 'A aula inteira em anotações, fórmulas incluídas, na nota da aula',
  'barra1.op-allega': 'Anexar à aula',
  'barra1.op-allega-audio-d': 'Salvo o áudio nos anexos, com o link na nota',
  'barra1.op-lavagna': 'Transcrever em anotações',
  'barra1.op-lavagna-d': 'Texto e fórmulas em LaTeX, na nota da aula',
  'barra1.op-carte': 'Cartões de revisão',
  'barra1.op-carte-foto-d': 'As perguntas que cairiam na prova',
  'barra1.op-allega-foto-d': 'A foto na nota da aula',
  'barra1.op-carte-d': 'Perguntas e respostas para a revisão espaçada',
  'barra1.op-riassunto': 'Resumo no Obsidian',
  'barra1.op-riassunto-d': 'Anotações organizadas com fórmulas, numa nota nova',
  'barra1.op-definizioni': 'Definições para os jogos',
  'barra1.op-definizioni-d': 'Adiciono à aula: viram jogos de memória',
  'barra1.op-orale': 'Me testa sobre isso',
  'barra1.op-orale-d': 'Um professor de prova oral com perguntas sobre este material',
  'barra1.op-allega-d': 'Salvo o arquivo com o link na nota',
  'barra1.op-crocette': 'Quiz de múltipla escolha',
  'barra1.op-crocette-d': 'Perguntas com 4 respostas, como na prova escrita: treino ou simulação de prova',
  'barra1.op-temi': 'Provas antigas',
  'barra1.op-temi-d': 'Os exercícios de uma prova antiga, separados por tópico, um por dia no plano',
  'barra1.op-programma': 'É a ementa da prova',
  'barra1.op-programma-d': 'Divido em tópicos e preparo o plano até a prova',
  'barra1.op-domande': 'Perguntas que caíram nas provas',
  'barra1.op-domande-d': 'Coloco embaixo dos tópicos delas: os que mais caem sobem no plano',
};
