// Textos da barra, terceira parte (português do Brasil): revisão de bolso, Moodle, quiz de múltipla escolha, provas
// antigas, simulado, ementa da prova, «deixa eu explicar», envio, arquivos, voz, atalhos e avisos do app (js/lode.js).
export default {
  // Revisão de bolso
  'barra3.tasca-solo-app': 'A revisão de bolso fica no app: precisa do vault do Obsidian.',
  'barra3.tasca-spenta': 'Revisão de bolso só quando você pedir.',
  'barra3.tasca-spenta-nota': 'A nota {nota} fica no vault: escreva «revisão de bolso» para atualizar.',
  'barra3.tasca-spenta-sintesi': 'revisão de bolso desligada',
  'barra3.tasca-preparo': 'Preparando a nota…',
  'barra3.tasca-errore': 'Não consigo ler ou escrever a nota {nota}: {errore}',
  'barra3.tasca-estranea': 'No vault já existe uma nota **{nota}** que não foi o Lode que escreveu: não vou mexer. Renomeie e tente de novo.',
  'barra3.tasca-segnata-sapevi': 'Registrei o cartão que você fez no celular: você sabia.',
  'barra3.tasca-segnata-non-sapevi': 'Registrei o cartão que você fez no celular: você não sabia.',
  'barra3.tasca-segnate': 'Registrei {n} cartões que você fez no celular: {sapevo} você sabia, {no} não.',
  'barra3.tasca-gia': { one: 'Um cartão você já tinha revisado no computador: não registro duas vezes.', other: '{n} cartões você já tinha revisado no computador: não registro duas vezes.' },
  'barra3.tasca-vecchia': 'A nota no celular é de uma rodada antiga: não registro nada.',
  'barra3.tasca-cambiata': 'A nota ainda está mudando: o Obsidian está sincronizando. Não reescrevo agora, tente de novo daqui a um minuto.',
  'barra3.tasca-domani': { one: 'Na nota {nota} tem {n} cartão para amanhã.', other: 'Na nota {nota} tem {n} cartões para amanhã.' },
  'barra3.tasca-domani-niente': 'Amanhã você não tem cartões para revisar: a nota {nota} avisa.',
  'barra3.tasca-titolo': 'Revisão de bolso',
  'barra3.tasca-aspetta': 'Espere o celular terminar de sincronizar e tente de novo. Se a nota certa não chegar, reescreva: as marcações daquela cópia eu não registro.',
  'barra3.apri-nota': 'Abrir a nota',
  'barra3.riscrivi-nota': 'Reescrever a nota',
  'barra3.tasca-solo-quando': 'Só quando eu pedir',
  'barra3.tasca-ogni-sera': 'Toda noite',
  'barra3.tasca-sera-accesa': 'Toda noite depois das 19h eu reescrevo sozinho, se o Lode estiver aberto.',
  'barra3.tasca-sera-spenta': 'Só reescrevo quando você pedir.',
  'barra3.tasca-come-arriva': 'Funciona se o vault chega no celular (iCloud, Obsidian Sync, Syncthing). O Lode não usa a internet: quem leva a nota é o serviço que você já usa.',
  'barra3.non-apro-nota': 'Não consigo abrir a nota: {errore}',
  'barra3.tasca-riscrivi-detto': 'Reescrever a nota {nota}',
  'barra3.tasca-sintesi': 'revisão de bolso',

  // Moodle
  'barra3.moodle-solo-app': 'A conexão com o Moodle está no **app para desktop** do Lode.',
  'barra3.moodle-non-risponde': 'O Moodle não responde: {errore}',
  'barra3.moodle-non-collegato': 'O Moodle não está conectado.',
  'barra3.moodle-scollegato': 'Moodle desconectado.',
  'barra3.moodle-scollegato-nota': 'O token foi apagado deste computador. Os arquivos já baixados ficam no seu vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} disciplina seguida: {corsi}', other: '{n} disciplinas seguidas: {corsi}' },
  'barra3.file-nuovi': 'Arquivos novos',
  'barra3.scadenze': 'Prazos',
  'barra3.corsi': 'Disciplinas',
  'barra3.scollega': 'Desconectar',
  'barra3.moodle-senza-portachiavi': 'Este computador não tem um chaveiro: a conexão vale até você fechar o Lode.',
  'barra3.moodle-novita-detto': 'Novidades do Moodle',
  'barra3.moodle-corsi-detto': 'Disciplinas do Moodle',
  'barra3.moodle-scollega-detto': 'Desconectar o Moodle',
  'barra3.moodle-collega': 'Conectar o Moodle',
  'barra3.moodle-collega-intro': 'A plataforma das disciplinas da sua universidade (Moodle, AVA, e-learning…): o Lode pega os arquivos novos e os prazos das disciplinas que você escolher. Só leitura: não entrega nada e não escreve nada.',
  'barra3.moodle-indirizzo-esempio': 'Endereço, por exemplo moodle.suauniversidade.br',
  'barra3.moodle-indirizzo': 'Endereço do Moodle',
  'barra3.continua': 'Continuar',
  'barra3.moodle-collega-nota': 'Você entra como no app oficial do Moodle. A conexão fica criptografada neste computador, nunca no vault; com «desconecta o moodle» você tira.',
  'barra3.moodle-cerco': 'Procurando o site…',
  'barra3.moodle-non-indirizzo': 'Isso não parece um endereço.',
  'barra3.moodle-non-trovo': 'Não encontro um Moodle com o app ativado neste endereço ({motivo}). Copie o endereço da barra do navegador quando estiver na página das suas disciplinas.',
  'barra3.moodle-accesso-annullato': 'Acesso cancelado.',
  'barra3.moodle-accesso-fallito': 'Não deu para entrar: {motivo}.',
  'barra3.moodle-entra-sso': '<b>{nome}</b> · o acesso é com o login da universidade (login institucional), numa janela do Lode.',
  'barra3.accedi': 'Entrar',
  'barra3.moodle-accedi-finestra': 'Entre na janela que abriu…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · acesso com usuário e senha do Moodle.',
  'barra3.utente': 'Usuário',
  'barra3.password': 'Senha',
  'barra3.moodle-password-nota': 'A senha vai só para o Moodle: o Lode não salva.',
  'barra3.moodle-collega-sintesi': 'conectar o Moodle',
  'barra3.moodle-leggo-corsi': 'Lendo suas disciplinas…',
  'barra3.moodle-corsi-errore': 'Não consigo ler as disciplinas: {errore}',
  'barra3.moodle-nessun-corso': 'No Moodle você não aparece inscrito em nenhuma disciplina.',
  'barra3.moodle-corsi-titolo': 'Disciplinas do Moodle · {sito}',
  'barra3.moodle-scegli-corsi': 'Escolha quais seguir e com qual disciplina do Lode: os arquivos novos delas chegam aqui.',
  'barra3.concluso': 'encerrada',
  'barra3.moodle-corso-per': 'Disciplina do Lode para {nome}',
  'barra3.non-seguire': 'Não seguir',
  'barra3.moodle-con-nome': 'Com o nome do Moodle',
  'barra3.salva': 'Salvar',
  'barra3.moodle-seguo': { one: 'Sigo {n} disciplina no Moodle.', other: 'Sigo {n} disciplinas no Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Nenhuma disciplina seguida.',
  'barra3.moodle-ti-avviso': 'Eu aviso quando chegarem arquivos novos.',
  'barra3.moodle-corsi-sintesi': 'disciplinas do Moodle',
  'barra3.moodle-guardo': 'Olhando os arquivos no Moodle…',
  'barra3.moodle-non-leggo': 'Não consigo ler {corsi}: {errore}.',
  'barra3.moodle-nessun-file': 'Nas disciplinas que você segue ainda não há arquivos.',
  'barra3.moodle-piu-recenti': 'os arquivos mais recentes',
  'barra3.moodle-file-nuovi': { one: '{n} arquivo novo', other: '{n} arquivos novos' },
  'barra3.moodle-niente-nuovo': 'nada de novo, os últimos arquivos',
  'barra3.nuovo': 'novo',
  'barra3.apri': 'Abrir',
  'barra3.moodle-apri-nota': '«Abrir» leva o arquivo para o Lode como se você tivesse arrastado: cartões, resumo, ementa, quiz.',
  'barra3.scarico': 'Baixando…',
  'barra3.non-riesco': 'Não consigo',
  'barra3.aperto': 'Aberto',
  'barra3.moodle-file-da': '{nome} do Moodle',
  'barra3.file-illeggibile': 'Não consigo ler o arquivo: {errore}',
  'barra3.moodle-sintesi-nuovi': 'Moodle: {n} arquivos novos',
  'barra3.moodle-nessuna-scadenza': 'Nenhum prazo no Moodle nas próximas semanas.',
  'barra3.moodle-scadenze-titolo': 'Prazos no Moodle',
  'barra3.scadenze-sintesi': '{n} prazos',
  'barra3.guarda': 'Ver',

  // quiz de múltipla escolha
  'barra3.non-trovo-esame': 'Não encontro a prova **{nome}**.',
  'barra3.il-tuo-materiale': 'o seu material',
  'barra3.quiz-poco-materiale': 'Para um quiz sobre **{nome}** preciso de mais material: arraste a apostila ou os slides (escolha «Quiz de múltipla escolha»), ou crie alguns cartões.',
  'barra3.quiz-senza-ai': 'Para o quiz sem IA preciso de pelo menos 4 cartões ou 4 definições de **{nome}**. Com a IA (escreva «IA») faço até a partir da apostila.',
  'barra3.quiz-fonte-dispensa-nome': 'Perguntas da apostila «{nome}».',
  'barra3.quiz-fonte-dispensa': 'Perguntas da apostila.',
  'barra3.quiz-fonte-ai': 'Perguntas dos seus cartões, definições e perguntas que caíram.',
  'barra3.quiz-fonte-carte-definizioni': 'Perguntas dos seus cartões e definições.',
  'barra3.quiz-fonte-carte': 'Perguntas dos seus cartões.',
  'barra3.quiz-fonte-definizioni': 'Perguntas das suas definições.',
  'barra3.quiz-le-scrive': 'Quem escreve é {motore}: fico só com as que o material comprova.',
  'barra3.quiz-sbagliate-altre': 'As respostas erradas são as de outros cartões da disciplina.',
  'barra3.quiz-titolo': 'Quiz de múltipla escolha · {nome}',
  'barra3.quiz-allenamento': 'Treino · {n} perguntas',
  'barra3.quiz-allenamento-sotto': 'A correção na hora, com a explicação',
  'barra3.quiz-simulazione': 'Simulação de prova · {n} perguntas em {n} minutos',
  'barra3.quiz-simulazione-sotto': 'Como na prova escrita: o tempo corre, a correção no fim, a nota de 0 a 30',
  'barra3.quiz-simulazione-detto': 'Simulação de prova · {nome}',
  'barra3.quiz-detto': 'Quiz · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulação · {nome}',
  'barra3.quiz-preparo': 'Preparando as perguntas… {fatte} de {n}',
  'barra3.quiz-errore': 'Não consigo preparar as perguntas: {errore}',
  'barra3.quiz-niente': 'Não consegui preparar perguntas confiáveis com este material.',
  'barra3.quiz-sintesi': 'quiz de {nome}',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} de {n}',
  'barra3.x-di-n': '{x} de {n}',
  'barra3.quiz-domanda-n': 'Pergunta {x} de {n}',
  'barra3.indietro': 'Voltar',
  'barra3.salta': 'Pular',
  'barra3.lascia-vuota': 'Deixar em branco',
  'barra3.consegna': 'Entregar',
  'barra3.quiz-giusta-e': 'A resposta certa é a {lettera}.',
  'barra3.avanti': 'Avançar',
  'barra3.risultato': 'Resultado',
  'barra3.tasto-invio': 'Enter',
  'barra3.quiz-voto': 'Nota: <em>{voto}</em>',
  'barra3.tempo-scaduto': 'tempo esgotado',
  'barra3.quiz-tutte-giuste': 'Todas certas.',
  'barra3.quiz-da-rivedere': { one: '{n} para rever.', other: '{n} para rever.' },
  'barra3.quiz-scartate': { one: '{n} pergunta descartada porque o material não comprovava', other: '{n} perguntas descartadas porque o material não comprovava' },
  'barra3.da-rivedere': 'Para rever',
  'barra3.lasciata-vuota': 'Deixada em branco',
  'barra3.hai-scelto': 'Você escolheu: {x}',
  'barra3.giusta-era': 'Certa: {x}',
  'barra3.quiz-sbagliate-carte': 'As erradas viram cartões',
  'barra3.quiz-un-altro': 'Outro quiz',
  'barra3.quiz-punti': 'Uma resposta certa vale 1 ponto, errada ou em branco 0.',
  'barra3.quiz-regole-vere': 'A prova escrita de verdade pode ter regras diferentes (desconto pelas erradas, nota mínima): é um treino.',
  'barra3.quiz-carte-aggiunte': { one: '{n} cartão adicionado: volta hoje na revisão', other: '{n} cartões adicionados: voltam hoje na revisão' },
  'barra3.quiz-sintesi-esito': 'quiz de {nome}: {giuste} de {n}',

  // provas antigas
  'barra3.tema-del': 'de {data}',
  'barra3.tema-di': 'de «{fonte}»',
  'barra3.tema-es': 'ex. {es}',
  'barra3.tema-es-da': 'ex. {es} {da}',
  'barra3.tema-circa': 'cerca de {min} min no papel',
  'barra3.leggo-file': 'Lendo {nome}…',
  'barra3.cmd-temi-di': '«provas antigas de {nome}:»',
  'barra3.cmd-temi': '«provas antigas:»',
  'barra3.temi-scansione': 'Este PDF parece uma digitalização: sem IA eu não leio imagens. Cole o texto dos exercícios com {cmd} e o texto embaixo.',
  'barra3.temi-illeggibile': 'Não consigo ler o texto deste arquivo. Cole com {cmd} e o texto embaixo.',
  'barra3.aggiungi-prima-esame': 'Primeiro adicione a prova, por exemplo: «prova de cálculo 2 dia 15 de janeiro 4 créditos».',
  'barra3.non-trovo-esame-aggiungi': 'Não encontro a prova **{nome}**. Adicione antes, por exemplo: «prova de {nome} dia 15 de janeiro 4 créditos».',
  'barra3.aggiungi-esame-compito': 'Primeiro adicione uma prova, por exemplo: «prova de cálculo 2 dia 15 de janeiro 4 créditos». Depois cole uma prova antiga.',
  'barra3.prova-invito': 'Quer fazer uma prova inteira, com o tempo de verdade?',
  'barra3.prova-generale': 'Simulado',
  'barra3.prova-generale-di': 'Simulado de {nome}',
  'barra3.temi-titolo': 'Provas antigas · {nome}',
  'barra3.temi-nessuno-oggi': 'Nenhum exercício para hoje.',
  'barra3.temi-prossimo': 'O próximo volta {data}.',
  'barra3.temi-vuoto': 'Cole o texto de uma prova antiga (as que circulam no grupo da turma ou no site do professor), ou arraste o PDF. Eu divido em exercícios, coloco embaixo dos tópicos deles e todo dia sugiro um.',
  'barra3.temi-segnaposto': 'Problema 1. Calcule…&#10;Problema 2. Estude…',
  'barra3.temi-testo-compito': 'Texto da prova',
  'barra3.temi-dividi': 'Dividir em exercícios',
  'barra3.temi-di': 'Provas antigas de {nome}',
  'barra3.temi-di-sintesi': 'provas antigas de {nome}',
  'barra3.temi-nessun-esercizio': 'Não encontrei exercícios neste texto.',
  'barra3.temi-compito-del': 'prova {data}',
  'barra3.temi-un-pezzo': 'Não encontrei «Problema 1», «Problema 2»… Se a prova tem vários exercícios, escreva com essas marcas e cole de novo.',
  'barra3.temi-senza-programma': 'Para {nome} ainda não tem ementa: salvo sem tópico.',
  'barra3.temi-metti': 'Colocar no plano',
  'barra3.temi-es': 'Ex. {n}',
  'barra3.temi-con-soluzione': 'com a resolução do professor',
  'barra3.temi-argomento-di': 'Tópico do exercício {n}',
  'barra3.temi-che-argomento': 'Que tópico é?',
  'barra3.temi-unisci': 'Juntar ao anterior',
  'barra3.togli': 'Tirar',
  'barra3.temi-nel-piano': { one: '{n} exercício no plano.', other: '{n} exercícios no plano.' },
  'barra3.temi-nel-piano-arg': { one: '{n} exercício no plano: {con} com o tópico, {senza} sem.', other: '{n} exercícios no plano: {con} com o tópico, {senza} sem.' },
  'barra3.temi-senza-programma-nota': 'Sem ementa eu não sei onde colocar: cole a ementa de {nome} e eu organizo.',
  'barra3.temi-doppi': { one: '{n} já estava lá.', other: '{n} já estavam lá.' },
  'barra3.temi-ogni-giorno': 'Todo dia um sobre os tópicos do plano.',
  'barra3.programma': 'Ementa',
  'barra3.fanne-uno': 'Fazer um',
  'barra3.esercizio-di': 'Exercício de {nome}',
  'barra3.temi-gia': 'Esses exercícios já estavam lá.',
  'barra3.temi-sintesi-n': { one: 'provas antigas de {nome}: {n} exercício', other: 'provas antigas de {nome}: {n} exercícios' },
  'barra3.tema-titolo': 'Exercício · {nome}',
  'barra3.tema-fallo': 'Faça no papel, sem olhar as anotações. Quando terminar:',
  'barra3.giusto': 'Certo',
  'barra3.sbagliato': 'Errado',
  'barra3.non-sapevo': 'Não sabia por onde começar',
  'barra3.tema-voto-tuo': 'Quem dá a nota é você: o Lode não corrige o exercício.',
  'barra3.tema-torna': { one: 'Volta daqui a {n} dia.', other: 'Volta daqui a {n} dias.' },
  'barra3.tema-guarda-soluzione': 'Olhe a resolução e refaça do zero, não só releia.',
  'barra3.tema-rileggi': 'Releia o tópico e refaça do zero, sem olhar.',
  'barra3.tema-prima-rileggi-arg': 'Primeiro releia o tópico: {arg}.',
  'barra3.tema-prima-rileggi': 'Primeiro releia o tópico.',
  'barra3.tema-vedi-soluzione': 'Ver a resolução do professor',
  'barra3.tema-altro': 'Outro exercício',
  'barra3.esercizio-di-esito': 'exercício de {nome}: {esito}',
  'barra3.esercizio-di-sintesi': 'exercício de {nome}',

  // simulado
  'barra3.prova-prima-compiti': 'Primeiro cole ou arraste as provas antigas: «provas antigas de {nome}: …».',
  'barra3.prova-compito-del': 'Prova de {data}',
  'barra3.prova-scelti': 'Exercícios escolhidos por você',
  'barra3.prova-compito-fonte': 'Prova «{fonte}»',
  'barra3.prova-compito-incollato': 'Prova colada',
  'barra3.n-esercizi': { one: '{n} exercício', other: '{n} exercícios' },
  'barra3.n-punti': '{punti} pontos',
  'barra3.prova-titolo': 'Simulado · {nome}',
  'barra3.prova-quanto-dura': 'Quanto tempo dura?',
  'barra3.prova-minuti-aria': 'Quantos minutos dura a prova',
  'barra3.minuti': 'minutos',
  'barra3.prova-altro-compito': 'Outra prova',
  'barra3.prova-gia-fatto': 'já feita em {data}',
  'barra3.comincio': 'Começar',
  'barra3.prova-su-carta': 'No papel, sem anotações, como na prova. As resoluções você vê no fim.',
  'barra3.prova-durata-letta': 'Li isso na prova.',
  'barra3.prova-di-solito': 'Normalmente 2 horas.',
  'barra3.prova-sintesi': 'simulado de {nome}',
  'barra3.prova-scegli': 'Não encontro uma prova inteira: escolha você os exercícios.',
  'barra3.prova-scegli-nota': '120 minutos, no papel, sem anotações. As resoluções você vê no fim.',
  'barra3.prova-ferma-pausa': 'Tem uma pausa rolando: paro ela e começo o simulado?',
  'barra3.prova-ferma-focus': 'Tem um foco ligado: paro ele e começo o simulado?',
  'barra3.si-parti': 'Sim, começa',
  'barra3.no': 'Não',
  'barra3.prova-durata-fino': '{min} minutos, até as {ora}',
  'barra3.esercizio-n': 'Exercício {n}',
  'barra3.prova-passo': 'Passar para o próximo',
  'barra3.consegno': 'Entregar',
  'barra3.lascio-perdere': 'Desistir',
  'barra3.prova-nota-tempo': 'O tempo corre na pílula. «Passar para o próximo» é opcional: marca quanto tempo você fica em cada exercício.',
  'barra3.prova-lascio-chiede': 'Desistir? Não registro nada: nem os exercícios nem a prova.',
  'barra3.si-lascio': 'Sim, desistir',
  'barra3.no-continuo': 'Não, continuar',
  'barra3.prova-lasciata': 'Você desistiu: não registrei nada. Quando quiser refazer, escreva «simulado de {nome}».',
  'barra3.prova-consegnato': 'Entregue. Pegue a folha e, para cada exercício, me diga como foi.',
  'barra3.prova-come-andato': 'Como foi o exercício {n}',
  'barra3.prova-esito-tuo': 'O Lode não corrige: o resultado quem escolhe é você.',
  'barra3.prova-sintesi-esito': 'simulado de {nome}: {fatti} de {n}',
  'barra3.prova-sintesi-come': 'simulado de {nome}: como foi',

  // ementa da prova
  'barra3.aggiungi-esame-programma': 'Primeiro adicione uma prova, por exemplo: «prova de cálculo 2 dia 15 de janeiro 4 créditos». Depois cole a ementa dela.',
  'barra3.programma-titolo': 'Ementa · {nome}',
  'barra3.programma-vuoto': 'Cole a ementa da disciplina (da página da disciplina ou do PDF), ou arraste o arquivo para cá. Eu divido em tópicos, mostro o que você já sabe e preparo o plano até a prova.',
  'barra3.programma-segnaposto': '1. Limites e continuidade&#10;2. Derivadas: definição, regras, teoremas de Rolle e do valor médio&#10;…',
  'barra3.programma-del-corso': 'Ementa da disciplina',
  'barra3.programma-leggi': 'Ler a ementa',
  'barra3.programma-di': 'Ementa de {nome}',
  'barra3.programma-da-moodle': 'Pegar do Moodle',
  'barra3.programma-moodle-vuota': 'No Moodle a descrição está vazia',
  'barra3.programma-di-moodle': 'Ementa de {nome} do Moodle',
  'barra3.programma-sintesi': 'ementa de {nome}',
  'barra3.programma-leggo': 'Lendo a ementa…',
  'barra3.programma-niente': 'Não consigo tirar os tópicos deste texto. Cole um por linha, de preferência numerados.',
  'barra3.programma-salvo': { one: '{n} tópico para {nome}: salvo?', other: '{n} tópicos para {nome}: salvo?' },
  'barra3.programma-letti-da': 'Quem leu foi {motore}: confira se estão todos.',
  'barra3.programma-se-non-torna': 'Se algo não bater, cole de novo a ementa corrigida.',
  'barra3.programma-stesso-nome': 'Os tópicos com o mesmo nome mantêm perguntas e resultados.',
  'barra3.programma-cuscinetto': 'Hoje é o dia de folga: recupere o que ficou para trás, ou descanse.',
  'barra3.programma-ultimo': 'Último dia: revisão geral. As perguntas que caíram e os pontos fracos: {cosa}.',
  'barra3.tutto-il-programma': 'toda a ementa',
  'barra3.studia': 'Estudar',
  'barra3.ripassa': 'Revisar',
  'barra3.cuscinetto': 'folga',
  'barra3.ripasso-generale': 'revisão geral',
  'barra3.percento-pronto': '{p}% pronto',
  'barra3.oggi': 'Hoje',
  'barra3.esercizio-di-oggi': 'Exercício de hoje',
  'barra3.fallo-adesso': 'Fazer agora',
  'barra3.interrogami-questi': 'Me testa nesses',
  'barra3.focus': 'Foco',
  'barra3.da-rivedere-piccolo': 'para rever',
  'barra3.uscita-volte': { one: 'caiu {n} vez', other: 'caiu {n} vezes' },
  'barra3.fatto-oggi': 'feito hoje',
  'barra3.lo-spiego-io': 'Deixa eu explicar',
  'barra3.interrogami': 'Me testa',
  'barra3.prossimi-giorni': 'Os próximos dias',
  'barra3.senza-data-appello': '(sem data da prova: plano de duas semanas)',
  'barra3.domande-appelli': 'Perguntas que caíram nas provas',
  'barra3.n-senza-argomento': { one: '{n} sem tópico', other: '{n} sem tópico' },
  'barra3.domande-segnaposto': 'Uma por linha: as que circulam no grupo da turma',
  'barra3.domande-uscite': 'Perguntas que caíram',
  'barra3.aggiungi': 'Adicionar',
  'barra3.domande-senza-argomento': 'Não sei de que tópico são: {lista}',
  'barra3.programma-nota': 'O plano é refeito todo dia a partir do que você sabe: anotações, cartões, revisão e testes. Primeiro os tópicos fracos e os que mais caem; cada tópico novo volta depois de alguns dias.',
  'barra3.interrogami-oggi': 'Me testa nos tópicos de hoje',
  'barra3.interrogami-su': 'Me testa sobre {x}',
  'barra3.te-lo-spiego-su': 'Deixa eu explicar: {x}',
  'barra3.programma-sintesi-pronto': 'ementa de {nome}: {p}% pronta',
  'barra3.domande-nessuna': 'Não encontrei perguntas: escreva uma por linha.',
  'barra3.domande-salvate': { one: '{n} pergunta salva.', other: '{n} perguntas salvas.' },
  'barra3.domande-incolla-programma': 'Cole também a ementa: eu coloco elas embaixo dos tópicos.',
  'barra3.domande-aggiunte': { one: '{n} pergunta adicionada.', other: '{n} perguntas adicionadas.' },
  'barra3.domande-senza': { one: '{n} sem tópico: não entendo de qual ela fala.', other: '{n} sem tópico: não entendo de quais elas falam.' },
  'barra3.domande-salgono': 'Os tópicos que mais caem sobem no plano.',
  'barra3.domande-uscite-sintesi': 'perguntas que caíram',

  // deixa eu explicar e a prova oral sobre a ementa
  'barra3.spiego-titolo': 'Deixa eu explicar · {nome}',
  'barra3.spiego-istruzioni': 'Explique como se estivesse na prova oral, com suas palavras: escreva aqui embaixo ou segure {tasti} e fale. Quando terminar, envie.',
  'barra3.spiego-risponde': 'Quem responde é {motore}, usando suas anotações.',
  'barra3.spiego-controllo': { one: 'Confiro {n} ponto tirado da ementa e das suas anotações: não mostro antes.', other: 'Confiro {n} pontos tirados da ementa e das suas anotações: não mostro antes.' },
  'barra3.spiego-senza-appunti': 'Para este tópico não tenho anotações: sem IA só posso registrar que você revisou.',
  'barra3.spiego-esci': 'Escreva «sair» para deixar pra lá.',
  'barra3.spiego-segnaposto': 'Sua explicação…',
  'barra3.spiego-sintesi': 'explico {x}',
  'barra3.chiedi-o-scrivi': 'Pergunte ou escreva um comando…',
  'barra3.spiego-ascolto': 'Ouvindo a explicação…',
  'barra3.mancava': 'Faltou: {cosa}',
  'barra3.spiego-errore': 'Não consigo avaliar agora: {errore}',
  'barra3.spiego-segnato': 'Registrado: você revisou {x}.',
  'barra3.spiego-controllo-vero': 'Para uma verificação de verdade, precisa de anotações sobre este tópico, ou da IA.',
  'barra3.punti-su': '{x} pontos de {n}',
  'barra3.spiego-parole-chiave': 'Eu confiro as palavras-chave, não o raciocínio: se você disse um ponto com outras palavras, vale do mesmo jeito.',
  'barra3.spiego-sicuro': 'Tópico marcado como seguro.',
  'barra3.spiego-cerchio-vuoto': 'Os com o círculo vazio: releia e tente de novo daqui a uns dois dias.',
  'barra3.orale-niente': 'Hoje não tem nada no plano para testar.',
  'barra3.orale-contesto': 'Prova oral · <b>{nome}</b> · {cosa}',
  'barra3.n-argomenti': { one: '{n} tópico', other: '{n} tópicos' },
  'barra3.esci': 'Sair',
  'barra3.orale-sintesi': 'prova oral de {nome} sobre a ementa',

  // enviar, arquivos, voz
  'barra3.crea-carte-da-file': 'Crie os cartões de revisão a partir deste arquivo.',
  'barra3.niente-spiegazione': 'Tudo bem, sem explicação.',
  'barra3.non-so-senza-ai': 'Isso eu ainda não sei fazer sem IA. Olha o que eu entendo:',
  'barra3.foto': 'foto',
  'barra3.togli-file': 'Tirar {nome}',
  'barra3.allegati-con-ai': 'Enter: faço cartões. Ou peça outra coisa…',
  'barra3.allegati-senza-ai': 'Enter: importo os cartões (CSV, TSV, texto)',
  'barra3.importa-solo-testo': 'Sem IA eu só leio arquivos de texto com um cartão por linha (pergunta, depois Tab ou «;» ou « = », depois resposta), como a exportação do Anki. Para PDF e fotos precisa do cérebro local ou da sua IA (escreva «IA»).',
  'barra3.importa-carte': { one: 'Importar {n} cartão?', other: 'Importar {n} cartões?' },
  'barra3.e-altre': { one: 'e mais {n}', other: 'e mais {n}' },
  'barra3.importa-in': 'Coloco em {nome}: você muda pela página.',
  'barra3.carte-importate': { one: '{n} cartão importado.', other: '{n} cartões importados.' },
  'barra3.ripassa-ora': 'Revisar agora',
  'barra3.ti-ascolto': 'Estou ouvindo',
  'barra3.ti-ascolto-preparo': 'Estou ouvindo · preparando a voz…',
  'barra3.ti-ascolto-preparo-p': 'Estou ouvindo · preparando a voz {p}%',
  'barra3.voce-pronta': '{voce} local · segure {tasti} e fale',
  'barra3.scarico-voce': 'Baixando {voce} · {p}%',
  'barra3.voce-ripiego': 'O Parakeet não inicia: preparando o Whisper',
  'barra3.preparo-voce': 'Preparando a voz',

  // atalhos, links e avisos
  'barra3.piu-tardi': 'Tudo bem, mais tarde',
  'barra3.trascrivi-lezione': 'Transcrever a aula',
  'barra3.fine-trascrizione': 'Encerrar transcrição',
  'barra3.ripeti': 'Repete',
  'barra3.spegni-ripeti': 'Desligar o Repete',
  'barra3.accendi-ripeti': 'Ligar o Repete',
  'barra3.gioca': 'Jogar',
  'barra3.pausa': 'Pausa',
  'barra3.focus-fatto': { one: '{n} minuto feito · pausa', other: '{n} minutos feitos · pausa' },
  'barra3.tempo-scaduto-consegna': 'Tempo esgotado · entregue',
  'barra3.pausa-finita': 'Fim da pausa · bora de novo?',
  'barra3.ripeti-spento': 'Repete desligado depois de 3 horas',
  'barra3.lode-pronta': 'O Lode {versione} está pronto',
  'barra3.lode-uscita': 'Saiu o Lode {versione}',
  'barra3.sync-in-pausa': 'Sincronização em pausa · digite a senha',
  'barra3.cervello-locale': 'Cérebro local',
  'barra3.ripassa-esame': 'Revisar {nome}',
  'barra3.ripasso': 'Revisão',
  'barra3.libretto': 'Histórico',
};
