// Textos das boas-vindas (português do Brasil): os passos obrigatórios (nome, instalações) e a configuração rápida
// (curso, histórico, provas, horário, hábitos), mais a conexão com um Lode que já existe em outro computador.
export default {
  // a moldura
  'benvenuto.tasti-mac': '⌥ Espaço',
  'benvenuto.tasti-altri': 'Ctrl ⇧ Espaço',
  'benvenuto.avanti': 'Avançar',
  'benvenuto.indietro': 'Voltar',
  'benvenuto.salta': 'Pular',
  'benvenuto.obbligatorio': 'Obrigatório',
  'benvenuto.facoltativo': 'Opcional · configuração rápida',
  // oi
  'benvenuto.ciao-titolo': 'Oi.<br>Eu sou o Lode.',
  'benvenuto.ciao-sotto': 'Eu moro numa barrinha no topo da tela. Na aula, não deixo você perder nada; em casa, treino você no que está prestes a esquecer; e guardo tudo no seu Obsidian.',
  'benvenuto.ciao-nota': 'Primeiro três coisas necessárias (dois minutos, mais os downloads). Depois, se quiser, a configuração rápida.',
  'benvenuto.altro-computer': 'Já uso o Lode em outro computador',
  'benvenuto.sperimentale': '(experimental)',
  'benvenuto.iniziamo': 'Vamos começar',
  // outro computador
  'benvenuto.scegli-vault-cloud': 'Escolha o vault do Lode na sua pasta da nuvem (iCloud Drive, OneDrive, Dropbox, Google Drive).',
  'benvenuto.scegli-vault': 'Escolher o vault…',
  'benvenuto.password-dati': 'A senha dos dados do Lode, se você colocou uma',
  'benvenuto.collego': 'Conectando…',
  'benvenuto.cartella-no': 'Não consigo usar essa pasta.',
  'benvenuto.ricevo-dati': 'Recebendo os dados dos outros computadores… O Lode já pode ser usado: eles chegam sozinhos.',
  'benvenuto.inizia': 'Começar',
  'benvenuto.password-sbagliata': 'Senha errada: tente de novo.',
  'benvenuto.password-serve': 'Os dados do Lode estão protegidos por uma senha: digite aqui em cima.',
  // nome
  'benvenuto.nome-titolo': 'Qual é o seu nome?',
  'benvenuto.nome-sotto': 'Só para cumprimentar você. Fica no seu computador.',
  'benvenuto.nome-segnaposto': 'Seu nome',
  'benvenuto.togli-esempio': 'Tirar os dados de exemplo da «Giulia» (provas, notas, cartões e horas de estudo de mentira). O que você adicionou fica.',
  // instalações
  'benvenuto.web-titolo': 'O Lode completo mora no app.',
  'benvenuto.web-sotto': 'No navegador você tem histórico, timer, revisão e jogos. Obsidian, a IA no computador, a voz e a transcrição das aulas ficam no app para desktop.',
  'benvenuto.installa-titolo': 'Vamos preparar seu computador.',
  'benvenuto.installa-sotto': 'Três instalações, uma vez só. Depois o Lode funciona até sem internet, e nada seu sai do computador.',
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'onde moram suas anotações: um vault já pronto',
  'benvenuto.cervello': 'O cérebro local',
  'benvenuto.cervello-cosa': 'Ollama e Qwen3.5: lê as anotações, cria cartões e definições, explica e faz perguntas',
  'benvenuto.voce': 'A voz',
  'benvenuto.voce-cosa': '{voce}: comandos por voz, «Repete» e transcrição das aulas',
  'benvenuto.peso-gb': '{n} GB',
  'benvenuto.peso-mb': '{n} MB',
  'benvenuto.installa-nota': 'O Obsidian é grátis para uso pessoal e vem do site oficial dele. O cérebro local é escolhido de acordo com a memória do computador.',
  'benvenuto.installa-tutto': 'Instalar tudo',
  'benvenuto.gia-installato': 'Já instalado',
  'benvenuto.modello-pronto': '{modello} já está pronto',
  'benvenuto.gia-pronta': 'Já está pronta',
  'benvenuto.voce-pronta': '{voce} está pronto',
  'benvenuto.scarico-voce-pct': 'Baixando a voz · {p}%',
  'benvenuto.tutto-pronto': 'O Obsidian, o cérebro local e a voz estão prontos.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'o cérebro local',
  'benvenuto.scarico-voce': 'a voz',
  'benvenuto.scarico-pct': '{cosa} {p}%',
  'benvenuto.scarico-continua-voce': 'Ainda estou baixando: {cosa}. Eu continuo sozinho, mesmo com a janela fechada; a voz volta na barra assim que você abrir o Lode.',
  'benvenuto.scarico-continua': 'Ainda estou baixando: {cosa}. Eu continuo sozinho, mesmo com a janela fechada.',
  'benvenuto.scarico-solo-voce': 'Ainda estou baixando: {cosa}. A voz volta na barra assim que você abrir o Lode.',
  // configuração rápida
  'benvenuto.veloce-titolo': '{nome}, quer a configuração rápida?',
  'benvenuto.veloce-sotto': 'Me conta da faculdade, das provas e dos horários: a partir de amanhã o Lode sabe quando você está em aula, quanto falta para a formatura e o que revisar antes de cada prova.',
  'benvenuto.veloce-lista': ['Universidade e curso', 'O histórico, colado do portal do aluno ou escrito à mão', 'As provas que faltam, com as datas', 'O horário das aulas, até pelo calendário da universidade (.ics)', 'Como e quando você estuda'],
  'benvenuto.veloce-nota': 'Tudo opcional, tudo editável depois. Nada vai para a internet.',
  'benvenuto.facciamolo': 'Bora',
  // curso
  'benvenuto.corso-titolo': 'Onde você estuda?',
  'benvenuto.ateneo': 'Universidade',
  'benvenuto.ateneo-segnaposto': 'Comece a digitar…',
  'benvenuto.corso': 'Curso',
  'benvenuto.corso-segnaposto': 'Engenharia de Computação',
  'benvenuto.tipo': 'Tipo',
  'benvenuto.tipo-180': 'Graduação de 3 anos · 180 créditos',
  'benvenuto.tipo-120': 'Mestrado · 120 créditos',
  'benvenuto.tipo-300': 'Curso integrado de 5 anos · 300 créditos',
  'benvenuto.tipo-360': 'Curso integrado de 6 anos · 360 créditos',
  'benvenuto.anno': 'Ano',
  'benvenuto.anni': ['1º', '2º', '3º', '4º', '5º', '6º', 'Atrasado'],
  'benvenuto.lode-vale': 'O louvor vale',
  'benvenuto.lode-nota': 'Depende do regulamento: na dúvida, 30',
  // histórico
  'benvenuto.libretto-titolo': 'As provas que você já fez',
  'benvenuto.libretto-sotto': 'Abra o histórico no portal da universidade (Esse3, SIGAA, Júpiter…), selecione tudo, copie e cole aqui. Eu cuido do resto. Ou escreva uma por linha: «Cálculo 1, 4 créditos, 8».',
  'benvenuto.libretto-segnaposto': 'Cole o histórico aqui…',
  'benvenuto.leggi-libretto': 'Ler o histórico',
  'benvenuto.leggo-libretto': 'Lendo o histórico…',
  'benvenuto.leggo': 'Lendo…',
  'benvenuto.esami-trovati': { one: '{n} prova encontrada: confira e confirme.', other: '{n} provas encontradas: confira e confirme.' },
  'benvenuto.esami-non-trovati': 'Não encontrei provas: tente escrever uma por linha.',
  'benvenuto.col-esame': 'Prova',
  'benvenuto.col-cfu': 'Créditos',
  'benvenuto.col-voto': 'Nota',
  'benvenuto.col-data': 'Data',
  'benvenuto.importa': 'Importar',
  'benvenuto.idoneo': 'aprovado',
  'benvenuto.voto-lode': '{voto}L',
  // provas que faltam
  'benvenuto.esame': 'Prova',
  'benvenuto.cfu': 'Créditos',
  'benvenuto.data-appello': 'Data da prova',
  'benvenuto.togli': 'Tirar',
  'benvenuto.esami-titolo': 'As provas que faltam',
  'benvenuto.esami-sotto': 'Com a data da prova, se você souber. A partir dela o Lode calcula quantas horas você precisa por dia e sugere revisões e jogos quando você tiver um tempinho.',
  'benvenuto.altro-esame': '+ Outra prova',
  // horário
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · sala {aula}',
  'benvenuto.nessuna-lezione': 'Nenhuma aula ainda.',
  'benvenuto.orario-titolo': 'O horário das aulas',
  'benvenuto.orario-sotto': 'Assim o Lode sabe quando você está em aula: a barra se prepara para a aula, «Repete» e a transcrição ficam a uma tecla, e em casa ele treina você no que acabou de ouvir.',
  'benvenuto.scrivila': 'Escreva do jeito que você falaria',
  'benvenuto.frase-segnaposto': 'cálculo 2 segunda e quarta 9-11 sala 7',
  'benvenuto.aggiungi': 'Adicionar',
  'benvenuto.importa-ics': 'Importar o calendário (.ics)',
  'benvenuto.incolla-orario': 'Ou cole o horário do site da universidade',
  'benvenuto.orario-segnaposto': 'Cole aqui a tabela do horário…',
  'benvenuto.leggi-orario': 'Ler o horário',
  'benvenuto.frase-aiuto': 'Escreva disciplina, dias e horas: «física segunda 14-16 sala B2».',
  'benvenuto.lezioni-calendario': { one: '{n} aula do calendário.', other: '{n} aulas do calendário.' },
  'benvenuto.calendario-vuoto': 'Não encontrei aulas semanais no calendário.',
  'benvenuto.leggo-orario': 'Lendo o horário…',
  'benvenuto.lezioni-trovate': { one: '{n} aula encontrada.', other: '{n} aulas encontradas.' },
  'benvenuto.lezioni-non-trovate': 'Não encontrei aulas: tente escrever uma de cada vez.',
  // hábitos
  'benvenuto.abitudini-titolo': 'Como você estuda?',
  'benvenuto.abitudini-sotto': 'O Lode sugere revisões, jogos e perguntas rápidas em momentos aleatórios do dia, quando você está no computador. Me diz com que frequência e quando deixar você em paz.',
  'benvenuto.quando-meglio': 'Quando você estuda melhor',
  'benvenuto.mattina': 'Manhã',
  'benvenuto.pomeriggio': 'Tarde',
  'benvenuto.sera': 'Noite',
  'benvenuto.notte': 'Madrugada',
  'benvenuto.proposte': 'Sugestões do Lode',
  'benvenuto.scelta-mai': 'Nunca',
  'benvenuto.scelta-poco': 'Poucas',
  'benvenuto.scelta-normale': 'Normais',
  'benvenuto.scelta-spesso': 'Muitas',
  'benvenuto.proposte-nota': 'Quanto mais perto a prova, mais vezes. Nunca durante aulas, foco ou de madrugada.',
  'benvenuto.silenzio-dalle': 'Silêncio das',
  'benvenuto.silenzio-alle': 'às',
  'benvenuto.focus': 'Foco',
  'benvenuto.minuti': '{n} min',
  'benvenuto.ripeti-in-aula': 'Na aula, o «Repete» liga sozinho (o último minuto e meio, só na memória). Pergunte ao professor se pode gravar.',
  // fim
  'benvenuto.fine-titolo': 'Pronto, {nome}.',
  'benvenuto.fine-sotto': 'Agora o Lode mora no topo da tela. Passe o mouse por cima para abrir, segure <b>{tasti}</b> para falar com ele, arraste um PDF ou uma foto do quadro para cima dele.',
  'benvenuto.fine-esami': '{fatti} provas no histórico, {dare} para fazer',
  'benvenuto.fine-esami-prossimo': '{fatti} provas no histórico, {dare} para fazer · a próxima é {nome}',
  'benvenuto.fine-lezioni': { one: '{n} aula por semana no horário', other: '{n} aulas por semana no horário' },
  'benvenuto.fine-proposte': 'Sugestões: {quante}',
  'benvenuto.quante-mai': 'nunca',
  'benvenuto.quante-poco': 'poucas',
  'benvenuto.quante-normale': 'normais',
  'benvenuto.quante-spesso': 'muitas',
  'benvenuto.apri-lode': 'Abrir o Lode',
};
