// Textos do app de desktop (português do Brasil): janelas do sistema, menu do ícone, notificações e mensagens do
// processo principal (desktop/*.mjs) que chegam ao estudante.
export default {
  // main.mjs: janelas do sistema
  'desktop.non-ci-sono-riuscito': 'Não consegui.',
  'desktop.benvenuto-in-lode': 'Boas-vindas ao Lode',
  'desktop.dove-tenere-il-vault': 'Onde guardar o vault',
  'desktop.usa-questa-cartella': 'Usar esta pasta',
  'desktop.non-e-andata': 'Não deu certo.',
  'desktop.vault-con-sincronizzazione': 'Com a sincronização, o vault se troca em «Sincronizar entre seus computadores»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Parar neste computador» tira o vault da pasta da nuvem.',
  'desktop.scegli-il-vault': 'Escolha o vault do Obsidian',
  'desktop.usa-questo-vault': 'Usar este vault',
  'desktop.cartella-non-usabile': 'O Lode não consegue usar a pasta {cartella}',
  'desktop.cartella-protetta-windows': 'Provavelmente o Windows está protegendo a pasta (Segurança do Windows › Proteção contra ransomware › Acesso controlado a pastas) ou o antivírus está bloqueando o Lode. Permita o Lode ou escolha outra pasta.',
  'desktop.scegli-altra-cartella': 'Escolher outra pasta',
  'desktop.riprova': 'Tentar de novo',
  'desktop.non-ora': 'Agora não',
  'desktop.obsidian-pronto': 'O Obsidian está pronto no seu vault',
  'desktop.modello-pronto': '{modello} está pronto',
  'desktop.ponte-non-partito': 'A ponte com os agentes não iniciou: reinicie o Lode.',
  'desktop.agente-togliere': 'Tirar o Lode da configuração de {agente}?',
  'desktop.agente-collegare': 'Conectar {agente} ao Lode?',
  'desktop.agente-toglie-righe': 'O Lode tira só as linhas dele em:\n{file}',
  'desktop.agente-aggiunge-righe': 'O Lode adiciona só as linhas dele, o resto fica como está em:\n{file}',
  'desktop.agente-manda-eventi': '{agente} vai mandar ao Lode, neste computador, os eventos das sessões (arquivos tocados, comandos, fim da rodada). O Lode não responde e não decide nada. ',
  'desktop.agente-file-com-era': 'O arquivo como estava fica em {file}.',
  'desktop.togli': 'Tirar',
  'desktop.collega': 'Conectar',
  'desktop.annulla': 'Cancelar',
  // main.mjs: o menu do ícone
  'desktop.menu-avvisami-versioni': 'Avisar sobre versões novas',
  'desktop.menu-aggiornamenti-automatici': 'Atualizações automáticas',
  'desktop.menu-riavvia-con': 'Reiniciar com o Lode {versione}',
  'desktop.menu-scarica': 'Baixar o Lode {versione}…',
  'desktop.menu-apri': 'Abrir o Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Espaço',
  'desktop.tasti-apri': 'Ctrl+Shift+Espaço',
  'desktop.menu-quadro': 'O painel: histórico, provas, revisão',
  'desktop.menu-rifai-configurazione': 'Refazer a configuração…',
  'desktop.menu-apri-vault-obsidian': 'Abrir o vault no Obsidian',
  'desktop.menu-mostra-vault': 'Mostrar o vault na pasta',
  'desktop.menu-altro-vault': 'Usar outro vault…',
  'desktop.menu-avvio-accensione': 'Abrir o Lode ao ligar o computador',
  'desktop.menu-icona-mac': 'Ícone do Lode em Aplicativos',
  'desktop.menu-icona-win': 'Ícone do Lode no menu Iniciar e na área de trabalho',
  'desktop.menu-icona-linux': 'Ícone do Lode no menu de aplicativos',
  'desktop.menu-esci': 'Sair do Lode',
  // sincronizza.mjs: a sincronização entre os computadores
  'desktop.sync-file-occupato': 'Um arquivo está sendo usado por outro programa: feche e tente de novo. O vault de antes está intacto.',
  'desktop.sync-file-occupato-nome': 'Um arquivo está sendo usado por outro programa ({file}): feche e tente de novo. O vault de antes está intacto.',
  'desktop.sync-disco-pieno': 'O disco da pasta da nuvem está cheio. O vault de antes está intacto.',
  'desktop.sync-permesso': 'O Lode não tem permissão para ler ou escrever um arquivo. O vault de antes está intacto.',
  'desktop.sync-permesso-nome': 'O Lode não tem permissão para ler ou escrever um arquivo ({file}). O vault de antes está intacto.',
  'desktop.sync-copia-diversa': 'A cópia de {file} não saiu igual: tente de novo. O vault de antes está intacto.',
  'desktop.sync-copia-non-riuscita': 'A cópia do vault não deu certo: tente de novo. O vault de antes está intacto.',
  'desktop.sync-sto-accendendo': 'Já estou ligando a sincronização: espere terminar.',
  'desktop.sync-cartella-titolo': 'A pasta que sincroniza',
  'desktop.sync-sincronizza-qui': 'Sincronizar aqui',
  'desktop.sync-spostamento-con-password': 'A mudança começou com a senha: digite de novo.',
  'desktop.sync-dati-occupati': 'O arquivo de dados do Lode está sendo usado por outro programa (um antivírus?): tente de novo daqui a pouco.',
  'desktop.sync-diario-illeggibile': 'Não dá para ler o diário do Lode neste computador.',
  'desktop.sync-controllo-altro-computer': 'Vendo se outro computador já sincroniza este vault…',
  'desktop.sync-aspetto-dati': 'Esperando os dados do Lode chegarem da nuvem (ainda não dá para ler o arquivo de dados): tente de novo daqui a pouco.',
  'desktop.sync-altra-password': 'Neste vault a sincronização já está ligada com outra senha: digite essa.',
  'desktop.sync-gia-con-password': 'Neste vault a sincronização já está ligada com senha: digite a senha.',
  'desktop.sync-non-accendo': 'Não consigo ligar a sincronização aqui.',
  'desktop.sync-cartella-dentro-vault': 'Esta pasta está dentro do vault: escolha uma fora, por exemplo a pasta do iCloud Drive, OneDrive ou Dropbox.',
  'desktop.sync-dati-non-ancora': 'Ainda não dá para ler os dados do Lode (pasta inacessível?): tente de novo daqui a pouco.',
  'desktop.sync-copio-vault': 'Copiando o vault…',
  'desktop.sync-copio-vault-file': { one: 'Copiando o vault… {n} arquivo', other: 'Copiando o vault… {n} arquivos' },
  'desktop.sync-cifro-pubblico': 'Criptografando e publicando os dados do Lode…',
  'desktop.sync-pubblico': 'Publicando os dados do Lode…',
  'desktop.sync-non-creo-dati': 'Não consigo criar os dados do Lode na pasta da nuvem. O vault de antes está intacto.',
  'desktop.sync-vault-nel-cloud': 'O vault do Lode na pasta da nuvem',
  'desktop.sync-non-e-vault-sincronizzato': 'Nesta pasta não tem um vault do Lode sincronizado: escolha a pasta «Lode» dentro da pasta da nuvem (no outro computador: «Sincronizar entre seus computadores»).',
  'desktop.sync-diario-altro-vault': 'Neste computador o Lode já usa o diário de outro vault: antes, «Parar neste computador».',
  'desktop.sync-password-sbagliata-di-nuovo': 'Senha errada: digite de novo.',
  'desktop.sync-password-vecchia': 'Essa é a senha antiga: ela mudou em outro computador, digite a nova.',
  'desktop.sync-lode-piu-nuova': 'Este vault foi protegido por um Lode mais novo: atualize o seu.',
  'desktop.sync-gruppo-manomesso': 'A senha está certa, mas o arquivo do grupo na pasta da nuvem foi alterado por fora: não vou usar. Confira a pasta da nuvem.',
  'desktop.sync-gruppo-in-chiaro': 'O grupo na pasta da nuvem não está criptografado: no outro computador a sincronização está sem senha, ou o arquivo do grupo foi adulterado. Se no outro computador você não colocou senha, tente de novo sem.',
  'desktop.sync-password-sbagliata': 'Senha errada.',
  'desktop.sync-adesso-non-si-puo': 'Agora não dá.',
  'desktop.sync-cartella-in-cloud': 'Esta pasta está numa pasta da nuvem: para sincronizar, use «Sincronizar entre seus computadores».',
  'desktop.sync-fuori-dal-vault': 'Escolha uma pasta fora do vault atual.',
  'desktop.sync-non-sposto-dati': 'Não consigo mover os dados do Lode para essa pasta. O vault de antes está intacto.',
  'desktop.sync-riprova-tra-poco': 'Agora não dá: tente de novo daqui a pouco.',
  'desktop.sync-password-corta': 'A senha precisa ter pelo menos 8 caracteres.',
  'desktop.sync-diario-illeggibile-riprova': 'Não dá para ler o diário do Lode neste computador: primeiro clique em «Tentar de novo».',
  'desktop.sync-non-accesa': 'Neste computador a sincronização não está ligada.',
  'desktop.sync-vault-spostato-scegli': 'O vault não está mais onde o Lode procurava: se você moveu, use «Encontrar o vault» e escolha a pasta nova.',
  'desktop.sync-dove-fuori-cloud': 'Onde guardar o vault, fora da pasta da nuvem',
  'desktop.sync-tieni-qui': 'Guardar o vault aqui',
  'desktop.sync-fuori-dal-cloud': 'Escolha uma pasta fora da pasta da nuvem.',
  'desktop.sync-vault-spostato': 'O vault não está mais onde o Lode procurava: se você moveu, use «Encontrar o vault».',
  'desktop.sync-cambio-in-arrivo': 'As últimas alterações deste computador ainda não estão na pasta da nuvem (está chegando uma mudança dos outros computadores): tente de novo daqui a pouco.',
  'desktop.sync-smetti-serve-password': 'As alterações feitas na pausa ficariam só neste computador: digite a senha antes de parar (ou «Esqueci a senha»).',
  'desktop.sync-note-non-scaricate': 'Algumas notas não estão baixadas neste computador ({note}): abra ou baixe pelo serviço de nuvem e tente de novo.',
  'desktop.sync-note-non-scaricate-altre': { one: "Algumas notas não estão baixadas neste computador ({note} e mais {n}): abra ou baixe pelo serviço de nuvem e tente de novo.", other: "Algumas notas não estão baixadas neste computador ({note} e mais {n}): abra ou baixe pelo serviço de nuvem e tente de novo." },
  'desktop.sync-copio-fuori-cloud': 'Copiando o vault para fora da pasta da nuvem…',
  // progetto.mjs: «segue o projeto», o resumo «Pronto. Em palavras simples» e a confirmação dos comandos
  'desktop.progetto-elenco': '{primi} e {ultimo}',
  'desktop.progetto-elenco-altre': { one: '{primi} e mais {n}', other: '{primi} e mais {n}' },
  'desktop.progetto-elenco-altri': { one: '{primi} e mais {n}', other: '{primi} e mais {n}' },
  'desktop.progetto-righe-piu-meno': { one: '{n} linha a mais e {meno} a menos', other: '{n} linhas a mais e {meno} a menos' },
  'desktop.progetto-righe-piu': { one: '{n} linha a mais', other: '{n} linhas a mais' },
  'desktop.progetto-righe-meno': { one: '{n} linha a menos', other: '{n} linhas a menos' },
  'desktop.progetto-solo-spazi': 'só espaços ou quebras de linha',
  'desktop.progetto-file-nuovo': { one: 'arquivo novo ({n} linha)', other: 'arquivo novo ({n} linhas)' },
  'desktop.progetto-file-tolto': 'removido',
  'desktop.progetto-funzioni-nuove': { one: 'nova função {elenco}', other: 'novas funções {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'alterada {elenco}', other: 'alteradas {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'removida {elenco}', other: 'removidas {elenco}' },
  'desktop.progetto-file': '{file}: {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'Novo {elenco}.', other: 'Novos {elenco}.' },
  'desktop.progetto-esito-compila': 'compila',
  'desktop.progetto-esito-non-compila': 'não compila',
  'desktop.progetto-esito-sintassi-a-posto': 'sintaxe ok',
  'desktop.progetto-esito-errore-di-sintassi': 'erro de sintaxe',
  'desktop.progetto-esito-make-riuscito': 'make funcionou',
  'desktop.progetto-esito-make-non-riuscito': 'make não funcionou',
  'desktop.progetto-prove-su': { one: '{n} teste de {tot}', other: '{n} testes de {tot}' },
  'desktop.progetto-prova-non-partita': 'o teste não começou',
  'desktop.progetto-inizio-alle': { one: 'Às {ora} mudou {n} arquivo (+{piu} −{meno}).', other: 'Às {ora} mudaram {n} arquivos (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'Das {da} às {a} mudou {n} arquivo (+{piu} −{meno}).', other: 'Das {da} às {a} mudaram {n} arquivos (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**Testado?** Sim: é o código testado às {ora} ({esito}).',
  'desktop.progetto-provato-no-codice': '**Testado?** Não, mas aqui só mudaram arquivos que não são código.',
  'desktop.progetto-provato-no': '**Testado?** Não: depois da última alteração ({ora}) ninguém compilou com o Lode.',
  'desktop.progetto-nota-chi': 'Não sei quem escreveu estas linhas.',
  'desktop.progetto-altri-file': { one: 'E mais {n} arquivo.', other: 'E mais {n} arquivos.' },
  'desktop.progetto-nessuna-cartella': 'Não recebi nenhuma pasta.',
  'desktop.progetto-non-trovo-cartella': 'Não acho esta pasta.',
  'desktop.progetto-cartella-non-file': 'Escolha uma pasta, não um arquivo.',
  'desktop.progetto-radice-disco': 'Esta é a raiz do disco: escolha a pasta só do projeto (por exemplo lab3).',
  'desktop.progetto-tutta-la-home': 'Esta pasta contém toda a sua home: escolha a pasta só do projeto.',
  'desktop.progetto-e-il-vault': 'Este é o vault do Lode (ou contém ele): escolha a pasta do projeto.',
  'desktop.progetto-dati-di-lode': 'Esta é a pasta onde o Lode guarda os dados dele: escolha a do projeto.',
  'desktop.progetto-troppi-progetti': 'Já sigo {n} projetos: pare de seguir um («para de seguir …») e tente de novo.',
  'desktop.progetto-cartella-illeggibile': 'Não consigo ler esta pasta.',
  'desktop.progetto-troppi-file': 'Aqui tem mais de {n} arquivos: escolha a pasta só do projeto (por exemplo lab3).',
  'desktop.progetto-non-seguo': 'Não sigo este projeto.',
  'desktop.progetto-versione-scaduta': 'Essa versão não existe mais: o Lode guarda as versões por 30 dias.',
  'desktop.progetto-file-non-seguito': 'Este arquivo não está entre os que eu sigo.',
  'desktop.progetto-file-illeggibile': 'Não consigo ler o arquivo.',
  'desktop.progetto-poi-per-ogni-prova': 'Depois, para cada teste .in → .out:\n{comandi}',
  'desktop.progetto-senza-prove': 'Não rodo o programa: não tem testes .in/.out.',
  'desktop.progetto-resto-non-mostro': '(o resto eu não mostro)',
  'desktop.progetto-smesso-durante-prova': 'Parei de seguir o projeto durante o teste.',
  'desktop.progetto-scegli-cartella': 'Escolha a pasta do projeto',
  'desktop.progetto-segui-cartella': 'Seguir esta pasta',
  'desktop.progetto-scegli-di-nuovo': 'Escolha a pasta de novo («segue o projeto»).',
  'desktop.progetto-conferma-aperta': 'Já tem uma janela de confirmação aberta: responda primeiro a ela.',
  'desktop.progetto-eseguira': 'O Lode vai executar este comando na pasta {cartella}.',
  'desktop.progetto-come-terminale': 'É como rodar no terminal: o programa roda no seu computador.',
  'desktop.progetto-esegui-sempre': 'Executar sempre neste projeto',
  // esegui.mjs: testar o código do projeto
  'desktop.esegui-riapri': 'Se você acabou de adicionar ao PATH, saia do Lode (pelo menu) e abra de novo.',
  'desktop.esegui-manca-c-win': 'Não acho um compilador C. Instale o MSYS2 (msys2.org), abra «MSYS2 UCRT64» e digite `pacman -S mingw-w64-ucrt-x86_64-gcc`: o Lode encontra sozinho em C:\\msys64\\ucrt64\\bin. Outras opções: WinLibs (winlibs.com) ou WSL. O Lode não baixa nada no seu lugar.',
  'desktop.esegui-manca-c-mac': 'Não acho um compilador C. Abra o Terminal e digite `xcode-select --install`: isso instala o clang da Apple. Depois tente de novo.',
  'desktop.esegui-manca-c-linux': 'Não acho um compilador C. Instale o gcc (por exemplo `sudo apt install build-essential`) e tente de novo.',
  'desktop.esegui-manca-python-win': 'Não acho o Python 3. Instale pelo python.org (marque «Add python.exe to PATH») ou pela Microsoft Store e tente de novo.',
  'desktop.esegui-manca-python': 'Não acho o Python 3. Instale (python.org, ou pelo gerenciador de pacotes) e tente de novo.',
  'desktop.esegui-manca-java': 'Não acho um JDK (javac e java). Instale um, por exemplo o Temurin pelo adoptium.net, e tente de novo.',
  'desktop.esegui-manca-make-win': 'Tem um Makefile, mas não acho o make. Com o MSYS2, em «MSYS2 UCRT64»: `pacman -S mingw-w64-ucrt-x86_64-make`. Ou tire o Makefile e o Lode compila sozinho os arquivos .c.',
  'desktop.esegui-manca-make': 'Tem um Makefile, mas não acho o make. Instale (no Mac: `xcode-select --install`) e tente de novo.',
  'desktop.esegui-manca-programma': 'Falta um programa para testar o código.',
  'desktop.esegui-senza-prove': 'Não acho testes .in/.out: só compilo, não rodo o programa.',
  'desktop.esegui-make-prove': { one: 'Com o Makefile não rodo o teste .in/.out: não sei qual programa ele cria.', other: 'Com o Makefile não rodo os {n} testes .in/.out: não sei qual programa ele cria.' },
  'desktop.esegui-poi-prove': { one: 'depois o teste (arquivo .in → .out esperado)', other: 'depois os {n} testes (arquivos .in → .out esperado)' },
  'desktop.esegui-poi-prove-in': { one: 'depois o teste em {cartella}/ (arquivo .in → .out esperado)', other: 'depois os {n} testes em {cartella}/ (arquivos .in → .out esperado)' },
  'desktop.esegui-senza-programma': '{prove}; {n} sem um programa claro',
  'desktop.esegui-make-leggi': 'O make executa os comandos escritos no Makefile: leia antes de confirmar.',
  'desktop.esegui-make-assente': 'Tem um Makefile, mas não acho o make: eu compilo os arquivos .c.',
  'desktop.esegui-niente-codice': 'Não acho código C, Python ou Java para testar nesta pasta.',
  'desktop.esegui-virgolette': 'As aspas não estão fechadas.',
  'desktop.esegui-invisibili': 'No comando tem caracteres invisíveis (quebra de linha, controle ou direção do texto): digite de novo à mão.',
  'desktop.esegui-comando-vuoto': 'O comando está vazio.',
  'desktop.esegui-comando-illeggibile': 'Não dá para ler o comando.',
  'desktop.esegui-non-trovo-programma': 'Não acho o programa «{programma}».',
  'desktop.esegui-bat': 'Arquivos .bat e .cmd eu não rodo: escreva o comando que eles contêm.',
  'desktop.esegui-compilazione-lenta': 'A compilação não terminou em {n} segundos.',
  'desktop.esegui-prova-senza-programma': 'não sei de qual programa ele é',
  'desktop.esegui-programma-non-creato': 'O comando não criou o programa para testar.',
  'desktop.esegui-prova-illeggibile': 'não consigo ler os arquivos do teste',
  // moodle.mjs: Moodle só leitura
  'desktop.moodle-risponde': 'O Moodle responde {stato}',
  'desktop.moodle-errore': 'erro do Moodle',
  'desktop.moodle-sito-risponde': 'o site responde {stato}',
  'desktop.moodle-non-e-moodle': 'não é um Moodle, ou o serviço para apps está desligado',
  'desktop.moodle-non-collegato': 'O Moodle não está conectado',
  'desktop.moodle-accesso-non-riuscito': 'o login não deu certo',
  'desktop.moodle-accedi-a': 'Entrar em {sito}',
  'desktop.moodle-risposta-non-valida': 'resposta inválida do Moodle',
  'desktop.moodle-tempo-scaduto': 'tempo esgotado',
  'desktop.moodle-file-non-trovato': 'arquivo não encontrado',
  'desktop.moodle-file-troppo-grande': 'arquivo grande demais',
  'desktop.moodle-file-non-su-moodle': 'o arquivo não está no Moodle',
  // installa.mjs: o Obsidian e o cérebro local (Ollama)
  'desktop.installa-download-non-riuscito': 'o download não deu certo ({stato})',
  'desktop.installa-non-firmato': 'O instalador do {nome} não tem a assinatura oficial do {nome}, então não instalei. Tente de novo mais tarde ou baixe você mesmo pelo site oficial.',
  'desktop.installa-versione-obsidian': 'versão do Obsidian desconhecida',
  'desktop.installa-scarico-obsidian': 'Baixando o Obsidian {versione}',
  'desktop.installa-scarico-obsidian-mb': 'Baixando o Obsidian {versione} · {mb} MB',
  'desktop.installa-installo-obsidian': 'Instalando o Obsidian',
  'desktop.installa-obsidian-installato': 'Obsidian {versione} instalado',
  'desktop.installa-perche-4b': 'rápido mesmo sem placa de vídeo: definições, cartões, jogos e prova oral',
  'desktop.installa-perche-35b': 'o melhor, e rápido como um modelo pequeno, para computadores com muita memória',
  'desktop.installa-perche-9b': 'explica bem e aguenta a prova oral',
  'desktop.installa-perche-memoria': 'para {gb} GB de memória: definições, cartões, jogos e prova oral',
  'desktop.installa-ollama-non-avviato': 'O Ollama não iniciou',
  'desktop.installa-ollama-linux': 'No Linux, instale o Ollama pelo ollama.com com o script deles e depois volte aqui.',
  'desktop.installa-scarico-ollama-mb': 'Baixando o Ollama · {mb} MB',
  'desktop.installa-installo-ollama': 'Instalando o Ollama',
  'desktop.installa-avvio-ollama': 'Iniciando o Ollama',
  'desktop.installa-ollama-non-risponde': 'O Ollama não responde',
  'desktop.installa-scarico-modello': 'Baixando {nome} · {fatti} de {totale} GB',
  'desktop.installa-modello-pronto': '{nome} pronto',
  'desktop.installa-modello-assente': 'O modelo {modello} não está instalado',
  'desktop.installa-modello-non-risponde': 'O modelo local não responde',
  // aggiorna.mjs: as versões novas do Lode
  'desktop.aggiorna-github-risponde': 'O GitHub responde {stato}',
  'desktop.aggiorna-non-installato': 'A atualização não foi instalada. Tente de novo, ou feche o Lode: ela se instala ao sair.',
  'desktop.aggiorna-non-installato-perche': 'A atualização não foi instalada: {motivo}. Tente de novo, ou feche o Lode: ela se instala ao sair.',
  'desktop.aggiorna-niente-pronto': 'Não tem nenhuma atualização pronta para instalar.',
  'desktop.aggiorna-dove-scaricare': 'Ainda não sei de onde baixar: tente de novo daqui a pouco.',
  // voce-onnx.mjs e voce-onnx-motore.mjs: a voz Parakeet ONNX
  'desktop.voce-modello-illeggibile': 'Não consigo ler o modelo de voz: tente de novo daqui a pouco.',
  'desktop.voce-spazio': 'Para a voz Parakeet precisa de uns {serve} MB livres no disco, e tem {liberi}.',
  'desktop.voce-rete': 'Não consigo baixar a voz: confira a conexão e tente de novo. ({dettaglio})',
  'desktop.voce-rete-stato': 'Não consigo baixar a voz ({stato}): tente de novo mais tarde.',
  'desktop.voce-file-troppo-grande': 'O arquivo da voz é maior do que o esperado.',
  'desktop.voce-interrotto': 'O download da voz parou: na próxima vez ele continua daqui. ({dettaglio})',
  'desktop.voce-impronta': 'O arquivo da voz «{file}» não é o certo (impressão digital SHA256 diferente): apaguei.',
  'desktop.voce-addon': 'O programa da voz (sherpa-onnx) não carrega neste computador.',
  'desktop.voce-modello-rovinato': 'O modelo do Parakeet não carrega (talvez um arquivo esteja corrompido).',
  'desktop.voce-pezzo-non-trascritto': 'O Parakeet não conseguiu transcrever este trecho.',
  'desktop.voce-motore-chiuso': 'O motor da voz fechou de repente.',
  'desktop.voce-motore-chiuso-codice': 'O motor da voz fechou de repente ({codice}).',
  'desktop.voce-motore-non-risponde': 'O motor da voz não responde.',
  // agenti-collegamenti.mjs: a conexão com os agentes de programação
  'desktop.agenti-claude-eventi': ['prompt', 'alterações e comandos', 'fim da rodada', 'notificações'],
  'desktop.agenti-claude-nota': 'Os hooks valem a partir da próxima sessão (ou revise em /hooks).',
  'desktop.agenti-codex-eventi': ['prompt', 'alterações (apply_patch) e comandos', 'fim da rodada'],
  'desktop.agenti-codex-nota': 'Na próxima sessão o Codex pede para você aprovar os hooks novos: faça isso com /hooks.',
  'desktop.agenti-gemini-eventi': ['prompt', 'ferramentas (arquivos e comandos)', 'fim da resposta', 'notificações'],
  'desktop.agenti-gemini-nota': 'Vale a partir da próxima sessão do Gemini CLI.',
  'desktop.agenti-cursor-eventi': ['prompt', 'arquivos alterados', 'comandos', 'resposta do agente'],
  'desktop.agenti-cursor-nota': 'Reinicie o Cursor para ele ler os hooks. O Cursor não informa o código de saída dos comandos: os testes rodados aparecem, o resultado não.',
  'desktop.agenti-copilot-eventi': ['prompt', 'ferramentas (arquivos e comandos)', 'fim da rodada', 'notificações'],
  'desktop.agenti-copilot-nota': 'Um único arquivo do Lode em ~/.copilot/hooks: vale a partir da próxima sessão. O Copilot não manda a última mensagem do agente.',
  'desktop.agenti-windsurf-eventi': ['prompt', 'código escrito', 'comandos', 'resposta do Cascade'],
  'desktop.agenti-windsurf-nota': 'Vale a partir da próxima conversa do Cascade. O Windsurf não informa o código de saída dos comandos.',
  'desktop.agenti-qwen-eventi': ['prompt', 'ferramentas (arquivos e comandos)', 'fim da rodada', 'notificações'],
  'desktop.agenti-qwen-nota': 'Vale a partir da próxima sessão do Qwen Code.',
  'desktop.agenti-opencode-eventi': ['arquivos alterados', 'comandos', 'fim da rodada'],
  'desktop.agenti-opencode-nota': 'Um plugin do Lode em ~/.config/opencode/plugins: vale a partir da próxima vez que o OpenCode abrir. Só lê: não mexe nas respostas.',
  'desktop.agenti-kilo-eventi': ['arquivos alterados', 'comandos', 'fim da rodada'],
  'desktop.agenti-kilo-nota': 'O plugin é o do OpenCode (o Kilo é um fork dele): vale a partir da próxima vez que abrir. O formato dos eventos ainda precisa ser conferido na sua versão.',
  'desktop.agenti-aider-eventi': ['fim da resposta (sem detalhes)'],
  'desktop.agenti-aider-nota': 'O Aider só avisa que terminou de responder, sem dizer o que tocou: os arquivos alterados quem vê é o «segue o projeto».',
  'desktop.agenti-non-json': 'não é um objeto JSON',
  'desktop.agenti-file-non-di-lode': 'já existe um arquivo com este nome que não é do Lode',
  'desktop.agenti-notifiche-aider': 'já existem as notificações do Aider: o Lode não sobrescreve',
  'desktop.agenti-file-illeggibile': 'Não dá para ler {file} ({motivo}): não vou mexer. Arrume ou conecte à mão.',
  'desktop.agenti-altre-righe': { one: 'e mais {n} linha', other: 'e mais {n} linhas' },
  'desktop.agenti-test-non-rilanciati': 'Diz que os testes passam, mas depois da última alteração não rodou de novo.',
  'desktop.agenti-test-non-lanciati': 'Diz que os testes passam, mas nesta rodada não vi ele rodar.',
  'desktop.agenti-test-toccati': 'Alterou os testes ({file}) enquanto falhavam: confira se não ficaram mais fáceis.',
  // collegamento.mjs: o Lode aberto pelo código (ícone, abrir ao ligar, permissões do Mac)
  'desktop.permesso-audio-computer': 'O Lode só ouve o áudio do computador quando você transcreve uma videoaula. O áudio nunca fica no computador: na nota vai só o texto.',
  'desktop.permesso-microfono': 'O Lode usa o microfone quando você fala com ele, para o «Repete» na aula e para transcrever as aulas que você escolher. O áudio nunca fica no computador.',
  'desktop.icona-non-creata': 'não consigo criar {file}',
};
