// O registro no vault (português do Brasil): as linhas do diário do projeto, a tabela «Cosa so davvero» e a
// seção «Informatica» de Lode/Memoria.md. Os títulos das seções («## Cosa ho capito», «## Cosa so davvero», «## Informatica»),
// as propriedades e as marcas %% lode:… %% NÃO ficam aqui: são nomes do vault, que o código procura.
export default {
  'diario.concetto-for': 'Laço for',
  'diario.concetto-while': 'Laço while',
  'diario.concetto-do-while': 'Laço do-while',
  'diario.concetto-ritroso': 'Contagem regressiva',
  'diario.concetto-array': 'Array',
  'diario.concetto-divisione-intera': 'Divisão inteira',
  'diario.concetto-resto': 'Resto com negativos',
  'diario.concetto-cast': 'Cast para double',
  'diario.concetto-incremento': 'i++ e ++i',
  'diario.concetto-switch': 'switch e break',
  'diario.concetto-cortocircuito': '&& e || em curto-circuito',
  'diario.concetto-else-pendente': 'else pendente',
  'diario.concetto-puntatori': 'Passagem por referência',
  'diario.concetto-parametri': 'Passagem por valor',
  'diario.concetto-visibilita': 'Variáveis nos blocos',
  'diario.concetto-char': 'char e códigos ASCII',
  'diario.concetto-ricorsione': 'Recursão',
  'diario.concetto-annidati': 'Laços aninhados',
  'diario.concetto-break-continue': 'break e continue',
  'diario.concetto-ternario': 'Operador ternário',
  'diario.concetto-printf': 'printf e formatos',
  'diario.elenco-e': '{prima} e {ultimo}',
  'diario.errore-titolo': '«{titolo}»',
  'diario.errore-generico': 'erro',
  'diario.passo-dove': '«onde olhar»',
  'diario.passo-cosa': '«o que quer dizer»',
  'diario.passi-visti': { one: 'visto {passi}', other: 'vistos {passi}' },
  'diario.funzione-nuova': 'nova {nome}',
  'diario.funzione-nuova-in': 'nova {nome} em {file}',
  'diario.funzione-cambiata': 'alterada {nome}',
  'diario.funzione-cambiata-in': 'alterada {nome} em {file}',
  'diario.funzione-tolta': 'removida {nome}',
  'diario.funzione-tolta-in': 'removida {nome} em {file}',
  'diario.file-nuovo': 'novo {file}',
  'diario.file-tolto': 'removido {file}',
  'diario.cambiati-file': { one: 'Alterado {n} arquivo', other: 'Alterados {n} arquivos' },
  'diario.cambiato-codice': 'Código alterado',
  'diario.altre-modifiche': { one: 'e mais {n} alteração', other: 'e mais {n} alterações' },
  'diario.chi-ha-scritto': 'quem escreveu: não sei',
  'diario.cambiato-durante': 'o código mudou durante o teste',
  'diario.prova-non-compila': 'Teste: ✗ não compila',
  'diario.prova-non-compila-errore': 'Teste: ✗ não compila, {errore}',
  'diario.prova-non-partita': 'Teste: não rodou',
  'diario.prova-ok': 'Teste: ✓ compila · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} testes',
  'diario.nessun-caso': 'nenhum caso de teste',
  'diario.ma-cambiato': 'mas o código mudou durante o teste',
  'diario.codice-provato': 'código testado',
  'diario.prova-ko': 'Teste: ✗ compila · {ok}/{tot} testes',
  'diario.n-prove': { one: '{n} teste', other: '{n} testes' },
  'diario.nessuna-prova': 'nenhum teste',
  'diario.errori-risolti': { one: '{n} erro resolvido', other: '{n} erros resolvidos' },
  'diario.n-errori': { one: '{n} erro', other: '{n} erros' },
  'diario.n-risolti': { one: '{n} resolvido', other: '{n} resolvidos' },
  'diario.correzioni-viste': 'correções vistas: {n}',
  'diario.oggi': 'Hoje: {parti}',
  'diario.ultima-non-provata': 'última alteração não testada',
  'diario.smette': 'O Lode para de seguir {progetto}',
  'diario.segue': 'O Lode segue {progetto}',
  'diario.errore': 'Erro: {errore}',
  'diario.correzione-vista': 'Correção vista: {errore}',
  'diario.spiegate': 'Explicadas: {spiegate} de {totale}',
  'diario.spiegate-rivedere': 'Explicadas: {spiegate} de {totale}; para rever: {nomi}',
  'diario.ieri': 'ontem',
  'diario.giorni-fa': { one: 'há {n} dia', other: 'há {n} dias' },
  'diario.stato-da-rifare': 'refazer',
  'diario.stato-sicuro': 'seguro',
  'diario.stato-mai-fatto': 'nunca feito',
  'diario.diari-dei-progetti': 'Diários dos projetos:',
  'diario.tabella-nota': 'Contas do Lode nos exercícios «O que imprime?», sem IA. «Refazer» quer dizer que é hora de revisar.',
  'diario.tabella-testa': '| Tópico | Exercícios | De primeira | Última vez | Estado |',
  'diario.nessun-esercizio': 'Nenhum exercício ainda. Escreva «o que imprime» na barra: são 5 perguntas de um minuto.',
  'diario.errori-frequenti': 'Erros que você mais encontra: {errori}.',
  'diario.sbagli-spesso': 'Você erra muito: {sbagli}.',
  'diario.memoria-stampa': { one: '«O que imprime?»: {n} exercício, {giuste}% certos de primeira.', other: '«O que imprime?»: {n} exercícios, {giuste}% certos de primeira.' },
  'diario.da-rifare': 'Refazer: {argomenti}.',
};
