// «Pronto para a apresentação» (português do Brasil): os estados das funções, os pontos achados no código e o cartão.
// As palavras que reconhecem a explicação do estudante (controlla() em js/codice/discussione.js) NÃO ficam aqui.
export default {
  'discussione.data-breve': '{g}/{m}',
  'discussione.stato-agente': 'alterada enquanto o agente trabalhava · nunca explicada',
  'discussione.stato-mai': 'nunca explicada',
  'discussione.stato-cambiata': 'alterada depois da última vez que você explicou',
  'discussione.stato-rivedere': { one: 'para rever · você pulou um ponto', other: 'para rever · você pulou {n} pontos' },
  'discussione.stato-spiegata': 'explicada em {data}',
  'discussione.spiegata-adesso': 'explicada agora',
  'discussione.punto-parametri-breve': 'os parâmetros',
  'discussione.punto-parametri': 'os parâmetros ({nomi})',
  'discussione.punto-niente': 'que não recebe nada',
  'discussione.punto-chiama': 'que chama `{nome}`',
  'discussione.punto-ciclo-breve': 'o laço',
  'discussione.punto-ciclo': 'que tem um laço',
  'discussione.punto-ricorsiva-breve': 'que é recursiva',
  'discussione.punto-ricorsiva': 'que é recursiva: chama a si mesma',
  'discussione.punto-restituisce-breve': 'o que retorna',
  'discussione.punto-restituisce-niente': 'que não retorna nada',
  'discussione.punto-restituisce-valore': 'que retorna um valor',
  'discussione.punto-restituisce-tipo': 'que retorna um `{tipo}`',
  'discussione.file-non-arrivato': 'o arquivo não chegou',
  'discussione.nota': 'O Lode não sabe quem escreveu as linhas: «enquanto o agente trabalhava» quer dizer que o arquivo mudou durante uma rodada dele. O Lode não explica o código para você: só confere se você sabe explicar.',
  'discussione.hai-detto': 'Você falou: {punti}.',
  'discussione.nessun-punto': 'Não achei nenhum dos pontos que vejo no código.',
  'discussione.hai-saltato': 'Você pulou: {punti}.',
  'discussione.tutti-i-punti': 'Você tocou em todos os pontos que achei no código.',
  'discussione.la-so-spiegare': 'Sei explicar',
  'discussione.proviamo': 'Vamos tentar',
  'discussione.titolo': 'Pronto para a apresentação',
  'discussione.intro': 'As funções que mudaram desde que você segue o projeto. Primeiro as que mudaram enquanto um agente trabalhava e que você nunca explicou.',
  'discussione.diario-spento': 'Diário desligado: não anoto nada.',
  'discussione.spiegate': 'Explicadas: {spiegate} de {totale}',
  'discussione.nessuna-funzione': 'Não vejo funções alteradas em {nome} desde que você começou a seguir. Quando mudarem, elas aparecem aqui.',
  'discussione.lingua-sconosciuta': 'Nessa linguagem não sei conferir: marque você se sabe explicar.',
  'discussione.leggo-il-file': 'Lendo o arquivo…',
  'discussione.file-lungo': '{file} tem {n} linhas: acima de 2000 eu não leio. Marque você se sabe explicar.',
  'discussione.non-riesco-leggere': 'Não consigo ler {file}: {errore}',
  'discussione.non-trovo-piu': 'Não acho mais <code>{nome}</code> em {file}: talvez você tenha renomeado ou apagado.',
  'discussione.togli': 'Tirar da lista',
  'discussione.spiegala': '<code>{firma}</code> · {file}, linha {riga}. Explique como na apresentação: o que recebe, o que retorna, como funciona. O código eu mostro depois.',
  'discussione.aria-spiegazione': 'Sua explicação de {nome}',
  'discussione.ho-finito': 'Terminei',
  'discussione.alla-buona': 'Os pontos são achados pelo código, de forma simples: ele não diz se a explicação está certa.',
};
