// Os erros do compilador e dos programas (js/errori.js), em português do Brasil.
// As chaves «errori.<item>.<campo>» são os textos de cada item do dicionário: etiqueta, breve, frase, onde, o que, conceito.
// As mensagens do compilador citadas ficam em inglês, como o compilador imprime.
export default {
  'errori.for-punto-e-virgola.etichetta': 'o `for` com vírgulas',
  'errori.for-punto-e-virgola.frase': 'as três partes do `for` se separam com `;`',
  'errori.for-punto-e-virgola.dove': `Olhe o \`for\` {allaRiga}: entre os parênteses precisa ter dois \`;\`.`,
  'errori.for-punto-e-virgola.cosa': 'O `for` tem três partes: início, condição e passo, como em `for (i = 0; i < n; i++)`. Elas se separam com `;`, não com `,`. Com vírgulas o compilador vê uma parte só.',
  'errori.for-punto-e-virgola.concetto': 'laço for',
  'errori.punto-e-virgola.etichetta': 'falta `;`',
  'errori.punto-e-virgola.breve': 'falta ;',
  'errori.punto-e-virgola.frase': 'falta um `;`',
  'errori.punto-e-virgola.dove': `Olhe o fim da linha {riga}, a que vem antes da {riga2}: ali falta o \`;\`. O compilador só percebe quando lê a linha seguinte.`,
  'errori.punto-e-virgola.dove-2': `Olhe o fim da linha {riga}{colonna}: ali falta o \`;\`.`,
  'errori.punto-e-virgola.dove-3': `Olhe o fim da linha {riga} e o da linha anterior: às vezes o compilador só percebe na linha seguinte.`,
  'errori.punto-e-virgola.dove-4': 'Olhe o fim das instruções perto do ponto indicado.',
  'errori.punto-e-virgola.cosa': `Em {L} cada instrução termina com \`;\`, como uma frase termina com ponto. Sem ele, o compilador gruda a instrução na seguinte e não entende mais o que você queria dizer. Por isso às vezes o erro aparece na linha seguinte.`,
  'errori.punto-e-virgola.concetto': 'fim das instruções',
  'errori.include-mancante.etichetta': 'falta um `#include`',
  'errori.include-mancante.breve': `falta #include{h}`,
  'errori.include-mancante.frase-2': 'esta função',
  'errori.include-mancante.frase': `para usar {nome} falta \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'esta função',
  'errori.include-mancante.frase-3': `para usar {nome} falta um \`#include\``,
  'errori.include-mancante.dove-2': `: falta a de \`<{h}>\``,
  'errori.include-mancante.dove': `Olhe no topo do arquivo, onde ficam as linhas \`#include\`{h}.`,
  'errori.include-mancante.cosa': '`bool`, `true` e `false` não existem no C básico: chegam com `{h}`.',
  'errori.include-mancante.cosa-3': 'Esse nome',
  'errori.include-mancante.cosa-4': `, ou seja, \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome} não é você que escreve: está na biblioteca padrão do C. Para usar, você precisa incluir o arquivo que o descreve (o header){h}. Sem \`#include\` o compilador não sabe que ele existe nem como se usa.`,
  'errori.include-mancante.cosa-5': ' Com `math.h`, no Linux adicione também `-lm` no fim do comando de compilação.',
  'errori.include-mancante.concetto': 'bibliotecas e #include',
  'errori.funzione-non-dichiarata.etichetta': 'função não declarada',
  'errori.funzione-non-dichiarata.breve-2': 'função',
  'errori.funzione-non-dichiarata.breve': `{nome} não declarada`,
  'errori.funzione-non-dichiarata.frase': `você usa a função {nome} antes de declarar`,
  'errori.funzione-non-dichiarata.dove': `Procure onde você escreve a função {nome}: se ela está abaixo da linha {riga}, ali o compilador ainda não a conhece. Confira também se o nome está escrito exatamente igual.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Procure onde você escreve a função {nome}: se ela está abaixo da linha do erro, ali o compilador ainda não a conhece. Confira também se o nome está escrito exatamente igual.`,
  'errori.funzione-non-dichiarata.cosa': 'O compilador lê o arquivo de cima para baixo. Se você chama uma função que ele ainda não viu, ele não sabe quais parâmetros ela quer nem o que retorna: os compiladores recentes param, os mais antigos tentam adivinhar e muitas vezes erram. Mova a função para cima do `main`, ou escreva acima do `main` o protótipo dela: a primeira linha da função seguida de `;`.',
  'errori.funzione-non-dichiarata.concetto': 'protótipos das funções',
  'errori.non-dichiarato.etichetta': 'nome não declarado',
  'errori.non-dichiarato.breve-2': 'nome',
  'errori.non-dichiarato.breve': `{nome} não declarado`,
  'errori.non-dichiarato.frase': `você usa {nome}, mas ele não foi declarado`,
  'errori.non-dichiarato.frase-2': 'você usa um nome que não foi declarado',
  'errori.non-dichiarato.dove': `O compilador sugere {s}: veja se você queria escrever isso. `,
  'errori.non-dichiarato.dove-3': 'este nome',
  'errori.non-dichiarato.dove-2': `Procure onde você declara {nome}: talvez tenha outro nome (uma letra diferente, maiúsculas e minúsculas), ou esteja declarado dentro de outro bloco \`{ }\`.`,
  'errori.non-dichiarato.cosa': 'O método que você chama não existe com esse nome e com esses tipos de argumentos. Confira como está escrito e se está na classe certa. ',
  'errori.non-dichiarato.cosa-2': 'Antes de usar uma variável você precisa declarar, ou seja, escrever o tipo e o nome dela (por exemplo `int conta = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'Uma variável declarada dentro de `{ }` só existe ali dentro: fora do bloco o compilador não a vê mais. A ordem também conta: a declaração precisa estar acima da linha que a usa.',
  'errori.non-dichiarato.concetto': 'declaração e escopo das variáveis',
  'errori.formato.etichetta': 'formato errado no printf ou scanf',
  'errori.formato.frase': `o formato pede um {atteso}, mas você passa um {dato}`,
  'errori.formato.frase-2': 'o formato não corresponde ao valor que você passa',
  'errori.formato.dove': `Olhe a linha {riga}: compare cada \`%\` da string com o valor na mesma posição.`,
  'errori.formato.dove-senza-riga': `Olhe a linha indicada: compare cada \`%\` da string com o valor na mesma posição.`,
  'errori.formato.cosa': 'No `scanf` cada `%` pede o endereço de uma variável do tipo certo: `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → array de `char`. Se o tipo não bate, o valor lido é gravado errado.',
  'errori.formato.cosa-2': ` Para um {dato} no \`scanf\` se usa {p}.`,
  'errori.formato.cosa-3': 'O `printf` não sabe de que tipo são os valores: ele confia na string de formato. `%d` é para `int`, `%f` para `double`, `%c` para `char`, `%s` para strings. Se o formato não bate com o valor, ele imprime números sem sentido.',
  'errori.formato.cosa-4': ' Para um `unsigned long` se usa `%lu`; se for o resultado de `strlen` ou `sizeof` (um `size_t`) se usa `%zu`.',
  'errori.formato.cosa-5': ` Para um {dato} no \`printf\` se usa {p}.`,
  'errori.formato.concetto': 'printf, scanf e os formatos',
  'errori.scanf-e-commerciale.etichetta': 'falta `&` no scanf',
  'errori.scanf-e-commerciale.breve': 'falta & no scanf',
  'errori.scanf-e-commerciale.frase': 'o `scanf` quer o endereço da variável: falta `&`',
  'errori.scanf-e-commerciale.dove': `Olhe o \`scanf\` {allaRiga}: tem uma variável sem \`&\` na frente.`,
  'errori.scanf-e-commerciale.cosa': 'O `scanf` precisa escrever dentro da sua variável, então ele precisa saber onde ela fica na memória: o endereço dela, que se obtém com `&`. Se escreve `scanf("%d", &n);`. Os arrays de `char` (as strings) são exceção: o nome deles já é um endereço, então nada de `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf e endereços',
  'errori.return-mancante.etichetta': 'falta o `return`',
  'errori.return-mancante.breve': 'falta o return',
  'errori.return-mancante.frase-2': `a função {nome}`,
  'errori.return-mancante.frase-3': 'a função',
  'errori.return-mancante.frase-4': 'em alguns casos ',
  'errori.return-mancante.frase': `{p} {sigla}chega ao fim sem \`return\``,
  'errori.return-mancante.dove': `Olhe a \`}\` {allaRiga}: é o fim da função{p}. Siga cada caminho possível (cada \`if\` e \`else\`) e confira se termina com um \`return\`.`,
  'errori.return-mancante.cosa-2': ` (aqui ela retorna {tipo})`,
  'errori.return-mancante.cosa': `Uma função que não é \`void\`{tipo} promete retornar um valor. Se ela chega à \`}\` final sem \`return\`, quem chama recebe um valor qualquer. Acontece muito com um \`if\` que tem o seu \`return\`, mas sem um \`else\`.`,
  'errori.return-mancante.concetto': 'return nas funções',
  'errori.assegnamento-in-condizione.etichetta': '`=` no lugar de `==`',
  'errori.assegnamento-in-condizione.breve': '= no lugar de ==',
  'errori.assegnamento-in-condizione.frase': 'na condição tem `=` (atribui) em vez de `==` (compara)',
  'errori.assegnamento-in-condizione.dove': `Olhe a condição {allaRiga}{colonna}.`,
  'errori.assegnamento-in-condizione.cosa': '`=` coloca um valor na variável; `==` confere se dois valores são iguais. `if (x = 5)` atribui 5 a `x` e é sempre verdadeiro, porque 5 não é zero. Para comparar você precisa de `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'atribuição e comparação',
  'errori.confronto-stringhe.etichetta': 'strings comparadas com `==`',
  'errori.confronto-stringhe.frase': 'você compara strings com `==`',
  'errori.confronto-stringhe.dove': `Olhe a comparação {allaRiga}.`,
  'errori.confronto-stringhe.cosa': 'Em C, `==` entre duas strings compara os endereços, não as letras: quase sempre dá falso mesmo se o texto é igual. Para comparar o texto se usa `strcmp(a, b) == 0`, de `{h}`. Se você queria um caractere só, escreva entre aspas simples: `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'strings em C',
  'errori.puntatore-intero.etichetta': 'comparação entre ponteiro e inteiro',
  'errori.puntatore-intero.frase': 'você compara um endereço (um ponteiro) com um número ou um caractere',
  'errori.puntatore-intero.dove': `Olhe os dois lados da comparação {allaRiga}.`,
  'errori.puntatore-intero.cosa': 'De um lado tem um ponteiro (um endereço, por exemplo uma string), do outro um número ou um caractere. Um erro típico: `"a"` entre aspas duplas é uma string, `\'a\'` entre aspas simples é um caractere. Para conferir um caractere escreva `s[0] == \'a\'`; para comparar duas strings use `strcmp`.',
  'errori.puntatore-intero.concetto': 'caracteres, strings e ponteiros',
  'errori.puntatori-incompatibili.etichetta': 'ponteiros de tipos diferentes',
  'errori.puntatori-incompatibili.frase': `você usa um {dato} onde precisa de um {atteso}`,
  'errori.puntatori-incompatibili.frase-2': 'você usa um ponteiro de um tipo onde precisa de outro',
  'errori.puntatori-incompatibili.dove': `Olhe a linha {riga}: compare o tipo do que você passa (ou atribui) com o tipo necessário.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Olhe a linha indicada: compare o tipo do que você passa (ou atribui) com o tipo necessário.`,
  'errori.puntatori-incompatibili.cosa': 'Um ponteiro carrega o tipo daquilo para que aponta: um `int *` aponta para inteiros, um `char *` para caracteres. Usar um no lugar do outro normalmente quer dizer que você errou a variável, ou o tipo na declaração ou no parâmetro da função.',
  'errori.puntatori-incompatibili.concetto': 'ponteiros',
  'errori.intero-puntatore.etichetta': 'número e endereço misturados',
  'errori.intero-puntatore.frase': 'você mistura um número e um endereço (um ponteiro)',
  'errori.intero-puntatore.dove': `Olhe a linha {riga}: de um lado tem um ponteiro, do outro um valor normal.`,
  'errori.intero-puntatore.dove-senza-riga': `Olhe a linha indicada: de um lado tem um ponteiro, do outro um valor normal.`,
  'errori.intero-puntatore.cosa': 'Um ponteiro guarda um endereço de memória, não um número qualquer. Se você quer o endereço de uma variável, escreva `&x`; se quer o valor para onde um ponteiro aponta, escreva `*p`.',
  'errori.intero-puntatore.cosa-2': ' Aqui o compilador sugere `&`.',
  'errori.intero-puntatore.cosa-3': ' Aqui o compilador sugere `*`.',
  'errori.intero-puntatore.cosa-4': ' Cuidado: `"a"` entre aspas duplas é uma string; um caractere se escreve entre aspas simples: `\'a\'`.',
  'errori.intero-puntatore.concetto': 'ponteiros',
  'errori.variabile-non-usata.etichetta': 'variável não usada',
  'errori.variabile-non-usata.breve-2': 'variável',
  'errori.variabile-non-usata.breve': `{nome} não usada`,
  'errori.variabile-non-usata.frase-2': 'uma variável',
  'errori.variabile-non-usata.frase': `{nome} foi declarada, mas você nunca usa`,
  'errori.variabile-non-usata.dove': `Olhe a declaração {allaRiga}.`,
  'errori.variabile-non-usata.cosa': 'É só um aviso: o programa compila do mesmo jeito. Mas muitas vezes quer dizer que você esqueceu de usar a variável, ou que no lugar dela usa sem querer outra com um nome parecido. Se não serve, tire.',
  'errori.variabile-non-usata.concetto': 'variáveis',
  'errori.parametro-non-usato.etichetta': 'parâmetro não usado',
  'errori.parametro-non-usato.frase': `o parâmetro {nome} nunca é usado`,
  'errori.parametro-non-usato.dove': `Olhe a primeira linha da função {allaRiga}.`,
  'errori.parametro-non-usato.cosa': 'A função recebe esse valor, mas não usa. Às vezes tudo bem (por exemplo `argc` e `argv` no `main`); outras vezes quer dizer que no lugar dele você usa outra variável.',
  'errori.parametro-non-usato.concetto': 'parâmetros das funções',
  'errori.non-inizializzata.etichetta': 'variável sem valor',
  'errori.non-inizializzata.breve-2': 'variável',
  'errori.non-inizializzata.breve': `{nome} sem valor`,
  'errori.non-inizializzata.frase-2': 'uma variável',
  'errori.non-inizializzata.frase': `você usa {nome} antes de dar um valor a ela`,
  'errori.non-inizializzata.dove-2': 'esta variável',
  'errori.non-inizializzata.dove-3': ` (linha {dichiarata})`,
  'errori.non-inizializzata.dove': `Olhe {laRiga}, depois suba até onde {nome} é declarada{dichiarata}: tem algum caminho em que ela nunca recebe um valor?`,
  'errori.non-inizializzata.cosa': 'Em Java uma variável local precisa receber um valor antes de ser lida, em todos os caminhos possíveis (mesmo quando um `if` é falso). Dê um valor inicial na declaração, por exemplo `int soma = 0;`.',
  'errori.non-inizializzata.cosa-2': 'Uma variável local recém-declarada tem um valor qualquer, o que sobrou na memória. Antes de ler, você precisa dar um valor a ela, por exemplo `int soma = 0;`. Acontece muito com somas e contadores.',
  'errori.non-inizializzata.concetto': 'inicialização das variáveis',
  'errori.riferimento-non-definito.etichetta': 'função nunca definida (linker)',
  'errori.riferimento-non-definito.breve': 'falta o main',
  'errori.riferimento-non-definito.breve-3': 'função',
  'errori.riferimento-non-definito.breve-2': `{nome} não definida`,
  'errori.riferimento-non-definito.frase': 'falta a função `main`',
  'errori.riferimento-non-definito.frase-2': `{nome} não é encontrada: falta \`-lm\` no comando`,
  'errori.riferimento-non-definito.frase-4': 'uma função',
  'errori.riferimento-non-definito.frase-3': `{nome} é usada, mas não acho onde ela está escrita`,
  'errori.riferimento-non-definito.dove': 'Confira se um dos arquivos tem `int main(void)` (ou `int main(int argc, char *argv[])`) escrito exatamente assim, e se esse arquivo está no comando de compilação.',
  'errori.riferimento-non-definito.dove-2': 'Olhe o comando de compilação: no fim precisa de `-lm`.',
  'errori.riferimento-non-definito.dove-4': 'esta função',
  'errori.riferimento-non-definito.dove-3': `O linker não indica uma linha. Procure no projeto onde {nome} está escrita por inteiro, ou seja, a versão com as \`{ }\`: o nome precisa ser idêntico (maiúsculas também) e o arquivo que a contém precisa estar no comando de compilação.`,
  'errori.riferimento-non-definito.cosa': 'Todo programa em C começa pelo `main`. Se ele falta, ou está escrito com outro nome (`Main`, `mian`), não tem um ponto de partida. No Windows a mensagem às vezes fala de `WinMain`: é o mesmo problema.',
  'errori.riferimento-non-definito.cosa-2': 'As funções de `{h}` ficam numa biblioteca à parte. No Linux (e às vezes com MinGW) é preciso adicionar `-lm` no fim do comando: `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'A compilação tem duas fases: primeiro cada arquivo `.c` é traduzido sozinho, depois o linker junta todos. O protótipo diz ao compilador que a função existe, mas o linker não achou o corpo dela em lugar nenhum. Normalmente o nome está escrito diferente, falta um arquivo no comando, ou a função nunca foi escrita.',
  'errori.riferimento-non-definito.concetto': 'compilação e linker',
  'errori.definizione-multipla.etichetta': 'definido duas vezes (linker)',
  'errori.definizione-multipla.breve-2': 'nome',
  'errori.definizione-multipla.breve': `{nome} definido duas vezes`,
  'errori.definizione-multipla.frase-2': 'um nome',
  'errori.definizione-multipla.frase': `{nome} está definido duas vezes no programa`,
  'errori.definizione-multipla.dove-2': 'este nome',
  'errori.definizione-multipla.dove': `Procure {nome} em todos os arquivos do projeto. Muitas vezes é uma variável ou uma função escrita dentro de um arquivo \`.h\` incluído por vários arquivos \`.c\`, ou um arquivo \`.c\` incluído com \`#include\`.`,
  'errori.definizione-multipla.cosa': 'Cada função e cada variável global precisa ter uma só definição no programa inteiro. Nos arquivos `.h` vão só os protótipos (e as variáveis com `extern`); os corpos das funções vão nos `.c`. Um arquivo `.c` não se inclui com `#include`.',
  'errori.definizione-multipla.concetto': 'arquivos .h e .c',
  'errori.tipi-in-conflitto.etichetta': 'declarações diferentes',
  'errori.tipi-in-conflitto.frase-2': 'uma função',
  'errori.tipi-in-conflitto.frase': `{nome} está declarada de dois jeitos diferentes`,
  'errori.tipi-in-conflitto.dove-3': ` (linha {prima})`,
  'errori.tipi-in-conflitto.dove': `Compare a linha {riga} com a declaração anterior{prima}: o tipo de retorno e os parâmetros precisam ser idênticos.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Compare a linha indicada com a declaração anterior{prima}: o tipo de retorno e os parâmetros precisam ser idênticos.`,
  'errori.tipi-in-conflitto.dove-5': 'a função',
  'errori.tipi-in-conflitto.dove-4': ` A primeira declaração aqui é implícita: você chamou {nome} antes de declarar. Coloque o protótipo acima do \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'O protótipo (a linha com `;`, normalmente no topo ou num `.h`) e a função de verdade precisam dizer as mesmas coisas: mesmo tipo de retorno, mesmos tipos de parâmetros, na mesma ordem.',
  'errori.tipi-in-conflitto.concetto': 'protótipos das funções',
  'errori.argomenti.etichetta': 'número errado de argumentos',
  'errori.argomenti.frase': ` ({h} em vez de {e})`,
  'errori.argomenti.frase-2': `você passa menos argumentos do que a função pede{quanti}`,
  'errori.argomenti.frase-3': `você passa mais argumentos do que a função pede{quanti}`,
  'errori.argomenti.frase-5': 'esta função',
  'errori.argomenti.frase-4': `a chamada para {nome} não corresponde aos parâmetros dela`,
  'errori.argomenti.dove-2': ` (linha {dich})`,
  'errori.argomenti.dove': `Compare a chamada {allaRiga} com a primeira linha da função{nome}{dich}: conte os argumentos e veja os tipos deles.`,
  'errori.argomenti.cosa': 'Uma função precisa ser chamada com tantos argumentos quantos são os parâmetros dela, na mesma ordem. Se a função é `int soma(int a, int b)`, a chamada é `soma(x, y)`.',
  'errori.argomenti.concetto': 'parâmetros das funções',
  'errori.graffa.etichetta': 'chave faltando',
  'errori.graffa.frase': 'tem uma `}` sobrando',
  'errori.graffa.frase-2': 'falta uma `}`',
  'errori.graffa.dove': `Olhe a \`}\` {allaRiga}: ela fecha um bloco que já estava fechado. Conte as \`{\` e as \`}\` acima.`,
  'errori.graffa.dove-3': ` (linha {riga})`,
  'errori.graffa.dove-4': ` A \`{\` que ficou aberta está na linha {aperta}.`,
  'errori.graffa.dove-2': `O compilador só percebe no fim{riga}, mas a chave falta antes.{aperta} Conte as \`{\` e as \`}\` de cada função, de cada \`if\` e de cada laço.`,
  'errori.graffa.cosa': 'Cada `{` abre um bloco e cada `}` fecha: elas precisam estar em pares. Com o código bem indentado (cada bloco um pouco mais para a direita) a chave que falta aparece na hora.',
  'errori.graffa.concetto': 'blocos e chaves',
  'errori.parentesi.etichetta': 'parêntese faltando',
  'errori.parentesi.frase': 'falta um `)`',
  'errori.parentesi.dove-2': `, coluna {apertaCol}`,
  'errori.parentesi.dove': `O \`(\` que ficou aberto está na linha {aperta}{apertaCol}: o \`)\` dele falta antes do ponto indicado {allaRiga}.`,
  'errori.parentesi.dove-3': `Olhe a linha {riga} e conte os \`(\` e os \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Olhe a linha indicada e conte os \`(\` e os \`)\`.`,
  'errori.parentesi.cosa': 'Cada `(` precisa do seu `)`. Em condições longas e em chamadas dentro de outras chamadas é fácil perder um: conte da esquerda para a direita.',
  'errori.parentesi.concetto': 'parênteses',
  'errori.espressione-attesa.etichetta': 'falta um valor',
  'errori.espressione-attesa.frase': 'o compilador esperava um valor e não achou',
  'errori.espressione-attesa.dove': `Olhe {laRiga}{colonna}: ali falta alguma coisa (um número, uma variável) ou tem um símbolo sobrando. Acontece também com aspas não fechadas na mesma linha.`,
  'errori.espressione-attesa.cosa': 'Depois de um `=`, de um operador como `+` ou de uma vírgula, o compilador espera um valor. Se encontra logo `;`, `)` ou outro símbolo, ele para.',
  'errori.espressione-attesa.concetto': 'expressões',
  'errori.ridefinizione.etichetta': 'declarado duas vezes',
  'errori.ridefinizione.breve-2': 'nome',
  'errori.ridefinizione.breve': `{nome} declarado duas vezes`,
  'errori.ridefinizione.frase-2': 'um nome',
  'errori.ridefinizione.frase': `{nome} está declarado duas vezes`,
  'errori.ridefinizione.dove': `As duas declarações estão na linha {prima} e na linha {riga}.`,
  'errori.ridefinizione.dove-4': 'este nome',
  'errori.ridefinizione.dove-2': `Procure acima da linha {riga} outro lugar onde {nome} é declarado.`,
  'errori.ridefinizione.dove-2-senza-riga': `Procure acima da linha indicada outro lugar onde {nome} é declarado.`,
  'errori.ridefinizione.cosa': 'No mesmo bloco um nome se declara uma vez só. Se você só quer mudar o valor, escreva `x = 2;` sem o tipo na frente.',
  'errori.ridefinizione.concetto': 'declaração das variáveis',
  'errori.non-array.etichetta': '`[ ]` em algo que não é array',
  'errori.non-array.frase': 'você usa `[ ]` em algo que não é um array',
  'errori.non-array.dove': `Olhe os colchetes {allaRiga}{colonna}.`,
  'errori.non-array.cosa': 'Os colchetes servem para pegar um elemento de um array (ou de um ponteiro). Uma variável simples, como um `int`, não tem elementos. Talvez você quisesse usar outra variável, ou declarar ela como array, por exemplo `int v[10];`.',
  'errori.non-array.concetto': 'arrays',
  'errori.freccia-punto.etichetta': '`.` e `->` trocados',
  'errori.freccia-punto.frase': 'com uma struct (não um ponteiro) se usa `.`, não `->`',
  'errori.freccia-punto.frase-2': 'com um ponteiro para struct se usa `->`, não `.`',
  'errori.freccia-punto.frase-3': 'o campo da struct é acessado do jeito errado',
  'errori.freccia-punto.dove': `Olhe {laRiga}{colonna}: confira como está declarada a variável antes do ponto ou da seta.`,
  'errori.freccia-punto.cosa': 'Se você tem a própria struct (`struct nodo n`), o campo se acessa com o ponto: `n.val`. Se tem um ponteiro para a struct (`struct nodo *p`), se usa a seta: `p->val`, que quer dizer `(*p).val`.',
  'errori.freccia-punto.concetto': 'structs e ponteiros',
  'errori.membro-inesistente.etichetta': 'campo que não existe',
  'errori.membro-inesistente.frase-2': 'a struct',
  'errori.membro-inesistente.frase': `{p} não tem um campo {m}`,
  'errori.membro-inesistente.frase-3': 'a struct não tem esse campo',
  'errori.membro-inesistente.dove-2': ` com {m}`,
  'errori.membro-inesistente.dove': `Olhe a definição da struct{p} e compare os nomes dos campos{m}.`,
  'errori.membro-inesistente.cosa': 'Os campos de uma struct são os que estão escritos na definição dela, com esses nomes exatos. Um nome diferente, mesmo que seja só uma letra, é outro campo.',
  'errori.membro-inesistente.concetto': 'structs',
  'errori.header-non-trovato.etichetta': 'header não encontrado',
  'errori.header-non-trovato.frase-2': 'incluído',
  'errori.header-non-trovato.frase': `não acho o arquivo {h}`,
  'errori.header-non-trovato.dove': `Olhe a linha \`#include\` {allaRiga}.`,
  'errori.header-non-trovato.dove-2': ` Talvez você quisesse {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` só existe em alguns compiladores antigos para Windows (Turbo C, Dev-C++): não faz parte do C padrão.',
  'errori.header-non-trovato.cosa': 'Com `#include {sistema}` o compilador procura o arquivo entre os do sistema; com `#include {progetto}` procura primeiro na pasta do projeto. Se o nome está errado, mesmo que seja numa letra, ele não acha e para na hora.',
  'errori.header-non-trovato.concetto': 'bibliotecas e #include',
  'errori.file-sorgente-mancante.etichetta': 'arquivo não encontrado',
  'errori.file-sorgente-mancante.frase-2': 'indicado',
  'errori.file-sorgente-mancante.frase': `o compilador não acha o arquivo {h}`,
  'errori.file-sorgente-mancante.dove': 'Olhe o comando de compilação e os nomes dos arquivos na pasta.',
  'errori.file-sorgente-mancante.cosa': 'O comando cita um arquivo que não está na pasta. Confira o nome (maiúsculas, extensão `.c`) e se o comando roda a partir da pasta certa.',
  'errori.file-sorgente-mancante.concetto': 'compilação',
  'errori.non-assegnabile.etichetta': 'atribuição impossível',
  'errori.non-assegnabile.frase': 'você não pode copiar um array (ou uma string) com `=`',
  'errori.non-assegnabile.frase-2': 'à esquerda do `=` tem algo que não é uma variável',
  'errori.non-assegnabile.dove': `Olhe o que está à esquerda do \`=\` {allaRiga}.`,
  'errori.non-assegnabile.cosa': 'Um array não se copia com `=`. Para uma string use `strcpy(destino, "texto");` de `{h}`, ou dê o valor na declaração: `char nome[10] = "texto";`.',
  'errori.non-assegnabile.cosa-2': 'À esquerda do `=` precisa ter um lugar onde colocar o valor: uma variável, um elemento de array, um campo. Não uma conta como `a + 1`. Se você queria comparar, precisa de `==`.',
  'errori.non-assegnabile.concetto': 'atribuição',
  'errori.tipo-sconosciuto.etichetta': 'tipo desconhecido',
  'errori.tipo-sconosciuto.frase-2': 'este nome',
  'errori.tipo-sconosciuto.frase': `{nome} não é um tipo que o compilador conhece`,
  'errori.tipo-sconosciuto.dove-2': 'o tipo',
  'errori.tipo-sconosciuto.dove': `Olhe {laRiga} e procure acima onde você define {nome}.`,
  'errori.tipo-sconosciuto.cosa': 'Em C o tipo `string` não existe (existe em C++ e em outras linguagens). Uma string em C é um array de `char`: `char s[50];` ou `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Antes de usar um tipo como `Nodo` você precisa definir, por exemplo com `typedef struct nodo Nodo;`, acima da linha que o usa. Confira também maiúsculas e minúsculas.',
  'errori.tipo-sconosciuto.concetto': 'tipos e typedef',
  'errori.virgolette.etichetta': 'string não fechada',
  'errori.virgolette.frase': 'uma string não está fechada: falta `"`',
  'errori.virgolette.dove': `Olhe {laRiga}{colonna}: dali começa a string. Procure onde ela deveria terminar.`,
  'errori.virgolette.cosa': 'Uma string começa e termina com `"` na mesma linha. Se falta a de fechamento, o compilador considera string todo o resto da linha e depois se perde: por isso os erros que vêm depois muitas vezes somem sozinhos.',
  'errori.virgolette.concetto': 'strings',
  'errori.if-vuoto.etichetta': '`;` depois da condição',
  'errori.if-vuoto.frase': `tem um \`;\` logo depois do \`{kw}\``,
  'errori.if-vuoto.frase-2': `tem um \`;\` logo depois da condição {if}`,
  'errori.if-vuoto.dove': `Olhe a linha {riga}: logo depois do \`{kw}\` tem um \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Olhe a linha indicada: logo depois do \`{kw}\` tem um \`;\`.`,
  'errori.if-vuoto.dove-3': `Olhe o fim da linha {riga}: depois do \`)\` da condição tem um \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Olhe o fim da linha indicada: depois do \`)\` da condição tem um \`;\`.`,
  'errori.if-vuoto.cosa': 'O `;` logo depois do `else` é uma instrução vazia: o `else` só comanda ela. O bloco `{ }` abaixo é executado sempre, mesmo quando a condição do `if` é verdadeira.',
  'errori.if-vuoto.cosa-2': 'O `;` logo depois do `do` é uma instrução vazia: o laço repete só ela. O bloco `{ }` abaixo não faz parte do laço.',
  'errori.if-vuoto.cosa-3': 'O `;` logo depois de `if (...)` é uma instrução vazia: o `if` controla só ela. O bloco `{ }` abaixo é executado sempre, seja qual for a condição. Com `while` é pior: o laço pode nunca terminar.',
  'errori.if-vuoto.concetto': 'if e laços',
  'errori.confronto-inutile.etichetta': 'instrução que não faz nada',
  'errori.confronto-inutile.frase': 'tem um `==` que não faz nada: talvez você quisesse `=`',
  'errori.confronto-inutile.frase-2': 'esta instrução não faz nada',
  'errori.confronto-inutile.dove': `Olhe {laRiga}{colonna}.`,
  'errori.confronto-inutile.cosa': 'Uma comparação sozinha (`x == 4;`) calcula verdadeiro ou falso e joga o resultado fora. Se você queria dar um valor à variável, precisa de um `=` só: `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'Uma conta que não é guardada numa variável, nem impressa, nem usada numa condição, é jogada fora. Talvez falte um `=` ou uma chamada de função.',
  'errori.confronto-inutile.concetto': 'atribuição e comparação',
  'errori.indirizzo-locale.etichetta': 'endereço de uma variável local',
  'errori.indirizzo-locale.frase-2': 'uma variável local',
  'errori.indirizzo-locale.frase': `você retorna o endereço de {nome}, que some quando a função termina`,
  'errori.indirizzo-locale.dove': `Olhe o \`return\` {allaRiga}.`,
  'errori.indirizzo-locale.cosa': 'As variáveis locais só vivem enquanto a função está rodando. Retornar o endereço delas é dar a quem chama um lugar de memória que não existe mais. Se você precisa retornar um array, crie com `malloc` (e depois lembre do `free`), ou receba ele como parâmetro.',
  'errori.indirizzo-locale.concetto': 'memória e funções',
  'errori.segni-diversi.etichetta': 'números com e sem sinal',
  'errori.segni-diversi.frase': 'você compara um número com sinal e um sem sinal',
  'errori.segni-diversi.dove': `Olhe a comparação {allaRiga}.`,
  'errori.segni-diversi.cosa': 'Funções como `strlen` retornam um número sem sinal (`size_t`). Comparar com um `int` normalmente funciona, mas se o `int` é negativo a comparação erra. É um aviso: você pode declarar o índice como `size_t`, ou guardar o tamanho num `int` antes do laço.',
  'errori.segni-diversi.concetto': 'tipos inteiros',
  'errori.return-void.etichetta': '`return` e `void` em conflito',
  'errori.return-void.frase': '`return;` sem valor numa função que precisa retornar um',
  'errori.return-void.frase-2': 'uma função `void` não pode retornar um valor',
  'errori.return-void.dove': `Olhe o \`return\` {allaRiga} e a primeira linha da função.`,
  'errori.return-void.cosa': '`void` quer dizer que a função não retorna nada: ali se escreve só `return;` (ou nada). Se a função precisa dar um resultado, no lugar de `void` vai o tipo certo, por exemplo `int`, e cada `return` precisa ter um valor.',
  'errori.return-void.concetto': 'return nas funções',
  'errori.main-int.etichetta': '`main` que não é `int`',
  'errori.main-int.frase': 'o `main` precisa retornar `int`',
  'errori.main-int.dove-2': ` (linha {riga})`,
  'errori.main-int.dove': `Olhe a linha do \`main\`{riga}.`,
  'errori.main-int.cosa': 'O padrão do C pede `int main(void)`, e no fim `return 0;` para dizer «tudo certo». `void main` só alguns compiladores antigos aceitam.',
  'errori.main-int.concetto': 'a função main',
  'errori.fuori-array.etichetta': 'índice fora do array',
  'errori.fuori-array.frase': `você usa o índice {i}, mas o array não vai até ali`,
  'errori.fuori-array.frase-2': 'você usa um índice fora do array',
  'errori.fuori-array.dove-2': ` e a declaração do array na linha {riga}`,
  'errori.fuori-array.dove': `Olhe {laRiga}{riga}.`,
  'errori.fuori-array.cosa': 'Um array de N elementos tem índices de `0` a `N-1`: com `int v[5]` o último é `v[4]`, e `v[5]` já está fora. Acontece muito com um laço `for (i = 0; i <= 5; i++)` em vez de `i < 5`.',
  'errori.fuori-array.concetto': 'arrays e índices',
  'errori.argomenti-formato.etichetta': '`%` e valores não batem',
  'errori.argomenti-formato.frase': 'na string tem mais `%` do que valores',
  'errori.argomenti-formato.frase-2': 'você passa mais valores do que os `%` da string',
  'errori.argomenti-formato.dove': `Olhe a string {allaRiga} e conte os \`%\` e os valores depois da vírgula.`,
  'errori.argomenti-formato.cosa': 'Cada `%d`, `%f`, `%c`… na string do `printf` (ou do `scanf`) pega o valor seguinte, na ordem. O número de `%` e o número de valores depois da string precisam ser iguais.',
  'errori.argomenti-formato.concetto': 'printf e os formatos',
  'errori.divisione-zero.etichetta': 'divisão por zero',
  'errori.divisione-zero.frase': 'você divide por zero',
  'errori.divisione-zero.dove': `Olhe a divisão {allaRiga}.`,
  'errori.divisione-zero.cosa': 'Dividir um inteiro por zero não tem resultado: normalmente o programa trava. Antes de dividir, confira se o divisor não é zero, por exemplo com `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'divisão',
  'errori.troppi-inizializzatori.etichetta': 'valores demais no array',
  'errori.troppi-inizializzatori.frase': 'você coloca mais valores do que o array consegue guardar',
  'errori.troppi-inizializzatori.dove': `Olhe a declaração {allaRiga}: compare o tamanho entre \`[ ]\` com quantos valores tem entre \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'Se um array tem espaço para 2 valores e entre as chaves você escreve 3, o terceiro é jogado fora. Aumente o tamanho ou tire valores. Você também pode deixar os colchetes vazios, `int v[] = {1, 2, 3};`, e o compilador conta sozinho.',
  'errori.troppi-inizializzatori.concetto': 'arrays',
  'errori.operandi.etichetta': 'operação impossível entre esses tipos',
  'errori.operandi.frase': `a operação não pode ser feita entre {a} e {b}`,
  'errori.operandi.frase-2': 'a operação não pode ser feita entre esses dois tipos',
  'errori.operandi.dove': `Olhe o operador {allaRiga}{colonna} e os tipos dos dois lados.`,
  'errori.operandi.cosa': 'Operadores como `&&`, `+` ou `<` pedem tipos precisos: `&&` trabalha com `boolean`, `<` com números. Strings não se comparam com `<`: se usa `compareTo`, e para igualdade `equals`.',
  'errori.operandi.cosa-2': 'Operadores como `+`, `-` e `<` funcionam com números (e alguns com ponteiros). Duas structs não se somam nem se comparam diretamente: trabalhe com os campos delas, por exemplo `a.x + b.x`. Em C as strings não se juntam com `+`: se usa `strcat`.',
  'errori.operandi.concetto': 'tipos e operadores',
  'errori.carattere-strano.etichetta': 'caractere estranho no código',
  'errori.carattere-strano.frase': 'tem um caractere estranho no código',
  'errori.carattere-strano.dove': `Olhe {laRiga}{colonna}.`,
  'errori.carattere-strano.cosa': 'Muitas vezes é um caractere copiado de um PDF ou de uma página da web: aspas curvas `“ ”`, um apóstrofo curvo, um espaço especial ou um travessão. A olho parecem iguais, mas para o compilador não são. Reescreva a linha à mão.',
  'errori.carattere-strano.concetto': 'caracteres no código',
  'errori.non-sicura.etichetta': 'Visual Studio e as funções «não seguras»',
  'errori.non-sicura.frase-2': 'esta função',
  'errori.non-sicura.frase': `o Visual Studio não aceita {nome}: considera não segura`,
  'errori.non-sicura.dove': 'Não tem nada de errado no seu C: é uma regra do Visual Studio.',
  'errori.non-sicura.cosa': 'O Visual Studio aponta `scanf`, `strcpy` e parecidas porque, mal usadas, podem escrever depois do fim de um array. O C padrão permite e as disciplinas usam. Para desligar o aviso, escreva `#define _CRT_SECURE_NO_WARNINGS` como a primeiríssima linha do arquivo, antes dos `#include`. Se o professor prefere `scanf_s`, siga o professor.',
  'errori.non-sicura.concetto': 'compiladores diferentes',
  'errori.ricorsione-infinita.etichetta': 'recursão sem fim',
  'errori.ricorsione-infinita.frase': 'a função sempre chama a si mesma: nunca para',
  'errori.ricorsione-infinita.dove': `Olhe a função{p} {allaRiga}: procure o caso base, ou seja, um \`if\` que retorna um valor sem chamar a função de novo.`,
  'errori.ricorsione-infinita.cosa': 'Uma função recursiva precisa ter um caso base, e cada chamada precisa se aproximar desse caso (por exemplo com `n - 1`). Aqui todo caminho leva a outra chamada: o programa vai encher a memória e parar.',
  'errori.ricorsione-infinita.concetto': 'recursão',
  'errori.sintassi.etichetta': 'código escrito de um jeito que o compilador não entende',
  'errori.sintassi.frase': 'o compilador não entende como o código continua aqui',
  'errori.sintassi.dove': `Olhe {laRiga} e a anterior: muitas vezes o problema de verdade está logo acima, por exemplo um \`;\` sobrando depois da primeira linha de uma função, uma \`}\` a mais ou um parêntese não fechado.`,
  'errori.sintassi.cosa': 'O compilador lê o código seguindo regras precisas, como a gramática de uma língua. Aqui ele achou algo que não pode estar naquele lugar. A mensagem original diz o que ele esperava.',
  'errori.sintassi.concetto': 'sintaxe',
  'errori.java-tipi.etichetta': 'tipos incompatíveis (Java)',
  'errori.java-tipi.frase': `de {dato} para {atteso} você pode perder dados`,
  'errori.java-tipi.frase-2': `{dato} não pode ser usado onde precisa de {atteso}`,
  'errori.java-tipi.frase-3': 'o valor não tem o tipo necessário',
  'errori.java-tipi.dove': `Olhe {laRiga}{colonna}: compare o tipo da variável com o do valor.`,
  'errori.java-tipi.cosa': 'Em Java cada variável tem um tipo e o compilador confere se os valores correspondem. De `double` para `int` se perdem as casas decimais, então é preciso dizer isso explicitamente com um cast: `(int) x`. Uma `String` não vira número sozinha: se usa `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'tipos em Java',
  'errori.java-import.etichetta': 'falta um `import` (Java)',
  'errori.java-import.frase-2': 'esta classe',
  'errori.java-import.frase': `para usar {nome} falta um \`import\``,
  'errori.java-import.dove': 'Olhe no topo do arquivo, acima da classe, onde ficam as linhas `import`.',
  'errori.java-import.cosa-2': 'Esta classe',
  'errori.java-import.cosa-3': `, ou seja, \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} está num pacote da biblioteca do Java: para usar, precisa do \`import\` no topo do arquivo{nome2}. Confira também maiúsculas e minúsculas.`,
  'errori.java-import.concetto': 'import em Java',
  'errori.java-nome-file.etichetta': 'nome do arquivo e da classe diferentes',
  'errori.java-nome-file.frase-2': 'pública',
  'errori.java-nome-file.frase-3': 'Classe',
  'errori.java-nome-file.frase': `a classe {nome} precisa ficar no arquivo {nome2}`,
  'errori.java-nome-file.dove': 'Olhe o nome do arquivo e a linha `public class`.',
  'errori.java-nome-file.cosa': 'Em Java uma classe `public` precisa ficar num arquivo com o mesmo nome, maiúsculas também: `public class Main` vai em `Main.java`. Renomeie o arquivo ou a classe.',
  'errori.java-nome-file.concetto': 'classes e arquivos em Java',
  'errori.java-statico.etichetta': 'não static usado a partir de static',
  'errori.java-statico.frase-2': 'este nome',
  'errori.java-statico.frase': `{nome} não é \`static\`, mas você usa a partir de um método \`static\``,
  'errori.java-statico.dove-2': 'esse nome',
  'errori.java-statico.dove': `Olhe {laRiga} e onde {nome} é declarado.`,
  'errori.java-statico.cosa': 'O `main` é `static`: pertence à classe, não a um objeto. De lá você só pode usar métodos e variáveis `static`, ou criar antes um objeto com `new` e usar ele. Nos exercícios com uma classe só, muitas vezes falta o `static` no método.',
  'errori.java-statico.concetto': 'static em Java',
  'errori.java-irraggiungibile.etichetta': 'instrução nunca executada',
  'errori.java-irraggiungibile.frase': 'esta instrução nunca vai ser executada',
  'errori.java-irraggiungibile.dove': `Olhe {laRiga} e a linha anterior.`,
  'errori.java-irraggiungibile.cosa': 'Antes desta linha tem um `return`, um `break`, um `continue` ou um laço que não termina: dali o programa nunca chega aqui. Tire a linha ou mova para antes.',
  'errori.java-irraggiungibile.concetto': 'fluxo do programa',
  'errori.java-indice.etichetta': 'índice fora (Java)',
  'errori.java-indice.frase': `você usa o índice {i}, mas o tamanho é {l}`,
  'errori.java-indice.frase-2': 'você lê uma posição que o array (ou a string) não tem',
  'errori.java-indice.cosa': 'Os índices começam em 0: com tamanho 5 vão de 0 a 4. Confira a condição do laço: muitas vezes tem `<=` onde precisa de `<`, ou se usa `length` como índice.',
  'errori.java-indice.concetto': 'arrays e índices',
  'errori.java-null.etichetta': 'objeto null (Java)',
  'errori.java-null.frase': 'você usa um objeto que vale `null`',
  'errori.java-null.cosa': 'O objeto nunca foi criado com `new`, ou um método retornou `null`. As versões recentes do Java escrevem na mensagem qual variável era `null`.',
  'errori.java-null.concetto': 'objetos e null',
  'errori.java-divisione-zero.etichetta': 'divisão por zero (Java)',
  'errori.java-divisione-zero.frase': 'você divide um inteiro por zero',
  'errori.java-divisione-zero.cosa': 'Dividir um inteiro por zero (também com `%`) não tem resultado e o Java para. Antes da divisão confira o divisor, por exemplo com `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'divisão',
  'errori.java-input.etichetta': 'entrada que não é número (Java)',
  'errori.java-input.frase': `{v} não é um número`,
  'errori.java-input.frase-2': 'o programa esperava um número e leu outra coisa',
  'errori.java-input.cosa': 'O programa queria um número e achou outra coisa: letras, espaços, uma linha vazia, ou uma vírgula no lugar do ponto. Confira o que você digita na entrada, ou o arquivo `.in` do teste.',
  'errori.java-input.concetto': 'entrada',
  'errori.java-stack.etichetta': 'recursão sem fim (Java)',
  'errori.java-stack.frase': 'o método chama a si mesmo vezes demais',
  'errori.java-stack.cosa': 'Todo método recursivo precisa de um caso base: uma condição em que ele retorna um valor sem chamar a si mesmo. E cada chamada precisa se aproximar do caso base.',
  'errori.java-stack.concetto': 'recursão',
  'errori.py-uguale.etichetta': '`=` no lugar de `==`',
  'errori.py-uguale.breve': '= no lugar de ==',
  'errori.py-uguale.frase': 'na condição tem `=` em vez de `==`',
  'errori.py-uguale.dove': `Olhe a condição {allaRiga}.`,
  'errori.py-uguale.cosa': '`=` coloca um valor numa variável; `==` confere se dois valores são iguais. Numa condição (`if`, `elif`, `while`) precisa de `==`: `if x == 5:`.',
  'errori.py-uguale.concetto': 'atribuição e comparação',
  'errori.py-due-punti.etichetta': 'faltam os `:`',
  'errori.py-due-punti.frase': 'faltam os `:` no fim da linha',
  'errori.py-due-punti.dove': `Olhe o fim da linha {riga}.`,
  'errori.py-due-punti.dove-senza-riga': `Olhe o fim da linha indicada.`,
  'errori.py-due-punti.cosa': 'Em Python `if`, `elif`, `else`, `for`, `while`, `def` e `class` terminam com `:`. Os dois-pontos dizem «agora começa o bloco», que se escreve embaixo, com recuo.',
  'errori.py-due-punti.concetto': 'blocos em Python',
  'errori.py-parentesi.etichetta': 'parêntese não fechado',
  'errori.py-parentesi.frase': `tem um {c} que não fecha nada`,
  'errori.py-parentesi.frase-2': `um {p} não está fechado`,
  'errori.py-parentesi.dove': `Olhe {laRiga}: conte os parênteses abertos e fechados. Se a linha parece certa, olhe a anterior.`,
  'errori.py-parentesi.cosa': 'Cada `(`, `[` e `{` precisa do seu fechamento do mesmo tipo. Se falta um, o Python continua lendo as linhas seguintes como se fossem a mesma instrução.',
  'errori.py-parentesi.concetto': 'parênteses',
  'errori.py-stringa.etichetta': 'string não fechada',
  'errori.py-stringa.frase': 'uma string não está fechada',
  'errori.py-stringa.dove': `Olhe {laRiga}: a string começa ali. Procure onde falta a aspa de fechamento.`,
  'errori.py-stringa.cosa': 'Uma string começa e termina com o mesmo tipo de aspas, `"` ou `\'`, na mesma linha. Se dentro do texto tem um apóstrofo, use aspas duplas: `"d\'água"`.',
  'errori.py-stringa.concetto': 'strings',
  'errori.py-print.etichetta': '`print` sem parênteses',
  'errori.py-print.frase': 'o `print` precisa de parênteses',
  'errori.py-print.dove': `Olhe {laRiga}.`,
  'errori.py-print.cosa': 'No Python 3 o `print` é uma função: se escreve `print("oi")`. A forma sem parênteses era do Python 2, que ainda aparece em exemplos antigos na internet.',
  'errori.py-print.concetto': 'funções',
  'errori.py-indentazione.etichetta': 'recuo errado',
  'errori.py-indentazione.frase': 'falta o recuo depois dos dois-pontos',
  'errori.py-indentazione.frase-2': 'tem um recuo sobrando',
  'errori.py-indentazione.frase-3': 'o recuo não bate com as linhas de cima',
  'errori.py-indentazione.frase-4': 'você mistura tabs e espaços no recuo',
  'errori.py-indentazione.frase-5': 'o recuo da linha está errado',
  'errori.py-indentazione.dove-2': ` O \`{kw}\` está na linha {l}.`,
  'errori.py-indentazione.dove': `Olhe {laRiga} e a de cima: compare os espaços no começo da linha.{kw}`,
  'errori.py-indentazione.cosa': 'Em Python o recuo (os espaços no começo da linha) faz parte do código: diz quais linhas estão dentro de um `if`, de um `for` ou de uma `def`. Depois dos `:` a linha de baixo precisa ter recuo, e as linhas do mesmo bloco precisam ter o mesmo recuo. Use sempre 4 espaços, sem misturar com tabs.',
  'errori.py-indentazione.concetto': 'blocos em Python',
  'errori.py-sintassi.etichetta': 'linha que o Python não sabe ler',
  'errori.py-sintassi.frase': 'talvez falte uma vírgula',
  'errori.py-sintassi.frase-2': 'o Python não consegue ler esta linha',
  'errori.py-sintassi.dove': `Olhe {laRiga}: o sinal \`^\` embaixo da linha mostra onde o Python percebeu o problema. Muitas vezes o erro de verdade está logo antes, até na linha de cima (um parêntese ou uma aspa não fechada).`,
  'errori.py-sintassi.cosa': 'Entre dois valores de uma lista, de uma tupla ou dos argumentos de uma função precisa de vírgula: `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'O Python lê o código seguindo regras precisas, como a gramática de uma língua. Aqui ele achou algo que não pode estar naquele lugar. A mensagem original, depois de `SyntaxError:`, diz o que não bate.',
  'errori.py-sintassi.concetto': 'sintaxe',
  'errori.py-nome.etichetta': 'nome que não existe',
  'errori.py-nome.breve-2': 'nome',
  'errori.py-nome.breve': `{nome} não definido`,
  'errori.py-nome.frase-2': 'este nome',
  'errori.py-nome.frase': `{nome} ainda não existe quando o Python chega na linha {riga}`,
  'errori.py-nome.frase-senza-riga': `{nome} ainda não existe quando o Python chega na linha indicada`,
  'errori.py-nome.dove': `O Python sugere {s}: veja se você queria escrever isso. `,
  'errori.py-nome.dove-3': 'este nome',
  'errori.py-nome.dove-2': `Procure onde você dá um valor a {nome}: precisa estar acima desta linha e escrito igual, maiúsculas também. Se é uma função, a \`def\` precisa vir antes da chamada.`,
  'errori.py-nome.cosa': 'Em Python um nome só existe depois que você dá um valor a ele (`x = ...`), depois da `def` dele ou depois do `import`. As variáveis criadas dentro de uma função não existem fora.',
  'errori.py-nome.cosa-2': ' Cuidado: em Python se escreve `True`, `False` e `None`, com maiúscula.',
  'errori.py-nome.cosa-3': ` Se {nome} era para ser um texto, faltam as aspas: {nome2}.`,
  'errori.py-nome.concetto': 'variáveis em Python',
  'errori.py-locale.etichetta': 'variável local sem valor',
  'errori.py-locale.frase-2': 'uma variável',
  'errori.py-locale.frase': `você usa {nome} dentro da função antes de dar um valor a ela`,
  'errori.py-locale.dove-2': 'a variável',
  'errori.py-locale.dove': `Olhe {laRiga} e procure, na mesma função, onde você atribui {nome}.`,
  'errori.py-locale.cosa': 'Se dentro de uma função você atribui um valor a uma variável, para o Python ela vira local na função inteira, até nas linhas de antes. Assim ele não lê mais a variável de mesmo nome que está fora. É melhor passar o valor como parâmetro e retornar o resultado com `return`.',
  'errori.py-locale.concetto': 'funções e variáveis locais',
  'errori.py-tipo-concatena.etichetta': 'texto e número misturados',
  'errori.py-tipo-concatena.frase': 'você mistura um texto (`str`) e um número',
  'errori.py-tipo-concatena.frase-2': `a operação não pode ser feita entre {a} e {b}`,
  'errori.py-tipo-concatena.dove': `Olhe {laRiga}: de que tipo é cada valor perto do operador?`,
  'errori.py-tipo-concatena.cosa': 'Para o Python `"5"` (texto) e `5` (número) são coisas diferentes. Para juntar texto e número, converta o número: `"Total: " + str(x)`, ou use uma f-string: `f"Total: {x}"`. Se o valor vem de `input()`, lembre que `input()` sempre retorna texto: para fazer contas você precisa de `int(input())` ou `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'tipos em Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` usados errado',
  'errori.py-tipo-indice.frase': 'o índice precisa ser um número inteiro',
  'errori.py-tipo-indice.frase-2': `um valor \`{immut}\` não pode ser modificado`,
  'errori.py-tipo-indice.frase-3': 'você usa `[ ]` num valor `None`',
  'errori.py-tipo-indice.frase-4': `você usa \`[ ]\` num valor do tipo {p}, que não tem elementos`,
  'errori.py-tipo-indice.dove': `Olhe os colchetes {allaRiga}.`,
  'errori.py-tipo-indice.cosa': 'Com `v[i]` o `i` precisa ser um `int`. Se vem de `input()` é texto: converta com `int()`. Se nasce de uma divisão com `/` é um `float`: use `//`.',
  'errori.py-tipo-indice.cosa-2': 'Strings e tuplas em Python não mudam: você cria um valor novo, por exemplo `s = "C" + s[1:]`. Se precisa modificar os elementos, use uma lista.',
  'errori.py-tipo-indice.cosa-3': 'Os colchetes `[ ]` servem para listas, strings, dicionários e tuplas. Um número não tem elementos. Se o tipo é `NoneType`, a variável vale `None`: muitas vezes é o resultado de uma função sem `return`.',
  'errori.py-tipo-indice.concetto': 'listas e índices',
  'errori.py-tipo-argomenti.etichetta': 'número errado de argumentos',
  'errori.py-tipo-argomenti.frase-2': 'função',
  'errori.py-tipo-argomenti.frase': `{p} é chamada com o número errado de argumentos`,
  'errori.py-tipo-argomenti.dove': `Compare a chamada {allaRiga} com a linha \`def\` da função.`,
  'errori.py-tipo-argomenti.cosa': 'Uma função precisa ser chamada com tantos argumentos quantos são os parâmetros na `def` dela. Nos métodos de uma classe o primeiro parâmetro é `self` e o Python passa ele sozinho: se a mensagem diz «takes 1 positional argument but 2 were given», talvez falte `self` na `def`.',
  'errori.py-tipo-argomenti.concetto': 'funções e parâmetros',
  'errori.py-non-iterabile.etichetta': '`for` num número',
  'errori.py-non-iterabile.frase': `você tenta percorrer um valor do tipo {p}, que não tem elementos`,
  'errori.py-non-iterabile.dove': `Olhe {laRiga}: o que vem depois do \`in\`?`,
  'errori.py-non-iterabile.cosa': 'O `for` percorre os elementos de uma lista, de uma string ou de um `range`. Um número não tem elementos: para repetir n vezes se escreve `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'laços for',
  'errori.py-non-chiamabile.etichetta': '`( )` depois de algo que não é função',
  'errori.py-non-chiamabile.frase': `você coloca \`( )\` depois de um valor do tipo {p}, que não é uma função`,
  'errori.py-non-chiamabile.dove': `Olhe {laRiga}: o que vem logo antes dos parênteses?`,
  'errori.py-non-chiamabile.cosa': 'Os parênteses depois de um nome querem dizer «chame esta função». Muitas vezes uma variável tem o mesmo nome de uma função (por exemplo `sum = 0` e depois `sum(v)`), ou falta um operador: `2(x + 1)` em vez de `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'funções',
  'errori.py-tipo.etichetta': 'tipo errado',
  'errori.py-tipo.frase': 'uma operação recebe um valor do tipo errado',
  'errori.py-tipo.dove': `Olhe {laRiga}: de que tipo são os valores usados? Você pode imprimir com \`print(type(x))\`.`,
  'errori.py-tipo.cosa': 'Cada valor em Python tem um tipo (`int`, `str`, `list`…) e cada operação aceita só alguns tipos. A mensagem original diz quais tipos ela encontrou.',
  'errori.py-tipo.concetto': 'tipos em Python',
  'errori.py-indice.etichetta': 'posição que não existe',
  'errori.py-indice.frase': 'você tira um elemento de uma lista vazia',
  'errori.py-indice.frase-stringa': 'você está lendo uma posição que a string não tem',
  'errori.py-indice.frase-tupla': 'você está lendo uma posição que a tupla não tem',
  'errori.py-indice.frase-lista': 'você está lendo uma posição que a lista não tem',
  'errori.py-indice.dove': `Olhe {laRiga}: quanto vale o índice nesse momento, e quantos elementos existem?`,
  'errori.py-indice.cosa': 'Uma lista de n elementos tem as posições de `0` a `n-1`: com 3 elementos a última é `v[2]`. Acontece muito com `range(len(v) + 1)` ou com um laço que vai um passo além. Uma lista vazia não tem nenhuma posição: até `v[0]` é um erro.',
  'errori.py-indice.concetto': 'listas e índices',
  'errori.py-chiave.etichetta': 'chave que não existe',
  'errori.py-chiave.frase': `a chave {k} não está no dicionário`,
  'errori.py-chiave.frase-2': 'a chave não está no dicionário',
  'errori.py-chiave.dove': `Olhe {laRiga}: como a chave está escrita, e como estão escritas as do dicionário?`,
  'errori.py-chiave.cosa': 'Com `d[k]` a chave já precisa existir. Confira como está escrita (maiúsculas, espaços, número ou texto). Para conferir antes: `if k in d:`. Para ter um valor reserva: `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'dicionários',
  'errori.py-valore.etichetta': 'valor errado',
  'errori.py-valore.frase': `{v} não pode ser transformado em número`,
  'errori.py-valore.frase-2': 'as variáveis à esquerda do `=` não são tantas quanto os valores',
  'errori.py-valore.frase-3': 'uma função matemática recebe um valor que ela não aceita',
  'errori.py-valore.frase-4': 'o tipo está certo, mas o valor não',
  'errori.py-valore.dove': `Olhe {laRiga}: que valor chega ali de verdade? Você pode imprimir com \`print(repr(x))\`.`,
  'errori.py-valore.cosa': '`int()` só transforma em número um texto feito de dígitos. Espaços no meio, letras, o texto vazio ou um número com vírgula (`"2,5"`) não funcionam. Para decimais você precisa de `float()` e do ponto: `"2.5"`. Se você lê de `input()` ou de um arquivo, confira o que chega de verdade.',
  'errori.py-valore.cosa-2': 'Com `a, b = valores` o número de variáveis à esquerda precisa ser igual ao número de valores à direita. Muitas vezes o `split()` retorna mais (ou menos) pedaços do que você esperava.',
  'errori.py-valore.cosa-3': 'Funções como `math.sqrt` e `math.log` não aceitam todos os números: nada de raiz de negativo, nada de logaritmo de zero. Confira o valor antes da chamada.',
  'errori.py-valore.cosa-4': 'O valor tem o tipo certo, mas não serve para essa operação. A mensagem original diz qual valor não serviu.',
  'errori.py-valore.concetto': 'conversões e entrada',
  'errori.py-divisione-zero.etichetta': 'divisão por zero',
  'errori.py-divisione-zero.frase': 'você divide por zero',
  'errori.py-divisione-zero.dove': `Olhe {laRiga}: qual divisor vale 0 nesse momento? Muitas vezes é o \`len()\` de uma lista vazia ou um contador que ficou em 0.`,
  'errori.py-divisione-zero.cosa': 'Dividir por zero não tem resultado, então o Python para. Vale também para `//` e `%`. Antes da divisão confira o divisor: `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'divisão',
  'errori.py-attributo.etichetta': 'método ou atributo que não existe',
  'errori.py-attributo.frase': `a variável vale \`None\`, então não tem {a}`,
  'errori.py-attributo.frase-2': `o módulo {mod} não tem {a}`,
  'errori.py-attributo.frase-3': `um valor do tipo {p} não tem {a}`,
  'errori.py-attributo.frase-4': 'esse valor não tem esse atributo',
  'errori.py-attributo.dove': `Olhe {laRiga}: o que vem antes do ponto, e de que tipo é?`,
  'errori.py-attributo.cosa': 'Um valor `None` normalmente vem de uma função sem `return`, ou de métodos como `v.sort()` que mudam a lista e retornam `None` (então `v = v.sort()` perde a lista).',
  'errori.py-attributo.cosa-2': 'Confira como o nome está escrito. Se o seu arquivo tem o mesmo nome do módulo (por exemplo `random.py` ou `math.py`), o Python importa o seu arquivo no lugar do módulo de verdade: renomeie.',
  'errori.py-attributo.cosa-3': 'Cada tipo tem os seus métodos: listas têm `append`, `pop`, `sort`; strings têm `upper`, `split`, `strip`. Confira o nome do método e o tipo da variável.',
  'errori.py-attributo.concetto': 'métodos e tipos',
  'errori.py-ricorsione.etichetta': 'recursão sem fim',
  'errori.py-ricorsione.frase': 'a função chama a si mesma vezes demais',
  'errori.py-ricorsione.dove': `Olhe a função{funzione} {allaRiga}: onde está o caso base, e cada chamada se aproxima dele?`,
  'errori.py-ricorsione.cosa': 'Toda função recursiva precisa de um caso base: uma condição em que ela retorna um valor sem chamar a si mesma. E cada chamada precisa se aproximar do caso base (por exemplo `n - 1`, não `n + 1`). O Python para depois de umas 1000 chamadas uma dentro da outra.',
  'errori.py-ricorsione.concetto': 'recursão',
  'errori.py-modulo.etichetta': 'módulo que não existe',
  'errori.py-modulo.frase': `no módulo {m} não tem {nome}`,
  'errori.py-modulo.frase-2': `o módulo {m} não existe`,
  'errori.py-modulo.frase-3': 'um módulo não é importado',
  'errori.py-modulo.dove': `Olhe a linha \`import\` {allaRiga}.`,
  'errori.py-modulo.cosa': 'Ou o nome está escrito errado, ou o módulo não está instalado para este Python. Os módulos externos (por exemplo `numpy`) se instalam com `python3 -m pip install nome` (no Windows `py -m pip install nome`). Se o módulo é um arquivo seu, ele precisa estar na mesma pasta e se chamar `nome.py`.',
  'errori.py-modulo.concetto': 'módulos e import',
  'errori.py-file.etichetta': 'arquivo não encontrado',
  'errori.py-file.frase': `não acho o arquivo {p}`,
  'errori.py-file.dove': `Olhe o \`open\` {allaRiga}.`,
  'errori.py-file.cosa': 'O Python procura o arquivo a partir da pasta de onde você roda o programa, não da pasta do script. Confira o nome, a extensão (o Windows às vezes esconde) e a pasta.',
  'errori.py-file.concetto': 'arquivos',
  'errori.py-input-finito.etichetta': 'entrada acabou',
  'errori.py-input-finito.frase': 'o programa pede uma entrada que não chega',
  'errori.py-input-finito.dove': `Olhe o \`input()\` {allaRiga}.`,
  'errori.py-input-finito.cosa': 'O `input()` esperava uma linha, mas a entrada já tinha acabado. Nos testes com arquivos `.in` confira se o arquivo tem tantas linhas quantos são os `input()`.',
  'errori.py-input-finito.concetto': 'entrada',
  'errori.esec-memoria.etichetta': 'memória que não é dele (segmentation fault)',
  'errori.esec-memoria.breve': 'memória que não é dele',
  'errori.esec-memoria.frase': 'o programa usou memória que não é dele',
  'errori.esec-memoria.cosa': 'Aqui o ponteiro valia `NULL`. ',
  'errori.esec-memoria.cosa-2': 'Muitas vezes é um ponteiro `NULL` (`p->next` com `p` valendo `NULL`), um índice fora do array ou uma recursão sem fim. O sistema para o programa para proteger o resto da memória.',
  'errori.esec-memoria.cosa-3': ` No Windows este erro tem o código {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'ponteiros e memória',
  'errori.esec-divisione-zero.etichetta': 'divisão inteira por zero',
  'errori.esec-divisione-zero.frase': 'o programa dividiu um inteiro por zero',
  'errori.esec-divisione-zero.cosa': 'Um inteiro dividido por zero (também com `%`) não tem resultado e o sistema para o programa. O nome «floating point exception» engana: acontece justamente com inteiros. Confira os divisores, por exemplo um contador que ainda vale 0.',
  'errori.esec-divisione-zero.concetto': 'divisão',
  'errori.esec-stack.etichetta': 'pilha de chamadas cheia (stack overflow)',
  'errori.esec-stack.frase': 'a pilha de chamadas está cheia: talvez uma recursão sem fim',
  'errori.esec-stack.cosa': 'Cada chamada de função ocupa um pouco de memória na pilha (a stack). Uma função recursiva sem caso base, ou com um caso base que nunca chega, enche a pilha. Um array local enorme também pode bastar: nesse caso use `malloc`.',
  'errori.esec-stack.concetto': 'recursão',
  'errori.esec-fuori-array.etichetta': 'escrita fora de um array',
  'errori.esec-fuori-array.frase': 'o programa leu ou escreveu fora de um array',
  'errori.esec-fuori-array.frase-letto': 'o programa leu fora de um array',
  'errori.esec-fuori-array.frase-scritto': 'o programa escreveu fora de um array',
  'errori.esec-fuori-array.cosa': 'Um array de N elementos vai de `0` a `N-1`. Confira as condições dos laços (`<` e não `<=`), as strings sem espaço para o `\'\\0\'` final e os `malloc` com o tamanho certo (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'arrays e índices',
  'errori.esec-heap.etichetta': 'malloc e free mal usados',
  'errori.esec-heap.frase': 'a memória pega com `malloc` foi mal usada',
  'errori.esec-heap.cosa': 'Acontece quando você libera a mesma memória duas vezes (`free` duas vezes), quando usa um ponteiro depois do `free`, ou quando escreve depois do fim de um bloco pego com `malloc`. Depois de `free(p);` ajuda escrever `p = NULL;`.',
  'errori.esec-heap.concetto': 'memória dinâmica',
  'errori.esec-memoria-persa.etichetta': 'memória nunca liberada',
  'errori.esec-memoria-persa.frase': 'o programa pega memória com `malloc` e não libera',
  'errori.esec-memoria-persa.cosa': 'Cada `malloc` (ou `calloc`) precisa do seu `free` quando a memória não serve mais. Nas listas cada nó precisa ser liberado, um por vez, antes de perder o ponteiro.',
  'errori.esec-memoria-persa.concetto': 'memória dinâmica',
  'errori.esec-non-inizializzata.etichetta': 'valor nunca inicializado',
  'errori.esec-non-inizializzata.frase': 'o programa usa um valor que nunca foi inicializado',
  'errori.esec-non-inizializzata.cosa': 'Uma variável local (ou a memória pega com `malloc`) tem valores quaisquer até você dar um valor a ela. Inicialize antes de ler.',
  'errori.esec-non-inizializzata.concetto': 'inicialização das variáveis',
  'errori.esec-asserzione.etichetta': 'assert falhou',
  'errori.esec-asserzione.frase': `um \`assert\` falhou: {cond} era falsa`,
  'errori.esec-asserzione.frase-2': 'um `assert` falhou',
  'errori.esec-asserzione.cosa': '`assert(condição)` para o programa se a condição é falsa. Quem escreveu (você ou o professor) está dizendo: «aqui isso precisa ser sempre verdade». O problema de verdade está antes: procure onde o valor ficou errado.',
  'errori.esec-asserzione.concetto': 'assert e verificações',
  'errori.esec-abort.etichetta': 'programa interrompido (abort)',
  'errori.esec-abort.frase': 'o programa se interrompeu sozinho (abort)',
  'errori.esec-abort.cosa': 'Normalmente quem pede é a biblioteca, quando acha um problema grave: um `assert` que falhou, um `free` errado, memória corrompida. Olhe as linhas impressas logo antes: muitas vezes dizem o motivo.',
  'errori.esec-abort.concetto': 'memória dinâmica',
  'errori.esec-overflow.etichetta': 'inteiro grande demais',
  'errori.esec-overflow.frase': 'um inteiro ficou grande demais',
  'errori.esec-overflow.cosa': 'Um `int` vai até 2147483647. Passando disso, o resultado sai errado. Acontece com fatoriais e potências: use `long long` (com `%lld` no `printf`), ou confira as contas.',
  'errori.esec-overflow.concetto': 'tipos inteiros',
  'errori.esec-tempo.etichetta': 'tempo esgotado',
  'errori.esec-tempo.frase': 'o programa não terminou a tempo',
  'errori.esec-tempo.cosa': 'Talvez tenha um laço que não termina: a condição nunca fica falsa, ou a variável do laço não muda. Ou o programa está esperando uma entrada (`scanf`, `input()`) que não chega.',
  'errori.esec-tempo.concetto': 'laços',
  'errori.esec-segnale.etichetta': 'programa parado pelo sistema',
  'errori.esec-segnale.frase': `o programa foi parado pelo sistema{segnale}`,
  'errori.esec-segnale.cosa': 'O sistema parou o programa enquanto ele rodava. O Lode não consegue dizer mais a partir desse sinal: olhe as últimas linhas impressas e as linhas alteradas há pouco.',
  'errori.esec-segnale.concetto': 'execução',
  // ---- fora do dicionário: lugares, contagens, passos, correções, cartão ----
  'errori.tempo-scaduto': 'Tempo esgotado',
  'errori.segnale': 'Sinal {sig}',
  'errori.codice-uscita': `Código de saída {codice}`,
  'errori.codice-uscita-windows': `Código de saída {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'mais um erro', other: 'mais {n} erros' },
  'errori.avvisi': { one: '1 aviso', other: '{n} avisos' },
  'errori.conto': 'e {cosa}',
  'errori.conto-errori-e-avvisi': 'e {errori} e {avvisi}',
  'errori.un-nome': 'um nome',
  'errori.alla-riga': 'na linha {n}',
  'errori.nel-punto-indicato': 'no ponto indicado',
  'errori.la-riga': 'a linha {n}',
  'errori.il-punto-indicato': 'o ponto indicado',
  'errori.colonna': ', coluna {n}',
  'errori.del-if': 'do `if`',
  'errori.del-while': 'do `while`',
  'errori.del-for': 'do `for`',
  'errori.sconosciuto': 'erro desconhecido',
  'errori.errore': 'erro',
  'errori.nella-funzione': ', na função {funzione}',
  'errori.di-file': ' de {file}',
  'errori.fermato-alla-riga': 'O programa parou na linha {riga}{file}{funzione}.',
  'errori.poi-guarda-cambiate': ` Depois olhe as linhas alteradas desde o último teste que deu certo: {righe}.`,
  'errori.guarda-prima-cambiate': `Olhe primeiro as linhas alteradas desde o último teste que deu certo: {righe}.`,
  'errori.sistema-senza-riga': 'O sistema não diz a linha. Coloque alguns `printf` para ver até onde o programa chega; no Mac e no Linux você também pode compilar com `-g -fsanitize=address` para ter arquivo e linha.',
  'errori.messaggio-senza-riga': 'A mensagem não diz a linha: olhe as últimas linhas impressas pelo programa.',
  'errori.cambiate-e-altre': { one: '{righe} e mais {n}', other: '{righe} e mais {n}' },
  'errori.correggi-punto': `Adicione \`;\` no fim da instrução: na linha {riga} ou na anterior.`,
  'errori.correggi-punto-senza-riga': 'Adicione `;` no fim da instrução.',
  'errori.correggi-punto-fine': `No fim da linha {riga} adicione \`;\`:`,
  'errori.correggi-punto-dentro': `Na linha {riga}, no ponto indicado, adicione \`;\`:`,
  'errori.correggi-include-in-cima': 'No topo do arquivo, junto com os outros `#include`, adicione:',
  'errori.correggi-include-dopo': 'Depois da linha {riga} adicione:',
  'errori.correggi-include-primo': 'No topo do arquivo adicione:',
  'errori.correggi-uguale': 'Na condição troque `=` por `==`.',
  'errori.correggi-uguale-riga': `Na linha {riga} troque \`=\` por \`==\`:`,
  'errori.correggi-return': `Antes da \`}\` que fecha {nome}, adicione um \`return\` com o valor certo para os casos que ficaram de fora. Qual valor, quem decide é você: depende do que a função precisa calcular.`,
  'errori.correggi-return-senza-nome': `Antes da \`}\` que fecha a função, adicione um \`return\` com o valor certo para os casos que ficaram de fora. Qual valor, quem decide é você: depende do que a função precisa calcular.`,
  'errori.generico.dove-linker': 'O linker não indica uma linha: procure no projeto o nome citado na mensagem, e confira se todos os arquivos `.c` estão no comando de compilação.',
  'errori.generico.dove-senza-riga': 'A mensagem não indica uma linha: leia o texto original aqui embaixo.',
  'errori.generico.dove-python': 'O {L} parou {allaRiga}{file}. Se ali parece tudo certo, olhe a linha anterior.',
  'errori.generico.dove': 'Olhe {laRiga}{colonna}{file}. Se ali parece tudo certo, olhe também a linha anterior: muitas vezes o compilador só percebe um problema depois.',
  'errori.generico.eccezione-leggendo': '{eccezione} é o tipo de erro que o {L} encontrou enquanto lia o programa. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} é o tipo de erro que o {L} encontrou enquanto executava o programa. ',
  'errori.generico.cosa': 'O Lode ainda não tem uma explicação para esta mensagem. O texto original está aqui embaixo: leia as palavras entre aspas, normalmente são o nome ou o tipo que está dando problema.',
  'errori.catena': ' Você chegou aqui assim: {passi}.',
  'errori.catena-passo': 'linha {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, linha {riga}',
  'errori.luogo-riga': 'linha {riga}',
  'errori.con-eccezione': '{eccezione}: {frase}',
  'errori.intestazione': '**{luogo}**: {frase}',
  'errori.intestazione-eccezione': '**{luogo}** · {frase}',
  'errori.per-diario': '{dove}«{breve}»',
  'errori.non-lo-conosco': 'esse erro eu ainda não conheço',
  'errori.parola-avviso': 'aviso',
  'errori.e-un-avviso': `É um aviso: o programa compila do mesmo jeito, mas do jeito que está provavelmente não faz o que você quer. {cosa}`,
  'errori.passo-dove': 'Onde olhar',
  'errori.passo-cosa': 'O que quer dizer',
  'errori.passo-correzione': 'Me mostra a correção',
  'errori.file-cambiato': 'O arquivo mudou desde então: os números das linhas podem não bater.',
  'errori.tipo-errore': 'Erro',
  'errori.tipo-avviso': 'Aviso',
  'errori.tipo-linker': 'Erro do linker',
  'errori.tipo-esecuzione': 'Parou',
  'errori.segnaposto-valore': '‹valor›',
  'errori.correzione-vista': 'correção vista',
  'errori.messaggio-originale': 'Mensagem original',
};
