// «Coisas novas», o dicionário fixo da biblioteca padrão (português do Brasil): para cada item a pergunta de prova oral
// e a resposta. Os nomes das funções e as regras que as procuram no código ficam em js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': 'O que tem na memória que o malloc acabou de retornar?',
  'glossario.malloc.risposta': 'Lixo: o malloc não zera a memória. Se não houver memória, retorna NULL, então você confere antes de usar.',
  'glossario.calloc.domanda': 'Qual a diferença entre calloc(n, size) e malloc(n * size)?',
  'glossario.calloc.risposta': 'O calloc zera todos os bytes, o malloc deixa lixo. Se não houver memória, os dois retornam NULL.',
  'glossario.realloc.domanda': 'O que o realloc faz se falhar?',
  'glossario.realloc.risposta': 'Retorna NULL e o bloco antigo continua válido: precisa ser liberado à parte. Por isso se escreve p2 = realloc(p, n) e não p = realloc(p, n).',
  'glossario.free.domanda': 'O que acontece se você usar um ponteiro depois do free?',
  'glossario.free.risposta': 'É comportamento indefinido: aquela memória não é mais sua. Liberar duas vezes também é. Já free(NULL) não faz nada.',
  'glossario.strtok.domanda': 'Por que não dá para usar strtok numa string literal?',
  'glossario.strtok.risposta': 'Porque ele escreve na string: no lugar de cada separador põe \'\\0\'. A partir da segunda chamada você passa NULL e o strtok continua do ponto que ele guardou.',
  'glossario.strcpy.domanda': 'O que o strcpy confere no tamanho do destino?',
  'glossario.strcpy.risposta': 'Nada: copia até o \'\\0\', incluído. Se o destino for pequeno demais, escreve depois do fim do array, e isso é comportamento indefinido.',
  'glossario.strncpy.domanda': 'strncpy(d, s, n) sempre põe o \'\\0\' no final?',
  'glossario.strncpy.risposta': 'Não: se s tem n caracteres ou mais, d fica sem nenhum \'\\0\'. Se s é mais curta, preenche o resto com zeros.',
  'glossario.strcmp.domanda': 'O que o strcmp retorna se as duas strings forem iguais?',
  'glossario.strcmp.risposta': '0. Um número negativo se a primeira vem antes, positivo se vem depois: por isso if (strcmp(a, b)) quer dizer «são diferentes».',
  'glossario.strlen.domanda': 'O strlen conta também o \'\\0\' do final?',
  'glossario.strlen.risposta': 'Não: conta os caracteres antes do \'\\0\'. Para copiar a string você precisa de strlen(s) + 1 bytes.',
  'glossario.strcat.domanda': 'O que precisa para strcat(d, s) funcionar?',
  'glossario.strcat.risposta': 'd já precisa ter uma string com o \'\\0\' e espaço para as duas, mais o \'\\0\'. O strcat não confere o espaço.',
  'glossario.memcpy.domanda': 'Dá para usar memcpy se a origem e o destino se sobrepõem?',
  'glossario.memcpy.risposta': 'Não, é comportamento indefinido. Nesse caso se usa memmove.',
  'glossario.memset.domanda': 'memset(v, 1, n * sizeof(int)) põe os int de v em 1?',
  'glossario.memset.risposta': 'Não: o memset escreve o mesmo valor em cada byte, então cada int de 32 bits vale 16843009. Para zerar funciona: memset(v, 0, …).',
  'glossario.sizeof.domanda': 'Quanto vale sizeof(v) se v é um parâmetro int v[]?',
  'glossario.sizeof.risposta': 'O tamanho de um ponteiro, não do array: como parâmetro, int v[] é int *v. Por isso o tamanho é passado à parte.',
  'glossario.fgets.domanda': 'O que o fgets deixa no fim da linha lida?',
  'glossario.fgets.risposta': 'A quebra de linha, se coube, e depois o \'\\0\': fgets(s, n, f) lê no máximo n - 1 caracteres. No fim do arquivo retorna NULL.',
  'glossario.scanf.domanda': 'O que o scanf retorna?',
  'glossario.scanf.risposta': 'Quantos valores ele leu e atribuiu, ou EOF se a entrada acabar antes. Se você não confere, uma letra no lugar de um número passa em silêncio.',
  'glossario.sscanf.domanda': 'Qual a diferença entre scanf e sscanf?',
  'glossario.sscanf.risposta': 'O sscanf lê de uma string em vez da entrada. É muito usado depois do fgets: primeiro você lê a linha inteira, depois separa as partes.',
  'glossario.fopen.domanda': 'O que o fopen retorna se o arquivo não abre?',
  'glossario.fopen.risposta': 'NULL: confira antes de ler ou escrever. Cuidado: com "w" um arquivo que já existe é esvaziado na hora.',
  'glossario.fclose.domanda': 'O que o fclose faz num arquivo em que você escreveu?',
  'glossario.fclose.risposta': 'Grava no arquivo o que ainda está no buffer e libera o FILE. Depois do fclose aquele ponteiro não se usa mais.',
  'glossario.fprintf.domanda': 'Qual a diferença entre fprintf(stderr, ...) e printf(...)?',
  'glossario.fprintf.risposta': 'O printf escreve no stdout, o fprintf no fluxo que você passa. O stderr normalmente não tem buffer e não vai para o arquivo se você redireciona a saída com >.',
  'glossario.atoi.domanda': 'O que atoi("oi") retorna?',
  'glossario.atoi.risposta': '0, sem nenhum sinal de erro: você não distingue "0" de um texto errado. Para conferir se usa strtol.',
  'glossario.strtol.domanda': 'Para que serve o segundo argumento do strtol?',
  'glossario.strtol.risposta': 'É um char ** onde o strtol coloca o ponto em que parou: se for igual ao início, ele não leu nenhum dígito. O terceiro argumento é a base.',
  'glossario.qsort.domanda': 'O que a função de comparação do qsort precisa retornar?',
  'glossario.qsort.risposta': 'Um int negativo, zero ou positivo se o primeiro elemento vem antes, é igual ou vem depois. Ela recebe dois const void * que você converte para o tipo certo.',
  'glossario.exit.domanda': 'Qual a diferença entre exit(1) e return 1 dentro do main?',
  'glossario.exit.risposta': 'Dentro do main fazem a mesma coisa. Mas o exit encerra o programa de qualquer função, depois de esvaziar e fechar os arquivos abertos.',
  'glossario.assert.domanda': 'O que assert(x) faz se x for falso?',
  'glossario.assert.risposta': 'Escreve no stderr a condição, o arquivo e a linha, e depois para o programa com abort. Com -DNDEBUG os assert somem: dentro deles não vai código necessário.',
  'glossario.static-locale.domanda': 'O que muda se uma variável dentro de uma função é static?',
  'glossario.static-locale.risposta': 'Ela é inicializada uma vez só e guarda o valor de uma chamada para a outra. Se você não inicializa, começa em 0.',
  'glossario.computeifabsent.domanda': 'O que map.computeIfAbsent(k, x -> new ArrayList<>()) faz?',
  'glossario.computeifabsent.risposta': 'Se k não existe, cria a lista, coloca no mapa e retorna. Se já existe, retorna a que está lá. Assim depois você pode fazer .add sem conferir.',
  'glossario.getordefault.domanda': 'O que map.getOrDefault(k, 0) retorna se k não existe?',
  'glossario.getordefault.risposta': '0, e o mapa não muda: k não é adicionada.',
  'glossario.putifabsent.domanda': 'O que map.putIfAbsent(k, v) retorna?',
  'glossario.putifabsent.risposta': 'O valor que já estava lá, e aí o mapa não muda. Se k não existia, coloca v e retorna null.',
  'glossario.list-remove.domanda': 'Numa List<Integer> com [5, 7, 9], o que list.remove(1) faz?',
  'glossario.list-remove.risposta': 'Remove o elemento na posição 1, ou seja, o 7: com um int é escolhido remove(int índice). Para remover o valor 1 é preciso list.remove(Integer.valueOf(1)).',
  'glossario.equals.domanda': 'Qual a diferença entre == e equals em duas String?',
  'glossario.equals.risposta': 'O == confere se são o mesmo objeto, o equals se têm os mesmos caracteres. Duas strings iguais podem ser dois objetos diferentes.',
  'glossario.hashcode.domanda': 'Se você sobrescreve equals, o que precisa fazer com hashCode?',
  'glossario.hashcode.risposta': 'Sobrescrever ele também: objetos iguais pelo equals precisam ter o mesmo hashCode. Senão HashMap e HashSet não os encontram.',
  'glossario.collections-sort.domanda': 'O Collections.sort é estável?',
  'glossario.collections-sort.risposta': 'Sim: os elementos iguais na comparação ficam na ordem de antes. Ele ordena a própria lista e não retorna nada.',
  'glossario.comparator-comparing.domanda': 'O que Comparator.comparing(Aluno::getNota).reversed() faz?',
  'glossario.comparator-comparing.risposta': 'Compara os alunos pela nota, ao contrário: da maior para a menor. Com thenComparing você adiciona um segundo critério para notas iguais.',
  'glossario.optional.domanda': 'Por que não se chama get() num Optional sem conferir?',
  'glossario.optional.risposta': 'Se estiver vazio, o get() lança NoSuchElementException. Use orElse, orElseGet ou isPresent.',
  'glossario.stream.domanda': 'O que acontece se num stream você chama só map e filter, sem collect?',
  'glossario.stream.risposta': 'Nada: map e filter são preguiçosas. O trabalho só começa com uma operação final como collect, forEach ou count. E um stream se usa uma vez só.',
  'glossario.stringbuilder.domanda': 'Por que num laço se usa StringBuilder em vez de s = s + x?',
  'glossario.stringbuilder.risposta': 'Uma String nunca muda: cada + cria uma nova e copia tudo de novo. O StringBuilder adiciona no fim do mesmo objeto, e o toString() dá o resultado.',
  'glossario.integer-parseint.domanda': 'O que acontece com Integer.parseInt("12a")?',
  'glossario.integer-parseint.risposta': 'Lança NumberFormatException. " 12" com o espaço também lança: antes se usa trim().',
  'glossario.scanner-nextint.domanda': 'Por que um nextLine() logo depois de nextInt() retorna uma linha vazia?',
  'glossario.scanner-nextint.risposta': 'O nextInt lê o número mas deixa a quebra de linha lá. O nextLine lê até essa quebra e retorna "". Você faz um nextLine() a mais para descartá-la.',
  'glossario.try-with-resources.domanda': 'O que try (Scanner in = new Scanner(f)) { ... } faz?',
  'glossario.try-with-resources.risposta': 'Fecha sozinho o recurso no fim do bloco, mesmo se vier uma exceção. Funciona com as classes que implementam AutoCloseable.',
  'glossario.instanceof.domanda': 'O que x instanceof String retorna se x é null?',
  'glossario.instanceof.risposta': 'false, sem exceção. A partir do Java 16 você pode escrever x instanceof String s e usar s na hora.',
  'glossario.arrays-aslist.domanda': 'O que acontece se você faz add na lista de Arrays.asList?',
  'glossario.arrays-aslist.risposta': 'Lança UnsupportedOperationException: a lista tem tamanho fixo e está ligada ao array. Já o set funciona, e muda também o array.',
  'glossario.iterator-remove.domanda': 'Como você remove elementos de uma lista enquanto percorre ela?',
  'glossario.iterator-remove.risposta': 'Com um Iterator e it.remove(), ou com removeIf. Com list.remove dentro de um for-each normalmente vem ConcurrentModificationException.',
  'glossario.substring.domanda': 'O que "revisão".substring(1, 4) retorna?',
  'glossario.substring.risposta': '"evi": os caracteres da posição 1 até a 3. O segundo índice fica de fora, e a string original não muda.',
  'glossario.compareto.domanda': 'O que a.compareTo(b) retorna?',
  'glossario.compareto.risposta': 'Um número negativo se a vem antes de b, zero se são iguais, positivo se vem depois. Não precisa ser -1 ou 1: o que conta é o sinal.',
  'glossario.list-comprehension.domanda': 'O que [x * 2 for x in v if x > 0] constrói?',
  'glossario.list-comprehension.risposta': 'Uma lista nova com o dobro só dos elementos positivos de v. É um for com if e append escrito numa linha; v não muda.',
  'glossario.list-comprehension-annidata.domanda': 'Em [x for linha in m for x in linha], qual for é o externo?',
  'glossario.list-comprehension-annidata.risposta': 'O primeiro: os for se leem na ordem em que você escreveria um dentro do outro. O resultado é m achatada numa lista só.',
  'glossario.lambda.domanda': 'O que uma lambda pode ter em Python?',
  'glossario.lambda.risposta': 'Uma única expressão, que vira o valor retornado. Nada de instruções como return, for ou uma atribuição normal.',
  'glossario.sorted-con-key.domanda': 'O que sorted(v, key=len) faz?',
  'glossario.sorted-con-key.risposta': 'Retorna uma lista nova ordenada pelo tamanho; v fica como estava. Com tamanhos iguais, a ordem original se mantém: a ordenação é estável.',
  'glossario.enumerate.domanda': 'O que enumerate(v) dá?',
  'glossario.enumerate.risposta': 'Os pares (índice, elemento), com o índice começando em 0. Com enumerate(v, 1) começa em 1.',
  'glossario.zip.domanda': 'O que o zip faz se as listas têm tamanhos diferentes?',
  'glossario.zip.risposta': 'Para na mais curta: os elementos que sobram se perdem sem erro. A partir do Python 3.10, com strict=True dá erro.',
  'glossario.dict-get.domanda': 'Qual a diferença entre d[k] e d.get(k)?',
  'glossario.dict-get.risposta': 'd[k] lança KeyError se k não existe, d.get(k) retorna None, ou o segundo argumento se você passar. O get não adiciona k.',
  'glossario.setdefault.domanda': 'O que d.setdefault(k, []) faz?',
  'glossario.setdefault.risposta': 'Se k não existe, adiciona com [] e retorna essa lista. Se já existe, retorna o valor que está lá. A [] é criada de qualquer jeito a cada chamada.',
  'glossario.defaultdict.domanda': 'O que acontece se você lê uma chave que não existe num defaultdict(list)?',
  'glossario.defaultdict.risposta': 'Ele cria a chave com uma lista vazia e retorna, sem KeyError. Cuidado: só ler d[k] já adiciona k.',
  'glossario.counter.domanda': 'O que um Counter retorna para uma chave que nunca viu?',
  'glossario.counter.risposta': '0, sem KeyError e sem adicionar a chave. most_common(n) dá as n mais frequentes.',
  'glossario.with-open.domanda': 'Por que se escreve with open(nome) as f?',
  'glossario.with-open.risposta': 'O arquivo se fecha sozinho ao sair do bloco, mesmo se vier uma exceção. Sem with você precisa chamar f.close().',
  'glossario.yield.domanda': 'O que retorna uma função que tem yield?',
  'glossario.yield.risposta': 'Um gerador. O corpo só começa quando você pede o primeiro valor, com next ou com um for, e para a cada yield. Ele se percorre uma vez só.',
  'glossario.args-e-kwargs.domanda': 'Em def f(*args, **kwargs), o que são args e kwargs?',
  'glossario.args-e-kwargs.risposta': 'args é uma tupla com os argumentos posicionais a mais, kwargs um dicionário com os passados por nome.',
  'glossario.rovescia.domanda': 'O que v[::-1] dá?',
  'glossario.rovescia.risposta': 'Uma cópia de v ao contrário: funciona com listas, strings e tuplas. v não muda.',
  'glossario.is-e-uguale.domanda': 'Qual a diferença entre is e ==?',
  'glossario.is-e-uguale.risposta': 'O == compara os valores, o is confere se são o mesmo objeto. O is se usa com None; com números e strings se usa ==.',
  'glossario.default-mutabile.domanda': 'Por que def f(x, v=[]) é uma armadilha?',
  'glossario.default-mutabile.risposta': 'A lista padrão é criada uma vez só, quando f é definida: cada chamada vê as alterações das anteriores. Escreva v=None e crie a lista dentro.',
  'glossario.f-string.domanda': 'O que print(f"{x:.2f}") imprime se x vale 3.14159?',
  'glossario.f-string.risposta': '3.14: depois dos dois-pontos vem o formato, e .2f quer dizer duas casas depois da vírgula, arredondadas.',
  'glossario.extend.domanda': 'Qual a diferença entre v.append(w) e v.extend(w)?',
  'glossario.extend.risposta': 'O append adiciona w como um único elemento, mesmo se for uma lista. O extend adiciona um por um os elementos de w. Os dois mudam v e retornam None.',
  'glossario.split.domanda': 'Qual a diferença entre s.split() e s.split(" ")?',
  'glossario.split.risposta': 'Sem argumentos, divide em qualquer espaço, mesmo mais de um, e pula as partes vazias. Com " " cada espaço separa: dois espaços seguidos dão uma string vazia.',
  'glossario.da-riga': 'De: {file}, linha {riga}',
};
