// «Quero fazer…» (js/guida.js e o guia na barra, js/lode.js): as fichas do guia passo a passo e as receitas escritas à mão para quando
// não há IA. Cada passo de uma receita é uma lista de quatro textos: [título, o que fazer (2 a 4 frases simples), quando está
// pronto, uma ajuda para quem não consegue]. O número de passos de cada receita está em RICETTE em js/guida.js.
export default {
  'guida.serve-per': 'Para «{cosa}» você precisa de:',
  'guida.nessuna-app': 'Não achei apps adequados no computador. Tudo bem: quando for preciso, o passo diz o que instalar.',
  'guida.apri': 'Abrir',
  'guida.apri-tutte': 'Abrir todos',
  'guida.aperta': 'Aberto: {app}.',
  'guida.non-aperta': 'Não consegui abrir {app}.',
  'guida.cominciamo': 'Vamos começar',
  'guida.preparo': 'Estou preparando o plano',
  'guida.piano-ai': 'Plano escrito com {motore}: se um passo não serve para você, pule.',
  'guida.piano-ricetta': 'Plano do Lode, sem IA.',
  'guida.piano-generico': 'Para isso não tenho uma receita: proponho um plano genérico, para você adaptar.',
  'guida.piano-ripiego': 'A IA não deu um plano válido: uso o do Lode.',
  'guida.passo-di': 'Passo {i} de {tot}',
  'guida.fatto-quando': 'Pronto quando: {quando}',
  'guida.ti-serve': 'Você precisa de: {app}',
  'guida.fatto-avanti': 'Feito, avançar',
  'guida.non-ci-riesco': 'Não consigo',
  'guida.indietro': 'Voltar',
  'guida.basta': 'Chega',
  'guida.un-aiuto': 'Uma ajuda',
  'guida.piu-piccolo': 'Menor, um pedaço de cada vez:',
  'guida.ci-penso': 'Eu cuido disso',
  'guida.fallo-con': 'Faça com {agente}',
  'guida.scegli-cartella': 'Primeiro escolha a pasta onde trabalhar.',
  'guida.cartella': 'Escolher a pasta',
  'guida.testo-agente': 'Este é o texto que chega ao {agente}, na pasta «{cartella}». Você pode mudá-lo.',
  'guida.nota-agente': 'Abre-se uma janela do Terminal com o {agente}: ele usa a sua assinatura, sem chave. Leia o que ele faz antes de dizer sim.',
  'guida.agente-aperto': 'Abri o Terminal com o {agente}.',
  'guida.agente-segue': 'O Lode acompanha a pasta: quando o {agente} terminar, aviso você aqui.',
  'guida.agente-errore': 'O Terminal não abriu: {errore}',
  'guida.agente-finito': 'O {agente} terminou: confira e clique em Feito.',
  'guida.prompt-agente': 'Estou fazendo isto: {obiettivo}. Agora o passo é «{passo}»: {cosa} Faça só este passo, me explique com palavras simples o que você faz e pare no final.',
  'guida.fine-titolo': 'Tudo pronto!',
  'guida.fine-testo': { one: '{titolo}: o passo está feito. Bom trabalho.', other: '{titolo}: {n} passos de {n}, todos feitos. Bom trabalho.' },
  'guida.chiusa': 'Guia deixado de lado',
  'guida.chiusa-nota': 'Quando quiser continuar, escreva «retomar o guia».',
  'guida.ripresa': 'Continuo de onde você parou.',
  'guida.nessuna': 'Você não tem um guia pela metade. Experimente escrever «quero fazer uma apresentação».',
  'guida.proposta-titolo': 'Pela metade: {titolo}',
  'guida.proposta-testo': 'Você está no passo {i} de {tot}.',
  'guida.proposta-bottone': 'Retomar',
  'guida.nel-vault': 'A lista dos passos também está no vault: {nota}.',
  // a nota no vault (no idioma do vault)
  'guida.nota-file': 'Passo a passo',
  'guida.nota-intro': 'O guia do Lode. O Lode marca um passo quando você clica em «Feito, avançar» na barra.',
  'guida.nota-quando': 'Pronto quando',
  'guida.linguaggio': 'a sua linguagem',

  // as receitas: [título, o que fazer, pronto quando, ajuda]
  'guida.r-tesi-1': ['Entenda o que pedem', 'Releia o enunciado ou converse com o orientador. Escreva numa linha a pergunta que o seu trabalho responde. Anote o prazo e quantas páginas são necessárias.', 'você tem uma frase com a pergunta e a data de entrega', 'Se não sabe por onde começar, escreva três perguntas sobre o tema que despertam a sua curiosidade e escolha a que tem mais material.'],
  'guida.r-tesi-2': ['Reúna as fontes', 'Procure de 5 a 10 fontes sérias: livros, artigos, apostilas do curso. Guarde todas num lugar só, com autor e ano. Para cada uma, escreva duas linhas sobre o que você precisa dela.', 'você tem uma lista de fontes com duas linhas cada', 'Comece pela bibliografia de um bom artigo: ela leva a outras fontes que alguém já escolheu.'],
  'guida.r-tesi-3': ['Faça o sumário', 'Escreva os títulos dos capítulos e, embaixo de cada um, três ou quatro pontos. Não precisa ser perfeito. O sumário é o mapa: você vai mudá-lo enquanto escreve.', 'você tem um sumário com os pontos de cada capítulo', 'Use o esquema clássico: introdução, o que já se sabe, o que você fez, resultados, conclusão.'],
  'guida.r-tesi-4': ['Escreva o primeiro rascunho', 'Escreva um capítulo de cada vez, sem corrigir. Melhor uma página ruim do que uma página em branco. Coloque as citações logo, para não perdê-las.', 'cada capítulo tem um texto, mesmo ruim', 'Faça sessões curtas: «foco 25» e escreva só um parágrafo.'],
  'guida.r-tesi-5': ['Releia e ajuste', 'Releia tudo em voz alta: as frases longas aparecem. Confira se cada capítulo responde à pergunta inicial. Arrume as citações e a bibliografia.', 'você releu tudo uma vez, do começo ao fim', 'Imprima ou mude a fonte: nas mesmas folhas o olho pula os erros.'],
  'guida.r-tesi-6': ['Entregue', 'Exporte em PDF e confira as páginas uma por uma. Siga as regras do formato pedido. Envie o arquivo e guarde uma cópia.', 'o arquivo foi entregue e você tem uma cópia', 'Leia as regras de formato do departamento antes de exportar: margens, fonte, folha de rosto.'],

  'guida.r-sito-1': ['Decida o que o site deve fazer', 'Escreva quem vai ver o site e o que essa pessoa deve encontrar. Faça a lista das páginas, por exemplo Início, Sobre mim, Projetos, Contato. Desenhe a página principal numa folha.', 'você tem a lista das páginas e um esboço', 'Veja três sites parecidos de que você gosta e anote o que eles têm em comum.'],
  'guida.r-sito-2': ['Prepare a pasta', 'Crie uma pasta para o site e abra no editor. Dentro dela, crie index.html e style.css. Escreva uma página só com um título e abra no navegador.', 'o navegador mostra o seu título', 'No arquivo index.html basta escrever a tag h1 com o seu nome: salve e recarregue a página.'],
  'guida.r-sito-3': ['Escreva a estrutura', 'Coloque em HTML as partes da página: cabeçalho, seções, rodapé. Use títulos e parágrafos de verdade, sem estilo por enquanto. Adicione as outras páginas e os links entre elas.', 'todas as páginas existem e os links funcionam', 'Uma página de cada vez: copie index.html, mude o texto e ligue com uma tag a.'],
  'guida.r-sito-4': ['Dê o estilo', 'No CSS escolha uma fonte, duas cores e as margens. Faça com que fique bom de ler também no celular. Confira com as ferramentas do navegador.', 'o site é fácil de ler no computador e no celular', 'Comece com poucas regras: font-family, max-width para o texto, um pouco de padding.'],
  'guida.r-sito-5': ['Coloque no ar', 'Escolha um serviço gratuito para sites estáticos, por exemplo GitHub Pages ou Netlify. Envie a pasta e abra o endereço que eles derem. Mande para um amigo e pergunte o que ele não entende.', 'o site abre a partir de um endereço público', 'Com o GitHub Pages: crie um repositório, envie os arquivos e ative o Pages nas configurações.'],

  'guida.r-codice-1': ['Entenda o problema', 'Releia o enunciado e escreva com palavras o que entra e o que sai do programa. Prepare dois ou três exemplos com o resultado certo. Assim você vai saber quando funciona.', 'você tem dois ou três exemplos de entrada e saída', 'Faça um exemplo pequenininho à mão, numa folha, passo a passo.'],
  'guida.r-codice-2': ['Prepare o ambiente', 'Crie uma pasta para o projeto e abra no editor. Confira se {linguaggio} funciona: escreva um programa que imprime uma linha e execute.', 'o programa de teste imprime a sua linha', 'Se o comando não for encontrado, o programa não está instalado ou não está no PATH: procure o guia oficial para o seu sistema.'],
  'guida.r-codice-3': ['Escreva a primeira versão', 'Escreva em {linguaggio} a versão mais simples que resolve o primeiro exemplo. Sem casos especiais por enquanto. Execute o programa com frequência, depois de poucas linhas.', 'o primeiro exemplo dá o resultado certo', 'Divida em funções pequenas: uma lê, uma calcula, uma imprime.'],
  'guida.r-codice-4': ['Teste todos os casos', 'Teste os outros exemplos e os casos extremos: vazio, um só elemento, números grandes. Quando algo der errado, leia o erro e imprima os valores no meio. Corrija um erro de cada vez.', 'todos os exemplos dão o resultado certo', 'Copie o erro e escreva «explica o erro»: eu explico um passo de cada vez.'],
  'guida.r-codice-5': ['Limpe e entregue', 'Dê nomes claros às variáveis e tire as impressões de teste. Adicione duas linhas que expliquem como executar. Releia o enunciado e confira se você fez tudo.', 'o código está limpo e o enunciado foi cumprido', 'Explique o código em voz alta, linha por linha: onde você travar, há algo a arrumar.'],

  'guida.r-presentazione-1': ['Decida a mensagem', 'Escreva numa frase o que quem ouve deve lembrar. Veja quanto tempo você tem: mais ou menos um slide por minuto. Escolha três pontos, não mais.', 'você tem a frase da mensagem e três pontos', 'Imagine que conta para um amigo em um minuto: o que você disser é a mensagem.'],
  'guida.r-presentazione-2': ['Faça o roteiro', 'Escreva um título para cada slide, em ordem. Primeiro a abertura, depois os três pontos, depois o encerramento. Sem visual por enquanto.', 'você tem uma lista de títulos, um por slide', 'Use post-its ou uma lista: mudar as ideias de lugar é mais fácil antes de abrir o programa.'],
  'guida.r-presentazione-3': ['Preencha os slides', 'Uma ideia por slide, poucas palavras, imagens grandes. O texto longo você fala, não escreve. Use o mesmo estilo em todos.', 'cada slide tem o seu conteúdo', 'Se um slide tem mais de seis linhas, divida em dois.'],
  'guida.r-presentazione-4': ['Ensaie em voz alta', 'Repita a apresentação inteira com o cronômetro. Anote onde você trava e onde fica longo. Corte o que não ajuda a mensagem.', 'você ensaiou no tempo certo', 'Grave com o celular e ouça uma vez.'],
  'guida.r-presentazione-5': ['Prepare o dia', 'Exporte também em PDF, caso o programa não esteja lá. Leve o arquivo num pen drive ou na nuvem. Prepare a resposta para duas perguntas prováveis.', 'você tem o PDF reserva e as duas respostas', 'Chegue alguns minutos antes e teste o projetor.'],

  'guida.r-video-1': ['Escreva o que você vai contar', 'Decida numa frase do que trata o vídeo e quanto ele dura. Escreva o roteiro das cenas. Se você fala, escreva o texto e leia em voz alta.', 'você tem o roteiro e o texto', 'Um vídeo curto funciona melhor: comece por um de um minuto.'],
  'guida.r-video-2': ['Grave', 'Grave as cenas do roteiro, cada uma mais de uma vez. Cuide da luz e principalmente do áudio: um microfone perto conta mais que a câmera. Segure o celular parado e na horizontal, se não for para redes sociais.', 'todas as cenas estão gravadas', 'Grave num lugar silencioso, com a janela na sua frente e não atrás.'],
  'guida.r-video-3': ['Edite', 'Importe os arquivos no programa de edição. Coloque as cenas em ordem e corte as pausas e os erros. Assista a tudo uma vez sem parar.', 'o vídeo dá para ver do começo ao fim', 'Corte mais do que você acha: um segundo a mais se sente.'],
  'guida.r-video-4': ['Dê o acabamento', 'Ajuste o volume, adicione os títulos e, se precisar, música baixa. Use música livre de direitos. Adicione legendas se alguém for ver sem áudio.', 'áudio, títulos e legendas estão certos', 'Ouça com fones: dá para notar as mudanças de volume.'],
  'guida.r-video-5': ['Exporte e entregue', 'Exporte em MP4, 1080p, que serve quase em qualquer lugar. Assista ao arquivo exportado até o fim. Envie ou entregue e guarde o projeto.', 'o arquivo foi entregue e você assistiu a tudo', 'Se o arquivo for grande demais, exporte com bitrate mais baixo.'],

  'guida.r-dati-1': ['Escreva a pergunta', 'Escreva numa linha o que você quer descobrir com os dados. Decida qual gráfico responderia: uma evolução, uma comparação, uma distribuição. Assim você sabe o que procurar.', 'você tem a pergunta e o tipo de gráfico', 'Complete a frase: quando uma coisa muda, a outra também muda?'],
  'guida.r-dati-2': ['Prepare os dados', 'Abra os dados numa planilha. Uma linha por observação, uma coluna por variável, com um nome claro. Tire as linhas vazias e as duplicadas.', 'a tabela está limpa, com os cabeçalhos', 'Trabalhe numa cópia: guarde sempre o arquivo original.'],
  'guida.r-dati-3': ['Olhe os números', 'Calcule para cada coluna a média, o mínimo e o máximo. Procure os valores estranhos: erros de digitação ou casos de verdade? Anote o que você notar.', 'você tem os números de resumo e as notas', 'Ordene a coluna: os valores estranhos vão parar no topo ou no fim.'],
  'guida.r-dati-4': ['Faça o gráfico', 'Crie o gráfico que responde à pergunta. Coloque o título, o nome dos eixos e as unidades. Tire tudo o que não ajuda a ler.', 'o gráfico se entende sem explicações', 'Linhas para a evolução no tempo, barras para comparar, histograma para a distribuição.'],
  'guida.r-dati-5': ['Escreva o que ele diz', 'Embaixo do gráfico escreva duas ou três frases: o que se vê e o que isso significa. Diga também o que os dados não podem dizer. Salve o gráfico como imagem.', 'você tem o gráfico salvo e as frases', 'Separe o que você vê da sua explicação: primeiro os fatos, depois a ideia.'],

  'guida.r-esame-1': ['Organize a ementa', 'Pegue a ementa da disciplina e cole no Lode com «programa». Você terá o mapa dos temas. Marque os que você já sabe.', 'a ementa está no Lode', 'Se não achar a ementa, veja a página da disciplina ou pergunte aos colegas.'],
  'guida.r-esame-2': ['Faça um plano', 'Conte os dias que faltam e divida os temas. Deixe os últimos dias para revisar. Coloque o plano no calendário.', 'cada tema tem o seu dia', 'Escreva «plano da semana» e o Lode mostra as suas horas livres de verdade.'],
  'guida.r-esame-3': ['Estude um tema por dia', 'Faça sessões curtas com o cronômetro, por exemplo «foco 50». No fim de cada tema, faça cartões com o que precisa lembrar. Revise todo dia com «revisar».', 'você estudou todos os temas pelo menos uma vez', 'Explique o tema em voz alta como se fosse o professor: onde você travar, releia.'],
  'guida.r-esame-4': ['Ponha-se à prova', 'Faça o «quiz» ou peça perguntas com «me faz perguntas». Anote as perguntas erradas e estude de novo. Repita até saber.', 'você responde bem à maioria das perguntas', 'Comece pelos temas que você sabe menos: é aí que se ganha mais.'],
  'guida.r-esame-5': ['Faça uma prova de verdade', 'Dois ou três dias antes, faça a «prova completa» com uma prova antiga e o tempo real. Corrija e revise os erros. No dia anterior, durma.', 'você fez uma prova inteira no tempo', 'Se não tem provas antigas, peça aos colegas ou no grupo da disciplina.'],

  'guida.r-generico-1': ['Escreva o resultado', 'Escreva numa frase como será a coisa pronta. Quanto mais concreta, melhor. Anote também para quando você precisa.', 'você tem a frase do resultado e a data', 'Imagine mostrar a alguém: o que essa pessoa vê?'],
  'guida.r-generico-2': ['Procure o que você precisa', 'Faça a lista do que você precisa: programas, materiais, pessoas para conversar. Veja como outra pessoa fez, por exemplo num vídeo ou num guia.', 'você tem a lista do que precisa', 'Procure o nome da coisa com «tutorial» ou «guia para iniciantes».'],
  'guida.r-generico-3': ['Dê o primeiro passo pequeno', 'Escolha a menor coisa que você pode fazer agora, em 20 minutos. Faça já, mesmo que não fique perfeita. O resto fica mais fácil.', 'você fez o primeiro pedaço', 'Se 20 minutos é muito, faça 5: o importante é começar.'],
  'guida.r-generico-4': ['Siga em frente e confira', 'Divida o resto em pedaços de uma sessão e faça um de cada vez. Depois de cada pedaço, compare com o resultado que você escreveu. Peça uma opinião antes do fim.', 'o resultado está como você escreveu', 'Se travar, volte ao pedaço anterior e deixe-o menor.'],
};
