// Seu histórico com sistemas de notas diferentes do italiano (português do Brasil): «quanto eu preciso», «e se eu tirar»,
// créditos, nota final, o histórico colado (js/libretto.js, js/lode.js, js/pagina.js, js/benvenuto.js).
export default {
  'libretto.crediti-di': '{fatti} de {tot} {crediti}',
  'libretto.serve-gia': 'Para chegar a <b>{obiettivo}</b>, basta você passar nas matérias que faltam.',
  'libretto.serve-media': 'Para chegar a <b>{obiettivo}</b>, você precisa de média <b>{voto}</b> nos {cfu} {crediti} que faltam.',
  'libretto.serve-impossibile': 'Chegar a <b>{obiettivo}</b> não dá mais: mire em {punta}.',
  'libretto.obiettivo-fuori': 'No sistema {sistema}, o objetivo vai de {da} a {a}.',
  'libretto.simula-esito': 'Média <b>{media}</b> <span class="{classe}">{delta}</span> · {finale} <b>{valore}</b>',
  'libretto.voto-altro-sistema': "{voto} ({sistema}): não conta neste sistema",
  'libretto.totali-opzione': '{n} {crediti}',
  'libretto.esame-nuovo-crediti': '{nome} (nova, {n} {crediti})',
  'libretto.simula': 'Com **{voto}** em {nome}, sua média vai de {prima} para **{dopo}** ({delta}): {finale} **{valore}**.',
  'libretto.simula-primo': 'Com {voto} em **{nome}**, sua média começaria em **{media}**: {finale} **{valore}**.',
  'libretto.sintesi-media-finale': 'média {media}, {finale} {valore}',
  'libretto.non-valido': 'No sistema {sistema} não existe a nota {voto}.',
  'libretto.non-superato': '{voto} em {nome} não é aprovação (precisa de {sufficienza}): não vou anotar no histórico.',
  'libretto.nuovo-esame': 'Matéria nova com {n} {crediti}: corrija no seu histórico.',
  'libretto.formula': 'média ponderada pelos {crediti}',
  'libretto.piede-esami': { one: '{n} matéria · {cfu} {crediti}', other: '{n} matérias · {cfu} {crediti}' },
  'libretto.piede-media': 'média <b>{media}</b> · {finale} <b>{valore}</b>',
  'libretto.campo-voto-nota': 'como no seu histórico ({esempio}); vazio se você ainda não fez',
  'libretto.voto-non-letto': 'Não consigo ler a nota «{voto}»: escreva como no seu histórico, por exemplo {esempio}.',
  'libretto.incolla-sotto': 'Abra seu histórico no portal da faculdade, selecione tudo, copie e cole aqui: uma linha por matéria, com nome, créditos e nota. Ou escreva você mesmo, por exemplo «{esempio}».',
  'libretto.alla-laurea': '{n} {crediti} para se formar',
  'libretto.campo-crediti': 'Créditos ({crediti})',
  'libretto.libretto-vuoto': 'Nenhuma matéria ainda. Escreva na barra <kbd>tirei {voto} em física</kbd>.',
  'libretto.riga-esempio': '{nome}, {n} {crediti}, {voto}',
  'libretto.esame-esempio': 'Cálculo 1',
};
