// As perguntas de «O que imprime?» (js/codice/modelli.js), em português do Brasil.
// Chaves: modelli.<modelo>.cosa / .concetto / .frase-N (as frases dos mutantes, na ordem), modelli.<modelo>.<linguagem>.… para
// o que muda em Python e Java; modelli.concetti.* e modelli.errori.* são os nomes dos tópicos e dos erros.
export default {
  'modelli.hai-scelto': 'Você escolheu `{s}`',
  'modelli.niente': '(nada)',
  'modelli.concetti.for': 'Laço for',
  'modelli.concetti.while': 'Laço while',
  'modelli.concetti.do-while': 'Laço do-while',
  'modelli.concetti.ritroso': 'Contagem regressiva',
  'modelli.concetti.array': 'Array',
  'modelli.concetti.divisione-intera': 'Divisão inteira',
  'modelli.concetti.resto': 'Resto com negativos',
  'modelli.concetti.cast': 'Cast para double',
  'modelli.concetti.incremento': 'i++ e ++i',
  'modelli.concetti.assegnamento': 'Atribuições compostas (+=)',
  'modelli.concetti.switch': 'switch e break',
  'modelli.concetti.cortocircuito': '&& e || em curto-circuito',
  'modelli.concetti.else-pendente': 'else pendente',
  'modelli.concetti.puntatori': 'Passagem por referência',
  'modelli.concetti.parametri': 'Passagem por valor',
  'modelli.concetti.visibilita': 'Variáveis nos blocos',
  'modelli.concetti.char': 'char e códigos ASCII',
  'modelli.concetti.ricorsione': 'Recursão',
  'modelli.concetti.annidati': 'Laços aninhados',
  'modelli.concetti.break-continue': 'break e continue',
  'modelli.concetti.ternario': 'Operador ternário',
  'modelli.errori.fuori-di-uno': 'erro de um a mais/a menos',
  'modelli.errori.divisione-intera': 'divisão inteira',
  'modelli.errori.post-vs-pre': 'i++ e ++i',
  'modelli.errori.break-dimenticato': 'break esquecido',
  'modelli.errori.copia-del-parametro': 'cópia do parâmetro',
  'modelli.errori.cortocircuito': 'curto-circuito',
  'modelli.errori.resto-col-segno': 'resto com sinal',
  'modelli.errori.piu-uguale': '+= e =',
  'modelli.errori.maggiore-o-uguale': '> e >=',
  'modelli.errori.indice-valore': 'índice e valor',
  'modelli.errori.sovrascrittura': 'primeiro e último',
  'modelli.errori.else-pendente': 'else pendente',
  'modelli.errori.variabile-nascosta': 'variável escondida',
  'modelli.errori.carattere-codice': 'caractere e código',
  'modelli.errori.caso-base': 'caso base',
  'modelli.errori.passo-del-ciclo': 'quando o passo do laço acontece',
  'modelli.errori.ricorsione': 'recursão',
  'modelli.errori.cicli-annidati': 'laços aninhados',
  'modelli.errori.break-continue': 'break e continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'ternário ao contrário',
  'modelli.errori.scambi-in-fila': 'trocas em sequência',
  'modelli.for-minore.cosa': 'este for',
  'modelli.for-minore.concetto': 'Com `i < n` a última volta tem i = n - 1: o valor n nunca é impresso.',
  'modelli.for-minore.frase': `{hai}: é o que ele imprimiria com \`i <= {b}\`. Aqui o laço para antes.`,
  'modelli.for-minore.frase-2': `{hai}: é como se o \`i++\` acontecesse antes da primeira volta. O incremento vem no fim de cada volta: a primeira volta tem i = {a}.`,
  'modelli.for-minore.frase-3': `{hai}: você parou uma volta antes. Com \`i < {b}\` a última volta tem i = {b2}.`,
  'modelli.for-passo.cosa': 'este for',
  'modelli.for-passo.concetto': 'Com `<=` o laço faz também a volta em que i é igual ao limite.',
  'modelli.for-passo.frase': `{hai}: é o que ele imprimiria com \`i < {b}\`. Com \`<=\` o {b} também é impresso.`,
  'modelli.for-passo.frase-2': `{hai}: o \`i += {s}\` não acontece antes da primeira volta. A primeira volta tem i = {a}.`,
  'modelli.for-indietro.cosa': 'esta contagem regressiva',
  'modelli.for-indietro.concetto': 'O laço roda enquanto a condição é verdadeira: com `i > L` o valor L não é impresso.',
  'modelli.for-indietro.frase': `{hai}: é o que ele imprimiria com \`i >= {l}\`. Com \`i > {l}\` a última volta tem i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai}: o \`i--\` vem no fim da volta, não antes. A primeira volta imprime {n}.`,
  'modelli.for-indietro.frase-3': `{hai}: você parou uma volta antes. i = {l} também satisfaz \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'este while',
  'modelli.while-somma.concetto': 'O while sai quando a condição fica falsa: depois de `while (i < n)` a variável i vale n.',
  'modelli.while-somma.frase': `{hai}: é o que ele imprimiria com \`i <= {n}\`. Aqui o laço faz uma volta a menos.`,
  'modelli.while-somma.frase-2': `{hai}: é como se o \`i++\` viesse antes de \`s += i\`. Aqui s soma i e só depois i cresce.`,
  'modelli.while-somma.frase-3': `{hai}: depois do laço i não vale {n}. O while sai justamente quando i vira {n2}.`,
  'modelli.while-dimezza.cosa': 'este while',
  'modelli.while-dimezza.concetto': 'Entre dois int, a `/` trunca: 7 / 2 dá 3, e dividindo por dois se chega a 1 sem casas decimais.',
  'modelli.while-dimezza.frase': `{hai}: é o que aconteceria se n fosse um double. n é um int: \`n /= 2\` joga fora a parte decimal.`,
  'modelli.while-dimezza.frase-2': `{hai}: é o que ele imprimiria com \`n >= 1\`. O laço para assim que n chega a 1.`,
  'modelli.while-post.cosa': 'este while com i++',
  'modelli.while-post.concetto': '`i++ < n` compara o valor antigo e depois incrementa: dentro do laço i já cresceu.',
  'modelli.while-post.frase': `{hai}: é o que ele imprimiria com \`++i\`. Com \`i++\` a comparação usa o valor de antes.`,
  'modelli.while-post.frase-2': `{hai}: quando o printf roda, i já foi incrementado pela comparação.`,
  'modelli.while-post.frase-3': `{hai}: a última comparação, a falsa, também incrementa i. No fim i vale {n}.`,
  'modelli.array-somma.cosa': 'esta soma',
  'modelli.array-somma.concetto': 'Os índices de um array de n elementos vão de 0 a n - 1.',
  'modelli.array-somma.frase': `{hai}: você pulou o \`v[0]\`. O primeiro elemento tem índice 0.`,
  'modelli.array-somma.frase-2': `{hai}: você deixou o último de fora. Com \`i < {k}\` a última volta lê \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai}: é o último elemento, como se fosse \`s = v[i]\`. O \`+=\` soma, não substitui.`,
  'modelli.array-massimo.cosa': 'este máximo',
  'modelli.array-massimo.concetto': 'p é um índice: conta a partir de 0. Com `>` fica a primeira posição do máximo.',
  'modelli.array-massimo.frase': `{hai}: você contou as posições a partir de 1. Em {linguaggio} o primeiro elemento tem índice 0.`,
  'modelli.array-massimo.frase-2': `{hai}: é o que o \`>=\` faria. Com \`>\` um máximo igual não muda p: fica o primeiro.`,
  'modelli.array-massimo.frase-3': `{hai}: você deixou o último elemento de fora. Ele também é comparado.`,
  'modelli.array-ultimo.cosa': 'esta busca',
  'modelli.array-ultimo.concetto': 'O laço não para quando acha x: p é sobrescrito e fica a última posição.',
  'modelli.array-ultimo.frase': `{hai}: é a primeira posição. O laço não para: cada vez que acha x, reescreve p.`,
  'modelli.array-ultimo.frase-2': `{hai}: você contou as posições a partir de 1. Em {linguaggio} o primeiro elemento tem índice 0.`,
  'modelli.array-ultimo.frase-3': `{hai}: é o valor procurado, não a posição dele. p é um índice.`,
  'modelli.media-array.cosa': 'esta média',
  'modelli.media-array.concetto': '`s / n` entre int trunca. `(double)s / n` converte antes e divide com casas decimais.',
  'modelli.media-array.frase': `{hai}: \`s / {k}\` é uma divisão entre dois int: a parte decimal se perde.`,
  'modelli.media-array.frase-2': `{hai}: o cast \`(double)s\` acontece antes da divisão, então a divisão mantém as casas decimais.`,
  'modelli.media-array.frase-3': `{hai}: a divisão entre int não arredonda, trunca.`,
  'modelli.divisione-double.cosa': 'esta divisão',
  'modelli.divisione-double.concetto': 'O tipo do resultado não importa: `a / b` entre int trunca mesmo se o resultado vai para um double.',
  'modelli.divisione-double.frase': `{hai}: \`a / b\` é calculado entre int, antes de ir para m. O double recebe um número já truncado.`,
  'modelli.divisione-double.frase-2': `{hai}: a divisão entre int não arredonda, trunca em direção ao zero.`,
  'modelli.cast-prima-dopo.cosa': 'estes dois casts',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` divide entre int e depois converte. `(double)s / n` converte e depois divide.',
  'modelli.cast-prima-dopo.frase': `{hai}: em \`(double)(s / n)\` os parênteses fazem dividir antes, entre int. O cast vem depois.`,
  'modelli.cast-prima-dopo.frase-2': `{hai}: em \`(double)s / n\` o cast vale só para s, e a divisão mantém as casas decimais.`,
  'modelli.cast-prima-dopo.frase-3': `{hai}: você trocou os dois. Os parênteses decidem se o cast vem antes ou depois da divisão.`,
  'modelli.diviso-due.cosa': 'esta divisão por 2',
  'modelli.diviso-due.concetto': 'Basta um double na conta: `a / 2.0` mantém as casas decimais, `a / 2` não.',
  'modelli.diviso-due.frase': `{hai}: \`a / 2\` é entre dois int: trunca e dá um int, que o %d imprime sem casas decimais.`,
  'modelli.diviso-due.frase-2': `{hai}: \`2.0\` é um double, então \`a / 2.0\` mantém as casas decimais.`,
  'modelli.diviso-due.frase-3': `{hai}: \`a / 2\` não arredonda: trunca em direção ao zero.`,
  'modelli.resto-negativi.cosa': 'este resto',
  'modelli.resto-negativi.concetto': `Em {linguaggio} a divisão trunca em direção ao zero e o resto tem o sinal do dividendo: -7 % 3 dá -1.`,
  'modelli.resto-negativi.frase': `{hai}: é assim que o Python faz, arredondando para baixo. Em {linguaggio} se trunca em direção ao zero.`,
  'modelli.resto-negativi.frase-2': `{hai}: em {linguaggio} o resto nem sempre é positivo. Ele tem o sinal do dividendo, ou seja, de a.`,
  'modelli.resto-negativi.frase-3': `{hai}: a divisão entre int trunca em direção ao zero, não para baixo.`,
  'modelli.post-pre.cosa': 'estes incrementos',
  'modelli.post-pre.concetto': '`x = i--` usa o valor de antes e depois decrementa; `y = --i` decrementa e depois usa o valor novo.',
  'modelli.post-pre.concetto-2': '`x = i++` usa o valor de antes e depois incrementa; `y = ++i` incrementa e depois usa o valor novo.',
  'modelli.post-pre.frase': `{hai}: com \`x = i{op}\` o x pega o valor de antes, depois i muda.`,
  'modelli.post-pre.frase-2': `{hai}: com \`y = {op}i\` primeiro i muda, depois y pega o valor novo.`,
  'modelli.post-pre.frase-3': `{hai}: você trocou os dois. O sinal depois (\`i{op}\`) usa o valor de antes, o sinal antes (\`{op}i\`) usa o valor novo.`,
  'modelli.piu-uguale.cosa': 'este +=',
  'modelli.piu-uguale.concetto': '`s += x` quer dizer `s = s + x`: soma ao valor que já estava lá.',
  'modelli.piu-uguale.frase': `{hai}: é só a última volta, como se fosse \`=\`. O \`+=\` soma toda vez.`,
  'modelli.piu-uguale.frase-2': `{hai}: com \`<=\` o i = {n} também faz a sua volta.`,
  'modelli.piu-uguale.frase-3': `{hai}: você esqueceu o valor inicial. s começa em {a}.`,
  'modelli.switch.cosa': 'este switch',
  'modelli.switch.concetto': 'Sem break a execução cai no case de baixo e continua até o primeiro break ou até o fim.',
  'modelli.switch.frase': `{hai}: é como se cada case tivesse o seu break. Sem break a execução continua no case de baixo.`,
  'modelli.switch.frase-2': `{hai}: você pulou o break. Ali o switch para.`,
  'modelli.switch.frase-3': `{hai}: o default não roda sempre. Ele roda se nenhum case corresponde, ou se você chega nele caindo de um case sem break.`,
  'modelli.cortocircuito.cosa': 'este if com || e &&',
  'modelli.cortocircuito.concetto': 'Se a primeira parte já basta para decidir (verdadeira com ||, falsa com &&), a segunda não é executada.',
  'modelli.cortocircuito.frase': `{hai}: o \`++n\` não é executado. Com \`{op}\` a primeira parte já basta para decidir, e n fica 0.`,
  'modelli.cortocircuito.frase-3': 'O || quer pelo menos uma parte verdadeira',
  'modelli.cortocircuito.frase-4': 'O && quer as duas partes verdadeiras',
  'modelli.cortocircuito.frase-2': `{hai}: você leu \`{op}\`. {op2}.`,
  'modelli.else-pendente.cosa': 'este else',
  'modelli.else-pendente.concetto': 'O else vai com o if mais próximo que ainda não tem else, seja qual for a indentação.',
  'modelli.else-pendente.frase': `{hai}: você seguiu a indentação. Mas o else vai com o if mais próximo, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai}: com \`i < {n}\` a última volta tem i = {n2}.`,
  'modelli.swap-valore.cosa': 'esta troca',
  'modelli.swap-valore.concetto': 'Uma função recebe cópias dos valores: trocar a e b não mexe em x e y.',
  'modelli.swap-valore.frase': `{hai}: a e b são cópias de x e y. A troca fica dentro da função.`,
  'modelli.swap-valore.frase-2': `{hai}: dentro da função a troca acontece de verdade. Quem troca são as cópias, não x e y.`,
  'modelli.swap-indirizzo.cosa': 'estas trocas com ponteiros',
  'modelli.swap-indirizzo.concetto': 'Com `&x` a função recebe o endereço: `*a = …` muda o próprio x. As trocas acontecem uma depois da outra.',
  'modelli.swap-indirizzo.frase': `{hai}: aqui não são cópias. \`&x\` passa o endereço, e \`*a\` escreve no próprio x.`,
  'modelli.swap-indirizzo.frase-2': `{hai}: as trocas vão em ordem. Primeiro x com y, depois o y novo com z.`,
  'modelli.swap-indirizzo.frase-3': `{hai}: a segunda troca vê o y já mudado pela primeira.`,
  'modelli.valore-e-indirizzo.cosa': 'esta função',
  'modelli.valore-e-indirizzo.concetto': 'a é uma cópia de x; b é o endereço de y: só `*b = …` muda a variável do main.',
  'modelli.valore-e-indirizzo.frase': `{hai}: a é uma cópia de x. Mudar a não muda x.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai}: b não é uma cópia, é o endereço de y. \`*b = …\` muda y.`,
  'modelli.array-in-funzione.cosa': 'este array passado para uma função',
  'modelli.array-in-funzione.concetto': 'Um array é passado por endereço: a função muda o próprio a. Já um int é passado como cópia.',
  'modelli.array-in-funzione.frase': `{hai}: um array não é copiado. A função trabalha nos mesmos elementos de a.`,
  'modelli.array-in-funzione.frase-2': `{hai}: já n é uma cópia. O \`n--\` da função não mexe no n do main.`,
  'modelli.blocco-ombra.cosa': 'estes dois x',
  'modelli.blocco-ombra.concetto': 'O x declarado no bloco é outra variável: esconde o de fora e some no }.',
  'modelli.blocco-ombra.frase': `{hai}: \`int x = {b}\` dentro das chaves cria um x novo. Fora, o x ainda vale {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai}: dentro do bloco o x mais próximo é o interno. É ele que o y usa.`,
  'modelli.char-ascii.cosa': 'estes char',
  'modelli.char-ascii.concetto': 'Um char é um número: \'a\' vale 97. %c imprime a letra, %d o código. Maiúscula = minúscula - 32.',
  'modelli.char-ascii.frase': `{hai}: o %d não dá a posição no alfabeto. Dá o código ASCII: 'a' vale 97.`,
  'modelli.char-ascii.frase-2': `{hai}: o %d imprime o número do caractere, não a letra.`,
  'modelli.char-ascii.frase-3': `{hai}: d é um char e o %c imprime ele como letra, a maiúscula.`,
  'modelli.fattoriale.cosa': 'esta recursão',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), e o caso base para a descida em 1.',
  'modelli.fattoriale.frase': `{hai}: é fatt({n}). Você fez um passo a menos: multiplica de {n2} até 1.`,
  'modelli.fattoriale.frase-2': `{hai}: é fatt({n}). Você fez um passo a mais: começa em {n2}.`,
  'modelli.fattoriale.frase-3': `{hai}: você parou na primeira chamada. fatt(n - 1) continua chamando a si mesma até o caso base.`,
  'modelli.somma-cifre.cosa': 'esta recursão',
  'modelli.somma-cifre.concetto': 'n % 10 é o último dígito, n / 10 tira o último dígito. O caso base retorna o dígito que sobra.',
  'modelli.somma-cifre.frase': `{hai}: você perdeu o primeiro dígito. O caso base retorna n, não 0.`,
  'modelli.somma-cifre.frase-2': `{hai}: é a quantidade de dígitos. Aqui cada chamada soma \`n % 10\`, o dígito, não 1.`,
  'modelli.somma-cifre.frase-3': `{hai}: é só o último dígito. O valor de retorno se soma ao da chamada seguinte.`,
  'modelli.ricorsione-ordine.cosa': 'esta recursão',
  'modelli.ricorsione-ordine.concetto': 'O printf vem depois da chamada: imprime na volta, então do menor para o maior.',
  'modelli.ricorsione-ordine.frase': `{hai}: seria assim com o printf antes da chamada. Aqui se imprime na volta.`,
  'modelli.ricorsione-ordine.frase-2': `{hai}: com n = 0 a função sai na hora, sem imprimir.`,
  'modelli.annidati-conta.cosa': 'estes laços aninhados',
  'modelli.annidati-conta.concetto': 'O laço interno recomeça a cada volta do externo: aqui ele roda i vezes, ou seja, 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai}: é o que daria \`j <= i\`. Com \`j < i\` a primeira volta (i = 0) não conta nada.`,
  'modelli.annidati-conta.frase-2': `{hai}: o laço interno não roda sempre {n} vezes: roda i vezes.`,
  'modelli.annidati-stelle.cosa': 'estas estrelas',
  'modelli.annidati-stelle.concetto': 'Para cada linha i o laço interno imprime i símbolos, depois o `\\n` quebra a linha.',
  'modelli.annidati-stelle.frase': `{hai}: um símbolo a mais por linha. j começa em 0 e com \`j < i\` faz i voltas.`,
  'modelli.annidati-stelle.frase-2': `{hai}: o laço interno depende de i: não imprime sempre {n} símbolos.`,
  'modelli.annidati-stelle.frase-3': `{hai}: falta a última linha. Com \`i <= {n}\` a linha {n} também é impressa.`,
  'modelli.break-continue.cosa': 'este break e este continue',
  'modelli.break-continue.concetto': `O \`continue\` pula para a próxima volta; o \`break\` sai do laço, e o {l} daquela volta não acontece.`,
  'modelli.break-continue.frase': `{hai}: o \`continue\` não sai do laço: só pula a volta com i = {a}.`,
  'modelli.break-continue.frase-2': `{hai}: o \`break\` não pula uma volta: sai do laço quando i vale {b}.`,
  'modelli.break-continue.frase-3': `{hai}: o break vem antes do {l}: o {b} não é impresso.`,
  'modelli.do-while.cosa': 'este do-while',
  'modelli.do-while.concetto': 'O do-while confere a condição no fim de cada volta: o corpo roda sempre pelo menos uma vez.',
  'modelli.do-while.frase': `{hai}: é o que um while faria. O do-while executa o corpo antes de conferir.`,
  'modelli.do-while.frase-3': 'O do-while não acrescenta uma volta: confere a condição no fim de cada volta.',
  'modelli.do-while.frase-4': 'Depois da primeira volta a condição já é falsa.',
  'modelli.do-while.frase-2': `{hai}: uma volta a mais. {vero}`,
  'modelli.do-while.frase-5': `{hai}: é o que daria \`i {op}= {b}\`. Com \`i {op} {b}\`, quando i chega a {b} o laço para.`,
  'modelli.do-while.frase-6': `{hai}: você imprimiu i como estava antes da última volta. A última volta também muda i: a conferência vem depois.`,
  'modelli.ternario.cosa': 'estes ternários',
  'modelli.ternario.concetto': '`c ? x : y` vale x se c é verdadeira, y se é falsa.',
  'modelli.ternario.frase-m-vera': `{hai}: para m você pegou o ramo errado. \`a > b\` é verdadeira, então vale o que vem depois do \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai}: para m você pegou o ramo errado. \`a > b\` é falsa, então vale o que vem depois do \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai}: para d você pegou o ramo errado. \`a < b\` é verdadeira, então vale o que vem depois do \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai}: para d você pegou o ramo errado. \`a < b\` é falsa, então vale o que vem depois do \`:\`.`,
  'modelli.ternario.frase-7': `{hai}: você leu os dois ternários ao contrário. Verdadeira → o valor depois do \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` para antes de {b2}: a última volta tem i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai}: é o que \`{b}\` imprimiria. O range para antes do segundo número.`,
  'modelli.for-minore.python.frase-2': `{hai}: você pulou a primeira volta. O range começa justamente em {a}.`,
  'modelli.for-minore.python.frase-3': `{hai}: você parou uma volta antes. \`{b}\` vai até {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` vai de {s2} em {s2} e para antes de {b}: o {b2} também é impresso.`,
  'modelli.for-passo.python.frase': `{hai}: é o que \`{s}\` imprimiria. Aqui o segundo número é {b}, então o {b2} também é impresso.`,
  'modelli.for-passo.python.frase-2': `{hai}: o range começa em {a}, não em {s}. O passo se soma depois da primeira volta.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` conta para trás e para antes de {l}: o {l} não é impresso.`,
  'modelli.for-indietro.python.frase': `{hai}: você imprimiu também o {l}. O range para antes: a última volta tem i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai}: o range começa justamente em {n}: a primeira volta imprime {n}.`,
  'modelli.for-indietro.python.frase-3': `{hai}: você parou uma volta antes. O {l} também é impresso.`,
  'modelli.while-somma.python.concetto': 'O while sai quando a condição fica falsa: depois de `while i < n` a variável i vale n.',
  'modelli.while-somma.python.frase': `{hai}: é como se o \`i += 1\` viesse antes de \`s += i\`. Aqui s soma i e só depois i cresce.`,
  'modelli.while-dimezza.python.concetto': '`//` é a divisão inteira: 7 // 2 dá 3, e dividindo por dois se chega a 1 sem casas decimais.',
  'modelli.while-dimezza.python.frase': `{hai}: você manteve as casas decimais, como faria \`n /= 2\`. \`n //= 2\` é a divisão inteira: joga fora a parte decimal.`,
  'modelli.array-somma.python.frase': `{hai}: você deixou o último de fora. \`range({k})\` vai até {k2}: a última volta lê \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` é a divisão inteira; `/` em Python sempre mantém as casas decimais, mesmo entre dois int.',
  'modelli.media-array.python.frase': `{hai}: \`s // {k}\` é a divisão inteira: a parte decimal se perde.`,
  'modelli.media-array.python.frase-2': `{hai}: em Python a \`/\` mantém as casas decimais, não trunca como a \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai}: a \`//\` não arredonda: vai para baixo.`,
  'modelli.media-array.java.frase': `{hai}: \`s / {k}\` é entre dois int: em Java (como em C, e não como em Python) a divisão continua inteira e a parte decimal se perde.`,
  'modelli.divisione-double.java.frase': `{hai}: \`a / b\` é calculado entre int, antes de ir para m. Em Java, como em C, a divisão entre dois int trunca: o double recebe um número já truncado.`,
  'modelli.diviso-due.python.concetto': 'Em Python `//` é a divisão inteira e `/` sempre mantém as casas decimais, mesmo entre dois int.',
  'modelli.diviso-due.python.frase': `{hai}: \`a // 2\` é a divisão inteira: dá um int, sem casas decimais.`,
  'modelli.diviso-due.python.frase-2': `{hai}: em Python a \`/\` não trunca como em C ou em Java: \`a / 2\` também mantém as casas decimais.`,
  'modelli.diviso-due.python.frase-3': `{hai}: \`a // 2\` não arredonda: vai para baixo.`,
  'modelli.resto-negativi.python.concetto': 'Em Python a `//` vai para baixo e o resto tem o sinal do divisor: -7 // 3 dá -3 e -7 % 3 dá 2.',
  'modelli.resto-negativi.python.frase': `{hai}: é assim que fazem C e Java, que truncam em direção ao zero. Em Python a \`//\` vai para baixo.`,
  'modelli.resto-negativi.python.frase-2': `{hai}: em Python o resto tem o sinal do divisor, ou seja, de b, não do dividendo.`,
  'modelli.resto-negativi.python.frase-3': `{hai}: a \`//\` arredonda para baixo, não em direção ao zero.`,
  'modelli.piu-uguale.python.frase': `{hai}: \`range(1, {n})\` vai até {n2}: o i = {n2} também faz a sua volta.`,
  'modelli.swap-valore.python.concetto': 'A função recebe os valores: reatribuir a e b dentro da função não mexe em x e y.',
  'modelli.swap-valore.python.frase': `{hai}: a e b são nomes da função. Reatribuir eles não muda x e y.`,
  'modelli.swap-valore.python.frase-2': `{hai}: dentro da função a troca acontece de verdade. Quem troca são a e b, não x e y.`,
  'modelli.array-in-funzione.python.concetto': 'A lista vai para a função do jeito que é: `v[n] *= …` muda o próprio a. Já n é um nome da função: `n -= 1` não mexe no n de fora.',
  'modelli.array-in-funzione.python.frase': `{hai}: uma lista não é copiada. A função trabalha nos mesmos elementos de a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai}: já o n não. O \`n -= 1\` da função não mexe no n de fora.`,
  'modelli.array-in-funzione.java.concetto': 'Um array é passado como referência: a função muda o próprio a. Já um int é passado como cópia.',
  'modelli.somma-cifre.python.concetto': '`n % 10` é o último dígito, `n // 10` tira o último dígito. O caso base retorna o dígito que sobra.',
  'modelli.ricorsione-ordine.python.concetto': 'O print vem depois da chamada: imprime na volta, então do menor para o maior.',
  'modelli.ricorsione-ordine.python.frase': `{hai}: seria assim com o print antes da chamada. Aqui se imprime na volta.`,
  'modelli.annidati-conta.python.concetto': 'O laço interno recomeça a cada volta do externo: `range(i)` faz i voltas, ou seja, 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai}: é o que daria \`range(i + 1)\`. Com i = 0, \`range(i)\` não faz nenhuma volta.`,
  'modelli.annidati-stelle.python.concetto': 'Para cada linha i o laço interno imprime i símbolos, depois o `print()` quebra a linha.',
  'modelli.annidati-stelle.python.frase': `{hai}: um símbolo a mais por linha. \`range(i)\` faz i voltas, não i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai}: falta a última linha. \`range(1, {n})\` vai até {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'Para cada linha i o laço interno imprime i símbolos, depois o `println()` quebra a linha.',
};
