// O plano para quem trabalha (js/ore.js): os tempos «cerca de», as linhas da semana, o que não cabe e as escolhas.
export default {
  'ore.circa-min': 'cerca de {m} min',
  'ore.circa-ore': { one: 'cerca de {n} hora', other: 'cerca de {n} horas' },
  'ore.circa-h': 'cerca de {h} h',
  'ore.circa-h-min': 'cerca de {h} h {m}',
  'ore.opzione-cuscinetto': 'Uso também os dias de folga',
  'ore.opzione-un-ripasso': 'Uma revisão só para os tópicos novos, não duas',
  'ore.opzione-tetto': 'Nos dias de trabalho estudo 3 horas, não 2',
  'ore.giorni-brevi': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  'ore.libere': '{circa} livres',
  'ore.niente-ore-libere': 'nenhuma hora livre',
  'ore.giorno': '{g} {n}',
  'ore.lavoro': 'trabalho {turni}',
  'ore.voce-tema': 'exercício de prova ({circa})',
  'ore.argomento': 'tópico',
  'ore.voce-generale': 'revisão geral ({circa})',
  'ore.esame': 'Prova',
  'ore.voce-cuscinetto': '{nome}: dia de folga, para recuperar',
  'ore.oggi-niente': 'Hoje você não tem horas livres para estudar{lav}.',
  'ore.oggi-hai': 'Hoje você tem {liberi}{lav}: {lista}.',
  'ore.oggi-hai-vuoto': 'Hoje você tem {liberi}{lav}. Não tem nada no plano para hoje.',
  'ore.per-esame': '{circa} para {nome}',
  'ore.un-esame': 'uma prova',
  'ore.mancano': 'Até a prova de {nome} faltam {circa}.',
  'ore.questo-esame': 'esta prova',
  'ore.recuperi': '{testo} · você recupera {circa}',
  'ore.ripiego': 'Com as horas que você tem, não cabe tudo. Você pode me mandar mais dias de estudo («estudo das 9 às 21») ou pensar na data seguinte: você decide.',
  'ore.mancano-ancora': 'Ainda faltam {circa}.',
  'ore.ora-ci-sta': 'Agora cabe.',
};
