// Textos da página embaixo da barra (português do Brasil): saudação, números do curso, cards das provas, histórico,
// baralhos, janelas da prova e das configurações, backup.
export default {
  // saudação e linha de baixo
  'pagina.saluto-notte': 'Ainda acordado',
  'pagina.saluto-mattina': 'Bom dia',
  'pagina.saluto-pomeriggio': 'Boa tarde',
  'pagina.saluto-sera': 'Boa noite',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} cartão para revisar', other: '{n} cartões para revisar' },
  'pagina.sotto-serie': { one: '{n} dia seguido', other: '{n} dias seguidos' },
  'pagina.sotto-niente': 'Nada pendente hoje.',
  'pagina.sotto-vuoto': 'Seu histórico, o plano de estudo e a revisão. Tudo aqui, tudo seu.',
  // cabeçalho
  'pagina.sottotitolo': 'assistente de estudo',
  'pagina.esporta': 'Exportar',
  'pagina.impostazioni': 'Configurações',
  'pagina.suggerimento': 'Passe o mouse sobre a barra lá em cima, aperte <kbd>/</kbd> para escrever ou segure <kbd>{tasti}</kbd> para falar.',
  // os números
  'pagina.media-ponderata': 'Média ponderada',
  'pagina.media-dettaglio': { one: 'aritmética {media} · {n} nota', other: 'aritmética {media} · {n} notas' },
  'pagina.primo-voto': 'registre a primeira nota pela barra',
  'pagina.base-laurea': 'Base de formatura',
  'pagina.base-formula': 'média × 110 / 30',
  'pagina.crediti': 'Créditos',
  'pagina.cfu-alla-laurea': '{n} créditos para a formatura',
  'pagina.questa-settimana': 'Esta semana',
  'pagina.minuti-settimana': 'Minutos de estudo nos últimos 7 dias',
  'pagina.giorno-ore': '{giorno}: {ore}',
  'pagina.iniziali-giorni': ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  // provas
  'pagina.prossimi-esami': 'Próximas provas',
  'pagina.nuovo-esame': 'Nova prova',
  'pagina.vuoto-scrivi': 'Escreva na barra lá em cima:',
  'pagina.vuoto-comando': 'prova de cálculo 2 dia 15 de janeiro 4 créditos',
  'pagina.vuoto-oppure': 'ou {bottone}',
  'pagina.prova-esempio': 'teste com os dados de exemplo',
  'pagina.programma-aggiungi': '+ Ementa da prova',
  'pagina.giorno-cuscinetto': 'dia de folga',
  'pagina.ripasso-generale': 'revisão geral',
  'pagina.niente-di-nuovo': 'nada de novo',
  'pagina.programma-pronto': '<b>{pct}% da ementa</b> · hoje: {oggi}',
  'pagina.data-da-decidere': 'Data a definir',
  'pagina.quando-cfu': '{quando} · {cfu} créditos',
  'pagina.giorni-maiuscolo': { one: 'DIA', other: 'DIAS' },
  'pagina.ore-studiate': '{fatte} de {tot} h estudadas',
  'pagina.ore-oggi': '<b>{h} h</b> hoje',
  'pagina.oggi-in-pari': 'em dia hoje',
  'pagina.focus': 'Foco',
  'pagina.ripassa': 'Revisar',
  'pagina.ripassa-n': 'Revisar {n}',
  'pagina.interrogami': 'Me testa',
  'pagina.modifica-segna-voto': 'Editar · Registrar nota',
  // histórico e revisão
  'pagina.libretto': 'Histórico',
  'pagina.segna-voto': 'Registrar uma nota',
  'pagina.ripasso': 'Revisão',
  'pagina.da-file': 'De um arquivo',
  'pagina.libretto-vuoto': 'Nenhuma prova feita. Escreva na barra <kbd>tirei 28 em física</kbd>.',
  'pagina.col-esame': 'Prova',
  'pagina.col-cfu': 'Créditos',
  'pagina.col-voto': 'Nota',
  'pagina.col-data': 'Data',
  'pagina.idoneo': 'aprovado',
  'pagina.voto-lode': '{voto}L',
  'pagina.modifica-esame': 'Editar {nome}',
  'pagina.libretto-esami': '{n} provas · {cfu} créditos',
  'pagina.libretto-media': 'média <b>{media}</b> · base <b>{base}</b>',
  'pagina.mazzi-vuoto': 'Nenhum cartão ainda. Escreva <kbd>cartão: pergunta = resposta</kbd> ou arraste um PDF para a janela.',
  'pagina.esame-tolto': 'Prova removida',
  'pagina.senza-esame': 'Sem prova',
  'pagina.n-carte': { one: '{n} cartão', other: '{n} cartões' },
  'pagina.da-ripassare-oggi': 'para revisar hoje',
  'pagina.piede': 'O Lode é open source (MIT). Seus dados ficam neste navegador: sem conta, sem servidor.',
  'pagina.importa-backup': 'Importar um backup',
  // janela da prova
  'pagina.esame-correggi': 'Corrija os dados ou registre a nota.',
  'pagina.esame-aiuto': 'Você também pode escrever na barra: «prova de física 2 dia 20 de fevereiro 6 créditos».',
  'pagina.campo-nome': 'Nome',
  'pagina.esempio-esame': 'Cálculo 2',
  'pagina.campo-cfu': 'Créditos',
  'pagina.campo-data': 'Data',
  'pagina.campo-data-appello': 'Data da prova',
  'pagina.campo-voto': 'Nota',
  'pagina.campo-voto-nota': 'vazio se você ainda não fez',
  'pagina.trenta-e-lode': '30 com louvor',
  'pagina.idoneita': 'Aprovado sem nota',
  'pagina.campo-ore': 'Horas de estudo previstas',
  'pagina.campo-ore-nota': 'para o plano',
  'pagina.ore-segnaposto': '10 × créditos',
  'pagina.elimina': 'Excluir',
  'pagina.annulla': 'Cancelar',
  'pagina.salva': 'Salvar',
  'pagina.conferma-elimina': 'Excluir {nome}? As horas e os cartões dela ficam, sem prova.',
  'pagina.esame-eliminato': 'Prova excluída',
  'pagina.salvato': 'Salvo',
  'pagina.esame-aggiunto': 'Prova adicionada',
  // janela das configurações
  'pagina.impostazioni-aiuto': 'Tudo fica neste computador. A chave da sua IA vai só para o serviço que você escolher.',
  'pagina.campo-tuo-nome': 'Seu nome',
  'pagina.esempio-nome': 'Júlia',
  'pagina.campo-corso': 'Curso',
  'pagina.esempio-corso': 'Engenharia de Computação',
  'pagina.campo-cfu-laurea': 'Créditos do curso',
  'pagina.campo-lode-vale': 'O louvor vale',
  'pagina.campo-focus': 'Foco (minutos)',
  'pagina.campo-pausa': 'Pausa (minutos)',
  'pagina.rintocco': 'Sinal sonoro no fim do foco',
  'pagina.aspetto-chiaro': 'Tema claro',
  'pagina.campo-ai': 'Sua IA',
  'pagina.campo-ai-nota': 'opcional, paga por uso: quem paga o serviço é você',
  'pagina.solo-locale': 'Só o cérebro local (grátis)',
  'pagina.campo-chiave': 'Chave',
  'pagina.campo-chiave-nota': 'é criada no site do serviço',
  'pagina.chiave-segnaposto': 'cole a chave',
  'pagina.voce-alta': 'Ler as respostas em voz alta',
  'pagina.ai-attiva': 'IA <b>ativa</b>: {nome}.',
  'pagina.senza-chiave': 'Sem chave o Lode funciona do mesmo jeito: comandos, timer, histórico e revisão são todos locais; no app também tem o cérebro local grátis.',
  'pagina.cancella-tutto': 'Apagar tudo',
  'pagina.conferma-azzera': 'Apagar todos os dados do Lode deste navegador? É bom exportar antes.',
  'pagina.dati-cancellati-chiave': 'Dados apagados, inclusive a chave de {nome}: revogue também na sua conta ({sito})',
  'pagina.dati-cancellati': 'Dados apagados',
  'pagina.chiave-cancellata': 'Chave de {nome} apagada daqui: revogue também na sua conta ({sito})',
  'pagina.impostazioni-salvate': 'Configurações salvas',
  'pagina.ai-collegata': '{nome} conectada',
  'pagina.ai-collegata-modello': '{nome} conectada · {modello}',
  'pagina.chiave-non-valida': 'A chave não é válida',
  'pagina.chiave-non-verificabile': 'Não consigo verificar a chave agora',
  // backup e dados de exemplo
  'pagina.backup-scaricato': 'Backup baixado',
  'pagina.conferma-importa': 'Substituir os dados atuais por este backup?',
  'pagina.backup-importato': 'Backup importado',
  'pagina.non-backup': 'Este arquivo não é um backup do Lode',
  'pagina.conferma-esempio': 'Carregar os dados de exemplo no lugar dos seus?',
  'pagina.esempio-caricato': 'Dados de exemplo carregados: passe o mouse sobre a barra lá em cima',
};
