// «Seguir o projeto» na barra (português do Brasil): pílula, cartões «Sigo…?», «O que está mudando»,
// «Pronto. Em palavras simples», «Testado?» e «Coisas novas».
export default {
  'progetto.solo-app': 'Seguir um projeto só funciona no app de desktop do Lode.',
  'progetto.provo': 'testando…',
  'progetto.file-cambiati': '{n} arquivos +{piu} −{meno}',
  'progetto.fatto-non-provato': 'pronto · não testado',
  'progetto.oggi-non-provato': '{nome}: não testado',
  'progetto.oggi-esito': '{nome}: {breve}',
  'progetto.oggi-sta-cambiando': '{nome}: mudando',
  'progetto.ultima-prova-alle': 'O último teste, às {ora}',
  'progetto.vedi': 'Ver',
  'progetto.esito': 'Resultado',
  'progetto.prova': 'Testar',
  'progetto.provato': 'Testado?',
  'progetto.cosa-e-cambiato': 'O que mudou',
  'progetto.cosa-sta-cambiando': 'O que está mudando',
  'progetto.serve-seguito': 'Precisa de um projeto seguido no app: escreva «segue o projeto».',
  'progetto.non-seguo-nome': 'Não sigo nenhum projeto chamado «{nome}».',
  'progetto.non-seguo-niente': 'Não sigo nenhum projeto. Escreva **segue o projeto** e escolha a pasta do laboratório.',
  'progetto.capito-testo': 'O Lode olha os arquivos e confere se o código foi testado: ele não escreve código no seu lugar. Se você usa um agente ou uma IA, o que é permitido quem decide é a sua disciplina: pergunte ao professor. O diário é um registro para você, não uma prova para o professor: é o que o Lode viu, e ele não sabe quem escreveu as linhas. Para um trabalho avaliado, marque o projeto como "avaliado": o Lode vai dizer onde olhar e o que um erro quer dizer, mas não vai mostrar a correção.',
  'progetto.prima-di-cominciare': 'Antes de começar',
  'progetto.ho-capito': 'Entendi',
  'progetto.solo-app-desktop': 'Seguir um projeto só funciona no **app de desktop** do Lode: lá eu olho a pasta do seu laboratório.',
  'progetto.va-bene-non-seguo': 'Tudo bem, não sigo nada.',
  'progetto.seguo-gia': 'Já sigo **{nome}**.',
  'progetto.seguo-domanda': 'Sigo <b>{nome}</b>?',
  'progetto.seguo-aria': 'Sigo {nome}?',
  'progetto.seguo-spiega': 'Olho os arquivos e guardo as versões na pasta do Lode: na sua pasta eu não escrevo. Os comandos que você confirma (por exemplo make) sim, como no terminal. Não sei quem escreve as linhas (você, um agente ou um copia e cola): digo o que mudou e se você testou.',
  'progetto.nota-windows': 'Enquanto eu sigo a pasta, o Windows não deixa você renomear ou mover: antes escreva «para de seguir».',
  'progetto.corso': 'Disciplina',
  'progetto.nessun-corso': 'Nenhuma disciplina',
  'progetto.valutato': 'Projeto avaliado (entrega)',
  'progetto.valutato-spiega': 'Digo onde olhar, mas sem correções prontas',
  'progetto.no-diario': 'Não escrever o diário deste projeto',
  'progetto.no-diario-spiega': 'Nenhum nome de arquivo ou de função vai para o vault',
  'progetto.n-file': { one: '{n} arquivo', other: '{n} arquivos' },
  'progetto.segui': 'Seguir',
  'progetto.annulla': 'Cancelar',
  'progetto.annullato': 'Cancelado.',
  'progetto.non-seguo-niente-nota': 'Não sigo nada.',
  'progetto.seguo-fatto': 'Sigo {nome}.',
  'progetto.seguo-fatto-nota': 'Digo o que muda e se você testou. As versões eu guardo na pasta do Lode.',
  'progetto.seguo-sintesi': 'sigo {nome}',
  'progetto.smetto-domanda': 'Paro de seguir <b>{nome}</b>?',
  'progetto.smetto-spiega': 'Apago as cópias que guardei na pasta do Lode. Seus arquivos eu não toco.',
  'progetto.smetti-di-seguire': 'Parar de seguir',
  'progetto.continuo-a-seguire': 'Continuo seguindo {nome}.',
  'progetto.non-seguo-piu': 'Não sigo mais {nome}.',
  'progetto.non-seguo-piu-nota': 'As cópias do Lode foram apagadas. Seus arquivos eu não toquei.',
  'progetto.smesso-sintesi': 'parei {nome}',
  'progetto.etichetta-nuovo': 'novo',
  'progetto.etichetta-tolto': 'removido',
  'progetto.etichetta-grande': 'arquivo grande: só as contagens',
  'progetto.etichetta-spazi': 'só espaços ou quebras de linha',
  'progetto.etichetta-cambiato': 'alterado',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Fechar',
  'progetto.diff-grande': 'Arquivo grande (+{piu} −{meno}): não mostro o detalhe.',
  'progetto.diff-solo-spazi': 'Só mudam espaços no fim das linhas ou as quebras de linha.',
  'progetto.diff-aria': 'Alterações em {file}',
  'progetto.diff-tagliato': '… o resto eu não mostro',
  'progetto.niente-di-diverso': 'Nada de diferente.',
  'progetto.niente-di-nuovo': 'Nada de novo.',
  'progetto.niente-di-nuovo-dalle': 'Nada de novo desde as {ora}.',
  'progetto.nome-dalle': '{nome} desde as {ora}',
  'progetto.prova-adesso': 'Testar agora',
  'progetto.visto': 'Visto',
  'progetto.provato-breve': 'testado',
  'progetto.prova-il-progetto': 'Testar o projeto',
  'progetto.visto-fatto': 'Visto.',
  'progetto.visto-nota': 'Daqui em diante mostro só as alterações novas.',
  'progetto.visto-sintesi': 'visto',
  'progetto.fatto-titolo': 'Pronto. Em palavras simples',
  'progetto.vedi-le-modifiche': 'Ver as alterações',
  'progetto.modifiche-tratto': 'Alterações · {da}–{a}',
  'progetto.provato-si': '**Sim**: o código de {nome} é o que foi testado às {ora} ({breve}).',
  'progetto.provato-no-cambiato': '<b>Não</b>: depois do último teste ({ora}) o código de {nome} mudou.',
  'progetto.provato-no-cambiato-alle': '<b>Não</b>: depois do último teste ({ora}) o código de {nome} mudou, a última vez às {ultima}.',
  'progetto.provato-no-mai': '<b>Não</b>: você ainda não testou {nome} com o Lode.',
  'progetto.provato-nota': 'Não sei quem escreveu as linhas: só sei se o código de agora passou por um teste.',
  'progetto.comando-manca': 'Para testar {nome} falta {cosa}',
  'progetto.comando-come': 'Como eu testo {nome}?',
  'progetto.comando-lancia': 'Agora tem testes .in/.out: para rodar o programa preciso de um novo sim.',
  'progetto.comando-cambiato': 'Os arquivos do projeto mudaram: o comando de antes não basta mais.',
  'progetto.comando-userei': 'Para testar eu usaria <code>{comando}</code>',
  'progetto.comando-nota': 'Só executo o comando que você confirma na janela do sistema, nunca um proposto por um agente. Não é uma sandbox: o programa roda no seu computador, como no terminal, e pode escrever arquivos na sua pasta.',
  'progetto.riprova': 'Tentar de novo',
  'progetto.usa-questo': 'Usar este',
  'progetto.scrivo-io': 'Eu escrevo o comando',
  'progetto.cambia': 'Mudar',
  'progetto.comando-aria': 'Comando para testar',
  'progetto.usa-questo-comando': 'Usar este comando',
  'progetto.non-eseguo': 'Não executo nada.',
  'progetto.non-confermato': 'Você não confirmou o comando.',
  'progetto.comando-confermato': 'Comando confirmado.',
  'progetto.comando-confermato-nota': 'Para este projeto uso sempre ele, até os arquivos mudarem de forma.',
  'progetto.comando-confermato-sintesi': 'comando confirmado',
  'progetto.uscita-caso': '— teste {caso} —',
  'progetto.non-seguo-questo': 'Não sigo este projeto.',
  'progetto.sto-gia-provando': 'Já estou testando este projeto: só um instante.',
  'progetto.niente': 'nada',
  'progetto.riga-vuota': 'uma linha vazia',
  'progetto.caso-ok': 'Teste {caso}',
  'progetto.caso-ok-codice': 'Teste {caso} · passa, mas o programa sai com o código {codice}',
  'progetto.caso-errore': 'Teste {caso}: {errore}',
  'progetto.caso-scaduto': 'Teste {caso}: não terminou a tempo. Um laço que não para, ou o programa está esperando outra entrada?',
  'progetto.caso-troncato': 'Teste {caso}: escreveu demais (mais de 200 KB) e eu parei.',
  'progetto.caso-crash': 'Teste {caso}: o programa parou com um erro.',
  'progetto.caso-crash-segnale': 'Teste {caso}: o programa parou com um erro ({segnale}).',
  'progetto.caso-crash-codice': 'Teste {caso}: o programa parou com um erro (código {codice}).',
  'progetto.caso-diverso': 'Teste {caso} · linha {riga}: esperado {atteso}, obtido {ottenuto}',
  'progetto.sintassi-ok': 'A sintaxe está ok',
  'progetto.sintassi-errore': 'Erro de sintaxe',
  'progetto.make-ok': 'O make funcionou',
  'progetto.make-errore': 'O make não funcionou',
  'progetto.compila': 'Compila',
  'progetto.non-compila': 'Não compila',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si} e passa no teste.', other: '{si} e passa em todos os {n} testes.' },
  'progetto.esito-senza-prove': '{si}. Não tem testes .in/.out: não rodei o programa.',
  'progetto.esito-non-passano': { one: 'Um teste de {tot} não passa.', other: '{n} testes de {tot} não passam.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no}: {file}.',
  'progetto.non-compila-file-riga': '{no}: {file}, linha {riga}.',
  'progetto.non-partita': 'O teste não começou.',
  'progetto.passano': 'Passam: {nomi}',
  'progetto.saltate': { one: 'Um teste pulado: {motivo}.', other: '{n} testes pulados: {motivo}.' },
  'progetto.avvisi': { one: '{n} aviso do compilador.', other: '{n} avisos do compilador.' },
  'progetto.cambiato-durante': '<b>O código mudou enquanto eu testava: refaço?</b>',
  'progetto.rifai': 'Refazer',
  'progetto.prova-di-nuovo': 'Testar de novo',
  'progetto.nota-cose-nuove': 'Do dicionário do Lode: só funções da biblioteca padrão. Não vê as ideias, só os nomes.',
  'progetto.file-riga': '{file}, linha {riga}',
  'progetto.domanda-orale': 'Pergunta de prova oral:',
  'progetto.risposta': 'Resposta',
  'progetto.cose-nuove': 'Coisas novas: {nomi}',
  'progetto.mettila-nel-ripasso': 'Colocar na revisão',
  'progetto.la-so-gia': 'Já sei',
  'progetto.nel-ripasso': 'Na revisão.',
  'progetto.la-sai-gia': 'você já sabe',
};
