// Sistemas de classificação (português): nomes, créditos, nota final, mentions e classes (js/sistemi.js).
export default {
  'sistemi.scelta': 'Sistema de classificação',
  'sistemi.nome.it': 'Itália · 18–30 cum laude',
  'sistemi.nome.es': 'Espanha · 0–10',
  'sistemi.nome.fr': 'França · 0–20',
  'sistemi.nome.de': 'Alemanha · 1,0–5,0',
  'sistemi.nome.pt': 'Portugal · 0–20',
  'sistemi.nome.br': 'Brasil · 0–10',
  'sistemi.nome.uk': 'Reino Unido · 0–100 %',
  'sistemi.nome.us': 'Estados Unidos · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'créditos',
  'sistemi.crediti.uk': 'créditos',
  'sistemi.crediti.us': 'horas de crédito',
  'sistemi.ponderata': 'Média ponderada',
  'sistemi.finale.it': 'Base de licenciatura (em 110)',
  'sistemi.finale.es': 'Média do expediente',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Nota final (Gesamtnote)',
  'sistemi.finale.pt': 'Média final',
  'sistemi.finale.br': 'Coeficiente de rendimento (CR)',
  'sistemi.finale.uk': 'Classe do diploma',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'sem mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Reprovado',
  'sistemi.idoneo': 'aprovado',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
