// «O que imprime?», o cartão dos exercícios (português do Brasil).
export default {
  'stampa.titolo': 'O que imprime?',
  'stampa.anteprima': 'O que {cosa} imprime?',
  'stampa.risposta-assente': 'Essa resposta não existe.',
  'stampa.hai-scritto-altro': 'Você escreveu `{uscita}`: não é isso que ele imprime.',
  'stampa.nessuna-risposta': 'Nenhuma resposta.',
  'stampa.aria-codice': 'Código {lingua}',
  'stampa.non-riesco': 'Hoje não consigo preparar as perguntas de {lingua}. Tente de novo daqui a pouco.',
  'stampa.conto': '{i} de {n}',
  'stampa.scrivi-uscita': 'Escreva a saída exata',
  'stampa.scegli-uscita': 'Escolha a saída · teclas 1-4',
  'stampa.aria-campo': 'O que o programa imprime',
  'stampa.segnaposto': 'Escreva o que ele imprime',
  'stampa.controlla': 'Conferir <kbd>Enter</kbd>',
  'stampa.piu-righe': 'Mais de uma linha? Separe com um espaço.',
  'stampa.aria-risposta': 'Resposta {n}: {uscita}',
  'stampa.giusto': 'Certo · calculado pelo Lode',
  'stampa.stampa-giusta': 'Imprime <code>{uscita}</code>.',
  'stampa.avanti': 'Próxima <kbd>Enter</kbd>',
  'stampa.com-e-andata': 'Ver como foi <kbd>Enter</kbd>',
  'stampa.tutte-giuste': 'Acertou todas. As respostas foram calculadas pelo Lode.',
  'stampa.da-rinforzare': 'Para reforçar: {nomi}. Volte amanhã.',
  'stampa.secondi': { one: '{n} segundo', other: '{n} segundos' },
  'stampa.ancora-una': 'Mais uma',
  'stampa.sintesi': 'O que imprime? {punti} de {tot}',
};
