// Textos da sincronização entre computadores (português do Brasil): o que é criptografado e o que fica aberto, a linha
// de status e os avisos (docs/SINCRONIZZAZIONE.md §10.7 e §12). O README diz as mesmas coisas: veja js/sync-testi.js.
export default {
  'sync.cifrati': 'os dados do Lode no diário (provas, notas, cartões e revisões, sessões, perfil, configurações): não as páginas para o Obsidian que o Lode gera a partir deles, aqui embaixo',
  'sync.in-chiaro': [
    'anotações, Sbobine, arquivos para o Anki, diários dos Progetti',
    'Orario.md com as salas',
    'as páginas que o Lode escreve para o Obsidian, geradas justamente desses dados: Esami (notas, média, créditos e horas estudadas por prova), Memoria (horas de estudo do mês, em que parte do dia você estuda, a sequência de dias, as definições erradas e quantas vezes), Home (a próxima prova, quantos cartões há para revisar), Corsi, Glossario',
    'nomes, tamanhos e horários dos arquivos (quando você estuda)',
    'quantos computadores existem, quantos arquivos cada um escreve e quantas ações tem em cada arquivo (um arquivo por dia)',
    'o arquivo do grupo (salt e verificação da senha, quando nasceu e em qual computador, a impressão digital do dati.json anterior)',
    'quando a senha mudou',
    'o dati.json mínimo que diz «Atualize o Lode»',
  ],
  'sync.sul-computer': 'No computador o diário do Lode fica aberto, protegido só pela sua conta do sistema.',
  'sync.cronologia': 'No histórico do serviço de nuvem fica o que passou sem criptografia antes da senha.',
  'sync.dimenticata': 'Se você esquecer a senha, nada se perde: cada computador tem seus dados no disco. Com «Esqueci a senha» você escolhe uma nova, e os outros computadores vão pedir ela.',
  'sync.nuova-password': 'Escolha uma senha nova. Os outros computadores vão pedir ela. Nenhum dado se perde: cada computador tem os seus no disco.',
  'sync.smetti': 'O Lode vai copiar o vault para uma pasta fora de {servizio} e usar essa. Os outros computadores continuam sincronizando entre si. Para parar em todos, faça isso em cada computador.',
  'sync.la-cartella-cloud': 'a pasta da nuvem',
  'sync.prima': 'Antes de sincronizar, atualize o Lode em todos os computadores.',
  'sync.sperimentale': 'É nova e experimental: testada a fundo com um simulador de vários computadores e uma nuvem malvada, mas ainda não por muitos estudantes. Antes de ligar, o Lode guarda uma cópia de tudo: o vault de agora fica onde está, intacto, e os dados do Lode vão também para a pasta «copie» dos dados do Lode. Se algo não bater, conte pra gente no GitHub (Issues de W1kicartel/Lode).',
  // a linha de status
  'sync.spenta': 'Desligada · provas, notas e cartões ficam neste computador',
  'sync.fermo': 'O diário do Lode neste computador não pode ser lido.',
  'sync.solo-qui': 'Só neste computador · não sincronizado',
  'sync.la-tua-cartella': 'sua pasta da nuvem',
  'sync.stato-password': 'Em pausa: digite a senha para sincronizar.',
  'sync.rigenerato-altra': 'Em outro computador foi escolhida outra senha ao mesmo tempo: digite aquela.',
  'sync.rigenerato': 'A senha mudou em outro computador: digite a nova para sincronizar.',
  'sync.sparito': 'A pasta do Lode no vault sumiu: foi movida ou apagada?',
  'sync.in-arrivo': 'Recebendo os dados dos outros computadores… ({dove})',
  'sync.da-migrare': 'Esperando os dados da nuvem…',
  'sync.scrittura': 'O disco está cheio (ou não dá para gravar): as últimas alterações estão esperando e eu tento de novo sozinho.',
  'sync.versione': 'Sincronizado com {dove} · outro computador tem um Lode mais novo: atualize',
  'sync.in-pari': 'Sincronizado com {dove}',
  'sync.in-pari-cifrato': 'Sincronizado com {dove} · criptografado',
  'sync.in-pari-ora': 'Sincronizado com {dove} · verificado às {ora}',
  'sync.in-pari-cifrato-ora': 'Sincronizado com {dove} · criptografado · verificado às {ora}',
  'sync.altro-stato': 'Sincronização: {stato}',
  'sync.in-avvio': 'iniciando',
  // os avisos
  'sync.avviso-clone': 'Este computador parece uma cópia de outro: a partir de agora ele tem um nome novo. Nada se perdeu.',
  'sync.avviso-orologio': 'O relógio de outro computador parece muito adiantado: confira a data e a hora.',
  'sync.avviso-rovinato-mio': 'Um arquivo do Lode deste computador na pasta da nuvem estava corrompido ou adulterado: separei e refiz a partir do diário.',
  'sync.avviso-rovinato-altro': 'Um arquivo do Lode de outro computador está corrompido ou adulterado: vou pular até ele voltar a ser legível.',
  'sync.avviso-scrittura': 'O disco está cheio ou não dá para gravar: as últimas alterações ainda não estão no diário. Tento de novo a cada volta e quando você fechar o Lode.',
  'sync.avviso-recupero': 'Não deu para gravar o diário: as alterações daquele momento estão num arquivo separado na pasta de dados do Lode.',
  'sync.avviso-portachiavi': 'As Chaves (Keychain) não deram a senha do Lode (permissão negada, ou o Lode foi atualizado): digite de novo.',
  'sync.avviso-gruppi-doppi': 'Na pasta da nuvem há dois grupos do Lode, um criptografado e outro não: não vou juntar sozinho.',
  'sync.avviso-lode-vecchia': 'Uma versão antiga do Lode gravou dados em .lode/dati.json: atualize. Eles não entram sozinhos: tem uma cópia na pasta de dados do Lode, e os registros novos se importam com «Importar os acréscimos».',
  'sync.avviso-altra-password': 'Em outro computador foi escolhida outra senha ao mesmo tempo: digite aquela.',
  'sync.avviso-manomesso': 'O arquivo do grupo do Lode na pasta da nuvem foi alterado por fora (não bate com a senha): não vou usar. Confira a pasta da nuvem.',
  'sync.avviso-gruppo-chiaro': 'O arquivo do grupo do Lode diz «sem senha», mas os dados dos outros computadores estão criptografados: foi adulterado? Não publico nada até voltar ao normal.',
  'sync.avviso-parametri': 'Este vault foi protegido por um Lode mais novo: atualize.',
};
