// Textos das páginas que o Lode escreve no vault para o estudante (português do Brasil): Home, Esami, Glossario, as
// páginas das disciplinas e a Memoria. Não estão aqui os nomes de notas, pastas, seções e chaves que o código lê de novo:
// esses ficam como estão no código (vão virar a tabela NOMI).
export default {
  // a memória
  'vault.prop-gioco': 'jogos',
  'vault.prop-ripasso': 'revisão dos cartões',
  'vault.prop-stelle': 'reler as ★',
  'vault.prop-orale': 'perguntas rápidas',
  'vault.prop-focus': 'foco',
  'vault.prop-stampa': 'o que imprime',
  'vault.prop-voce': '{nome} ({si} de {tot})',
  'vault.memoria-proposte': 'Das sugestões do Lode, você aceita principalmente: {elenco}.',
  'vault.memoria-titolo': 'O que eu sei sobre você',
  'vault.memoria-commento': 'Esta nota é escrita pelo Lode. Você pode ler e também corrigir: a seção «{sezione}» eu leio toda vez que uso a IA.',
  'vault.titolo-in-breve': 'Em resumo',
  'vault.memoria-lezioni': { one: '{n} aula anotada', other: '{n} aulas anotadas' },
  'vault.memoria-definizioni': { one: '{n} definição', other: '{n} definições' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni}: **{sicure} seguras**, {deboli} para reforçar, {mai} ainda para jogar.',
  'vault.memoria-serie': { one: 'Sequência de estudo: {n} dia seguido. Este mês: {h} h.', other: 'Sequência de estudo: {n} dias seguidos. Este mês: {h} h.' },
  'vault.memoria-fascia': 'Você estuda principalmente de **{fascia}**.',
  'vault.fascia-mattina': 'manhã',
  'vault.fascia-pomeriggio': 'tarde',
  'vault.fascia-sera': 'noite',
  'vault.titolo-da-rinforzare': 'Para reforçar',
  'vault.sbagliata': { one: 'errada {n} vez de {tot}', other: 'errada {n} vezes de {tot}' },
  'vault.niente-per-ora': 'Nada, por enquanto.',
  'vault.titolo-sicure': 'Seguras',
  'vault.sicure-vuoto': 'Nenhuma ainda: jogue algumas partidas.',
  'vault.ancora-nessuna': 'Nenhuma ainda.',
  'vault.note-commento': 'Escreva aqui como você quer ser ajudado: «me explica com exemplos práticos», «tenho dislexia, frases curtas», «a oral de Cálculo é com o Rossi, bem teórica».',
  // Home
  'vault.home-carte': '{n} cartões para revisar',
  'vault.alias-memoria': 'O que o Lode sabe de mim',
  'vault.alias-benvenuto': 'Como funciona',
  'vault.titolo-oggi': 'Hoje',
  'vault.aula': 'sala {aula}',
  'vault.niente-lezioni-oggi': 'Nenhuma aula hoje.',
  'vault.titolo-corsi': 'Disciplinas',
  'vault.n-lezioni': { one: '{n} aula', other: '{n} aulas' },
  'vault.idoneo': 'aprovado',
  'vault.voto-e-lode': '{voto} com louvor',
  'vault.appello': 'prova {data}',
  'vault.corsi-vuoto': 'Adicione o horário pela barra: «aula cálculo 2 segunda 9-11 sala 7».',
  'vault.titolo-ultime-lezioni': 'Últimas aulas',
  'vault.definizioni-n': '{n} definições',
  'vault.titolo-carriera': 'Vida acadêmica',
  'vault.carriera': 'Média **{media}** · base de formatura **{base}**/110 · {cfu} de {tot} créditos → {esami}',
  // Esami
  'vault.titolo-prossimi-appelli': 'Próximas provas',
  'vault.tabella-appelli': '| Prova | Data | Faltam | Créditos | Horas estudadas |',
  'vault.ore-di': '{fatte} de {tot} h',
  'vault.nessun-appello': 'Nenhuma prova marcada.',
  'vault.senza-data': 'Sem data: {elenco}.',
  'vault.titolo-libretto': 'Histórico',
  'vault.tabella-libretto': '| Prova | Créditos | Nota | Data |',
  'vault.voto-l': '{voto}L',
  'vault.libretto-piede': 'Média ponderada **{media}** · base de formatura **{base}**/110 · {cfu} de {tot} créditos',
  'vault.libretto-vuoto': 'Nenhuma prova feita ainda.',
  // Glossario
  'vault.n-definizioni': { one: '{n} definição', other: '{n} definições' },
  'vault.da-rinforzare': '*para reforçar*',
  'vault.glossario-vuoto': 'As definições das aulas aparecem aqui, em ordem alfabética, separadas por disciplina.',
  // a página da disciplina
  'vault.corso-cfu': '**{cfu} créditos**',
  'vault.corso-voto': 'nota {voto}',
  'vault.corso-voto-lode': 'nota {voto} com louvor',
  'vault.corso-appello': 'prova **{data}** (daqui a {n} dias) · {fatte} de {tot} h estudadas',
  'vault.corso-lezioni': 'Aulas: {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} sala {aula}',
  'vault.lezioni-vuoto': 'Nenhuma ainda: a primeira nasce quando você marcar algo na aula.',
};
