// Die Leiste (js/lode.js, erster Teil: Pille, Panel, Startseite, Werkzeuge, Wiederholung, Stundenplan, Transkription, Dateien), auf Deutsch.
export default {
  // i tasti per parlare e i numeri scritti in lettere («Tre carte da ripassare»)
  'barra1.tasti-mac': '⌥ Leertaste',
  'barra1.tasti': 'Strg ⇧ Leertaste',
  'barra1.numeri': ['Keine', 'Eine', 'Zwei', 'Drei', 'Vier', 'Fünf', 'Sechs', 'Sieben', 'Acht', 'Neun', 'Zehn'],
  // il saluto e la frase in cima al pannello
  'barra1.saluto-notte': 'Noch wach',
  'barra1.saluto-mattina': 'Guten Morgen',
  'barra1.saluto-pomeriggio': 'Guten Tag',
  'barra1.saluto-sera': 'Guten Abend',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': 'Heute ist {nome}. Viel Erfolg!',
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} Karte zu wiederholen.', other: '{quante} Karten zu wiederholen.' },
  'barra1.niente-in-sospeso': 'Heute steht nichts aus.',
  'barra1.dimmi-esame': 'Sag mir deine nächste Prüfung, dann mache ich den Plan.',
  // la conchiglia: campo, piede, file trascinati
  'barra1.aria-lode': 'Lode, Lernassistent',
  'barra1.aria-torna-home': 'Zurück zur Startseite von Lode',
  'barra1.indietro': 'Zurück',
  'barra1.aria-campo': 'Frag etwas oder schreib einen Befehl',
  'barra1.campo': 'Frag etwas oder schreib einen Befehl…',
  'barra1.ti-ascolto': 'Ich höre zu',
  'barra1.esc-annulla': 'Esc bricht ab',
  'barra1.un-attimo': 'Einen Moment…',
  'barra1.aria-parla': 'Sprechen (oder {tasti} gedrückt halten)',
  'barra1.tieni-premuto': 'Zum Sprechen gedrückt halten <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'Die Daten bleiben auf diesem Computer',
  'barra1.lascia-file': 'Datei hier ablegen',
  'barra1.lascia-file-cosa': 'PDF, Folien, Notizen, Fotos der Tafel: Lode macht daraus Lernkarten',
  'barra1.dopo': 'Später',
  // «Oggi»: le righe della home
  'barra1.di-stamattina': 'von heute Morgen',
  'barra1.di-oggi': 'von heute',
  'barra1.di-ieri': 'von gestern',
  'barra1.di-giorno': 'vom {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} Definition aus {corso} {quando}', other: '{n} Definitionen aus {corso} {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} Definition aus den letzten Vorlesungen', other: '{n} Definitionen aus den letzten Vorlesungen' },
  'barra1.sync-bloccata': 'Lode arbeitet mit den Daten dieses Computers: Die Änderungen warten im Tagebuch.',
  'barra1.sblocca': 'Entsperren',
  'barra1.sync-sparita': 'Der Lode-Ordner im Vault ist weg',
  'barra1.sync-sparita-dett': 'Wurde er verschoben oder gelöscht? Die Daten dieses Computers sind sicher in seinem Tagebuch.',
  'barra1.vedi': 'Ansehen',
  'barra1.sync-spostamento': 'Das Verschieben in den Cloud-Ordner wurde unterbrochen',
  'barra1.sync-spostamento-dett': 'Der alte Vault ist unverändert: Ich mache da weiter, wo ich aufgehört habe.',
  'barra1.riprendi': 'Fortsetzen',
  'barra1.detto-sincronizza': 'Zwischen Computern synchronisieren',
  'barra1.dati-altrove': 'Dieser Vault synchronisiert sich mit Lode auf einem anderen Computer',
  'barra1.dati-altrove-dett': 'Die Daten sind im Tagebuch von Lode 2: Wähl „Ich nutze Lode schon auf einem anderen Computer“, um sie hier zu sehen. Die Änderungen von jetzt kommen in eine eigene Datei, nicht über die Daten.',
  'barra1.uso-gia-lode': 'Ich nutze Lode schon',
  'barra1.detto-uso-gia-lode': 'Ich nutze Lode schon auf einem anderen Computer',
  'barra1.dati-fermo': 'Das Tagebuch von Lode auf diesem Computer ist nicht lesbar',
  'barra1.dati-fermo-dett': 'Es wurde nichts gelöscht: Der Datenordner von Lode antwortet nicht (Festplatte voll oder defekt?).',
  'barra1.riprova': 'Nochmal versuchen',
  'barra1.dati-illeggibili': 'Ich kann deine Daten nicht lesen',
  'barra1.dati-illeggibili-dett': 'Prüfungen, Noten und Karten sind sicher, aber der Ordner antwortet nicht (OneDrive offline oder Datei gesperrt). Die Änderungen von jetzt kommen in eine eigene Datei; ich versuche es selbst wieder.',
  'barra1.lezione-alle': '{corso} um {ora}',
  'barra1.lezione-aula-tra': 'Raum {aula} · in {n} Min.',
  'barra1.lezione-tra': 'in {n} Min.',
  'barra1.appunti': 'Notizen',
  'barra1.orario': 'Stundenplan',
  'barra1.completa-lode': 'Lode vervollständigen',
  'barra1.completa-tutti-e-due': 'Obsidian und das lokale Gehirn: ein Klick, kostenlos',
  'barra1.completa-obsidian': 'Obsidian: ein Klick, kostenlos',
  'barra1.completa-cervello': 'das lokale Gehirn: ein Klick, kostenlos',
  'barra1.prepara': 'Einrichten',
  'barra1.detto-prepara-lode': 'Lode einrichten',
  'barra1.chiudi-lezione-di': 'Vorlesung {corso} abschließen',
  'barra1.chiudi-lezione-dett': { one: '{n} Wort Notizen · ich ziehe Definitionen und ★ heraus', other: '{n} Wörter Notizen · ich ziehe Definitionen und ★ heraus' },
  'barra1.chiudi': 'Abschließen',
  'barra1.detto-chiudi-lezione': 'Vorlesung abschließen',
  'barra1.gioco-due-minuti': 'Zwei-Minuten-Spiel',
  'barra1.gioca': 'Spielen',
  'barra1.esame-ore-oggi': '{data} · heute {ore} Std., um im Plan zu bleiben',
  'barra1.esame-in-pari': '{data} · heute bist du im Plan',
  'barra1.focus': 'Fokus',
  'barra1.ripasso': 'Wiederholung',
  'barra1.ripasso-carte-min': { one: '{n} Karte · etwa {min} Min.', other: '{n} Karten · etwa {min} Min.' },
  'barra1.inizia': 'Starten',
  'barra1.studio-oggi': 'heute {ore} gelernt',
  'barra1.non-hai-studiato': 'Heute hast du noch nicht gelernt',
  'barra1.giorni-di-fila': { one: '{n} Tag am Stück', other: '{n} Tage am Stück' },
  'barra1.bastano-25': '25 Minuten reichen, um eine Serie zu starten',
  'barra1.libretto': 'Notenübersicht',
  // in aula, Ripeti, la trascrizione, la home
  'barra1.in-aula': 'In der Vorlesung · {corso}',
  'barra1.aula-finisce-tra': 'Raum {aula} · endet in {n} Min.',
  'barra1.finisce-tra': 'endet in {n} Min.',
  'barra1.cattura-stella': '★ Prüfungsrelevant',
  'barra1.cattura-definizione': 'Definition',
  'barra1.cattura-domanda': 'Frage',
  'barra1.cose-segnate': { one: '{quante} Sache heute als prüfungsrelevant markiert.', other: '{quante} Sachen heute als prüfungsrelevant markiert.' },
  'barra1.ripeti-attivo-memoria': '„Nochmal“ aktiv · nur im Speicher, nie auf der Festplatte',
  'barra1.ripeti': 'Nochmal',
  'barra1.spegni': 'Ausschalten',
  'barra1.ripeti-spento-invito': '<b>Nochmal 60 s</b> · einen Satz verpasst? Lode spielt ihn dir nochmal vor. Nichts wird gespeichert.',
  'barra1.trascrivi-lezione': 'Vorlesung transkribieren',
  'barra1.trascrivi-lezione-dett': 'Alles, was der Prof sagt, auch Formeln, in der Obsidian-Notiz · {tasti}',
  'barra1.trascrizione-in-pausa': 'Pausiert · {min} Min. · {parole} Wörter',
  'barra1.trascrizione-in-corso': 'Transkribiere · {min} Min. · {parole} Wörter',
  'barra1.prima-riga': 'Ich höre zu: Die erste Zeile kommt in etwa zwanzig Sekunden.',
  'barra1.pausa': 'Pause',
  'barra1.fine': 'Ende',
  'barra1.oggi': 'Heute',
  'barra1.cfu-di': '{fatti} von {tot} ECTS',
  'barra1.inizia-da-qui': 'Fang hier an',
  'barra1.inizia-da-qui-dett': 'Schreib „Vorlesung Analysis 2 Montag 9-11 Raum 7“ oder probier die Beispieldaten',
  'barra1.esempio': 'Beispiel',
  // gli strumenti e la testa del pannello
  'barra1.strumento-gioco': 'Spiel',
  'barra1.strumento-codice': 'Code',
  'barra1.strumento-note': 'Notizen',
  'barra1.strumento-interrogami': 'Frag mich ab',
  'barra1.strumento-esami': 'Prüfungen',
  'barra1.sei-a-lezione': 'Du bist in der Vorlesung {corso}. Schreib in Ruhe mit: Ich sorge dafür, dass nichts verloren geht.',
  'barra1.testa-media': 'Schnitt {media}',
  'barra1.testa-serie': { one: 'Serie von {n} Tag', other: 'Serie von {n} Tagen' },
  // la pillola
  'barra1.ripeti-attivo-titolo': '„Nochmal“ aktiv: die letzten anderthalb Minuten, nur im Speicher',
  'barra1.in-pausa': 'pausiert',
  'barra1.pausa-minuscolo': 'Pause',
  'barra1.aria-timer': '{cosa}: noch {resta}',
  'barra1.prova-generale': 'Probeklausur',
  'barra1.focus-su': 'Fokus auf {nome}',
  'barra1.aria-ripeti-acceso': '. Nochmal: Mikrofon an',
  'barra1.pillola-trascrizione-in-pausa': 'Transkription pausiert · {parole} Wörter',
  'barra1.pillola-trascrivo': 'transkribiere · {parole} Wörter',
  'barra1.fine-tra': 'Ende in {n} Min.',
  'barra1.pillola-aula-tra': 'Raum {aula} · in {n} Min.',
  'barra1.microfono-acceso': 'Mikrofon an',
  'barra1.due-minuti': '2 Minuten',
  'barra1.pillola-tra-giorni': 'in {n} T.',
  // in italiano la pillola dice «carte» anche con una carta sola (com'era prima); in tedesco il singolare giusto
  'barra1.pillola-carte': { one: '{n} Karte', other: '{n} Karten' },
  'barra1.pillola-da-ripassare': { one: 'Karte zu wiederholen', other: 'Karten zu wiederholen' },
  'barra1.passa-qui-sopra': 'Maus hierher',
  'barra1.aria-pillola': 'Lode: {testo}{ripeti}. Fahr mit der Maus drüber oder drück {tasti}.',
  // la conversazione, «Fatto.», «Conferma / Annulla»
  'barra1.altre-righe': { one: '{n} Zeile', other: '{n} Zeilen' },
  'barra1.altro': 'mehr',
  'barra1.fatto': 'Erledigt.',
  'barra1.annulla': 'Abbrechen',
  'barra1.disfa': 'Rückgängig',
  'barra1.annullato-minuscolo': 'rückgängig gemacht',
  'barra1.confermi': 'Bestätigen?',
  'barra1.conferma': 'Bestätigen',
  'barra1.scrivi-si': 'Du kannst auch „ja“ schreiben.',
  'barra1.annullato': 'Rückgängig gemacht.',
  'barra1.niente-cambiato': 'Ich habe nichts geändert.',
  // Focus
  'barra1.durata': 'Dauer',
  'barra1.min': 'Min.',
  'barra1.su-che-cosa': 'Woran',
  'barra1.studio-libero': 'Freies Lernen',
  'barra1.pausa-alla-fine': 'Am Ende {n} Minuten Pause. Die Stunden zählen für deinen Lernplan.',
  'barra1.sintesi-focus': 'Fokus',
  'barra1.focus-di-min': 'Fokus von {min} Minuten.',
  'barra1.focus-di-min-su': 'Fokus von {min} Minuten auf {nome}.',
  'barra1.ci-vediamo': 'Bis zur Pause.',
  'barra1.sintesi-focus-min': 'Fokus {min} Min.',
  // Libretto ed «e se prendo…»
  'barra1.media-ponderata': 'Gewichteter Schnitt',
  'barra1.aritmetica-esami': { one: 'arithmetisch {media} · {n} Prüfung', other: 'arithmetisch {media} · {n} Prüfungen' },
  'barra1.nessun-voto': 'noch keine Note',
  'barra1.base-di-laurea': 'Abschlussbasis (Italien)',
  'barra1.serve-gia': 'Um mit <b>{obiettivo}</b> zu starten, musst du die restlichen Prüfungen nur bestehen.',
  'barra1.serve-media': 'Um mit <b>{obiettivo}</b> zu starten, brauchst du einen Schnitt von <b>{voto}</b> in den {cfu} ECTS, die noch fehlen.',
  'barra1.serve-impossibile': 'Mit <b>{obiettivo}</b> zu starten, geht nicht mehr: Ziel lieber auf {punta}.',
  'barra1.e-se': 'Was wäre, wenn…',
  'barra1.esame': 'Prüfung',
  'barra1.voto': 'Note',
  'barra1.simula-esito': 'Schnitt <b>{media}</b> <span class="{classe}">{delta}</span> · Basis <b>{base}</b>',
  'barra1.sintesi-media-base': 'Schnitt {media}, Basis {base}',
  'barra1.sintesi-libretto-vuoto': 'Notenübersicht leer',
  'barra1.simula-non-trovo': 'Ich finde **{nome}** nicht bei deinen Prüfungen. Füg sie hinzu mit „Prüfung {nome} 6 ECTS“.',
  'barra1.simula-primo': 'Mit {voto} in **{nome}** würde dein Schnitt bei **{voto}** starten: Basis **{base}**.',
  'barra1.simula-primo-lode': 'Mit {voto} cum laude in **{nome}** würde dein Schnitt bei **{voto}** starten: Basis **{base}**.',
  'barra1.simula': 'Mit **{voto}** in {nome} geht der Schnitt von {prima} auf **{dopo}** ({delta}): Abschlussbasis **{base}**.',
  'barra1.simula-lode': 'Mit **{voto} cum laude** in {nome} geht der Schnitt von {prima} auf **{dopo}** ({delta}): Abschlussbasis **{base}**.',
  'barra1.sintesi-media': 'Schnitt {media}',
  // Esami
  'barra1.incolla-programma': 'Füg den Prüfungsstoff ein: Ich mache dir den Plan nach Themen',
  'barra1.giorno-cuscinetto': 'Puffertag',
  'barra1.ripasso-generale': 'allgemeine Wiederholung',
  'barra1.niente-di-nuovo': 'nichts Neues',
  'barra1.pronto': '{n} % bereit',
  'barra1.prossimi-appelli': 'Nächste Prüfungstermine · {n}',
  'barra1.esame-riga': '{data} · {cfu} ECTS · {fatte} von {tot} Std.',
  'barra1.ore-oggi': '{ore} Std. heute',
  'barra1.giorni-parola': { one: 'Tag', other: 'Tage' },
  'barra1.nessun-appello': 'Kein Prüfungstermin im Kalender.',
  'barra1.senza-data': 'Ohne Datum: {nomi}.',
  'barra1.nuovo-esame': 'Neue Prüfung',
  'barra1.nome-esame': 'Name der Prüfung',
  'barra1.cfu': 'ECTS',
  'barra1.data-appello': 'Prüfungsdatum',
  'barra1.aggiungi': 'Hinzufügen',
  'barra1.programma-di': 'Prüfungsstoff {nome}',
  'barra1.esame-aggiunto': '{nome} hinzugefügt.',
  'barra1.senza-data-nota': 'ohne Datum',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': 'kein Prüfungstermin',
  // Ripasso
  'barra1.ripasso-di': 'Wiederholung · {nome}',
  'barra1.niente-da-ripassare': 'Heute gibt es nichts zu wiederholen. Die nächste Karte kommt {quando} zurück.',
  'barra1.nessuna-carta': 'Noch keine Karten. Schreib „Karte: Frage = Antwort“ oder zieh ein PDF hierher.',
  'barra1.risposta': 'Antwort',
  'barra1.aggiungi-carta': 'Karte hinzufügen',
  'barra1.carta-aggiunta': 'Karte hinzugefügt.',
  'barra1.torna-oggi': 'Sie kommt noch heute in die Wiederholung.',
  'barra1.sintesi-niente-da-ripassare': 'nichts zu wiederholen',
  'barra1.mostra-risposta': 'Antwort zeigen <kbd>Leertaste</kbd>',
  'barra1.x-di-y': '{x} von {y}',
  'barra1.ripasso-finito': { one: 'Wiederholung fertig: {n} Karte in {min} Min.', other: 'Wiederholung fertig: {n} Karten in {min} Min.' },
  'barra1.difficili-domani': 'Die schweren kommen morgen wieder.',
  'barra1.sintesi-carte-ripassate': { one: '{n} Karte wiederholt', other: '{n} Karten wiederholt' },
  'barra1.sintesi-ripasso-di': { one: 'Wiederholung von {n} Karte', other: 'Wiederholung von {n} Karten' },
  // i comandi da provare
  'barra1.prova-a-scrivere': 'Schreib zum Beispiel',
  'barra1.aiuto-senza-ai': 'Mit dem lokalen Gehirn (kostenlos) oder deiner KI (schreib „KI“) kannst du dir auch Dinge erklären lassen, Karten aus PDFs machen und dich abfragen lassen.',
  'barra1.sintesi-comandi': 'Befehle',
  // Orario
  'barra1.orario-lezioni': { one: 'Stundenplan · {n} Vorlesung pro Woche', other: 'Stundenplan · {n} Vorlesungen pro Woche' },
  'barra1.corso-aula': '{corso} · Raum {aula}',
  'barra1.punto-aula': ' · Raum {aula}',
  'barra1.togli': '{nome} entfernen',
  'barra1.corso': 'Kurs',
  'barra1.giorni': 'Tage',
  'barra1.inizio': 'Beginn',
  'barra1.aula': 'Raum',
  'barra1.orario-oppure-scrivi': 'Oder schreib: „Vorlesung Analysis 2 Montag und Mittwoch 9-11 Raum 7“.',
  'barra1.in-orario': '{corso} im Stundenplan.',
  'barra1.sintesi-lezioni-settimana': { one: '{n} Vorlesung pro Woche', other: '{n} Vorlesungen pro Woche' },
  // il piano per chi lavora
  'barra1.ore-regola': { one: '{n} Stunde', other: '{n} Stunden' },
  'barra1.la-tua-settimana': 'Deine Woche',
  'barra1.detto-piano-settimana': 'Wochenplan',
  'barra1.lavori': 'Du arbeitest {turni}.',
  'barra1.lavori-nota': 'Das ziehe ich von der Lernzeit ab, mit einer halben Stunde für den Weg. An Arbeitstagen lernst du höchstens {tetto}: Ändern kannst du das mit „an Arbeitstagen lerne ich höchstens {altro} Stunden“.',
  'barra1.turni-cambiati': 'Schichten geändert.',
  'barra1.turni-salvati': 'Schichten gespeichert.',
  'barra1.sintesi-lavoro': 'Arbeit {turni}',
  'barra1.turni-tolti': 'Schichten entfernt.',
  'barra1.turni-tolti-nota': 'Der Plan zählt wieder deinen ganzen Lerntag.',
  'barra1.giorno-non-lavori': '{giorno} arbeitest du nicht.',
  'barra1.ore-libere': 'Diese Stunden sind wieder frei zum Lernen.',
  'barra1.giorno-lavori-anche': '{giorno} arbeitest du auch {da}–{a}.',
  'barra1.solo-quel-giorno': 'Nur an diesem Tag: Ich ziehe es von der Lernzeit ab.',
  'barra1.tetto': 'An Arbeitstagen lernst du höchstens {tetto}.',
  'barra1.tetto-nota': 'Der Plan wird mit dieser Grenze neu gemacht.',
  'barra1.studi-dalle': 'Du lernst von {da} bis {a}.',
  'barra1.studi-dalle-nota': 'Der Plan nutzt nur diese Stunden, ohne Vorlesungen und Arbeit.',
  'barra1.togli-scelta': 'Entfernen: {scelta}',
  'barra1.niente-nel-piano': 'nichts im Plan',
  'barra1.settimana-lavori': 'Du arbeitest {turni}: Das ziehe ich von der Lernzeit ab, mit einer halben Stunde für den Weg. An Arbeitstagen lernst du höchstens {tetto}.',
  'barra1.settimana-se-lavori': 'Wenn du arbeitest, schreib es mir: „ich arbeite Montag Mittwoch Freitag 14-19“.',
  'barra1.settimana-un-esame': 'Mit nur einer Prüfung und ohne Arbeit ist der Plan der des Prüfungsstoffs.',
  'barra1.settimana-stime': 'Die Stunden sind Schätzungen: ein neues Thema etwa 1 Std., eine Wiederholung etwa 30 Min.',
  'barra1.sintesi-la-tua-settimana': 'deine Woche',
  // la cattura veloce in aula
  'barra1.cattura-stella-campo': 'Was hat der Prof gesagt, das in der Prüfung drankommt?',
  'barra1.cattura-definizione-campo': 'Begriff: Definition',
  'barra1.cattura-domanda-campo': 'Die Frage an den Prof',
  'barra1.scrivila-cosi': 'Schreib sie so: **Begriff: Definition**.',
  'barra1.errore-vault': 'Ich kann nicht in den Vault schreiben: {errore}',
  'barra1.dove-sparsi': 'in den losen Notizen von heute',
  'barra1.dove-in': 'in {corso}',
  'barra1.segnato-dove': '★ Markiert {dove}.',
  'barra1.definizione-dove': '„{termine}“ {dove}.',
  'barra1.domanda-dove': 'Frage gespeichert {dove}.',
  // trascrivere: in aula, dal computer, da una registrazione
  'barra1.videolezioni-app': 'Die Transkription von Videovorlesungen gibt es in der **Desktop-App** von Lode: Sie hört den Ton des Computers und schreibt in die Obsidian-Notiz der Vorlesung.',
  'barra1.sto-gia-trascrivendo': 'Ich transkribiere schon.',
  'barra1.parole-finora': { one: '{n} Wort bis jetzt.', other: '{n} Wörter bis jetzt.' },
  'barra1.lezione-dal-computer': 'Vorlesung vom Computer',
  'barra1.computer-spiega': 'Starte die Videovorlesung (auf der Plattform deiner Uni, in Teams, Zoom oder wo du sie schaust): Ich höre den Ton, der aus dem Computer kommt, und schreibe ihn in die Notiz der Vorlesung, Formeln inklusive.',
  'barra1.nome-del-corso': 'Name des Kurses',
  'barra1.computer-patto': 'Nur zum Lernen für dich: Ich lade das Video nicht herunter und lade nichts hoch, der Ton wird nicht gespeichert und in die Notiz kommt nur Text. Die Vorlesungen gehören den Lehrenden: Teil die Transkription nicht, wenn deine Uni es nicht erlaubt.',
  'barra1.computer-mac': 'Beim ersten Mal fragt dich der Mac nach der Erlaubnis, den Systemton aufzunehmen.',
  'barra1.computer-windows': 'Unter Windows hörst du den Ton wie immer: Ich höre ihn auch.',
  'barra1.computer-linux': 'Unter Linux höre ich den „Monitor“ der Audioausgabe.',
  'barra1.detto-trascrivi-videolezione': 'Videovorlesung {corso} transkribieren',
  'barra1.sintesi-lezione-dal-computer': 'Vorlesung vom Computer',
  'barra1.computer-permesso-mac': 'Der Mac gibt mir den Ton des Computers nicht: Schalte unter **Systemeinstellungen › Datenschutz & Sicherheit › Bildschirm- & Systemaudioaufnahme** Lode ein und versuch es nochmal (manchmal musst du Lode neu öffnen).',
  'barra1.computer-permesso': 'Das System gibt mir den Ton des Computers nicht: Versuch es nochmal und bestätige die Freigabe.',
  'barra1.computer-non-sento-mac': 'Ich kann den Ton des Computers nicht hören (dafür brauchst du macOS 14.2 oder neuer). {errore}',
  'barra1.computer-non-sento-windows': 'Ich kann den Ton des Computers nicht hören. {errore}',
  'barra1.computer-non-sento-linux': 'Ich kann den Ton des Computers nicht hören (dafür brauchst du PulseAudio oder PipeWire). {errore}',
  'barra1.computer-muto': 'Ich höre nichts vom Computer. Läuft die Videovorlesung, und ist der Ton an?',
  'barra1.computer-muto-mac': 'Ich höre nichts vom Computer. Läuft die Videovorlesung, mit Ton an? Wenn ja, gibt mir der Mac den Ton nicht: **Systemeinstellungen › Datenschutz & Sicherheit › Bildschirm- & Systemaudioaufnahme**, Lode einschalten und nochmal versuchen.',
  'barra1.trascrizione-app': 'Die Transkription der Vorlesungen gibt es in der **Desktop-App** von Lode: Sie schreibt direkt in die Obsidian-Notiz der Vorlesung.',
  'barra1.computer-aggiorna': 'Diese Version kann den Ton des Computers nicht hören: Aktualisier Lode.',
  'barra1.preparo-voce': 'Ich bereite die Spracheingabe vor…',
  'barra1.trascrivo-file': 'Ich transkribiere „{file}“ in die Vorlesung {corso}.',
  'barra1.puoi-chiudere': 'Du kannst das Panel schließen: Ich sag dir Bescheid, wenn ich fertig bin.',
  'barra1.sintesi-registrazione': 'Aufnahme wird transkribiert',
  'barra1.ascolto-computer': 'Ich höre den Ton des Computers für {corso}.',
  'barra1.ascolto-computer-nota': 'Starte die Videovorlesung: Die Zeilen kommen alle 20-30 Sekunden in die Notiz. Wenn sie vorbei ist, schreib „Ende der Vorlesung“.',
  'barra1.apri-in-obsidian': 'In Obsidian öffnen',
  'barra1.sintesi-videolezione': 'Videovorlesung wird transkribiert',
  'barra1.avviso-videolezione': 'Ich höre die Videovorlesung',
  'barra1.trascrivo-sparsi': 'Ich transkribiere in die losen Notizen.',
  'barra1.trascrivo-lezione-di': 'Ich transkribiere die Vorlesung {corso}.',
  'barra1.righe-ogni': 'Die Zeilen kommen alle 20-30 Sekunden in die Notiz.',
  'barra1.sintesi-trascrizione-avviata': 'Transkription gestartet',
  'barra1.avviso-trascrivo': 'Ich transkribiere die Vorlesung',
  'barra1.errore-trascrivere': 'Ich kann nicht transkribieren: {errore}',
  'barra1.non-sto-trascrivendo': 'Ich transkribiere gerade nichts.',
  'barra1.ultimi-secondi': 'Ich transkribiere die letzten Sekunden…',
  'barra1.lezione-trascritta': 'Vorlesung transkribiert: {parole} Wörter.',
  'barra1.righe-sospese': { one: '{n} Zeile ist noch nicht in der Notiz (der Ordner antwortet nicht): Ich schreibe sie, sobald ich kann, lass mich offen.', other: '{n} Zeilen sind noch nicht in der Notiz (der Ordner antwortet nicht): Ich schreibe sie, sobald ich kann, lass mich offen.' },
  'barra1.tutto-nella-nota': 'Alles ist in der Notiz.',
  'barra1.riordina': 'Aufräumen',
  'barra1.detto-riordina': 'Vorlesung aufräumen',
  'barra1.condividi': 'Teilen',
  'barra1.detto-condividi': 'Mitschrift teilen',
  'barra1.sintesi-parole-trascritte': { one: '{n} Wort transkribiert', other: '{n} Wörter transkribiert' },
  'barra1.con-cervello-locale': 'Mit dem **lokalen Gehirn** (über „Lode einrichten“) wird die Transkription mit einem Klick zu geordneten Notizen, Definitionen und ★.',
  // riordinare la lezione con l'AI
  'barra1.non-trovo-trascrizione-di': 'Ich finde keine Transkription von **{corso}**.',
  'barra1.non-trovo-trascrizione': 'Ich finde keine transkribierte Vorlesung. Drück in der Vorlesung auf **Vorlesung transkribieren**.',
  'barra1.riordinare-serve-ai': 'Zum Aufräumen brauche ich KI: Installier das **lokale Gehirn** über „Lode einrichten“ (kostenlos, offline) oder verbinde deine KI: Schreib „KI“.',
  'barra1.riordino': 'Ich räume {corso} auf…',
  'barra1.riordino-per-cento': 'Ich räume {corso} auf… {n} %',
  'barra1.errore-riordinare': 'Das Aufräumen hat nicht geklappt: {errore}',
  'barra1.salvare-riordinati': 'Die aufgeräumten Notizen von {corso} speichern?',
  'barra1.appunti-salvati': 'Notizen in der Notiz gespeichert.',
  'barra1.sintesi-lezione-riordinata': 'Vorlesung aufgeräumt',
  'barra1.detto-definizioni-lezione': 'Definitionen aus der Vorlesung',
  // «Ripeti» e il permesso di ascoltare la lezione
  'barra1.ascoltare-lezione': 'Die Vorlesung mithören?',
  'barra1.consenso-ripeti': 'ich behalte nur die letzten anderthalb Minuten im Speicher, nie auf der Festplatte',
  'barra1.trascrivi': 'Transkribieren',
  'barra1.consenso-trascrivi': 'ich schreibe die Vorlesung in die Notiz, der Ton wird nicht gespeichert',
  'barra1.dove': 'Wo',
  'barra1.consenso-dove': 'alles auf dem Computer, nichts im Internet',
  'barra1.consenso-nota': 'Ob du eine Vorlesung aufnehmen darfst, hängt von deiner Uni und der Lehrperson ab: Frag vorher.',
  'barra1.solo-la-prima-volta': 'Das frage ich nur beim ersten Mal.',
  'barra1.d-accordo': 'Einverstanden.',
  'barra1.ripeti-app': '„Nochmal“ gibt es in der **Desktop-App** von Lode.',
  'barra1.ripeti-e-attivo': '„Nochmal“ ist aktiv.',
  'barra1.ripeti-attivo-nota': 'Ich behalte die letzten anderthalb Minuten im Speicher, nie auf der Festplatte. Etwas verpasst? {tasti} oder „nochmal“.',
  'barra1.ripeti-attivo-nota-fuori': 'Ich behalte die letzten anderthalb Minuten im Speicher, nie auf der Festplatte. Etwas verpasst? {tasti} oder „nochmal“. Außerhalb deiner Vorlesungszeiten bleibe ich höchstens 3 Stunden an.',
  'barra1.detto-spegni-ripeti': '„Nochmal“ ausschalten',
  'barra1.sintesi-ripeti-attivo': '„Nochmal“ an',
  'barra1.ripeti-spento': '„Nochmal“ ausgeschaltet.',
  'barra1.microfono-resta': 'Das Mikrofon bleibt für die Transkription an, bis du sie beendest.',
  'barra1.microfono-chiuso': 'Das Mikrofon ist aus.',
  'barra1.non-si-accende-piu': ' In der Vorlesung schaltet es sich nicht mehr von selbst ein: Du schaltest es mit {tasti} wieder ein.',
  'barra1.ripeti-e-spento': '„Nochmal“ ist aus.',
  'barra1.ripeti-e-spento-nota': '„Nochmal“ schreibt dir, was der Prof in den letzten 60 Sekunden gesagt hat: Du schaltest es hier ein oder mit {tasti}. Wenn du etwas anderes wolltest, frag mich mit deinen eigenen Worten.',
  'barra1.accendi': 'Einschalten',
  'barra1.detto-accendi-ripeti': '„Nochmal“ einschalten',
  'barra1.sintesi-ripeti-spento': '„Nochmal“ aus',
  'barra1.ascolto-da-un-attimo': 'Ich höre erst seit einem Moment zu: Ich habe noch nichts, was ich dir wiederholen kann.',
  'barra1.riascolto': { one: 'Ich höre die letzte {n} Sekunde nochmal…', other: 'Ich höre die letzten {n} Sekunden nochmal…' },
  'barra1.errore-riascoltare': 'Das nochmal Hören hat nicht geklappt: {errore}',
  'barra1.niente-sentito': 'In den letzten 60 Sekunden habe ich niemanden sprechen hören.',
  'barra1.ultimi-secondi-ora': { one: 'Die letzte {n} Sekunde · {ora}', other: 'Die letzten {n} Sekunden · {ora}' },
  'barra1.agli-appunti': 'Zu den Notizen',
  'barra1.copia': 'Kopieren',
  'barra1.copiato': 'Kopiert',
  'barra1.negli-appunti-di': 'In den Notizen von {corso}.',
  // condividere la sbobina
  'barra1.sbobine-app': 'Mitschriften teilst du über die **Desktop-App**.',
  'barra1.non-trovo-lezione-di': 'Ich finde keine Vorlesung von **{corso}** zum Teilen.',
  'barra1.non-trovo-lezione': 'Ich finde keine Vorlesung zum Teilen: Transkribier sie zuerst oder räum sie auf.',
  'barra1.preparo-sbobina': 'Ich bereite die Mitschrift vor…',
  'barra1.sbobina-pronta': 'Mitschrift von {corso} ist fertig.',
  'barra1.scegli-dove': 'Wähl, wohin du sie schickst: AirDrop, Nachrichten, Mail…',
  'barra1.mostra': 'Zeigen',
  'barra1.sintesi-sbobina-condivisa': 'Mitschrift geteilt',
  'barra1.errore-sbobina': 'Ich kann die Mitschrift nicht vorbereiten: {errore}',
  // le carte per Anki
  'barra1.anki-non-trovo-di': 'Ich finde keine Karten oder Definitionen von **{corso}** zum Exportieren.',
  'barra1.anki-non-trovo': 'Ich habe noch keine Karten oder Definitionen zum Exportieren: Notier in der Vorlesung ein paar Definitionen („def: Gradient = …“) oder mach Karten aus einem PDF.',
  'barra1.anki-carte-mazzi': { one: '{n} Karte für Anki, {mazzi} Stapel.', other: '{n} Karten für Anki, {mazzi} Stapel.' },
  'barra1.anki-carte-mazzo': { one: '{n} Karte für Anki im Stapel {mazzo}.', other: '{n} Karten für Anki im Stapel {mazzo}.' },
  'barra1.anki-doppioni': { one: ' {n} Duplikat übersprungen.', other: ' {n} Duplikate übersprungen.' },
  'barra1.anki-importa-download': 'In Anki: Datei › Importieren, wähl „{file}“ (liegt in den Downloads) und als Notiztyp „Einfach“ („Basic“ auf Englisch).',
  'barra1.anki-importa-vault': 'In Anki: Datei › Importieren, wähl „{file}“ im Vault und als Notiztyp „Einfach“ („Basic“ auf Englisch).',
  'barra1.scarica': 'Herunterladen',
  'barra1.sintesi-anki': 'Karten für Anki',
  'barra1.errore-mostrare': 'Ich kann die Datei nicht zeigen: {errore}',
  'barra1.errore-anki': 'Ich kann die Datei für Anki nicht speichern: {errore}',
  // i file lasciati sulla pillola
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'PowerPoint-Folien',
  'barra1.tipo-word': 'Word-Dokument',
  'barra1.tipo-testo': 'Text',
  'barra1.tipo-sbobina': 'Mitschrift von Lode',
  'barra1.tipo-carte': 'Karten (Anki/CSV)',
  'barra1.tipo-foto': 'Foto',
  'barra1.tipo-audio': 'Audioaufnahme',
  'barra1.tipo-altro': 'Datei',
  'barra1.uno-alla-volta': { one: 'Eins nach dem anderen: Ich fange mit **{nome}** an, dann zieh die andere Datei rein.', other: 'Eins nach dem anderen: Ich fange mit **{nome}** an, dann zieh die anderen {n} rein.' },
  'barra1.errore-leggere-file': 'Ich kann die Datei nicht lesen: {errore}',
  'barra1.serve-ai': 'braucht das lokale Gehirn oder deine KI',
  'barra1.serve-app': 'in der Desktop-App',
  'barra1.op-sbobina': 'Zu meinem Vault hinzufügen',
  'barra1.op-sbobina-d': 'Wird zu einer Vorlesung in deinem Obsidian: Definitionen und ★ kommen in die Spiele',
  'barra1.op-allega-soltanto': 'Nur anhängen',
  'barra1.op-allega-soltanto-d': 'Ich speichere die Datei in den Anhängen der Vorlesung',
  'barra1.op-importa-carte': 'Karten importieren',
  'barra1.op-importa-carte-d': 'Eine pro Zeile: Frage, dann Tab, „;“ oder „ = “, dann Antwort',
  'barra1.op-audio': 'Aufnahme transkribieren',
  'barra1.op-audio-d': 'Die ganze Vorlesung als Notizen, Formeln inklusive, in der Notiz der Vorlesung',
  'barra1.op-allega': 'An die Vorlesung anhängen',
  'barra1.op-allega-audio-d': 'Ich speichere die Audiodatei in den Anhängen, mit Link in der Notiz',
  'barra1.op-lavagna': 'Als Notizen abschreiben',
  'barra1.op-lavagna-d': 'Text und Formeln in LaTeX, in der Notiz der Vorlesung',
  'barra1.op-carte': 'Lernkarten',
  'barra1.op-carte-foto-d': 'Die Fragen, die in der Prüfung kommen würden',
  'barra1.op-allega-foto-d': 'Das Foto in der Notiz der Vorlesung',
  'barra1.op-carte-d': 'Fragen und Antworten für die verteilte Wiederholung',
  'barra1.op-riassunto': 'Zusammenfassung in Obsidian',
  'barra1.op-riassunto-d': 'Geordnete Notizen mit Formeln, in einer neuen Notiz',
  'barra1.op-definizioni': 'Definitionen für die Spiele',
  'barra1.op-definizioni-d': 'Ich füge sie der Vorlesung hinzu: Sie werden zu Gedächtnisspielen',
  'barra1.op-orale': 'Frag mich dazu ab',
  'barra1.op-orale-d': 'Ein Prof wie in der Mündlichen, mit Fragen zu diesem Material',
  'barra1.op-allega-d': 'Ich speichere die Datei mit Link in der Notiz',
  'barra1.op-crocette': 'Multiple-Choice-Quiz',
  'barra1.op-crocette-d': 'Fragen mit 4 Antworten, wie in der Klausur: Training oder Prüfungssimulation',
  'barra1.op-temi': 'Altklausuren',
  'barra1.op-temi-d': 'Die Aufgaben einer alten Klausur, nach Thema sortiert, eine pro Tag im Plan',
  'barra1.op-programma': 'Das ist der Prüfungsstoff',
  'barra1.op-programma-d': 'Ich teile ihn in Themen und mache dir den Plan bis zur Prüfung',
  'barra1.op-domande': 'Fragen aus früheren Prüfungen',
  'barra1.op-domande-d': 'Ich ordne sie ihren Themen zu: Was öfter drankommt, rückt im Plan nach oben',
};
