// Texte der Leiste, dritter Teil (Deutsch): Karten fürs Handy, Moodle, Multiple-Choice-Quiz, Altklausuren, Probeklausur,
// Prüfungsstoff, „ich erklär’s dir“, Senden, Dateien, Sprache, Tastenkürzel und Hinweise der App (js/lode.js).
export default {
  // Ripasso in tasca
  'barra3.tasca-solo-app': 'Karten fürs Handy gibt es in der App: Dafür braucht es den Obsidian-Vault.',
  'barra3.tasca-spenta': 'Karten fürs Handy nur, wenn du danach fragst.',
  'barra3.tasca-spenta-nota': 'Die Notiz {nota} bleibt im Vault: Schreib „Karten fürs Handy“, um sie zu aktualisieren.',
  'barra3.tasca-spenta-sintesi': 'Karten fürs Handy aus',
  'barra3.tasca-preparo': 'Ich bereite die Notiz vor…',
  'barra3.tasca-errore': 'Ich kann die Notiz {nota} nicht lesen oder schreiben: {errore}',
  'barra3.tasca-estranea': 'Im Vault gibt es schon eine Notiz **{nota}**, die nicht von Lode ist: Die fasse ich nicht an. Benenn sie um und versuch es nochmal.',
  'barra3.tasca-segnata-sapevi': 'Ich habe die Karte eingetragen, die du auf dem Handy gemacht hast: Du wusstest sie.',
  'barra3.tasca-segnata-non-sapevi': 'Ich habe die Karte eingetragen, die du auf dem Handy gemacht hast: Du wusstest sie nicht.',
  'barra3.tasca-segnate': 'Ich habe {n} Karten eingetragen, die du auf dem Handy gemacht hast: {sapevo} gewusst, {no} nicht.',
  'barra3.tasca-gia': { one: 'Eine Karte hattest du schon am Computer wiederholt: Die trage ich nicht doppelt ein.', other: '{n} Karten hattest du schon am Computer wiederholt: Die trage ich nicht doppelt ein.' },
  'barra3.tasca-vecchia': 'Die Notiz auf dem Handy ist von einer alten Runde: Ich trage nichts ein.',
  'barra3.tasca-cambiata': 'Die Notiz ändert sich noch: Obsidian synchronisiert sie gerade. Ich schreibe sie jetzt nicht neu, versuch es in einer Minute nochmal.',
  'barra3.tasca-domani': { one: 'In der Notiz {nota} ist {n} Karte für morgen.', other: 'In der Notiz {nota} sind {n} Karten für morgen.' },
  'barra3.tasca-domani-niente': 'Morgen hast du keine Karten zu wiederholen: Das steht in der Notiz {nota}.',
  'barra3.tasca-titolo': 'Karten fürs Handy',
  'barra3.tasca-aspetta': 'Warte, bis das Handy fertig synchronisiert hat, und versuch es nochmal. Wenn die richtige Notiz nicht ankommt, schreib sie neu: Die Haken in dieser Kopie trage ich nicht ein.',
  'barra3.apri-nota': 'Notiz öffnen',
  'barra3.riscrivi-nota': 'Notiz neu schreiben',
  'barra3.tasca-solo-quando': 'Nur wenn ich frage',
  'barra3.tasca-ogni-sera': 'Jeden Abend',
  'barra3.tasca-sera-accesa': 'Jeden Abend nach 19 Uhr schreibe ich sie selbst neu, wenn Lode offen ist.',
  'barra3.tasca-sera-spenta': 'Ich schreibe sie nur neu, wenn du mich fragst.',
  'barra3.tasca-come-arriva': 'Das funktioniert, wenn der Vault aufs Handy kommt (iCloud, Obsidian Sync, Syncthing). Lode nutzt kein Netz: Die Notiz bringt der Dienst, den du schon nutzt.',
  'barra3.non-apro-nota': 'Ich kann die Notiz nicht öffnen: {errore}',
  'barra3.tasca-riscrivi-detto': 'Notiz {nota} neu schreiben',
  'barra3.tasca-sintesi': 'Karten fürs Handy',

  // Moodle
  'barra3.moodle-solo-app': 'Die Verbindung zu Moodle gibt es in der **Desktop-App** von Lode.',
  'barra3.moodle-non-risponde': 'Moodle antwortet nicht: {errore}',
  'barra3.moodle-non-collegato': 'Moodle ist nicht verbunden.',
  'barra3.moodle-scollegato': 'Moodle getrennt.',
  'barra3.moodle-scollegato-nota': 'Der Token ist von diesem Computer gelöscht. Die Dateien, die schon geholt wurden, bleiben in deinem Vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} Kurs verfolgt: {corsi}', other: '{n} Kurse verfolgt: {corsi}' },
  'barra3.file-nuovi': 'Neue Dateien',
  'barra3.scadenze': 'Fristen',
  'barra3.corsi': 'Kurse',
  'barra3.scollega': 'Trennen',
  'barra3.moodle-senza-portachiavi': 'Dieser Computer hat keinen Schlüsselbund: Die Verbindung gilt, bis du Lode schließt.',
  'barra3.moodle-novita-detto': 'Neues auf Moodle',
  'barra3.moodle-corsi-detto': 'Moodle-Kurse',
  'barra3.moodle-scollega-detto': 'Moodle trennen',
  'barra3.moodle-collega': 'Moodle verbinden',
  'barra3.moodle-collega-intro': 'Die Lernplattform deiner Uni (Moodle, eLearning, Lernraum…): Lode holt die neuen Dateien und die Fristen der Kurse, die du wählst. Nur lesen: Es gibt nichts ab und schreibt nichts.',
  'barra3.moodle-indirizzo-esempio': 'Adresse, zum Beispiel moodle.uni-beispiel.de',
  'barra3.moodle-indirizzo': 'Moodle-Adresse',
  'barra3.continua': 'Weiter',
  'barra3.moodle-collega-nota': 'Du meldest dich an wie in der offiziellen Moodle-App. Die Verbindung bleibt verschlüsselt auf diesem Computer, nie im Vault; mit „Moodle trennen“ entfernst du sie.',
  'barra3.moodle-cerco': 'Ich suche die Seite…',
  'barra3.moodle-non-indirizzo': 'Das sieht nicht wie eine Adresse aus.',
  'barra3.moodle-non-trovo': 'Unter dieser Adresse finde ich kein Moodle mit aktivierter App ({motivo}). Kopier die Adresse aus der Adresszeile des Browsers, wenn du auf der Seite deiner Kurse bist.',
  'barra3.moodle-accesso-annullato': 'Anmeldung abgebrochen.',
  'barra3.moodle-accesso-fallito': 'Anmeldung fehlgeschlagen: {motivo}.',
  'barra3.moodle-entra-sso': '<b>{nome}</b> · Anmeldung mit dem Uni-Login (Single Sign-on), in einem Fenster von Lode.',
  'barra3.accedi': 'Anmelden',
  'barra3.moodle-accedi-finestra': 'Melde dich in dem Fenster an, das sich geöffnet hat…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · Anmeldung mit Moodle-Benutzername und Passwort.',
  'barra3.utente': 'Benutzername',
  'barra3.password': 'Passwort',
  'barra3.moodle-password-nota': 'Das Passwort geht nur an Moodle: Lode speichert es nicht.',
  'barra3.moodle-collega-sintesi': 'Moodle verbinden',
  'barra3.moodle-leggo-corsi': 'Ich lese deine Kurse…',
  'barra3.moodle-corsi-errore': 'Ich kann die Kurse nicht lesen: {errore}',
  'barra3.moodle-nessun-corso': 'Auf Moodle bist du in keinem Kurs eingeschrieben.',
  'barra3.moodle-corsi-titolo': 'Moodle-Kurse · {sito}',
  'barra3.moodle-scegli-corsi': 'Wähl, welche du verfolgen willst und mit welchem Kurs in Lode: Ihre neuen Dateien kommen hierher.',
  'barra3.concluso': 'beendet',
  'barra3.moodle-corso-per': 'Kurs in Lode für {nome}',
  'barra3.non-seguire': 'Nicht verfolgen',
  'barra3.moodle-con-nome': 'Mit dem Namen aus Moodle',
  'barra3.salva': 'Speichern',
  'barra3.moodle-seguo': { one: 'Ich verfolge {n} Kurs auf Moodle.', other: 'Ich verfolge {n} Kurse auf Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Kein Kurs verfolgt.',
  'barra3.moodle-ti-avviso': 'Ich sag dir Bescheid, wenn neue Dateien kommen.',
  'barra3.moodle-corsi-sintesi': 'Moodle-Kurse',
  'barra3.moodle-guardo': 'Ich schaue nach Dateien auf Moodle…',
  'barra3.moodle-non-leggo': 'Ich kann {corsi} nicht lesen: {errore}.',
  'barra3.moodle-nessun-file': 'In den Kursen, die du verfolgst, gibt es noch keine Dateien.',
  'barra3.moodle-piu-recenti': 'die neuesten Dateien',
  'barra3.moodle-file-nuovi': { one: '{n} neue Datei', other: '{n} neue Dateien' },
  'barra3.moodle-niente-nuovo': 'nichts Neues, die letzten Dateien',
  'barra3.nuovo': 'neu',
  'barra3.apri': 'Öffnen',
  'barra3.moodle-apri-nota': '„Öffnen“ bringt die Datei in Lode, als hättest du sie reingezogen: Karten, Zusammenfassung, Prüfungsstoff, Quiz.',
  'barra3.scarico': 'Lade…',
  'barra3.non-riesco': 'Geht nicht',
  'barra3.aperto': 'Geöffnet',
  'barra3.moodle-file-da': '{nome} von Moodle',
  'barra3.file-illeggibile': 'Ich kann die Datei nicht lesen: {errore}',
  'barra3.moodle-sintesi-nuovi': { one: 'Moodle: {n} neue Datei', other: 'Moodle: {n} neue Dateien' },
  'barra3.moodle-nessuna-scadenza': 'Keine Fristen auf Moodle in den nächsten Wochen.',
  'barra3.moodle-scadenze-titolo': 'Fristen auf Moodle',
  'barra3.scadenze-sintesi': { one: '{n} Frist', other: '{n} Fristen' },
  'barra3.guarda': 'Ansehen',

  // quiz a crocette
  'barra3.non-trovo-esame': 'Ich finde die Prüfung **{nome}** nicht.',
  'barra3.il-tuo-materiale': 'deinem Material',
  'barra3.quiz-poco-materiale': 'Für ein Quiz zu **{nome}** brauche ich mehr Material: Zieh das Skript oder die Folien rein (wähl „Multiple-Choice-Quiz“) oder mach ein paar Karten.',
  'barra3.quiz-senza-ai': 'Für das Quiz ohne KI brauche ich mindestens 4 Karten oder 4 Definitionen zu **{nome}**. Mit KI (schreib „KI“) mache ich es auch aus dem Skript.',
  'barra3.quiz-fonte-dispensa-nome': 'Fragen aus dem Skript „{nome}“.',
  'barra3.quiz-fonte-dispensa': 'Fragen aus dem Skript.',
  'barra3.quiz-fonte-ai': 'Fragen aus deinen Karten, Definitionen und früheren Prüfungsfragen.',
  'barra3.quiz-fonte-carte-definizioni': 'Fragen aus deinen Karten und Definitionen.',
  'barra3.quiz-fonte-carte': 'Fragen aus deinen Karten.',
  'barra3.quiz-fonte-definizioni': 'Fragen aus deinen Definitionen.',
  'barra3.quiz-le-scrive': 'Geschrieben werden sie von {motore}: Ich behalte nur die, die das Material belegt.',
  'barra3.quiz-sbagliate-altre': 'Die falschen Antworten stammen von anderen Karten des Kurses.',
  'barra3.quiz-titolo': 'Multiple-Choice-Quiz · {nome}',
  'barra3.quiz-allenamento': { one: 'Training · {n} Frage', other: 'Training · {n} Fragen' },
  'barra3.quiz-allenamento-sotto': 'Sofort korrigiert, mit Erklärung',
  'barra3.quiz-simulazione': { one: 'Prüfungssimulation · {n} Frage in {n} Minute', other: 'Prüfungssimulation · {n} Fragen in {n} Minuten' },
  'barra3.quiz-simulazione-sotto': 'Wie in der Klausur: Die Zeit läuft, korrigiert wird am Ende, Note auf der 30er-Skala',
  'barra3.quiz-simulazione-detto': 'Prüfungssimulation · {nome}',
  'barra3.quiz-detto': 'Quiz · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulation · {nome}',
  'barra3.quiz-preparo': 'Ich bereite die Fragen vor… {fatte} von {n}',
  'barra3.quiz-errore': 'Ich kann die Fragen nicht vorbereiten: {errore}',
  'barra3.quiz-niente': 'Aus diesem Material konnte ich keine verlässlichen Fragen machen.',
  'barra3.quiz-sintesi': 'Quiz {nome}',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} von {n}',
  'barra3.x-di-n': '{x} von {n}',
  'barra3.quiz-domanda-n': 'Frage {x} von {n}',
  'barra3.indietro': 'Zurück',
  'barra3.salta': 'Überspringen',
  'barra3.lascia-vuota': 'Leer lassen',
  'barra3.consegna': 'Abgeben',
  'barra3.quiz-giusta-e': 'Die richtige Antwort ist {lettera}.',
  'barra3.avanti': 'Weiter',
  'barra3.risultato': 'Ergebnis',
  'barra3.tasto-invio': 'Enter',
  'barra3.quiz-voto': 'Note: <em>{voto}</em>',
  'barra3.tempo-scaduto': 'Zeit abgelaufen',
  'barra3.quiz-tutte-giuste': 'Alle richtig.',
  'barra3.quiz-da-rivedere': { one: '{n} zum Wiederholen.', other: '{n} zum Wiederholen.' },
  'barra3.quiz-scartate': { one: '{n} Frage verworfen, weil das Material sie nicht belegt hat', other: '{n} Fragen verworfen, weil das Material sie nicht belegt hat' },
  'barra3.da-rivedere': 'Zum Wiederholen',
  'barra3.lasciata-vuota': 'Leer gelassen',
  'barra3.hai-scelto': 'Deine Wahl: {x}',
  'barra3.giusta-era': 'Richtig: {x}',
  'barra3.quiz-sbagliate-carte': 'Aus den falschen werden Karten',
  'barra3.quiz-un-altro': 'Noch ein Quiz',
  'barra3.quiz-punti': 'Eine richtige Antwort bringt 1 Punkt, eine falsche oder leere 0.',
  'barra3.quiz-regole-vere': 'Die echte Klausur kann andere Regeln haben (Minuspunkte für falsche Antworten, Grenzen): Das hier ist Training.',
  'barra3.quiz-carte-aggiunte': { one: '{n} Karte hinzugefügt: Sie kommt heute noch in die Wiederholung', other: '{n} Karten hinzugefügt: Sie kommen heute noch in die Wiederholung' },
  'barra3.quiz-sintesi-esito': 'Quiz {nome}: {giuste} von {n}',

  // temi d'esame
  'barra3.tema-del': 'vom {data}',
  'barra3.tema-di': 'aus „{fonte}“',
  'barra3.tema-es': 'Aufg. {es}',
  'barra3.tema-es-da': 'Aufg. {es} {da}',
  'barra3.tema-circa': 'etwa {min} Min. auf Papier',
  'barra3.leggo-file': 'Ich lese {nome}…',
  'barra3.cmd-temi-di': '„Altklausuren für {nome}:“',
  'barra3.cmd-temi': '„Altklausuren:“',
  'barra3.temi-scansione': 'Dieses PDF sieht aus wie ein Scan: Ohne KI lese ich keine Bilder. Schreib {cmd} und füg darunter den Text der Aufgaben ein.',
  'barra3.temi-illeggibile': 'Aus dieser Datei kann ich keinen Text lesen. Füg ihn mit {cmd} und dem Text darunter ein.',
  'barra3.aggiungi-prima-esame': 'Füg zuerst die Prüfung hinzu, zum Beispiel: „Prüfung Analysis 2 am 15. Januar 9 ECTS“.',
  'barra3.non-trovo-esame-aggiungi': 'Ich finde die Prüfung **{nome}** nicht. Füg sie zuerst hinzu, zum Beispiel: „Prüfung {nome} am 15. Januar 9 ECTS“.',
  'barra3.aggiungi-esame-compito': 'Füg zuerst eine Prüfung hinzu, zum Beispiel: „Prüfung Analysis 2 am 15. Januar 9 ECTS“. Dann füg eine alte Klausur ein.',
  'barra3.prova-invito': 'Willst du eine ganze Klausur probieren, mit echter Zeit?',
  'barra3.prova-generale': 'Probeklausur',
  'barra3.prova-generale-di': 'Probeklausur {nome}',
  'barra3.temi-titolo': 'Altklausuren · {nome}',
  'barra3.temi-nessuno-oggi': 'Heute ist keine Aufgabe fällig.',
  'barra3.temi-prossimo': 'Die nächste kommt {data} wieder.',
  'barra3.temi-vuoto': 'Füg den Text einer alten Klausur ein (die, die in der Kursgruppe oder auf der Seite des Profs rumgehen) oder zieh das PDF rein. Ich teile sie in Aufgaben, ordne sie ihren Themen zu und schlage dir jeden Tag eine vor.',
  'barra3.temi-segnaposto': 'Aufgabe 1. Berechne…&#10;Aufgabe 2. Untersuche…',
  'barra3.temi-testo-compito': 'Text der Klausur',
  'barra3.temi-dividi': 'In Aufgaben teilen',
  'barra3.temi-di': 'Altklausuren {nome}',
  'barra3.temi-di-sintesi': 'Altklausuren {nome}',
  'barra3.temi-nessun-esercizio': 'In diesem Text habe ich keine Aufgaben gefunden.',
  'barra3.temi-compito-del': 'Klausur {data}',
  'barra3.temi-un-pezzo': 'Ich habe kein „Aufgabe 1“, „Aufgabe 2“… gefunden. Wenn die Klausur mehrere Aufgaben hat, schreib sie mit diesen Markierungen und füg sie nochmal ein.',
  'barra3.temi-senza-programma': 'Für {nome} gibt es noch keinen Prüfungsstoff: Ich speichere sie ohne Thema.',
  'barra3.temi-metti': 'In den Plan aufnehmen',
  'barra3.temi-es': 'Aufg. {n}',
  'barra3.temi-con-soluzione': 'mit der Lösung des Profs',
  'barra3.temi-argomento-di': 'Thema der Aufgabe {n}',
  'barra3.temi-che-argomento': 'Welches Thema ist das?',
  'barra3.temi-unisci': 'Mit der vorherigen zusammenführen',
  'barra3.togli': 'Entfernen',
  'barra3.temi-nel-piano': { one: '{n} Aufgabe im Plan.', other: '{n} Aufgaben im Plan.' },
  'barra3.temi-nel-piano-arg': { one: '{n} Aufgabe im Plan: {con} mit Thema, {senza} ohne.', other: '{n} Aufgaben im Plan: {con} mit Thema, {senza} ohne.' },
  'barra3.temi-senza-programma-nota': 'Ohne Prüfungsstoff weiß ich nicht, wohin damit: Füg den Prüfungsstoff von {nome} ein, dann sortiere ich sie.',
  'barra3.temi-doppi': { one: '{n} war schon da.', other: '{n} waren schon da.' },
  'barra3.temi-ogni-giorno': 'Jeden Tag eine zu den Themen im Plan.',
  'barra3.programma': 'Prüfungsstoff',
  'barra3.fanne-uno': 'Eine machen',
  'barra3.esercizio-di': 'Aufgabe {nome}',
  'barra3.temi-gia': 'Diese Aufgaben waren schon da.',
  'barra3.temi-sintesi-n': { one: 'Altklausuren {nome}: {n} Aufgabe', other: 'Altklausuren {nome}: {n} Aufgaben' },
  'barra3.tema-titolo': 'Aufgabe · {nome}',
  'barra3.tema-fallo': 'Mach sie auf Papier, ohne in die Notizen zu schauen. Wenn du fertig bist:',
  'barra3.giusto': 'Richtig',
  'barra3.sbagliato': 'Falsch',
  'barra3.non-sapevo': 'Wusste nicht, wo ich anfangen soll',
  'barra3.tema-voto-tuo': 'Die Bewertung gibst du dir selbst: Lode korrigiert die Aufgabe nicht.',
  'barra3.tema-torna': { one: 'Kommt in {n} Tag wieder.', other: 'Kommt in {n} Tagen wieder.' },
  'barra3.tema-guarda-soluzione': 'Schau dir die Lösung an und mach sie nochmal von vorn, nicht nur durchlesen.',
  'barra3.tema-rileggi': 'Lies das Thema nochmal und mach sie von vorn, ohne hinzuschauen.',
  'barra3.tema-prima-rileggi-arg': 'Lies zuerst das Thema nochmal: {arg}.',
  'barra3.tema-prima-rileggi': 'Lies zuerst das Thema nochmal.',
  'barra3.tema-vedi-soluzione': 'Lösung des Profs ansehen',
  'barra3.tema-altro': 'Noch eine Aufgabe',
  'barra3.esercizio-di-esito': 'Aufgabe {nome}: {esito}',
  'barra3.esercizio-di-sintesi': 'Aufgabe {nome}',

  // prova generale
  'barra3.prova-prima-compiti': 'Füg zuerst die alten Klausuren ein oder zieh sie rein: „Altklausuren für {nome}: …“.',
  'barra3.prova-compito-del': 'Klausur vom {data}',
  'barra3.prova-scelti': 'Von dir gewählte Aufgaben',
  'barra3.prova-compito-fonte': 'Klausur „{fonte}“',
  'barra3.prova-compito-incollato': 'Eingefügte Klausur',
  'barra3.n-esercizi': { one: '{n} Aufgabe', other: '{n} Aufgaben' },
  'barra3.n-punti': { one: '{punti} Punkt', other: '{punti} Punkte' },
  'barra3.prova-titolo': 'Probeklausur · {nome}',
  'barra3.prova-quanto-dura': 'Wie lange dauert sie?',
  'barra3.prova-minuti-aria': 'Wie viele Minuten die Klausur dauert',
  'barra3.minuti': 'Minuten',
  'barra3.prova-altro-compito': 'Eine andere Klausur',
  'barra3.prova-gia-fatto': 'schon gemacht am {data}',
  'barra3.comincio': 'Los geht’s',
  'barra3.prova-su-carta': 'Auf Papier, ohne Notizen, wie in der Prüfung. Die Lösungen siehst du am Ende.',
  'barra3.prova-durata-letta': 'Das stand in der Klausur.',
  'barra3.prova-di-solito': 'Meistens 2 Stunden.',
  'barra3.prova-sintesi': 'Probeklausur {nome}',
  'barra3.prova-scegli': 'Ich finde keine ganze Klausur: Wähl die Aufgaben selbst.',
  'barra3.prova-scegli-nota': '120 Minuten, auf Papier, ohne Notizen. Die Lösungen siehst du am Ende.',
  'barra3.prova-ferma-pausa': 'Gerade läuft eine Pause: Soll ich sie beenden und mit der Probeklausur starten?',
  'barra3.prova-ferma-focus': 'Gerade läuft ein Fokus: Soll ich ihn beenden und mit der Probeklausur starten?',
  'barra3.si-parti': 'Ja, los',
  'barra3.no': 'Nein',
  'barra3.prova-durata-fino': '{min} Minuten, bis {ora}',
  'barra3.esercizio-n': 'Aufgabe {n}',
  'barra3.prova-passo': 'Nächste Aufgabe',
  'barra3.consegno': 'Abgeben',
  'barra3.lascio-perdere': 'Abbrechen',
  'barra3.prova-nota-tempo': 'Die Zeit läuft in der Pille. „Nächste Aufgabe“ ist optional: Es misst, wie lange du an jeder Aufgabe sitzt.',
  'barra3.prova-lascio-chiede': 'Abbrechen? Ich trage nichts ein: weder die Aufgaben noch die Klausur.',
  'barra3.si-lascio': 'Ja, abbrechen',
  'barra3.no-continuo': 'Nein, weiter',
  'barra3.prova-lasciata': 'Abgebrochen: Ich habe nichts eingetragen. Wenn du sie nochmal machen willst, schreib „Probeklausur für {nome}“.',
  'barra3.prova-consegnato': 'Abgegeben. Nimm dein Blatt und sag mir bei jeder Aufgabe, wie es gelaufen ist.',
  'barra3.prova-come-andato': 'Wie lief Aufgabe {n}',
  'barra3.prova-esito-tuo': 'Lode korrigiert nicht: Das Ergebnis wählst du.',
  'barra3.prova-sintesi-esito': 'Probeklausur {nome}: {fatti} von {n}',
  'barra3.prova-sintesi-come': 'Probeklausur {nome}: wie es gelaufen ist',

  // programma d'esame
  'barra3.aggiungi-esame-programma': 'Füg zuerst eine Prüfung hinzu, zum Beispiel: „Prüfung Analysis 2 am 15. Januar 9 ECTS“. Dann füg ihren Prüfungsstoff ein.',
  'barra3.programma-titolo': 'Prüfungsstoff · {nome}',
  'barra3.programma-vuoto': 'Füg den Prüfungsstoff des Kurses ein (von der Kursseite oder aus dem PDF) oder zieh die Datei hierher. Ich teile ihn in Themen, zeige dir, was du schon kannst, und mache dir den Plan bis zur Prüfung.',
  'barra3.programma-segnaposto': '1. Grenzwerte und Stetigkeit&#10;2. Ableitungen: Definition, Regeln, Satz von Rolle und Mittelwertsatz&#10;…',
  'barra3.programma-del-corso': 'Prüfungsstoff des Kurses',
  'barra3.programma-leggi': 'Prüfungsstoff lesen',
  'barra3.programma-di': 'Prüfungsstoff {nome}',
  'barra3.programma-da-moodle': 'Von Moodle holen',
  'barra3.programma-moodle-vuota': 'Auf Moodle ist die Beschreibung leer',
  'barra3.programma-di-moodle': 'Prüfungsstoff {nome} von Moodle',
  'barra3.programma-sintesi': 'Prüfungsstoff {nome}',
  'barra3.programma-leggo': 'Ich lese den Prüfungsstoff…',
  'barra3.programma-niente': 'Aus diesem Text bekomme ich die Themen nicht heraus. Füg sie einzeln pro Zeile ein, am besten nummeriert.',
  'barra3.programma-salvo': { one: '{n} Thema für {nome}: speichern?', other: '{n} Themen für {nome}: speichern?' },
  'barra3.programma-letti-da': '{motore} hat sie gelesen: Prüf, ob alle da sind.',
  'barra3.programma-se-non-torna': 'Wenn etwas nicht stimmt, füg den korrigierten Prüfungsstoff nochmal ein.',
  'barra3.programma-stesso-nome': 'Themen mit demselben Namen behalten Fragen und Ergebnisse.',
  'barra3.programma-cuscinetto': 'Heute ist Puffertag: Hol nach, was liegen geblieben ist, oder ruh dich aus.',
  'barra3.programma-ultimo': 'Letzter Tag: allgemeine Wiederholung. Die Prüfungsfragen und die Schwachstellen: {cosa}.',
  'barra3.tutto-il-programma': 'der ganze Prüfungsstoff',
  'barra3.studia': 'Lernen',
  'barra3.ripassa': 'Wiederholen',
  'barra3.cuscinetto': 'Puffer',
  'barra3.ripasso-generale': 'allgemeine Wiederholung',
  'barra3.percento-pronto': '{p} % bereit',
  'barra3.oggi': 'Heute',
  'barra3.esercizio-di-oggi': 'Aufgabe für heute',
  'barra3.fallo-adesso': 'Jetzt machen',
  'barra3.interrogami-questi': 'Frag mich dazu ab',
  'barra3.focus': 'Fokus',
  'barra3.da-rivedere-piccolo': 'zum Wiederholen',
  'barra3.uscita-volte': { one: '{n}-mal drangekommen', other: '{n}-mal drangekommen' },
  'barra3.fatto-oggi': 'heute gemacht',
  'barra3.lo-spiego-io': 'Ich erklär’s',
  'barra3.interrogami': 'Frag mich ab',
  'barra3.prossimi-giorni': 'Die nächsten Tage',
  'barra3.senza-data-appello': '(ohne Prüfungsdatum: Plan über zwei Wochen)',
  'barra3.domande-appelli': 'Fragen aus früheren Prüfungen',
  'barra3.n-senza-argomento': { one: '{n} ohne Thema', other: '{n} ohne Thema' },
  'barra3.domande-segnaposto': 'Eine pro Zeile: die, die in der Kursgruppe rumgehen',
  'barra3.domande-uscite': 'Prüfungsfragen',
  'barra3.aggiungi': 'Hinzufügen',
  'barra3.domande-senza-argomento': 'Ich weiß nicht, zu welchem Thema sie gehören: {lista}',
  'barra3.programma-nota': 'Der Plan wird jeden Tag neu gemacht, aus dem, was du kannst: Notizen, Karten, Wiederholung und Abfragen. Zuerst die schwachen Themen und die, die am häufigsten drankommen; jedes neue Thema kommt nach ein paar Tagen wieder.',
  'barra3.interrogami-oggi': 'Frag mich zu den Themen von heute ab',
  'barra3.interrogami-su': 'Frag mich zu {x} ab',
  'barra3.te-lo-spiego-su': 'Ich erklär’s dir: {x}',
  'barra3.programma-sintesi-pronto': 'Prüfungsstoff {nome}: {p} % bereit',
  'barra3.domande-nessuna': 'Ich habe keine Fragen gefunden: Schreib eine pro Zeile.',
  'barra3.domande-salvate': { one: '{n} Frage gespeichert.', other: '{n} Fragen gespeichert.' },
  'barra3.domande-incolla-programma': 'Füg auch den Prüfungsstoff ein: Dann ordne ich sie ihren Themen zu.',
  'barra3.domande-aggiunte': { one: '{n} Frage hinzugefügt.', other: '{n} Fragen hinzugefügt.' },
  'barra3.domande-senza': { one: '{n} ohne Thema: Ich verstehe nicht, worum es geht.', other: '{n} ohne Thema: Ich verstehe nicht, worum es geht.' },
  'barra3.domande-salgono': 'Die Themen, die am häufigsten drankommen, rücken im Plan nach oben.',
  'barra3.domande-uscite-sintesi': 'Prüfungsfragen',

  // te lo spiego io e l'orale sul programma
  'barra3.spiego-titolo': 'Ich erklär’s dir · {nome}',
  'barra3.spiego-istruzioni': 'Erklär es, als wärst du in der Mündlichen, mit deinen eigenen Worten: Schreib hier unten oder halt {tasti} gedrückt und sprich. Wenn du fertig bist, schick es ab.',
  'barra3.spiego-risponde': 'Dir antwortet {motore}, mit deinen Notizen.',
  'barra3.spiego-controllo': { one: 'Ich prüfe {n} Punkt aus dem Prüfungsstoff und deinen Notizen: Ich zeige ihn dir nicht vorher.', other: 'Ich prüfe {n} Punkte aus dem Prüfungsstoff und deinen Notizen: Ich zeige sie dir nicht vorher.' },
  'barra3.spiego-senza-appunti': 'Zu diesem Thema habe ich keine Notizen: Ohne KI kann ich nur eintragen, dass du es wiederholt hast.',
  'barra3.spiego-esci': 'Schreib „beenden“, um es zu lassen.',
  'barra3.spiego-segnaposto': 'Deine Erklärung…',
  'barra3.spiego-sintesi': 'ich erkläre {x}',
  'barra3.chiedi-o-scrivi': 'Frag etwas oder schreib einen Befehl…',
  'barra3.spiego-ascolto': 'Ich höre mir die Erklärung an…',
  'barra3.mancava': 'Es fehlte: {cosa}',
  'barra3.spiego-errore': 'Ich kann sie gerade nicht bewerten: {errore}',
  'barra3.spiego-segnato': 'Eingetragen: Du hast {x} wiederholt.',
  'barra3.spiego-controllo-vero': 'Für eine echte Prüfung brauche ich Notizen zu diesem Thema oder KI.',
  'barra3.punti-su': { one: '{x} von {tot} Punkten', other: '{x} von {tot} Punkten' },
  'barra3.spiego-parole-chiave': 'Ich prüfe die Schlüsselwörter, nicht die Argumentation: Wenn du einen Punkt mit anderen Worten gesagt hast, zählt er trotzdem.',
  'barra3.spiego-sicuro': 'Thema als sicher markiert.',
  'barra3.spiego-cerchio-vuoto': 'Die mit dem leeren Kreis: Lies sie nochmal und versuch es in ein paar Tagen wieder.',
  'barra3.orale-niente': 'Heute steht im Plan nichts zum Abfragen.',
  'barra3.orale-contesto': 'Mündliche · <b>{nome}</b> · {cosa}',
  'barra3.n-argomenti': { one: '{n} Thema', other: '{n} Themen' },
  'barra3.esci': 'Beenden',
  'barra3.orale-sintesi': 'Mündliche {nome} zum Prüfungsstoff',

  // inviare, file, voce
  'barra3.crea-carte-da-file': 'Mach Lernkarten aus dieser Datei.',
  'barra3.niente-spiegazione': 'Okay, keine Erklärung.',
  'barra3.non-so-senza-ai': 'Das kann ich ohne KI noch nicht. Das verstehe ich:',
  'barra3.foto': 'Foto',
  'barra3.togli-file': '{nome} entfernen',
  'barra3.allegati-con-ai': 'Enter: Ich mache Karten daraus. Oder frag etwas anderes…',
  'barra3.allegati-senza-ai': 'Enter: Ich importiere die Karten (CSV, TSV, Text)',
  'barra3.importa-solo-testo': 'Ohne KI lese ich nur Textdateien mit einer Karte pro Zeile (Frage, dann Tab oder „;“ oder „ = “, dann Antwort), wie der Export von Anki. Für PDFs und Fotos brauchst du das lokale Gehirn oder deine KI (schreib „KI“).',
  'barra3.importa-carte': { one: '{n} Karte importieren?', other: '{n} Karten importieren?' },
  'barra3.e-altre': { one: 'und {n} weitere', other: 'und {n} weitere' },
  'barra3.importa-in': 'Ich lege sie in {nome} ab: Das änderst du auf der Seite.',
  'barra3.carte-importate': { one: '{n} Karte importiert.', other: '{n} Karten importiert.' },
  'barra3.ripassa-ora': 'Jetzt wiederholen',
  'barra3.ti-ascolto': 'Ich höre zu',
  'barra3.ti-ascolto-preparo': 'Ich höre zu · bereite die Spracheingabe vor…',
  'barra3.ti-ascolto-preparo-p': 'Ich höre zu · bereite die Spracheingabe vor {p} %',
  'barra3.voce-pronta': '{voce} lokal · halt {tasti} gedrückt und sprich',
  'barra3.scarico-voce': 'Lade {voce} · {p} %',
  'barra3.voce-ripiego': 'Parakeet startet nicht: Ich bereite Whisper vor',
  'barra3.preparo-voce': 'Ich bereite die Spracheingabe vor',

  // collegamenti, scorciatoie e avvisi
  'barra3.piu-tardi': 'Okay, später',
  'barra3.trascrivi-lezione': 'Vorlesung transkribieren',
  'barra3.fine-trascrizione': 'Transkription beenden',
  'barra3.ripeti': 'Nochmal',
  'barra3.spegni-ripeti': '„Nochmal“ ausschalten',
  'barra3.accendi-ripeti': '„Nochmal“ einschalten',
  'barra3.gioca': 'Spielen',
  'barra3.pausa': 'Pause',
  'barra3.focus-fatto': { one: '{n} Minute geschafft · Pause', other: '{n} Minuten geschafft · Pause' },
  'barra3.tempo-scaduto-consegna': 'Zeit abgelaufen · abgeben',
  'barra3.pausa-finita': 'Pause vorbei · weiter?',
  'barra3.ripeti-spento': '„Nochmal“ nach 3 Stunden ausgeschaltet',
  'barra3.lode-pronta': 'Lode {versione} ist bereit',
  'barra3.lode-uscita': 'Lode {versione} ist da',
  'barra3.sync-in-pausa': 'Synchronisierung pausiert · gib das Passwort ein',
  'barra3.cervello-locale': 'Lokales Gehirn',
  'barra3.ripassa-esame': '{nome} wiederholen',
  'barra3.ripasso': 'Wiederholung',
  'barra3.libretto': 'Notenübersicht',
};
