// Texte der Leiste, zweiter Teil (Deutsch): Dateien in der Leiste, Vorschläge des Coachs, deine KI, „Lode einrichten“ und
// Updates, Synchronisierung, Notizen, Abschluss der Vorlesung, Spiele, lokale Befehle, erklärte Fehler und Tagebuch,
// KI-Werkzeuge, mündliche Prüfung, Programmier-Agenten (js/lode.js).
export default {
  'barra2.file-non-so-usare': 'Damit kann ich nichts anfangen: {motivo}.',
  'barra2.peso-kb': '{n} KB',
  'barra2.peso-mb': '{n} MB',
  'barra2.cosa-ne-faccio': 'Was soll ich damit machen?',
  'barra2.per': 'Für',
  'barra2.corso': 'Kurs',
  'barra2.data-lezione': 'Datum der Vorlesung',
  'barra2.non-andata': 'Hat nicht geklappt: {errore}',
  'barra2.sintesi-cosa-ne-faccio': '{nome}: Was mache ich damit?',
  'barra2.allegato-lezione': 'An die Vorlesung {corso} angehängt.',
  'barra2.apri': 'Öffnen',
  'barra2.sbobina-nel-vault': 'Mitschrift von {corso} in deinem Vault.',
  'barra2.sbobina-nota-da': '{data} · von {da}',
  'barra2.sbobina-ricevuta': 'Mitschrift erhalten',
  'barra2.nessuna-riga-carte': 'Ich habe in dieser Datei keine Zeilen „Frage, Antwort“ gefunden.',
  'barra2.apro-registrazione': 'Ich öffne die Aufnahme…',
  'barra2.leggo-foto': 'Ich lese das Foto…',
  'barra2.lavagna-titolo': 'In die Notizen von {corso} übernehmen?',
  'barra2.lavagna-nota': 'Zusammen mit dem Foto, in der Notiz der heutigen Vorlesung. Lies es nochmal durch: Abgeschrieben hat es {motore}.',
  'barra2.lavagna-fatta': 'Tafel in den Notizen.',
  'barra2.leggo-file': 'Ich lese {nome}…',
  'barra2.file-senza-testo': 'Aus dieser Datei kann ich keinen Text lesen.',
  'barra2.file-senza-testo-incolla': 'Aus dieser Datei kann ich keinen Text lesen: Füg ihn ins Feld ein.',
  'barra2.prima-esame': 'Füg zuerst die Prüfung hinzu, zum Beispiel: „Prüfung Analysis 2 am 15. Januar 9 ECTS“.',
  'barra2.scrivo-carte': 'Ich schreibe die Karten…',
  'barra2.file-senza-carte': 'Aus dieser Datei habe ich keine Karten herausbekommen.',
  'barra2.riassumo': 'Ich fasse {nome} zusammen… {p} %',
  'barra2.riassunto-titolo': 'Die Zusammenfassung in Obsidian speichern?',
  'barra2.riassunto-nota': 'Neue Notiz in {cartella}, mit der Originaldatei als Anhang.',
  'barra2.riassunto-salvato': 'Zusammenfassung gespeichert.',
  'barra2.stelle-titolo': '★ Prüfungsrelevant · {esame}',
  'barra2.ora-un-gioco': 'Jetzt ein Spiel',
  'barra2.gioca': 'Spielen',
  'barra2.la-tua-ai': 'Deine KI',
  'barra2.ai-locale-attivo': 'Gerade nutzt Lode das <b>lokale Gehirn</b>: kostenlos, offline, die Notizen bleiben hier.',
  'barra2.ai-locale-da-installare': 'Das kostenlose <b>lokale Gehirn</b> installierst du über „Lode einrichten“.',
  'barra2.ai-chiave-spiegazione': 'Wenn du eine stärkere KI willst, verbinde deinen Schlüssel: Du bezahlst den Dienst direkt, nach Verbrauch (meist ein paar Cent pro Sitzung). Lode sieht nichts und verdient nichts daran; der Schlüssel bleibt auf diesem Computer.',
  'barra2.ai-nome-collegata': '{nome} · verbunden',
  'barra2.chiave-api': 'API-Schlüssel',
  'barra2.collega': 'Verbinden',
  'barra2.modello': 'Modell',
  'barra2.ai-solo-spiegazioni': 'Notizen und Vorlesungen bleiben auf dem Computer: deine KI nur für Erklärungen und die Mündliche',
  'barra2.usa-solo-locale': 'Nur das lokale Gehirn nutzen',
  'barra2.chiave-di': 'Schlüssel für {nome}',
  'barra2.incolla-chiave': 'Schlüssel einfügen',
  'barra2.si-crea-su': 'Du bekommst ihn auf <b>{sito}</b>.',
  'barra2.provo-chiave': 'Ich teste den Schlüssel…',
  'barra2.ai-collegata': '{nome} verbunden.',
  'barra2.ai-modello': 'Modell {modello}.',
  'barra2.ai-appunti-restano': 'Die Notizen bleiben auf dem Computer.',
  'barra2.ai-usano-tua': 'Erklärungen, Mündliche, Karten und Aufräumen nutzen deine KI.',
  'barra2.sintesi-ai-collegata': 'KI verbunden',
  'barra2.chiave-non-valida': 'Der Schlüssel ist ungültig.',
  'barra2.servizio-irraggiungibile': 'Ich erreiche den Dienst nicht: Bist du online?',
  'barra2.solo-locale-fatto': 'Lode nutzt nur das lokale Gehirn.',
  'barra2.ai-scollegata-sito': 'Ich habe den Schlüssel von diesem Computer gelöscht. In deinem {nome}-Konto gilt er noch: Wenn du ihn nicht mehr brauchst, widerruf ihn auch dort ({sito}).',
  'barra2.ai-scollegata-nome': 'Ich habe den Schlüssel von diesem Computer gelöscht. In deinem {nome}-Konto gilt er noch: Wenn du ihn nicht mehr brauchst, widerruf ihn auch dort.',
  'barra2.ai-scollegata': 'Ich habe den Schlüssel von diesem Computer gelöscht. In deinem Konto gilt er noch: Wenn du ihn nicht mehr brauchst, widerruf ihn auch dort.',
  'barra2.sintesi-la-tua-ai': 'deine KI',
  'barra2.agg-pronta': 'Lode {versione} ist bereit',
  'barra2.agg-si-installa': 'Wird automatisch installiert, wenn du Lode schließt',
  'barra2.riavvia-ora': 'Jetzt neu starten',
  'barra2.agg-uscita': 'Lode {versione} ist da',
  'barra2.agg-scarica-dmg': 'Lade die .dmg herunter und zieh Lode in Programme',
  'barra2.agg-scarica-github': 'Lade die neue Version von GitHub herunter',
  'barra2.scarica': 'Herunterladen',
  'barra2.agg-spenti': 'Lode {versione} · aus: Neue Versionen gibt es auf GitHub, auf der Seite Releases',
  'barra2.agg-scarico': 'Lade Lode {versione} · {p} %',
  'barra2.agg-pronta-riga': 'Lode {versione} ist bereit · wird automatisch installiert, wenn du Lode schließt',
  'barra2.agg-uscita-mac': 'Lode {versione} ist da · lade die .dmg herunter und zieh Lode in Programme',
  'barra2.agg-uscita-github': 'Lode {versione} ist da · lade es von GitHub herunter',
  'barra2.agg-manuale': 'Lode {versione} · ich sag Bescheid, wenn eine neue Version da ist (von GitHub, alle 6 Stunden)',
  'barra2.agg-automatici': 'Lode {versione} · aktualisiert sich selbst von GitHub, prüft alle 6 Stunden',
  'barra2.spegni': 'Ausschalten',
  'barra2.accendi': 'Einschalten',
  'barra2.prep-solo-app': 'Obsidian und das lokale Gehirn installierst du über die **Desktop-App** von Lode.',
  'barra2.prepara-lode': 'Lode einrichten',
  'barra2.il-tuo-vault': 'Dein Vault',
  'barra2.prep-vault-dett': '{percorso} · Home, Kurse, Vorlesungen, Glossar',
  'barra2.obs-installato': 'Installiert und mit dem Vault verbunden',
  'barra2.obs-da-installare': 'Kostenlos für den privaten Gebrauch · offizieller Installer von GitHub, etwa 230 MB',
  'barra2.installa': 'Installieren',
  'barra2.cervello-locale': 'Lokales Gehirn',
  'barra2.cervello-pronto-dett': '{modello} · läuft auf dem Computer, ohne Internet',
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · etwa {gb} GB',
  'barra2.pronto': 'bereit',
  'barra2.voce': 'Sprache',
  'barra2.voce-pronta-dett': '{voce} lokal · halt {tasti} gedrückt und sprich',
  'barra2.voce-da-preparare': '{descrizione}, lokal, auf Deutsch · etwa {peso} MB, nur einmal',
  'barra2.pronta': 'bereit',
  'barra2.prepara': 'Einrichten',
  'barra2.facoltativa': 'optional',
  'barra2.tua-ai-collegata-dett': '{nome} verbunden · du bezahlst nach Verbrauch, direkt beim Dienst',
  'barra2.tua-ai-da-collegare': 'Claude, ChatGPT, Gemini, Mistral…: stärker, nach Verbrauch mit deinem Schlüssel',
  'barra2.cambia': 'Ändern',
  'barra2.sincronizza-computer': 'Zwischen deinen Computern synchronisieren',
  'barra2.sperimentale': 'experimentell',
  'barra2.sblocca': 'Entsperren',
  'barra2.gestisci': 'Verwalten',
  'barra2.attiva': 'Aktivieren',
  'barra2.uso-gia-altrove': 'Ich nutze Lode schon auf einem anderen Computer',
  'barra2.collega-dett': 'Verbinde diesen Computer mit dem Vault, den du schon im Cloud-Ordner hast',
  'barra2.aggiornamenti': 'Updates',
  'barra2.prep-nota': 'Das lokale Gehirn ist kostenlos und arbeitet offline: Es zieht Definitionen heraus, macht Karten, erklärt und fragt ab. Deine KI ist ein optionales Extra: Lode sieht nichts und verdient nichts daran.',
  'barra2.detto-mia-ai': 'Meine KI',
  'barra2.detto-sincronizza': 'Zwischen Computern synchronisieren',
  'barra2.scarico-voce': 'Ich lade {voce}…',
  'barra2.sintesi-prepara': 'Lode einrichten',
  'barra2.installare-obsidian': 'Obsidian installieren?',
  'barra2.da': 'Von',
  'barra2.github-obsidian': 'github.com/obsidianmd (offiziell)',
  'barra2.peso': 'Größe',
  'barra2.circa-230-mb': 'etwa 230 MB',
  'barra2.dove': 'Wo',
  'barra2.applicazioni': 'Programme',
  'barra2.il-tuo-utente': 'dein Benutzerordner',
  'barra2.obs-nota': 'Obsidian ist für den privaten Gebrauch kostenlos. Es öffnet sich direkt in deinem Vault, auf der Home.',
  'barra2.installare-nome': '{nome} installieren?',
  'barra2.installare-cervello': 'Das lokale Gehirn installieren?',
  'barra2.cosa': 'Was',
  'barra2.ollama-motore': 'Ollama (Engine) + {nome}',
  'barra2.circa-gb': 'etwa {gb} GB',
  'barra2.perche': 'Warum',
  'barra2.cervello-nota': 'Wird nur einmal heruntergeladen. Danach funktioniert es ohne Internet und ohne Schlüssel.',
  'barra2.solo-clic': 'Wird nur per Klick bestätigt.',
  'barra2.avviato': 'Gestartet.',
  'barra2.continuo-da-solo': 'Du kannst das Panel schließen: Ich mache allein weiter.',
  'barra2.obsidian-pronto': 'Obsidian ist bereit',
  'barra2.cervello-pronto': 'Lokales Gehirn bereit',
  'barra2.sync-piede-cifrati': 'Verschlüsselt, synchronisiert mit {servizio}',
  'barra2.sync-piede': 'Synchronisiert mit {servizio}',
  'barra2.la-tua-cartella-cloud': 'deinem Cloud-Ordner',
  'barra2.dati-restano-qui': 'Die Daten bleiben auf diesem Computer',
  'barra2.portachiavi-mac': 'Das Passwort wird auf diesem Computer gespeichert (im Schlüsselbund).',
  'barra2.portachiavi-windows': 'Das Passwort wird auf diesem Computer gespeichert (geschützt durch dein Windows-Konto).',
  'barra2.portachiavi-sistema': 'Das Passwort wird auf diesem Computer gespeichert (im Schlüsselbund des Systems).',
  'barra2.senza-portachiavi': 'Dieser Computer hat keinen sicheren Schlüsselbund: Lode fragt dich bei jedem Start nach dem Passwort.',
  'barra2.sync-solo-app': 'Die Synchronisierung zwischen Computern gibt es in der **Desktop-App** von Lode.',
  'barra2.sync-stato-illeggibile': 'Ich kann den Status der Synchronisierung nicht lesen.',
  'barra2.sync-altro-computer': 'Öffne auf dem anderen Computer Lode und wähl „Ich nutze Lode schon auf einem anderen Computer“, dann den Vault „{vault}“ in {servizio}.',
  'barra2.la-cartella-cloud': 'dem Cloud-Ordner',
  'barra2.sync-non-accesa': 'Die Synchronisierung ist nicht an: Die Daten von Lode bleiben auf diesem Computer.',
  'barra2.sync-titolo-altro': 'Ich nutze Lode schon auf einem anderen Computer · experimentell',
  'barra2.sync-titolo': 'Zwischen deinen Computern synchronisieren · experimentell',
  'barra2.sync-sperimentale': '<b>Experimentell.</b> {testo}',
  'barra2.sync-cartella-cloud': 'Ich nutze den Cloud-Ordner, den du schon hast: kein Konto, kein Server von Lode. Ich kopiere den Vault dorthin und wechsle zur Kopie; der alte Ordner bleibt, wo er ist. {prima}',
  'barra2.sync-interrotto': '<b>Das Verschieben in {servizio} wurde unterbrochen.</b> Der alte Vault ist unverändert: Wähl den Ordner nochmal, dann mache ich da weiter, wo ich aufgehört habe.',
  'barra2.cartella-cloud': 'den Cloud-Ordner',
  'barra2.sync-interrotto-pw': 'Es hatte mit Passwort angefangen: Ich frage dich nochmal danach.',
  'barra2.vault-gia-qui': 'der Vault ist schon hier: nichts zu verschieben',
  'barra2.altra-cartella': 'Ein anderer Ordner…',
  'barra2.altra-cartella-dett': 'Syncthing, ein Netzwerkordner',
  'barra2.nessuna-cartella-cloud': 'Ich finde auf diesem Computer kein iCloud Drive, OneDrive, Dropbox oder Google Drive: Wähl selbst den Ordner, der synchronisiert wird.',
  'barra2.scegli-vault-cloud': 'Wähl den Vault im Cloud-Ordner',
  'barra2.gia-sincronizzato': '{servizio} · schon synchronisiert',
  'barra2.scegli-vault': 'Vault wählen…',
  'barra2.scegli-vault-dett': 'der Ordner „Lode“ in deinem Cloud-Ordner',
  'barra2.vault-resta': 'Der Vault, der jetzt auf diesem Computer ist, bleibt, wo er ist, unverändert.',
  'barra2.vault-resta-altro': 'Wenn Lode hier schon Prüfungen, Noten oder Karten hat, bringe ich sie als „Daten eines anderen ersten Starts“ in die Gruppe: Du importierst sie selbst, nichts ersetzt die Daten der anderen Computer.',
  'barra2.la-cartella-che-scegli': 'dem Ordner, den du wählst',
  'barra2.sintesi-uso-gia-altrove': 'Lode schon woanders in Nutzung',
  'barra2.sintesi-sincronizza': 'synchronisieren',
  'barra2.sincronizzare-con': 'Mit {servizio} synchronisieren?',
  'barra2.vault': 'Vault',
  'barra2.vault-resta-cloud': 'bleibt, wo er ist: Er ist schon im Cloud-Ordner',
  'barra2.cartella-lode-in': 'ein Ordner „Lode“ in {servizio}',
  'barra2.prima': 'Vorher',
  'barra2.dati-json-cronologia': 'die alte dati.json bleibt im Verlauf des Dienstes',
  'barra2.vault-adesso-resta': 'der jetzige Vault bleibt, wo er ist, unverändert',
  'barra2.dati-di-lode': 'Lode-Daten',
  'barra2.un-diario-per-computer': 'ein Tagebuch pro Computer: keine Konflikte, nichts geht verloren',
  'barra2.proteggi-con-password': 'Lode-Daten mit einem Passwort schützen',
  'barra2.password-almeno-8': 'Passwort (mindestens 8 Zeichen)',
  'barra2.password': 'Passwort',
  'barra2.ripetila': 'Wiederholen',
  'barra2.ripeti-password': 'Passwort wiederholen',
  'barra2.cifrati-in-chiaro-anche': '<b>Verschlüsselt:</b> {cifrati}. <b>Unverschlüsselt im Cloud-Ordner</b>, auch mit Passwort:',
  'barra2.sync-nota-password': 'Das Passwort kannst du auch später hinzufügen („Mit einem Passwort schützen“) oder ändern („Passwort ändern“). Auf den anderen Computern: „Ich nutze Lode schon auf einem anderen Computer“. {prima}',
  'barra2.spostamento-con-password': 'Das Verschieben hatte mit Passwort angefangen: Gib es nochmal ein.',
  'barra2.almeno-8': 'Mindestens 8 Zeichen.',
  'barra2.password-diverse': 'Die beiden Passwörter sind nicht gleich.',
  'barra2.preparo': 'Bereite vor…',
  'barra2.sincronizzato-con': 'Synchronisiert mit {servizio}.',
  'barra2.vault-era-gia-cloud': 'Der Vault war schon im Cloud-Ordner: Ab jetzt schreibt jeder Computer nur sein eigenes Tagebuch.',
  'barra2.cartella-prima-resta': 'Der alte Ordner („{da}“) bleibt, wo er war: Lösch ihn selbst, wann du willst. Auf den anderen Computern: „Ich nutze Lode schon auf einem anderen Computer“.',
  'barra2.vault-gia-in-servizio': 'In {servizio} gibt es schon einen synchronisierten Lode-Vault.',
  'barra2.usa-uso-gia': 'Nutz „Ich nutze Lode schon auf einem anderen Computer“, um dich damit zu verbinden.',
  'barra2.annullato': 'Abgebrochen.',
  'barra2.niente-cambiato': 'Ich habe nichts geändert.',
  'barra2.scrivi-password': 'Gib das Passwort ein.',
  'barra2.non-ancora': 'Noch nicht.',
  'barra2.non-andata-vault-intatto': 'Hat nicht geklappt: {errore}. Der alte Vault ist unverändert.',
  'barra2.collegato-vault-in': 'Mit dem Vault in {servizio} verbunden.',
  'barra2.dati-protetti-password': 'Die Lode-Daten sind mit einem Passwort geschützt: Gib es ein, um sie zu empfangen.',
  'barra2.ricevo-dati': 'Ich empfange die Daten von den anderen Computern: Sie kommen von selbst. Du kannst Lode schon nutzen.',
  'barra2.dati-importati-altrove': 'Die Daten, die du auf diesem Computer hattest ({n} Einträge), sind unter „Daten eines anderen ersten Starts“ im Tab „Synchronisieren“: Importier sie von dort. Die alte Datei bleibt im Vault „{vault}“.',
  'barra2.cartella-inusabile': 'Diesen Ordner kann ich nicht nutzen.',
  'barra2.diario-illeggibile': 'Das Tagebuch von Lode auf diesem Computer ist nicht lesbar',
  'barra2.diario-illeggibile-nota': 'Es wurde nichts gelöscht: Der Datenordner von Lode antwortet nicht (Festplatte voll oder defekt?). Die Änderungen von jetzt kommen in eine eigene Datei.',
  'barra2.riprova': 'Nochmal versuchen',
  'barra2.vault-sparito': 'Die Lode-Daten dieses Computers sind sicher in seinem Tagebuch. Wenn du den Vault verschoben hast, wähl den Ordner, in den du ihn gelegt hast.',
  'barra2.trova-vault': 'Vault suchen',
  'barra2.lode-vecchia-campi': { one: '<b>Von einem alten Lode:</b> {n} Feld, das anders ist als heute. Es ändert nichts von selbst: Die Kopie der Datei liegt im Datenordner von Lode (sync/copie).', other: '<b>Von einem alten Lode:</b> {n} Felder, die anders sind als heute. Sie ändern nichts von selbst: Die Kopie der Datei liegt im Datenordner von Lode (sync/copie).' },
  'barra2.aggiunte': { one: '<b>Daten eines anderen ersten Starts oder eines alten Lode:</b> {n} Eintrag (Prüfungen, Karten, Lerneinheiten…), den das Tagebuch nicht hat. Er kommt nicht von selbst rein.', other: '<b>Daten eines anderen ersten Starts oder eines alten Lode:</b> {n} Einträge (Prüfungen, Karten, Lerneinheiten…), die das Tagebuch nicht hat. Sie kommen nicht von selbst rein.' },
  'barra2.importa-aggiunte': 'Ergänzungen importieren',
  'barra2.password-dati-lode': 'Passwort der Lode-Daten',
  'barra2.intanto-funziona': 'Solange arbeitet Lode mit den Daten dieses Computers: Die Änderungen warten im Tagebuch. {portachiavi}',
  'barra2.ho-dimenticato-password': 'Passwort vergessen',
  'barra2.dimentica-password-qui': 'Passwort hier vergessen',
  'barra2.cifrati-in-chiaro': '<b>Verschlüsselt:</b> {cifrati}. <b>Unverschlüsselt im Cloud-Ordner:</b>',
  'barra2.cambia-password': 'Passwort ändern',
  'barra2.senza-password': 'Ohne Passwort: Wer deinen Cloud-Ordner lesen kann, kann auch die Lode-Daten lesen, so wie schon die Notizen.',
  'barra2.proteggi-password': 'Mit einem Passwort schützen',
  'barra2.recuperi': 'Die Änderungen, die das Tagebuch nicht übernehmen konnte, stehen in {n} Dateien „recupero-…json“ (die letzte: „{file}“) im Datenordner von Lode: Ich habe sie nicht weggeworfen.',
  'barra2.recupero': 'Die Änderungen, die das Tagebuch nicht übernehmen konnte, stehen in der Datei „{file}“ im Datenordner von Lode: Ich habe sie nicht weggeworfen.',
  'barra2.smetti-qui': 'Auf diesem Computer aufhören',
  'barra2.importati-record': { one: '{n} Eintrag importiert.', other: '{n} Einträge importiert.' },
  'barra2.ora-su-tutti': 'Jetzt sind sie auf allen Computern.',
  'barra2.non-andata-punto': 'Hat nicht geklappt.',
  'barra2.controllo': 'Prüfe…',
  'barra2.sbloccata': 'Entsperrt.',
  'barra2.password-ricordata': 'Das Passwort ist auf diesem Computer gespeichert.',
  'barra2.chiedero-prossimo-avvio': 'Ich frage dich beim nächsten Start danach.',
  'barra2.password-nuova-almeno-8': 'Neues Passwort (mindestens 8 Zeichen)',
  'barra2.password-nuova': 'Neues Passwort',
  'barra2.password-nuova-pronta': 'Neues Passwort bereit.',
  'barra2.altri-chiederanno': 'Die anderen Computer fragen dich einmal danach.',
  'barra2.cambiare-password': 'Passwort ändern?',
  'barra2.rifa-password-nuova': 'Lode schreibt die Lode-Daten im Cloud-Ordner mit dem neuen Passwort neu. {testo}',
  'barra2.scegliere-password-nuova': 'Ein neues Passwort wählen?',
  'barra2.proteggere-password': 'Die Lode-Daten mit einem Passwort schützen?',
  'barra2.rifa-cifrati': 'Lode schreibt die Lode-Daten im Cloud-Ordner neu, verschlüsselt mit dem Passwort. Die anderen Computer fragen dich danach. {testo}',
  'barra2.password-dimenticata': 'Passwort auf diesem Computer vergessen.',
  'barra2.chiedero-di-nuovo': 'Ich frage dich nochmal danach.',
  'barra2.smettere-qui': 'Auf diesem Computer aufhören?',
  'barra2.vault-copiato-fuori': 'kopiert in einen Ordner außerhalb des Cloud-Ordners, den du wählst',
  'barra2.tutti-dati': 'alle, auch die der anderen Computer bis heute',
  'barra2.gli-altri-computer': 'Die anderen Computer',
  'barra2.continuano-sincronizzarsi': 'synchronisieren weiter untereinander',
  'barra2.smesso-qui': 'Auf diesem Computer beendet.',
  'barra2.smesso-nota': 'Der Vault ist jetzt außerhalb des Cloud-Ordners. Um überall aufzuhören, mach das auf jedem Computer.',
  'barra2.sintesi-smessa': 'Synchronisierung hier beendet',
  'barra2.ultima-lezione': 'Letzte Vorlesung',
  'barra2.lezione-di': 'Vorlesung {corso}',
  'barra2.cosa-sa-lode': 'Was Lode über mich weiß',
  'barra2.vai-a-note': { one: 'Gehe zu… · {n} Notiz', other: 'Gehe zu… · {n} Notizen' },
  'barra2.radice-vault': 'Vault',
  'barra2.oggi': 'heute',
  'barra2.cerca-nota-segnaposto': 'Notiz suchen: Kurs, Vorlesung, Datum…',
  'barra2.cerca-nota': 'Notiz suchen',
  'barra2.nessuna-nota': 'Keine Notiz gefunden.',
  'barra2.sintesi-cerco': 'suche „{q}“',
  'barra2.sintesi-note': 'Notizen',
  'barra2.niente-appunti-di': 'Ich finde in den letzten Tagen keine Notizen zu **{corso}**.',
  'barra2.niente-appunti': 'Ich finde keine Vorlesung mit genug Notizen: Schreib sie in den Abschnitt „{sezione}“ der Notiz.',
  'barra2.appunti-serve-ai': 'Um die Notizen zu lesen, brauche ich KI: Installier das **lokale Gehirn** (kostenlos, funktioniert offline) über „Lode einrichten“ oder verbinde deine KI: Schreib „KI“.',
  'barra2.leggo-appunti-di': 'Ich lese die Notizen von {corso}…',
  'barra2.appunti-illeggibili': 'Ich konnte die Notizen nicht lesen: {errore}',
  'barra2.nessuna-definizione-nuova': 'In den Notizen habe ich keine neuen Definitionen gefunden. Schreib sie aus, auch wenn sie kurz sind.',
  'barra2.aggiungere-a': 'Zu {corso} · {data} hinzufügen?',
  'barra2.chiudi-nota': { one: '{n} Definition in der Notiz der Vorlesung. Prüf, ob sie stimmt: Geschrieben hat sie {motore}.', other: '{n} Definitionen in der Notiz der Vorlesung. Prüf, ob sie stimmen: Geschrieben hat sie {motore}.' },
  'barra2.chiudi-nota-stelle': { one: '{n} Definition und {stelle} ★ in der Notiz der Vorlesung. Prüf, ob alles stimmt: Geschrieben hat es {motore}.', other: '{n} Definitionen und {stelle} ★ in der Notiz der Vorlesung. Prüf, ob alles stimmt: Geschrieben hat es {motore}.' },
  'barra2.lezione-chiusa': 'Vorlesung abgeschlossen.',
  'barra2.definizioni-pronte': { one: '{n} Definition bereit für die Spiele.', other: '{n} Definitionen bereit für die Spiele.' },
  'barra2.sintesi-definizioni': { one: '{n} Definition', other: '{n} Definitionen' },
  'barra2.appunti-sparsi-oggi': 'die losen Notizen von heute',
  'barra2.la-nota-di': 'die Notiz von {corso}',
  'barra2.apro-in-obsidian': 'Ich öffne {nome} in Obsidian.',
  'barra2.apro-se-non-trova': 'Ich öffne {nome}. Wenn Obsidian den Vault nicht findet, mach beim ersten Mal **Ordner als Vault öffnen** und wähl den Ordner „{percorso}“: Danach bleibt er verbunden.',
  'barra2.aperto-editor': 'Ich habe {nome} mit dem Editor des Systems geöffnet. Mit **Obsidian** (kostenlos, obsidian.md) ist der Vault „{percorso}“ schon bereit: Ordner, Vorlagen, Stundenplan und dein Gedächtnis.',
  'barra2.nota-non-si-apre': 'Ich kann die Notiz nicht öffnen: {errore}',
  'barra2.appunti-solo-app': 'Notizen in Obsidian gibt es in der **Desktop-App** von Lode: Dort wird jede Vorlesung zu einer Notiz in deinem Vault, mit den ★ und Definitionen, die du über die Leiste markierst.',
  'barra2.gioco-sai-gia-di': 'Die Definitionen von {corso} für heute kannst du schon: Sie kommen zurück, wenn sie dir gerade entwischen.',
  'barra2.gioco-sai-gia': 'Die Definitionen für heute kannst du schon: Sie kommen zurück, wenn sie dir gerade entwischen.',
  'barra2.gioco-nessuna-di': 'Noch keine Definitionen von {corso}. Drück in der Vorlesung auf **Definition** (oder schreib „def: Begriff = Definition“) oder schreib sie in Obsidian in den Abschnitt „{sezione}“ der Vorlesung.',
  'barra2.gioco-nessuna': 'Noch keine Definitionen. Drück in der Vorlesung auf **Definition** (oder schreib „def: Begriff = Definition“) oder schreib sie in Obsidian in den Abschnitt „{sezione}“ der Vorlesung.',
  'barra2.gioco-di': 'Spiel · {corso}',
  'barra2.ultime-lezioni': 'letzte Vorlesungen',
  'barra2.manche-di': '{i} von {n}',
  'barra2.abbina': 'Ordne jedem Begriff seine Definition zu.',
  'barra2.chi-sono': 'Wer bin ich?',
  'barra2.completa': '{termine}: Ergänze die Definition.',
  'barra2.parola-mancante': 'Fehlendes Wort',
  'barra2.controlla-invio': 'Prüfen <kbd>Enter</kbd>',
  'barra2.non-la-so': 'Weiß ich nicht',
  'barra2.te-la-ricordi': 'Weißt du es noch?',
  'barra2.mostra-spazio': 'Zeigen <kbd>Leertaste</kbd>',
  'barra2.non-la-sapevo': 'Wusste ich nicht <kbd>1</kbd>',
  'barra2.la-sapevo': 'Wusste ich <kbd>2</kbd>',
  'barra2.tutte-giuste': 'Alle richtig. Die sitzen.',
  'barra2.da-rinforzare': 'Zum Festigen: {elenco}. Sie kommen morgen wieder.',
  'barra2.secondi': { one: '{n} Sekunde', other: '{n} Sekunden' },
  'barra2.minuti': '{n} Min.',
  'barra2.sintesi-punti': '{punti} von {tot}',
  'barra2.ancora-una': 'Noch eine',
  'barra2.gioca-ancora': 'Nochmal spielen',
  'barra2.sintesi-gioco': 'Spiel',
  'barra2.pausa-finita': 'Pause vorbei.',
  'barra2.fermato-dopo': 'Nach {tempo} gestoppt.',
  'barra2.prova-resta-aperta': 'Die Probeklausur bleibt offen: Schreib „Probeklausur“, um sie abzugeben.',
  'barra2.li-conto': 'Ich zähle sie zu deiner Lernzeit.',
  'barra2.sintesi-timer-fermato': 'Timer gestoppt',
  'barra2.nessun-timer': 'Es läuft kein Timer.',
  'barra2.timer-in-pausa': 'Timer pausiert.',
  'barra2.scrivi-riprendi': 'Schreib „weiter“, wenn du zurück bist.',
  'barra2.si-riparte': 'Weiter geht’s.',
  'barra2.focus-esame-sconosciuto': 'Ich finde **{nome}** nicht bei deinen Prüfungen. Soll ich freies Lernen starten? Schreib „Fokus {min}“.',
  'barra2.di-quale-esame': 'Welche Prüfung?',
  'barra2.idoneita-registrata': '{nome}: als bestanden eingetragen.',
  'barra2.voto-in': '{voto} in {nome}.',
  'barra2.voto-lode-in': '{voto} cum laude in {nome}.',
  'barra2.nuovo-esame-6-cfu': 'Neue Prüfung mit 6 ECTS: Korrigier die ECTS in der Notenübersicht.',
  'barra2.media-diff': 'Schnitt {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome}: {voto}',
  'barra2.idoneita': 'bestanden',
  'barra2.trenta-e-lode': '30 cum laude. Das wird gefeiert.',
  'barra2.bel-colpo': 'Starke Leistung. Heute durchatmen, morgen geht’s weiter.',
  'barra2.esame-aggiornato': '{nome} aktualisiert.',
  'barra2.esame-aggiunto': '{nome} hinzugefügt.',
  'barra2.esame-nota': '{quando} · {cfu} ECTS',
  'barra2.esame-nota-cambiali': '{quando} · {cfu} ECTS (ändere sie, wenn es mehr sind)',
  'barra2.senza-data': 'ohne Datum',
  'barra2.piano-ore': 'Um gut vorbereitet zu sein: etwa **{h} Std. pro Tag** ({tot} Std. insgesamt).',
  'barra2.proposte-spente-riaccendi': 'Die Vorschläge sind aus: Du schaltest sie mit „Vorschläge normal“ wieder ein.',
  'barra2.proposte-da-adesso': 'Ab jetzt schlage ich dir Spiele, Wiederholungen und Fragen zu {nome} vor, wenn du am Computer bist und Zeit hast.',
  'barra2.proposte-da-adesso-vicino': 'Ab jetzt schlage ich dir Spiele, Wiederholungen und Fragen zu {nome} vor, wenn du am Computer bist und Zeit hast, immer öfter, je näher die Prüfung rückt.',
  'barra2.carta-aggiunta': 'Karte hinzugefügt.',
  'barra2.senza-esame': 'ohne Prüfung',
  'barra2.esame-sconosciuto': 'Ich finde **{nome}** nicht bei deinen Prüfungen.',
  'barra2.spiego-senza-programma': 'Füg zuerst den Prüfungsstoff einer Prüfung ein („Prüfungsstoff für Analysis 2“): Dann erklärst du mir die Themen und ich sage dir, was du ausgelassen hast.',
  'barra2.argomento-sconosciuto': 'Ich finde **{q}** nicht im Prüfungsstoff deiner Prüfungen.',
  'barra2.esame-non-trovato': 'Ich finde die Prüfung **{nome}** nicht.',
  'barra2.domande-di-quale-esame': 'Welche Prüfung? Zum Beispiel: „Prüfungsfragen für Analysis 2: …“.',
  'barra2.nella-nota-lezione': 'In der Notiz der Vorlesung.',
  'barra2.in-orario': '{corso} im Stundenplan.',
  'barra2.aula': 'Raum {aula}',
  'barra2.sintesi-in-orario': '{corso} im Stundenplan',
  'barra2.orario-spiegazione': 'Wenn du in der Vorlesung bist, weiß die Leiste das: Sie öffnet sich mit der Schnellerfassung (★ prüfungsrelevant, Definitionen, Fragen) und schlägt dir zu Hause zwei Minuten Spiel zu dem vor, was du gerade gehört hast.',
  'barra2.proposte-spente': 'Vorschläge aus.',
  'barra2.proposte-poche': 'Wenige Vorschläge.',
  'barra2.proposte-normali': 'Normale Vorschläge.',
  'barra2.proposte-frequenti': 'Häufige Vorschläge.',
  'barra2.riaccendi-quando-vuoi': 'Du schaltest sie wieder ein, wann du willst.',
  'barra2.proposte-mai-quando': 'Nie in der Vorlesung, bei der Arbeit, im Fokus oder in den Ruhezeiten.',
  'barra2.niente-da-proporre': 'Gerade habe ich nichts vorzuschlagen: Füg eine Prüfung mit Datum hinzu oder notier in der Vorlesung ein paar Definitionen.',
  'barra2.trascrizione-in-pausa': 'Transkription pausiert.',
  'barra2.scrivi-riprendi-trascrizione': 'Schreib „Transkription fortsetzen“, wenn es weitergeht.',
  'barra2.riprendo-trascrivere': 'Ich transkribiere weiter.',
  'barra2.err-valutato': 'Bewertetes Projekt: Die Korrektur zeige ich dir nicht.',
  'barra2.errore-spiegato': 'Fehler erklärt',
  'barra2.correzione-vista': 'Korrektur angesehen',
  'barra2.copia-errore': 'Kopier den Fehler aus dem Terminal (oder der IDE) und schreib nochmal „erklär den Fehler“.',
  'barra2.incolla-errore': 'Füg den Fehler nach dem Doppelpunkt ein: „erklär den Fehler: …“.',
  'barra2.nessun-errore-nel-testo': 'In diesem Text finde ich keinen Fehler vom Compiler oder vom Programm. Kopier alles, ab der Zeile mit dem Dateinamen, und versuch es nochmal.',
  'barra2.segui-valutato': 'Du verfolgst ein bewertetes Projekt: Die Korrektur zeige ich dir nicht.',
  'barra2.diario-solo-app': 'Das Tagebuch liegt im Vault: Dafür brauchst du die **Desktop-App** von Lode.',
  'barra2.progetto-sconosciuto': 'Ich finde kein Projekt mit dem Namen „{nome}“.',
  'barra2.nessun-progetto-segui': 'Ich verfolge noch kein Projekt. Schreib **Projekt verfolgen** und wähl den Ordner des Praktikums.',
  'barra2.diario-spento-per': 'Für **{progetto}** ist das Tagebuch aus: Ich schreibe nichts in den Vault. Du schaltest es wieder ein mit „Tagebuch für {progetto} einschalten“.',
  'barra2.diario-non-si-apre': 'Ich kann das Tagebuch nicht öffnen: {errore}',
  'barra2.diario-di': 'Tagebuch von {progetto}.',
  'barra2.aperto-editor-sistema': 'Mit dem Editor des Systems geöffnet: Mit Obsidian ist es bequemer.',
  'barra2.aperto-in-obsidian': '{file} · in Obsidian geöffnet.',
  'barra2.sintesi-diario-di': 'Tagebuch von {progetto}',
  'barra2.nessun-progetto': 'Ich verfolge noch kein Projekt.',
  'barra2.diario-acceso': 'Tagebuch von {nome} an.',
  'barra2.diario-acceso-nota': 'Ich schreibe in den Vault, was ich sehe: was sich ändert und die Tests. Wer die Zeilen schreibt, weiß ich nicht.',
  'barra2.diario-spento': 'Tagebuch von {nome} aus.',
  'barra2.diario-spento-nota': 'Ab jetzt schreibe ich nichts mehr zu diesem Projekt in den Vault. Die schon geschriebenen Notizen bleiben: Du kannst sie in Obsidian löschen.',
  'barra2.focus-di-minuti': 'Fokus von {min} Minuten.',
  'barra2.focus-di-minuti-su': 'Fokus von {min} Minuten auf {nome}.',
  'barra2.salvare-carte': { one: '{n} Karte speichern?', other: '{n} Karten speichern?' },
  'barra2.salvare-carte-di': { one: '{n} Karte von {nome} speichern?', other: '{n} Karten von {nome} speichern?' },
  'barra2.entrano-ripasso': 'Sie kommen in die heutige Wiederholung.',
  'barra2.carte-salvate': { one: '{n} Karte gespeichert.', other: '{n} Karten gespeichert.' },
  'barra2.ripassa-ora': 'Jetzt wiederholen',
  'barra2.sintesi-carte': { one: '{n} Karte', other: '{n} Karten' },
  'barra2.aggiungere-esame': '{nome} hinzufügen?',
  'barra2.esame': 'Prüfung',
  'barra2.cfu': 'ECTS',
  'barra2.appello': 'Termin',
  'barra2.registrare-voto': '{voto} eintragen?',
  'barra2.registrare-voto-lode': '{voto} cum laude eintragen?',
  'barra2.esame-nuovo-6-cfu': '{nome} (neu, 6 ECTS)',
  'barra2.voto': 'Note',
  'barra2.voto-e-lode': '{voto} cum laude',
  'barra2.voto-registrato': 'Note eingetragen.',
  'barra2.media': 'Schnitt {media}',
  'barra2.leggo-il-file': 'Ich lese die Datei…',
  'barra2.prof-ci-pensa': 'Der Prof denkt nach…',
  'barra2.un-attimo': 'Einen Moment…',
  'barra2.file-senza-carte-locale': 'Aus dieser Datei habe ich keine Karten herausbekommen: Wenn es ein PDF ist, kann das lokale Modell es nicht lesen. Versuch es mit einem Foto der Seiten oder mit dem Text.',
  'barra2.file-illeggibile': 'Ich konnte die Datei nicht lesen: {errore}',
  'barra2.chiave-non-valida-ricollega': 'Der Schlüssel ist ungültig: Verbinde ihn neu, indem du „KI“ schreibst.',
  'barra2.troppe-richieste': 'Zu viele Anfragen in kurzer Zeit: Versuch es in einer Minute nochmal.',
  'barra2.sovraccarico': '{motore} ist gerade überlastet: Versuch es gleich nochmal.',
  'barra2.manca-rete': 'Anscheinend gibt es kein Netz.',
  'barra2.qualcosa-non-andato': 'Etwas hat nicht geklappt: {errore}',
  'barra2.orale-serve-ai-app': 'Zum Abfragen brauche ich KI: Installier das **lokale Gehirn** über „Lode einrichten“ (kostenlos, offline) oder verbinde deine KI (schreib „KI“). Solange kannst du die Karten **wiederholen**.',
  'barra2.orale-serve-ai-web': 'Zum Abfragen brauche ich KI: Füg deinen Claude-Schlüssel in den **Einstellungen** hinzu (kostet ein paar Cent pro Sitzung). Solange kannst du die Karten **wiederholen**.',
  'barra2.orale-esame-sconosciuto': 'Ich finde **{nome}** nicht: Ich frage dich trotzdem dazu ab.',
  'barra2.su-quale-esame': 'Zu welcher Prüfung?',
  'barra2.aggiungi-prima-esame': 'Füg zuerst eine Prüfung hinzu.',
  'barra2.interrogami-su': 'Frag mich zu {nome} ab',
  'barra2.orale-di-contesto': 'Mündliche · <b>{nome}</b>',
  'barra2.esci': 'Beenden',
  'barra2.sintesi-orale-di': 'Mündliche {nome}',
  'barra2.domanda-n-di': '**Frage {n} von {max}.** {domanda}',
  'barra2.prof-non-risponde': 'Der Prof antwortet nicht: {errore}',
  'barra2.prof-ascolta': 'Der Prof hört zu…',
  'barra2.orale-mancava': 'Es fehlte: {cosa}',
  'barra2.era-giusta': 'War richtig',
  'barra2.segnata-giusta': 'Als richtig markiert',
  'barra2.prof-scrive-voto': 'Der Prof schreibt die Note…',
  'barra2.orale-titolo': { one: 'Mündliche · {nome} · {n} Frage', other: 'Mündliche · {nome} · {n} Fragen' },
  'barra2.da-ripassare': 'Zu wiederholen',
  'barra2.orale-calcolo': 'Die Note rechnet Lode aus deinen Antworten aus (richtig 3 Punkte, teilweise 2).',
  'barra2.orale-calcolo-contestate': { one: 'Die Note rechnet Lode aus deinen Antworten aus (richtig 3 Punkte, teilweise 2), mit der Antwort, die du als richtig markiert hast.', other: 'Die Note rechnet Lode aus deinen Antworten aus (richtig 3 Punkte, teilweise 2), mit den Antworten, die du als richtig markiert hast.' },
  'barra2.orale-giudizi-locale': 'Die Bewertungen sind die Meinung des lokalen Modells: Es kann sich irren. Das ist Training, keine Vorhersage.',
  'barra2.orale-giudizi-ai': 'Die Bewertungen sind die Meinung der KI. Das ist Training, keine Vorhersage.',
  'barra2.sintesi-orale-voto': 'Mündliche {nome}: {voto}',
  'barra2.orale-chiuso': 'Mündliche beendet.',
  'barra2.ripassa-esitato': 'Wiederhol die Fragen, bei denen du gezögert hast.',
  'barra2.agenti-solo-app': 'Die Brücke zu den Agenten gibt es in der **Desktop-App** von Lode.',
  'barra2.ponte-non-risponde': 'Die Brücke antwortet nicht: {errore}',
  'barra2.agente-sconosciuto': 'Mit **{agente}** kann ich mich noch nicht verbinden. Schreib „Agenten“, um die zu sehen, die ich kenne.',
  'barra2.agenti-titolo': 'Programmier-Agenten',
  'barra2.agenti-spiegazione': 'Verbinde den Agenten, den du fürs Praktikum nutzt: Am Ende jedes Zugs sagt dir Lode, was er in den Projekten, die du verfolgst, wirklich angefasst hat, ob er nach der letzten Änderung die Tests laufen ließ und ob er Tests geändert hat, während sie fehlschlugen.',
  'barra2.ag-collegato-eventi': { one: 'verbunden · {n} Ereignis, das letzte um {ora}', other: 'verbunden · {n} Ereignisse, das letzte um {ora}' },
  'barra2.ag-collegato-nessuno': 'verbunden · noch kein Ereignis',
  'barra2.ag-trovato': 'auf diesem Computer gefunden',
  'barra2.ag-non-trovato': 'nicht gefunden',
  'barra2.scollega': 'Trennen',
  'barra2.agenti-nota': 'Nur lesen: Lode antwortet den Agenten nicht, entscheidet nichts und erweitert ihre Rechte nicht. Bevor ich in ihre Konfiguration schreibe, zeige ich dir die genauen Zeilen. Ereignisse zählen nur in den Projekten, die du verfolgst („Projekt verfolgen“), der Rest wird verworfen; was du dem Agenten schreibst, wird nicht gespeichert.',
  'barra2.sintesi-agenti': 'Agenten',
  'barra2.niente-toccato': 'Okay, ich habe nichts angefasst.',
  'barra2.ag-scollegato': '{nome} getrennt.',
  'barra2.ag-gia-collegato': '{nome} war schon verbunden.',
  'barra2.ag-collegato': '{nome} verbunden.',
  'barra2.ag-tolte-righe': 'Ich habe nur meine eigenen Zeilen entfernt.',
  'barra2.ag-poi-segui': 'Dann verfolge das Projekt des Praktikums („Projekt verfolgen“).',
  'barra2.l-agente': 'Der Agent',
  'barra2.ag-finito-test-dopo': { one: 'ist fertig: {n} Datei, Tests nach der letzten Änderung ausgeführt', other: 'ist fertig: {n} Dateien, Tests nach der letzten Änderung ausgeführt' },
  'barra2.ag-finito-test-prima': { one: 'ist fertig: {n} Datei, Tests nicht nochmal ausgeführt', other: 'ist fertig: {n} Dateien, Tests nicht nochmal ausgeführt' },
  'barra2.ag-finito-senza-test': { one: 'ist fertig: {n} Datei, keine Tests', other: 'ist fertig: {n} Dateien, keine Tests' },
  'barra2.guarda': 'Ansehen',
  'barra2.nessun-turno': 'Noch kein Zug eines Agenten in den Projekten, die du verfolgst. Schreib „Agenten“, um einen zu verbinden.',
  'barra2.esito-non-noto': 'Ergebnis unbekannt',
  'barra2.riuscito': 'erfolgreich',
  'barra2.fallito-codice': 'fehlgeschlagen (Code {codice})',
  'barra2.alle': 'um {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> Datei geändert: {elenco}.', other: '<b>{n}</b> Dateien geändert: {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> Dateien geändert.',
  'barra2.comandi': { one: '{n} Befehl', other: '{n} Befehle' },
  'barra2.test-lanciati-dopo': { one: 'Tests {n}-mal ausgeführt, zuletzt <code>{comando}</code> {esito}, nach der letzten Änderung', other: 'Tests {n}-mal ausgeführt, zuletzt <code>{comando}</code> {esito}, nach der letzten Änderung' },
  'barra2.test-lanciati-prima': { one: 'Tests {n}-mal ausgeführt, zuletzt <code>{comando}</code> {esito}, <b>vor</b> der letzten Änderung', other: 'Tests {n}-mal ausgeführt, zuletzt <code>{comando}</code> {esito}, <b>vor</b> der letzten Änderung' },
  'barra2.nessun-test-lanciato': 'keine Tests ausgeführt',
  'barra2.cosa-cambiato': 'Was sich geändert hat',
  'barra2.prova-tu': 'Teste selbst',
  'barra2.preparati-discussione': 'Bereite dich auf die Abnahme vor',
  'barra2.parole-agente': 'Was der Agent sagt, sind Worte: Die Tests hat er nur dann wirklich ausgeführt, wenn du sie hier siehst. Die Regeln sind fest: Wenn sie nichts finden, ist das keine Garantie.',
  'barra2.prova-il-progetto': 'Projekt testen',
  'barra2.sintesi-turno': { one: '{chi}: {n} Datei', other: '{chi}: {n} Dateien' },
};
