// Texte der Begrüßung (Deutsch): die Pflichtschritte (Name, Installationen) und die schnelle Einrichtung (Studiengang,
// Notenübersicht, Prüfungen, Stundenplan, Gewohnheiten), dazu die Verbindung mit einem Lode, das schon auf einem anderen
// Computer läuft.
export default {
  // la cornice
  'benvenuto.tasti-mac': '⌥ Leertaste',
  'benvenuto.tasti-altri': 'Strg ⇧ Leertaste',
  'benvenuto.avanti': 'Weiter',
  'benvenuto.indietro': 'Zurück',
  'benvenuto.salta': 'Überspringen',
  'benvenuto.obbligatorio': 'Pflicht',
  'benvenuto.facoltativo': 'Optional · schnelle Einrichtung',
  // ciao
  'benvenuto.ciao-titolo': 'Hallo.<br>Ich bin Lode.',
  'benvenuto.ciao-sotto': 'Ich wohne in einer kleinen Leiste oben am Bildschirm. In der Vorlesung verpasst du nichts, zu Hause trainiere ich dich mit dem, was du gleich vergisst, und alles landet in deinem Obsidian.',
  'benvenuto.ciao-nota': 'Erst drei nötige Dinge (zwei Minuten, plus Downloads). Dann, wenn du willst, die schnelle Einrichtung.',
  'benvenuto.altro-computer': 'Ich nutze Lode schon auf einem anderen Computer',
  'benvenuto.sperimentale': '(experimentell)',
  'benvenuto.iniziamo': 'Los geht’s',
  // un altro computer
  'benvenuto.scegli-vault-cloud': 'Wähl den Lode-Vault in deinem Cloud-Ordner (iCloud Drive, OneDrive, Dropbox, Google Drive).',
  'benvenuto.scegli-vault': 'Vault wählen…',
  'benvenuto.password-dati': 'Das Passwort für die Lode-Daten, falls du eins gesetzt hast',
  'benvenuto.collego': 'Verbinde…',
  'benvenuto.cartella-no': 'Diesen Ordner kann ich nicht nutzen.',
  'benvenuto.ricevo-dati': 'Ich empfange die Daten von den anderen Computern… Du kannst Lode schon nutzen: Sie kommen von selbst.',
  'benvenuto.inizia': 'Starten',
  'benvenuto.password-sbagliata': 'Falsches Passwort: Versuch es nochmal.',
  'benvenuto.password-serve': 'Die Lode-Daten sind mit einem Passwort geschützt: Gib es oben ein.',
  // nome
  'benvenuto.nome-titolo': 'Wie heißt du?',
  'benvenuto.nome-sotto': 'Nur zum Begrüßen. Bleibt auf deinem Computer.',
  'benvenuto.nome-segnaposto': 'Dein Name',
  'benvenuto.togli-esempio': 'Die Beispieldaten von „Giulia“ entfernen (erfundene Prüfungen, Noten, Karten und Lernstunden). Was du selbst hinzugefügt hast, bleibt.',
  // installazioni
  'benvenuto.web-titolo': 'Das ganze Lode gibt es in der App.',
  'benvenuto.web-sotto': 'Im Browser hast du Notenübersicht, Timer, Wiederholung und Spiele. Obsidian, die KI auf dem Computer, die Sprache und die Transkription der Vorlesungen gibt es in der Desktop-App.',
  'benvenuto.installa-titolo': 'Machen wir deinen Computer bereit.',
  'benvenuto.installa-sotto': 'Drei Installationen, nur einmal. Danach funktioniert Lode auch ohne Internet, und nichts von dir verlässt den Computer.',
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'wo deine Notizen wohnen: ein fertiger Vault',
  'benvenuto.cervello': 'Das lokale Gehirn',
  'benvenuto.cervello-cosa': 'Ollama und Qwen3.5: liest die Notizen, macht Karten und Definitionen, erklärt und fragt ab',
  'benvenuto.voce': 'Die Sprache',
  'benvenuto.voce-cosa': '{voce}: Sprachbefehle, „Nochmal“ und Transkription der Vorlesungen',
  'benvenuto.peso-gb': '{n} GB',
  'benvenuto.peso-mb': '{n} MB',
  'benvenuto.installa-nota': 'Obsidian ist für den privaten Gebrauch kostenlos und kommt von der offiziellen Website. Das lokale Gehirn wird nach dem Arbeitsspeicher des Computers ausgewählt.',
  'benvenuto.installa-tutto': 'Alles installieren',
  'benvenuto.gia-installato': 'Schon installiert',
  'benvenuto.modello-pronto': '{modello} ist schon bereit',
  'benvenuto.gia-pronta': 'Schon bereit',
  'benvenuto.voce-pronta': '{voce} ist bereit',
  'benvenuto.scarico-voce-pct': 'Lade die Sprache · {p} %',
  'benvenuto.tutto-pronto': 'Obsidian, das lokale Gehirn und die Sprache sind bereit.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'das lokale Gehirn',
  'benvenuto.scarico-voce': 'die Sprache',
  'benvenuto.scarico-pct': '{cosa} {p} %',
  'benvenuto.scarico-continua-voce': 'Ich lade noch: {cosa}. Das läuft von selbst weiter, auch bei geschlossenem Fenster; die Sprache macht in der Leiste weiter, sobald du Lode öffnest.',
  'benvenuto.scarico-continua': 'Ich lade noch: {cosa}. Das läuft von selbst weiter, auch bei geschlossenem Fenster.',
  'benvenuto.scarico-solo-voce': 'Ich lade noch: {cosa}. Die Sprache macht in der Leiste weiter, sobald du Lode öffnest.',
  // setup veloce
  'benvenuto.veloce-titolo': '{nome}, willst du die schnelle Einrichtung?',
  'benvenuto.veloce-sotto': 'Erzähl mir von Uni, Prüfungen und Stundenplan: Ab morgen weiß Lode, wann du in der Vorlesung bist, wie viel dir bis zum Abschluss fehlt und was du vor jeder Prüfung wiederholen solltest.',
  'benvenuto.veloce-lista': ['Uni und Studiengang', 'Deine Notenübersicht, aus dem Uni-Portal eingefügt oder von Hand geschrieben', 'Die Prüfungen, die noch kommen, mit Datum', 'Der Stundenplan, auch aus dem Uni-Kalender (.ics)', 'Wie und wann du lernst'],
  'benvenuto.veloce-nota': 'Alles optional, alles später änderbar. Nichts geht ins Internet.',
  'benvenuto.facciamolo': 'Los',
  // corso
  'benvenuto.corso-titolo': 'Wo studierst du?',
  'benvenuto.ateneo': 'Uni',
  'benvenuto.ateneo-segnaposto': 'Fang an zu tippen…',
  'benvenuto.corso': 'Studiengang',
  'benvenuto.corso-segnaposto': 'Informatik',
  'benvenuto.tipo': 'Art',
  'benvenuto.tipo-180': 'Bachelor · 180 ECTS',
  'benvenuto.tipo-120': 'Master · 120 ECTS',
  'benvenuto.tipo-300': 'Staatsexamen · 300 ECTS',
  'benvenuto.tipo-360': 'Staatsexamen · 360 ECTS',
  'benvenuto.anno': 'Jahr',
  'benvenuto.anni': ['1.', '2.', '3.', '4.', '5.', '6.', 'Über der Regelstudienzeit'],
  'benvenuto.lode-vale': 'Cum laude zählt als',
  'benvenuto.lode-nota': 'Hängt von der Prüfungsordnung ab: im Zweifel 30',
  // libretto
  'benvenuto.libretto-titolo': 'Die Prüfungen, die du schon hast',
  'benvenuto.libretto-sotto': 'Öffne deine Notenübersicht im Uni-Portal (Esse3, Infostud, HISinOne…), markier alles, kopier es und füg es hier ein. Den Rest mache ich. Oder schreib jede in eine Zeile: „Analysis 1, 9 ECTS, 28“.',
  'benvenuto.libretto-segnaposto': 'Notenübersicht hier einfügen…',
  'benvenuto.leggi-libretto': 'Notenübersicht lesen',
  'benvenuto.leggo-libretto': 'Lese die Notenübersicht…',
  'benvenuto.leggo': 'Lese…',
  'benvenuto.esami-trovati': '{n} Prüfungen gefunden: Prüf sie und bestätige.',
  'benvenuto.esami-non-trovati': 'Ich habe keine Prüfungen gefunden: Schreib jede in eine eigene Zeile.',
  'benvenuto.col-esame': 'Prüfung',
  'benvenuto.col-cfu': 'ECTS',
  'benvenuto.col-voto': 'Note',
  'benvenuto.col-data': 'Datum',
  'benvenuto.importa': 'Importieren',
  'benvenuto.idoneo': 'bestanden',
  'benvenuto.voto-lode': '{voto}L',
  // esami da dare
  'benvenuto.esame': 'Prüfung',
  'benvenuto.cfu': 'ECTS',
  'benvenuto.data-appello': 'Prüfungsdatum',
  'benvenuto.togli': 'Entfernen',
  'benvenuto.esami-titolo': 'Die Prüfungen, die noch kommen',
  'benvenuto.esami-sotto': 'Mit dem Prüfungsdatum, wenn du es weißt. Daraus rechnet Lode aus, wie viele Stunden du jeden Tag brauchst, und schlägt dir Wiederholungen und Spiele vor, wenn du kurz Zeit hast.',
  'benvenuto.altro-esame': '+ Noch eine Prüfung',
  // orario
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · Raum {aula}',
  'benvenuto.nessuna-lezione': 'Noch keine Vorlesung.',
  'benvenuto.orario-titolo': 'Dein Stundenplan',
  'benvenuto.orario-sotto': 'So weiß Lode, wann du im Hörsaal sitzt: Die Leiste macht sich für die Vorlesung bereit, „Nochmal“ und die Transkription sind einen Tastendruck entfernt, und zu Hause trainiert sie dich mit dem, was du gerade gehört hast.',
  'benvenuto.scrivila': 'Schreib es, wie du es sagen würdest',
  'benvenuto.frase-segnaposto': 'Analysis 2 Montag und Mittwoch 9-11 Raum 7',
  'benvenuto.aggiungi': 'Hinzufügen',
  'benvenuto.importa-ics': 'Kalender importieren (.ics)',
  'benvenuto.incolla-orario': 'Oder füg den Stundenplan von der Uni-Website ein',
  'benvenuto.orario-segnaposto': 'Tabelle des Stundenplans hier einfügen…',
  'benvenuto.leggi-orario': 'Stundenplan lesen',
  'benvenuto.frase-aiuto': 'Schreib Kurs, Tage und Uhrzeit: „Physik Montag 14-16 Raum B2“.',
  'benvenuto.lezioni-calendario': '{n} Vorlesungen aus dem Kalender.',
  'benvenuto.calendario-vuoto': 'Im Kalender habe ich keine wöchentlichen Vorlesungen gefunden.',
  'benvenuto.leggo-orario': 'Lese den Stundenplan…',
  'benvenuto.lezioni-trovate': '{n} Vorlesungen gefunden.',
  'benvenuto.lezioni-non-trovate': 'Ich habe keine Vorlesungen gefunden: Schreib sie einzeln.',
  // abitudini
  'benvenuto.abitudini-titolo': 'Wie lernst du?',
  'benvenuto.abitudini-sotto': 'Lode schlägt dir zu zufälligen Zeiten am Tag Wiederholungen, Spiele und schnelle Fragen vor, wenn du am Computer bist. Sag mir, wie oft und wann ich dich in Ruhe lassen soll.',
  'benvenuto.quando-meglio': 'Wann du am besten lernst',
  'benvenuto.mattina': 'Morgens',
  'benvenuto.pomeriggio': 'Nachmittags',
  'benvenuto.sera': 'Abends',
  'benvenuto.notte': 'Nachts',
  'benvenuto.proposte': 'Vorschläge von Lode',
  'benvenuto.scelta-mai': 'Nie',
  'benvenuto.scelta-poco': 'Wenige',
  'benvenuto.scelta-normale': 'Normal',
  'benvenuto.scelta-spesso': 'Viele',
  'benvenuto.proposte-nota': 'Je näher die Prüfung, desto öfter. Nie während Vorlesungen, Fokus oder nachts.',
  'benvenuto.silenzio-dalle': 'Ruhe von',
  'benvenuto.silenzio-alle': 'bis',
  'benvenuto.focus': 'Fokus',
  'benvenuto.minuti': '{n} Min.',
  'benvenuto.ripeti-in-aula': 'Im Hörsaal schaltet sich „Nochmal“ von selbst ein (die letzten anderthalb Minuten, nur im Speicher). Frag die Lehrperson, ob Aufnehmen erlaubt ist.',
  // fine
  'benvenuto.fine-titolo': 'Fertig, {nome}.',
  'benvenuto.fine-sotto': 'Lode wohnt jetzt oben am Bildschirm. Fahr mit der Maus drüber, um es zu öffnen, halt <b>{tasti}</b> gedrückt, um mit ihm zu sprechen, zieh ein PDF oder ein Foto der Tafel drauf.',
  'benvenuto.fine-esami': '{fatti} Prüfungen in der Notenübersicht, {dare} noch offen',
  'benvenuto.fine-esami-prossimo': '{fatti} Prüfungen in der Notenübersicht, {dare} noch offen · die nächste ist {nome}',
  'benvenuto.fine-lezioni': '{n} Vorlesungen pro Woche im Stundenplan',
  'benvenuto.fine-proposte': 'Vorschläge: {quante}',
  'benvenuto.quante-mai': 'nie',
  'benvenuto.quante-poco': 'wenige',
  'benvenuto.quante-normale': 'normal',
  'benvenuto.quante-spesso': 'viele',
  'benvenuto.apri-lode': 'Lode öffnen',
};
