// Texte der Desktop-App (Deutsch): Systemfenster, Menü des Symbols, Benachrichtigungen und Meldungen des
// Hauptprozesses (desktop/*.mjs), die bei den Studierenden ankommen.
export default {
  // main.mjs: finestre di sistema
  'desktop.non-ci-sono-riuscito': 'Das hat nicht geklappt.',
  'desktop.benvenuto-in-lode': 'Willkommen bei Lode',
  'desktop.dove-tenere-il-vault': 'Wo der Vault liegen soll',
  'desktop.usa-questa-cartella': 'Diesen Ordner nehmen',
  'desktop.non-e-andata': 'Hat nicht geklappt.',
  'desktop.vault-con-sincronizzazione': 'Mit Synchronisierung wechselst du den Vault über „Zwischen deinen Computern synchronisieren“',
  'desktop.vault-con-sincronizzazione-dettaglio': '„Auf diesem Computer aufhören“ holt den Vault aus dem Cloud-Ordner.',
  'desktop.scegli-il-vault': 'Obsidian-Vault wählen',
  'desktop.usa-questo-vault': 'Diesen Vault nehmen',
  'desktop.cartella-non-usabile': 'Lode kann den Ordner {cartella} nicht benutzen',
  'desktop.cartella-protetta-windows': 'Wahrscheinlich schützt Windows ihn (Windows-Sicherheit › Ransomware-Schutz › Überwachter Ordnerzugriff) oder der Virenscanner blockiert Lode. Lass Lode zu oder wähl einen anderen Ordner.',
  'desktop.scegli-altra-cartella': 'Anderen Ordner wählen',
  'desktop.riprova': 'Nochmal versuchen',
  'desktop.non-ora': 'Nicht jetzt',
  'desktop.obsidian-pronto': 'Obsidian ist für deinen Vault bereit',
  'desktop.modello-pronto': '{modello} ist bereit',
  'desktop.ponte-non-partito': 'Die Verbindung zu den Agenten ist nicht gestartet: Starte Lode neu.',
  'desktop.agente-togliere': 'Lode aus der Konfiguration von {agente} entfernen?',
  'desktop.agente-collegare': '{agente} mit Lode verbinden?',
  'desktop.agente-toglie-righe': 'Lode entfernt nur seine eigenen Zeilen in:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode fügt nur seine eigenen Zeilen hinzu, der Rest bleibt, wie er ist, in:\n{file}',
  'desktop.agente-manda-eventi': '{agente} schickt Lode auf diesem Computer die Ereignisse der Sitzungen (berührte Dateien, Befehle, Ende des Zugs). Lode antwortet nicht und entscheidet nichts. ',
  'desktop.agente-file-com-era': 'Die Datei, wie sie vorher war, bleibt in {file}.',
  'desktop.togli': 'Entfernen',
  'desktop.collega': 'Verbinden',
  'desktop.annulla': 'Abbrechen',
  // main.mjs: il menu dell'icona
  'desktop.menu-avvisami-versioni': 'Bei neuen Versionen Bescheid sagen',
  'desktop.menu-aggiornamenti-automatici': 'Automatische Updates',
  'desktop.menu-riavvia-con': 'Mit Lode {versione} neu starten',
  'desktop.menu-scarica': 'Lode {versione} herunterladen…',
  'desktop.menu-apri': 'Lode öffnen ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Leertaste',
  'desktop.tasti-apri': 'Strg+Umschalt+Leertaste',
  'desktop.menu-quadro': 'Die Übersicht: Noten, Prüfungen, Wiederholung',
  'desktop.menu-rifai-configurazione': 'Einrichtung neu machen…',
  'desktop.menu-apri-vault-obsidian': 'Vault in Obsidian öffnen',
  'desktop.menu-mostra-vault': 'Vault im Ordner zeigen',
  'desktop.menu-altro-vault': 'Anderen Vault nehmen…',
  'desktop.menu-avvio-accensione': 'Lode beim Hochfahren starten',
  'desktop.menu-icona-mac': 'Lode-Symbol in Programme',
  'desktop.menu-icona-win': 'Lode-Symbol im Startmenü und auf dem Desktop',
  'desktop.menu-icona-linux': 'Lode-Symbol im Anwendungsmenü',
  'desktop.menu-esci': 'Lode beenden',
  // sincronizza.mjs: la sincronizzazione fra i computer
  'desktop.sync-file-occupato': 'Eine Datei wird von einem anderen Programm benutzt: Schließ es und versuch es nochmal. Der bisherige Vault ist unversehrt.',
  'desktop.sync-file-occupato-nome': 'Eine Datei wird von einem anderen Programm benutzt ({file}): Schließ es und versuch es nochmal. Der bisherige Vault ist unversehrt.',
  'desktop.sync-disco-pieno': 'Die Festplatte des Cloud-Ordners ist voll. Der bisherige Vault ist unversehrt.',
  'desktop.sync-permesso': 'Lode darf eine Datei nicht lesen oder schreiben. Der bisherige Vault ist unversehrt.',
  'desktop.sync-permesso-nome': 'Lode darf eine Datei nicht lesen oder schreiben ({file}). Der bisherige Vault ist unversehrt.',
  'desktop.sync-copia-diversa': 'Die Kopie von {file} ist nicht identisch geworden: Versuch es nochmal. Der bisherige Vault ist unversehrt.',
  'desktop.sync-copia-non-riuscita': 'Das Kopieren des Vaults hat nicht geklappt: Versuch es nochmal. Der bisherige Vault ist unversehrt.',
  'desktop.sync-sto-accendendo': 'Ich schalte die Synchronisierung schon ein: Warte, bis das fertig ist.',
  'desktop.sync-cartella-titolo': 'Der Ordner, der synchronisiert wird',
  'desktop.sync-sincronizza-qui': 'Hier synchronisieren',
  'desktop.sync-spostamento-con-password': 'Das Verschieben hat mit Passwort angefangen: Gib es nochmal ein.',
  'desktop.sync-dati-occupati': 'Die Datendatei von Lode wird von einem anderen Programm benutzt (ein Virenscanner?): Versuch es gleich nochmal.',
  'desktop.sync-diario-illeggibile': 'Das Protokoll von Lode auf diesem Computer lässt sich nicht lesen.',
  'desktop.sync-controllo-altro-computer': 'Ich prüfe, ob schon ein anderer Computer diesen Vault synchronisiert…',
  'desktop.sync-aspetto-dati': 'Ich warte, bis die Daten von Lode aus der Cloud da sind (die Datendatei lässt sich noch nicht lesen): Versuch es gleich nochmal.',
  'desktop.sync-altra-password': 'Für diesen Vault ist die Synchronisierung schon mit einem anderen Passwort an: Gib das ein.',
  'desktop.sync-gia-con-password': 'Für diesen Vault ist die Synchronisierung schon mit Passwort an: Gib es ein.',
  'desktop.sync-non-accendo': 'Ich kann die Synchronisierung hier nicht einschalten.',
  'desktop.sync-cartella-dentro-vault': 'Dieser Ordner liegt im Vault: Wähl einen außerhalb, zum Beispiel den Ordner von iCloud Drive, OneDrive oder Dropbox.',
  'desktop.sync-dati-non-ancora': 'Die Daten von Lode lassen sich noch nicht lesen (Ordner nicht erreichbar?): Versuch es gleich nochmal.',
  'desktop.sync-copio-vault': 'Ich kopiere den Vault…',
  'desktop.sync-copio-vault-file': 'Ich kopiere den Vault… {n} Dateien',
  'desktop.sync-cifro-pubblico': 'Ich verschlüssele und veröffentliche die Daten von Lode…',
  'desktop.sync-pubblico': 'Ich veröffentliche die Daten von Lode…',
  'desktop.sync-non-creo-dati': 'Ich kann die Daten von Lode im Cloud-Ordner nicht anlegen. Der bisherige Vault ist unversehrt.',
  'desktop.sync-vault-nel-cloud': 'Der Lode-Vault im Cloud-Ordner',
  'desktop.sync-non-e-vault-sincronizzato': 'In diesem Ordner ist kein synchronisierter Lode-Vault: Wähl den Ordner „Lode“ im Cloud-Ordner (auf dem anderen Computer: „Zwischen deinen Computern synchronisieren“).',
  'desktop.sync-diario-altro-vault': 'Auf diesem Computer benutzt Lode schon das Protokoll eines anderen Vaults: Erst „Auf diesem Computer aufhören“.',
  'desktop.sync-password-sbagliata-di-nuovo': 'Falsches Passwort: Gib es nochmal ein.',
  'desktop.sync-password-vecchia': 'Das ist das alte Passwort: Auf einem anderen Computer wurde es geändert, gib das neue ein.',
  'desktop.sync-lode-piu-nuova': 'Dieser Vault wurde von einer neueren Lode-Version geschützt: Aktualisiere Lode.',
  'desktop.sync-gruppo-manomesso': 'Das Passwort stimmt, aber die Gruppendatei im Cloud-Ordner wurde von außen geändert: Ich benutze sie nicht. Prüf den Cloud-Ordner.',
  'desktop.sync-gruppo-in-chiaro': 'Die Gruppe im Cloud-Ordner ist nicht verschlüsselt: Auf dem anderen Computer läuft die Synchronisierung ohne Passwort, oder die Gruppendatei wurde manipuliert. Wenn du auf dem anderen Computer kein Passwort gesetzt hast, versuch es ohne.',
  'desktop.sync-password-sbagliata': 'Falsches Passwort.',
  'desktop.sync-adesso-non-si-puo': 'Das geht gerade nicht.',
  'desktop.sync-cartella-in-cloud': 'Dieser Ordner liegt in einem Cloud-Ordner: Zum Synchronisieren nimm „Zwischen deinen Computern synchronisieren“.',
  'desktop.sync-fuori-dal-vault': 'Wähl einen Ordner außerhalb des aktuellen Vaults.',
  'desktop.sync-non-sposto-dati': 'Ich kann die Daten von Lode nicht in diesen Ordner verschieben. Der bisherige Vault ist unversehrt.',
  'desktop.sync-riprova-tra-poco': 'Das geht gerade nicht: Versuch es gleich nochmal.',
  'desktop.sync-password-corta': 'Das Passwort muss mindestens 8 Zeichen haben.',
  'desktop.sync-diario-illeggibile-riprova': 'Das Protokoll von Lode auf diesem Computer lässt sich nicht lesen: Erst „Nochmal versuchen“.',
  'desktop.sync-non-accesa': 'Auf diesem Computer ist die Synchronisierung nicht an.',
  'desktop.sync-vault-spostato-scegli': 'Der Vault ist nicht mehr da, wo Lode ihn gesucht hat: Wenn du ihn verschoben hast, nimm „Vault suchen“ und wähl den verschobenen Ordner.',
  'desktop.sync-dove-fuori-cloud': 'Wo der Vault liegen soll, außerhalb des Cloud-Ordners',
  'desktop.sync-tieni-qui': 'Vault hier ablegen',
  'desktop.sync-fuori-dal-cloud': 'Wähl einen Ordner außerhalb des Cloud-Ordners.',
  'desktop.sync-vault-spostato': 'Der Vault ist nicht mehr da, wo Lode ihn gesucht hat: Wenn du ihn verschoben hast, nimm „Vault suchen“.',
  'desktop.sync-cambio-in-arrivo': 'Die letzten Änderungen dieses Computers sind noch nicht im Cloud-Ordner (gerade kommt eine Änderung von den anderen Computern): Versuch es gleich nochmal.',
  'desktop.sync-smetti-serve-password': 'Die Änderungen aus der Pause blieben nur auf diesem Computer: Gib das Passwort ein, bevor du aufhörst (oder „Passwort vergessen“).',
  'desktop.sync-note-non-scaricate': 'Einige Notizen sind auf diesem Computer nicht heruntergeladen ({note}): Öffne sie oder lade sie aus dem Cloud-Dienst herunter, dann versuch es nochmal.',
  'desktop.sync-note-non-scaricate-altre': 'Einige Notizen sind auf diesem Computer nicht heruntergeladen ({note} und {n} weitere): Öffne sie oder lade sie aus dem Cloud-Dienst herunter, dann versuch es nochmal.',
  'desktop.sync-copio-fuori-cloud': 'Ich kopiere den Vault aus dem Cloud-Ordner heraus…',
  // progetto.mjs: «segui il progetto», il riassunto «Fatto. In parole semplici» e la conferma dei comandi
  'desktop.progetto-elenco': '{primi} und {ultimo}',
  'desktop.progetto-elenco-altre': '{primi} und {n} weitere',
  'desktop.progetto-elenco-altri': '{primi} und {n} weitere',
  'desktop.progetto-righe-piu-meno': { one: '{n} Zeile mehr und {meno} weniger', other: '{n} Zeilen mehr und {meno} weniger' },
  'desktop.progetto-righe-piu': { one: '{n} Zeile mehr', other: '{n} Zeilen mehr' },
  'desktop.progetto-righe-meno': { one: '{n} Zeile weniger', other: '{n} Zeilen weniger' },
  'desktop.progetto-solo-spazi': 'nur Leerzeichen oder Zeilenumbrüche',
  'desktop.progetto-file-nuovo': { one: 'neue Datei ({n} Zeile)', other: 'neue Datei ({n} Zeilen)' },
  'desktop.progetto-file-tolto': 'entfernt',
  'desktop.progetto-funzioni-nuove': { one: 'neue Funktion {elenco}', other: 'neue Funktionen {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'geändert: {elenco}', other: 'geändert: {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'entfernt: {elenco}', other: 'entfernt: {elenco}' },
  'desktop.progetto-file': '{file}: {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'Neu: {elenco}.', other: 'Neu: {elenco}.' },
  'desktop.progetto-esito-compila': 'kompiliert',
  'desktop.progetto-esito-non-compila': 'kompiliert nicht',
  'desktop.progetto-esito-sintassi-a-posto': 'Syntax in Ordnung',
  'desktop.progetto-esito-errore-di-sintassi': 'Syntaxfehler',
  'desktop.progetto-esito-make-riuscito': 'make erfolgreich',
  'desktop.progetto-esito-make-non-riuscito': 'make fehlgeschlagen',
  'desktop.progetto-prove-su': { one: '{n} von {tot} Tests', other: '{n} von {tot} Tests' },
  'desktop.progetto-prova-non-partita': 'der Test ist nicht gestartet',
  'desktop.progetto-inizio-alle': { one: 'Um {ora} hat sich {n} Datei geändert (+{piu} −{meno}).', other: 'Um {ora} haben sich {n} Dateien geändert (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'Von {da} bis {a} hat sich {n} Datei geändert (+{piu} −{meno}).', other: 'Von {da} bis {a} haben sich {n} Dateien geändert (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**Getestet?** Ja: Das ist der Code, der um {ora} getestet wurde ({esito}).',
  'desktop.progetto-provato-no-codice': '**Getestet?** Nein, aber hier haben sich nur Dateien geändert, die kein Code sind.',
  'desktop.progetto-provato-no': '**Getestet?** Nein: Nach der letzten Änderung ({ora}) hat niemand mit Lode kompiliert.',
  'desktop.progetto-nota-chi': 'Ich weiß nicht, wer diese Zeilen geschrieben hat.',
  'desktop.progetto-altri-file': 'Und {n} weitere Dateien.',
  'desktop.progetto-nessuna-cartella': 'Ich habe keinen Ordner bekommen.',
  'desktop.progetto-non-trovo-cartella': 'Ich finde diesen Ordner nicht.',
  'desktop.progetto-cartella-non-file': 'Wähl einen Ordner, keine Datei.',
  'desktop.progetto-radice-disco': 'Das ist das Stammverzeichnis der Festplatte: Wähl nur den Ordner des Projekts (zum Beispiel lab3).',
  'desktop.progetto-tutta-la-home': 'Dieser Ordner enthält dein ganzes Home-Verzeichnis: Wähl nur den Ordner des Projekts.',
  'desktop.progetto-e-il-vault': 'Das ist der Vault von Lode (oder er liegt darin): Wähl den Ordner des Projekts.',
  'desktop.progetto-dati-di-lode': 'In diesem Ordner speichert Lode seine Daten: Wähl den Ordner des Projekts.',
  'desktop.progetto-troppi-progetti': 'Ich verfolge schon {n} Projekte: Hör bei einem auf („… nicht mehr verfolgen“) und versuch es dann nochmal.',
  'desktop.progetto-cartella-illeggibile': 'Ich kann diesen Ordner nicht lesen.',
  'desktop.progetto-troppi-file': 'Hier sind mehr als {n} Dateien: Wähl nur den Ordner des Projekts (zum Beispiel lab3).',
  'desktop.progetto-non-seguo': 'Dieses Projekt verfolge ich nicht.',
  'desktop.progetto-versione-scaduta': 'Diese Version gibt es nicht mehr: Lode hebt Versionen 30 Tage auf.',
  'desktop.progetto-file-non-seguito': 'Diese Datei gehört nicht zu denen, die ich verfolge.',
  'desktop.progetto-file-illeggibile': 'Ich kann die Datei nicht lesen.',
  'desktop.progetto-poi-per-ogni-prova': 'Dann, für jeden Test .in → .out:\n{comandi}',
  'desktop.progetto-senza-prove': 'Das Programm starte ich nicht: Es gibt keine .in/.out-Tests.',
  'desktop.progetto-resto-non-mostro': '(den Rest zeige ich nicht)',
  'desktop.progetto-smesso-durante-prova': 'Ich habe während des Tests aufgehört, das Projekt zu verfolgen.',
  'desktop.progetto-scegli-cartella': 'Ordner des Projekts wählen',
  'desktop.progetto-segui-cartella': 'Diesen Ordner verfolgen',
  'desktop.progetto-scegli-di-nuovo': 'Wähl den Ordner nochmal („Projekt verfolgen“).',
  'desktop.progetto-conferma-aperta': 'Es ist schon ein Bestätigungsfenster offen: Antworte zuerst dort.',
  'desktop.progetto-eseguira': 'Lode führt diesen Befehl im Ordner {cartella} aus.',
  'desktop.progetto-come-terminale': 'Das ist, als würdest du ihn im Terminal starten: Das Programm läuft auf deinem Rechner.',
  'desktop.progetto-esegui-sempre': 'Für dieses Projekt immer ausführen',
  // esegui.mjs: provare il codice del progetto
  'desktop.esegui-riapri': 'Wenn du ihn gerade erst zum PATH hinzugefügt hast, beende Lode (über das Menü) und öffne es wieder.',
  'desktop.esegui-manca-c-win': 'Ich finde keinen C-Compiler. Installier MSYS2 (msys2.org), öffne „MSYS2 UCRT64“ und schreib `pacman -S mingw-w64-ucrt-x86_64-gcc`: Lode findet ihn dann von selbst in C:\\msys64\\ucrt64\\bin. Alternativ WinLibs (winlibs.com) oder WSL. Lode lädt nichts für dich herunter.',
  'desktop.esegui-manca-c-mac': 'Ich finde keinen C-Compiler. Öffne das Terminal und schreib `xcode-select --install`: Das installiert clang von Apple. Dann versuch es nochmal.',
  'desktop.esegui-manca-c-linux': 'Ich finde keinen C-Compiler. Installier gcc (zum Beispiel `sudo apt install build-essential`), dann versuch es nochmal.',
  'desktop.esegui-manca-python-win': 'Ich finde kein Python 3. Installier es von python.org (Haken bei „Add python.exe to PATH“) oder aus dem Microsoft Store, dann versuch es nochmal.',
  'desktop.esegui-manca-python': 'Ich finde kein Python 3. Installier es (python.org oder über den Paketmanager), dann versuch es nochmal.',
  'desktop.esegui-manca-java': 'Ich finde kein JDK (javac und java). Installier eins, zum Beispiel Temurin von adoptium.net, dann versuch es nochmal.',
  'desktop.esegui-manca-make-win': 'Es gibt ein Makefile, aber ich finde make nicht. Mit MSYS2, in „MSYS2 UCRT64“: `pacman -S mingw-w64-ucrt-x86_64-make`. Oder nimm das Makefile weg, dann kompiliert Lode die .c-Dateien selbst.',
  'desktop.esegui-manca-make': 'Es gibt ein Makefile, aber ich finde make nicht. Installier es (auf dem Mac: `xcode-select --install`), dann versuch es nochmal.',
  'desktop.esegui-manca-programma': 'Es fehlt ein Programm, um den Code zu testen.',
  'desktop.esegui-senza-prove': 'Ich finde keine .in/.out-Tests: Ich kompiliere nur, das Programm starte ich nicht.',
  'desktop.esegui-make-prove': 'Mit dem Makefile starte ich die {n} .in/.out-Tests nicht: Ich weiß nicht, welches Programm es erzeugt.',
  'desktop.esegui-poi-prove': { one: 'dann der Test (.in-Datei → erwartete .out)', other: 'dann die {n} Tests (.in-Datei → erwartete .out)' },
  'desktop.esegui-poi-prove-in': { one: 'dann der Test in {cartella}/ (.in-Datei → erwartete .out)', other: 'dann die {n} Tests in {cartella}/ (.in-Datei → erwartete .out)' },
  'desktop.esegui-senza-programma': '{prove}; {n} ohne klares Programm',
  'desktop.esegui-make-leggi': 'make führt die Befehle aus, die im Makefile stehen: Lies es, bevor du bestätigst.',
  'desktop.esegui-make-assente': 'Es gibt ein Makefile, aber ich finde make nicht: Ich kompiliere die .c-Dateien selbst.',
  'desktop.esegui-niente-codice': 'Ich finde in diesem Ordner keinen C-, Python- oder Java-Code zum Testen.',
  'desktop.esegui-virgolette': 'Die Anführungszeichen sind nicht geschlossen.',
  'desktop.esegui-invisibili': 'Im Befehl sind unsichtbare Zeichen (Zeilenumbruch, Steuer- oder Textrichtungszeichen): Tipp ihn von Hand neu.',
  'desktop.esegui-comando-vuoto': 'Der Befehl ist leer.',
  'desktop.esegui-comando-illeggibile': 'Der Befehl lässt sich nicht lesen.',
  'desktop.esegui-non-trovo-programma': 'Ich finde das Programm „{programma}“ nicht.',
  'desktop.esegui-bat': '.bat- und .cmd-Dateien starte ich nicht: Schreib den Befehl, der darin steht.',
  'desktop.esegui-compilazione-lenta': 'Das Kompilieren war nicht innerhalb von {n} Sekunden fertig.',
  'desktop.esegui-prova-senza-programma': 'ich weiß nicht, zu welchem Programm er gehört',
  'desktop.esegui-programma-non-creato': 'Der Befehl hat das Programm zum Testen nicht erzeugt.',
  'desktop.esegui-prova-illeggibile': 'ich kann die Dateien des Tests nicht lesen',
  // moodle.mjs: Moodle in sola lettura
  'desktop.moodle-risponde': 'Moodle antwortet {stato}',
  'desktop.moodle-errore': 'Moodle-Fehler',
  'desktop.moodle-sito-risponde': 'die Seite antwortet {stato}',
  'desktop.moodle-non-e-moodle': 'das ist kein Moodle, oder der Dienst für Apps ist aus',
  'desktop.moodle-non-collegato': 'Moodle ist nicht verbunden',
  'desktop.moodle-accesso-non-riuscito': 'Anmeldung fehlgeschlagen',
  'desktop.moodle-accedi-a': 'Bei {sito} anmelden',
  'desktop.moodle-risposta-non-valida': 'ungültige Antwort von Moodle',
  'desktop.moodle-tempo-scaduto': 'Zeit abgelaufen',
  'desktop.moodle-file-non-trovato': 'Datei nicht gefunden',
  'desktop.moodle-file-troppo-grande': 'Datei zu groß',
  'desktop.moodle-file-non-su-moodle': 'die Datei liegt nicht auf Moodle',
  // installa.mjs: Obsidian e il cervello locale (Ollama)
  'desktop.installa-download-non-riuscito': 'Download fehlgeschlagen ({stato})',
  'desktop.installa-non-firmato': 'Der Installer von {nome} hat nicht die offizielle Signatur von {nome}, deshalb habe ich ihn nicht installiert. Versuch es später nochmal oder lade ihn selbst von der offiziellen Website herunter.',
  'desktop.installa-versione-obsidian': 'unbekannte Obsidian-Version',
  'desktop.installa-scarico-obsidian': 'Lade Obsidian {versione} herunter',
  'desktop.installa-scarico-obsidian-mb': 'Lade Obsidian {versione} herunter · {mb} MB',
  'desktop.installa-installo-obsidian': 'Installiere Obsidian',
  'desktop.installa-obsidian-installato': 'Obsidian {versione} installiert',
  'desktop.installa-perche-4b': 'schnell auch ohne Grafikkarte: Definitionen, Karten, Spiele und Abfrage',
  'desktop.installa-perche-35b': 'das beste, und so schnell wie ein kleines Modell, für Computer mit viel Arbeitsspeicher',
  'desktop.installa-perche-9b': 'erklärt gut und kann gut abfragen',
  'desktop.installa-perche-memoria': 'für {gb} GB Arbeitsspeicher: Definitionen, Karten, Spiele und Abfrage',
  'desktop.installa-ollama-non-avviato': 'Ollama ist nicht gestartet',
  'desktop.installa-ollama-linux': 'Unter Linux installier Ollama von ollama.com mit deren Skript und komm dann hierher zurück.',
  'desktop.installa-scarico-ollama-mb': 'Lade Ollama herunter · {mb} MB',
  'desktop.installa-installo-ollama': 'Installiere Ollama',
  'desktop.installa-avvio-ollama': 'Starte Ollama',
  'desktop.installa-ollama-non-risponde': 'Ollama antwortet nicht',
  'desktop.installa-scarico-modello': 'Lade {nome} herunter · {fatti} von {totale} GB',
  'desktop.installa-modello-pronto': '{nome} bereit',
  'desktop.installa-modello-assente': 'Das Modell {modello} ist nicht installiert',
  'desktop.installa-modello-non-risponde': 'Das lokale Modell antwortet nicht',
  // aggiorna.mjs: le versioni nuove di Lode
  'desktop.aggiorna-github-risponde': 'GitHub antwortet {stato}',
  'desktop.aggiorna-non-installato': 'Das Update wurde nicht installiert. Versuch es nochmal oder schließ Lode: Es wird beim Beenden installiert.',
  'desktop.aggiorna-non-installato-perche': 'Das Update wurde nicht installiert: {motivo}. Versuch es nochmal oder schließ Lode: Es wird beim Beenden installiert.',
  'desktop.aggiorna-niente-pronto': 'Es gibt kein fertiges Update zum Installieren.',
  'desktop.aggiorna-dove-scaricare': 'Ich weiß noch nicht, wo ich es herunterladen kann: Versuch es gleich nochmal.',
  // voce-onnx.mjs e voce-onnx-motore.mjs: la voce Parakeet ONNX
  'desktop.voce-modello-illeggibile': 'Ich kann das Sprachmodell nicht lesen: Versuch es gleich nochmal.',
  'desktop.voce-spazio': 'Für die Spracherkennung Parakeet brauchst du etwa {serve} MB freien Speicher, frei sind {liberi}.',
  'desktop.voce-rete': 'Ich kann die Spracherkennung nicht herunterladen: Prüf die Verbindung und versuch es nochmal. ({dettaglio})',
  'desktop.voce-rete-stato': 'Ich kann die Spracherkennung nicht herunterladen ({stato}): Versuch es später nochmal.',
  'desktop.voce-file-troppo-grande': 'Die Datei der Spracherkennung ist größer als erwartet.',
  'desktop.voce-interrotto': 'Der Download der Spracherkennung wurde unterbrochen: Beim nächsten Mal geht es hier weiter. ({dettaglio})',
  'desktop.voce-impronta': 'Die Datei der Spracherkennung „{file}“ ist nicht die richtige (anderer SHA256-Fingerabdruck): Ich habe sie gelöscht.',
  'desktop.voce-addon': 'Das Programm der Spracherkennung (sherpa-onnx) lädt auf diesem Computer nicht.',
  'desktop.voce-modello-rovinato': 'Das Parakeet-Modell lädt nicht (vielleicht ist eine Datei beschädigt).',
  'desktop.voce-pezzo-non-trascritto': 'Parakeet konnte dieses Stück nicht transkribieren.',
  'desktop.voce-motore-chiuso': 'Die Spracherkennung hat sich plötzlich beendet.',
  'desktop.voce-motore-chiuso-codice': 'Die Spracherkennung hat sich plötzlich beendet ({codice}).',
  'desktop.voce-motore-non-risponde': 'Die Spracherkennung antwortet nicht.',
  // agenti-collegamenti.mjs: il collegamento con gli agenti di programmazione
  'desktop.agenti-claude-eventi': ['Prompts', 'Änderungen und Befehle', 'Ende des Zugs', 'Benachrichtigungen'],
  'desktop.agenti-claude-nota': 'Die Hooks gelten ab der nächsten Sitzung (oder sieh sie dir mit /hooks an).',
  'desktop.agenti-codex-eventi': ['Prompts', 'Änderungen (apply_patch) und Befehle', 'Ende des Zugs'],
  'desktop.agenti-codex-nota': 'In der nächsten Sitzung bittet Codex dich, die neuen Hooks zu bestätigen: Mach das mit /hooks.',
  'desktop.agenti-gemini-eventi': ['Prompts', 'Werkzeuge (Dateien und Befehle)', 'Ende der Antwort', 'Benachrichtigungen'],
  'desktop.agenti-gemini-nota': 'Gilt ab der nächsten Sitzung von Gemini CLI.',
  'desktop.agenti-cursor-eventi': ['Prompts', 'geänderte Dateien', 'Befehle', 'Antwort des Agenten'],
  'desktop.agenti-cursor-nota': 'Starte Cursor neu, damit es die Hooks liest. Cursor meldet den Exit-Code der Befehle nicht: Gestartete Tests sieht man, das Ergebnis nicht.',
  'desktop.agenti-copilot-eventi': ['Prompts', 'Werkzeuge (Dateien und Befehle)', 'Ende des Zugs', 'Benachrichtigungen'],
  'desktop.agenti-copilot-nota': 'Eine einzige Lode-Datei in ~/.copilot/hooks: gilt ab der nächsten Sitzung. Copilot schickt die letzte Nachricht des Agenten nicht mit.',
  'desktop.agenti-windsurf-eventi': ['Prompts', 'geschriebener Code', 'Befehle', 'Antwort von Cascade'],
  'desktop.agenti-windsurf-nota': 'Gilt ab der nächsten Unterhaltung mit Cascade. Windsurf meldet den Exit-Code der Befehle nicht.',
  'desktop.agenti-qwen-eventi': ['Prompts', 'Werkzeuge (Dateien und Befehle)', 'Ende des Zugs', 'Benachrichtigungen'],
  'desktop.agenti-qwen-nota': 'Gilt ab der nächsten Sitzung von Qwen Code.',
  'desktop.agenti-opencode-eventi': ['geänderte Dateien', 'Befehle', 'Ende des Zugs'],
  'desktop.agenti-opencode-nota': 'Ein Lode-Plugin in ~/.config/opencode/plugins: gilt ab dem nächsten Start von OpenCode. Es liest nur mit: Die Antworten fasst es nicht an.',
  'desktop.agenti-kilo-eventi': ['geänderte Dateien', 'Befehle', 'Ende des Zugs'],
  'desktop.agenti-kilo-nota': 'Das Plugin ist das von OpenCode (Kilo ist ein Fork davon): gilt ab dem nächsten Start. Das Format der Ereignisse musst du bei deiner Version noch prüfen.',
  'desktop.agenti-aider-eventi': ['Ende der Antwort (ohne Details)'],
  'desktop.agenti-aider-nota': 'Aider meldet nur, dass es mit der Antwort fertig ist, nicht, was es angefasst hat: Die geänderten Dateien sieht „Projekt verfolgen“.',
  'desktop.agenti-non-json': 'ist kein JSON-Objekt',
  'desktop.agenti-file-non-di-lode': 'es gibt schon eine Datei mit diesem Namen, die nicht von Lode ist',
  'desktop.agenti-notifiche-aider': 'die Benachrichtigungen von Aider sind schon eingerichtet: Lode überschreibt sie nicht',
  'desktop.agenti-file-illeggibile': '{file} lässt sich nicht lesen ({motivo}): Ich fasse die Datei nicht an. Reparier sie oder verbinde von Hand.',
  'desktop.agenti-altre-righe': 'und {n} weitere Zeilen',
  'desktop.agenti-test-non-rilanciati': 'Er sagt, die Tests laufen durch, hat sie aber nach seiner letzten Änderung nicht nochmal gestartet.',
  'desktop.agenti-test-non-lanciati': 'Er sagt, die Tests laufen durch, aber ich habe in diesem Zug nicht gesehen, dass er sie gestartet hat.',
  'desktop.agenti-test-toccati': 'Er hat die Tests geändert ({file}), während sie fehlschlugen: Prüf, dass er sie nicht leichter gemacht hat.',
  // collegamento.mjs: Lode avviata dal codice (icona, avvio all'accensione, permessi del Mac)
  'desktop.permesso-audio-computer': 'Lode hört den Ton des Computers nur, wenn du eine Video-Vorlesung transkribierst. Der Ton bleibt nie auf dem Computer: In die Notiz kommt nur der Text.',
  'desktop.permesso-microfono': 'Lode benutzt das Mikrofon, wenn du mit Lode sprichst, für „Nochmal“ in der Vorlesung und um die Vorlesungen zu transkribieren, die du auswählst. Der Ton bleibt nie auf dem Computer.',
  'desktop.icona-non-creata': 'ich kann {file} nicht anlegen',
};
