// Das Protokoll im Vault (Deutsch): die Zeilen im Projekttagebuch, die Tabelle «Cosa so davvero» und der
// Abschnitt «Informatica» in Lode/Memoria.md. Die Abschnittstitel («## Cosa ho capito», «## Cosa so davvero», «## Informatica»),
// die Eigenschaften und die Marken %% lode:… %% stehen NICHT hier: Das sind Namen im Vault, die der Code wiederfindet.
export default {
  'diario.concetto-for': 'for-Schleife',
  'diario.concetto-while': 'while-Schleife',
  'diario.concetto-do-while': 'do-while-Schleife',
  'diario.concetto-ritroso': 'Rückwärts zählen',
  'diario.concetto-array': 'Arrays',
  'diario.concetto-divisione-intera': 'Ganzzahldivision',
  'diario.concetto-resto': 'Rest mit negativen Zahlen',
  'diario.concetto-cast': 'Cast nach double',
  'diario.concetto-incremento': 'i++ und ++i',
  'diario.concetto-switch': 'switch und break',
  'diario.concetto-cortocircuito': '&& und || mit Kurzschluss',
  'diario.concetto-else-pendente': 'Dangling else',
  'diario.concetto-puntatori': 'Übergabe per Adresse',
  'diario.concetto-parametri': 'Übergabe per Wert',
  'diario.concetto-visibilita': 'Variablen in Blöcken',
  'diario.concetto-char': 'char und ASCII-Codes',
  'diario.concetto-ricorsione': 'Rekursion',
  'diario.concetto-annidati': 'Verschachtelte Schleifen',
  'diario.concetto-break-continue': 'break und continue',
  'diario.concetto-ternario': 'Ternärer Operator',
  'diario.concetto-printf': 'printf und Formate',
  'diario.elenco-e': '{prima} und {ultimo}',
  'diario.errore-titolo': '„{titolo}“',
  'diario.errore-generico': 'Fehler',
  'diario.passo-dove': '„Wo nachsehen“',
  'diario.passo-cosa': '„Was es bedeutet“',
  'diario.passi-visti': { one: '{passi} gesehen', other: '{passi} gesehen' },
  'diario.funzione-nuova': 'neu: {nome}',
  'diario.funzione-nuova-in': 'neu: {nome} in {file}',
  'diario.funzione-cambiata': 'geändert: {nome}',
  'diario.funzione-cambiata-in': 'geändert: {nome} in {file}',
  'diario.funzione-tolta': 'entfernt: {nome}',
  'diario.funzione-tolta-in': 'entfernt: {nome} in {file}',
  'diario.file-nuovo': 'neu: {file}',
  'diario.file-tolto': 'entfernt: {file}',
  'diario.cambiati-file': { one: '{n} Datei geändert', other: '{n} Dateien geändert' },
  'diario.cambiato-codice': 'Code geändert',
  'diario.altre-modifiche': { one: 'und {n} weitere Änderung', other: 'und {n} weitere Änderungen' },
  'diario.chi-ha-scritto': 'wer es geschrieben hat: weiß ich nicht',
  'diario.cambiato-durante': 'der Code hat sich während des Tests geändert',
  'diario.prova-non-compila': 'Test: ✗ kompiliert nicht',
  'diario.prova-non-compila-errore': 'Test: ✗ kompiliert nicht, {errore}',
  'diario.prova-non-partita': 'Test: nicht gestartet',
  'diario.prova-ok': 'Test: ✓ kompiliert · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} Tests',
  'diario.nessun-caso': 'kein Testfall',
  'diario.ma-cambiato': 'aber der Code hat sich während des Tests geändert',
  'diario.codice-provato': 'Code getestet',
  'diario.prova-ko': 'Test: ✗ kompiliert · {ok}/{tot} Tests',
  'diario.n-prove': { one: '{n} Test', other: '{n} Tests' },
  'diario.nessuna-prova': 'kein Test',
  'diario.errori-risolti': { one: '{n} Fehler behoben', other: '{n} Fehler behoben' },
  'diario.n-errori': { one: '{n} Fehler', other: '{n} Fehler' },
  'diario.n-risolti': { one: '{n} behoben', other: '{n} behoben' },
  'diario.correzioni-viste': 'Korrekturen angesehen: {n}',
  'diario.oggi': 'Heute: {parti}',
  'diario.ultima-non-provata': 'letzte Änderung nicht getestet',
  'diario.smette': 'Lode verfolgt {progetto} nicht mehr',
  'diario.segue': 'Lode verfolgt {progetto}',
  'diario.errore': 'Fehler: {errore}',
  'diario.correzione-vista': 'Korrektur angesehen: {errore}',
  'diario.spiegate': 'Erklärt: {spiegate} von {totale}',
  'diario.spiegate-rivedere': 'Erklärt: {spiegate} von {totale}; nochmal ansehen: {nomi}',
  'diario.ieri': 'gestern',
  'diario.giorni-fa': { one: 'vor {n} Tag', other: 'vor {n} Tagen' },
  'diario.stato-da-rifare': 'nochmal üben',
  'diario.stato-sicuro': 'sicher',
  'diario.stato-mai-fatto': 'nie gemacht',
  'diario.diari-dei-progetti': 'Projekttagebücher:',
  'diario.tabella-nota': 'Lodes Zählung der „Was gibt das aus?“-Aufgaben, ohne KI. „Nochmal üben“ heißt: Zeit, es zu wiederholen.',
  'diario.tabella-testa': '| Thema | Aufgaben | Beim ersten Mal richtig | Zuletzt | Stand |',
  'diario.nessun-esercizio': 'Noch keine Aufgabe. Schreib „was gibt das aus“ in die Leiste: 5 Fragen, je eine Minute.',
  'diario.errori-frequenti': 'Fehler, die dir am häufigsten begegnen: {errori}.',
  'diario.sbagli-spesso': 'Da liegst du oft falsch: {sbagli}.',
  'diario.memoria-stampa': { one: '„Was gibt das aus?“: {n} Aufgabe, {giuste} % beim ersten Mal richtig.', other: '„Was gibt das aus?“: {n} Aufgaben, {giuste} % beim ersten Mal richtig.' },
  'diario.da-rifare': 'Nochmal üben: {argomenti}.',
};
