// «Bereit für die Abnahme» (Deutsch): der Stand der Funktionen, die Punkte im Code und die Karte.
// Die Wörter, die die Erklärung der Studierenden erkennen (controlla() in js/codice/discussione.js), stehen NICHT hier.
export default {
  'discussione.data-breve': '{g}.{m}.',
  'discussione.stato-agente': 'geändert, während der Agent gearbeitet hat · nie erklärt',
  'discussione.stato-mai': 'nie erklärt',
  'discussione.stato-cambiata': 'geändert, seit du sie zuletzt erklärt hast',
  'discussione.stato-rivedere': { one: 'nochmal ansehen · du hast einen Punkt ausgelassen', other: 'nochmal ansehen · du hast {n} Punkte ausgelassen' },
  'discussione.stato-spiegata': 'erklärt am {data}',
  'discussione.spiegata-adesso': 'gerade erklärt',
  'discussione.punto-parametri-breve': 'die Parameter',
  'discussione.punto-parametri': 'die Parameter ({nomi})',
  'discussione.punto-niente': 'dass sie nichts bekommt',
  'discussione.punto-chiama': 'dass sie `{nome}` aufruft',
  'discussione.punto-ciclo-breve': 'die Schleife',
  'discussione.punto-ciclo': 'dass es eine Schleife gibt',
  'discussione.punto-ricorsiva-breve': 'dass sie rekursiv ist',
  'discussione.punto-ricorsiva': 'dass sie rekursiv ist: Sie ruft sich selbst auf',
  'discussione.punto-restituisce-breve': 'was sie zurückgibt',
  'discussione.punto-restituisce-niente': 'dass sie nichts zurückgibt',
  'discussione.punto-restituisce-valore': 'dass sie einen Wert zurückgibt',
  'discussione.punto-restituisce-tipo': 'dass sie einen `{tipo}` zurückgibt',
  'discussione.file-non-arrivato': 'die Datei ist nicht angekommen',
  'discussione.nota': 'Lode weiß nicht, wer die Zeilen geschrieben hat: „während der Agent gearbeitet hat“ heißt, dass sich die Datei in einem seiner Züge geändert hat. Lode erklärt dir den Code nicht: Es prüft nur, ob du ihn erklären kannst.',
  'discussione.hai-detto': 'Du hast gesagt: {punti}.',
  'discussione.nessun-punto': 'Ich finde keinen der Punkte, die ich im Code sehe.',
  'discussione.hai-saltato': 'Ausgelassen: {punti}.',
  'discussione.tutti-i-punti': 'Du hast alle Punkte genannt, die ich im Code finde.',
  'discussione.la-so-spiegare': 'Kann ich erklären',
  'discussione.proviamo': 'Los geht’s',
  'discussione.titolo': 'Bereit für die Abnahme',
  'discussione.intro': 'Die Funktionen, die sich geändert haben, seit du das Projekt verfolgst. Zuerst die, die sich geändert haben, während ein Agent gearbeitet hat, und die du nie erklärt hast.',
  'discussione.diario-spento': 'Tagebuch aus: Ich notiere nichts.',
  'discussione.spiegate': 'Erklärt: {spiegate} von {totale}',
  'discussione.nessuna-funzione': 'Ich sehe keine geänderten Funktionen in {nome}, seit du es verfolgst. Wenn sich welche ändern, findest du sie hier.',
  'discussione.lingua-sconosciuta': 'Diese Sprache kann ich nicht prüfen: Sag du, ob du sie erklären kannst.',
  'discussione.leggo-il-file': 'Ich lese die Datei…',
  'discussione.file-lungo': '{file} hat {n} Zeilen: Über 2000 lese ich nicht. Sag du, ob du sie erklären kannst.',
  'discussione.non-riesco-leggere': 'Ich kann {file} nicht lesen: {errore}',
  'discussione.non-trovo-piu': 'Ich finde <code>{nome}</code> nicht mehr in {file}: Vielleicht hast du sie umbenannt oder gelöscht.',
  'discussione.togli': 'Aus der Liste nehmen',
  'discussione.spiegala': '<code>{firma}</code> · {file}, Zeile {riga}. Erklär sie wie bei der Abnahme: Was bekommt sie, was gibt sie zurück, wie funktioniert sie. Den Code zeige ich dir danach.',
  'discussione.aria-spiegazione': 'Deine Erklärung von {nome}',
  'discussione.ho-finito': 'Fertig',
  'discussione.alla-buona': 'Die Punkte findet der Code, grob: Er sagt nicht, ob die Erklärung richtig ist.',
};
