// Die Fehler von Compiler und Programmen (js/errori.js), auf Deutsch.
// Die Schlüssel «errori.<voce>.<campo>» sind die Texte jedes Eintrags im Wörterbuch: etichetta, breve, frase, dove, cosa, concetto.
export default {
  'errori.for-punto-e-virgola.etichetta': 'das `for` mit Kommas',
  'errori.for-punto-e-virgola.frase': 'die drei Teile des `for` trennt man mit `;`',
  'errori.for-punto-e-virgola.dove': `Sieh dir das \`for\` {allaRiga} an: In den Klammern müssen zwei \`;\` stehen.`,
  'errori.for-punto-e-virgola.cosa': 'Das `for` hat drei Teile: Start, Bedingung und Schritt, wie in `for (i = 0; i < n; i++)`. Man trennt sie mit `;`, nicht mit `,`. Mit Kommas sieht der Compiler nur einen Teil.',
  'errori.for-punto-e-virgola.concetto': 'for-Schleife',
  'errori.punto-e-virgola.etichetta': '`;` fehlt',
  'errori.punto-e-virgola.breve': '; fehlt',
  'errori.punto-e-virgola.frase': 'ein `;` fehlt',
  'errori.punto-e-virgola.dove': `Sieh dir das Ende von Zeile {riga} an, der Zeile vor {riga2}: Dort fehlt das \`;\`. Der Compiler merkt es erst, wenn er die nächste Zeile liest.`,
  'errori.punto-e-virgola.dove-2': `Sieh dir Zeile {riga}{colonna} an, ganz am Ende: Dort fehlt das \`;\`.`,
  'errori.punto-e-virgola.dove-3': `Sieh dir das Ende von Zeile {riga} und das der Zeile davor an: Manchmal merkt der Compiler es erst in der nächsten Zeile.`,
  'errori.punto-e-virgola.dove-4': 'Sieh dir das Ende der Anweisungen in der Nähe der markierten Stelle an.',
  'errori.punto-e-virgola.cosa': `In {L} endet jede Anweisung mit \`;\`, so wie ein Satz mit einem Punkt endet. Ohne hängt der Compiler die Anweisung an die nächste und versteht nicht mehr, was du meinst. Deshalb wird der Fehler manchmal erst in der nächsten Zeile gemeldet.`,
  'errori.punto-e-virgola.concetto': 'Ende von Anweisungen',
  'errori.include-mancante.etichetta': 'ein `#include` fehlt',
  'errori.include-mancante.breve': `#include{h} fehlt`,
  'errori.include-mancante.frase-2': 'diese Funktion',
  'errori.include-mancante.frase': `für {nome} fehlt \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'diese Funktion',
  'errori.include-mancante.frase-3': `für {nome} fehlt ein \`#include\``,
  'errori.include-mancante.dove-2': `: Die für \`<{h}>\` fehlt`,
  'errori.include-mancante.dove': `Sieh oben in der Datei nach, wo die \`#include\`-Zeilen stehen{h}.`,
  'errori.include-mancante.cosa': '`bool`, `true` und `false` gibt es in C nicht von Haus aus: Sie kommen mit `{h}`.',
  'errori.include-mancante.cosa-3': 'Diesen Namen',
  'errori.include-mancante.cosa-4': `, also \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome} schreibst du nicht selbst: Das steht in der C-Standardbibliothek. Um es zu benutzen, musst du die Datei einbinden, die es beschreibt (den Header){h}. Ohne \`#include\` weiß der Compiler nicht, dass es existiert und wie man es benutzt.`,
  'errori.include-mancante.cosa-5': ' Bei `math.h` hängst du unter Linux auch `-lm` ans Ende des Compiler-Befehls.',
  'errori.include-mancante.concetto': 'Bibliotheken und #include',
  'errori.funzione-non-dichiarata.etichetta': 'Funktion nicht deklariert',
  'errori.funzione-non-dichiarata.breve-2': 'Funktion',
  'errori.funzione-non-dichiarata.breve': `{nome} nicht deklariert`,
  'errori.funzione-non-dichiarata.frase': `du benutzt die Funktion {nome}, bevor du sie deklarierst`,
  'errori.funzione-non-dichiarata.dove': `Such, wo du die Funktion {nome} schreibst: Wenn sie unter Zeile {riga} steht, kennt der Compiler sie dort noch nicht. Prüf auch, ob der Name genau gleich geschrieben ist.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Such, wo du die Funktion {nome} schreibst: Wenn sie unter der Fehlerzeile steht, kennt der Compiler sie dort noch nicht. Prüf auch, ob der Name genau gleich geschrieben ist.`,
  'errori.funzione-non-dichiarata.cosa': 'Der Compiler liest die Datei von oben nach unten. Wenn du eine Funktion aufrufst, die er noch nicht gesehen hat, weiß er nicht, welche Parameter sie will und was sie zurückgibt: Neuere Compiler brechen ab, ältere raten und liegen oft falsch. Schieb die Funktion über `main` oder schreib ihren Prototyp über `main`: die erste Zeile der Funktion, gefolgt von `;`.',
  'errori.funzione-non-dichiarata.concetto': 'Funktionsprototypen',
  'errori.non-dichiarato.etichetta': 'Name nicht deklariert',
  'errori.non-dichiarato.breve-2': 'Name',
  'errori.non-dichiarato.breve': `{nome} nicht deklariert`,
  'errori.non-dichiarato.frase': `du benutzt {nome}, aber es ist nicht deklariert`,
  'errori.non-dichiarato.frase-2': 'du benutzt einen Namen, der nicht deklariert ist',
  'errori.non-dichiarato.dove': `Der Compiler schlägt {s} vor: Prüf, ob du das schreiben wolltest. `,
  'errori.non-dichiarato.dove-3': 'diesen Namen',
  'errori.non-dichiarato.dove-2': `Such, wo du {nome} deklarierst: Vielleicht heißt es anders (ein anderer Buchstabe, Groß- und Kleinschreibung), oder es ist in einem anderen Block \`{ }\` deklariert.`,
  'errori.non-dichiarato.cosa': 'Die Methode, die du aufrufst, gibt es mit diesem Namen und diesen Argumenttypen nicht. Prüf, wie sie geschrieben ist und ob sie in der richtigen Klasse steht. ',
  'errori.non-dichiarato.cosa-2': 'Bevor du eine Variable benutzt, musst du sie deklarieren, also ihren Typ und Namen schreiben (zum Beispiel `int zaehler = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'Eine Variable, die in `{ }` deklariert ist, gibt es nur dort drin: Außerhalb des Blocks sieht der Compiler sie nicht mehr. Auch die Reihenfolge zählt: Die Deklaration muss über der Zeile stehen, die sie benutzt.',
  'errori.non-dichiarato.concetto': 'Deklaration und Sichtbarkeit von Variablen',
  'errori.formato.etichetta': 'falsches Format in printf oder scanf',
  'errori.formato.frase': `das Format will einen {atteso}, aber du übergibst einen {dato}`,
  'errori.formato.frase-2': 'das Format passt nicht zu dem Wert, den du übergibst',
  'errori.formato.dove': `Sieh dir Zeile {riga} an: Vergleich jedes \`%\` im String mit dem Wert an derselben Stelle.`,
  'errori.formato.dove-senza-riga': `Sieh dir die markierte Zeile an: Vergleich jedes \`%\` im String mit dem Wert an derselben Stelle.`,
  'errori.formato.cosa': 'In `scanf` will jedes `%` die Adresse einer Variablen vom richtigen Typ: `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → `char`-Array. Wenn der Typ nicht passt, wird der gelesene Wert falsch gespeichert.',
  'errori.formato.cosa-2': ` Für einen {dato} nimmt man in \`scanf\` {p}.`,
  'errori.formato.cosa-3': '`printf` weiß nicht, welchen Typ die Werte haben: Es verlässt sich auf den Format-String. `%d` ist für `int`, `%f` für `double`, `%c` für `char`, `%s` für Strings. Wenn das Format nicht zum Wert passt, kommen unsinnige Zahlen heraus.',
  'errori.formato.cosa-4': ' Für einen `unsigned long` nimmt man `%lu`; wenn es das Ergebnis von `strlen` oder `sizeof` ist (ein `size_t`), nimmt man `%zu`.',
  'errori.formato.cosa-5': ` Für einen {dato} nimmt man in \`printf\` {p}.`,
  'errori.formato.concetto': 'printf, scanf und Formate',
  'errori.scanf-e-commerciale.etichetta': '`&` fehlt in scanf',
  'errori.scanf-e-commerciale.breve': '& fehlt in scanf',
  'errori.scanf-e-commerciale.frase': '`scanf` will die Adresse der Variablen: `&` fehlt',
  'errori.scanf-e-commerciale.dove': `Sieh dir das \`scanf\` {allaRiga} an: Da steht eine Variable ohne \`&\` davor.`,
  'errori.scanf-e-commerciale.cosa': '`scanf` muss in deine Variable schreiben, also muss es wissen, wo sie im Speicher liegt: ihre Adresse, die man mit `&` bekommt. Man schreibt `scanf("%d", &n);`. `char`-Arrays (Strings) sind die Ausnahme: Ihr Name ist schon eine Adresse, also kein `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf und Adressen',
  'errori.return-mancante.etichetta': 'das `return` fehlt',
  'errori.return-mancante.breve': 'return fehlt',
  'errori.return-mancante.frase-2': `die Funktion {nome}`,
  'errori.return-mancante.frase-3': 'die Funktion',
  'errori.return-mancante.frase-4': 'in manchen Fällen ',
  'errori.return-mancante.frase': `{p} kommt {sigla}ohne \`return\` ans Ende`,
  'errori.return-mancante.dove': `Sieh dir die \`}\` {allaRiga} an: Das ist das Ende der Funktion{p}. Geh jeden möglichen Weg durch (jedes \`if\` und \`else\`) und prüf, ob er mit einem \`return\` endet.`,
  'errori.return-mancante.cosa-2': ` (hier gibt sie {tipo} zurück)`,
  'errori.return-mancante.cosa': `Eine Funktion, die nicht \`void\` ist{tipo}, verspricht einen Rückgabewert. Wenn sie ohne \`return\` an der letzten \`}\` ankommt, bekommt der Aufrufer einen zufälligen Wert. Das passiert oft bei einem \`if\` mit eigenem \`return\`, aber ohne \`else\`.`,
  'errori.return-mancante.concetto': 'return in Funktionen',
  'errori.assegnamento-in-condizione.etichetta': '`=` statt `==`',
  'errori.assegnamento-in-condizione.breve': '= statt ==',
  'errori.assegnamento-in-condizione.frase': 'in der Bedingung steht `=` (zuweisen) statt `==` (vergleichen)',
  'errori.assegnamento-in-condizione.dove': `Sieh dir die Bedingung {allaRiga}{colonna} an.`,
  'errori.assegnamento-in-condizione.cosa': '`=` legt einen Wert in die Variable; `==` prüft, ob zwei Werte gleich sind. `if (x = 5)` weist `x` den Wert 5 zu und ist immer wahr, weil 5 nicht null ist. Zum Vergleichen brauchst du `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'Zuweisung und Vergleich',
  'errori.confronto-stringhe.etichetta': 'Strings mit `==` verglichen',
  'errori.confronto-stringhe.frase': 'du vergleichst Strings mit `==`',
  'errori.confronto-stringhe.dove': `Sieh dir den Vergleich {allaRiga} an.`,
  'errori.confronto-stringhe.cosa': 'In C vergleicht `==` zwischen zwei Strings die Adressen, nicht die Buchstaben: Das ist fast immer falsch, auch wenn der Text gleich ist. Um den Text zu vergleichen, nimmt man `strcmp(a, b) == 0` aus `{h}`. Wenn du nur ein Zeichen wolltest, schreib es in einfache Anführungszeichen: `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'Strings in C',
  'errori.puntatore-intero.etichetta': 'Vergleich zwischen Zeiger und Ganzzahl',
  'errori.puntatore-intero.frase': 'du vergleichst eine Adresse (einen Zeiger) mit einer Zahl oder einem Zeichen',
  'errori.puntatore-intero.dove': `Sieh dir beide Seiten des Vergleichs {allaRiga} an.`,
  'errori.puntatore-intero.cosa': 'Auf einer Seite steht ein Zeiger (eine Adresse, zum Beispiel ein String), auf der anderen eine Zahl oder ein Zeichen. Ein typischer Fehler: `"a"` in doppelten Anführungszeichen ist ein String, `\'a\'` in einfachen ist ein Zeichen. Um ein Zeichen zu prüfen, schreib `s[0] == \'a\'`; um zwei Strings zu vergleichen, nimm `strcmp`.',
  'errori.puntatore-intero.concetto': 'Zeichen, Strings und Zeiger',
  'errori.puntatori-incompatibili.etichetta': 'Zeiger verschiedenen Typs',
  'errori.puntatori-incompatibili.frase': `du benutzt einen {dato}, wo ein {atteso} gebraucht wird`,
  'errori.puntatori-incompatibili.frase-2': 'du benutzt einen Zeiger eines Typs, wo ein anderer gebraucht wird',
  'errori.puntatori-incompatibili.dove': `Sieh dir Zeile {riga} an: Vergleich den Typ dessen, was du übergibst (oder zuweist), mit dem Typ, der gebraucht wird.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Sieh dir die markierte Zeile an: Vergleich den Typ dessen, was du übergibst (oder zuweist), mit dem Typ, der gebraucht wird.`,
  'errori.puntatori-incompatibili.cosa': 'Ein Zeiger trägt den Typ dessen mit, worauf er zeigt: Ein `int *` zeigt auf Ganzzahlen, ein `char *` auf Zeichen. Wenn du den einen statt des anderen benutzt, hast du meist die falsche Variable erwischt, oder der Typ in der Deklaration oder im Funktionsparameter stimmt nicht.',
  'errori.puntatori-incompatibili.concetto': 'Zeiger',
  'errori.intero-puntatore.etichetta': 'Zahl und Adresse vermischt',
  'errori.intero-puntatore.frase': 'du vermischst eine Zahl und eine Adresse (einen Zeiger)',
  'errori.intero-puntatore.dove': `Sieh dir Zeile {riga} an: Auf einer Seite steht ein Zeiger, auf der anderen ein normaler Wert.`,
  'errori.intero-puntatore.dove-senza-riga': `Sieh dir die markierte Zeile an: Auf einer Seite steht ein Zeiger, auf der anderen ein normaler Wert.`,
  'errori.intero-puntatore.cosa': 'Ein Zeiger enthält eine Speicheradresse, keine beliebige Zahl. Wenn du die Adresse einer Variablen willst, schreib `&x`; wenn du den Wert willst, auf den ein Zeiger zeigt, schreib `*p`.',
  'errori.intero-puntatore.cosa-2': ' Hier schlägt der Compiler `&` vor.',
  'errori.intero-puntatore.cosa-3': ' Hier schlägt der Compiler `*` vor.',
  'errori.intero-puntatore.cosa-4': ' Achtung: `"a"` in doppelten Anführungszeichen ist ein String; ein Zeichen schreibt man in einfache Anführungszeichen: `\'a\'`.',
  'errori.intero-puntatore.concetto': 'Zeiger',
  'errori.variabile-non-usata.etichetta': 'unbenutzte Variable',
  'errori.variabile-non-usata.breve-2': 'Variable',
  'errori.variabile-non-usata.breve': `{nome} unbenutzt`,
  'errori.variabile-non-usata.frase-2': 'eine Variable',
  'errori.variabile-non-usata.frase': `{nome} ist deklariert, aber du benutzt sie nie`,
  'errori.variabile-non-usata.dove': `Sieh dir die Deklaration {allaRiga} an.`,
  'errori.variabile-non-usata.cosa': 'Das ist nur eine Warnung: Das Programm kompiliert trotzdem. Oft heißt es aber, dass du vergessen hast, sie zu benutzen, oder dass du aus Versehen eine andere Variable mit ähnlichem Namen benutzt. Wenn du sie nicht brauchst, nimm sie raus.',
  'errori.variabile-non-usata.concetto': 'Variablen',
  'errori.parametro-non-usato.etichetta': 'unbenutzter Parameter',
  'errori.parametro-non-usato.frase': `der Parameter {nome} wird nie benutzt`,
  'errori.parametro-non-usato.dove': `Sieh dir die erste Zeile der Funktion {allaRiga} an.`,
  'errori.parametro-non-usato.cosa': 'Die Funktion bekommt diesen Wert, benutzt ihn aber nicht. Manchmal ist das okay (zum Beispiel `argc` und `argv` in `main`); manchmal heißt es, dass du stattdessen eine andere Variable benutzt.',
  'errori.parametro-non-usato.concetto': 'Funktionsparameter',
  'errori.non-inizializzata.etichetta': 'Variable ohne Wert',
  'errori.non-inizializzata.breve-2': 'Variable',
  'errori.non-inizializzata.breve': `{nome} ohne Wert`,
  'errori.non-inizializzata.frase-2': 'eine Variable',
  'errori.non-inizializzata.frase': `du benutzt {nome}, bevor sie einen Wert hat`,
  'errori.non-inizializzata.dove-2': 'diese Variable',
  'errori.non-inizializzata.dove-3': ` (Zeile {dichiarata})`,
  'errori.non-inizializzata.dove': `Sieh dir {laRiga} an und geh dann zurück bis zur Deklaration von {nome}{dichiarata}: Gibt es einen Weg, auf dem sie nie einen Wert bekommt?`,
  'errori.non-inizializzata.cosa': 'In Java muss eine lokale Variable einen Wert bekommen, bevor sie gelesen wird, und zwar auf jedem möglichen Weg (auch wenn ein `if` falsch ist). Gib ihr in der Deklaration einen Startwert, zum Beispiel `int summe = 0;`.',
  'errori.non-inizializzata.cosa-2': 'Eine frisch deklarierte lokale Variable enthält einen zufälligen Wert, den, der noch im Speicher stand. Bevor du sie liest, musst du ihr einen Wert geben, zum Beispiel `int summe = 0;`. Das passiert oft bei Summen und Zählern.',
  'errori.non-inizializzata.concetto': 'Initialisierung von Variablen',
  'errori.riferimento-non-definito.etichetta': 'Funktion nie definiert (Linker)',
  'errori.riferimento-non-definito.breve': 'main fehlt',
  'errori.riferimento-non-definito.breve-3': 'Funktion',
  'errori.riferimento-non-definito.breve-2': `{nome} nicht definiert`,
  'errori.riferimento-non-definito.frase': 'die Funktion `main` fehlt',
  'errori.riferimento-non-definito.frase-2': `{nome} wird nicht gefunden: Im Befehl fehlt \`-lm\``,
  'errori.riferimento-non-definito.frase-4': 'eine Funktion',
  'errori.riferimento-non-definito.frase-3': `{nome} wird benutzt, aber ich finde nicht, wo sie geschrieben ist`,
  'errori.riferimento-non-definito.dove': 'Prüf, ob eine der Dateien `int main(void)` (oder `int main(int argc, char *argv[])`) genau so enthält, und ob diese Datei im Compiler-Befehl steht.',
  'errori.riferimento-non-definito.dove-2': 'Sieh dir den Compiler-Befehl an: Am Ende braucht es `-lm`.',
  'errori.riferimento-non-definito.dove-4': 'diese Funktion',
  'errori.riferimento-non-definito.dove-3': `Der Linker nennt keine Zeile. Such im Projekt den Rumpf von {nome}, also die Version mit den \`{ }\`: Der Name muss identisch sein (auch Groß- und Kleinschreibung), und die Datei, in der sie steht, muss im Compiler-Befehl stehen.`,
  'errori.riferimento-non-definito.cosa': 'Jedes C-Programm startet bei `main`. Wenn es fehlt oder anders geschrieben ist (`Main`, `mian`), gibt es keinen Startpunkt. Unter Windows spricht die Meldung manchmal von `WinMain`: Das ist dasselbe Problem.',
  'errori.riferimento-non-definito.cosa-2': 'Die Funktionen aus `{h}` stehen in einer eigenen Bibliothek. Unter Linux (und manchmal mit MinGW) musst du `-lm` ans Ende des Befehls hängen: `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'Das Kompilieren hat zwei Phasen: Erst wird jede `.c`-Datei für sich übersetzt, dann fügt der Linker sie zusammen. Der Prototyp sagt dem Compiler, dass die Funktion existiert, aber der Linker hat ihren Rumpf nirgends gefunden. Meist ist der Name anders geschrieben, eine Datei fehlt im Befehl, oder die Funktion wurde nie geschrieben.',
  'errori.riferimento-non-definito.concetto': 'Kompilieren und Linker',
  'errori.definizione-multipla.etichetta': 'doppelt definiert (Linker)',
  'errori.definizione-multipla.breve-2': 'Name',
  'errori.definizione-multipla.breve': `{nome} doppelt definiert`,
  'errori.definizione-multipla.frase-2': 'ein Name',
  'errori.definizione-multipla.frase': `{nome} ist im Programm zweimal definiert`,
  'errori.definizione-multipla.dove-2': 'diesen Namen',
  'errori.definizione-multipla.dove': `Such {nome} in allen Dateien des Projekts. Oft ist es eine Variable oder Funktion, die in einer \`.h\`-Datei steht, die mehrere \`.c\`-Dateien einbinden, oder eine \`.c\`-Datei, die mit \`#include\` eingebunden wird.`,
  'errori.definizione-multipla.cosa': 'Jede Funktion und jede globale Variable darf im ganzen Programm nur eine Definition haben. In `.h`-Dateien gehören nur die Prototypen (und Variablen mit `extern`); die Funktionsrümpfe gehören in die `.c`-Dateien. Eine `.c`-Datei bindet man nicht mit `#include` ein.',
  'errori.definizione-multipla.concetto': '.h- und .c-Dateien',
  'errori.tipi-in-conflitto.etichetta': 'unterschiedliche Deklarationen',
  'errori.tipi-in-conflitto.frase-2': 'eine Funktion',
  'errori.tipi-in-conflitto.frase': `{nome} ist auf zwei verschiedene Arten deklariert`,
  'errori.tipi-in-conflitto.dove-3': ` (Zeile {prima})`,
  'errori.tipi-in-conflitto.dove': `Vergleich Zeile {riga} mit der vorherigen Deklaration{prima}: Rückgabetyp und Parameter müssen identisch sein.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Vergleich die markierte Zeile mit der vorherigen Deklaration{prima}: Rückgabetyp und Parameter müssen identisch sein.`,
  'errori.tipi-in-conflitto.dove-5': 'die Funktion',
  'errori.tipi-in-conflitto.dove-4': ` Die erste Deklaration ist hier implizit: Du hast {nome} aufgerufen, bevor du sie deklariert hast. Schreib den Prototyp über \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'Der Prototyp (die Zeile mit `;`, meist oben oder in einer `.h`) und die echte Funktion müssen dasselbe sagen: gleicher Rückgabetyp, gleiche Parametertypen, in derselben Reihenfolge.',
  'errori.tipi-in-conflitto.concetto': 'Funktionsprototypen',
  'errori.argomenti.etichetta': 'falsche Anzahl Argumente',
  'errori.argomenti.frase': ` ({h} statt {e})`,
  'errori.argomenti.frase-2': `du übergibst weniger Argumente, als die Funktion will{quanti}`,
  'errori.argomenti.frase-3': `du übergibst mehr Argumente, als die Funktion will{quanti}`,
  'errori.argomenti.frase-5': 'diese Funktion',
  'errori.argomenti.frase-4': `der Aufruf von {nome} passt nicht zu ihren Parametern`,
  'errori.argomenti.dove-2': ` (Zeile {dich})`,
  'errori.argomenti.dove': `Vergleich den Aufruf {allaRiga} mit der ersten Zeile der Funktion{nome}{dich}: Zähl die Argumente und sieh dir ihre Typen an.`,
  'errori.argomenti.cosa': 'Eine Funktion ruft man mit so vielen Argumenten auf, wie sie Parameter hat, in derselben Reihenfolge. Wenn die Funktion `int summe(int a, int b)` ist, lautet der Aufruf `summe(x, y)`.',
  'errori.argomenti.concetto': 'Funktionsparameter',
  'errori.graffa.etichetta': 'fehlende geschweifte Klammer',
  'errori.graffa.frase': 'eine `}` ist zu viel',
  'errori.graffa.frase-2': 'eine `}` fehlt',
  'errori.graffa.dove': `Sieh dir die \`}\` {allaRiga} an: Sie schließt einen Block, der schon geschlossen war. Zähl die \`{\` und \`}\` darüber.`,
  'errori.graffa.dove-3': ` (Zeile {riga})`,
  'errori.graffa.dove-4': ` Die offene \`{\` steht in Zeile {aperta}.`,
  'errori.graffa.dove-2': `Der Compiler merkt es erst am Ende{riga}, aber die Klammer fehlt weiter oben.{aperta} Zähl die \`{\` und \`}\` jeder Funktion, jedes \`if\` und jeder Schleife.`,
  'errori.graffa.cosa': 'Jede `{` öffnet einen Block und jede `}` schließt ihn: Es müssen gleich viele sein. Mit gut eingerücktem Code (jeder Block etwas nach rechts) siehst du die fehlende Klammer sofort.',
  'errori.graffa.concetto': 'Blöcke und geschweifte Klammern',
  'errori.parentesi.etichetta': 'fehlende Klammer',
  'errori.parentesi.frase': 'eine `)` fehlt',
  'errori.parentesi.dove-2': `, Spalte {apertaCol}`,
  'errori.parentesi.dove': `Die offene \`(\` steht in Zeile {aperta}{apertaCol}: Ihre \`)\` fehlt vor der gemeldeten Stelle {allaRiga}.`,
  'errori.parentesi.dove-3': `Sieh dir Zeile {riga} an und zähl die \`(\` und \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Sieh dir die markierte Zeile an und zähl die \`(\` und \`)\`.`,
  'errori.parentesi.cosa': 'Jede `(` braucht ihre `)`. In langen Bedingungen und bei Aufrufen in anderen Aufrufen verliert man leicht eine: Zähl sie von links nach rechts.',
  'errori.parentesi.concetto': 'Klammern',
  'errori.espressione-attesa.etichetta': 'ein Wert fehlt',
  'errori.espressione-attesa.frase': 'der Compiler hat einen Wert erwartet und keinen gefunden',
  'errori.espressione-attesa.dove': `Sieh dir {laRiga}{colonna} an: Dort fehlt etwas (eine Zahl, eine Variable), oder ein Zeichen ist zu viel. Das passiert auch bei nicht geschlossenen Anführungszeichen in derselben Zeile.`,
  'errori.espressione-attesa.cosa': 'Nach einem `=`, einem Operator wie `+` oder einem Komma erwartet der Compiler einen Wert. Wenn er sofort `;`, `)` oder ein anderes Zeichen findet, bricht er ab.',
  'errori.espressione-attesa.concetto': 'Ausdrücke',
  'errori.ridefinizione.etichetta': 'doppelt deklariert',
  'errori.ridefinizione.breve-2': 'Name',
  'errori.ridefinizione.breve': `{nome} doppelt deklariert`,
  'errori.ridefinizione.frase-2': 'ein Name',
  'errori.ridefinizione.frase': `{nome} ist zweimal deklariert`,
  'errori.ridefinizione.dove': `Die beiden Deklarationen stehen in Zeile {prima} und in Zeile {riga}.`,
  'errori.ridefinizione.dove-4': 'diesen Namen',
  'errori.ridefinizione.dove-2': `Such über Zeile {riga} eine weitere Deklaration von {nome}.`,
  'errori.ridefinizione.dove-2-senza-riga': `Such über der markierten Zeile eine weitere Deklaration von {nome}.`,
  'errori.ridefinizione.cosa': 'Im selben Block deklariert man einen Namen nur einmal. Wenn du nur den Wert ändern willst, schreib `x = 2;` ohne den Typ davor.',
  'errori.ridefinizione.concetto': 'Deklaration von Variablen',
  'errori.non-array.etichetta': '`[ ]` auf etwas, das kein Array ist',
  'errori.non-array.frase': 'du benutzt `[ ]` auf etwas, das kein Array ist',
  'errori.non-array.dove': `Sieh dir die eckigen Klammern {allaRiga}{colonna} an.`,
  'errori.non-array.cosa': 'Eckige Klammern holen ein Element aus einem Array (oder einem Zeiger). Eine einfache Variable wie ein `int` hat keine Elemente. Vielleicht wolltest du eine andere Variable benutzen oder sie als Array deklarieren, zum Beispiel `int v[10];`.',
  'errori.non-array.concetto': 'Arrays',
  'errori.freccia-punto.etichetta': '`.` und `->` vertauscht',
  'errori.freccia-punto.frase': 'bei einer Struktur (keinem Zeiger) nimmt man `.`, nicht `->`',
  'errori.freccia-punto.frase-2': 'bei einem Zeiger auf eine Struktur nimmt man `->`, nicht `.`',
  'errori.freccia-punto.frase-3': 'das Feld der Struktur wird falsch geholt',
  'errori.freccia-punto.dove': `Sieh dir {laRiga}{colonna} an: Prüf, wie die Variable vor dem Punkt oder dem Pfeil deklariert ist.`,
  'errori.freccia-punto.cosa': 'Wenn du die Struktur selbst hast (`struct nodo n`), holst du das Feld mit dem Punkt: `n.val`. Wenn du einen Zeiger auf die Struktur hast (`struct nodo *p`), nimmst du den Pfeil: `p->val`, das heißt `(*p).val`.',
  'errori.freccia-punto.concetto': 'Strukturen und Zeiger',
  'errori.membro-inesistente.etichetta': 'Feld, das es nicht gibt',
  'errori.membro-inesistente.frase-2': 'die Struktur',
  'errori.membro-inesistente.frase': `{p} hat kein Feld {m}`,
  'errori.membro-inesistente.frase-3': 'die Struktur hat dieses Feld nicht',
  'errori.membro-inesistente.dove-2': ` mit {m}`,
  'errori.membro-inesistente.dove': `Sieh dir die Definition der Struktur{p} an und vergleich die Namen der Felder{m}.`,
  'errori.membro-inesistente.cosa': 'Die Felder einer Struktur sind die, die in ihrer Definition stehen, mit genau diesen Namen. Ein anderer Name, auch nur ein Buchstabe Unterschied, ist ein anderes Feld.',
  'errori.membro-inesistente.concetto': 'Strukturen',
  'errori.header-non-trovato.etichetta': 'Header nicht gefunden',
  'errori.header-non-trovato.frase-2': 'aus dem #include',
  'errori.header-non-trovato.frase': `ich finde die Datei {h} nicht`,
  'errori.header-non-trovato.dove': `Sieh dir die \`#include\`-Zeile {allaRiga} an.`,
  'errori.header-non-trovato.dove-2': ` Vielleicht meintest du {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` gibt es nur bei einigen alten Compilern für Windows (Turbo C, Dev-C++): Es gehört nicht zum C-Standard.',
  'errori.header-non-trovato.cosa': 'Mit `#include {sistema}` sucht der Compiler die Datei unter denen des Systems; mit `#include {progetto}` sucht er sie zuerst im Ordner des Projekts. Wenn der Name auch nur in einem Buchstaben falsch ist, findet er sie nicht und bricht sofort ab.',
  'errori.header-non-trovato.concetto': 'Bibliotheken und #include',
  'errori.file-sorgente-mancante.etichetta': 'Datei nicht gefunden',
  'errori.file-sorgente-mancante.frase-2': 'aus dem Befehl',
  'errori.file-sorgente-mancante.frase': `der Compiler findet die Datei {h} nicht`,
  'errori.file-sorgente-mancante.dove': 'Sieh dir den Compiler-Befehl und die Dateinamen im Ordner an.',
  'errori.file-sorgente-mancante.cosa': 'Der Befehl nennt eine Datei, die es im Ordner nicht gibt. Prüf den Namen (Großbuchstaben, Endung `.c`) und ob der Befehl im richtigen Ordner startet.',
  'errori.file-sorgente-mancante.concetto': 'Kompilieren',
  'errori.non-assegnabile.etichetta': 'Zuweisung nicht möglich',
  'errori.non-assegnabile.frase': 'ein Array (oder einen String) kannst du nicht mit `=` kopieren',
  'errori.non-assegnabile.frase-2': 'links von `=` steht etwas, das keine Variable ist',
  'errori.non-assegnabile.dove': `Sieh dir an, was links von \`=\` {allaRiga} steht.`,
  'errori.non-assegnabile.cosa': 'Ein Array kopiert man nicht mit `=`. Für einen String nimm `strcpy(ziel, "text");` aus `{h}`, oder gib den Wert schon bei der Deklaration: `char name[10] = "text";`.',
  'errori.non-assegnabile.cosa-2': 'Links von `=` muss ein Platz stehen, an den der Wert kommt: eine Variable, ein Array-Element, ein Feld. Keine Rechnung wie `a + 1`. Wenn du vergleichen wolltest, brauchst du `==`.',
  'errori.non-assegnabile.concetto': 'Zuweisung',
  'errori.tipo-sconosciuto.etichetta': 'unbekannter Typ',
  'errori.tipo-sconosciuto.frase-2': 'dieser Name',
  'errori.tipo-sconosciuto.frase': `{nome} ist kein Typ, den der Compiler kennt`,
  'errori.tipo-sconosciuto.dove-2': 'den Typ',
  'errori.tipo-sconosciuto.dove': `Sieh dir {laRiga} an und such weiter oben, wo du {nome} definierst.`,
  'errori.tipo-sconosciuto.cosa': 'In C gibt es den Typ `string` nicht (den gibt es in C++ und anderen Sprachen). Ein String ist in C ein `char`-Array: `char s[50];` oder `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Bevor du einen Typ wie `Nodo` benutzt, musst du ihn definieren, zum Beispiel mit `typedef struct nodo Nodo;`, über der Zeile, die ihn benutzt. Prüf auch Groß- und Kleinschreibung.',
  'errori.tipo-sconosciuto.concetto': 'Typen und typedef',
  'errori.virgolette.etichetta': 'String nicht geschlossen',
  'errori.virgolette.frase': 'ein String ist nicht geschlossen: `"` fehlt',
  'errori.virgolette.dove': `Sieh dir {laRiga}{colonna} an: Dort beginnt der String. Such, wo er enden sollte.`,
  'errori.virgolette.cosa': 'Ein String beginnt und endet mit `"` in derselben Zeile. Wenn das schließende fehlt, hält der Compiler den ganzen Rest der Zeile für den String und kommt danach durcheinander: Deshalb verschwinden die Fehler danach oft von selbst.',
  'errori.virgolette.concetto': 'Strings',
  'errori.if-vuoto.etichetta': '`;` nach der Bedingung',
  'errori.if-vuoto.frase': `direkt nach \`{kw}\` steht ein \`;\``,
  'errori.if-vuoto.frase-2': `direkt nach der Bedingung {if} steht ein \`;\``,
  'errori.if-vuoto.dove': `Sieh dir Zeile {riga} an: Direkt nach \`{kw}\` steht ein \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Sieh dir die markierte Zeile an: Direkt nach \`{kw}\` steht ein \`;\`.`,
  'errori.if-vuoto.dove-3': `Sieh dir das Ende von Zeile {riga} an: Nach der \`)\` der Bedingung steht ein \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Sieh dir das Ende der markierten Zeile an: Nach der \`)\` der Bedingung steht ein \`;\`.`,
  'errori.if-vuoto.cosa': 'Das `;` direkt nach `else` ist eine leere Anweisung: Das `else` steuert nur diese. Der Block `{ }` darunter läuft immer, auch wenn die Bedingung des `if` wahr ist.',
  'errori.if-vuoto.cosa-2': 'Das `;` direkt nach `do` ist eine leere Anweisung: Die Schleife wiederholt nur diese. Der Block `{ }` darunter gehört nicht zur Schleife.',
  'errori.if-vuoto.cosa-3': 'Das `;` direkt nach `if (...)` ist eine leere Anweisung: Das `if` steuert nur diese. Der Block `{ }` darunter läuft immer, egal wie die Bedingung ist. Bei `while` ist es schlimmer: Die Schleife kann endlos laufen.',
  'errori.if-vuoto.concetto': 'if und Schleifen',
  'errori.confronto-inutile.etichetta': 'Anweisung, die nichts tut',
  'errori.confronto-inutile.frase': 'da steht ein `==`, das nichts tut: Vielleicht meintest du `=`',
  'errori.confronto-inutile.frase-2': 'diese Anweisung tut nichts',
  'errori.confronto-inutile.dove': `Sieh dir {laRiga}{colonna} an.`,
  'errori.confronto-inutile.cosa': 'Ein Vergleich allein (`x == 4;`) berechnet wahr oder falsch und wirft das Ergebnis weg. Wenn du der Variablen einen Wert geben wolltest, brauchst du ein einzelnes `=`: `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'Eine Rechnung, die weder in einer Variablen gespeichert noch ausgegeben noch in einer Bedingung benutzt wird, wird weggeworfen. Vielleicht fehlt ein `=` oder ein Funktionsaufruf.',
  'errori.confronto-inutile.concetto': 'Zuweisung und Vergleich',
  'errori.indirizzo-locale.etichetta': 'Adresse einer lokalen Variablen',
  'errori.indirizzo-locale.frase-2': 'einer lokalen Variablen',
  'errori.indirizzo-locale.frase': `du gibst die Adresse von {nome} zurück, die verschwindet, wenn die Funktion endet`,
  'errori.indirizzo-locale.dove': `Sieh dir das \`return\` {allaRiga} an.`,
  'errori.indirizzo-locale.cosa': 'Lokale Variablen leben nur, solange die Funktion läuft. Ihre Adresse zurückzugeben heißt, dem Aufrufer einen Speicherplatz zu geben, den es nicht mehr gibt. Wenn du ein Array zurückgeben musst, erzeug es mit `malloc` (und denk danach an `free`) oder lass es dir als Parameter übergeben.',
  'errori.indirizzo-locale.concetto': 'Speicher und Funktionen',
  'errori.segni-diversi.etichetta': 'Zahlen mit und ohne Vorzeichen',
  'errori.segni-diversi.frase': 'du vergleichst eine Zahl mit Vorzeichen und eine ohne',
  'errori.segni-diversi.dove': `Sieh dir den Vergleich {allaRiga} an.`,
  'errori.segni-diversi.cosa': 'Funktionen wie `strlen` geben eine Zahl ohne Vorzeichen zurück (`size_t`). Sie mit einem `int` zu vergleichen, klappt meistens, aber wenn der `int` negativ ist, geht der Vergleich schief. Es ist eine Warnung: Du kannst den Index als `size_t` deklarieren oder die Länge vor der Schleife in einem `int` speichern.',
  'errori.segni-diversi.concetto': 'Ganzzahltypen',
  'errori.return-void.etichetta': '`return` und `void` widersprechen sich',
  'errori.return-void.frase': '`return;` ohne Wert in einer Funktion, die einen zurückgeben muss',
  'errori.return-void.frase-2': 'eine `void`-Funktion kann keinen Wert zurückgeben',
  'errori.return-void.dove': `Sieh dir das \`return\` {allaRiga} und die erste Zeile der Funktion an.`,
  'errori.return-void.cosa': '`void` heißt, die Funktion gibt nichts zurück: Dort schreibt man nur `return;` (oder gar nichts). Wenn die Funktion ein Ergebnis liefern soll, kommt statt `void` der richtige Typ hin, zum Beispiel `int`, und jedes `return` braucht einen Wert.',
  'errori.return-void.concetto': 'return in Funktionen',
  'errori.main-int.etichetta': '`main` ist nicht `int`',
  'errori.main-int.frase': '`main` muss `int` zurückgeben',
  'errori.main-int.dove-2': ` (Zeile {riga})`,
  'errori.main-int.dove': `Sieh dir die Zeile von \`main\`{riga} an.`,
  'errori.main-int.cosa': 'Der C-Standard will `int main(void)` und am Ende `return 0;` für „alles gut“. `void main` akzeptieren nur einige alte Compiler.',
  'errori.main-int.concetto': 'die main-Funktion',
  'errori.fuori-array.etichetta': 'Index außerhalb des Arrays',
  'errori.fuori-array.frase': `du benutzt den Index {i}, aber das Array reicht nicht so weit`,
  'errori.fuori-array.frase-2': 'du benutzt einen Index außerhalb des Arrays',
  'errori.fuori-array.dove-2': ` und die Deklaration des Arrays in Zeile {riga}`,
  'errori.fuori-array.dove': `Sieh dir {laRiga}{riga} an.`,
  'errori.fuori-array.cosa': 'Ein Array mit N Elementen hat die Indizes `0` bis `N-1`: Bei `int v[5]` ist das letzte `v[4]`, und `v[5]` liegt schon außerhalb. Das passiert oft mit einer Schleife `for (i = 0; i <= 5; i++)` statt `i < 5`.',
  'errori.fuori-array.concetto': 'Arrays und Indizes',
  'errori.argomenti-formato.etichetta': '`%` und Werte passen nicht zusammen',
  'errori.argomenti-formato.frase': 'im String stehen mehr `%` als Werte',
  'errori.argomenti-formato.frase-2': 'du übergibst mehr Werte, als `%` im String stehen',
  'errori.argomenti-formato.dove': `Sieh dir den String {allaRiga} an und zähl die \`%\` und die Werte nach dem Komma.`,
  'errori.argomenti-formato.cosa': 'Jedes `%d`, `%f`, `%c`… im String von `printf` (oder `scanf`) nimmt sich den nächsten Wert, der Reihe nach. Die Zahl der `%` und die Zahl der Werte nach dem String müssen gleich sein.',
  'errori.argomenti-formato.concetto': 'printf und Formate',
  'errori.divisione-zero.etichetta': 'Division durch null',
  'errori.divisione-zero.frase': 'du teilst durch null',
  'errori.divisione-zero.dove': `Sieh dir die Division {allaRiga} an.`,
  'errori.divisione-zero.cosa': 'Eine Ganzzahl durch null zu teilen hat kein Ergebnis: Meistens stürzt das Programm ab. Prüf vor dem Teilen, dass der Divisor nicht null ist, zum Beispiel mit `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'Division',
  'errori.troppi-inizializzatori.etichetta': 'zu viele Werte im Array',
  'errori.troppi-inizializzatori.frase': 'du gibst mehr Werte an, als das Array fassen kann',
  'errori.troppi-inizializzatori.dove': `Sieh dir die Deklaration {allaRiga} an: Vergleich die Größe in \`[ ]\` mit der Zahl der Werte in \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'Wenn ein Array Platz für 2 Werte hat und du 3 in die geschweiften Klammern schreibst, wird der dritte weggeworfen. Mach das Array größer oder nimm Werte raus. Du kannst die eckigen Klammern auch leer lassen, `int v[] = {1, 2, 3};`, dann zählt der Compiler selbst.',
  'errori.troppi-inizializzatori.concetto': 'Arrays',
  'errori.operandi.etichetta': 'Operation zwischen diesen Typen nicht möglich',
  'errori.operandi.frase': `die Operation geht nicht zwischen {a} und {b}`,
  'errori.operandi.frase-2': 'die Operation geht nicht zwischen diesen zwei Typen',
  'errori.operandi.dove': `Sieh dir den Operator {allaRiga}{colonna} und die Typen auf beiden Seiten an.`,
  'errori.operandi.cosa': 'Operatoren wie `&&`, `+` oder `<` wollen bestimmte Typen: `&&` arbeitet mit `boolean`, `<` mit Zahlen. Strings vergleicht man nicht mit `<`: Man nimmt `compareTo`, und für Gleichheit `equals`.',
  'errori.operandi.cosa-2': 'Operatoren wie `+`, `-` und `<` funktionieren mit Zahlen (und manche mit Zeigern). Zwei Strukturen kann man nicht direkt addieren oder vergleichen: Arbeite mit ihren Feldern, zum Beispiel `a.x + b.x`. Strings verbindet man in C nicht mit `+`: Man nimmt `strcat`.',
  'errori.operandi.concetto': 'Typen und Operatoren',
  'errori.carattere-strano.etichetta': 'seltsames Zeichen im Code',
  'errori.carattere-strano.frase': 'im Code steht ein seltsames Zeichen',
  'errori.carattere-strano.dove': `Sieh dir {laRiga}{colonna} an.`,
  'errori.carattere-strano.cosa': 'Oft ist es ein Zeichen, das aus einem PDF oder einer Webseite kopiert wurde: typografische Anführungszeichen `“ ”`, ein schräger Apostroph, ein spezielles Leerzeichen oder ein langer Strich. Für das Auge sehen sie gleich aus, für den Compiler nicht. Tipp die Zeile von Hand neu.',
  'errori.carattere-strano.concetto': 'Zeichen im Code',
  'errori.non-sicura.etichetta': 'Visual Studio und die „unsicheren“ Funktionen',
  'errori.non-sicura.frase-2': 'diese Funktion',
  'errori.non-sicura.frase': `Visual Studio will {nome} nicht: Es hält sie für unsicher`,
  'errori.non-sicura.dove': 'An deinem C ist nichts falsch: Das ist eine Regel von Visual Studio.',
  'errori.non-sicura.cosa': 'Visual Studio meldet `scanf`, `strcpy` und ähnliche, weil sie, falsch benutzt, über das Ende eines Arrays hinaus schreiben können. Der C-Standard erlaubt sie, und die Kurse benutzen sie. Um die Warnung abzuschalten, schreib `#define _CRT_SECURE_NO_WARNINGS` als allererste Zeile der Datei, vor die `#include`. Wenn deine Dozentin oder dein Dozent `scanf_s` lieber mag, halt dich daran.',
  'errori.non-sicura.concetto': 'verschiedene Compiler',
  'errori.ricorsione-infinita.etichetta': 'endlose Rekursion',
  'errori.ricorsione-infinita.frase': 'die Funktion ruft sich immer wieder selbst auf: Sie hört nie auf',
  'errori.ricorsione-infinita.dove': `Sieh dir die Funktion{p} {allaRiga} an: Such den Basisfall, also ein \`if\`, das einen Wert zurückgibt, ohne die Funktion nochmal aufzurufen.`,
  'errori.ricorsione-infinita.cosa': 'Eine rekursive Funktion braucht einen Basisfall, und jeder Aufruf muss diesem Fall näher kommen (zum Beispiel mit `n - 1`). Hier führt jeder Weg zu einem weiteren Aufruf: Das Programm füllt den Speicher und bricht ab.',
  'errori.ricorsione-infinita.concetto': 'Rekursion',
  'errori.sintassi.etichetta': 'Code, den der Compiler so nicht versteht',
  'errori.sintassi.frase': 'der Compiler versteht nicht, wie der Code hier weitergeht',
  'errori.sintassi.dove': `Sieh dir {laRiga} und die Zeile davor an: Oft liegt das eigentliche Problem direkt darüber, zum Beispiel ein \`;\` zu viel nach der ersten Zeile einer Funktion, eine \`}\` zu viel oder eine nicht geschlossene Klammer.`,
  'errori.sintassi.cosa': 'Der Compiler liest den Code nach festen Regeln, wie die Grammatik einer Sprache. Hier hat er etwas gefunden, das an dieser Stelle nicht stehen darf. Die Originalmeldung sagt, was er erwartet hat.',
  'errori.sintassi.concetto': 'Syntax',
  'errori.java-tipi.etichetta': 'inkompatible Typen (Java)',
  'errori.java-tipi.frase': `von {dato} nach {atteso} können Daten verloren gehen`,
  'errori.java-tipi.frase-2': `{dato} kann man nicht benutzen, wo {atteso} gebraucht wird`,
  'errori.java-tipi.frase-3': 'der Wert hat nicht den Typ, der gebraucht wird',
  'errori.java-tipi.dove': `Sieh dir {laRiga}{colonna} an: Vergleich den Typ der Variablen mit dem des Werts.`,
  'errori.java-tipi.cosa': 'In Java hat jede Variable einen Typ, und der Compiler prüft, ob die Werte passen. Von `double` nach `int` gehen die Nachkommastellen verloren, also musst du das ausdrücklich mit einem Cast sagen: `(int) x`. Ein `String` wird nicht von selbst zu einer Zahl: Man nimmt `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'Typen in Java',
  'errori.java-import.etichetta': 'ein `import` fehlt (Java)',
  'errori.java-import.frase-2': 'diese Klasse',
  'errori.java-import.frase': `für {nome} fehlt ein \`import\``,
  'errori.java-import.dove': 'Sieh oben in der Datei nach, über der Klasse, wo die `import`-Zeilen stehen.',
  'errori.java-import.cosa-2': 'Diese Klasse',
  'errori.java-import.cosa-3': `, also \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} liegt in einem Paket der Java-Bibliothek: Um sie zu benutzen, brauchst du das \`import\` oben in der Datei{nome2}. Prüf auch Groß- und Kleinschreibung.`,
  'errori.java-import.concetto': 'import in Java',
  'errori.java-nome-file.etichetta': 'Datei und Klasse heißen verschieden',
  'errori.java-nome-file.frase-2': '(public)',
  'errori.java-nome-file.frase-3': 'Klasse',
  'errori.java-nome-file.frase': `die Klasse {nome} muss in der Datei {nome2} stehen`,
  'errori.java-nome-file.dove': 'Sieh dir den Dateinamen und die Zeile `public class` an.',
  'errori.java-nome-file.cosa': 'In Java muss eine `public`-Klasse in einer Datei mit demselben Namen stehen, auch in Groß- und Kleinschreibung: `public class Main` gehört in `Main.java`. Benenn die Datei oder die Klasse um.',
  'errori.java-nome-file.concetto': 'Klassen und Dateien in Java',
  'errori.java-statico.etichetta': 'nicht-static aus static benutzt',
  'errori.java-statico.frase-2': 'dieser Name',
  'errori.java-statico.frase': `{nome} ist nicht \`static\`, aber du benutzt es aus einer \`static\`-Methode`,
  'errori.java-statico.dove-2': 'diesem Namen',
  'errori.java-statico.dove': `Sieh dir {laRiga} und die Deklaration von {nome} an.`,
  'errori.java-statico.cosa': '`main` ist `static`: Es gehört zur Klasse, nicht zu einem Objekt. Von dort aus kannst du nur `static`-Methoden und -Variablen benutzen, oder du erzeugst zuerst ein Objekt mit `new` und benutzt das. In Übungen mit nur einer Klasse fehlt der Methode oft das `static`.',
  'errori.java-statico.concetto': 'static in Java',
  'errori.java-irraggiungibile.etichetta': 'Anweisung, die nie ausgeführt wird',
  'errori.java-irraggiungibile.frase': 'diese Anweisung wird nie ausgeführt',
  'errori.java-irraggiungibile.dove': `Sieh dir {laRiga} und die Zeile davor an.`,
  'errori.java-irraggiungibile.cosa': 'Vor dieser Zeile steht ein `return`, ein `break`, ein `continue` oder eine Schleife, die nicht endet: Von dort kommt das Programm nie hierher. Nimm sie raus oder schieb sie davor.',
  'errori.java-irraggiungibile.concetto': 'Programmablauf',
  'errori.java-indice.etichetta': 'Index außerhalb (Java)',
  'errori.java-indice.frase': `du benutzt den Index {i}, aber die Länge ist {l}`,
  'errori.java-indice.frase-2': 'du liest eine Position, die das Array (oder der String) nicht hat',
  'errori.java-indice.cosa': 'Indizes starten bei 0: Bei Länge 5 gehen sie von 0 bis 4. Prüf die Bedingung der Schleife: Oft steht da `<=`, wo `<` hingehört, oder `length` wird als Index benutzt.',
  'errori.java-indice.concetto': 'Arrays und Indizes',
  'errori.java-null.etichetta': 'null-Objekt (Java)',
  'errori.java-null.frase': 'du benutzt ein Objekt, das `null` ist',
  'errori.java-null.cosa': 'Das Objekt wurde nie mit `new` erzeugt, oder eine Methode hat `null` zurückgegeben. Neuere Java-Versionen schreiben in die Meldung, welche Variable `null` war.',
  'errori.java-null.concetto': 'Objekte und null',
  'errori.java-divisione-zero.etichetta': 'Division durch null (Java)',
  'errori.java-divisione-zero.frase': 'du teilst eine Ganzzahl durch null',
  'errori.java-divisione-zero.cosa': 'Eine Ganzzahl durch null zu teilen (auch mit `%`) hat kein Ergebnis, und Java bricht ab. Prüf vor der Division den Divisor, zum Beispiel mit `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'Division',
  'errori.java-input.etichetta': 'Eingabe, die keine Zahl ist (Java)',
  'errori.java-input.frase': `{v} ist keine Zahl`,
  'errori.java-input.frase-2': 'das Programm hat eine Zahl erwartet und etwas anderes gelesen',
  'errori.java-input.cosa': 'Das Programm wollte eine Zahl und hat etwas anderes gefunden: Buchstaben, Leerzeichen, eine leere Zeile oder ein Komma statt eines Punkts. Prüf, was du eingibst, oder die `.in`-Datei des Tests.',
  'errori.java-input.concetto': 'Eingabe',
  'errori.java-stack.etichetta': 'endlose Rekursion (Java)',
  'errori.java-stack.frase': 'die Methode ruft sich zu oft selbst auf',
  'errori.java-stack.cosa': 'Jede rekursive Methode braucht einen Basisfall: eine Bedingung, bei der sie einen Wert zurückgibt, ohne sich nochmal aufzurufen. Und jeder Aufruf muss dem Basisfall näher kommen.',
  'errori.java-stack.concetto': 'Rekursion',
  'errori.py-uguale.etichetta': '`=` statt `==`',
  'errori.py-uguale.breve': '= statt ==',
  'errori.py-uguale.frase': 'in der Bedingung steht `=` statt `==`',
  'errori.py-uguale.dove': `Sieh dir die Bedingung {allaRiga} an.`,
  'errori.py-uguale.cosa': '`=` legt einen Wert in eine Variable; `==` prüft, ob zwei Werte gleich sind. In einer Bedingung (`if`, `elif`, `while`) brauchst du `==`: `if x == 5:`.',
  'errori.py-uguale.concetto': 'Zuweisung und Vergleich',
  'errori.py-due-punti.etichetta': 'der `:` fehlt',
  'errori.py-due-punti.frase': 'am Ende der Zeile fehlt der `:`',
  'errori.py-due-punti.dove': `Sieh dir das Ende von Zeile {riga} an.`,
  'errori.py-due-punti.dove-senza-riga': `Sieh dir das Ende der markierten Zeile an.`,
  'errori.py-due-punti.cosa': 'In Python enden `if`, `elif`, `else`, `for`, `while`, `def` und `class` mit `:`. Der Doppelpunkt sagt „jetzt beginnt der Block“, der darunter steht, eingerückt.',
  'errori.py-due-punti.concetto': 'Blöcke in Python',
  'errori.py-parentesi.etichetta': 'Klammer nicht geschlossen',
  'errori.py-parentesi.frase': `da steht eine {c}, die nichts schließt`,
  'errori.py-parentesi.frase-2': `eine {p} ist nicht geschlossen`,
  'errori.py-parentesi.dove': `Sieh dir {laRiga} an: Zähl die offenen und geschlossenen Klammern. Wenn die Zeile richtig aussieht, sieh dir die davor an.`,
  'errori.py-parentesi.cosa': 'Jede `(`, `[` und `{` braucht ihre schließende Klammer vom selben Typ. Wenn eine fehlt, liest Python die nächsten Zeilen weiter, als gehörten sie zur selben Anweisung.',
  'errori.py-parentesi.concetto': 'Klammern',
  'errori.py-stringa.etichetta': 'String nicht geschlossen',
  'errori.py-stringa.frase': 'ein String ist nicht geschlossen',
  'errori.py-stringa.dove': `Sieh dir {laRiga} an: Dort beginnt der String. Such, wo das schließende Anführungszeichen fehlt.`,
  'errori.py-stringa.cosa': 'Ein String beginnt und endet mit derselben Art Anführungszeichen, `"` oder `\'`, in derselben Zeile. Wenn im Text ein Apostroph steht, nimm doppelte Anführungszeichen: `"Rock \'n\' Roll"`.',
  'errori.py-stringa.concetto': 'Strings',
  'errori.py-print.etichetta': '`print` ohne Klammern',
  'errori.py-print.frase': '`print` will Klammern',
  'errori.py-print.dove': `Sieh dir {laRiga} an.`,
  'errori.py-print.cosa': 'In Python 3 ist `print` eine Funktion: Man schreibt `print("hallo")`. Die Form ohne Klammern stammt aus Python 2, das man noch in alten Beispielen im Internet findet.',
  'errori.py-print.concetto': 'Funktionen',
  'errori.py-indentazione.etichetta': 'falsche Einrückung',
  'errori.py-indentazione.frase': 'nach dem Doppelpunkt fehlt die Einrückung',
  'errori.py-indentazione.frase-2': 'da ist eine Einrückung zu viel',
  'errori.py-indentazione.frase-3': 'die Einrückung passt nicht zu den Zeilen darüber',
  'errori.py-indentazione.frase-4': 'du mischst Tabs und Leerzeichen in der Einrückung',
  'errori.py-indentazione.frase-5': 'die Einrückung der Zeile ist falsch',
  'errori.py-indentazione.dove-2': ` Das \`{kw}\` steht in Zeile {l}.`,
  'errori.py-indentazione.dove': `Sieh dir {laRiga} und die Zeile darüber an: Vergleich die Leerzeichen am Zeilenanfang.{kw}`,
  'errori.py-indentazione.cosa': 'In Python gehört die Einrückung (die Leerzeichen am Zeilenanfang) zum Code: Sie sagt, welche Zeilen in einem `if`, einem `for` oder einer `def` stehen. Nach dem `:` muss die Zeile darunter eingerückt sein, und die Zeilen im selben Block müssen gleich eingerückt sein. Nimm immer 4 Leerzeichen und misch sie nicht mit Tabs.',
  'errori.py-indentazione.concetto': 'Blöcke in Python',
  'errori.py-sintassi.etichetta': 'Zeile, die Python nicht lesen kann',
  'errori.py-sintassi.frase': 'vielleicht fehlt ein Komma',
  'errori.py-sintassi.frase-2': 'Python kann diese Zeile nicht lesen',
  'errori.py-sintassi.dove': `Sieh dir {laRiga} an: Das Zeichen \`^\` unter der Zeile zeigt, wo Python das Problem bemerkt hat. Oft liegt der eigentliche Fehler kurz davor, auch in der Zeile darüber (eine nicht geschlossene Klammer oder ein Anführungszeichen).`,
  'errori.py-sintassi.cosa': 'Zwischen zwei Werten einer Liste, eines Tupels oder den Argumenten einer Funktion braucht es ein Komma: `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'Python liest den Code nach festen Regeln, wie die Grammatik einer Sprache. Hier hat es etwas gefunden, das an dieser Stelle nicht stehen darf. Die Originalmeldung nach `SyntaxError:` sagt, was nicht passt.',
  'errori.py-sintassi.concetto': 'Syntax',
  'errori.py-nome.etichetta': 'Name, den es nicht gibt',
  'errori.py-nome.breve-2': 'Name',
  'errori.py-nome.breve': `{nome} nicht definiert`,
  'errori.py-nome.frase-2': 'dieser Name',
  'errori.py-nome.frase': `{nome} existiert noch nicht, wenn Python in Zeile {riga} ankommt`,
  'errori.py-nome.frase-senza-riga': `{nome} existiert noch nicht, wenn Python in der markierten Zeile ankommt`,
  'errori.py-nome.dove': `Python schlägt {s} vor: Prüf, ob du das schreiben wolltest. `,
  'errori.py-nome.dove-3': 'diesem Namen',
  'errori.py-nome.dove-2': `Such, wo du {nome} einen Wert gibst: Das muss über dieser Zeile stehen und genau gleich geschrieben sein, auch in Groß- und Kleinschreibung. Wenn es eine Funktion ist, muss die \`def\` vor dem Aufruf kommen.`,
  'errori.py-nome.cosa': 'In Python gibt es einen Namen erst, nachdem du ihm einen Wert gegeben hast (`x = ...`), nach seiner `def` oder nach dem `import`. Variablen, die in einer Funktion entstehen, gibt es außerhalb nicht.',
  'errori.py-nome.cosa-2': ' Achtung: In Python schreibt man `True`, `False` und `None` groß.',
  'errori.py-nome.cosa-3': ` Wenn {nome} ein Text sein sollte, fehlen die Anführungszeichen: {nome2}.`,
  'errori.py-nome.concetto': 'Variablen in Python',
  'errori.py-locale.etichetta': 'lokale Variable ohne Wert',
  'errori.py-locale.frase-2': 'eine Variable',
  'errori.py-locale.frase': `du benutzt {nome} in der Funktion, bevor sie einen Wert hat`,
  'errori.py-locale.dove-2': 'die Variable',
  'errori.py-locale.dove': `Sieh dir {laRiga} an und such in derselben Funktion, wo du {nome} zuweist.`,
  'errori.py-locale.cosa': 'Wenn du in einer Funktion einer Variablen einen Wert zuweist, ist sie für Python in der ganzen Funktion lokal, auch in den Zeilen davor. Dann liest Python nicht mehr die gleichnamige Variable von außen. Besser: Übergib den Wert als Parameter und gib das Ergebnis mit `return` zurück.',
  'errori.py-locale.concetto': 'Funktionen und lokale Variablen',
  'errori.py-tipo-concatena.etichetta': 'Text und Zahl vermischt',
  'errori.py-tipo-concatena.frase': 'du vermischst einen Text (`str`) und eine Zahl',
  'errori.py-tipo-concatena.frase-2': `die Operation geht nicht zwischen {a} und {b}`,
  'errori.py-tipo-concatena.dove': `Sieh dir {laRiga} an: Welchen Typ hat jeder Wert neben dem Operator?`,
  'errori.py-tipo-concatena.cosa': 'Für Python sind `"5"` (Text) und `5` (Zahl) verschiedene Dinge. Um Text und Zahl zu verbinden, wandle die Zahl um: `"Summe: " + str(x)`, oder nimm einen f-String: `f"Summe: {x}"`. Wenn der Wert aus `input()` kommt: `input()` gibt immer Text zurück, zum Rechnen brauchst du `int(input())` oder `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'Typen in Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` falsch benutzt',
  'errori.py-tipo-indice.frase': 'der Index muss eine Ganzzahl sein',
  'errori.py-tipo-indice.frase-2': `einen \`{immut}\`-Wert kann man nicht ändern`,
  'errori.py-tipo-indice.frase-3': 'du benutzt `[ ]` auf einem `None`-Wert',
  'errori.py-tipo-indice.frase-4': `du benutzt \`[ ]\` auf einem Wert vom Typ {p}, der keine Elemente hat`,
  'errori.py-tipo-indice.dove': `Sieh dir die eckigen Klammern {allaRiga} an.`,
  'errori.py-tipo-indice.cosa': 'Bei `v[i]` muss `i` ein `int` sein. Wenn es aus `input()` kommt, ist es Text: Wandle es mit `int()` um. Wenn es aus einer Division mit `/` kommt, ist es ein `float`: Nimm `//`.',
  'errori.py-tipo-indice.cosa-2': 'Strings und Tupel kann man in Python nicht ändern: Man erzeugt einen neuen Wert, zum Beispiel `s = "C" + s[1:]`. Wenn du Elemente ändern musst, nimm eine Liste.',
  'errori.py-tipo-indice.cosa-3': 'Eckige Klammern `[ ]` sind für Listen, Strings, Dictionaries und Tupel. Eine Zahl hat keine Elemente. Wenn der Typ `NoneType` ist, ist die Variable `None`: Oft ist das das Ergebnis einer Funktion ohne `return`.',
  'errori.py-tipo-indice.concetto': 'Listen und Indizes',
  'errori.py-tipo-argomenti.etichetta': 'falsche Anzahl Argumente',
  'errori.py-tipo-argomenti.frase-2': 'funktion',
  'errori.py-tipo-argomenti.frase': `{p} wird mit der falschen Anzahl Argumente aufgerufen`,
  'errori.py-tipo-argomenti.dove': `Vergleich den Aufruf {allaRiga} mit der \`def\`-Zeile der Funktion.`,
  'errori.py-tipo-argomenti.cosa': 'Eine Funktion ruft man mit so vielen Argumenten auf, wie ihre `def` Parameter hat. Bei Methoden einer Klasse ist der erste Parameter `self`, und Python übergibt ihn selbst: Wenn da „takes 1 positional argument but 2 were given“ steht, fehlt vielleicht `self` in der `def`.',
  'errori.py-tipo-argomenti.concetto': 'Funktionen und Parameter',
  'errori.py-non-iterabile.etichetta': '`for` über eine Zahl',
  'errori.py-non-iterabile.frase': `du versuchst, einen Wert vom Typ {p} zu durchlaufen, der keine Elemente hat`,
  'errori.py-non-iterabile.dove': `Sieh dir {laRiga} an: Was steht nach \`in\`?`,
  'errori.py-non-iterabile.cosa': 'Das `for` durchläuft die Elemente einer Liste, eines Strings oder eines `range`. Eine Zahl hat keine Elemente: Um etwas n-mal zu wiederholen, schreibt man `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'for-Schleifen',
  'errori.py-non-chiamabile.etichetta': '`( )` nach etwas, das keine Funktion ist',
  'errori.py-non-chiamabile.frase': `du setzt \`( )\` hinter einen Wert vom Typ {p}, der keine Funktion ist`,
  'errori.py-non-chiamabile.dove': `Sieh dir {laRiga} an: Was steht direkt vor den runden Klammern?`,
  'errori.py-non-chiamabile.cosa': 'Runde Klammern nach einem Namen heißen „ruf diese Funktion auf“. Oft hat eine Variable denselben Namen wie eine Funktion (zum Beispiel `sum = 0` und danach `sum(v)`), oder ein Operator fehlt: `2(x + 1)` statt `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'Funktionen',
  'errori.py-tipo.etichetta': 'falscher Typ',
  'errori.py-tipo.frase': 'eine Operation bekommt einen Wert vom falschen Typ',
  'errori.py-tipo.dove': `Sieh dir {laRiga} an: Welchen Typ haben die benutzten Werte? Du kannst sie mit \`print(type(x))\` ausgeben.`,
  'errori.py-tipo.cosa': 'Jeder Wert in Python hat einen Typ (`int`, `str`, `list`…), und jede Operation akzeptiert nur bestimmte Typen. Die Originalmeldung sagt, welche Typen sie gefunden hat.',
  'errori.py-tipo.concetto': 'Typen in Python',
  'errori.py-indice.etichetta': 'Position, die es nicht gibt',
  'errori.py-indice.frase': 'du nimmst ein Element aus einer leeren Liste',
  'errori.py-indice.frase-stringa': 'du liest eine Position, die der String nicht hat',
  'errori.py-indice.frase-tupla': 'du liest eine Position, die das Tupel nicht hat',
  'errori.py-indice.frase-lista': 'du liest eine Position, die die Liste nicht hat',
  'errori.py-indice.dove': `Sieh dir {laRiga} an: Welchen Wert hat der Index in dem Moment, und wie viele Elemente gibt es?`,
  'errori.py-indice.cosa': 'Eine Liste mit n Elementen hat die Positionen `0` bis `n-1`: Bei 3 Elementen ist die letzte `v[2]`. Das passiert oft mit `range(len(v) + 1)` oder einer Schleife, die einen Schritt zu weit geht. Eine leere Liste hat gar keine Position: Auch `v[0]` ist ein Fehler.',
  'errori.py-indice.concetto': 'Listen und Indizes',
  'errori.py-chiave.etichetta': 'Schlüssel, den es nicht gibt',
  'errori.py-chiave.frase': `der Schlüssel {k} ist nicht im Dictionary`,
  'errori.py-chiave.frase-2': 'der Schlüssel ist nicht im Dictionary',
  'errori.py-chiave.dove': `Sieh dir {laRiga} an: Wie ist der Schlüssel geschrieben, und wie die im Dictionary?`,
  'errori.py-chiave.cosa': 'Bei `d[k]` muss der Schlüssel schon existieren. Prüf, wie er geschrieben ist (Großbuchstaben, Leerzeichen, Zahl oder Text). Zum vorherigen Prüfen: `if k in d:`. Für einen Ersatzwert: `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'Dictionaries',
  'errori.py-valore.etichetta': 'falscher Wert',
  'errori.py-valore.frase': `{v} lässt sich nicht in eine Zahl umwandeln`,
  'errori.py-valore.frase-2': 'links von `=` stehen nicht so viele Variablen, wie es Werte gibt',
  'errori.py-valore.frase-3': 'eine mathematische Funktion bekommt einen Wert, den sie nicht akzeptiert',
  'errori.py-valore.frase-4': 'der Typ stimmt, aber der Wert nicht',
  'errori.py-valore.dove': `Sieh dir {laRiga} an: Welcher Wert kommt dort wirklich an? Du kannst ihn mit \`print(repr(x))\` ausgeben.`,
  'errori.py-valore.cosa': '`int()` wandelt nur einen Text aus Ziffern in eine Zahl um. Leerzeichen in der Mitte, Buchstaben, ein leerer Text oder eine Zahl mit Komma (`"2,5"`) gehen nicht. Für Dezimalzahlen brauchst du `float()` und den Punkt: `"2.5"`. Wenn du aus `input()` oder einer Datei liest, prüf, was wirklich ankommt.',
  'errori.py-valore.cosa-2': 'Bei `a, b = werte` muss die Zahl der Variablen links gleich der Zahl der Werte rechts sein. Oft gibt `split()` mehr (oder weniger) Teile zurück, als du erwartet hast.',
  'errori.py-valore.cosa-3': 'Funktionen wie `math.sqrt` und `math.log` akzeptieren nicht alle Zahlen: keine Wurzel aus einer negativen Zahl, kein Logarithmus von null. Prüf den Wert vor dem Aufruf.',
  'errori.py-valore.cosa-4': 'Der Wert hat den richtigen Typ, passt aber nicht zu dieser Operation. Die Originalmeldung sagt, welcher Wert nicht gepasst hat.',
  'errori.py-valore.concetto': 'Umwandlungen und Eingabe',
  'errori.py-divisione-zero.etichetta': 'Division durch null',
  'errori.py-divisione-zero.frase': 'du teilst durch null',
  'errori.py-divisione-zero.dove': `Sieh dir {laRiga} an: Welcher Divisor ist in dem Moment 0? Oft ist es \`len()\` einer leeren Liste oder ein Zähler, der bei 0 geblieben ist.`,
  'errori.py-divisione-zero.cosa': 'Durch null zu teilen hat kein Ergebnis, also bricht Python ab. Das gilt auch für `//` und `%`. Prüf vor der Division den Divisor: `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'Division',
  'errori.py-attributo.etichetta': 'Methode oder Attribut, das es nicht gibt',
  'errori.py-attributo.frase': `die Variable ist \`None\`, also hat sie kein {a}`,
  'errori.py-attributo.frase-2': `das Modul {mod} hat kein {a}`,
  'errori.py-attributo.frase-3': `ein Wert vom Typ {p} hat kein {a}`,
  'errori.py-attributo.frase-4': 'dieser Wert hat dieses Attribut nicht',
  'errori.py-attributo.dove': `Sieh dir {laRiga} an: Was steht vor dem Punkt, und welchen Typ hat es?`,
  'errori.py-attributo.cosa': 'Ein `None`-Wert kommt meist aus einer Funktion ohne `return` oder aus Methoden wie `v.sort()`, die die Liste ändern und `None` zurückgeben (also verliert `v = v.sort()` die Liste).',
  'errori.py-attributo.cosa-2': 'Prüf, wie der Name geschrieben ist. Wenn deine Datei so heißt wie das Modul (zum Beispiel `random.py` oder `math.py`), importiert Python deine Datei statt des echten Moduls: Benenn sie um.',
  'errori.py-attributo.cosa-3': 'Jeder Typ hat seine eigenen Methoden: Listen haben `append`, `pop`, `sort`; Strings haben `upper`, `split`, `strip`. Prüf den Namen der Methode und den Typ der Variablen.',
  'errori.py-attributo.concetto': 'Methoden und Typen',
  'errori.py-ricorsione.etichetta': 'endlose Rekursion',
  'errori.py-ricorsione.frase': 'die Funktion ruft sich zu oft selbst auf',
  'errori.py-ricorsione.dove': `Sieh dir die Funktion{funzione} {allaRiga} an: Wo ist der Basisfall, und kommt jeder Aufruf ihm näher?`,
  'errori.py-ricorsione.cosa': 'Jede rekursive Funktion braucht einen Basisfall: eine Bedingung, bei der sie einen Wert zurückgibt, ohne sich nochmal aufzurufen. Und jeder Aufruf muss dem Basisfall näher kommen (zum Beispiel `n - 1`, nicht `n + 1`). Python bricht nach etwa 1000 ineinander verschachtelten Aufrufen ab.',
  'errori.py-ricorsione.concetto': 'Rekursion',
  'errori.py-modulo.etichetta': 'Modul, das es nicht gibt',
  'errori.py-modulo.frase': `im Modul {m} gibt es kein {nome}`,
  'errori.py-modulo.frase-2': `das Modul {m} gibt es nicht`,
  'errori.py-modulo.frase-3': 'ein Modul lässt sich nicht importieren',
  'errori.py-modulo.dove': `Sieh dir die \`import\`-Zeile {allaRiga} an.`,
  'errori.py-modulo.cosa': 'Entweder ist der Name falsch geschrieben, oder das Modul ist für dieses Python nicht installiert. Externe Module (zum Beispiel `numpy`) installiert man mit `python3 -m pip install name` (unter Windows `py -m pip install name`). Wenn das Modul eine eigene Datei ist, muss sie im selben Ordner liegen und `name.py` heißen.',
  'errori.py-modulo.concetto': 'Module und import',
  'errori.py-file.etichetta': 'Datei nicht gefunden',
  'errori.py-file.frase': `ich finde die Datei {p} nicht`,
  'errori.py-file.dove': `Sieh dir das \`open\` {allaRiga} an.`,
  'errori.py-file.cosa': 'Python sucht die Datei ausgehend von dem Ordner, aus dem du das Programm startest, nicht von dem des Skripts. Prüf den Namen, die Endung (Windows versteckt sie manchmal) und den Ordner.',
  'errori.py-file.concetto': 'Dateien',
  'errori.py-input-finito.etichetta': 'Eingabe zu Ende',
  'errori.py-input-finito.frase': 'das Programm will eine Eingabe, die nicht kommt',
  'errori.py-input-finito.dove': `Sieh dir das \`input()\` {allaRiga} an.`,
  'errori.py-input-finito.cosa': '`input()` hat auf eine Zeile gewartet, aber die Eingabe war schon zu Ende. Bei Tests mit `.in`-Dateien prüf, ob die Datei so viele Zeilen hat, wie es `input()` gibt.',
  'errori.py-input-finito.concetto': 'Eingabe',
  'errori.esec-memoria.etichetta': 'fremder Speicher (Segmentation Fault)',
  'errori.esec-memoria.breve': 'fremder Speicher',
  'errori.esec-memoria.frase': 'das Programm hat Speicher benutzt, der ihm nicht gehört',
  'errori.esec-memoria.cosa': 'Hier war der Zeiger `NULL`. ',
  'errori.esec-memoria.cosa-2': 'Oft ist es ein `NULL`-Zeiger (`p->next`, wenn `p` `NULL` ist), ein Index außerhalb des Arrays oder eine endlose Rekursion. Das System stoppt das Programm, um den restlichen Speicher zu schützen.',
  'errori.esec-memoria.cosa-3': ` Unter Windows hat dieser Fehler den Code {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'Zeiger und Speicher',
  'errori.esec-divisione-zero.etichetta': 'Ganzzahldivision durch null',
  'errori.esec-divisione-zero.frase': 'das Programm hat eine Ganzzahl durch null geteilt',
  'errori.esec-divisione-zero.cosa': 'Eine Ganzzahl durch null geteilt (auch mit `%`) hat kein Ergebnis, und das System stoppt das Programm. Der Name „floating point exception“ täuscht: Es passiert gerade mit Ganzzahlen. Prüf die Divisoren, zum Beispiel einen Zähler, der noch 0 ist.',
  'errori.esec-divisione-zero.concetto': 'Division',
  'errori.esec-stack.etichetta': 'Aufrufstapel voll (Stack Overflow)',
  'errori.esec-stack.frase': 'der Aufrufstapel ist voll: Vielleicht eine endlose Rekursion',
  'errori.esec-stack.cosa': 'Jeder Funktionsaufruf belegt etwas Speicher auf dem Stapel (dem Stack). Eine rekursive Funktion ohne Basisfall, oder mit einem Basisfall, der nie erreicht wird, füllt ihn. Auch ein riesiges lokales Array kann reichen: Nimm in dem Fall `malloc`.',
  'errori.esec-stack.concetto': 'Rekursion',
  'errori.esec-fuori-array.etichetta': 'Schreiben außerhalb eines Arrays',
  'errori.esec-fuori-array.frase': 'das Programm hat außerhalb eines Arrays gelesen oder geschrieben',
  'errori.esec-fuori-array.frase-letto': 'das Programm hat außerhalb eines Arrays gelesen',
  'errori.esec-fuori-array.frase-scritto': 'das Programm hat außerhalb eines Arrays geschrieben',
  'errori.esec-fuori-array.cosa': 'Ein Array mit N Elementen geht von `0` bis `N-1`. Prüf die Bedingungen der Schleifen (`<` und nicht `<=`), Strings ohne Platz für die abschließende `\'\\0\'` und `malloc` mit der richtigen Größe (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'Arrays und Indizes',
  'errori.esec-heap.etichetta': 'malloc und free falsch benutzt',
  'errori.esec-heap.frase': 'der mit `malloc` geholte Speicher wurde falsch benutzt',
  'errori.esec-heap.cosa': 'Das passiert, wenn du denselben Speicher zweimal freigibst (zweimal `free`), wenn du einen Zeiger nach `free` benutzt oder wenn du über das Ende eines mit `malloc` geholten Blocks schreibst. Nach `free(p);` hilft es, `p = NULL;` zu schreiben.',
  'errori.esec-heap.concetto': 'dynamischer Speicher',
  'errori.esec-memoria-persa.etichetta': 'Speicher nie freigegeben',
  'errori.esec-memoria-persa.frase': 'das Programm holt Speicher mit `malloc` und gibt ihn nicht frei',
  'errori.esec-memoria-persa.cosa': 'Jedes `malloc` (oder `calloc`) braucht sein `free`, wenn der Speicher nicht mehr gebraucht wird. Bei Listen gibst du jeden Knoten einzeln frei, bevor du den Zeiger verlierst.',
  'errori.esec-memoria-persa.concetto': 'dynamischer Speicher',
  'errori.esec-non-inizializzata.etichetta': 'Wert nie initialisiert',
  'errori.esec-non-inizializzata.frase': 'das Programm benutzt einen Wert, der nie initialisiert wurde',
  'errori.esec-non-inizializzata.cosa': 'Eine lokale Variable (oder mit `malloc` geholter Speicher) enthält zufällige Werte, bis du ihr einen Wert gibst. Initialisier sie, bevor du sie liest.',
  'errori.esec-non-inizializzata.concetto': 'Initialisierung von Variablen',
  'errori.esec-asserzione.etichetta': 'assert fehlgeschlagen',
  'errori.esec-asserzione.frase': `ein \`assert\` ist fehlgeschlagen: {cond} war falsch`,
  'errori.esec-asserzione.frase-2': 'ein `assert` ist fehlgeschlagen',
  'errori.esec-asserzione.cosa': '`assert(bedingung)` stoppt das Programm, wenn die Bedingung falsch ist. Wer es geschrieben hat (du oder die Lehrperson), sagt damit: „Hier muss das immer wahr sein.“ Das eigentliche Problem liegt davor: Such, wo der Wert falsch geworden ist.',
  'errori.esec-asserzione.concetto': 'assert und Prüfungen',
  'errori.esec-abort.etichetta': 'Programm abgebrochen (abort)',
  'errori.esec-abort.frase': 'das Programm hat sich selbst abgebrochen (abort)',
  'errori.esec-abort.cosa': 'Meist verlangt das die Bibliothek, wenn sie ein schweres Problem findet: ein fehlgeschlagenes `assert`, ein falsches `free`, beschädigten Speicher. Sieh dir die Zeilen an, die direkt davor ausgegeben wurden: Oft steht dort der Grund.',
  'errori.esec-abort.concetto': 'dynamischer Speicher',
  'errori.esec-overflow.etichetta': 'Ganzzahl zu groß',
  'errori.esec-overflow.frase': 'eine Ganzzahl ist zu groß geworden',
  'errori.esec-overflow.cosa': 'Ein `int` geht bis 2147483647. Darüber ist das Ergebnis falsch. Das passiert bei Fakultäten und Potenzen: Nimm `long long` (mit `%lld` in `printf`) oder prüf die Rechnung.',
  'errori.esec-overflow.concetto': 'Ganzzahltypen',
  'errori.esec-tempo.etichetta': 'Zeit abgelaufen',
  'errori.esec-tempo.frase': 'das Programm ist nicht rechtzeitig fertig geworden',
  'errori.esec-tempo.cosa': 'Vielleicht gibt es eine Schleife, die nicht endet: Die Bedingung wird nie falsch, oder die Schleifenvariable ändert sich nicht. Oder das Programm wartet auf eine Eingabe (`scanf`, `input()`), die nicht kommt.',
  'errori.esec-tempo.concetto': 'Schleifen',
  'errori.esec-segnale.etichetta': 'Programm vom System gestoppt',
  'errori.esec-segnale.frase': `das Programm wurde vom System gestoppt{segnale}`,
  'errori.esec-segnale.cosa': 'Das System hat das Programm gestoppt, während es lief. Mehr kann Lode aus diesem Signal nicht sagen: Sieh dir die letzten ausgegebenen Zeilen und die kürzlich geänderten Zeilen an.',
  'errori.esec-segnale.concetto': 'Ausführung',
  // ---- fuori dal dizionario: luoghi, conti, passi, correzioni, scheda ----
  'errori.tempo-scaduto': 'Zeit abgelaufen',
  'errori.segnale': 'Signal {sig}',
  'errori.codice-uscita': `Exit-Code {codice}`,
  'errori.codice-uscita-windows': `Exit-Code {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'ein weiterer Fehler', other: '{n} weitere Fehler' },
  'errori.avvisi': { one: '1 Warnung', other: '{n} Warnungen' },
  'errori.conto': 'und {cosa}',
  'errori.conto-errori-e-avvisi': 'und {errori} und {avvisi}',
  'errori.un-nome': 'einen Namen',
  'errori.alla-riga': 'in Zeile {n}',
  'errori.nel-punto-indicato': 'an der markierten Stelle',
  'errori.la-riga': 'Zeile {n}',
  'errori.il-punto-indicato': 'die markierte Stelle',
  'errori.colonna': ', Spalte {n}',
  'errori.del-if': 'des `if`',
  'errori.del-while': 'des `while`',
  'errori.del-for': 'des `for`',
  'errori.sconosciuto': 'unbekannter Fehler',
  'errori.errore': 'Fehler',
  'errori.nella-funzione': ', in der Funktion {funzione}',
  'errori.di-file': ' von {file}',
  'errori.fermato-alla-riga': 'Das Programm ist in Zeile {riga}{file}{funzione} stehen geblieben.',
  'errori.poi-guarda-cambiate': ` Sieh dir danach die Zeilen an, die sich seit dem letzten erfolgreichen Test geändert haben: {righe}.`,
  'errori.guarda-prima-cambiate': `Sieh dir zuerst die Zeilen an, die sich seit dem letzten erfolgreichen Test geändert haben: {righe}.`,
  'errori.sistema-senza-riga': 'Das System nennt keine Zeile. Füg ein paar `printf` ein, um zu sehen, wie weit das Programm kommt; auf Mac und Linux kannst du auch mit `-g -fsanitize=address` kompilieren, dann bekommst du Datei und Zeile.',
  'errori.messaggio-senza-riga': 'Die Meldung nennt keine Zeile: Sieh dir die letzten Zeilen an, die das Programm ausgegeben hat.',
  'errori.cambiate-e-altre': { one: '{righe} und {n} weitere', other: '{righe} und {n} weitere' },
  'errori.correggi-punto': `Setz \`;\` ans Ende der Anweisung: in Zeile {riga} oder in der davor.`,
  'errori.correggi-punto-senza-riga': 'Setz `;` ans Ende der Anweisung.',
  'errori.correggi-punto-fine': `Setz ans Ende von Zeile {riga} ein \`;\`:`,
  'errori.correggi-punto-dentro': `Setz in Zeile {riga}, an der markierten Stelle, ein \`;\`:`,
  'errori.correggi-include-in-cima': 'Füg oben in der Datei, bei den anderen `#include`, hinzu:',
  'errori.correggi-include-dopo': 'Füg nach Zeile {riga} hinzu:',
  'errori.correggi-include-primo': 'Füg oben in der Datei hinzu:',
  'errori.correggi-uguale': 'Ersetz in der Bedingung `=` durch `==`.',
  'errori.correggi-uguale-riga': `Ersetz in Zeile {riga} \`=\` durch \`==\`:`,
  'errori.correggi-return': `Füg vor der \`}\`, die {nome} schließt, ein \`return\` mit dem richtigen Wert für die übrigen Fälle hinzu. Welcher Wert, entscheidest du: Das hängt davon ab, was die Funktion berechnen soll.`,
  'errori.correggi-return-senza-nome': `Füg vor der \`}\`, die die Funktion schließt, ein \`return\` mit dem richtigen Wert für die übrigen Fälle hinzu. Welcher Wert, entscheidest du: Das hängt davon ab, was die Funktion berechnen soll.`,
  'errori.generico.dove-linker': 'Der Linker nennt keine Zeile: Such im Projekt den Namen aus der Meldung und prüf, ob alle `.c`-Dateien im Compiler-Befehl stehen.',
  'errori.generico.dove-senza-riga': 'Die Meldung nennt keine Zeile: Lies den Originaltext hier unten.',
  'errori.generico.dove-python': '{L} ist {allaRiga}{file} stehen geblieben. Wenn dort alles richtig aussieht, sieh dir die Zeile davor an.',
  'errori.generico.dove': 'Sieh dir {laRiga}{colonna}{file} an. Wenn dort alles richtig aussieht, sieh dir auch die Zeile davor an: Oft merkt der Compiler ein Problem erst danach.',
  'errori.generico.eccezione-leggendo': '{eccezione} ist die Art Fehler, auf die {L} beim Lesen des Programms gestoßen ist. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} ist die Art Fehler, auf die {L} beim Ausführen des Programms gestoßen ist. ',
  'errori.generico.cosa': 'Für diese Meldung hat Lode noch keine Erklärung. Der Originaltext steht hier unten: Lies die Wörter in Anführungszeichen, meist sind sie der Name oder der Typ, der Probleme macht.',
  'errori.catena': ' So bist du dort gelandet: {passi}.',
  'errori.catena-passo': 'Zeile {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, Zeile {riga}',
  'errori.luogo-riga': 'Zeile {riga}',
  'errori.con-eccezione': '{eccezione}: {frase}',
  'errori.intestazione': '**{luogo}**: {frase}',
  'errori.intestazione-eccezione': '**{luogo}** · {frase}',
  'errori.per-diario': '{dove}„{breve}“',
  'errori.non-lo-conosco': 'diesen Fehler kenne ich noch nicht',
  'errori.parola-avviso': 'Warnung',
  'errori.e-un-avviso': `Das ist eine Warnung: Das Programm kompiliert trotzdem, macht aber so, wie es ist, wahrscheinlich nicht, was du willst. {cosa}`,
  'errori.passo-dove': 'Wo nachsehen',
  'errori.passo-cosa': 'Was es bedeutet',
  'errori.passo-correzione': 'Zeig mir die Korrektur',
  'errori.file-cambiato': 'Die Datei hat sich seitdem geändert: Die Zeilennummern stimmen vielleicht nicht mehr.',
  'errori.tipo-errore': 'Fehler',
  'errori.tipo-avviso': 'Warnung',
  'errori.tipo-linker': 'Linker-Fehler',
  'errori.tipo-esecuzione': 'Abgebrochen',
  'errori.segnaposto-valore': '‹wert›',
  'errori.correzione-vista': 'Korrektur angesehen',
  'errori.messaggio-originale': 'Originalmeldung',
};
