// Beispieldaten (esempio() in js/dati.js) und die Wörter, die die Programme von «Cosa stampa?» ausgeben. Gleiche Form wie it/esempio.js.
export default {
  'esempio.nome': 'Lena',
  'esempio.corso': 'Informatik',
  'esempio.esami': ['Mathematik 1', 'Grundlagen der Programmierung', 'Lineare Algebra', 'Physik 1', 'Englisch B2', 'Objektorientierte Programmierung', 'Mathematik 2', 'Datenbanksysteme', 'Physik 2'],
  'esempio.aule': ['HS 1', 'PC-Pool 2', 'Audimax'],
  'esempio.carte': [
    ['Was ist der Gradient von f(x, y)?', 'Der Vektor der partiellen Ableitungen (∂f/∂x, ∂f/∂y): Er zeigt in die Richtung des stärksten Anstiegs.'],
    ['Formuliere den Satz von Schwarz', 'Sind die gemischten zweiten partiellen Ableitungen in einer Umgebung stetig, dann gilt f_xy = f_yx.'],
    ['Bedingung für einen kritischen Punkt', 'Der Gradient verschwindet: ∇f(x₀) = 0.'],
    ['Wie klassifiziert man einen kritischen Punkt?', 'Mit der Hesse-Matrix: positiv definit → Minimum, negativ definit → Maximum, indefinit → Sattelpunkt.'],
    ['Was ist ein Doppelintegral über einem Normalbereich?', 'Ein iteriertes Integral: zuerst über die „innere“ Variable, mit Grenzen, die von der anderen abhängen, dann über die andere.'],
    ['Satz von Green: Aussage', 'Das Kurvenintegral von P dx + Q dy über ∂D ist gleich dem Doppelintegral über D von (∂Q/∂x − ∂P/∂y).'],
    ['Exakte Differentialform: Definition', 'ω ist exakt, wenn es eine Funktion U (ein Potential) mit dU = ω gibt.'],
    ['Geometrische Reihe: Wann konvergiert sie?', 'Für |q| < 1, mit der Summe 1/(1 − q).'],
    ['Was ist ein Primärschlüssel?', 'Eine minimale Menge von Attributen, die jedes Tupel einer Relation eindeutig identifiziert.'],
    ['Unterschied zwischen LEFT JOIN und INNER JOIN', 'Der LEFT JOIN behält alle Zeilen der linken Tabelle, auch ohne Partner (mit NULL); der INNER JOIN nur die passenden Paare.'],
    ['Was garantiert die dritte Normalform?', 'Dass jedes Nichtschlüsselattribut vom Schlüssel abhängt, vom ganzen Schlüssel und von nichts anderem als dem Schlüssel (keine transitiven Abhängigkeiten).'],
  ],
  'esempio.domande': ['Warum braucht der Satz von Schwarz die Stetigkeit der gemischten Ableitungen?'],
  'esempio.stelle': ['Der Satz von Green kommt in jeder Klausur dran, mit Beweis', 'Kritische Punkte klassifizieren: Diese Aufgabe kommt sicher dran'],
  'esempio.stelle-basi': ['Normalisierung bis zur BCNF: kommt in jeder Klausur'],
  'esempio.definizioni': [
    ['Gradient', 'Der Vektor der partiellen Ableitungen von f: Er zeigt in die Richtung des stärksten Anstiegs.'],
    ['Kritischer Punkt', 'Ein Punkt, an dem der Gradient der Funktion verschwindet.'],
    ['Hesse-Matrix', 'Die quadratische Matrix der zweiten partiellen Ableitungen einer Funktion.'],
    ['Sattelpunkt', 'Ein kritischer Punkt, der weder lokales Maximum noch lokales Minimum ist: Die Hesse-Matrix ist indefinit.'],
    ['Satz von Green', 'Er verbindet das Kurvenintegral entlang des Randes eines Gebiets mit dem Doppelintegral über das Gebiet.'],
    ['Exakte Differentialform', 'Eine Form, die ein Potential besitzt, also das Differential einer Funktion ist.'],
  ],
  'esempio.definizioni-basi': [
    ['Primärschlüssel', 'Eine minimale Menge von Attributen, die jedes Tupel eindeutig identifiziert.'],
    ['Fremdschlüssel', 'Ein Attribut, das auf den Primärschlüssel einer anderen Relation verweist.'],
    ['Funktionale Abhängigkeit', 'Eine Bedingung, bei der die Werte einer Attributmenge die Werte einer anderen bestimmen.'],
    ['Boyce-Codd-Normalform', 'Jede nichttriviale funktionale Abhängigkeit hat auf der linken Seite einen Superschlüssel.'],
  ],
  'esempio.switch-parole': ['eins', 'zwei', 'drei', 'vier'],
  'esempio.switch-altro': 'sonst',
  'esempio.si': 'ja',
  'esempio.no': 'nein',
  'esempio.hai-scritto': 'Du hast `{s}` geschrieben',
};
