// «Neues», das feste Wörterbuch der Standardbibliothek (Deutsch): zu jedem Eintrag die Prüfungsfrage
// und die Antwort. Die Funktionsnamen und die Regeln, die sie im Code suchen, bleiben in js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': 'Was steht in dem Speicher, den malloc gerade zurückgegeben hat?',
  'glossario.malloc.risposta': 'Zufällige Werte: malloc setzt ihn nicht auf null. Wenn kein Speicher mehr da ist, gibt es NULL zurück, also prüft man das vor der Benutzung.',
  'glossario.calloc.domanda': 'Was ist der Unterschied zwischen calloc(n, size) und malloc(n * size)?',
  'glossario.calloc.risposta': 'calloc setzt alle Bytes auf null, malloc lässt zufällige Werte stehen. Wenn kein Speicher da ist, geben beide NULL zurück.',
  'glossario.realloc.domanda': 'Was macht realloc, wenn es fehlschlägt?',
  'glossario.realloc.risposta': 'Es gibt NULL zurück, und der alte Block bleibt gültig: Den musst du separat freigeben. Deshalb schreibt man p2 = realloc(p, n) und nicht p = realloc(p, n).',
  'glossario.free.domanda': 'Was passiert, wenn du einen Zeiger nach free benutzt?',
  'glossario.free.risposta': 'Das ist undefiniertes Verhalten: Der Speicher gehört dir nicht mehr. Ihn zweimal freizugeben auch. free(NULL) dagegen macht gar nichts.',
  'glossario.strtok.domanda': 'Warum kann man strtok nicht auf ein String-Literal anwenden?',
  'glossario.strtok.risposta': 'Weil es in den String schreibt: An jede Trennstelle setzt es \'\\0\'. Ab dem zweiten Aufruf übergibt man NULL, und strtok macht an der Stelle weiter, die es sich gemerkt hat.',
  'glossario.strcpy.domanda': 'Was prüft strcpy an der Größe des Ziels?',
  'glossario.strcpy.risposta': 'Nichts: Es kopiert bis einschließlich \'\\0\'. Ist das Ziel zu klein, schreibt es über das Ende des Arrays hinaus, und das ist undefiniertes Verhalten.',
  'glossario.strncpy.domanda': 'Setzt strncpy(d, s, n) immer die abschließende \'\\0\'?',
  'glossario.strncpy.risposta': 'Nein: Hat s n Zeichen oder mehr, steht in d keine \'\\0\'. Ist s kürzer, füllt es den Rest mit Nullen auf.',
  'glossario.strcmp.domanda': 'Was gibt strcmp zurück, wenn die beiden Strings gleich sind?',
  'glossario.strcmp.risposta': '0. Eine negative Zahl, wenn der erste vorher kommt, eine positive, wenn er danach kommt: Deshalb heißt if (strcmp(a, b)) „sie sind verschieden“.',
  'glossario.strlen.domanda': 'Zählt strlen die abschließende \'\\0\' mit?',
  'glossario.strlen.risposta': 'Nein: Es zählt die Zeichen vor der \'\\0\'. Um den String zu kopieren, brauchst du strlen(s) + 1 Bytes.',
  'glossario.strcat.domanda': 'Was braucht strcat(d, s), damit es funktioniert?',
  'glossario.strcat.risposta': 'd muss schon einen String mit \'\\0\' enthalten und Platz für beide haben, plus die \'\\0\'. Den Platz prüft strcat nicht.',
  'glossario.memcpy.domanda': 'Darf man memcpy benutzen, wenn sich Quelle und Ziel überlappen?',
  'glossario.memcpy.risposta': 'Nein, das ist undefiniertes Verhalten. In dem Fall nimmt man memmove.',
  'glossario.memset.domanda': 'Setzt memset(v, 1, n * sizeof(int)) die ints in v auf 1?',
  'glossario.memset.risposta': 'Nein: memset schreibt denselben Wert in jedes Byte, also hat jeder 32-Bit-int den Wert 16843009. Zum Nullsetzen passt es dagegen: memset(v, 0, …).',
  'glossario.sizeof.domanda': 'Was ist sizeof(v), wenn v ein Parameter int v[] ist?',
  'glossario.sizeof.risposta': 'Die Größe eines Zeigers, nicht des Arrays: Als Parameter ist int v[] dasselbe wie int *v. Deshalb übergibt man die Länge extra.',
  'glossario.fgets.domanda': 'Was lässt fgets am Ende der gelesenen Zeile stehen?',
  'glossario.fgets.risposta': 'Den Zeilenumbruch, wenn er noch reingepasst hat, und dann die \'\\0\': Mit fgets(s, n, f) liest es höchstens n - 1 Zeichen. Am Dateiende gibt es NULL zurück.',
  'glossario.scanf.domanda': 'Was gibt scanf zurück?',
  'glossario.scanf.risposta': 'Wie viele Werte es gelesen und zugewiesen hat, oder EOF, wenn die Eingabe vorher endet. Wenn du das nicht prüfst, geht ein Buchstabe statt einer Zahl einfach durch.',
  'glossario.sscanf.domanda': 'Was ist der Unterschied zwischen scanf und sscanf?',
  'glossario.sscanf.risposta': 'sscanf liest aus einem String statt aus der Eingabe. Man nimmt es oft nach fgets: Erst liest du die ganze Zeile, dann zerlegst du sie.',
  'glossario.fopen.domanda': 'Was gibt fopen zurück, wenn sich die Datei nicht öffnen lässt?',
  'glossario.fopen.risposta': 'NULL: Das prüft man, bevor man liest oder schreibt. Achtung: Mit "w" wird eine vorhandene Datei sofort geleert.',
  'glossario.fclose.domanda': 'Was macht fclose bei einer Datei, in die du geschrieben hast?',
  'glossario.fclose.risposta': 'Es schreibt, was noch im Puffer ist, in die Datei und gibt das FILE frei. Nach fclose benutzt man den Zeiger nicht mehr.',
  'glossario.fprintf.domanda': 'Was ist der Unterschied zwischen fprintf(stderr, ...) und printf(...)?',
  'glossario.fprintf.risposta': 'printf schreibt auf stdout, fprintf auf den Stream, den du übergibst. stderr ist meist ungepuffert und landet nicht in der Datei, wenn du die Ausgabe mit > umleitest.',
  'glossario.atoi.domanda': 'Was gibt atoi("hallo") zurück?',
  'glossario.atoi.risposta': '0, ohne jedes Fehlersignal: Du kannst "0" nicht von falschem Text unterscheiden. Zum Prüfen nimmt man strtol.',
  'glossario.strtol.domanda': 'Wofür ist das zweite Argument von strtol?',
  'glossario.strtol.risposta': 'Es ist ein char **, in das strtol die Stelle schreibt, an der es aufgehört hat: Ist das der Anfang, hat es keine Ziffern gelesen. Das dritte Argument ist die Basis.',
  'glossario.qsort.domanda': 'Was muss die Vergleichsfunktion von qsort zurückgeben?',
  'glossario.qsort.risposta': 'Einen negativen int, null oder einen positiven int, wenn das erste Element davor kommt, gleich ist oder danach kommt. Sie bekommt zwei const void *, die man in den richtigen Typ umwandelt.',
  'glossario.exit.domanda': 'Was ist der Unterschied zwischen exit(1) und return 1 in main?',
  'glossario.exit.risposta': 'In main machen sie dasselbe. exit beendet das Programm aber aus jeder Funktion heraus, nachdem es die offenen Dateien geleert und geschlossen hat.',
  'glossario.assert.domanda': 'Was macht assert(x), wenn x falsch ist?',
  'glossario.assert.risposta': 'Es schreibt die Bedingung, die Datei und die Zeile auf stderr und beendet das Programm mit abort. Mit -DNDEBUG verschwinden die asserts: Code, der gebraucht wird, gehört nicht hinein.',
  'glossario.static-locale.domanda': 'Was ändert sich, wenn eine Variable in einer Funktion static ist?',
  'glossario.static-locale.risposta': 'Sie wird nur einmal initialisiert und behält ihren Wert von einem Aufruf zum nächsten. Wenn du sie nicht initialisierst, startet sie bei 0.',
  'glossario.computeifabsent.domanda': 'Was macht map.computeIfAbsent(k, x -> new ArrayList<>())?',
  'glossario.computeifabsent.risposta': 'Wenn k fehlt, erzeugt es die Liste, legt sie in die Map und gibt sie zurück. Wenn k schon da ist, gibt es die vorhandene zurück. So kannst du danach ohne Prüfung .add aufrufen.',
  'glossario.getordefault.domanda': 'Was gibt map.getOrDefault(k, 0) zurück, wenn k fehlt?',
  'glossario.getordefault.risposta': '0, und die Map ändert sich nicht: k wird nicht hinzugefügt.',
  'glossario.putifabsent.domanda': 'Was gibt map.putIfAbsent(k, v) zurück?',
  'glossario.putifabsent.risposta': 'Den Wert, der schon da war, und dann ändert sich die Map nicht. Wenn k fehlte, legt es v ab und gibt null zurück.',
  'glossario.list-remove.domanda': 'Was macht list.remove(1) bei einer List<Integer> mit [5, 7, 9]?',
  'glossario.list-remove.risposta': 'Es entfernt das Element an Position 1, also 7: Mit einem int wird remove(int index) gewählt. Um den Wert 1 zu entfernen, brauchst du list.remove(Integer.valueOf(1)).',
  'glossario.equals.domanda': 'Was ist der Unterschied zwischen == und equals bei zwei Strings?',
  'glossario.equals.risposta': '== prüft, ob es dasselbe Objekt ist, equals, ob sie dieselben Zeichen haben. Zwei gleiche Strings können zwei verschiedene Objekte sein.',
  'glossario.hashcode.domanda': 'Wenn du equals überschreibst, was musst du mit hashCode machen?',
  'glossario.hashcode.risposta': 'Es auch überschreiben: Objekte, die laut equals gleich sind, müssen denselben hashCode haben. Sonst finden HashMap und HashSet sie nicht wieder.',
  'glossario.collections-sort.domanda': 'Ist Collections.sort stabil?',
  'glossario.collections-sort.risposta': 'Ja: Elemente, die beim Vergleich gleich sind, bleiben in ihrer bisherigen Reihenfolge. Es sortiert die Liste an Ort und Stelle und gibt nichts zurück.',
  'glossario.comparator-comparing.domanda': 'Was macht Comparator.comparing(Student::getPunkte).reversed()?',
  'glossario.comparator-comparing.risposta': 'Es vergleicht die Studierenden nach Punkten, umgekehrt: vom höchsten zum niedrigsten Wert. Mit thenComparing fügst du ein zweites Kriterium für gleiche Punkte hinzu.',
  'glossario.optional.domanda': 'Warum ruft man get() auf einem Optional nicht ohne Prüfung auf?',
  'glossario.optional.risposta': 'Wenn es leer ist, wirft get() eine NoSuchElementException. Man nimmt orElse, orElseGet oder isPresent.',
  'glossario.stream.domanda': 'Was passiert, wenn du auf einem Stream nur map und filter aufrufst, ohne collect?',
  'glossario.stream.risposta': 'Nichts: map und filter sind lazy. Die Arbeit startet erst mit einer terminalen Operation wie collect, forEach oder count. Und einen Stream kann man nur einmal benutzen.',
  'glossario.stringbuilder.domanda': 'Warum nimmt man in einer Schleife StringBuilder statt s = s + x?',
  'glossario.stringbuilder.risposta': 'Ein String ändert sich nie: Jedes + erzeugt einen neuen und kopiert alles. StringBuilder hängt am selben Objekt an, und toString() liefert das Ergebnis.',
  'glossario.integer-parseint.domanda': 'Was passiert bei Integer.parseInt("12a")?',
  'glossario.integer-parseint.risposta': 'Es wirft eine NumberFormatException. Auch " 12" mit Leerzeichen wirft sie: Vorher nimmt man trim().',
  'glossario.scanner-nextint.domanda': 'Warum gibt ein nextLine() direkt nach nextInt() eine leere Zeile zurück?',
  'glossario.scanner-nextint.risposta': 'nextInt liest die Zahl, lässt aber den Zeilenumbruch stehen. nextLine liest bis zu diesem Umbruch und gibt "" zurück. Man ruft ein zusätzliches nextLine() auf, um ihn wegzuwerfen.',
  'glossario.try-with-resources.domanda': 'Was macht try (Scanner in = new Scanner(f)) { ... }?',
  'glossario.try-with-resources.risposta': 'Es schließt die Ressource am Ende des Blocks von selbst, auch wenn eine Exception kommt. Das geht mit Klassen, die AutoCloseable implementieren.',
  'glossario.instanceof.domanda': 'Was gibt x instanceof String zurück, wenn x null ist?',
  'glossario.instanceof.risposta': 'false, ohne Exception. Ab Java 16 kannst du x instanceof String s schreiben und s sofort benutzen.',
  'glossario.arrays-aslist.domanda': 'Was passiert, wenn du add auf der Liste von Arrays.asList aufrufst?',
  'glossario.arrays-aslist.risposta': 'Es wirft eine UnsupportedOperationException: Die Liste hat eine feste Größe und hängt am Array. set funktioniert dagegen und ändert auch das Array.',
  'glossario.iterator-remove.domanda': 'Wie entfernst du Elemente aus einer Liste, während du sie durchläufst?',
  'glossario.iterator-remove.risposta': 'Mit einem Iterator und it.remove() oder mit removeIf. Mit list.remove in einer for-each-Schleife kommt meist eine ConcurrentModificationException.',
  'glossario.substring.domanda': 'Was gibt "Vorlesung".substring(1, 4) zurück?',
  'glossario.substring.risposta': '"orl": die Zeichen von Position 1 bis 3. Der zweite Index ist ausgeschlossen, und der ursprüngliche String ändert sich nicht.',
  'glossario.compareto.domanda': 'Was gibt a.compareTo(b) zurück?',
  'glossario.compareto.risposta': 'Eine negative Zahl, wenn a vor b kommt, null, wenn sie gleich sind, eine positive, wenn a danach kommt. Nicht unbedingt -1 oder 1: Es zählt das Vorzeichen.',
  'glossario.list-comprehension.domanda': 'Was baut [x * 2 for x in v if x > 0]?',
  'glossario.list-comprehension.risposta': 'Eine neue Liste mit dem Doppelten der positiven Elemente von v. Das ist eine for-Schleife mit if und append in einer Zeile; v ändert sich nicht.',
  'glossario.list-comprehension-annidata.domanda': 'Welches for ist in [x for riga in m for x in riga] das äußere?',
  'glossario.list-comprehension-annidata.risposta': 'Das erste: Die fors liest man in der Reihenfolge, in der du sie verschachtelt schreiben würdest. Das Ergebnis ist m, flach in einer einzigen Liste.',
  'glossario.lambda.domanda': 'Was darf in einem Lambda in Python stehen?',
  'glossario.lambda.risposta': 'Ein einziger Ausdruck, der zum Rückgabewert wird. Keine Anweisungen wie return, for oder eine normale Zuweisung.',
  'glossario.sorted-con-key.domanda': 'Was macht sorted(v, key=len)?',
  'glossario.sorted-con-key.risposta': 'Es gibt eine neue Liste zurück, nach Länge sortiert; v bleibt, wie es ist. Bei gleicher Länge bleibt die ursprüngliche Reihenfolge: Die Sortierung ist stabil.',
  'glossario.enumerate.domanda': 'Was liefert enumerate(v)?',
  'glossario.enumerate.risposta': 'Die Paare (Index, Element), der Index startet bei 0. Mit enumerate(v, 1) startet er bei 1.',
  'glossario.zip.domanda': 'Was macht zip, wenn die Listen unterschiedlich lang sind?',
  'glossario.zip.risposta': 'Es hört bei der kürzesten auf: Die übrigen Elemente gehen ohne Fehler verloren. Ab Python 3.10 gibt es mit strict=True einen Fehler.',
  'glossario.dict-get.domanda': 'Was ist der Unterschied zwischen d[k] und d.get(k)?',
  'glossario.dict-get.risposta': 'd[k] wirft einen KeyError, wenn k fehlt, d.get(k) gibt None zurück, oder das zweite Argument, wenn du eins übergibst. get fügt k nicht hinzu.',
  'glossario.setdefault.domanda': 'Was macht d.setdefault(k, [])?',
  'glossario.setdefault.risposta': 'Wenn k fehlt, fügt es k mit [] hinzu und gibt diese Liste zurück. Wenn k schon da ist, gibt es den vorhandenen Wert zurück. Die [] wird trotzdem bei jedem Aufruf erzeugt.',
  'glossario.defaultdict.domanda': 'Was passiert, wenn du in einem defaultdict(list) einen fehlenden Schlüssel liest?',
  'glossario.defaultdict.risposta': 'Er wird mit einer leeren Liste angelegt und zurückgegeben, ohne KeyError. Achtung: Schon das Lesen von d[k] fügt k hinzu.',
  'glossario.counter.domanda': 'Was gibt ein Counter für einen Schlüssel zurück, den er nie gesehen hat?',
  'glossario.counter.risposta': '0, ohne KeyError und ohne ihn hinzuzufügen. most_common(n) liefert die n häufigsten.',
  'glossario.with-open.domanda': 'Warum schreibt man with open(nome) as f?',
  'glossario.with-open.risposta': 'Die Datei wird beim Verlassen des Blocks von selbst geschlossen, auch wenn eine Exception kommt. Ohne with musst du f.close() aufrufen.',
  'glossario.yield.domanda': 'Was gibt eine Funktion zurück, die yield enthält?',
  'glossario.yield.risposta': 'Einen Generator. Der Rumpf startet erst, wenn du den ersten Wert anforderst, mit next oder einer for-Schleife, und hält bei jedem yield an. Man kann ihn nur einmal durchlaufen.',
  'glossario.args-e-kwargs.domanda': 'Was sind args und kwargs in def f(*args, **kwargs)?',
  'glossario.args-e-kwargs.risposta': 'args ist ein Tupel mit den zusätzlichen Positionsargumenten, kwargs ein Dictionary mit denen, die per Name übergeben wurden.',
  'glossario.rovescia.domanda': 'Was liefert v[::-1]?',
  'glossario.rovescia.risposta': 'Eine umgekehrte Kopie von v: Das geht mit Listen, Strings und Tupeln. v ändert sich nicht.',
  'glossario.is-e-uguale.domanda': 'Was ist der Unterschied zwischen is und ==?',
  'glossario.is-e-uguale.risposta': '== vergleicht die Werte, is prüft, ob es dasselbe Objekt ist. is nimmt man bei None; bei Zahlen und Strings nimmt man ==.',
  'glossario.default-mutabile.domanda': 'Warum ist def f(x, v=[]) eine Falle?',
  'glossario.default-mutabile.risposta': 'Die Default-Liste wird nur einmal erzeugt, wenn f definiert wird: Jeder Aufruf sieht die Änderungen der vorherigen. Man schreibt v=None und erzeugt die Liste innen.',
  'glossario.f-string.domanda': 'Was gibt print(f"{x:.2f}") aus, wenn x 3.14159 ist?',
  'glossario.f-string.risposta': '3.14: Nach dem Doppelpunkt steht das Format, und .2f heißt zwei Nachkommastellen, gerundet.',
  'glossario.extend.domanda': 'Was ist der Unterschied zwischen v.append(w) und v.extend(w)?',
  'glossario.extend.risposta': 'append fügt w als ein einziges Element hinzu, auch wenn es eine Liste ist. extend fügt die Elemente von w einzeln hinzu. Beide ändern v und geben None zurück.',
  'glossario.split.domanda': 'Was ist der Unterschied zwischen s.split() und s.split(" ")?',
  'glossario.split.risposta': 'Ohne Argument trennt es an beliebigem Leerraum, auch an mehreren Leerzeichen, und lässt leere Teile weg. Mit " " trennt jedes Leerzeichen: Zwei Leerzeichen hintereinander ergeben einen leeren String.',
  'glossario.da-riga': 'Aus: {file}, Zeile {riga}',
};
