// „Ich will … machen“ (js/guida.js und die Anleitung in der Leiste, js/lode.js): die Karten der Schritt-für-Schritt-Anleitung und die von
// Hand geschriebenen Rezepte für den Fall, dass keine KI da ist. Jeder Schritt eines Rezepts ist eine Liste aus vier Texten: [Titel, was man
// tut (2-4 einfache Sätze), wann es fertig ist, eine Hilfe für alle, die nicht weiterkommen]. Die Zahl der Schritte jedes Rezepts steht in RICETTE in js/guida.js.
export default {
  'guida.serve-per': 'Für „{cosa}“ brauchst du:',
  'guida.nessuna-app': 'Auf dem Computer habe ich keine passenden Apps gefunden. Das ist okay: Wenn es nötig ist, sagt dir der Schritt, was du installieren musst.',
  'guida.apri': 'Öffnen',
  'guida.apri-tutte': 'Alle öffnen',
  'guida.aperta': 'Geöffnet: {app}.',
  'guida.non-aperta': 'Ich konnte {app} nicht öffnen.',
  'guida.cominciamo': 'Los geht\'s',
  'guida.preparo': 'Ich bereite den Plan vor',
  'guida.piano-ai': 'Plan, geschrieben mit {motore}: Wenn ein Schritt nichts für dich ist, überspring ihn.',
  'guida.piano-ricetta': 'Plan von Lode, ohne KI.',
  'guida.piano-generico': 'Dafür habe ich kein Rezept: Ich schlage dir einen allgemeinen Plan vor, den du anpassen kannst.',
  'guida.piano-ripiego': 'Die KI hat keinen brauchbaren Plan geliefert: Ich nehme den von Lode.',
  'guida.passo-di': 'Schritt {i} von {tot}',
  'guida.fatto-quando': 'Fertig, wenn: {quando}',
  'guida.ti-serve': 'Du brauchst: {app}',
  'guida.fatto-avanti': 'Erledigt, weiter',
  'guida.non-ci-riesco': 'Ich schaffe es nicht',
  'guida.indietro': 'Zurück',
  'guida.basta': 'Schluss',
  'guida.un-aiuto': 'Eine Hilfe',
  'guida.piu-piccolo': 'Kleiner, ein Stück nach dem anderen:',
  'guida.ci-penso': 'Ich kümmere mich',
  'guida.fallo-con': 'Mach es mit {agente}',
  'guida.scegli-cartella': 'Wähl zuerst den Ordner, in dem gearbeitet wird.',
  'guida.cartella': 'Ordner wählen',
  'guida.testo-agente': 'Das ist der Text, der bei {agente} ankommt, im Ordner „{cartella}“. Du kannst ihn ändern.',
  'guida.nota-agente': 'Es öffnet sich ein Terminal-Fenster mit {agente}: Er nutzt dein Abo, keinen Schlüssel. Lies, was er tut, bevor du Ja sagst.',
  'guida.agente-aperto': 'Ich habe das Terminal mit {agente} geöffnet.',
  'guida.agente-segue': 'Lode beobachtet den Ordner: Wenn {agente} fertig ist, sage ich dir hier Bescheid.',
  'guida.agente-errore': 'Das Terminal hat sich nicht geöffnet: {errore}',
  'guida.agente-finito': '{agente} ist fertig: Prüf es und tippe auf Erledigt.',
  'guida.prompt-agente': 'Ich mache gerade das: {obiettivo}. Jetzt ist der Schritt „{passo}“: {cosa} Mach nur diesen Schritt, erklär mir in einfachen Worten, was du tust, und hör am Ende auf.',
  'guida.fine-titolo': 'Alles geschafft!',
  'guida.fine-testo': { one: '{titolo}: {n} Schritt von {n}, geschafft. Gut gemacht.', other: '{titolo}: {n} Schritte von {n}, alle geschafft. Gut gemacht.' },
  'guida.chiusa': 'Anleitung beiseitegelegt',
  'guida.chiusa-nota': 'Wenn du weitermachen willst, schreib „Anleitung fortsetzen“.',
  'guida.ripresa': 'Ich mache da weiter, wo du aufgehört hast.',
  'guida.nessuna': 'Du hast keine Anleitung, die halb fertig ist. Schreib doch mal „ich will eine Präsentation machen“.',
  'guida.proposta-titolo': 'Mittendrin: {titolo}',
  'guida.proposta-testo': 'Du bist bei Schritt {i} von {tot}.',
  'guida.proposta-bottone': 'Fortsetzen',
  'guida.nel-vault': 'Die Liste der Schritte steht auch im Vault: {nota}.',
  // die Notiz im Vault (in der Sprache des Vaults)
  'guida.nota-file': 'Schritt für Schritt',
  'guida.nota-intro': 'Die Anleitung von Lode. Lode hakt einen Schritt ab, wenn du in der Leiste auf „Erledigt, weiter“ tippst.',
  'guida.nota-quando': 'Fertig, wenn',
  'guida.linguaggio': 'deine Sprache',

  // die Rezepte: [Titel, was man tut, wann es fertig ist, Hilfe]
  'guida.r-tesi-1': ['Versteh, was von dir verlangt wird', 'Lies die Aufgabenstellung noch einmal oder sprich mit deinem Betreuer. Schreib in einer Zeile die Frage auf, die deine Arbeit beantwortet. Notier den Abgabetermin und wie viele Seiten verlangt sind.', 'du hast einen Satz mit der Frage und das Abgabedatum', 'Wenn du nicht weißt, wo du anfangen sollst, schreib drei Fragen zum Thema auf, die dich neugierig machen, und nimm die mit dem meisten Material.'],
  'guida.r-tesi-2': ['Sammle die Quellen', 'Such 5-10 seriöse Quellen: Bücher, Artikel, Skripte aus dem Kurs. Speicher alle an einem Ort, mit Autor und Jahr. Schreib zu jeder zwei Zeilen, wofür du sie brauchst.', 'du hast eine Liste von Quellen mit je zwei Zeilen', 'Fang beim Literaturverzeichnis eines guten Artikels an: Es führt dich zu weiteren Quellen, die schon jemand ausgewählt hat.'],
  'guida.r-tesi-3': ['Mach die Gliederung', 'Schreib die Kapitelüberschriften auf und darunter jeweils drei oder vier Punkte. Sie muss nicht perfekt sein. Die Gliederung ist die Landkarte: Du änderst sie beim Schreiben.', 'du hast eine Gliederung mit den Punkten jedes Kapitels', 'Nimm das klassische Schema: Einleitung, was man schon weiß, was du gemacht hast, Ergebnisse, Schluss.'],
  'guida.r-tesi-4': ['Schreib den ersten Entwurf', 'Schreib ein Kapitel nach dem anderen, ohne zu korrigieren. Lieber eine schlechte Seite als eine leere. Setz die Zitate gleich ein, damit du sie nicht verlierst.', 'jedes Kapitel hat einen Text, auch einen schlechten', 'Mach kurze Einheiten: „Fokus 25“ und schreib nur einen Absatz.'],
  'guida.r-tesi-5': ['Lies nochmal und bessere nach', 'Lies alles laut vor: Lange Sätze hört man. Prüf, ob jedes Kapitel die Anfangsfrage beantwortet. Bring Zitate und Literaturverzeichnis in Ordnung.', 'du hast alles einmal gelesen, von vorn bis hinten', 'Druck es aus oder wechsle die Schrift: Auf denselben Seiten überspringt das Auge die Fehler.'],
  'guida.r-tesi-6': ['Gib ab', 'Exportier als PDF und prüf die Seiten eine nach der anderen. Halt dich an die Regeln des verlangten Formats. Schick die Datei ab und behalt eine Kopie.', 'die Datei ist abgegeben und du hast eine Kopie', 'Lies vor dem Export die Formatregeln deines Instituts: Ränder, Schrift, Titelblatt.'],

  'guida.r-sito-1': ['Entscheide, was die Website können soll', 'Schreib auf, wer sie ansehen wird und was er dort finden soll. Mach eine Liste der Seiten, zum Beispiel Start, Über mich, Projekte, Kontakt. Zeichne die Hauptseite auf ein Blatt.', 'du hast die Liste der Seiten und eine Skizze', 'Sieh dir drei ähnliche Websites an, die dir gefallen, und notier, was sie gemeinsam haben.'],
  'guida.r-sito-2': ['Bereite den Ordner vor', 'Leg einen Ordner für die Website an und öffne ihn im Editor. Erstell darin index.html und style.css. Schreib eine Seite mit nur einer Überschrift und öffne sie im Browser.', 'der Browser zeigt deine Überschrift', 'In die Datei index.html reicht das Tag h1 mit deinem Namen: speichern und die Seite neu laden.'],
  'guida.r-sito-3': ['Schreib die Struktur', 'Setz die Teile der Seite in HTML um: Kopfbereich, Abschnitte, Fußbereich. Nimm echte Überschriften und Absätze, noch kein Design. Füg die anderen Seiten und die Links dazwischen hinzu.', 'alle Seiten sind da und die Links funktionieren', 'Eine Seite nach der anderen: kopier index.html, änder den Text und verlinke mit einem a-Tag.'],
  'guida.r-sito-4': ['Gib ihr ein Design', 'Wähl im CSS eine Schrift, zwei Farben und die Abstände. Sorg dafür, dass sie sich auch auf dem Handy gut lesen lässt. Prüf es mit den Werkzeugen des Browsers.', 'die Website liest sich gut am Computer und am Handy', 'Fang mit wenigen Regeln an: font-family, max-width für den Text, ein bisschen padding.'],
  'guida.r-sito-5': ['Stell sie ins Netz', 'Wähl einen kostenlosen Dienst für statische Websites, zum Beispiel GitHub Pages oder Netlify. Lad den Ordner hoch und öffne die Adresse, die du bekommst. Schick sie einem Freund und frag, was er nicht versteht.', 'die Website öffnet sich über eine öffentliche Adresse', 'Mit GitHub Pages: ein Repository anlegen, die Dateien hochladen und Pages in den Einstellungen einschalten.'],

  'guida.r-codice-1': ['Versteh das Problem', 'Lies die Aufgabenstellung noch einmal und schreib in Worten auf, was ins Programm hineingeht und was herauskommt. Bereite zwei oder drei Beispiele mit dem richtigen Ergebnis vor. So weißt du, wann es funktioniert.', 'du hast zwei oder drei Beispiele für Eingabe und Ausgabe', 'Mach ein ganz kleines Beispiel von Hand, auf einem Blatt, Schritt für Schritt.'],
  'guida.r-codice-2': ['Richte die Umgebung ein', 'Leg einen Ordner für das Projekt an und öffne ihn im Editor. Prüf, ob {linguaggio} funktioniert: Schreib ein Programm, das eine Zeile ausgibt, und starte es.', 'das Testprogramm gibt seine Zeile aus', 'Wenn der Befehl nicht gefunden wird, ist das Programm nicht installiert oder nicht im PATH: Such die offizielle Anleitung für dein System.'],
  'guida.r-codice-3': ['Schreib die erste Version', 'Schreib in {linguaggio} die einfachste Version, die das erste Beispiel löst. Noch keine Sonderfälle. Starte das Programm oft, schon nach wenigen Zeilen.', 'das erste Beispiel gibt das richtige Ergebnis', 'Teil es in kleine Funktionen: eine liest, eine rechnet, eine gibt aus.'],
  'guida.r-codice-4': ['Teste alle Fälle', 'Probier die anderen Beispiele und die Grenzfälle aus: leer, nur ein Element, große Zahlen. Wenn etwas nicht stimmt, lies den Fehler und gib die Werte zwischendurch aus. Behebe einen Fehler nach dem anderen.', 'alle Beispiele geben das richtige Ergebnis', 'Kopier den Fehler und schreib „erklär den Fehler“: Ich erkläre ihn dir Schritt für Schritt.'],
  'guida.r-codice-5': ['Räum auf und gib ab', 'Gib den Variablen klare Namen und nimm die Testausgaben heraus. Füg zwei Zeilen hinzu, die erklären, wie man es startet. Lies die Aufgabenstellung noch einmal und prüf, ob du alles gemacht hast.', 'der Code ist sauber und die Aufgabe ist erfüllt', 'Erklär den Code laut, Zeile für Zeile: Wo du hängen bleibst, gibt es etwas zu verbessern.'],

  'guida.r-presentazione-1': ['Entscheide die Kernaussage', 'Schreib in einem Satz auf, was sich die Zuhörer merken sollen. Sieh nach, wie viel Zeit du hast: ungefähr eine Folie pro Minute. Wähl drei Punkte, nicht mehr.', 'du hast den Satz der Kernaussage und drei Punkte', 'Stell dir vor, du erzählst es einem Freund in einer Minute: Was du sagst, ist die Kernaussage.'],
  'guida.r-presentazione-2': ['Mach den Ablauf', 'Schreib für jede Folie einen Titel, der Reihe nach. Erst der Einstieg, dann die drei Punkte, dann der Schluss. Noch keine Grafik.', 'du hast eine Liste von Titeln, einen pro Folie', 'Nimm Haftzettel oder eine Liste: Ideen zu verschieben ist leichter, bevor du das Programm öffnest.'],
  'guida.r-presentazione-3': ['Füll die Folien', 'Eine Idee pro Folie, wenige Worte, große Bilder. Den langen Text sagst du, du schreibst ihn nicht. Nimm überall denselben Stil.', 'jede Folie hat ihren Inhalt', 'Wenn eine Folie mehr als sechs Zeilen hat, teil sie in zwei.'],
  'guida.r-presentazione-4': ['Probe laut', 'Geh die ganze Präsentation mit der Stoppuhr noch einmal durch. Notier, wo du hängst und wo du zu lang wirst. Streich, was für die Kernaussage nicht nötig ist.', 'du hast sie in der richtigen Zeit geprobt', 'Nimm dich mit dem Handy auf und hör dir einmal selbst zu.'],
  'guida.r-presentazione-5': ['Bereite den Tag vor', 'Exportier auch als PDF, falls das Programm nicht da ist. Nimm die Datei auf einem Stick mit oder leg sie in die Cloud. Bereite die Antworten auf zwei wahrscheinliche Fragen vor.', 'du hast das Ersatz-PDF und die zwei Antworten', 'Komm ein paar Minuten früher und probier den Beamer aus.'],

  'guida.r-video-1': ['Schreib auf, was du erzählst', 'Entscheide in einem Satz, worum es im Video geht und wie lang es dauert. Schreib den Ablauf der Szenen auf. Wenn du sprichst, schreib den Text und lies ihn laut vor.', 'du hast den Ablauf und den Text', 'Ein kurzes Video funktioniert besser: Fang mit einem von einer Minute an.'],
  'guida.r-video-2': ['Nimm auf', 'Nimm die Szenen aus dem Ablauf auf, jede mehrmals. Achte auf das Licht und vor allem auf den Ton: Ein Mikrofon in der Nähe zählt mehr als die Kamera. Halt das Handy ruhig und im Querformat, außer es ist für soziale Netzwerke.', 'alle Szenen sind aufgenommen', 'Nimm an einem ruhigen Ort auf, mit dem Fenster vor dir und nicht hinter dir.'],
  'guida.r-video-3': ['Schneide', 'Importier die Dateien ins Schnittprogramm. Bring die Szenen in die richtige Reihenfolge und schneide die Pausen und Fehler heraus. Sieh dir alles einmal an, ohne anzuhalten.', 'das Video lässt sich von Anfang bis Ende ansehen', 'Schneide mehr weg, als du denkst: Eine Sekunde zu viel merkt man.'],
  'guida.r-video-4': ['Feinschliff', 'Stell die Lautstärke ein, füg Titel und, wenn nötig, leise Musik hinzu. Nimm rechtefreie Musik. Füg Untertitel hinzu, wenn jemand es ohne Ton ansieht.', 'Ton, Titel und Untertitel sind in Ordnung', 'Hör mit Kopfhörern: Lautstärkesprünge hört man.'],
  'guida.r-video-5': ['Exportiere und gib ab', 'Exportier als MP4, 1080p, das passt fast überall. Sieh dir die exportierte Datei bis zum Ende an. Lad sie hoch oder gib sie ab und behalt das Projekt.', 'die Datei ist abgegeben und du hast sie ganz angesehen', 'Wenn die Datei zu groß ist, exportier mit einer niedrigeren Bitrate.'],

  'guida.r-dati-1': ['Schreib die Frage auf', 'Schreib in einer Zeile auf, was du aus den Daten herausfinden willst. Entscheide, welches Diagramm darauf antworten würde: eine Entwicklung, ein Vergleich, eine Verteilung. So weißt du, wonach du suchst.', 'du hast die Frage und die Art des Diagramms', 'Vervollständige den Satz: Wenn sich das eine ändert, ändert sich dann auch das andere?'],
  'guida.r-dati-2': ['Bereite die Daten vor', 'Öffne die Daten in einer Tabellenkalkulation. Eine Zeile pro Beobachtung, eine Spalte pro Variable, mit klarem Namen. Entferne leere Zeilen und Doppelte.', 'die Tabelle ist sauber, mit Spaltenüberschriften', 'Arbeite an einer Kopie: Behalt immer die Originaldatei.'],
  'guida.r-dati-3': ['Sieh dir die Zahlen an', 'Berechne für jede Spalte Mittelwert, Minimum und Maximum. Such nach seltsamen Werten: Tippfehler oder echte Fälle? Notier, was dir auffällt.', 'du hast die Übersichtszahlen und die Notizen', 'Sortier die Spalte: Die seltsamen Werte landen ganz oben oder ganz unten.'],
  'guida.r-dati-4': ['Mach das Diagramm', 'Erstell das Diagramm, das die Frage beantwortet. Setz den Titel, die Namen der Achsen und die Einheiten. Entferne alles, was man zum Lesen nicht braucht.', 'das Diagramm versteht man ohne Erklärung', 'Linien für die Entwicklung über die Zeit, Balken zum Vergleichen, Histogramm für die Verteilung.'],
  'guida.r-dati-5': ['Schreib auf, was es sagt', 'Schreib unter das Diagramm zwei oder drei Sätze: was man sieht und was es bedeutet. Sag auch, was die Daten nicht sagen können. Speicher das Diagramm als Bild.', 'du hast das Diagramm gespeichert und die Sätze', 'Trenn, was du siehst, von deiner Erklärung: erst die Fakten, dann die Idee.'],

  'guida.r-esame-1': ['Bring den Stoff in Ordnung', 'Nimm den Prüfungsstoff des Kurses und füg ihn in Lode ein, mit „Prüfungsstoff“. Du bekommst die Karte der Themen. Markier die, die du schon kannst.', 'der Stoff ist in Lode', 'Wenn du den Stoff nicht findest, sieh auf der Seite des Kurses nach oder frag deine Kommilitonen.'],
  'guida.r-esame-2': ['Mach einen Plan', 'Zähl die Tage, die noch bleiben, und verteil die Themen. Heb dir die letzten Tage zum Wiederholen auf. Trag den Plan in den Kalender ein.', 'jedes Thema hat seinen Tag', 'Schreib „Wochenplan“, dann zeigt dir Lode deine wirklich freien Stunden.'],
  'guida.r-esame-3': ['Lern ein Thema pro Tag', 'Mach kurze Einheiten mit dem Timer, zum Beispiel „Fokus 50“. Mach am Ende jedes Themas Karten mit dem, was du dir merken musst. Wiederhole sie jeden Tag mit „wiederholen“.', 'du hast alle Themen mindestens einmal gelernt', 'Erklär das Thema laut, als wärst du der Prof: Wo du hängst, lies nach.'],
  'guida.r-esame-4': ['Teste dich selbst', 'Mach das „Quiz“ oder lass dich mit „frag mich ab“ abfragen. Markier die falschen Fragen und lern sie nochmal. Wiederhol, bis du sie kannst.', 'du beantwortest die meisten Fragen richtig', 'Fang mit den Themen an, die du am wenigsten kannst: Da gewinnst du am meisten.'],
  'guida.r-esame-5': ['Mach eine echte Probe', 'Zwei oder drei Tage vorher mach die „Probeklausur“ mit einer alten Klausur und der echten Zeit. Korrigier sie und wiederhol die Fehler. Schlaf am Tag davor.', 'du hast eine ganze Klausur in der Zeit geschafft', 'Wenn du keine alten Klausuren hast, frag deine Kommilitonen oder in der Kursgruppe.'],

  'guida.r-generico-1': ['Schreib das Ergebnis auf', 'Schreib in einem Satz auf, wie die fertige Sache aussehen wird. Je konkreter, desto besser. Notier auch, bis wann du sie brauchst.', 'du hast den Satz des Ergebnisses und das Datum', 'Stell dir vor, du zeigst es jemandem: Was sieht er?'],
  'guida.r-generico-2': ['Such, was du brauchst', 'Mach eine Liste dessen, was du brauchst: Programme, Material, Leute, mit denen du sprechen musst. Sieh dir an, wie jemand anderes es gemacht hat, zum Beispiel in einem Video oder einer Anleitung.', 'du hast die Liste dessen, was du brauchst', 'Such nach dem Namen der Sache mit „Tutorial“ oder „Anleitung für Anfänger“.'],
  'guida.r-generico-3': ['Mach den ersten kleinen Schritt', 'Wähl das Kleinste, was du jetzt in 20 Minuten tun kannst. Mach es sofort, auch wenn es nicht perfekt ist. Der Rest wird leichter.', 'du hast das erste Stück gemacht', 'Wenn dir 20 Minuten zu viel sind, nimm 5 Minuten: Hauptsache, du fängst an.'],
  'guida.r-generico-4': ['Mach weiter und prüf nach', 'Teil den Rest in Stücke von je einer Einheit und mach sie eins nach dem anderen. Vergleich nach jedem Stück mit dem Ergebnis, das du aufgeschrieben hast. Hol dir eine Meinung, bevor du fertig bist.', 'das Ergebnis ist so, wie du es aufgeschrieben hattest', 'Wenn du hängst, geh zum Stück davor zurück und mach es kleiner.'],
};
