// Deine Noten in Notensystemen außer dem italienischen (Deutsch): «was brauche ich», «was wenn ich», Credits, Endnote,
// der eingefügte Notenspiegel (js/libretto.js, js/lode.js, js/pagina.js, js/benvenuto.js).
export default {
  'libretto.crediti-di': '{fatti} von {tot} {crediti}',
  'libretto.serve-gia': 'Für <b>{obiettivo}</b> reicht es, die restlichen Prüfungen zu bestehen.',
  'libretto.serve-media': 'Für <b>{obiettivo}</b> brauchst du einen Schnitt von <b>{voto}</b> in den restlichen {cfu} {crediti}.',
  'libretto.serve-impossibile': '<b>{obiettivo}</b> ist nicht mehr drin: ziel auf {punta}.',
  'libretto.obiettivo-fuori': 'Im System {sistema} geht das Ziel von {da} bis {a}.',
  'libretto.simula-esito': 'Schnitt <b>{media}</b> <span class="{classe}">{delta}</span> · {finale} <b>{valore}</b>',
  'libretto.simula': 'Mit **{voto}** in {nome} geht dein Schnitt von {prima} auf **{dopo}** ({delta}): {finale} **{valore}**.',
  'libretto.simula-primo': 'Mit {voto} in **{nome}** würde dein Schnitt bei **{media}** anfangen: {finale} **{valore}**.',
  'libretto.sintesi-media-finale': 'Schnitt {media}, {finale} {valore}',
  'libretto.non-valido': 'Im System {sistema} gibt es die Note {voto} nicht.',
  'libretto.non-superato': '{voto} in {nome} ist nicht bestanden (du brauchst {sufficienza}): ich trage es nicht ein.',
  'libretto.nuovo-esame': 'Neue Prüfung mit {n} {crediti}: korrigier sie in deinen Noten.',
  'libretto.formula': 'gewichtet nach {crediti}',
  'libretto.piede-esami': { one: '{n} Prüfung · {cfu} {crediti}', other: '{n} Prüfungen · {cfu} {crediti}' },
  'libretto.piede-media': 'Schnitt <b>{media}</b> · {finale} <b>{valore}</b>',
  'libretto.campo-voto-nota': 'wie im Notenspiegel ({esempio}); leer, wenn du sie noch nicht geschrieben hast',
  'libretto.voto-non-letto': 'Ich kann die Note «{voto}» nicht lesen: schreib sie wie im Notenspiegel, zum Beispiel {esempio}.',
  'libretto.incolla-sotto': 'Öffne deinen Notenspiegel im Uni-Portal, markier alles, kopier es und füg es hier ein: eine Zeile pro Prüfung, mit Name, Credits und Note. Oder schreib sie selbst, zum Beispiel «{esempio}».',
  'libretto.alla-laurea': 'noch {n} {crediti} bis zum Abschluss',
  'libretto.campo-crediti': 'Credits ({crediti})',
  'libretto.libretto-vuoto': 'Noch keine Prüfungen. Schreib in die Leiste <kbd>ich habe eine {voto} in Physik</kbd>.',
  'libretto.riga-esempio': '{nome}, {n} {crediti}, {voto}',
  'libretto.esame-esempio': 'Analysis 1',
};
