// Die Fragen von «Was gibt das aus?» (js/codice/modelli.js), auf Deutsch.
// Schlüssel: modelli.<modello>.cosa / .concetto / .frase-N (die Sätze der Mutanten, in Reihenfolge), modelli.<modello>.<lingua>.… für
// das, was sich in Python und Java ändert; modelli.concetti.* und modelli.errori.* sind die Namen der Themen und der Fehler.
export default {
  'modelli.hai-scelto': 'Du hast `{s}` gewählt',
  'modelli.niente': '(nichts)',
  'modelli.concetti.for': 'for-Schleife',
  'modelli.concetti.while': 'while-Schleife',
  'modelli.concetti.do-while': 'do-while-Schleife',
  'modelli.concetti.ritroso': 'Rückwärts zählen',
  'modelli.concetti.array': 'Arrays',
  'modelli.concetti.divisione-intera': 'Ganzzahldivision',
  'modelli.concetti.resto': 'Rest mit negativen Zahlen',
  'modelli.concetti.cast': 'Cast nach double',
  'modelli.concetti.incremento': 'i++ und ++i',
  'modelli.concetti.assegnamento': 'Zusammengesetzte Zuweisung (+=)',
  'modelli.concetti.switch': 'switch und break',
  'modelli.concetti.cortocircuito': '&& und || mit Kurzschluss',
  'modelli.concetti.else-pendente': 'Dangling else',
  'modelli.concetti.puntatori': 'Übergabe per Adresse',
  'modelli.concetti.parametri': 'Übergabe per Wert',
  'modelli.concetti.visibilita': 'Variablen in Blöcken',
  'modelli.concetti.char': 'char und ASCII-Codes',
  'modelli.concetti.ricorsione': 'Rekursion',
  'modelli.concetti.annidati': 'Verschachtelte Schleifen',
  'modelli.concetti.break-continue': 'break und continue',
  'modelli.concetti.ternario': 'Ternärer Operator',
  'modelli.errori.fuori-di-uno': 'um eins daneben',
  'modelli.errori.divisione-intera': 'Ganzzahldivision',
  'modelli.errori.post-vs-pre': 'i++ und ++i',
  'modelli.errori.break-dimenticato': 'vergessenes break',
  'modelli.errori.copia-del-parametro': 'Kopie des Parameters',
  'modelli.errori.cortocircuito': 'Kurzschluss',
  'modelli.errori.resto-col-segno': 'Rest mit Vorzeichen',
  'modelli.errori.piu-uguale': '+= und =',
  'modelli.errori.maggiore-o-uguale': '> und >=',
  'modelli.errori.indice-valore': 'Index und Wert',
  'modelli.errori.sovrascrittura': 'erster und letzter',
  'modelli.errori.else-pendente': 'Dangling else',
  'modelli.errori.variabile-nascosta': 'verdeckte Variable',
  'modelli.errori.carattere-codice': 'Zeichen und Code',
  'modelli.errori.caso-base': 'Basisfall',
  'modelli.errori.passo-del-ciclo': 'wann der Schritt der Schleife kommt',
  'modelli.errori.ricorsione': 'Rekursion',
  'modelli.errori.cicli-annidati': 'verschachtelte Schleifen',
  'modelli.errori.break-continue': 'break und continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'Ternäroperator verkehrt herum',
  'modelli.errori.scambi-in-fila': 'Vertauschungen nacheinander',
  'modelli.for-minore.cosa': 'diese for-Schleife',
  'modelli.for-minore.concetto': 'Mit `i < n` hat der letzte Durchlauf i = n - 1: Der Wert n wird nie ausgegeben.',
  'modelli.for-minore.frase': `{hai}: Das käme mit \`i <= {b}\` heraus. Hier hört die Schleife früher auf.`,
  'modelli.for-minore.frase-2': `{hai}: Das wäre so, als käme \`i++\` vor dem ersten Durchlauf. Das Inkrement kommt am Ende jedes Durchlaufs: Der erste Durchlauf hat i = {a}.`,
  'modelli.for-minore.frase-3': `{hai}: Du hast einen Durchlauf zu früh aufgehört. Mit \`i < {b}\` hat der letzte Durchlauf i = {b2}.`,
  'modelli.for-passo.cosa': 'diese for-Schleife',
  'modelli.for-passo.concetto': 'Mit `<=` macht die Schleife auch den Durchlauf, in dem i gleich der Grenze ist.',
  'modelli.for-passo.frase': `{hai}: Das käme mit \`i < {b}\` heraus. Mit \`<=\` wird auch {b} ausgegeben.`,
  'modelli.for-passo.frase-2': `{hai}: \`i += {s}\` kommt nicht vor dem ersten Durchlauf. Der erste Durchlauf hat i = {a}.`,
  'modelli.for-indietro.cosa': 'dieser Countdown',
  'modelli.for-indietro.concetto': 'Die Schleife läuft, solange die Bedingung wahr ist: Mit `i > L` wird der Wert L nicht ausgegeben.',
  'modelli.for-indietro.frase': `{hai}: Das käme mit \`i >= {l}\` heraus. Mit \`i > {l}\` hat der letzte Durchlauf i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai}: \`i--\` kommt am Ende des Durchlaufs, nicht vorher. Der erste Durchlauf gibt {n} aus.`,
  'modelli.for-indietro.frase-3': `{hai}: Du hast einen Durchlauf zu früh aufgehört. Auch i = {l} erfüllt \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'diese while-Schleife',
  'modelli.while-somma.concetto': 'Die while-Schleife endet, wenn die Bedingung falsch wird: Nach `while (i < n)` hat i den Wert n.',
  'modelli.while-somma.frase': `{hai}: Das käme mit \`i <= {n}\` heraus. Hier macht die Schleife einen Durchlauf weniger.`,
  'modelli.while-somma.frase-2': `{hai}: Das wäre so, als käme \`i++\` vor \`s += i\`. Hier addiert s erst i, und erst danach wächst i.`,
  'modelli.while-somma.frase-3': `{hai}: Nach der Schleife ist i nicht {n}. Die while-Schleife endet genau, wenn i {n2} wird.`,
  'modelli.while-dimezza.cosa': 'diese while-Schleife',
  'modelli.while-dimezza.concetto': 'Zwischen zwei ints schneidet `/` ab: 7 / 2 ergibt 3, und beim Halbieren kommt man ohne Nachkommastellen bei 1 an.',
  'modelli.while-dimezza.frase': `{hai}: Das würde passieren, wenn n ein double wäre. n ist ein int: \`n /= 2\` wirft die Nachkommastellen weg.`,
  'modelli.while-dimezza.frase-2': `{hai}: Das käme mit \`n >= 1\` heraus. Die Schleife hört auf, sobald n bei 1 ist.`,
  'modelli.while-post.cosa': 'diese while-Schleife mit i++',
  'modelli.while-post.concetto': '`i++ < n` vergleicht den alten Wert und erhöht dann: In der Schleife ist i schon gewachsen.',
  'modelli.while-post.frase': `{hai}: Das käme mit \`++i\` heraus. Mit \`i++\` benutzt der Vergleich den Wert von vorher.`,
  'modelli.while-post.frase-2': `{hai}: Wenn printf startet, hat der Vergleich i schon erhöht.`,
  'modelli.while-post.frase-3': `{hai}: Auch der letzte Vergleich, der falsche, erhöht i. Am Ende ist i {n}.`,
  'modelli.array-somma.cosa': 'diese Summe',
  'modelli.array-somma.concetto': 'Die Indizes eines Arrays mit n Elementen gehen von 0 bis n - 1.',
  'modelli.array-somma.frase': `{hai}: Du hast \`v[0]\` übersprungen. Das erste Element hat den Index 0.`,
  'modelli.array-somma.frase-2': `{hai}: Du hast das letzte weggelassen. Mit \`i < {k}\` liest der letzte Durchlauf \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai}: Das ist das letzte Element, als stünde da \`s = v[i]\`. \`+=\` addiert, es ersetzt nicht.`,
  'modelli.array-massimo.cosa': 'dieses Maximum',
  'modelli.array-massimo.concetto': 'p ist ein Index: Er zählt ab 0. Mit `>` bleibt die erste Position des Maximums.',
  'modelli.array-massimo.frase': `{hai}: Du hast die Positionen ab 1 gezählt. In {linguaggio} hat das erste Element den Index 0.`,
  'modelli.array-massimo.frase-2': `{hai}: Das würde \`>=\` machen. Mit \`>\` verschiebt ein gleich großes Maximum p nicht: Es bleibt das erste.`,
  'modelli.array-massimo.frase-3': `{hai}: Du hast das letzte Element weggelassen. Auch das wird verglichen.`,
  'modelli.array-ultimo.cosa': 'diese Suche',
  'modelli.array-ultimo.concetto': 'Die Schleife hört nicht auf, wenn sie x findet: p wird überschrieben und bleibt die letzte Position.',
  'modelli.array-ultimo.frase': `{hai}: Das ist die erste Position. Die Schleife hört nicht auf: Jedes Mal, wenn sie x findet, überschreibt sie p.`,
  'modelli.array-ultimo.frase-2': `{hai}: Du hast die Positionen ab 1 gezählt. In {linguaggio} hat das erste Element den Index 0.`,
  'modelli.array-ultimo.frase-3': `{hai}: Das ist der gesuchte Wert, nicht seine Position. p ist ein Index.`,
  'modelli.media-array.cosa': 'dieser Mittelwert',
  'modelli.media-array.concetto': '`s / n` zwischen ints schneidet ab. `(double)s / n` wandelt zuerst um und teilt mit Nachkommastellen.',
  'modelli.media-array.frase': `{hai}: \`s / {k}\` ist eine Division zwischen zwei ints: Die Nachkommastellen gehen verloren.`,
  'modelli.media-array.frase-2': `{hai}: Der Cast \`(double)s\` kommt vor der Division, also behält die Division die Nachkommastellen.`,
  'modelli.media-array.frase-3': `{hai}: Die Division zwischen ints rundet nicht, sie schneidet ab.`,
  'modelli.divisione-double.cosa': 'diese Division',
  'modelli.divisione-double.concetto': 'Der Typ des Ergebnisses zählt nicht: `a / b` zwischen ints schneidet ab, auch wenn es in einem double landet.',
  'modelli.divisione-double.frase': `{hai}: \`a / b\` wird zwischen ints berechnet, bevor es in m landet. Der double bekommt eine schon abgeschnittene Zahl.`,
  'modelli.divisione-double.frase-2': `{hai}: Die Division zwischen ints rundet nicht, sie schneidet Richtung null ab.`,
  'modelli.cast-prima-dopo.cosa': 'diese zwei Casts',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` teilt zwischen ints und wandelt dann um. `(double)s / n` wandelt um und teilt dann.',
  'modelli.cast-prima-dopo.frase': `{hai}: In \`(double)(s / n)\` sorgen die Klammern dafür, dass zuerst geteilt wird, zwischen ints. Der Cast kommt danach.`,
  'modelli.cast-prima-dopo.frase-2': `{hai}: In \`(double)s / n\` gilt der Cast nur für s, und die Division behält die Nachkommastellen.`,
  'modelli.cast-prima-dopo.frase-3': `{hai}: Du hast sie vertauscht. Die Klammern entscheiden, ob der Cast vor oder nach der Division kommt.`,
  'modelli.diviso-due.cosa': 'diese Division durch 2',
  'modelli.diviso-due.concetto': 'Ein double in der Rechnung reicht: `a / 2.0` behält die Nachkommastellen, `a / 2` nicht.',
  'modelli.diviso-due.frase': `{hai}: \`a / 2\` ist zwischen zwei ints: Es schneidet ab und ergibt einen int, den %d ohne Nachkommastellen ausgibt.`,
  'modelli.diviso-due.frase-2': `{hai}: \`2.0\` ist ein double, also behält \`a / 2.0\` die Nachkommastellen.`,
  'modelli.diviso-due.frase-3': `{hai}: \`a / 2\` rundet nicht: Es schneidet Richtung null ab.`,
  'modelli.resto-negativi.cosa': 'dieser Rest',
  'modelli.resto-negativi.concetto': `In {linguaggio} schneidet die Division Richtung null ab, und der Rest hat das Vorzeichen des Dividenden: -7 % 3 ergibt -1.`,
  'modelli.resto-negativi.frase': `{hai}: So macht es Python, das nach unten rundet. In {linguaggio} wird Richtung null abgeschnitten.`,
  'modelli.resto-negativi.frase-2': `{hai}: In {linguaggio} ist der Rest nicht immer positiv. Er hat das Vorzeichen des Dividenden, also von a.`,
  'modelli.resto-negativi.frase-3': `{hai}: Die Division zwischen ints schneidet Richtung null ab, nicht nach unten.`,
  'modelli.post-pre.cosa': 'diese Inkremente',
  'modelli.post-pre.concetto': '`x = i--` benutzt den alten Wert und verringert dann; `y = --i` verringert und benutzt dann den neuen Wert.',
  'modelli.post-pre.concetto-2': '`x = i++` benutzt den alten Wert und erhöht dann; `y = ++i` erhöht und benutzt dann den neuen Wert.',
  'modelli.post-pre.frase': `{hai}: Mit \`x = i{op}\` bekommt x den alten Wert, dann ändert sich i.`,
  'modelli.post-pre.frase-2': `{hai}: Mit \`y = {op}i\` ändert sich zuerst i, dann bekommt y den neuen Wert.`,
  'modelli.post-pre.frase-3': `{hai}: Du hast sie vertauscht. Das Zeichen dahinter (\`i{op}\`) benutzt den alten Wert, das davor (\`{op}i\`) den neuen.`,
  'modelli.piu-uguale.cosa': 'dieses +=',
  'modelli.piu-uguale.concetto': '`s += x` heißt `s = s + x`: Es addiert zum vorhandenen Wert.',
  'modelli.piu-uguale.frase': `{hai}: Das ist nur der letzte Durchlauf, als stünde da \`=\`. \`+=\` addiert jedes Mal.`,
  'modelli.piu-uguale.frase-2': `{hai}: Mit \`<=\` macht auch i = {n} seinen Durchlauf.`,
  'modelli.piu-uguale.frase-3': `{hai}: Du hast den Startwert vergessen. s startet bei {a}.`,
  'modelli.switch.cosa': 'dieses switch',
  'modelli.switch.concetto': 'Ohne break fällt die Ausführung in den case darunter und läuft bis zum ersten break oder bis zum Ende weiter.',
  'modelli.switch.frase': `{hai}: Das wäre so, als hätte jeder case sein eigenes break. Ohne break geht es im case darunter weiter.`,
  'modelli.switch.frase-2': `{hai}: Du hast das break übersprungen. Dort hört das switch auf.`,
  'modelli.switch.frase-3': `{hai}: default läuft nicht immer. Es läuft, wenn kein case passt, oder wenn man aus einem case ohne break hineinfällt.`,
  'modelli.cortocircuito.cosa': 'dieses if mit || und &&',
  'modelli.cortocircuito.concetto': 'Wenn der erste Teil schon reicht (wahr bei ||, falsch bei &&), wird der zweite nicht ausgeführt.',
  'modelli.cortocircuito.frase': `{hai}: \`++n\` wird nicht ausgeführt. Bei \`{op}\` reicht schon der erste Teil für die Entscheidung, und n bleibt 0.`,
  'modelli.cortocircuito.frase-3': '|| braucht mindestens einen wahren Teil',
  'modelli.cortocircuito.frase-4': '&& braucht zwei wahre Teile',
  'modelli.cortocircuito.frase-2': `{hai}: Du hast \`{op}\` falsch gelesen. {op2}.`,
  'modelli.else-pendente.cosa': 'dieses else',
  'modelli.else-pendente.concetto': 'Das else gehört zum nächsten if, das noch kein else hat, egal wie eingerückt ist.',
  'modelli.else-pendente.frase': `{hai}: Du bist der Einrückung gefolgt. Aber das else gehört zum nächsten if, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai}: Mit \`i < {n}\` hat der letzte Durchlauf i = {n2}.`,
  'modelli.swap-valore.cosa': 'dieser Tausch',
  'modelli.swap-valore.concetto': 'Eine Funktion bekommt Kopien der Werte: a und b zu tauschen ändert x und y nicht.',
  'modelli.swap-valore.frase': `{hai}: a und b sind Kopien von x und y. Der Tausch bleibt in der Funktion.`,
  'modelli.swap-valore.frase-2': `{hai}: In der Funktion findet der Tausch wirklich statt. Getauscht werden die Kopien, nicht x und y.`,
  'modelli.swap-indirizzo.cosa': 'diese Vertauschungen mit Zeigern',
  'modelli.swap-indirizzo.concetto': 'Mit `&x` bekommt die Funktion die Adresse: `*a = …` ändert wirklich x. Die Vertauschungen passieren nacheinander.',
  'modelli.swap-indirizzo.frase': `{hai}: Hier sind es keine Kopien. \`&x\` übergibt die Adresse, und \`*a\` schreibt wirklich in x.`,
  'modelli.swap-indirizzo.frase-2': `{hai}: Die Vertauschungen laufen der Reihe nach. Erst x mit y, dann das neue y mit z.`,
  'modelli.swap-indirizzo.frase-3': `{hai}: Der zweite Tausch sieht das y, das der erste schon geändert hat.`,
  'modelli.valore-e-indirizzo.cosa': 'diese Funktion',
  'modelli.valore-e-indirizzo.concetto': 'a ist eine Kopie von x; b ist die Adresse von y: Nur `*b = …` ändert die Variable in main.',
  'modelli.valore-e-indirizzo.frase': `{hai}: a ist eine Kopie von x. Wenn sich a ändert, ändert sich x nicht.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai}: b ist keine Kopie, sondern die Adresse von y. \`*b = …\` ändert y.`,
  'modelli.array-in-funzione.cosa': 'dieses Array, das an eine Funktion übergeben wird',
  'modelli.array-in-funzione.concetto': 'Ein Array wird per Adresse übergeben: Die Funktion ändert wirklich a. Ein int dagegen wird als Kopie übergeben.',
  'modelli.array-in-funzione.frase': `{hai}: Ein Array wird nicht kopiert. Die Funktion arbeitet auf denselben Elementen wie a.`,
  'modelli.array-in-funzione.frase-2': `{hai}: n dagegen ist eine Kopie. Das \`n--\` der Funktion ändert das n in main nicht.`,
  'modelli.blocco-ombra.cosa': 'diese zwei x',
  'modelli.blocco-ombra.concetto': 'Das im Block deklarierte x ist eine andere Variable: Es verdeckt das äußere und verschwindet bei der }.',
  'modelli.blocco-ombra.frase': `{hai}: \`int x = {b}\` in den geschweiften Klammern erzeugt ein neues x. Draußen ist x immer noch {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai}: Im Block ist das nächste x das innere. y benutzt dieses.`,
  'modelli.char-ascii.cosa': 'diese chars',
  'modelli.char-ascii.concetto': 'Ein char ist eine Zahl: \'a\' ist 97. %c gibt den Buchstaben aus, %d den Code. Großbuchstabe = Kleinbuchstabe - 32.',
  'modelli.char-ascii.frase': `{hai}: %d liefert nicht die Position im Alphabet. Es liefert den ASCII-Code: 'a' ist 97.`,
  'modelli.char-ascii.frase-2': `{hai}: %d gibt die Zahl des Zeichens aus, nicht den Buchstaben.`,
  'modelli.char-ascii.frase-3': `{hai}: d ist ein char, und %c gibt es als Buchstaben aus, als Großbuchstaben.`,
  'modelli.fattoriale.cosa': 'diese Rekursion',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), und der Basisfall stoppt den Abstieg bei 1.',
  'modelli.fattoriale.frase': `{hai}: Das ist fatt({n}). Du hast einen Schritt zu wenig gemacht: Man multipliziert von {n2} bis 1.`,
  'modelli.fattoriale.frase-2': `{hai}: Das ist fatt({n}). Du hast einen Schritt zu viel gemacht: Man startet bei {n2}.`,
  'modelli.fattoriale.frase-3': `{hai}: Du hast beim ersten Aufruf aufgehört. fatt(n - 1) ruft sich weiter auf, bis zum Basisfall.`,
  'modelli.somma-cifre.cosa': 'diese Rekursion',
  'modelli.somma-cifre.concetto': 'n % 10 ist die letzte Ziffer, n / 10 entfernt die letzte Ziffer. Der Basisfall gibt die übrige Ziffer zurück.',
  'modelli.somma-cifre.frase': `{hai}: Du hast die erste Ziffer verloren. Der Basisfall gibt n zurück, nicht 0.`,
  'modelli.somma-cifre.frase-2': `{hai}: Das ist die Anzahl der Ziffern. Hier addiert jeder Aufruf \`n % 10\`, die Ziffer, nicht 1.`,
  'modelli.somma-cifre.frase-3': `{hai}: Das ist nur die letzte Ziffer. Der Rückgabewert wird zu dem des nächsten Aufrufs addiert.`,
  'modelli.ricorsione-ordine.cosa': 'diese Rekursion',
  'modelli.ricorsione-ordine.concetto': 'printf kommt nach dem Aufruf: Ausgegeben wird beim Zurückkehren, also von der kleinsten zur größten Zahl.',
  'modelli.ricorsione-ordine.frase': `{hai}: So wäre es mit printf vor dem Aufruf. Hier wird beim Zurückkehren ausgegeben.`,
  'modelli.ricorsione-ordine.frase-2': `{hai}: Bei n = 0 kehrt die Funktion sofort zurück, ohne Ausgabe.`,
  'modelli.annidati-conta.cosa': 'diese verschachtelten Schleifen',
  'modelli.annidati-conta.concetto': 'Die innere Schleife startet bei jedem Durchlauf der äußeren neu: Hier läuft sie i-mal, also 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai}: Das käme mit \`j <= i\` heraus. Mit \`j < i\` zählt der erste Durchlauf (i = 0) gar nichts.`,
  'modelli.annidati-conta.frase-2': `{hai}: Die innere Schleife läuft nicht immer {n}-mal: Sie läuft i-mal.`,
  'modelli.annidati-stelle.cosa': 'diese Sterne',
  'modelli.annidati-stelle.concetto': 'Für jede Zeile i gibt die innere Schleife i Zeichen aus, dann macht `\\n` einen Zeilenumbruch.',
  'modelli.annidati-stelle.frase': `{hai}: ein Zeichen zu viel pro Zeile. j startet bei 0, und mit \`j < i\` macht es i Durchläufe.`,
  'modelli.annidati-stelle.frase-2': `{hai}: Die innere Schleife hängt von i ab: Sie gibt nicht immer {n} Zeichen aus.`,
  'modelli.annidati-stelle.frase-3': `{hai}: Die letzte Zeile fehlt. Mit \`i <= {n}\` wird auch Zeile {n} ausgegeben.`,
  'modelli.break-continue.cosa': 'dieses break und dieses continue',
  'modelli.break-continue.concetto': `\`continue\` springt zum nächsten Durchlauf; \`break\` verlässt die Schleife, und das {l} dieses Durchlaufs kommt nicht mehr.`,
  'modelli.break-continue.frase': `{hai}: \`continue\` verlässt die Schleife nicht: Es überspringt nur den Durchlauf mit i = {a}.`,
  'modelli.break-continue.frase-2': `{hai}: \`break\` überspringt keinen Durchlauf: Es verlässt die Schleife, wenn i {b} ist.`,
  'modelli.break-continue.frase-3': `{hai}: Das break kommt vor dem {l}: {b} wird nicht ausgegeben.`,
  'modelli.do-while.cosa': 'diese do-while-Schleife',
  'modelli.do-while.concetto': 'Die do-while-Schleife prüft die Bedingung am Ende jedes Durchlaufs: Der Rumpf läuft immer mindestens einmal.',
  'modelli.do-while.frase': `{hai}: Das würde eine while-Schleife machen. Die do-while-Schleife führt den Rumpf aus, bevor sie prüft.`,
  'modelli.do-while.frase-3': 'Die do-while-Schleife fügt keinen Durchlauf hinzu: Sie prüft die Bedingung am Ende jedes Durchlaufs.',
  'modelli.do-while.frase-4': 'Nach dem ersten Durchlauf ist die Bedingung schon falsch.',
  'modelli.do-while.frase-2': `{hai}: ein Durchlauf zu viel. {vero}`,
  'modelli.do-while.frase-5': `{hai}: Das käme mit \`i {op}= {b}\` heraus. Mit \`i {op} {b}\` hört die Schleife auf, wenn i bei {b} ankommt.`,
  'modelli.do-while.frase-6': `{hai}: Du hast i so ausgegeben, wie es vor dem letzten Durchlauf war. Auch der letzte Durchlauf ändert i: Die Prüfung kommt danach.`,
  'modelli.ternario.cosa': 'diese Ternäroperatoren',
  'modelli.ternario.concetto': '`c ? x : y` ist x, wenn c wahr ist, y, wenn c falsch ist.',
  'modelli.ternario.frase-m-vera': `{hai}: Für m hast du den falschen Zweig genommen. \`a > b\` ist wahr, also gilt der Wert nach \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai}: Für m hast du den falschen Zweig genommen. \`a > b\` ist falsch, also gilt der Wert nach \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai}: Für d hast du den falschen Zweig genommen. \`a < b\` ist wahr, also gilt der Wert nach \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai}: Für d hast du den falschen Zweig genommen. \`a < b\` ist falsch, also gilt der Wert nach \`:\`.`,
  'modelli.ternario.frase-7': `{hai}: Du hast beide Ternäroperatoren verkehrt herum gelesen. Wahr → der Wert nach \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` hört vor {b2} auf: Der letzte Durchlauf hat i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai}: Das würde \`{b}\` ausgeben. range hört vor der zweiten Zahl auf.`,
  'modelli.for-minore.python.frase-2': `{hai}: Du hast den ersten Durchlauf übersprungen. range startet genau bei {a}.`,
  'modelli.for-minore.python.frase-3': `{hai}: Du hast einen Durchlauf zu früh aufgehört. \`{b}\` geht bis {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` geht in {s2}er-Schritten und hört vor {b} auf: Auch {b2} wird ausgegeben.`,
  'modelli.for-passo.python.frase': `{hai}: Das würde \`{s}\` ausgeben. Hier ist die zweite Zahl {b}, also wird auch {b2} ausgegeben.`,
  'modelli.for-passo.python.frase-2': `{hai}: range startet bei {a}, nicht bei {s}. Der Schritt kommt nach dem ersten Durchlauf dazu.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` zählt rückwärts und hört vor {l} auf: {l} wird nicht ausgegeben.`,
  'modelli.for-indietro.python.frase': `{hai}: Du hast auch {l} ausgegeben. range hört vorher auf: Der letzte Durchlauf hat i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai}: range startet genau bei {n}: Der erste Durchlauf gibt {n} aus.`,
  'modelli.for-indietro.python.frase-3': `{hai}: Du hast einen Durchlauf zu früh aufgehört. Auch {l} wird ausgegeben.`,
  'modelli.while-somma.python.concetto': 'Die while-Schleife endet, wenn die Bedingung falsch wird: Nach `while i < n` hat i den Wert n.',
  'modelli.while-somma.python.frase': `{hai}: Das wäre so, als käme \`i += 1\` vor \`s += i\`. Hier addiert s erst i, und erst danach wächst i.`,
  'modelli.while-dimezza.python.concetto': '`//` ist die Ganzzahldivision: 7 // 2 ergibt 3, und beim Halbieren kommt man ohne Nachkommastellen bei 1 an.',
  'modelli.while-dimezza.python.frase': `{hai}: Du hast die Nachkommastellen behalten, wie es \`n /= 2\` tun würde. \`n //= 2\` ist die Ganzzahldivision: Sie wirft die Nachkommastellen weg.`,
  'modelli.array-somma.python.frase': `{hai}: Du hast das letzte weggelassen. \`range({k})\` geht bis {k2}: Der letzte Durchlauf liest \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` ist die Ganzzahldivision; `/` behält in Python immer die Nachkommastellen, auch zwischen zwei ints.',
  'modelli.media-array.python.frase': `{hai}: \`s // {k}\` ist die Ganzzahldivision: Die Nachkommastellen gehen verloren.`,
  'modelli.media-array.python.frase-2': `{hai}: In Python behält \`/\` die Nachkommastellen, es schneidet nicht ab wie \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai}: \`//\` rundet nicht: Es geht nach unten.`,
  'modelli.media-array.java.frase': `{hai}: \`s / {k}\` ist zwischen zwei ints: In Java (wie in C, nicht wie in Python) bleibt die Division ganzzahlig, und die Nachkommastellen gehen verloren.`,
  'modelli.divisione-double.java.frase': `{hai}: \`a / b\` wird zwischen ints berechnet, bevor es in m landet. In Java schneidet die Division zwischen zwei ints ab, wie in C: Der double bekommt eine schon abgeschnittene Zahl.`,
  'modelli.diviso-due.python.concetto': 'In Python ist `//` die Ganzzahldivision, und `/` behält immer die Nachkommastellen, auch zwischen zwei ints.',
  'modelli.diviso-due.python.frase': `{hai}: \`a // 2\` ist die Ganzzahldivision: Sie ergibt einen int, ohne Nachkommastellen.`,
  'modelli.diviso-due.python.frase-2': `{hai}: In Python schneidet \`/\` nicht ab wie in C oder Java: Auch \`a / 2\` behält die Nachkommastellen.`,
  'modelli.diviso-due.python.frase-3': `{hai}: \`a // 2\` rundet nicht: Es geht nach unten.`,
  'modelli.resto-negativi.python.concetto': 'In Python geht `//` nach unten, und der Rest hat das Vorzeichen des Divisors: -7 // 3 ergibt -3 und -7 % 3 ergibt 2.',
  'modelli.resto-negativi.python.frase': `{hai}: So machen es C und Java, die Richtung null abschneiden. In Python geht \`//\` nach unten.`,
  'modelli.resto-negativi.python.frase-2': `{hai}: In Python hat der Rest das Vorzeichen des Divisors, also von b, nicht des Dividenden.`,
  'modelli.resto-negativi.python.frase-3': `{hai}: \`//\` rundet nach unten, nicht Richtung null.`,
  'modelli.piu-uguale.python.frase': `{hai}: \`range(1, {n})\` geht bis {n2}: Auch i = {n2} macht seinen Durchlauf.`,
  'modelli.swap-valore.python.concetto': 'Die Funktion bekommt die Werte: a und b in der Funktion neu zuzuweisen ändert x und y nicht.',
  'modelli.swap-valore.python.frase': `{hai}: a und b sind Namen der Funktion. Sie neu zuzuweisen ändert x und y nicht.`,
  'modelli.swap-valore.python.frase-2': `{hai}: In der Funktion findet der Tausch wirklich statt. Getauscht werden a und b, nicht x und y.`,
  'modelli.array-in-funzione.python.concetto': 'Die Liste kommt so, wie sie ist, in der Funktion an: `v[n] *= …` ändert wirklich a. n dagegen ist ein Name der Funktion: `n -= 1` ändert das äußere n nicht.',
  'modelli.array-in-funzione.python.frase': `{hai}: Eine Liste wird nicht kopiert. Die Funktion arbeitet auf denselben Elementen wie a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai}: n dagegen nicht. Das \`n -= 1\` der Funktion ändert das äußere n nicht.`,
  'modelli.array-in-funzione.java.concetto': 'Ein Array wird als Referenz übergeben: Die Funktion ändert wirklich a. Ein int dagegen wird als Kopie übergeben.',
  'modelli.somma-cifre.python.concetto': '`n % 10` ist die letzte Ziffer, `n // 10` entfernt die letzte Ziffer. Der Basisfall gibt die übrige Ziffer zurück.',
  'modelli.ricorsione-ordine.python.concetto': 'print kommt nach dem Aufruf: Ausgegeben wird beim Zurückkehren, also von der kleinsten zur größten Zahl.',
  'modelli.ricorsione-ordine.python.frase': `{hai}: So wäre es mit print vor dem Aufruf. Hier wird beim Zurückkehren ausgegeben.`,
  'modelli.annidati-conta.python.concetto': 'Die innere Schleife startet bei jedem Durchlauf der äußeren neu: `range(i)` macht i Durchläufe, also 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai}: Das käme mit \`range(i + 1)\` heraus. Bei i = 0 macht \`range(i)\` keinen einzigen Durchlauf.`,
  'modelli.annidati-stelle.python.concetto': 'Für jede Zeile i gibt die innere Schleife i Zeichen aus, dann macht `print()` einen Zeilenumbruch.',
  'modelli.annidati-stelle.python.frase': `{hai}: ein Zeichen zu viel pro Zeile. \`range(i)\` macht i Durchläufe, nicht i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai}: Die letzte Zeile fehlt. \`range(1, {n})\` geht bis {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'Für jede Zeile i gibt die innere Schleife i Zeichen aus, dann macht `println()` einen Zeilenumbruch.',
};
