// Der Plan für alle, die arbeiten (js/ore.js): die „etwa“-Zeiten, die Zeilen der Woche, was nicht reinpasst, die Optionen.
export default {
  'ore.circa-min': 'etwa {m} Min.',
  'ore.circa-ore': { one: 'etwa {n} Stunde', other: 'etwa {n} Stunden' },
  'ore.circa-h': 'etwa {h} Std.',
  'ore.circa-h-min': 'etwa {h} Std. {m}',
  'ore.opzione-cuscinetto': 'Ich nutze auch die Puffertage',
  'ore.opzione-un-ripasso': 'Nur eine Wiederholung für neue Themen, nicht zwei',
  'ore.opzione-tetto': 'An Arbeitstagen lerne ich 3 Stunden, nicht 2',
  'ore.giorni-brevi': ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  'ore.libere': '{circa} frei',
  'ore.niente-ore-libere': 'keine freie Zeit',
  'ore.giorno': '{g} {n}.',
  'ore.lavoro': 'Arbeit {turni}',
  'ore.voce-tema': 'Prüfungsaufgabe ({circa})',
  'ore.argomento': 'Thema',
  'ore.voce-generale': 'allgemeine Wiederholung ({circa})',
  'ore.esame': 'Prüfung',
  'ore.voce-cuscinetto': '{nome}: Puffertag zum Aufholen',
  'ore.oggi-niente': 'Heute hast du keine freie Zeit zum Lernen{lav}.',
  'ore.oggi-hai': 'Heute hast du {liberi}{lav}: {lista}.',
  'ore.oggi-hai-vuoto': 'Heute hast du {liberi}{lav}. Im Plan steht heute nichts.',
  'ore.per-esame': '{circa} für {nome}',
  'ore.un-esame': 'eine Prüfung',
  'ore.mancano': 'Bis zur Prüfung {nome} fehlen dir {circa}.',
  'ore.questo-esame': 'diese Prüfung',
  'ore.recuperi': '{testo} · du holst {circa} auf',
  'ore.ripiego': 'Mit deiner freien Zeit passt nicht alles rein. Du kannst mir mehr Lerntage schreiben („ich lerne von 9 bis 21“) oder an den nächsten Prüfungstermin denken: Du entscheidest.',
  'ore.mancano-ancora': 'Dir fehlen noch {circa}.',
  'ore.ora-ci-sta': 'Jetzt passt es.',
};
