// Texte der Seite unter der Leiste (Deutsch): Begrüßung, Zahlen zum Studium, Prüfungskarten, Notenübersicht, Stapel,
// Fenster für Prüfung und Einstellungen, Backup.
export default {
  // saluto e riga sotto
  'pagina.saluto-notte': 'Noch wach',
  'pagina.saluto-mattina': 'Guten Morgen',
  'pagina.saluto-pomeriggio': 'Guten Tag',
  'pagina.saluto-sera': 'Guten Abend',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} Karte zu wiederholen', other: '{n} Karten zu wiederholen' },
  'pagina.sotto-serie': { one: '{n} Tag am Stück', other: '{n} Tage am Stück' },
  'pagina.sotto-niente': 'Heute steht nichts aus.',
  'pagina.sotto-vuoto': 'Deine Noten, dein Lernplan und deine Wiederholung. Alles hier, alles deins.',
  // testata
  'pagina.sottotitolo': 'Lernassistent',
  'pagina.esporta': 'Exportieren',
  'pagina.impostazioni': 'Einstellungen',
  'pagina.suggerimento': 'Fahr über die Leiste oben, drück <kbd>/</kbd> zum Schreiben oder halt <kbd>{tasti}</kbd> gedrückt zum Sprechen.',
  // i numeri
  'pagina.media-ponderata': 'Gewichteter Schnitt',
  'pagina.media-dettaglio': { one: 'arithmetisch {media} · {n} Note', other: 'arithmetisch {media} · {n} Noten' },
  'pagina.primo-voto': 'trag die erste Note über die Leiste ein',
  'pagina.base-laurea': 'Abschlussbasis (Italien)',
  'pagina.base-formula': 'Schnitt × 110 / 30',
  'pagina.crediti': 'Credits',
  'pagina.cfu-alla-laurea': '{n} ECTS bis zum Abschluss',
  'pagina.questa-settimana': 'Diese Woche',
  'pagina.minuti-settimana': 'Lernminuten in den letzten 7 Tagen',
  'pagina.giorno-ore': '{giorno}: {ore}',
  'pagina.iniziali-giorni': ['S', 'M', 'D', 'M', 'D', 'F', 'S'],
  // esami
  'pagina.prossimi-esami': 'Nächste Prüfungen',
  'pagina.nuovo-esame': 'Neue Prüfung',
  'pagina.vuoto-scrivi': 'Schreib in die Leiste oben:',
  'pagina.vuoto-comando': 'Prüfung Analysis 2 am 15. Januar 9 ECTS',
  'pagina.vuoto-oppure': 'oder {bottone}',
  'pagina.prova-esempio': 'probier es mit den Beispieldaten',
  'pagina.programma-aggiungi': '+ Prüfungsstoff',
  'pagina.giorno-cuscinetto': 'Puffertag',
  'pagina.ripasso-generale': 'allgemeine Wiederholung',
  'pagina.niente-di-nuovo': 'nichts Neues',
  'pagina.programma-pronto': '<b>{pct} % des Stoffs</b> · heute: {oggi}',
  'pagina.data-da-decidere': 'Datum offen',
  'pagina.quando-cfu': '{quando} · {cfu} ECTS',
  'pagina.giorni-maiuscolo': { one: 'TAG', other: 'TAGE' },
  'pagina.ore-studiate': '{fatte} von {tot} Std. gelernt',
  'pagina.ore-oggi': '<b>{h} Std.</b> heute',
  'pagina.oggi-in-pari': 'heute im Plan',
  'pagina.focus': 'Fokus',
  'pagina.ripassa': 'Wiederholen',
  'pagina.ripassa-n': '{n} wiederholen',
  'pagina.interrogami': 'Frag mich ab',
  'pagina.modifica-segna-voto': 'Bearbeiten · Note eintragen',
  // libretto e ripasso
  'pagina.libretto': 'Notenübersicht',
  'pagina.segna-voto': 'Note eintragen',
  'pagina.ripasso': 'Wiederholung',
  'pagina.da-file': 'Aus Datei',
  'pagina.libretto-vuoto': 'Noch keine Prüfung abgelegt. Schreib in die Leiste <kbd>ich hab 28 in Physik</kbd>.',
  'pagina.col-esame': 'Prüfung',
  'pagina.col-cfu': 'ECTS',
  'pagina.col-voto': 'Note',
  'pagina.col-data': 'Datum',
  'pagina.idoneo': 'bestanden',
  'pagina.voto-lode': '{voto}L',
  'pagina.modifica-esame': '{nome} bearbeiten',
  'pagina.libretto-esami': '{n} Prüfungen · {cfu} ECTS',
  'pagina.libretto-media': 'Schnitt <b>{media}</b> · Basis <b>{base}</b>',
  'pagina.mazzi-vuoto': 'Noch keine Karten. Schreib <kbd>Karte: Frage = Antwort</kbd> oder zieh ein PDF ins Fenster.',
  'pagina.esame-tolto': 'Prüfung entfernt',
  'pagina.senza-esame': 'Ohne Prüfung',
  'pagina.n-carte': { one: '{n} Karte', other: '{n} Karten' },
  'pagina.da-ripassare-oggi': 'heute zu wiederholen',
  'pagina.piede': 'Lode ist Open Source (MIT). Deine Daten bleiben in diesem Browser: kein Konto, kein Server.',
  'pagina.importa-backup': 'Backup importieren',
  // finestra dell'esame
  'pagina.esame-correggi': 'Korrigier die Daten oder trag die Note ein.',
  'pagina.esame-aiuto': 'Du kannst es auch in die Leiste schreiben: „Prüfung Physik 2 am 20. Februar 6 ECTS“.',
  'pagina.campo-nome': 'Name',
  'pagina.esempio-esame': 'Analysis 2',
  'pagina.campo-cfu': 'ECTS',
  'pagina.campo-data': 'Datum',
  'pagina.campo-data-appello': 'Prüfungsdatum',
  'pagina.campo-voto': 'Note',
  'pagina.campo-voto-nota': 'leer, wenn du sie noch nicht geschrieben hast',
  'pagina.trenta-e-lode': '30 cum laude',
  'pagina.idoneita': 'Unbenotet (bestanden)',
  'pagina.campo-ore': 'Geplante Lernstunden',
  'pagina.campo-ore-nota': 'für den Plan',
  'pagina.ore-segnaposto': '10 × ECTS',
  'pagina.elimina': 'Löschen',
  'pagina.annulla': 'Abbrechen',
  'pagina.salva': 'Speichern',
  'pagina.conferma-elimina': '{nome} löschen? Die Stunden und Karten bleiben, ohne Prüfung.',
  'pagina.esame-eliminato': 'Prüfung gelöscht',
  'pagina.salvato': 'Gespeichert',
  'pagina.esame-aggiunto': 'Prüfung hinzugefügt',
  // finestra delle impostazioni
  'pagina.impostazioni-aiuto': 'Alles bleibt auf diesem Computer. Der Schlüssel deiner KI geht nur an den Dienst, den du wählst.',
  'pagina.campo-tuo-nome': 'Dein Name',
  'pagina.esempio-nome': 'Giulia',
  'pagina.campo-corso': 'Studiengang',
  'pagina.esempio-corso': 'Informatik',
  'pagina.campo-cfu-laurea': 'ECTS für den Abschluss',
  'pagina.campo-lode-vale': 'Cum laude zählt als',
  'pagina.campo-focus': 'Fokus (Minuten)',
  'pagina.campo-pausa': 'Pause (Minuten)',
  'pagina.rintocco': 'Gong am Ende des Fokus',
  'pagina.aspetto-chiaro': 'Helles Design',
  'pagina.campo-ai': 'Deine KI',
  'pagina.campo-ai-nota': 'optional, nach Verbrauch: Du bezahlst den Dienst',
  'pagina.solo-locale': 'Nur das lokale Gehirn (kostenlos)',
  'pagina.campo-chiave': 'Schlüssel',
  'pagina.campo-chiave-nota': 'wird auf der Website des Dienstes erstellt',
  'pagina.chiave-segnaposto': 'Schlüssel einfügen',
  'pagina.voce-alta': 'Antworten laut vorlesen',
  'pagina.ai-attiva': 'KI <b>aktiv</b>: {nome}.',
  'pagina.senza-chiave': 'Ohne Schlüssel funktioniert Lode trotzdem: Befehle, Timer, Notenübersicht und Wiederholung laufen alle lokal; in der App gibt es auch das kostenlose lokale Gehirn.',
  'pagina.cancella-tutto': 'Alles löschen',
  'pagina.conferma-azzera': 'Alle Lode-Daten aus diesem Browser löschen? Exportier sie lieber vorher.',
  'pagina.dati-cancellati-chiave': 'Daten gelöscht, auch der Schlüssel für {nome}: Widerruf ihn auch in deinem Konto ({sito})',
  'pagina.dati-cancellati': 'Daten gelöscht',
  'pagina.chiave-cancellata': 'Schlüssel für {nome} hier gelöscht: Widerruf ihn auch in deinem Konto ({sito})',
  'pagina.impostazioni-salvate': 'Einstellungen gespeichert',
  'pagina.ai-collegata': '{nome} verbunden',
  'pagina.ai-collegata-modello': '{nome} verbunden · {modello}',
  'pagina.chiave-non-valida': 'Der Schlüssel ist ungültig',
  'pagina.chiave-non-verificabile': 'Ich kann den Schlüssel gerade nicht prüfen',
  // backup e dati di esempio
  'pagina.backup-scaricato': 'Backup heruntergeladen',
  'pagina.conferma-importa': 'Die aktuellen Daten durch dieses Backup ersetzen?',
  'pagina.backup-importato': 'Backup importiert',
  'pagina.non-backup': 'Diese Datei ist kein Backup von Lode',
  'pagina.conferma-esempio': 'Beispieldaten statt deiner Daten laden?',
  'pagina.esempio-caricato': 'Beispieldaten geladen: Fahr über die Leiste oben',
};
