// «Projekt verfolgen» in der Leiste (Deutsch): Pille, Karten «Verfolge ich…?», «Was sich gerade ändert»,
// «Fertig. In einfachen Worten», «Getestet?» und «Neues».
export default {
  'progetto.solo-app': 'Ein Projekt verfolgen geht nur in der Desktop-App von Lode.',
  'progetto.provo': 'ich teste…',
  'progetto.file-cambiati': '{n} Dateien +{piu} −{meno}',
  'progetto.fatto-non-provato': 'fertig · nicht getestet',
  'progetto.oggi-non-provato': '{nome}: nicht getestet',
  'progetto.oggi-esito': '{nome}: {breve}',
  'progetto.oggi-sta-cambiando': '{nome}: ändert sich gerade',
  'progetto.ultima-prova-alle': 'Der letzte Test, um {ora}',
  'progetto.vedi': 'Ansehen',
  'progetto.esito': 'Ergebnis',
  'progetto.prova': 'Testen',
  'progetto.provato': 'Getestet?',
  'progetto.cosa-e-cambiato': 'Was sich geändert hat',
  'progetto.cosa-sta-cambiando': 'Was sich gerade ändert',
  'progetto.serve-seguito': 'Dafür brauchst du ein Projekt, das die App verfolgt: Schreib „Projekt verfolgen“.',
  'progetto.non-seguo-nome': 'Ich verfolge kein Projekt namens „{nome}“.',
  'progetto.non-seguo-niente': 'Ich verfolge kein Projekt. Schreib **Projekt verfolgen** und wähl den Ordner deines Praktikums.',
  'progetto.capito-testo': 'Lode sieht sich die Dateien an und prüft, ob der Code getestet ist: Es schreibt keinen Code für dich. Wenn du einen Agenten oder eine KI nutzt, entscheidet dein Kurs, was erlaubt ist: Frag deine:n Dozent:in. Das Tagebuch ist ein Protokoll für dich, kein Beweis für den Prof: Es ist das, was Lode gesehen hat, und Lode weiß nicht, wer die Zeilen geschrieben hat. Für eine benotete Abgabe markier das Projekt als „benotet“: Lode sagt dir, wo du nachsehen musst und was ein Fehler bedeutet, zeigt dir aber nicht die Korrektur.',
  'progetto.prima-di-cominciare': 'Bevor du loslegst',
  'progetto.ho-capito': 'Verstanden',
  'progetto.solo-app-desktop': 'Ein Projekt verfolgen geht nur in der **Desktop-App** von Lode: Dort sehe ich mir den Ordner deines Praktikums an.',
  'progetto.va-bene-non-seguo': 'Okay, ich verfolge nichts.',
  'progetto.seguo-gia': 'Ich verfolge schon **{nome}**.',
  'progetto.seguo-domanda': '<b>{nome}</b> verfolgen?',
  'progetto.seguo-aria': '{nome} verfolgen?',
  'progetto.seguo-spiega': 'Ich sehe mir die Dateien an und speichere die Versionen im Ordner von Lode: In deinen Ordner schreibe ich nicht. Die Befehle, die du bestätigst (zum Beispiel make), schon, wie im Terminal. Ich weiß nicht, wer die Zeilen schreibt (du, ein Agent oder Copy-Paste): Ich sage dir, was sich geändert hat und ob du es getestet hast.',
  'progetto.nota-windows': 'Solange ich ihn verfolge, lässt dich Windows den Ordner nicht umbenennen oder verschieben: Schreib vorher „nicht mehr verfolgen“.',
  'progetto.corso': 'Kurs',
  'progetto.nessun-corso': 'Kein Kurs',
  'progetto.valutato': 'Benotetes Projekt (Abgabe)',
  'progetto.valutato-spiega': 'Ich sage dir, wo du nachsehen musst, aber keine fertigen Korrekturen',
  'progetto.no-diario': 'Für dieses Projekt kein Tagebuch schreiben',
  'progetto.no-diario-spiega': 'Im Vault landen keine Datei- oder Funktionsnamen',
  'progetto.n-file': { one: '{n} Datei', other: '{n} Dateien' },
  'progetto.segui': 'Verfolgen',
  'progetto.annulla': 'Abbrechen',
  'progetto.annullato': 'Abgebrochen.',
  'progetto.non-seguo-niente-nota': 'Ich verfolge nichts.',
  'progetto.seguo-fatto': 'Ich verfolge {nome}.',
  'progetto.seguo-fatto-nota': 'Ich sage dir, was sich ändert und ob du es getestet hast. Die Versionen speichere ich im Ordner von Lode.',
  'progetto.seguo-sintesi': 'verfolge {nome}',
  'progetto.smetto-domanda': '<b>{nome}</b> nicht mehr verfolgen?',
  'progetto.smetto-spiega': 'Ich lösche die Kopien, die ich im Ordner von Lode gespeichert habe. Deine Dateien fasse ich nicht an.',
  'progetto.smetti-di-seguire': 'Nicht mehr verfolgen',
  'progetto.continuo-a-seguire': 'Ich verfolge {nome} weiter.',
  'progetto.non-seguo-piu': 'Ich verfolge {nome} nicht mehr.',
  'progetto.non-seguo-piu-nota': 'Die Kopien von Lode sind weg. Deine Dateien habe ich nicht angefasst.',
  'progetto.smesso-sintesi': '{nome} beendet',
  'progetto.etichetta-nuovo': 'neu',
  'progetto.etichetta-tolto': 'entfernt',
  'progetto.etichetta-grande': 'große Datei: nur die Zahlen',
  'progetto.etichetta-spazi': 'nur Leerzeichen oder Zeilenumbrüche',
  'progetto.etichetta-cambiato': 'geändert',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Schließen',
  'progetto.diff-grande': 'Große Datei (+{piu} −{meno}): Die Details zeige ich nicht.',
  'progetto.diff-solo-spazi': 'Es ändern sich nur Leerzeichen am Zeilenende oder Zeilenumbrüche.',
  'progetto.diff-aria': 'Änderungen an {file}',
  'progetto.diff-tagliato': '… den Rest zeige ich nicht',
  'progetto.niente-di-diverso': 'Nichts anders.',
  'progetto.niente-di-nuovo': 'Nichts Neues.',
  'progetto.niente-di-nuovo-dalle': 'Nichts Neues seit {ora}.',
  'progetto.nome-dalle': '{nome} seit {ora}',
  'progetto.prova-adesso': 'Jetzt testen',
  'progetto.visto': 'Gesehen',
  'progetto.provato-breve': 'getestet',
  'progetto.prova-il-progetto': 'Projekt testen',
  'progetto.visto-fatto': 'Gesehen.',
  'progetto.visto-nota': 'Ab jetzt zeige ich dir nur die neuen Änderungen.',
  'progetto.visto-sintesi': 'gesehen',
  'progetto.fatto-titolo': 'Fertig. In einfachen Worten',
  'progetto.vedi-le-modifiche': 'Änderungen ansehen',
  'progetto.modifiche-tratto': 'Änderungen · {da}–{a}',
  'progetto.provato-si': '**Ja**: Der Code von {nome} ist der, der um {ora} getestet wurde ({breve}).',
  'progetto.provato-no-cambiato': '<b>Nein</b>: Nach dem letzten Test ({ora}) hat sich der Code von {nome} geändert.',
  'progetto.provato-no-cambiato-alle': '<b>Nein</b>: Nach dem letzten Test ({ora}) hat sich der Code von {nome} geändert, zuletzt um {ultima}.',
  'progetto.provato-no-mai': '<b>Nein</b>: {nome} hast du mit Lode noch nicht getestet.',
  'progetto.provato-nota': 'Ich weiß nicht, wer die Zeilen geschrieben hat: Ich weiß nur, ob der aktuelle Code durch einen Test gegangen ist.',
  'progetto.comando-manca': 'Um {nome} zu testen, fehlt {cosa}',
  'progetto.comando-come': 'Wie teste ich {nome}?',
  'progetto.comando-lancia': 'Jetzt gibt es .in/.out-Tests: Um das Programm zu starten, brauche ich nochmal dein Ja.',
  'progetto.comando-cambiato': 'Die Dateien des Projekts haben sich geändert: Der Befehl von vorhin reicht nicht mehr.',
  'progetto.comando-userei': 'Zum Testen würde ich <code>{comando}</code> nehmen',
  'progetto.comando-nota': 'Ich führe nur den Befehl aus, den du im Systemfenster bestätigst, nie einen, den ein Agent vorschlägt. Das ist keine Sandbox: Das Programm läuft auf deinem Rechner, wie im Terminal, und kann Dateien in deinen Ordner schreiben.',
  'progetto.riprova': 'Nochmal versuchen',
  'progetto.usa-questo': 'Den nehmen',
  'progetto.scrivo-io': 'Ich schreibe den Befehl selbst',
  'progetto.cambia': 'Ändern',
  'progetto.comando-aria': 'Befehl zum Testen',
  'progetto.usa-questo-comando': 'Diesen Befehl nehmen',
  'progetto.non-eseguo': 'Ich führe nichts aus.',
  'progetto.non-confermato': 'Du hast den Befehl nicht bestätigt.',
  'progetto.comando-confermato': 'Befehl bestätigt.',
  'progetto.comando-confermato-nota': 'Für dieses Projekt nehme ich ihn immer, solange sich die Dateien nicht grundlegend ändern.',
  'progetto.comando-confermato-sintesi': 'Befehl bestätigt',
  'progetto.uscita-caso': '— Test {caso} —',
  'progetto.non-seguo-questo': 'Dieses Projekt verfolge ich nicht.',
  'progetto.sto-gia-provando': 'Ich teste dieses Projekt schon: einen Moment.',
  'progetto.niente': 'nichts',
  'progetto.riga-vuota': 'eine leere Zeile',
  'progetto.caso-ok': 'Test {caso}',
  'progetto.caso-ok-codice': 'Test {caso} · bestanden, aber das Programm endet mit Code {codice}',
  'progetto.caso-errore': 'Test {caso}: {errore}',
  'progetto.caso-scaduto': 'Test {caso}: nicht rechtzeitig fertig geworden. Eine Schleife, die nicht aufhört, oder wartet das Programm auf weitere Eingaben?',
  'progetto.caso-troncato': 'Test {caso}: hat zu viel ausgegeben (über 200 KB), ich habe ihn gestoppt.',
  'progetto.caso-crash': 'Test {caso}: Das Programm ist mit einem Fehler abgebrochen.',
  'progetto.caso-crash-segnale': 'Test {caso}: Das Programm ist mit einem Fehler abgebrochen ({segnale}).',
  'progetto.caso-crash-codice': 'Test {caso}: Das Programm ist mit einem Fehler abgebrochen (Code {codice}).',
  'progetto.caso-diverso': 'Test {caso} · Zeile {riga}: erwartet {atteso}, bekommen {ottenuto}',
  'progetto.sintassi-ok': 'Die Syntax passt',
  'progetto.sintassi-errore': 'Syntaxfehler',
  'progetto.make-ok': 'make hat geklappt',
  'progetto.make-errore': 'make hat nicht geklappt',
  'progetto.compila': 'Kompiliert',
  'progetto.non-compila': 'Kompiliert nicht',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si}, und der Test ist bestanden.', other: '{si}, und alle {n} Tests sind bestanden.' },
  'progetto.esito-senza-prove': '{si}. Es gibt keine .in/.out-Tests: Das Programm habe ich nicht gestartet.',
  'progetto.esito-non-passano': { one: 'Ein Test von {tot} schlägt fehl.', other: '{n} von {tot} Tests schlagen fehl.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no}: {file}.',
  'progetto.non-compila-file-riga': '{no}: {file}, Zeile {riga}.',
  'progetto.non-partita': 'Der Test ist nicht gestartet.',
  'progetto.passano': 'Bestanden: {nomi}',
  'progetto.saltate': { one: 'Ein Test übersprungen: {motivo}.', other: '{n} Tests übersprungen: {motivo}.' },
  'progetto.avvisi': { one: '{n} Compiler-Warnung.', other: '{n} Compiler-Warnungen.' },
  'progetto.cambiato-durante': '<b>Der Code hat sich während des Tests geändert: nochmal?</b>',
  'progetto.rifai': 'Nochmal',
  'progetto.prova-di-nuovo': 'Nochmal testen',
  'progetto.nota-cose-nuove': 'Aus dem Wörterbuch von Lode: nur Funktionen der Standardbibliothek. Es sieht keine Ideen, nur Namen.',
  'progetto.file-riga': '{file}, Zeile {riga}',
  'progetto.domanda-orale': 'Prüfungsfrage:',
  'progetto.risposta': 'Antwort',
  'progetto.cose-nuove': 'Neues: {nomi}',
  'progetto.mettila-nel-ripasso': 'Zu den Lernkarten',
  'progetto.la-so-gia': 'Kann ich schon',
  'progetto.nel-ripasso': 'Bei den Lernkarten.',
  'progetto.la-sai-gia': 'kannst du schon',
};
