// Notensysteme (Deutsch): Namen, Leistungspunkte, Endnote, Mentions und Klassen (js/sistemi.js).
export default {
  'sistemi.scelta': 'Notensystem',
  'sistemi.nome.it': 'Italien · 18–30 cum laude',
  'sistemi.nome.es': 'Spanien · 0–10',
  'sistemi.nome.fr': 'Frankreich · 0–20',
  'sistemi.nome.de': 'Deutschland · 1,0–5,0',
  'sistemi.nome.pt': 'Portugal · 0–20',
  'sistemi.nome.br': 'Brasilien · 0–10',
  'sistemi.nome.uk': 'Vereinigtes Königreich · 0–100 %',
  'sistemi.nome.us': 'USA · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'Credits',
  'sistemi.crediti.uk': 'Credits',
  'sistemi.crediti.us': 'Credit Hours',
  'sistemi.ponderata': 'Gewichteter Durchschnitt',
  'sistemi.finale.it': 'Abschlussbasis (von 110)',
  'sistemi.finale.es': 'Notendurchschnitt (expediente)',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Gesamtnote',
  'sistemi.finale.pt': 'Endnote (média final)',
  'sistemi.finale.br': 'Leistungskoeffizient (CR)',
  'sistemi.finale.uk': 'Klasse',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'ohne Mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Nicht bestanden',
  'sistemi.idoneo': 'bestanden',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
