// «Was gibt das aus?», die Aufgabenkarte (Deutsch).
export default {
  'stampa.titolo': 'Was gibt das aus?',
  'stampa.anteprima': 'Was gibt das aus: {cosa}?',
  'stampa.risposta-assente': 'Diese Antwort gibt es nicht.',
  'stampa.hai-scritto-altro': 'Du hast `{uscita}` geschrieben: Das gibt das Programm nicht aus.',
  'stampa.nessuna-risposta': 'Keine Antwort.',
  'stampa.aria-codice': 'Code in {lingua}',
  'stampa.non-riesco': 'Heute kann ich keine Fragen zu {lingua} vorbereiten. Versuch es gleich nochmal.',
  'stampa.conto': '{i} von {n}',
  'stampa.scrivi-uscita': 'Schreib die genaue Ausgabe',
  'stampa.scegli-uscita': 'Wähl die Ausgabe · Tasten 1-4',
  'stampa.aria-campo': 'Was das Programm ausgibt',
  'stampa.segnaposto': 'Schreib, was es ausgibt',
  'stampa.controlla': 'Prüfen <kbd>Enter</kbd>',
  'stampa.piu-righe': 'Mehrere Zeilen? Trenn sie mit einem Leerzeichen.',
  'stampa.aria-risposta': 'Antwort {n}: {uscita}',
  'stampa.giusto': 'Richtig · von Lode berechnet',
  'stampa.stampa-giusta': 'Ausgabe: <code>{uscita}</code>.',
  'stampa.avanti': 'Weiter <kbd>Enter</kbd>',
  'stampa.com-e-andata': 'Zum Ergebnis <kbd>Enter</kbd>',
  'stampa.tutte-giuste': 'Alles richtig. Die Antworten hat Lode berechnet.',
  'stampa.da-rinforzare': 'Noch üben: {nomi}. Komm morgen wieder.',
  'stampa.secondi': { one: '{n} Sekunde', other: '{n} Sekunden' },
  'stampa.ancora-una': 'Noch eine',
  'stampa.sintesi': 'Was gibt das aus? {punti} von {tot}',
};
