// Texte der Synchronisierung zwischen den Computern (Deutsch): was verschlüsselt ist und was lesbar bleibt, die Statuszeile
// und die Hinweise (docs/SINCRONIZZAZIONE.md §10.7 und §12). Das README sagt dasselbe: siehe js/sync-testi.js.
export default {
  'sync.cifrati': 'die Daten von Lode im Tagebuch (Prüfungen, Noten, Karten und Wiederholungen, Lerneinheiten, Profil, Einstellungen): nicht die Seiten für Obsidian, die Lode daraus macht, siehe unten',
  'sync.in-chiaro': [
    'Notizen, «Sbobine» (Mitschriften), Dateien für Anki, Tagebücher in «Progetti»',
    '«Orario.md» mit den Räumen',
    'die Seiten, die Lode für Obsidian schreibt, gemacht genau aus diesen Daten: «Esami» (Noten, Schnitt, ECTS und Lernstunden pro Prüfung), «Memoria» (Lernstunden im Monat, zu welcher Tageszeit du lernst, die Serie der Tage, die falschen Definitionen und wie oft), «Home» (der nächste Prüfungstermin, wie viele Karten zu wiederholen sind), «Corsi», «Glossario»',
    'Namen, Größen und Zeiten der Dateien (wann du lernst)',
    'wie viele Computer es gibt, wie viele Dateien jeder schreibt und wie viele Aktionen in jeder Datei stehen (eine Datei pro Tag)',
    'die Gruppendatei (Salt und Passwortprüfung, wann sie entstanden ist und auf welchem Computer, der Fingerabdruck der vorherigen dati.json)',
    'wann das Passwort geändert wurde',
    'die minimale dati.json, die „Lode aktualisieren“ sagt',
  ],
  'sync.sul-computer': 'Auf dem Computer bleibt das Tagebuch von Lode lesbar, geschützt nur durch dein Benutzerkonto.',
  'sync.cronologia': 'Im Verlauf des Cloud-Dienstes bleibt, was vor dem Passwort unverschlüsselt hochgeladen wurde.',
  'sync.dimenticata': 'Wenn du das Passwort vergisst, geht nichts verloren: Jeder Computer hat seine Daten auf der Festplatte. Mit „Passwort vergessen“ wählst du ein neues, und die anderen Computer fragen dich danach.',
  'sync.nuova-password': 'Wähl ein neues Passwort. Die anderen Computer fragen dich danach. Es gehen keine Daten verloren: Jeder Computer hat seine auf der Festplatte.',
  'sync.smetti': 'Lode kopiert den Vault in einen Ordner außerhalb von {servizio} und nutzt dann diesen. Die anderen Computer synchronisieren weiter untereinander. Um überall aufzuhören, mach das auf jedem Computer.',
  'sync.la-cartella-cloud': 'dem Cloud-Ordner',
  'sync.prima': 'Bevor du synchronisierst, aktualisier Lode auf allen Computern.',
  'sync.sperimentale': 'Das ist neu und experimentell: gründlich getestet mit einem Simulator für mehrere Computer und einer fiesen Cloud, aber noch nicht von vielen Studierenden. Bevor du sie einschaltest, macht Lode eine Kopie von allem: Der jetzige Vault bleibt, wo er ist, unverändert, und die Daten von Lode kommen auch in den Ordner „copie“ der Lode-Daten. Wenn etwas nicht stimmt, erzähl es uns auf GitHub (Issues von W1kicartel/Lode).',
  // la riga di stato
  'sync.spenta': 'Aus · Prüfungen, Noten und Karten bleiben auf diesem Computer',
  'sync.fermo': 'Das Tagebuch von Lode auf diesem Computer ist nicht lesbar.',
  'sync.solo-qui': 'Nur auf diesem Computer · nicht synchronisiert',
  'sync.la-tua-cartella': 'deinem Cloud-Ordner',
  'sync.stato-password': 'Pausiert: Gib das Passwort ein, um zu synchronisieren.',
  'sync.rigenerato-altra': 'Auf einem anderen Computer wurde gleichzeitig ein anderes Passwort gewählt: Gib dieses ein.',
  'sync.rigenerato': 'Auf einem anderen Computer wurde das Passwort geändert: Gib das neue ein, um zu synchronisieren.',
  'sync.sparito': 'Der Lode-Ordner im Vault ist weg: Wurde er verschoben oder gelöscht?',
  'sync.in-arrivo': 'Ich empfange die Daten von den anderen Computern… (mit {dove})',
  'sync.da-migrare': 'Ich warte auf die Daten aus der Cloud…',
  'sync.scrittura': 'Die Festplatte ist voll (oder nicht beschreibbar): Die letzten Änderungen warten, ich versuche es selbst wieder.',
  'sync.versione': 'Synchronisiert mit {dove} · ein anderer Computer hat ein neueres Lode: aktualisier es',
  'sync.in-pari': 'Synchronisiert mit {dove}',
  'sync.in-pari-cifrato': 'Synchronisiert mit {dove} · verschlüsselt',
  'sync.in-pari-ora': 'Synchronisiert mit {dove} · geprüft um {ora}',
  'sync.in-pari-cifrato-ora': 'Synchronisiert mit {dove} · verschlüsselt · geprüft um {ora}',
  'sync.altro-stato': 'Synchronisierung: {stato}',
  'sync.in-avvio': 'startet',
  // gli avvisi
  'sync.avviso-clone': 'Dieser Computer sieht aus wie eine Kopie eines anderen: Ab jetzt hat er einen neuen Namen. Es ist nichts verloren gegangen.',
  'sync.avviso-orologio': 'Die Uhr eines anderen Computers scheint weit vorzugehen: Prüf Datum und Uhrzeit.',
  'sync.avviso-rovinato-mio': 'Eine Lode-Datei dieses Computers im Cloud-Ordner war beschädigt oder manipuliert: Ich habe sie beiseitegelegt und aus dem Tagebuch wiederhergestellt.',
  'sync.avviso-rovinato-altro': 'Eine Lode-Datei eines anderen Computers ist beschädigt oder manipuliert: Ich überspringe sie, bis sie wieder lesbar ist.',
  'sync.avviso-scrittura': 'Die Festplatte ist voll oder nicht beschreibbar: Die letzten Änderungen sind noch nicht im Tagebuch. Ich versuche es bei jeder Runde wieder und wenn du Lode schließt.',
  'sync.avviso-recupero': 'Das Tagebuch konnte nicht geschrieben werden: Die Änderungen von diesem Moment stehen in einer eigenen Datei im Datenordner von Lode.',
  'sync.avviso-portachiavi': 'Der Schlüsselbund hat das Passwort von Lode nicht herausgegeben (Zugriff verweigert, oder Lode wurde aktualisiert): Gib es nochmal ein.',
  'sync.avviso-gruppi-doppi': 'Im Cloud-Ordner gibt es zwei Lode-Gruppen, eine verschlüsselt und eine nicht: Die führe ich nicht selbst zusammen.',
  'sync.avviso-lode-vecchia': 'Eine alte Version von Lode hat Daten in .lode/dati.json geschrieben: Aktualisier sie. Sie kommen nicht von selbst rein: Eine Kopie liegt im Datenordner von Lode, und die neuen Einträge importierst du mit „Ergänzungen importieren“.',
  'sync.avviso-altra-password': 'Auf einem anderen Computer wurde gleichzeitig ein anderes Passwort gewählt: Gib dieses ein.',
  'sync.avviso-manomesso': 'Die Gruppendatei von Lode im Cloud-Ordner wurde von außen geändert (sie passt nicht zum Passwort): Ich nutze sie nicht. Prüf den Cloud-Ordner.',
  'sync.avviso-gruppo-chiaro': 'Die Gruppendatei von Lode sagt „ohne Passwort“, aber die Daten der anderen Computer sind verschlüsselt: Wurde sie manipuliert? Ich veröffentliche nichts, bis das wieder stimmt.',
  'sync.avviso-parametri': 'Dieser Vault wurde von einem neueren Lode geschützt: Aktualisier es.',
};
