// Vault-Namen (js/nomi.js), Deutsch: Ordner, Notizen, Abschnitte und Wörter, die Lode in einen neuen Vault schreibt und wieder liest.
export default {
  // cartelle (create una volta, alla nascita del vault: poi restano quelle)
  'vaultnomi.cartella-lezioni': 'Vorlesungen',
  'vaultnomi.cartella-corsi': 'Kurse',
  'vaultnomi.cartella-sbobine': 'Mitschriften',
  'vaultnomi.cartella-anki': 'Anki',
  'vaultnomi.cartella-allegati': 'Anhänge',
  'vaultnomi.cartella-materiali': 'Materialien',
  'vaultnomi.cartella-progetti': 'Projekte',
  'vaultnomi.cartella-modelli': 'Vorlagen',
  'vaultnomi.cartella-inbox': 'Eingang',
  // i «corsi» che Lode inventa quando non ce n'è uno (diventano cartelle e note)
  'vaultnomi.corso-sparsi': 'Lose Notizen',
  'vaultnomi.corso-videolezioni': 'Videovorlesungen',
  'vaultnomi.corso-varie': 'Sonstiges',
  // note (senza «.md»)
  'vaultnomi.nota-home': 'Start',
  'vaultnomi.nota-orario': 'Stundenplan',
  'vaultnomi.nota-esami': 'Prüfungen',
  'vaultnomi.nota-glossario': 'Glossar',
  'vaultnomi.nota-benvenuto': 'Willkommen',
  'vaultnomi.nota-memoria': 'Gedächtnis',
  'vaultnomi.nota-tasca': 'Für unterwegs',
  'vaultnomi.modello-lezione': 'Vorlesung',
  'vaultnomi.modello-esame': 'Prüfung',
  'vaultnomi.modello-ripasso': 'Wiederholung',
  // titoli delle sezioni che Lode scrive e rilegge
  'vaultnomi.sezione-appunti': 'Notizen',
  'vaultnomi.sezione-stella': '★ Prüfungsrelevant',
  'vaultnomi.sezione-definizioni': 'Definitionen',
  'vaultnomi.sezione-domande': 'Fragen an den Prof',
  'vaultnomi.sezione-trascrizione': 'Transkript',
  'vaultnomi.sezione-riordinati': 'Von Lode geordnete Notizen',
  'vaultnomi.titolo-note-per-lode': 'Notizen für Lode',
  'vaultnomi.titolo-cosa-ho-capito': 'Was ich verstanden habe',
  'vaultnomi.titolo-cosa-so-davvero': 'Was ich wirklich kann',
  'vaultnomi.titolo-informatica': 'Informatik',
  'vaultnomi.titolo-ripasso-in-tasca': 'Wiederholung für unterwegs',
  'vaultnomi.titolo-orario': 'Vorlesungsplan',
  'vaultnomi.titolo-lezioni': 'Vorlesungen',
  'vaultnomi.titolo-stelle-ultime': '★ Prüfungsrelevant, zuletzt',
  // il ripasso in tasca: il titolo della risposta e le due caselle (il giro le rilegge)
  'vaultnomi.parola-risposta': 'Antwort',
  'vaultnomi.parola-sapevo': 'wusste ich',
  'vaultnomi.parola-non-sapevo': 'wusste ich nicht',
  // la nota dell'orario: colonne, giorni (domenica per primo) e la riga che spiega
  'vaultnomi.orario-colonne': ['Kurs', 'Tage', 'Beginn', 'Ende', 'Raum'],
  'vaultnomi.giorni-brevi': ['so', 'mo', 'di', 'mi', 'do', 'fr', 'sa'],
  'vaultnomi.orario-spiega': 'Lode liest ihn, um zu wissen, wann du in der Vorlesung bist. Du kannst ihn hier oder in der Leiste ändern („Vorlesung Analysis 2 Montag und Mittwoch 9-11 Raum 7“).',
  // i commenti dentro le note nuove
  'vaultnomi.commento-definizioni': 'Eine pro Zeile: - **Begriff**: Definition. Lode macht daraus Gedächtnisspiele und Karten.',
  'vaultnomi.commento-corso': 'Schreib ruhig darüber oder darunter: Lodes Kasten (Vorlesungen, ★, Prüfung) aktualisiert sich selbst, den Rest fasst Lode nicht an.',
  'vaultnomi.commento-cosa-ho-capito': 'Dieser Teil gehört dir: Lode fasst ihn nie an. Was du heute verstanden hast, was dir noch nicht klar ist.',
  'vaultnomi.segnalibro-memoria': 'Was Lode über mich weiß',
  // i modelli di Obsidian e le note che nascono col vault
  'vaultnomi.esame-programma': 'Stoff',
  'vaultnomi.esame-domande': 'Fragen, die immer kommen',
  'vaultnomi.esame-domande-commento': 'Die du von anderen hörst oder in alten Klausuren findest. Lode fragt dich damit ab.',
  'vaultnomi.esame-esercizi': 'Typische Aufgaben',
  'vaultnomi.esame-manca': 'Was mir noch fehlt',
  'vaultnomi.ripasso-tre-righe': 'In drei Zeilen',
  'vaultnomi.ripasso-commento-definizioni': '- **Begriff**: Definition. Sie landen in Lodes Spielen.',
  'vaultnomi.ripasso-collegamenti': 'Verknüpfungen',
  'vaultnomi.ripasso-commento-collegamenti': 'Verwandte Vorlesungen und Begriffe: [[...]]',
  'vaultnomi.memoria-titolo': 'Was ich über dich weiß',
  'vaultnomi.memoria-commento': 'Diese Notiz schreibt Lode nach jedem Spiel. Der Abschnitt „{sezione}“ gehört dir: Ich lese ihn jedes Mal, wenn ich die KI nutze.',
  'vaultnomi.memoria-in-breve': 'Kurz gesagt',
  'vaultnomi.memoria-ancora-niente': 'Noch nichts: Notier in der Vorlesung ein paar Definitionen und spiel eine Runde.',
  'vaultnomi.memoria-note-commento': 'Schreib hier, wie ich dir helfen soll: „erklär mit Beispielen aus der Praxis“, „kurze Sätze“, „die mündliche Prüfung in Analysis ist sehr theoretisch“.',
  'vaultnomi.parola-corso': 'Kurs',
  'vaultnomi.benvenuto-firma': 'hat **Lode** eingerichtet',
  'vaultnomi.benvenuto-testo': '# Willkommen in deinem Vault\n\nDiesen Vault {firma}, der Assistent, der oben auf deinem Bildschirm wohnt. Es ist ein ganz normaler Obsidian-Vault: Die Notizen gehören dir, in Markdown, und bleiben auf diesem Computer.\n\n## Wie sie zusammenarbeiten\n- **In der Vorlesung** weiß Lode, wann du in der Vorlesung bist (aus dem [[{orario}]]), und hält die Notiz der Vorlesung in `{lezioni}/<{corso}>/` bereit. In der Leiste notierst du im Flug:\n  - **{stella}** (⌃⌥S): was der Prof angekündigt hat, dass er fragen wird;\n  - **Definition** (⌃⌥D): „Begriff: Definition“;\n  - **Frage** (⌃⌥Q): für den Prof.\n- **Deine Notizen** schreibst du hier, in Obsidian, wie immer. Die Definitionen im Abschnitt „{definizioni}“ (`- **Begriff**: Definition`) oder geschrieben als `Begriff :: Definition` findet Lode von selbst.\n- **Zu Hause** schlägt dir die Leiste zwei Minuten Spiel mit den Definitionen der letzten Vorlesung vor, genau dann, wenn sie dir zu entwischen drohen.\n- **[[{memoria}]]** (in `{lode}/`) ist das, was Lode über dich gelernt hat: sichere Definitionen, solche zum Festigen, wie du lernst. Im Abschnitt „{notePerLode}“ kannst du ihm sagen, wie es dir helfen soll.\n\n## Tastenkürzel\n| | Mac | Windows |\n|---|---|---|\n| Lode öffnen und schreiben | ⌥ Leertaste | Strg ⇧ Leertaste |\n| {stella} | ⌃⌥ S | Strg Alt S |\n| Definition | ⌃⌥ D | Strg Alt D |\n| Frage an den Prof | ⌃⌥ Q | Strg Alt Q |\n| Gedächtnisspiel | ⌃⌥ G | Strg Alt G |\n',
  // frasi della barra che citano un nome del vault: il nome arriva dal vault, non dalla lingua della barra
  'vaultnomi.frase-orario-nel-vault': 'Der Stundenplan liegt auch im Vault, in „{nota}“: Du kannst ihn in Obsidian ändern.',
  'vaultnomi.frase-nella-cartella': 'Sie liegt im Ordner {cartella} deines Vaults.',
  'vaultnomi.frase-riordinati-nota': 'Sie kommen in die Notiz, unter „{sezione}“, unter das Transkript (das bleibt). {motore} hat sie geschrieben: lies sie noch mal.',
};
