// Texte der Seiten, die Lode für Studierende in den Vault schreibt (Deutsch): Home, Prüfungen, Glossar, die Kursseiten
// und das Gedächtnis. Namen von Notizen, Ordnern, Abschnitten und Schlüsseln, die der Code wieder liest, stehen nicht
// hier: Sie bleiben im Code (sie werden die Tabelle NOMI).
export default {
  // la memoria
  'vault.prop-gioco': 'Spiele',
  'vault.prop-ripasso': 'Karten wiederholen',
  'vault.prop-stelle': 'die ★ nochmal lesen',
  'vault.prop-orale': 'schnelle Fragen',
  'vault.prop-focus': 'Fokus',
  'vault.prop-stampa': 'Was gibt das aus?',
  'vault.prop-voce': '{nome} ({si} von {tot})',
  'vault.memoria-proposte': 'Von den Vorschlägen von Lode nimmst du vor allem an: {elenco}.',
  'vault.memoria-titolo': 'Was ich über dich weiß',
  'vault.memoria-commento': 'Diese Notiz schreibt Lode. Du kannst sie lesen und auch korrigieren: Den Abschnitt „{sezione}“ lese ich jedes Mal, wenn ich die KI nutze.',
  'vault.titolo-in-breve': 'Kurz gesagt',
  'vault.memoria-lezioni': { one: '{n} Vorlesung mit Notizen', other: '{n} Vorlesungen mit Notizen' },
  'vault.memoria-definizioni': { one: '{n} Definition', other: '{n} Definitionen' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni}: **{sicure} sitzen**, {deboli} zum Festigen, {mai} noch nicht gespielt.',
  'vault.memoria-serie': { one: 'Lernserie: {n} Tag am Stück. Diesen Monat: {h} Std.', other: 'Lernserie: {n} Tage am Stück. Diesen Monat: {h} Std.' },
  'vault.memoria-fascia': 'Du lernst vor allem **{fascia}**.',
  'vault.fascia-mattina': 'morgens',
  'vault.fascia-pomeriggio': 'nachmittags',
  'vault.fascia-sera': 'abends',
  'vault.titolo-da-rinforzare': 'Zum Festigen',
  'vault.sbagliata': { one: '{n}-mal von {tot} falsch', other: '{n}-mal von {tot} falsch' },
  'vault.niente-per-ora': 'Noch nichts.',
  'vault.titolo-sicure': 'Sitzen',
  'vault.sicure-vuoto': 'Noch keine: Spiel ein paar Runden.',
  'vault.ancora-nessuna': 'Noch keine.',
  'vault.note-commento': 'Schreib hier, wie ich dir helfen soll: „erklär mir mit praktischen Beispielen“, „ich bin Legastheniker, kurze Sätze“, „die Mündliche in Analysis ist bei Rossi, sehr theoretisch“.',
  // Home
  'vault.home-carte': '{n} Karten zu wiederholen',
  'vault.alias-memoria': 'Was Lode über mich weiß',
  'vault.alias-benvenuto': 'So funktioniert es',
  'vault.titolo-oggi': 'Heute',
  'vault.aula': 'Raum {aula}',
  'vault.niente-lezioni-oggi': 'Heute keine Vorlesungen.',
  'vault.titolo-corsi': 'Kurse',
  'vault.n-lezioni': { one: '{n} Vorlesung', other: '{n} Vorlesungen' },
  'vault.idoneo': 'bestanden',
  'vault.voto-e-lode': '{voto} cum laude',
  'vault.appello': 'Prüfung {data}',
  'vault.corsi-vuoto': 'Füg den Stundenplan über die Leiste hinzu: „Vorlesung Analysis 2 Montag 9-11 Raum 7“.',
  'vault.titolo-ultime-lezioni': 'Letzte Vorlesungen',
  'vault.definizioni-n': '{n} Definitionen',
  'vault.titolo-carriera': 'Studium',
  'vault.carriera': 'Schnitt **{media}** · Abschlussbasis (Italien) **{base}**/110 · {cfu} von {tot} ECTS → {esami}',
  // Esami
  'vault.titolo-prossimi-appelli': 'Nächste Prüfungstermine',
  'vault.tabella-appelli': '| Prüfung | Datum | In | ECTS | Gelernt |',
  'vault.ore-di': '{fatte} von {tot} Std.',
  'vault.nessun-appello': 'Kein Prüfungstermin eingetragen.',
  'vault.senza-data': 'Ohne Datum: {elenco}.',
  'vault.titolo-libretto': 'Notenübersicht',
  'vault.tabella-libretto': '| Prüfung | ECTS | Note | Datum |',
  'vault.voto-l': '{voto}L',
  'vault.libretto-piede': 'Gewichteter Schnitt **{media}** · Abschlussbasis (Italien) **{base}**/110 · {cfu} von {tot} ECTS',
  'vault.libretto-vuoto': 'Noch keine Prüfung abgelegt.',
  // Glossario
  'vault.n-definizioni': { one: '{n} Definition', other: '{n} Definitionen' },
  'vault.da-rinforzare': '*zum Festigen*',
  'vault.glossario-vuoto': 'Die Definitionen aus den Vorlesungen erscheinen hier, alphabetisch und nach Kurs sortiert.',
  // la pagina del corso
  'vault.corso-cfu': '**{cfu} ECTS**',
  'vault.corso-voto': 'Note {voto}',
  'vault.corso-voto-lode': 'Note {voto} cum laude',
  'vault.corso-appello': 'Prüfung **{data}** (in {n} Tagen) · {fatte} von {tot} Std. gelernt',
  'vault.corso-lezioni': 'Vorlesungen: {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} Raum {aula}',
  'vault.lezioni-vuoto': 'Noch keine: Die erste entsteht, wenn du in der Vorlesung etwas notierst.',
};
