// The bar (js/lode.js, first part: pill, panel, home, tools, review, timetable, transcription, files), in English.
export default {
  // the keys to talk and numbers in words («Three cards to review»)
  'barra1.tasti-mac': '⌥ Space',
  'barra1.tasti': 'Ctrl ⇧ Space',
  'barra1.numeri': ['No', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'],
  // the greeting and the line at the top of the panel
  'barra1.saluto-notte': 'Still up',
  'barra1.saluto-mattina': 'Good morning',
  'barra1.saluto-pomeriggio': 'Good afternoon',
  'barra1.saluto-sera': 'Good evening',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': "{nome} is today. Good luck.",
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} card to review.', other: '{quante} cards to review.' },
  'barra1.niente-in-sospeso': 'Nothing pending today.',
  'barra1.dimmi-esame': "Tell me your next exam and I'll make the plan.",
  // the shell: field, footer, dragged files
  'barra1.aria-lode': 'Lode, study assistant',
  'barra1.aria-torna-home': 'Back to Lode home',
  'barra1.indietro': 'Back',
  'barra1.aria-campo': 'Ask or type a command',
  'barra1.campo': 'Ask or type a command…',
  'barra1.ti-ascolto': "I'm listening",
  'barra1.esc-annulla': 'Esc to cancel',
  'barra1.un-attimo': 'One moment…',
  'barra1.aria-parla': 'Talk (or hold {tasti})',
  'barra1.tieni-premuto': 'Hold to talk <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'Your data stays on this computer',
  'barra1.lascia-file': 'Drop the file here',
  'barra1.lascia-file-cosa': 'PDFs, slides, notes, photos of the board: Lode turns them into review cards',
  'barra1.dopo': 'Later',
  // «Today»: the home rows
  'barra1.di-stamattina': 'from this morning',
  'barra1.di-oggi': 'from today',
  'barra1.di-ieri': 'from yesterday',
  'barra1.di-giorno': 'from {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} {corso} definition {quando}', other: '{n} {corso} definitions {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} definition from your latest lectures', other: '{n} definitions from your latest lectures' },
  'barra1.sync-bloccata': "Lode is working with this computer's data: changes are waiting in the journal.",
  'barra1.sblocca': 'Unlock',
  'barra1.sync-sparita': "Lode's folder in the vault is gone",
  'barra1.sync-sparita-dett': "Was it moved or deleted? This computer's data is safe in its journal.",
  'barra1.vedi': 'See',
  'barra1.sync-spostamento': 'Moving to the cloud folder was interrupted',
  'barra1.sync-spostamento-dett': "Your previous vault is untouched: I'll pick up where I left off.",
  'barra1.riprendi': 'Resume',
  'barra1.detto-sincronizza': 'Sync between computers',
  'barra1.dati-altrove': 'This vault syncs with Lode on another computer',
  'barra1.dati-altrove-dett': "The data is in Lode 2's journal: choose «I already use Lode on another computer» to see it here. Changes you make now go to a separate file, not over the data.",
  'barra1.uso-gia-lode': 'I already use Lode',
  'barra1.detto-uso-gia-lode': 'I already use Lode on another computer',
  'barra1.dati-fermo': "Lode's journal on this computer can't be read",
  'barra1.dati-fermo-dett': "Nothing was deleted: Lode's data folder isn't responding (disk full or broken?).",
  'barra1.riprova': 'Try again',
  'barra1.dati-illeggibili': "I can't read your data",
  'barra1.dati-illeggibili-dett': "Exams, grades and cards are safe, but the folder isn't responding (OneDrive offline or a locked file). Changes you make now go to a separate file; I'll retry on my own.",
  'barra1.lezione-alle': '{corso} at {ora}',
  'barra1.lezione-aula-tra': 'Room {aula} · in {n} min',
  'barra1.lezione-tra': 'in {n} min',
  'barra1.appunti': 'Notes',
  'barra1.orario': 'Timetable',
  'barra1.completa-lode': 'Finish setting up Lode',
  'barra1.completa-tutti-e-due': 'Obsidian and the local brain: one click, free',
  'barra1.completa-obsidian': 'Obsidian: one click, free',
  'barra1.completa-cervello': 'the local brain: one click, free',
  'barra1.prepara': 'Set up',
  'barra1.detto-prepara-lode': 'Set up Lode',
  'barra1.chiudi-lezione-di': 'Wrap up the {corso} lecture',
  'barra1.chiudi-lezione-dett': "{n} words of notes · I'll pull out definitions and ★",
  'barra1.chiudi': 'Wrap up',
  'barra1.detto-chiudi-lezione': 'Wrap up the lecture',
  'barra1.gioco-due-minuti': 'Two-minute game',
  'barra1.gioca': 'Play',
  'barra1.esame-ore-oggi': '{data} · {ore} h today to stay on track',
  'barra1.esame-in-pari': "{data} · you're on track today",
  'barra1.focus': 'Focus',
  'barra1.ripasso': 'Review',
  'barra1.ripasso-carte-min': { one: '{n} card · about {min} min', other: '{n} cards · about {min} min' },
  'barra1.inizia': 'Start',
  'barra1.studio-oggi': '{ore} of study today',
  'barra1.non-hai-studiato': "You haven't studied yet today",
  'barra1.giorni-di-fila': { one: '{n} day in a row', other: '{n} days in a row' },
  'barra1.bastano-25': '25 minutes is enough to start a streak',
  'barra1.libretto': 'Grades',
  // in class, Repeat, transcription, home
  'barra1.in-aula': 'In class · {corso}',
  'barra1.aula-finisce-tra': 'room {aula} · ends in {n} min',
  'barra1.finisce-tra': 'ends in {n} min',
  'barra1.cattura-stella': '★ For the exam',
  'barra1.cattura-definizione': 'Definition',
  'barra1.cattura-domanda': 'Question',
  'barra1.cose-segnate': { one: '{quante} thing marked for the exam today.', other: '{quante} things marked for the exam today.' },
  'barra1.ripeti-attivo-memoria': 'Repeat on · only in memory, never on disk',
  'barra1.ripeti': 'Repeat',
  'barra1.spegni': 'Turn off',
  'barra1.ripeti-spento-invito': '<b>Repeat 60 s</b> · missed a sentence? Lode repeats it for you. Nothing is saved.',
  'barra1.trascrivi-lezione': 'Transcribe the lecture',
  'barra1.trascrivi-lezione-dett': 'Everything the lecturer says, formulas included, in your Obsidian note · {tasti}',
  'barra1.trascrizione-in-pausa': 'Paused · {min} min · {parole} words',
  'barra1.trascrizione-in-corso': 'Transcribing · {min} min · {parole} words',
  'barra1.prima-riga': 'Listening: the first line arrives in about twenty seconds.',
  'barra1.pausa': 'Pause',
  'barra1.fine': 'End',
  'barra1.oggi': 'Today',
  'barra1.cfu-di': '{fatti} of {tot} credits',
  'barra1.inizia-da-qui': 'Start here',
  'barra1.inizia-da-qui-dett': 'Type «lecture calculus 2 monday 9-11 room 7», or try the sample data',
  'barra1.esempio': 'Sample',
  // the tools and the panel header
  'barra1.strumento-gioco': 'Game',
  'barra1.strumento-codice': 'Code',
  'barra1.strumento-note': 'Notes',
  'barra1.strumento-interrogami': 'Quiz me',
  'barra1.strumento-esami': 'Exams',
  'barra1.sei-a-lezione': "You're in your {corso} lecture. Take notes calmly: I'll make sure you don't miss anything.",
  'barra1.testa-media': 'average {media}',
  'barra1.testa-serie': { one: '{n}-day streak', other: '{n}-day streak' },
  // the pill
  'barra1.ripeti-attivo-titolo': 'Repeat on: the last minute and a half, only in memory',
  'barra1.in-pausa': 'paused',
  'barra1.pausa-minuscolo': 'break',
  'barra1.aria-timer': '{cosa}: {resta} left',
  'barra1.prova-generale': 'Mock exam',
  'barra1.focus-su': 'Focus on {nome}',
  'barra1.aria-ripeti-acceso': '. Repeat: microphone on',
  'barra1.pillola-trascrizione-in-pausa': 'transcription paused · {parole} words',
  'barra1.pillola-trascrivo': 'transcribing · {parole} words',
  'barra1.fine-tra': 'ends in {n} min',
  'barra1.pillola-aula-tra': 'room {aula} · in {n} min',
  'barra1.microfono-acceso': 'microphone on',
  'barra1.due-minuti': '2 minutes',
  'barra1.pillola-tra-giorni': 'in {n} d',
  // in Italian the pill says «carte» even with a single card; in English it follows the number
  'barra1.pillola-carte': { one: '{n} card', other: '{n} cards' },
  'barra1.pillola-da-ripassare': { one: 'card to review', other: 'cards to review' },
  'barra1.passa-qui-sopra': 'hover here',
  'barra1.aria-pillola': 'Lode: {testo}{ripeti}. Hover or press {tasti}.',
  // the conversation, «Done.», «Confirm / Cancel»
  'barra1.altre-righe': { one: '{n} line', other: '{n} lines' },
  'barra1.altro': 'more',
  'barra1.fatto': 'Done.',
  'barra1.annulla': 'Cancel',
  'barra1.annullato-minuscolo': 'cancelled',
  'barra1.confermi': 'Confirm?',
  'barra1.conferma': 'Confirm',
  'barra1.scrivi-si': 'You can also type «yes».',
  'barra1.annullato': 'Cancelled.',
  'barra1.niente-cambiato': "I didn't change anything.",
  // Focus
  'barra1.durata': 'Length',
  'barra1.min': 'min',
  'barra1.su-che-cosa': 'On what',
  'barra1.studio-libero': 'Free study',
  'barra1.pausa-alla-fine': "{n}-minute break at the end. The hours count towards the exam plan.",
  'barra1.sintesi-focus': 'focus',
  'barra1.focus-di-min': '{min}-minute focus.',
  'barra1.focus-di-min-su': '{min}-minute focus on {nome}.',
  'barra1.ci-vediamo': 'See you at the break.',
  'barra1.sintesi-focus-min': 'focus {min} min',
  // Grades and «what if I get…»
  'barra1.media-ponderata': 'Weighted average',
  'barra1.aritmetica-esami': 'unweighted {media} · {n} exams',
  'barra1.nessun-voto': 'no grades yet',
  'barra1.base-di-laurea': 'Starting graduation mark',
  'barra1.serve-gia': 'To start from <b>{obiettivo}</b> you just need to pass the remaining exams.',
  'barra1.serve-media': 'To start from <b>{obiettivo}</b> you need an average of <b>{voto}</b> in the {cfu} credits left.',
  'barra1.serve-impossibile': "Starting from <b>{obiettivo}</b> isn't possible any more: aim for {punta}.",
  'barra1.e-se': 'What if…',
  'barra1.esame': 'Exam',
  'barra1.voto': 'Grade',
  'barra1.simula-esito': 'Average <b>{media}</b> <span class="{classe}">{delta}</span> · starting mark <b>{base}</b>',
  'barra1.sintesi-media-base': 'average {media}, starting mark {base}',
  'barra1.sintesi-libretto-vuoto': 'no grades yet',
  'barra1.simula-non-trovo': "I can't find **{nome}** among your exams. Add it with «exam {nome} 6 credits».",
  'barra1.simula-primo': 'With {voto} in **{nome}** your average would start at **{voto}**: starting mark **{base}**.',
  'barra1.simula-primo-lode': 'With {voto} cum laude in **{nome}** your average would start at **{voto}**: starting mark **{base}**.',
  'barra1.simula': 'With **{voto}** in {nome} your average goes from {prima} to **{dopo}** ({delta}): starting graduation mark **{base}**.',
  'barra1.simula-lode': 'With **{voto} cum laude** in {nome} your average goes from {prima} to **{dopo}** ({delta}): starting graduation mark **{base}**.',
  'barra1.sintesi-media': 'average {media}',
  // Exams
  'barra1.incolla-programma': "Paste the syllabus: I'll make you a plan by topic",
  'barra1.giorno-cuscinetto': 'buffer day',
  'barra1.ripasso-generale': 'general review',
  'barra1.niente-di-nuovo': 'nothing new',
  'barra1.pronto': '{n}% ready',
  'barra1.prossimi-appelli': 'Upcoming exams · {n}',
  'barra1.esame-riga': '{data} · {cfu} credits · {fatte} of {tot} h',
  'barra1.ore-oggi': '{ore} h today',
  'barra1.giorni-parola': { one: 'day', other: 'days' },
  'barra1.nessun-appello': 'No exams on the calendar.',
  'barra1.senza-data': 'No date: {nomi}.',
  'barra1.nuovo-esame': 'New exam',
  'barra1.nome-esame': 'Exam name',
  'barra1.cfu': 'Credits',
  'barra1.data-appello': 'Exam date',
  'barra1.aggiungi': 'Add',
  'barra1.programma-di': '{nome} syllabus',
  'barra1.esame-aggiunto': '{nome} added.',
  'barra1.senza-data-nota': 'no date',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': 'no exams',
  // Review
  'barra1.ripasso-di': 'Review · {nome}',
  'barra1.niente-da-ripassare': 'Nothing to review today. The next card comes back {quando}.',
  'barra1.nessuna-carta': 'No cards yet. Type «card: question = answer», or drag a PDF here.',
  'barra1.risposta': 'Answer',
  'barra1.aggiungi-carta': 'Add card',
  'barra1.carta-aggiunta': 'Card added.',
  'barra1.torna-oggi': "It'll come up in today's review.",
  'barra1.sintesi-niente-da-ripassare': 'nothing to review',
  'barra1.mostra-risposta': 'Show answer <kbd>Space</kbd>',
  'barra1.x-di-y': '{x} of {y}',
  'barra1.ripasso-finito': { one: 'Review done: {n} card in {min} min.', other: 'Review done: {n} cards in {min} min.' },
  'barra1.difficili-domani': 'The hard ones come back tomorrow.',
  'barra1.sintesi-carte-ripassate': { one: '{n} card reviewed', other: '{n} cards reviewed' },
  'barra1.sintesi-ripasso-di': { one: 'review of {n} card', other: 'review of {n} cards' },
  // commands to try
  'barra1.prova-a-scrivere': 'Try typing',
  'barra1.aiuto-senza-ai': 'With the local brain (free) or your own AI (type «AI») you can also ask for explanations, make cards from PDFs and get quizzed.',
  'barra1.sintesi-comandi': 'commands',
  // Timetable
  'barra1.orario-lezioni': { one: 'Timetable · {n} lecture a week', other: 'Timetable · {n} lectures a week' },
  'barra1.corso-aula': '{corso} · room {aula}',
  'barra1.punto-aula': ' · room {aula}',
  'barra1.togli': 'Remove {nome}',
  'barra1.corso': 'Course',
  'barra1.giorni': 'Days',
  'barra1.inizio': 'Start',
  'barra1.aula': 'Room',
  'barra1.orario-nel-vault': 'The timetable is also in the vault, in «Orario.md»: you can change it from Obsidian.',
  'barra1.orario-oppure-scrivi': 'Or type: «lecture calculus 2 monday and wednesday 9-11 room 7».',
  'barra1.in-orario': '{corso} added to the timetable.',
  'barra1.sintesi-lezioni-settimana': { one: '{n} lecture a week', other: '{n} lectures a week' },
  // the plan for students who work
  'barra1.ore-regola': { one: '{n} hour', other: '{n} hours' },
  'barra1.la-tua-settimana': 'Your week',
  'barra1.detto-piano-settimana': 'Week plan',
  'barra1.lavori': 'You work {turni}.',
  'barra1.lavori-nota': "I take it out of your study hours, with half an hour for travel. On work days you study at most {tetto}: change it with «on work days I study at most {altro} hours».",
  'barra1.turni-cambiati': 'Shifts changed.',
  'barra1.turni-salvati': 'Shifts saved.',
  'barra1.sintesi-lavoro': 'work {turni}',
  'barra1.turni-tolti': 'Shifts removed.',
  'barra1.turni-tolti-nota': 'The plan counts your whole study day again.',
  'barra1.giorno-non-lavori': "You're not working on {giorno}.",
  'barra1.ore-libere': 'Those hours are free for studying again.',
  'barra1.giorno-lavori-anche': "On {giorno} you're also working {da}–{a}.",
  'barra1.solo-quel-giorno': "Just that day: I'll take it out of your study hours.",
  'barra1.tetto': 'On work days you study at most {tetto}.',
  'barra1.tetto-nota': 'The plan is redone with this limit.',
  'barra1.studi-dalle': 'You study from {da} to {a}.',
  'barra1.studi-dalle-nota': 'The plan only uses these hours, minus lectures and work.',
  'barra1.togli-scelta': 'Remove: {scelta}',
  'barra1.niente-nel-piano': 'nothing in the plan',
  'barra1.settimana-lavori': "You work {turni}: I take it out of your study hours, with half an hour for travel. On work days you study at most {tetto}.",
  'barra1.settimana-se-lavori': 'If you work, tell me: «I work monday wednesday friday 14-19».',
  'barra1.settimana-un-esame': "With just one exam and no job, the plan is the syllabus plan.",
  'barra1.settimana-stime': 'Hours are estimates: a new topic about 1 h, a review about 30 min.',
  'barra1.sintesi-la-tua-settimana': 'your week',
  // quick capture in class
  'barra1.cattura-stella-campo': 'What did the lecturer say will be on the exam?',
  'barra1.cattura-definizione-campo': 'Term: definition',
  'barra1.cattura-domanda-campo': 'The question to ask the lecturer',
  'barra1.scrivila-cosi': 'Write it like this: **term: definition**.',
  'barra1.errore-vault': "I can't write to the vault: {errore}",
  'barra1.dove-sparsi': "in today's loose notes",
  'barra1.dove-in': 'in {corso}',
  'barra1.segnato-dove': '★ Marked {dove}.',
  'barra1.definizione-dove': '«{termine}» saved {dove}.',
  'barra1.domanda-dove': 'Question saved {dove}.',
  // transcribing: in class, from the computer, from a recording
  'barra1.videolezioni-app': "Video lecture transcription is in Lode's **desktop app**: it listens to the computer's audio and writes into the lecture's Obsidian note.",
  'barra1.sto-gia-trascrivendo': "I'm already transcribing.",
  'barra1.parole-finora': { one: '{n} word so far.', other: '{n} words so far.' },
  'barra1.lezione-dal-computer': 'Lecture from the computer',
  'barra1.computer-spiega': "Start the video lecture (on your university's platform, on Teams, Zoom or wherever you watch it): I listen to the audio coming out of the computer and write it into the lecture note, formulas included.",
  'barra1.nome-del-corso': 'Course name',
  'barra1.computer-patto': "Only for your own study: I don't download the video or upload anything, the audio isn't saved and only the text goes in the note. Lectures belong to the lecturers: don't share the transcription if your university's rules don't allow it.",
  'barra1.computer-mac': "The first time, your Mac asks for permission to record system audio.",
  'barra1.computer-windows': "On Windows you hear the audio as usual: I listen to it too.",
  'barra1.computer-linux': "On Linux I listen to the audio output's «monitor».",
  'barra1.detto-trascrivi-videolezione': 'Transcribe the {corso} video lecture',
  'barra1.sintesi-lezione-dal-computer': 'lecture from the computer',
  'barra1.computer-permesso-mac': "Your Mac won't give me the computer's audio: in **System Settings › Privacy & Security › Screen & System Audio Recording** turn on Lode, then try again (sometimes you need to reopen Lode).",
  'barra1.computer-permesso': "The system won't give me the computer's audio: try again and accept the sharing request.",
  'barra1.computer-non-sento-mac': "I can't listen to the computer's audio (you need macOS 14.2 or newer). {errore}",
  'barra1.computer-non-sento-windows': "I can't listen to the computer's audio. {errore}",
  'barra1.computer-non-sento-linux': "I can't listen to the computer's audio (you need PulseAudio or PipeWire). {errore}",
  'barra1.computer-muto': "I can't hear anything from the computer. Has the video lecture started, with the volume up?",
  'barra1.computer-muto-mac': "I can't hear anything from the computer. Has the video lecture started, with the volume up? If so, your Mac isn't giving me the audio: **System Settings › Privacy & Security › Screen & System Audio Recording**, turn on Lode and try again.",
  'barra1.trascrizione-app': "Lecture transcription is in Lode's **desktop app**: it writes straight into the lecture's Obsidian note.",
  'barra1.computer-aggiorna': "This version can't listen to the computer's audio: update Lode.",
  'barra1.preparo-voce': 'Getting voice ready…',
  'barra1.trascrivo-file': 'Transcribing «{file}» into the {corso} lecture.',
  'barra1.puoi-chiudere': "You can close the panel: I'll let you know when it's done.",
  'barra1.sintesi-registrazione': 'recording being transcribed',
  'barra1.ascolto-computer': "Listening to the computer's audio for {corso}.",
  'barra1.ascolto-computer-nota': 'Start the video lecture: lines arrive in the note every 20-30 seconds. When it ends, type «end of lecture».',
  'barra1.apri-in-obsidian': 'Open in Obsidian',
  'barra1.sintesi-videolezione': 'video lecture being transcribed',
  'barra1.avviso-videolezione': 'Listening to the video lecture',
  'barra1.trascrivo-sparsi': 'Transcribing into loose notes.',
  'barra1.trascrivo-lezione-di': 'Transcribing the {corso} lecture.',
  'barra1.righe-ogni': 'Lines arrive in the note every 20-30 seconds.',
  'barra1.sintesi-trascrizione-avviata': 'transcription started',
  'barra1.avviso-trascrivo': 'Transcribing the lecture',
  'barra1.errore-trascrivere': "I can't transcribe: {errore}",
  'barra1.non-sto-trascrivendo': "I'm not transcribing anything.",
  'barra1.ultimi-secondi': 'Transcribing the last few seconds…',
  'barra1.lezione-trascritta': 'Lecture transcribed: {parole} words.',
  'barra1.righe-sospese': { one: "{n} line isn't in the note yet (the folder isn't responding): I'll write it as soon as I can, keep me open.", other: "{n} lines aren't in the note yet (the folder isn't responding): I'll write them as soon as I can, keep me open." },
  'barra1.tutto-nella-nota': "It's all in the note.",
  'barra1.riordina': 'Tidy up',
  'barra1.detto-riordina': 'Tidy up the lecture',
  'barra1.condividi': 'Share',
  'barra1.detto-condividi': 'Share the lecture write-up',
  'barra1.sintesi-parole-trascritte': { one: '{n} word transcribed', other: '{n} words transcribed' },
  'barra1.con-cervello-locale': 'With the **local brain** (from «Set up Lode») the transcription becomes tidy notes, definitions and ★ in one click.',
  // tidying up the lecture with AI
  'barra1.non-trovo-trascrizione-di': "I can't find a transcription of **{corso}**.",
  'barra1.non-trovo-trascrizione': "I can't find a transcribed lecture. In class, press **Transcribe the lecture**.",
  'barra1.riordinare-serve-ai': 'Tidying up needs AI: install the **local brain** from «Set up Lode» (free, offline) or connect your own AI: type «AI».',
  'barra1.riordino': 'Tidying up {corso}…',
  'barra1.riordino-per-cento': 'Tidying up {corso}… {n}%',
  'barra1.errore-riordinare': "I couldn't tidy it up: {errore}",
  'barra1.salvare-riordinati': 'Save the tidied notes for {corso}?',
  'barra1.riordinati-nota': 'They go in the note, under «Appunti riordinati da Lode», below the transcription (which stays). {motore} wrote them: read them through.',
  'barra1.appunti-salvati': 'Notes saved in the note.',
  'barra1.sintesi-lezione-riordinata': 'lecture tidied up',
  'barra1.detto-definizioni-lezione': 'Definitions from the lecture',
  // «Repeat» and permission to listen to the lecture
  'barra1.ascoltare-lezione': 'Listen to the lecture?',
  'barra1.consenso-ripeti': 'I keep only the last minute and a half in memory, never on disk',
  'barra1.trascrivi': 'Transcribe',
  'barra1.consenso-trascrivi': "I write the lecture into the note, the audio isn't saved",
  'barra1.dove': 'Where',
  'barra1.consenso-dove': 'everything on your computer, nothing online',
  'barra1.consenso-nota': 'Recording a lecture depends on your university rules and the lecturer: ask first.',
  'barra1.solo-la-prima-volta': "I'll only ask you the first time.",
  'barra1.d-accordo': 'OK.',
  'barra1.ripeti-app': "«Repeat» is in Lode's **desktop app**.",
  'barra1.ripeti-e-attivo': 'Repeat is on.',
  'barra1.ripeti-attivo-nota': 'I keep the last minute and a half in memory, never on disk. Missed something? {tasti} or «repeat».',
  'barra1.ripeti-attivo-nota-fuori': 'I keep the last minute and a half in memory, never on disk. Missed something? {tasti} or «repeat». Outside lecture hours I stay on for 3 hours at most.',
  'barra1.detto-spegni-ripeti': 'Turn off Repeat',
  'barra1.sintesi-ripeti-attivo': 'repeat on',
  'barra1.ripeti-spento': 'Repeat off.',
  'barra1.microfono-resta': 'The microphone stays on for the transcription until you close it.',
  'barra1.microfono-chiuso': 'The microphone is off.',
  'barra1.non-si-accende-piu': " It won't turn on by itself in class any more: turn it back on with {tasti}.",
  'barra1.ripeti-e-spento': 'Repeat is off.',
  'barra1.ripeti-e-spento-nota': 'Repeat writes out what the lecturer said in the last 60 seconds: turn it on here or with {tasti}. If you wanted something else, ask me in your own words.',
  'barra1.accendi': 'Turn on',
  'barra1.detto-accendi-ripeti': 'Turn on Repeat',
  'barra1.sintesi-ripeti-spento': 'repeat off',
  'barra1.ascolto-da-un-attimo': "I've only just started listening: I have nothing to repeat yet.",
  'barra1.riascolto': { one: 'Replaying the last {n} second…', other: 'Replaying the last {n} seconds…' },
  'barra1.errore-riascoltare': "I couldn't replay it: {errore}",
  'barra1.niente-sentito': "I didn't hear anyone speaking in the last 60 seconds.",
  'barra1.ultimi-secondi-ora': { one: 'The last {n} second · {ora}', other: 'The last {n} seconds · {ora}' },
  'barra1.agli-appunti': 'To notes',
  'barra1.copia': 'Copy',
  'barra1.copiato': 'Copied',
  'barra1.negli-appunti-di': 'In the {corso} notes.',
  // sharing the lecture write-up
  'barra1.sbobine-app': "Lecture write-ups are shared from the **desktop app**.",
  'barra1.non-trovo-lezione-di': "I can't find a **{corso}** lecture to share.",
  'barra1.non-trovo-lezione': "I can't find a lecture to share: transcribe it or tidy it up first.",
  'barra1.preparo-sbobina': 'Preparing the lecture write-up…',
  'barra1.sbobina-pronta': '{corso} lecture write-up ready.',
  'barra1.scegli-dove': 'Choose where to send it: AirDrop, Messages, Mail…',
  'barra1.nella-cartella-sbobine': "It's in the vault's «Sbobine» folder.",
  'barra1.mostra': 'Show',
  'barra1.sintesi-sbobina-condivisa': 'lecture write-up shared',
  'barra1.errore-sbobina': "I can't prepare the lecture write-up: {errore}",
  // cards for Anki
  'barra1.anki-non-trovo-di': "I can't find any **{corso}** cards or definitions to export.",
  'barra1.anki-non-trovo': "I don't have any cards or definitions to export yet: mark a few definitions in class («def: gradient = …») or make cards from a PDF.",
  'barra1.anki-carte-mazzi': { one: '{n} card for Anki, {mazzi} decks.', other: '{n} cards for Anki, {mazzi} decks.' },
  'barra1.anki-carte-mazzo': { one: '{n} card for Anki in the {mazzo} deck.', other: '{n} cards for Anki in the {mazzo} deck.' },
  'barra1.anki-doppioni': { one: ' {n} duplicate skipped.', other: ' {n} duplicates skipped.' },
  'barra1.anki-importa-download': 'In Anki: File › Import, choose «{file}» (it\'s in your downloads) and «Basic» as the note type.',
  'barra1.anki-importa-vault': 'In Anki: File › Import, choose «{file}» in the vault and «Basic» as the note type.',
  'barra1.scarica': 'Download',
  'barra1.sintesi-anki': 'cards for Anki',
  'barra1.errore-mostrare': "I can't show the file: {errore}",
  'barra1.errore-anki': "I can't save the Anki file: {errore}",
  // files dropped on the pill
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'PowerPoint slides',
  'barra1.tipo-word': 'Word document',
  'barra1.tipo-testo': 'text',
  'barra1.tipo-sbobina': 'Lode lecture write-up',
  'barra1.tipo-carte': 'cards (Anki/CSV)',
  'barra1.tipo-foto': 'photo',
  'barra1.tipo-audio': 'audio recording',
  'barra1.tipo-altro': 'file',
  'barra1.uno-alla-volta': { one: "One at a time: I'll start with **{nome}**, then drop the other {n}.", other: "One at a time: I'll start with **{nome}**, then drop the other {n}." },
  'barra1.errore-leggere-file': "I can't read the file: {errore}",
  'barra1.serve-ai': 'needs the local brain or your own AI',
  'barra1.serve-app': 'in the desktop app',
  'barra1.op-sbobina': 'Add to my vault',
  'barra1.op-sbobina-d': 'It becomes a lecture in your Obsidian: definitions and ★ go into the games',
  'barra1.op-allega-soltanto': 'Just attach it',
  'barra1.op-allega-soltanto-d': "I save the file in the lecture's attachments",
  'barra1.op-importa-carte': 'Import the cards',
  'barra1.op-importa-carte-d': 'One per line: question, then Tab, «;» or « = », then answer',
  'barra1.op-audio': 'Transcribe the recording',
  'barra1.op-audio-d': 'The whole lecture as notes, formulas included, in the lecture note',
  'barra1.op-allega': 'Attach to the lecture',
  'barra1.op-allega-audio-d': 'I save the audio in the attachments, with a link in the note',
  'barra1.op-lavagna': 'Transcribe into notes',
  'barra1.op-lavagna-d': 'Text and formulas in LaTeX, in the lecture note',
  'barra1.op-carte': 'Review cards',
  'barra1.op-carte-foto-d': "The questions they'd ask at the exam",
  'barra1.op-allega-foto-d': 'The photo in the lecture note',
  'barra1.op-carte-d': 'Questions and answers for spaced review',
  'barra1.op-riassunto': 'Summary in Obsidian',
  'barra1.op-riassunto-d': 'Tidy notes with formulas, in a new note',
  'barra1.op-definizioni': 'Definitions for the games',
  'barra1.op-definizioni-d': 'I add them to the lecture: they become memory games',
  'barra1.op-orale': 'Quiz me on this',
  'barra1.op-orale-d': 'An oral examiner with questions on this material',
  'barra1.op-allega-d': 'I save the file with a link in the note',
  'barra1.op-crocette': 'Multiple-choice quiz',
  'barra1.op-crocette-d': 'Questions with 4 answers, like the written exam: practice or exam simulation',
  'barra1.op-temi': 'Past papers',
  'barra1.op-temi-d': 'The exercises from an old paper, split by topic, one a day in the plan',
  'barra1.op-programma': "It's the exam syllabus",
  'barra1.op-programma-d': "I split it into topics and make you a plan up to the exam",
  'barra1.op-domande': 'Past exam questions',
  'barra1.op-domande-d': 'I put them under their topics: the ones that come up most move up in the plan',
};
