// Bar texts, third part (English): pocket review, Moodle, multiple-choice quiz, past papers, mock exam, exam syllabus,
// “let me explain”, sending, files, voice, shortcuts and app notices (js/lode.js).
export default {
  // Pocket review
  'barra3.tasca-solo-app': 'Pocket review lives in the app: it needs the Obsidian vault.',
  'barra3.tasca-spenta': 'Pocket review only when you ask.',
  'barra3.tasca-spenta-nota': 'The {nota} note stays in the vault: type “pocket review” to update it.',
  'barra3.tasca-spenta-sintesi': 'pocket review off',
  'barra3.tasca-preparo': 'Preparing the note…',
  'barra3.tasca-errore': "I can't read or write the {nota} note: {errore}",
  'barra3.tasca-estranea': "There's already a **{nota}** note in the vault that Lode didn't write: I won't touch it. Rename it and try again.",
  'barra3.tasca-segnata-sapevi': 'I recorded the card you did on your phone: you knew it.',
  'barra3.tasca-segnata-non-sapevi': "I recorded the card you did on your phone: you didn't know it.",
  'barra3.tasca-segnate': 'I recorded {n} cards you did on your phone: you knew {sapevo}, not {no}.',
  'barra3.tasca-gia': { one: "You'd already reviewed one card on the computer: I won't record it twice.", other: "You'd already reviewed {n} cards on the computer: I won't record them twice." },
  'barra3.tasca-vecchia': "The note on your phone is from an old round: I won't record anything.",
  'barra3.tasca-cambiata': "The note is still changing: Obsidian is syncing it. I won't rewrite it now, try again in a minute.",
  'barra3.tasca-domani': { one: "There's {n} card for tomorrow in the {nota} note.", other: 'There are {n} cards for tomorrow in the {nota} note.' },
  'barra3.tasca-domani-niente': 'No cards to review tomorrow: the {nota} note says so.',
  'barra3.tasca-titolo': 'Pocket review',
  'barra3.tasca-aspetta': "Wait for your phone to finish syncing and try again. If the right note doesn't arrive, rewrite it: I won't record the ticks from that copy.",
  'barra3.apri-nota': 'Open the note',
  'barra3.riscrivi-nota': 'Rewrite the note',
  'barra3.tasca-solo-quando': 'Only when I ask',
  'barra3.tasca-ogni-sera': 'Every evening',
  'barra3.tasca-sera-accesa': 'Every evening after 19:00 I rewrite it on my own, if Lode is open.',
  'barra3.tasca-sera-spenta': 'I only rewrite it when you ask.',
  'barra3.tasca-come-arriva': "It works if your vault reaches your phone (iCloud, Obsidian Sync, Syncthing). Lode doesn't use the network: the service you already use carries the note.",
  'barra3.non-apro-nota': "I can't open the note: {errore}",
  'barra3.tasca-riscrivi-detto': 'Rewrite the {nota} note',
  'barra3.tasca-sintesi': 'pocket review',

  // Moodle
  'barra3.moodle-solo-app': "The Moodle connection is in Lode's **desktop app**.",
  'barra3.moodle-non-risponde': "Moodle isn't responding: {errore}",
  'barra3.moodle-non-collegato': "Moodle isn't connected.",
  'barra3.moodle-scollegato': 'Moodle disconnected.',
  'barra3.moodle-scollegato-nota': 'The token is deleted from this computer. Files you already got stay in your vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} course followed: {corsi}', other: '{n} courses followed: {corsi}' },
  'barra3.file-nuovi': 'New files',
  'barra3.scadenze': 'Deadlines',
  'barra3.corsi': 'Courses',
  'barra3.scollega': 'Disconnect',
  'barra3.moodle-senza-portachiavi': 'This computer has no keyring: the connection lasts until you close Lode.',
  'barra3.moodle-novita-detto': "What's new on Moodle",
  'barra3.moodle-corsi-detto': 'Moodle courses',
  'barra3.moodle-scollega-detto': 'Disconnect Moodle',
  'barra3.moodle-collega': 'Connect Moodle',
  'barra3.moodle-collega-intro': "Your university's course platform (Virtuale, Ariel, e-learning…): Lode picks up new files and deadlines from the courses you choose. Read only: it doesn't submit or write anything.",
  'barra3.moodle-indirizzo-esempio': 'Address, for example virtuale.unibo.it',
  'barra3.moodle-indirizzo': 'Moodle address',
  'barra3.continua': 'Continue',
  'barra3.moodle-collega-nota': "You log in as in the official Moodle app. The connection stays encrypted on this computer, never in the vault; “disconnect moodle” removes it.",
  'barra3.moodle-cerco': 'Looking for the site…',
  'barra3.moodle-non-indirizzo': "That doesn't look like an address.",
  'barra3.moodle-non-trovo': "I can't find a Moodle with the app enabled at this address ({motivo}). Copy the address from the browser bar when you're on your courses page.",
  'barra3.moodle-accesso-annullato': 'Login cancelled.',
  'barra3.moodle-accesso-fallito': 'Login failed: {motivo}.',
  'barra3.moodle-entra-sso': "<b>{nome}</b> · you log in with your university login (SPID or your university credentials), in a Lode window.",
  'barra3.accedi': 'Log in',
  'barra3.moodle-accedi-finestra': 'Log in in the window that opened…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · log in with your Moodle username and password.',
  'barra3.utente': 'Username',
  'barra3.password': 'Password',
  'barra3.moodle-password-nota': "The password only goes to Moodle: Lode doesn't save it.",
  'barra3.moodle-collega-sintesi': 'connect Moodle',
  'barra3.moodle-leggo-corsi': 'Reading your courses…',
  'barra3.moodle-corsi-errore': "I can't read the courses: {errore}",
  'barra3.moodle-nessun-corso': "You're not enrolled in any course on Moodle.",
  'barra3.moodle-corsi-titolo': 'Moodle courses · {sito}',
  'barra3.moodle-scegli-corsi': 'Choose which ones to follow and which Lode course they go with: their new files arrive here.',
  'barra3.concluso': 'finished',
  'barra3.moodle-corso-per': 'Lode course for {nome}',
  'barra3.non-seguire': "Don't follow",
  'barra3.moodle-con-nome': 'With the Moodle name',
  'barra3.salva': 'Save',
  'barra3.moodle-seguo': { one: "I'm following {n} course on Moodle.", other: "I'm following {n} courses on Moodle." },
  'barra3.moodle-nessuno-seguito': 'No courses followed.',
  'barra3.moodle-ti-avviso': "I'll let you know when new files arrive.",
  'barra3.moodle-corsi-sintesi': 'Moodle courses',
  'barra3.moodle-guardo': 'Checking the files on Moodle…',
  'barra3.moodle-non-leggo': "I can't read {corsi}: {errore}.",
  'barra3.moodle-nessun-file': 'There are no files yet in the courses you follow.',
  'barra3.moodle-piu-recenti': 'the latest files',
  'barra3.moodle-file-nuovi': { one: '{n} new file', other: '{n} new files' },
  'barra3.moodle-niente-nuovo': 'nothing new, the latest files',
  'barra3.nuovo': 'new',
  'barra3.apri': 'Open',
  'barra3.moodle-apri-nota': '“Open” brings it into Lode as if you had dragged it in: cards, summary, syllabus, quiz.',
  'barra3.scarico': 'Downloading…',
  'barra3.non-riesco': "Couldn't",
  'barra3.aperto': 'Opened',
  'barra3.moodle-file-da': '{nome} from Moodle',
  'barra3.file-illeggibile': "I can't read the file: {errore}",
  'barra3.moodle-sintesi-nuovi': { one: 'Moodle: {n} new file', other: 'Moodle: {n} new files' },
  'barra3.moodle-nessuna-scadenza': 'No deadlines on Moodle in the next few weeks.',
  'barra3.moodle-scadenze-titolo': 'Deadlines on Moodle',
  'barra3.scadenze-sintesi': { one: '{n} deadline', other: '{n} deadlines' },
  'barra3.guarda': 'Look',

  // multiple-choice quiz
  'barra3.non-trovo-esame': "I can't find the **{nome}** exam.",
  'barra3.il-tuo-materiale': 'your material',
  'barra3.quiz-poco-materiale': 'For a quiz on **{nome}** I need more material: drag in the handout or slides (choose “Multiple-choice quiz”), or make a few cards.',
  'barra3.quiz-senza-ai': "For a quiz without AI I need at least 4 cards or 4 definitions for **{nome}**. With AI (type “AI”) I can also make it from the handout.",
  'barra3.quiz-fonte-dispensa-nome': 'Questions from the handout “{nome}”.',
  'barra3.quiz-fonte-dispensa': 'Questions from the handout.',
  'barra3.quiz-fonte-ai': 'Questions from your cards, definitions and past exam questions.',
  'barra3.quiz-fonte-carte-definizioni': 'Questions from your cards and definitions.',
  'barra3.quiz-fonte-carte': 'Questions from your cards.',
  'barra3.quiz-fonte-definizioni': 'Questions from your definitions.',
  'barra3.quiz-le-scrive': '{motore} writes them: I only keep the ones the material backs up.',
  'barra3.quiz-sbagliate-altre': 'The wrong answers come from other cards in the course.',
  'barra3.quiz-titolo': 'Multiple-choice quiz · {nome}',
  'barra3.quiz-allenamento': { one: 'Practice · {n} question', other: 'Practice · {n} questions' },
  'barra3.quiz-allenamento-sotto': 'Marked straight away, with the explanation',
  'barra3.quiz-simulazione': { one: 'Exam simulation · {n} question in {n} minute', other: 'Exam simulation · {n} questions in {n} minutes' },
  'barra3.quiz-simulazione-sotto': 'Like the written exam: the clock runs, marking at the end, the grade out of 30',
  'barra3.quiz-simulazione-detto': 'Exam simulation · {nome}',
  'barra3.quiz-detto': 'Quiz · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulation · {nome}',
  'barra3.quiz-preparo': 'Preparing the questions… {fatte} of {n}',
  'barra3.quiz-errore': "I can't prepare the questions: {errore}",
  'barra3.quiz-niente': "I couldn't prepare reliable questions from this material.",
  'barra3.quiz-sintesi': '{nome} quiz',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} of {n}',
  'barra3.x-di-n': '{x} of {n}',
  'barra3.quiz-domanda-n': 'Question {x} of {n}',
  'barra3.indietro': 'Back',
  'barra3.salta': 'Skip',
  'barra3.lascia-vuota': 'Leave blank',
  'barra3.consegna': 'Hand in',
  'barra3.quiz-giusta-e': 'The right answer is {lettera}.',
  'barra3.avanti': 'Next',
  'barra3.risultato': 'Result',
  'barra3.tasto-invio': 'Enter',
  'barra3.quiz-voto': 'Grade: <em>{voto}</em>',
  'barra3.tempo-scaduto': "time's up",
  'barra3.quiz-tutte-giuste': 'All correct.',
  'barra3.quiz-da-rivedere': { one: '{n} to go over again.', other: '{n} to go over again.' },
  'barra3.quiz-scartate': { one: "{n} question dropped because the material didn't back it up", other: "{n} questions dropped because the material didn't back them up" },
  'barra3.da-rivedere': 'To go over again',
  'barra3.lasciata-vuota': 'Left blank',
  'barra3.hai-scelto': 'You chose: {x}',
  'barra3.giusta-era': 'Correct answer: {x}',
  'barra3.quiz-sbagliate-carte': 'Turn the wrong ones into cards',
  'barra3.quiz-un-altro': 'Another quiz',
  'barra3.quiz-punti': 'A right answer is worth 1 point, a wrong or blank one 0.',
  'barra3.quiz-regole-vere': "The real written exam may have different rules (penalties for wrong answers, pass marks): this is practice.",
  'barra3.quiz-carte-aggiunte': { one: "{n} card added: it comes back in today's review", other: "{n} cards added: they come back in today's review" },
  'barra3.quiz-sintesi-esito': '{nome} quiz: {giuste} of {n}',

  // past papers
  'barra3.tema-del': 'from {data}',
  'barra3.tema-di': 'from “{fonte}”',
  'barra3.tema-es': 'ex. {es}',
  'barra3.tema-es-da': 'ex. {es} {da}',
  'barra3.tema-circa': 'about {min} min on paper',
  'barra3.leggo-file': 'Reading {nome}…',
  'barra3.cmd-temi-di': '“past papers for {nome}:”',
  'barra3.cmd-temi': '“past papers:”',
  'barra3.temi-scansione': "This PDF looks like a scan: without AI I can't read images. Paste the exercise text with {cmd} and the text below it.",
  'barra3.temi-illeggibile': "I can't read any text from this file. Paste it with {cmd} and the text below it.",
  'barra3.aggiungi-prima-esame': 'Add the exam first, for example: “exam calculus 2 on 15 January 9 credits”.',
  'barra3.non-trovo-esame-aggiungi': "I can't find the **{nome}** exam. Add it first, for example: “exam {nome} on 15 January 9 credits”.",
  'barra3.aggiungi-esame-compito': 'Add an exam first, for example: “exam calculus 2 on 15 January 9 credits”. Then paste an old paper.',
  'barra3.prova-invito': 'Want to try a whole paper, with the real time limit?',
  'barra3.prova-generale': 'Mock exam',
  'barra3.prova-generale-di': '{nome} mock exam',
  'barra3.temi-titolo': 'Past papers · {nome}',
  'barra3.temi-nessuno-oggi': 'No exercises due today.',
  'barra3.temi-prossimo': 'The next one comes back {data}.',
  'barra3.temi-vuoto': "Paste the text of an old paper (the ones going round the course group chat or on the lecturer's website), or drag in the PDF. I split it into exercises, put them under their topics and suggest one every day.",
  'barra3.temi-segnaposto': 'Esercizio 1. Calculate…&#10;Esercizio 2. Study…',
  'barra3.temi-testo-compito': 'Text of the paper',
  'barra3.temi-dividi': 'Split into exercises',
  'barra3.temi-di': '{nome} past papers',
  'barra3.temi-di-sintesi': '{nome} past papers',
  'barra3.temi-nessun-esercizio': "I didn't find any exercises in this text.",
  'barra3.temi-compito-del': 'paper {data}',
  'barra3.temi-un-pezzo': "I didn't find “Esercizio 1”, “Esercizio 2”… If the paper has several exercises, mark them that way and paste it again.",
  'barra3.temi-senza-programma': "There's no syllabus for {nome} yet: I'll save them without a topic.",
  'barra3.temi-metti': 'Put them in the plan',
  'barra3.temi-es': 'Ex. {n}',
  'barra3.temi-con-soluzione': "with the lecturer's solution",
  'barra3.temi-argomento-di': 'Topic of exercise {n}',
  'barra3.temi-che-argomento': 'Which topic is it?',
  'barra3.temi-unisci': 'Merge with the previous one',
  'barra3.togli': 'Remove',
  'barra3.temi-nel-piano': { one: '{n} exercise in the plan.', other: '{n} exercises in the plan.' },
  'barra3.temi-nel-piano-arg': { one: '{n} exercise in the plan: {con} with its topic, {senza} without.', other: '{n} exercises in the plan: {con} with their topic, {senza} without.' },
  'barra3.temi-senza-programma-nota': "Without a syllabus I don't know where to put them: paste the {nome} syllabus and I'll sort them.",
  'barra3.temi-doppi': { one: '{n} was already there.', other: '{n} were already there.' },
  'barra3.temi-ogni-giorno': 'Every day, one on the topics in the plan.',
  'barra3.programma': 'Syllabus',
  'barra3.fanne-uno': 'Do one',
  'barra3.esercizio-di': '{nome} exercise',
  'barra3.temi-gia': 'These exercises were already there.',
  'barra3.temi-sintesi-n': { one: '{nome} past papers: {n} exercise', other: '{nome} past papers: {n} exercises' },
  'barra3.tema-titolo': 'Exercise · {nome}',
  'barra3.tema-fallo': "Do it on paper, without looking at your notes. When you're done:",
  'barra3.giusto': 'Right',
  'barra3.sbagliato': 'Wrong',
  'barra3.non-sapevo': "I didn't know where to start",
  'barra3.tema-voto-tuo': "You grade yourself: Lode doesn't mark the exercise.",
  'barra3.tema-torna': { one: 'It comes back in {n} day.', other: 'It comes back in {n} days.' },
  'barra3.tema-guarda-soluzione': "Look at the solution and do it again from scratch, don't just reread it.",
  'barra3.tema-rileggi': 'Reread the topic and do it again from scratch, without looking.',
  'barra3.tema-prima-rileggi-arg': 'First reread the topic: {arg}.',
  'barra3.tema-prima-rileggi': 'First reread the topic.',
  'barra3.tema-vedi-soluzione': "See the lecturer's solution",
  'barra3.tema-altro': 'Another exercise',
  'barra3.esercizio-di-esito': '{nome} exercise: {esito}',
  'barra3.esercizio-di-sintesi': '{nome} exercise',

  // mock exam
  'barra3.prova-prima-compiti': 'First paste or drag in the old papers: “past papers for {nome}: …”.',
  'barra3.prova-compito-del': 'Paper from {data}',
  'barra3.prova-scelti': 'Exercises you picked',
  'barra3.prova-compito-fonte': 'Paper “{fonte}”',
  'barra3.prova-compito-incollato': 'Pasted paper',
  'barra3.n-esercizi': { one: '{n} exercise', other: '{n} exercises' },
  'barra3.n-punti': '{punti} points',
  'barra3.prova-titolo': 'Mock exam · {nome}',
  'barra3.prova-quanto-dura': 'How long is it?',
  'barra3.prova-minuti-aria': 'How many minutes the exam lasts',
  'barra3.minuti': 'minutes',
  'barra3.prova-altro-compito': 'Another paper',
  'barra3.prova-gia-fatto': 'already done on {data}',
  'barra3.comincio': 'Start',
  'barra3.prova-su-carta': "On paper, no notes, like the real exam. You'll see the solutions at the end.",
  'barra3.prova-durata-letta': 'I read it in the paper.',
  'barra3.prova-di-solito': 'Usually 2 hours.',
  'barra3.prova-sintesi': '{nome} mock exam',
  'barra3.prova-scegli': "I can't find a whole paper: pick the exercises yourself.",
  'barra3.prova-scegli-nota': "120 minutes, on paper, no notes. You'll see the solutions at the end.",
  'barra3.prova-ferma-pausa': "There's a break running: shall I stop it and start the mock exam?",
  'barra3.prova-ferma-focus': "There's a focus running: shall I stop it and start the mock exam?",
  'barra3.si-parti': 'Yes, start',
  'barra3.no': 'No',
  'barra3.prova-durata-fino': '{min} minutes, until {ora}',
  'barra3.esercizio-n': 'Exercise {n}',
  'barra3.prova-passo': 'Next one',
  'barra3.consegno': 'Hand in',
  'barra3.lascio-perdere': 'Give up',
  'barra3.prova-nota-tempo': 'The clock runs in the pill. “Next one” is optional: it records how long you spend on each exercise.',
  'barra3.prova-lascio-chiede': "Give it up? I won't record anything: neither the exercises nor the paper.",
  'barra3.si-lascio': 'Yes, give up',
  'barra3.no-continuo': "No, I'll keep going",
  'barra3.prova-lasciata': "Given up: I didn't record anything. When you want to do it again, type “mock exam for {nome}”.",
  'barra3.prova-consegnato': 'Handed in. Take your sheet and, for each exercise, tell me how it went.',
  'barra3.prova-come-andato': 'How did exercise {n} go',
  'barra3.prova-esito-tuo': "Lode doesn't mark it: you choose the outcome.",
  'barra3.prova-sintesi-esito': '{nome} mock exam: {fatti} of {n}',
  'barra3.prova-sintesi-come': '{nome} mock exam: how it went',

  // exam syllabus
  'barra3.aggiungi-esame-programma': 'Add an exam first, for example: “exam calculus 2 on 15 January 9 credits”. Then paste its syllabus.',
  'barra3.programma-titolo': 'Syllabus · {nome}',
  'barra3.programma-vuoto': "Paste the course syllabus (from the course page or the PDF), or drag the file here. I split it into topics, show you what you already know and make you a plan up to the exam.",
  'barra3.programma-segnaposto': '1. Limits and continuity&#10;2. Derivatives: definition, rules, Rolle\'s and Lagrange\'s theorems&#10;…',
  'barra3.programma-del-corso': 'Course syllabus',
  'barra3.programma-leggi': 'Read the syllabus',
  'barra3.programma-di': '{nome} syllabus',
  'barra3.programma-da-moodle': 'Get it from Moodle',
  'barra3.programma-moodle-vuota': 'The description on Moodle is empty',
  'barra3.programma-di-moodle': '{nome} syllabus from Moodle',
  'barra3.programma-sintesi': '{nome} syllabus',
  'barra3.programma-leggo': 'Reading the syllabus…',
  'barra3.programma-niente': "I can't get the topics out of this text. Paste them one per line, numbered if you can.",
  'barra3.programma-salvo': { one: '{n} topic for {nome}: shall I save it?', other: '{n} topics for {nome}: shall I save them?' },
  'barra3.programma-letti-da': '{motore} read them: check they are all there.',
  'barra3.programma-se-non-torna': "If something doesn't look right, paste the corrected syllabus again.",
  'barra3.programma-stesso-nome': 'Topics with the same name keep their questions and outcomes.',
  'barra3.programma-cuscinetto': "Today is the buffer day: catch up on what fell behind, or take a rest.",
  'barra3.programma-ultimo': 'Last day: general review. Past exam questions and weak spots: {cosa}.',
  'barra3.tutto-il-programma': 'the whole syllabus',
  'barra3.studia': 'Study',
  'barra3.ripassa': 'Review',
  'barra3.cuscinetto': 'buffer',
  'barra3.ripasso-generale': 'general review',
  'barra3.percento-pronto': '{p}% ready',
  'barra3.oggi': 'Today',
  'barra3.esercizio-di-oggi': "Today's exercise",
  'barra3.fallo-adesso': 'Do it now',
  'barra3.interrogami-questi': 'Quiz me on these',
  'barra3.focus': 'Focus',
  'barra3.da-rivedere-piccolo': 'to go over',
  'barra3.uscita-volte': { one: 'came up {n} time', other: 'came up {n} times' },
  'barra3.fatto-oggi': 'done today',
  'barra3.lo-spiego-io': 'Let me explain',
  'barra3.interrogami': 'Quiz me',
  'barra3.prossimi-giorni': 'The next few days',
  'barra3.senza-data-appello': '(no exam date: two-week plan)',
  'barra3.domande-appelli': 'Past exam questions',
  'barra3.n-senza-argomento': { one: '{n} without a topic', other: '{n} without a topic' },
  'barra3.domande-segnaposto': 'One per line: the ones going round the course group chat',
  'barra3.domande-uscite': 'Past questions',
  'barra3.aggiungi': 'Add',
  'barra3.domande-senza-argomento': "I don't know which topic these belong to: {lista}",
  'barra3.programma-nota': 'The plan is redone every day from what you know: notes, cards, reviews and quizzes. Weak topics and the ones that come up most go first; every new topic comes back after a few days.',
  'barra3.interrogami-oggi': "Quiz me on today's topics",
  'barra3.interrogami-su': 'Quiz me on {x}',
  'barra3.te-lo-spiego-su': 'Let me explain: {x}',
  'barra3.programma-sintesi-pronto': '{nome} syllabus: {p}% ready',
  'barra3.domande-nessuna': "I didn't find any questions: write one per line.",
  'barra3.domande-salvate': { one: '{n} question saved.', other: '{n} questions saved.' },
  'barra3.domande-incolla-programma': "Paste the syllabus too: I'll put them under their topics.",
  'barra3.domande-aggiunte': { one: '{n} question added.', other: '{n} questions added.' },
  'barra3.domande-senza': { one: "{n} without a topic: I can't tell which one it's about.", other: "{n} without a topic: I can't tell which ones they're about." },
  'barra3.domande-salgono': 'Topics that come up most move up in the plan.',
  'barra3.domande-uscite-sintesi': 'past questions',

  // let me explain, and the oral on the syllabus
  'barra3.spiego-titolo': 'Let me explain · {nome}',
  'barra3.spiego-istruzioni': "Explain it as if you were in the oral, in your own words: type below or hold {tasti} and talk. When you're done, send.",
  'barra3.spiego-risponde': '{motore} answers you, using your notes.',
  'barra3.spiego-controllo': { one: "I'll check {n} point taken from the syllabus and your notes: I won't show it to you first.", other: "I'll check {n} points taken from the syllabus and your notes: I won't show them to you first." },
  'barra3.spiego-senza-appunti': "I have no notes on this topic: without AI I can only record that you reviewed it.",
  'barra3.spiego-esci': 'Type “exit” to leave it.',
  'barra3.spiego-segnaposto': 'Your explanation…',
  'barra3.spiego-sintesi': 'explaining {x}',
  'barra3.chiedi-o-scrivi': 'Ask or type a command…',
  'barra3.spiego-ascolto': 'Listening to your explanation…',
  'barra3.mancava': 'Missing: {cosa}',
  'barra3.spiego-errore': "I can't assess it right now: {errore}",
  'barra3.spiego-segnato': 'Recorded: you reviewed {x}.',
  'barra3.spiego-controllo-vero': 'For a real check you need notes on this topic, or AI.',
  'barra3.punti-su': '{x} points out of {n}',
  'barra3.spiego-parole-chiave': 'I check the keywords, not the reasoning: if you said a point in different words, it still counts.',
  'barra3.spiego-sicuro': 'Topic marked as solid.',
  'barra3.spiego-cerchio-vuoto': 'The ones with an empty circle: reread them and try again in a couple of days.',
  'barra3.orale-niente': "There's nothing in today's plan to be quizzed on.",
  'barra3.orale-contesto': 'Oral · <b>{nome}</b> · {cosa}',
  'barra3.n-argomenti': { one: '{n} topic', other: '{n} topics' },
  'barra3.esci': 'Exit',
  'barra3.orale-sintesi': '{nome} oral on the syllabus',

  // sending, files, voice
  'barra3.crea-carte-da-file': 'Make review cards from this file.',
  'barra3.niente-spiegazione': 'OK, no explanation.',
  'barra3.non-so-senza-ai': "I can't do this without AI yet. Here's what I understand:",
  'barra3.foto': 'photo',
  'barra3.togli-file': 'Remove {nome}',
  'barra3.allegati-con-ai': "Enter: I'll make cards. Or ask something else…",
  'barra3.allegati-senza-ai': 'Enter: import the cards (CSV, TSV, text)',
  'barra3.importa-solo-testo': 'Without AI I only read text files with one card per line (question, then Tab or “;” or “ = ”, then answer), like an Anki export. PDFs and photos need the local brain or your own AI (type “AI”).',
  'barra3.importa-carte': { one: 'Import {n} card?', other: 'Import {n} cards?' },
  'barra3.e-altre': { one: 'and {n} more', other: 'and {n} more' },
  'barra3.importa-in': 'I\'ll put them in {nome}: you can change it from the page.',
  'barra3.carte-importate': { one: '{n} card imported.', other: '{n} cards imported.' },
  'barra3.ripassa-ora': 'Review now',
  'barra3.ti-ascolto': "I'm listening",
  'barra3.ti-ascolto-preparo': "I'm listening · getting voice ready…",
  'barra3.ti-ascolto-preparo-p': "I'm listening · getting voice ready {p}%",
  'barra3.voce-pronta': '{voce}, local · hold {tasti} and talk',
  'barra3.scarico-voce': 'Downloading {voce} · {p}%',
  'barra3.voce-ripiego': "Parakeet won't start: getting Whisper ready",
  'barra3.preparo-voce': 'Getting voice ready',

  // links, shortcuts and notices
  'barra3.piu-tardi': 'OK, later',
  'barra3.trascrivi-lezione': 'Transcribe the lecture',
  'barra3.fine-trascrizione': 'End transcription',
  'barra3.ripeti': 'Repeat',
  'barra3.spegni-ripeti': 'Turn off Repeat',
  'barra3.accendi-ripeti': 'Turn on Repeat',
  'barra3.gioca': 'Play',
  'barra3.pausa': 'Break',
  'barra3.focus-fatto': { one: '{n} minute done · break', other: '{n} minutes done · break' },
  'barra3.tempo-scaduto-consegna': "Time's up · hand in",
  'barra3.pausa-finita': 'Break over · ready to go again?',
  'barra3.ripeti-spento': 'Repeat turned off after 3 hours',
  'barra3.lode-pronta': 'Lode {versione} is ready',
  'barra3.lode-uscita': 'Lode {versione} is out',
  'barra3.sync-in-pausa': 'Sync paused · type the password',
  'barra3.cervello-locale': 'Local brain',
  'barra3.ripassa-esame': 'Review {nome}',
  'barra3.ripasso': 'Review',
  'barra3.libretto': 'Grades',
};
