// Bar texts, second part (English): files dropped in the bar, coach suggestions, your AI, “Set up Lode” and updates,
// sync, notes, wrapping up the lecture, games, local commands, explained errors and diary, AI tools, oral exam, coding
// agents (js/lode.js).
export default {
  'barra2.file-non-so-usare': "I don't know how to use this: {motivo}.",
  'barra2.peso-kb': '{n} KB',
  'barra2.peso-mb': '{n} MB',
  'barra2.cosa-ne-faccio': 'What should I do with it?',
  'barra2.per': 'For',
  'barra2.corso': 'Course',
  'barra2.data-lezione': 'Lecture date',
  'barra2.non-andata': "It didn't work: {errore}",
  'barra2.sintesi-cosa-ne-faccio': '{nome}: what should I do with it?',
  'barra2.allegato-lezione': 'Attached to the {corso} lecture.',
  'barra2.apri': 'Open',
  'barra2.sbobina-nel-vault': '{corso} lecture write-up in your vault.',
  'barra2.sbobina-nota-da': '{data} · from {da}',
  'barra2.sbobina-ricevuta': 'lecture write-up received',
  'barra2.nessuna-riga-carte': "I didn't find any “question, answer” lines in this file.",
  'barra2.apro-registrazione': 'Opening the recording…',
  'barra2.leggo-foto': 'Reading the photo…',
  'barra2.lavagna-titolo': 'Add to the {corso} notes?',
  'barra2.lavagna-nota': "Together with the photo, in today's lecture note. Read it through: {motore} transcribed it.",
  'barra2.lavagna-fatta': 'Board added to your notes.',
  'barra2.leggo-file': 'Reading {nome}…',
  'barra2.file-senza-testo': "I can't read any text from this file.",
  'barra2.file-senza-testo-incolla': "I can't read any text from this file: paste it into the field.",
  'barra2.prima-esame': 'Add the exam first, for example: “exam calculus 2 on 15 January 9 credits”.',
  'barra2.scrivo-carte': 'Writing the cards…',
  'barra2.file-senza-carte': "I couldn't get any cards out of this file.",
  'barra2.riassumo': 'Summarising {nome}… {p}%',
  'barra2.riassunto-titolo': 'Save the summary in Obsidian?',
  'barra2.riassunto-nota': 'New note in {cartella}, with the original file attached.',
  'barra2.riassunto-salvato': 'Summary saved.',
  'barra2.stelle-titolo': '★ For the exam · {esame}',
  'barra2.ora-un-gioco': 'Now a game',
  'barra2.gioca': 'Play',
  'barra2.la-tua-ai': 'Your AI',
  'barra2.ai-locale-attivo': 'Lode is now using the <b>local brain</b>: free, offline, your notes stay here.',
  'barra2.ai-locale-da-installare': 'The free <b>local brain</b> is installed from “Set up Lode”.',
  'barra2.ai-chiave-spiegazione': "If you want a more powerful AI, connect your own key: you pay the service directly, as you go (usually a few cents per session). Lode doesn't see or earn anything; the key stays on this computer.",
  'barra2.ai-nome-collegata': '{nome} · connected',
  'barra2.chiave-api': 'API key',
  'barra2.collega': 'Connect',
  'barra2.modello': 'Model',
  'barra2.ai-solo-spiegazioni': 'Notes and lectures stay on the computer: your AI only for explanations and oral practice',
  'barra2.usa-solo-locale': 'Use only the local brain',
  'barra2.chiave-di': '{nome} key',
  'barra2.incolla-chiave': 'paste the key',
  'barra2.si-crea-su': 'Create it at <b>{sito}</b>.',
  'barra2.provo-chiave': 'Testing the key…',
  'barra2.ai-collegata': '{nome} connected.',
  'barra2.ai-modello': 'Model {modello}.',
  'barra2.ai-appunti-restano': 'Your notes stay on the computer.',
  'barra2.ai-usano-tua': 'Explanations, oral practice, cards and tidying up use your AI.',
  'barra2.sintesi-ai-collegata': 'AI connected',
  'barra2.chiave-non-valida': 'The key is not valid.',
  'barra2.servizio-irraggiungibile': "I can't reach the service: are you online?",
  'barra2.solo-locale-fatto': 'Lode uses only the local brain.',
  'barra2.ai-scollegata-sito': "I deleted the key from this computer. It still works in your {nome} account: if you don't need it any more, revoke it there too ({sito}).",
  'barra2.ai-scollegata-nome': "I deleted the key from this computer. It still works in your {nome} account: if you don't need it any more, revoke it there too.",
  'barra2.ai-scollegata': "I deleted the key from this computer. It still works in your account: if you don't need it any more, revoke it there too.",
  'barra2.sintesi-la-tua-ai': 'your AI',
  'barra2.agg-pronta': 'Lode {versione} is ready',
  'barra2.agg-si-installa': 'It installs itself when you close Lode',
  'barra2.riavvia-ora': 'Restart now',
  'barra2.agg-uscita': 'Lode {versione} is out',
  'barra2.agg-scarica-dmg': 'Download the .dmg and drag Lode into Applications',
  'barra2.agg-scarica-github': 'Download the new version from GitHub',
  'barra2.scarica': 'Download',
  'barra2.agg-spenti': 'Lode {versione} · updates off: new versions are on GitHub, on the Releases page',
  'barra2.agg-scarico': 'Downloading Lode {versione} · {p}%',
  'barra2.agg-pronta-riga': 'Lode {versione} is ready · it installs itself when you close Lode',
  'barra2.agg-uscita-mac': 'Lode {versione} is out · download the .dmg and drag Lode into Applications',
  'barra2.agg-uscita-github': 'Lode {versione} is out · download it from GitHub',
  'barra2.agg-manuale': "Lode {versione} · I'll tell you when a new one is out (from GitHub, every 6 hours)",
  'barra2.agg-automatici': 'Lode {versione} · updates itself from GitHub, checks every 6 hours',
  'barra2.spegni': 'Turn off',
  'barra2.accendi': 'Turn on',
  'barra2.prep-solo-app': "Obsidian and the local brain are installed from Lode's **desktop app**.",
  'barra2.prepara-lode': 'Set up Lode',
  'barra2.il-tuo-vault': 'Your vault',
  'barra2.prep-vault-dett': '{percorso} · Home, courses, lectures, glossary',
  'barra2.obs-installato': 'Installed and connected to the vault',
  'barra2.obs-da-installare': 'Free for personal use · official installer from GitHub, about 230 MB',
  'barra2.installa': 'Install',
  'barra2.cervello-locale': 'Local brain',
  'barra2.cervello-pronto-dett': '{modello} · runs on your computer, no internet needed',
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · about {gb} GB',
  'barra2.pronto': 'ready',
  'barra2.voce': 'Voice',
  'barra2.voce-pronta-dett': '{voce}, local · hold {tasti} and talk',
  'barra2.voce-da-preparare': '{descrizione}, local, in English · about {peso} MB, just once',
  'barra2.pronta': 'ready',
  'barra2.prepara': 'Set up',
  'barra2.facoltativa': 'optional',
  'barra2.tua-ai-collegata-dett': '{nome} connected · you pay as you go, directly to the service',
  'barra2.tua-ai-da-collegare': 'Claude, ChatGPT, Gemini, Mistral…: more powerful, pay as you go with your own key',
  'barra2.cambia': 'Change',
  'barra2.sincronizza-computer': 'Sync between your computers',
  'barra2.sperimentale': 'experimental',
  'barra2.sblocca': 'Unlock',
  'barra2.gestisci': 'Manage',
  'barra2.attiva': 'Turn on',
  'barra2.uso-gia-altrove': 'I already use Lode on another computer',
  'barra2.collega-dett': 'Connect this computer to the vault you already have in your cloud folder',
  'barra2.aggiornamenti': 'Updates',
  'barra2.prep-nota': "The local brain is free and works offline: it pulls out definitions, makes cards, explains and quizzes you. Your own AI is an optional boost: Lode doesn't see or earn anything.",
  'barra2.detto-mia-ai': 'My AI',
  'barra2.detto-sincronizza': 'Sync between computers',
  'barra2.scarico-voce': 'Downloading {voce}…',
  'barra2.sintesi-prepara': 'set up Lode',
  'barra2.installare-obsidian': 'Install Obsidian?',
  'barra2.da': 'From',
  'barra2.github-obsidian': 'github.com/obsidianmd (official)',
  'barra2.peso': 'Size',
  'barra2.circa-230-mb': 'about 230 MB',
  'barra2.dove': 'Where',
  'barra2.applicazioni': 'Applications',
  'barra2.il-tuo-utente': 'your user folder',
  'barra2.obs-nota': 'Obsidian is free for personal use. It opens straight on your vault, on Home.',
  'barra2.installare-nome': 'Install {nome}?',
  'barra2.installare-cervello': 'Install the local brain?',
  'barra2.cosa': 'What',
  'barra2.ollama-motore': 'Ollama (engine) + {nome}',
  'barra2.circa-gb': 'about {gb} GB',
  'barra2.perche': 'Why',
  'barra2.cervello-nota': 'It downloads just once. Then it works without internet and without keys.',
  'barra2.solo-clic': 'Only a click confirms it.',
  'barra2.avviato': 'Started.',
  'barra2.continuo-da-solo': "You can close the panel: I'll carry on by myself.",
  'barra2.obsidian-pronto': 'Obsidian is ready',
  'barra2.cervello-pronto': 'Local brain ready',
  'barra2.sync-piede-cifrati': 'Encrypted, synced with {servizio}',
  'barra2.sync-piede': 'Synced with {servizio}',
  'barra2.la-tua-cartella-cloud': 'your cloud folder',
  'barra2.dati-restano-qui': 'Your data stays on this computer',
  'barra2.portachiavi-mac': 'The password is remembered on this computer (in the Keychain).',
  'barra2.portachiavi-windows': 'The password is remembered on this computer (protected by your Windows account).',
  'barra2.portachiavi-sistema': "The password is remembered on this computer (in the system keyring).",
  'barra2.senza-portachiavi': "This computer has no secure keyring: Lode will ask for the password every time it starts.",
  'barra2.sync-solo-app': "Sync between computers is in Lode's **desktop app**.",
  'barra2.sync-stato-illeggibile': "I can't read the sync status.",
  'barra2.sync-altro-computer': 'On the other computer, open Lode and choose “I already use Lode on another computer”, then the “{vault}” vault in {servizio}.',
  'barra2.la-cartella-cloud': 'the cloud folder',
  'barra2.sync-non-accesa': "Sync isn't on: Lode's data stays on this computer.",
  'barra2.sync-titolo-altro': 'I already use Lode on another computer · experimental',
  'barra2.sync-titolo': 'Sync between your computers · experimental',
  'barra2.sync-sperimentale': '<b>Experimental.</b> {testo}',
  'barra2.sync-cartella-cloud': "I use the cloud folder you already have: no account, no Lode server. I copy the vault there and switch to the copy; the old folder stays where it is. {prima}",
  'barra2.sync-interrotto': '<b>Moving to {servizio} was interrupted.</b> Your previous vault is untouched: choose the folder again and I\'ll pick up where I left off.',
  'barra2.cartella-cloud': 'cloud folder',
  'barra2.sync-interrotto-pw': "It started with a password: I'll ask you to type it again.",
  'barra2.vault-gia-qui': 'the vault is already here: nothing to move',
  'barra2.altra-cartella': 'Another folder…',
  'barra2.altra-cartella-dett': 'Syncthing, a network folder',
  'barra2.nessuna-cartella-cloud': "I can't find iCloud Drive, OneDrive, Dropbox or Google Drive on this computer: choose the folder that syncs yourself.",
  'barra2.scegli-vault-cloud': 'Choose the vault in the cloud folder',
  'barra2.gia-sincronizzato': '{servizio} · already synced',
  'barra2.scegli-vault': 'Choose the vault…',
  'barra2.scegli-vault-dett': 'the “Lode” folder in your cloud folder',
  'barra2.vault-resta': 'The vault currently on this computer stays where it is, untouched.',
  'barra2.vault-resta-altro': "If Lode here already has exams, grades or cards, I bring them into the group as “Data from another first launch”: you import them, nothing replaces the other computers' data.",
  'barra2.la-cartella-che-scegli': 'the folder you choose',
  'barra2.sintesi-uso-gia-altrove': 'I already use Lode elsewhere',
  'barra2.sintesi-sincronizza': 'sync',
  'barra2.sincronizzare-con': 'Sync with {servizio}?',
  'barra2.vault': 'Vault',
  'barra2.vault-resta-cloud': "stays where it is: it's already in the cloud folder",
  'barra2.cartella-lode-in': 'a “Lode” folder in {servizio}',
  'barra2.prima': 'Before',
  'barra2.dati-json-cronologia': "the old dati.json stays in the service's history",
  'barra2.vault-adesso-resta': 'your current vault stays where it is, untouched',
  'barra2.dati-di-lode': "Lode's data",
  'barra2.un-diario-per-computer': 'one journal per computer: no conflicts, nothing lost',
  'barra2.proteggi-con-password': "Protect Lode's data with a password",
  'barra2.password-almeno-8': 'Password (at least 8 characters)',
  'barra2.password': 'Password',
  'barra2.ripetila': 'Repeat it',
  'barra2.ripeti-password': 'Repeat the password',
  'barra2.cifrati-in-chiaro-anche': '<b>Encrypted:</b> {cifrati}. <b>Readable in the cloud folder</b>, even with the password:',
  'barra2.sync-nota-password': 'You can add the password later too (“Protect with a password”), or change it (“Change password”). On the other computers: “I already use Lode on another computer”. {prima}',
  'barra2.spostamento-con-password': 'The move started with a password: type it again.',
  'barra2.almeno-8': 'At least 8 characters.',
  'barra2.password-diverse': "The two passwords don't match.",
  'barra2.preparo': 'Preparing…',
  'barra2.sincronizzato-con': 'Synced with {servizio}.',
  'barra2.vault-era-gia-cloud': 'The vault was already in the cloud folder: from now on each computer only writes its own journal.',
  'barra2.cartella-prima-resta': 'The old folder (“{da}”) stays where it was: delete it yourself whenever you like. On the other computers: “I already use Lode on another computer”.',
  'barra2.vault-gia-in-servizio': "There's already a synced Lode vault in {servizio}.",
  'barra2.usa-uso-gia': 'Use “I already use Lode on another computer” to connect to it.',
  'barra2.annullato': 'Cancelled.',
  'barra2.niente-cambiato': "I didn't change anything.",
  'barra2.scrivi-password': 'Type the password.',
  'barra2.non-ancora': 'Not yet.',
  'barra2.non-andata-vault-intatto': "It didn't work: {errore}. Your previous vault is untouched.",
  'barra2.collegato-vault-in': 'Connected to the vault in {servizio}.',
  'barra2.dati-protetti-password': "Lode's data is protected by a password: type it to receive the data.",
  'barra2.ricevo-dati': "Getting data from the other computers: it'll arrive on its own. You can already use Lode.",
  'barra2.dati-importati-altrove': 'The data you had on this computer ({n} records) is in “Data from another first launch” in the “Sync” tab: import it from there. The old file stays in the “{vault}” vault.',
  'barra2.cartella-inusabile': "I can't use that folder.",
  'barra2.diario-illeggibile': "Lode's journal on this computer can't be read",
  'barra2.diario-illeggibile-nota': "Nothing was deleted: Lode's data folder isn't responding (disk full or broken?). Changes you make now go to a separate file.",
  'barra2.riprova': 'Try again',
  'barra2.vault-sparito': "This computer's Lode data is safe in its journal. If you moved the vault, choose the folder you put it in.",
  'barra2.trova-vault': 'Find the vault',
  'barra2.lode-vecchia-campi': { one: "<b>From an old Lode:</b> {n} field that differs from the current ones. Nothing changes by itself: a copy of the file is in Lode's data folder (sync/copie).", other: "<b>From an old Lode:</b> {n} fields that differ from the current ones. Nothing changes by itself: a copy of the file is in Lode's data folder (sync/copie)." },
  'barra2.aggiunte': { one: "<b>Data from another first launch or an old Lode:</b> {n} record (exams, cards, sessions…) that the journal doesn't have. It doesn't come in by itself.", other: "<b>Data from another first launch or an old Lode:</b> {n} records (exams, cards, sessions…) that the journal doesn't have. They don't come in by themselves." },
  'barra2.importa-aggiunte': 'Import the additions',
  'barra2.password-dati-lode': "Password for Lode's data",
  'barra2.intanto-funziona': "Meanwhile Lode works with this computer's data: changes wait in the journal. {portachiavi}",
  'barra2.ho-dimenticato-password': 'I forgot the password',
  'barra2.dimentica-password-qui': 'Forget the password here',
  'barra2.cifrati-in-chiaro': '<b>Encrypted:</b> {cifrati}. <b>Readable in the cloud folder:</b>',
  'barra2.cambia-password': 'Change password',
  'barra2.senza-password': "No password: anyone who can read your cloud folder can also read Lode's data, just like your notes.",
  'barra2.proteggi-password': 'Protect with a password',
  'barra2.recuperi': "The changes the journal couldn't take are in {n} “recupero-…json” files (the latest: “{file}”), in Lode's data folder: I didn't throw them away.",
  'barra2.recupero': "The changes the journal couldn't take are in the “{file}” file, in Lode's data folder: I didn't throw them away.",
  'barra2.smetti-qui': 'Stop on this computer',
  'barra2.importati-record': { one: 'Imported {n} record.', other: 'Imported {n} records.' },
  'barra2.ora-su-tutti': "Now they're on all your computers.",
  'barra2.non-andata-punto': "It didn't work.",
  'barra2.controllo': 'Checking…',
  'barra2.sbloccata': 'Unlocked.',
  'barra2.password-ricordata': 'The password is remembered on this computer.',
  'barra2.chiedero-prossimo-avvio': "I'll ask you for it next time Lode starts.",
  'barra2.password-nuova-almeno-8': 'New password (at least 8 characters)',
  'barra2.password-nuova': 'New password',
  'barra2.password-nuova-pronta': 'New password ready.',
  'barra2.altri-chiederanno': 'The other computers will ask you for it once.',
  'barra2.cambiare-password': 'Change the password?',
  'barra2.rifa-password-nuova': "Lode rebuilds its data in the cloud folder with the new password. {testo}",
  'barra2.scegliere-password-nuova': 'Choose a new password?',
  'barra2.proteggere-password': "Protect Lode's data with a password?",
  'barra2.rifa-cifrati': "Lode rebuilds its data in the cloud folder, encrypted with the password. The other computers will ask you for it. {testo}",
  'barra2.password-dimenticata': 'Password forgotten on this computer.',
  'barra2.chiedero-di-nuovo': "I'll ask you for it again.",
  'barra2.smettere-qui': 'Stop on this computer?',
  'barra2.vault-copiato-fuori': 'copied to a folder outside the cloud folder, which you choose',
  'barra2.tutti-dati': "all of it, including the other computers' data up to today",
  'barra2.gli-altri-computer': 'The other computers',
  'barra2.continuano-sincronizzarsi': 'keep syncing with each other',
  'barra2.smesso-qui': 'Stopped on this computer.',
  'barra2.smesso-nota': 'The vault is now outside the cloud folder. To stop everywhere, do it on every computer.',
  'barra2.sintesi-smessa': 'sync stopped here',
  'barra2.ultima-lezione': 'Last lecture',
  'barra2.lezione-di': '{corso} lecture',
  'barra2.cosa-sa-lode': 'What Lode knows about me',
  'barra2.vai-a-note': { one: 'Go to… · {n} note', other: 'Go to… · {n} notes' },
  'barra2.radice-vault': 'vault',
  'barra2.oggi': 'today',
  'barra2.cerca-nota-segnaposto': 'Search for a note: course, lecture, date…',
  'barra2.cerca-nota': 'Search for a note',
  'barra2.nessuna-nota': 'No notes found.',
  'barra2.sintesi-cerco': 'searching “{q}”',
  'barra2.sintesi-note': 'notes',
  'barra2.niente-appunti-di': "I can't find any **{corso}** notes from the last few days.",
  'barra2.niente-appunti': "I can't find a lecture with enough notes: write them in the “{sezione}” section of the note.",
  'barra2.appunti-serve-ai': 'Reading your notes needs AI: install the **local brain** (free, works offline) from “Set up Lode”, or connect your own AI: type “AI”.',
  'barra2.leggo-appunti-di': 'Reading the {corso} notes…',
  'barra2.appunti-illeggibili': "I couldn't read the notes: {errore}",
  'barra2.nessuna-definizione-nuova': "I didn't find any new definitions in the notes. Try writing them out in full, even short ones.",
  'barra2.aggiungere-a': 'Add to {corso} · {data}?',
  'barra2.chiudi-nota': { one: '{n} definition in the lecture note. Check it is right: {motore} wrote it.', other: '{n} definitions in the lecture note. Check they are right: {motore} wrote them.' },
  'barra2.chiudi-nota-stelle': { one: '{n} definition and {stelle} ★ in the lecture note. Check they are right: {motore} wrote them.', other: '{n} definitions and {stelle} ★ in the lecture note. Check they are right: {motore} wrote them.' },
  'barra2.lezione-chiusa': 'Lecture wrapped up.',
  'barra2.definizioni-pronte': { one: '{n} definition ready for the games.', other: '{n} definitions ready for the games.' },
  'barra2.sintesi-definizioni': { one: '{n} definition', other: '{n} definitions' },
  'barra2.appunti-sparsi-oggi': "today's loose notes",
  'barra2.la-nota-di': 'the {corso} note',
  'barra2.apro-in-obsidian': 'Opening {nome} in Obsidian.',
  'barra2.apro-se-non-trova': "Opening {nome}. If Obsidian can't find the vault, the first time choose **Open folder as vault** and pick the “{percorso}” folder: then it stays connected.",
  'barra2.aperto-editor': 'I opened {nome} with the system editor. With **Obsidian** (free, obsidian.md) the “{percorso}” vault is ready to go: folders, templates, timetable and your memory.',
  'barra2.nota-non-si-apre': "I can't open the note: {errore}",
  'barra2.appunti-solo-app': "Obsidian notes are in Lode's **desktop app**: there every lecture becomes a note in your vault, with the ★ and definitions you mark from the bar.",
  'barra2.gioco-sai-gia-di': "You already know today's {corso} definitions: they come back when they're about to slip away.",
  'barra2.gioco-sai-gia': "You already know today's definitions: they come back when they're about to slip away.",
  'barra2.gioco-nessuna-di': 'No {corso} definitions yet. In class press **Definition** (or type “def: term = definition”), or write them in Obsidian in the lecture\'s “{sezione}” section.',
  'barra2.gioco-nessuna': 'No definitions yet. In class press **Definition** (or type “def: term = definition”), or write them in Obsidian in the lecture\'s “{sezione}” section.',
  'barra2.gioco-di': 'Game · {corso}',
  'barra2.ultime-lezioni': 'latest lectures',
  'barra2.manche-di': '{i} of {n}',
  'barra2.abbina': 'Match each term to its definition.',
  'barra2.chi-sono': 'Who am I?',
  'barra2.completa': '{termine}: complete the definition.',
  'barra2.parola-mancante': 'Missing word',
  'barra2.controlla-invio': 'Check <kbd>Enter</kbd>',
  'barra2.non-la-so': "I don't know",
  'barra2.te-la-ricordi': 'Do you remember it?',
  'barra2.mostra-spazio': 'Show <kbd>Space</kbd>',
  'barra2.non-la-sapevo': "I didn't know it <kbd>1</kbd>",
  'barra2.la-sapevo': 'I knew it <kbd>2</kbd>',
  'barra2.tutte-giuste': 'All right. These ones stick.',
  'barra2.da-rinforzare': 'To strengthen: {elenco}. They come back tomorrow.',
  'barra2.secondi': { one: '{n} second', other: '{n} seconds' },
  'barra2.minuti': '{n} min',
  'barra2.sintesi-punti': '{punti} of {tot}',
  'barra2.ancora-una': 'One more',
  'barra2.gioca-ancora': 'Play again',
  'barra2.sintesi-gioco': 'game',
  'barra2.pausa-finita': 'Break over.',
  'barra2.fermato-dopo': 'Stopped after {tempo}.',
  'barra2.prova-resta-aperta': 'The mock exam stays open: type “mock exam” to hand it in.',
  'barra2.li-conto': 'I count them in your study hours.',
  'barra2.sintesi-timer-fermato': 'timer stopped',
  'barra2.nessun-timer': "There's no timer running.",
  'barra2.timer-in-pausa': 'Timer paused.',
  'barra2.scrivi-riprendi': "Type “resume” when you're back.",
  'barra2.si-riparte': "Let's go again.",
  'barra2.focus-esame-sconosciuto': "I can't find **{nome}** among your exams. Shall I start free study? Type “focus {min}”.",
  'barra2.di-quale-esame': 'Which exam?',
  'barra2.idoneita-registrata': '{nome}: pass recorded.',
  'barra2.voto-in': '{voto} in {nome}.',
  'barra2.voto-lode-in': '{voto} cum laude in {nome}.',
  'barra2.nuovo-esame-6-cfu': 'New 6-credit exam: fix the credits in your grades.',
  'barra2.media-diff': 'Average {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome}: {voto}',
  'barra2.idoneita': 'pass',
  'barra2.trenta-e-lode': '30 cum laude. Time to celebrate.',
  'barra2.bel-colpo': 'Nice one. Rest today, tomorrow we go again.',
  'barra2.esame-aggiornato': '{nome} updated.',
  'barra2.esame-aggiunto': '{nome} added.',
  'barra2.esame-nota': '{quando} · {cfu} credits',
  'barra2.esame-nota-cambiali': '{quando} · {cfu} credits (change them if there are more)',
  'barra2.senza-data': 'no date',
  'barra2.piano-ore': 'To get there ready: about **{h} h a day** ({tot} h in total).',
  'barra2.proposte-spente-riaccendi': 'Suggestions are off: turn them back on with “suggestions normal”.',
  'barra2.proposte-da-adesso': "From now on, when you're at the computer and free, I'll suggest games, reviews and questions on {nome}.",
  'barra2.proposte-da-adesso-vicino': "From now on, when you're at the computer and free, I'll suggest games, reviews and questions on {nome}, more and more often as it gets closer.",
  'barra2.carta-aggiunta': 'Card added.',
  'barra2.senza-esame': 'no exam',
  'barra2.esame-sconosciuto': "I can't find **{nome}** among your exams.",
  'barra2.spiego-senza-programma': "First paste an exam syllabus (“syllabus for calculus 2”): then you explain its topics to me and I'll tell you what you skipped.",
  'barra2.argomento-sconosciuto': "I can't find **{q}** in your exam syllabuses.",
  'barra2.esame-non-trovato': "I can't find the **{nome}** exam.",
  'barra2.domande-di-quale-esame': 'Which exam? For example: “past exam questions for calculus 2: …”.',
  'barra2.nella-nota-lezione': 'In the lecture note.',
  'barra2.in-orario': '{corso} added to the timetable.',
  'barra2.aula': 'room {aula}',
  'barra2.sintesi-in-orario': '{corso} in the timetable',
  'barra2.orario-spiegazione': "When you're in class the bar knows it: it opens on quick capture (★ for the exam, definitions, questions) and at home it suggests two minutes of play on what you just covered.",
  'barra2.proposte-spente': 'Suggestions off.',
  'barra2.proposte-poche': 'Few suggestions.',
  'barra2.proposte-normali': 'Normal suggestions.',
  'barra2.proposte-frequenti': 'Frequent suggestions.',
  'barra2.riaccendi-quando-vuoi': 'Turn them back on whenever you like.',
  'barra2.proposte-mai-quando': 'Never in class, at work, in focus or during quiet hours.',
  'barra2.niente-da-proporre': "I've got nothing to suggest for now: add an exam with a date, or mark a few definitions in class.",
  'barra2.trascrizione-in-pausa': 'Transcription paused.',
  'barra2.scrivi-riprendi-trascrizione': 'Type “resume transcription” when it starts again.',
  'barra2.riprendo-trascrivere': 'Transcribing again.',
  'barra2.err-valutato': "Graded project: I won't show you the fix.",
  'barra2.errore-spiegato': 'Error explained',
  'barra2.correzione-vista': 'fix seen',
  'barra2.copia-errore': 'Copy the error from the terminal (or the IDE) and type “explain the error” again.',
  'barra2.incolla-errore': 'Paste the error after the colon: “explain the error: …”.',
  'barra2.nessun-errore-nel-testo': "I can't find a compiler or program error in this text. Copy all of it, from the line with the file name, and try again.",
  'barra2.segui-valutato': "You're following a graded project: I won't show you the fix.",
  'barra2.diario-solo-app': "The diary lives in the vault: you need Lode's **desktop app**.",
  'barra2.progetto-sconosciuto': "I can't find a project called “{nome}”.",
  'barra2.nessun-progetto-segui': "I'm not following any project yet. Type **follow project** and choose the lab folder.",
  'barra2.diario-spento-per': "The diary for **{progetto}** is off: I don't write anything in the vault. Turn it back on with “turn on the diary for {progetto}”.",
  'barra2.diario-non-si-apre': "I can't open the diary: {errore}",
  'barra2.diario-di': '{progetto} diary.',
  'barra2.aperto-editor-sistema': "Opened with the system editor: it's easier with Obsidian.",
  'barra2.aperto-in-obsidian': '{file} · opened in Obsidian.',
  'barra2.sintesi-diario-di': '{progetto} diary',
  'barra2.nessun-progetto': "I'm not following any project yet.",
  'barra2.diario-acceso': '{nome} diary on.',
  'barra2.diario-acceso-nota': "I write down in the vault what I see: what changes and the test runs. I can't tell who wrote the lines.",
  'barra2.diario-spento': '{nome} diary off.',
  'barra2.diario-spento-nota': "From now on I won't write anything about this project in the vault. Notes already written stay: you can remove them from Obsidian.",
  'barra2.focus-di-minuti': '{min}-minute focus.',
  'barra2.focus-di-minuti-su': '{min}-minute focus on {nome}.',
  'barra2.salvare-carte': { one: 'Save {n} card?', other: 'Save {n} cards?' },
  'barra2.salvare-carte-di': { one: 'Save {n} {nome} card?', other: 'Save {n} {nome} cards?' },
  'barra2.entrano-ripasso': "They go into today's review.",
  'barra2.carte-salvate': { one: '{n} card saved.', other: '{n} cards saved.' },
  'barra2.ripassa-ora': 'Review now',
  'barra2.sintesi-carte': { one: '{n} card', other: '{n} cards' },
  'barra2.aggiungere-esame': 'Add {nome}?',
  'barra2.esame': 'Exam',
  'barra2.cfu': 'Credits',
  'barra2.appello': 'Exam date',
  'barra2.registrare-voto': 'Record {voto}?',
  'barra2.registrare-voto-lode': 'Record {voto} cum laude?',
  'barra2.esame-nuovo-6-cfu': '{nome} (new, 6 credits)',
  'barra2.voto': 'Grade',
  'barra2.voto-e-lode': '{voto} cum laude',
  'barra2.voto-registrato': 'Grade recorded.',
  'barra2.media': 'Average {media}',
  'barra2.leggo-il-file': 'Reading the file…',
  'barra2.prof-ci-pensa': 'The examiner is thinking…',
  'barra2.un-attimo': 'One moment…',
  'barra2.file-senza-carte-locale': "I couldn't get any cards out of this file: if it's a PDF, the local model can't read it. Try a photo of the pages or the text.",
  'barra2.file-illeggibile': "I couldn't read the file: {errore}",
  'barra2.chiave-non-valida-ricollega': 'The key is not valid: connect it again by typing “AI”.',
  'barra2.troppe-richieste': 'Too many requests in a short time: try again in a minute.',
  'barra2.sovraccarico': '{motore} is overloaded right now: try again shortly.',
  'barra2.manca-rete': "Looks like you're offline.",
  'barra2.qualcosa-non-andato': 'Something went wrong: {errore}',
  'barra2.orale-serve-ai-app': 'A mock oral needs AI: install the **local brain** from “Set up Lode” (free, offline) or connect your own AI (type “AI”). Meanwhile you can **review** your cards.',
  'barra2.orale-serve-ai-web': 'A mock oral needs AI: add your Claude key in **Settings** (it costs a few cents per session). Meanwhile you can **review** your cards.',
  'barra2.orale-esame-sconosciuto': "I can't find **{nome}**: I'll quiz you on it anyway.",
  'barra2.su-quale-esame': 'On which exam?',
  'barra2.aggiungi-prima-esame': 'Add an exam first.',
  'barra2.interrogami-su': 'Quiz me on {nome}',
  'barra2.orale-di-contesto': 'Oral · <b>{nome}</b>',
  'barra2.esci': 'Exit',
  'barra2.sintesi-orale-di': '{nome} oral',
  'barra2.domanda-n-di': '**Question {n} of {max}.** {domanda}',
  'barra2.prof-non-risponde': "The examiner isn't answering: {errore}",
  'barra2.prof-ascolta': 'The examiner is listening…',
  'barra2.orale-mancava': 'Missing: {cosa}',
  'barra2.era-giusta': 'It was right',
  'barra2.segnata-giusta': 'Marked right',
  'barra2.prof-scrive-voto': 'The examiner is writing the grade…',
  'barra2.orale-titolo': { one: 'Oral · {nome} · {n} question', other: 'Oral · {nome} · {n} questions' },
  'barra2.da-ripassare': 'To review',
  'barra2.orale-calcolo': 'Lode works out the grade from your answers (right 3 points, partial 2).',
  'barra2.orale-calcolo-contestate': { one: 'Lode works out the grade from your answers (right 3 points, partial 2), counting the answer you marked right.', other: 'Lode works out the grade from your answers (right 3 points, partial 2), counting the answers you marked right.' },
  'barra2.orale-giudizi-locale': "The judgements are the local model's opinion: it can be wrong. It's practice, not a prediction.",
  'barra2.orale-giudizi-ai': "The judgements are the AI's opinion. It's practice, not a prediction.",
  'barra2.sintesi-orale-voto': '{nome} oral: {voto}',
  'barra2.orale-chiuso': 'Oral over.',
  'barra2.ripassa-esitato': 'Review the questions where you hesitated.',
  'barra2.agenti-solo-app': "The bridge with the agents is in Lode's **desktop app**.",
  'barra2.ponte-non-risponde': "The bridge isn't responding: {errore}",
  'barra2.agente-sconosciuto': "I can't connect to **{agente}** yet. Type “agents” to see the ones I know.",
  'barra2.agenti-titolo': 'Coding agents',
  'barra2.agenti-spiegazione': 'Connect the agent you use for labs: at the end of each turn Lode tells you what it really touched in the projects you follow, whether it ran the tests after the last change and whether it changed the tests while they were failing.',
  'barra2.ag-collegato-eventi': { one: 'connected · {n} event, the last at {ora}', other: 'connected · {n} events, the last at {ora}' },
  'barra2.ag-collegato-nessuno': 'connected · no events yet',
  'barra2.ag-trovato': 'found on this computer',
  'barra2.ag-non-trovato': 'not found',
  'barra2.scollega': 'Disconnect',
  'barra2.agenti-nota': "Read only: Lode doesn't answer the agents, doesn't decide anything and doesn't widen their permissions. Before writing to their configuration it shows you the exact lines. Events only count in the projects you follow (“follow project”), the rest are thrown away; what you write to the agent isn't saved.",
  'barra2.sintesi-agenti': 'agents',
  'barra2.niente-toccato': "OK, I didn't touch anything.",
  'barra2.ag-scollegato': '{nome} disconnected.',
  'barra2.ag-gia-collegato': '{nome} was already connected.',
  'barra2.ag-collegato': '{nome} connected.',
  'barra2.ag-tolte-righe': 'I only removed my own lines.',
  'barra2.ag-poi-segui': 'Then follow the lab project (“follow project”).',
  'barra2.l-agente': 'The agent',
  'barra2.ag-finito-test-dopo': { one: 'has finished: {n} file, tests run after the last change', other: 'has finished: {n} files, tests run after the last change' },
  'barra2.ag-finito-test-prima': { one: 'has finished: {n} file, tests not run again', other: 'has finished: {n} files, tests not run again' },
  'barra2.ag-finito-senza-test': { one: 'has finished: {n} file, no tests', other: 'has finished: {n} files, no tests' },
  'barra2.guarda': 'Look',
  'barra2.nessun-turno': "No agent turns yet in the projects you follow. Type “agents” to connect one.",
  'barra2.esito-non-noto': 'outcome unknown',
  'barra2.riuscito': 'passed',
  'barra2.fallito-codice': 'failed (code {codice})',
  'barra2.alle': 'at {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> file touched: {elenco}.', other: '<b>{n}</b> files touched: {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> files touched.',
  'barra2.comandi': { one: '{n} command', other: '{n} commands' },
  'barra2.test-lanciati-dopo': { one: 'tests run {n} time, the last <code>{comando}</code> {esito}, after the last change', other: 'tests run {n} times, the last <code>{comando}</code> {esito}, after the last change' },
  'barra2.test-lanciati-prima': { one: 'tests run {n} time, the last <code>{comando}</code> {esito}, <b>before</b> the last change', other: 'tests run {n} times, the last <code>{comando}</code> {esito}, <b>before</b> the last change' },
  'barra2.nessun-test-lanciato': 'no tests run',
  'barra2.cosa-cambiato': 'What changed',
  'barra2.prova-tu': 'Test it yourself',
  'barra2.preparati-discussione': 'Get ready for the discussion',
  'barra2.parole-agente': "What the agent says is just words: it really ran the tests only if you see them here. The rules are fixed: if they find nothing, that's not a guarantee.",
  'barra2.prova-il-progetto': 'Test the project',
  'barra2.sintesi-turno': { one: '{chi}: {n} file', other: '{chi}: {n} files' },
};
