// Welcome texts (English): the required steps (name, installs) and the quick setup (course, grades, exams, timetable,
// habits), plus connecting to a Lode you already have on another computer.
export default {
  // the frame
  'benvenuto.tasti-mac': '⌥ Space',
  'benvenuto.tasti-altri': 'Ctrl ⇧ Space',
  'benvenuto.avanti': 'Next',
  'benvenuto.indietro': 'Back',
  'benvenuto.salta': 'Skip',
  'benvenuto.obbligatorio': 'Required',
  'benvenuto.facoltativo': 'Optional · quick setup',
  // hello
  'benvenuto.ciao-titolo': "Hi.<br>I'm Lode.",
  'benvenuto.ciao-sotto': "I live in a small bar at the top of your screen. In class I make sure you don't miss a thing, at home I train you on what you're about to forget, and I keep everything in your Obsidian.",
  'benvenuto.ciao-nota': 'First, three things you need (two minutes, plus the downloads). Then, if you like, the quick setup.',
  'benvenuto.altro-computer': 'I already use Lode on another computer',
  'benvenuto.sperimentale': '(experimental)',
  'benvenuto.iniziamo': "Let's start",
  // another computer
  'benvenuto.scegli-vault-cloud': "Choose Lode's vault in your cloud folder (iCloud Drive, OneDrive, Dropbox, Google Drive).",
  'benvenuto.scegli-vault': 'Choose the vault…',
  'benvenuto.password-dati': "The password for Lode's data, if you set one",
  'benvenuto.collego': 'Connecting…',
  'benvenuto.cartella-no': "I can't use that folder.",
  'benvenuto.ricevo-dati': "Getting data from the other computers… You can already use Lode: it'll arrive on its own.",
  'benvenuto.inizia': 'Start',
  'benvenuto.password-sbagliata': 'Wrong password: try again.',
  'benvenuto.password-serve': "Lode's data is protected by a password: type it above.",
  // name
  'benvenuto.nome-titolo': "What's your name?",
  'benvenuto.nome-sotto': 'Just to say hi. It stays on your computer.',
  'benvenuto.nome-segnaposto': 'Your name',
  'benvenuto.togli-esempio': "Remove “Giulia”'s sample data (fake exams, grades, cards and study hours). Anything you added yourself stays.",
  // installs
  'benvenuto.web-titolo': 'The full Lode lives in the app.',
  'benvenuto.web-sotto': 'In the browser you get grades, timer, reviews and games. Obsidian, AI on your computer, voice and lecture transcription are in the desktop app.',
  'benvenuto.installa-titolo': "Let's get your computer ready.",
  'benvenuto.installa-sotto': "Three installs, just once. After that Lode works offline too, and nothing of yours leaves your computer.",
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'where your notes live: a vault ready to go',
  'benvenuto.cervello': 'The local brain',
  'benvenuto.cervello-cosa': 'Ollama and Qwen3.5: reads your notes, makes cards and definitions, explains and quizzes you',
  'benvenuto.voce': 'Voice',
  'benvenuto.voce-cosa': '{voce}: voice commands, “Repeat” and lecture transcription',
  'benvenuto.peso-gb': '{n} GB',
  'benvenuto.peso-mb': '{n} MB',
  'benvenuto.installa-nota': "Obsidian is free for personal use and comes from its official website. The local brain is chosen based on your computer's memory.",
  'benvenuto.installa-tutto': 'Install everything',
  'benvenuto.gia-installato': 'Already installed',
  'benvenuto.modello-pronto': '{modello} is already ready',
  'benvenuto.gia-pronta': 'Already set up',
  'benvenuto.voce-pronta': '{voce} is ready',
  'benvenuto.scarico-voce-pct': 'Downloading voice · {p}%',
  'benvenuto.tutto-pronto': 'Obsidian, the local brain and voice are ready.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'the local brain',
  'benvenuto.scarico-voce': 'voice',
  'benvenuto.scarico-pct': '{cosa} {p}%',
  'benvenuto.scarico-continua-voce': 'Still downloading: {cosa}. It carries on by itself, even with the window closed; voice picks up in the bar as soon as you open Lode.',
  'benvenuto.scarico-continua': 'Still downloading: {cosa}. It carries on by itself, even with the window closed.',
  'benvenuto.scarico-solo-voce': 'Still downloading: {cosa}. Voice picks up in the bar as soon as you open Lode.',
  // quick setup
  'benvenuto.veloce-titolo': '{nome}, want the quick setup?',
  'benvenuto.veloce-sotto': "Tell me about your university, exams and timetable: from tomorrow Lode knows when you're in class, how far you are from graduating and what to review before each exam.",
  'benvenuto.veloce-lista': ['University and degree course', 'Your grades, pasted from the student portal or typed by hand', 'The exams you still have to take, with dates', "Your lecture timetable, also from the university's calendar (.ics)", 'How and when you study'],
  'benvenuto.veloce-nota': 'All optional, all editable later. Nothing goes online.',
  'benvenuto.facciamolo': "Let's do it",
  // course
  'benvenuto.corso-titolo': 'Where do you study?',
  'benvenuto.ateneo': 'University',
  'benvenuto.ateneo-segnaposto': 'Start typing…',
  'benvenuto.corso': 'Degree course',
  'benvenuto.corso-segnaposto': 'Computer Engineering',
  'benvenuto.tipo': 'Type',
  'benvenuto.tipo-180': "Bachelor's · 180 credits",
  'benvenuto.tipo-120': "Master's · 120 credits",
  'benvenuto.tipo-300': 'Single-cycle · 300 credits',
  'benvenuto.tipo-360': 'Single-cycle · 360 credits',
  'benvenuto.anno': 'Year',
  'benvenuto.anni': ['1st', '2nd', '3rd', '4th', '5th', '6th', 'Extra years'],
  'benvenuto.lode-vale': 'Cum laude counts as',
  'benvenuto.lode-nota': 'It depends on your regulations: if unsure, 30',
  // grades
  'benvenuto.libretto-titolo': "Exams you've already passed",
  'benvenuto.libretto-sotto': "Open your grades on the university portal (Esse3, Infostud…), select all, copy and paste here. I'll handle it. Or type them one per line: “Calculus 1, 9 credits, 28”.",
  'benvenuto.libretto-segnaposto': 'Paste your grades here…',
  'benvenuto.leggi-libretto': 'Read my grades',
  'benvenuto.leggo-libretto': 'Reading your grades…',
  'benvenuto.leggo': 'Reading…',
  'benvenuto.esami-trovati': { one: '{n} exam found: check and confirm.', other: '{n} exams found: check and confirm.' },
  'benvenuto.esami-non-trovati': "I didn't find any exams: try typing them one per line.",
  'benvenuto.col-esame': 'Exam',
  'benvenuto.col-cfu': 'Credits',
  'benvenuto.col-voto': 'Grade',
  'benvenuto.col-data': 'Date',
  'benvenuto.importa': 'Import',
  'benvenuto.idoneo': 'passed',
  'benvenuto.voto-lode': '{voto}L',
  // exams to take
  'benvenuto.esame': 'Exam',
  'benvenuto.cfu': 'Credits',
  'benvenuto.data-appello': 'Exam date',
  'benvenuto.togli': 'Remove',
  'benvenuto.esami-titolo': 'Exams still to take',
  'benvenuto.esami-sotto': 'With the exam date, if you know it. From there Lode works out how many hours you need each day and suggests reviews and games when you have a moment.',
  'benvenuto.altro-esame': '+ Another exam',
  // timetable
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · room {aula}',
  'benvenuto.nessuna-lezione': 'No lectures yet.',
  'benvenuto.orario-titolo': 'Your lecture timetable',
  'benvenuto.orario-sotto': "So Lode knows when you're in class: the bar gets ready for the lecture, “Repeat” and transcription are one key away, and at home it trains you on what you just heard.",
  'benvenuto.scrivila': "Type it the way you'd say it",
  'benvenuto.frase-segnaposto': 'calculus 2 monday and wednesday 9-11 room 7',
  'benvenuto.aggiungi': 'Add',
  'benvenuto.importa-ics': 'Import the calendar (.ics)',
  'benvenuto.incolla-orario': "Or paste the timetable from your university's website",
  'benvenuto.orario-segnaposto': 'Paste the timetable here…',
  'benvenuto.leggi-orario': 'Read the timetable',
  'benvenuto.frase-aiuto': 'Type course, days and times: “physics Monday 14-16 room B2”.',
  'benvenuto.lezioni-calendario': { one: '{n} lecture from the calendar.', other: '{n} lectures from the calendar.' },
  'benvenuto.calendario-vuoto': "I didn't find any weekly lectures in the calendar.",
  'benvenuto.leggo-orario': 'Reading the timetable…',
  'benvenuto.lezioni-trovate': { one: '{n} lecture found.', other: '{n} lectures found.' },
  'benvenuto.lezioni-non-trovate': "I didn't find any lectures: try typing them one at a time.",
  // habits
  'benvenuto.abitudini-titolo': 'How do you study?',
  'benvenuto.abitudini-sotto': "Lode suggests reviews, games and quick questions at random moments of the day, when you're at the computer. Tell me how often, and when to leave you alone.",
  'benvenuto.quando-meglio': 'When you study best',
  'benvenuto.mattina': 'Morning',
  'benvenuto.pomeriggio': 'Afternoon',
  'benvenuto.sera': 'Evening',
  'benvenuto.notte': 'Night',
  'benvenuto.proposte': "Lode's suggestions",
  'benvenuto.scelta-mai': 'Never',
  'benvenuto.scelta-poco': 'Few',
  'benvenuto.scelta-normale': 'Normal',
  'benvenuto.scelta-spesso': 'Lots',
  'benvenuto.proposte-nota': 'The closer the exam, the more often. Never during lectures, focus or at night.',
  'benvenuto.silenzio-dalle': 'Quiet from',
  'benvenuto.silenzio-alle': 'to',
  'benvenuto.focus': 'Focus',
  'benvenuto.minuti': '{n} min',
  'benvenuto.ripeti-in-aula': 'In class, “Repeat” turns on by itself (the last minute and a half, only in memory). Ask your lecturer if recording is allowed.',
  // end
  'benvenuto.fine-titolo': 'Done, {nome}.',
  'benvenuto.fine-sotto': 'Lode now lives at the top of your screen. Hover over it to open it, hold <b>{tasti}</b> to talk to it, drag a PDF or a photo of the board onto it.',
  'benvenuto.fine-esami': { one: '{fatti} exam in your grades, {dare} to take', other: '{fatti} exams in your grades, {dare} to take' },
  'benvenuto.fine-esami-prossimo': { one: '{fatti} exam in your grades, {dare} to take · the next one is {nome}', other: '{fatti} exams in your grades, {dare} to take · the next one is {nome}' },
  'benvenuto.fine-lezioni': { one: '{n} lecture a week in your timetable', other: '{n} lectures a week in your timetable' },
  'benvenuto.fine-proposte': 'Suggestions: {quante}',
  'benvenuto.quante-mai': 'never',
  'benvenuto.quante-poco': 'few',
  'benvenuto.quante-normale': 'normal',
  'benvenuto.quante-spesso': 'lots',
  'benvenuto.apri-lode': 'Open Lode',
};
