// Texts of the desktop app (English): system windows, tray icon menu, notifications and messages from the
// main process (desktop/*.mjs) that reach the student.
export default {
  // main.mjs: system windows
  'desktop.non-ci-sono-riuscito': 'That didn\'t work.',
  'desktop.benvenuto-in-lode': 'Welcome to Lode',
  'desktop.dove-tenere-il-vault': 'Where to keep the vault',
  'desktop.usa-questa-cartella': 'Use this folder',
  'desktop.non-e-andata': 'That didn\'t work.',
  'desktop.vault-con-sincronizzazione': 'With sync on, you change the vault from «Sync between your computers»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Stop on this computer» moves the vault out of the cloud folder.',
  'desktop.scegli-il-vault': 'Choose your Obsidian vault',
  'desktop.usa-questo-vault': 'Use this vault',
  'desktop.cartella-non-usabile': 'Lode can\'t use the folder {cartella}',
  'desktop.cartella-protetta-windows': 'Windows is probably protecting it (Windows Security › Ransomware protection › Controlled folder access) or your antivirus is blocking Lode. Allow Lode, or choose another folder.',
  'desktop.scegli-altra-cartella': 'Choose another folder',
  'desktop.riprova': 'Try again',
  'desktop.non-ora': 'Not now',
  'desktop.obsidian-pronto': 'Obsidian is ready on your vault',
  'desktop.modello-pronto': '{modello} is ready',
  'desktop.ponte-non-partito': 'The bridge with the agents didn\'t start: restart Lode.',
  'desktop.agente-togliere': 'Remove Lode from the {agente} configuration?',
  'desktop.agente-collegare': 'Connect {agente} to Lode?',
  'desktop.agente-toglie-righe': 'Lode only removes its own lines in:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode only adds its own lines, everything else stays as it is, in:\n{file}',
  'desktop.agente-manda-eventi': '{agente} will send Lode, on this computer, the session events (files touched, commands, end of turn). Lode doesn\'t reply and doesn\'t decide anything. ',
  'desktop.agente-file-com-era': 'The file as it was stays in {file}.',
  'desktop.togli': 'Remove',
  'desktop.collega': 'Connect',
  'desktop.annulla': 'Cancel',
  // main.mjs: the tray icon menu
  'desktop.menu-avvisami-versioni': 'Tell me about new versions',
  'desktop.menu-aggiornamenti-automatici': 'Automatic updates',
  'desktop.menu-riavvia-con': 'Restart with Lode {versione}',
  'desktop.menu-scarica': 'Download Lode {versione}…',
  'desktop.menu-apri': 'Open Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Space',
  'desktop.tasti-apri': 'Ctrl+Shift+Space',
  'desktop.menu-quadro': 'The overview: grades, exams, review',
  'desktop.menu-rifai-configurazione': 'Set up again…',
  'desktop.menu-apri-vault-obsidian': 'Open the vault in Obsidian',
  'desktop.menu-mostra-vault': 'Show the vault in its folder',
  'desktop.menu-altro-vault': 'Use another vault…',
  'desktop.menu-avvio-accensione': 'Start Lode when the computer starts',
  'desktop.menu-icona-mac': 'Lode icon in Applications',
  'desktop.menu-icona-win': 'Lode icon in the Start menu and on the desktop',
  'desktop.menu-icona-linux': 'Lode icon in the applications menu',
  'desktop.menu-esci': 'Quit Lode',
  // sincronizza.mjs: sync between computers
  'desktop.sync-file-occupato': 'A file is being used by another program: close it and try again. Your previous vault is untouched.',
  'desktop.sync-file-occupato-nome': 'A file is being used by another program ({file}): close it and try again. Your previous vault is untouched.',
  'desktop.sync-disco-pieno': 'The disk of the cloud folder is full. Your previous vault is untouched.',
  'desktop.sync-permesso': 'Lode isn\'t allowed to read or write a file. Your previous vault is untouched.',
  'desktop.sync-permesso-nome': 'Lode isn\'t allowed to read or write a file ({file}). Your previous vault is untouched.',
  'desktop.sync-copia-diversa': 'The copy of {file} didn\'t come out identical: try again. Your previous vault is untouched.',
  'desktop.sync-copia-non-riuscita': 'Copying the vault didn\'t work: try again. Your previous vault is untouched.',
  'desktop.sync-sto-accendendo': 'I\'m already turning sync on: wait for it to finish.',
  'desktop.sync-cartella-titolo': 'The folder that syncs',
  'desktop.sync-sincronizza-qui': 'Sync here',
  'desktop.sync-spostamento-con-password': 'The move started with the password: type it again.',
  'desktop.sync-dati-occupati': 'Lode\'s data file is being used by another program (an antivirus?): try again in a bit.',
  'desktop.sync-diario-illeggibile': 'Lode\'s log on this computer can\'t be read.',
  'desktop.sync-controllo-altro-computer': 'Checking whether another computer already syncs this vault…',
  'desktop.sync-aspetto-dati': 'Waiting for Lode\'s data to arrive from the cloud (the data file can\'t be read yet): try again in a bit.',
  'desktop.sync-altra-password': 'Sync is already on for this vault with a different password: type that one.',
  'desktop.sync-gia-con-password': 'Sync is already on for this vault with a password: type it.',
  'desktop.sync-non-accendo': 'I can\'t turn sync on here.',
  'desktop.sync-cartella-dentro-vault': 'This folder is inside the vault: choose one outside it, for example your iCloud Drive, OneDrive or Dropbox folder.',
  'desktop.sync-dati-non-ancora': 'Lode\'s data can\'t be read yet (folder not reachable?): try again in a bit.',
  'desktop.sync-copio-vault': 'Copying the vault…',
  'desktop.sync-copio-vault-file': 'Copying the vault… {n} files',
  'desktop.sync-cifro-pubblico': 'Encrypting and publishing Lode\'s data…',
  'desktop.sync-pubblico': 'Publishing Lode\'s data…',
  'desktop.sync-non-creo-dati': 'I can\'t create Lode\'s data in the cloud folder. Your previous vault is untouched.',
  'desktop.sync-vault-nel-cloud': 'The Lode vault in the cloud folder',
  'desktop.sync-non-e-vault-sincronizzato': 'There\'s no synced Lode vault in this folder: choose the «Lode» folder inside the cloud folder (on the other computer: «Sync between your computers»).',
  'desktop.sync-diario-altro-vault': 'On this computer Lode already uses the log of another vault: first «Stop on this computer».',
  'desktop.sync-password-sbagliata-di-nuovo': 'Wrong password: type it again.',
  'desktop.sync-password-vecchia': 'That\'s the old password: it was changed on another computer, type the new one.',
  'desktop.sync-lode-piu-nuova': 'This vault was protected by a newer Lode: update yours.',
  'desktop.sync-gruppo-manomesso': 'The password is right, but the group file in the cloud folder was changed from outside: I won\'t use it. Check the cloud folder.',
  'desktop.sync-gruppo-in-chiaro': 'The group in the cloud folder isn\'t encrypted: either sync on the other computer has no password, or the group file has been tampered with. If you didn\'t set a password on the other computer, try again without one.',
  'desktop.sync-password-sbagliata': 'Wrong password.',
  'desktop.sync-adesso-non-si-puo': 'Not possible right now.',
  'desktop.sync-cartella-in-cloud': 'This folder is inside a cloud folder: to sync, use «Sync between your computers».',
  'desktop.sync-fuori-dal-vault': 'Choose a folder outside your current vault.',
  'desktop.sync-non-sposto-dati': 'I can\'t move Lode\'s data to that folder. Your previous vault is untouched.',
  'desktop.sync-riprova-tra-poco': 'Not possible right now: try again in a bit.',
  'desktop.sync-password-corta': 'The password must be at least 8 characters long.',
  'desktop.sync-diario-illeggibile-riprova': 'Lode\'s log on this computer can\'t be read: first «Try again».',
  'desktop.sync-non-accesa': 'Sync isn\'t on for this computer.',
  'desktop.sync-vault-spostato-scegli': 'The vault is no longer where Lode was looking for it: if you moved it, use «Find the vault» and choose the folder you moved.',
  'desktop.sync-dove-fuori-cloud': 'Where to keep the vault, outside the cloud folder',
  'desktop.sync-tieni-qui': 'Keep the vault here',
  'desktop.sync-fuori-dal-cloud': 'Choose a folder outside the cloud folder.',
  'desktop.sync-vault-spostato': 'The vault is no longer where Lode was looking for it: if you moved it, use «Find the vault».',
  'desktop.sync-cambio-in-arrivo': 'The latest changes from this computer aren\'t in the cloud folder yet (a change from your other computers is on its way): try again in a bit.',
  'desktop.sync-smetti-serve-password': 'Changes made while paused would stay on this computer only: type the password before stopping (or «I forgot the password»).',
  'desktop.sync-note-non-scaricate': 'Some notes aren\'t downloaded on this computer ({note}): open them or download them from the cloud service, then try again.',
  'desktop.sync-note-non-scaricate-altre': 'Some notes aren\'t downloaded on this computer ({note} and {n} more): open them or download them from the cloud service, then try again.',
  'desktop.sync-copio-fuori-cloud': 'Copying the vault out of the cloud folder…',
  // progetto.mjs: «follow the project», the «Done. In plain words» summary and command confirmation
  'desktop.progetto-elenco': '{primi} and {ultimo}',
  'desktop.progetto-elenco-altre': '{primi} and {n} more',
  'desktop.progetto-elenco-altri': '{primi} and {n} more',
  'desktop.progetto-righe-piu-meno': { one: '{n} line added and {meno} removed', other: '{n} lines added and {meno} removed' },
  'desktop.progetto-righe-piu': { one: '{n} line added', other: '{n} lines added' },
  'desktop.progetto-righe-meno': { one: '{n} line removed', other: '{n} lines removed' },
  'desktop.progetto-solo-spazi': 'only spaces or line breaks',
  'desktop.progetto-file-nuovo': { one: 'new file ({n} line)', other: 'new file ({n} lines)' },
  'desktop.progetto-file-tolto': 'removed',
  'desktop.progetto-funzioni-nuove': { one: 'new function {elenco}', other: 'new functions {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'changed {elenco}', other: 'changed {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'removed {elenco}', other: 'removed {elenco}' },
  'desktop.progetto-file': '{file}: {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'New {elenco}.', other: 'New {elenco}.' },
  'desktop.progetto-esito-compila': 'compiles',
  'desktop.progetto-esito-non-compila': 'doesn\'t compile',
  'desktop.progetto-esito-sintassi-a-posto': 'syntax fine',
  'desktop.progetto-esito-errore-di-sintassi': 'syntax error',
  'desktop.progetto-esito-make-riuscito': 'make worked',
  'desktop.progetto-esito-make-non-riuscito': 'make failed',
  'desktop.progetto-prove-su': { one: '{n} test of {tot}', other: '{n} tests of {tot}' },
  'desktop.progetto-prova-non-partita': 'the test didn\'t start',
  'desktop.progetto-inizio-alle': { one: 'At {ora}, {n} file changed (+{piu} −{meno}).', other: 'At {ora}, {n} files changed (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'From {da} to {a}, {n} file changed (+{piu} −{meno}).', other: 'From {da} to {a}, {n} files changed (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**Tested?** Yes: it\'s the code tested at {ora} ({esito}).',
  'desktop.progetto-provato-no-codice': '**Tested?** No, but only files that aren\'t code changed here.',
  'desktop.progetto-provato-no': '**Tested?** No: nobody has compiled with Lode since the last change ({ora}).',
  'desktop.progetto-nota-chi': 'I don\'t know who wrote these lines.',
  'desktop.progetto-altri-file': 'And {n} more files.',
  'desktop.progetto-nessuna-cartella': 'I didn\'t get any folder.',
  'desktop.progetto-non-trovo-cartella': 'I can\'t find this folder.',
  'desktop.progetto-cartella-non-file': 'Choose a folder, not a file.',
  'desktop.progetto-radice-disco': 'This is the root of the disk: choose just the project folder (for example lab3).',
  'desktop.progetto-tutta-la-home': 'This folder contains your whole home: choose just the project folder.',
  'desktop.progetto-e-il-vault': 'This is the Lode vault (or contains it): choose the project folder.',
  'desktop.progetto-dati-di-lode': 'This is the folder where Lode keeps its data: choose the project one.',
  'desktop.progetto-troppi-progetti': 'I\'m already following {n} projects: stop following one («stop following …»), then try again.',
  'desktop.progetto-cartella-illeggibile': 'I can\'t read this folder.',
  'desktop.progetto-troppi-file': 'There are more than {n} files here: choose just the project folder (for example lab3).',
  'desktop.progetto-non-seguo': 'I\'m not following this project.',
  'desktop.progetto-versione-scaduta': 'That version is gone: Lode keeps versions for 30 days.',
  'desktop.progetto-file-non-seguito': 'This file isn\'t one of the ones I follow.',
  'desktop.progetto-file-illeggibile': 'I can\'t read the file.',
  'desktop.progetto-poi-per-ogni-prova': 'Then, for each .in → .out test:\n{comandi}',
  'desktop.progetto-senza-prove': 'I won\'t run the program: there are no .in/.out tests.',
  'desktop.progetto-resto-non-mostro': '(I won\'t show the rest)',
  'desktop.progetto-smesso-durante-prova': 'I stopped following the project during the test.',
  'desktop.progetto-scegli-cartella': 'Choose the project folder',
  'desktop.progetto-segui-cartella': 'Follow this folder',
  'desktop.progetto-scegli-di-nuovo': 'Choose the folder again («follow project»).',
  'desktop.progetto-conferma-aperta': 'A confirmation window is already open: answer that one first.',
  'desktop.progetto-eseguira': 'Lode will run this command in the folder {cartella}.',
  'desktop.progetto-come-terminale': 'It\'s like running it from the terminal: the program runs on your computer.',
  'desktop.progetto-esegui-sempre': 'Always run for this project',
  // esegui.mjs: testing the project's code
  'desktop.esegui-riapri': 'If you\'ve just added it to the PATH, quit Lode (from the menu) and open it again.',
  'desktop.esegui-manca-c-win': 'I can\'t find a C compiler. Install MSYS2 (msys2.org), open «MSYS2 UCRT64» and type `pacman -S mingw-w64-ucrt-x86_64-gcc`: Lode finds it by itself in C:\\msys64\\ucrt64\\bin. Alternatively WinLibs (winlibs.com) or WSL. Lode doesn\'t download anything for you.',
  'desktop.esegui-manca-c-mac': 'I can\'t find a C compiler. Open Terminal and type `xcode-select --install`: it installs Apple\'s clang. Then try again.',
  'desktop.esegui-manca-c-linux': 'I can\'t find a C compiler. Install gcc (for example `sudo apt install build-essential`), then try again.',
  'desktop.esegui-manca-python-win': 'I can\'t find Python 3. Install it from python.org (tick «Add python.exe to PATH») or from the Microsoft Store, then try again.',
  'desktop.esegui-manca-python': 'I can\'t find Python 3. Install it (python.org, or from your package manager), then try again.',
  'desktop.esegui-manca-java': 'I can\'t find a JDK (javac and java). Install one, for example Temurin from adoptium.net, then try again.',
  'desktop.esegui-manca-make-win': 'There\'s a Makefile but I can\'t find make. With MSYS2, in «MSYS2 UCRT64»: `pacman -S mingw-w64-ucrt-x86_64-make`. Or remove the Makefile and Lode compiles the .c files by itself.',
  'desktop.esegui-manca-make': 'There\'s a Makefile but I can\'t find make. Install it (on a Mac: `xcode-select --install`), then try again.',
  'desktop.esegui-manca-programma': 'A program needed to test the code is missing.',
  'desktop.esegui-senza-prove': 'I can\'t find any .in/.out tests: I\'ll only compile, I won\'t run the program.',
  'desktop.esegui-make-prove': 'With the Makefile I won\'t run the {n} .in/.out tests: I don\'t know which program it builds.',
  'desktop.esegui-poi-prove': { one: 'then the test (.in file → expected .out)', other: 'then the {n} tests (.in file → expected .out)' },
  'desktop.esegui-poi-prove-in': { one: 'then the test in {cartella}/ (.in file → expected .out)', other: 'then the {n} tests in {cartella}/ (.in file → expected .out)' },
  'desktop.esegui-senza-programma': '{prove}; {n} without a clear program',
  'desktop.esegui-make-leggi': 'make runs the commands written in the Makefile: read it before confirming.',
  'desktop.esegui-make-assente': 'There\'s a Makefile but I can\'t find make: I\'ll compile the .c files myself.',
  'desktop.esegui-niente-codice': 'I can\'t find any C, Python or Java code to test in this folder.',
  'desktop.esegui-virgolette': 'The quotes aren\'t closed.',
  'desktop.esegui-invisibili': 'The command contains invisible characters (line breaks, control or text direction characters): type it again by hand.',
  'desktop.esegui-comando-vuoto': 'The command is empty.',
  'desktop.esegui-comando-illeggibile': 'The command can\'t be read.',
  'desktop.esegui-non-trovo-programma': 'I can\'t find the program «{programma}».',
  'desktop.esegui-bat': 'I don\'t run .bat and .cmd files: type the command they contain.',
  'desktop.esegui-compilazione-lenta': 'Compiling didn\'t finish within {n} seconds.',
  'desktop.esegui-prova-senza-programma': 'I don\'t know which program it\'s for',
  'desktop.esegui-programma-non-creato': 'The command didn\'t create the program to test.',
  'desktop.esegui-prova-illeggibile': 'I can\'t read the test files',
  // moodle.mjs: read-only Moodle
  'desktop.moodle-risponde': 'Moodle replies {stato}',
  'desktop.moodle-errore': 'Moodle error',
  'desktop.moodle-sito-risponde': 'the site replies {stato}',
  'desktop.moodle-non-e-moodle': 'it isn\'t a Moodle, or the app service is turned off',
  'desktop.moodle-non-collegato': 'Moodle isn\'t connected',
  'desktop.moodle-accesso-non-riuscito': 'login failed',
  'desktop.moodle-accedi-a': 'Log in to {sito}',
  'desktop.moodle-risposta-non-valida': 'invalid reply from Moodle',
  'desktop.moodle-tempo-scaduto': 'timed out',
  'desktop.moodle-file-non-trovato': 'file not found',
  'desktop.moodle-file-troppo-grande': 'file too large',
  'desktop.moodle-file-non-su-moodle': 'the file isn\'t on Moodle',
  // installa.mjs: Obsidian and the local brain (Ollama)
  'desktop.installa-download-non-riuscito': 'download failed ({stato})',
  'desktop.installa-non-firmato': 'The {nome} installer doesn\'t have the official {nome} signature, so I didn\'t install it. Try again later, or download it yourself from the official site.',
  'desktop.installa-versione-obsidian': 'unknown Obsidian version',
  'desktop.installa-scarico-obsidian': 'Downloading Obsidian {versione}',
  'desktop.installa-scarico-obsidian-mb': 'Downloading Obsidian {versione} · {mb} MB',
  'desktop.installa-installo-obsidian': 'Installing Obsidian',
  'desktop.installa-obsidian-installato': 'Obsidian {versione} installed',
  'desktop.installa-perche-4b': 'fast even without a graphics card: definitions, cards, games and oral',
  'desktop.installa-perche-35b': 'the smartest, and as fast as a small model, for computers with lots of memory',
  'desktop.installa-perche-9b': 'explains well and handles the oral',
  'desktop.installa-perche-memoria': 'for {gb} GB of memory: definitions, cards, games and oral',
  'desktop.installa-ollama-non-avviato': 'Ollama didn\'t start',
  'desktop.installa-ollama-linux': 'On Linux, install Ollama from ollama.com with their script, then come back here.',
  'desktop.installa-scarico-ollama-mb': 'Downloading Ollama · {mb} MB',
  'desktop.installa-installo-ollama': 'Installing Ollama',
  'desktop.installa-avvio-ollama': 'Starting Ollama',
  'desktop.installa-ollama-non-risponde': 'Ollama isn\'t responding',
  'desktop.installa-scarico-modello': 'Downloading {nome} · {fatti} of {totale} GB',
  'desktop.installa-modello-pronto': '{nome} ready',
  'desktop.installa-modello-assente': 'The model {modello} isn\'t installed',
  'desktop.installa-modello-non-risponde': 'The local model isn\'t responding',
  // aggiorna.mjs: new versions of Lode
  'desktop.aggiorna-github-risponde': 'GitHub replies {stato}',
  'desktop.aggiorna-non-installato': 'The update didn\'t install. Try again, or quit Lode: it installs when you quit.',
  'desktop.aggiorna-non-installato-perche': 'The update didn\'t install: {motivo}. Try again, or quit Lode: it installs when you quit.',
  'desktop.aggiorna-niente-pronto': 'There\'s no update ready to install.',
  'desktop.aggiorna-dove-scaricare': 'I don\'t know where to download it from yet: try again in a bit.',
  // voce-onnx.mjs and voce-onnx-motore.mjs: the Parakeet ONNX voice
  'desktop.voce-modello-illeggibile': 'I can\'t read the voice model: try again in a bit.',
  'desktop.voce-spazio': 'The Parakeet voice needs about {serve} MB free on the disk, there are {liberi}.',
  'desktop.voce-rete': 'I can\'t download the voice: check your connection and try again. ({dettaglio})',
  'desktop.voce-rete-stato': 'I can\'t download the voice ({stato}): try again later.',
  'desktop.voce-file-troppo-grande': 'The voice file is bigger than expected.',
  'desktop.voce-interrotto': 'The voice download was interrupted: it\'ll resume from here next time. ({dettaglio})',
  'desktop.voce-impronta': 'The voice file «{file}» isn\'t the right one (different SHA256 fingerprint): I deleted it.',
  'desktop.voce-addon': 'The voice program (sherpa-onnx) won\'t load on this computer.',
  'desktop.voce-modello-rovinato': 'The Parakeet model won\'t load (maybe a file is damaged).',
  'desktop.voce-pezzo-non-trascritto': 'Parakeet couldn\'t transcribe this part.',
  'desktop.voce-motore-chiuso': 'The voice engine closed unexpectedly.',
  'desktop.voce-motore-chiuso-codice': 'The voice engine closed unexpectedly ({codice}).',
  'desktop.voce-motore-non-risponde': 'The voice engine isn\'t responding.',
  // agenti-collegamenti.mjs: the connection with coding agents
  'desktop.agenti-claude-eventi': ['prompts', 'edits and commands', 'end of turn', 'notifications'],
  'desktop.agenti-claude-nota': 'The hooks apply from the next session (or review them in /hooks).',
  'desktop.agenti-codex-eventi': ['prompts', 'edits (apply_patch) and commands', 'end of turn'],
  'desktop.agenti-codex-nota': 'In the next session Codex will ask you to approve the new hooks: do it with /hooks.',
  'desktop.agenti-gemini-eventi': ['prompts', 'tools (files and commands)', 'end of reply', 'notifications'],
  'desktop.agenti-gemini-nota': 'Applies from the next Gemini CLI session.',
  'desktop.agenti-cursor-eventi': ['prompts', 'edited files', 'commands', 'agent reply'],
  'desktop.agenti-cursor-nota': 'Restart Cursor so it reads the hooks. Cursor doesn\'t report the commands\' exit code: you see the tests it runs, not the result.',
  'desktop.agenti-copilot-eventi': ['prompts', 'tools (files and commands)', 'end of turn', 'notifications'],
  'desktop.agenti-copilot-nota': 'A single Lode file in ~/.copilot/hooks: applies from the next session. Copilot doesn\'t send the agent\'s last message.',
  'desktop.agenti-windsurf-eventi': ['prompts', 'code written', 'commands', 'Cascade reply'],
  'desktop.agenti-windsurf-nota': 'Applies from the next Cascade conversation. Windsurf doesn\'t report the commands\' exit code.',
  'desktop.agenti-qwen-eventi': ['prompts', 'tools (files and commands)', 'end of turn', 'notifications'],
  'desktop.agenti-qwen-nota': 'Applies from the next Qwen Code session.',
  'desktop.agenti-opencode-eventi': ['edited files', 'commands', 'end of turn'],
  'desktop.agenti-opencode-nota': 'A Lode plugin in ~/.config/opencode/plugins: applies from the next OpenCode start. It only reads: it doesn\'t touch the replies.',
  'desktop.agenti-kilo-eventi': ['edited files', 'commands', 'end of turn'],
  'desktop.agenti-kilo-nota': 'The plugin is the OpenCode one (Kilo is a fork of it): applies from the next start. Event format still to be checked on your version.',
  'desktop.agenti-aider-eventi': ['end of reply (no details)'],
  'desktop.agenti-aider-nota': 'Aider only says it has finished replying, not what it touched: «follow project» sees the changed files.',
  'desktop.agenti-non-json': 'it isn\'t a JSON object',
  'desktop.agenti-file-non-di-lode': 'there\'s already a file with this name that isn\'t Lode\'s',
  'desktop.agenti-notifiche-aider': 'Aider notifications are already set: Lode won\'t overwrite them',
  'desktop.agenti-file-illeggibile': '{file} can\'t be read ({motivo}): I won\'t touch it. Fix it or connect by hand.',
  'desktop.agenti-altre-righe': 'and {n} more lines',
  'desktop.agenti-test-non-rilanciati': 'It says the tests pass, but it hasn\'t run them again since its last change.',
  'desktop.agenti-test-non-lanciati': 'It says the tests pass, but I didn\'t see it run them in this turn.',
  'desktop.agenti-test-toccati': 'It changed the tests ({file}) while they were failing: check it didn\'t make them easier.',
  // collegamento.mjs: Lode started from code (icon, start at login, Mac permissions)
  'desktop.permesso-audio-computer': 'Lode only listens to the computer\'s audio when you transcribe a video lecture. The audio never stays on the computer: only the text goes into the note.',
  'desktop.permesso-microfono': 'Lode uses the microphone when you talk to it, for «Repeat» in class and to transcribe the lectures you choose. The audio never stays on the computer.',
  'desktop.icona-non-creata': 'I can\'t create {file}',
};
