// The log in the vault (English): the lines of the project diary, the «Cosa so davvero» table and the
// «Informatica» section of Lode/Memoria.md. Section titles («## Cosa ho capito», «## Cosa so davvero», «## Informatica»),
// properties and the %% lode:… %% markers are NOT here: they are vault names that the code looks for.
export default {
  'diario.concetto-for': 'for loop',
  'diario.concetto-while': 'while loop',
  'diario.concetto-do-while': 'do-while loop',
  'diario.concetto-ritroso': 'Counting down',
  'diario.concetto-array': 'Arrays',
  'diario.concetto-divisione-intera': 'Integer division',
  'diario.concetto-resto': 'Remainder with negatives',
  'diario.concetto-cast': 'Cast to double',
  'diario.concetto-incremento': 'i++ and ++i',
  'diario.concetto-switch': 'switch and break',
  'diario.concetto-cortocircuito': 'Short-circuit && and ||',
  'diario.concetto-else-pendente': 'Dangling else',
  'diario.concetto-puntatori': 'Pass by address',
  'diario.concetto-parametri': 'Pass by value',
  'diario.concetto-visibilita': 'Variables in blocks',
  'diario.concetto-char': 'char and ASCII codes',
  'diario.concetto-ricorsione': 'Recursion',
  'diario.concetto-annidati': 'Nested loops',
  'diario.concetto-break-continue': 'break and continue',
  'diario.concetto-ternario': 'Ternary operator',
  'diario.concetto-printf': 'printf and formats',
  'diario.elenco-e': '{prima} and {ultimo}',
  'diario.errore-titolo': '«{titolo}»',
  'diario.errore-generico': 'error',
  'diario.passo-dove': '«where to look»',
  'diario.passo-cosa': '«what it means»',
  'diario.passi-visti': { one: 'seen {passi}', other: 'seen {passi}' },
  'diario.funzione-nuova': 'added {nome}',
  'diario.funzione-nuova-in': 'added {nome} in {file}',
  'diario.funzione-cambiata': 'changed {nome}',
  'diario.funzione-cambiata-in': 'changed {nome} in {file}',
  'diario.funzione-tolta': 'removed {nome}',
  'diario.funzione-tolta-in': 'removed {nome} from {file}',
  'diario.file-nuovo': 'new file {file}',
  'diario.file-tolto': 'removed {file}',
  'diario.cambiati-file': { one: 'Changed {n} file', other: 'Changed {n} files' },
  'diario.cambiato-codice': 'Changed the code',
  'diario.altre-modifiche': { one: 'and {n} more change', other: 'and {n} more changes' },
  'diario.chi-ha-scritto': 'who wrote it: I don\'t know',
  'diario.cambiato-durante': 'the code changed during the test',
  'diario.prova-non-compila': 'Test: ✗ doesn\'t compile',
  'diario.prova-non-compila-errore': 'Test: ✗ doesn\'t compile, {errore}',
  'diario.prova-non-partita': 'Test: didn\'t start',
  'diario.prova-ok': 'Test: ✓ compiles · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} tests',
  'diario.nessun-caso': 'no test cases',
  'diario.ma-cambiato': 'but the code changed during the test',
  'diario.codice-provato': 'code tested',
  'diario.prova-ko': 'Test: ✗ compiles · {ok}/{tot} tests',
  'diario.n-prove': { one: '{n} test', other: '{n} tests' },
  'diario.nessuna-prova': 'no tests',
  'diario.errori-risolti': { one: '{n} error fixed', other: '{n} errors fixed' },
  'diario.n-errori': { one: '{n} error', other: '{n} errors' },
  'diario.n-risolti': { one: '{n} fixed', other: '{n} fixed' },
  'diario.correzioni-viste': 'fixes seen: {n}',
  'diario.oggi': 'Today: {parti}',
  'diario.ultima-non-provata': 'last change not tested',
  'diario.smette': 'Lode stops following {progetto}',
  'diario.segue': 'Lode follows {progetto}',
  'diario.errore': 'Error: {errore}',
  'diario.correzione-vista': 'Fix seen: {errore}',
  'diario.spiegate': 'Explained: {spiegate} of {totale}',
  'diario.spiegate-rivedere': 'Explained: {spiegate} of {totale}; to go over again: {nomi}',
  'diario.ieri': 'yesterday',
  'diario.giorni-fa': { one: '{n} day ago', other: '{n} days ago' },
  'diario.stato-da-rifare': 'redo',
  'diario.stato-sicuro': 'solid',
  'diario.stato-mai-fatto': 'never done',
  'diario.diari-dei-progetti': 'Project diaries:',
  'diario.tabella-nota': 'Lode\'s tally of the «What does it print?» exercises, no AI. «Redo» means it\'s time to go over it again.',
  'diario.tabella-testa': '| Topic | Exercises | First try | Last time | Status |',
  'diario.nessun-esercizio': 'No exercises yet. Type «what does it print» in the bar: 5 one-minute questions.',
  'diario.errori-frequenti': 'Errors you run into most: {errori}.',
  'diario.sbagli-spesso': 'You often get wrong: {sbagli}.',
  'diario.memoria-stampa': { one: '«What does it print?»: {n} exercise, {giuste}% right first time.', other: '«What does it print?»: {n} exercises, {giuste}% right first time.' },
  'diario.da-rifare': 'Redo: {argomenti}.',
};
