// DA TRADURRE (en): per ora è la copia del catalogo italiano, messa dalla fase di estrazione perché la barra e
// test/lingue.mjs trovino tutte le chiavi. La fase di traduzione sostituisce i testi (stesse chiavi, parametri e tag).
// «Pronto per la discussione» (italiano, lingua di partenza): gli stati delle funzioni, i punti trovati nel codice e la scheda.
// Le parole che riconoscono la spiegazione dello studente (controlla() in js/codice/discussione.js) NON stanno qui.
export default {
  'discussione.data-breve': '{g}/{m}',
  'discussione.stato-agente': 'cambiata mentre lavorava l\'agente · mai spiegata',
  'discussione.stato-mai': 'mai spiegata',
  'discussione.stato-cambiata': 'cambiata dopo l\'ultima volta che l\'hai spiegata',
  'discussione.stato-rivedere': { one: 'da rivedere · hai saltato un punto', other: 'da rivedere · hai saltato {n} punti' },
  'discussione.stato-spiegata': 'spiegata il {data}',
  'discussione.spiegata-adesso': 'spiegata adesso',
  'discussione.punto-parametri-breve': 'i parametri',
  'discussione.punto-parametri': 'i parametri ({nomi})',
  'discussione.punto-niente': 'che non riceve niente',
  'discussione.punto-chiama': 'che chiama `{nome}`',
  'discussione.punto-ciclo-breve': 'il ciclo',
  'discussione.punto-ciclo': 'che c\'è un ciclo',
  'discussione.punto-ricorsiva-breve': 'che è ricorsiva',
  'discussione.punto-ricorsiva': 'che è ricorsiva: chiama se stessa',
  'discussione.punto-restituisce-breve': 'cosa restituisce',
  'discussione.punto-restituisce-niente': 'che non restituisce niente',
  'discussione.punto-restituisce-valore': 'che restituisce un valore',
  'discussione.punto-restituisce-tipo': 'che restituisce un `{tipo}`',
  'discussione.file-non-arrivato': 'il file non è arrivato',
  'discussione.nota': 'Lode non sa chi ha scritto le righe: «mentre lavorava l\'agente» vuol dire che il file è cambiato durante un suo turno. Lode non ti spiega il codice: controlla solo che tu lo sappia spiegare.',
  'discussione.hai-detto': 'Hai detto: {punti}.',
  'discussione.nessun-punto': 'Non trovo nessuno dei punti che vedo nel codice.',
  'discussione.hai-saltato': 'Hai saltato: {punti}.',
  'discussione.tutti-i-punti': 'Hai toccato tutti i punti che trovo nel codice.',
  'discussione.la-so-spiegare': 'La so spiegare',
  'discussione.proviamo': 'Proviamo',
  'discussione.titolo': 'Pronto per la discussione',
  'discussione.intro': 'Le funzioni cambiate da quando segui il progetto. Prima quelle cambiate mentre lavorava un agente e che non hai mai spiegato.',
  'discussione.diario-spento': 'Diario spento: non mi segno niente.',
  'discussione.spiegate': 'Spiegate: {spiegate} su {totale}',
  'discussione.nessuna-funzione': 'Non vedo funzioni cambiate in {nome} da quando lo segui. Quando cambiano, le trovi qui.',
  'discussione.lingua-sconosciuta': 'Per questa lingua non so controllare: segnala tu se la sai spiegare.',
  'discussione.leggo-il-file': 'Leggo il file…',
  'discussione.file-lungo': '{file} ha {n} righe: oltre 2000 non lo leggo. Segnala tu se la sai spiegare.',
  'discussione.non-riesco-leggere': 'Non riesco a leggere {file}: {errore}',
  'discussione.non-trovo-piu': 'Non trovo più <code>{nome}</code> in {file}: forse l\'hai rinominata o tolta.',
  'discussione.togli': 'Togli dall\'elenco',
  'discussione.spiegala': '<code>{firma}</code> · {file}, riga {riga}. Spiegala come alla discussione: cosa riceve, cosa restituisce, come funziona. Il codice te lo mostro dopo.',
  'discussione.aria-spiegazione': 'La tua spiegazione di {nome}',
  'discussione.ho-finito': 'Ho finito',
  'discussione.alla-buona': 'I punti li trova il codice, alla buona: non dice se la spiegazione è giusta.',
};
