// “Ready for the discussion” (English): function states, the points found in the code and the card.
// The words that recognise the student's explanation (controlla() in js/codice/discussione.js) are NOT here.
export default {
  'discussione.data-breve': '{g}/{m}',
  'discussione.stato-agente': 'changed while the agent was working · never explained',
  'discussione.stato-mai': 'never explained',
  'discussione.stato-cambiata': 'changed since you last explained it',
  'discussione.stato-rivedere': { one: 'go over it again · you skipped a point', other: 'go over it again · you skipped {n} points' },
  'discussione.stato-spiegata': 'explained on {data}',
  'discussione.spiegata-adesso': 'explained just now',
  'discussione.punto-parametri-breve': 'the parameters',
  'discussione.punto-parametri': 'the parameters ({nomi})',
  'discussione.punto-niente': 'that it takes nothing',
  'discussione.punto-chiama': 'that it calls `{nome}`',
  'discussione.punto-ciclo-breve': 'the loop',
  'discussione.punto-ciclo': 'that there\'s a loop',
  'discussione.punto-ricorsiva-breve': 'that it\'s recursive',
  'discussione.punto-ricorsiva': 'that it\'s recursive: it calls itself',
  'discussione.punto-restituisce-breve': 'what it returns',
  'discussione.punto-restituisce-niente': 'that it returns nothing',
  'discussione.punto-restituisce-valore': 'that it returns a value',
  'discussione.punto-restituisce-tipo': 'that it returns a `{tipo}`',
  'discussione.file-non-arrivato': 'the file didn\'t come through',
  'discussione.nota': 'Lode doesn\'t know who wrote the lines: “while the agent was working” means the file changed during one of its turns. Lode doesn\'t explain the code to you: it only checks that you can explain it.',
  'discussione.hai-detto': 'You said: {punti}.',
  'discussione.nessun-punto': 'I can\'t find any of the points I see in the code.',
  'discussione.hai-saltato': 'You skipped: {punti}.',
  'discussione.tutti-i-punti': 'You covered every point I find in the code.',
  'discussione.la-so-spiegare': 'I can explain it',
  'discussione.proviamo': 'Let\'s try',
  'discussione.titolo': 'Ready for the discussion',
  'discussione.intro': 'The functions that changed since you started following the project. First the ones that changed while an agent was working and that you\'ve never explained.',
  'discussione.diario-spento': 'Diary off: I\'m not noting anything down.',
  'discussione.spiegate': 'Explained: {spiegate} of {totale}',
  'discussione.nessuna-funzione': 'I don\'t see any changed functions in {nome} since you started following it. When they change, you\'ll find them here.',
  'discussione.lingua-sconosciuta': 'I can\'t check this language: tell me yourself if you can explain it.',
  'discussione.leggo-il-file': 'Reading the file…',
  'discussione.file-lungo': '{file} has {n} lines: I don\'t read past 2000. Tell me yourself if you can explain it.',
  'discussione.non-riesco-leggere': 'I can\'t read {file}: {errore}',
  'discussione.non-trovo-piu': 'I can\'t find <code>{nome}</code> in {file} any more: maybe you renamed or removed it.',
  'discussione.togli': 'Remove from the list',
  'discussione.spiegala': '<code>{firma}</code> · {file}, line {riga}. Explain it as you would at the discussion: what it takes, what it returns, how it works. I\'ll show you the code afterwards.',
  'discussione.aria-spiegazione': 'Your explanation of {nome}',
  'discussione.ho-finito': 'I\'m done',
  'discussione.alla-buona': 'The points are found by the code, roughly: it doesn\'t tell you whether the explanation is right.',
};
