// Compiler and program errors (js/errori.js), in English.
// The keys “errori.<entry>.<field>” are the texts of each dictionary entry: label, short, sentence, where, what, concept.
// Compiler messages quoted here stay in English, exactly as the compiler prints them.
export default {
  'errori.for-punto-e-virgola.etichetta': 'the `for` with commas',
  'errori.for-punto-e-virgola.frase': 'the three parts of the `for` must be separated with `;`',
  'errori.for-punto-e-virgola.dove': `Look at the \`for\` {allaRiga}: there must be two \`;\` inside the brackets.`,
  'errori.for-punto-e-virgola.cosa': 'A `for` has three parts: start, condition and step, as in `for (i = 0; i < n; i++)`. They\'re separated with `;`, not `,`. With commas the compiler sees just one part.',
  'errori.for-punto-e-virgola.concetto': 'for loop',
  'errori.punto-e-virgola.etichetta': 'missing `;`',
  'errori.punto-e-virgola.breve': 'missing ;',
  'errori.punto-e-virgola.frase': 'a `;` is missing',
  'errori.punto-e-virgola.dove': `Look at the end of line {riga}, the one before {riga2}: the \`;\` is missing there. The compiler only notices when it reads the next line.`,
  'errori.punto-e-virgola.dove-2': `Look at the end of line {riga}{colonna}: the \`;\` is missing there.`,
  'errori.punto-e-virgola.dove-3': `Look at the end of line {riga} and of the line before: sometimes the compiler only notices on the next line.`,
  'errori.punto-e-virgola.dove-4': 'Look at the end of the statements near the point shown.',
  'errori.punto-e-virgola.cosa': `In {L} every statement ends with \`;\`, just as a sentence ends with a full stop. Without it, the compiler glues the statement to the next one and can no longer tell what you meant. That's why the error is sometimes reported on the following line.`,
  'errori.punto-e-virgola.concetto': 'end of statements',
  'errori.include-mancante.etichetta': 'missing `#include`',
  'errori.include-mancante.breve': `missing #include{h}`,
  'errori.include-mancante.frase-2': 'this function',
  'errori.include-mancante.frase': `to use {nome} you need \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'this function',
  'errori.include-mancante.frase-3': `to use {nome} you need an \`#include\``,
  'errori.include-mancante.dove-2': `: the one for \`<{h}>\` is missing`,
  'errori.include-mancante.dove': `Look at the top of the file, where the \`#include\` lines are{h}.`,
  'errori.include-mancante.cosa': '`bool`, `true` and `false` aren\'t built into C: they come with `{h}`.',
  'errori.include-mancante.cosa-3': 'This name',
  'errori.include-mancante.cosa-4': `, that is \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome} isn't something you write yourself: it's in the C standard library. To use it you have to include the file that describes it (the header){h}. Without \`#include\` the compiler doesn't know it exists or how to use it.`,
  'errori.include-mancante.cosa-5': ' With `math.h`, on Linux also add `-lm` at the end of the compile command.',
  'errori.include-mancante.concetto': 'libraries and #include',
  'errori.funzione-non-dichiarata.etichetta': 'undeclared function',
  'errori.funzione-non-dichiarata.breve-2': 'function',
  'errori.funzione-non-dichiarata.breve': `{nome} undeclared`,
  'errori.funzione-non-dichiarata.frase': `you use the function {nome} before declaring it`,
  'errori.funzione-non-dichiarata.dove': `Find where you write the function {nome}: if it's below line {riga}, the compiler doesn't know it yet at that point. Also check the name is spelled exactly the same.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Find where you write the function {nome}: if it's below the line with the error, the compiler doesn't know it yet at that point. Also check the name is spelled exactly the same.`,
  'errori.funzione-non-dichiarata.cosa': 'The compiler reads the file from top to bottom. If you call a function it hasn\'t seen yet, it doesn\'t know what parameters it takes or what it returns: recent compilers stop, older ones guess and often get it wrong. Move the function above `main`, or write its prototype above `main`: the first line of the function followed by `;`.',
  'errori.funzione-non-dichiarata.concetto': 'function prototypes',
  'errori.non-dichiarato.etichetta': 'undeclared name',
  'errori.non-dichiarato.breve-2': 'name',
  'errori.non-dichiarato.breve': `{nome} undeclared`,
  'errori.non-dichiarato.frase': `you use {nome} but it isn't declared`,
  'errori.non-dichiarato.frase-2': 'you use a name that isn\'t declared',
  'errori.non-dichiarato.dove': `The compiler suggests {s}: check whether that's what you meant. `,
  'errori.non-dichiarato.dove-3': 'this name',
  'errori.non-dichiarato.dove-2': `Find where you declare {nome}: maybe it has a different name (one letter off, upper or lower case), or it's declared inside another \`{ }\` block.`,
  'errori.non-dichiarato.cosa': 'The method you call doesn\'t exist with that name and those argument types. Check how it\'s spelled and that it\'s in the right class. ',
  'errori.non-dichiarato.cosa-2': 'Before using a variable you have to declare it, that is write its type and its name (for example `int count = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'A variable declared inside `{ }` only exists in there: outside the block the compiler can\'t see it. Order matters too: the declaration must come above the line that uses it.',
  'errori.non-dichiarato.concetto': 'declaring variables and scope',
  'errori.formato.etichetta': 'wrong printf or scanf format',
  'errori.formato.frase': `the format expects a {atteso} but you pass a {dato}`,
  'errori.formato.frase-2': 'the format doesn\'t match the value you pass',
  'errori.formato.dove': `Look at line {riga}: match each \`%\` in the string with the value in the same position.`,
  'errori.formato.dove-senza-riga': `Look at the line shown: match each \`%\` in the string with the value in the same position.`,
  'errori.formato.cosa': 'In `scanf` each `%` wants the address of a variable of the right type: `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → `char` array. If the type doesn\'t match, the value read gets stored wrongly.',
  'errori.formato.cosa-2': ` For a {dato} in \`scanf\` you use {p}.`,
  'errori.formato.cosa-3': '`printf` doesn\'t know what type the values are: it trusts the format string. `%d` is for `int`s, `%f` for `double`s, `%c` for `char`s, `%s` for strings. If the format doesn\'t match the value, it prints meaningless numbers.',
  'errori.formato.cosa-4': ' For an `unsigned long` you use `%lu`; if it\'s the result of `strlen` or `sizeof` (a `size_t`) you use `%zu`.',
  'errori.formato.cosa-5': ` For a {dato} in \`printf\` you use {p}.`,
  'errori.formato.concetto': 'printf, scanf and formats',
  'errori.scanf-e-commerciale.etichetta': 'missing `&` in scanf',
  'errori.scanf-e-commerciale.breve': 'missing & in scanf',
  'errori.scanf-e-commerciale.frase': '`scanf` wants the address of the variable: `&` is missing',
  'errori.scanf-e-commerciale.dove': `Look at the \`scanf\` {allaRiga}: there's a variable without \`&\` in front of it.`,
  'errori.scanf-e-commerciale.cosa': '`scanf` has to write into your variable, so it needs to know where it is in memory: its address, which you get with `&`. You write `scanf("%d", &n);`. `char` arrays (strings) are the exception: their name is already an address, so no `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf and addresses',
  'errori.return-mancante.etichetta': 'missing `return`',
  'errori.return-mancante.breve': 'missing return',
  'errori.return-mancante.frase-2': `the function {nome}`,
  'errori.return-mancante.frase-3': 'the function',
  'errori.return-mancante.frase-4': 'sometimes ',
  'errori.return-mancante.frase': `{p} {sigla}reaches the end without a \`return\``,
  'errori.return-mancante.dove': `Look at the \`}\` {allaRiga}: it's the end of the function{p}. Follow every possible path (every \`if\` and \`else\`) and check that it ends with a \`return\`.`,
  'errori.return-mancante.cosa-2': ` (here it returns {tipo})`,
  'errori.return-mancante.cosa': `A function that isn't \`void\`{tipo} promises to return a value. If it reaches the final \`}\` without a \`return\`, the caller gets a random value. It often happens with an \`if\` that has its own \`return\` but no \`else\`.`,
  'errori.return-mancante.concetto': 'return in functions',
  'errori.assegnamento-in-condizione.etichetta': '`=` instead of `==`',
  'errori.assegnamento-in-condizione.breve': '= instead of ==',
  'errori.assegnamento-in-condizione.frase': 'the condition has `=` (assigns) instead of `==` (compares)',
  'errori.assegnamento-in-condizione.dove': `Look at the condition {allaRiga}{colonna}.`,
  'errori.assegnamento-in-condizione.cosa': '`=` puts a value into the variable; `==` checks whether two values are equal. `if (x = 5)` assigns 5 to `x` and is always true, because 5 isn\'t zero. To compare you need `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'assignment and comparison',
  'errori.confronto-stringhe.etichetta': 'strings compared with `==`',
  'errori.confronto-stringhe.frase': 'you compare strings with `==`',
  'errori.confronto-stringhe.dove': `Look at the comparison {allaRiga}.`,
  'errori.confronto-stringhe.cosa': 'In C `==` between two strings compares the addresses, not the letters: it\'s almost always false even if the text is the same. To compare the text you use `strcmp(a, b) == 0`, from `{h}`. If you meant a single character, write it in single quotes: `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'strings in C',
  'errori.puntatore-intero.etichetta': 'comparison between pointer and integer',
  'errori.puntatore-intero.frase': 'you compare an address (a pointer) with a number or a character',
  'errori.puntatore-intero.dove': `Look at both sides of the comparison {allaRiga}.`,
  'errori.puntatore-intero.cosa': 'On one side there\'s a pointer (an address, for example a string), on the other a number or a character. A typical mistake: `"a"` in double quotes is a string, `\'a\'` in single quotes is a character. To check a character write `s[0] == \'a\'`; to compare two strings use `strcmp`.',
  'errori.puntatore-intero.concetto': 'characters, strings and pointers',
  'errori.puntatori-incompatibili.etichetta': 'pointers of different types',
  'errori.puntatori-incompatibili.frase': `you use a {dato} where a {atteso} is needed`,
  'errori.puntatori-incompatibili.frase-2': 'you use a pointer of one type where another is needed',
  'errori.puntatori-incompatibili.dove': `Look at line {riga}: compare the type of what you pass (or assign) with the type that's needed.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Look at the line shown: compare the type of what you pass (or assign) with the type that's needed.`,
  'errori.puntatori-incompatibili.cosa': 'A pointer carries the type of what it points to: an `int *` points to integers, a `char *` to characters. Using one in place of the other usually means you picked the wrong variable, or the wrong type in the declaration or in the function parameter.',
  'errori.puntatori-incompatibili.concetto': 'pointers',
  'errori.intero-puntatore.etichetta': 'number and address mixed up',
  'errori.intero-puntatore.frase': 'you mix a number and an address (a pointer)',
  'errori.intero-puntatore.dove': `Look at line {riga}: on one side there's a pointer, on the other a normal value.`,
  'errori.intero-puntatore.dove-senza-riga': `Look at the line shown: on one side there's a pointer, on the other a normal value.`,
  'errori.intero-puntatore.cosa': 'A pointer holds a memory address, not just any number. If you want the address of a variable write `&x`; if you want the value a pointer points to write `*p`.',
  'errori.intero-puntatore.cosa-2': ' Here the compiler suggests `&`.',
  'errori.intero-puntatore.cosa-3': ' Here the compiler suggests `*`.',
  'errori.intero-puntatore.cosa-4': ' Careful: `"a"` in double quotes is a string; a character goes in single quotes: `\'a\'`.',
  'errori.intero-puntatore.concetto': 'pointers',
  'errori.variabile-non-usata.etichetta': 'unused variable',
  'errori.variabile-non-usata.breve-2': 'variable',
  'errori.variabile-non-usata.breve': `{nome} unused`,
  'errori.variabile-non-usata.frase-2': 'a variable',
  'errori.variabile-non-usata.frase': `{nome} is declared but you never use it`,
  'errori.variabile-non-usata.dove': `Look at the declaration {allaRiga}.`,
  'errori.variabile-non-usata.cosa': 'It\'s only a warning: the program compiles anyway. But it often means you forgot to use it, or that you\'re using another variable with a similar name by mistake. If you don\'t need it, remove it.',
  'errori.variabile-non-usata.concetto': 'variables',
  'errori.parametro-non-usato.etichetta': 'unused parameter',
  'errori.parametro-non-usato.frase': `the parameter {nome} is never used`,
  'errori.parametro-non-usato.dove': `Look at the first line of the function {allaRiga}.`,
  'errori.parametro-non-usato.cosa': 'The function receives this value but doesn\'t use it. Sometimes that\'s fine (for example `argc` and `argv` in `main`); other times it means you\'re using another variable in its place.',
  'errori.parametro-non-usato.concetto': 'function parameters',
  'errori.non-inizializzata.etichetta': 'variable with no value',
  'errori.non-inizializzata.breve-2': 'variable',
  'errori.non-inizializzata.breve': `{nome} has no value`,
  'errori.non-inizializzata.frase-2': 'a variable',
  'errori.non-inizializzata.frase': `you use {nome} before giving it a value`,
  'errori.non-inizializzata.dove-2': 'this variable',
  'errori.non-inizializzata.dove-3': ` (line {dichiarata})`,
  'errori.non-inizializzata.dove': `Look at {laRiga}, then go back up to the declaration of {nome}{dichiarata}: is there a path where it never gets a value?`,
  'errori.non-inizializzata.cosa': 'In Java a local variable must get a value before it\'s read, on every possible path (even when an `if` is false). Give it a starting value in the declaration, for example `int sum = 0;`.',
  'errori.non-inizializzata.cosa-2': 'A freshly declared local variable holds a random value, whatever was left in memory. Before reading it you have to give it a value, for example `int sum = 0;`. It often happens with sums and counters.',
  'errori.non-inizializzata.concetto': 'initialising variables',
  'errori.riferimento-non-definito.etichetta': 'function never defined (linker)',
  'errori.riferimento-non-definito.breve': 'missing main',
  'errori.riferimento-non-definito.breve-3': 'function',
  'errori.riferimento-non-definito.breve-2': `{nome} not defined`,
  'errori.riferimento-non-definito.frase': 'the `main` function is missing',
  'errori.riferimento-non-definito.frase-2': `{nome} can't be found: \`-lm\` is missing from the command`,
  'errori.riferimento-non-definito.frase-4': 'a function',
  'errori.riferimento-non-definito.frase-3': `{nome} is used but I can't find where it's written`,
  'errori.riferimento-non-definito.dove': 'Check that one of the files has `int main(void)` (or `int main(int argc, char *argv[])`) written exactly like that, and that the file is in the compile command.',
  'errori.riferimento-non-definito.dove-2': 'Look at the compile command: it needs `-lm` at the end.',
  'errori.riferimento-non-definito.dove-4': 'this function',
  'errori.riferimento-non-definito.dove-3': `The linker doesn't give a line. Search the project for the body of {nome}, that is the version with the \`{ }\`: the name must be identical (including upper case) and the file that contains it must be in the compile command.`,
  'errori.riferimento-non-definito.cosa': 'Every C program starts from `main`. If it\'s missing, or written with another name (`Main`, `mian`), there\'s no place to start from. On Windows the message sometimes mentions `WinMain`: it\'s the same problem.',
  'errori.riferimento-non-definito.cosa-2': 'The functions in `{h}` live in a separate library. On Linux (and sometimes with MinGW) you need to add `-lm` at the end of the command: `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'Compiling has two stages: first each `.c` file is translated on its own, then the linker joins them. The prototype tells the compiler the function exists, but the linker couldn\'t find its body anywhere. Usually the name is spelled differently, a file is missing from the command, or the function was never written.',
  'errori.riferimento-non-definito.concetto': 'compiling and the linker',
  'errori.definizione-multipla.etichetta': 'defined twice (linker)',
  'errori.definizione-multipla.breve-2': 'name',
  'errori.definizione-multipla.breve': `{nome} defined twice`,
  'errori.definizione-multipla.frase-2': 'a name',
  'errori.definizione-multipla.frase': `{nome} is defined twice in the program`,
  'errori.definizione-multipla.dove-2': 'this name',
  'errori.definizione-multipla.dove': `Search for {nome} in all the project files. It's often a variable or a function written inside a \`.h\` file included by several \`.c\` files, or a \`.c\` file included with \`#include\`.`,
  'errori.definizione-multipla.cosa': 'Every function and every global variable must have exactly one definition in the whole program. `.h` files only hold prototypes (and variables with `extern`); function bodies go in the `.c` files. You don\'t include a `.c` file with `#include`.',
  'errori.definizione-multipla.concetto': '.h and .c files',
  'errori.tipi-in-conflitto.etichetta': 'conflicting declarations',
  'errori.tipi-in-conflitto.frase-2': 'a function',
  'errori.tipi-in-conflitto.frase': `{nome} is declared in two different ways`,
  'errori.tipi-in-conflitto.dove-3': ` (line {prima})`,
  'errori.tipi-in-conflitto.dove': `Compare line {riga} with the earlier declaration{prima}: return type and parameters must be identical.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Compare the line shown with the earlier declaration{prima}: return type and parameters must be identical.`,
  'errori.tipi-in-conflitto.dove-5': 'the function',
  'errori.tipi-in-conflitto.dove-4': ` Here the first declaration is implicit: you called {nome} before declaring it. Put the prototype above \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'The prototype (the line with `;`, usually at the top or in a `.h`) and the actual function must say the same things: same return type, same parameter types, in the same order.',
  'errori.tipi-in-conflitto.concetto': 'function prototypes',
  'errori.argomenti.etichetta': 'wrong number of arguments',
  'errori.argomenti.frase': ` ({h} instead of {e})`,
  'errori.argomenti.frase-2': `you pass fewer arguments than the function wants{quanti}`,
  'errori.argomenti.frase-3': `you pass more arguments than the function wants{quanti}`,
  'errori.argomenti.frase-5': 'this function',
  'errori.argomenti.frase-4': `the call to {nome} doesn't match its parameters`,
  'errori.argomenti.dove-2': ` (line {dich})`,
  'errori.argomenti.dove': `Compare the call {allaRiga} with the first line of the function{nome}{dich}: count the arguments and look at their types.`,
  'errori.argomenti.cosa': 'A function must be called with as many arguments as it has parameters, in the same order. If the function is `int sum(int a, int b)`, the call is `sum(x, y)`.',
  'errori.argomenti.concetto': 'function parameters',
  'errori.graffa.etichetta': 'missing brace',
  'errori.graffa.frase': 'there\'s one `}` too many',
  'errori.graffa.frase-2': 'a `}` is missing',
  'errori.graffa.dove': `Look at the \`}\` {allaRiga}: it closes a block that was already closed. Count the \`{\` and \`}\` above it.`,
  'errori.graffa.dove-3': ` (line {riga})`,
  'errori.graffa.dove-4': ` The \`{\` left open is on line {aperta}.`,
  'errori.graffa.dove-2': `The compiler only notices at the end{riga}, but the brace is missing earlier.{aperta} Count the \`{\` and \`}\` of every function, every \`if\` and every loop.`,
  'errori.graffa.cosa': 'Every `{` opens a block and every `}` closes it: they must balance. With well-indented code (each block shifted a little to the right) the missing brace jumps out.',
  'errori.graffa.concetto': 'blocks and braces',
  'errori.parentesi.etichetta': 'missing bracket',
  'errori.parentesi.frase': 'a `)` is missing',
  'errori.parentesi.dove-2': `, column {apertaCol}`,
  'errori.parentesi.dove': `The \`(\` left open is on line {aperta}{apertaCol}: its \`)\` is missing before the point reported {allaRiga}.`,
  'errori.parentesi.dove-3': `Look at line {riga} and count the \`(\` and \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Look at the line shown and count the \`(\` and \`)\`.`,
  'errori.parentesi.cosa': 'Every `(` needs its `)`. In long conditions and in calls inside other calls it\'s easy to lose one: count them from left to right.',
  'errori.parentesi.concetto': 'brackets',
  'errori.espressione-attesa.etichetta': 'missing value',
  'errori.espressione-attesa.frase': 'the compiler expected a value and didn\'t find one',
  'errori.espressione-attesa.dove': `Look at {laRiga}{colonna}: something is missing there (a number, a variable) or there's an extra symbol. It also happens with unclosed quotes on the same line.`,
  'errori.espressione-attesa.cosa': 'After an `=`, an operator like `+` or a comma, the compiler expects a value. If it finds `;`, `)` or another symbol straight away, it stops.',
  'errori.espressione-attesa.concetto': 'expressions',
  'errori.ridefinizione.etichetta': 'declared twice',
  'errori.ridefinizione.breve-2': 'name',
  'errori.ridefinizione.breve': `{nome} declared twice`,
  'errori.ridefinizione.frase-2': 'a name',
  'errori.ridefinizione.frase': `{nome} is declared twice`,
  'errori.ridefinizione.dove': `The two declarations are on line {prima} and line {riga}.`,
  'errori.ridefinizione.dove-4': 'this name',
  'errori.ridefinizione.dove-2': `Look above line {riga} for another declaration of {nome}.`,
  'errori.ridefinizione.dove-2-senza-riga': `Look above the line shown for another declaration of {nome}.`,
  'errori.ridefinizione.cosa': 'In the same block a name is declared only once. If you just want to change the value, write `x = 2;` without the type in front.',
  'errori.ridefinizione.concetto': 'declaring variables',
  'errori.non-array.etichetta': '`[ ]` on something that isn\'t an array',
  'errori.non-array.frase': 'you use `[ ]` on something that isn\'t an array',
  'errori.non-array.dove': `Look at the square brackets {allaRiga}{colonna}.`,
  'errori.non-array.cosa': 'Square brackets are for taking an element of an array (or of a pointer). A plain variable, like an `int`, has no elements. Maybe you meant to use another variable, or to declare it as an array, for example `int v[10];`.',
  'errori.non-array.concetto': 'arrays',
  'errori.freccia-punto.etichetta': '`.` and `->` swapped',
  'errori.freccia-punto.frase': 'with a struct (not a pointer) you use `.`, not `->`',
  'errori.freccia-punto.frase-2': 'with a pointer to a struct you use `->`, not `.`',
  'errori.freccia-punto.frase-3': 'the struct field is accessed the wrong way',
  'errori.freccia-punto.dove': `Look at {laRiga}{colonna}: check how the variable before the dot or arrow is declared.`,
  'errori.freccia-punto.cosa': 'If you have the struct itself (`struct node n`), you get the field with a dot: `n.val`. If you have a pointer to the struct (`struct node *p`), you use the arrow: `p->val`, which means `(*p).val`.',
  'errori.freccia-punto.concetto': 'structs and pointers',
  'errori.membro-inesistente.etichetta': 'field that doesn\'t exist',
  'errori.membro-inesistente.frase-2': 'the struct',
  'errori.membro-inesistente.frase': `{p} has no field {m}`,
  'errori.membro-inesistente.frase-3': 'the struct has no such field',
  'errori.membro-inesistente.dove-2': ` with {m}`,
  'errori.membro-inesistente.dove': `Look at the definition of the struct{p} and compare the field names{m}.`,
  'errori.membro-inesistente.cosa': 'A struct\'s fields are the ones written in its definition, with those exact names. A different name, even by one letter, is a different field.',
  'errori.membro-inesistente.concetto': 'structs',
  'errori.header-non-trovato.etichetta': 'header not found',
  'errori.header-non-trovato.frase-2': 'included',
  'errori.header-non-trovato.frase': `I can't find the file {h}`,
  'errori.header-non-trovato.dove': `Look at the \`#include\` line {allaRiga}.`,
  'errori.header-non-trovato.dove-2': ` Maybe you meant {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` only exists with some old Windows compilers (Turbo C, Dev-C++): it\'s not part of standard C.',
  'errori.header-non-trovato.cosa': 'With `#include {sistema}` the compiler looks for the file among the system ones; with `#include {progetto}` it looks in the project folder first. If the name is wrong by even one letter, it can\'t find it and stops straight away.',
  'errori.header-non-trovato.concetto': 'libraries and #include',
  'errori.file-sorgente-mancante.etichetta': 'file not found',
  'errori.file-sorgente-mancante.frase-2': 'given',
  'errori.file-sorgente-mancante.frase': `the compiler can't find the file {h}`,
  'errori.file-sorgente-mancante.dove': 'Look at the compile command and the file names in the folder.',
  'errori.file-sorgente-mancante.cosa': 'The command names a file that isn\'t in the folder. Check the name (upper case, `.c` extension) and that the command runs from the right folder.',
  'errori.file-sorgente-mancante.concetto': 'compiling',
  'errori.non-assegnabile.etichetta': 'impossible assignment',
  'errori.non-assegnabile.frase': 'you can\'t copy an array (or a string) with `=`',
  'errori.non-assegnabile.frase-2': 'on the left of `=` there\'s something that isn\'t a variable',
  'errori.non-assegnabile.dove': `Look at what's on the left of \`=\` {allaRiga}.`,
  'errori.non-assegnabile.cosa': 'You don\'t copy an array with `=`. For a string use `strcpy(destination, "text");` from `{h}`, or give the value when you declare it: `char name[10] = "text";`.',
  'errori.non-assegnabile.cosa-2': 'On the left of `=` there must be a place to put the value: a variable, an array element, a field. Not a calculation like `a + 1`. If you meant to compare, you need `==`.',
  'errori.non-assegnabile.concetto': 'assignment',
  'errori.tipo-sconosciuto.etichetta': 'unknown type',
  'errori.tipo-sconosciuto.frase-2': 'this name',
  'errori.tipo-sconosciuto.frase': `{nome} isn't a type the compiler knows`,
  'errori.tipo-sconosciuto.dove-2': 'the type',
  'errori.tipo-sconosciuto.dove': `Look at {laRiga} and search above for where you define {nome}.`,
  'errori.tipo-sconosciuto.cosa': 'In C there\'s no `string` type (there is in C++ and other languages). A string in C is an array of `char`: `char s[50];` or `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Before using a type like `Node` you have to define it, for example with `typedef struct node Node;`, above the line that uses it. Check upper and lower case too.',
  'errori.tipo-sconosciuto.concetto': 'types and typedef',
  'errori.virgolette.etichetta': 'unclosed string',
  'errori.virgolette.frase': 'a string isn\'t closed: a `"` is missing',
  'errori.virgolette.dove': `Look at {laRiga}{colonna}: that's where the string starts. Find where it should end.`,
  'errori.virgolette.cosa': 'A string starts and ends with `"` on the same line. If the closing one is missing, the compiler treats the whole rest of the line as a string and then gets lost: that\'s why the errors after it often disappear by themselves.',
  'errori.virgolette.concetto': 'strings',
  'errori.if-vuoto.etichetta': '`;` after the condition',
  'errori.if-vuoto.frase': `there's a \`;\` right after \`{kw}\``,
  'errori.if-vuoto.frase-2': `there's a \`;\` right after the condition {if}`,
  'errori.if-vuoto.dove': `Look at line {riga}: right after \`{kw}\` there's a \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Look at the line shown: right after \`{kw}\` there's a \`;\`.`,
  'errori.if-vuoto.dove-3': `Look at the end of line {riga}: after the \`)\` of the condition there's a \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Look at the end of the line shown: after the \`)\` of the condition there's a \`;\`.`,
  'errori.if-vuoto.cosa': 'The `;` right after `else` is an empty statement: the `else` only controls that. The `{ }` block below always runs, even when the `if` condition is true.',
  'errori.if-vuoto.cosa-2': 'The `;` right after `do` is an empty statement: the loop only repeats that. The `{ }` block below isn\'t part of the loop.',
  'errori.if-vuoto.cosa-3': 'The `;` right after `if (...)` is an empty statement: the `if` only controls that. The `{ }` block below always runs, whatever the condition. With `while` it\'s worse: the loop may never end.',
  'errori.if-vuoto.concetto': 'if and loops',
  'errori.confronto-inutile.etichetta': 'statement that does nothing',
  'errori.confronto-inutile.frase': 'there\'s an `==` that does nothing: maybe you meant `=`',
  'errori.confronto-inutile.frase-2': 'this statement does nothing',
  'errori.confronto-inutile.dove': `Look at {laRiga}{colonna}.`,
  'errori.confronto-inutile.cosa': 'A comparison on its own (`x == 4;`) works out true or false and throws the result away. If you wanted to give the variable a value you need a single `=`: `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'A calculation that isn\'t stored in a variable, printed or used in a condition gets thrown away. Maybe an `=` or a function call is missing.',
  'errori.confronto-inutile.concetto': 'assignment and comparison',
  'errori.indirizzo-locale.etichetta': 'address of a local variable',
  'errori.indirizzo-locale.frase-2': 'a local variable',
  'errori.indirizzo-locale.frase': `you return the address of {nome}, which disappears when the function ends`,
  'errori.indirizzo-locale.dove': `Look at the \`return\` {allaRiga}.`,
  'errori.indirizzo-locale.cosa': 'Local variables only live while the function is running. Returning their address means giving the caller a memory location that no longer exists. If you need to return an array, create it with `malloc` (and then remember `free`), or have it passed in as a parameter.',
  'errori.indirizzo-locale.concetto': 'memory and functions',
  'errori.segni-diversi.etichetta': 'signed and unsigned numbers',
  'errori.segni-diversi.frase': 'you compare a signed number with an unsigned one',
  'errori.segni-diversi.dove': `Look at the comparison {allaRiga}.`,
  'errori.segni-diversi.cosa': 'Functions like `strlen` return an unsigned number (`size_t`). Comparing it with an `int` usually works, but if the `int` is negative the comparison goes wrong. It\'s a warning: you can declare the index as `size_t`, or store the length in an `int` before the loop.',
  'errori.segni-diversi.concetto': 'integer types',
  'errori.return-void.etichetta': '`return` and `void` clash',
  'errori.return-void.frase': '`return;` with no value in a function that must return one',
  'errori.return-void.frase-2': 'a `void` function can\'t return a value',
  'errori.return-void.dove': `Look at the \`return\` {allaRiga} and the first line of the function.`,
  'errori.return-void.cosa': '`void` means the function returns nothing: there you only write `return;` (or nothing). If the function has to give a result, put the right type in place of `void`, for example `int`, and every `return` must have a value.',
  'errori.return-void.concetto': 'return in functions',
  'errori.main-int.etichetta': '`main` not `int`',
  'errori.main-int.frase': '`main` must return `int`',
  'errori.main-int.dove-2': ` (line {riga})`,
  'errori.main-int.dove': `Look at the \`main\` line{riga}.`,
  'errori.main-int.cosa': 'The C standard wants `int main(void)`, and `return 0;` at the end to say “all good”. Only some old compilers accept `void main`.',
  'errori.main-int.concetto': 'the main function',
  'errori.fuori-array.etichetta': 'index outside the array',
  'errori.fuori-array.frase': `you use index {i}, but the array doesn't go that far`,
  'errori.fuori-array.frase-2': 'you use an index outside the array',
  'errori.fuori-array.dove-2': ` and the array declaration on line {riga}`,
  'errori.fuori-array.dove': `Look at {laRiga}{riga}.`,
  'errori.fuori-array.cosa': 'An array of N elements has indices from `0` to `N-1`: with `int v[5]` the last one is `v[4]`, and `v[5]` is already outside. It often happens with a loop `for (i = 0; i <= 5; i++)` instead of `i < 5`.',
  'errori.fuori-array.concetto': 'arrays and indices',
  'errori.argomenti-formato.etichetta': '`%` and values don\'t add up',
  'errori.argomenti-formato.frase': 'there are more `%` in the string than values',
  'errori.argomenti-formato.frase-2': 'you pass more values than there are `%` in the string',
  'errori.argomenti-formato.dove': `Look at the string {allaRiga} and count the \`%\` and the values after the comma.`,
  'errori.argomenti-formato.cosa': 'Each `%d`, `%f`, `%c`… in the `printf` (or `scanf`) string takes the next value, in order. The number of `%` and the number of values after the string must be the same.',
  'errori.argomenti-formato.concetto': 'printf and formats',
  'errori.divisione-zero.etichetta': 'division by zero',
  'errori.divisione-zero.frase': 'you divide by zero',
  'errori.divisione-zero.dove': `Look at the division {allaRiga}.`,
  'errori.divisione-zero.cosa': 'Dividing an integer by zero has no result: usually the program crashes. Before dividing, check the divisor isn\'t zero, for example with `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'division',
  'errori.troppi-inizializzatori.etichetta': 'too many values in the array',
  'errori.troppi-inizializzatori.frase': 'you put in more values than the array can hold',
  'errori.troppi-inizializzatori.dove': `Look at the declaration {allaRiga}: compare the size inside \`[ ]\` with how many values there are inside \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'If an array has room for 2 values and you write 3 inside the braces, the third is thrown away. Increase the size or remove some values. You can also leave the square brackets empty, `int v[] = {1, 2, 3};`, and the compiler counts for you.',
  'errori.troppi-inizializzatori.concetto': 'arrays',
  'errori.operandi.etichetta': 'operation not possible between these types',
  'errori.operandi.frase': `the operation can't be done between {a} and {b}`,
  'errori.operandi.frase-2': 'the operation can\'t be done between these two types',
  'errori.operandi.dove': `Look at the operator {allaRiga}{colonna} and the types on both sides.`,
  'errori.operandi.cosa': 'Operators like `&&`, `+` or `<` want specific types: `&&` works on `boolean`, `<` on numbers. Strings aren\'t compared with `<`: you use `compareTo`, and `equals` for equality.',
  'errori.operandi.cosa-2': 'Operators like `+`, `-` and `<` work on numbers (and some on pointers). You can\'t add or compare two structs directly: work on their fields, for example `a.x + b.x`. Strings in C aren\'t joined with `+`: you use `strcat`.',
  'errori.operandi.concetto': 'types and operators',
  'errori.carattere-strano.etichetta': 'strange character in the code',
  'errori.carattere-strano.frase': 'there\'s a strange character in the code',
  'errori.carattere-strano.dove': `Look at {laRiga}{colonna}.`,
  'errori.carattere-strano.cosa': 'It\'s often a character copied from a PDF or a web page: curly quotes `“ ”`, a curly apostrophe, a special space or a long dash. They look the same to the eye, but not to the compiler. Type the line again by hand.',
  'errori.carattere-strano.concetto': 'characters in the code',
  'errori.non-sicura.etichetta': 'Visual Studio and “unsafe” functions',
  'errori.non-sicura.frase-2': 'this function',
  'errori.non-sicura.frase': `Visual Studio doesn't want {nome}: it considers it unsafe`,
  'errori.non-sicura.dove': 'There\'s nothing wrong with your C: it\'s a Visual Studio rule.',
  'errori.non-sicura.cosa': 'Visual Studio flags `scanf`, `strcpy` and the like because, used badly, they can write past the end of an array. Standard C allows them and courses use them. To turn the warning off, write `#define _CRT_SECURE_NO_WARNINGS` as the very first line of the file, before the `#include`s. If your lecturer prefers `scanf_s`, do what your lecturer says.',
  'errori.non-sicura.concetto': 'different compilers',
  'errori.ricorsione-infinita.etichetta': 'endless recursion',
  'errori.ricorsione-infinita.frase': 'the function always calls itself: it never stops',
  'errori.ricorsione-infinita.dove': `Look at the function{p} {allaRiga}: find the base case, that is an \`if\` that returns a value without calling the function again.`,
  'errori.ricorsione-infinita.cosa': 'A recursive function must have a base case, and every call must get closer to it (for example with `n - 1`). Here every path leads to another call: the program will fill up the memory and stop.',
  'errori.ricorsione-infinita.concetto': 'recursion',
  'errori.sintassi.etichetta': 'code written in a way the compiler doesn\'t understand',
  'errori.sintassi.frase': 'the compiler doesn\'t understand how the code goes on here',
  'errori.sintassi.dove': `Look at {laRiga} and the one before: the real problem is often just above, for example an extra \`;\` after the first line of a function, an extra \`}\` or an unclosed bracket.`,
  'errori.sintassi.cosa': 'The compiler reads the code following strict rules, like the grammar of a language. Here it found something that can\'t go at that point. The original message says what it expected.',
  'errori.sintassi.concetto': 'syntax',
  'errori.java-tipi.etichetta': 'incompatible types (Java)',
  'errori.java-tipi.frase': `going from {dato} to {atteso} can lose data`,
  'errori.java-tipi.frase-2': `{dato} can't be used where {atteso} is needed`,
  'errori.java-tipi.frase-3': 'the value doesn\'t have the type that\'s needed',
  'errori.java-tipi.dove': `Look at {laRiga}{colonna}: compare the type of the variable with the type of the value.`,
  'errori.java-tipi.cosa': 'In Java every variable has a type and the compiler checks that values match. From `double` to `int` you lose the decimals, so you have to say so explicitly with a cast: `(int) x`. A `String` doesn\'t turn into a number by itself: you use `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'types in Java',
  'errori.java-import.etichetta': 'missing `import` (Java)',
  'errori.java-import.frase-2': 'this class',
  'errori.java-import.frase': `to use {nome} you need an \`import\``,
  'errori.java-import.dove': 'Look at the top of the file, above the class, where the `import` lines are.',
  'errori.java-import.cosa-2': 'This class',
  'errori.java-import.cosa-3': `, that is \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} lives in a package of the Java library: to use it you need the \`import\` at the top of the file{nome2}. Check upper and lower case too.`,
  'errori.java-import.concetto': 'import in Java',
  'errori.java-nome-file.etichetta': 'file name and class name differ',
  'errori.java-nome-file.frase-2': 'public',
  'errori.java-nome-file.frase-3': 'ClassName',
  'errori.java-nome-file.frase': `the {nome} class must be in the file {nome2}`,
  'errori.java-nome-file.dove': 'Look at the file name and the `public class` line.',
  'errori.java-nome-file.cosa': 'In Java a `public` class must be in a file with the same name, upper case included: `public class Main` goes in `Main.java`. Rename the file or the class.',
  'errori.java-nome-file.concetto': 'classes and files in Java',
  'errori.java-statico.etichetta': 'non-static used from static',
  'errori.java-statico.frase-2': 'this name',
  'errori.java-statico.frase': `{nome} isn't \`static\`, but you use it from a \`static\` method`,
  'errori.java-statico.dove-2': 'that name',
  'errori.java-statico.dove': `Look at {laRiga} and the declaration of {nome}.`,
  'errori.java-statico.cosa': '`main` is `static`: it belongs to the class, not to an object. From there you can only use `static` methods and variables, or first create an object with `new` and use that. In single-class exercises the method is often just missing `static`.',
  'errori.java-statico.concetto': 'static in Java',
  'errori.java-irraggiungibile.etichetta': 'statement never run',
  'errori.java-irraggiungibile.frase': 'this statement will never run',
  'errori.java-irraggiungibile.dove': `Look at {laRiga} and the line before.`,
  'errori.java-irraggiungibile.cosa': 'Before this line there\'s a `return`, a `break`, a `continue` or a loop that never ends: from there the program never gets here. Remove it or move it earlier.',
  'errori.java-irraggiungibile.concetto': 'program flow',
  'errori.java-indice.etichetta': 'index out of bounds (Java)',
  'errori.java-indice.frase': `you use index {i}, but the length is {l}`,
  'errori.java-indice.frase-2': 'you read a position the array (or the string) doesn\'t have',
  'errori.java-indice.cosa': 'Indices start at 0: with length 5 they go from 0 to 4. Check the loop condition: there\'s often `<=` where `<` is needed, or `length` is used as an index.',
  'errori.java-indice.concetto': 'arrays and indices',
  'errori.java-null.etichetta': 'null object (Java)',
  'errori.java-null.frase': 'you use an object that is `null`',
  'errori.java-null.cosa': 'The object was never created with `new`, or a method returned `null`. Recent versions of Java say in the message which variable was `null`.',
  'errori.java-null.concetto': 'objects and null',
  'errori.java-divisione-zero.etichetta': 'division by zero (Java)',
  'errori.java-divisione-zero.frase': 'you divide an integer by zero',
  'errori.java-divisione-zero.cosa': 'Dividing an integer by zero (with `%` too) has no result and Java stops. Before the division, check the divisor, for example with `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'division',
  'errori.java-input.etichetta': 'input that isn\'t a number (Java)',
  'errori.java-input.frase': `{v} isn't a number`,
  'errori.java-input.frase-2': 'the program expected a number and read something else',
  'errori.java-input.cosa': 'The program wanted a number and found something else: letters, spaces, an empty line, or a comma instead of a dot. Check what you type as input, or the test\'s `.in` file.',
  'errori.java-input.concetto': 'input',
  'errori.java-stack.etichetta': 'endless recursion (Java)',
  'errori.java-stack.frase': 'the method calls itself too many times',
  'errori.java-stack.cosa': 'Every recursive method needs a base case: a condition where it returns a value without calling itself. And every call must get closer to the base case.',
  'errori.java-stack.concetto': 'recursion',
  'errori.py-uguale.etichetta': '`=` instead of `==`',
  'errori.py-uguale.breve': '= instead of ==',
  'errori.py-uguale.frase': 'the condition has `=` instead of `==`',
  'errori.py-uguale.dove': `Look at the condition {allaRiga}.`,
  'errori.py-uguale.cosa': '`=` puts a value into a variable; `==` checks whether two values are equal. In a condition (`if`, `elif`, `while`) you need `==`: `if x == 5:`.',
  'errori.py-uguale.concetto': 'assignment and comparison',
  'errori.py-due-punti.etichetta': 'missing `:`',
  'errori.py-due-punti.frase': 'the `:` at the end of the line is missing',
  'errori.py-due-punti.dove': `Look at the end of line {riga}.`,
  'errori.py-due-punti.dove-senza-riga': `Look at the end of the line shown.`,
  'errori.py-due-punti.cosa': 'In Python `if`, `elif`, `else`, `for`, `while`, `def` and `class` end with `:`. The colon says “the block starts now”, and the block goes underneath, indented.',
  'errori.py-due-punti.concetto': 'blocks in Python',
  'errori.py-parentesi.etichetta': 'unclosed bracket',
  'errori.py-parentesi.frase': `there's a {c} that doesn't close anything`,
  'errori.py-parentesi.frase-2': `a {p} isn't closed`,
  'errori.py-parentesi.dove': `Look at {laRiga}: count the opening and closing brackets. If the line looks right, look at the one before.`,
  'errori.py-parentesi.cosa': 'Every `(`, `[` and `{` needs its own closing bracket of the same kind. If one is missing, Python keeps reading the following lines as if they were the same statement.',
  'errori.py-parentesi.concetto': 'brackets',
  'errori.py-stringa.etichetta': 'unclosed string',
  'errori.py-stringa.frase': 'a string isn\'t closed',
  'errori.py-stringa.dove': `Look at {laRiga}: the string starts there. Find where the closing quote is missing.`,
  'errori.py-stringa.cosa': 'A string starts and ends with the same kind of quote, `"` or `\'`, on the same line. If the text contains an apostrophe, use double quotes: `"it\'s"`.',
  'errori.py-stringa.concetto': 'strings',
  'errori.py-print.etichetta': '`print` without brackets',
  'errori.py-print.frase': '`print` needs brackets',
  'errori.py-print.dove': `Look at {laRiga}.`,
  'errori.py-print.cosa': 'In Python 3 `print` is a function: you write `print("hello")`. The form without brackets was Python 2, which you still find in old examples online.',
  'errori.py-print.concetto': 'functions',
  'errori.py-indentazione.etichetta': 'wrong indentation',
  'errori.py-indentazione.frase': 'the indentation after the colon is missing',
  'errori.py-indentazione.frase-2': 'there\'s too much indentation',
  'errori.py-indentazione.frase-3': 'the indentation doesn\'t match the lines above',
  'errori.py-indentazione.frase-4': 'you mix tabs and spaces in the indentation',
  'errori.py-indentazione.frase-5': 'the line\'s indentation is wrong',
  'errori.py-indentazione.dove-2': ` The \`{kw}\` is on line {l}.`,
  'errori.py-indentazione.dove': `Look at {laRiga} and the one above: compare the spaces at the start of the line.{kw}`,
  'errori.py-indentazione.cosa': 'In Python indentation (the spaces at the start of a line) is part of the code: it says which lines are inside an `if`, a `for` or a `def`. After the `:` the line below must be indented, and lines in the same block must be indented the same. Always use 4 spaces, without mixing them with tabs.',
  'errori.py-indentazione.concetto': 'blocks in Python',
  'errori.py-sintassi.etichetta': 'line Python can\'t read',
  'errori.py-sintassi.frase': 'maybe a comma is missing',
  'errori.py-sintassi.frase-2': 'Python can\'t read this line',
  'errori.py-sintassi.dove': `Look at {laRiga}: the \`^\` under the line shows where Python noticed the problem. The real mistake is often just before it, even on the line above (an unclosed bracket or quote).`,
  'errori.py-sintassi.cosa': 'Between two values in a list, a tuple or a function\'s arguments you need a comma: `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'Python reads the code following strict rules, like the grammar of a language. Here it found something that can\'t go at that point. The original message, after `SyntaxError:`, says what doesn\'t fit.',
  'errori.py-sintassi.concetto': 'syntax',
  'errori.py-nome.etichetta': 'name that doesn\'t exist',
  'errori.py-nome.breve-2': 'name',
  'errori.py-nome.breve': `{nome} not defined`,
  'errori.py-nome.frase-2': 'this name',
  'errori.py-nome.frase': `{nome} doesn't exist yet when Python gets to line {riga}`,
  'errori.py-nome.frase-senza-riga': `{nome} doesn't exist yet when Python gets to the line shown`,
  'errori.py-nome.dove': `Python suggests {s}: check whether that's what you meant. `,
  'errori.py-nome.dove-3': 'this name',
  'errori.py-nome.dove-2': `Find where you give {nome} a value: it must be above this line and spelled the same, upper case included. If it's a function, the \`def\` must come before the call.`,
  'errori.py-nome.cosa': 'In Python a name only exists after you give it a value (`x = ...`), after its `def` or after the `import`. Variables created inside a function don\'t exist outside it.',
  'errori.py-nome.cosa-2': ' Careful: in Python you write `True`, `False` and `None`, with a capital letter.',
  'errori.py-nome.cosa-3': ` If {nome} was meant to be text, the quotes are missing: {nome2}.`,
  'errori.py-nome.concetto': 'variables in Python',
  'errori.py-locale.etichetta': 'local variable with no value',
  'errori.py-locale.frase-2': 'a variable',
  'errori.py-locale.frase': `you use {nome} inside the function before giving it a value`,
  'errori.py-locale.dove-2': 'the variable',
  'errori.py-locale.dove': `Look at {laRiga} and find, in the same function, where you assign {nome}.`,
  'errori.py-locale.cosa': 'If you assign a value to a variable inside a function, Python treats it as local in the whole function, even in the lines before. So it no longer reads the variable with the same name outside. It\'s better to pass the value as a parameter and give back the result with `return`.',
  'errori.py-locale.concetto': 'functions and local variables',
  'errori.py-tipo-concatena.etichetta': 'text and number mixed up',
  'errori.py-tipo-concatena.frase': 'you mix text (`str`) and a number',
  'errori.py-tipo-concatena.frase-2': `the operation can't be done between {a} and {b}`,
  'errori.py-tipo-concatena.dove': `Look at {laRiga}: what type is each value next to the operator?`,
  'errori.py-tipo-concatena.cosa': 'For Python `"5"` (text) and `5` (number) are different things. To join text and a number, convert the number: `"Total: " + str(x)`, or use an f-string: `f"Total: {x}"`. If the value comes from `input()`, remember that `input()` always returns text: to do maths you need `int(input())` or `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'types in Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` used wrongly',
  'errori.py-tipo-indice.frase': 'the index must be an integer',
  'errori.py-tipo-indice.frase-2': `a \`{immut}\` value can't be changed`,
  'errori.py-tipo-indice.frase-3': 'you use `[ ]` on a `None` value',
  'errori.py-tipo-indice.frase-4': `you use \`[ ]\` on a value of type {p}, which has no elements`,
  'errori.py-tipo-indice.dove': `Look at the square brackets {allaRiga}.`,
  'errori.py-tipo-indice.cosa': 'With `v[i]` the `i` must be an `int`. If it comes from `input()` it\'s text: convert it with `int()`. If it comes from a division with `/` it\'s a `float`: use `//`.',
  'errori.py-tipo-indice.cosa-2': 'Strings and tuples in Python can\'t be changed: you create a new value, for example `s = "C" + s[1:]`. If you need to change the elements, use a list.',
  'errori.py-tipo-indice.cosa-3': 'Square brackets `[ ]` are for lists, strings, dictionaries and tuples. A number has no elements. If the type is `NoneType`, the variable is `None`: it\'s often the result of a function with no `return`.',
  'errori.py-tipo-indice.concetto': 'lists and indices',
  'errori.py-tipo-argomenti.etichetta': 'wrong number of arguments',
  'errori.py-tipo-argomenti.frase-2': 'the function',
  'errori.py-tipo-argomenti.frase': `{p} is called with the wrong number of arguments`,
  'errori.py-tipo-argomenti.dove': `Compare the call {allaRiga} with the function's \`def\` line.`,
  'errori.py-tipo-argomenti.cosa': 'A function must be called with as many arguments as there are parameters in its `def`. In a class\'s methods the first parameter is `self` and Python passes it by itself: if it says “takes 1 positional argument but 2 were given”, maybe `self` is missing from the `def`.',
  'errori.py-tipo-argomenti.concetto': 'functions and parameters',
  'errori.py-non-iterabile.etichetta': '`for` over a number',
  'errori.py-non-iterabile.frase': `you try to loop over a value of type {p}, which has no elements`,
  'errori.py-non-iterabile.dove': `Look at {laRiga}: what comes after \`in\`?`,
  'errori.py-non-iterabile.cosa': 'A `for` goes through the elements of a list, a string or a `range`. A number has no elements: to repeat n times you write `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'for loops',
  'errori.py-non-chiamabile.etichetta': '`( )` after something that isn\'t a function',
  'errori.py-non-chiamabile.frase': `you put \`( )\` after a value of type {p}, which isn't a function`,
  'errori.py-non-chiamabile.dove': `Look at {laRiga}: what's right before the round brackets?`,
  'errori.py-non-chiamabile.cosa': 'Round brackets after a name mean “call this function”. Often a variable has the same name as a function (for example `sum = 0` and then `sum(v)`), or an operator is missing: `2(x + 1)` instead of `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'functions',
  'errori.py-tipo.etichetta': 'wrong type',
  'errori.py-tipo.frase': 'an operation gets a value of the wrong type',
  'errori.py-tipo.dove': `Look at {laRiga}: what type are the values used? You can print them with \`print(type(x))\`.`,
  'errori.py-tipo.cosa': 'Every value in Python has a type (`int`, `str`, `list`…) and every operation only accepts certain types. The original message says which types it found.',
  'errori.py-tipo.concetto': 'types in Python',
  'errori.py-indice.etichetta': 'position that doesn\'t exist',
  'errori.py-indice.frase': 'you remove an element from an empty list',
  'errori.py-indice.frase-stringa': 'you\'re reading a position the string doesn\'t have',
  'errori.py-indice.frase-tupla': 'you\'re reading a position the tuple doesn\'t have',
  'errori.py-indice.frase-lista': 'you\'re reading a position the list doesn\'t have',
  'errori.py-indice.dove': `Look at {laRiga}: what's the index at that moment, and how many elements are there?`,
  'errori.py-indice.cosa': 'A list of n elements has positions from `0` to `n-1`: with 3 elements the last one is `v[2]`. It often happens with `range(len(v) + 1)` or with a loop that goes one step too far. An empty list has no positions at all: even `v[0]` is an error.',
  'errori.py-indice.concetto': 'lists and indices',
  'errori.py-chiave.etichetta': 'key that isn\'t there',
  'errori.py-chiave.frase': `the key {k} isn't in the dictionary`,
  'errori.py-chiave.frase-2': 'the key isn\'t in the dictionary',
  'errori.py-chiave.dove': `Look at {laRiga}: how is the key spelled, and how are the ones in the dictionary spelled?`,
  'errori.py-chiave.cosa': 'With `d[k]` the key must already exist. Check how it\'s written (upper case, spaces, number or text). To check first: `if k in d:`. To get a fallback value: `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'dictionaries',
  'errori.py-valore.etichetta': 'wrong value',
  'errori.py-valore.frase': `{v} can't be turned into a number`,
  'errori.py-valore.frase-2': 'there aren\'t as many variables on the left of `=` as there are values',
  'errori.py-valore.frase-3': 'a maths function gets a value it doesn\'t accept',
  'errori.py-valore.frase-4': 'the type is right but the value isn\'t',
  'errori.py-valore.dove': `Look at {laRiga}: what value actually gets there? You can print it with \`print(repr(x))\`.`,
  'errori.py-valore.cosa': '`int()` only turns text made of digits into a number. Spaces in the middle, letters, empty text or a number with a decimal comma (`"2,5"`) won\'t work. For decimals you need `float()` and a dot: `"2.5"`. If you read from `input()` or from a file, check what actually arrives.',
  'errori.py-valore.cosa-2': 'With `a, b = values` the number of variables on the left must equal the number of values on the right. Often `split()` returns more (or fewer) pieces than you expected.',
  'errori.py-valore.cosa-3': 'Functions like `math.sqrt` and `math.log` don\'t accept every number: no square root of a negative, no logarithm of zero. Check the value before the call.',
  'errori.py-valore.cosa-4': 'The value has the right type but doesn\'t work for that operation. The original message says which value was wrong.',
  'errori.py-valore.concetto': 'conversions and input',
  'errori.py-divisione-zero.etichetta': 'division by zero',
  'errori.py-divisione-zero.frase': 'you divide by zero',
  'errori.py-divisione-zero.dove': `Look at {laRiga}: which divisor is 0 at that moment? It's often the \`len()\` of an empty list or a counter left at 0.`,
  'errori.py-divisione-zero.cosa': 'Dividing by zero has no result, so Python stops. The same goes for `//` and `%`. Before the division, check the divisor: `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'division',
  'errori.py-attributo.etichetta': 'method or attribute that isn\'t there',
  'errori.py-attributo.frase': `the variable is \`None\`, so it has no {a}`,
  'errori.py-attributo.frase-2': `the module {mod} has no {a}`,
  'errori.py-attributo.frase-3': `a value of type {p} has no {a}`,
  'errori.py-attributo.frase-4': 'that value doesn\'t have this attribute',
  'errori.py-attributo.dove': `Look at {laRiga}: what's before the dot, and what type is it?`,
  'errori.py-attributo.cosa': 'A `None` value usually comes from a function with no `return`, or from methods like `v.sort()` that change the list and return `None` (so `v = v.sort()` loses the list).',
  'errori.py-attributo.cosa-2': 'Check how the name is spelled. If your file has the same name as the module (for example `random.py` or `math.py`), Python imports your file instead of the real module: rename it.',
  'errori.py-attributo.cosa-3': 'Each type has its own methods: lists have `append`, `pop`, `sort`; strings have `upper`, `split`, `strip`. Check the method name and the type of the variable.',
  'errori.py-attributo.concetto': 'methods and types',
  'errori.py-ricorsione.etichetta': 'endless recursion',
  'errori.py-ricorsione.frase': 'the function calls itself too many times',
  'errori.py-ricorsione.dove': `Look at the function{funzione} {allaRiga}: where's the base case, and does every call get closer to it?`,
  'errori.py-ricorsione.cosa': 'Every recursive function needs a base case: a condition where it returns a value without calling itself. And every call must get closer to the base case (for example `n - 1`, not `n + 1`). Python stops after about 1000 nested calls.',
  'errori.py-ricorsione.concetto': 'recursion',
  'errori.py-modulo.etichetta': 'module that isn\'t there',
  'errori.py-modulo.frase': `there's no {nome} in the module {m}`,
  'errori.py-modulo.frase-2': `the module {m} isn't there`,
  'errori.py-modulo.frase-3': 'a module won\'t import',
  'errori.py-modulo.dove': `Look at the \`import\` line {allaRiga}.`,
  'errori.py-modulo.cosa': 'Either the name is misspelled, or the module isn\'t installed for this Python. External modules (for example `numpy`) are installed with `python3 -m pip install name` (on Windows `py -m pip install name`). If the module is one of your files, it must be in the same folder and be called `name.py`.',
  'errori.py-modulo.concetto': 'modules and import',
  'errori.py-file.etichetta': 'file not found',
  'errori.py-file.frase': `I can't find the file {p}`,
  'errori.py-file.dove': `Look at the \`open\` {allaRiga}.`,
  'errori.py-file.cosa': 'Python looks for the file starting from the folder you run the program from, not the script\'s folder. Check the name, the extension (Windows sometimes hides it) and the folder.',
  'errori.py-file.concetto': 'files',
  'errori.py-input-finito.etichetta': 'input ran out',
  'errori.py-input-finito.frase': 'the program asks for input that never comes',
  'errori.py-input-finito.dove': `Look at the \`input()\` {allaRiga}.`,
  'errori.py-input-finito.cosa': '`input()` was waiting for a line, but the input had already ended. In tests with `.in` files, check the file has as many lines as there are `input()` calls.',
  'errori.py-input-finito.concetto': 'input',
  'errori.esec-memoria.etichetta': 'memory that isn\'t its own (segmentation fault)',
  'errori.esec-memoria.breve': 'memory not its own',
  'errori.esec-memoria.frase': 'the program used memory that isn\'t its own',
  'errori.esec-memoria.cosa': 'Here the pointer was `NULL`. ',
  'errori.esec-memoria.cosa-2': 'It\'s often a `NULL` pointer (`p->next` with `p` being `NULL`), an index outside the array or endless recursion. The system stops the program to protect the rest of the memory.',
  'errori.esec-memoria.cosa-3': ` On Windows this error has the code {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'pointers and memory',
  'errori.esec-divisione-zero.etichetta': 'integer division by zero',
  'errori.esec-divisione-zero.frase': 'the program divided an integer by zero',
  'errori.esec-divisione-zero.cosa': 'An integer divided by zero (with `%` too) has no result and the system stops the program. The name “floating point exception” is misleading: it happens precisely with integers. Check the divisors, for example a counter that is still 0.',
  'errori.esec-divisione-zero.concetto': 'division',
  'errori.esec-stack.etichetta': 'call stack full (stack overflow)',
  'errori.esec-stack.frase': 'the call stack is full: maybe endless recursion',
  'errori.esec-stack.cosa': 'Every function call takes up a bit of memory on the stack. A recursive function with no base case, or with a base case that\'s never reached, fills it up. A huge local array can be enough too: in that case use `malloc`.',
  'errori.esec-stack.concetto': 'recursion',
  'errori.esec-fuori-array.etichetta': 'writing outside an array',
  'errori.esec-fuori-array.frase': 'the program read or wrote outside an array',
  'errori.esec-fuori-array.frase-letto': 'the program read outside an array',
  'errori.esec-fuori-array.frase-scritto': 'the program wrote outside an array',
  'errori.esec-fuori-array.cosa': 'An array of N elements goes from `0` to `N-1`. Check the loop conditions (`<` not `<=`), strings with no room for the final `\'\\0\'` and `malloc` calls with the right size (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'arrays and indices',
  'errori.esec-heap.etichetta': 'malloc and free used wrongly',
  'errori.esec-heap.frase': 'the memory taken with `malloc` was used wrongly',
  'errori.esec-heap.cosa': 'It happens when you free the same memory twice (`free` twice), when you use a pointer after `free`, or when you write past the end of a block taken with `malloc`. After `free(p);` it helps to write `p = NULL;`.',
  'errori.esec-heap.concetto': 'dynamic memory',
  'errori.esec-memoria-persa.etichetta': 'memory never freed',
  'errori.esec-memoria-persa.frase': 'the program takes memory with `malloc` and doesn\'t free it',
  'errori.esec-memoria-persa.cosa': 'Every `malloc` (or `calloc`) must have its `free` when the memory is no longer needed. In lists every node must be freed, one at a time, before you lose the pointer.',
  'errori.esec-memoria-persa.concetto': 'dynamic memory',
  'errori.esec-non-inizializzata.etichetta': 'value never initialised',
  'errori.esec-non-inizializzata.frase': 'the program uses a value that was never initialised',
  'errori.esec-non-inizializzata.cosa': 'A local variable (or memory taken with `malloc`) holds random values until you give it one. Initialise it before reading it.',
  'errori.esec-non-inizializzata.concetto': 'initialising variables',
  'errori.esec-asserzione.etichetta': 'assert failed',
  'errori.esec-asserzione.frase': `an \`assert\` failed: {cond} was false`,
  'errori.esec-asserzione.frase-2': 'an `assert` failed',
  'errori.esec-asserzione.cosa': '`assert(condition)` stops the program if the condition is false. Whoever wrote it (you or your lecturer) is saying: “this must always be true here”. The real problem is earlier: find where the value went wrong.',
  'errori.esec-asserzione.concetto': 'assert and checks',
  'errori.esec-abort.etichetta': 'program aborted (abort)',
  'errori.esec-abort.frase': 'the program stopped itself (abort)',
  'errori.esec-abort.cosa': 'It\'s usually the library asking for it when it finds a serious problem: a failed `assert`, a wrong `free`, corrupted memory. Look at the lines printed just before: they often say why.',
  'errori.esec-abort.concetto': 'dynamic memory',
  'errori.esec-overflow.etichetta': 'integer too large',
  'errori.esec-overflow.frase': 'an integer got too large',
  'errori.esec-overflow.cosa': 'An `int` goes up to 2147483647. Beyond that, the result is wrong. It happens with factorials and powers: use `long long` (with `%lld` in `printf`), or check your sums.',
  'errori.esec-overflow.concetto': 'integer types',
  'errori.esec-tempo.etichetta': 'timed out',
  'errori.esec-tempo.frase': 'the program didn\'t finish in time',
  'errori.esec-tempo.cosa': 'Maybe there\'s a loop that never ends: the condition never becomes false, or the loop variable doesn\'t change. Or the program is waiting for input (`scanf`, `input()`) that never comes.',
  'errori.esec-tempo.concetto': 'loops',
  'errori.esec-segnale.etichetta': 'program stopped by the system',
  'errori.esec-segnale.frase': `the program was stopped by the system{segnale}`,
  'errori.esec-segnale.cosa': 'The system stopped the program while it was running. Lode can\'t say more from this signal: look at the last lines printed and the lines changed recently.',
  'errori.esec-segnale.concetto': 'running programs',
  // ---- outside the dictionary: places, counts, steps, fixes, card ----
  'errori.tempo-scaduto': 'Timed out',
  'errori.segnale': 'Signal {sig}',
  'errori.codice-uscita': `Exit code {codice}`,
  'errori.codice-uscita-windows': `Exit code {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'one more error', other: '{n} more errors' },
  'errori.avvisi': { one: '1 warning', other: '{n} warnings' },
  'errori.conto': 'and {cosa}',
  'errori.conto-errori-e-avvisi': 'and {errori} and {avvisi}',
  'errori.un-nome': 'a name',
  'errori.alla-riga': 'on line {n}',
  'errori.nel-punto-indicato': 'at the point shown',
  'errori.la-riga': 'line {n}',
  'errori.il-punto-indicato': 'the point shown',
  'errori.colonna': ', column {n}',
  'errori.del-if': "of the `if`",
  'errori.del-while': 'of the `while`',
  'errori.del-for': 'of the `for`',
  'errori.sconosciuto': 'unknown error',
  'errori.errore': 'error',
  'errori.nella-funzione': ', in the function {funzione}',
  'errori.di-file': ' of {file}',
  'errori.fermato-alla-riga': 'The program stopped on line {riga}{file}{funzione}.',
  'errori.poi-guarda-cambiate': ` Then look at the lines changed since the last successful test: {righe}.`,
  'errori.guarda-prima-cambiate': `First look at the lines changed since the last successful test: {righe}.`,
  'errori.sistema-senza-riga': 'The system doesn\'t give the line. Add a few `printf`s to see how far the program gets; on Mac and Linux you can also compile with `-g -fsanitize=address` to get the file and line.',
  'errori.messaggio-senza-riga': 'The message doesn\'t give the line: look at the last lines the program printed.',
  'errori.cambiate-e-altre': { one: '{righe} and {n} more', other: '{righe} and {n} more' },
  'errori.correggi-punto': `Add \`;\` at the end of the statement: on line {riga} or the one before.`,
  'errori.correggi-punto-senza-riga': 'Add `;` at the end of the statement.',
  'errori.correggi-punto-fine': `At the end of line {riga} add \`;\`:`,
  'errori.correggi-punto-dentro': `On line {riga}, at the point shown, add \`;\`:`,
  'errori.correggi-include-in-cima': 'At the top of the file, with the other `#include`s, add:',
  'errori.correggi-include-dopo': 'After line {riga} add:',
  'errori.correggi-include-primo': 'At the top of the file add:',
  'errori.correggi-uguale': 'In the condition replace `=` with `==`.',
  'errori.correggi-uguale-riga': `On line {riga} replace \`=\` with \`==\`:`,
  'errori.correggi-return': `Before the \`}\` that closes {nome}, add a \`return\` with the right value for the cases left out. Which value is up to you: it depends on what the function has to work out.`,
  'errori.correggi-return-senza-nome': `Before the \`}\` that closes the function, add a \`return\` with the right value for the cases left out. Which value is up to you: it depends on what the function has to work out.`,
  'errori.generico.dove-linker': 'The linker doesn\'t give a line: search the project for the name quoted in the message, and check that all the `.c` files are in the compile command.',
  'errori.generico.dove-senza-riga': 'The message doesn\'t give a line: read the original text below.',
  'errori.generico.dove-python': '{L} stopped {allaRiga}{file}. If everything looks right there, look at the line before.',
  'errori.generico.dove': 'Look at {laRiga}{colonna}{file}. If everything looks right there, look at the line before too: the compiler often only notices a problem afterwards.',
  'errori.generico.eccezione-leggendo': '{eccezione} is the kind of error {L} ran into while reading the program. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} is the kind of error {L} ran into while running the program. ',
  'errori.generico.cosa': 'Lode doesn\'t have an explanation for this message yet. The original text is below: read the words in quotes, they\'re usually the name or the type causing the trouble.',
  'errori.catena': ' You got there like this: {passi}.',
  'errori.catena-passo': 'line {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, line {riga}',
  'errori.luogo-riga': 'line {riga}',
  'errori.con-eccezione': '{eccezione}: {frase}',
  'errori.intestazione': '**{luogo}**: {frase}',
  'errori.intestazione-eccezione': '**{luogo}** · {frase}',
  'errori.per-diario': '{dove}“{breve}”',
  'errori.non-lo-conosco': 'I don\'t know this error yet',
  'errori.parola-avviso': 'warning',
  'errori.e-un-avviso': `It's a warning: the program compiles anyway, but as it is it probably doesn't do what you want. {cosa}`,
  'errori.passo-dove': 'Where to look',
  'errori.passo-cosa': 'What it means',
  'errori.passo-correzione': 'Show me the fix',
  'errori.file-cambiato': 'The file has changed since then: the line numbers might not match.',
  'errori.tipo-errore': 'Error',
  'errori.tipo-avviso': 'Warning',
  'errori.tipo-linker': 'Linker error',
  'errori.tipo-esecuzione': 'It stopped',
  'errori.segnaposto-valore': '‹value›',
  'errori.correzione-vista': 'fix seen',
  'errori.messaggio-originale': 'Original message',
};
