// Sample data (esempio() in js/dati.js) and the words printed by the «Cosa stampa?» programs. Same shape as it/esempio.js.
export default {
  'esempio.nome': 'Emily',
  'esempio.corso': 'Computer Engineering',
  'esempio.esami': ['Engineering Mathematics 1', 'Programming Fundamentals', 'Linear Algebra', 'Mechanics', 'Professional Skills', 'Object-Oriented Programming', 'Engineering Mathematics 2', 'Databases', 'Electromagnetism'],
  'esempio.aule': ['LT1', 'Lab 2', 'Main Hall'],
  'esempio.carte': [
    ['What is the gradient of f(x, y)?', 'The vector of partial derivatives (∂f/∂x, ∂f/∂y): it points in the direction of steepest ascent.'],
    ["State Schwarz's theorem", 'If the mixed second partial derivatives are continuous in a neighbourhood, then f_xy = f_yx.'],
    ['Condition for a stationary point', 'The gradient vanishes: ∇f(x₀) = 0.'],
    ['How do you classify a stationary point?', 'With the Hessian matrix: positive definite → minimum, negative definite → maximum, indefinite → saddle point.'],
    ['What is a double integral over a normal domain?', 'An iterated integral: first over the ‘inner’ variable, with limits that depend on the other one, then over the other one.'],
    ["Green's theorem: statement", 'The line integral of P dx + Q dy over ∂D equals the double integral over D of (∂Q/∂x − ∂P/∂y).'],
    ['Exact differential form: definition', 'ω is exact if there is a function U (a potential) with dU = ω.'],
    ['Geometric series: when does it converge?', 'For |q| < 1, with sum 1/(1 − q).'],
    ['What is a primary key?', 'A minimal set of attributes that uniquely identifies each tuple of a relation.'],
    ['Difference between LEFT JOIN and INNER JOIN', 'A LEFT JOIN keeps every row of the left table, even without a match (with NULLs); an INNER JOIN keeps only the pairs that match.'],
    ['What does third normal form guarantee?', 'That every non-key attribute depends on the key, the whole key and nothing but the key (no transitive dependencies).'],
  ],
  'esempio.domande': ["Why does Schwarz's theorem need the mixed derivatives to be continuous?"],
  'esempio.stelle': ["Green's theorem is in every exam, with the proof", 'Classifying critical points with the Hessian: a guaranteed exercise'],
  'esempio.stelle-basi': ['Normalisation up to BCNF: always in the written exam'],
  'esempio.definizioni': [
    ['Gradient', 'The vector of the partial derivatives of f: it points in the direction of steepest ascent.'],
    ['Stationary point', 'A point where the gradient of the function vanishes.'],
    ['Hessian matrix', 'The square matrix of the second partial derivatives of a function.'],
    ['Saddle point', 'A stationary point that is neither a local maximum nor a local minimum: the Hessian is indefinite.'],
    ["Green's theorem", 'It links the line integral around the boundary of a domain to the double integral over the domain.'],
    ['Exact differential form', 'A form that has a potential, that is, it is the differential of a function.'],
  ],
  'esempio.definizioni-basi': [
    ['Primary key', 'A minimal set of attributes that uniquely identifies each tuple.'],
    ['Foreign key', 'An attribute that refers to the primary key of another relation.'],
    ['Functional dependency', 'A constraint where the value of one set of attributes determines the value of another.'],
    ['Boyce-Codd normal form', 'Every non-trivial functional dependency has a superkey on its left-hand side.'],
  ],
  'esempio.switch-parole': ['one', 'two', 'three', 'four'],
  'esempio.switch-altro': 'other',
  'esempio.si': 'yes',
  'esempio.no': 'no',
  'esempio.hai-scritto': 'You wrote `{s}`',
};
