// “New things”, the fixed dictionary of the standard library (English): for each entry, the oral exam question
// and the answer. Function names and the rules that find them in the code stay in js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': 'What\'s in the memory malloc has just returned?',
  'glossario.malloc.risposta': 'Garbage values: malloc doesn\'t zero it. If there\'s no memory it returns NULL, so you check before using it.',
  'glossario.calloc.domanda': 'What\'s the difference between calloc(n, size) and malloc(n * size)?',
  'glossario.calloc.risposta': 'calloc sets every byte to zero, malloc leaves garbage values. If there\'s no memory, both return NULL.',
  'glossario.realloc.domanda': 'What does realloc do if it fails?',
  'glossario.realloc.risposta': 'It returns NULL and the old block stays valid: you have to free it separately. That\'s why you write p2 = realloc(p, n) and not p = realloc(p, n).',
  'glossario.free.domanda': 'What happens if you use a pointer after free?',
  'glossario.free.risposta': 'It\'s undefined behaviour: that memory isn\'t yours any more. Freeing it twice is too. free(NULL), on the other hand, does nothing.',
  'glossario.strtok.domanda': 'Why can\'t you use strtok on a string literal?',
  'glossario.strtok.risposta': 'Because it writes into the string: it replaces each separator with \'\\0\'. From the second call on you pass NULL, and strtok carries on from the point it remembers.',
  'glossario.strcpy.domanda': 'What does strcpy check about the size of the destination?',
  'glossario.strcpy.risposta': 'Nothing: it copies up to and including the \'\\0\'. If the destination is too small it writes past the end of the array, which is undefined behaviour.',
  'glossario.strncpy.domanda': 'Does strncpy(d, s, n) always add the final \'\\0\'?',
  'glossario.strncpy.risposta': 'No: if s has n characters or more, there\'s no \'\\0\' in d. If s is shorter, it fills the rest with zeros.',
  'glossario.strcmp.domanda': 'What does strcmp return if the two strings are equal?',
  'glossario.strcmp.risposta': '0. A negative number if the first comes before, positive if it comes after: that\'s why if (strcmp(a, b)) means “they\'re different”.',
  'glossario.strlen.domanda': 'Does strlen count the final \'\\0\' too?',
  'glossario.strlen.risposta': 'No: it counts the characters before the \'\\0\'. To copy the string you need strlen(s) + 1 bytes.',
  'glossario.strcat.domanda': 'What do you need for strcat(d, s) to work?',
  'glossario.strcat.risposta': 'd must already hold a string ending in \'\\0\' and have room for both, plus the \'\\0\'. strcat doesn\'t check the space.',
  'glossario.memcpy.domanda': 'Can you use memcpy if source and destination overlap?',
  'glossario.memcpy.risposta': 'No, it\'s undefined behaviour. In that case you use memmove.',
  'glossario.memset.domanda': 'Does memset(v, 1, n * sizeof(int)) set the ints in v to 1?',
  'glossario.memset.risposta': 'No: memset writes the same value into every byte, so each 32-bit int becomes 16843009. For zeroing it\'s fine: memset(v, 0, …).',
  'glossario.sizeof.domanda': 'What is sizeof(v) if v is a parameter int v[]?',
  'glossario.sizeof.risposta': 'The size of a pointer, not of the array: as a parameter, int v[] is int *v. That\'s why you pass the length separately.',
  'glossario.fgets.domanda': 'What does fgets leave at the end of the line it reads?',
  'glossario.fgets.risposta': 'The newline, if it fitted, and then the \'\\0\': fgets(s, n, f) reads at most n - 1 characters. At end of file it returns NULL.',
  'glossario.scanf.domanda': 'What does scanf return?',
  'glossario.scanf.risposta': 'How many values it read and assigned, or EOF if the input ends first. If you don\'t check it, a letter instead of a number slips through silently.',
  'glossario.sscanf.domanda': 'What\'s the difference between scanf and sscanf?',
  'glossario.sscanf.risposta': 'sscanf reads from a string instead of from the input. It\'s often used after fgets: first read the whole line, then split it up.',
  'glossario.fopen.domanda': 'What does fopen return if the file won\'t open?',
  'glossario.fopen.risposta': 'NULL: check it before reading or writing. Careful: with "w" an existing file is emptied straight away.',
  'glossario.fclose.domanda': 'What does fclose do on a file you\'ve written to?',
  'glossario.fclose.risposta': 'It writes whatever is still in the buffer to the file and frees the FILE. After fclose you don\'t use that pointer any more.',
  'glossario.fprintf.domanda': 'What\'s the difference between fprintf(stderr, ...) and printf(...)?',
  'glossario.fprintf.risposta': 'printf writes to stdout, fprintf to the stream you pass it. stderr is usually unbuffered and doesn\'t end up in the file if you redirect the output with >.',
  'glossario.atoi.domanda': 'What does atoi("hello") return?',
  'glossario.atoi.risposta': '0, with no sign of an error: you can\'t tell "0" from bad text. To check, you use strtol.',
  'glossario.strtol.domanda': 'What\'s the second argument of strtol for?',
  'glossario.strtol.risposta': 'It\'s a char ** where strtol puts the point where it stopped: if that\'s the start, it read no digits. The third argument is the base.',
  'glossario.qsort.domanda': 'What must qsort\'s comparison function return?',
  'glossario.qsort.risposta': 'A negative int, zero or a positive int if the first element goes before, is equal or goes after. It gets two const void * to convert to the right type.',
  'glossario.exit.domanda': 'What\'s the difference between exit(1) and return 1 inside main?',
  'glossario.exit.risposta': 'Inside main they do the same thing. But exit ends the program from any function, after flushing and closing the open files.',
  'glossario.assert.domanda': 'What does assert(x) do if x is false?',
  'glossario.assert.risposta': 'It writes the condition, the file and the line to stderr, then stops the program with abort. With -DNDEBUG the asserts disappear: don\'t put code you need inside them.',
  'glossario.static-locale.domanda': 'What changes if a variable inside a function is static?',
  'glossario.static-locale.risposta': 'It\'s initialised only once and keeps its value from one call to the next. If you don\'t initialise it, it starts at 0.',
  'glossario.computeifabsent.domanda': 'What does map.computeIfAbsent(k, x -> new ArrayList<>()) do?',
  'glossario.computeifabsent.risposta': 'If k isn\'t there, it creates the list, puts it in the map and returns it. If it\'s already there, it returns that one. So afterwards you can call .add without checks.',
  'glossario.getordefault.domanda': 'What does map.getOrDefault(k, 0) return if k isn\'t there?',
  'glossario.getordefault.risposta': '0, and the map doesn\'t change: k isn\'t added.',
  'glossario.putifabsent.domanda': 'What does map.putIfAbsent(k, v) return?',
  'glossario.putifabsent.risposta': 'The value that was already there, and then the map doesn\'t change. If k wasn\'t there, it puts v and returns null.',
  'glossario.list-remove.domanda': 'On a List<Integer> holding [5, 7, 9], what does list.remove(1) do?',
  'glossario.list-remove.risposta': 'It removes the element at position 1, that is 7: with an int, remove(int index) is chosen. To remove the value 1 you need list.remove(Integer.valueOf(1)).',
  'glossario.equals.domanda': 'What\'s the difference between == and equals on two Strings?',
  'glossario.equals.risposta': '== checks whether they\'re the same object, equals whether they have the same characters. Two equal strings can be two different objects.',
  'glossario.hashcode.domanda': 'If you override equals, what do you have to do with hashCode?',
  'glossario.hashcode.risposta': 'Override it too: objects equal under equals must have the same hashCode. Otherwise HashMap and HashSet can\'t find them.',
  'glossario.collections-sort.domanda': 'Is Collections.sort stable?',
  'glossario.collections-sort.risposta': 'Yes: elements that compare equal stay in their previous order. It sorts the list in place and returns nothing.',
  'glossario.comparator-comparing.domanda': 'What does Comparator.comparing(Student::getGrade).reversed() do?',
  'glossario.comparator-comparing.risposta': 'It compares students by grade, reversed: from highest to lowest. With thenComparing you add a second criterion for equal grades.',
  'glossario.optional.domanda': 'Why don\'t you call get() on an Optional without checking?',
  'glossario.optional.risposta': 'If it\'s empty, get() throws NoSuchElementException. You use orElse, orElseGet or isPresent.',
  'glossario.stream.domanda': 'What happens if you only call map and filter on a stream, without collect?',
  'glossario.stream.risposta': 'Nothing: map and filter are lazy. The work only starts with a terminal operation like collect, forEach or count. And a stream can only be used once.',
  'glossario.stringbuilder.domanda': 'Why do you use StringBuilder in a loop instead of s = s + x?',
  'glossario.stringbuilder.risposta': 'A String never changes: every + creates a new one and copies everything again. StringBuilder appends to the same object, and toString() gives you the result.',
  'glossario.integer-parseint.domanda': 'What happens with Integer.parseInt("12a")?',
  'glossario.integer-parseint.risposta': 'It throws NumberFormatException. " 12" with the space throws it too: use trim() first.',
  'glossario.scanner-nextint.domanda': 'Why does a nextLine() straight after nextInt() return an empty line?',
  'glossario.scanner-nextint.risposta': 'nextInt reads the number but leaves the newline behind. nextLine reads up to that newline and returns "". You add an extra nextLine() to throw it away.',
  'glossario.try-with-resources.domanda': 'What does try (Scanner in = new Scanner(f)) { ... } do?',
  'glossario.try-with-resources.risposta': 'It closes the resource by itself at the end of the block, even if an exception is thrown. It works with classes that implement AutoCloseable.',
  'glossario.instanceof.domanda': 'What does x instanceof String return if x is null?',
  'glossario.instanceof.risposta': 'false, with no exception. Since Java 16 you can write x instanceof String s and use s straight away.',
  'glossario.arrays-aslist.domanda': 'What happens if you call add on the list from Arrays.asList?',
  'glossario.arrays-aslist.risposta': 'It throws UnsupportedOperationException: the list has a fixed size and is backed by the array. set works, though, and changes the array too.',
  'glossario.iterator-remove.domanda': 'How do you remove elements from a list while you go through it?',
  'glossario.iterator-remove.risposta': 'With an Iterator and it.remove(), or with removeIf. With list.remove inside a for-each you usually get ConcurrentModificationException.',
  'glossario.substring.domanda': 'What does "lecture".substring(1, 4) return?',
  'glossario.substring.risposta': '"ect": the characters from position 1 to 3. The second index is excluded, and the original string doesn\'t change.',
  'glossario.compareto.domanda': 'What does a.compareTo(b) return?',
  'glossario.compareto.risposta': 'A negative number if a comes before b, zero if they\'re equal, positive if it comes after. Not necessarily -1 or 1: the sign is what counts.',
  'glossario.list-comprehension.domanda': 'What does [x * 2 for x in v if x > 0] build?',
  'glossario.list-comprehension.risposta': 'A new list with double the value of only the positive elements of v. It\'s a for with an if and append written in one line; v doesn\'t change.',
  'glossario.list-comprehension-annidata.domanda': 'In [x for riga in m for x in riga], which for is the outer one?',
  'glossario.list-comprehension-annidata.risposta': 'The first: the fors read in the order you\'d nest them one inside the other. The result is m flattened into a single list.',
  'glossario.lambda.domanda': 'What can a lambda contain in Python?',
  'glossario.lambda.risposta': 'A single expression, which becomes the return value. No statements like return, for or a normal assignment.',
  'glossario.sorted-con-key.domanda': 'What does sorted(v, key=len) do?',
  'glossario.sorted-con-key.risposta': 'It returns a new list sorted by length; v stays as it is. Items of the same length keep their original order: the sort is stable.',
  'glossario.enumerate.domanda': 'What does enumerate(v) give you?',
  'glossario.enumerate.risposta': 'The pairs (index, element), with the index starting at 0. With enumerate(v, 1) it starts at 1.',
  'glossario.zip.domanda': 'What does zip do if the lists have different lengths?',
  'glossario.zip.risposta': 'It stops at the shortest: the extra elements are lost with no error. Since Python 3.10, strict=True raises an error.',
  'glossario.dict-get.domanda': 'What\'s the difference between d[k] and d.get(k)?',
  'glossario.dict-get.risposta': 'd[k] raises KeyError if k is missing, d.get(k) returns None, or the second argument if you pass one. get doesn\'t add k.',
  'glossario.setdefault.domanda': 'What does d.setdefault(k, []) do?',
  'glossario.setdefault.risposta': 'If k is missing, it adds it with [] and returns that list. If it\'s already there, it returns the value it has. The [] is created on every call anyway.',
  'glossario.defaultdict.domanda': 'What happens if you read a missing key in a defaultdict(list)?',
  'glossario.defaultdict.risposta': 'It creates it with an empty list and returns it, with no KeyError. Careful: even just reading d[k] adds k.',
  'glossario.counter.domanda': 'What does a Counter return for a key it has never seen?',
  'glossario.counter.risposta': '0, with no KeyError and without adding it. most_common(n) gives you the n most frequent.',
  'glossario.with-open.domanda': 'Why do you write with open(nome) as f?',
  'glossario.with-open.risposta': 'The file closes by itself when you leave the block, even if an exception is raised. Without with you have to call f.close().',
  'glossario.yield.domanda': 'What does a function that contains yield return?',
  'glossario.yield.risposta': 'A generator. The body only starts when you ask for the first value, with next or a for, and it pauses at every yield. You can go through it only once.',
  'glossario.args-e-kwargs.domanda': 'In def f(*args, **kwargs), what are args and kwargs?',
  'glossario.args-e-kwargs.risposta': 'args is a tuple with the extra positional arguments, kwargs a dictionary with the ones passed by name.',
  'glossario.rovescia.domanda': 'What does v[::-1] give you?',
  'glossario.rovescia.risposta': 'A reversed copy of v: it works with lists, strings and tuples. v doesn\'t change.',
  'glossario.is-e-uguale.domanda': 'What\'s the difference between is and ==?',
  'glossario.is-e-uguale.risposta': '== compares values, is checks whether they\'re the same object. Use is with None; with numbers and strings use ==.',
  'glossario.default-mutabile.domanda': 'Why is def f(x, v=[]) a trap?',
  'glossario.default-mutabile.risposta': 'The default list is created only once, when f is defined: every call sees the changes made by the earlier ones. You write v=None and create the list inside.',
  'glossario.f-string.domanda': 'What does print(f"{x:.2f}") print if x is 3.14159?',
  'glossario.f-string.risposta': '3.14: after the colon comes the format, and .2f means two digits after the decimal point, rounded.',
  'glossario.extend.domanda': 'What\'s the difference between v.append(w) and v.extend(w)?',
  'glossario.extend.risposta': 'append adds w as a single element, even if it\'s a list. extend adds the elements of w one by one. Both change v and return None.',
  'glossario.split.domanda': 'What\'s the difference between s.split() and s.split(" ")?',
  'glossario.split.risposta': 'With no arguments it splits on any whitespace, even several spaces, and skips empty parts. With " " every space splits: two spaces in a row give an empty string.',
  'glossario.da-riga': 'From: {file}, line {riga}',
};
