// “I want to…” (js/guida.js and the guide in the bar, js/lode.js): the step-by-step guide cards and the recipes written by
// hand for when there is no AI. Every step of a recipe is a list of four texts: [title, what to do (2-4 simple sentences),
// when it is done, a hint for anyone who gets stuck]. The number of steps in each recipe is in RICETTE in js/guida.js.
export default {
  'guida.serve-per': 'For “{cosa}” you need:',
  'guida.nessuna-app': 'I didn’t find any suitable apps on this computer. That’s fine: when you need one, the step tells you what to install.',
  'guida.apri': 'Open',
  'guida.apri-tutte': 'Open all',
  'guida.aperta': 'Opened: {app}.',
  'guida.non-aperta': 'I couldn’t open {app}.',
  'guida.cominciamo': 'Let’s start',
  'guida.preparo': 'Preparing the plan',
  'guida.piano-ai': 'Plan written with {motore}: if a step isn’t right for you, skip it.',
  'guida.piano-ricetta': 'Lode’s plan, without AI.',
  'guida.piano-generico': 'I don’t have a recipe for this, so here is a general plan to adapt.',
  'guida.piano-ripiego': 'The AI didn’t give a valid plan: I’m using Lode’s.',
  'guida.passo-di': 'Step {i} of {tot}',
  'guida.fatto-quando': 'Done when: {quando}',
  'guida.ti-serve': 'You need: {app}',
  'guida.fatto-avanti': 'Done, next',
  'guida.non-ci-riesco': 'I can’t do it',
  'guida.indietro': 'Back',
  'guida.basta': 'Stop',
  'guida.un-aiuto': 'A hint',
  'guida.piu-piccolo': 'Smaller, one piece at a time:',
  'guida.ci-penso': 'I’ll think about it',
  'guida.fallo-con': 'Do it with {agente}',
  'guida.scegli-cartella': 'First choose the folder to work in.',
  'guida.cartella': 'Choose the folder',
  'guida.testo-agente': 'This is the text that goes to {agente}, in the folder “{cartella}”. You can change it.',
  'guida.nota-agente': 'A Terminal window opens with {agente}: it uses your subscription, no key needed. Read what it does before you say yes.',
  'guida.agente-aperto': 'I opened the Terminal with {agente}.',
  'guida.agente-segue': 'Lode is watching the folder: when {agente} finishes, I’ll tell you here.',
  'guida.agente-errore': 'The Terminal didn’t open: {errore}',
  'guida.agente-finito': '{agente} has finished: check the result and press Done.',
  'guida.prompt-agente': 'I’m doing this: {obiettivo}. The step now is “{passo}”: {cosa} Do only this step, explain in plain words what you are doing, and stop at the end.',
  'guida.fine-titolo': 'All done!',
  'guida.fine-testo': { one: '{titolo}: the step is done. Nice work.', other: '{titolo}: {n} steps out of {n}, all done. Nice work.' },
  'guida.chiusa': 'Guide set aside',
  'guida.chiusa-nota': 'When you want to continue, type “resume the guide”.',
  'guida.ripresa': 'Picking up where you left off.',
  'guida.nessuna': 'You don’t have a guide in progress. Try typing “I want to make a presentation”.',
  'guida.proposta-titolo': 'In progress: {titolo}',
  'guida.proposta-testo': 'You’re on step {i} of {tot}.',
  'guida.proposta-bottone': 'Resume',
  'guida.nel-vault': 'The list of steps is also in the vault: {nota}.',
  // the note in the vault (in the vault’s language)
  'guida.nota-file': 'Step by step',
  'guida.nota-intro': 'Lode’s guide. Lode ticks a step when you press “Done, next” in the bar.',
  'guida.nota-quando': 'Done when',
  'guida.linguaggio': 'your language',

  // the recipes: [title, what to do, done when, hint]
  'guida.r-tesi-1': ['Understand what they ask', 'Reread the assignment or talk to your supervisor. Write in one line the question your work answers. Note the deadline and how many pages you need.', 'you have one sentence with the question and the due date', 'If you don’t know where to start, write three questions about the topic that make you curious and pick the one with the most material.'],
  'guida.r-tesi-2': ['Gather your sources', 'Look for 5-10 serious sources: books, articles, course notes. Save them all in one place, with author and year. For each one, write two lines on what you need it for.', 'you have a list of sources with two lines each', 'Start from the bibliography of a good article: it leads you to other sources someone has already picked.'],
  'guida.r-tesi-3': ['Make the outline', 'Write the chapter titles and, under each, three or four points. It doesn’t have to be perfect. The outline is the map: you’ll change it as you write.', 'you have an outline with the points of each chapter', 'Use the classic structure: introduction, what is already known, what you did, results, conclusions.'],
  'guida.r-tesi-4': ['Write the first draft', 'Write one chapter at a time, without correcting. A bad page is better than an empty page. Add the quotes right away so you don’t lose them.', 'every chapter has a text, even a bad one', 'Work in short sessions: “focus 25” and write just one paragraph.'],
  'guida.r-tesi-5': ['Reread and fix', 'Read everything out loud: you can hear the long sentences. Check that every chapter answers the first question. Fix the citations and the bibliography.', 'you have reread everything once, from start to finish', 'Print it or change the font: on the same page your eye skips the mistakes.'],
  'guida.r-tesi-6': ['Hand it in', 'Export to PDF and check the pages one by one. Follow the rules of the required format. Send the file and keep a copy.', 'the file is handed in and you have a copy', 'Read your department’s format rules before exporting: margins, font, title page.'],

  'guida.r-sito-1': ['Decide what the site should do', 'Write who will look at it and what they should find. List the pages: for example Home, About me, Projects, Contact. Sketch the main page on a sheet of paper.', 'you have the list of pages and a sketch', 'Look at three similar sites you like and note what they have in common.'],
  'guida.r-sito-2': ['Set up the folder', 'Create a folder for the site and open it in the editor. Inside, create index.html and style.css. Write a page with just a title and open it in the browser.', 'the browser shows your title', 'In index.html it’s enough to write the h1 tag with your name: save and reload the page.'],
  'guida.r-sito-3': ['Write the structure', 'Put the parts of the page in HTML: header, sections, footer. Use real headings and paragraphs, no style for now. Add the other pages and the links between them.', 'all the pages are there and the links work', 'One page at a time: copy index.html, change the text and link it with an a tag.'],
  'guida.r-sito-4': ['Add the style', 'In the CSS pick a font, two colors and the margins. Make sure it reads well on a phone too. Check it with the browser’s tools.', 'the site reads well on the computer and on the phone', 'Start with a few rules: font-family, max-width for the text, a bit of padding.'],
  'guida.r-sito-5': ['Put it online', 'Pick a free service for static sites, for example GitHub Pages or Netlify. Upload the folder and open the address they give you. Send it to a friend and ask what they don’t understand.', 'the site opens from a public address', 'With GitHub Pages: create a repository, upload the files and turn on Pages in the settings.'],

  'guida.r-codice-1': ['Understand the problem', 'Reread the assignment and write in words what goes into the program and what comes out. Prepare two or three examples with the right result. That way you’ll know when it works.', 'you have two or three examples of input and output', 'Work out one tiny example by hand, on paper, step by step.'],
  'guida.r-codice-2': ['Set up the environment', 'Create a folder for the project and open it in the editor. Check that {linguaggio} works: write a program that prints one line and run it.', 'the test program prints its line', 'If the command isn’t found, the program isn’t installed or isn’t in the PATH: look for the official guide for your system.'],
  'guida.r-codice-3': ['Write the first version', 'Write in {linguaggio} the simplest version that solves the first example. No special cases for now. Run the program often, after just a few lines.', 'the first example gives the right result', 'Split it into small functions: one reads, one calculates, one prints.'],
  'guida.r-codice-4': ['Try all the cases', 'Try the other examples and the edge cases: empty, a single item, big numbers. When something goes wrong, read the error and print the values halfway through. Fix one error at a time.', 'all the examples give the right result', 'Copy the error and type “explain the error”: I’ll explain it one step at a time.'],
  'guida.r-codice-5': ['Clean up and hand in', 'Give the variables clear names and remove the test prints. Add two lines explaining how to run it. Reread the assignment and check you did everything.', 'the code is clean and the assignment is met', 'Explain the code out loud, line by line: where you get stuck, there’s something to fix.'],

  'guida.r-presentazione-1': ['Decide the message', 'Write in one sentence what your audience should remember. Check how much time you have: roughly one slide a minute. Pick three points, no more.', 'you have the message sentence and three points', 'Imagine telling it to a friend in one minute: what you say is the message.'],
  'guida.r-presentazione-2': ['Make the outline', 'Write a title for each slide, in order. First the opening, then the three points, then the closing. No graphics for now.', 'you have a list of titles, one per slide', 'Use sticky notes or a list: moving ideas around is easier before you open the program.'],
  'guida.r-presentazione-3': ['Fill in the slides', 'One idea per slide, few words, big images. The long text you say, you don’t write it. Use the same style on all of them.', 'every slide has its content', 'If a slide has more than six lines, split it in two.'],
  'guida.r-presentazione-4': ['Practice out loud', 'Run through the whole presentation with a timer. Mark where you get stuck and where you run long. Cut whatever the message doesn’t need.', 'you ran through it in the right time', 'Record yourself on your phone and listen back once.'],
  'guida.r-presentazione-5': ['Get ready for the day', 'Export to PDF too, in case the program isn’t there. Bring the file on a USB stick or in the cloud. Prepare an answer to two likely questions.', 'you have the backup PDF and the two answers', 'Arrive a few minutes early and test the projector.'],

  'guida.r-video-1': ['Write what you’ll tell', 'Decide in one sentence what the video is about and how long it lasts. Write the list of scenes. If you speak, write the text and read it out loud.', 'you have the scene list and the text', 'A short video works better: start with one that’s a minute long.'],
  'guida.r-video-2': ['Record', 'Record the scenes on your list, each one several times. Take care of the light and above all the sound: a microphone close to you matters more than the camera. Hold the phone still and sideways, unless it’s for social media.', 'you have recorded all the scenes', 'Record in a quiet place, with a window in front of you and not behind.'],
  'guida.r-video-3': ['Edit', 'Import the files into the editing program. Put the scenes in order and cut the pauses and the mistakes. Watch everything once without stopping.', 'the video plays from start to finish', 'Cut more than you think: one second too many is noticeable.'],
  'guida.r-video-4': ['Polish', 'Fix the volume, add the titles and, if needed, quiet music. Use royalty-free music. Add subtitles if someone will watch without sound.', 'sound, titles and subtitles are all set', 'Listen with headphones: you can hear the jumps in volume.'],
  'guida.r-video-5': ['Export and hand in', 'Export as MP4, 1080p, which works almost everywhere. Watch the exported file to the end. Upload it or hand it in and keep the project.', 'the file is handed in and you watched all of it', 'If the file is too big, export at a lower bitrate.'],

  'guida.r-dati-1': ['Write the question', 'Write in one line what you want to find out from the data. Decide which chart would answer it: a trend, a comparison, a distribution. That way you know what to look for.', 'you have the question and the type of chart', 'Complete the sentence: when one thing changes, does the other change too?'],
  'guida.r-dati-2': ['Prepare the data', 'Open the data in a spreadsheet. One row per observation, one column per variable, with a clear name. Remove empty rows and duplicates.', 'the table is clean, with headers', 'Work on a copy: always keep the original file.'],
  'guida.r-dati-3': ['Look at the numbers', 'For each column calculate the mean, minimum and maximum. Look for strange values: typos or real cases? Note what you notice.', 'you have the summary numbers and the notes', 'Sort the column: the strange values end up at the top or at the bottom.'],
  'guida.r-dati-4': ['Make the chart', 'Create the chart that answers the question. Add the title, the axis names and the units. Remove everything that isn’t needed to read it.', 'the chart makes sense without explanations', 'Lines for change over time, bars to compare, a histogram for the distribution.'],
  'guida.r-dati-5': ['Write what it says', 'Under the chart write two or three sentences: what you see and what it means. Say what the data can’t tell you, too. Save the chart as an image.', 'you have the chart saved and the sentences', 'Keep what you see apart from your explanation: facts first, then the idea.'],

  'guida.r-esame-1': ['Put the syllabus in order', 'Take the course syllabus and paste it into Lode with “syllabus”. You’ll get the map of the topics. Mark the ones you already know.', 'the syllabus is in Lode', 'If you can’t find the syllabus, look at the course page or ask your classmates.'],
  'guida.r-esame-2': ['Make a plan', 'Count the days left and split the topics. Leave the last days for review. Put the plan in the calendar.', 'every topic has its day', 'Type “weekly plan” and Lode shows you your real free hours.'],
  'guida.r-esame-3': ['Study one topic a day', 'Do short sessions with the timer, for example “focus 50”. At the end of each topic make cards with the things to remember. Review them every day with “review”.', 'you have studied all the topics at least once', 'Explain the topic out loud as if you were the professor: where you get stuck, reread.'],
  'guida.r-esame-4': ['Test yourself', 'Take the “quiz” or have me ask you questions with “quiz me”. Mark the questions you got wrong and study them again. Repeat until you know them.', 'you answer most of the questions well', 'Start with the topics you know least: that’s where you gain the most.'],
  'guida.r-esame-5': ['Do a real trial', 'Two or three days before, do the “mock exam” with an old paper and the real time. Correct it and review your mistakes. The day before, sleep.', 'you have done a whole paper in the time', 'If you don’t have old papers, ask your classmates or the course group.'],

  'guida.r-generico-1': ['Write the result', 'Write in one sentence what the finished thing will look like. The more concrete, the better. Note when you need it by, too.', 'you have the result sentence and the date', 'Imagine showing it to someone: what do they see?'],
  'guida.r-generico-2': ['Find what you need', 'List what you need: programs, materials, people to talk to. See how someone else did it, for example in a video or a guide.', 'you have the list of what you need', 'Search for the name of the thing plus “tutorial” or “beginner’s guide”.'],
  'guida.r-generico-3': ['Take a small first step', 'Pick the smallest thing you can do right now, in 20 minutes. Do it straight away, even if it’s not perfect. The rest gets easier.', 'you have done the first piece', 'If 20 minutes feels like a lot, do 5 minutes: starting is enough.'],
  'guida.r-generico-4': ['Keep going and check', 'Split the rest into one-session pieces and do them one at a time. After each piece, compare with the result you wrote down. Ask for an opinion before the end.', 'the result is as you wrote it', 'If you get stuck, go back to the previous piece and make it smaller.'],
};
