// Your grades in grading systems other than Italy's (English): «what do I need», «what if I get», credits, final grade,
// the pasted transcript (js/libretto.js, js/lode.js, js/pagina.js, js/benvenuto.js).
export default {
  'libretto.crediti-di': '{fatti} of {tot} {crediti}',
  'libretto.serve-gia': 'To reach <b>{obiettivo}</b> you just need to pass the exams you have left.',
  'libretto.serve-media': 'To reach <b>{obiettivo}</b> you need an average of <b>{voto}</b> in the {cfu} {crediti} you have left.',
  'libretto.serve-impossibile': '<b>{obiettivo}</b> is out of reach now: aim for {punta}.',
  'libretto.obiettivo-fuori': 'In the {sistema} system the target goes from {da} to {a}.',
  'libretto.simula-esito': 'Average <b>{media}</b> <span class="{classe}">{delta}</span> · {finale} <b>{valore}</b>',
  'libretto.voto-altro-sistema': "{voto} ({sistema}): doesn't count in this system",
  'libretto.totali-opzione': '{n} {crediti}',
  'libretto.simula': 'With **{voto}** in {nome} your average goes from {prima} to **{dopo}** ({delta}): {finale} **{valore}**.',
  'libretto.simula-primo': 'With {voto} in **{nome}** your average would start at **{media}**: {finale} **{valore}**.',
  'libretto.sintesi-media-finale': 'average {media}, {finale} {valore}',
  'libretto.non-valido': 'There is no {voto} in the {sistema} system.',
  'libretto.non-superato': '{voto} in {nome} is not a pass (you need {sufficienza}): I won\'t add it to your grades.',
  'libretto.nuovo-esame': 'New exam worth {n} {crediti}: fix them in your grades.',
  'libretto.formula': 'weighted by {crediti}',
  'libretto.piede-esami': { one: '{n} exam · {cfu} {crediti}', other: '{n} exams · {cfu} {crediti}' },
  'libretto.piede-media': 'average <b>{media}</b> · {finale} <b>{valore}</b>',
  'libretto.campo-voto-nota': 'as on your transcript ({esempio}); empty if you haven\'t taken it yet',
  'libretto.voto-non-letto': 'I can\'t read the grade «{voto}»: write it as on your transcript, for example {esempio}.',
  'libretto.incolla-sotto': 'Open your transcript on the university portal, select all, copy and paste it here: one line per exam, with name, credits and grade. Or type them yourself, for example «{esempio}».',
  'libretto.alla-laurea': '{n} {crediti} to graduation',
  'libretto.campo-crediti': 'Credits ({crediti})',
  'libretto.libretto-vuoto': 'No exams yet. Type in the bar <kbd>I got {voto} in physics</kbd>.',
  'libretto.riga-esempio': '{nome}, {n} {crediti}, {voto}',
  'libretto.esame-esempio': 'Calculus 1',
};
