// The “What does it print?” questions (js/codice/modelli.js), in English.
// Keys: modelli.<model>.cosa / .concetto / .frase-N (the mutant sentences, in order), modelli.<model>.<language>.… for
// what changes in Python and Java; modelli.concetti.* and modelli.errori.* are the names of topics and mistakes.
export default {
  'modelli.hai-scelto': 'You picked `{s}`',
  'modelli.niente': '(nothing)',
  'modelli.concetti.for': 'for loop',
  'modelli.concetti.while': 'while loop',
  'modelli.concetti.do-while': 'do-while loop',
  'modelli.concetti.ritroso': 'Counting down',
  'modelli.concetti.array': 'Arrays',
  'modelli.concetti.divisione-intera': 'Integer division',
  'modelli.concetti.resto': 'Remainder with negatives',
  'modelli.concetti.cast': 'Cast to double',
  'modelli.concetti.incremento': 'i++ and ++i',
  'modelli.concetti.assegnamento': 'Compound assignment (+=)',
  'modelli.concetti.switch': 'switch and break',
  'modelli.concetti.cortocircuito': 'Short-circuit && and ||',
  'modelli.concetti.else-pendente': 'Dangling else',
  'modelli.concetti.puntatori': 'Pass by address',
  'modelli.concetti.parametri': 'Pass by value',
  'modelli.concetti.visibilita': 'Variables in blocks',
  'modelli.concetti.char': 'char and ASCII codes',
  'modelli.concetti.ricorsione': 'Recursion',
  'modelli.concetti.annidati': 'Nested loops',
  'modelli.concetti.break-continue': 'break and continue',
  'modelli.concetti.ternario': 'Ternary operator',
  'modelli.errori.fuori-di-uno': 'off by one',
  'modelli.errori.divisione-intera': 'integer division',
  'modelli.errori.post-vs-pre': 'i++ and ++i',
  'modelli.errori.break-dimenticato': 'missing break',
  'modelli.errori.copia-del-parametro': 'copy of the parameter',
  'modelli.errori.cortocircuito': 'short-circuit',
  'modelli.errori.resto-col-segno': 'sign of the remainder',
  'modelli.errori.piu-uguale': '+= and =',
  'modelli.errori.maggiore-o-uguale': '> and >=',
  'modelli.errori.indice-valore': 'index and value',
  'modelli.errori.sovrascrittura': 'first and last',
  'modelli.errori.else-pendente': 'dangling else',
  'modelli.errori.variabile-nascosta': 'shadowed variable',
  'modelli.errori.carattere-codice': 'character and code',
  'modelli.errori.caso-base': 'base case',
  'modelli.errori.passo-del-ciclo': 'when the loop step happens',
  'modelli.errori.ricorsione': 'recursion',
  'modelli.errori.cicli-annidati': 'nested loops',
  'modelli.errori.break-continue': 'break and continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'ternary the wrong way round',
  'modelli.errori.scambi-in-fila': 'swaps in a row',
  'modelli.for-minore.cosa': 'this for',
  'modelli.for-minore.concetto': 'With `i < n` the last pass has i = n - 1: the value n is never printed.',
  'modelli.for-minore.frase': `{hai}: that's what it would print with \`i <= {b}\`. Here the loop stops earlier.`,
  'modelli.for-minore.frase-2': `{hai}: it's as if \`i++\` ran before the first pass. The increment comes at the end of each pass: the first pass has i = {a}.`,
  'modelli.for-minore.frase-3': `{hai}: you stopped one pass too early. With \`i < {b}\` the last pass has i = {b2}.`,
  'modelli.for-passo.cosa': 'this for',
  'modelli.for-passo.concetto': 'With `<=` the loop also does the pass where i equals the limit.',
  'modelli.for-passo.frase': `{hai}: that's what it would print with \`i < {b}\`. With \`<=\`, {b} gets printed too.`,
  'modelli.for-passo.frase-2': `{hai}: \`i += {s}\` doesn't run before the first pass. The first pass has i = {a}.`,
  'modelli.for-indietro.cosa': 'this countdown',
  'modelli.for-indietro.concetto': 'The loop runs while the condition is true: with `i > L` the value L isn\'t printed.',
  'modelli.for-indietro.frase': `{hai}: that's what it would print with \`i >= {l}\`. With \`i > {l}\` the last pass has i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai}: \`i--\` comes at the end of the pass, not before. The first pass prints {n}.`,
  'modelli.for-indietro.frase-3': `{hai}: you stopped one pass too early. i = {l} also satisfies \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'this while',
  'modelli.while-somma.concetto': 'The while exits when the condition becomes false: after `while (i < n)` the variable i is n.',
  'modelli.while-somma.frase': `{hai}: that's what it would print with \`i <= {n}\`. Here the loop does one pass fewer.`,
  'modelli.while-somma.frase-2': `{hai}: it's as if \`i++\` came before \`s += i\`. Here s adds i and only then does i go up.`,
  'modelli.while-somma.frase-3': `{hai}: after the loop i isn't {n}. The while exits exactly when i becomes {n2}.`,
  'modelli.while-dimezza.cosa': 'this while',
  'modelli.while-dimezza.concetto': 'Between two ints `/` truncates: 7 / 2 is 3, and halving gets you to 1 with no decimals.',
  'modelli.while-dimezza.frase': `{hai}: that's what would happen if n were a double. n is an int: \`n /= 2\` throws away the decimal part.`,
  'modelli.while-dimezza.frase-2': `{hai}: that's what it would print with \`n >= 1\`. The loop stops as soon as n gets to 1.`,
  'modelli.while-post.cosa': 'this while with i++',
  'modelli.while-post.concetto': '`i++ < n` compares the old value and then increments: inside the loop i has already gone up.',
  'modelli.while-post.frase': `{hai}: that's what it would print with \`++i\`. With \`i++\` the comparison uses the old value.`,
  'modelli.while-post.frase-2': `{hai}: when printf runs, i has already been incremented by the comparison.`,
  'modelli.while-post.frase-3': `{hai}: the last comparison, the false one, increments i too. At the end i is {n}.`,
  'modelli.array-somma.cosa': 'this sum',
  'modelli.array-somma.concetto': 'The indices of an array of n elements go from 0 to n - 1.',
  'modelli.array-somma.frase': `{hai}: you skipped \`v[0]\`. The first element has index 0.`,
  'modelli.array-somma.frase-2': `{hai}: you left out the last one. With \`i < {k}\` the last pass reads \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai}: that's the last element, as if it said \`s = v[i]\`. \`+=\` adds, it doesn't replace.`,
  'modelli.array-massimo.cosa': 'this maximum',
  'modelli.array-massimo.concetto': 'p is an index: it counts from 0. With `>` the first position of the maximum stays.',
  'modelli.array-massimo.frase': `{hai}: you counted the positions from 1. In {linguaggio} the first element has index 0.`,
  'modelli.array-massimo.frase-2': `{hai}: that's what \`>=\` would do. With \`>\` an equal maximum doesn't move p: the first one stays.`,
  'modelli.array-massimo.frase-3': `{hai}: you left out the last element. It gets compared too.`,
  'modelli.array-ultimo.cosa': 'this search',
  'modelli.array-ultimo.concetto': 'The loop doesn\'t stop when it finds x: p gets overwritten and ends up as the last position.',
  'modelli.array-ultimo.frase': `{hai}: that's the first position. The loop doesn't stop: every time it finds x it rewrites p.`,
  'modelli.array-ultimo.frase-2': `{hai}: you counted the positions from 1. In {linguaggio} the first element has index 0.`,
  'modelli.array-ultimo.frase-3': `{hai}: that's the value being searched for, not its position. p is an index.`,
  'modelli.media-array.cosa': 'this average',
  'modelli.media-array.concetto': '`s / n` between ints truncates. `(double)s / n` converts first and divides with decimals.',
  'modelli.media-array.frase': `{hai}: \`s / {k}\` is a division between two ints: the decimal part is lost.`,
  'modelli.media-array.frase-2': `{hai}: the cast \`(double)s\` happens before the division, so the division keeps the decimals.`,
  'modelli.media-array.frase-3': `{hai}: division between ints doesn't round, it truncates.`,
  'modelli.divisione-double.cosa': 'this division',
  'modelli.divisione-double.concetto': 'The type of the result doesn\'t matter: `a / b` between ints truncates even if it ends up in a double.',
  'modelli.divisione-double.frase': `{hai}: \`a / b\` is worked out between ints, before it goes into m. The double gets a number that's already truncated.`,
  'modelli.divisione-double.frase-2': `{hai}: division between ints doesn't round, it truncates towards zero.`,
  'modelli.cast-prima-dopo.cosa': 'these two casts',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` divides between ints and then converts. `(double)s / n` converts and then divides.',
  'modelli.cast-prima-dopo.frase': `{hai}: in \`(double)(s / n)\` the brackets make the division happen first, between ints. The cast comes after.`,
  'modelli.cast-prima-dopo.frase-2': `{hai}: in \`(double)s / n\` the cast only applies to s, and the division keeps the decimals.`,
  'modelli.cast-prima-dopo.frase-3': `{hai}: you swapped them. The brackets decide whether the cast comes before or after the division.`,
  'modelli.diviso-due.cosa': 'this division by 2',
  'modelli.diviso-due.concetto': 'One double in the sum is enough: `a / 2.0` keeps the decimals, `a / 2` doesn\'t.',
  'modelli.diviso-due.frase': `{hai}: \`a / 2\` is between two ints: it truncates and gives an int, which %d prints with no decimals.`,
  'modelli.diviso-due.frase-2': `{hai}: \`2.0\` is a double, so \`a / 2.0\` keeps the decimals.`,
  'modelli.diviso-due.frase-3': `{hai}: \`a / 2\` doesn't round: it truncates towards zero.`,
  'modelli.resto-negativi.cosa': 'this remainder',
  'modelli.resto-negativi.concetto': `In {linguaggio} division truncates towards zero and the remainder has the sign of the dividend: -7 % 3 is -1.`,
  'modelli.resto-negativi.frase': `{hai}: that's what Python does, rounding down. In {linguaggio} it truncates towards zero.`,
  'modelli.resto-negativi.frase-2': `{hai}: in {linguaggio} the remainder isn't always positive. It has the sign of the dividend, that is of a.`,
  'modelli.resto-negativi.frase-3': `{hai}: division between ints truncates towards zero, not downwards.`,
  'modelli.post-pre.cosa': 'these increments',
  'modelli.post-pre.concetto': '`x = i--` uses the old value and then decrements; `y = --i` decrements and then uses the new value.',
  'modelli.post-pre.concetto-2': '`x = i++` uses the old value and then increments; `y = ++i` increments and then uses the new value.',
  'modelli.post-pre.frase': `{hai}: with \`x = i{op}\` x takes the old value, then i changes.`,
  'modelli.post-pre.frase-2': `{hai}: with \`y = {op}i\` i changes first, then y takes the new value.`,
  'modelli.post-pre.frase-3': `{hai}: you swapped them. The sign after (\`i{op}\`) uses the old value, the sign before (\`{op}i\`) the new one.`,
  'modelli.piu-uguale.cosa': 'this +=',
  'modelli.piu-uguale.concetto': '`s += x` means `s = s + x`: it adds to the value that was there.',
  'modelli.piu-uguale.frase': `{hai}: that's only the last pass, as if it said \`=\`. \`+=\` adds every time.`,
  'modelli.piu-uguale.frase-2': `{hai}: with \`<=\`, i = {n} gets its pass too.`,
  'modelli.piu-uguale.frase-3': `{hai}: you forgot the starting value. s starts at {a}.`,
  'modelli.switch.cosa': 'this switch',
  'modelli.switch.concetto': 'Without break, execution falls through into the case below and carries on until the first break or the end.',
  'modelli.switch.frase': `{hai}: it's as if every case had its own break. Without break you carry on into the case below.`,
  'modelli.switch.frase-2': `{hai}: you skipped the break. That's where the switch stops.`,
  'modelli.switch.frase-3': `{hai}: default doesn't always run. It runs if no case matches, or if you fall into it from a case without break.`,
  'modelli.cortocircuito.cosa': 'this if with || and &&',
  'modelli.cortocircuito.concetto': 'If the first part is enough to decide (true with ||, false with &&), the second isn\'t run.',
  'modelli.cortocircuito.frase': `{hai}: \`++n\` isn't run. With \`{op}\` the first part is already enough to decide, and n stays 0.`,
  'modelli.cortocircuito.frase-3': '|| needs at least one part to be true',
  'modelli.cortocircuito.frase-4': '&& needs both parts to be true',
  'modelli.cortocircuito.frase-2': `{hai}: you read \`{op}\`. {op2}.`,
  'modelli.else-pendente.cosa': 'this else',
  'modelli.else-pendente.concetto': 'The else goes with the nearest if that doesn\'t already have an else, whatever the indentation.',
  'modelli.else-pendente.frase': `{hai}: you followed the indentation. But the else goes with the nearest if, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai}: with \`i < {n}\` the last pass has i = {n2}.`,
  'modelli.swap-valore.cosa': 'this swap',
  'modelli.swap-valore.concetto': 'A function gets copies of the values: swapping a and b doesn\'t touch x and y.',
  'modelli.swap-valore.frase': `{hai}: a and b are copies of x and y. The swap stays inside the function.`,
  'modelli.swap-valore.frase-2': `{hai}: inside the function the swap really happens. It's the copies that get swapped, not x and y.`,
  'modelli.swap-indirizzo.cosa': 'these swaps with pointers',
  'modelli.swap-indirizzo.concetto': 'With `&x` the function gets the address: `*a = …` changes x itself. The swaps happen one after the other.',
  'modelli.swap-indirizzo.frase': `{hai}: these aren't copies. \`&x\` passes the address, and \`*a\` writes into x itself.`,
  'modelli.swap-indirizzo.frase-2': `{hai}: the swaps go in order. First x with y, then the new y with z.`,
  'modelli.swap-indirizzo.frase-3': `{hai}: the second swap sees y already changed by the first.`,
  'modelli.valore-e-indirizzo.cosa': 'this function',
  'modelli.valore-e-indirizzo.concetto': 'a is a copy of x; b is the address of y: only `*b = …` changes the variable in main.',
  'modelli.valore-e-indirizzo.frase': `{hai}: a is a copy of x. Changing a doesn't change x.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai}: b isn't a copy, it's the address of y. \`*b = …\` changes y.`,
  'modelli.array-in-funzione.cosa': 'this array passed to a function',
  'modelli.array-in-funzione.concetto': 'An array is passed by address: the function changes a itself. An int, on the other hand, is passed as a copy.',
  'modelli.array-in-funzione.frase': `{hai}: an array isn't copied. The function works on the same elements as a.`,
  'modelli.array-in-funzione.frase-2': `{hai}: n, on the other hand, is a copy. The function's \`n--\` doesn't touch the n in main.`,
  'modelli.blocco-ombra.cosa': 'these two x\'s',
  'modelli.blocco-ombra.concetto': 'The x declared in the block is a different variable: it hides the outer one and disappears at the }.',
  'modelli.blocco-ombra.frase': `{hai}: \`int x = {b}\` inside the braces creates a new x. Outside, x is still {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai}: inside the block the nearest x is the inner one. y uses that.`,
  'modelli.char-ascii.cosa': 'these chars',
  'modelli.char-ascii.concetto': 'A char is a number: \'a\' is 97. %c prints the letter, %d the code. Uppercase = lowercase - 32.',
  'modelli.char-ascii.frase': `{hai}: %d doesn't give the position in the alphabet. It gives the ASCII code: 'a' is 97.`,
  'modelli.char-ascii.frase-2': `{hai}: %d prints the character's number, not the letter.`,
  'modelli.char-ascii.frase-3': `{hai}: d is a char and %c prints it as a letter, the uppercase one.`,
  'modelli.fattoriale.cosa': 'this recursion',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), and the base case stops the descent at 1.',
  'modelli.fattoriale.frase': `{hai}: that's fatt({n}). You did one step too few: you multiply from {n2} down to 1.`,
  'modelli.fattoriale.frase-2': `{hai}: that's fatt({n}). You did one step too many: you start from {n2}.`,
  'modelli.fattoriale.frase-3': `{hai}: you stopped at the first call. fatt(n - 1) keeps calling itself until the base case.`,
  'modelli.somma-cifre.cosa': 'this recursion',
  'modelli.somma-cifre.concetto': 'n % 10 is the last digit, n / 10 drops the last digit. The base case returns the digit that\'s left.',
  'modelli.somma-cifre.frase': `{hai}: you lost the first digit. The base case returns n, not 0.`,
  'modelli.somma-cifre.frase-2': `{hai}: that's the number of digits. Here each call adds \`n % 10\`, the digit, not 1.`,
  'modelli.somma-cifre.frase-3': `{hai}: that's only the last digit. The return value is added to the one from the next call.`,
  'modelli.ricorsione-ordine.cosa': 'this recursion',
  'modelli.ricorsione-ordine.concetto': 'printf comes after the call: it prints on the way back, so from smallest to largest.',
  'modelli.ricorsione-ordine.frase': `{hai}: that's how it would be with printf before the call. Here it prints on the way back.`,
  'modelli.ricorsione-ordine.frase-2': `{hai}: with n = 0 the function returns straight away, without printing.`,
  'modelli.annidati-conta.cosa': 'these nested loops',
  'modelli.annidati-conta.concetto': 'The inner loop starts again on every pass of the outer one: here it runs i times, that is 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai}: that's what \`j <= i\` would give. With \`j < i\` the first pass (i = 0) counts nothing.`,
  'modelli.annidati-conta.frase-2': `{hai}: the inner loop doesn't always run {n} times: it runs i times.`,
  'modelli.annidati-stelle.cosa': 'these stars',
  'modelli.annidati-stelle.concetto': 'For each row i the inner loop prints i symbols, then `\\n` starts a new line.',
  'modelli.annidati-stelle.frase': `{hai}: one symbol too many per row. j starts at 0 and with \`j < i\` it does i passes.`,
  'modelli.annidati-stelle.frase-2': `{hai}: the inner loop depends on i: it doesn't always print {n} symbols.`,
  'modelli.annidati-stelle.frase-3': `{hai}: the last row is missing. With \`i <= {n}\` row {n} gets printed too.`,
  'modelli.break-continue.cosa': 'this break and this continue',
  'modelli.break-continue.concetto': `\`continue\` jumps to the next pass; \`break\` leaves the loop, and the {l} of that pass never happens.`,
  'modelli.break-continue.frase': `{hai}: \`continue\` doesn't leave the loop: it only skips the pass with i = {a}.`,
  'modelli.break-continue.frase-2': `{hai}: \`break\` doesn't skip a pass: it leaves the loop when i is {b}.`,
  'modelli.break-continue.frase-3': `{hai}: the break comes before the {l}: {b} isn't printed.`,
  'modelli.do-while.cosa': 'this do-while',
  'modelli.do-while.concetto': 'The do-while checks the condition at the end of each pass: the body always runs at least once.',
  'modelli.do-while.frase': `{hai}: that's what a while would do. The do-while runs the body before checking.`,
  'modelli.do-while.frase-3': 'The do-while doesn\'t add a pass: it checks the condition at the end of each pass.',
  'modelli.do-while.frase-4': 'After the first pass the condition is already false.',
  'modelli.do-while.frase-2': `{hai}: one pass too many. {vero}`,
  'modelli.do-while.frase-5': `{hai}: that's what \`i {op}= {b}\` would give. With \`i {op} {b}\`, when i gets to {b} the loop stops.`,
  'modelli.do-while.frase-6': `{hai}: you printed i as it was before the last pass. The last pass changes i too: the check comes after.`,
  'modelli.ternario.cosa': 'these ternaries',
  'modelli.ternario.concetto': '`c ? x : y` is x if c is true, y if it\'s false.',
  'modelli.ternario.frase-m-vera': `{hai}: for m you took the wrong branch. \`a > b\` is true, so it's the value after \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai}: for m you took the wrong branch. \`a > b\` is false, so it's the value after \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai}: for d you took the wrong branch. \`a < b\` is true, so it's the value after \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai}: for d you took the wrong branch. \`a < b\` is false, so it's the value after \`:\`.`,
  'modelli.ternario.frase-7': `{hai}: you read both ternaries the wrong way round. True → the value after \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` stops before {b2}: the last pass has i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai}: that's what \`{b}\` would print. range stops before the second number.`,
  'modelli.for-minore.python.frase-2': `{hai}: you skipped the first pass. range starts exactly at {a}.`,
  'modelli.for-minore.python.frase-3': `{hai}: you stopped one pass too early. \`{b}\` goes up to {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` goes in steps of {s2} and stops before {b}: {b2} gets printed too.`,
  'modelli.for-passo.python.frase': `{hai}: that's what \`{s}\` would print. Here the second number is {b}, so {b2} gets printed too.`,
  'modelli.for-passo.python.frase-2': `{hai}: range starts at {a}, not at {s}. The step is added after the first pass.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` counts down and stops before {l}: {l} isn't printed.`,
  'modelli.for-indietro.python.frase': `{hai}: you printed {l} too. range stops before it: the last pass has i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai}: range starts exactly at {n}: the first pass prints {n}.`,
  'modelli.for-indietro.python.frase-3': `{hai}: you stopped one pass too early. {l} gets printed too.`,
  'modelli.while-somma.python.concetto': 'The while exits when the condition becomes false: after `while i < n` the variable i is n.',
  'modelli.while-somma.python.frase': `{hai}: it's as if \`i += 1\` came before \`s += i\`. Here s adds i and only then does i go up.`,
  'modelli.while-dimezza.python.concetto': '`//` is integer division: 7 // 2 is 3, and halving gets you to 1 with no decimals.',
  'modelli.while-dimezza.python.frase': `{hai}: you kept the decimals, as \`n /= 2\` would. \`n //= 2\` is integer division: it throws away the decimal part.`,
  'modelli.array-somma.python.frase': `{hai}: you left out the last one. \`range({k})\` goes up to {k2}: the last pass reads \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` is integer division; in Python `/` always keeps the decimals, even between two ints.',
  'modelli.media-array.python.frase': `{hai}: \`s // {k}\` is integer division: the decimal part is lost.`,
  'modelli.media-array.python.frase-2': `{hai}: in Python \`/\` keeps the decimals, it doesn't truncate like \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai}: \`//\` doesn't round: it goes down.`,
  'modelli.media-array.java.frase': `{hai}: \`s / {k}\` is between two ints: in Java (as in C, unlike Python) the division stays integer and the decimal part is lost.`,
  'modelli.divisione-double.java.frase': `{hai}: \`a / b\` is worked out between ints, before it goes into m. In Java, as in C, division between two ints truncates: the double gets a number that's already truncated.`,
  'modelli.diviso-due.python.concetto': 'In Python `//` is integer division and `/` always keeps the decimals, even between two ints.',
  'modelli.diviso-due.python.frase': `{hai}: \`a // 2\` is integer division: it gives an int, with no decimals.`,
  'modelli.diviso-due.python.frase-2': `{hai}: in Python \`/\` doesn't truncate like in C or Java: \`a / 2\` keeps the decimals too.`,
  'modelli.diviso-due.python.frase-3': `{hai}: \`a // 2\` doesn't round: it goes down.`,
  'modelli.resto-negativi.python.concetto': 'In Python `//` goes down and the remainder has the sign of the divisor: -7 // 3 is -3 and -7 % 3 is 2.',
  'modelli.resto-negativi.python.frase': `{hai}: that's what C and Java do, truncating towards zero. In Python \`//\` goes down.`,
  'modelli.resto-negativi.python.frase-2': `{hai}: in Python the remainder has the sign of the divisor, that is of b, not of the dividend.`,
  'modelli.resto-negativi.python.frase-3': `{hai}: \`//\` rounds down, not towards zero.`,
  'modelli.piu-uguale.python.frase': `{hai}: \`range(1, {n})\` goes up to {n2}: i = {n2} gets its pass too.`,
  'modelli.swap-valore.python.concetto': 'The function gets the values: reassigning a and b inside the function doesn\'t touch x and y.',
  'modelli.swap-valore.python.frase': `{hai}: a and b are the function's own names. Reassigning them doesn't change x and y.`,
  'modelli.swap-valore.python.frase-2': `{hai}: inside the function the swap really happens. a and b get swapped, not x and y.`,
  'modelli.array-in-funzione.python.concetto': 'The list is passed to the function as it is: `v[n] *= …` changes a itself. n, on the other hand, is the function\'s own name: `n -= 1` doesn\'t touch the outer n.',
  'modelli.array-in-funzione.python.frase': `{hai}: a list isn't copied. The function works on the same elements as a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai}: not n, though. The function's \`n -= 1\` doesn't touch the outer n.`,
  'modelli.array-in-funzione.java.concetto': 'An array is passed as a reference: the function changes a itself. An int, on the other hand, is passed as a copy.',
  'modelli.somma-cifre.python.concetto': '`n % 10` is the last digit, `n // 10` drops the last digit. The base case returns the digit that\'s left.',
  'modelli.ricorsione-ordine.python.concetto': 'print comes after the call: it prints on the way back, so from smallest to largest.',
  'modelli.ricorsione-ordine.python.frase': `{hai}: that's how it would be with print before the call. Here it prints on the way back.`,
  'modelli.annidati-conta.python.concetto': 'The inner loop starts again on every pass of the outer one: `range(i)` does i passes, that is 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai}: that's what \`range(i + 1)\` would give. With i = 0, \`range(i)\` does no passes.`,
  'modelli.annidati-stelle.python.concetto': 'For each row i the inner loop prints i symbols, then `print()` starts a new line.',
  'modelli.annidati-stelle.python.frase': `{hai}: one symbol too many per row. \`range(i)\` does i passes, not i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai}: the last row is missing. \`range(1, {n})\` goes up to {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'For each row i the inner loop prints i symbols, then `println()` starts a new line.',
};
