// The plan for students who work (js/ore.js): the “about” times, the week lines, what doesn't fit, and the choices.
export default {
  'ore.circa-min': 'about {m} min',
  'ore.circa-ore': { one: 'about {n} hour', other: 'about {n} hours' },
  'ore.circa-h': 'about {h} h',
  'ore.circa-h-min': 'about {h} h {m}',
  'ore.opzione-cuscinetto': 'Use the buffer days too',
  'ore.opzione-un-ripasso': 'Only one review for new topics, not two',
  'ore.opzione-tetto': 'On work days I study 3 hours, not 2',
  'ore.giorni-brevi': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  'ore.libere': '{circa} free',
  'ore.niente-ore-libere': 'no free hours',
  'ore.giorno': '{g} {n}',
  'ore.lavoro': 'work {turni}',
  'ore.voce-tema': 'exam exercise ({circa})',
  'ore.argomento': 'topic',
  'ore.voce-generale': 'general review ({circa})',
  'ore.esame': 'Exam',
  'ore.voce-cuscinetto': '{nome}: buffer day, to catch up',
  'ore.oggi-niente': 'No free hours to study today{lav}.',
  'ore.oggi-hai': 'Today you have {liberi}{lav}: {lista}.',
  'ore.oggi-hai-vuoto': "Today you have {liberi}{lav}. There's nothing in the plan today.",
  'ore.per-esame': '{circa} for {nome}',
  'ore.un-esame': 'an exam',
  'ore.mancano': 'You still need {circa} before the {nome} exam.',
  'ore.questo-esame': 'this exam',
  'ore.recuperi': '{testo} · you catch up {circa}',
  'ore.ripiego': "With the hours you have, it doesn't all fit. You can give me extra study days (“I study from 9 to 21”) or think about the next exam date: your call.",
  'ore.mancano-ancora': 'You still need {circa}.',
  'ore.ora-ci-sta': 'Now it fits.',
};
