// Texts of the page under the bar (English): greeting, degree numbers, exam cards, grades, decks, the exam and
// settings windows, backup.
export default {
  // greeting and the line below
  'pagina.saluto-notte': 'Still up',
  'pagina.saluto-mattina': 'Good morning',
  'pagina.saluto-pomeriggio': 'Good afternoon',
  'pagina.saluto-sera': 'Good evening',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} card to review', other: '{n} cards to review' },
  'pagina.sotto-serie': { one: '{n} day in a row', other: '{n} days in a row' },
  'pagina.sotto-niente': 'Nothing pending today.',
  'pagina.sotto-vuoto': 'Your grades, your study plan and your reviews. All here, all yours.',
  // header
  'pagina.sottotitolo': 'study assistant',
  'pagina.esporta': 'Export',
  'pagina.impostazioni': 'Settings',
  'pagina.suggerimento': 'Hover over the bar at the top, press <kbd>/</kbd> to type or hold <kbd>{tasti}</kbd> to talk.',
  // the numbers
  'pagina.media-ponderata': 'Weighted average',
  'pagina.media-dettaglio': { one: 'unweighted {media} · {n} grade', other: 'unweighted {media} · {n} grades' },
  'pagina.primo-voto': 'add your first grade from the bar',
  'pagina.base-laurea': 'Starting graduation mark',
  'pagina.base-formula': 'average × 110 / 30',
  'pagina.crediti': 'Credits',
  'pagina.cfu-alla-laurea': '{n} credits to graduation',
  'pagina.questa-settimana': 'This week',
  'pagina.minuti-settimana': 'Minutes studied in the last 7 days',
  'pagina.giorno-ore': '{giorno}: {ore}',
  'pagina.iniziali-giorni': ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  // exams
  'pagina.prossimi-esami': 'Upcoming exams',
  'pagina.nuovo-esame': 'New exam',
  'pagina.vuoto-scrivi': 'Type in the bar at the top:',
  'pagina.vuoto-comando': 'exam calculus 2 on 15 January 9 credits',
  'pagina.vuoto-oppure': 'or {bottone}',
  'pagina.prova-esempio': 'try it with sample data',
  'pagina.programma-aggiungi': '+ Exam syllabus',
  'pagina.giorno-cuscinetto': 'buffer day',
  'pagina.ripasso-generale': 'general review',
  'pagina.niente-di-nuovo': 'nothing new',
  'pagina.programma-pronto': '<b>{pct}% of the syllabus</b> · today: {oggi}',
  'pagina.data-da-decidere': 'Date to be set',
  'pagina.quando-cfu': '{quando} · {cfu} credits',
  'pagina.giorni-maiuscolo': { one: 'DAY', other: 'DAYS' },
  'pagina.ore-studiate': '{fatte} of {tot} h studied',
  'pagina.ore-oggi': '<b>{h} h</b> today',
  'pagina.oggi-in-pari': 'on track today',
  'pagina.focus': 'Focus',
  'pagina.ripassa': 'Review',
  'pagina.ripassa-n': 'Review {n}',
  'pagina.interrogami': 'Quiz me',
  'pagina.modifica-segna-voto': 'Edit · Add grade',
  // grades and review
  'pagina.libretto': 'Grades',
  'pagina.segna-voto': 'Add a grade',
  'pagina.ripasso': 'Review',
  'pagina.da-file': 'From file',
  'pagina.libretto-vuoto': 'No exams taken yet. Type in the bar <kbd>I got 28 in physics</kbd>.',
  'pagina.col-esame': 'Exam',
  'pagina.col-cfu': 'Credits',
  'pagina.col-voto': 'Grade',
  'pagina.col-data': 'Date',
  'pagina.idoneo': 'passed',
  'pagina.voto-lode': '{voto}L',
  'pagina.modifica-esame': 'Edit {nome}',
  'pagina.libretto-esami': '{n} exams · {cfu} credits',
  'pagina.libretto-media': 'average <b>{media}</b> · starting mark <b>{base}</b>',
  'pagina.mazzi-vuoto': 'No cards yet. Type <kbd>card: question = answer</kbd> or drag a PDF onto the window.',
  'pagina.esame-tolto': 'Exam removed',
  'pagina.senza-esame': 'No exam',
  'pagina.n-carte': { one: '{n} card', other: '{n} cards' },
  'pagina.da-ripassare-oggi': 'to review today',
  'pagina.piede': 'Lode is open source (MIT). Your data stays in this browser: no account, no server.',
  'pagina.importa-backup': 'Import a backup',
  // exam window
  'pagina.esame-correggi': 'Fix the details or add the grade.',
  'pagina.esame-aiuto': 'You can also type it in the bar: “exam physics 2 on 20 February 6 credits”.',
  'pagina.campo-nome': 'Name',
  'pagina.esempio-esame': 'Calculus 2',
  'pagina.campo-cfu': 'Credits',
  'pagina.campo-data': 'Date',
  'pagina.campo-data-appello': 'Exam date',
  'pagina.campo-voto': 'Grade',
  'pagina.campo-voto-nota': "leave empty if you haven't taken it yet",
  'pagina.trenta-e-lode': '30 cum laude',
  'pagina.idoneita': 'Pass/fail',
  'pagina.campo-ore': 'Planned study hours',
  'pagina.campo-ore-nota': 'for the plan',
  'pagina.ore-segnaposto': '10 × credits',
  'pagina.elimina': 'Delete',
  'pagina.annulla': 'Cancel',
  'pagina.salva': 'Save',
  'pagina.conferma-elimina': 'Delete {nome}? Its hours and cards stay, without an exam.',
  'pagina.esame-eliminato': 'Exam deleted',
  'pagina.salvato': 'Saved',
  'pagina.esame-aggiunto': 'Exam added',
  // settings window
  'pagina.impostazioni-aiuto': 'Everything stays on this computer. Your AI key only goes to the service you choose.',
  'pagina.campo-tuo-nome': 'Your name',
  'pagina.esempio-nome': 'Alex',
  'pagina.campo-corso': 'Degree course',
  'pagina.esempio-corso': 'Computer Engineering',
  'pagina.campo-cfu-laurea': 'Credits for the degree',
  'pagina.campo-lode-vale': 'Cum laude counts as',
  'pagina.campo-focus': 'Focus (minutes)',
  'pagina.campo-pausa': 'Break (minutes)',
  'pagina.rintocco': 'Chime at the end of focus',
  'pagina.aspetto-chiaro': 'Light theme',
  'pagina.campo-ai': 'Your AI',
  'pagina.campo-ai-nota': 'optional, pay as you go: you pay the service',
  'pagina.solo-locale': 'Only the local brain (free)',
  'pagina.campo-chiave': 'Key',
  'pagina.campo-chiave-nota': "you create it on the service's website",
  'pagina.chiave-segnaposto': 'paste the key',
  'pagina.voce-alta': 'Read answers aloud',
  'pagina.ai-attiva': 'AI <b>on</b>: {nome}.',
  'pagina.senza-chiave': 'Lode works without a key too: commands, timer, grades and reviews are all local; the app also has the free local brain.',
  'pagina.cancella-tutto': 'Delete everything',
  'pagina.conferma-azzera': "Delete all of Lode's data from this browser? Better export it first.",
  'pagina.dati-cancellati-chiave': 'Data deleted, including the {nome} key: revoke it in your account too ({sito})',
  'pagina.dati-cancellati': 'Data deleted',
  'pagina.chiave-cancellata': '{nome} key deleted from here: revoke it in your account too ({sito})',
  'pagina.impostazioni-salvate': 'Settings saved',
  'pagina.ai-collegata': '{nome} connected',
  'pagina.ai-collegata-modello': '{nome} connected · {modello}',
  'pagina.chiave-non-valida': 'The key is not valid',
  'pagina.chiave-non-verificabile': "I can't check the key right now",
  // backup and sample data
  'pagina.backup-scaricato': 'Backup downloaded',
  'pagina.conferma-importa': 'Replace your current data with this backup?',
  'pagina.backup-importato': 'Backup imported',
  'pagina.non-backup': "This file isn't a Lode backup",
  'pagina.conferma-esempio': 'Load the sample data instead of yours?',
  'pagina.esempio-caricato': 'Sample data loaded: hover over the bar at the top',
};
