// “Follow the project” in the bar (English): pill, cards “Shall I follow…?”, “What's changing”,
// “Done. In plain words”, “Tested?” and “New things”.
export default {
  'progetto.solo-app': 'You can only follow a project in the Lode desktop app.',
  'progetto.provo': 'testing…',
  'progetto.file-cambiati': '{n} files +{piu} −{meno}',
  'progetto.fatto-non-provato': 'done · not tested',
  'progetto.oggi-non-provato': '{nome}: not tested',
  'progetto.oggi-esito': '{nome}: {breve}',
  'progetto.oggi-sta-cambiando': '{nome}: changing',
  'progetto.ultima-prova-alle': 'Last test at {ora}',
  'progetto.vedi': 'See',
  'progetto.esito': 'Result',
  'progetto.prova': 'Test',
  'progetto.provato': 'Tested?',
  'progetto.cosa-e-cambiato': 'What changed',
  'progetto.cosa-sta-cambiando': 'What\'s changing',
  'progetto.serve-seguito': 'You need a project followed in the app: type “follow project”.',
  'progetto.non-seguo-nome': 'I\'m not following any project called “{nome}”.',
  'progetto.non-seguo-niente': 'I\'m not following any project. Type **follow project** and pick your lab folder.',
  'progetto.capito-testo': 'Lode watches the files and checks whether the code has been tested: it doesn\'t write code for you. If you use an agent or an AI, your course decides what\'s allowed: ask your lecturer. The diary is a log for you, not evidence for your lecturer: it\'s what Lode saw, and it doesn\'t know who wrote the lines. For a graded assignment, mark the project as "graded": Lode will tell you where to look and what an error means, but it won\'t show you the fix.',
  'progetto.prima-di-cominciare': 'Before you start',
  'progetto.ho-capito': 'Got it',
  'progetto.solo-app-desktop': 'You can only follow a project in the Lode **desktop app**: that\'s where I watch your lab folder.',
  'progetto.va-bene-non-seguo': 'OK, I won\'t follow anything.',
  'progetto.seguo-gia': 'I\'m already following **{nome}**.',
  'progetto.seguo-domanda': 'Shall I follow <b>{nome}</b>?',
  'progetto.seguo-aria': 'Shall I follow {nome}?',
  'progetto.seguo-spiega': 'I watch the files and keep the versions in Lode\'s folder: I don\'t write in your folder. The commands you confirm (make, for example) do, just like from the terminal. I don\'t know who writes the lines (you, an agent or a copy-paste): I tell you what changed and whether you tested it.',
  'progetto.nota-windows': 'While I\'m following it, Windows won\'t let you rename or move the folder: type “stop following” first.',
  'progetto.corso': 'Course',
  'progetto.nessun-corso': 'No course',
  'progetto.valutato': 'Graded project (assignment)',
  'progetto.valutato-spiega': 'I tell you where to look, but no ready-made fixes',
  'progetto.no-diario': 'Don\'t keep a diary for this project',
  'progetto.no-diario-spiega': 'No file or function names end up in the vault',
  'progetto.n-file': { one: '{n} file', other: '{n} files' },
  'progetto.segui': 'Follow',
  'progetto.annulla': 'Cancel',
  'progetto.annullato': 'Cancelled.',
  'progetto.non-seguo-niente-nota': 'Not following anything.',
  'progetto.seguo-fatto': 'Following {nome}.',
  'progetto.seguo-fatto-nota': 'I\'ll tell you what changes and whether you tested it. I keep the versions in Lode\'s folder.',
  'progetto.seguo-sintesi': 'following {nome}',
  'progetto.smetto-domanda': 'Stop following <b>{nome}</b>?',
  'progetto.smetto-spiega': 'I\'ll delete the copies I kept in Lode\'s folder. I won\'t touch your files.',
  'progetto.smetti-di-seguire': 'Stop following',
  'progetto.continuo-a-seguire': 'Still following {nome}.',
  'progetto.non-seguo-piu': 'No longer following {nome}.',
  'progetto.non-seguo-piu-nota': 'Lode\'s copies are gone. I didn\'t touch your files.',
  'progetto.smesso-sintesi': 'stopped {nome}',
  'progetto.etichetta-nuovo': 'new',
  'progetto.etichetta-tolto': 'removed',
  'progetto.etichetta-grande': 'large file: counts only',
  'progetto.etichetta-spazi': 'only spaces or line breaks',
  'progetto.etichetta-cambiato': 'changed',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Close',
  'progetto.diff-grande': 'Large file (+{piu} −{meno}): I won\'t show the details.',
  'progetto.diff-solo-spazi': 'Only trailing spaces or line breaks change.',
  'progetto.diff-aria': 'Changes to {file}',
  'progetto.diff-tagliato': '… I won\'t show the rest',
  'progetto.niente-di-diverso': 'Nothing different.',
  'progetto.niente-di-nuovo': 'Nothing new.',
  'progetto.niente-di-nuovo-dalle': 'Nothing new since {ora}.',
  'progetto.nome-dalle': '{nome} since {ora}',
  'progetto.prova-adesso': 'Test now',
  'progetto.visto': 'Seen',
  'progetto.provato-breve': 'tested',
  'progetto.prova-il-progetto': 'Test the project',
  'progetto.visto-fatto': 'Seen.',
  'progetto.visto-nota': 'From now on I\'ll only show you the new changes.',
  'progetto.visto-sintesi': 'seen',
  'progetto.fatto-titolo': 'Done. In plain words',
  'progetto.vedi-le-modifiche': 'See the changes',
  'progetto.modifiche-tratto': 'Changes · {da}–{a}',
  'progetto.provato-si': '**Yes**: the code of {nome} is the one tested at {ora} ({breve}).',
  'progetto.provato-no-cambiato': '<b>No</b>: the code of {nome} has changed since the last test ({ora}).',
  'progetto.provato-no-cambiato-alle': '<b>No</b>: the code of {nome} has changed since the last test ({ora}), most recently at {ultima}.',
  'progetto.provato-no-mai': '<b>No</b>: you haven\'t tested {nome} with Lode yet.',
  'progetto.provato-nota': 'I don\'t know who wrote the lines: I only know whether the current code went through a test.',
  'progetto.comando-manca': 'To test {nome}, {cosa} is missing',
  'progetto.comando-come': 'How do I test {nome}?',
  'progetto.comando-lancia': 'There are .in/.out tests now: to run the program I need a new yes.',
  'progetto.comando-cambiato': 'The project files have changed: the old command isn\'t enough any more.',
  'progetto.comando-userei': 'To test it I\'d use <code>{comando}</code>',
  'progetto.comando-nota': 'I only run the command you confirm in the system window, never one suggested by an agent. It\'s not a sandbox: the program runs on your computer, just like from the terminal, and it can write files in your folder.',
  'progetto.riprova': 'Try again',
  'progetto.usa-questo': 'Use this',
  'progetto.scrivo-io': 'I\'ll write the command',
  'progetto.cambia': 'Change',
  'progetto.comando-aria': 'Command to test',
  'progetto.usa-questo-comando': 'Use this command',
  'progetto.non-eseguo': 'I won\'t run anything.',
  'progetto.non-confermato': 'You didn\'t confirm the command.',
  'progetto.comando-confermato': 'Command confirmed.',
  'progetto.comando-confermato-nota': 'I\'ll always use it for this project, until the files change shape.',
  'progetto.comando-confermato-sintesi': 'command confirmed',
  'progetto.uscita-caso': '— test {caso} —',
  'progetto.non-seguo-questo': 'I\'m not following this project.',
  'progetto.sto-gia-provando': 'I\'m already testing this project: hang on.',
  'progetto.niente': 'nothing',
  'progetto.riga-vuota': 'an empty line',
  'progetto.caso-ok': 'Test {caso}',
  'progetto.caso-ok-codice': 'Test {caso} · passes, but the program exits with code {codice}',
  'progetto.caso-errore': 'Test {caso}: {errore}',
  'progetto.caso-scaduto': 'Test {caso}: didn\'t finish in time. A loop that never stops, or is the program waiting for more input?',
  'progetto.caso-troncato': 'Test {caso}: it printed too much (over 200 KB) and I stopped it.',
  'progetto.caso-crash': 'Test {caso}: the program stopped with an error.',
  'progetto.caso-crash-segnale': 'Test {caso}: the program stopped with an error ({segnale}).',
  'progetto.caso-crash-codice': 'Test {caso}: the program stopped with an error (code {codice}).',
  'progetto.caso-diverso': 'Test {caso} · line {riga}: expected {atteso}, got {ottenuto}',
  'progetto.sintassi-ok': 'The syntax is fine',
  'progetto.sintassi-errore': 'Syntax error',
  'progetto.make-ok': 'make worked',
  'progetto.make-errore': 'make failed',
  'progetto.compila': 'It compiles',
  'progetto.non-compila': 'It doesn\'t compile',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si}, and it passes the test.', other: '{si}, and it passes all {n} tests.' },
  'progetto.esito-senza-prove': '{si}. There are no .in/.out tests: I didn\'t run the program.',
  'progetto.esito-non-passano': { one: '{n} test out of {tot} fails.', other: '{n} tests out of {tot} fail.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no}: {file}.',
  'progetto.non-compila-file-riga': '{no}: {file}, line {riga}.',
  'progetto.non-partita': 'The test didn\'t start.',
  'progetto.passano': 'Passing: {nomi}',
  'progetto.saltate': { one: '{n} test skipped: {motivo}.', other: '{n} tests skipped: {motivo}.' },
  'progetto.avvisi': { one: '{n} compiler warning.', other: '{n} compiler warnings.' },
  'progetto.cambiato-durante': '<b>The code changed while I was testing: shall I run it again?</b>',
  'progetto.rifai': 'Run again',
  'progetto.prova-di-nuovo': 'Test again',
  'progetto.nota-cose-nuove': 'From Lode\'s dictionary: standard library functions only. It doesn\'t see ideas, only names.',
  'progetto.file-riga': '{file}, line {riga}',
  'progetto.domanda-orale': 'Oral exam question:',
  'progetto.risposta': 'Answer',
  'progetto.cose-nuove': 'New things: {nomi}',
  'progetto.mettila-nel-ripasso': 'Add it to review',
  'progetto.la-so-gia': 'I know it already',
  'progetto.nel-ripasso': 'Added to review.',
  'progetto.la-sai-gia': 'you know it already',
};
