// Grading systems (English): system names, credits, final grade, mentions and classes (js/sistemi.js).
export default {
  'sistemi.scelta': 'Grading system',
  'sistemi.nome.it': 'Italy · 18–30 cum laude',
  'sistemi.nome.es': 'Spain · 0–10',
  'sistemi.nome.fr': 'France · 0–20',
  'sistemi.nome.de': 'Germany · 1.0–5.0',
  'sistemi.nome.pt': 'Portugal · 0–20',
  'sistemi.nome.br': 'Brazil · 0–10',
  'sistemi.nome.uk': 'United Kingdom · 0–100%',
  'sistemi.nome.us': 'United States · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'credits',
  'sistemi.crediti.uk': 'credits',
  'sistemi.crediti.us': 'credit hours',
  'sistemi.media': 'Average',
  'sistemi.ponderata': 'Weighted average',
  'sistemi.aritmetica': 'Simple average',
  'sistemi.finale.it': 'Graduation base (out of 110)',
  'sistemi.finale.es': 'Transcript average',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Final grade (Gesamtnote)',
  'sistemi.finale.pt': 'Final average',
  'sistemi.finale.br': 'Performance coefficient (CR)',
  'sistemi.finale.uk': 'Degree classification',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'no mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Fail',
  'sistemi.idoneo': 'pass',
  'sistemi.lode': '30 cum laude',
  'sistemi.matricula': 'Matrícula de Honor',
  'sistemi.sufficienza': 'Pass mark: {v}',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
