// «What does it print?», the exercise card (English).
export default {
  'stampa.titolo': 'What does it print?',
  'stampa.anteprima': 'What does {cosa} print?',
  'stampa.risposta-assente': 'That answer isn\'t there.',
  'stampa.hai-scritto-altro': 'You wrote `{uscita}`: that\'s not what it prints.',
  'stampa.nessuna-risposta': 'No answer.',
  'stampa.aria-codice': '{lingua} code',
  'stampa.non-riesco': 'I can\'t get the {lingua} questions ready today. Try again in a bit.',
  'stampa.conto': '{i} of {n}',
  'stampa.scrivi-uscita': 'Type the exact output',
  'stampa.scegli-uscita': 'Pick the output · keys 1-4',
  'stampa.aria-campo': 'What the program prints',
  'stampa.segnaposto': 'Type what it prints',
  'stampa.controlla': 'Check <kbd>Enter</kbd>',
  'stampa.piu-righe': 'More than one line? Separate them with a space.',
  'stampa.aria-risposta': 'Answer {n}: {uscita}',
  'stampa.giusto': 'Right · worked out by Lode',
  'stampa.stampa-giusta': 'It prints <code>{uscita}</code>.',
  'stampa.avanti': 'Next <kbd>Enter</kbd>',
  'stampa.com-e-andata': 'See how it went <kbd>Enter</kbd>',
  'stampa.tutte-giuste': 'All right. Lode worked out the answers.',
  'stampa.da-rinforzare': 'Needs more work: {nomi}. Come back tomorrow.',
  'stampa.secondi': { one: '{n} second', other: '{n} seconds' },
  'stampa.ancora-una': 'One more',
  'stampa.sintesi': 'What does it print? {punti} out of {tot}',
};
