// Sync between computers (English): what is encrypted and what stays readable, the status line and the warnings
// (docs/SINCRONIZZAZIONE.md §10.7 and §12). The README says the same things: see js/sync-testi.js.
export default {
  'sync.cifrati': "Lode's data in the journal (exams, grades, cards and reviews, sessions, profile, settings): not the Obsidian pages Lode makes from it, listed below",
  'sync.in-chiaro': [
    'notes, lecture write-ups (“Sbobine”), Anki files, project diaries',
    'Orario.md with the rooms',
    "the pages Lode writes for Obsidian, made from that very data: Exams (grades, average, credits and hours studied per exam), Memory (study hours this month, what time of day you study, your streak, the definitions you got wrong and how often), Home (the next exam date, how many cards are due), Courses, Glossary",
    'file names, sizes and times (when you study)',
    'how many computers there are, how many files each one writes and how many actions are in each file (one file per day)',
    "the group file (salt and password check, when it was created and on which computer, the fingerprint of the earlier dati.json)",
    'when the password changed',
    'the minimal dati.json that says “Update Lode”',
  ],
  'sync.sul-computer': "On the computer, Lode's journal stays readable, protected only by your system account.",
  'sync.cronologia': "The cloud service's history keeps whatever was stored unencrypted before the password.",
  'sync.dimenticata': 'If you forget the password, nothing is lost: every computer has its data on disk. With “I forgot the password” you choose a new one, and the other computers will ask you for it.',
  'sync.nuova-password': 'Choose a new password. The other computers will ask you for it. No data is lost: every computer keeps its own on disk.',
  'sync.smetti': 'Lode will copy the vault to a folder outside {servizio} and use that one. The other computers keep syncing with each other. To stop everywhere, do it on every computer.',
  'sync.la-cartella-cloud': 'the cloud folder',
  'sync.prima': 'Before syncing, update Lode on all your computers.',
  'sync.sperimentale': "It's new and experimental: tested hard with a simulator of several computers and a nasty cloud, but not yet by lots of students. Before turning it on, Lode keeps a copy of everything: your current vault stays where it is, untouched, and Lode's data also goes into the “copie” folder in Lode's data. If something looks wrong, tell us on GitHub (Issues at W1kicartel/Lode).",
  // the status line
  'sync.spenta': 'Off · exams, grades and cards stay on this computer',
  'sync.fermo': "Lode's journal on this computer can't be read.",
  'sync.solo-qui': 'Only on this computer · not synced',
  'sync.la-tua-cartella': 'your cloud folder',
  'sync.stato-password': 'Paused: type the password to sync.',
  'sync.rigenerato-altra': 'Another computer chose a different password at the same moment: type that one.',
  'sync.rigenerato': 'The password changed on another computer: type the new one to sync.',
  'sync.sparito': "Lode's folder in the vault is gone: was it moved or deleted?",
  'sync.in-arrivo': 'Getting data from the other computers… ({dove})',
  'sync.da-migrare': 'Waiting for data from the cloud…',
  'sync.scrittura': "The disk is full (or can't be written to): the latest changes are waiting and I'll retry on my own.",
  'sync.versione': 'Synced with {dove} · another computer has a newer Lode: update this one',
  'sync.in-pari': 'Synced with {dove}',
  'sync.in-pari-cifrato': 'Synced with {dove} · encrypted',
  'sync.in-pari-ora': 'Synced with {dove} · checked at {ora}',
  'sync.in-pari-cifrato-ora': 'Synced with {dove} · encrypted · checked at {ora}',
  'sync.altro-stato': 'Sync: {stato}',
  'sync.in-avvio': 'starting',
  // the warnings
  'sync.avviso-clone': 'This computer looks like a copy of another one: from now on it has a new name. Nothing was lost.',
  'sync.avviso-orologio': "Another computer's clock seems far ahead: check the date and time.",
  'sync.avviso-rovinato-mio': "A Lode file from this computer in the cloud folder was damaged or tampered with: I set it aside and rebuilt it from the journal.",
  'sync.avviso-rovinato-altro': "A Lode file from another computer is damaged or tampered with: I'll skip it until it's readable again.",
  'sync.avviso-scrittura': "The disk is full or can't be written to: the latest changes aren't in the journal yet. I retry every round and when you close Lode.",
  'sync.avviso-recupero': "The journal couldn't be written: the changes from that moment are in a separate file in Lode's data folder.",
  'sync.avviso-portachiavi': "The Keychain didn't hand over Lode's password (permission denied, or Lode was updated): type it again.",
  'sync.avviso-gruppi-doppi': "There are two Lode groups in the cloud folder, one encrypted and one not: I won't merge them on my own.",
  'sync.avviso-lode-vecchia': "An old version of Lode wrote data to .lode/dati.json: update it. That data doesn't come in by itself: a copy is in Lode's data folder, and you can import the new records with “Import the additions”.",
  'sync.avviso-altra-password': 'Another computer chose a different password at the same moment: type that one.',
  'sync.avviso-manomesso': "Lode's group file in the cloud folder was changed from outside (it doesn't match the password): I won't use it. Check the cloud folder.",
  'sync.avviso-gruppo-chiaro': "Lode's group file says “no password” but the other computers' data is encrypted: has it been tampered with? I won't publish anything until it's fixed.",
  'sync.avviso-parametri': 'This vault was protected by a newer Lode: update this one.',
};
