// Texts of the pages Lode writes in the vault for the student (English): Home, Exams, Glossary, the course pages and
// Memory. Note, folder, section and key names that the code reads back are not here: they stay in the code (they will
// become the NOMI table).
export default {
  // memory
  'vault.prop-gioco': 'games',
  'vault.prop-ripasso': 'card reviews',
  'vault.prop-stelle': 'rereading the ★',
  'vault.prop-orale': 'quick questions',
  'vault.prop-focus': 'focus',
  'vault.prop-stampa': 'what does it print',
  'vault.prop-voce': '{nome} ({si} of {tot})',
  'vault.memoria-proposte': "Of Lode's suggestions, you mostly accept: {elenco}.",
  'vault.memoria-titolo': 'What I know about you',
  'vault.memoria-commento': 'Lode writes this note. You can read it and correct it too: I read the “{sezione}” section every time I use the AI.',
  'vault.titolo-in-breve': 'In short',
  'vault.memoria-lezioni': { one: '{n} lecture with notes', other: '{n} lectures with notes' },
  'vault.memoria-definizioni': { one: '{n} definition', other: '{n} definitions' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni}: **{sicure} solid**, {deboli} to strengthen, {mai} not played yet.',
  'vault.memoria-serie': { one: 'Study streak: {n} day in a row. This month: {h} h.', other: 'Study streak: {n} days in a row. This month: {h} h.' },
  'vault.memoria-fascia': 'You mostly study in the **{fascia}**.',
  'vault.fascia-mattina': 'morning',
  'vault.fascia-pomeriggio': 'afternoon',
  'vault.fascia-sera': 'evening',
  'vault.titolo-da-rinforzare': 'To strengthen',
  'vault.sbagliata': { one: 'wrong {n} time out of {tot}', other: 'wrong {n} times out of {tot}' },
  'vault.niente-per-ora': 'Nothing, for now.',
  'vault.titolo-sicure': 'Solid',
  'vault.sicure-vuoto': 'None yet: play a few rounds.',
  'vault.ancora-nessuna': 'None yet.',
  'vault.note-commento': 'Write here how you want to be helped: “explain with practical examples”, “I\'m dyslexic, short sentences”, “the Calculus oral is with Rossi, very theoretical”.',
  // Home
  'vault.home-carte': '{n} cards to review',
  'vault.alias-memoria': 'What Lode knows about me',
  'vault.alias-benvenuto': 'How it works',
  'vault.titolo-oggi': 'Today',
  'vault.aula': 'room {aula}',
  'vault.niente-lezioni-oggi': 'No lectures today.',
  'vault.titolo-corsi': 'Courses',
  'vault.n-lezioni': { one: '{n} lecture', other: '{n} lectures' },
  'vault.idoneo': 'passed',
  'vault.voto-e-lode': '{voto} cum laude',
  'vault.appello': 'exam {data}',
  'vault.corsi-vuoto': 'Add your timetable from the bar: “lecture calculus 2 Monday 9-11 room 7”.',
  'vault.titolo-ultime-lezioni': 'Latest lectures',
  'vault.definizioni-n': '{n} definitions',
  'vault.titolo-carriera': 'Degree',
  'vault.carriera': 'Average **{media}** · starting graduation mark **{base}**/110 · {cfu} of {tot} credits → {esami}',
  // Exams
  'vault.titolo-prossimi-appelli': 'Upcoming exams',
  'vault.tabella-appelli': '| Exam | Date | In | Credits | Hours studied |',
  'vault.ore-di': '{fatte} of {tot} h',
  'vault.nessun-appello': 'No exam dates yet.',
  'vault.senza-data': 'No date: {elenco}.',
  'vault.titolo-libretto': 'Grades',
  'vault.tabella-libretto': '| Exam | Credits | Grade | Date |',
  'vault.voto-l': '{voto}L',
  'vault.libretto-piede': 'Weighted average **{media}** · starting graduation mark **{base}**/110 · {cfu} of {tot} credits',
  'vault.libretto-vuoto': 'No exams taken yet.',
  // Glossary
  'vault.n-definizioni': { one: '{n} definition', other: '{n} definitions' },
  'vault.da-rinforzare': '*to strengthen*',
  'vault.glossario-vuoto': 'Definitions from your lectures show up here, in alphabetical order, split by course.',
  // the course page
  'vault.corso-cfu': '**{cfu} credits**',
  'vault.corso-voto': 'grade {voto}',
  'vault.corso-voto-lode': 'grade {voto} cum laude',
  'vault.corso-appello': 'exam on **{data}** (in {n} days) · {fatte} of {tot} h studied',
  'vault.corso-lezioni': 'Lectures: {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} room {aula}',
  'vault.lezioni-vuoto': 'None yet: the first one appears when you note something down in class.',
};
