// Vault names (js/nomi.js), English: folders, notes, sections and words Lode writes into a new vault and reads back.
export default {
  // cartelle (create una volta, alla nascita del vault: poi restano quelle)
  'vaultnomi.cartella-lezioni': 'Lectures',
  'vaultnomi.cartella-corsi': 'Courses',
  'vaultnomi.cartella-sbobine': 'Transcripts',
  'vaultnomi.cartella-anki': 'Anki',
  'vaultnomi.cartella-allegati': 'Attachments',
  'vaultnomi.cartella-materiali': 'Materials',
  'vaultnomi.cartella-progetti': 'Projects',
  'vaultnomi.cartella-modelli': 'Templates',
  'vaultnomi.cartella-inbox': 'Inbox',
  // i «corsi» che Lode inventa quando non ce n'è uno (diventano cartelle e note)
  'vaultnomi.corso-sparsi': 'Loose notes',
  'vaultnomi.corso-videolezioni': 'Video lectures',
  'vaultnomi.corso-varie': 'Misc',
  // note (senza «.md»)
  'vaultnomi.nota-home': 'Home',
  'vaultnomi.nota-orario': 'Timetable',
  'vaultnomi.nota-esami': 'Exams',
  'vaultnomi.nota-glossario': 'Glossary',
  'vaultnomi.nota-benvenuto': 'Welcome',
  'vaultnomi.nota-memoria': 'Memory',
  'vaultnomi.nota-tasca': 'Pocket review',
  'vaultnomi.modello-lezione': 'Lecture',
  'vaultnomi.modello-esame': 'Exam',
  'vaultnomi.modello-ripasso': 'Review',
  // titoli delle sezioni che Lode scrive e rilegge
  'vaultnomi.sezione-appunti': 'Notes',
  'vaultnomi.sezione-stella': '★ For the exam',
  'vaultnomi.sezione-definizioni': 'Definitions',
  'vaultnomi.sezione-domande': 'Questions for the professor',
  'vaultnomi.sezione-trascrizione': 'Transcript',
  'vaultnomi.sezione-riordinati': 'Notes tidied up by Lode',
  'vaultnomi.titolo-note-per-lode': 'Notes for Lode',
  'vaultnomi.titolo-cosa-ho-capito': 'What I understood',
  'vaultnomi.titolo-cosa-so-davvero': 'What I really know',
  'vaultnomi.titolo-informatica': 'Computer science',
  'vaultnomi.titolo-ripasso-in-tasca': 'Pocket review',
  'vaultnomi.titolo-orario': 'Lecture timetable',
  'vaultnomi.titolo-lezioni': 'Lectures',
  'vaultnomi.titolo-stelle-ultime': '★ For the exam, latest',
  // il ripasso in tasca: il titolo della risposta e le due caselle (il giro le rilegge)
  'vaultnomi.parola-risposta': 'Answer',
  'vaultnomi.parola-sapevo': 'knew it',
  'vaultnomi.parola-non-sapevo': 'didn\'t know',
  // la nota dell'orario: colonne, giorni (domenica per primo) e la riga che spiega
  'vaultnomi.orario-colonne': ['Course', 'Days', 'Start', 'End', 'Room'],
  'vaultnomi.giorni-brevi': ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
  'vaultnomi.orario-spiega': 'Lode reads it to know when you are in class. Edit it here or from the bar (“lecture calculus 2 monday and wednesday 9-11 room 7”).',
  // i commenti dentro le note nuove
  'vaultnomi.commento-definizioni': 'One per line: - **Term**: definition. Lode turns them into memory games and cards.',
  'vaultnomi.commento-corso': 'Write above or below as you like: Lode\'s box (lectures, ★, exam date) updates itself and Lode never touches the rest.',
  'vaultnomi.commento-cosa-ho-capito': 'This part is yours: Lode never touches it. What you understood today, what still doesn\'t add up.',
  'vaultnomi.segnalibro-memoria': 'What Lode knows about me',
  // i nomi dei file che Lode compone (sbobine, materiali)
  'vaultnomi.file-sbobina': '{data} {corso} · transcript',
  'vaultnomi.file-sbobina-di': '{data} {corso} · transcript by {da}',
  'vaultnomi.materiale-originale': 'original file',
  // i modelli di Obsidian e le note che nascono col vault
  'vaultnomi.esame-programma': 'Syllabus',
  'vaultnomi.esame-domande': 'Questions they always ask',
  'vaultnomi.esame-domande-commento': 'The ones you hear from classmates or find in past papers. Lode uses them to quiz you.',
  'vaultnomi.esame-esercizi': 'Typical exercises',
  'vaultnomi.esame-manca': 'What I\'m missing',
  'vaultnomi.ripasso-tre-righe': 'In three lines',
  'vaultnomi.ripasso-commento-definizioni': '- **Term**: definition. They end up in Lode\'s games.',
  'vaultnomi.ripasso-collegamenti': 'Links',
  'vaultnomi.ripasso-commento-collegamenti': 'Related lectures and concepts: [[...]]',
  'vaultnomi.memoria-titolo': 'What I know about you',
  'vaultnomi.memoria-commento': 'Lode writes this note after every game. The “{sezione}” section stays yours: I read it every time I use the AI.',
  'vaultnomi.memoria-in-breve': 'In short',
  'vaultnomi.memoria-ancora-niente': 'Nothing yet: jot down a few definitions in class and play a round.',
  'vaultnomi.memoria-note-commento': 'Write here how you want to be helped: “explain with practical examples”, “short sentences”, “the Calculus oral exam is very theoretical”.',
  'vaultnomi.parola-corso': 'course',
  'vaultnomi.benvenuto-firma': 'was set up by **Lode**',
  'vaultnomi.benvenuto-testo': '# Welcome to your vault\n\nThis vault {firma}, the assistant that lives at the top of your screen. It\'s a normal Obsidian vault: the notes are yours, in Markdown, and they stay on this computer.\n\n## How they work together\n- **In class** Lode knows when you\'re in a lecture (from the [[{orario}]]) and keeps the lecture note ready in `{lezioni}/<{corso}>/`. From the bar you jot down on the fly:\n  - **{stella}** (⌃⌥S): what the professor said will be asked;\n  - **Definition** (⌃⌥D): “term: definition”;\n  - **Question** (⌃⌥Q): to ask the professor.\n- **Your notes** you write here, in Obsidian, as always. Lode finds on its own the definitions you put in the “{definizioni}” section (`- **Term**: definition`) or write as `Term :: definition`.\n- **At home** the bar offers you a two-minute game on the definitions of the last lecture, right when they\'re about to slip away.\n- **[[{memoria}]]** (in `{lode}/`) is what Lode has learned about you: solid definitions, ones to reinforce, how you study. In the “{notePerLode}” section you can tell it how you want to be helped.\n\n## Shortcuts\n| | Mac | Windows |\n|---|---|---|\n| Open Lode and type | ⌥ Space | Ctrl ⇧ Space |\n| {stella} | ⌃⌥ S | Ctrl Alt S |\n| Definition | ⌃⌥ D | Ctrl Alt D |\n| Question for the professor | ⌃⌥ Q | Ctrl Alt Q |\n| Memory game | ⌃⌥ G | Ctrl Alt G |\n',
  // frasi della barra che citano un nome del vault: il nome arriva dal vault, non dalla lingua della barra
  'vaultnomi.frase-orario-nel-vault': 'Your timetable is also in the vault, in “{nota}”: you can change it from Obsidian.',
  'vaultnomi.frase-nella-cartella': 'It\'s in the {cartella} folder of your vault.',
  'vaultnomi.frase-riordinati-nota': 'They go into the note, under “{sezione}”, below the transcript (which stays). {motore} wrote them: read them over.',
};
