// La barra (js/lode.js, prima parte: pillola, pannello, home, strumenti, ripasso, orario, trascrizione, file), in italiano.
export default {
  // i tasti per parlare e i numeri scritti in lettere («Tre carte da ripassare»)
  'barra1.tasti-mac': '⌥ Spazio',
  'barra1.tasti': 'Ctrl ⇧ Spazio',
  'barra1.numeri': ['Nessuna', 'Una', 'Due', 'Tre', 'Quattro', 'Cinque', 'Sei', 'Sette', 'Otto', 'Nove', 'Dieci'],
  // il saluto e la frase in cima al pannello
  'barra1.saluto-notte': 'Ancora sveglio',
  'barra1.saluto-mattina': 'Buongiorno',
  'barra1.saluto-pomeriggio': 'Buon pomeriggio',
  'barra1.saluto-sera': 'Buonasera',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': "Oggi c'è {nome}. In bocca al lupo.",
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} carta da ripassare.', other: '{quante} carte da ripassare.' },
  'barra1.niente-in-sospeso': 'Niente in sospeso oggi.',
  'barra1.dimmi-esame': 'Dimmi il tuo prossimo esame e preparo il piano.',
  // la conchiglia: campo, piede, file trascinati
  'barra1.aria-lode': 'Lode, assistente di studio',
  'barra1.aria-torna-home': 'Torna alla home di Lode',
  'barra1.indietro': 'Indietro',
  'barra1.aria-campo': 'Chiedi o scrivi un comando',
  'barra1.campo': 'Chiedi o scrivi un comando…',
  'barra1.ti-ascolto': 'Ti ascolto',
  'barra1.esc-annulla': 'Esc annulla',
  'barra1.un-attimo': 'Un attimo…',
  'barra1.aria-parla': 'Parla (oppure tieni premuto {tasti})',
  'barra1.tieni-premuto': 'Tieni premuto per parlare <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'I dati restano su questo computer',
  'barra1.lascia-file': 'Lascia qui il file',
  'barra1.lascia-file-cosa': 'PDF, slide, appunti, foto della lavagna: Lode ne fa carte del ripasso',
  'barra1.dopo': 'Dopo',
  // «Oggi»: le righe della home
  'barra1.di-stamattina': 'di stamattina',
  'barra1.di-oggi': 'di oggi',
  'barra1.di-ieri': 'di ieri',
  'barra1.di-giorno': 'di {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} definizione di {corso} {quando}', other: '{n} definizioni di {corso} {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} definizione delle ultime lezioni', other: '{n} definizioni delle ultime lezioni' },
  'barra1.sync-bloccata': 'Lode funziona con i dati di questo computer: le modifiche aspettano nel diario.',
  'barra1.sblocca': 'Sblocca',
  'barra1.sync-sparita': "La cartella di Lode nel vault non c'è più",
  'barra1.sync-sparita-dett': 'È stata spostata o cancellata? I dati di questo computer sono al sicuro nel suo diario.',
  'barra1.vedi': 'Vedi',
  'barra1.sync-spostamento': 'Lo spostamento nella cartella cloud si è interrotto',
  'barra1.sync-spostamento-dett': 'Il vault di prima è intatto: riprendo da dove ero rimasto.',
  'barra1.riprendi': 'Riprendi',
  'barra1.detto-sincronizza': 'Sincronizza fra i computer',
  'barra1.dati-altrove': 'Questo vault si sincronizza con Lode su un altro computer',
  'barra1.dati-altrove-dett': 'I dati sono nel diario di Lode 2: scegli «Uso già Lode su un altro computer» per vederli qui. Le modifiche di adesso vanno in un file a parte, non sopra i dati.',
  'barra1.uso-gia-lode': 'Uso già Lode',
  'barra1.detto-uso-gia-lode': 'Uso già Lode su un altro computer',
  'barra1.dati-fermo': 'Il diario di Lode su questo computer non si legge',
  'barra1.dati-fermo-dett': 'Niente è stato cancellato: la cartella dei dati di Lode non risponde (disco pieno o guasto?).',
  'barra1.riprova': 'Riprova',
  'barra1.dati-illeggibili': 'Non riesco a leggere i tuoi dati',
  'barra1.dati-illeggibili-dett': 'Esami, voti e carte sono al sicuro, ma la cartella non risponde (OneDrive offline o file bloccato). Le modifiche di adesso vanno in un file a parte; riprovo da solo.',
  'barra1.lezione-alle': '{corso} alle {ora}',
  'barra1.lezione-aula-tra': 'Aula {aula} · tra {n} min',
  'barra1.lezione-tra': 'tra {n} min',
  'barra1.appunti': 'Appunti',
  'barra1.orario': 'Orario',
  'barra1.completa-lode': 'Completa Lode',
  'barra1.completa-tutti-e-due': 'Obsidian e il cervello locale: un clic, gratis',
  'barra1.completa-obsidian': 'Obsidian: un clic, gratis',
  'barra1.completa-cervello': 'il cervello locale: un clic, gratis',
  'barra1.prepara': 'Prepara',
  'barra1.detto-prepara-lode': 'Prepara Lode',
  'barra1.chiudi-lezione-di': 'Chiudi la lezione di {corso}',
  'barra1.chiudi-lezione-dett': { one: '{n} parola di appunti · estraggo definizioni e ★', other: '{n} parole di appunti · estraggo definizioni e ★' },
  'barra1.chiudi': 'Chiudi',
  'barra1.detto-chiudi-lezione': 'Chiudi lezione',
  'barra1.gioco-due-minuti': 'Gioco da due minuti',
  'barra1.gioca': 'Gioca',
  'barra1.esame-ore-oggi': '{data} · {ore} h oggi per stare in pari',
  'barra1.esame-in-pari': '{data} · oggi sei in pari',
  'barra1.focus': 'Focus',
  'barra1.ripasso': 'Ripasso',
  'barra1.ripasso-carte-min': { one: '{n} carta · circa {min} min', other: '{n} carte · circa {min} min' },
  'barra1.inizia': 'Inizia',
  'barra1.studio-oggi': '{ore} di studio oggi',
  'barra1.non-hai-studiato': 'Oggi non hai ancora studiato',
  'barra1.giorni-di-fila': { one: '{n} giorno di fila', other: '{n} giorni di fila' },
  'barra1.bastano-25': 'Bastano 25 minuti per iniziare una serie',
  'barra1.libretto': 'Libretto',
  // in aula, Ripeti, la trascrizione, la home
  'barra1.in-aula': 'In aula · {corso}',
  'barra1.aula-finisce-tra': 'aula {aula} · finisce tra {n} min',
  'barra1.finisce-tra': 'finisce tra {n} min',
  'barra1.cattura-stella': '★ Da esame',
  'barra1.cattura-definizione': 'Definizione',
  'barra1.cattura-domanda': 'Domanda',
  'barra1.cose-segnate': { one: '{quante} cosa segnata da esame oggi.', other: '{quante} cose segnate da esame oggi.' },
  'barra1.ripeti-attivo-memoria': 'Ripeti attivo · solo in memoria, mai su disco',
  'barra1.ripeti': 'Ripeti',
  'barra1.spegni': 'Spegni',
  'barra1.ripeti-spento-invito': '<b>Ripeti 60 s</b> · ti sei perso una frase? Lode te la ripete. Niente viene salvato.',
  'barra1.trascrivi-lezione': 'Trascrivi la lezione',
  'barra1.trascrivi-lezione-dett': 'Tutto quello che dice il prof, formule comprese, nella nota Obsidian · {tasti}',
  'barra1.trascrizione-in-pausa': { one: 'In pausa · {min} min · {parole} parola', other: 'In pausa · {min} min · {parole} parole' },
  'barra1.trascrizione-in-corso': { one: 'Trascrivo · {min} min · {parole} parola', other: 'Trascrivo · {min} min · {parole} parole' },
  'barra1.prima-riga': 'Ascolto: la prima riga arriva fra una ventina di secondi.',
  'barra1.pausa': 'Pausa',
  'barra1.fine': 'Fine',
  'barra1.oggi': 'Oggi',
  'barra1.cfu-di': '{fatti} di {tot} CFU',
  'barra1.inizia-da-qui': 'Inizia da qui',
  'barra1.inizia-da-qui-dett': 'Scrivi «lezione analisi 2 lunedì 9-11 aula 7», oppure prova i dati di esempio',
  'barra1.esempio': 'Esempio',
  // gli strumenti e la testa del pannello
  'barra1.strumento-gioco': 'Gioco',
  'barra1.strumento-codice': 'Codice',
  'barra1.strumento-note': 'Note',
  'barra1.strumento-interrogami': 'Interrogami',
  'barra1.strumento-esami': 'Esami',
  'barra1.sei-a-lezione': 'Sei a lezione di {corso}. Prendi appunti tranquillo: ci penso io a non perdere niente.',
  'barra1.testa-media': 'media {media}',
  'barra1.testa-serie': { one: 'serie di {n} giorno', other: 'serie di {n} giorni' },
  // la pillola
  'barra1.ripeti-attivo-titolo': "Ripeti attivo: l'ultimo minuto e mezzo, solo in memoria",
  'barra1.in-pausa': 'in pausa',
  'barra1.pausa-minuscolo': 'pausa',
  'barra1.aria-timer': '{cosa}: mancano {resta}',
  'barra1.prova-generale': 'Prova generale',
  'barra1.focus-su': 'Focus su {nome}',
  'barra1.aria-ripeti-acceso': '. Ripeti: microfono acceso',
  'barra1.pillola-trascrizione-in-pausa': { one: 'trascrizione in pausa · {parole} parola', other: 'trascrizione in pausa · {parole} parole' },
  'barra1.pillola-trascrivo': { one: 'trascrivo · {parole} parola', other: 'trascrivo · {parole} parole' },
  'barra1.fine-tra': 'fine tra {n} min',
  'barra1.pillola-aula-tra': 'aula {aula} · tra {n} min',
  'barra1.microfono-acceso': 'microfono acceso',
  'barra1.due-minuti': '2 minuti',
  'barra1.pillola-tra-giorni': 'tra {n} g',
  // in italiano la pillola dice «carte» anche con una carta sola (com'era prima)
  'barra1.pillola-carte': { one: '{n} carte', other: '{n} carte' },
  'barra1.pillola-da-ripassare': { one: 'carte da ripassare', other: 'carte da ripassare' },
  'barra1.passa-qui-sopra': 'passa qui sopra',
  'barra1.aria-pillola': 'Lode: {testo}{ripeti}. Passa sopra o premi {tasti}.',
  // la conversazione, «Fatto.», «Conferma / Annulla»
  'barra1.altre-righe': { one: '{n} riga', other: '{n} righe' },
  'barra1.altro': 'altro',
  'barra1.fatto': 'Fatto.',
  'barra1.annulla': 'Annulla',
  'barra1.disfa': 'Annulla',
  'barra1.annullato-minuscolo': 'annullato',
  'barra1.disfatto': 'annullato',
  'barra1.confermi': 'Confermi?',
  'barra1.conferma': 'Conferma',
  'barra1.scrivi-si': 'Puoi anche scrivere «sì».',
  'barra1.annullato': 'Annullato.',
  'barra1.niente-cambiato': 'Non ho cambiato niente.',
  // Focus
  'barra1.durata': 'Durata',
  'barra1.min': 'min',
  'barra1.su-che-cosa': 'Su che cosa',
  'barra1.studio-libero': 'Studio libero',
  'barra1.pausa-alla-fine': "Pausa di {n} minuti alla fine. Le ore contano nel piano dell'esame.",
  'barra1.sintesi-focus': 'focus',
  'barra1.focus-di-min': 'Focus di {min} minuti.',
  'barra1.focus-di-min-su': 'Focus di {min} minuti su {nome}.',
  'barra1.ci-vediamo': 'Ci vediamo alla pausa.',
  'barra1.sintesi-focus-min': 'focus {min} min',
  // Libretto ed «e se prendo…»
  'barra1.media-ponderata': 'Media ponderata',
  'barra1.aritmetica-esami': { one: 'aritmetica {media} · {n} esame', other: 'aritmetica {media} · {n} esami' },
  'barra1.nessun-voto': 'ancora nessun voto',
  'barra1.base-di-laurea': 'Base di laurea',
  'barra1.serve-gia': 'Per partire da <b>{obiettivo}</b> ti basta passare gli esami che restano.',
  'barra1.serve-media': 'Per partire da <b>{obiettivo}</b> ti serve <b>{voto}</b> di media nei {cfu} CFU che mancano.',
  'barra1.serve-impossibile': 'Partire da <b>{obiettivo}</b> non è più possibile: punta a {punta}.',
  'barra1.e-se': 'E se…',
  'barra1.esame': 'Esame',
  'barra1.voto': 'Voto',
  'barra1.simula-esito': 'Media <b>{media}</b> <span class="{classe}">{delta}</span> · base <b>{base}</b>',
  'barra1.sintesi-media-base': 'media {media}, base {base}',
  'barra1.sintesi-libretto-vuoto': 'libretto vuoto',
  'barra1.simula-non-trovo': 'Non trovo **{nome}** tra i tuoi esami. Aggiungilo con «esame {nome} 6 cfu».',
  'barra1.simula-primo': 'Con {voto} in **{nome}** la tua media partirebbe da **{voto}**: base **{base}**.',
  'barra1.simula-primo-lode': 'Con {voto} e lode in **{nome}** la tua media partirebbe da **{voto}**: base **{base}**.',
  'barra1.simula': 'Con **{voto}** in {nome} la media passa da {prima} a **{dopo}** ({delta}): base di laurea **{base}**.',
  'barra1.simula-lode': 'Con **{voto} e lode** in {nome} la media passa da {prima} a **{dopo}** ({delta}): base di laurea **{base}**.',
  'barra1.sintesi-media': 'media {media}',
  // Esami
  'barra1.incolla-programma': 'Incolla il programma: ti preparo il piano per argomenti',
  'barra1.giorno-cuscinetto': 'giorno cuscinetto',
  'barra1.ripasso-generale': 'ripasso generale',
  'barra1.niente-di-nuovo': 'niente di nuovo',
  'barra1.pronto': '{n}% pronto',
  'barra1.prossimi-appelli': 'Prossimi appelli · {n}',
  'barra1.esame-riga': '{data} · {cfu} CFU · {fatte} di {tot} h',
  'barra1.ore-oggi': '{ore} h oggi',
  'barra1.giorni-parola': { one: 'giorno', other: 'giorni' },
  'barra1.nessun-appello': 'Nessun appello in calendario.',
  'barra1.senza-data': 'Senza data: {nomi}.',
  'barra1.nuovo-esame': 'Nuovo esame',
  'barra1.nome-esame': "Nome dell'esame",
  'barra1.cfu': 'CFU',
  'barra1.data-appello': "Data dell'appello",
  'barra1.aggiungi': 'Aggiungi',
  'barra1.programma-di': 'Programma di {nome}',
  'barra1.esame-aggiunto': '{nome} aggiunto.',
  'barra1.senza-data-nota': 'senza data',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': 'nessun appello',
  // Ripasso
  'barra1.ripasso-di': 'Ripasso · {nome}',
  'barra1.niente-da-ripassare': 'Niente da ripassare oggi. La prossima carta torna {quando}.',
  'barra1.nessuna-carta': 'Ancora nessuna carta. Scrivi «carta: domanda = risposta», oppure trascina qui un PDF.',
  'barra1.risposta': 'Risposta',
  'barra1.aggiungi-carta': 'Aggiungi carta',
  'barra1.carta-aggiunta': 'Carta aggiunta.',
  'barra1.torna-oggi': 'Torna oggi stesso nel ripasso.',
  'barra1.sintesi-niente-da-ripassare': 'niente da ripassare',
  'barra1.mostra-risposta': 'Mostra risposta <kbd>Spazio</kbd>',
  'barra1.x-di-y': '{x} di {y}',
  'barra1.ripasso-finito': { one: 'Ripasso finito: {n} carta in {min} min.', other: 'Ripasso finito: {n} carte in {min} min.' },
  'barra1.difficili-domani': 'Le difficili tornano domani.',
  'barra1.sintesi-carte-ripassate': { one: '{n} carte ripassate', other: '{n} carte ripassate' },
  'barra1.sintesi-ripasso-di': { one: 'ripasso di {n} carte', other: 'ripasso di {n} carte' },
  // i comandi da provare
  'barra1.prova-a-scrivere': 'Prova a scrivere',
  'barra1.aiuto-senza-ai': 'Con il cervello locale (gratis) o la tua AI (scrivi «AI») puoi anche chiedere spiegazioni, creare carte dai PDF e farti interrogare.',
  'barra1.sintesi-comandi': 'comandi',
  // Orario
  'barra1.orario-lezioni': { one: 'Orario · {n} lezione a settimana', other: 'Orario · {n} lezioni a settimana' },
  'barra1.corso-aula': '{corso} · aula {aula}',
  'barra1.punto-aula': ' · aula {aula}',
  'barra1.togli': 'Togli {nome}',
  'barra1.corso': 'Corso',
  'barra1.giorni': 'Giorni',
  'barra1.inizio': 'Inizio',
  'barra1.aula': 'Aula',
  'barra1.orario-oppure-scrivi': 'Oppure scrivi: «lezione analisi 2 lunedì e mercoledì 9-11 aula 7».',
  'barra1.in-orario': '{corso} in orario.',
  'barra1.sintesi-lezioni-settimana': { one: '{n} lezioni a settimana', other: '{n} lezioni a settimana' },
  // il piano per chi lavora
  'barra1.ore-regola': { one: '{n} ora', other: '{n} ore' },
  'barra1.la-tua-settimana': 'La tua settimana',
  'barra1.detto-piano-settimana': 'Piano della settimana',
  'barra1.lavori': 'Lavori {turni}.',
  'barra1.lavori-nota': "Lo tolgo dalle ore di studio, con mezz'ora per il viaggio. Nei giorni di lavoro studi al massimo {tetto}: lo cambi con «nei giorni di lavoro studio al massimo {altro} ore».",
  'barra1.turni-cambiati': 'Turni cambiati.',
  'barra1.turni-salvati': 'Turni salvati.',
  'barra1.sintesi-lavoro': 'lavoro {turni}',
  'barra1.turni-tolti': 'Turni tolti.',
  'barra1.turni-tolti-nota': 'Il piano torna a contare tutta la tua giornata di studio.',
  'barra1.giorno-non-lavori': '{giorno} non lavori.',
  'barra1.ore-libere': 'Quelle ore tornano libere per studiare.',
  'barra1.giorno-lavori-anche': '{giorno} lavori anche {da}–{a}.',
  'barra1.solo-quel-giorno': 'Solo quel giorno: lo tolgo dalle ore di studio.',
  'barra1.tetto': 'Nei giorni di lavoro studi al massimo {tetto}.',
  'barra1.tetto-nota': 'Il piano si rifà con questo tetto.',
  'barra1.studi-dalle': 'Studi dalle {da} alle {a}.',
  'barra1.studi-dalle-nota': 'Il piano usa solo queste ore, meno lezioni e lavoro.',
  'barra1.togli-scelta': 'Togli: {scelta}',
  'barra1.niente-nel-piano': 'niente nel piano',
  'barra1.settimana-lavori': "Lavori {turni}: lo tolgo dalle ore di studio, con mezz'ora per il viaggio. Nei giorni di lavoro studi al massimo {tetto}.",
  'barra1.settimana-se-lavori': 'Se lavori, scrivimelo: «lavoro lunedì mercoledì venerdì 14-19».',
  'barra1.settimana-un-esame': 'Con un esame solo e senza lavoro, il piano è quello del programma.',
  'barra1.settimana-stime': 'Le ore sono stime: un argomento nuovo circa 1 h, un ripasso circa 30 min.',
  'barra1.sintesi-la-tua-settimana': 'la tua settimana',
  // la cattura veloce in aula
  'barra1.cattura-stella-campo': "Cosa ha detto il prof che sarà all'esame?",
  'barra1.cattura-definizione-campo': 'Termine: definizione',
  'barra1.cattura-domanda-campo': 'La domanda da fare al prof',
  'barra1.scrivila-cosi': 'Scrivila così: **termine: definizione**.',
  'barra1.errore-vault': 'Non riesco a scrivere nel vault: {errore}',
  'barra1.dove-sparsi': 'negli appunti sparsi di oggi',
  'barra1.dove-in': 'in {corso}',
  'barra1.segnato-dove': '★ Segnato {dove}.',
  'barra1.definizione-dove': '«{termine}» {dove}.',
  'barra1.domanda-dove': 'Domanda salvata {dove}.',
  // trascrivere: in aula, dal computer, da una registrazione
  'barra1.videolezioni-app': "La trascrizione delle videolezioni è nell'**app desktop** di Lode: ascolta l'audio del computer e scrive nella nota Obsidian della lezione.",
  'barra1.sto-gia-trascrivendo': 'Sto già trascrivendo.',
  'barra1.parole-finora': { one: '{n} parole finora.', other: '{n} parole finora.' },
  'barra1.lezione-dal-computer': 'Lezione dal computer',
  'barra1.computer-spiega': "Fai partire la videolezione (sulla piattaforma del tuo ateneo, su Teams, Zoom o dove la segui): ascolto l'audio che esce dal computer e la scrivo nella nota della lezione, formule comprese.",
  'barra1.nome-del-corso': 'Nome del corso',
  'barra1.computer-patto': "Solo per studiare tu: non scarico il video e non carico niente online, l'audio non si salva e nella nota va solo il testo. Le lezioni sono dei docenti: non condividere la trascrizione se il regolamento del tuo ateneo non lo permette.",
  'barra1.computer-mac': "La prima volta il Mac ti chiede il permesso di registrare l'audio del sistema.",
  'barra1.computer-windows': "Su Windows senti l'audio come sempre: lo ascolto anch'io.",
  'barra1.computer-linux': "Su Linux ascolto il «monitor» dell'uscita audio.",
  'barra1.detto-trascrivi-videolezione': 'Trascrivi la videolezione di {corso}',
  'barra1.sintesi-lezione-dal-computer': 'lezione dal computer',
  'barra1.computer-permesso-mac': "Il Mac non mi dà l'audio del computer: in **Impostazioni di Sistema › Privacy e sicurezza › Registrazione audio dello schermo e del sistema** attiva Lode, poi riprova (a volte serve riaprire Lode).",
  'barra1.computer-permesso': "Il sistema non mi dà l'audio del computer: riprova e conferma la richiesta di condivisione.",
  'barra1.computer-non-sento-mac': "Non riesco ad ascoltare l'audio del computer (serve macOS 14.2 o più recente). {errore}",
  'barra1.computer-non-sento-windows': "Non riesco ad ascoltare l'audio del computer. {errore}",
  'barra1.computer-non-sento-linux': "Non riesco ad ascoltare l'audio del computer (serve PulseAudio o PipeWire). {errore}",
  'barra1.computer-muto': 'Non sento niente dal computer. La videolezione è partita, con il volume alzato?',
  'barra1.computer-muto-mac': "Non sento niente dal computer. La videolezione è partita, con il volume alzato? Se sì, il Mac non mi sta dando l'audio: **Impostazioni di Sistema › Privacy e sicurezza › Registrazione audio dello schermo e del sistema**, attiva Lode e riprova.",
  'barra1.trascrizione-app': "La trascrizione delle lezioni è nell'**app desktop** di Lode: scrive direttamente nella nota Obsidian della lezione.",
  'barra1.computer-aggiorna': "Questa versione non riesce ad ascoltare l'audio del computer: aggiorna Lode.",
  'barra1.preparo-voce': 'Preparo la voce…',
  'barra1.trascrivo-file': 'Trascrivo «{file}» nella lezione di {corso}.',
  'barra1.puoi-chiudere': 'Puoi chiudere il pannello: ti avviso alla fine.',
  'barra1.sintesi-registrazione': 'registrazione in trascrizione',
  'barra1.ascolto-computer': "Ascolto l'audio del computer per {corso}.",
  'barra1.ascolto-computer-nota': 'Fai partire la videolezione: le righe arrivano nella nota ogni 20-30 secondi. Quando finisce, scrivi «fine lezione».',
  'barra1.apri-in-obsidian': 'Apri in Obsidian',
  'barra1.sintesi-videolezione': 'videolezione in trascrizione',
  'barra1.avviso-videolezione': 'Ascolto la videolezione',
  'barra1.trascrivo-sparsi': 'Trascrivo gli appunti sparsi.',
  'barra1.trascrivo-lezione-di': 'Trascrivo la lezione di {corso}.',
  'barra1.righe-ogni': 'Le righe arrivano nella nota ogni 20-30 secondi.',
  'barra1.sintesi-trascrizione-avviata': 'trascrizione avviata',
  'barra1.avviso-trascrivo': 'Trascrivo la lezione',
  'barra1.errore-trascrivere': 'Non riesco a trascrivere: {errore}',
  'barra1.non-sto-trascrivendo': 'Non sto trascrivendo niente.',
  'barra1.ultimi-secondi': 'Trascrivo gli ultimi secondi…',
  'barra1.lezione-trascritta': { one: 'Lezione trascritta: {parole} parola.', other: 'Lezione trascritta: {parole} parole.' },
  'barra1.righe-sospese': { one: '{n} riga non è ancora nella nota (la cartella non risponde): le scrivo appena posso, tienimi aperto.', other: '{n} righe non sono ancora nella nota (la cartella non risponde): le scrivo appena posso, tienimi aperto.' },
  'barra1.tutto-nella-nota': 'È tutto nella nota.',
  'barra1.riordina': 'Riordina',
  'barra1.detto-riordina': 'Riordina la lezione',
  'barra1.condividi': 'Condividi',
  'barra1.detto-condividi': 'Condividi la sbobina',
  'barra1.sintesi-parole-trascritte': { one: '{n} parole trascritte', other: '{n} parole trascritte' },
  'barra1.con-cervello-locale': 'Con il **cervello locale** (da «Prepara Lode») la trascrizione diventa appunti ordinati, definizioni e ★ con un clic.',
  // riordinare la lezione con l'AI
  'barra1.non-trovo-trascrizione-di': 'Non trovo una trascrizione di **{corso}**.',
  'barra1.non-trovo-trascrizione': 'Non trovo una lezione trascritta. In aula premi **Trascrivi la lezione**.',
  'barra1.riordinare-serve-ai': "Per riordinare serve l'AI: installa il **cervello locale** da «Prepara Lode» (gratis, offline) o collega la tua AI: scrivi «AI».",
  'barra1.riordino': 'Riordino {corso}…',
  'barra1.riordino-per-cento': 'Riordino {corso}… {n}%',
  'barra1.errore-riordinare': 'Non sono riuscito a riordinare: {errore}',
  'barra1.salvare-riordinati': 'Salvare gli appunti riordinati di {corso}?',
  'barra1.appunti-salvati': 'Appunti salvati nella nota.',
  'barra1.sintesi-lezione-riordinata': 'lezione riordinata',
  'barra1.detto-definizioni-lezione': 'Definizioni dalla lezione',
  // «Ripeti» e il permesso di ascoltare la lezione
  'barra1.ascoltare-lezione': 'Ascoltare la lezione?',
  'barra1.consenso-ripeti': "tengo in memoria solo l'ultimo minuto e mezzo, mai su disco",
  'barra1.trascrivi': 'Trascrivi',
  'barra1.consenso-trascrivi': "scrivo la lezione nella nota, l'audio non si salva",
  'barra1.dove': 'Dove',
  'barra1.consenso-dove': 'tutto sul computer, niente su internet',
  'barra1.consenso-nota': 'Registrare una lezione dipende dal regolamento del tuo ateneo e dal docente: chiedi prima.',
  'barra1.solo-la-prima-volta': 'Te lo chiedo solo la prima volta.',
  'barra1.d-accordo': "D'accordo.",
  'barra1.ripeti-app': "«Ripeti» è nell'**app desktop** di Lode.",
  'barra1.ripeti-e-attivo': 'Ripeti è attivo.',
  'barra1.ripeti-attivo-nota': "Tengo in memoria l'ultimo minuto e mezzo, mai su disco. Ti sei perso qualcosa? {tasti} o «ripeti».",
  'barra1.ripeti-attivo-nota-fuori': "Tengo in memoria l'ultimo minuto e mezzo, mai su disco. Ti sei perso qualcosa? {tasti} o «ripeti». Fuori dall'orario di lezione resto acceso al massimo 3 ore.",
  'barra1.detto-spegni-ripeti': 'Spegni Ripeti',
  'barra1.sintesi-ripeti-attivo': 'ripeti attivo',
  'barra1.ripeti-spento': 'Ripeti spento.',
  'barra1.microfono-resta': 'Il microfono resta acceso per la trascrizione, finché non la chiudi.',
  'barra1.microfono-chiuso': 'Il microfono è chiuso.',
  'barra1.non-si-accende-piu': ' A lezione non si accende più da solo: lo riaccendi con {tasti}.',
  'barra1.ripeti-e-spento': 'Ripeti è spento.',
  'barra1.ripeti-e-spento-nota': 'Ripeti ti scrive cosa ha detto il prof negli ultimi 60 secondi: lo accendi qui o con {tasti}. Se volevi altro, chiedimelo con parole tue.',
  'barra1.accendi': 'Accendi',
  'barra1.detto-accendi-ripeti': 'Accendi Ripeti',
  'barra1.sintesi-ripeti-spento': 'ripeti spento',
  'barra1.ascolto-da-un-attimo': 'Ascolto da un attimo: non ho ancora niente da ripeterti.',
  'barra1.riascolto': { one: 'Riascolto gli ultimi {n} secondi…', other: 'Riascolto gli ultimi {n} secondi…' },
  'barra1.errore-riascoltare': 'Non sono riuscito a riascoltare: {errore}',
  'barra1.niente-sentito': 'Negli ultimi 60 secondi non ho sentito parlare.',
  'barra1.ultimi-secondi-ora': { one: 'Gli ultimi {n} secondi · {ora}', other: 'Gli ultimi {n} secondi · {ora}' },
  'barra1.agli-appunti': 'Agli appunti',
  'barra1.copia': 'Copia',
  'barra1.copiato': 'Copiato',
  'barra1.negli-appunti-di': 'Negli appunti di {corso}.',
  // condividere la sbobina
  'barra1.sbobine-app': "Le sbobine si condividono dall'**app desktop**.",
  'barra1.non-trovo-lezione-di': 'Non trovo una lezione di **{corso}** da condividere.',
  'barra1.non-trovo-lezione': 'Non trovo una lezione da condividere: prima trascrivila o riordinala.',
  'barra1.preparo-sbobina': 'Preparo la sbobina…',
  'barra1.sbobina-pronta': 'Sbobina di {corso} pronta.',
  'barra1.scegli-dove': 'Scegli dove mandarla: AirDrop, Messaggi, Mail…',
  'barra1.mostra': 'Mostra',
  'barra1.sintesi-sbobina-condivisa': 'sbobina condivisa',
  'barra1.errore-sbobina': 'Non riesco a preparare la sbobina: {errore}',
  // le carte per Anki
  'barra1.anki-non-trovo-di': 'Non trovo carte né definizioni di **{corso}** da esportare.',
  'barra1.anki-non-trovo': 'Non ho ancora carte né definizioni da esportare: segna qualche definizione a lezione («def: gradiente = …») o crea delle carte da un PDF.',
  'barra1.anki-carte-mazzi': { one: '{n} carta per Anki, {mazzi} mazzi.', other: '{n} carte per Anki, {mazzi} mazzi.' },
  'barra1.anki-carte-mazzo': { one: '{n} carta per Anki nel mazzo {mazzo}.', other: '{n} carte per Anki nel mazzo {mazzo}.' },
  'barra1.anki-doppioni': { one: ' {n} doppione saltato.', other: ' {n} doppioni saltati.' },
  'barra1.anki-importa-download': 'In Anki: File › Importa, scegli «{file}» (è tra i download) e come tipo di nota «Basilare» («Basic» in inglese).',
  'barra1.anki-importa-vault': 'In Anki: File › Importa, scegli «{file}» nel vault e come tipo di nota «Basilare» («Basic» in inglese).',
  'barra1.scarica': 'Scarica',
  'barra1.sintesi-anki': 'carte per Anki',
  'barra1.errore-mostrare': 'Non riesco a mostrare il file: {errore}',
  'barra1.errore-anki': 'Non riesco a salvare il file per Anki: {errore}',
  // i file lasciati sulla pillola
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'slide PowerPoint',
  'barra1.tipo-word': 'documento Word',
  'barra1.tipo-testo': 'testo',
  'barra1.tipo-sbobina': 'sbobina di Lode',
  'barra1.tipo-carte': 'carte (Anki/CSV)',
  'barra1.tipo-foto': 'foto',
  'barra1.tipo-audio': 'registrazione audio',
  'barra1.tipo-altro': 'file',
  'barra1.uno-alla-volta': { one: 'Uno alla volta: comincio da **{nome}**, poi lascia gli altri {n}.', other: 'Uno alla volta: comincio da **{nome}**, poi lascia gli altri {n}.' },
  'barra1.errore-leggere-file': 'Non riesco a leggere il file: {errore}',
  'barra1.serve-ai': 'serve il cervello locale o la tua AI',
  'barra1.serve-app': "nell'app desktop",
  'barra1.op-sbobina': 'Aggiungi al mio vault',
  'barra1.op-sbobina-d': 'Diventa una lezione nel tuo Obsidian: definizioni e ★ entrano nei giochi',
  'barra1.op-allega-soltanto': 'Allega soltanto',
  'barra1.op-allega-soltanto-d': 'Salvo il file negli allegati della lezione',
  'barra1.op-importa-carte': 'Importa le carte',
  'barra1.op-importa-carte-d': 'Una per riga: domanda, poi Tab, «;» o « = », poi risposta',
  'barra1.op-audio': 'Trascrivi la registrazione',
  'barra1.op-audio-d': 'Tutta la lezione in appunti, formule comprese, nella nota della lezione',
  'barra1.op-allega': 'Allega alla lezione',
  'barra1.op-allega-audio-d': "Salvo l'audio negli allegati, con il link nella nota",
  'barra1.op-lavagna': 'Trascrivi in appunti',
  'barra1.op-lavagna-d': 'Testo e formule in LaTeX, nella nota della lezione',
  'barra1.op-carte': 'Carte del ripasso',
  'barra1.op-carte-foto-d': "Le domande che chiederebbero all'esame",
  'barra1.op-allega-foto-d': 'La foto nella nota della lezione',
  'barra1.op-carte-d': 'Domande e risposte per il ripasso a intervalli',
  'barra1.op-riassunto': 'Riassunto in Obsidian',
  'barra1.op-riassunto-d': 'Appunti ordinati con formule, in una nota nuova',
  'barra1.op-definizioni': 'Definizioni per i giochi',
  'barra1.op-definizioni-d': 'Le aggiungo alla lezione: diventano giochi di memoria',
  'barra1.op-orale': 'Interrogami su questo',
  'barra1.op-orale-d': "Un prof d'orale con domande su questo materiale",
  'barra1.op-allega-d': 'Salvo il file con il link nella nota',
  'barra1.op-crocette': 'Quiz a crocette',
  'barra1.op-crocette-d': "Domande con 4 risposte, come allo scritto: allenamento o simulazione d'esame",
  'barra1.op-temi': "Temi d'esame",
  'barra1.op-temi-d': 'Gli esercizi di un compito vecchio, divisi per argomento, uno al giorno nel piano',
  'barra1.op-programma': "È il programma d'esame",
  'barra1.op-programma-d': "Lo divido in argomenti e ti preparo il piano fino all'appello",
  'barra1.op-domande': 'Domande uscite agli appelli',
  'barra1.op-domande-d': 'Le metto sotto i loro argomenti: quelli che escono di più salgono nel piano',
};
