// Testi della barra, terza parte (italiano, lingua di partenza): ripasso in tasca, Moodle, quiz a crocette, temi d'esame,
// prova generale, programma d'esame, «te lo spiego io», invio, file, voce, scorciatoie e avvisi dell'app (js/lode.js).
export default {
  // Ripasso in tasca
  'barra3.tasca-solo-app': 'Il ripasso in tasca va nell\'app: serve il vault di Obsidian.',
  'barra3.tasca-spenta': 'Ripasso in tasca solo quando lo chiedi.',
  'barra3.tasca-spenta-nota': 'La nota {nota} resta nel vault: scrivi «ripasso in tasca» per aggiornarla.',
  'barra3.tasca-spenta-sintesi': 'ripasso in tasca spento',
  'barra3.tasca-preparo': 'Preparo la nota…',
  'barra3.tasca-errore': 'Non riesco a leggere o scrivere la nota {nota}: {errore}',
  'barra3.tasca-estranea': 'Nel vault c\'è già una nota **{nota}** che non ha scritto Lode: non la tocco. Rinominala e riprova.',
  'barra3.tasca-segnata-sapevi': 'Ho segnato la carta che hai fatto sul telefono: la sapevi.',
  'barra3.tasca-segnata-non-sapevi': 'Ho segnato la carta che hai fatto sul telefono: non la sapevi.',
  'barra3.tasca-segnate': 'Ho segnato {n} carte che hai fatto sul telefono: {sapevo} sapevi, {no} no.',
  'barra3.tasca-gia': { one: 'Una carta l\'avevi già ripassata sul computer: non la segno due volte.', other: '{n} carte le avevi già ripassate sul computer: non le segno due volte.' },
  'barra3.tasca-vecchia': 'La nota sul telefono è di un giro vecchio: non segno niente.',
  'barra3.tasca-cambiata': 'La nota sta ancora cambiando: Obsidian la sta sincronizzando. Non la riscrivo adesso, riprova tra un minuto.',
  'barra3.tasca-domani': { one: 'Nella nota {nota} c\'è {n} carta per domani.', other: 'Nella nota {nota} ci sono {n} carte per domani.' },
  'barra3.tasca-domani-niente': 'Domani non hai carte da ripassare: la nota {nota} lo dice.',
  'barra3.tasca-titolo': 'Ripasso in tasca',
  'barra3.tasca-aspetta': 'Aspetta che il telefono finisca di sincronizzare e riprova. Se la nota giusta non arriva, riscrivila: le spunte di quella copia non le segno.',
  'barra3.apri-nota': 'Apri la nota',
  'barra3.riscrivi-nota': 'Riscrivi la nota',
  'barra3.tasca-solo-quando': 'Solo quando lo chiedo',
  'barra3.tasca-ogni-sera': 'Ogni sera',
  'barra3.tasca-sera-accesa': 'Ogni sera dopo le 19 la riscrivo da sola, se Lode è aperto.',
  'barra3.tasca-sera-spenta': 'La riscrivo solo quando me lo chiedi.',
  'barra3.tasca-come-arriva': 'Funziona se il vault arriva sul telefono (iCloud, Obsidian Sync, Syncthing). Lode non usa la rete: la nota la porta il servizio che usi già.',
  'barra3.non-apro-nota': 'Non riesco ad aprire la nota: {errore}',
  'barra3.tasca-riscrivi-detto': 'Riscrivi la nota {nota}',
  'barra3.tasca-sintesi': 'ripasso in tasca',

  // Moodle
  'barra3.moodle-solo-app': 'Il collegamento a Moodle è nell\'**app desktop** di Lode.',
  'barra3.moodle-non-risponde': 'Moodle non risponde: {errore}',
  'barra3.moodle-non-collegato': 'Moodle non è collegato.',
  'barra3.moodle-scollegato': 'Moodle scollegato.',
  'barra3.moodle-scollegato-nota': 'Il token è cancellato da questo computer. I file già presi restano nel tuo vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} corso seguito: {corsi}', other: '{n} corsi seguiti: {corsi}' },
  'barra3.file-nuovi': 'File nuovi',
  'barra3.scadenze': 'Scadenze',
  'barra3.corsi': 'Corsi',
  'barra3.scollega': 'Scollega',
  'barra3.moodle-senza-portachiavi': 'Questo computer non ha un portachiavi: il collegamento vale fino a quando chiudi Lode.',
  'barra3.moodle-novita-detto': 'Novità da Moodle',
  'barra3.moodle-corsi-detto': 'Corsi di Moodle',
  'barra3.moodle-scollega-detto': 'Scollega Moodle',
  'barra3.moodle-collega': 'Collega Moodle',
  'barra3.moodle-collega-intro': 'La piattaforma dei corsi del tuo ateneo (Virtuale, Ariel, e-learning…): Lode prende i file nuovi e le scadenze dei corsi che scegli. Solo lettura: non consegna niente e non scrive niente.',
  'barra3.moodle-indirizzo-esempio': 'Indirizzo, per esempio virtuale.unibo.it',
  'barra3.moodle-indirizzo': 'Indirizzo di Moodle',
  'barra3.continua': 'Continua',
  'barra3.moodle-collega-nota': 'Entri come nell\'app Moodle ufficiale. Il collegamento resta cifrato su questo computer, mai nel vault; con «scollega moodle» lo togli.',
  'barra3.moodle-cerco': 'Cerco il sito…',
  'barra3.moodle-non-indirizzo': 'Questo non sembra un indirizzo.',
  'barra3.moodle-non-trovo': 'Non trovo un Moodle con l\'app attiva a questo indirizzo ({motivo}). Copia l\'indirizzo dalla barra del browser quando sei sulla pagina dei tuoi corsi.',
  'barra3.moodle-accesso-annullato': 'Accesso annullato.',
  'barra3.moodle-accesso-fallito': 'Accesso non riuscito: {motivo}.',
  'barra3.moodle-entra-sso': '<b>{nome}</b> · si entra con il login dell\'ateneo (SPID o le credenziali d\'ateneo), in una finestra di Lode.',
  'barra3.accedi': 'Accedi',
  'barra3.moodle-accedi-finestra': 'Accedi nella finestra che si è aperta…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · accesso con utente e password di Moodle.',
  'barra3.utente': 'Utente',
  'barra3.password': 'Password',
  'barra3.moodle-password-nota': 'La password va solo a Moodle: Lode non la salva.',
  'barra3.moodle-collega-sintesi': 'collega Moodle',
  'barra3.moodle-leggo-corsi': 'Leggo i tuoi corsi…',
  'barra3.moodle-corsi-errore': 'Non riesco a leggere i corsi: {errore}',
  'barra3.moodle-nessun-corso': 'Su Moodle non risulti iscritto a nessun corso.',
  'barra3.moodle-corsi-titolo': 'Corsi di Moodle · {sito}',
  'barra3.moodle-scegli-corsi': 'Scegli quali seguire e con quale corso di Lode: i loro file nuovi arrivano qui.',
  'barra3.concluso': 'concluso',
  'barra3.moodle-corso-per': 'Corso di Lode per {nome}',
  'barra3.non-seguire': 'Non seguire',
  'barra3.moodle-con-nome': 'Con il nome di Moodle',
  'barra3.salva': 'Salva',
  'barra3.moodle-seguo': { one: 'Seguo {n} corso su Moodle.', other: 'Seguo {n} corsi su Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Nessun corso seguito.',
  'barra3.moodle-ti-avviso': 'Ti avviso quando arrivano file nuovi.',
  'barra3.moodle-corsi-sintesi': 'corsi di Moodle',
  'barra3.moodle-guardo': 'Guardo i file su Moodle…',
  'barra3.moodle-non-leggo': 'Non riesco a leggere {corsi}: {errore}.',
  'barra3.moodle-nessun-file': 'Nei corsi che segui non ci sono ancora file.',
  'barra3.moodle-piu-recenti': 'i file più recenti',
  'barra3.moodle-file-nuovi': { one: '{n} file nuovo', other: '{n} file nuovi' },
  'barra3.moodle-niente-nuovo': 'niente di nuovo, gli ultimi file',
  'barra3.nuovo': 'nuovo',
  'barra3.apri': 'Apri',
  'barra3.moodle-apri-nota': '«Apri» lo porta in Lode come se lo avessi trascinato: carte, riassunto, programma, quiz.',
  'barra3.scarico': 'Scarico…',
  'barra3.non-riesco': 'Non riesco',
  'barra3.aperto': 'Aperto',
  'barra3.moodle-file-da': '{nome} da Moodle',
  'barra3.file-illeggibile': 'Non riesco a leggere il file: {errore}',
  'barra3.moodle-sintesi-nuovi': 'Moodle: {n} file nuovi',
  'barra3.moodle-nessuna-scadenza': 'Nessuna scadenza su Moodle nelle prossime settimane.',
  'barra3.moodle-scadenze-titolo': 'Scadenze su Moodle',
  'barra3.scadenze-sintesi': '{n} scadenze',
  'barra3.guarda': 'Guarda',

  // quiz a crocette
  'barra3.non-trovo-esame': 'Non trovo l\'esame **{nome}**.',
  'barra3.il-tuo-materiale': 'il tuo materiale',
  'barra3.quiz-poco-materiale': 'Per un quiz su **{nome}** mi serve più materiale: trascina la dispensa o le slide (scegli «Quiz a crocette»), oppure crea qualche carta.',
  'barra3.quiz-senza-ai': 'Per il quiz senza AI mi servono almeno 4 carte o 4 definizioni di **{nome}**. Con l\'AI (scrivi «AI») lo faccio anche dalla dispensa.',
  'barra3.quiz-fonte-dispensa-nome': 'Domande dalla dispensa «{nome}».',
  'barra3.quiz-fonte-dispensa': 'Domande dalla dispensa .',
  'barra3.quiz-fonte-ai': 'Domande dalle tue carte, definizioni e domande uscite.',
  'barra3.quiz-fonte-carte-definizioni': 'Domande dalle tue carte e definizioni.',
  'barra3.quiz-fonte-carte': 'Domande dalle tue carte.',
  'barra3.quiz-fonte-definizioni': 'Domande dalle tue definizioni.',
  'barra3.quiz-le-scrive': 'Le scrive {motore}: tengo solo quelle che il materiale dimostra.',
  'barra3.quiz-sbagliate-altre': 'Le risposte sbagliate sono quelle di altre carte del corso.',
  'barra3.quiz-titolo': 'Quiz a crocette · {nome}',
  'barra3.quiz-allenamento': 'Allenamento · {n} domande',
  'barra3.quiz-allenamento-sotto': 'La correzione subito, con la spiegazione',
  'barra3.quiz-simulazione': 'Simulazione d\'esame · {n} domande in {n} minuti',
  'barra3.quiz-simulazione-sotto': 'Come allo scritto: il tempo scorre, la correzione alla fine, il voto in trentesimi',
  'barra3.quiz-simulazione-detto': 'Simulazione d\'esame · {nome}',
  'barra3.quiz-detto': 'Quiz · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulazione · {nome}',
  'barra3.quiz-preparo': 'Preparo le domande… {fatte} di {n}',
  'barra3.quiz-errore': 'Non riesco a preparare le domande: {errore}',
  'barra3.quiz-niente': 'Non sono riuscito a preparare domande affidabili da questo materiale.',
  'barra3.quiz-sintesi': 'quiz di {nome}',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} di {n}',
  'barra3.x-di-n': '{x} di {n}',
  'barra3.quiz-domanda-n': 'Domanda {x} di {n}',
  'barra3.indietro': 'Indietro',
  'barra3.salta': 'Salta',
  'barra3.lascia-vuota': 'Lascia vuota',
  'barra3.consegna': 'Consegna',
  'barra3.quiz-giusta-e': 'La risposta giusta è la {lettera}.',
  'barra3.avanti': 'Avanti',
  'barra3.risultato': 'Risultato',
  'barra3.tasto-invio': 'Invio',
  'barra3.quiz-voto': 'Voto: <em>{voto}</em>',
  'barra3.tempo-scaduto': 'tempo scaduto',
  'barra3.quiz-tutte-giuste': 'Tutte giuste.',
  'barra3.quiz-da-rivedere': { one: '{n} da rivedere.', other: '{n} da rivedere.' },
  'barra3.quiz-scartate': { one: '{n} domande scartate perché il materiale non le dimostrava', other: '{n} domande scartate perché il materiale non le dimostrava' },
  'barra3.da-rivedere': 'Da rivedere',
  'barra3.lasciata-vuota': 'Lasciata vuota',
  'barra3.hai-scelto': 'Hai scelto: {x}',
  'barra3.giusta-era': 'Giusta: {x}',
  'barra3.quiz-sbagliate-carte': 'Le sbagliate diventano carte',
  'barra3.quiz-un-altro': 'Un altro quiz',
  'barra3.quiz-punti': 'Una risposta giusta vale 1 punto, sbagliata o vuota 0.',
  'barra3.quiz-regole-vere': 'Lo scritto vero può avere regole diverse (penalità per le sbagliate, soglie): è un allenamento.',
  'barra3.quiz-carte-aggiunte': { one: '{n} carte aggiunte: tornano oggi nel ripasso', other: '{n} carte aggiunte: tornano oggi nel ripasso' },
  'barra3.quiz-sintesi-esito': 'quiz di {nome}: {giuste} su {n}',

  // temi d'esame
  'barra3.tema-del': 'del {data}',
  'barra3.tema-di': 'di «{fonte}»',
  'barra3.tema-es': 'es. {es}',
  'barra3.tema-es-da': 'es. {es} {da}',
  'barra3.tema-circa': 'circa {min} min su carta',
  'barra3.leggo-file': 'Leggo {nome}…',
  'barra3.cmd-temi-di': '«temi d\'esame di {nome}:»',
  'barra3.cmd-temi': '«temi d\'esame:»',
  'barra3.temi-scansione': 'Questo PDF sembra una scansione: senza AI non leggo le immagini. Incolla il testo degli esercizi con {cmd} e il testo sotto.',
  'barra3.temi-illeggibile': 'Da questo file non riesco a leggere il testo. Incollalo con {cmd} e il testo sotto.',
  'barra3.aggiungi-prima-esame': 'Aggiungi prima l\'esame, per esempio: «esame analisi 2 il 15 gennaio 9 cfu».',
  'barra3.non-trovo-esame-aggiungi': 'Non trovo l\'esame **{nome}**. Aggiungilo prima, per esempio: «esame {nome} il 15 gennaio 9 cfu».',
  'barra3.aggiungi-esame-compito': 'Aggiungi prima un esame, per esempio: «esame analisi 2 il 15 gennaio 9 cfu». Poi incolla un compito vecchio.',
  'barra3.prova-invito': 'Vuoi provare un compito intero, col tempo vero?',
  'barra3.prova-generale': 'Prova generale',
  'barra3.prova-generale-di': 'Prova generale di {nome}',
  'barra3.temi-titolo': 'Temi d\'esame · {nome}',
  'barra3.temi-nessuno-oggi': 'Nessun esercizio in scadenza oggi.',
  'barra3.temi-prossimo': 'Il prossimo torna {data}.',
  'barra3.temi-vuoto': 'Incolla il testo di un compito vecchio (quelli che girano nel gruppo del corso o sul sito del prof), oppure trascina il PDF. Lo divido in esercizi, li metto sotto i loro argomenti e ogni giorno te ne propongo uno.',
  'barra3.temi-segnaposto': 'Esercizio 1. Calcolare…&#10;Esercizio 2. Studiare…',
  'barra3.temi-testo-compito': 'Testo del compito',
  'barra3.temi-dividi': 'Dividi in esercizi',
  'barra3.temi-di': 'Temi d\'esame di {nome}',
  'barra3.temi-di-sintesi': 'temi d\'esame di {nome}',
  'barra3.temi-nessun-esercizio': 'Non ho trovato esercizi in questo testo.',
  'barra3.temi-compito-del': 'compito {data}',
  'barra3.temi-un-pezzo': 'Non ho trovato «Esercizio 1», «Esercizio 2»… Se il compito ha più esercizi, scrivili con quei segni e incollalo di nuovo.',
  'barra3.temi-senza-programma': 'Per {nome} non c\'è ancora il programma: li salvo senza argomento.',
  'barra3.temi-metti': 'Mettili nel piano',
  'barra3.temi-es': 'Es. {n}',
  'barra3.temi-con-soluzione': 'con la soluzione del prof',
  'barra3.temi-argomento-di': 'Argomento dell\'esercizio {n}',
  'barra3.temi-che-argomento': 'Che argomento è?',
  'barra3.temi-unisci': 'Unisci al precedente',
  'barra3.togli': 'Togli',
  'barra3.temi-nel-piano': { one: '{n} esercizio nel piano.', other: '{n} esercizi nel piano.' },
  'barra3.temi-nel-piano-arg': { one: '{n} esercizio nel piano: {con} con il loro argomento, {senza} senza.', other: '{n} esercizi nel piano: {con} con il loro argomento, {senza} senza.' },
  'barra3.temi-senza-programma-nota': 'Senza programma non so dove metterli: incolla il programma di {nome} e li sistemo.',
  'barra3.temi-doppi': { one: '{n} c\'erano già.', other: '{n} c\'erano già.' },
  'barra3.temi-ogni-giorno': 'Ogni giorno uno sugli argomenti del piano.',
  'barra3.programma': 'Programma',
  'barra3.fanne-uno': 'Fanne uno',
  'barra3.esercizio-di': 'Esercizio di {nome}',
  'barra3.temi-gia': 'Questi esercizi c\'erano già.',
  'barra3.temi-sintesi-n': { one: 'temi d\'esame di {nome}: {n} esercizi', other: 'temi d\'esame di {nome}: {n} esercizi' },
  'barra3.tema-titolo': 'Esercizio · {nome}',
  'barra3.tema-fallo': 'Fallo su carta, senza guardare gli appunti. Quando hai finito:',
  'barra3.giusto': 'Giusto',
  'barra3.sbagliato': 'Sbagliato',
  'barra3.non-sapevo': 'Non sapevo da dove partire',
  'barra3.tema-voto-tuo': 'Il voto te lo dai tu: Lode non corregge l\'esercizio.',
  'barra3.tema-torna': { one: 'Torna tra {n} giorni.', other: 'Torna tra {n} giorni.' },
  'barra3.tema-guarda-soluzione': 'Guarda la soluzione e rifallo da capo, non rileggerla e basta.',
  'barra3.tema-rileggi': 'Rileggi l\'argomento e rifallo da capo, senza guardare.',
  'barra3.tema-prima-rileggi-arg': 'Prima rileggi l\'argomento: {arg}.',
  'barra3.tema-prima-rileggi': 'Prima rileggi l\'argomento.',
  'barra3.tema-vedi-soluzione': 'Vedi la soluzione del prof',
  'barra3.tema-altro': 'Un altro esercizio',
  'barra3.esercizio-di-esito': 'esercizio di {nome}: {esito}',
  'barra3.esercizio-di-sintesi': 'esercizio di {nome}',
//FINE
};
