// Testi della barra, seconda parte (italiano, lingua di partenza): file lasciati nella barra, proposte dell'allenatore,
// la tua AI, «Prepara Lode» e aggiornamenti, sincronizzazione, note, chiusura della lezione, giochi, comandi locali,
// errori spiegati e diario, strumenti dell'AI, orale, agenti di programmazione (js/lode.js).
export default {
  'barra2.file-non-so-usare': 'Questo non lo so usare: {motivo}.',
  'barra2.peso-kb': '{n} KB',
  'barra2.peso-mb': '{n} MB',
  'barra2.cosa-ne-faccio': 'Cosa ne faccio?',
  'barra2.per': 'Per',
  'barra2.corso': 'Corso',
  'barra2.data-lezione': 'Data della lezione',
  'barra2.non-andata': 'Non è andata: {errore}',
  'barra2.sintesi-cosa-ne-faccio': '{nome}: cosa ne faccio?',
  'barra2.allegato-lezione': 'Allegato alla lezione di {corso}.',
  'barra2.apri': 'Apri',
  'barra2.sbobina-nel-vault': 'Sbobina di {corso} nel tuo vault.',
  'barra2.sbobina-nota-da': '{data} · da {da}',
  'barra2.sbobina-ricevuta': 'sbobina ricevuta',
  'barra2.nessuna-riga-carte': 'Non ho trovato righe «domanda, risposta» in questo file.',
  'barra2.apro-registrazione': 'Apro la registrazione…',
  'barra2.leggo-foto': 'Leggo la foto…',
  'barra2.lavagna-titolo': 'Mettere negli appunti di {corso}?',
  'barra2.lavagna-nota': 'Insieme alla foto, nella nota della lezione di oggi. Rileggila: l\'ha trascritta {motore}.',
  'barra2.lavagna-fatta': 'Lavagna negli appunti.',
  'barra2.leggo-file': 'Leggo {nome}…',
  'barra2.file-senza-testo': 'Da questo file non riesco a leggere il testo.',
  'barra2.file-senza-testo-incolla': 'Da questo file non riesco a leggere il testo: incollalo nel campo.',
  'barra2.prima-esame': 'Aggiungi prima l\'esame, per esempio: «esame analisi 2 il 15 gennaio 9 cfu».',
  'barra2.scrivo-carte': 'Scrivo le carte…',
  'barra2.file-senza-carte': 'Da questo file non ho tirato fuori carte.',
  'barra2.riassumo': 'Riassumo {nome}… {p}%',
  'barra2.riassunto-titolo': 'Salvare il riassunto in Obsidian?',
  'barra2.riassunto-nota': 'Nota nuova in {cartella}, con il file originale allegato.',
  'barra2.riassunto-salvato': 'Riassunto salvato.',
  'barra2.stelle-titolo': '★ Da esame · {esame}',
  'barra2.ora-un-gioco': 'Ora un gioco',
  'barra2.gioca': 'Gioca',
  'barra2.la-tua-ai': 'La tua AI',
  'barra2.ai-locale-attivo': 'Adesso Lode usa il <b>cervello locale</b>: gratis, offline, gli appunti restano qui.',
  'barra2.ai-locale-da-installare': 'Il <b>cervello locale</b> gratis si installa da «Prepara Lode».',
  'barra2.ai-chiave-spiegazione': 'Se vuoi un\'AI più potente, collega la tua chiave: paghi direttamente il servizio, a consumo (di solito pochi centesimi a sessione). Lode non vede né incassa niente; la chiave resta su questo computer.',
  'barra2.ai-nome-collegata': '{nome} · collegata',
  'barra2.chiave-api': 'Chiave API',
  'barra2.collega': 'Collega',
  'barra2.modello': 'Modello',
  'barra2.ai-solo-spiegazioni': 'Appunti e lezioni restano sul computer: la tua AI solo per spiegazioni e orale',
  'barra2.usa-solo-locale': 'Usa solo il cervello locale',
  'barra2.chiave-di': 'Chiave di {nome}',
  'barra2.incolla-chiave': 'incolla la chiave',
  'barra2.si-crea-su': 'Si crea su <b>{sito}</b>.',
  'barra2.provo-chiave': 'Provo la chiave…',
  'barra2.ai-collegata': '{nome} collegata.',
  'barra2.ai-modello': 'Modello {modello}.',
  'barra2.ai-appunti-restano': 'Gli appunti restano sul computer.',
  'barra2.ai-usano-tua': 'Spiegazioni, orale, carte e riordino usano la tua AI.',
  'barra2.sintesi-ai-collegata': 'AI collegata',
  'barra2.chiave-non-valida': 'La chiave non è valida.',
  'barra2.servizio-irraggiungibile': 'Non riesco a raggiungere il servizio: c\'è la rete?',
  'barra2.solo-locale-fatto': 'Lode usa solo il cervello locale.',
  'barra2.ai-scollegata-sito': 'Ho cancellato la chiave da questo computer. Nel tuo account {nome} vale ancora: se non ti serve più, revocala anche lì ({sito}).',
  'barra2.ai-scollegata-nome': 'Ho cancellato la chiave da questo computer. Nel tuo account {nome} vale ancora: se non ti serve più, revocala anche lì.',
  'barra2.ai-scollegata': 'Ho cancellato la chiave da questo computer. Nel tuo account vale ancora: se non ti serve più, revocala anche lì.',
  'barra2.sintesi-la-tua-ai': 'la tua AI',
  'barra2.agg-pronta': 'Lode {versione} è pronta',
  'barra2.agg-si-installa': 'Si installa da sola quando chiudi Lode',
  'barra2.riavvia-ora': 'Riavvia ora',
  'barra2.agg-uscita': 'È uscita Lode {versione}',
  'barra2.agg-scarica-dmg': 'Scarica il .dmg e trascina Lode in Applicazioni',
  'barra2.agg-scarica-github': 'Scarica la versione nuova da GitHub',
  'barra2.scarica': 'Scarica',
  'barra2.agg-spenti': 'Lode {versione} · spenti: le versioni nuove sono su GitHub, nella pagina Release',
  'barra2.agg-scarico': 'Scarico Lode {versione} · {p}%',
  'barra2.agg-pronta-riga': 'Lode {versione} è pronta · si installa da sola quando chiudi Lode',
  'barra2.agg-uscita-mac': 'È uscita Lode {versione} · scarica il .dmg e trascina Lode in Applicazioni',
  'barra2.agg-uscita-github': 'È uscita Lode {versione} · scaricala da GitHub',
  'barra2.agg-manuale': 'Lode {versione} · ti avviso quando ne esce una nuova (da GitHub, ogni 6 ore)',
  'barra2.agg-automatici': 'Lode {versione} · si aggiorna da sola da GitHub, controlla ogni 6 ore',
  'barra2.spegni': 'Spegni',
  'barra2.accendi': 'Accendi',
  'barra2.prep-solo-app': 'Obsidian e il cervello locale si installano dall\'**app desktop** di Lode.',
  'barra2.prepara-lode': 'Prepara Lode',
  'barra2.il-tuo-vault': 'Il tuo vault',
  'barra2.prep-vault-dett': '{percorso} · Home, corsi, lezioni, glossario',
  'barra2.obs-installato': 'Installato e collegato al vault',
  'barra2.obs-da-installare': 'Gratis per uso personale · installer ufficiale da GitHub, circa 230 MB',
  'barra2.installa': 'Installa',
  'barra2.cervello-locale': 'Cervello locale',
  'barra2.cervello-pronto-dett': '{modello} · gira sul computer, senza internet',
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · circa {gb} GB',
  'barra2.pronto': 'pronto',
  'barra2.voce': 'Voce',
  'barra2.voce-pronta-dett': '{voce} in locale · tieni premuto {tasti} e parla',
  'barra2.pronta': 'pronta',
  'barra2.prepara': 'Prepara',
  'barra2.facoltativa': 'facoltativa',
  'barra2.tua-ai-collegata-dett': '{nome} collegata · paghi tu a consumo, direttamente al servizio',
  'barra2.tua-ai-da-collegare': 'Claude, ChatGPT, Gemini, Mistral…: più potente, a consumo con la tua chiave',
  'barra2.cambia': 'Cambia',
  'barra2.sincronizza-computer': 'Sincronizza fra i tuoi computer',
  'barra2.sperimentale': 'sperimentale',
  'barra2.sblocca': 'Sblocca',
  'barra2.gestisci': 'Gestisci',
  'barra2.attiva': 'Attiva',
  'barra2.uso-gia-altrove': 'Uso già Lode su un altro computer',
  'barra2.collega-dett': 'Collega questo computer al vault che hai già nella cartella cloud',
  'barra2.aggiornamenti': 'Aggiornamenti',
  'barra2.prep-nota': 'Il cervello locale è gratis e lavora offline: estrae definizioni, crea carte, spiega e interroga. La tua AI è un potenziamento facoltativo: Lode non vede né incassa niente.',
  'barra2.detto-mia-ai': 'La mia AI',
  'barra2.detto-sincronizza': 'Sincronizza fra i computer',
  'barra2.scarico-voce': 'Scarico {voce}…',
  'barra2.sintesi-prepara': 'prepara Lode',
  'barra2.installare-obsidian': 'Installare Obsidian?',
  'barra2.da': 'Da',
  'barra2.github-obsidian': 'github.com/obsidianmd (ufficiale)',
  'barra2.peso': 'Peso',
  'barra2.circa-230-mb': 'circa 230 MB',
  'barra2.dove': 'Dove',
  'barra2.applicazioni': 'Applicazioni',
  'barra2.il-tuo-utente': 'il tuo utente',
  'barra2.obs-nota': 'Obsidian è gratis per uso personale. Si apre già sul tuo vault, sulla Home.',
  'barra2.installare-nome': 'Installare {nome}?',
  'barra2.installare-cervello': 'Installare il cervello locale?',
  'barra2.cosa': 'Cosa',
  'barra2.ollama-motore': 'Ollama (motore) + {nome}',
  'barra2.circa-gb': 'circa {gb} GB',
  'barra2.perche': 'Perché',
  'barra2.cervello-nota': 'Si scarica una volta sola. Poi funziona senza internet e senza chiavi.',
  'barra2.solo-clic': 'Si conferma solo col clic.',
  'barra2.avviato': 'Avviato.',
  'barra2.continuo-da-solo': 'Puoi chiudere il pannello: continuo da solo.',
  'barra2.obsidian-pronto': 'Obsidian è pronto',
  'barra2.cervello-pronto': 'Cervello locale pronto',
  'barra2.sync-piede-cifrati': 'Cifrati, sincronizzati con {servizio}',
  'barra2.sync-piede': 'Sincronizzati con {servizio}',
  'barra2.la-tua-cartella-cloud': 'la tua cartella cloud',
  'barra2.dati-restano-qui': 'I dati restano su questo computer',
  'barra2.portachiavi-mac': 'La password si ricorda su questo computer (nel Portachiavi).',
  'barra2.portachiavi-windows': 'La password si ricorda su questo computer (protetta dal tuo account di Windows).',
  'barra2.portachiavi-sistema': 'La password si ricorda su questo computer (nel portachiavi del sistema).',
  'barra2.senza-portachiavi': 'Questo computer non ha un portachiavi sicuro: Lode ti chiederà la password a ogni avvio.',
  'barra2.sync-solo-app': 'La sincronizzazione fra i computer è nell\'**app desktop** di Lode.',
  'barra2.sync-stato-illeggibile': 'Non riesco a leggere lo stato della sincronizzazione.',
  'barra2.sync-altro-computer': 'Sull\'altro computer apri Lode e scegli «Uso già Lode su un altro computer», poi il vault «{vault}» in {servizio}.',
  'barra2.la-cartella-cloud': 'la cartella cloud',
  'barra2.sync-non-accesa': 'La sincronizzazione non è accesa: i dati di Lode restano su questo computer.',
  'barra2.sync-titolo-altro': 'Uso già Lode su un altro computer · sperimentale',
  'barra2.sync-titolo': 'Sincronizza fra i tuoi computer · sperimentale',
  'barra2.sync-sperimentale': '<b>Sperimentale.</b> {testo}',
  'barra2.sync-cartella-cloud': 'Uso la cartella cloud che hai già: niente account, niente server di Lode. Copio il vault lì e passo alla copia; la cartella di prima resta dov\'è. {prima}',
  'barra2.sync-interrotto': '<b>Lo spostamento in {servizio} si è interrotto.</b> Il vault di prima è intatto: scegli di nuovo la cartella e riprendo da dove ero rimasto.',
  'barra2.cartella-cloud': 'cartella cloud',
  'barra2.sync-interrotto-pw': 'Era cominciato con la password: ti chiederò di scriverla di nuovo.',
  'barra2.vault-gia-qui': 'il vault è già qui: niente da spostare',
  'barra2.altra-cartella': 'Un\'altra cartella…',
  'barra2.altra-cartella-dett': 'Syncthing, una cartella di rete',
  'barra2.nessuna-cartella-cloud': 'Non trovo iCloud Drive, OneDrive, Dropbox o Google Drive su questo computer: scegli tu la cartella che si sincronizza.',
  'barra2.scegli-vault-cloud': 'Scegli il vault nella cartella cloud',
  'barra2.gia-sincronizzato': '{servizio} · già sincronizzato',
  'barra2.scegli-vault': 'Scegli il vault…',
  'barra2.scegli-vault-dett': 'la cartella «Lode» nella tua cartella cloud',
  'barra2.vault-resta': 'Il vault che c\'è adesso su questo computer resta dov\'è, intatto.',
  'barra2.vault-resta-altro': 'Se Lode qui ha già esami, voti o carte, li porto nel gruppo come «Dati di un altro primo avvio»: li importi tu, niente sostituisce i dati degli altri computer.',
  'barra2.la-cartella-che-scegli': 'la cartella che scegli',
  'barra2.sintesi-uso-gia-altrove': 'uso già Lode altrove',
  'barra2.sintesi-sincronizza': 'sincronizza',
  'barra2.sincronizzare-con': 'Sincronizzare con {servizio}?',
  'barra2.vault': 'Vault',
  'barra2.vault-resta-cloud': 'resta dov\'è: è già nella cartella cloud',
  'barra2.cartella-lode-in': 'una cartella «Lode» in {servizio}',
  'barra2.prima': 'Prima',
  'barra2.dati-json-cronologia': 'il dati.json di prima resta nella cronologia del servizio',
  'barra2.vault-adesso-resta': 'il vault di adesso resta dov\'è, intatto',
  'barra2.dati-di-lode': 'Dati di Lode',
  'barra2.un-diario-per-computer': 'un diario per computer: niente conflitti, niente si perde',
  'barra2.proteggi-con-password': 'Proteggi i dati di Lode con una password',
  'barra2.password-almeno-8': 'Password (almeno 8 caratteri)',
  'barra2.password': 'Password',
  'barra2.ripetila': 'Ripetila',
  'barra2.ripeti-password': 'Ripeti la password',
  'barra2.cifrati-in-chiaro-anche': '<b>Cifrati:</b> {cifrati}. <b>In chiaro nella cartella cloud</b>, anche con la password:',
  'barra2.sync-nota-password': 'La password si può aggiungere anche dopo («Proteggi con una password»), o cambiare («Cambia password»). Sugli altri computer: «Uso già Lode su un altro computer». {prima}',
  'barra2.spostamento-con-password': 'Lo spostamento era cominciato con la password: scrivila di nuovo.',
  'barra2.almeno-8': 'Almeno 8 caratteri.',
  'barra2.password-diverse': 'Le due password non sono uguali.',
  'barra2.preparo': 'Preparo…',
  'barra2.sincronizzato-con': 'Sincronizzato con {servizio}.',
  'barra2.vault-era-gia-cloud': 'Il vault era già nella cartella cloud: da adesso ogni computer scrive solo il suo diario.',
  'barra2.cartella-prima-resta': 'La cartella di prima («{da}») resta dov\'era: cancellala tu quando vuoi. Sugli altri computer: «Uso già Lode su un altro computer».',
  'barra2.vault-gia-in-servizio': 'In {servizio} c\'è già un vault di Lode sincronizzato.',
  'barra2.usa-uso-gia': 'Usa «Uso già Lode su un altro computer» per collegarti a quello.',
  'barra2.annullato': 'Annullato.',
  'barra2.niente-cambiato': 'Non ho cambiato niente.',
  'barra2.scrivi-password': 'Scrivi la password.',
  'barra2.non-ancora': 'Non ancora.',
  'barra2.non-andata-vault-intatto': 'Non è andata: {errore}. Il vault di prima è intatto.',
  'barra2.collegato-vault-in': 'Collegato al vault in {servizio}.',
  'barra2.dati-protetti-password': 'I dati di Lode sono protetti da una password: scrivila per riceverli.',
  'barra2.ricevo-dati': 'Ricevo i dati dagli altri computer: arrivano da soli. Lode è già usabile.',
  'barra2.dati-importati-altrove': { one: 'I dati che avevi su questo computer ({n} record) sono in «Dati di un altro primo avvio» nella scheda «Sincronizza»: importali da lì. Il file di prima resta nel vault «{vault}».', other: 'I dati che avevi su questo computer ({n} record) sono in «Dati di un altro primo avvio» nella scheda «Sincronizza»: importali da lì. Il file di prima resta nel vault «{vault}».' },
  'barra2.cartella-inusabile': 'Non riesco a usare quella cartella.',
  'barra2.diario-illeggibile': 'Il diario di Lode su questo computer non si legge',
  'barra2.diario-illeggibile-nota': 'Niente è stato cancellato: la cartella dei dati di Lode non risponde (disco pieno o guasto?). Le modifiche di adesso vanno in un file a parte.',
  'barra2.riprova': 'Riprova',
  'barra2.vault-sparito': 'I dati di Lode di questo computer sono al sicuro nel suo diario. Se hai spostato il vault, scegli la cartella dove l\'hai messo.',
  'barra2.trova-vault': 'Trova il vault',
  'barra2.lode-vecchia-campi': { one: '<b>Da una Lode vecchia:</b> {n} campo diverso da quelli di adesso. Non cambiano niente da soli: la copia del file è nella cartella dei dati di Lode (sync/copie).', other: '<b>Da una Lode vecchia:</b> {n} campi diversi da quelli di adesso. Non cambiano niente da soli: la copia del file è nella cartella dei dati di Lode (sync/copie).' },
  'barra2.aggiunte': { one: '<b>Dati di un altro primo avvio o di una Lode vecchia:</b> {n} record (esami, carte, sessioni…) che il diario non ha. Non entrano da soli.', other: '<b>Dati di un altro primo avvio o di una Lode vecchia:</b> {n} record (esami, carte, sessioni…) che il diario non ha. Non entrano da soli.' },
  'barra2.importa-aggiunte': 'Importa le aggiunte',
  'barra2.password-dati-lode': 'Password dei dati di Lode',
  'barra2.intanto-funziona': 'Intanto Lode funziona con i dati di questo computer: le modifiche aspettano nel diario. {portachiavi}',
  'barra2.ho-dimenticato-password': 'Ho dimenticato la password',
  'barra2.dimentica-password-qui': 'Dimentica la password qui',
  'barra2.cifrati-in-chiaro': '<b>Cifrati:</b> {cifrati}. <b>In chiaro nella cartella cloud:</b>',
  'barra2.cambia-password': 'Cambia password',
  'barra2.senza-password': 'Senza password: chi può leggere la tua cartella cloud può leggere anche i dati di Lode, come già gli appunti.',
  'barra2.proteggi-password': 'Proteggi con una password',
  'barra2.recuperi': 'Le modifiche che il diario non ha potuto prendere sono in {n} file «recupero-…json» (l\'ultimo: «{file}»), nella cartella dei dati di Lode: non le ho buttate.',
  'barra2.recupero': 'Le modifiche che il diario non ha potuto prendere sono nel file «{file}», nella cartella dei dati di Lode: non le ho buttate.',
  'barra2.smetti-qui': 'Smetti su questo computer',
  'barra2.importati-record': { one: 'Importato {n} record.', other: 'Importati {n} record.' },
  'barra2.ora-su-tutti': 'Ora sono su tutti i computer.',
  'barra2.non-andata-punto': 'Non è andata.',
  'barra2.controllo': 'Controllo…',
  'barra2.sbloccata': 'Sbloccata.',
  'barra2.password-ricordata': 'La password è ricordata su questo computer.',
  'barra2.chiedero-prossimo-avvio': 'Te la chiederò al prossimo avvio.',
  'barra2.password-nuova-almeno-8': 'Password nuova (almeno 8 caratteri)',
  'barra2.password-nuova': 'Password nuova',
  'barra2.password-nuova-pronta': 'Password nuova pronta.',
  'barra2.altri-chiederanno': 'Gli altri computer te la chiederanno una volta.',
  'barra2.cambiare-password': 'Cambiare la password?',
  'barra2.rifa-password-nuova': 'Lode rifà i dati di Lode nella cartella cloud con la password nuova. {testo}',
  'barra2.scegliere-password-nuova': 'Scegliere una password nuova?',
  'barra2.proteggere-password': 'Proteggere i dati di Lode con una password?',
  'barra2.rifa-cifrati': 'Lode rifà i dati di Lode nella cartella cloud, cifrati con la password. Gli altri computer te la chiederanno. {testo}',
  'barra2.password-dimenticata': 'Password dimenticata su questo computer.',
  'barra2.chiedero-di-nuovo': 'Te la chiederò di nuovo.',
  'barra2.smettere-qui': 'Smettere su questo computer?',
  'barra2.vault-copiato-fuori': 'copiato in una cartella fuori dalla cartella cloud, che scegli tu',
  'barra2.tutti-dati': 'tutti, anche quelli degli altri computer fino a oggi',
  'barra2.gli-altri-computer': 'Gli altri computer',
  'barra2.continuano-sincronizzarsi': 'continuano a sincronizzarsi tra loro',
  'barra2.smesso-qui': 'Smesso su questo computer.',
  'barra2.smesso-nota': 'Il vault ora è fuori dalla cartella cloud. Per smettere ovunque, fallo su ogni computer.',
  'barra2.sintesi-smessa': 'sincronizzazione smessa qui',
  'barra2.ultima-lezione': 'Ultima lezione',
  'barra2.lezione-di': 'Lezione di {corso}',
  'barra2.cosa-sa-lode': 'Cosa sa Lode di me',
  'barra2.vai-a-note': { one: 'Vai a… · {n} note', other: 'Vai a… · {n} note' },
  'barra2.radice-vault': 'vault',
  'barra2.oggi': 'oggi',
  'barra2.cerca-nota-segnaposto': 'Cerca una nota: corso, lezione, data…',
  'barra2.cerca-nota': 'Cerca una nota',
  'barra2.nessuna-nota': 'Nessuna nota trovata.',
  'barra2.sintesi-cerco': 'cerco «{q}»',
  'barra2.sintesi-note': 'note',
  'barra2.niente-appunti-di': 'Non trovo appunti di **{corso}** negli ultimi giorni.',
  'barra2.niente-appunti': 'Non trovo una lezione con abbastanza appunti: scrivili nella sezione «{sezione}» della nota.',
  'barra2.appunti-serve-ai': 'Per leggere gli appunti serve l\'AI: installa il **cervello locale** (gratis, funziona offline) da «Prepara Lode», oppure collega la tua AI: scrivi «AI».',
  'barra2.leggo-appunti-di': 'Leggo gli appunti di {corso}…',
  'barra2.appunti-illeggibili': 'Non sono riuscito a leggere gli appunti: {errore}',
  'barra2.nessuna-definizione-nuova': 'Negli appunti non ho trovato definizioni nuove. Prova a scriverle per esteso, anche brevi.',
  'barra2.aggiungere-a': 'Aggiungere a {corso} · {data}?',
  'barra2.chiudi-nota': { one: '{n} definizioni nella nota della lezione. Controlla che siano giuste: le ha scritte {motore}.', other: '{n} definizioni nella nota della lezione. Controlla che siano giuste: le ha scritte {motore}.' },
  'barra2.chiudi-nota-stelle': { one: '{n} definizioni e {stelle} ★ nella nota della lezione. Controlla che siano giuste: le ha scritte {motore}.', other: '{n} definizioni e {stelle} ★ nella nota della lezione. Controlla che siano giuste: le ha scritte {motore}.' },
  'barra2.lezione-chiusa': 'Lezione chiusa.',
  'barra2.definizioni-pronte': { one: '{n} definizioni pronte per i giochi.', other: '{n} definizioni pronte per i giochi.' },
  'barra2.sintesi-definizioni': { one: '{n} definizioni', other: '{n} definizioni' },
  'barra2.appunti-sparsi-oggi': 'gli appunti sparsi di oggi',
  'barra2.la-nota-di': 'la nota di {corso}',
  'barra2.apro-in-obsidian': 'Apro {nome} in Obsidian.',
  'barra2.apro-se-non-trova': 'Apro {nome}. Se Obsidian non trova il vault, la prima volta fai **Apri cartella come vault** e scegli la cartella «{percorso}»: poi resta collegato.',
  'barra2.aperto-editor': 'Ho aperto {nome} con l\'editor di sistema. Con **Obsidian** (gratis, obsidian.md) il vault «{percorso}» è già pronto: cartelle, modelli, orario e la tua memoria.',
  'barra2.nota-non-si-apre': 'Non riesco ad aprire la nota: {errore}',
  'barra2.appunti-solo-app': 'Gli appunti in Obsidian sono nell\'**app desktop** di Lode: lì ogni lezione diventa una nota del tuo vault, con le ★ e le definizioni che segni dalla barra.',
  'barra2.gioco-sai-gia-di': 'Le definizioni di {corso} per oggi le sai già: tornano quando stanno per scappare.',
  'barra2.gioco-sai-gia': 'Le definizioni per oggi le sai già: tornano quando stanno per scappare.',
  'barra2.gioco-nessuna-di': 'Ancora nessuna definizione di {corso}. In aula premi **Definizione** (o scrivi «def: termine = definizione»), oppure scrivile in Obsidian nella sezione «{sezione}» della lezione.',
  'barra2.gioco-nessuna': 'Ancora nessuna definizione. In aula premi **Definizione** (o scrivi «def: termine = definizione»), oppure scrivile in Obsidian nella sezione «{sezione}» della lezione.',
  'barra2.gioco-di': 'Gioco · {corso}',
  'barra2.ultime-lezioni': 'ultime lezioni',
  'barra2.manche-di': '{i} di {n}',
  'barra2.abbina': 'Abbina ogni termine alla sua definizione.',
  'barra2.chi-sono': 'Chi sono?',
  'barra2.completa': '{termine}: completa la definizione.',
  'barra2.parola-mancante': 'Parola mancante',
  'barra2.controlla-invio': 'Controlla <kbd>Invio</kbd>',
  'barra2.non-la-so': 'Non la so',
  'barra2.te-la-ricordi': 'Te la ricordi?',
  'barra2.mostra-spazio': 'Mostra <kbd>Spazio</kbd>',
  'barra2.non-la-sapevo': 'Non la sapevo <kbd>1</kbd>',
  'barra2.la-sapevo': 'La sapevo <kbd>2</kbd>',
  'barra2.tutte-giuste': 'Tutte giuste. Queste restano.',
  'barra2.da-rinforzare': 'Da rinforzare: {elenco}. Tornano domani.',
  'barra2.secondi': { one: '{n} secondi', other: '{n} secondi' },
  'barra2.minuti': '{n} min',
  'barra2.sintesi-punti': '{punti} su {tot}',
  'barra2.ancora-una': 'Ancora una',
  'barra2.gioca-ancora': 'Gioca ancora',
  'barra2.sintesi-gioco': 'gioco',
  'barra2.pausa-finita': 'Pausa finita.',
  'barra2.fermato-dopo': 'Fermato dopo {tempo}.',
  'barra2.prova-resta-aperta': 'La prova resta aperta: scrivi «prova generale» per consegnarla.',
  'barra2.li-conto': 'Li conto nelle ore di studio.',
  'barra2.sintesi-timer-fermato': 'timer fermato',
  'barra2.nessun-timer': 'Non c\'è nessun timer acceso.',
  'barra2.timer-in-pausa': 'Timer in pausa.',
  'barra2.scrivi-riprendi': 'Scrivi «riprendi» quando torni.',
  'barra2.si-riparte': 'Si riparte.',
  'barra2.focus-esame-sconosciuto': 'Non trovo **{nome}** tra i tuoi esami. Faccio partire lo studio libero? Scrivi «focus {min}».',
  'barra2.di-quale-esame': 'Di quale esame?',
  'barra2.idoneita-registrata': '{nome}: idoneità registrata.',
  'barra2.voto-in': '{voto} in {nome}.',
  'barra2.voto-lode-in': '{voto} e lode in {nome}.',
  'barra2.nuovo-esame-6-cfu': 'Nuovo esame da 6 CFU: correggi i CFU nel libretto.',
  'barra2.media-diff': 'Media {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome}: {voto}',
  'barra2.idoneita': 'idoneità',
  'barra2.trenta-e-lode': 'Trenta e lode. Questa si festeggia.',
  'barra2.bel-colpo': 'Bel colpo. Respira oggi, domani si riparte.',
  'barra2.esame-aggiornato': '{nome} aggiornato.',
  'barra2.esame-aggiunto': '{nome} aggiunto.',
  'barra2.esame-nota': '{quando} · {cfu} CFU',
  'barra2.esame-nota-cambiali': '{quando} · {cfu} CFU (cambiali se sono di più)',
  'barra2.senza-data': 'senza data',
  'barra2.piano-ore': 'Per arrivarci pronto: circa **{h} h al giorno** ({tot} h in tutto).',
  'barra2.proposte-spente-riaccendi': 'Le proposte sono spente: le riaccendi con «proposte normali».',
  'barra2.proposte-da-adesso': 'Da adesso, quando sei al computer e libero, ti propongo giochi, ripassi e domande su {nome}.',
  'barra2.proposte-da-adesso-vicino': 'Da adesso, quando sei al computer e libero, ti propongo giochi, ripassi e domande su {nome}, sempre più spesso man mano che si avvicina.',
  'barra2.carta-aggiunta': 'Carta aggiunta.',
  'barra2.senza-esame': 'senza esame',
  'barra2.esame-sconosciuto': 'Non trovo **{nome}** tra i tuoi esami.',
  'barra2.spiego-senza-programma': 'Prima incolla il programma di un esame («programma di analisi 2»): poi mi spieghi i suoi argomenti e ti dico cosa hai saltato.',
  'barra2.argomento-sconosciuto': 'Non trovo **{q}** nei programmi dei tuoi esami.',
  'barra2.esame-non-trovato': 'Non trovo l\'esame **{nome}**.',
  'barra2.domande-di-quale-esame': 'Di quale esame? Per esempio: «domande uscite di analisi 2: …».',
  'barra2.nella-nota-lezione': 'Nella nota della lezione.',
  'barra2.in-orario': '{corso} in orario.',
  'barra2.aula': 'aula {aula}',
  'barra2.sintesi-in-orario': '{corso} in orario',
  'barra2.orario-spiegazione': 'Quando sei a lezione la barra lo sa: si apre sulla cattura veloce (★ da esame, definizioni, domande) e a casa ti propone due minuti di gioco su quello che hai appena fatto.',
  'barra2.proposte-spente': 'Proposte spente.',
  'barra2.proposte-poche': 'Proposte poche.',
  'barra2.proposte-normali': 'Proposte normali.',
  'barra2.proposte-frequenti': 'Proposte frequenti.',
  'barra2.riaccendi-quando-vuoi': 'Le riaccendi quando vuoi.',
  'barra2.proposte-mai-quando': 'Mai a lezione, al lavoro, in focus o nelle ore di silenzio.',
  'barra2.niente-da-proporre': 'Per ora non ho niente da proporti: aggiungi un esame con la data, o segna qualche definizione a lezione.',
  'barra2.trascrizione-in-pausa': 'Trascrizione in pausa.',
  'barra2.scrivi-riprendi-trascrizione': 'Scrivi «riprendi trascrizione» quando ricomincia.',
  'barra2.riprendo-trascrivere': 'Riprendo a trascrivere.',
  'barra2.err-valutato': 'Progetto valutato: la correzione non te la mostro.',
  'barra2.errore-spiegato': 'Errore spiegato',
  'barra2.correzione-vista': 'correzione vista',
  'barra2.copia-errore': 'Copia l\'errore dal terminale (o dall\'IDE) e riscrivi «spiegami l\'errore».',
  'barra2.incolla-errore': 'Incolla l\'errore dopo i due punti: «spiegami l\'errore: …».',
  'barra2.nessun-errore-nel-testo': 'In questo testo non trovo un errore del compilatore o del programma. Copia tutto, dalla riga con il nome del file, e riprova.',
  'barra2.segui-valutato': 'Segui un progetto valutato: la correzione non te la mostro.',
  'barra2.diario-solo-app': 'Il diario sta nel vault: serve l\'**app desktop** di Lode.',
  'barra2.progetto-sconosciuto': 'Non trovo un progetto che si chiama «{nome}».',
  'barra2.nessun-progetto-segui': 'Non seguo ancora nessun progetto. Scrivi **segui progetto** e scegli la cartella del laboratorio.',
  'barra2.diario-spento-per': 'Per **{progetto}** il diario è spento: nel vault non scrivo niente. Lo riaccendi con «accendi il diario di {progetto}».',
  'barra2.diario-non-si-apre': 'Non riesco ad aprire il diario: {errore}',
  'barra2.diario-di': 'Diario di {progetto}.',
  'barra2.aperto-editor-sistema': 'Aperto con l\'editor di sistema: con Obsidian è più comodo.',
  'barra2.aperto-in-obsidian': '{file} · aperto in Obsidian.',
  'barra2.sintesi-diario-di': 'diario di {progetto}',
  'barra2.nessun-progetto': 'Non seguo ancora nessun progetto.',
  'barra2.diario-acceso': 'Diario di {nome} acceso.',
  'barra2.diario-acceso-nota': 'Scrivo nel vault quello che vedo: cosa cambia e le prove. Non so chi scrive le righe.',
  'barra2.diario-spento': 'Diario di {nome} spento.',
  'barra2.diario-spento-nota': 'Da adesso nel vault non scrivo niente di questo progetto. Le note già scritte restano: puoi toglierle da Obsidian.',
  'barra2.focus-di-minuti': 'Focus di {min} minuti.',
  'barra2.focus-di-minuti-su': 'Focus di {min} minuti su {nome}.',
  'barra2.salvare-carte': { one: 'Salvare {n} carta?', other: 'Salvare {n} carte?' },
  'barra2.salvare-carte-di': { one: 'Salvare {n} carta di {nome}?', other: 'Salvare {n} carte di {nome}?' },
  'barra2.entrano-ripasso': 'Entrano nel ripasso di oggi.',
  'barra2.carte-salvate': { one: '{n} carte salvate.', other: '{n} carte salvate.' },
  'barra2.ripassa-ora': 'Ripassa ora',
  'barra2.sintesi-carte': { one: '{n} carte', other: '{n} carte' },
  'barra2.aggiungere-esame': 'Aggiungere {nome}?',
  'barra2.esame': 'Esame',
  'barra2.cfu': 'CFU',
  'barra2.appello': 'Appello',
  'barra2.registrare-voto': 'Registrare {voto}?',
  'barra2.registrare-voto-lode': 'Registrare {voto} e lode?',
  'barra2.esame-nuovo-6-cfu': '{nome} (nuovo, 6 CFU)',
  'barra2.voto': 'Voto',
  'barra2.voto-e-lode': '{voto} e lode',
  'barra2.voto-registrato': 'Voto registrato.',
  'barra2.media': 'Media {media}',
  'barra2.leggo-il-file': 'Leggo il file…',
  'barra2.prof-ci-pensa': 'Il prof ci pensa…',
  'barra2.un-attimo': 'Un attimo…',
  'barra2.file-senza-carte-locale': 'Da questo file non ho tirato fuori carte: se è un PDF, il modello locale non lo legge. Prova con una foto delle pagine o col testo.',
  'barra2.file-illeggibile': 'Non sono riuscito a leggere il file: {errore}',
  'barra2.chiave-non-valida-ricollega': 'La chiave non è valida: ricollegala scrivendo «AI».',
  'barra2.troppe-richieste': 'Troppe richieste in poco tempo: riprova tra un minuto.',
  'barra2.sovraccarico': '{motore} è sovraccarico in questo momento: riprova tra poco.',
  'barra2.manca-rete': 'Sembra che manchi la rete.',
  'barra2.qualcosa-non-andato': 'Qualcosa non è andato: {errore}',
  'barra2.orale-serve-ai-app': 'Per l\'interrogazione serve l\'AI: installa il **cervello locale** da «Prepara Lode» (gratis, offline) o collega la tua AI (scrivi «AI»). Intanto puoi fare il **ripasso** delle carte.',
  'barra2.orale-serve-ai-web': 'Per l\'interrogazione serve l\'AI: aggiungi la tua chiave Claude in **Impostazioni** (costa pochi centesimi a sessione). Intanto puoi fare il **ripasso** delle carte.',
  'barra2.orale-esame-sconosciuto': 'Non trovo **{nome}**: ti interrogo comunque su quello.',
  'barra2.su-quale-esame': 'Su quale esame?',
  'barra2.aggiungi-prima-esame': 'Aggiungi prima un esame.',
  'barra2.interrogami-su': 'Interrogami su {nome}',
  'barra2.orale-di-contesto': 'Orale · <b>{nome}</b>',
  'barra2.esci': 'Esci',
  'barra2.sintesi-orale-di': 'orale di {nome}',
  'barra2.domanda-n-di': '**Domanda {n} di {max}.** {domanda}',
  'barra2.prof-non-risponde': 'Il prof non risponde: {errore}',
  'barra2.prof-ascolta': 'Il prof ascolta…',
  'barra2.orale-mancava': 'Mancava: {cosa}',
  'barra2.era-giusta': 'Era giusta',
  'barra2.segnata-giusta': 'Segnata giusta',
  'barra2.prof-scrive-voto': 'Il prof scrive il voto…',
  'barra2.orale-titolo': { one: 'Orale · {nome} · {n} domanda', other: 'Orale · {nome} · {n} domande' },
  'barra2.da-ripassare': 'Da ripassare',
  'barra2.orale-calcolo': 'Il voto lo calcola Lode dalle tue risposte (giusta 3 punti, parziale 2).',
  'barra2.orale-calcolo-contestate': { one: 'Il voto lo calcola Lode dalle tue risposte (giusta 3 punti, parziale 2), contando la risposta che hai segnato giusta.', other: 'Il voto lo calcola Lode dalle tue risposte (giusta 3 punti, parziale 2), contando le risposte che hai segnato giuste.' },
  'barra2.orale-giudizi-locale': 'I giudizi sono il parere del modello locale: può sbagliare. È un allenamento, non una previsione.',
  'barra2.orale-giudizi-ai': 'I giudizi sono il parere dell\'AI. È un allenamento, non una previsione.',
  'barra2.sintesi-orale-voto': 'orale di {nome}: {voto}',
  'barra2.orale-chiuso': 'Orale chiuso.',
  'barra2.ripassa-esitato': 'Ripassa le domande dove hai esitato.',
  'barra2.agenti-solo-app': 'Il ponte con gli agenti è nell\'**app desktop** di Lode.',
  'barra2.ponte-non-risponde': 'Il ponte non risponde: {errore}',
  'barra2.agente-sconosciuto': 'Non so ancora collegarmi a **{agente}**. Scrivi «agenti» per vedere quelli che conosco.',
  'barra2.agenti-titolo': 'Agenti di programmazione',
  'barra2.agenti-spiegazione': 'Collega l\'agente che usi per i laboratori: a fine turno Lode ti dice cosa ha toccato davvero nei progetti che segui, se ha lanciato i test dopo l\'ultima modifica e se ha cambiato i test mentre fallivano.',
  'barra2.ag-collegato-eventi': { one: 'collegato · {n} eventi, l\'ultimo alle {ora}', other: 'collegato · {n} eventi, l\'ultimo alle {ora}' },
  'barra2.ag-collegato-nessuno': 'collegato · ancora nessun evento',
  'barra2.ag-trovato': 'trovato su questo computer',
  'barra2.ag-non-trovato': 'non trovato',
  'barra2.scollega': 'Scollega',
  'barra2.agenti-nota': 'Solo lettura: Lode non risponde agli agenti, non decide niente e non allarga i loro permessi. Prima di scrivere nella loro configurazione ti mostra le righe esatte. Gli eventi contano solo nei progetti che segui («segui progetto»), gli altri si buttano; il testo che scrivi all\'agente non si salva.',
  'barra2.sintesi-agenti': 'agenti',
  'barra2.niente-toccato': 'Va bene, non ho toccato niente.',
  'barra2.ag-scollegato': '{nome} scollegato.',
  'barra2.ag-gia-collegato': '{nome} era già collegato.',
  'barra2.ag-collegato': '{nome} collegato.',
  'barra2.ag-tolte-righe': 'Ho tolto solo le mie righe.',
  'barra2.ag-poi-segui': 'Poi segui il progetto del laboratorio («segui progetto»).',
  'barra2.l-agente': 'L\'agente',
  'barra2.ag-finito-test-dopo': { one: 'ha finito: {n} file, test lanciati dopo l\'ultima modifica', other: 'ha finito: {n} file, test lanciati dopo l\'ultima modifica' },
  'barra2.ag-finito-test-prima': { one: 'ha finito: {n} file, test non rilanciati', other: 'ha finito: {n} file, test non rilanciati' },
  'barra2.ag-finito-senza-test': { one: 'ha finito: {n} file, nessun test', other: 'ha finito: {n} file, nessun test' },
  'barra2.guarda': 'Guarda',
  'barra2.nessun-turno': 'Ancora nessun turno di un agente nei progetti che segui. Scrivi «agenti» per collegarne uno.',
  'barra2.esito-non-noto': 'esito non noto',
  'barra2.riuscito': 'riuscito',
  'barra2.fallito-codice': 'fallito (codice {codice})',
  'barra2.alle': 'alle {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> file toccato: {elenco}.', other: '<b>{n}</b> file toccati: {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> file toccati.',
  'barra2.comandi': { one: '{n} comando', other: '{n} comandi' },
  'barra2.test-lanciati-dopo': { one: 'test lanciati {n} volta, l\'ultima <code>{comando}</code> {esito}, dopo l\'ultima modifica', other: 'test lanciati {n} volte, l\'ultima <code>{comando}</code> {esito}, dopo l\'ultima modifica' },
  'barra2.test-lanciati-prima': { one: 'test lanciati {n} volta, l\'ultima <code>{comando}</code> {esito}, <b>prima</b> dell\'ultima modifica', other: 'test lanciati {n} volte, l\'ultima <code>{comando}</code> {esito}, <b>prima</b> dell\'ultima modifica' },
  'barra2.nessun-test-lanciato': 'nessun test lanciato',
  'barra2.cosa-cambiato': 'Cosa è cambiato',
  'barra2.prova-tu': 'Prova tu',
  'barra2.preparati-discussione': 'Preparati alla discussione',
  'barra2.parole-agente': 'Quello che dice l\'agente sono parole: le prove le ha lanciate davvero solo se le vedi qui. Le regole sono fisse: se non trovano niente, non è una garanzia.',
  'barra2.prova-il-progetto': 'Prova il progetto',
  'barra2.sintesi-turno': { one: '{chi}: {n} file', other: '{chi}: {n} file' },
};
