// Testi della barra, terza parte (italiano, lingua di partenza): ripasso in tasca, Moodle, quiz a crocette, temi d'esame,
// prova generale, programma d'esame, «te lo spiego io», invio, file, voce, scorciatoie e avvisi dell'app (js/lode.js).
export default {
  // Ripasso in tasca
  'barra3.tasca-solo-app': 'Il ripasso in tasca va nell\'app: serve il vault di Obsidian.',
  'barra3.tasca-spenta': 'Ripasso in tasca solo quando lo chiedi.',
  'barra3.tasca-spenta-nota': 'La nota {nota} resta nel vault: scrivi «ripasso in tasca» per aggiornarla.',
  'barra3.tasca-spenta-sintesi': 'ripasso in tasca spento',
  'barra3.tasca-preparo': 'Preparo la nota…',
  'barra3.tasca-errore': 'Non riesco a leggere o scrivere la nota {nota}: {errore}',
  'barra3.tasca-estranea': 'Nel vault c\'è già una nota **{nota}** che non ha scritto Lode: non la tocco. Rinominala e riprova.',
  'barra3.tasca-segnata-sapevi': 'Ho segnato la carta che hai fatto sul telefono: la sapevi.',
  'barra3.tasca-segnata-non-sapevi': 'Ho segnato la carta che hai fatto sul telefono: non la sapevi.',
  'barra3.tasca-segnate': 'Ho segnato {n} carte che hai fatto sul telefono: {sapevo} sapevi, {no} no.',
  'barra3.tasca-gia': { one: 'Una carta l\'avevi già ripassata sul computer: non la segno due volte.', other: '{n} carte le avevi già ripassate sul computer: non le segno due volte.' },
  'barra3.tasca-vecchia': 'La nota sul telefono è di un giro vecchio: non segno niente.',
  'barra3.tasca-cambiata': 'La nota sta ancora cambiando: Obsidian la sta sincronizzando. Non la riscrivo adesso, riprova tra un minuto.',
  'barra3.tasca-domani': { one: 'Nella nota {nota} c\'è {n} carta per domani.', other: 'Nella nota {nota} ci sono {n} carte per domani.' },
  'barra3.tasca-domani-niente': 'Domani non hai carte da ripassare: la nota {nota} lo dice.',
  'barra3.tasca-titolo': 'Ripasso in tasca',
  'barra3.tasca-aspetta': 'Aspetta che il telefono finisca di sincronizzare e riprova. Se la nota giusta non arriva, riscrivila: le spunte di quella copia non le segno.',
  'barra3.apri-nota': 'Apri la nota',
  'barra3.riscrivi-nota': 'Riscrivi la nota',
  'barra3.tasca-solo-quando': 'Solo quando lo chiedo',
  'barra3.tasca-ogni-sera': 'Ogni sera',
  'barra3.tasca-sera-accesa': 'Ogni sera dopo le 19 la riscrivo da sola, se Lode è aperto.',
  'barra3.tasca-sera-spenta': 'La riscrivo solo quando me lo chiedi.',
  'barra3.tasca-come-arriva': 'Funziona se il vault arriva sul telefono (iCloud, Obsidian Sync, Syncthing). Lode non usa la rete: la nota la porta il servizio che usi già.',
  'barra3.non-apro-nota': 'Non riesco ad aprire la nota: {errore}',
  'barra3.tasca-riscrivi-detto': 'Riscrivi la nota {nota}',
  'barra3.tasca-sintesi': 'ripasso in tasca',

  // Moodle
  'barra3.moodle-solo-app': 'Il collegamento a Moodle è nell\'**app desktop** di Lode.',
  'barra3.moodle-non-risponde': 'Moodle non risponde: {errore}',
  'barra3.moodle-non-collegato': 'Moodle non è collegato.',
  'barra3.moodle-scollegato': 'Moodle scollegato.',
  'barra3.moodle-scollegato-nota': 'Il token è cancellato da questo computer. I file già presi restano nel tuo vault.',
  'barra3.moodle-corsi-seguiti': { one: '{n} corso seguito: {corsi}', other: '{n} corsi seguiti: {corsi}' },
  'barra3.file-nuovi': 'File nuovi',
  'barra3.scadenze': 'Scadenze',
  'barra3.corsi': 'Corsi',
  'barra3.scollega': 'Scollega',
  'barra3.moodle-senza-portachiavi': 'Questo computer non ha un portachiavi: il collegamento vale fino a quando chiudi Lode.',
  'barra3.moodle-novita-detto': 'Novità da Moodle',
  'barra3.moodle-corsi-detto': 'Corsi di Moodle',
  'barra3.moodle-scollega-detto': 'Scollega Moodle',
  'barra3.moodle-collega': 'Collega Moodle',
  'barra3.moodle-collega-intro': 'La piattaforma dei corsi del tuo ateneo (Virtuale, Ariel, e-learning…): Lode prende i file nuovi e le scadenze dei corsi che scegli. Solo lettura: non consegna niente e non scrive niente.',
  'barra3.moodle-indirizzo-esempio': 'Indirizzo, per esempio virtuale.unibo.it',
  'barra3.moodle-indirizzo': 'Indirizzo di Moodle',
  'barra3.continua': 'Continua',
  'barra3.moodle-collega-nota': 'Entri come nell\'app Moodle ufficiale. Il collegamento resta cifrato su questo computer, mai nel vault; con «scollega moodle» lo togli.',
  'barra3.moodle-cerco': 'Cerco il sito…',
  'barra3.moodle-non-indirizzo': 'Questo non sembra un indirizzo.',
  'barra3.moodle-non-trovo': 'Non trovo un Moodle con l\'app attiva a questo indirizzo ({motivo}). Copia l\'indirizzo dalla barra del browser quando sei sulla pagina dei tuoi corsi.',
  'barra3.moodle-accesso-annullato': 'Accesso annullato.',
  'barra3.moodle-accesso-fallito': 'Accesso non riuscito: {motivo}.',
  'barra3.moodle-entra-sso': '<b>{nome}</b> · si entra con il login dell\'ateneo (SPID o le credenziali d\'ateneo), in una finestra di Lode.',
  'barra3.accedi': 'Accedi',
  'barra3.moodle-accedi-finestra': 'Accedi nella finestra che si è aperta…',
  'barra3.moodle-entra-password': '<b>{nome}</b> · accesso con utente e password di Moodle.',
  'barra3.utente': 'Utente',
  'barra3.password': 'Password',
  'barra3.moodle-password-nota': 'La password va solo a Moodle: Lode non la salva.',
  'barra3.moodle-collega-sintesi': 'collega Moodle',
  'barra3.moodle-leggo-corsi': 'Leggo i tuoi corsi…',
  'barra3.moodle-corsi-errore': 'Non riesco a leggere i corsi: {errore}',
  'barra3.moodle-nessun-corso': 'Su Moodle non risulti iscritto a nessun corso.',
  'barra3.moodle-corsi-titolo': 'Corsi di Moodle · {sito}',
  'barra3.moodle-scegli-corsi': 'Scegli quali seguire e con quale corso di Lode: i loro file nuovi arrivano qui.',
  'barra3.concluso': 'concluso',
  'barra3.moodle-corso-per': 'Corso di Lode per {nome}',
  'barra3.non-seguire': 'Non seguire',
  'barra3.moodle-con-nome': 'Con il nome di Moodle',
  'barra3.salva': 'Salva',
  'barra3.moodle-seguo': { one: 'Seguo {n} corso su Moodle.', other: 'Seguo {n} corsi su Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Nessun corso seguito.',
  'barra3.moodle-ti-avviso': 'Ti avviso quando arrivano file nuovi.',
  'barra3.moodle-corsi-sintesi': 'corsi di Moodle',
  'barra3.moodle-guardo': 'Guardo i file su Moodle…',
  'barra3.moodle-non-leggo': 'Non riesco a leggere {corsi}: {errore}.',
  'barra3.moodle-nessun-file': 'Nei corsi che segui non ci sono ancora file.',
  'barra3.moodle-piu-recenti': 'i file più recenti',
  'barra3.moodle-file-nuovi': { one: '{n} file nuovo', other: '{n} file nuovi' },
  'barra3.moodle-niente-nuovo': 'niente di nuovo, gli ultimi file',
  'barra3.nuovo': 'nuovo',
  'barra3.apri': 'Apri',
  'barra3.moodle-apri-nota': '«Apri» lo porta in Lode come se lo avessi trascinato: carte, riassunto, programma, quiz.',
  'barra3.scarico': 'Scarico…',
  'barra3.non-riesco': 'Non riesco',
  'barra3.aperto': 'Aperto',
  'barra3.moodle-file-da': '{nome} da Moodle',
  'barra3.file-illeggibile': 'Non riesco a leggere il file: {errore}',
  'barra3.moodle-sintesi-nuovi': 'Moodle: {n} file nuovi',
  'barra3.moodle-nessuna-scadenza': 'Nessuna scadenza su Moodle nelle prossime settimane.',
  'barra3.moodle-scadenze-titolo': 'Scadenze su Moodle',
  'barra3.scadenze-sintesi': '{n} scadenze',
  'barra3.guarda': 'Guarda',
//FINE
};
