// Testi del benvenuto (italiano, lingua di partenza): i passi obbligatori (nome, installazioni) e il setup veloce
// (corso, libretto, esami, orario, abitudini), più il collegamento a una Lode che c'è già su un altro computer.
export default {
  // la cornice
  'benvenuto.tasti-mac': '⌥ Spazio',
  'benvenuto.tasti-altri': 'Ctrl ⇧ Spazio',
  'benvenuto.avanti': 'Avanti',
  'benvenuto.indietro': 'Indietro',
  'benvenuto.salta': 'Salta',
  'benvenuto.obbligatorio': 'Obbligatorio',
  'benvenuto.facoltativo': 'Facoltativo · setup veloce',
  // ciao
  'benvenuto.ciao-titolo': 'Ciao.<br>Io sono Lode.',
  'benvenuto.ciao-sotto': 'Vivo in una piccola barra in cima allo schermo. In aula non ti faccio perdere niente, a casa ti alleno su quello che stai per dimenticare, e tengo tutto nel tuo Obsidian.',
  'benvenuto.ciao-nota': 'Prima tre cose necessarie (due minuti, più i download). Poi, se vuoi, il setup veloce.',
  'benvenuto.altro-computer': 'Uso già Lode su un altro computer',
  'benvenuto.sperimentale': '(sperimentale)',
  'benvenuto.iniziamo': 'Iniziamo',
  // un altro computer
  'benvenuto.scegli-vault-cloud': 'Scegli il vault di Lode nella tua cartella cloud (iCloud Drive, OneDrive, Dropbox, Google Drive).',
  'benvenuto.scegli-vault': 'Scegli il vault…',
  'benvenuto.password-dati': 'La password dei dati di Lode, se l\'hai messa',
  'benvenuto.collego': 'Collego…',
  'benvenuto.cartella-no': 'Non riesco a usare quella cartella.',
  'benvenuto.ricevo-dati': 'Ricevo i dati dagli altri computer… Lode è già usabile: arrivano da soli.',
  'benvenuto.inizia': 'Inizia',
  'benvenuto.password-sbagliata': 'Password sbagliata: riprova.',
  'benvenuto.password-serve': 'I dati di Lode sono protetti da una password: scrivila qui sopra.',
  // nome
  'benvenuto.nome-titolo': 'Come ti chiami?',
  'benvenuto.nome-sotto': 'Solo per salutarti. Resta sul tuo computer.',
  'benvenuto.nome-segnaposto': 'Il tuo nome',
  'benvenuto.togli-esempio': 'Togli i dati di esempio di «Giulia» (esami, voti, carte e ore di studio finti). Le cose che hai aggiunto tu restano.',
  // installazioni
  'benvenuto.web-titolo': 'Lode completa vive nell\'app.',
  'benvenuto.web-sotto': 'Nel browser hai libretto, timer, ripasso e giochi. Obsidian, l\'AI sul computer, la voce e la trascrizione delle lezioni sono nell\'app desktop.',
  'benvenuto.installa-titolo': 'Prepariamo il tuo computer.',
  'benvenuto.installa-sotto': 'Tre installazioni, una volta sola. Poi Lode funziona anche senza internet, e niente di tuo esce dal computer.',
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'dove vivono i tuoi appunti: un vault già pronto',
  'benvenuto.cervello': 'Il cervello locale',
  'benvenuto.cervello-cosa': 'Ollama e Qwen3.5: legge gli appunti, crea carte e definizioni, spiega e interroga',
  'benvenuto.voce': 'La voce',
  'benvenuto.voce-cosa': '{voce}: comandi a voce, «Ripeti» e trascrizione delle lezioni',
  'benvenuto.peso-gb': '{n} GB',
  'benvenuto.peso-mb': '{n} MB',
  'benvenuto.installa-nota': 'Obsidian è gratis per uso personale e viene dal suo sito ufficiale. Il cervello locale si sceglie in base alla memoria del computer.',
  'benvenuto.installa-tutto': 'Installa tutto',
  'benvenuto.gia-installato': 'Già installato',
  'benvenuto.modello-pronto': '{modello} è già pronto',
  'benvenuto.gia-pronta': 'Già pronta',
  'benvenuto.voce-pronta': '{voce} è pronto',
  'benvenuto.scarico-voce-pct': 'Scarico la voce · {p}%',
  'benvenuto.tutto-pronto': 'Obsidian, il cervello locale e la voce sono pronti.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'il cervello locale',
  'benvenuto.scarico-voce': 'la voce',
  'benvenuto.scarico-pct': '{cosa} {p}%',
  'benvenuto.scarico-continua-voce': 'Sto ancora scaricando: {cosa}. Continua da solo, anche a finestra chiusa; la voce riprende nella barra appena apri Lode.',
  'benvenuto.scarico-continua': 'Sto ancora scaricando: {cosa}. Continua da solo, anche a finestra chiusa.',
  'benvenuto.scarico-solo-voce': 'Sto ancora scaricando: {cosa}. La voce riprende nella barra appena apri Lode.',
  // setup veloce
  'benvenuto.veloce-titolo': '{nome}, vuoi il setup veloce?',
  'benvenuto.veloce-sotto': 'Raccontami università, esami e orari: da domani Lode sa quando sei a lezione, quanto ti manca alla laurea e cosa ripassare prima di ogni appello.',
  'benvenuto.veloce-lista': ['Ateneo e corso di laurea', 'Il libretto, incollato da Esse3 o scritto a mano', 'Gli esami da dare, con le date', 'L\'orario delle lezioni, anche dal calendario dell\'ateneo (.ics)', 'Come e quando studi'],
  'benvenuto.veloce-nota': 'Tutto facoltativo, tutto modificabile dopo. Niente va su internet.',
  'benvenuto.facciamolo': 'Facciamolo',
  // corso
  'benvenuto.corso-titolo': 'Dove studi?',
  'benvenuto.ateneo': 'Ateneo',
  'benvenuto.ateneo-segnaposto': 'Inizia a scrivere…',
  'benvenuto.corso': 'Corso di laurea',
  'benvenuto.corso-segnaposto': 'Ingegneria informatica',
  'benvenuto.tipo': 'Tipo',
  'benvenuto.tipo-180': 'Triennale · 180 CFU',
  'benvenuto.tipo-120': 'Magistrale · 120 CFU',
  'benvenuto.tipo-300': 'Ciclo unico · 300 CFU',
  'benvenuto.tipo-360': 'Ciclo unico · 360 CFU',
  'benvenuto.anno': 'Anno',
  'benvenuto.anni': ['1°', '2°', '3°', '4°', '5°', '6°', 'Fuori corso'],
  'benvenuto.lode-vale': 'La lode vale',
  'benvenuto.lode-nota': 'Dipende dal regolamento: nel dubbio 30',
  // libretto
  'benvenuto.libretto-titolo': 'Gli esami che hai già dato',
  'benvenuto.libretto-sotto': 'Apri il libretto sul portale dell\'ateneo (Esse3, Infostud…), seleziona tutto, copia e incolla qui. Ci penso io. Oppure scrivili una riga ciascuno: «Analisi 1, 9 CFU, 28».',
  'benvenuto.libretto-segnaposto': 'Incolla qui il libretto…',
  'benvenuto.leggi-libretto': 'Leggi il libretto',
  'benvenuto.leggo-libretto': 'Leggo il libretto…',
  'benvenuto.leggo': 'Leggo…',
  'benvenuto.esami-trovati': { one: '{n} esame trovato: controlla e conferma.', other: '{n} esami trovati: controlla e conferma.' },
  'benvenuto.esami-non-trovati': 'Non ho trovato esami: prova a scriverli una riga ciascuno.',
  'benvenuto.col-esame': 'Esame',
  'benvenuto.col-cfu': 'CFU',
  'benvenuto.col-voto': 'Voto',
  'benvenuto.col-data': 'Data',
  'benvenuto.importa': 'Importa',
  'benvenuto.idoneo': 'idoneo',
  'benvenuto.voto-lode': '{voto}L',
  // esami da dare
  'benvenuto.esame': 'Esame',
  'benvenuto.cfu': 'CFU',
  'benvenuto.data-appello': 'Data dell\'appello',
  'benvenuto.togli': 'Togli',
  'benvenuto.esami-titolo': 'Gli esami da dare',
  'benvenuto.esami-sotto': 'Con la data dell\'appello, se la sai. Da lì Lode calcola quante ore ti servono ogni giorno e ti propone ripassi e giochi quando hai un momento.',
  'benvenuto.altro-esame': '+ Un altro esame',
  // orario
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · aula {aula}',
  'benvenuto.nessuna-lezione': 'Ancora nessuna lezione.',
  'benvenuto.orario-titolo': 'L\'orario delle lezioni',
  'benvenuto.orario-sotto': 'Così Lode sa quando sei in aula: la barra si prepara alla lezione, «Ripeti» e la trascrizione sono a un tasto, e a casa ti allena su quello che hai appena sentito.',
  'benvenuto.scrivila': 'Scrivila come la diresti',
  'benvenuto.frase-segnaposto': 'analisi 2 lunedì e mercoledì 9-11 aula 7',
  'benvenuto.aggiungi': 'Aggiungi',
  'benvenuto.importa-ics': 'Importa il calendario (.ics)',
  'benvenuto.incolla-orario': 'Oppure incolla l\'orario dal sito dell\'ateneo',
  'benvenuto.orario-segnaposto': 'Incolla qui la tabella dell\'orario…',
  'benvenuto.leggi-orario': 'Leggi l\'orario',
  'benvenuto.frase-aiuto': 'Scrivi corso, giorni e ore: «fisica lunedì 14-16 aula B2».',
  'benvenuto.lezioni-calendario': { one: '{n} lezione dal calendario.', other: '{n} lezioni dal calendario.' },
  'benvenuto.calendario-vuoto': 'Nel calendario non ho trovato lezioni settimanali.',
  'benvenuto.leggo-orario': 'Leggo l\'orario…',
  'benvenuto.lezioni-trovate': { one: '{n} lezione trovata.', other: '{n} lezioni trovate.' },
  'benvenuto.lezioni-non-trovate': 'Non ho trovato lezioni: prova a scriverle una alla volta.',
  // abitudini
  'benvenuto.abitudini-titolo': 'Come studi?',
  'benvenuto.abitudini-sotto': 'Lode ti propone ripassi, giochi e domande lampo in momenti a caso della giornata, quando sei al computer. Dimmi quanto spesso e quando lasciarti in pace.',
  'benvenuto.quando-meglio': 'Quando studi meglio',
  'benvenuto.mattina': 'Mattina',
  'benvenuto.pomeriggio': 'Pomeriggio',
  'benvenuto.sera': 'Sera',
  'benvenuto.notte': 'Notte',
  'benvenuto.proposte': 'Proposte di Lode',
  'benvenuto.scelta-mai': 'Mai',
  'benvenuto.scelta-poco': 'Poche',
  'benvenuto.scelta-normale': 'Normali',
  'benvenuto.scelta-spesso': 'Tante',
  'benvenuto.proposte-nota': 'Più l\'esame è vicino, più spesso. Mai durante lezioni, focus o di notte.',
  'benvenuto.silenzio-dalle': 'Silenzio dalle',
  'benvenuto.silenzio-alle': 'alle',
  'benvenuto.focus': 'Focus',
  'benvenuto.minuti': '{n} min',
  'benvenuto.ripeti-in-aula': 'In aula accendi «Ripeti» da solo (l\'ultimo minuto e mezzo, solo in memoria). Chiedi al docente se si può registrare.',
  // fine
  'benvenuto.fine-titolo': 'Fatto, {nome}.',
  'benvenuto.fine-sotto': 'Lode ora vive in cima allo schermo. Passaci sopra per aprirla, tieni premuto <b>{tasti}</b> per parlarle, trascinaci sopra un PDF o una foto della lavagna.',
  'benvenuto.fine-esami': '{fatti} esami nel libretto, {dare} da dare',
  'benvenuto.fine-esami-prossimo': '{fatti} esami nel libretto, {dare} da dare · il prossimo è {nome}',
  'benvenuto.fine-lezioni': { one: '{n} lezione a settimana in orario', other: '{n} lezioni a settimana in orario' },
  'benvenuto.fine-proposte': 'Proposte: {quante}',
  'benvenuto.quante-mai': 'mai',
  'benvenuto.quante-poco': 'poche',
  'benvenuto.quante-normale': 'normali',
  'benvenuto.quante-spesso': 'tante',
  'benvenuto.apri-lode': 'Apri Lode',
};
