// Testi dell'app desktop (italiano, lingua di partenza): finestre di sistema, menu dell'icona, notifiche e messaggi del
// processo principale (desktop/*.mjs) che arrivano allo studente.
export default {
  // main.mjs: finestre di sistema
  'desktop.non-ci-sono-riuscito': 'Non ci sono riuscito.',
  'desktop.benvenuto-in-lode': 'Benvenuto in Lode',
  'desktop.dove-tenere-il-vault': 'Dove tenere il vault',
  'desktop.usa-questa-cartella': 'Usa questa cartella',
  'desktop.non-e-andata': 'Non è andata.',
  'desktop.vault-con-sincronizzazione': 'Con la sincronizzazione il vault si cambia da «Sincronizza fra i tuoi computer»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Smetti su questo computer» porta il vault fuori dalla cartella cloud.',
  'desktop.scegli-il-vault': 'Scegli il vault Obsidian',
  'desktop.usa-questo-vault': 'Usa questo vault',
  'desktop.cartella-non-usabile': 'Lode non riesce a usare la cartella {cartella}',
  'desktop.cartella-protetta-windows': 'Probabilmente Windows la protegge (Sicurezza di Windows › Protezione da ransomware › Accesso alle cartelle controllato) o l\'antivirus blocca Lode. Consenti Lode, oppure scegli un\'altra cartella.',
  'desktop.scegli-altra-cartella': 'Scegli un\'altra cartella',
  'desktop.riprova': 'Riprova',
  'desktop.non-ora': 'Non ora',
  'desktop.obsidian-pronto': 'Obsidian è pronto sul tuo vault',
  'desktop.modello-pronto': '{modello} è pronto',
  'desktop.ponte-non-partito': 'Il ponte con gli agenti non è partito: riavvia Lode.',
  'desktop.agente-togliere': 'Togliere Lode dalla configurazione di {agente}?',
  'desktop.agente-collegare': 'Collegare {agente} a Lode?',
  'desktop.agente-toglie-righe': 'Lode toglie solo le sue righe in:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode aggiunge solo le sue righe, il resto resta com\'è in:\n{file}',
  'desktop.agente-manda-eventi': '{agente} manderà a Lode, su questo computer, gli eventi delle sessioni (file toccati, comandi, fine del turno). Lode non risponde e non decide niente. ',
  'desktop.agente-file-com-era': 'Il file com\'era resta in {file}.',
  'desktop.togli': 'Togli',
  'desktop.collega': 'Collega',
  'desktop.annulla': 'Annulla',
  // main.mjs: il menu dell'icona
  'desktop.menu-avvisami-versioni': 'Avvisami delle versioni nuove',
  'desktop.menu-aggiornamenti-automatici': 'Aggiornamenti automatici',
  'desktop.menu-riavvia-con': 'Riavvia con Lode {versione}',
  'desktop.menu-scarica': 'Scarica Lode {versione}…',
  'desktop.menu-apri': 'Apri Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Spazio',
  'desktop.tasti-apri': 'Ctrl+Shift+Spazio',
  'desktop.menu-quadro': 'Il quadro: libretto, esami, ripasso',
  'desktop.menu-rifai-configurazione': 'Rifai la configurazione…',
  'desktop.menu-apri-vault-obsidian': 'Apri il vault in Obsidian',
  'desktop.menu-mostra-vault': 'Mostra il vault nella cartella',
  'desktop.menu-altro-vault': 'Usa un altro vault…',
  'desktop.menu-avvio-accensione': 'Avvia Lode all\'accensione',
  'desktop.menu-icona-mac': 'Icona di Lode in Applicazioni',
  'desktop.menu-icona-win': 'Icona di Lode nel menu Start e sul desktop',
  'desktop.menu-icona-linux': 'Icona di Lode nel menu delle applicazioni',
  'desktop.menu-esci': 'Esci da Lode',
  // sincronizza.mjs: la sincronizzazione fra i computer
  'desktop.sync-file-occupato': 'Un file è usato da un altro programma: chiudilo e riprova. Il vault di prima è intatto.',
  'desktop.sync-file-occupato-nome': 'Un file è usato da un altro programma ({file}): chiudilo e riprova. Il vault di prima è intatto.',
  'desktop.sync-disco-pieno': 'Il disco della cartella cloud è pieno. Il vault di prima è intatto.',
  'desktop.sync-permesso': 'Lode non ha il permesso di leggere o scrivere un file. Il vault di prima è intatto.',
  'desktop.sync-permesso-nome': 'Lode non ha il permesso di leggere o scrivere un file ({file}). Il vault di prima è intatto.',
  'desktop.sync-copia-diversa': 'La copia di {file} non è venuta uguale: riprova. Il vault di prima è intatto.',
  'desktop.sync-copia-non-riuscita': 'La copia del vault non è riuscita: riprova. Il vault di prima è intatto.',
  'desktop.sync-sto-accendendo': 'Sto già accendendo la sincronizzazione: aspetta che finisca.',
  'desktop.sync-cartella-titolo': 'La cartella che si sincronizza',
  'desktop.sync-sincronizza-qui': 'Sincronizza qui',
  'desktop.sync-spostamento-con-password': 'Lo spostamento era cominciato con la password: scrivila di nuovo.',
  'desktop.sync-dati-occupati': 'Il file dei dati di Lode è usato da un altro programma (un antivirus?): riprova tra poco.',
  'desktop.sync-diario-illeggibile': 'Il diario di Lode su questo computer non si legge.',
  'desktop.sync-controllo-altro-computer': 'Controllo se un altro computer sincronizza già questo vault…',
  'desktop.sync-aspetto-dati': 'Aspetto che i dati di Lode arrivino dal cloud (il file dei dati non si legge ancora): riprova tra poco.',
  'desktop.sync-altra-password': 'Su questo vault la sincronizzazione è già accesa con un\'altra password: scrivi quella.',
  'desktop.sync-gia-con-password': 'Su questo vault la sincronizzazione è già accesa con la password: scrivila.',
  'desktop.sync-non-accendo': 'Non riesco ad accendere la sincronizzazione qui.',
  'desktop.sync-cartella-dentro-vault': 'Questa cartella è dentro il vault: scegline una fuori, per esempio la cartella di iCloud Drive, OneDrive o Dropbox.',
  'desktop.sync-dati-non-ancora': 'I dati di Lode non si leggono ancora (cartella non raggiungibile?): riprova tra poco.',
  'desktop.sync-copio-vault': 'Copio il vault…',
  'desktop.sync-copio-vault-file': 'Copio il vault… {n} file',
  'desktop.sync-cifro-pubblico': 'Cifro e pubblico i dati di Lode…',
  'desktop.sync-pubblico': 'Pubblico i dati di Lode…',
  'desktop.sync-non-creo-dati': 'Non riesco a creare i dati di Lode nella cartella cloud. Il vault di prima è intatto.',
  'desktop.sync-vault-nel-cloud': 'Il vault di Lode nella cartella cloud',
  'desktop.sync-non-e-vault-sincronizzato': 'In questa cartella non c\'è un vault di Lode sincronizzato: scegli la cartella «Lode» dentro la cartella cloud (sull\'altro computer: «Sincronizza fra i tuoi computer»).',
  'desktop.sync-diario-altro-vault': 'Su questo computer Lode usa già il diario di un altro vault: prima «Smetti su questo computer».',
  'desktop.sync-password-sbagliata-di-nuovo': 'Password sbagliata: scrivila di nuovo.',
  'desktop.sync-password-vecchia': 'Questa è la password di prima: su un altro computer è cambiata, scrivi quella nuova.',
  'desktop.sync-lode-piu-nuova': 'Questo vault è stato protetto da una Lode più nuova: aggiornala.',
  'desktop.sync-gruppo-manomesso': 'La password è giusta, ma il file del gruppo nella cartella cloud è stato cambiato da fuori: non lo uso. Controlla la cartella cloud.',
  'desktop.sync-gruppo-in-chiaro': 'Il gruppo nella cartella cloud non è cifrato: sull\'altro computer la sincronizzazione è senza password, o il file del gruppo è stato manomesso. Se sull\'altro computer non hai messo la password, riprova senza.',
  'desktop.sync-password-sbagliata': 'Password sbagliata.',
  'desktop.sync-adesso-non-si-puo': 'Adesso non si può.',
  'desktop.sync-cartella-in-cloud': 'Questa cartella è in una cartella cloud: per sincronizzare usa «Sincronizza fra i tuoi computer».',
  'desktop.sync-fuori-dal-vault': 'Scegli una cartella fuori dal vault di adesso.',
  'desktop.sync-non-sposto-dati': 'Non riesco a spostare i dati di Lode in quella cartella. Il vault di prima è intatto.',
  'desktop.sync-riprova-tra-poco': 'Adesso non si può: riprova tra poco.',
  'desktop.sync-password-corta': 'La password deve avere almeno 8 caratteri.',
  'desktop.sync-diario-illeggibile-riprova': 'Il diario di Lode su questo computer non si legge: prima «Riprova».',
  'desktop.sync-non-accesa': 'Su questo computer la sincronizzazione non è accesa.',
  'desktop.sync-vault-spostato-scegli': 'Il vault non è più dove Lode lo cercava: se l\'hai spostato, usa «Trova il vault» e scegli la cartella spostata.',
  'desktop.sync-dove-fuori-cloud': 'Dove tenere il vault, fuori dalla cartella cloud',
  'desktop.sync-tieni-qui': 'Tieni qui il vault',
  'desktop.sync-fuori-dal-cloud': 'Scegli una cartella fuori dalla cartella cloud.',
  'desktop.sync-vault-spostato': 'Il vault non è più dove Lode lo cercava: se l\'hai spostato, usa «Trova il vault».',
  'desktop.sync-cambio-in-arrivo': 'Le ultime modifiche di questo computer non sono ancora nella cartella cloud (sta arrivando un cambio dagli altri computer): riprova tra poco.',
  'desktop.sync-smetti-serve-password': 'Le modifiche fatte in pausa resterebbero solo su questo computer: scrivi la password prima di smettere (o «Ho dimenticato la password»).',
  'desktop.sync-note-non-scaricate': 'Alcune note non sono scaricate su questo computer ({note}): aprile o scaricale dal servizio cloud, poi riprova.',
  'desktop.sync-note-non-scaricate-altre': 'Alcune note non sono scaricate su questo computer ({note} e altre {n}): aprile o scaricale dal servizio cloud, poi riprova.',
  'desktop.sync-copio-fuori-cloud': 'Copio il vault fuori dalla cartella cloud…',
  // progetto.mjs: «segui il progetto», il riassunto «Fatto. In parole semplici» e la conferma dei comandi
  'desktop.progetto-elenco': '{primi} e {ultimo}',
  'desktop.progetto-elenco-altre': '{primi} e altre {n}',
  'desktop.progetto-elenco-altri': '{primi} e altri {n}',
  'desktop.progetto-righe-piu-meno': { one: '{n} riga in più e {meno} in meno', other: '{n} righe in più e {meno} in meno' },
  'desktop.progetto-righe-piu': { one: '{n} riga in più', other: '{n} righe in più' },
  'desktop.progetto-righe-meno': { one: '{n} riga in meno', other: '{n} righe in meno' },
  'desktop.progetto-solo-spazi': 'solo spazi o a capo',
  'desktop.progetto-file-nuovo': { one: 'file nuovo ({n} riga)', other: 'file nuovo ({n} righe)' },
  'desktop.progetto-file-tolto': 'tolto',
  'desktop.progetto-funzioni-nuove': { one: 'nuova funzione {elenco}', other: 'nuove funzioni {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'cambiata {elenco}', other: 'cambiate {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'tolta {elenco}', other: 'tolte {elenco}' },
  'desktop.progetto-file': '{file}: {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'Nuovo {elenco}.', other: 'Nuovi {elenco}.' },
  'desktop.progetto-esito-compila': 'compila',
  'desktop.progetto-esito-non-compila': 'non compila',
  'desktop.progetto-esito-sintassi-a-posto': 'sintassi a posto',
  'desktop.progetto-esito-errore-di-sintassi': 'errore di sintassi',
  'desktop.progetto-esito-make-riuscito': 'make riuscito',
  'desktop.progetto-esito-make-non-riuscito': 'make non riuscito',
  'desktop.progetto-prove-su': { one: '{n} prova su {tot}', other: '{n} prove su {tot}' },
  'desktop.progetto-prova-non-partita': 'la prova non è partita',
  'desktop.progetto-inizio-alle': { one: 'Alle {ora} è cambiato {n} file (+{piu} −{meno}).', other: 'Alle {ora} sono cambiati {n} file (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'Dalle {da} alle {a} è cambiato {n} file (+{piu} −{meno}).', other: 'Dalle {da} alle {a} sono cambiati {n} file (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**Provato?** Sì: è il codice provato alle {ora} ({esito}).',
  'desktop.progetto-provato-no-codice': '**Provato?** No, ma qui sono cambiati solo file che non sono codice.',
  'desktop.progetto-provato-no': '**Provato?** No: dopo l\'ultima modifica ({ora}) nessuno ha compilato con Lode.',
  'desktop.progetto-nota-chi': 'Non so chi ha scritto queste righe.',
  'desktop.progetto-altri-file': 'E altri {n} file.',
  'desktop.progetto-nessuna-cartella': 'Non ho ricevuto nessuna cartella.',
  'desktop.progetto-non-trovo-cartella': 'Non trovo questa cartella.',
  'desktop.progetto-cartella-non-file': 'Scegli una cartella, non un file.',
  'desktop.progetto-radice-disco': 'Questa è la radice del disco: scegli la cartella del solo progetto (per esempio lab3).',
  'desktop.progetto-tutta-la-home': 'Questa cartella contiene tutta la tua home: scegli la cartella del solo progetto.',
  'desktop.progetto-e-il-vault': 'Questo è il vault di Lode (o lo contiene): scegli la cartella del progetto.',
  'desktop.progetto-dati-di-lode': 'Questa è la cartella dove Lode tiene i suoi dati: scegli quella del progetto.',
  'desktop.progetto-troppi-progetti': 'Seguo già {n} progetti: smetti di seguirne uno («smetti di seguire …»), poi riprova.',
  'desktop.progetto-cartella-illeggibile': 'Non riesco a leggere questa cartella.',
  'desktop.progetto-troppi-file': 'Qui ci sono più di {n} file: scegli la cartella del solo progetto (per esempio lab3).',
  'desktop.progetto-non-seguo': 'Non seguo questo progetto.',
  'desktop.progetto-versione-scaduta': 'Quella versione non c\'è più: Lode tiene le versioni per 30 giorni.',
  'desktop.progetto-file-non-seguito': 'Questo file non è tra quelli che seguo.',
  'desktop.progetto-file-illeggibile': 'Non riesco a leggere il file.',
  'desktop.progetto-poi-per-ogni-prova': 'Poi, per ogni prova .in → .out:\n{comandi}',
  'desktop.progetto-senza-prove': 'Il programma non lo lancio: non ci sono prove .in/.out.',
  'desktop.progetto-resto-non-mostro': '(il resto non lo mostro)',
  'desktop.progetto-smesso-durante-prova': 'Ho smesso di seguire il progetto durante la prova.',
  'desktop.progetto-scegli-cartella': 'Scegli la cartella del progetto',
  'desktop.progetto-segui-cartella': 'Segui questa cartella',
  'desktop.progetto-scegli-di-nuovo': 'Scegli di nuovo la cartella («segui progetto»).',
  'desktop.progetto-conferma-aperta': 'C\'è già una finestra di conferma aperta: rispondi prima a quella.',
  'desktop.progetto-eseguira': 'Lode eseguirà questo comando nella cartella {cartella}.',
  'desktop.progetto-come-terminale': 'È come lanciarlo dal terminale: il programma gira sul tuo computer.',
  'desktop.progetto-esegui-sempre': 'Esegui sempre per questo progetto',
  // esegui.mjs: provare il codice del progetto
  'desktop.esegui-riapri': 'Se lo hai appena aggiunto al PATH, esci da Lode (dal menu) e riaprila.',
  'desktop.esegui-manca-c-win': 'Non trovo un compilatore C. Installa MSYS2 (msys2.org), apri «MSYS2 UCRT64» e scrivi `pacman -S mingw-w64-ucrt-x86_64-gcc`: Lode lo trova da sola in C:\\msys64\\ucrt64\\bin. In alternativa WinLibs (winlibs.com) o WSL. Lode non scarica niente al posto tuo.',
  'desktop.esegui-manca-c-mac': 'Non trovo un compilatore C. Apri il Terminale e scrivi `xcode-select --install`: installa clang di Apple. Poi riprova.',
  'desktop.esegui-manca-c-linux': 'Non trovo un compilatore C. Installa gcc (per esempio `sudo apt install build-essential`), poi riprova.',
  'desktop.esegui-manca-python-win': 'Non trovo Python 3. Installalo da python.org (spunta «Add python.exe to PATH») oppure dal Microsoft Store, poi riprova.',
  'desktop.esegui-manca-python': 'Non trovo Python 3. Installalo (python.org, oppure dal gestore dei pacchetti), poi riprova.',
  'desktop.esegui-manca-java': 'Non trovo un JDK (javac e java). Installane uno, per esempio Temurin da adoptium.net, poi riprova.',
  'desktop.esegui-manca-make-win': 'C\'è un Makefile ma non trovo make. Con MSYS2, in «MSYS2 UCRT64»: `pacman -S mingw-w64-ucrt-x86_64-make`. Oppure togli il Makefile e Lode compila da sola i file .c.',
  'desktop.esegui-manca-make': 'C\'è un Makefile ma non trovo make. Installalo (sul Mac: `xcode-select --install`), poi riprova.',
  'desktop.esegui-manca-programma': 'Manca un programma per provare il codice.',
  'desktop.esegui-senza-prove': 'Non trovo prove .in/.out: compilo soltanto, il programma non lo lancio.',
  'desktop.esegui-make-prove': 'Con il Makefile le {n} prove .in/.out non le lancio: non so quale programma crea.',
  'desktop.esegui-poi-prove': { one: 'poi la prova (file .in → .out atteso)', other: 'poi le {n} prove (file .in → .out atteso)' },
  'desktop.esegui-poi-prove-in': { one: 'poi la prova in {cartella}/ (file .in → .out atteso)', other: 'poi le {n} prove in {cartella}/ (file .in → .out atteso)' },
  'desktop.esegui-senza-programma': '; {n} senza un programma chiaro',
  'desktop.esegui-make-leggi': 'make esegue i comandi scritti nel Makefile: leggilo prima di confermare.',
  'desktop.esegui-make-assente': 'C\'è un Makefile ma non trovo make: compilo io i file .c.',
  'desktop.esegui-niente-codice': 'Non trovo codice C, Python o Java da provare in questa cartella.',
  'desktop.esegui-virgolette': 'Le virgolette non sono chiuse.',
  'desktop.esegui-invisibili': 'Nel comando ci sono caratteri invisibili (a capo, controllo o direzione del testo): riscrivilo a mano.',
  'desktop.esegui-comando-vuoto': 'Il comando è vuoto.',
  'desktop.esegui-comando-illeggibile': 'Il comando non si legge.',
  'desktop.esegui-non-trovo-programma': 'Non trovo il programma «{programma}».',
  'desktop.esegui-bat': 'I file .bat e .cmd non li lancio: scrivi il comando che contengono.',
  'desktop.esegui-compilazione-lenta': 'La compilazione non è finita entro {n} secondi.',
  'desktop.esegui-prova-senza-programma': 'non so a quale programma va',
  'desktop.esegui-programma-non-creato': 'Il comando non ha creato il programma da provare.',
  'desktop.esegui-prova-illeggibile': 'non riesco a leggere i file della prova',
  // moodle.mjs: Moodle in sola lettura
  'desktop.moodle-risponde': 'Moodle risponde {stato}',
  'desktop.moodle-errore': 'errore di Moodle',
  'desktop.moodle-sito-risponde': 'il sito risponde {stato}',
  'desktop.moodle-non-e-moodle': 'non è un Moodle, o il servizio per le app è spento',
  'desktop.moodle-non-collegato': 'Moodle non è collegato',
  'desktop.moodle-accesso-non-riuscito': 'accesso non riuscito',
  'desktop.moodle-accedi-a': 'Accedi a {sito}',
  'desktop.moodle-risposta-non-valida': 'risposta di Moodle non valida',
  'desktop.moodle-tempo-scaduto': 'tempo scaduto',
  'desktop.moodle-file-non-trovato': 'file non trovato',
  'desktop.moodle-file-troppo-grande': 'file troppo grande',
  'desktop.moodle-file-non-su-moodle': 'il file non sta su Moodle',
  // installa.mjs: Obsidian e il cervello locale (Ollama)
  'desktop.installa-download-non-riuscito': 'download non riuscito ({stato})',
  'desktop.installa-non-firmato': 'L\'installer di {nome} non ha la firma ufficiale di {nome}, quindi non l\'ho installato. Riprova più tardi, oppure scaricalo tu dal sito ufficiale.',
  'desktop.installa-versione-obsidian': 'versione di Obsidian sconosciuta',
  'desktop.installa-scarico-obsidian': 'Scarico Obsidian {versione}',
  'desktop.installa-scarico-obsidian-mb': 'Scarico Obsidian {versione} · {mb} MB',
  'desktop.installa-installo-obsidian': 'Installo Obsidian',
  'desktop.installa-obsidian-installato': 'Obsidian {versione} installato',
  'desktop.installa-perche-4b': 'veloce anche senza scheda video: definizioni, carte, giochi e orale',
  'desktop.installa-perche-35b': 'il più bravo e veloce come un modello piccolo, per computer con molta memoria',
  'desktop.installa-perche-9b': 'spiega bene e regge l\'orale',
  'desktop.installa-perche-memoria': 'per {gb} GB di memoria: definizioni, carte, giochi e orale',
  'desktop.installa-ollama-non-avviato': 'Ollama non si è avviato',
  'desktop.installa-ollama-linux': 'Su Linux installa Ollama da ollama.com con il loro script, poi torna qui.',
  'desktop.installa-scarico-ollama-mb': 'Scarico Ollama · {mb} MB',
  'desktop.installa-installo-ollama': 'Installo Ollama',
  'desktop.installa-avvio-ollama': 'Avvio Ollama',
  'desktop.installa-ollama-non-risponde': 'Ollama non risponde',
  'desktop.installa-scarico-modello': 'Scarico {nome} · {fatti} di {totale} GB',
  'desktop.installa-modello-pronto': '{nome} pronto',
  'desktop.installa-modello-assente': 'Il modello {modello} non è installato',
  'desktop.installa-modello-non-risponde': 'Il modello locale non risponde',
  // aggiorna.mjs: le versioni nuove di Lode
  'desktop.aggiorna-github-risponde': 'GitHub risponde {stato}',
  'desktop.aggiorna-non-installato': 'L\'aggiornamento non si è installato. Riprova, o chiudi Lode: si installa all\'uscita.',
  'desktop.aggiorna-non-installato-perche': 'L\'aggiornamento non si è installato: {motivo}. Riprova, o chiudi Lode: si installa all\'uscita.',
  'desktop.aggiorna-niente-pronto': 'Non c\'è un aggiornamento pronto da installare.',
  'desktop.aggiorna-dove-scaricare': 'Non so ancora dove scaricarla: riprova fra poco.',
  // voce-onnx.mjs e voce-onnx-motore.mjs: la voce Parakeet ONNX
  'desktop.voce-modello-illeggibile': 'Non riesco a leggere il modello della voce: riprova fra poco.',
  'desktop.voce-spazio': 'Per la voce Parakeet servono circa {serve} MB liberi sul disco, ce ne sono {liberi}.',
  'desktop.voce-rete': 'Non riesco a scaricare la voce: controlla la connessione e riprova. ({dettaglio})',
  'desktop.voce-rete-stato': 'Non riesco a scaricare la voce ({stato}): riprova più tardi.',
  'desktop.voce-file-troppo-grande': 'Il file della voce è più grande del previsto.',
  'desktop.voce-interrotto': 'Il download della voce si è interrotto: riprende da qui la prossima volta. ({dettaglio})',
  'desktop.voce-impronta': 'Il file della voce «{file}» non è quello giusto (impronta SHA256 diversa): l\'ho cancellato.',
  'desktop.voce-addon': 'Il programma della voce (sherpa-onnx) non si carica su questo computer.',
  'desktop.voce-modello-rovinato': 'Il modello di Parakeet non si carica (forse un file è rovinato).',
  'desktop.voce-pezzo-non-trascritto': 'Parakeet non è riuscito a trascrivere questo pezzo.',
  'desktop.voce-motore-chiuso': 'Il motore della voce si è chiuso all\'improvviso.',
  'desktop.voce-motore-chiuso-codice': 'Il motore della voce si è chiuso all\'improvviso ({codice}).',
  'desktop.voce-motore-non-risponde': 'Il motore della voce non risponde.',
  // agenti-collegamenti.mjs: il collegamento con gli agenti di programmazione
  'desktop.agenti-claude-eventi': ['prompt', 'modifiche e comandi', 'fine del turno', 'notifiche'],
  'desktop.agenti-claude-nota': 'Gli hook valgono dalla prossima sessione (o rivedili in /hooks).',
  'desktop.agenti-codex-eventi': ['prompt', 'modifiche (apply_patch) e comandi', 'fine del turno'],
  'desktop.agenti-codex-nota': 'Alla prossima sessione Codex ti chiede di approvare gli hook nuovi: fallo con /hooks.',
  'desktop.agenti-gemini-eventi': ['prompt', 'strumenti (file e comandi)', 'fine della risposta', 'notifiche'],
  'desktop.agenti-gemini-nota': 'Vale dalla prossima sessione di Gemini CLI.',
  'desktop.agenti-cursor-eventi': ['prompt', 'file modificati', 'comandi', 'risposta dell\'agente'],
  'desktop.agenti-cursor-nota': 'Riavvia Cursor perché legga gli hook. Cursor non dice il codice d\'uscita dei comandi: i test lanciati si vedono, l\'esito no.',
  'desktop.agenti-copilot-eventi': ['prompt', 'strumenti (file e comandi)', 'fine del turno', 'notifiche'],
  'desktop.agenti-copilot-nota': 'Un file solo di Lode in ~/.copilot/hooks: vale dalla prossima sessione. Copilot non manda l\'ultimo messaggio dell\'agente.',
  'desktop.agenti-windsurf-eventi': ['prompt', 'codice scritto', 'comandi', 'risposta di Cascade'],
  'desktop.agenti-windsurf-nota': 'Vale dalla prossima conversazione di Cascade. Windsurf non dice il codice d\'uscita dei comandi.',
  'desktop.agenti-qwen-eventi': ['prompt', 'strumenti (file e comandi)', 'fine del turno', 'notifiche'],
  'desktop.agenti-qwen-nota': 'Vale dalla prossima sessione di Qwen Code.',
  'desktop.agenti-opencode-eventi': ['file modificati', 'comandi', 'fine del turno'],
  'desktop.agenti-opencode-nota': 'Un plugin di Lode in ~/.config/opencode/plugins: vale dal prossimo avvio di OpenCode. Legge e basta: non tocca le risposte.',
  'desktop.agenti-kilo-eventi': ['file modificati', 'comandi', 'fine del turno'],
  'desktop.agenti-kilo-nota': 'Il plugin è quello di OpenCode (Kilo ne è un fork): vale dal prossimo avvio. Formato degli eventi da verificare sulla tua versione.',
  'desktop.agenti-aider-eventi': ['fine della risposta (senza dettagli)'],
  'desktop.agenti-aider-nota': 'Aider avvisa solo che ha finito di rispondere, senza dire cosa ha toccato: i file cambiati li vede «segui progetto».',
  'desktop.agenti-non-json': 'non è un oggetto JSON',
  'desktop.agenti-file-non-di-lode': 'c\'è già un file con questo nome che non è di Lode',
  'desktop.agenti-notifiche-aider': 'ci sono già le notifiche di Aider: Lode non le sovrascrive',
  'desktop.agenti-file-illeggibile': '{file} non si legge ({motivo}): non lo tocco. Sistemalo o collega a mano.',
  'desktop.agenti-altre-righe': 'e altre {n} righe',
  'desktop.agenti-test-non-rilanciati': 'Dice che i test passano, ma dopo la sua ultima modifica non li ha rilanciati.',
  'desktop.agenti-test-non-lanciati': 'Dice che i test passano, ma in questo turno non l\'ho visto lanciarli.',
  'desktop.agenti-test-toccati': 'Ha modificato i test ({file}) mentre fallivano: controlla che non li abbia resi più facili.',
  // collegamento.mjs: Lode avviata dal codice (icona, avvio all'accensione, permessi del Mac)
  'desktop.permesso-audio-computer': 'Lode ascolta l\'audio del computer solo quando trascrivi una videolezione. L\'audio non resta mai sul computer: nella nota va solo il testo.',
  'desktop.permesso-microfono': 'Lode usa il microfono quando parli con lui, per «Ripeti» in aula e per trascrivere le lezioni che scegli. L\'audio non resta mai sul computer.',
  'desktop.icona-non-creata': 'non riesco a creare {file}',
};
