// Testi dell'app desktop (italiano, lingua di partenza): finestre di sistema, menu dell'icona, notifiche e messaggi del
// processo principale (desktop/*.mjs) che arrivano allo studente.
export default {
  // main.mjs: finestre di sistema
  'desktop.non-ci-sono-riuscito': 'Non ci sono riuscito.',
  'desktop.benvenuto-in-lode': 'Benvenuto in Lode',
  'desktop.dove-tenere-il-vault': 'Dove tenere il vault',
  'desktop.usa-questa-cartella': 'Usa questa cartella',
  'desktop.non-e-andata': 'Non è andata.',
  'desktop.vault-con-sincronizzazione': 'Con la sincronizzazione il vault si cambia da «Sincronizza fra i tuoi computer»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Smetti su questo computer» porta il vault fuori dalla cartella cloud.',
  'desktop.scegli-il-vault': 'Scegli il vault Obsidian',
  'desktop.usa-questo-vault': 'Usa questo vault',
  'desktop.cartella-non-usabile': 'Lode non riesce a usare la cartella {cartella}',
  'desktop.cartella-protetta-windows': 'Probabilmente Windows la protegge (Sicurezza di Windows › Protezione da ransomware › Accesso alle cartelle controllato) o l\'antivirus blocca Lode. Consenti Lode, oppure scegli un\'altra cartella.',
  'desktop.scegli-altra-cartella': 'Scegli un\'altra cartella',
  'desktop.riprova': 'Riprova',
  'desktop.non-ora': 'Non ora',
  'desktop.obsidian-pronto': 'Obsidian è pronto sul tuo vault',
  'desktop.modello-pronto': '{modello} è pronto',
  'desktop.ponte-non-partito': 'Il ponte con gli agenti non è partito: riavvia Lode.',
  'desktop.agente-togliere': 'Togliere Lode dalla configurazione di {agente}?',
  'desktop.agente-collegare': 'Collegare {agente} a Lode?',
  'desktop.agente-toglie-righe': 'Lode toglie solo le sue righe in:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode aggiunge solo le sue righe, il resto resta com\'è in:\n{file}',
  'desktop.agente-manda-eventi': '{agente} manderà a Lode, su questo computer, gli eventi delle sessioni (file toccati, comandi, fine del turno). Lode non risponde e non decide niente. ',
  'desktop.agente-file-com-era': 'Il file com\'era resta in {file}.',
  'desktop.togli': 'Togli',
  'desktop.collega': 'Collega',
  'desktop.annulla': 'Annulla',
  // main.mjs: il menu dell'icona
  'desktop.menu-avvisami-versioni': 'Avvisami delle versioni nuove',
  'desktop.menu-aggiornamenti-automatici': 'Aggiornamenti automatici',
  'desktop.menu-riavvia-con': 'Riavvia con Lode {versione}',
  'desktop.menu-scarica': 'Scarica Lode {versione}…',
  'desktop.menu-apri': 'Apri Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Spazio',
  'desktop.tasti-apri': 'Ctrl+Shift+Spazio',
  'desktop.menu-quadro': 'Il quadro: libretto, esami, ripasso',
  'desktop.menu-rifai-configurazione': 'Rifai la configurazione…',
  'desktop.menu-apri-vault-obsidian': 'Apri il vault in Obsidian',
  'desktop.menu-mostra-vault': 'Mostra il vault nella cartella',
  'desktop.menu-altro-vault': 'Usa un altro vault…',
  'desktop.menu-avvio-accensione': 'Avvia Lode all\'accensione',
  'desktop.menu-icona-mac': 'Icona di Lode in Applicazioni',
  'desktop.menu-icona-win': 'Icona di Lode nel menu Start e sul desktop',
  'desktop.menu-icona-linux': 'Icona di Lode nel menu delle applicazioni',
  'desktop.menu-esci': 'Esci da Lode',
};
