// Testi dell'app desktop (italiano, lingua di partenza): finestre di sistema, menu dell'icona, notifiche e messaggi del
// processo principale (desktop/*.mjs) che arrivano allo studente.
export default {
  // main.mjs: finestre di sistema
  'desktop.non-ci-sono-riuscito': 'Non ci sono riuscito.',
  'desktop.benvenuto-in-lode': 'Benvenuto in Lode',
  'desktop.dove-tenere-il-vault': 'Dove tenere il vault',
  'desktop.usa-questa-cartella': 'Usa questa cartella',
  'desktop.non-e-andata': 'Non è andata.',
  'desktop.vault-con-sincronizzazione': 'Con la sincronizzazione il vault si cambia da «Sincronizza fra i tuoi computer»',
  'desktop.vault-con-sincronizzazione-dettaglio': '«Smetti su questo computer» porta il vault fuori dalla cartella cloud.',
  'desktop.scegli-il-vault': 'Scegli il vault Obsidian',
  'desktop.usa-questo-vault': 'Usa questo vault',
  'desktop.cartella-non-usabile': 'Lode non riesce a usare la cartella {cartella}',
  'desktop.cartella-protetta-windows': 'Probabilmente Windows la protegge (Sicurezza di Windows › Protezione da ransomware › Accesso alle cartelle controllato) o l\'antivirus blocca Lode. Consenti Lode, oppure scegli un\'altra cartella.',
  'desktop.scegli-altra-cartella': 'Scegli un\'altra cartella',
  'desktop.riprova': 'Riprova',
  'desktop.non-ora': 'Non ora',
  'desktop.obsidian-pronto': 'Obsidian è pronto sul tuo vault',
  'desktop.modello-pronto': '{modello} è pronto',
  'desktop.ponte-non-partito': 'Il ponte con gli agenti non è partito: riavvia Lode.',
  'desktop.agente-togliere': 'Togliere Lode dalla configurazione di {agente}?',
  'desktop.agente-collegare': 'Collegare {agente} a Lode?',
  'desktop.agente-toglie-righe': 'Lode toglie solo le sue righe in:\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode aggiunge solo le sue righe, il resto resta com\'è in:\n{file}',
  'desktop.agente-manda-eventi': '{agente} manderà a Lode, su questo computer, gli eventi delle sessioni (file toccati, comandi, fine del turno). Lode non risponde e non decide niente. ',
  'desktop.agente-file-com-era': 'Il file com\'era resta in {file}.',
  'desktop.togli': 'Togli',
  'desktop.collega': 'Collega',
  'desktop.annulla': 'Annulla',
  // main.mjs: il menu dell'icona
  'desktop.menu-avvisami-versioni': 'Avvisami delle versioni nuove',
  'desktop.menu-aggiornamenti-automatici': 'Aggiornamenti automatici',
  'desktop.menu-riavvia-con': 'Riavvia con Lode {versione}',
  'desktop.menu-scarica': 'Scarica Lode {versione}…',
  'desktop.menu-apri': 'Apri Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Spazio',
  'desktop.tasti-apri': 'Ctrl+Shift+Spazio',
  'desktop.menu-quadro': 'Il quadro: libretto, esami, ripasso',
  'desktop.menu-rifai-configurazione': 'Rifai la configurazione…',
  'desktop.menu-apri-vault-obsidian': 'Apri il vault in Obsidian',
  'desktop.menu-mostra-vault': 'Mostra il vault nella cartella',
  'desktop.menu-altro-vault': 'Usa un altro vault…',
  'desktop.menu-avvio-accensione': 'Avvia Lode all\'accensione',
  'desktop.menu-icona-mac': 'Icona di Lode in Applicazioni',
  'desktop.menu-icona-win': 'Icona di Lode nel menu Start e sul desktop',
  'desktop.menu-icona-linux': 'Icona di Lode nel menu delle applicazioni',
  'desktop.menu-esci': 'Esci da Lode',
  // sincronizza.mjs: la sincronizzazione fra i computer
  'desktop.sync-file-occupato': 'Un file è usato da un altro programma: chiudilo e riprova. Il vault di prima è intatto.',
  'desktop.sync-file-occupato-nome': 'Un file è usato da un altro programma ({file}): chiudilo e riprova. Il vault di prima è intatto.',
  'desktop.sync-disco-pieno': 'Il disco della cartella cloud è pieno. Il vault di prima è intatto.',
  'desktop.sync-permesso': 'Lode non ha il permesso di leggere o scrivere un file. Il vault di prima è intatto.',
  'desktop.sync-permesso-nome': 'Lode non ha il permesso di leggere o scrivere un file ({file}). Il vault di prima è intatto.',
  'desktop.sync-copia-diversa': 'La copia di {file} non è venuta uguale: riprova. Il vault di prima è intatto.',
  'desktop.sync-copia-non-riuscita': 'La copia del vault non è riuscita: riprova. Il vault di prima è intatto.',
  'desktop.sync-sto-accendendo': 'Sto già accendendo la sincronizzazione: aspetta che finisca.',
  'desktop.sync-cartella-titolo': 'La cartella che si sincronizza',
  'desktop.sync-sincronizza-qui': 'Sincronizza qui',
  'desktop.sync-spostamento-con-password': 'Lo spostamento era cominciato con la password: scrivila di nuovo.',
  'desktop.sync-dati-occupati': 'Il file dei dati di Lode è usato da un altro programma (un antivirus?): riprova tra poco.',
  'desktop.sync-diario-illeggibile': 'Il diario di Lode su questo computer non si legge.',
  'desktop.sync-controllo-altro-computer': 'Controllo se un altro computer sincronizza già questo vault…',
  'desktop.sync-aspetto-dati': 'Aspetto che i dati di Lode arrivino dal cloud (il file dei dati non si legge ancora): riprova tra poco.',
  'desktop.sync-altra-password': 'Su questo vault la sincronizzazione è già accesa con un\'altra password: scrivi quella.',
  'desktop.sync-gia-con-password': 'Su questo vault la sincronizzazione è già accesa con la password: scrivila.',
  'desktop.sync-non-accendo': 'Non riesco ad accendere la sincronizzazione qui.',
  'desktop.sync-cartella-dentro-vault': 'Questa cartella è dentro il vault: scegline una fuori, per esempio la cartella di iCloud Drive, OneDrive o Dropbox.',
  'desktop.sync-dati-non-ancora': 'I dati di Lode non si leggono ancora (cartella non raggiungibile?): riprova tra poco.',
  'desktop.sync-copio-vault': 'Copio il vault…',
  'desktop.sync-copio-vault-file': 'Copio il vault… {n} file',
  'desktop.sync-cifro-pubblico': 'Cifro e pubblico i dati di Lode…',
  'desktop.sync-pubblico': 'Pubblico i dati di Lode…',
  'desktop.sync-non-creo-dati': 'Non riesco a creare i dati di Lode nella cartella cloud. Il vault di prima è intatto.',
  'desktop.sync-vault-nel-cloud': 'Il vault di Lode nella cartella cloud',
  'desktop.sync-non-e-vault-sincronizzato': 'In questa cartella non c\'è un vault di Lode sincronizzato: scegli la cartella «Lode» dentro la cartella cloud (sull\'altro computer: «Sincronizza fra i tuoi computer»).',
  'desktop.sync-diario-altro-vault': 'Su questo computer Lode usa già il diario di un altro vault: prima «Smetti su questo computer».',
  'desktop.sync-password-sbagliata-di-nuovo': 'Password sbagliata: scrivila di nuovo.',
  'desktop.sync-password-vecchia': 'Questa è la password di prima: su un altro computer è cambiata, scrivi quella nuova.',
  'desktop.sync-lode-piu-nuova': 'Questo vault è stato protetto da una Lode più nuova: aggiornala.',
  'desktop.sync-gruppo-manomesso': 'La password è giusta, ma il file del gruppo nella cartella cloud è stato cambiato da fuori: non lo uso. Controlla la cartella cloud.',
  'desktop.sync-gruppo-in-chiaro': 'Il gruppo nella cartella cloud non è cifrato: sull\'altro computer la sincronizzazione è senza password, o il file del gruppo è stato manomesso. Se sull\'altro computer non hai messo la password, riprova senza.',
  'desktop.sync-password-sbagliata': 'Password sbagliata.',
  'desktop.sync-adesso-non-si-puo': 'Adesso non si può.',
  'desktop.sync-cartella-in-cloud': 'Questa cartella è in una cartella cloud: per sincronizzare usa «Sincronizza fra i tuoi computer».',
  'desktop.sync-fuori-dal-vault': 'Scegli una cartella fuori dal vault di adesso.',
  'desktop.sync-non-sposto-dati': 'Non riesco a spostare i dati di Lode in quella cartella. Il vault di prima è intatto.',
  'desktop.sync-riprova-tra-poco': 'Adesso non si può: riprova tra poco.',
  'desktop.sync-password-corta': 'La password deve avere almeno 8 caratteri.',
  'desktop.sync-diario-illeggibile-riprova': 'Il diario di Lode su questo computer non si legge: prima «Riprova».',
  'desktop.sync-non-accesa': 'Su questo computer la sincronizzazione non è accesa.',
  'desktop.sync-vault-spostato-scegli': 'Il vault non è più dove Lode lo cercava: se l\'hai spostato, usa «Trova il vault» e scegli la cartella spostata.',
  'desktop.sync-dove-fuori-cloud': 'Dove tenere il vault, fuori dalla cartella cloud',
  'desktop.sync-tieni-qui': 'Tieni qui il vault',
  'desktop.sync-fuori-dal-cloud': 'Scegli una cartella fuori dalla cartella cloud.',
  'desktop.sync-vault-spostato': 'Il vault non è più dove Lode lo cercava: se l\'hai spostato, usa «Trova il vault».',
  'desktop.sync-cambio-in-arrivo': 'Le ultime modifiche di questo computer non sono ancora nella cartella cloud (sta arrivando un cambio dagli altri computer): riprova tra poco.',
  'desktop.sync-smetti-serve-password': 'Le modifiche fatte in pausa resterebbero solo su questo computer: scrivi la password prima di smettere (o «Ho dimenticato la password»).',
  'desktop.sync-note-non-scaricate': 'Alcune note non sono scaricate su questo computer ({note}): aprile o scaricale dal servizio cloud, poi riprova.',
  'desktop.sync-note-non-scaricate-altre': 'Alcune note non sono scaricate su questo computer ({note} e altre {n}): aprile o scaricale dal servizio cloud, poi riprova.',
  'desktop.sync-copio-fuori-cloud': 'Copio il vault fuori dalla cartella cloud…',
};
