// Il registro nel vault (italiano, lingua di partenza): le righe del diario del progetto, la tabella «Cosa so davvero» e la
// sezione «Informatica» di Lode/Memoria.md. I titoli delle sezioni («## Cosa ho capito», «## Cosa so davvero», «## Informatica»),
// le proprietà e i segni %% lode:… %% NON stanno qui: sono nomi del vault, che il codice ritrova.
export default {
  'diario.concetto-for': 'Ciclo for',
  'diario.concetto-while': 'Ciclo while',
  'diario.concetto-do-while': 'Ciclo do-while',
  'diario.concetto-ritroso': 'Conteggio a ritroso',
  'diario.concetto-array': 'Array',
  'diario.concetto-divisione-intera': 'Divisione intera',
  'diario.concetto-resto': 'Resto con i negativi',
  'diario.concetto-cast': 'Cast a double',
  'diario.concetto-incremento': 'i++ e ++i',
  'diario.concetto-switch': 'switch e break',
  'diario.concetto-cortocircuito': '&& e || in cortocircuito',
  'diario.concetto-else-pendente': 'else pendente',
  'diario.concetto-puntatori': 'Passaggio per indirizzo',
  'diario.concetto-parametri': 'Passaggio per valore',
  'diario.concetto-visibilita': 'Variabili nei blocchi',
  'diario.concetto-char': 'char e codici ASCII',
  'diario.concetto-ricorsione': 'Ricorsione',
  'diario.concetto-annidati': 'Cicli annidati',
  'diario.concetto-break-continue': 'break e continue',
  'diario.concetto-ternario': 'Operatore ternario',
  'diario.concetto-printf': 'printf e formati',
  'diario.elenco-e': '{prima} e {ultimo}',
  'diario.errore-titolo': '«{titolo}»',
  'diario.errore-generico': 'errore',
  'diario.passo-dove': '«dove guardare»',
  'diario.passo-cosa': '«cosa vuol dire»',
  'diario.passi-visti': { one: 'visto {passi}', other: 'visti {passi}' },
  'diario.funzione-nuova': 'nuova {nome}',
  'diario.funzione-nuova-in': 'nuova {nome} in {file}',
  'diario.funzione-cambiata': 'cambiata {nome}',
  'diario.funzione-cambiata-in': 'cambiata {nome} in {file}',
  'diario.funzione-tolta': 'tolta {nome}',
  'diario.funzione-tolta-in': 'tolta {nome} in {file}',
  'diario.file-nuovo': 'nuovo {file}',
  'diario.file-tolto': 'tolto {file}',
  'diario.cambiati-file': { one: 'Cambiato {n} file', other: 'Cambiati {n} file' },
  'diario.cambiato-codice': 'Cambiato il codice',
  'diario.altre-modifiche': { one: 'e {n} altra modifica', other: 'e {n} altre modifiche' },
  'diario.chi-ha-scritto': 'chi l\'ha scritto: non lo so',
  'diario.cambiato-durante': 'il codice è cambiato durante la prova',
  'diario.prova-non-compila': 'Prova: ✗ non compila',
  'diario.prova-non-compila-errore': 'Prova: ✗ non compila, {errore}',
  'diario.prova-non-partita': 'Prova: non partita',
  'diario.prova-ok': 'Prova: ✓ compila · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} prove',
  'diario.nessun-caso': 'nessun caso di prova',
  'diario.ma-cambiato': 'ma il codice è cambiato durante la prova',
  'diario.codice-provato': 'codice provato',
  'diario.prova-ko': 'Prova: ✗ compila · {ok}/{tot} prove',
  'diario.n-prove': { one: '{n} prova', other: '{n} prove' },
  'diario.nessuna-prova': 'nessuna prova',
  'diario.errori-risolti': { one: '{n} errore risolto', other: '{n} errori risolti' },
  'diario.n-errori': { one: '{n} errore', other: '{n} errori' },
  'diario.n-risolti': { one: '{n} risolto', other: '{n} risolti' },
  'diario.correzioni-viste': 'correzioni viste: {n}',
  'diario.oggi': 'Oggi: {parti}',
  'diario.ultima-non-provata': 'ultima modifica non provata',
  'diario.smette': 'Lode smette di seguire {progetto}',
  'diario.segue': 'Lode segue {progetto}',
  'diario.errore': 'Errore: {errore}',
  'diario.correzione-vista': 'Correzione vista: {errore}',
  'diario.spiegate': 'Spiegate: {spiegate} su {totale}',
  'diario.spiegate-rivedere': 'Spiegate: {spiegate} su {totale}; da rivedere: {nomi}',
  'diario.ieri': 'ieri',
  'diario.giorni-fa': { one: '{n} giorni fa', other: '{n} giorni fa' },
  'diario.stato-da-rifare': 'da rifare',
  'diario.stato-sicuro': 'sicuro',
  'diario.stato-mai-fatto': 'mai fatto',
  'diario.diari-dei-progetti': 'Diari dei progetti:',
  'diario.tabella-nota': 'Conti di Lode sugli esercizi «Cosa stampa?», senza AI. «Da rifare» vuol dire che è ora di ripassarlo.',
  'diario.tabella-testa': '| Argomento | Esercizi | Al primo colpo | Ultima volta | Stato |',
  'diario.nessun-esercizio': 'Ancora nessun esercizio. Scrivi «cosa stampa» nella barra: sono 5 domande da un minuto.',
  'diario.errori-frequenti': 'Errori che incontri di più: {errori}.',
  'diario.sbagli-spesso': 'Sbagli spesso: {sbagli}.',
  'diario.memoria-stampa': { one: '«Cosa stampa?»: {n} esercizio, {giuste}% giusti al primo colpo.', other: '«Cosa stampa?»: {n} esercizi, {giuste}% giusti al primo colpo.' },
  'diario.da-rifare': 'Da rifare: {argomenti}.',
};
