// Gli errori del compilatore e dei programmi (js/errori.js), in italiano: la lingua di partenza.
// Le chiavi «errori.<voce>.<campo>» sono i testi di ogni voce del dizionario: etichetta, breve, frase, dove, cosa, concetto.
export default {
  'errori.for-punto-e-virgola.etichetta': 'il `for` con le virgole',
  'errori.for-punto-e-virgola.frase': 'le tre parti del `for` vanno separate con `;`',
  'errori.for-punto-e-virgola.dove': `Guarda il \`for\` {allaRiga}: tra le parentesi devono esserci due \`;\`.`,
  'errori.for-punto-e-virgola.cosa': 'Il `for` ha tre parti: partenza, condizione e passo, come in `for (i = 0; i < n; i++)`. Si separano con `;`, non con `,`. Con le virgole il compilatore vede una parte sola.',
  'errori.for-punto-e-virgola.concetto': 'ciclo for',
  'errori.punto-e-virgola.etichetta': 'manca `;`',
  'errori.punto-e-virgola.breve': 'manca ;',
  'errori.punto-e-virgola.frase': 'manca un `;`',
  'errori.punto-e-virgola.dove': `Guarda la fine della riga {riga}, quella prima della {riga2}: lì manca il \`;\`. Il compilatore se ne accorge solo quando legge la riga dopo.`,
  'errori.punto-e-virgola.dove-2': `Guarda la fine della riga {riga}{colonna}: lì manca il \`;\`.`,
  'errori.punto-e-virgola.dove-3': `Guarda la fine della riga {riga} e quella della riga prima: il compilatore a volte se ne accorge solo sulla riga dopo.`,
  'errori.punto-e-virgola.dove-4': 'Guarda la fine delle istruzioni vicino al punto indicato.',
  'errori.punto-e-virgola.cosa': `In {L} ogni istruzione finisce con \`;\`, come una frase finisce con il punto. Senza, il compilatore attacca l'istruzione a quella dopo e non capisce più cosa volevi dire. Per questo a volte l'errore viene segnalato sulla riga successiva.`,
  'errori.punto-e-virgola.concetto': 'fine delle istruzioni',
  'errori.include-mancante.etichetta': 'manca un `#include`',
  'errori.include-mancante.breve': `manca #include{h}`,
  'errori.include-mancante.frase-2': 'questa funzione',
  'errori.include-mancante.frase': `per usare {nome} manca \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'questa funzione',
  'errori.include-mancante.frase-3': `per usare {nome} manca un \`#include\``,
  'errori.include-mancante.dove-2': `: manca quella di \`<{h}>\``,
  'errori.include-mancante.dove': `Guarda in cima al file, dove ci sono le righe \`#include\`{h}.`,
  'errori.include-mancante.cosa': '`bool`, `true` e `false` in C non ci sono di base: arrivano con `{h}`.',
  'errori.include-mancante.cosa-3': 'Questo nome',
  'errori.include-mancante.cosa-4': `, cioè \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome} non lo scrivi tu: sta nella libreria standard del C. Per usarlo devi includere il file che lo descrive (l'header){h}. Senza \`#include\` il compilatore non sa che esiste né come si usa.`,
  'errori.include-mancante.cosa-5': ' Con `math.h`, su Linux aggiungi anche `-lm` alla fine del comando di compilazione.',
  'errori.include-mancante.concetto': 'librerie e #include',
  'errori.funzione-non-dichiarata.etichetta': 'funzione non dichiarata',
  'errori.funzione-non-dichiarata.breve-2': 'funzione',
  'errori.funzione-non-dichiarata.breve': `{nome} non dichiarata`,
  'errori.funzione-non-dichiarata.frase': `usi la funzione {nome} prima di dichiararla`,
  'errori.funzione-non-dichiarata.dove': `Cerca dove scrivi la funzione {nome}: se sta sotto la riga {riga}, il compilatore lì non la conosce ancora. Controlla anche che il nome sia scritto proprio uguale.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Cerca dove scrivi la funzione {nome}: se sta sotto la riga dell'errore, il compilatore lì non la conosce ancora. Controlla anche che il nome sia scritto proprio uguale.`,
  'errori.funzione-non-dichiarata.cosa': 'Il compilatore legge il file dall\'alto in basso. Se chiami una funzione che non ha ancora visto, non sa quali parametri vuole né cosa restituisce: i compilatori recenti si fermano, quelli più vecchi tirano a indovinare e spesso sbagliano. Sposta la funzione sopra `main`, oppure scrivi sopra `main` il suo prototipo: la prima riga della funzione seguita da `;`.',
  'errori.funzione-non-dichiarata.concetto': 'prototipi delle funzioni',
  'errori.non-dichiarato.etichetta': 'nome non dichiarato',
  'errori.non-dichiarato.breve-2': 'nome',
  'errori.non-dichiarato.breve': `{nome} non dichiarato`,
  'errori.non-dichiarato.frase': `usi {nome} ma non è dichiarato`,
  'errori.non-dichiarato.frase-2': 'usi un nome che non è dichiarato',
  'errori.non-dichiarato.dove': `Il compilatore propone {s}: controlla se volevi scrivere quello. `,
  'errori.non-dichiarato.dove-3': 'questo nome',
  'errori.non-dichiarato.dove-2': `Cerca dove dichiari {nome}: forse ha un altro nome (una lettera diversa, maiuscole e minuscole), o è dichiarato dentro un altro blocco \`{ }\`.`,
  'errori.non-dichiarato.cosa': 'Il metodo che chiami non esiste con quel nome e con quei tipi di argomenti. Controlla come è scritto e che sia nella classe giusta. ',
  'errori.non-dichiarato.cosa-2': 'Prima di usare una variabile devi dichiararla, cioè scrivere il suo tipo e il suo nome (per esempio `int conta = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'Una variabile dichiarata dentro `{ }` esiste solo lì dentro: fuori dal blocco il compilatore non la vede più. Conta anche l\'ordine: la dichiarazione deve stare sopra la riga che la usa.',
  'errori.non-dichiarato.concetto': 'dichiarazione e visibilità delle variabili',
  'errori.formato.etichetta': 'formato di printf o scanf sbagliato',
  'errori.formato.frase': `il formato vuole un {atteso} ma passi un {dato}`,
  'errori.formato.frase-2': 'il formato non corrisponde al valore che passi',
  'errori.formato.dove': `Guarda la riga {riga}: confronta ogni \`%\` della stringa con il valore nella stessa posizione.`,
  'errori.formato.dove-senza-riga': `Guarda la riga indicata: confronta ogni \`%\` della stringa con il valore nella stessa posizione.`,
  'errori.formato.cosa': 'In `scanf` ogni `%` vuole l\'indirizzo di una variabile del tipo giusto: `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → array di `char`. Se il tipo non corrisponde, il valore letto finisce scritto male.',
  'errori.formato.cosa-2': ` Per un {dato} in \`scanf\` si usa {p}.`,
  'errori.formato.cosa-3': '`printf` non sa di che tipo sono i valori: si fida della stringa di formato. `%d` è per gli `int`, `%f` per i `double`, `%c` per i `char`, `%s` per le stringhe. Se il formato non corrisponde al valore, stampa numeri senza senso.',
  'errori.formato.cosa-4': ' Per un `unsigned long` si usa `%lu`; se è il risultato di `strlen` o `sizeof` (un `size_t`) si usa `%zu`.',
  'errori.formato.cosa-5': ` Per un {dato} in \`printf\` si usa {p}.`,
  'errori.formato.concetto': 'printf, scanf e i formati',
  'errori.scanf-e-commerciale.etichetta': 'manca `&` in scanf',
  'errori.scanf-e-commerciale.breve': 'manca & in scanf',
  'errori.scanf-e-commerciale.frase': '`scanf` vuole l\'indirizzo della variabile: manca `&`',
  'errori.scanf-e-commerciale.dove': `Guarda la \`scanf\` {allaRiga}: c'è una variabile senza \`&\` davanti.`,
  'errori.scanf-e-commerciale.cosa': '`scanf` deve scrivere dentro la tua variabile, quindi le serve sapere dove sta in memoria: il suo indirizzo, che si ottiene con `&`. Si scrive `scanf("%d", &n);`. Gli array di `char` (le stringhe) fanno eccezione: il loro nome è già un indirizzo, quindi niente `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf e indirizzi',
  'errori.return-mancante.etichetta': 'manca il `return`',
  'errori.return-mancante.breve': 'manca il return',
  'errori.return-mancante.frase-2': `la funzione {nome}`,
  'errori.return-mancante.frase-3': 'la funzione',
  'errori.return-mancante.frase-4': 'in alcuni casi ',
  'errori.return-mancante.frase': `{p} {sigla}arriva alla fine senza \`return\``,
  'errori.return-mancante.dove': `Guarda la \`}\` {allaRiga}: è la fine della funzione{p}. Segui ogni strada possibile (ogni \`if\` ed \`else\`) e controlla che finisca con un \`return\`.`,
  'errori.return-mancante.cosa-2': ` (qui restituisce {tipo})`,
  'errori.return-mancante.cosa': `Una funzione che non è \`void\`{tipo} promette di restituire un valore. Se arriva alla \`}\` finale senza \`return\`, chi la chiama riceve un valore a caso. Succede spesso con un \`if\` che ha il suo \`return\` ma senza un \`else\`.`,
  'errori.return-mancante.concetto': 'return nelle funzioni',
  'errori.assegnamento-in-condizione.etichetta': '`=` al posto di `==`',
  'errori.assegnamento-in-condizione.breve': '= al posto di ==',
  'errori.assegnamento-in-condizione.frase': 'nella condizione c\'è `=` (assegna) invece di `==` (confronta)',
  'errori.assegnamento-in-condizione.dove': `Guarda la condizione {allaRiga}{colonna}.`,
  'errori.assegnamento-in-condizione.cosa': '`=` mette un valore nella variabile; `==` controlla se due valori sono uguali. `if (x = 5)` assegna 5 a `x` ed è sempre vero, perché 5 non è zero. Per confrontare serve `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'assegnamento e confronto',
  'errori.confronto-stringhe.etichetta': 'stringhe confrontate con `==`',
  'errori.confronto-stringhe.frase': 'confronti delle stringhe con `==`',
  'errori.confronto-stringhe.dove': `Guarda il confronto {allaRiga}.`,
  'errori.confronto-stringhe.cosa': 'In C `==` tra due stringhe confronta gli indirizzi, non le lettere: quasi sempre dà falso anche se il testo è uguale. Per confrontare il testo si usa `strcmp(a, b) == 0`, da `{h}`. Se invece volevi un solo carattere, scrivilo tra apici singoli: `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'stringhe in C',
  'errori.puntatore-intero.etichetta': 'confronto tra puntatore e intero',
  'errori.puntatore-intero.frase': 'confronti un indirizzo (un puntatore) con un numero o un carattere',
  'errori.puntatore-intero.dove': `Guarda i due lati del confronto {allaRiga}.`,
  'errori.puntatore-intero.cosa': 'Da un lato c\'è un puntatore (un indirizzo, per esempio una stringa), dall\'altro un numero o un carattere. Un errore tipico: `"a"` tra virgolette doppie è una stringa, `\'a\'` tra apici singoli è un carattere. Per controllare un carattere scrivi `s[0] == \'a\'`; per confrontare due stringhe usa `strcmp`.',
  'errori.puntatore-intero.concetto': 'caratteri, stringhe e puntatori',
  'errori.puntatori-incompatibili.etichetta': 'puntatori di tipo diverso',
  'errori.puntatori-incompatibili.frase': `usi un {dato} dove serve un {atteso}`,
  'errori.puntatori-incompatibili.frase-2': 'usi un puntatore di un tipo dove ne serve un altro',
  'errori.puntatori-incompatibili.dove': `Guarda la riga {riga}: confronta il tipo di quello che passi (o assegni) con il tipo che serve.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Guarda la riga indicata: confronta il tipo di quello che passi (o assegni) con il tipo che serve.`,
  'errori.puntatori-incompatibili.cosa': 'Un puntatore porta con sé il tipo di quello a cui punta: un `int *` punta a interi, un `char *` a caratteri. Usarne uno al posto dell\'altro di solito vuol dire che hai sbagliato variabile, oppure il tipo nella dichiarazione o nel parametro della funzione.',
  'errori.puntatori-incompatibili.concetto': 'puntatori',
  'errori.intero-puntatore.etichetta': 'numero e indirizzo mescolati',
  'errori.intero-puntatore.frase': 'mescoli un numero e un indirizzo (un puntatore)',
  'errori.intero-puntatore.dove': `Guarda la riga {riga}: da una parte c'è un puntatore, dall'altra un valore normale.`,
  'errori.intero-puntatore.dove-senza-riga': `Guarda la riga indicata: da una parte c'è un puntatore, dall'altra un valore normale.`,
  'errori.intero-puntatore.cosa': 'Un puntatore contiene un indirizzo di memoria, non un numero qualsiasi. Se vuoi l\'indirizzo di una variabile scrivi `&x`; se vuoi il valore a cui punta un puntatore scrivi `*p`.',
  'errori.intero-puntatore.cosa-2': ' Qui il compilatore suggerisce `&`.',
  'errori.intero-puntatore.cosa-3': ' Qui il compilatore suggerisce `*`.',
  'errori.intero-puntatore.cosa-4': ' Attenzione: `"a"` tra virgolette doppie è una stringa; un carattere si scrive tra apici singoli: `\'a\'`.',
  'errori.intero-puntatore.concetto': 'puntatori',
  'errori.variabile-non-usata.etichetta': 'variabile non usata',
  'errori.variabile-non-usata.breve-2': 'variabile',
  'errori.variabile-non-usata.breve': `{nome} non usata`,
  'errori.variabile-non-usata.frase-2': 'una variabile',
  'errori.variabile-non-usata.frase': `{nome} è dichiarata ma non la usi mai`,
  'errori.variabile-non-usata.dove': `Guarda la dichiarazione {allaRiga}.`,
  'errori.variabile-non-usata.cosa': 'È solo un avviso: il programma compila lo stesso. Però spesso vuol dire che ti sei dimenticato di usarla, o che al suo posto usi per sbaglio un\'altra variabile con un nome simile. Se non serve, toglila.',
  'errori.variabile-non-usata.concetto': 'variabili',
  'errori.parametro-non-usato.etichetta': 'parametro non usato',
  'errori.parametro-non-usato.frase': `il parametro {nome} non viene mai usato`,
  'errori.parametro-non-usato.dove': `Guarda la prima riga della funzione {allaRiga}.`,
  'errori.parametro-non-usato.cosa': 'La funzione riceve questo valore ma non lo usa. A volte va bene (per esempio `argc` e `argv` in `main`); altre volte vuol dire che al suo posto usi un\'altra variabile.',
  'errori.parametro-non-usato.concetto': 'parametri delle funzioni',
  'errori.non-inizializzata.etichetta': 'variabile senza valore',
  'errori.non-inizializzata.breve-2': 'variabile',
  'errori.non-inizializzata.breve': `{nome} senza valore`,
  'errori.non-inizializzata.frase-2': 'una variabile',
  'errori.non-inizializzata.frase': `usi {nome} prima di darle un valore`,
  'errori.non-inizializzata.dove-2': 'questa variabile',
  'errori.non-inizializzata.dove-3': ` (riga {dichiarata})`,
  'errori.non-inizializzata.dove': `Guarda {laRiga}, poi risali fino alla dichiarazione di {nome}{dichiarata}: c'è una strada in cui non riceve mai un valore?`,
  'errori.non-inizializzata.cosa': 'In Java una variabile locale deve ricevere un valore prima di essere letta, su ogni strada possibile (anche quando un `if` è falso). Dai un valore di partenza nella dichiarazione, per esempio `int somma = 0;`.',
  'errori.non-inizializzata.cosa-2': 'Una variabile locale appena dichiarata contiene un valore a caso, quello rimasto in memoria. Prima di leggerla devi darle un valore, per esempio `int somma = 0;`. Capita spesso con le somme e i contatori.',
  'errori.non-inizializzata.concetto': 'inizializzazione delle variabili',
  'errori.riferimento-non-definito.etichetta': 'funzione mai definita (linker)',
  'errori.riferimento-non-definito.breve': 'manca main',
  'errori.riferimento-non-definito.breve-3': 'funzione',
  'errori.riferimento-non-definito.breve-2': `{nome} non definita`,
  'errori.riferimento-non-definito.frase': 'manca la funzione `main`',
  'errori.riferimento-non-definito.frase-2': `{nome} non viene trovata: manca \`-lm\` nel comando`,
  'errori.riferimento-non-definito.frase-4': 'una funzione',
  'errori.riferimento-non-definito.frase-3': `{nome} è usata ma non trovo dove è scritta`,
  'errori.riferimento-non-definito.dove': 'Controlla che uno dei file abbia `int main(void)` (oppure `int main(int argc, char *argv[])`) scritto proprio così, e che quel file sia nel comando di compilazione.',
  'errori.riferimento-non-definito.dove-2': 'Guarda il comando di compilazione: alla fine serve `-lm`.',
  'errori.riferimento-non-definito.dove-4': 'questa funzione',
  'errori.riferimento-non-definito.dove-3': `Il linker non indica una riga. Cerca nel progetto il corpo di {nome}, cioè la versione con le \`{ }\`: il nome deve essere identico (maiuscole comprese) e il file che la contiene deve essere nel comando di compilazione.`,
  'errori.riferimento-non-definito.cosa': 'Ogni programma C parte da `main`. Se manca, o è scritta con un altro nome (`Main`, `mian`), non c\'è un punto da cui partire. Su Windows il messaggio a volte parla di `WinMain`: è lo stesso problema.',
  'errori.riferimento-non-definito.cosa-2': 'Le funzioni di `{h}` stanno in una libreria a parte. Su Linux (e a volte con MinGW) bisogna aggiungere `-lm` alla fine del comando: `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'La compilazione ha due fasi: prima ogni file `.c` viene tradotto da solo, poi il linker li unisce. Il prototipo dice al compilatore che la funzione esiste, ma il linker non ha trovato il suo corpo da nessuna parte. Di solito il nome è scritto diverso, un file manca nel comando, o la funzione non è mai stata scritta.',
  'errori.riferimento-non-definito.concetto': 'compilazione e linker',
  'errori.definizione-multipla.etichetta': 'definita due volte (linker)',
  'errori.definizione-multipla.breve-2': 'nome',
  'errori.definizione-multipla.breve': `{nome} definito due volte`,
  'errori.definizione-multipla.frase-2': 'un nome',
  'errori.definizione-multipla.frase': `{nome} è definito due volte nel programma`,
  'errori.definizione-multipla.dove-2': 'questo nome',
  'errori.definizione-multipla.dove': `Cerca {nome} in tutti i file del progetto. Spesso è una variabile o una funzione scritta dentro un file \`.h\` incluso da più file \`.c\`, oppure un file \`.c\` incluso con \`#include\`.`,
  'errori.definizione-multipla.cosa': 'Ogni funzione e ogni variabile globale deve avere una sola definizione in tutto il programma. Nei file `.h` vanno solo i prototipi (e le variabili con `extern`); i corpi delle funzioni vanno nei `.c`. Un file `.c` non si include con `#include`.',
  'errori.definizione-multipla.concetto': 'file .h e .c',
  'errori.tipi-in-conflitto.etichetta': 'dichiarazioni diverse',
  'errori.tipi-in-conflitto.frase-2': 'una funzione',
  'errori.tipi-in-conflitto.frase': `{nome} è dichiarata in due modi diversi`,
  'errori.tipi-in-conflitto.dove-3': ` (riga {prima})`,
  'errori.tipi-in-conflitto.dove': `Confronta la riga {riga} con la dichiarazione precedente{prima}: tipo restituito e parametri devono essere identici.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Confronta la riga indicata con la dichiarazione precedente{prima}: tipo restituito e parametri devono essere identici.`,
  'errori.tipi-in-conflitto.dove-5': 'la funzione',
  'errori.tipi-in-conflitto.dove-4': ` La prima dichiarazione qui è implicita: hai chiamato {nome} prima di dichiararla. Metti il prototipo sopra \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'Il prototipo (la riga con `;`, di solito in alto o in un `.h`) e la funzione vera devono dire le stesse cose: stesso tipo restituito, stessi tipi dei parametri, nello stesso ordine.',
  'errori.tipi-in-conflitto.concetto': 'prototipi delle funzioni',
  'errori.argomenti.etichetta': 'numero di argomenti sbagliato',
  'errori.argomenti.frase': ` ({h} invece di {e})`,
  'errori.argomenti.frase-2': `passi meno argomenti di quelli che la funzione vuole{quanti}`,
  'errori.argomenti.frase-3': `passi più argomenti di quelli che la funzione vuole{quanti}`,
  'errori.argomenti.frase-5': 'questa funzione',
  'errori.argomenti.frase-4': `la chiamata a {nome} non corrisponde ai suoi parametri`,
  'errori.argomenti.dove-2': ` (riga {dich})`,
  'errori.argomenti.dove': `Confronta la chiamata {allaRiga} con la prima riga della funzione{nome}{dich}: conta gli argomenti e guarda i loro tipi.`,
  'errori.argomenti.cosa': 'Una funzione va chiamata con tanti argomenti quanti sono i suoi parametri, nello stesso ordine. Se la funzione è `int somma(int a, int b)`, la chiamata è `somma(x, y)`.',
  'errori.argomenti.concetto': 'parametri delle funzioni',
  'errori.graffa.etichetta': 'graffa che manca',
  'errori.graffa.frase': 'c\'è una `}` di troppo',
  'errori.graffa.frase-2': 'manca una `}`',
  'errori.graffa.dove': `Guarda la \`}\` {allaRiga}: chiude un blocco che era già chiuso. Conta le \`{\` e le \`}\` sopra.`,
  'errori.graffa.dove-3': ` (riga {riga})`,
  'errori.graffa.dove-4': ` La \`{\` rimasta aperta è alla riga {aperta}.`,
  'errori.graffa.dove-2': `Il compilatore se ne accorge solo alla fine{riga}, ma la graffa manca prima.{aperta} Conta le \`{\` e le \`}\` di ogni funzione, di ogni \`if\` e di ogni ciclo.`,
  'errori.graffa.cosa': 'Ogni `{` apre un blocco e ogni `}` lo chiude: devono essere in pari. Con il codice indentato bene (ogni blocco spostato un po\' a destra) la graffa che manca si vede subito.',
  'errori.graffa.concetto': 'blocchi e graffe',
  'errori.parentesi.etichetta': 'parentesi che manca',
  'errori.parentesi.frase': 'manca una `)`',
  'errori.parentesi.dove-2': `, colonna {apertaCol}`,
  'errori.parentesi.dove': `La \`(\` rimasta aperta è alla riga {aperta}{apertaCol}: la sua \`)\` manca prima del punto segnalato {allaRiga}.`,
  'errori.parentesi.dove-3': `Guarda la riga {riga} e conta le \`(\` e le \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Guarda la riga indicata e conta le \`(\` e le \`)\`.`,
  'errori.parentesi.cosa': 'Ogni `(` deve avere la sua `)`. Nelle condizioni lunghe e nelle chiamate dentro altre chiamate è facile perderne una: contale da sinistra a destra.',
  'errori.parentesi.concetto': 'parentesi',
  'errori.espressione-attesa.etichetta': 'manca un valore',
  'errori.espressione-attesa.frase': 'il compilatore si aspettava un valore e non l\'ha trovato',
  'errori.espressione-attesa.dove': `Guarda {laRiga}{colonna}: lì manca qualcosa (un numero, una variabile) oppure c'è un simbolo di troppo. Succede anche con le virgolette non chiuse sulla stessa riga.`,
  'errori.espressione-attesa.cosa': 'Dopo un `=`, un operatore come `+` o una virgola, il compilatore si aspetta un valore. Se trova subito `;`, `)` o un altro simbolo, si ferma.',
  'errori.espressione-attesa.concetto': 'espressioni',
  'errori.ridefinizione.etichetta': 'dichiarato due volte',
  'errori.ridefinizione.breve-2': 'nome',
  'errori.ridefinizione.breve': `{nome} dichiarato due volte`,
  'errori.ridefinizione.frase-2': 'un nome',
  'errori.ridefinizione.frase': `{nome} è dichiarato due volte`,
  'errori.ridefinizione.dove': `Le due dichiarazioni sono alla riga {prima} e alla riga {riga}.`,
  'errori.ridefinizione.dove-4': 'questo nome',
  'errori.ridefinizione.dove-2': `Cerca sopra la riga {riga} un'altra dichiarazione di {nome}.`,
  'errori.ridefinizione.dove-2-senza-riga': `Cerca sopra la riga indicata un'altra dichiarazione di {nome}.`,
  'errori.ridefinizione.cosa': 'Nello stesso blocco un nome si dichiara una volta sola. Se vuoi solo cambiare il valore, scrivi `x = 2;` senza il tipo davanti.',
  'errori.ridefinizione.concetto': 'dichiarazione delle variabili',
  'errori.non-array.etichetta': '`[ ]` su un non array',
  'errori.non-array.frase': 'usi `[ ]` su qualcosa che non è un array',
  'errori.non-array.dove': `Guarda le parentesi quadre {allaRiga}{colonna}.`,
  'errori.non-array.cosa': 'Le parentesi quadre servono a prendere un elemento di un array (o di un puntatore). Una variabile semplice, come un `int`, non ha elementi. Forse volevi usare un\'altra variabile, oppure dichiararla come array, per esempio `int v[10];`.',
  'errori.non-array.concetto': 'array',
  'errori.freccia-punto.etichetta': '`.` e `->` scambiati',
  'errori.freccia-punto.frase': 'con una struttura (non un puntatore) si usa `.`, non `->`',
  'errori.freccia-punto.frase-2': 'con un puntatore a struttura si usa `->`, non `.`',
  'errori.freccia-punto.frase-3': 'il campo della struttura si prende nel modo sbagliato',
  'errori.freccia-punto.dove': `Guarda {laRiga}{colonna}: controlla come è dichiarata la variabile prima del punto o della freccia.`,
  'errori.freccia-punto.cosa': 'Se hai la struttura stessa (`struct nodo n`), il campo si prende con il punto: `n.val`. Se hai un puntatore alla struttura (`struct nodo *p`), si usa la freccia: `p->val`, che vuol dire `(*p).val`.',
  'errori.freccia-punto.concetto': 'strutture e puntatori',
  'errori.membro-inesistente.etichetta': 'campo che non esiste',
  'errori.membro-inesistente.frase-2': 'la struttura',
  'errori.membro-inesistente.frase': `{p} non ha un campo {m}`,
  'errori.membro-inesistente.frase-3': 'la struttura non ha questo campo',
  'errori.membro-inesistente.dove-2': ` con {m}`,
  'errori.membro-inesistente.dove': `Guarda la definizione della struttura{p} e confronta i nomi dei campi{m}.`,
  'errori.membro-inesistente.cosa': 'I campi di una struttura sono quelli scritti nella sua definizione, con quei nomi esatti. Un nome diverso, anche di una lettera sola, è un altro campo.',
  'errori.membro-inesistente.concetto': 'strutture',
  'errori.header-non-trovato.etichetta': 'header non trovato',
  'errori.header-non-trovato.frase-2': 'incluso',
  'errori.header-non-trovato.frase': `non trovo il file {h}`,
  'errori.header-non-trovato.dove': `Guarda la riga \`#include\` {allaRiga}.`,
  'errori.header-non-trovato.dove-2': ` Forse volevi {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` esiste solo con alcuni compilatori vecchi per Windows (Turbo C, Dev-C++): non fa parte del C standard.',
  'errori.header-non-trovato.cosa': 'Con `#include {sistema}` il compilatore cerca il file tra quelli del sistema; con `#include {progetto}` lo cerca prima nella cartella del progetto. Se il nome è sbagliato anche di una lettera, non lo trova e si ferma subito.',
  'errori.header-non-trovato.concetto': 'librerie e #include',
  'errori.file-sorgente-mancante.etichetta': 'file non trovato',
  'errori.file-sorgente-mancante.frase-2': 'indicato',
  'errori.file-sorgente-mancante.frase': `il compilatore non trova il file {h}`,
  'errori.file-sorgente-mancante.dove': 'Guarda il comando di compilazione e i nomi dei file nella cartella.',
  'errori.file-sorgente-mancante.cosa': 'Il comando nomina un file che nella cartella non c\'è. Controlla il nome (maiuscole, estensione `.c`) e che il comando parta dalla cartella giusta.',
  'errori.file-sorgente-mancante.concetto': 'compilazione',
  'errori.non-assegnabile.etichetta': 'assegnamento impossibile',
  'errori.non-assegnabile.frase': 'non puoi copiare un array (o una stringa) con `=`',
  'errori.non-assegnabile.frase-2': 'a sinistra di `=` c\'è qualcosa che non è una variabile',
  'errori.non-assegnabile.dove': `Guarda quello che sta a sinistra di \`=\` {allaRiga}.`,
  'errori.non-assegnabile.cosa': 'Un array non si copia con `=`. Per una stringa usa `strcpy(destinazione, "testo");` da `{h}`, oppure dai il valore quando la dichiari: `char nome[10] = "testo";`.',
  'errori.non-assegnabile.cosa-2': 'A sinistra di `=` deve esserci un posto dove mettere il valore: una variabile, un elemento di array, un campo. Non un calcolo come `a + 1`. Se volevi confrontare, serve `==`.',
  'errori.non-assegnabile.concetto': 'assegnamento',
  'errori.tipo-sconosciuto.etichetta': 'tipo sconosciuto',
  'errori.tipo-sconosciuto.frase-2': 'questo nome',
  'errori.tipo-sconosciuto.frase': `{nome} non è un tipo che il compilatore conosce`,
  'errori.tipo-sconosciuto.dove-2': 'il tipo',
  'errori.tipo-sconosciuto.dove': `Guarda {laRiga} e cerca sopra dove definisci {nome}.`,
  'errori.tipo-sconosciuto.cosa': 'In C il tipo `string` non esiste (c\'è in C++ e in altri linguaggi). Una stringa in C è un array di `char`: `char s[50];` oppure `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Prima di usare un tipo come `Nodo` va definito, per esempio con `typedef struct nodo Nodo;`, sopra la riga che lo usa. Controlla anche maiuscole e minuscole.',
  'errori.tipo-sconosciuto.concetto': 'tipi e typedef',
  'errori.virgolette.etichetta': 'stringa non chiusa',
  'errori.virgolette.frase': 'una stringa non è chiusa: manca `"`',
  'errori.virgolette.dove': `Guarda {laRiga}{colonna}: da lì parte la stringa. Cerca dove dovrebbe finire.`,
  'errori.virgolette.cosa': 'Una stringa inizia e finisce con `"` sulla stessa riga. Se manca quella di chiusura, il compilatore considera stringa tutto il resto della riga e poi si perde: per questo gli errori che vengono dopo spesso spariscono da soli.',
  'errori.virgolette.concetto': 'stringhe',
  'errori.if-vuoto.etichetta': '`;` dopo la condizione',
  'errori.if-vuoto.frase': `c'è un \`;\` subito dopo \`{kw}\``,
  'errori.if-vuoto.frase-2': `c'è un \`;\` subito dopo la condizione {if}`,
  'errori.if-vuoto.dove': `Guarda la riga {riga}: subito dopo \`{kw}\` c'è un \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Guarda la riga indicata: subito dopo \`{kw}\` c'è un \`;\`.`,
  'errori.if-vuoto.dove-3': `Guarda la fine della riga {riga}: dopo la \`)\` della condizione c'è un \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Guarda la fine della riga indicata: dopo la \`)\` della condizione c'è un \`;\`.`,
  'errori.if-vuoto.cosa': 'Il `;` subito dopo `else` è un\'istruzione vuota: l\'`else` comanda solo quella. Il blocco `{ }` sotto viene eseguito sempre, anche quando la condizione dell\'`if` è vera.',
  'errori.if-vuoto.cosa-2': 'Il `;` subito dopo `do` è un\'istruzione vuota: il ciclo ripete solo quella. Il blocco `{ }` sotto non fa parte del ciclo.',
  'errori.if-vuoto.cosa-3': 'Il `;` subito dopo `if (...)` è un\'istruzione vuota: l\'`if` controlla solo quella. Il blocco `{ }` sotto viene eseguito sempre, qualunque sia la condizione. Con `while` è peggio: il ciclo può non finire mai.',
  'errori.if-vuoto.concetto': 'if e cicli',
  'errori.confronto-inutile.etichetta': 'istruzione che non fa niente',
  'errori.confronto-inutile.frase': 'c\'è un `==` che non fa niente: forse volevi `=`',
  'errori.confronto-inutile.frase-2': 'questa istruzione non fa niente',
  'errori.confronto-inutile.dove': `Guarda {laRiga}{colonna}.`,
  'errori.confronto-inutile.cosa': 'Un confronto da solo (`x == 4;`) calcola vero o falso e butta via il risultato. Se volevi dare un valore alla variabile serve un solo `=`: `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'Un calcolo che non viene salvato in una variabile, né stampato, né usato in una condizione, viene buttato via. Forse manca un `=` o una chiamata a funzione.',
  'errori.confronto-inutile.concetto': 'assegnamento e confronto',
  'errori.indirizzo-locale.etichetta': 'indirizzo di una variabile locale',
  'errori.indirizzo-locale.frase-2': 'una variabile locale',
  'errori.indirizzo-locale.frase': `restituisci l'indirizzo di {nome}, che sparisce quando la funzione finisce`,
  'errori.indirizzo-locale.dove': `Guarda il \`return\` {allaRiga}.`,
  'errori.indirizzo-locale.cosa': 'Le variabili locali vivono solo finché la funzione è in esecuzione. Restituire il loro indirizzo vuol dire dare a chi chiama un posto di memoria che non esiste più. Se devi restituire un array, crealo con `malloc` (e poi ricordati `free`), oppure fattelo passare come parametro.',
  'errori.indirizzo-locale.concetto': 'memoria e funzioni',
  'errori.segni-diversi.etichetta': 'numeri con e senza segno',
  'errori.segni-diversi.frase': 'confronti un numero con il segno e uno senza segno',
  'errori.segni-diversi.dove': `Guarda il confronto {allaRiga}.`,
  'errori.segni-diversi.cosa': 'Funzioni come `strlen` restituiscono un numero senza segno (`size_t`). Confrontarlo con un `int` di solito funziona, ma se l\'`int` è negativo il confronto sbaglia. È un avviso: puoi dichiarare l\'indice come `size_t`, oppure salvare la lunghezza in un `int` prima del ciclo.',
  'errori.segni-diversi.concetto': 'tipi interi',
  'errori.return-void.etichetta': '`return` e `void` in contrasto',
  'errori.return-void.frase': '`return;` senza valore in una funzione che deve restituirne uno',
  'errori.return-void.frase-2': 'una funzione `void` non può restituire un valore',
  'errori.return-void.dove': `Guarda il \`return\` {allaRiga} e la prima riga della funzione.`,
  'errori.return-void.cosa': '`void` vuol dire che la funzione non restituisce niente: lì si scrive solo `return;` (o niente). Se la funzione deve dare un risultato, al posto di `void` va il tipo giusto, per esempio `int`, e ogni `return` deve avere un valore.',
  'errori.return-void.concetto': 'return nelle funzioni',
  'errori.main-int.etichetta': '`main` non `int`',
  'errori.main-int.frase': '`main` deve restituire `int`',
  'errori.main-int.dove-2': ` (riga {riga})`,
  'errori.main-int.dove': `Guarda la riga di \`main\`{riga}.`,
  'errori.main-int.cosa': 'Lo standard del C vuole `int main(void)`, e alla fine `return 0;` per dire «tutto bene». `void main` lo accettano solo alcuni compilatori vecchi.',
  'errori.main-int.concetto': 'la funzione main',
  'errori.fuori-array.etichetta': 'indice fuori dall\'array',
  'errori.fuori-array.frase': `usi l'indice {i}, ma l'array non arriva fin lì`,
  'errori.fuori-array.frase-2': 'usi un indice fuori dall\'array',
  'errori.fuori-array.dove-2': ` e la dichiarazione dell'array alla riga {riga}`,
  'errori.fuori-array.dove': `Guarda {laRiga}{riga}.`,
  'errori.fuori-array.cosa': 'Un array di N elementi ha gli indici da `0` a `N-1`: con `int v[5]` l\'ultimo è `v[4]`, e `v[5]` è già fuori. Succede spesso con un ciclo `for (i = 0; i <= 5; i++)` invece di `i < 5`.',
  'errori.fuori-array.concetto': 'array e indici',
  'errori.argomenti-formato.etichetta': '`%` e valori non tornano',
  'errori.argomenti-formato.frase': 'nella stringa ci sono più `%` che valori',
  'errori.argomenti-formato.frase-2': 'passi più valori dei `%` nella stringa',
  'errori.argomenti-formato.dove': `Guarda la stringa {allaRiga} e conta i \`%\` e i valori dopo la virgola.`,
  'errori.argomenti-formato.cosa': 'Ogni `%d`, `%f`, `%c`… nella stringa di `printf` (o `scanf`) prende il valore successivo, nell\'ordine. Il numero di `%` e il numero di valori dopo la stringa devono essere uguali.',
  'errori.argomenti-formato.concetto': 'printf e i formati',
  'errori.divisione-zero.etichetta': 'divisione per zero',
  'errori.divisione-zero.frase': 'dividi per zero',
  'errori.divisione-zero.dove': `Guarda la divisione {allaRiga}.`,
  'errori.divisione-zero.cosa': 'Dividere un intero per zero non ha un risultato: di solito il programma si blocca. Prima di dividere controlla che il divisore non sia zero, per esempio con `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'divisione',
  'errori.troppi-inizializzatori.etichetta': 'troppi valori nell\'array',
  'errori.troppi-inizializzatori.frase': 'metti più valori di quanti l\'array ne può tenere',
  'errori.troppi-inizializzatori.dove': `Guarda la dichiarazione {allaRiga}: confronta la dimensione tra \`[ ]\` con quanti valori ci sono tra \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'Se un array ha posto per 2 valori e tra le graffe ne scrivi 3, il terzo viene buttato. Aumenta la dimensione o togli dei valori. Puoi anche lasciare le quadre vuote, `int v[] = {1, 2, 3};`, e il compilatore conta da solo.',
  'errori.troppi-inizializzatori.concetto': 'array',
  'errori.operandi.etichetta': 'operazione impossibile tra questi tipi',
  'errori.operandi.frase': `l'operazione non si può fare tra {a} e {b}`,
  'errori.operandi.frase-2': 'l\'operazione non si può fare tra questi due tipi',
  'errori.operandi.dove': `Guarda l'operatore {allaRiga}{colonna} e i tipi dei due lati.`,
  'errori.operandi.cosa': 'Gli operatori come `&&`, `+` o `<` vogliono tipi precisi: `&&` lavora su `boolean`, `<` sui numeri. Le stringhe non si confrontano con `<`: si usa `compareTo`, e per l\'uguaglianza `equals`.',
  'errori.operandi.cosa-2': 'Gli operatori come `+`, `-` e `<` funzionano sui numeri (e alcuni sui puntatori). Due strutture non si sommano e non si confrontano direttamente: lavora sui loro campi, per esempio `a.x + b.x`. Le stringhe in C non si uniscono con `+`: si usa `strcat`.',
  'errori.operandi.concetto': 'tipi e operatori',
  'errori.carattere-strano.etichetta': 'carattere strano nel codice',
  'errori.carattere-strano.frase': 'nel codice c\'è un carattere strano',
  'errori.carattere-strano.dove': `Guarda {laRiga}{colonna}.`,
  'errori.carattere-strano.cosa': 'Spesso è un carattere copiato da un PDF o da una pagina web: virgolette curve `“ ”`, un apostrofo curvo, uno spazio speciale o un trattino lungo. A occhio sembrano uguali, ma per il compilatore non lo sono. Riscrivi la riga a mano.',
  'errori.carattere-strano.concetto': 'caratteri nel codice',
  'errori.non-sicura.etichetta': 'Visual Studio e le funzioni «non sicure»',
  'errori.non-sicura.frase-2': 'questa funzione',
  'errori.non-sicura.frase': `Visual Studio non vuole {nome}: la considera non sicura`,
  'errori.non-sicura.dove': 'Non c\'è niente di sbagliato nel tuo C: è una regola di Visual Studio.',
  'errori.non-sicura.cosa': 'Visual Studio segnala `scanf`, `strcpy` e simili perché, usate male, possono scrivere oltre la fine di un array. Il C standard le permette e i corsi le usano. Per spegnere l\'avviso scrivi `#define _CRT_SECURE_NO_WARNINGS` come primissima riga del file, prima degli `#include`. Se il docente preferisce `scanf_s`, segui il docente.',
  'errori.non-sicura.concetto': 'compilatori diversi',
  'errori.ricorsione-infinita.etichetta': 'ricorsione senza fine',
  'errori.ricorsione-infinita.frase': 'la funzione chiama sempre se stessa: non si ferma mai',
  'errori.ricorsione-infinita.dove': `Guarda la funzione{p} {allaRiga}: cerca il caso base, cioè un \`if\` che restituisce un valore senza richiamare la funzione.`,
  'errori.ricorsione-infinita.cosa': 'Una funzione ricorsiva deve avere un caso base, e ogni chiamata deve avvicinarsi a quel caso (per esempio con `n - 1`). Qui ogni strada porta a un\'altra chiamata: il programma riempirà la memoria e si fermerà.',
  'errori.ricorsione-infinita.concetto': 'ricorsione',
  'errori.sintassi.etichetta': 'codice scritto in un modo che il compilatore non capisce',
  'errori.sintassi.frase': 'il compilatore non capisce come continua il codice qui',
  'errori.sintassi.dove': `Guarda {laRiga} e quella prima: spesso il problema vero sta subito sopra, per esempio un \`;\` di troppo dopo la prima riga di una funzione, una \`}\` in più o una parentesi non chiusa.`,
  'errori.sintassi.cosa': 'Il compilatore legge il codice seguendo regole precise, come la grammatica di una lingua. Qui ha trovato qualcosa che in quel punto non può stare. Il messaggio originale dice cosa si aspettava.',
  'errori.sintassi.concetto': 'sintassi',
  'errori.java-tipi.etichetta': 'tipi incompatibili (Java)',
  'errori.java-tipi.frase': `da {dato} a {atteso} si possono perdere dei dati`,
  'errori.java-tipi.frase-2': `{dato} non si può usare dove serve {atteso}`,
  'errori.java-tipi.frase-3': 'il valore non ha il tipo che serve',
  'errori.java-tipi.dove': `Guarda {laRiga}{colonna}: confronta il tipo della variabile con quello del valore.`,
  'errori.java-tipi.cosa': 'In Java ogni variabile ha un tipo e il compilatore controlla che i valori corrispondano. Da `double` a `int` si perdono i decimali, quindi va detto esplicitamente con un cast: `(int) x`. Una `String` non diventa un numero da sola: si usa `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'tipi in Java',
  'errori.java-import.etichetta': 'manca un `import` (Java)',
  'errori.java-import.frase-2': 'questa classe',
  'errori.java-import.frase': `per usare {nome} manca un \`import\``,
  'errori.java-import.dove': 'Guarda in cima al file, sopra la classe, dove ci sono le righe `import`.',
  'errori.java-import.cosa-2': 'Questa classe',
  'errori.java-import.cosa-3': `, cioè \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} sta in un pacchetto della libreria di Java: per usarla serve l'\`import\` in cima al file{nome2}. Controlla anche maiuscole e minuscole.`,
  'errori.java-import.concetto': 'import in Java',
  'errori.java-nome-file.etichetta': 'nome del file e della classe diversi',
  'errori.java-nome-file.frase-2': 'pubblica',
  'errori.java-nome-file.frase-3': 'Classe',
  'errori.java-nome-file.frase': `la classe {nome} deve stare nel file {nome2}`,
  'errori.java-nome-file.dove': 'Guarda il nome del file e la riga `public class`.',
  'errori.java-nome-file.cosa': 'In Java una classe `public` deve stare in un file con lo stesso nome, maiuscole comprese: `public class Main` va in `Main.java`. Rinomina il file o la classe.',
  'errori.java-nome-file.concetto': 'classi e file in Java',
  'errori.java-statico.etichetta': 'non static usato da static',
  'errori.java-statico.frase-2': 'questo nome',
  'errori.java-statico.frase': `{nome} non è \`static\`, ma lo usi da un metodo \`static\``,
  'errori.java-statico.dove-2': 'quel nome',
  'errori.java-statico.dove': `Guarda {laRiga} e la dichiarazione di {nome}.`,
  'errori.java-statico.cosa': '`main` è `static`: appartiene alla classe, non a un oggetto. Da lì puoi usare solo metodi e variabili `static`, oppure creare prima un oggetto con `new` e usare quello. Negli esercizi con una classe sola spesso al metodo manca `static`.',
  'errori.java-statico.concetto': 'static in Java',
  'errori.java-irraggiungibile.etichetta': 'istruzione mai eseguita',
  'errori.java-irraggiungibile.frase': 'questa istruzione non verrà mai eseguita',
  'errori.java-irraggiungibile.dove': `Guarda {laRiga} e la riga prima.`,
  'errori.java-irraggiungibile.cosa': 'Prima di questa riga c\'è un `return`, un `break`, un `continue` o un ciclo che non finisce: da lì il programma non arriva mai qui. Toglila o spostala prima.',
  'errori.java-irraggiungibile.concetto': 'flusso del programma',
  'errori.java-indice.etichetta': 'indice fuori (Java)',
  'errori.java-indice.frase': `usi l'indice {i}, ma la lunghezza è {l}`,
  'errori.java-indice.frase-2': 'leggi una posizione che l\'array (o la stringa) non ha',
  'errori.java-indice.cosa': 'Gli indici partono da 0: con lunghezza 5 vanno da 0 a 4. Controlla la condizione del ciclo: spesso c\'è `<=` dove serve `<`, oppure si usa `length` come indice.',
  'errori.java-indice.concetto': 'array e indici',
  'errori.java-null.etichetta': 'oggetto null (Java)',
  'errori.java-null.frase': 'usi un oggetto che vale `null`',
  'errori.java-null.cosa': 'L\'oggetto non è mai stato creato con `new`, oppure un metodo ha restituito `null`. Le versioni recenti di Java scrivono nel messaggio quale variabile era `null`.',
  'errori.java-null.concetto': 'oggetti e null',
  'errori.java-divisione-zero.etichetta': 'divisione per zero (Java)',
  'errori.java-divisione-zero.frase': 'dividi un intero per zero',
  'errori.java-divisione-zero.cosa': 'Dividere un intero per zero (anche con `%`) non ha un risultato e Java si ferma. Prima della divisione controlla il divisore, per esempio con `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'divisione',
  'errori.java-input.etichetta': 'input che non è un numero (Java)',
  'errori.java-input.frase': `{v} non è un numero`,
  'errori.java-input.frase-2': 'il programma aspettava un numero e ha letto altro',
  'errori.java-input.cosa': 'Il programma voleva un numero e ha trovato altro: lettere, spazi, una riga vuota, oppure una virgola al posto del punto. Controlla cosa scrivi in input, o il file `.in` della prova.',
  'errori.java-input.concetto': 'input',
  'errori.java-stack.etichetta': 'ricorsione senza fine (Java)',
  'errori.java-stack.frase': 'il metodo chiama se stesso troppe volte',
  'errori.java-stack.cosa': 'Ogni metodo ricorsivo ha bisogno di un caso base: una condizione in cui restituisce un valore senza richiamarsi. E ogni chiamata deve avvicinarsi al caso base.',
  'errori.java-stack.concetto': 'ricorsione',
  'errori.py-uguale.etichetta': '`=` al posto di `==`',
  'errori.py-uguale.breve': '= al posto di ==',
  'errori.py-uguale.frase': 'nella condizione c\'è `=` invece di `==`',
  'errori.py-uguale.dove': `Guarda la condizione {allaRiga}.`,
  'errori.py-uguale.cosa': '`=` mette un valore in una variabile; `==` controlla se due valori sono uguali. In una condizione (`if`, `elif`, `while`) serve `==`: `if x == 5:`.',
  'errori.py-uguale.concetto': 'assegnamento e confronto',
  'errori.py-due-punti.etichetta': 'mancano i `:`',
  'errori.py-due-punti.frase': 'mancano i `:` alla fine della riga',
  'errori.py-due-punti.dove': `Guarda la fine della riga {riga}.`,
  'errori.py-due-punti.dove-senza-riga': `Guarda la fine della riga indicata.`,
  'errori.py-due-punti.cosa': 'In Python `if`, `elif`, `else`, `for`, `while`, `def` e `class` finiscono con `:`. I due punti dicono «adesso inizia il blocco», che va scritto sotto, rientrato.',
  'errori.py-due-punti.concetto': 'blocchi in Python',
  'errori.py-parentesi.etichetta': 'parentesi non chiusa',
  'errori.py-parentesi.frase': `c'è una {c} che non chiude niente`,
  'errori.py-parentesi.frase-2': `una {p} non è chiusa`,
  'errori.py-parentesi.dove': `Guarda {laRiga}: conta le parentesi aperte e chiuse. Se la riga sembra giusta, guarda quella prima.`,
  'errori.py-parentesi.cosa': 'Ogni `(`, `[` e `{` deve avere la sua parentesi di chiusura dello stesso tipo. Se ne manca una, Python continua a leggere le righe dopo come se fossero la stessa istruzione.',
  'errori.py-parentesi.concetto': 'parentesi',
  'errori.py-stringa.etichetta': 'stringa non chiusa',
  'errori.py-stringa.frase': 'una stringa non è chiusa',
  'errori.py-stringa.dove': `Guarda {laRiga}: la stringa inizia lì. Cerca dove manca la virgoletta di chiusura.`,
  'errori.py-stringa.cosa': 'Una stringa inizia e finisce con lo stesso tipo di virgolette, `"` oppure `\'`, sulla stessa riga. Se dentro il testo c\'è un apostrofo, usa le virgolette doppie: `"l\'anno"`.',
  'errori.py-stringa.concetto': 'stringhe',
  'errori.py-print.etichetta': '`print` senza parentesi',
  'errori.py-print.frase': '`print` vuole le parentesi',
  'errori.py-print.dove': `Guarda {laRiga}.`,
  'errori.py-print.cosa': 'In Python 3 `print` è una funzione: si scrive `print("ciao")`. La forma senza parentesi era di Python 2, che si trova ancora in vecchi esempi su internet.',
  'errori.py-print.concetto': 'funzioni',
  'errori.py-indentazione.etichetta': 'rientro sbagliato',
  'errori.py-indentazione.frase': 'manca il rientro dopo i due punti',
  'errori.py-indentazione.frase-2': 'c\'è un rientro di troppo',
  'errori.py-indentazione.frase-3': 'il rientro non torna con le righe sopra',
  'errori.py-indentazione.frase-4': 'mescoli tab e spazi nel rientro',
  'errori.py-indentazione.frase-5': 'il rientro della riga è sbagliato',
  'errori.py-indentazione.dove-2': ` L'\`{kw}\` è alla riga {l}.`,
  'errori.py-indentazione.dove': `Guarda {laRiga} e quella sopra: confronta gli spazi a inizio riga.{kw}`,
  'errori.py-indentazione.cosa': 'In Python il rientro (gli spazi a inizio riga) fa parte del codice: dice quali righe stanno dentro un `if`, un `for` o una `def`. Dopo i `:` la riga sotto deve rientrare, e le righe dello stesso blocco devono rientrare uguali. Usa sempre 4 spazi, senza mescolarli con i tab.',
  'errori.py-indentazione.concetto': 'blocchi in Python',
  'errori.py-sintassi.etichetta': 'riga che Python non sa leggere',
  'errori.py-sintassi.frase': 'forse manca una virgola',
  'errori.py-sintassi.frase-2': 'Python non riesce a leggere questa riga',
  'errori.py-sintassi.dove': `Guarda {laRiga}: il segno \`^\` sotto la riga indica dove Python si è accorto del problema. Spesso l'errore vero è appena prima, anche nella riga sopra (una parentesi o una virgoletta non chiusa).`,
  'errori.py-sintassi.cosa': 'Tra due valori di una lista, di una tupla o degli argomenti di una funzione ci vuole la virgola: `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'Python legge il codice seguendo regole precise, come la grammatica di una lingua. Qui ha trovato qualcosa che in quel punto non può stare. Il messaggio originale, dopo `SyntaxError:`, dice cosa non torna.',
  'errori.py-sintassi.concetto': 'sintassi',
  'errori.py-nome.etichetta': 'nome che non esiste',
  'errori.py-nome.breve-2': 'nome',
  'errori.py-nome.breve': `{nome} non definito`,
  'errori.py-nome.frase-2': 'questo nome',
  'errori.py-nome.frase': `{nome} non esiste ancora quando Python arriva alla riga {riga}`,
  'errori.py-nome.frase-senza-riga': `{nome} non esiste ancora quando Python arriva alla riga indicata`,
  'errori.py-nome.dove': `Python propone {s}: controlla se volevi scrivere quello. `,
  'errori.py-nome.dove-3': 'questo nome',
  'errori.py-nome.dove-2': `Cerca dove dai un valore a {nome}: deve stare sopra questa riga ed essere scritto uguale, maiuscole comprese. Se è una funzione, la \`def\` deve venire prima della chiamata.`,
  'errori.py-nome.cosa': 'In Python un nome esiste solo dopo che gli hai dato un valore (`x = ...`), dopo la sua `def` o dopo l\'`import`. Le variabili create dentro una funzione non esistono fuori.',
  'errori.py-nome.cosa-2': ' Attenzione: in Python si scrive `True`, `False` e `None`, con la maiuscola.',
  'errori.py-nome.cosa-3': ` Se {nome} doveva essere un testo, mancano le virgolette: {nome2}.`,
  'errori.py-nome.concetto': 'variabili in Python',
  'errori.py-locale.etichetta': 'variabile locale senza valore',
  'errori.py-locale.frase-2': 'una variabile',
  'errori.py-locale.frase': `usi {nome} dentro la funzione prima di darle un valore`,
  'errori.py-locale.dove-2': 'la variabile',
  'errori.py-locale.dove': `Guarda {laRiga} e cerca, nella stessa funzione, dove assegni {nome}.`,
  'errori.py-locale.cosa': 'Se dentro una funzione assegni un valore a una variabile, per Python quella diventa locale in tutta la funzione, anche nelle righe prima. Così non legge più la variabile con lo stesso nome che sta fuori. Meglio passare il valore come parametro e restituire il risultato con `return`.',
  'errori.py-locale.concetto': 'funzioni e variabili locali',
  'errori.py-tipo-concatena.etichetta': 'testo e numero mescolati',
  'errori.py-tipo-concatena.frase': 'mescoli un testo (`str`) e un numero',
  'errori.py-tipo-concatena.frase-2': `l'operazione non si può fare tra {a} e {b}`,
  'errori.py-tipo-concatena.dove': `Guarda {laRiga}: di che tipo è ciascun valore vicino all'operatore?`,
  'errori.py-tipo-concatena.cosa': 'Per Python `"5"` (testo) e `5` (numero) sono cose diverse. Per unire testo e numero converti il numero: `"Totale: " + str(x)`, oppure usa una f-string: `f"Totale: {x}"`. Se il valore viene da `input()`, ricorda che `input()` restituisce sempre testo: per fare i conti serve `int(input())` o `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'tipi in Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` usate male',
  'errori.py-tipo-indice.frase': 'l\'indice deve essere un numero intero',
  'errori.py-tipo-indice.frase-2': `un valore \`{immut}\` non si può modificare`,
  'errori.py-tipo-indice.frase-3': 'usi `[ ]` su un valore `None`',
  'errori.py-tipo-indice.frase-4': `usi \`[ ]\` su un valore di tipo {p}, che non ha elementi`,
  'errori.py-tipo-indice.dove': `Guarda le parentesi quadre {allaRiga}.`,
  'errori.py-tipo-indice.cosa': 'Con `v[i]` la `i` deve essere un `int`. Se viene da `input()` è testo: convertila con `int()`. Se nasce da una divisione con `/` è un `float`: usa `//`.',
  'errori.py-tipo-indice.cosa-2': 'Le stringhe e le tuple in Python non si cambiano: si crea un valore nuovo, per esempio `s = "C" + s[1:]`. Se ti serve modificare gli elementi, usa una lista.',
  'errori.py-tipo-indice.cosa-3': 'Le quadre `[ ]` servono per liste, stringhe, dizionari e tuple. Un numero non ha elementi. Se il tipo è `NoneType`, la variabile vale `None`: spesso è il risultato di una funzione senza `return`.',
  'errori.py-tipo-indice.concetto': 'liste e indici',
  'errori.py-tipo-argomenti.etichetta': 'numero di argomenti sbagliato',
  'errori.py-tipo-argomenti.frase-2': 'la funzione',
  'errori.py-tipo-argomenti.frase': `{p} è chiamata con il numero sbagliato di argomenti`,
  'errori.py-tipo-argomenti.dove': `Confronta la chiamata {allaRiga} con la riga \`def\` della funzione.`,
  'errori.py-tipo-argomenti.cosa': 'Una funzione va chiamata con tanti argomenti quanti sono i parametri nella sua `def`. Nei metodi di una classe il primo parametro è `self` e Python lo passa da solo: se dice «takes 1 positional argument but 2 were given», forse manca `self` nella `def`.',
  'errori.py-tipo-argomenti.concetto': 'funzioni e parametri',
  'errori.py-non-iterabile.etichetta': '`for` su un numero',
  'errori.py-non-iterabile.frase': `provi a scorrere un valore di tipo {p}, che non ha elementi`,
  'errori.py-non-iterabile.dove': `Guarda {laRiga}: cosa c'è dopo \`in\`?`,
  'errori.py-non-iterabile.cosa': 'Il `for` scorre gli elementi di una lista, di una stringa o di un `range`. Un numero non ha elementi: per ripetere n volte si scrive `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'cicli for',
  'errori.py-non-chiamabile.etichetta': '`( )` dopo qualcosa che non è una funzione',
  'errori.py-non-chiamabile.frase': `metti \`( )\` dopo un valore di tipo {p}, che non è una funzione`,
  'errori.py-non-chiamabile.dove': `Guarda {laRiga}: cosa c'è subito prima delle parentesi tonde?`,
  'errori.py-non-chiamabile.cosa': 'Le parentesi tonde dopo un nome vogliono dire «chiama questa funzione». Spesso una variabile ha lo stesso nome di una funzione (per esempio `sum = 0` e poi `sum(v)`), oppure manca un operatore: `2(x + 1)` invece di `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'funzioni',
  'errori.py-tipo.etichetta': 'tipo sbagliato',
  'errori.py-tipo.frase': 'un\'operazione riceve un valore del tipo sbagliato',
  'errori.py-tipo.dove': `Guarda {laRiga}: di che tipo sono i valori usati? Puoi stamparli con \`print(type(x))\`.`,
  'errori.py-tipo.cosa': 'Ogni valore in Python ha un tipo (`int`, `str`, `list`…) e ogni operazione accetta solo certi tipi. Il messaggio originale dice quali tipi ha trovato.',
  'errori.py-tipo.concetto': 'tipi in Python',
  'errori.py-indice.etichetta': 'posizione che non esiste',
  'errori.py-indice.frase': 'togli un elemento da una lista vuota',
  'errori.py-indice.frase-3': 'la stringa',
  'errori.py-indice.frase-4': 'la tupla',
  'errori.py-indice.frase-5': 'la lista',
  'errori.py-indice.frase-2': `stai leggendo una posizione che {cosa} non ha`,
  'errori.py-indice.dove': `Guarda {laRiga}: quanto vale l'indice in quel momento, e quanti elementi ci sono?`,
  'errori.py-indice.cosa': 'Una lista di n elementi ha le posizioni da `0` a `n-1`: con 3 elementi l\'ultima è `v[2]`. Succede spesso con `range(len(v) + 1)` o con un ciclo che va un passo oltre. Una lista vuota non ha nessuna posizione: anche `v[0]` è un errore.',
  'errori.py-indice.concetto': 'liste e indici',
  'errori.py-chiave.etichetta': 'chiave che non c\'è',
  'errori.py-chiave.frase': `la chiave {k} non è nel dizionario`,
  'errori.py-chiave.frase-2': 'la chiave non è nel dizionario',
  'errori.py-chiave.dove': `Guarda {laRiga}: come è scritta la chiave, e come sono scritte quelle nel dizionario?`,
  'errori.py-chiave.cosa': 'Con `d[k]` la chiave deve esistere già. Controlla come è scritta (maiuscole, spazi, numero o testo). Per controllare prima: `if k in d:`. Per avere un valore di riserva: `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'dizionari',
  'errori.py-valore.etichetta': 'valore sbagliato',
  'errori.py-valore.frase': `{v} non si può trasformare in un numero`,
  'errori.py-valore.frase-2': 'le variabili a sinistra di `=` non sono tante quanti i valori',
  'errori.py-valore.frase-3': 'una funzione matematica riceve un valore che non accetta',
  'errori.py-valore.frase-4': 'il tipo è giusto ma il valore no',
  'errori.py-valore.dove': `Guarda {laRiga}: che valore arriva lì, davvero? Puoi stamparlo con \`print(repr(x))\`.`,
  'errori.py-valore.cosa': '`int()` trasforma in numero solo un testo fatto di cifre. Spazi in mezzo, lettere, il testo vuoto o un numero con la virgola (`"2,5"`) non vanno. Per i decimali serve `float()` e il punto: `"2.5"`. Se leggi da `input()` o da un file, controlla cosa arriva davvero.',
  'errori.py-valore.cosa-2': 'Con `a, b = valori` il numero di variabili a sinistra deve essere uguale al numero di valori a destra. Spesso `split()` restituisce più (o meno) pezzi di quelli che ti aspettavi.',
  'errori.py-valore.cosa-3': 'Funzioni come `math.sqrt` e `math.log` non accettano tutti i numeri: niente radice di un negativo, niente logaritmo di zero. Controlla il valore prima della chiamata.',
  'errori.py-valore.cosa-4': 'Il valore ha il tipo giusto ma non va bene per quell\'operazione. Il messaggio originale dice quale valore non andava.',
  'errori.py-valore.concetto': 'conversioni e input',
  'errori.py-divisione-zero.etichetta': 'divisione per zero',
  'errori.py-divisione-zero.frase': 'dividi per zero',
  'errori.py-divisione-zero.dove': `Guarda {laRiga}: quale divisore vale 0 in quel momento? Spesso è \`len()\` di una lista vuota o un contatore rimasto a 0.`,
  'errori.py-divisione-zero.cosa': 'Dividere per zero non ha un risultato, quindi Python si ferma. Vale anche per `//` e `%`. Prima della divisione controlla il divisore: `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'divisione',
  'errori.py-attributo.etichetta': 'metodo o attributo che non c\'è',
  'errori.py-attributo.frase': `la variabile vale \`None\`, quindi non ha {a}`,
  'errori.py-attributo.frase-2': `il modulo {mod} non ha {a}`,
  'errori.py-attributo.frase-3': `un valore di tipo {p} non ha {a}`,
  'errori.py-attributo.frase-4': 'quel valore non ha questo attributo',
  'errori.py-attributo.dove': `Guarda {laRiga}: cosa c'è prima del punto, e di che tipo è?`,
  'errori.py-attributo.cosa': 'Un valore `None` di solito arriva da una funzione senza `return`, oppure da metodi come `v.sort()` che cambiano la lista e restituiscono `None` (quindi `v = v.sort()` perde la lista).',
  'errori.py-attributo.cosa-2': 'Controlla come è scritto il nome. Se il tuo file si chiama come il modulo (per esempio `random.py` o `math.py`), Python importa il tuo file al posto del modulo vero: rinominalo.',
  'errori.py-attributo.cosa-3': 'Ogni tipo ha i suoi metodi: le liste hanno `append`, `pop`, `sort`; le stringhe hanno `upper`, `split`, `strip`. Controlla il nome del metodo e il tipo della variabile.',
  'errori.py-attributo.concetto': 'metodi e tipi',
  'errori.py-ricorsione.etichetta': 'ricorsione senza fine',
  'errori.py-ricorsione.frase': 'la funzione chiama se stessa troppe volte',
  'errori.py-ricorsione.dove': `Guarda la funzione{funzione} {allaRiga}: dov'è il caso base, e ogni chiamata ci si avvicina?`,
  'errori.py-ricorsione.cosa': 'Ogni funzione ricorsiva ha bisogno di un caso base: una condizione in cui restituisce un valore senza richiamarsi. E ogni chiamata deve avvicinarsi al caso base (per esempio `n - 1`, non `n + 1`). Python si ferma dopo circa 1000 chiamate una dentro l\'altra.',
  'errori.py-ricorsione.concetto': 'ricorsione',
  'errori.py-modulo.etichetta': 'modulo che non c\'è',
  'errori.py-modulo.frase': `nel modulo {m} non c'è {nome}`,
  'errori.py-modulo.frase-2': `il modulo {m} non c'è`,
  'errori.py-modulo.frase-3': 'un modulo non si importa',
  'errori.py-modulo.dove': `Guarda la riga \`import\` {allaRiga}.`,
  'errori.py-modulo.cosa': 'O il nome è scritto male, o il modulo non è installato per questo Python. I moduli esterni (per esempio `numpy`) si installano con `python3 -m pip install nome` (su Windows `py -m pip install nome`). Se il modulo è un tuo file, deve stare nella stessa cartella e chiamarsi `nome.py`.',
  'errori.py-modulo.concetto': 'moduli e import',
  'errori.py-file.etichetta': 'file non trovato',
  'errori.py-file.frase': `non trovo il file {p}`,
  'errori.py-file.dove': `Guarda la \`open\` {allaRiga}.`,
  'errori.py-file.cosa': 'Python cerca il file a partire dalla cartella da cui lanci il programma, non da quella dello script. Controlla il nome, l\'estensione (Windows a volte la nasconde) e la cartella.',
  'errori.py-file.concetto': 'file',
  'errori.py-input-finito.etichetta': 'input finito',
  'errori.py-input-finito.frase': 'il programma chiede un input che non arriva',
  'errori.py-input-finito.dove': `Guarda la \`input()\` {allaRiga}.`,
  'errori.py-input-finito.cosa': '`input()` aspettava una riga, ma l\'input era già finito. Nelle prove con i file `.in` controlla che il file abbia tante righe quante sono le `input()`.',
  'errori.py-input-finito.concetto': 'input',
  'errori.esec-memoria.etichetta': 'memoria che non è sua (segmentation fault)',
  'errori.esec-memoria.breve': 'memoria non sua',
  'errori.esec-memoria.frase': 'il programma ha usato memoria che non è sua',
  'errori.esec-memoria.cosa': 'Qui il puntatore valeva `NULL`. ',
  'errori.esec-memoria.cosa-2': 'Spesso è un puntatore `NULL` (`p->next` con `p` che vale `NULL`), un indice fuori dall\'array o una ricorsione senza fine. Il sistema ferma il programma per proteggere il resto della memoria.',
  'errori.esec-memoria.cosa-3': ` Su Windows questo errore ha il codice {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'puntatori e memoria',
  'errori.esec-divisione-zero.etichetta': 'divisione intera per zero',
  'errori.esec-divisione-zero.frase': 'il programma ha diviso un intero per zero',
  'errori.esec-divisione-zero.cosa': 'Un intero diviso per zero (anche con `%`) non ha un risultato e il sistema ferma il programma. Il nome «floating point exception» inganna: succede proprio con gli interi. Controlla i divisori, per esempio un contatore che vale ancora 0.',
  'errori.esec-divisione-zero.concetto': 'divisione',
  'errori.esec-stack.etichetta': 'pila delle chiamate piena (stack overflow)',
  'errori.esec-stack.frase': 'la pila delle chiamate è piena: forse una ricorsione senza fine',
  'errori.esec-stack.cosa': 'Ogni chiamata a funzione occupa un po\' di memoria nella pila (lo stack). Una funzione ricorsiva senza caso base, o con un caso base che non arriva mai, la riempie. Anche un array locale enorme può bastare: in quel caso usa `malloc`.',
  'errori.esec-stack.concetto': 'ricorsione',
  'errori.esec-fuori-array.etichetta': 'scrittura fuori da un array',
  'errori.esec-fuori-array.frase': 'il programma ha letto o scritto fuori da un array',
  'errori.esec-fuori-array.frase-letto': 'il programma ha letto fuori da un array',
  'errori.esec-fuori-array.frase-scritto': 'il programma ha scritto fuori da un array',
  'errori.esec-fuori-array.cosa': 'Un array di N elementi va da `0` a `N-1`. Controlla le condizioni dei cicli (`<` e non `<=`), le stringhe senza posto per il `\'\\0\'` finale e le `malloc` con la dimensione giusta (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'array e indici',
  'errori.esec-heap.etichetta': 'malloc e free usate male',
  'errori.esec-heap.frase': 'la memoria presa con `malloc` è stata usata male',
  'errori.esec-heap.cosa': 'Succede quando liberi due volte la stessa memoria (`free` due volte), quando usi un puntatore dopo `free`, o quando scrivi oltre la fine di un blocco preso con `malloc`. Dopo `free(p);` aiuta scrivere `p = NULL;`.',
  'errori.esec-heap.concetto': 'memoria dinamica',
  'errori.esec-memoria-persa.etichetta': 'memoria mai liberata',
  'errori.esec-memoria-persa.frase': 'il programma prende memoria con `malloc` e non la libera',
  'errori.esec-memoria-persa.cosa': 'Ogni `malloc` (o `calloc`) deve avere la sua `free` quando la memoria non serve più. Nelle liste va liberato ogni nodo, uno alla volta, prima di perdere il puntatore.',
  'errori.esec-memoria-persa.concetto': 'memoria dinamica',
  'errori.esec-non-inizializzata.etichetta': 'valore mai inizializzato',
  'errori.esec-non-inizializzata.frase': 'il programma usa un valore che non è mai stato inizializzato',
  'errori.esec-non-inizializzata.cosa': 'Una variabile locale (o la memoria presa con `malloc`) contiene valori a caso finché non le dai un valore. Inizializzala prima di leggerla.',
  'errori.esec-non-inizializzata.concetto': 'inizializzazione delle variabili',
  'errori.esec-asserzione.etichetta': 'assert fallita',
  'errori.esec-asserzione.frase': `una \`assert\` è fallita: {cond} era falsa`,
  'errori.esec-asserzione.frase-2': 'una `assert` è fallita',
  'errori.esec-asserzione.cosa': '`assert(condizione)` ferma il programma se la condizione è falsa. Chi l\'ha scritta (tu o il docente) dice: «qui deve essere sempre vero». Il problema vero è prima: cerca dove il valore è diventato sbagliato.',
  'errori.esec-asserzione.concetto': 'assert e controlli',
  'errori.esec-abort.etichetta': 'programma interrotto (abort)',
  'errori.esec-abort.frase': 'il programma si è interrotto da solo (abort)',
  'errori.esec-abort.cosa': 'Di solito lo chiede la libreria quando trova un problema grave: una `assert` fallita, una `free` sbagliata, memoria rovinata. Guarda le righe stampate subito prima: spesso dicono il motivo.',
  'errori.esec-abort.concetto': 'memoria dinamica',
  'errori.esec-overflow.etichetta': 'intero troppo grande',
  'errori.esec-overflow.frase': 'un intero è diventato troppo grande',
  'errori.esec-overflow.cosa': 'Un `int` arriva a 2147483647. Oltre, il risultato è sbagliato. Succede con fattoriali e potenze: usa `long long` (con `%lld` in `printf`), oppure controlla i conti.',
  'errori.esec-overflow.concetto': 'tipi interi',
  'errori.esec-tempo.etichetta': 'tempo scaduto',
  'errori.esec-tempo.frase': 'il programma non ha finito in tempo',
  'errori.esec-tempo.cosa': 'Forse c\'è un ciclo che non finisce: la condizione non diventa mai falsa, oppure la variabile del ciclo non cambia. Oppure il programma aspetta un input (`scanf`, `input()`) che non arriva.',
  'errori.esec-tempo.concetto': 'cicli',
  'errori.esec-segnale.etichetta': 'programma fermato dal sistema',
  'errori.esec-segnale.frase': `il programma è stato fermato dal sistema{segnale}`,
  'errori.esec-segnale.cosa': 'Il sistema ha fermato il programma mentre girava. Lode non sa dire di più da questo segnale: guarda le ultime righe stampate e le righe cambiate da poco.',
  'errori.esec-segnale.concetto': 'esecuzione',
  // ---- fuori dal dizionario: luoghi, conti, passi, correzioni, scheda ----
  'errori.tempo-scaduto': 'Tempo scaduto',
  'errori.segnale': 'Segnale {sig}',
  'errori.codice-uscita': `Codice d'uscita {codice}`,
  'errori.codice-uscita-windows': `Codice d'uscita {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'un altro errore', other: 'altri {n} errori' },
  'errori.avvisi': { one: '1 avviso', other: '{n} avvisi' },
  'errori.conto': 'e {cosa}',
  'errori.conto-errori-e-avvisi': 'e {errori} e {avvisi}',
  'errori.un-nome': 'un nome',
  'errori.alla-riga': 'alla riga {n}',
  'errori.nel-punto-indicato': 'nel punto indicato',
  'errori.la-riga': 'la riga {n}',
  'errori.il-punto-indicato': 'il punto indicato',
  'errori.colonna': ', colonna {n}',
  'errori.del-if': "dell'`if`",
  'errori.del-while': 'del `while`',
  'errori.del-for': 'del `for`',
  'errori.sconosciuto': 'errore sconosciuto',
  'errori.errore': 'errore',
  'errori.nella-funzione': ', nella funzione {funzione}',
  'errori.di-file': ' di {file}',
  'errori.fermato-alla-riga': 'Il programma si è fermato alla riga {riga}{file}{funzione}.',
  'errori.poi-guarda-cambiate': ` Poi guarda le righe cambiate dopo l'ultima prova riuscita: {righe}.`,
  'errori.guarda-prima-cambiate': `Guarda prima le righe cambiate dopo l'ultima prova riuscita: {righe}.`,
  'errori.sistema-senza-riga': 'Il sistema non dice la riga. Aggiungi qualche `printf` per capire fin dove arriva il programma; su Mac e Linux puoi anche compilare con `-g -fsanitize=address` per avere file e riga.',
  'errori.messaggio-senza-riga': 'Il messaggio non dice la riga: guarda le ultime righe stampate dal programma.',
  'errori.cambiate-e-altre': '{righe} e altre {n}',
  'errori.correggi-punto': `Aggiungi \`;\` alla fine dell'istruzione: sulla riga {riga} o su quella prima.`,
  'errori.correggi-punto-senza-riga': 'Aggiungi `;` alla fine dell\'istruzione.',
  'errori.correggi-punto-fine': `Alla fine della riga {riga} aggiungi \`;\`:`,
  'errori.correggi-punto-dentro': `Nella riga {riga}, nel punto indicato, aggiungi \`;\`:`,
  'errori.correggi-include-in-cima': 'In cima al file, insieme agli altri `#include`, aggiungi:',
  'errori.correggi-include-dopo': 'Dopo la riga {riga} aggiungi:',
  'errori.correggi-include-primo': 'In cima al file aggiungi:',
  'errori.correggi-uguale': 'Nella condizione sostituisci `=` con `==`.',
  'errori.correggi-uguale-riga': `Alla riga {riga} sostituisci \`=\` con \`==\`:`,
  'errori.correggi-return': `Prima della \`}\` che chiude {nome} aggiungi un \`return\` con il valore giusto per i casi rimasti fuori. Quale valore lo decidi tu: dipende da cosa deve calcolare la funzione.`,
  'errori.correggi-return-senza-nome': `Prima della \`}\` che chiude la funzione aggiungi un \`return\` con il valore giusto per i casi rimasti fuori. Quale valore lo decidi tu: dipende da cosa deve calcolare la funzione.`,
  'errori.generico.dove-linker': 'Il linker non indica una riga: cerca nel progetto il nome citato nel messaggio, e controlla che tutti i file `.c` siano nel comando di compilazione.',
  'errori.generico.dove-senza-riga': 'Il messaggio non indica una riga: leggi il testo originale qui sotto.',
  'errori.generico.dove-python': '{L} si è fermato {allaRiga}{file}. Se lì sembra tutto giusto, guarda la riga prima.',
  'errori.generico.dove': 'Guarda {laRiga}{colonna}{file}. Se lì sembra tutto giusto, guarda anche la riga prima: spesso il compilatore si accorge di un problema solo dopo.',
  'errori.generico.eccezione-leggendo': '{eccezione} è il tipo di errore che {L} ha incontrato mentre leggeva il programma. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} è il tipo di errore che {L} ha incontrato mentre eseguiva il programma. ',
  'errori.generico.cosa': 'Lode non ha ancora una spiegazione per questo messaggio. Il testo originale è qui sotto: leggi le parole tra apici, di solito sono il nome o il tipo che dà problemi.',
  'errori.catena': ' Ci sei arrivato così: {passi}.',
  'errori.catena-passo': 'riga {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, riga {riga}',
  'errori.luogo-riga': 'riga {riga}',
  'errori.non-lo-conosco': 'questo errore non lo conosco ancora',
  'errori.parola-avviso': 'avviso',
  'errori.e-un-avviso': `È un avviso: il programma compila lo stesso, ma così com'è probabilmente non fa quello che vuoi. {cosa}`,
  'errori.passo-dove': 'Dove guardare',
  'errori.passo-cosa': 'Cosa vuol dire',
  'errori.passo-correzione': 'Fammi vedere la correzione',
  'errori.file-cambiato': 'Il file è cambiato da allora: i numeri di riga potrebbero non tornare.',
  'errori.tipo-errore': 'Errore',
  'errori.tipo-avviso': 'Avviso',
  'errori.tipo-linker': 'Errore del linker',
  'errori.tipo-esecuzione': 'Si è fermato',
  'errori.segnaposto-valore': '‹valore›',
  'errori.correzione-vista': 'correzione vista',
  'errori.messaggio-originale': 'Messaggio originale',
};
