// «Cose nuove», il dizionario fisso della libreria standard (italiano, lingua di partenza): per ogni voce la domanda da orale
// e la risposta. I nomi delle funzioni e le regole che le cercano nel codice restano in js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': 'Cosa contiene la memoria appena restituita da malloc?',
  'glossario.malloc.risposta': 'Valori a caso: malloc non la azzera. Se non c\'è memoria restituisce NULL, quindi si controlla prima di usarla.',
  'glossario.calloc.domanda': 'Che differenza c\'è tra calloc(n, size) e malloc(n * size)?',
  'glossario.calloc.risposta': 'calloc mette a zero tutti i byte, malloc lascia valori a caso. Se non c\'è memoria tutte e due restituiscono NULL.',
  'glossario.realloc.domanda': 'Cosa fa realloc se fallisce?',
  'glossario.realloc.risposta': 'Restituisce NULL e il vecchio blocco resta valido: va liberato a parte. Per questo si scrive p2 = realloc(p, n) e non p = realloc(p, n).',
  'glossario.free.domanda': 'Cosa succede se usi un puntatore dopo free?',
  'glossario.free.risposta': 'È comportamento indefinito: quella memoria non è più tua. Anche liberarla due volte lo è. free(NULL) invece non fa niente.',
  'glossario.strtok.domanda': 'Perché strtok non si può usare su una stringa letterale?',
  'glossario.strtok.risposta': 'Perché scrive nella stringa: al posto di ogni separatore mette \'\\0\'. Dalla seconda chiamata si passa NULL e strtok riparte dal punto che ricorda lei.',
  'glossario.strcpy.domanda': 'Cosa controlla strcpy sulla dimensione della destinazione?',
  'glossario.strcpy.risposta': 'Niente: copia fino al \'\\0\' compreso. Se la destinazione è troppo piccola scrive oltre la fine dell\'array, ed è comportamento indefinito.',
  'glossario.strncpy.domanda': 'strncpy(d, s, n) mette sempre il \'\\0\' finale?',
  'glossario.strncpy.risposta': 'No: se s ha n caratteri o più, in d non c\'è nessun \'\\0\'. Se s è più corta, riempie di zeri il resto.',
  'glossario.strcmp.domanda': 'Cosa restituisce strcmp se le due stringhe sono uguali?',
  'glossario.strcmp.risposta': '0. Un numero negativo se la prima viene prima, positivo se viene dopo: per questo if (strcmp(a, b)) vuol dire «sono diverse».',
  'glossario.strlen.domanda': 'strlen conta anche il \'\\0\' finale?',
  'glossario.strlen.risposta': 'No: conta i caratteri prima del \'\\0\'. Per copiare la stringa servono strlen(s) + 1 byte.',
  'glossario.strcat.domanda': 'Cosa serve perché strcat(d, s) funzioni?',
  'glossario.strcat.risposta': 'd deve già contenere una stringa con il \'\\0\' e avere posto per tutte e due, più il \'\\0\'. strcat lo spazio non lo controlla.',
  'glossario.memcpy.domanda': 'Si può usare memcpy se sorgente e destinazione si sovrappongono?',
  'glossario.memcpy.risposta': 'No, è comportamento indefinito. In quel caso si usa memmove.',
  'glossario.memset.domanda': 'memset(v, 1, n * sizeof(int)) mette a 1 gli int di v?',
  'glossario.memset.risposta': 'No: memset scrive lo stesso valore in ogni byte, quindi ogni int a 32 bit vale 16843009. Per azzerare invece va bene: memset(v, 0, …).',
  'glossario.sizeof.domanda': 'Quanto vale sizeof(v) se v è un parametro int v[]?',
  'glossario.sizeof.risposta': 'La dimensione di un puntatore, non dell\'array: come parametro, int v[] è int *v. Per questo la lunghezza si passa a parte.',
  'glossario.fgets.domanda': 'Cosa lascia fgets in fondo alla riga letta?',
  'glossario.fgets.risposta': 'L\'a capo, se ci stava, e poi il \'\\0\': con fgets(s, n, f) legge al massimo n - 1 caratteri. A fine file restituisce NULL.',
  'glossario.scanf.domanda': 'Cosa restituisce scanf?',
  'glossario.scanf.risposta': 'Quanti valori ha letto e assegnato, o EOF se l\'input finisce prima. Se non lo controlli, una lettera al posto di un numero passa in silenzio.',
  'glossario.sscanf.domanda': 'Che differenza c\'è tra scanf e sscanf?',
  'glossario.sscanf.risposta': 'sscanf legge da una stringa invece che dall\'input. Si usa spesso dopo fgets: prima leggi la riga intera, poi la scomponi.',
  'glossario.fopen.domanda': 'Cosa restituisce fopen se il file non si apre?',
  'glossario.fopen.risposta': 'NULL: va controllato prima di leggere o scrivere. Attenzione: con "w" un file che c\'è già si svuota subito.',
  'glossario.fclose.domanda': 'Cosa fa fclose su un file in cui hai scritto?',
  'glossario.fclose.risposta': 'Scrive nel file quello che è ancora nel buffer e libera il FILE. Dopo fclose quel puntatore non si usa più.',
  'glossario.fprintf.domanda': 'Che differenza c\'è tra fprintf(stderr, ...) e printf(...)?',
  'glossario.fprintf.risposta': 'printf scrive su stdout, fprintf sul flusso che gli passi. stderr di solito non ha buffer e non finisce nel file se reindirizzi l\'uscita con >.',
  'glossario.atoi.domanda': 'Cosa restituisce atoi("ciao")?',
  'glossario.atoi.risposta': '0, senza nessun segnale di errore: non distingui "0" da un testo sbagliato. Per controllare si usa strtol.',
  'glossario.strtol.domanda': 'A cosa serve il secondo argomento di strtol?',
  'glossario.strtol.risposta': 'È un char ** dove strtol mette il punto in cui si è fermata: se coincide con l\'inizio, non ha letto cifre. Il terzo argomento è la base.',
  'glossario.qsort.domanda': 'Cosa deve restituire la funzione di confronto di qsort?',
  'glossario.qsort.risposta': 'Un int negativo, zero o positivo se il primo elemento va prima, è uguale o va dopo. Riceve due const void * da convertire al tipo giusto.',
  'glossario.exit.domanda': 'Che differenza c\'è tra exit(1) e return 1 dentro main?',
  'glossario.exit.risposta': 'Dentro main fanno la stessa cosa. exit però chiude il programma da qualunque funzione, dopo aver svuotato e chiuso i file aperti.',
  'glossario.assert.domanda': 'Cosa fa assert(x) se x è falso?',
  'glossario.assert.risposta': 'Scrive su stderr la condizione, il file e la riga, poi ferma il programma con abort. Con -DNDEBUG gli assert spariscono: dentro non va codice che serve.',
  'glossario.static-locale.domanda': 'Cosa cambia se una variabile dentro una funzione è static?',
  'glossario.static-locale.risposta': 'Si inizializza una volta sola e tiene il valore da una chiamata all\'altra. Se non la inizializzi parte da 0.',
  'glossario.computeifabsent.domanda': 'Cosa fa map.computeIfAbsent(k, x -> new ArrayList<>())?',
  'glossario.computeifabsent.risposta': 'Se k non c\'è crea la lista, la mette nella mappa e la restituisce. Se c\'è già, restituisce quella. Così dopo puoi fare .add senza controlli.',
  'glossario.getordefault.domanda': 'Cosa restituisce map.getOrDefault(k, 0) se k non c\'è?',
  'glossario.getordefault.risposta': '0, e la mappa non cambia: k non viene aggiunta.',
  'glossario.putifabsent.domanda': 'Cosa restituisce map.putIfAbsent(k, v)?',
  'glossario.putifabsent.risposta': 'Il valore che c\'era già, e allora la mappa non cambia. Se k non c\'era mette v e restituisce null.',
  'glossario.list-remove.domanda': 'Su una List<Integer> con [5, 7, 9], cosa fa list.remove(1)?',
  'glossario.list-remove.risposta': 'Toglie l\'elemento in posizione 1, cioè 7: con un int si sceglie remove(int indice). Per togliere il valore 1 serve list.remove(Integer.valueOf(1)).',
  'glossario.equals.domanda': 'Che differenza c\'è tra == ed equals su due String?',
  'glossario.equals.risposta': '== controlla se sono lo stesso oggetto, equals se hanno gli stessi caratteri. Due stringhe uguali possono essere due oggetti diversi.',
  'glossario.hashcode.domanda': 'Se ridefinisci equals, cosa devi fare con hashCode?',
  'glossario.hashcode.risposta': 'Ridefinire anche lui: oggetti uguali per equals devono avere lo stesso hashCode. Se no HashMap e HashSet non li ritrovano.',
  'glossario.collections-sort.domanda': 'Collections.sort è stabile?',
  'glossario.collections-sort.risposta': 'Sì: gli elementi uguali per il confronto restano nell\'ordine di prima. Ordina la lista sul posto e non restituisce niente.',
  'glossario.comparator-comparing.domanda': 'Cosa fa Comparator.comparing(Studente::getVoto).reversed()?',
  'glossario.comparator-comparing.risposta': 'Confronta gli studenti per voto, al contrario: dal più alto al più basso. Con thenComparing aggiungi un secondo criterio a parità di voto.',
  'glossario.optional.domanda': 'Perché non si chiama get() su un Optional senza controllare?',
  'glossario.optional.risposta': 'Se è vuoto, get() lancia NoSuchElementException. Si usa orElse, orElseGet o isPresent.',
  'glossario.stream.domanda': 'Cosa succede se su uno stream chiami solo map e filter, senza collect?',
  'glossario.stream.risposta': 'Niente: map e filter sono pigre. Il lavoro parte solo con un\'operazione finale come collect, forEach o count. E uno stream si usa una volta sola.',
  'glossario.stringbuilder.domanda': 'Perché in un ciclo si usa StringBuilder invece di s = s + x?',
  'glossario.stringbuilder.risposta': 'Una String non cambia mai: ogni + ne crea una nuova e ricopia tutto. StringBuilder aggiunge in fondo allo stesso oggetto, e toString() dà il risultato.',
  'glossario.integer-parseint.domanda': 'Cosa succede con Integer.parseInt("12a")?',
  'glossario.integer-parseint.risposta': 'Lancia NumberFormatException. Anche " 12" con lo spazio la lancia: prima si usa trim().',
  'glossario.scanner-nextint.domanda': 'Perché un nextLine() subito dopo nextInt() restituisce una riga vuota?',
  'glossario.scanner-nextint.risposta': 'nextInt legge il numero ma lascia lì l\'a capo. nextLine legge fino a quell\'a capo e restituisce "". Si fa un nextLine() in più per scartarlo.',
  'glossario.try-with-resources.domanda': 'Cosa fa try (Scanner in = new Scanner(f)) { ... }?',
  'glossario.try-with-resources.risposta': 'Chiude da solo la risorsa alla fine del blocco, anche se arriva un\'eccezione. Funziona con le classi che implementano AutoCloseable.',
  'glossario.instanceof.domanda': 'Cosa restituisce x instanceof String se x è null?',
  'glossario.instanceof.risposta': 'false, senza eccezioni. Da Java 16 puoi scrivere x instanceof String s e usare subito s.',
  'glossario.arrays-aslist.domanda': 'Cosa succede se fai add sulla lista di Arrays.asList?',
  'glossario.arrays-aslist.risposta': 'Lancia UnsupportedOperationException: la lista ha dimensione fissa ed è legata all\'array. set invece funziona, e cambia anche l\'array.',
  'glossario.iterator-remove.domanda': 'Come togli elementi da una lista mentre la scorri?',
  'glossario.iterator-remove.risposta': 'Con un Iterator e it.remove(), oppure con removeIf. Con list.remove dentro un for-each di solito arriva ConcurrentModificationException.',
  'glossario.substring.domanda': 'Cosa restituisce "lezione".substring(1, 4)?',
  'glossario.substring.risposta': '"ezi": i caratteri dalla posizione 1 alla 3. Il secondo indice è escluso, e la stringa di partenza non cambia.',
  'glossario.compareto.domanda': 'Cosa restituisce a.compareTo(b)?',
  'glossario.compareto.risposta': 'Un numero negativo se a viene prima di b, zero se sono uguali, positivo se viene dopo. Non per forza -1 o 1: conta il segno.',
  'glossario.list-comprehension.domanda': 'Cosa costruisce [x * 2 for x in v if x > 0]?',
  'glossario.list-comprehension.risposta': 'Una lista nuova con il doppio dei soli elementi positivi di v. È un for con if e append scritto in una riga; v non cambia.',
  'glossario.list-comprehension-annidata.domanda': 'In [x for riga in m for x in riga], quale for è quello esterno?',
  'glossario.list-comprehension-annidata.risposta': 'Il primo: i for si leggono nell\'ordine in cui li scriveresti uno dentro l\'altro. Il risultato è m appiattita in una lista sola.',
  'glossario.lambda.domanda': 'Cosa può contenere una lambda in Python?',
  'glossario.lambda.risposta': 'Una sola espressione, che diventa il valore restituito. Niente istruzioni come return, for o un assegnamento normale.',
  'glossario.sorted-con-key.domanda': 'Cosa fa sorted(v, key=len)?',
  'glossario.sorted-con-key.risposta': 'Restituisce una lista nuova ordinata per lunghezza; v resta com\'è. A parità di lunghezza l\'ordine di partenza resta: l\'ordinamento è stabile.',
  'glossario.enumerate.domanda': 'Cosa dà enumerate(v)?',
  'glossario.enumerate.risposta': 'Le coppie (indice, elemento), con l\'indice che parte da 0. Con enumerate(v, 1) parte da 1.',
  'glossario.zip.domanda': 'Cosa fa zip se le liste hanno lunghezze diverse?',
  'glossario.zip.risposta': 'Si ferma alla più corta: gli elementi in più si perdono senza errore. Da Python 3.10, con strict=True dà errore.',
  'glossario.dict-get.domanda': 'Che differenza c\'è tra d[k] e d.get(k)?',
  'glossario.dict-get.risposta': 'd[k] lancia KeyError se k manca, d.get(k) restituisce None, o il secondo argomento se lo passi. get non aggiunge k.',
  'glossario.setdefault.domanda': 'Cosa fa d.setdefault(k, [])?',
  'glossario.setdefault.risposta': 'Se k manca la aggiunge con [] e restituisce quella lista. Se c\'è già, restituisce il valore che c\'è. La [] si crea comunque a ogni chiamata.',
  'glossario.defaultdict.domanda': 'Cosa succede se leggi una chiave che manca in un defaultdict(list)?',
  'glossario.defaultdict.risposta': 'La crea con una lista vuota e la restituisce, senza KeyError. Attenzione: anche solo leggere d[k] aggiunge k.',
  'glossario.counter.domanda': 'Cosa restituisce un Counter per una chiave che non ha mai visto?',
  'glossario.counter.risposta': '0, senza KeyError e senza aggiungerla. most_common(n) dà le n più frequenti.',
  'glossario.with-open.domanda': 'Perché si scrive with open(nome) as f?',
  'glossario.with-open.risposta': 'Il file si chiude da solo all\'uscita dal blocco, anche se arriva un\'eccezione. Senza with devi chiamare f.close().',
  'glossario.yield.domanda': 'Cosa restituisce una funzione che contiene yield?',
  'glossario.yield.risposta': 'Un generatore. Il corpo parte solo quando chiedi il primo valore, con next o con un for, e si ferma a ogni yield. Si scorre una volta sola.',
  'glossario.args-e-kwargs.domanda': 'In def f(*args, **kwargs), cosa sono args e kwargs?',
  'glossario.args-e-kwargs.risposta': 'args è una tupla con gli argomenti posizionali in più, kwargs un dizionario con quelli passati per nome.',
  'glossario.rovescia.domanda': 'Cosa dà v[::-1]?',
  'glossario.rovescia.risposta': 'Una copia di v al contrario: funziona con liste, stringhe e tuple. v non cambia.',
  'glossario.is-e-uguale.domanda': 'Che differenza c\'è tra is e ==?',
  'glossario.is-e-uguale.risposta': '== confronta i valori, is controlla se sono lo stesso oggetto. is si usa con None; con numeri e stringhe si usa ==.',
  'glossario.default-mutabile.domanda': 'Perché def f(x, v=[]) è una trappola?',
  'glossario.default-mutabile.risposta': 'La lista di default si crea una volta sola, quando si definisce f: ogni chiamata vede le modifiche di quelle prima. Si scrive v=None e dentro si crea la lista.',
  'glossario.f-string.domanda': 'Cosa stampa print(f"{x:.2f}") se x vale 3.14159?',
  'glossario.f-string.risposta': '3.14: dopo i due punti c\'è il formato, e .2f vuol dire due cifre dopo la virgola, arrotondate.',
  'glossario.extend.domanda': 'Che differenza c\'è tra v.append(w) e v.extend(w)?',
  'glossario.extend.risposta': 'append aggiunge w come un solo elemento, anche se è una lista. extend aggiunge uno per uno gli elementi di w. Tutte e due cambiano v e restituiscono None.',
  'glossario.split.domanda': 'Che differenza c\'è tra s.split() e s.split(" ")?',
  'glossario.split.risposta': 'Senza argomenti divide su qualsiasi spazio, anche più di uno, e salta le parti vuote. Con " " ogni spazio separa: due spazi di fila danno una stringa vuota.',
  'glossario.da-riga': 'Da: {file}, riga {riga}',
};
