// «Voglio fare…» (js/guida.js e la guida nella barra, js/lode.js): le schede della guida passo passo e le ricette scritte a
// mano per quando non c'è l'AI. Ogni passo di una ricetta è un elenco di quattro testi: [titolo, cosa si fa (2-4 frasi
// semplici), quando è fatto, un aiuto per chi non ci riesce]. Il numero dei passi di ogni ricetta è in RICETTE di js/guida.js.
export default {
  'guida.serve-per': 'Per «{cosa}» ti servono:',
  'guida.nessuna-app': 'Sul computer non ho trovato app adatte. Va bene così: quando serve, il passo ti dice cosa installare.',
  'guida.apri': 'Apri',
  'guida.apri-tutte': 'Apri tutte',
  'guida.aperta': 'Aperta: {app}.',
  'guida.non-aperta': 'Non sono riuscito ad aprire {app}.',
  'guida.cominciamo': 'Cominciamo',
  'guida.preparo': 'Preparo il piano',
  'guida.piano-ai': 'Piano scritto con {motore}: se un passo non fa per te, saltalo.',
  'guida.piano-ricetta': 'Piano di Lode, senza AI.',
  'guida.piano-generico': 'Per questo non ho una ricetta: ti propongo un piano generico, da adattare.',
  'guida.piano-ripiego': 'L\'AI non ha dato un piano valido: uso quello di Lode.',
  'guida.passo-di': 'Passo {i} di {tot}',
  'guida.fatto-quando': 'Fatto quando: {quando}',
  'guida.ti-serve': 'Ti serve: {app}',
  'guida.fatto-avanti': 'Fatto, avanti',
  'guida.non-ci-riesco': 'Non ci riesco',
  'guida.indietro': 'Indietro',
  'guida.basta': 'Basta',
  'guida.un-aiuto': 'Un aiuto',
  'guida.piu-piccolo': 'Più piccolo, un pezzo alla volta:',
  'guida.ci-penso': 'Ci penso',
  'guida.fallo-con': 'Fallo con {agente}',
  'guida.scegli-cartella': 'Prima scegli la cartella in cui lavorare.',
  'guida.cartella': 'Scegli la cartella',
  'guida.testo-agente': 'Questo è il testo che arriva a {agente}, nella cartella «{cartella}». Puoi cambiarlo.',
  'guida.nota-agente': 'Si apre una finestra del Terminale con {agente}: usa il tuo abbonamento, nessuna chiave. Leggi cosa fa prima di dire di sì.',
  'guida.agente-aperto': 'Ho aperto il Terminale con {agente}.',
  'guida.agente-segue': 'La cartella è seguita da Lode: quando {agente} finisce, te lo dico qui.',
  'guida.agente-errore': 'Il Terminale non si è aperto: {errore}',
  'guida.agente-finito': '{agente} ha finito: controlla e premi Fatto.',
  'guida.prompt-agente': 'Sto facendo questo: {obiettivo}. Adesso il passo è «{passo}»: {cosa} Fai solo questo passo, spiegami in parole semplici cosa fai e fermati alla fine.',
  'guida.fine-titolo': 'Fatto tutto!',
  'guida.fine-testo': { one: '{titolo}: il passo è fatto. Bel lavoro.', other: '{titolo}: {n} passi su {n}, tutti fatti. Bel lavoro.' },
  'guida.chiusa': 'Guida messa da parte',
  'guida.chiusa-nota': 'Quando vuoi continuare, scrivi «riprendi la guida».',
  'guida.ripresa': 'Riprendo da dove eri rimasto.',
  'guida.nessuna': 'Non hai una guida a metà. Prova a scrivere «voglio fare una presentazione».',
  'guida.proposta-titolo': 'A metà: {titolo}',
  'guida.proposta-testo': 'Sei al passo {i} di {tot}.',
  'guida.proposta-bottone': 'Riprendi',
  'guida.nel-vault': 'La lista dei passi è anche nel vault: {nota}.',
  // la nota nel vault (nella lingua del vault)
  'guida.nota-file': 'Passo passo',
  'guida.nota-intro': 'La guida di Lode. Lode spunta un passo quando premi «Fatto, avanti» nella barra.',
  'guida.nota-quando': 'Fatto quando',
  'guida.linguaggio': 'il tuo linguaggio',

  // le ricette: [titolo, cosa, fatto quando, aiuto]
  'guida.r-tesi-1': ['Capisci cosa ti chiedono', 'Rileggi la consegna o parla con il relatore. Scrivi in una riga la domanda a cui risponde il tuo lavoro. Segna la scadenza e quante pagine servono.', 'hai una frase con la domanda e la data di consegna', 'Se non sai da dove partire, scrivi tre domande che ti incuriosiscono sull\'argomento e scegli quella con più materiale.'],
  'guida.r-tesi-2': ['Raccogli le fonti', 'Cerca 5-10 fonti serie: libri, articoli, dispense del corso. Salvale tutte in un posto solo, con autore e anno. Per ognuna scrivi due righe su cosa ti serve.', 'hai un elenco di fonti con due righe ciascuna', 'Parti dalla bibliografia di un articolo buono: ti porta ad altre fonti già scelte da qualcuno.'],
  'guida.r-tesi-3': ['Fai l\'indice', 'Scrivi i titoli dei capitoli e, sotto ognuno, tre o quattro punti. Non serve che sia perfetto. L\'indice è la mappa: lo cambierai mentre scrivi.', 'hai un indice con i punti di ogni capitolo', 'Usa lo schema classico: introduzione, cosa si sa già, cosa hai fatto tu, risultati, conclusioni.'],
  'guida.r-tesi-4': ['Scrivi la prima bozza', 'Scrivi un capitolo alla volta, senza correggere. Meglio una pagina brutta che una pagina vuota. Metti le citazioni subito, così non le perdi.', 'ogni capitolo ha un testo, anche brutto', 'Fai sessioni brevi: «focus 25» e scrivi solo un paragrafo.'],
  'guida.r-tesi-5': ['Rileggi e sistema', 'Rileggi tutto ad alta voce: le frasi lunghe si sentono. Controlla che ogni capitolo risponda alla domanda iniziale. Sistema citazioni e bibliografia.', 'hai riletto tutto una volta, dall\'inizio alla fine', 'Stampa o cambia carattere: sugli stessi fogli l\'occhio salta gli errori.'],
  'guida.r-tesi-6': ['Consegna', 'Esporta in PDF e controlla le pagine una per una. Segui le regole del formato richiesto. Manda il file e tieni una copia.', 'il file è consegnato e hai una copia', 'Leggi le regole di formato del dipartimento prima di esportare: margini, carattere, frontespizio.'],

  'guida.r-sito-1': ['Decidi cosa deve fare il sito', 'Scrivi chi lo guarderà e cosa deve trovare. Fai l\'elenco delle pagine: per esempio Home, Chi sono, Progetti, Contatti. Disegna su un foglio la pagina principale.', 'hai l\'elenco delle pagine e uno schizzo', 'Guarda tre siti simili che ti piacciono e annota cosa hanno in comune.'],
  'guida.r-sito-2': ['Prepara la cartella', 'Crea una cartella per il sito e aprila nell\'editor. Dentro crea index.html e style.css. Scrivi una pagina con solo un titolo e aprila nel browser.', 'il browser mostra il tuo titolo', 'Nel file index.html basta scrivere il tag h1 con il tuo nome: salva e ricarica la pagina.'],
  'guida.r-sito-3': ['Scrivi la struttura', 'Metti in HTML le parti della pagina: intestazione, sezioni, piè di pagina. Usa titoli e paragrafi veri, niente stile per ora. Aggiungi le altre pagine e i link fra loro.', 'tutte le pagine ci sono e i link funzionano', 'Una pagina alla volta: copia index.html, cambia il testo e collega con un tag a.'],
  'guida.r-sito-4': ['Dai lo stile', 'Nel CSS scegli un carattere, due colori e i margini. Fai in modo che si legga bene anche sul telefono. Controlla con gli strumenti del browser.', 'il sito si legge bene sul computer e sul telefono', 'Parti da poche regole: font-family, max-width per il testo, un po\' di padding.'],
  'guida.r-sito-5': ['Mettilo online', 'Scegli un servizio gratuito per siti statici, per esempio GitHub Pages o Netlify. Carica la cartella e apri l\'indirizzo che ti danno. Mandalo a un amico e chiedi cosa non capisce.', 'il sito si apre da un indirizzo pubblico', 'Con GitHub Pages: crea un repository, carica i file e attiva Pages nelle impostazioni.'],

  'guida.r-codice-1': ['Capisci il problema', 'Rileggi la consegna e scrivi a parole cosa entra e cosa esce dal programma. Prepara due o tre esempi con il risultato giusto. Così saprai quando funziona.', 'hai due o tre esempi di ingresso e uscita', 'Fai un esempio piccolissimo a mano, su un foglio, passo per passo.'],
  'guida.r-codice-2': ['Prepara l\'ambiente', 'Crea una cartella per il progetto e aprila nell\'editor. Controlla che {linguaggio} funzioni: scrivi un programma che stampa una riga e lancialo.', 'il programma di prova stampa la sua riga', 'Se il comando non si trova, il programma non è installato o non è nel PATH: cerca la guida ufficiale per il tuo sistema.'],
  'guida.r-codice-3': ['Scrivi la prima versione', 'Scrivi in {linguaggio} la versione più semplice che risolve il primo esempio. Niente casi speciali per ora. Lancia il programma spesso, dopo poche righe.', 'il primo esempio dà il risultato giusto', 'Dividi in funzioni piccole: una legge, una calcola, una stampa.'],
  'guida.r-codice-4': ['Prova tutti i casi', 'Prova gli altri esempi e i casi limite: vuoto, un solo elemento, numeri grandi. Quando qualcosa non va, leggi l\'errore e stampa i valori a metà. Correggi un errore alla volta.', 'tutti gli esempi danno il risultato giusto', 'Copia l\'errore e scrivi «spiegami l\'errore»: te lo spiego un passo alla volta.'],
  'guida.r-codice-5': ['Pulisci e consegna', 'Dai nomi chiari alle variabili e togli le stampe di prova. Aggiungi due righe che spiegano come si lancia. Rileggi la consegna e controlla di aver fatto tutto.', 'il codice è pulito e la consegna è rispettata', 'Spiega il codice a voce, riga per riga: dove ti blocchi, lì c\'è da sistemare.'],

  'guida.r-presentazione-1': ['Decidi il messaggio', 'Scrivi in una frase cosa deve ricordare chi ti ascolta. Guarda quanto tempo hai: più o meno una slide al minuto. Scegli tre punti, non di più.', 'hai la frase del messaggio e tre punti', 'Immagina di raccontarlo a un amico in un minuto: quello che dici è il messaggio.'],
  'guida.r-presentazione-2': ['Fai la scaletta', 'Scrivi un titolo per ogni slide, in ordine. Prima l\'apertura, poi i tre punti, poi la chiusura. Niente grafica per ora.', 'hai un elenco di titoli, uno per slide', 'Usa dei post-it o una lista: spostare le idee è più facile prima di aprire il programma.'],
  'guida.r-presentazione-3': ['Riempi le slide', 'Una idea per slide, poche parole, immagini grandi. Il testo lungo lo dici tu, non lo scrivi. Usa lo stesso stile in tutte.', 'ogni slide ha il suo contenuto', 'Se una slide ha più di sei righe, dividila in due.'],
  'guida.r-presentazione-4': ['Prova ad alta voce', 'Ripeti tutta la presentazione con il cronometro. Segna dove ti blocchi e dove vai lungo. Taglia quello che non serve al messaggio.', 'l\'hai ripetuta nel tempo giusto', 'Registrati con il telefono e riascoltati una volta.'],
  'guida.r-presentazione-5': ['Prepara il giorno', 'Esporta anche in PDF, nel caso il programma non ci sia. Porta il file su una chiavetta o nel cloud. Prepara una risposta a due domande probabili.', 'hai il PDF di riserva e le due risposte', 'Arriva qualche minuto prima e prova il proiettore.'],

  'guida.r-video-1': ['Scrivi cosa racconti', 'Decidi in una frase di cosa parla il video e quanto dura. Scrivi la scaletta delle scene. Se parli, scrivi il testo e leggilo ad alta voce.', 'hai la scaletta e il testo', 'Un video breve funziona meglio: parti da uno di un minuto.'],
  'guida.r-video-2': ['Registra', 'Registra le scene della scaletta, ognuna più volte. Cura la luce e soprattutto l\'audio: un microfono vicino conta più della telecamera. Tieni il telefono fermo e in orizzontale, se non è per i social.', 'hai tutte le scene registrate', 'Registra in un posto silenzioso, con una finestra davanti a te e non dietro.'],
  'guida.r-video-3': ['Monta', 'Importa i file nel programma di montaggio. Metti le scene in ordine e taglia le pause e gli errori. Guarda tutto una volta senza fermarti.', 'il video si guarda dall\'inizio alla fine', 'Taglia più di quanto pensi: un secondo di troppo si sente.'],
  'guida.r-video-4': ['Rifinisci', 'Sistema il volume, aggiungi i titoli e, se serve, la musica bassa. Usa musica libera da diritti. Aggiungi i sottotitoli se qualcuno lo guarderà senza audio.', 'audio, titoli e sottotitoli sono a posto', 'Ascolta con le cuffie: si sentono i salti di volume.'],
  'guida.r-video-5': ['Esporta e consegna', 'Esporta in MP4, 1080p, che va bene quasi ovunque. Guarda il file esportato fino alla fine. Caricalo o consegnalo e tieni il progetto.', 'il file è consegnato e l\'hai guardato tutto', 'Se il file è troppo grande, esporta a bitrate più basso.'],

  'guida.r-dati-1': ['Scrivi la domanda', 'Scrivi in una riga cosa vuoi scoprire dai dati. Decidi quale grafico risponderebbe: un andamento, un confronto, una distribuzione. Così sai cosa cercare.', 'hai la domanda e il tipo di grafico', 'Completa la frase: quando cambia una cosa, cambia anche l\'altra?'],
  'guida.r-dati-2': ['Prepara i dati', 'Apri i dati in un foglio di calcolo. Una riga per osservazione, una colonna per variabile, con un nome chiaro. Togli righe vuote e doppioni.', 'la tabella è pulita, con le intestazioni', 'Lavora su una copia: tieni sempre il file originale.'],
  'guida.r-dati-3': ['Guarda i numeri', 'Calcola per ogni colonna media, minimo e massimo. Cerca i valori strani: errori di battitura o casi veri? Annota cosa noti.', 'hai i numeri di riepilogo e le note', 'Ordina la colonna: i valori strani finiscono in cima o in fondo.'],
  'guida.r-dati-4': ['Fai il grafico', 'Crea il grafico che risponde alla domanda. Metti il titolo, il nome degli assi e le unità. Togli tutto quello che non serve a leggerlo.', 'il grafico si capisce senza spiegazioni', 'Linee per l\'andamento nel tempo, barre per confrontare, istogramma per la distribuzione.'],
  'guida.r-dati-5': ['Scrivi cosa dice', 'Sotto il grafico scrivi due o tre frasi: cosa si vede e cosa vuol dire. Di\' anche cosa i dati non possono dire. Salva il grafico come immagine.', 'hai il grafico salvato e le frasi', 'Separa quello che vedi dalla tua spiegazione: prima i fatti, poi l\'idea.'],

  'guida.r-esame-1': ['Metti in ordine il programma', 'Prendi il programma del corso e incollalo in Lode con «programma». Avrai la mappa degli argomenti. Segna quelli che sai già.', 'il programma è in Lode', 'Se non trovi il programma, guarda la pagina del corso o chiedi ai compagni.'],
  'guida.r-esame-2': ['Fai un piano', 'Conta i giorni che mancano e dividi gli argomenti. Lascia gli ultimi giorni per ripassare. Metti il piano nel calendario.', 'ogni argomento ha il suo giorno', 'Scrivi «piano della settimana» e Lode ti mostra le ore libere vere.'],
  'guida.r-esame-3': ['Studia un argomento al giorno', 'Fai sessioni brevi con il timer, per esempio «focus 50». Alla fine di ogni argomento fai carte con le cose da ricordare. Ripassale ogni giorno con «ripassa».', 'hai studiato tutti gli argomenti almeno una volta', 'Spiega l\'argomento ad alta voce come se fossi il prof: dove ti blocchi, rileggi.'],
  'guida.r-esame-4': ['Mettiti alla prova', 'Fai il «quiz» o fatti fare domande con «interrogami». Segna le domande sbagliate e ristudia quelle. Ripeti finché le sai.', 'rispondi bene alla maggior parte delle domande', 'Comincia dagli argomenti che sai meno: è lì che si guadagna di più.'],
  'guida.r-esame-5': ['Fai una prova vera', 'Due o tre giorni prima fai la «prova generale» con un compito vecchio e il tempo vero. Correggi e ripassa gli errori. Il giorno prima dormi.', 'hai fatto un compito intero nel tempo', 'Se non hai compiti vecchi, chiedili ai compagni o sul gruppo del corso.'],

  'guida.r-generico-1': ['Scrivi il risultato', 'Scrivi in una frase come sarà la cosa finita. Più è concreta, meglio è. Segna anche per quando ti serve.', 'hai la frase del risultato e la data', 'Immagina di mostrarla a qualcuno: cosa vede?'],
  'guida.r-generico-2': ['Cerca cosa ti serve', 'Fai l\'elenco di cosa ti serve: programmi, materiali, persone da sentire. Guarda come lo ha fatto qualcun altro, per esempio in un video o in una guida.', 'hai l\'elenco di cosa ti serve', 'Cerca il nome della cosa più «tutorial» o «guida per principianti».'],
  'guida.r-generico-3': ['Fai il primo passo piccolo', 'Scegli la cosa più piccola che puoi fare adesso, in 20 minuti. Falla subito, anche se non è perfetta. Il resto viene più facile.', 'hai fatto il primo pezzo', 'Se 20 minuti sono tanti, fai 5 minuti: basta partire.'],
  'guida.r-generico-4': ['Vai avanti e controlla', 'Dividi il resto in pezzi da una sessione e falli uno alla volta. Dopo ogni pezzo confronta con il risultato che hai scritto. Chiedi un parere prima della fine.', 'il risultato è come l\'avevi scritto', 'Se ti blocchi, torna al pezzo prima e rendilo più piccolo.'],
};
