// Le domande di «Cosa stampa?» (js/codice/modelli.js), in italiano: la lingua di partenza.
// Chiavi: modelli.<modello>.cosa / .concetto / .frase-N (le frasi dei mutanti, nell'ordine), modelli.<modello>.<lingua>.… per
// quello che cambia in Python e Java; modelli.concetti.* e modelli.errori.* sono i nomi degli argomenti e degli errori.
export default {
  'modelli.hai-scelto': 'Hai scelto `{s}`',
  'modelli.niente': '(niente)',
  'modelli.concetti.for': 'Ciclo for',
  'modelli.concetti.while': 'Ciclo while',
  'modelli.concetti.do-while': 'Ciclo do-while',
  'modelli.concetti.ritroso': 'Conteggio a ritroso',
  'modelli.concetti.array': 'Array',
  'modelli.concetti.divisione-intera': 'Divisione intera',
  'modelli.concetti.resto': 'Resto con i negativi',
  'modelli.concetti.cast': 'Cast a double',
  'modelli.concetti.incremento': 'i++ e ++i',
  'modelli.concetti.assegnamento': 'Assegnamenti composti (+=)',
  'modelli.concetti.switch': 'switch e break',
  'modelli.concetti.cortocircuito': '&& e || in cortocircuito',
  'modelli.concetti.else-pendente': 'else pendente',
  'modelli.concetti.puntatori': 'Passaggio per indirizzo',
  'modelli.concetti.parametri': 'Passaggio per valore',
  'modelli.concetti.visibilita': 'Variabili nei blocchi',
  'modelli.concetti.char': 'char e codici ASCII',
  'modelli.concetti.ricorsione': 'Ricorsione',
  'modelli.concetti.annidati': 'Cicli annidati',
  'modelli.concetti.break-continue': 'break e continue',
  'modelli.concetti.ternario': 'Operatore ternario',
  'modelli.errori.fuori-di-uno': 'fuori di uno',
  'modelli.errori.divisione-intera': 'divisione intera',
  'modelli.errori.post-vs-pre': 'i++ e ++i',
  'modelli.errori.break-dimenticato': 'break dimenticato',
  'modelli.errori.copia-del-parametro': 'copia del parametro',
  'modelli.errori.cortocircuito': 'cortocircuito',
  'modelli.errori.resto-col-segno': 'resto col segno',
  'modelli.errori.piu-uguale': '+= e =',
  'modelli.errori.maggiore-o-uguale': '> e >=',
  'modelli.errori.indice-valore': 'indice e valore',
  'modelli.errori.sovrascrittura': 'primo e ultimo',
  'modelli.errori.else-pendente': 'else pendente',
  'modelli.errori.variabile-nascosta': 'variabile nascosta',
  'modelli.errori.carattere-codice': 'carattere e codice',
  'modelli.errori.caso-base': 'caso base',
  'modelli.errori.passo-del-ciclo': 'quando scatta il passo del ciclo',
  'modelli.errori.ricorsione': 'ricorsione',
  'modelli.errori.cicli-annidati': 'cicli annidati',
  'modelli.errori.break-continue': 'break e continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'ternario al contrario',
  'modelli.errori.scambi-in-fila': 'scambi in fila',
  'modelli.for-minore.cosa': 'questo for',
  'modelli.for-minore.concetto': 'Con `i < n` l\'ultimo giro ha i = n - 1: il valore n non viene mai stampato.',
  'modelli.for-minore.frase': `{hai}: è quello che stamperebbe con \`i <= {b}\`. Qui il ciclo si ferma prima.`,
  'modelli.for-minore.frase-2': `{hai}: è come se \`i++\` scattasse prima del primo giro. L'incremento arriva alla fine di ogni giro: il primo giro ha i = {a}.`,
  'modelli.for-minore.frase-3': `{hai}: ti sei fermato un giro prima. Con \`i < {b}\` l'ultimo giro ha i = {b2}.`,
  'modelli.for-passo.cosa': 'questo for',
  'modelli.for-passo.concetto': 'Con `<=` il ciclo fa anche il giro in cui i è uguale al limite.',
  'modelli.for-passo.frase': `{hai}: è quello che stamperebbe con \`i < {b}\`. Con \`<=\` anche {b} viene stampato.`,
  'modelli.for-passo.frase-2': `{hai}: \`i += {s}\` non scatta prima del primo giro. Il primo giro ha i = {a}.`,
  'modelli.for-indietro.cosa': 'questo conto alla rovescia',
  'modelli.for-indietro.concetto': 'Il ciclo gira finché la condizione è vera: con `i > L` il valore L non viene stampato.',
  'modelli.for-indietro.frase': `{hai}: è quello che stamperebbe con \`i >= {l}\`. Con \`i > {l}\` l'ultimo giro ha i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai}: \`i--\` arriva alla fine del giro, non prima. Il primo giro stampa {n}.`,
  'modelli.for-indietro.frase-3': `{hai}: ti sei fermato un giro prima. Anche i = {l} rispetta \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'questo while',
  'modelli.while-somma.concetto': 'Il while esce quando la condizione diventa falsa: dopo `while (i < n)` la variabile i vale n.',
  'modelli.while-somma.frase': `{hai}: è quello che stamperebbe con \`i <= {n}\`. Qui il ciclo fa un giro in meno.`,
  'modelli.while-somma.frase-2': `{hai}: è come se \`i++\` venisse prima di \`s += i\`. Qui s somma i e solo dopo i cresce.`,
  'modelli.while-somma.frase-3': `{hai}: dopo il ciclo i non vale {n}. Il while esce proprio quando i diventa {n2}.`,
  'modelli.while-dimezza.cosa': 'questo while',
  'modelli.while-dimezza.concetto': 'Tra due int `/` tronca: 7 / 2 fa 3, e dimezzando si arriva a 1 senza virgole.',
  'modelli.while-dimezza.frase': `{hai}: è quello che succederebbe se n fosse un double. n è un int: \`n /= 2\` butta via la parte dopo la virgola.`,
  'modelli.while-dimezza.frase-2': `{hai}: è quello che stamperebbe con \`n >= 1\`. Il ciclo si ferma appena n arriva a 1.`,
  'modelli.while-post.cosa': 'questo while con i++',
  'modelli.while-post.concetto': '`i++ < n` confronta il valore vecchio e poi incrementa: dentro il ciclo i è già cresciuto.',
  'modelli.while-post.frase': `{hai}: è quello che stamperebbe con \`++i\`. Con \`i++\` il confronto usa il valore di prima.`,
  'modelli.while-post.frase-2': `{hai}: quando printf parte, i è già stato incrementato dal confronto.`,
  'modelli.while-post.frase-3': `{hai}: anche l'ultimo confronto, quello falso, incrementa i. Alla fine i vale {n}.`,
  'modelli.array-somma.cosa': 'questa somma',
  'modelli.array-somma.concetto': 'Gli indici di un array di n elementi vanno da 0 a n - 1.',
  'modelli.array-somma.frase': `{hai}: hai saltato \`v[0]\`. Il primo elemento ha indice 0.`,
  'modelli.array-somma.frase-2': `{hai}: hai lasciato fuori l'ultimo. Con \`i < {k}\` l'ultimo giro legge \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai}: è l'ultimo elemento, come se ci fosse \`s = v[i]\`. \`+=\` aggiunge, non sostituisce.`,
  'modelli.array-massimo.cosa': 'questo massimo',
  'modelli.array-massimo.concetto': 'p è un indice: conta da 0. Con `>` resta la prima posizione del massimo.',
  'modelli.array-massimo.frase': `{hai}: hai contato le posizioni da 1. In {linguaggio} il primo elemento ha indice 0.`,
  'modelli.array-massimo.frase-2': `{hai}: è quello che farebbe \`>=\`. Con \`>\` un massimo uguale non sposta p: resta il primo.`,
  'modelli.array-massimo.frase-3': `{hai}: hai lasciato fuori l'ultimo elemento. Anche lui viene confrontato.`,
  'modelli.array-ultimo.cosa': 'questa ricerca',
  'modelli.array-ultimo.concetto': 'Il ciclo non si ferma quando trova x: p viene sovrascritto e resta l\'ultima posizione.',
  'modelli.array-ultimo.frase': `{hai}: è la prima posizione. Il ciclo non si ferma: ogni volta che trova x riscrive p.`,
  'modelli.array-ultimo.frase-2': `{hai}: hai contato le posizioni da 1. In {linguaggio} il primo elemento ha indice 0.`,
  'modelli.array-ultimo.frase-3': `{hai}: è il valore cercato, non la sua posizione. p è un indice.`,
  'modelli.media-array.cosa': 'questa media',
  'modelli.media-array.concetto': '`s / n` tra int tronca. `(double)s / n` converte prima e divide con la virgola.',
  'modelli.media-array.frase': `{hai}: \`s / {k}\` è una divisione tra due int: la parte dopo la virgola si perde.`,
  'modelli.media-array.frase-2': `{hai}: il cast \`(double)s\` avviene prima della divisione, quindi la divisione tiene la virgola.`,
  'modelli.media-array.frase-3': `{hai}: la divisione tra int non arrotonda, tronca.`,
  'modelli.divisione-double.cosa': 'questa divisione',
  'modelli.divisione-double.concetto': 'Il tipo del risultato non conta: `a / b` tra int tronca anche se finisce in un double.',
  'modelli.divisione-double.frase': `{hai}: \`a / b\` si calcola tra int, prima di finire in m. Il double riceve un numero già troncato.`,
  'modelli.divisione-double.frase-2': `{hai}: la divisione tra int non arrotonda, tronca verso lo zero.`,
  'modelli.cast-prima-dopo.cosa': 'questi due cast',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` divide tra int e poi converte. `(double)s / n` converte e poi divide.',
  'modelli.cast-prima-dopo.frase': `{hai}: in \`(double)(s / n)\` le parentesi fanno dividere prima, tra int. Il cast arriva dopo.`,
  'modelli.cast-prima-dopo.frase-2': `{hai}: in \`(double)s / n\` il cast vale solo per s, e la divisione tiene la virgola.`,
  'modelli.cast-prima-dopo.frase-3': `{hai}: li hai scambiati. Le parentesi decidono se il cast arriva prima o dopo la divisione.`,
  'modelli.diviso-due.cosa': 'questa divisione per 2',
  'modelli.diviso-due.concetto': 'Basta un double nel conto: `a / 2.0` tiene la virgola, `a / 2` no.',
  'modelli.diviso-due.frase': `{hai}: \`a / 2\` è tra due int: tronca e dà un int, che %d stampa senza virgola.`,
  'modelli.diviso-due.frase-2': `{hai}: \`2.0\` è un double, quindi \`a / 2.0\` tiene la virgola.`,
  'modelli.diviso-due.frase-3': `{hai}: \`a / 2\` non arrotonda: tronca verso lo zero.`,
  'modelli.resto-negativi.cosa': 'questo resto',
  'modelli.resto-negativi.concetto': `In {linguaggio} la divisione tronca verso lo zero e il resto ha il segno del dividendo: -7 % 3 fa -1.`,
  'modelli.resto-negativi.frase': `{hai}: così fa Python, che arrotonda verso il basso. In {linguaggio} si tronca verso lo zero.`,
  'modelli.resto-negativi.frase-2': `{hai}: in {linguaggio} il resto non è sempre positivo. Ha il segno del dividendo, cioè di a.`,
  'modelli.resto-negativi.frase-3': `{hai}: la divisione tra int tronca verso lo zero, non verso il basso.`,
  'modelli.post-pre.cosa': 'questi incrementi',
  'modelli.post-pre.concetto': '`x = i--` usa il valore di prima e poi decrementa; `y = --i` decrementa e poi usa il valore nuovo.',
  'modelli.post-pre.concetto-2': '`x = i++` usa il valore di prima e poi incrementa; `y = ++i` incrementa e poi usa il valore nuovo.',
  'modelli.post-pre.frase': `{hai}: con \`x = i{op}\` x prende il valore di prima, poi i cambia.`,
  'modelli.post-pre.frase-2': `{hai}: con \`y = {op}i\` prima cambia i, poi y prende il valore nuovo.`,
  'modelli.post-pre.frase-3': `{hai}: li hai scambiati. Il segno dopo (\`i{op}\`) usa il valore di prima, quello prima (\`{op}i\`) il valore nuovo.`,
  'modelli.piu-uguale.cosa': 'questo +=',
  'modelli.piu-uguale.concetto': '`s += x` vuol dire `s = s + x`: aggiunge al valore che c\'era.',
  'modelli.piu-uguale.frase': `{hai}: è solo l'ultimo giro, come se ci fosse \`=\`. \`+=\` aggiunge ogni volta.`,
  'modelli.piu-uguale.frase-2': `{hai}: con \`<=\` anche i = {n} fa il suo giro.`,
  'modelli.piu-uguale.frase-3': `{hai}: hai dimenticato il valore iniziale. s parte da {a}.`,
  'modelli.switch.cosa': 'questo switch',
  'modelli.switch.concetto': 'Senza break l\'esecuzione cade nel case sotto e continua fino al primo break o alla fine.',
  'modelli.switch.frase': `{hai}: è come se ogni case avesse il suo break. Senza break si continua nel case sotto.`,
  'modelli.switch.frase-2': `{hai}: hai saltato il break. Lì lo switch si ferma.`,
  'modelli.switch.frase-3': `{hai}: default non parte sempre. Parte se nessun case corrisponde, o se ci arrivi cadendo da un case senza break.`,
  'modelli.cortocircuito.cosa': 'questo if con || e &&',
  'modelli.cortocircuito.concetto': 'Se il primo pezzo basta a decidere (vero con ||, falso con &&), il secondo non viene eseguito.',
  'modelli.cortocircuito.frase': `{hai}: \`++n\` non viene eseguito. Con \`{op}\` il primo pezzo basta già a decidere, e n resta 0.`,
  'modelli.cortocircuito.frase-3': '|| vuole vero almeno un pezzo',
  'modelli.cortocircuito.frase-4': '&& vuole veri tutti e due i pezzi',
  'modelli.cortocircuito.frase-2': `{hai}: hai letto \`{op}\`. {op2}.`,
  'modelli.else-pendente.cosa': 'questo else',
  'modelli.else-pendente.concetto': 'L\'else va con l\'if più vicino che non ha già un else, qualunque sia il rientro.',
  'modelli.else-pendente.frase': `{hai}: hai seguito il rientro. Ma l'else va con l'if più vicino, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai}: con \`i < {n}\` l'ultimo giro ha i = {n2}.`,
  'modelli.swap-valore.cosa': 'questo scambio',
  'modelli.swap-valore.concetto': 'Una funzione riceve copie dei valori: scambiare a e b non tocca x e y.',
  'modelli.swap-valore.frase': `{hai}: a e b sono copie di x e y. Lo scambio resta dentro la funzione.`,
  'modelli.swap-valore.frase-2': `{hai}: dentro la funzione lo scambio avviene davvero. Sono le copie a scambiarsi, non x e y.`,
  'modelli.swap-indirizzo.cosa': 'questi scambi con i puntatori',
  'modelli.swap-indirizzo.concetto': 'Con `&x` la funzione riceve l\'indirizzo: `*a = …` cambia proprio x. Gli scambi avvengono uno dopo l\'altro.',
  'modelli.swap-indirizzo.frase': `{hai}: qui non sono copie. \`&x\` passa l'indirizzo, e \`*a\` scrive proprio in x.`,
  'modelli.swap-indirizzo.frase-2': `{hai}: gli scambi vanno in ordine. Prima x con y, poi la y nuova con z.`,
  'modelli.swap-indirizzo.frase-3': `{hai}: il secondo scambio vede la y già cambiata dal primo.`,
  'modelli.valore-e-indirizzo.cosa': 'questa funzione',
  'modelli.valore-e-indirizzo.concetto': 'a è una copia di x; b è l\'indirizzo di y: solo `*b = …` cambia la variabile di main.',
  'modelli.valore-e-indirizzo.frase': `{hai}: a è una copia di x. Cambiare a non cambia x.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai}: b non è una copia, è l'indirizzo di y. \`*b = …\` cambia y.`,
  'modelli.array-in-funzione.cosa': 'questo array passato a una funzione',
  'modelli.array-in-funzione.concetto': 'Un array passa per indirizzo: la funzione cambia proprio a. Un int invece passa come copia.',
  'modelli.array-in-funzione.frase': `{hai}: un array non viene copiato. La funzione lavora sugli stessi elementi di a.`,
  'modelli.array-in-funzione.frase-2': `{hai}: n invece è una copia. Il \`n--\` della funzione non tocca la n di main.`,
  'modelli.blocco-ombra.cosa': 'queste due x',
  'modelli.blocco-ombra.concetto': 'La x dichiarata nel blocco è un\'altra variabile: nasconde quella di fuori e sparisce alla }.',
  'modelli.blocco-ombra.frase': `{hai}: \`int x = {b}\` dentro le graffe crea una x nuova. Fuori la x vale ancora {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai}: dentro il blocco la x più vicina è quella interna. y la usa.`,
  'modelli.char-ascii.cosa': 'questi char',
  'modelli.char-ascii.concetto': 'Un char è un numero: \'a\' vale 97. %c stampa la lettera, %d il codice. Maiuscola = minuscola - 32.',
  'modelli.char-ascii.frase': `{hai}: %d non dà la posizione nell'alfabeto. Dà il codice ASCII: 'a' vale 97.`,
  'modelli.char-ascii.frase-2': `{hai}: %d stampa il numero del carattere, non la lettera.`,
  'modelli.char-ascii.frase-3': `{hai}: d è un char e %c lo stampa come lettera, la maiuscola.`,
  'modelli.fattoriale.cosa': 'questa ricorsione',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), e il caso base ferma la discesa a 1.',
  'modelli.fattoriale.frase': `{hai}: è fatt({n}). Hai fatto un passo in meno: si moltiplica da {n2} fino a 1.`,
  'modelli.fattoriale.frase-2': `{hai}: è fatt({n}). Hai fatto un passo in più: si parte da {n2}.`,
  'modelli.fattoriale.frase-3': `{hai}: ti sei fermato alla prima chiamata. fatt(n - 1) continua a chiamarsi fino al caso base.`,
  'modelli.somma-cifre.cosa': 'questa ricorsione',
  'modelli.somma-cifre.concetto': 'n % 10 è l\'ultima cifra, n / 10 toglie l\'ultima cifra. Il caso base restituisce la cifra che resta.',
  'modelli.somma-cifre.frase': `{hai}: hai perso la prima cifra. Il caso base restituisce n, non 0.`,
  'modelli.somma-cifre.frase-2': `{hai}: è il numero delle cifre. Qui ogni chiamata aggiunge \`n % 10\`, la cifra, non 1.`,
  'modelli.somma-cifre.frase-3': `{hai}: è solo l'ultima cifra. Il valore di ritorno si somma a quello della chiamata dopo.`,
  'modelli.ricorsione-ordine.cosa': 'questa ricorsione',
  'modelli.ricorsione-ordine.concetto': 'printf viene dopo la chiamata: si stampa al ritorno, quindi dal più piccolo al più grande.',
  'modelli.ricorsione-ordine.frase': `{hai}: sarebbe così con printf prima della chiamata. Qui si stampa al ritorno.`,
  'modelli.ricorsione-ordine.frase-2': `{hai}: con n = 0 la funzione esce subito, senza stampare.`,
  'modelli.annidati-conta.cosa': 'questi cicli annidati',
  'modelli.annidati-conta.concetto': 'Il ciclo interno riparte a ogni giro di quello esterno: qui gira i volte, cioè 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai}: è quello che darebbe \`j <= i\`. Con \`j < i\` il primo giro (i = 0) non conta niente.`,
  'modelli.annidati-conta.frase-2': `{hai}: il ciclo interno non gira sempre {n} volte: gira i volte.`,
  'modelli.annidati-stelle.cosa': 'queste stelle',
  'modelli.annidati-stelle.concetto': 'Per ogni riga i il ciclo interno stampa i simboli, poi `\\n` va a capo.',
  'modelli.annidati-stelle.frase': `{hai}: un simbolo in più per riga. j parte da 0 e con \`j < i\` fa i giri.`,
  'modelli.annidati-stelle.frase-2': `{hai}: il ciclo interno dipende da i: non stampa sempre {n} simboli.`,
  'modelli.annidati-stelle.frase-3': `{hai}: manca l'ultima riga. Con \`i <= {n}\` anche la riga {n} viene stampata.`,
  'modelli.break-continue.cosa': 'questo break e questo continue',
  'modelli.break-continue.concetto': `\`continue\` salta al giro dopo; \`break\` esce dal ciclo, e il {l} di quel giro non arriva.`,
  'modelli.break-continue.frase': `{hai}: \`continue\` non esce dal ciclo: salta solo il giro con i = {a}.`,
  'modelli.break-continue.frase-2': `{hai}: \`break\` non salta un giro: esce dal ciclo quando i vale {b}.`,
  'modelli.break-continue.frase-3': `{hai}: il break arriva prima del {l}: {b} non viene stampato.`,
  'modelli.do-while.cosa': 'questo do-while',
  'modelli.do-while.concetto': 'Il do-while controlla la condizione alla fine di ogni giro: il corpo gira sempre almeno una volta.',
  'modelli.do-while.frase': `{hai}: è quello che farebbe un while. Il do-while esegue il corpo prima di controllare.`,
  'modelli.do-while.frase-3': 'Il do-while non aggiunge un giro: controlla la condizione alla fine di ogni giro.',
  'modelli.do-while.frase-4': 'Dopo il primo giro la condizione è già falsa.',
  'modelli.do-while.frase-2': `{hai}: un giro di troppo. {vero}`,
  'modelli.do-while.frase-5': `{hai}: è quello che darebbe \`i {op}= {b}\`. Con \`i {op} {b}\`, quando i arriva a {b} il ciclo si ferma.`,
  'modelli.do-while.frase-6': `{hai}: hai stampato i com'era prima dell'ultimo giro. Anche l'ultimo giro cambia i: il controllo arriva dopo.`,
  'modelli.ternario.cosa': 'questi ternari',
  'modelli.ternario.concetto': '`c ? x : y` vale x se c è vera, y se è falsa.',
  'modelli.ternario.frase-m-vera': `{hai}: per m hai preso il ramo sbagliato. \`a > b\` è vera, quindi vale quello dopo \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai}: per m hai preso il ramo sbagliato. \`a > b\` è falsa, quindi vale quello dopo \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai}: per d hai preso il ramo sbagliato. \`a < b\` è vera, quindi vale quello dopo \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai}: per d hai preso il ramo sbagliato. \`a < b\` è falsa, quindi vale quello dopo \`:\`.`,
  'modelli.ternario.frase-7': `{hai}: hai letto i due ternari al contrario. Vero → il valore dopo \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` si ferma prima di {b2}: l'ultimo giro ha i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai}: è quello che stamperebbe \`{b}\`. range si ferma prima del secondo numero.`,
  'modelli.for-minore.python.frase-2': `{hai}: hai saltato il primo giro. range parte proprio da {a}.`,
  'modelli.for-minore.python.frase-3': `{hai}: ti sei fermato un giro prima. \`{b}\` arriva fino a {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` va di {s2} in {s2} e si ferma prima di {b}: anche {b2} viene stampato.`,
  'modelli.for-passo.python.frase': `{hai}: è quello che stamperebbe \`{s}\`. Qui il secondo numero è {b}, quindi anche {b2} viene stampato.`,
  'modelli.for-passo.python.frase-2': `{hai}: range parte da {a}, non da {s}. Il passo si aggiunge dopo il primo giro.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` conta all'indietro e si ferma prima di {l}: {l} non viene stampato.`,
  'modelli.for-indietro.python.frase': `{hai}: hai stampato anche {l}. range si ferma prima: l'ultimo giro ha i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai}: range parte proprio da {n}: il primo giro stampa {n}.`,
  'modelli.for-indietro.python.frase-3': `{hai}: ti sei fermato un giro prima. Anche {l} viene stampato.`,
  'modelli.while-somma.python.concetto': 'Il while esce quando la condizione diventa falsa: dopo `while i < n` la variabile i vale n.',
  'modelli.while-somma.python.frase': `{hai}: è come se \`i += 1\` venisse prima di \`s += i\`. Qui s somma i e solo dopo i cresce.`,
  'modelli.while-dimezza.python.concetto': '`//` è la divisione intera: 7 // 2 fa 3, e dimezzando si arriva a 1 senza virgole.',
  'modelli.while-dimezza.python.frase': `{hai}: hai tenuto la virgola, come farebbe \`n /= 2\`. \`n //= 2\` è la divisione intera: butta via la parte dopo la virgola.`,
  'modelli.array-somma.python.frase': `{hai}: hai lasciato fuori l'ultimo. \`range({k})\` arriva fino a {k2}: l'ultimo giro legge \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` è la divisione intera; `/` in Python tiene sempre la virgola, anche tra due int.',
  'modelli.media-array.python.frase': `{hai}: \`s // {k}\` è la divisione intera: la parte dopo la virgola si perde.`,
  'modelli.media-array.python.frase-2': `{hai}: in Python \`/\` tiene la virgola, non tronca come \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai}: \`//\` non arrotonda: va verso il basso.`,
  'modelli.media-array.java.frase': `{hai}: \`s / {k}\` è tra due int: in Java (come in C, non come in Python) la divisione resta intera e la parte dopo la virgola si perde.`,
  'modelli.divisione-double.java.frase': `{hai}: \`a / b\` si calcola tra int, prima di finire in m. In Java, come in C, la divisione tra due int tronca: il double riceve un numero già troncato.`,
  'modelli.diviso-due.python.concetto': 'In Python `//` è la divisione intera e `/` tiene sempre la virgola, anche tra due int.',
  'modelli.diviso-due.python.frase': `{hai}: \`a // 2\` è la divisione intera: dà un int, senza virgola.`,
  'modelli.diviso-due.python.frase-2': `{hai}: in Python \`/\` non tronca come in C o in Java: anche \`a / 2\` tiene la virgola.`,
  'modelli.diviso-due.python.frase-3': `{hai}: \`a // 2\` non arrotonda: va verso il basso.`,
  'modelli.resto-negativi.python.concetto': 'In Python `//` va verso il basso e il resto ha il segno del divisore: -7 // 3 fa -3 e -7 % 3 fa 2.',
  'modelli.resto-negativi.python.frase': `{hai}: così fanno il C e Java, che troncano verso lo zero. In Python \`//\` va verso il basso.`,
  'modelli.resto-negativi.python.frase-2': `{hai}: in Python il resto ha il segno del divisore, cioè di b, non del dividendo.`,
  'modelli.resto-negativi.python.frase-3': `{hai}: \`//\` arrotonda verso il basso, non verso lo zero.`,
  'modelli.piu-uguale.python.frase': `{hai}: \`range(1, {n})\` arriva fino a {n2}: anche i = {n2} fa il suo giro.`,
  'modelli.swap-valore.python.concetto': 'La funzione riceve i valori: riassegnare a e b dentro la funzione non tocca x e y.',
  'modelli.swap-valore.python.frase': `{hai}: a e b sono nomi della funzione. Riassegnarli non cambia x e y.`,
  'modelli.swap-valore.python.frase-2': `{hai}: dentro la funzione lo scambio avviene davvero. Si scambiano a e b, non x e y.`,
  'modelli.array-in-funzione.python.concetto': 'La lista passa alla funzione così com\'è: `v[n] *= …` cambia proprio a. n invece è un nome della funzione: `n -= 1` non tocca la n di fuori.',
  'modelli.array-in-funzione.python.frase': `{hai}: una lista non viene copiata. La funzione lavora sugli stessi elementi di a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai}: n invece no. Il \`n -= 1\` della funzione non tocca la n di fuori.`,
  'modelli.array-in-funzione.java.concetto': 'Un array passa come riferimento: la funzione cambia proprio a. Un int invece passa come copia.',
  'modelli.somma-cifre.python.concetto': '`n % 10` è l\'ultima cifra, `n // 10` toglie l\'ultima cifra. Il caso base restituisce la cifra che resta.',
  'modelli.ricorsione-ordine.python.concetto': 'print viene dopo la chiamata: si stampa al ritorno, quindi dal più piccolo al più grande.',
  'modelli.ricorsione-ordine.python.frase': `{hai}: sarebbe così con print prima della chiamata. Qui si stampa al ritorno.`,
  'modelli.annidati-conta.python.concetto': 'Il ciclo interno riparte a ogni giro di quello esterno: `range(i)` fa i giri, cioè 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai}: è quello che darebbe \`range(i + 1)\`. Con i = 0, \`range(i)\` non fa nessun giro.`,
  'modelli.annidati-stelle.python.concetto': 'Per ogni riga i il ciclo interno stampa i simboli, poi `print()` va a capo.',
  'modelli.annidati-stelle.python.frase': `{hai}: un simbolo in più per riga. \`range(i)\` fa i giri, non i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai}: manca l'ultima riga. \`range(1, {n})\` arriva fino a {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'Per ogni riga i il ciclo interno stampa i simboli, poi `println()` va a capo.',
};
