// Il piano per chi lavora (js/ore.js): i tempi «circa», le righe della settimana, quello che non ci sta e le scelte.
export default {
  'ore.circa-min': 'circa {m} min',
  'ore.circa-ore': { one: 'circa {n} ora', other: 'circa {n} ore' },
  'ore.circa-h': 'circa {h} h',
  'ore.circa-h-min': 'circa {h} h {m}',
  'ore.opzione-cuscinetto': 'Uso anche i giorni cuscinetto',
  'ore.opzione-un-ripasso': 'Un ripasso solo per gli argomenti nuovi, non due',
  'ore.opzione-tetto': 'Nei giorni di lavoro studio 3 ore, non 2',
  'ore.giorni-brevi': ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
  'ore.libere': '{circa} libere',
  'ore.niente-ore-libere': 'niente ore libere',
  'ore.giorno': '{g} {n}',
  'ore.lavoro': 'lavoro {turni}',
  'ore.voce-tema': 'esercizio d\'esame ({circa})',
  'ore.argomento': 'argomento',
  'ore.voce-generale': 'ripasso generale ({circa})',
  'ore.esame': 'Esame',
  'ore.voce-cuscinetto': '{nome}: giorno cuscinetto, per recuperare',
  'ore.oggi-niente': 'Oggi non hai ore libere per studiare{lav}.',
  'ore.oggi-hai': 'Oggi hai {liberi}{lav}: {lista}.',
  'ore.oggi-hai-vuoto': 'Oggi hai {liberi}{lav}. Nel piano oggi non c\'è niente.',
  'ore.per-esame': '{circa} per {nome}',
  'ore.un-esame': 'un esame',
  'ore.mancano': 'Fino all\'appello di {nome} ti mancano {circa}.',
  'ore.questo-esame': 'questo esame',
  'ore.recuperi': '{testo} · recuperi {circa}',
  'ore.ripiego': 'Con le ore che hai non ci sta tutto. Puoi scrivermi giorni di studio in più («studio dalle 9 alle 21») o pensare all\'appello dopo: decidi tu.',
  'ore.mancano-ancora': 'Ti mancano ancora {circa}.',
  'ore.ora-ci-sta': 'Ora ci sta.',
};
