// Testi della pagina sotto la barra (italiano, lingua di partenza): saluto, numeri della carriera, carte degli esami,
// libretto, mazzi, finestre dell'esame e delle impostazioni, backup.
export default {
  // saluto e riga sotto
  'pagina.saluto-notte': 'Ancora sveglio',
  'pagina.saluto-mattina': 'Buongiorno',
  'pagina.saluto-pomeriggio': 'Buon pomeriggio',
  'pagina.saluto-sera': 'Buonasera',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} carta da ripassare', other: '{n} carte da ripassare' },
  'pagina.sotto-serie': { one: '{n} giorno di fila', other: '{n} giorni di fila' },
  'pagina.sotto-niente': 'Niente in sospeso oggi.',
  'pagina.sotto-vuoto': 'Il tuo libretto, il piano di studio e il ripasso. Tutto qui, tutto tuo.',
  // testata
  'pagina.sottotitolo': 'assistente di studio',
  'pagina.esporta': 'Esporta',
  'pagina.impostazioni': 'Impostazioni',
  'pagina.suggerimento': 'Passa sopra la barra in alto, premi <kbd>/</kbd> per scrivere o tieni premuto <kbd>{tasti}</kbd> per parlare.',
  // i numeri
  'pagina.media-ponderata': 'Media ponderata',
  'pagina.media-dettaglio': { one: 'aritmetica {media} · {n} voto', other: 'aritmetica {media} · {n} voti' },
  'pagina.primo-voto': 'segna il primo voto dalla barra',
  'pagina.base-laurea': 'Base di laurea',
  'pagina.base-formula': 'media × 110 / 30',
  'pagina.crediti': 'Crediti',
  'pagina.cfu-alla-laurea': '{n} CFU alla laurea',
  'pagina.questa-settimana': 'Questa settimana',
  'pagina.minuti-settimana': 'Minuti di studio negli ultimi 7 giorni',
  'pagina.giorno-ore': '{giorno}: {ore}',
  'pagina.iniziali-giorni': ['D', 'L', 'M', 'M', 'G', 'V', 'S'],
  // esami
  'pagina.prossimi-esami': 'Prossimi esami',
  'pagina.nuovo-esame': 'Nuovo esame',
  'pagina.vuoto-scrivi': 'Scrivi nella barra in alto:',
  'pagina.vuoto-comando': 'esame analisi 2 il 15 gennaio 9 cfu',
  'pagina.vuoto-oppure': 'oppure {bottone}',
  'pagina.prova-esempio': 'prova con i dati di esempio',
  'pagina.programma-aggiungi': '+ Programma d\'esame',
  'pagina.giorno-cuscinetto': 'giorno cuscinetto',
  'pagina.ripasso-generale': 'ripasso generale',
  'pagina.niente-di-nuovo': 'niente di nuovo',
  'pagina.programma-pronto': '<b>{pct}% del programma</b> · oggi: {oggi}',
  'pagina.data-da-decidere': 'Data da decidere',
  'pagina.quando-cfu': '{quando} · {cfu} CFU',
  'pagina.giorni-maiuscolo': { one: 'GIORNO', other: 'GIORNI' },
  'pagina.ore-studiate': '{fatte} di {tot} h studiate',
  'pagina.ore-oggi': '<b>{h} h</b> oggi',
  'pagina.oggi-in-pari': 'oggi in pari',
  'pagina.focus': 'Focus',
  'pagina.ripassa': 'Ripassa',
  'pagina.ripassa-n': 'Ripassa {n}',
  'pagina.interrogami': 'Interrogami',
  'pagina.modifica-segna-voto': 'Modifica · Segna voto',
  // libretto e ripasso
  'pagina.libretto': 'Libretto',
  'pagina.segna-voto': 'Segna un voto',
  'pagina.ripasso': 'Ripasso',
  'pagina.da-file': 'Da file',
  'pagina.libretto-vuoto': 'Nessun esame dato. Scrivi nella barra <kbd>ho preso 28 in fisica</kbd>.',
  'pagina.col-esame': 'Esame',
  'pagina.col-cfu': 'CFU',
  'pagina.col-voto': 'Voto',
  'pagina.col-data': 'Data',
  'pagina.idoneo': 'idoneo',
  'pagina.voto-lode': '{voto}L',
  'pagina.modifica-esame': 'Modifica {nome}',
  'pagina.libretto-esami': '{n} esami · {cfu} CFU',
  'pagina.libretto-media': 'media <b>{media}</b> · base <b>{base}</b>',
  'pagina.mazzi-vuoto': 'Ancora nessuna carta. Scrivi <kbd>carta: domanda = risposta</kbd> o trascina un PDF sulla finestra.',
  'pagina.esame-tolto': 'Esame tolto',
  'pagina.senza-esame': 'Senza esame',
  'pagina.n-carte': { one: '{n} carta', other: '{n} carte' },
  'pagina.da-ripassare-oggi': 'da ripassare oggi',
  'pagina.piede': 'Lode è open source (MIT). I tuoi dati restano in questo browser: nessun account, nessun server.',
  'pagina.importa-backup': 'Importa un backup',
  // finestra dell'esame
  'pagina.esame-correggi': 'Correggi i dati o segna il voto.',
  'pagina.esame-aiuto': 'Puoi anche scriverlo nella barra: «esame fisica 2 il 20 febbraio 6 cfu».',
  'pagina.campo-nome': 'Nome',
  'pagina.esempio-esame': 'Analisi 2',
  'pagina.campo-cfu': 'CFU',
  'pagina.campo-data': 'Data',
  'pagina.campo-data-appello': 'Data dell\'appello',
  'pagina.campo-voto': 'Voto',
  'pagina.campo-voto-nota': 'vuoto se non l\'hai ancora dato',
  'pagina.trenta-e-lode': '30 e lode',
  'pagina.idoneita': 'Idoneità',
  'pagina.campo-ore': 'Ore di studio previste',
  'pagina.campo-ore-nota': 'per il piano',
  'pagina.ore-segnaposto': '10 × CFU',
  'pagina.elimina': 'Elimina',
  'pagina.annulla': 'Annulla',
  'pagina.salva': 'Salva',
  'pagina.conferma-elimina': 'Eliminare {nome}? Le sue ore e le carte restano, senza esame.',
  'pagina.esame-eliminato': 'Esame eliminato',
  'pagina.salvato': 'Salvato',
  'pagina.esame-aggiunto': 'Esame aggiunto',
  // finestra delle impostazioni
  'pagina.impostazioni-aiuto': 'Tutto resta su questo computer. La chiave della tua AI va solo al servizio che scegli.',
  'pagina.campo-tuo-nome': 'Il tuo nome',
  'pagina.esempio-nome': 'Giulia',
  'pagina.campo-corso': 'Corso di laurea',
  'pagina.esempio-corso': 'Ingegneria informatica',
  'pagina.campo-cfu-laurea': 'CFU della laurea',
  'pagina.campo-lode-vale': 'La lode vale',
  'pagina.campo-focus': 'Focus (minuti)',
  'pagina.campo-pausa': 'Pausa (minuti)',
  'pagina.rintocco': 'Rintocco alla fine del focus',
  'pagina.aspetto-chiaro': 'Aspetto chiaro',
  'pagina.campo-ai': 'La tua AI',
  'pagina.campo-ai-nota': 'facoltativa, a consumo: paghi tu il servizio',
  'pagina.solo-locale': 'Solo il cervello locale (gratis)',
  'pagina.campo-chiave': 'Chiave',
  'pagina.campo-chiave-nota': 'si crea sul sito del servizio',
  'pagina.chiave-segnaposto': 'incolla la chiave',
  'pagina.voce-alta': 'Leggi le risposte ad alta voce',
  'pagina.ai-attiva': 'AI <b>attiva</b>: {nome}.',
  'pagina.senza-chiave': 'Senza chiave Lode funziona lo stesso: comandi, timer, libretto e ripasso sono tutti locali; nell\'app c\'è anche il cervello locale gratis.',
  'pagina.cancella-tutto': 'Cancella tutto',
  'pagina.conferma-azzera': 'Cancellare tutti i dati di Lode da questo browser? Prima conviene esportarli.',
  'pagina.dati-cancellati-chiave': 'Dati cancellati, anche la chiave di {nome}: revocala anche nel tuo account ({sito})',
  'pagina.dati-cancellati': 'Dati cancellati',
  'pagina.chiave-cancellata': 'Chiave di {nome} cancellata da qui: revocala anche nel tuo account ({sito})',
  'pagina.impostazioni-salvate': 'Impostazioni salvate',
  'pagina.ai-collegata': '{nome} collegata',
  'pagina.ai-collegata-modello': '{nome} collegata · {modello}',
  'pagina.chiave-non-valida': 'La chiave non è valida',
  'pagina.chiave-non-verificabile': 'Non riesco a verificare la chiave adesso',
  // backup e dati di esempio
  'pagina.backup-scaricato': 'Backup scaricato',
  'pagina.conferma-importa': 'Sostituire i dati attuali con questo backup?',
  'pagina.backup-importato': 'Backup importato',
  'pagina.non-backup': 'Questo file non è un backup di Lode',
  'pagina.conferma-esempio': 'Caricare i dati di esempio al posto dei tuoi?',
  'pagina.esempio-caricato': 'Dati di esempio caricati: passa sopra la barra in alto',
};
