// I sistemi dei voti (italiano, lingua di partenza): nomi dei sistemi, crediti, voto finale, mention e classi (js/sistemi.js).
export default {
  'sistemi.scelta': 'Sistema dei voti',
  'sistemi.nome.it': 'Italia · 18–30 e lode',
  'sistemi.nome.es': 'Spagna · 0–10',
  'sistemi.nome.fr': 'Francia · 0–20',
  'sistemi.nome.de': 'Germania · 1,0–5,0',
  'sistemi.nome.pt': 'Portogallo · 0–20',
  'sistemi.nome.br': 'Brasile · 0–10',
  'sistemi.nome.uk': 'Regno Unito · 0–100 %',
  'sistemi.nome.us': 'Stati Uniti · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'crediti',
  'sistemi.crediti.uk': 'crediti',
  'sistemi.crediti.us': 'ore di credito',
  'sistemi.media': 'Media',
  'sistemi.ponderata': 'Media ponderata',
  'sistemi.aritmetica': 'Media aritmetica',
  'sistemi.finale.it': 'Base di laurea',
  'sistemi.finale.es': 'Media del expediente',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Voto finale (Gesamtnote)',
  'sistemi.finale.pt': 'Média final',
  'sistemi.finale.br': 'Coefficiente di rendimento (CR)',
  'sistemi.finale.uk': 'Classe di laurea',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'nessuna mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Non sufficiente',
  'sistemi.idoneo': 'idoneo',
  'sistemi.lode': '30 e lode',
  'sistemi.matricula': 'Matrícula de Honor',
  'sistemi.sufficienza': 'Sufficienza: {v}',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
