// Testi della sincronizzazione fra i computer (italiano, lingua di partenza): cosa è cifrato e cosa resta in chiaro, la riga
// di stato e gli avvisi (docs/SINCRONIZZAZIONE.md §10.7 e §12). Il README dice le stesse cose: vedi js/sync-testi.js.
export default {
  'sync.cifrati': 'i dati di Lode nel diario (esami, voti, carte e ripassi, sessioni, profilo, impostazioni): non le pagine per Obsidian che Lode ne ricava, qui sotto',
  'sync.in-chiaro': [
    'appunti, Sbobine, file per Anki, diari dei Progetti',
    'Orario.md con le aule',
    'le pagine che Lode scrive per Obsidian, ricavate proprio da quei dati: Esami (voti, media, CFU e ore studiate per esame), Memoria (ore di studio del mese, in che fascia del giorno studi, la serie di giorni, le definizioni sbagliate e quante volte), Home (il prossimo appello, quante carte ci sono da ripassare), Corsi, Glossario',
    'nomi, dimensioni e orari dei file (quando studi)',
    'quanti computer ci sono, quanti file scrive ciascuno e quante azioni ha in ogni file (un file per giorno)',
    'il file del gruppo (sale e controllo della password, quando è nato e da quale computer, l\'impronta del dati.json di prima)',
    'quando è cambiata la password',
    'il dati.json minimo che dice «Aggiorna Lode»',
  ],
  'sync.sul-computer': 'Sul computer il diario di Lode resta in chiaro, protetto solo dal tuo account del sistema.',
  'sync.cronologia': 'Nella cronologia del servizio cloud resta quello che era passato in chiaro prima della password.',
  'sync.dimenticata': 'Se dimentichi la password non si perde niente: ogni computer ha i suoi dati sul disco. Con «Ho dimenticato la password» ne scegli una nuova, e gli altri computer te la chiederanno.',
  'sync.nuova-password': 'Scegli una password nuova. Gli altri computer te la chiederanno. Nessun dato si perde: ogni computer ha i suoi sul disco.',
  'sync.smetti': 'Lode copierà il vault in una cartella fuori da {servizio} e userà quella. Gli altri computer continuano a sincronizzarsi tra loro. Per smettere ovunque, fallo su ogni computer.',
  'sync.la-cartella-cloud': 'la cartella cloud',
  'sync.prima': 'Prima di sincronizzare, aggiorna Lode su tutti i computer.',
  'sync.sperimentale': 'È nuova e sperimentale: provata a fondo con un simulatore di più computer e un cloud dispettoso, ma non ancora da tanti studenti. Prima di accenderla Lode tiene una copia di tutto: il vault di adesso resta dov\'è, intatto, e i dati di Lode vanno anche nella cartella «copie» dei dati di Lode. Se qualcosa non torna, raccontacelo su GitHub (Issues di W1kicartel/Lode).',
  // la riga di stato
  'sync.spenta': 'Spenta · esami, voti e carte restano su questo computer',
  'sync.fermo': 'Il diario di Lode su questo computer non si legge.',
  'sync.solo-qui': 'Solo su questo computer · non sincronizzato',
  'sync.la-tua-cartella': 'la tua cartella cloud',
  'sync.stato-password': 'In pausa: scrivi la password per sincronizzare.',
  'sync.rigenerato-altra': 'Su un altro computer è stata scelta un\'altra password nello stesso momento: scrivi quella.',
  'sync.rigenerato': 'Su un altro computer è cambiata la password: scrivi quella nuova per sincronizzare.',
  'sync.sparito': 'La cartella di Lode nel vault non c\'è più: è stata spostata o cancellata?',
  'sync.in-arrivo': 'Ricevo i dati dagli altri computer… ({dove})',
  'sync.da-migrare': 'Aspetto i dati dal cloud…',
  'sync.scrittura': 'Il disco è pieno (o non si scrive): le ultime modifiche aspettano e le riprovo da solo.',
  'sync.versione': 'Sincronizzato con {dove} · un altro computer ha una Lode più nuova: aggiornala',
  'sync.in-pari': 'Sincronizzato con {dove}',
  'sync.in-pari-cifrato': 'Sincronizzato con {dove} · cifrato',
  'sync.in-pari-ora': 'Sincronizzato con {dove} · controllato alle {ora}',
  'sync.in-pari-cifrato-ora': 'Sincronizzato con {dove} · cifrato · controllato alle {ora}',
  'sync.altro-stato': 'Sincronizzazione: {stato}',
  'sync.in-avvio': 'in avvio',
  // gli avvisi
  'sync.avviso-clone': 'Questo computer sembra una copia di un altro: da adesso ha un nome nuovo. Non si è perso niente.',
  'sync.avviso-orologio': 'L\'orologio di un altro computer sembra molto avanti: controlla data e ora.',
  'sync.avviso-rovinato-mio': 'Un file di Lode di questo computer nella cartella cloud era rovinato o manomesso: l\'ho messo da parte e rimesso a posto dal diario.',
  'sync.avviso-rovinato-altro': 'Un file di Lode di un altro computer è rovinato o manomesso: lo salto finché non torna leggibile.',
  'sync.avviso-scrittura': 'Il disco è pieno o non si scrive: le ultime modifiche non sono ancora nel diario. Le riprovo a ogni giro e quando chiudi Lode.',
  'sync.avviso-recupero': 'Il diario non si poteva scrivere: le modifiche di quel momento sono in un file a parte nella cartella dei dati di Lode.',
  'sync.avviso-portachiavi': 'Il Portachiavi non ha dato la password di Lode (permesso negato, o Lode aggiornato): scrivila di nuovo.',
  'sync.avviso-gruppi-doppi': 'Nella cartella cloud ci sono due gruppi di Lode, uno cifrato e uno no: non li unisco da solo.',
  'sync.avviso-lode-vecchia': 'Una versione vecchia di Lode ha scritto dei dati in .lode/dati.json: aggiornala. Non entrano da soli: una copia è nella cartella dei dati di Lode, e i record nuovi si importano con «Importa le aggiunte».',
  'sync.avviso-altra-password': 'Su un altro computer è stata scelta un\'altra password nello stesso momento: scrivi quella.',
  'sync.avviso-manomesso': 'Il file del gruppo di Lode nella cartella cloud è stato cambiato da fuori (non torna con la password): non lo uso. Controlla la cartella cloud.',
  'sync.avviso-gruppo-chiaro': 'Il file del gruppo di Lode dice «senza password» ma i dati degli altri computer sono cifrati: è stato manomesso? Non pubblico niente finché non torna a posto.',
  'sync.avviso-parametri': 'Questo vault è stato protetto da una Lode più nuova: aggiornala.',
};
