// I nomi del vault (js/nomi.js): cartelle, note, sezioni e parole che Lode scrive nel vault e poi rilegge. Si scelgono
// UNA volta, quando il vault nasce, nella lingua di quel momento, e si salvano in .lode/vault.json: cambiare una voce qui
// non rinomina niente nei vault che esistono già. Niente caratteri vietati nei nomi di file (/ \\ : * ? " < > | # ^ [ ]).
export default {
  // cartelle (create una volta, alla nascita del vault: poi restano quelle)
  'vaultnomi.cartella-lezioni': 'Lezioni',
  'vaultnomi.cartella-corsi': 'Corsi',
  'vaultnomi.cartella-sbobine': 'Sbobine',
  'vaultnomi.cartella-anki': 'Anki',
  'vaultnomi.cartella-allegati': 'Allegati',
  'vaultnomi.cartella-materiali': 'Materiali',
  'vaultnomi.cartella-progetti': 'Progetti',
  'vaultnomi.cartella-modelli': 'Modelli',
  'vaultnomi.cartella-inbox': 'Inbox',
  // i «corsi» che Lode inventa quando non ce n'è uno (diventano cartelle e note)
  'vaultnomi.corso-sparsi': 'Appunti sparsi',
  'vaultnomi.corso-videolezioni': 'Videolezioni',
  'vaultnomi.corso-varie': 'Varie',
  // note (senza «.md»)
  'vaultnomi.nota-home': 'Home',
  'vaultnomi.nota-orario': 'Orario',
  'vaultnomi.nota-esami': 'Esami',
  'vaultnomi.nota-glossario': 'Glossario',
  'vaultnomi.nota-benvenuto': 'Benvenuto',
  'vaultnomi.nota-memoria': 'Memoria',
  'vaultnomi.nota-tasca': 'In tasca',
  'vaultnomi.modello-lezione': 'Lezione',
  'vaultnomi.modello-esame': 'Esame',
  'vaultnomi.modello-ripasso': 'Ripasso',
  // titoli delle sezioni che Lode scrive e rilegge
  'vaultnomi.sezione-appunti': 'Appunti',
  'vaultnomi.sezione-stella': '★ Da esame',
  'vaultnomi.sezione-definizioni': 'Definizioni',
  'vaultnomi.sezione-domande': 'Domande per il prof',
  'vaultnomi.sezione-trascrizione': 'Trascrizione',
  'vaultnomi.sezione-riordinati': 'Appunti riordinati da Lode',
  'vaultnomi.titolo-note-per-lode': 'Note per Lode',
  'vaultnomi.titolo-cosa-ho-capito': 'Cosa ho capito',
  'vaultnomi.titolo-cosa-so-davvero': 'Cosa so davvero',
  'vaultnomi.titolo-informatica': 'Informatica',
  'vaultnomi.titolo-ripasso-in-tasca': 'Ripasso in tasca',
  'vaultnomi.titolo-orario': 'Orario delle lezioni',
  'vaultnomi.titolo-lezioni': 'Lezioni',
  'vaultnomi.titolo-stelle-ultime': '★ Da esame, le ultime',
  // il ripasso in tasca: il titolo della risposta e le due caselle (il giro le rilegge)
  'vaultnomi.parola-risposta': 'Risposta',
  'vaultnomi.parola-sapevo': 'sapevo',
  'vaultnomi.parola-non-sapevo': 'non sapevo',
  // la nota dell'orario: colonne, giorni (domenica per primo) e la riga che spiega
  'vaultnomi.orario-colonne': ['Corso', 'Giorni', 'Inizio', 'Fine', 'Aula'],
  'vaultnomi.giorni-brevi': ['dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
  'vaultnomi.orario-spiega': 'Lode lo legge per sapere quando sei a lezione. Puoi modificarlo qui o dalla barra («lezione analisi 2 lunedì e mercoledì 9-11 aula 7»).',
  // i commenti dentro le note nuove
  'vaultnomi.commento-definizioni': 'Una per riga: - **Termine**: definizione. Lode ne fa giochi di memoria e carte.',
  'vaultnomi.commento-corso': 'Scrivi pure qui sopra o sotto: il riquadro di Lode (lezioni, ★, appello) si aggiorna da solo e il resto non lo tocca.',
  'vaultnomi.commento-cosa-ho-capito': 'Questa parte è tua: Lode non la tocca mai. Cosa hai capito oggi, cosa non ti torna ancora.',
  'vaultnomi.segnalibro-memoria': 'Cosa sa Lode di me',
  // i modelli di Obsidian e le note che nascono col vault
  'vaultnomi.esame-programma': 'Programma',
  'vaultnomi.esame-domande': 'Domande che fanno sempre',
  'vaultnomi.esame-domande-commento': 'Quelle che senti dai colleghi o trovi nei vecchi appelli. Lode le usa per interrogarti.',
  'vaultnomi.esame-esercizi': 'Esercizi tipo',
  'vaultnomi.esame-manca': 'Cosa mi manca',
  'vaultnomi.ripasso-tre-righe': 'In tre righe',
  'vaultnomi.ripasso-commento-definizioni': '- **Termine**: definizione. Finiscono nei giochi di Lode.',
  'vaultnomi.ripasso-collegamenti': 'Collegamenti',
  'vaultnomi.ripasso-commento-collegamenti': 'Le lezioni e i concetti legati: [[...]]',
  'vaultnomi.memoria-titolo': 'Cosa so di te',
  'vaultnomi.memoria-commento': 'Questa nota la scrive Lode dopo ogni gioco. La sezione «{sezione}» resta tua: la leggo ogni volta che uso l\'AI.',
  'vaultnomi.memoria-in-breve': 'In breve',
  'vaultnomi.memoria-ancora-niente': 'Ancora niente: segna qualche definizione in aula e gioca una partita.',
  'vaultnomi.memoria-note-commento': 'Scrivi qui come vuoi essere aiutato: «spiegami con esempi pratici», «frasi brevi», «l\'orale di Analisi è molto teorico».',
  'vaultnomi.benvenuto-firma': 'l\'ha preparato **Lode**',
  'vaultnomi.benvenuto-testo': '# Benvenuto nel tuo vault\n\nQuesto vault {firma}, l\'assistente che vive in cima allo schermo. È un normale vault di Obsidian: le note sono tue, in Markdown, e restano su questo computer.\n\n## Come lavorano insieme\n- **In aula** Lode sa quando sei a lezione (dall\'[[{orario}]]) e tiene pronta la nota della lezione in `{lezioni}/<corso>/`. Dalla barra segni al volo:\n  - **{stella}** (⌃⌥S): cosa il prof ha detto che chiederà;\n  - **Definizione** (⌃⌥D): «termine: definizione»;\n  - **Domanda** (⌃⌥Q): da fare al prof.\n- **Gli appunti** li scrivi qui, in Obsidian, come sempre. Le definizioni che metti nella sezione «{definizioni}» (`- **Termine**: definizione`) o scritte come `Termine :: definizione` Lode le trova da solo.\n- **A casa** la barra ti propone due minuti di gioco sulle definizioni dell\'ultima lezione, quando stanno per scappare.\n- **[[{memoria}]]** (in `{lode}/`) è quello che Lode ha imparato di te: definizioni sicure, da rinforzare, come studi. Nella sezione «{notePerLode}» puoi dirgli come vuoi essere aiutato.\n\n## Scorciatoie\n| | Mac | Windows |\n|---|---|---|\n| Apri Lode e scrivi | ⌥ Spazio | Ctrl ⇧ Spazio |\n| {stella} | ⌃⌥ S | Ctrl Alt S |\n| Definizione | ⌃⌥ D | Ctrl Alt D |\n| Domanda per il prof | ⌃⌥ Q | Ctrl Alt Q |\n| Gioco di memoria | ⌃⌥ G | Ctrl Alt G |\n',
  // frasi della barra che citano un nome del vault: il nome arriva dal vault, non dalla lingua della barra
  'vaultnomi.frase-orario-nel-vault': 'L\'orario è anche nel vault, in «{nota}»: puoi cambiarlo da Obsidian.',
  'vaultnomi.frase-nella-cartella': 'È nella cartella {cartella} del vault.',
  'vaultnomi.frase-riordinati-nota': 'Vanno nella nota, in «{sezione}», sotto la trascrizione (che resta). Li ha scritti {motore}: rileggili.',
};
