// Testi delle pagine che Lode scrive nel vault per lo studente (italiano, lingua di partenza): Home, Esami, Glossario, le
// pagine dei corsi e la Memoria. Non ci sono i nomi di note, cartelle, sezioni e chiavi che il codice rilegge: quelli restano
// come sono nel codice (diventeranno la tabella NOMI).
export default {
  // la memoria
  'vault.prop-gioco': 'giochi',
  'vault.prop-ripasso': 'ripasso delle carte',
  'vault.prop-stelle': 'rileggere le ★',
  'vault.prop-orale': 'domande lampo',
  'vault.prop-focus': 'focus',
  'vault.prop-stampa': 'cosa stampa',
  'vault.prop-voce': '{nome} ({si} su {tot})',
  'vault.memoria-proposte': 'Delle proposte di Lode accetti soprattutto: {elenco}.',
  'vault.memoria-titolo': 'Cosa so di te',
  'vault.memoria-commento': 'Questa nota la scrive Lode. Puoi leggerla e anche correggerla: la sezione «{sezione}» la leggo ogni volta che uso l\'AI.',
  'vault.titolo-in-breve': 'In breve',
  'vault.memoria-lezioni': { one: '{n} lezione annotata', other: '{n} lezioni annotate' },
  'vault.memoria-definizioni': { one: '{n} definizione', other: '{n} definizioni' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni}: **{sicure} sicure**, {deboli} da rinforzare, {mai} ancora da giocare.',
  'vault.memoria-serie': { one: 'Serie di studio: {n} giorno di fila. Questo mese: {h} h.', other: 'Serie di studio: {n} giorni di fila. Questo mese: {h} h.' },
  'vault.memoria-fascia': 'Studi soprattutto di **{fascia}**.',
  'vault.fascia-mattina': 'mattina',
  'vault.fascia-pomeriggio': 'pomeriggio',
  'vault.fascia-sera': 'sera',
  'vault.titolo-da-rinforzare': 'Da rinforzare',
  'vault.sbagliata': { one: 'sbagliata {n} volta su {tot}', other: 'sbagliata {n} volte su {tot}' },
  'vault.niente-per-ora': 'Niente, per ora.',
  'vault.titolo-sicure': 'Sicure',
  'vault.sicure-vuoto': 'Ancora nessuna: gioca qualche partita.',
  'vault.ancora-nessuna': 'Ancora nessuna.',
  'vault.note-commento': 'Scrivi qui come vuoi essere aiutato: «spiegami con esempi pratici», «sono dislessico, frasi brevi», «l\'orale di Analisi è con Rossi, molto teorico».',
  // Home
  'vault.home-carte': { one: '{n} carta da ripassare', other: '{n} carte da ripassare' },
  'vault.alias-memoria': 'Cosa sa Lode di me',
  'vault.alias-benvenuto': 'Come funziona',
  'vault.titolo-oggi': 'Oggi',
  'vault.aula': 'aula {aula}',
  'vault.niente-lezioni-oggi': 'Niente lezioni oggi.',
  'vault.titolo-corsi': 'Corsi',
  'vault.n-lezioni': { one: '{n} lezione', other: '{n} lezioni' },
  'vault.idoneo': 'idoneo',
  'vault.voto-e-lode': '{voto} e lode',
  'vault.appello': 'appello {data}',
  'vault.corsi-vuoto': 'Aggiungi l\'orario dalla barra: «lezione analisi 2 lunedì 9-11 aula 7».',
  'vault.titolo-ultime-lezioni': 'Ultime lezioni',
  'vault.definizioni-n': { one: '{n} definizione', other: '{n} definizioni' },
  'vault.titolo-carriera': 'Carriera',
  'vault.carriera': 'Media **{media}** · base di laurea **{base}**/110 · {cfu} di {tot} CFU → {esami}',
  // Esami
  'vault.titolo-prossimi-appelli': 'Prossimi appelli',
  'vault.tabella-appelli': '| Esame | Data | Tra | CFU | Ore studiate |',
  'vault.ore-di': '{fatte} di {tot} h',
  'vault.nessun-appello': 'Nessun appello segnato.',
  'vault.senza-data': 'Senza data: {elenco}.',
  'vault.titolo-libretto': 'Libretto',
  'vault.tabella-libretto': '| Esame | CFU | Voto | Data |',
  'vault.voto-l': '{voto}L',
  'vault.libretto-piede': 'Media ponderata **{media}** · base di laurea **{base}**/110 · {cfu} di {tot} CFU',
  'vault.libretto-vuoto': 'Ancora nessun esame dato.',
  // Glossario
  'vault.n-definizioni': { one: '{n} definizione', other: '{n} definizioni' },
  'vault.da-rinforzare': '*da rinforzare*',
  'vault.glossario-vuoto': 'Le definizioni delle lezioni compaiono qui, in ordine alfabetico, divise per corso.',
  // la pagina del corso
  'vault.corso-cfu': '**{cfu} CFU**',
  'vault.corso-voto': 'voto {voto}',
  'vault.corso-voto-lode': 'voto {voto} e lode',
  'vault.corso-appello': { one: 'appello **{data}** (tra {n} giorno) · {fatte} di {tot} h studiate', other: 'appello **{data}** (tra {n} giorni) · {fatte} di {tot} h studiate' },
  'vault.corso-lezioni': 'Lezioni: {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} aula {aula}',
  'vault.lezioni-vuoto': 'Ancora nessuna: la prima nasce quando segni qualcosa in aula.',
};
