// La barre (js/lode.js, première partie : pastille, panneau, accueil, outils, révision, emploi du temps, transcription,
// fichiers), en français.
export default {
  // les touches pour parler et les nombres écrits en lettres (« Trois cartes à réviser »)
  'barra1.tasti-mac': '⌥ Espace',
  'barra1.tasti': 'Ctrl ⇧ Espace',
  'barra1.numeri': ['Aucune', 'Une', 'Deux', 'Trois', 'Quatre', 'Cinq', 'Six', 'Sept', 'Huit', 'Neuf', 'Dix'],
  // la salutation et la phrase en haut du panneau
  'barra1.saluto-notte': 'Encore debout',
  'barra1.saluto-mattina': 'Bonjour',
  'barra1.saluto-pomeriggio': 'Bon après-midi',
  'barra1.saluto-sera': 'Bonsoir',
  'barra1.saluto-con-nome': '{saluto}, {nome}.',
  'barra1.saluto-senza-nome': '{saluto}.',
  'barra1.esame-oggi': "Aujourd'hui, c'est {nome}. Bonne chance !",
  'barra1.esame-tra': '{nome} {quando}.',
  'barra1.carte-da-ripassare': { one: '{quante} carte à réviser.', other: '{quante} cartes à réviser.' },
  'barra1.niente-in-sospeso': "Rien en attente aujourd'hui.",
  'barra1.dimmi-esame': 'Dis-moi ton prochain examen et je prépare le plan.',
  // la coquille : champ, pied, fichiers glissés
  'barra1.aria-lode': "Lode, assistant d'étude",
  'barra1.aria-torna-home': "Revenir à l'accueil de Lode",
  'barra1.indietro': 'Retour',
  'barra1.aria-campo': 'Demande ou écris une commande',
  'barra1.campo': 'Demande ou écris une commande…',
  'barra1.ti-ascolto': "Je t'écoute",
  'barra1.esc-annulla': 'Esc pour annuler',
  'barra1.un-attimo': 'Un instant…',
  'barra1.aria-parla': 'Parle (ou maintiens {tasti})',
  'barra1.tieni-premuto': 'Maintiens pour parler <kbd>{tasti}</kbd>',
  'barra1.dati-qui': 'Les données restent sur cet ordinateur',
  'barra1.lascia-file': 'Dépose le fichier ici',
  'barra1.lascia-file-cosa': 'PDF, diapos, notes, photos du tableau : Lode en fait des cartes de révision',
  'barra1.dopo': 'Plus tard',
  // « Aujourd'hui » : les lignes de l'accueil
  'barra1.di-stamattina': 'de ce matin',
  'barra1.di-oggi': "d'aujourd'hui",
  'barra1.di-ieri': "d'hier",
  'barra1.di-giorno': 'de {giorno}',
  'barra1.sugg-definizioni-corso': { one: '{n} définition de {corso} {quando}', other: '{n} définitions de {corso} {quando}' },
  'barra1.sugg-definizioni-ultime': { one: '{n} définition des derniers cours', other: '{n} définitions des derniers cours' },
  'barra1.sync-bloccata': 'Lode marche avec les données de cet ordinateur : les modifications attendent dans le journal.',
  'barra1.sblocca': 'Déverrouiller',
  'barra1.sync-sparita': "Le dossier de Lode dans le coffre n'est plus là",
  'barra1.sync-sparita-dett': 'Il a été déplacé ou supprimé ? Les données de cet ordinateur sont en sécurité dans son journal.',
  'barra1.vedi': 'Voir',
  'barra1.sync-spostamento': "Le déplacement vers le dossier cloud s'est interrompu",
  'barra1.sync-spostamento-dett': "L'ancien coffre est intact : je reprends là où je m'étais arrêté.",
  'barra1.riprendi': 'Reprendre',
  'barra1.detto-sincronizza': 'Synchronise entre les ordinateurs',
  'barra1.dati-altrove': 'Ce coffre se synchronise avec Lode sur un autre ordinateur',
  'barra1.dati-altrove-dett': "Les données sont dans le journal de Lode 2 : choisis « J'utilise déjà Lode sur un autre ordinateur » pour les voir ici. Les modifications faites maintenant vont dans un fichier à part, pas par-dessus les données.",
  'barra1.uso-gia-lode': "J'utilise déjà Lode",
  'barra1.detto-uso-gia-lode': "J'utilise déjà Lode sur un autre ordinateur",
  'barra1.dati-fermo': 'Le journal de Lode sur cet ordinateur est illisible',
  'barra1.dati-fermo-dett': "Rien n'a été supprimé : le dossier des données de Lode ne répond pas (disque plein ou en panne ?).",
  'barra1.riprova': 'Réessayer',
  'barra1.dati-illeggibili': "Je n'arrive pas à lire tes données",
  'barra1.dati-illeggibili-dett': 'Examens, notes et cartes sont en sécurité, mais le dossier ne répond pas (OneDrive hors ligne ou fichier verrouillé). Les modifications faites maintenant vont dans un fichier à part ; je réessaie tout seul.',
  'barra1.lezione-alle': '{corso} à {ora}',
  'barra1.lezione-aula-tra': 'Salle {aula} · dans {n} min',
  'barra1.lezione-tra': 'dans {n} min',
  'barra1.appunti': 'Notes',
  'barra1.orario': 'Emploi du temps',
  'barra1.completa-lode': 'Compléter Lode',
  'barra1.completa-tutti-e-due': 'Obsidian et le cerveau local : un clic, gratuit',
  'barra1.completa-obsidian': 'Obsidian : un clic, gratuit',
  'barra1.completa-cervello': 'le cerveau local : un clic, gratuit',
  'barra1.prepara': 'Préparer',
  'barra1.detto-prepara-lode': 'Prépare Lode',
  'barra1.chiudi-lezione-di': 'Clôturer le cours de {corso}',
  'barra1.chiudi-lezione-dett': { one: "{n} mot de notes · j'extrais les définitions et les ★", other: "{n} mots de notes · j'extrais les définitions et les ★" },
  'barra1.chiudi': 'Clôturer',
  'barra1.detto-chiudi-lezione': 'Clôture le cours',
  'barra1.gioco-due-minuti': 'Jeu de deux minutes',
  'barra1.gioca': 'Jouer',
  'barra1.esame-ore-oggi': "{data} · {ore} h aujourd'hui pour rester à jour",
  'barra1.esame-in-pari': "{data} · aujourd'hui, tu es à jour",
  'barra1.focus': 'Focus',
  'barra1.ripasso': 'Révision',
  'barra1.ripasso-carte-min': { one: '{n} carte · environ {min} min', other: '{n} cartes · environ {min} min' },
  'barra1.inizia': 'Commencer',
  'barra1.studio-oggi': "{ore} de révision aujourd'hui",
  'barra1.non-hai-studiato': "Tu n'as pas encore révisé aujourd'hui",
  'barra1.giorni-di-fila': { one: "{n} jour d'affilée", other: "{n} jours d'affilée" },
  'barra1.bastano-25': 'Il suffit de 25 minutes pour lancer une série',
  'barra1.libretto': 'Relevé de notes',
  // en cours, Répète, la transcription, l'accueil
  'barra1.in-aula': 'En cours · {corso}',
  'barra1.aula-finisce-tra': 'salle {aula} · finit dans {n} min',
  'barra1.finisce-tra': 'finit dans {n} min',
  'barra1.cattura-stella': "★ À l'exam",
  'barra1.cattura-definizione': 'Définition',
  'barra1.cattura-domanda': 'Question',
  'barra1.cose-segnate': { one: "{quante} chose notée pour l'exam aujourd'hui.", other: "{quante} choses notées pour l'exam aujourd'hui." },
  'barra1.ripeti-attivo-memoria': 'Répète actif · seulement en mémoire, jamais sur le disque',
  'barra1.ripeti': 'Répète',
  'barra1.spegni': 'Éteindre',
  'barra1.ripeti-spento-invito': "<b>Répète 60 s</b> · tu as raté une phrase ? Lode te la répète. Rien n'est enregistré.",
  'barra1.trascrivi-lezione': 'Transcrire le cours',
  'barra1.trascrivi-lezione-dett': 'Tout ce que dit le prof, formules comprises, dans la note Obsidian · {tasti}',
  'barra1.trascrizione-in-pausa': 'En pause · {min} min · {parole} mots',
  'barra1.trascrizione-in-corso': 'Je transcris · {min} min · {parole} mots',
  'barra1.prima-riga': "J'écoute : la première ligne arrive dans une vingtaine de secondes.",
  'barra1.pausa': 'Pause',
  'barra1.fine': 'Fin',
  'barra1.oggi': "Aujourd'hui",
  'barra1.cfu-di': '{fatti} sur {tot} crédits',
  'barra1.inizia-da-qui': 'Commence ici',
  'barra1.inizia-da-qui-dett': "Écris « cours analyse 2 lundi 9h-11h salle 7 », ou essaie les données d'exemple",
  'barra1.esempio': 'Exemple',
  // les outils et le haut du panneau
  'barra1.strumento-gioco': 'Jeu',
  'barra1.strumento-codice': 'Code',
  'barra1.strumento-note': 'Notes',
  'barra1.strumento-interrogami': 'Interroge-moi',
  'barra1.strumento-esami': 'Examens',
  'barra1.sei-a-lezione': "Tu es en cours de {corso}. Prends tes notes tranquille : je m'occupe de ne rien perdre.",
  'barra1.testa-media': 'moyenne {media}',
  'barra1.testa-serie': { one: 'série de {n} jour', other: 'série de {n} jours' },
  // la pastille
  'barra1.ripeti-attivo-titolo': 'Répète actif : la dernière minute et demie, seulement en mémoire',
  'barra1.in-pausa': 'en pause',
  'barra1.pausa-minuscolo': 'pause',
  'barra1.aria-timer': '{cosa} : il reste {resta}',
  'barra1.prova-generale': 'Examen blanc',
  'barra1.focus-su': 'Focus sur {nome}',
  'barra1.aria-ripeti-acceso': '. Répète : micro allumé',
  'barra1.pillola-trascrizione-in-pausa': 'transcription en pause · {parole} mots',
  'barra1.pillola-trascrivo': 'je transcris · {parole} mots',
  'barra1.fine-tra': 'fin dans {n} min',
  'barra1.pillola-aula-tra': 'salle {aula} · dans {n} min',
  'barra1.microfono-acceso': 'micro allumé',
  'barra1.due-minuti': '2 minutes',
  'barra1.pillola-tra-giorni': 'dans {n} j',
  // en français la pastille accorde « carte » avec le nombre
  'barra1.pillola-carte': { one: '{n} carte', other: '{n} cartes' },
  'barra1.pillola-da-ripassare': { one: 'carte à réviser', other: 'cartes à réviser' },
  'barra1.passa-qui-sopra': 'passe ici',
  'barra1.aria-pillola': 'Lode : {testo}{ripeti}. Passe dessus ou appuie sur {tasti}.',
  // la conversation, « C'est fait. », « Confirmer / Annuler »
  'barra1.altre-righe': { one: '{n} ligne', other: '{n} lignes' },
  'barra1.altro': 'suite',
  'barra1.fatto': "C'est fait.",
  'barra1.annulla': 'Annuler',
  'barra1.disfa': 'Annuler',
  'barra1.annullato-minuscolo': 'annulé',
  'barra1.confermi': 'Tu confirmes ?',
  'barra1.conferma': 'Confirmer',
  'barra1.scrivi-si': 'Tu peux aussi écrire « ok ».',
  'barra1.annullato': 'Annulé.',
  'barra1.niente-cambiato': "Je n'ai rien changé.",
  // Focus
  'barra1.durata': 'Durée',
  'barra1.min': 'min',
  'barra1.su-che-cosa': 'Sur quoi',
  'barra1.studio-libero': 'Étude libre',
  'barra1.pausa-alla-fine': "Pause de {n} minutes à la fin. Les heures comptent dans le plan de l'examen.",
  'barra1.sintesi-focus': 'focus',
  'barra1.focus-di-min': 'Focus de {min} minutes.',
  'barra1.focus-di-min-su': 'Focus de {min} minutes sur {nome}.',
  'barra1.ci-vediamo': 'On se retrouve à la pause.',
  'barra1.sintesi-focus-min': 'focus {min} min',
  // Relevé de notes et « et si j'ai… »
  'barra1.media-ponderata': 'Moyenne pondérée',
  'barra1.aritmetica-esami': { one: 'arithmétique {media} · {n} examen', other: 'arithmétique {media} · {n} examens' },
  'barra1.nessun-voto': 'pas encore de note',
  'barra1.base-di-laurea': 'Base di laurea (sur 110)',
  'barra1.serve-gia': 'Pour partir de <b>{obiettivo}</b>, il te suffit de valider les examens qui restent.',
  'barra1.serve-media': 'Pour partir de <b>{obiettivo}</b>, il te faut <b>{voto}</b> de moyenne sur les {cfu} crédits qui restent.',
  'barra1.serve-impossibile': "Partir de <b>{obiettivo}</b> n'est plus possible : vise {punta}.",
  'barra1.e-se': 'Et si…',
  'barra1.esame': 'Examen',
  'barra1.voto': 'Note',
  'barra1.simula-esito': 'Moyenne <b>{media}</b> <span class="{classe}">{delta}</span> · base <b>{base}</b>',
  'barra1.sintesi-media-base': 'moyenne {media}, base {base}',
  'barra1.sintesi-libretto-vuoto': 'relevé de notes vide',
  'barra1.simula-non-trovo': 'Je ne trouve pas **{nome}** dans tes examens. Ajoute-le avec « examen {nome} 6 ects ».',
  'barra1.simula-primo': 'Avec {voto} en **{nome}**, ta moyenne partirait de **{voto}** : base **{base}**.',
  'barra1.simula-primo-lode': 'Avec {voto} avec mention (lode) en **{nome}**, ta moyenne partirait de **{voto}** : base **{base}**.',
  'barra1.simula': 'Avec **{voto}** en {nome}, la moyenne passe de {prima} à **{dopo}** ({delta}) : base di laurea **{base}**.',
  'barra1.simula-lode': 'Avec **{voto} avec mention (lode)** en {nome}, la moyenne passe de {prima} à **{dopo}** ({delta}) : base di laurea **{base}**.',
  'barra1.sintesi-media': 'moyenne {media}',
  // Examens
  'barra1.incolla-programma': 'Colle le programme : je te prépare le plan par chapitres',
  'barra1.giorno-cuscinetto': 'jour tampon',
  'barra1.ripasso-generale': 'révision générale',
  'barra1.niente-di-nuovo': 'rien de nouveau',
  'barra1.pronto': 'prêt à {n} %',
  'barra1.prossimi-appelli': 'Prochains examens · {n}',
  'barra1.esame-riga': '{data} · {cfu} crédits · {fatte} sur {tot} h',
  'barra1.ore-oggi': "{ore} h aujourd'hui",
  'barra1.giorni-parola': { one: 'jour', other: 'jours' },
  'barra1.nessun-appello': 'Aucun examen dans le calendrier.',
  'barra1.senza-data': 'Sans date : {nomi}.',
  'barra1.nuovo-esame': 'Nouvel examen',
  'barra1.nome-esame': "Nom de l'examen",
  'barra1.cfu': 'Crédits',
  'barra1.data-appello': "Date de l'examen",
  'barra1.aggiungi': 'Ajouter',
  'barra1.programma-di': 'Programme de {nome}',
  'barra1.esame-aggiunto': '{nome} ajouté.',
  'barra1.senza-data-nota': 'sans date',
  'barra1.sintesi-appello': '{nome} {quando}',
  'barra1.sintesi-nessun-appello': "pas d'examen",
  // Révision
  'barra1.ripasso-di': 'Révision · {nome}',
  'barra1.niente-da-ripassare': "Rien à réviser aujourd'hui. La prochaine carte revient {quando}.",
  'barra1.nessuna-carta': 'Pas encore de cartes. Écris « carte : question = réponse », ou glisse un PDF ici.',
  'barra1.risposta': 'Réponse',
  'barra1.aggiungi-carta': 'Ajouter la carte',
  'barra1.carta-aggiunta': 'Carte ajoutée.',
  'barra1.torna-oggi': "Elle revient dès aujourd'hui dans la révision.",
  'barra1.sintesi-niente-da-ripassare': 'rien à réviser',
  'barra1.mostra-risposta': 'Voir la réponse <kbd>Espace</kbd>',
  'barra1.x-di-y': '{x} sur {y}',
  'barra1.ripasso-finito': { one: 'Révision terminée : {n} carte en {min} min.', other: 'Révision terminée : {n} cartes en {min} min.' },
  'barra1.difficili-domani': 'Les difficiles reviennent demain.',
  'barra1.sintesi-carte-ripassate': { one: '{n} carte révisée', other: '{n} cartes révisées' },
  'barra1.sintesi-ripasso-di': { one: 'révision de {n} carte', other: 'révision de {n} cartes' },
  // les commandes à essayer
  'barra1.prova-a-scrivere': "Essaie d'écrire",
  'barra1.aiuto-senza-ai': 'Avec le cerveau local (gratuit) ou ton IA (écris « IA »), tu peux aussi demander des explications, créer des cartes à partir des PDF et te faire interroger.',
  'barra1.sintesi-comandi': 'commandes',
  // Emploi du temps
  'barra1.orario-lezioni': { one: 'Emploi du temps · {n} cours par semaine', other: 'Emploi du temps · {n} cours par semaine' },
  'barra1.corso-aula': '{corso} · salle {aula}',
  'barra1.punto-aula': ' · salle {aula}',
  'barra1.togli': 'Enlever {nome}',
  'barra1.corso': 'Cours',
  'barra1.giorni': 'Jours',
  'barra1.inizio': 'Début',
  'barra1.aula': 'Salle',
  'barra1.orario-oppure-scrivi': 'Ou écris : « cours analyse 2 lundi et mercredi 9h-11h salle 7 ».',
  'barra1.in-orario': "{corso} ajouté à l'emploi du temps.",
  'barra1.sintesi-lezioni-settimana': { one: '{n} cours par semaine', other: '{n} cours par semaine' },
  // le plan pour ceux qui travaillent
  'barra1.ore-regola': { one: '{n} heure', other: '{n} heures' },
  'barra1.la-tua-settimana': 'Ta semaine',
  'barra1.detto-piano-settimana': 'Planning de la semaine',
  'barra1.lavori': 'Tu travailles {turni}.',
  'barra1.lavori-nota': "Je l'enlève des heures de révision, avec une demi-heure pour le trajet. Les jours de travail, tu révises au maximum {tetto} : change-le avec « les jours de boulot je révise max {altro}h ».",
  'barra1.turni-cambiati': 'Horaires modifiés.',
  'barra1.turni-salvati': 'Horaires enregistrés.',
  'barra1.sintesi-lavoro': 'travail {turni}',
  'barra1.turni-tolti': 'Horaires supprimés.',
  'barra1.turni-tolti-nota': 'Le plan recompte toute ta journée de révision.',
  'barra1.giorno-non-lavori': '{giorno}, tu ne travailles pas.',
  'barra1.ore-libere': 'Ces heures redeviennent libres pour réviser.',
  'barra1.giorno-lavori-anche': '{giorno}, tu travailles aussi de {da} à {a}.',
  'barra1.solo-quel-giorno': "Seulement ce jour-là : je l'enlève des heures de révision.",
  'barra1.tetto': 'Les jours de travail, tu révises au maximum {tetto}.',
  'barra1.tetto-nota': 'Le plan se refait avec ce plafond.',
  'barra1.studi-dalle': 'Tu révises de {da} à {a}.',
  'barra1.studi-dalle-nota': "Le plan n'utilise que ces heures, moins les cours et le travail.",
  'barra1.togli-scelta': 'Enlever : {scelta}',
  'barra1.niente-nel-piano': 'rien dans le plan',
  'barra1.settimana-lavori': "Tu travailles {turni} : je l'enlève des heures de révision, avec une demi-heure pour le trajet. Les jours de travail, tu révises au maximum {tetto}.",
  'barra1.settimana-se-lavori': 'Si tu travailles, écris-le-moi : « je bosse lundi mercredi vendredi 14h-19h ».',
  'barra1.settimana-un-esame': "Avec un seul examen et sans travail, le plan est celui du programme.",
  'barra1.settimana-stime': 'Les heures sont des estimations : un nouveau chapitre environ 1 h, une révision environ 30 min.',
  'barra1.sintesi-la-tua-settimana': 'ta semaine',
  // la saisie rapide en cours
  'barra1.cattura-stella-campo': "Qu'est-ce que le prof a dit qui tombera à l'exam ?",
  'barra1.cattura-definizione-campo': 'Terme : définition',
  'barra1.cattura-domanda-campo': 'La question à poser au prof',
  'barra1.scrivila-cosi': 'Écris-la comme ça : **terme : définition**.',
  'barra1.errore-vault': "Je n'arrive pas à écrire dans le coffre : {errore}",
  'barra1.dove-sparsi': "dans les notes en vrac d'aujourd'hui",
  'barra1.dove-in': 'dans {corso}',
  'barra1.segnato-dove': '★ Noté {dove}.',
  'barra1.definizione-dove': '« {termine} » noté {dove}.',
  'barra1.domanda-dove': 'Question enregistrée {dove}.',
  // transcrire : en cours, depuis l'ordinateur, depuis un enregistrement
  'barra1.videolezioni-app': "La transcription des cours en visio est dans l'**appli de bureau** de Lode : elle écoute le son de l'ordinateur et écrit dans la note Obsidian du cours.",
  'barra1.sto-gia-trascrivendo': 'Je transcris déjà.',
  'barra1.parole-finora': { one: "{n} mot jusqu'ici.", other: "{n} mots jusqu'ici." },
  'barra1.lezione-dal-computer': "Cours depuis l'ordinateur",
  'barra1.computer-spiega': "Lance le cours en visio (sur la plateforme de ta fac, sur Teams, Zoom ou là où tu le suis) : j'écoute le son qui sort de l'ordinateur et je l'écris dans la note du cours, formules comprises.",
  'barra1.nome-del-corso': 'Nom du cours',
  'barra1.computer-patto': "Seulement pour que tu révises : je ne télécharge pas la vidéo et je ne mets rien en ligne, le son n'est pas enregistré et seul le texte va dans la note. Les cours appartiennent aux enseignants : ne partage pas la transcription si le règlement de ta fac ne le permet pas.",
  'barra1.computer-mac': "La première fois, le Mac te demande l'autorisation d'enregistrer le son du système.",
  'barra1.computer-windows': "Sur Windows, tu entends le son comme d'habitude : moi aussi, je l'écoute.",
  'barra1.computer-linux': "Sur Linux, j'écoute le « monitor » de la sortie audio.",
  'barra1.detto-trascrivi-videolezione': 'Transcris la visio de {corso}',
  'barra1.sintesi-lezione-dal-computer': "cours depuis l'ordinateur",
  'barra1.computer-permesso-mac': "Le Mac ne me donne pas le son de l'ordinateur : dans **Réglages Système › Confidentialité et sécurité › Enregistrement de l'écran et de l'audio du système**, active Lode, puis réessaie (parfois il faut rouvrir Lode).",
  'barra1.computer-permesso': "Le système ne me donne pas le son de l'ordinateur : réessaie et accepte la demande de partage.",
  'barra1.computer-non-sento-mac': "Je n'arrive pas à écouter le son de l'ordinateur (il faut macOS 14.2 ou plus récent). {errore}",
  'barra1.computer-non-sento-windows': "Je n'arrive pas à écouter le son de l'ordinateur. {errore}",
  'barra1.computer-non-sento-linux': "Je n'arrive pas à écouter le son de l'ordinateur (il faut PulseAudio ou PipeWire). {errore}",
  'barra1.computer-muto': "Je n'entends rien sur l'ordinateur. Le cours en visio a démarré, avec le son monté ?",
  'barra1.computer-muto-mac': "Je n'entends rien sur l'ordinateur. Le cours en visio a démarré, avec le son monté ? Si oui, le Mac ne me donne pas le son : **Réglages Système › Confidentialité et sécurité › Enregistrement de l'écran et de l'audio du système**, active Lode et réessaie.",
  'barra1.trascrizione-app': "La transcription des cours est dans l'**appli de bureau** de Lode : elle écrit directement dans la note Obsidian du cours.",
  'barra1.computer-aggiorna': "Cette version n'arrive pas à écouter le son de l'ordinateur : mets Lode à jour.",
  'barra1.preparo-voce': 'Je prépare la voix…',
  'barra1.trascrivo-file': 'Je transcris « {file} » dans le cours de {corso}.',
  'barra1.puoi-chiudere': 'Tu peux fermer le panneau : je te préviens à la fin.',
  'barra1.sintesi-registrazione': 'enregistrement en transcription',
  'barra1.ascolto-computer': "J'écoute le son de l'ordinateur pour {corso}.",
  'barra1.ascolto-computer-nota': "Lance le cours en visio : les lignes arrivent dans la note toutes les 20-30 secondes. Quand c'est fini, écris « fin du cours ».",
  'barra1.apri-in-obsidian': 'Ouvrir dans Obsidian',
  'barra1.sintesi-videolezione': 'visio en transcription',
  'barra1.avviso-videolezione': "J'écoute le cours en visio",
  'barra1.trascrivo-sparsi': 'Je transcris dans les notes en vrac.',
  'barra1.trascrivo-lezione-di': 'Je transcris le cours de {corso}.',
  'barra1.righe-ogni': 'Les lignes arrivent dans la note toutes les 20-30 secondes.',
  'barra1.sintesi-trascrizione-avviata': 'transcription lancée',
  'barra1.avviso-trascrivo': 'Je transcris le cours',
  'barra1.errore-trascrivere': "Je n'arrive pas à transcrire : {errore}",
  'barra1.non-sto-trascrivendo': 'Je ne transcris rien.',
  'barra1.ultimi-secondi': 'Je transcris les dernières secondes…',
  'barra1.lezione-trascritta': 'Cours transcrit : {parole} mots.',
  'barra1.righe-sospese': { one: "{n} ligne n'est pas encore dans la note (le dossier ne répond pas) : je l'écris dès que je peux, garde-moi ouvert.", other: "{n} lignes ne sont pas encore dans la note (le dossier ne répond pas) : je les écris dès que je peux, garde-moi ouvert." },
  'barra1.tutto-nella-nota': 'Tout est dans la note.',
  'barra1.riordina': 'Mettre au propre',
  'barra1.detto-riordina': 'Mets au propre le cours',
  'barra1.condividi': 'Partager',
  'barra1.detto-condividi': 'Partage la transcription',
  'barra1.sintesi-parole-trascritte': { one: '{n} mot transcrit', other: '{n} mots transcrits' },
  'barra1.con-cervello-locale': 'Avec le **cerveau local** (depuis « Prépare Lode »), la transcription devient des notes au propre, des définitions et des ★ en un clic.',
  // remettre le cours au propre avec l'IA
  'barra1.non-trovo-trascrizione-di': 'Je ne trouve pas de transcription de **{corso}**.',
  'barra1.non-trovo-trascrizione': 'Je ne trouve pas de cours transcrit. En cours, appuie sur **Transcrire le cours**.',
  'barra1.riordinare-serve-ai': "Pour mettre au propre, il faut l'IA : installe le **cerveau local** depuis « Prépare Lode » (gratuit, hors ligne) ou connecte ton IA : écris « IA ».",
  'barra1.riordino': 'Je mets {corso} au propre…',
  'barra1.riordino-per-cento': 'Je mets {corso} au propre… {n} %',
  'barra1.errore-riordinare': "Je n'ai pas réussi à mettre au propre : {errore}",
  'barra1.salvare-riordinati': 'Enregistrer les notes au propre de {corso} ?',
  'barra1.appunti-salvati': 'Notes enregistrées dans la note.',
  'barra1.sintesi-lezione-riordinata': 'cours mis au propre',
  'barra1.detto-definizioni-lezione': 'Définitions du cours',
  // « Répète » et l'autorisation d'écouter le cours
  'barra1.ascoltare-lezione': 'Écouter le cours ?',
  'barra1.consenso-ripeti': "je garde en mémoire seulement la dernière minute et demie, jamais sur le disque",
  'barra1.trascrivi': 'Transcrire',
  'barra1.consenso-trascrivi': "j'écris le cours dans la note, le son n'est pas enregistré",
  'barra1.dove': 'Où',
  'barra1.consenso-dove': "tout sur l'ordinateur, rien sur internet",
  'barra1.consenso-nota': "Enregistrer un cours dépend du règlement de ta fac et de l'enseignant : demande avant.",
  'barra1.solo-la-prima-volta': 'Je te le demande seulement la première fois.',
  'barra1.d-accordo': "D'accord.",
  'barra1.ripeti-app': "« Répète » est dans l'**appli de bureau** de Lode.",
  'barra1.ripeti-e-attivo': 'Répète est actif.',
  'barra1.ripeti-attivo-nota': "Je garde en mémoire la dernière minute et demie, jamais sur le disque. Tu as raté quelque chose ? {tasti} ou « répète ».",
  'barra1.ripeti-attivo-nota-fuori': "Je garde en mémoire la dernière minute et demie, jamais sur le disque. Tu as raté quelque chose ? {tasti} ou « répète ». En dehors des heures de cours, je reste allumé 3 heures au maximum.",
  'barra1.detto-spegni-ripeti': 'Désactive Répète',
  'barra1.sintesi-ripeti-attivo': 'répète actif',
  'barra1.ripeti-spento': 'Répète éteint.',
  'barra1.microfono-resta': "Le micro reste allumé pour la transcription, jusqu'à ce que tu l'arrêtes.",
  'barra1.microfono-chiuso': 'Le micro est fermé.',
  'barra1.non-si-accende-piu': " En cours, il ne s'allume plus tout seul : rallume-le avec {tasti}.",
  'barra1.ripeti-e-spento': 'Répète est éteint.',
  'barra1.ripeti-e-spento-nota': "Répète t'écrit ce que le prof a dit dans les 60 dernières secondes : allume-le ici ou avec {tasti}. Si tu voulais autre chose, demande-le-moi avec tes mots.",
  'barra1.accendi': 'Allumer',
  'barra1.detto-accendi-ripeti': 'Allume Répète',
  'barra1.sintesi-ripeti-spento': 'répète éteint',
  'barra1.ascolto-da-un-attimo': "J'écoute depuis peu : je n'ai encore rien à te répéter.",
  'barra1.riascolto': { one: 'Je réécoute la dernière seconde…', other: 'Je réécoute les {n} dernières secondes…' },
  'barra1.errore-riascoltare': "Je n'ai pas réussi à réécouter : {errore}",
  'barra1.niente-sentito': "Dans les 60 dernières secondes, je n'ai entendu personne parler.",
  'barra1.ultimi-secondi-ora': { one: 'La dernière seconde · {ora}', other: 'Les {n} dernières secondes · {ora}' },
  'barra1.agli-appunti': 'Dans les notes',
  'barra1.copia': 'Copier',
  'barra1.copiato': 'Copié',
  'barra1.negli-appunti-di': 'Dans les notes de {corso}.',
  // partager la transcription
  'barra1.sbobine-app': "Les transcriptions se partagent depuis l'**appli de bureau**.",
  'barra1.non-trovo-lezione-di': 'Je ne trouve pas de cours de **{corso}** à partager.',
  'barra1.non-trovo-lezione': "Je ne trouve pas de cours à partager : transcris-le ou mets-le au propre d'abord.",
  'barra1.preparo-sbobina': 'Je prépare la transcription…',
  'barra1.sbobina-pronta': 'Transcription de {corso} prête.',
  'barra1.scegli-dove': "Choisis où l'envoyer : AirDrop, Messages, Mail…",
  'barra1.mostra': 'Afficher',
  'barra1.sintesi-sbobina-condivisa': 'transcription partagée',
  'barra1.errore-sbobina': "Je n'arrive pas à préparer la transcription : {errore}",
  // les cartes pour Anki
  'barra1.anki-non-trovo-di': 'Je ne trouve ni cartes ni définitions de **{corso}** à exporter.',
  'barra1.anki-non-trovo': "Je n'ai pas encore de cartes ni de définitions à exporter : note quelques définitions en cours (« déf : gradient = … ») ou crée des cartes à partir d'un PDF.",
  'barra1.anki-carte-mazzi': { one: '{n} carte pour Anki, {mazzi} paquets.', other: '{n} cartes pour Anki, {mazzi} paquets.' },
  'barra1.anki-carte-mazzo': { one: '{n} carte pour Anki dans le paquet {mazzo}.', other: '{n} cartes pour Anki dans le paquet {mazzo}.' },
  'barra1.anki-doppioni': { one: ' {n} doublon ignoré.', other: ' {n} doublons ignorés.' },
  'barra1.anki-importa-download': 'Dans Anki : Fichier › Importer, choisis « {file} » (il est dans les téléchargements) et comme type de note « Basique » (« Basic » en anglais).',
  'barra1.anki-importa-vault': 'Dans Anki : Fichier › Importer, choisis « {file} » dans le coffre et comme type de note « Basique » (« Basic » en anglais).',
  'barra1.scarica': 'Télécharger',
  'barra1.sintesi-anki': 'cartes pour Anki',
  'barra1.errore-mostrare': "Je n'arrive pas à afficher le fichier : {errore}",
  'barra1.errore-anki': "Je n'arrive pas à enregistrer le fichier pour Anki : {errore}",
  // les fichiers déposés sur la pastille
  'barra1.tipo-pdf': 'PDF',
  'barra1.tipo-slide': 'diapos PowerPoint',
  'barra1.tipo-word': 'document Word',
  'barra1.tipo-testo': 'texte',
  'barra1.tipo-sbobina': 'transcription de Lode',
  'barra1.tipo-carte': 'cartes (Anki/CSV)',
  'barra1.tipo-foto': 'photo',
  'barra1.tipo-audio': 'enregistrement audio',
  'barra1.tipo-altro': 'fichier',
  'barra1.uno-alla-volta': { one: "Un à la fois : je commence par **{nome}**, puis dépose l'autre.", other: 'Un à la fois : je commence par **{nome}**, puis dépose les {n} autres.' },
  'barra1.errore-leggere-file': "Je n'arrive pas à lire le fichier : {errore}",
  'barra1.serve-ai': 'il faut le cerveau local ou ton IA',
  'barra1.serve-app': "dans l'appli de bureau",
  'barra1.op-sbobina': 'Ajouter à mon coffre',
  'barra1.op-sbobina-d': 'Devient un cours dans ton Obsidian : définitions et ★ entrent dans les jeux',
  'barra1.op-allega-soltanto': 'Joindre seulement',
  'barra1.op-allega-soltanto-d': "J'enregistre le fichier dans les pièces jointes du cours",
  'barra1.op-importa-carte': 'Importer les cartes',
  'barra1.op-importa-carte-d': 'Une par ligne : question, puis Tab, « ; » ou « = », puis réponse',
  'barra1.op-audio': "Transcrire l'enregistrement",
  'barra1.op-audio-d': 'Tout le cours en notes, formules comprises, dans la note du cours',
  'barra1.op-allega': 'Joindre au cours',
  'barra1.op-allega-audio-d': "J'enregistre le son dans les pièces jointes, avec le lien dans la note",
  'barra1.op-lavagna': 'Transcrire en notes',
  'barra1.op-lavagna-d': 'Texte et formules en LaTeX, dans la note du cours',
  'barra1.op-carte': 'Cartes de révision',
  'barra1.op-carte-foto-d': "Les questions qu'on te poserait à l'examen",
  'barra1.op-allega-foto-d': 'La photo dans la note du cours',
  'barra1.op-carte-d': 'Questions et réponses pour la révision espacée',
  'barra1.op-riassunto': 'Résumé dans Obsidian',
  'barra1.op-riassunto-d': 'Des notes au propre avec les formules, dans une nouvelle note',
  'barra1.op-definizioni': 'Définitions pour les jeux',
  'barra1.op-definizioni-d': "Je les ajoute au cours : elles deviennent des jeux de mémoire",
  'barra1.op-orale': 'Interroge-moi là-dessus',
  'barra1.op-orale-d': "Un prof d'oral qui pose des questions sur ce document",
  'barra1.op-allega-d': "J'enregistre le fichier avec le lien dans la note",
  'barra1.op-crocette': 'QCM',
  'barra1.op-crocette-d': "Des questions à 4 réponses, comme à l'écrit : entraînement ou simulation d'examen",
  'barra1.op-temi': 'Annales',
  'barra1.op-temi-d': "Les exercices d'un ancien sujet, classés par chapitre, un par jour dans le plan",
  'barra1.op-programma': "C'est le programme de l'examen",
  'barra1.op-programma-d': "Je le découpe en chapitres et je te prépare le plan jusqu'à l'examen",
  'barra1.op-domande': 'Questions tombées aux examens',
  'barra1.op-domande-d': 'Je les range sous leurs chapitres : ceux qui tombent le plus montent dans le plan',
};
