// Textes de la barre, troisième partie (français) : révisions de poche, Moodle, QCM, annales, examen blanc, programme de
// l'examen, « je t'explique », envoi, fichiers, voix, raccourcis et notifications de l'appli (js/lode.js).
export default {
  // Révisions de poche
  'barra3.tasca-solo-app': "Les révisions de poche sont dans l'appli : il faut le coffre Obsidian.",
  'barra3.tasca-spenta': 'Révisions de poche seulement quand tu les demandes.',
  'barra3.tasca-spenta-nota': 'La note {nota} reste dans le coffre : écris « révisions de poche » pour la mettre à jour.',
  'barra3.tasca-spenta-sintesi': 'révisions de poche désactivées',
  'barra3.tasca-preparo': 'Je prépare la note…',
  'barra3.tasca-errore': "Je n'arrive pas à lire ou à écrire la note {nota} : {errore}",
  'barra3.tasca-estranea': "Dans le coffre, il y a déjà une note **{nota}** que Lode n'a pas écrite : je n'y touche pas. Renomme-la et réessaie.",
  'barra3.tasca-segnata-sapevi': "J'ai noté la carte que tu as faite sur le téléphone : tu la savais.",
  'barra3.tasca-segnata-non-sapevi': "J'ai noté la carte que tu as faite sur le téléphone : tu ne la savais pas.",
  'barra3.tasca-segnate': "J'ai noté {n} cartes que tu as faites sur le téléphone : {sapevo} sues, {no} non.",
  'barra3.tasca-gia': { one: "Tu avais déjà révisé une carte sur l'ordinateur : je ne la compte pas deux fois.", other: "Tu avais déjà révisé {n} cartes sur l'ordinateur : je ne les compte pas deux fois." },
  'barra3.tasca-vecchia': "La note sur le téléphone vient d'un ancien tour : je ne note rien.",
  'barra3.tasca-cambiata': "La note est encore en train de changer : Obsidian la synchronise. Je ne la réécris pas maintenant, réessaie dans une minute.",
  'barra3.tasca-domani': { one: 'Dans la note {nota}, il y a {n} carte pour demain.', other: 'Dans la note {nota}, il y a {n} cartes pour demain.' },
  'barra3.tasca-domani-niente': "Demain, tu n'as aucune carte à réviser : la note {nota} le dit.",
  'barra3.tasca-titolo': 'Révisions de poche',
  'barra3.tasca-aspetta': "Attends que le téléphone ait fini de synchroniser et réessaie. Si la bonne note n'arrive pas, réécris-la : je ne compte pas les cases cochées de cette copie.",
  'barra3.apri-nota': 'Ouvrir la note',
  'barra3.riscrivi-nota': 'Réécrire la note',
  'barra3.tasca-solo-quando': 'Seulement quand je le demande',
  'barra3.tasca-ogni-sera': 'Chaque soir',
  'barra3.tasca-sera-accesa': 'Chaque soir après 19 h, je la réécris toute seule, si Lode est ouvert.',
  'barra3.tasca-sera-spenta': 'Je la réécris seulement quand tu me le demandes.',
  'barra3.tasca-come-arriva': "Ça marche si le coffre arrive sur le téléphone (iCloud, Obsidian Sync, Syncthing). Lode n'utilise pas le réseau : c'est le service que tu utilises déjà qui apporte la note.",
  'barra3.non-apro-nota': "Je n'arrive pas à ouvrir la note : {errore}",
  'barra3.tasca-riscrivi-detto': 'Réécris la note {nota}',
  'barra3.tasca-sintesi': 'révisions de poche',

  // Moodle
  'barra3.moodle-solo-app': "La connexion à Moodle est dans l'**appli de bureau** de Lode.",
  'barra3.moodle-non-risponde': 'Moodle ne répond pas : {errore}',
  'barra3.moodle-non-collegato': "Moodle n'est pas connecté.",
  'barra3.moodle-scollegato': 'Moodle déconnecté.',
  'barra3.moodle-scollegato-nota': 'Le jeton est effacé de cet ordinateur. Les fichiers déjà récupérés restent dans ton coffre.',
  'barra3.moodle-corsi-seguiti': { one: '{n} cours suivi : {corsi}', other: '{n} cours suivis : {corsi}' },
  'barra3.file-nuovi': 'Nouveaux fichiers',
  'barra3.scadenze': 'Échéances',
  'barra3.corsi': 'Cours',
  'barra3.scollega': 'Déconnecter',
  'barra3.moodle-senza-portachiavi': "Cet ordinateur n'a pas de trousseau : la connexion dure jusqu'à ce que tu fermes Lode.",
  'barra3.moodle-novita-detto': 'Quoi de neuf sur Moodle',
  'barra3.moodle-corsi-detto': 'Mes cours sur Moodle',
  'barra3.moodle-scollega-detto': 'Déconnecte Moodle',
  'barra3.moodle-collega': 'Connecter Moodle',
  'barra3.moodle-collega-intro': "La plateforme de cours de ta fac (Moodle, e-campus, plateforme pédagogique…) : Lode récupère les nouveaux fichiers et les échéances des cours que tu choisis. Lecture seule : il ne rend rien et n'écrit rien.",
  'barra3.moodle-indirizzo-esempio': 'Adresse, par exemple moodle.univ-ville.fr',
  'barra3.moodle-indirizzo': 'Adresse de Moodle',
  'barra3.continua': 'Continuer',
  'barra3.moodle-collega-nota': "Tu te connectes comme dans l'appli Moodle officielle. La connexion reste chiffrée sur cet ordinateur, jamais dans le coffre ; avec « déconnecte moodle », tu l'enlèves.",
  'barra3.moodle-cerco': 'Je cherche le site…',
  'barra3.moodle-non-indirizzo': 'Ça ne ressemble pas à une adresse.',
  'barra3.moodle-non-trovo': "Je ne trouve pas de Moodle avec l'appli activée à cette adresse ({motivo}). Copie l'adresse depuis la barre du navigateur quand tu es sur la page de tes cours.",
  'barra3.moodle-accesso-annullato': 'Connexion annulée.',
  'barra3.moodle-accesso-fallito': 'Connexion échouée : {motivo}.',
  'barra3.moodle-entra-sso': "<b>{nome}</b> · on se connecte avec les identifiants de la fac (ENT ou compte universitaire), dans une fenêtre de Lode.",
  'barra3.accedi': 'Se connecter',
  'barra3.moodle-accedi-finestra': "Connecte-toi dans la fenêtre qui s'est ouverte…",
  'barra3.moodle-entra-password': '<b>{nome}</b> · connexion avec identifiant et mot de passe Moodle.',
  'barra3.utente': 'Identifiant',
  'barra3.password': 'Mot de passe',
  'barra3.moodle-password-nota': "Le mot de passe va seulement à Moodle : Lode ne l'enregistre pas.",
  'barra3.moodle-collega-sintesi': 'connecter Moodle',
  'barra3.moodle-leggo-corsi': 'Je lis tes cours…',
  'barra3.moodle-corsi-errore': "Je n'arrive pas à lire les cours : {errore}",
  'barra3.moodle-nessun-corso': "Sur Moodle, tu n'es inscrit à aucun cours.",
  'barra3.moodle-corsi-titolo': 'Cours Moodle · {sito}',
  'barra3.moodle-scegli-corsi': 'Choisis lesquels suivre et avec quel cours de Lode : leurs nouveaux fichiers arrivent ici.',
  'barra3.concluso': 'terminé',
  'barra3.moodle-corso-per': 'Cours de Lode pour {nome}',
  'barra3.non-seguire': 'Ne pas suivre',
  'barra3.moodle-con-nome': 'Avec le nom Moodle',
  'barra3.salva': 'Enregistrer',
  'barra3.moodle-seguo': { one: 'Je suis {n} cours sur Moodle.', other: 'Je suis {n} cours sur Moodle.' },
  'barra3.moodle-nessuno-seguito': 'Aucun cours suivi.',
  'barra3.moodle-ti-avviso': "Je te préviens quand de nouveaux fichiers arrivent.",
  'barra3.moodle-corsi-sintesi': 'cours Moodle',
  'barra3.moodle-guardo': 'Je regarde les fichiers sur Moodle…',
  'barra3.moodle-non-leggo': "Je n'arrive pas à lire {corsi} : {errore}.",
  'barra3.moodle-nessun-file': "Il n'y a pas encore de fichiers dans les cours que tu suis.",
  'barra3.moodle-piu-recenti': 'les fichiers les plus récents',
  'barra3.moodle-file-nuovi': { one: '{n} nouveau fichier', other: '{n} nouveaux fichiers' },
  'barra3.moodle-niente-nuovo': 'rien de nouveau, les derniers fichiers',
  'barra3.nuovo': 'nouveau',
  'barra3.apri': 'Ouvrir',
  'barra3.moodle-apri-nota': "« Ouvrir » l'apporte dans Lode comme si tu l'avais glissé : cartes, résumé, programme, QCM.",
  'barra3.scarico': 'Je télécharge…',
  'barra3.non-riesco': "Je n'y arrive pas",
  'barra3.aperto': 'Ouvert',
  'barra3.moodle-file-da': '{nome} depuis Moodle',
  'barra3.file-illeggibile': "Je n'arrive pas à lire le fichier : {errore}",
  'barra3.moodle-sintesi-nuovi': 'Moodle : {n} nouveaux fichiers',
  'barra3.moodle-nessuna-scadenza': 'Aucune échéance sur Moodle dans les prochaines semaines.',
  'barra3.moodle-scadenze-titolo': 'Échéances sur Moodle',
  'barra3.scadenze-sintesi': '{n} échéances',
  'barra3.guarda': 'Voir',

  // QCM
  'barra3.non-trovo-esame': "Je ne trouve pas l'examen **{nome}**.",
  'barra3.il-tuo-materiale': 'tes documents',
  'barra3.quiz-poco-materiale': "Pour un QCM sur **{nome}**, il me faut plus de matière : glisse le polycopié ou les diapos (choisis « QCM »), ou crée quelques cartes.",
  'barra3.quiz-senza-ai': "Pour le QCM sans IA, il me faut au moins 4 cartes ou 4 définitions de **{nome}**. Avec l'IA (écris « IA »), je le fais aussi à partir du polycopié.",
  'barra3.quiz-fonte-dispensa-nome': 'Questions tirées du polycopié « {nome} ».',
  'barra3.quiz-fonte-dispensa': 'Questions tirées du polycopié.',
  'barra3.quiz-fonte-ai': 'Questions tirées de tes cartes, de tes définitions et des questions tombées.',
  'barra3.quiz-fonte-carte-definizioni': 'Questions tirées de tes cartes et de tes définitions.',
  'barra3.quiz-fonte-carte': 'Questions tirées de tes cartes.',
  'barra3.quiz-fonte-definizioni': 'Questions tirées de tes définitions.',
  'barra3.quiz-le-scrive': "C'est {motore} qui les écrit : je garde seulement celles que les documents prouvent.",
  'barra3.quiz-sbagliate-altre': "Les mauvaises réponses viennent d'autres cartes du cours.",
  'barra3.quiz-titolo': 'QCM · {nome}',
  'barra3.quiz-allenamento': 'Entraînement · {n} questions',
  'barra3.quiz-allenamento-sotto': "La correction tout de suite, avec l'explication",
  'barra3.quiz-simulazione': "Simulation d'examen · {n} questions en {n} minutes",
  'barra3.quiz-simulazione-sotto': "Comme à l'écrit : le temps file, la correction à la fin, la note sur 30",
  'barra3.quiz-simulazione-detto': "Simulation d'examen · {nome}",
  'barra3.quiz-detto': 'QCM · {nome}',
  'barra3.quiz-capo-simulazione': 'Simulation · {nome}',
  'barra3.quiz-preparo': 'Je prépare les questions… {fatte} sur {n}',
  'barra3.quiz-errore': "Je n'arrive pas à préparer les questions : {errore}",
  'barra3.quiz-niente': "Je n'ai pas réussi à préparer des questions fiables à partir de ces documents.",
  'barra3.quiz-sintesi': 'QCM de {nome}',
  'barra3.quiz-conto-sim': '{tempo} · {fatte} sur {n}',
  'barra3.x-di-n': '{x} sur {n}',
  'barra3.quiz-domanda-n': 'Question {x} sur {n}',
  'barra3.indietro': 'Retour',
  'barra3.salta': 'Passer',
  'barra3.lascia-vuota': 'Laisser vide',
  'barra3.consegna': 'Rendre',
  'barra3.quiz-giusta-e': 'La bonne réponse est la {lettera}.',
  'barra3.avanti': 'Suivant',
  'barra3.risultato': 'Résultat',
  'barra3.tasto-invio': 'Entrée',
  'barra3.quiz-voto': 'Note : <em>{voto}</em>',
  'barra3.tempo-scaduto': 'temps écoulé',
  'barra3.quiz-tutte-giuste': 'Tout juste.',
  'barra3.quiz-da-rivedere': { one: '{n} à revoir.', other: '{n} à revoir.' },
  'barra3.quiz-scartate': { one: "{n} question écartée parce que les documents ne la prouvaient pas", other: "{n} questions écartées parce que les documents ne les prouvaient pas" },
  'barra3.da-rivedere': 'À revoir',
  'barra3.lasciata-vuota': 'Laissée vide',
  'barra3.hai-scelto': 'Tu as choisi : {x}',
  'barra3.giusta-era': 'Bonne réponse : {x}',
  'barra3.quiz-sbagliate-carte': 'Les fausses deviennent des cartes',
  'barra3.quiz-un-altro': 'Un autre QCM',
  'barra3.quiz-punti': 'Une bonne réponse vaut 1 point, une fausse ou vide 0.',
  'barra3.quiz-regole-vere': "Le vrai écrit peut avoir d'autres règles (points négatifs pour les fausses, seuils) : c'est un entraînement.",
  'barra3.quiz-carte-aggiunte': { one: "{n} carte ajoutée : elle revient aujourd'hui dans la révision", other: "{n} cartes ajoutées : elles reviennent aujourd'hui dans la révision" },
  'barra3.quiz-sintesi-esito': 'QCM de {nome} : {giuste} sur {n}',

  // annales
  'barra3.tema-del': 'du {data}',
  'barra3.tema-di': 'de « {fonte} »',
  'barra3.tema-es': 'ex. {es}',
  'barra3.tema-es-da': 'ex. {es} {da}',
  'barra3.tema-circa': 'environ {min} min sur papier',
  'barra3.leggo-file': 'Je lis {nome}…',
  'barra3.cmd-temi-di': '« annales de {nome} : »',
  'barra3.cmd-temi': '« annales : »',
  'barra3.temi-scansione': "Ce PDF a l'air d'être un scan : sans IA, je ne lis pas les images. Colle le texte des exercices avec {cmd} et le texte en dessous.",
  'barra3.temi-illeggibile': "Je n'arrive pas à lire le texte de ce fichier. Colle-le avec {cmd} et le texte en dessous.",
  'barra3.aggiungi-prima-esame': "Ajoute d'abord l'examen, par exemple : « examen analyse 2 le 15 janvier 9 ects ».",
  'barra3.non-trovo-esame-aggiungi': "Je ne trouve pas l'examen **{nome}**. Ajoute-le d'abord, par exemple : « examen {nome} le 15 janvier 9 ects ».",
  'barra3.aggiungi-esame-compito': "Ajoute d'abord un examen, par exemple : « examen analyse 2 le 15 janvier 9 ects ». Ensuite, colle un ancien sujet.",
  'barra3.prova-invito': 'Tu veux essayer un sujet entier, en temps réel ?',
  'barra3.prova-generale': 'Examen blanc',
  'barra3.prova-generale-di': 'Examen blanc de {nome}',
  'barra3.temi-titolo': 'Annales · {nome}',
  'barra3.temi-nessuno-oggi': "Aucun exercice prévu aujourd'hui.",
  'barra3.temi-prossimo': 'Le prochain revient {data}.',
  'barra3.temi-vuoto': "Colle le texte d'un ancien sujet (ceux qui circulent dans le groupe de la promo ou sur le site du prof), ou glisse le PDF. Je le découpe en exercices, je les range sous leurs chapitres et chaque jour je t'en propose un.",
  'barra3.temi-segnaposto': 'Exercice 1. Calculer…&#10;Exercice 2. Étudier…',
  'barra3.temi-testo-compito': 'Texte du sujet',
  'barra3.temi-dividi': 'Découper en exercices',
  'barra3.temi-di': 'Annales de {nome}',
  'barra3.temi-di-sintesi': 'annales de {nome}',
  'barra3.temi-nessun-esercizio': "Je n'ai pas trouvé d'exercices dans ce texte.",
  'barra3.temi-compito-del': 'sujet {data}',
  'barra3.temi-un-pezzo': "Je n'ai pas trouvé « Exercice 1 », « Exercice 2 »… Si le sujet a plusieurs exercices, écris-les avec ces marques et colle-le de nouveau.",
  'barra3.temi-senza-programma': "Pour {nome}, il n'y a pas encore de programme : je les enregistre sans chapitre.",
  'barra3.temi-metti': 'Les mettre dans le plan',
  'barra3.temi-es': 'Ex. {n}',
  'barra3.temi-con-soluzione': 'avec le corrigé du prof',
  'barra3.temi-argomento-di': "Chapitre de l'exercice {n}",
  'barra3.temi-che-argomento': 'Quel chapitre ?',
  'barra3.temi-unisci': 'Fusionner avec le précédent',
  'barra3.togli': 'Enlever',
  'barra3.temi-nel-piano': { one: '{n} exercice dans le plan.', other: '{n} exercices dans le plan.' },
  'barra3.temi-nel-piano-arg': { one: '{n} exercice dans le plan : {con} avec son chapitre, {senza} sans.', other: '{n} exercices dans le plan : {con} avec leur chapitre, {senza} sans.' },
  'barra3.temi-senza-programma-nota': 'Sans programme, je ne sais pas où les mettre : colle le programme de {nome} et je les range.',
  'barra3.temi-doppi': { one: '{n} y était déjà.', other: '{n} y étaient déjà.' },
  'barra3.temi-ogni-giorno': 'Chaque jour, un exercice sur les chapitres du plan.',
  'barra3.programma': 'Programme',
  'barra3.fanne-uno': 'Fais-en un',
  'barra3.esercizio-di': 'Exercice de {nome}',
  'barra3.temi-gia': 'Ces exercices y étaient déjà.',
  'barra3.temi-sintesi-n': { one: 'annales de {nome} : {n} exercice', other: 'annales de {nome} : {n} exercices' },
  'barra3.tema-titolo': 'Exercice · {nome}',
  'barra3.tema-fallo': "Fais-le sur papier, sans regarder tes notes. Quand tu as fini :",
  'barra3.giusto': 'Juste',
  'barra3.sbagliato': 'Faux',
  'barra3.non-sapevo': 'Je ne savais pas par où commencer',
  'barra3.tema-voto-tuo': "C'est toi qui te notes : Lode ne corrige pas l'exercice.",
  'barra3.tema-torna': { one: 'Il revient dans {n} jour.', other: 'Il revient dans {n} jours.' },
  'barra3.tema-guarda-soluzione': 'Regarde le corrigé et refais-le depuis le début, ne te contente pas de le relire.',
  'barra3.tema-rileggi': 'Relis le chapitre et refais-le depuis le début, sans regarder.',
  'barra3.tema-prima-rileggi-arg': "D'abord, relis le chapitre : {arg}.",
  'barra3.tema-prima-rileggi': "D'abord, relis le chapitre.",
  'barra3.tema-vedi-soluzione': 'Voir le corrigé du prof',
  'barra3.tema-altro': 'Un autre exercice',
  'barra3.esercizio-di-esito': 'exercice de {nome} : {esito}',
  'barra3.esercizio-di-sintesi': 'exercice de {nome}',

  // examen blanc
  'barra3.prova-prima-compiti': "Colle ou glisse d'abord les anciens sujets : « annales de {nome} : … ».",
  'barra3.prova-compito-del': 'Sujet du {data}',
  'barra3.prova-scelti': 'Exercices choisis par toi',
  'barra3.prova-compito-fonte': 'Sujet « {fonte} »',
  'barra3.prova-compito-incollato': 'Sujet collé',
  'barra3.n-esercizi': { one: '{n} exercice', other: '{n} exercices' },
  'barra3.n-punti': '{punti} points',
  'barra3.prova-titolo': 'Examen blanc · {nome}',
  'barra3.prova-quanto-dura': 'Ça dure combien ?',
  'barra3.prova-minuti-aria': "Combien de minutes dure l'examen blanc",
  'barra3.minuti': 'minutes',
  'barra3.prova-altro-compito': 'Un autre sujet',
  'barra3.prova-gia-fatto': 'déjà fait le {data}',
  'barra3.comincio': 'Je commence',
  'barra3.prova-su-carta': "Sur papier, sans notes, comme à l'examen. Tu vois les corrigés à la fin.",
  'barra3.prova-durata-letta': "Je l'ai lu dans le sujet.",
  'barra3.prova-di-solito': "D'habitude, 2 heures.",
  'barra3.prova-sintesi': 'examen blanc de {nome}',
  'barra3.prova-scegli': 'Je ne trouve pas de sujet entier : choisis toi-même les exercices.',
  'barra3.prova-scegli-nota': '120 minutes, sur papier, sans notes. Tu vois les corrigés à la fin.',
  'barra3.prova-ferma-pausa': "Il y a une pause en cours : je l'arrête et je lance l'examen blanc ?",
  'barra3.prova-ferma-focus': "Il y a un focus en cours : je l'arrête et je lance l'examen blanc ?",
  'barra3.si-parti': 'Oui, lance',
  'barra3.no': 'Non',
  'barra3.prova-durata-fino': "{min} minutes, jusqu'à {ora}",
  'barra3.esercizio-n': 'Exercice {n}',
  'barra3.prova-passo': 'Je passe au suivant',
  'barra3.consegno': 'Je rends',
  'barra3.lascio-perdere': "J'abandonne",
  'barra3.prova-nota-tempo': "Le temps défile dans la pastille. « Je passe au suivant » est facultatif : ça note combien de temps tu passes sur chaque exercice.",
  'barra3.prova-lascio-chiede': "J'abandonne ? Je ne note rien : ni les exercices ni le sujet.",
  'barra3.si-lascio': "Oui, j'abandonne",
  'barra3.no-continuo': 'Non, je continue',
  'barra3.prova-lasciata': "Abandonné : je n'ai rien noté. Quand tu veux le refaire, écris « examen blanc de {nome} ».",
  'barra3.prova-consegnato': "Rendu. Prends ta copie et, pour chaque exercice, dis-moi comment ça s'est passé.",
  'barra3.prova-come-andato': "Comment s'est passé l'exercice {n}",
  'barra3.prova-esito-tuo': "Lode ne corrige pas : c'est toi qui choisis le résultat.",
  'barra3.prova-sintesi-esito': 'examen blanc de {nome} : {fatti} sur {n}',
  'barra3.prova-sintesi-come': "examen blanc de {nome} : comment ça s'est passé",

  // programme de l'examen
  'barra3.aggiungi-esame-programma': "Ajoute d'abord un examen, par exemple : « examen analyse 2 le 15 janvier 9 ects ». Ensuite, colle son programme.",
  'barra3.programma-titolo': 'Programme · {nome}',
  'barra3.programma-vuoto': "Colle le programme du cours (depuis la page du cours ou le PDF), ou glisse le fichier ici. Je le découpe en chapitres, je te montre ce que tu sais déjà et je te prépare le plan jusqu'à l'examen.",
  'barra3.programma-segnaposto': '1. Limites et continuité&#10;2. Dérivées : définition, règles, théorèmes de Rolle et des accroissements finis&#10;…',
  'barra3.programma-del-corso': 'Programme du cours',
  'barra3.programma-leggi': 'Lire le programme',
  'barra3.programma-di': 'Programme de {nome}',
  'barra3.programma-da-moodle': 'Le prendre sur Moodle',
  'barra3.programma-moodle-vuota': 'Sur Moodle, la description est vide',
  'barra3.programma-di-moodle': 'Programme de {nome} depuis Moodle',
  'barra3.programma-sintesi': 'programme de {nome}',
  'barra3.programma-leggo': 'Je lis le programme…',
  'barra3.programma-niente': "Je n'arrive pas à tirer les chapitres de ce texte. Colle-les un par ligne, numérotés si possible.",
  'barra3.programma-salvo': { one: "{n} chapitre pour {nome} : je l'enregistre ?", other: '{n} chapitres pour {nome} : je les enregistre ?' },
  'barra3.programma-letti-da': "C'est {motore} qui les a lus : vérifie qu'ils y sont tous.",
  'barra3.programma-se-non-torna': 'Si quelque chose cloche, colle de nouveau le programme corrigé.',
  'barra3.programma-stesso-nome': 'Les chapitres qui gardent le même nom gardent leurs questions et leurs résultats.',
  'barra3.programma-cuscinetto': "Aujourd'hui, c'est le jour tampon : rattrape ce qui est resté en retard, ou repose-toi.",
  'barra3.programma-ultimo': 'Dernier jour : révision générale. Les questions tombées et les points faibles : {cosa}.',
  'barra3.tutto-il-programma': 'tout le programme',
  'barra3.studia': 'Étudier',
  'barra3.ripassa': 'Réviser',
  'barra3.cuscinetto': 'tampon',
  'barra3.ripasso-generale': 'révision générale',
  'barra3.percento-pronto': 'prêt à {p} %',
  'barra3.oggi': "Aujourd'hui",
  'barra3.esercizio-di-oggi': "Exercice du jour",
  'barra3.fallo-adesso': 'Le faire maintenant',
  'barra3.interrogami-questi': 'Interroge-moi là-dessus',
  'barra3.focus': 'Focus',
  'barra3.da-rivedere-piccolo': 'à revoir',
  'barra3.uscita-volte': { one: 'tombée {n} fois', other: 'tombée {n} fois' },
  'barra3.fatto-oggi': "fait aujourd'hui",
  'barra3.lo-spiego-io': "C'est moi qui explique",
  'barra3.interrogami': 'Interroge-moi',
  'barra3.prossimi-giorni': 'Les prochains jours',
  'barra3.senza-data-appello': "(sans date d'examen : plan sur deux semaines)",
  'barra3.domande-appelli': 'Questions tombées aux examens',
  'barra3.n-senza-argomento': { one: '{n} sans chapitre', other: '{n} sans chapitre' },
  'barra3.domande-segnaposto': 'Une par ligne : celles qui circulent dans le groupe de la promo',
  'barra3.domande-uscite': 'Questions tombées',
  'barra3.aggiungi': 'Ajouter',
  'barra3.domande-senza-argomento': 'Je ne sais pas de quel chapitre elles sont : {lista}',
  'barra3.programma-nota': "Le plan se refait chaque jour à partir de ce que tu sais : notes, cartes, révisions et interrogations. D'abord les chapitres faibles et ceux qui tombent le plus ; chaque nouveau chapitre revient quelques jours plus tard.",
  'barra3.interrogami-oggi': "Interroge-moi sur les chapitres d'aujourd'hui",
  'barra3.interrogami-su': 'Interroge-moi sur {x}',
  'barra3.te-lo-spiego-su': "Je t'explique : {x}",
  'barra3.programma-sintesi-pronto': 'programme de {nome} : prêt à {p} %',
  'barra3.domande-nessuna': "Je n'ai pas trouvé de questions : écris-en une par ligne.",
  'barra3.domande-salvate': { one: '{n} question enregistrée.', other: '{n} questions enregistrées.' },
  'barra3.domande-incolla-programma': 'Colle aussi le programme : je les range sous leurs chapitres.',
  'barra3.domande-aggiunte': { one: '{n} question ajoutée.', other: '{n} questions ajoutées.' },
  'barra3.domande-senza': { one: '{n} sans chapitre : je ne comprends pas de quel chapitre elle parle.', other: '{n} sans chapitre : je ne comprends pas de quel chapitre elles parlent.' },
  'barra3.domande-salgono': 'Les chapitres qui tombent le plus montent dans le plan.',
  'barra3.domande-uscite-sintesi': 'questions tombées',

  // je t'explique et l'oral sur le programme
  'barra3.spiego-titolo': "Je t'explique · {nome}",
  'barra3.spiego-istruzioni': "Explique-le comme à l'oral, avec tes mots : écris ci-dessous ou maintiens {tasti} et parle. Quand tu as fini, envoie.",
  'barra3.spiego-risponde': "C'est {motore} qui te répond, avec tes notes.",
  'barra3.spiego-controllo': { one: 'Je vérifie {n} point tiré du programme et de tes notes : je ne te le montre pas avant.', other: 'Je vérifie {n} points tirés du programme et de tes notes : je ne te les montre pas avant.' },
  'barra3.spiego-senza-appunti': "Pour ce chapitre, je n'ai pas de notes : sans IA, je peux seulement noter que tu l'as révisé.",
  'barra3.spiego-esci': 'Écris « quitte » pour laisser tomber.',
  'barra3.spiego-segnaposto': 'Ton explication…',
  'barra3.spiego-sintesi': "j'explique {x}",
  'barra3.chiedi-o-scrivi': 'Demande ou écris une commande…',
  'barra3.spiego-ascolto': "J'écoute l'explication…",
  'barra3.mancava': 'Il manquait : {cosa}',
  'barra3.spiego-errore': "Je n'arrive pas à l'évaluer maintenant : {errore}",
  'barra3.spiego-segnato': 'Noté : tu as révisé {x}.',
  'barra3.spiego-controllo-vero': "Pour une vraie vérification, il faut des notes sur ce chapitre, ou l'IA.",
  'barra3.punti-su': '{x} points sur {n}',
  'barra3.spiego-parole-chiave': "Je vérifie les mots-clés, pas le raisonnement : si tu as dit un point avec d'autres mots, ça compte quand même.",
  'barra3.spiego-sicuro': 'Chapitre marqué comme maîtrisé.',
  'barra3.spiego-cerchio-vuoto': "Ceux avec le cercle vide : relis-les et réessaie dans quelques jours.",
  'barra3.orale-niente': "Aujourd'hui, il n'y a rien à interroger dans le plan.",
  'barra3.orale-contesto': 'Oral · <b>{nome}</b> · {cosa}',
  'barra3.n-argomenti': { one: '{n} chapitre', other: '{n} chapitres' },
  'barra3.esci': 'Quitter',
  'barra3.orale-sintesi': 'oral de {nome} sur le programme',

  // envoyer, fichiers, voix
  'barra3.crea-carte-da-file': 'Crée les cartes de révision à partir de ce fichier.',
  'barra3.niente-spiegazione': "D'accord, pas d'explication.",
  'barra3.non-so-senza-ai': "Ça, je ne sais pas encore le faire sans IA. Voilà ce que je comprends :",
  'barra3.foto': 'photo',
  'barra3.togli-file': 'Enlever {nome}',
  'barra3.allegati-con-ai': "Entrée : j'en fais des cartes. Ou demande autre chose…",
  'barra3.allegati-senza-ai': "Entrée : j'importe les cartes (CSV, TSV, texte)",
  'barra3.importa-solo-testo': "Sans IA, je lis seulement des fichiers texte avec une carte par ligne (question, puis Tab ou « ; » ou « = », puis réponse), comme l'export d'Anki. Pour les PDF et les photos, il faut le cerveau local ou ton IA (écris « IA »).",
  'barra3.importa-carte': { one: 'Importer {n} carte ?', other: 'Importer {n} cartes ?' },
  'barra3.e-altre': { one: 'et {n} autre', other: 'et {n} autres' },
  'barra3.importa-in': 'Je les mets dans {nome} : tu peux changer ça depuis la page.',
  'barra3.carte-importate': { one: '{n} carte importée.', other: '{n} cartes importées.' },
  'barra3.ripassa-ora': 'Réviser maintenant',
  'barra3.ti-ascolto': "Je t'écoute",
  'barra3.ti-ascolto-preparo': "Je t'écoute · je prépare la voix…",
  'barra3.ti-ascolto-preparo-p': "Je t'écoute · je prépare la voix {p} %",
  'barra3.voce-pronta': '{voce} en local · maintiens {tasti} et parle',
  'barra3.scarico-voce': 'Je télécharge {voce} · {p} %',
  'barra3.voce-ripiego': 'Parakeet ne démarre pas : je prépare Whisper',
  'barra3.preparo-voce': 'Je prépare la voix',

  // liens, raccourcis et notifications
  'barra3.piu-tardi': "D'accord, plus tard",
  'barra3.trascrivi-lezione': 'Transcrire le cours',
  'barra3.fine-trascrizione': 'Fin de la transcription',
  'barra3.ripeti': 'Répète',
  'barra3.spegni-ripeti': 'Désactiver Répète',
  'barra3.accendi-ripeti': 'Activer Répète',
  'barra3.gioca': 'Jouer',
  'barra3.pausa': 'Pause',
  'barra3.focus-fatto': { one: '{n} minute faite · pause', other: '{n} minutes faites · pause' },
  'barra3.tempo-scaduto-consegna': 'Temps écoulé · rends ta copie',
  'barra3.pausa-finita': 'Pause terminée · on reprend ?',
  'barra3.ripeti-spento': 'Répète éteint après 3 heures',
  'barra3.lode-pronta': 'Lode {versione} est prêt',
  'barra3.lode-uscita': 'Lode {versione} est sorti',
  'barra3.sync-in-pausa': 'Synchro en pause · écris le mot de passe',
  'barra3.cervello-locale': 'Cerveau local',
  'barra3.ripassa-esame': 'Réviser {nome}',
  'barra3.ripasso': 'Révision',
  'barra3.libretto': 'Relevé de notes',
};
