// Textes de la barre, deuxième partie (français) : fichiers déposés dans la barre, suggestions du coach, ton IA,
// « Prépare Lode » et mises à jour, synchro, notes, clôture du cours, jeux, commandes locales, erreurs expliquées et
// journal, outils de l'IA, oral, agents de programmation (js/lode.js).
export default {
  'barra2.file-non-so-usare': "Ça, je ne sais pas l'utiliser : {motivo}.",
  'barra2.peso-kb': '{n} Ko',
  'barra2.peso-mb': '{n} Mo',
  'barra2.cosa-ne-faccio': "J'en fais quoi ?",
  'barra2.per': 'Pour',
  'barra2.corso': 'Cours',
  'barra2.data-lezione': 'Date du cours',
  'barra2.non-andata': "Ça n'a pas marché : {errore}",
  'barra2.sintesi-cosa-ne-faccio': "{nome} : j'en fais quoi ?",
  'barra2.allegato-lezione': 'Joint au cours de {corso}.',
  'barra2.apri': 'Ouvrir',
  'barra2.sbobina-nel-vault': 'Transcription de {corso} dans ton coffre.',
  'barra2.sbobina-nota-da': '{data} · de {da}',
  'barra2.sbobina-ricevuta': 'transcription reçue',
  'barra2.nessuna-riga-carte': "Je n'ai pas trouvé de lignes « question, réponse » dans ce fichier.",
  'barra2.apro-registrazione': "J'ouvre l'enregistrement…",
  'barra2.leggo-foto': 'Je lis la photo…',
  'barra2.lavagna-titolo': 'Mettre dans les notes de {corso} ?',
  'barra2.lavagna-nota': "Avec la photo, dans la note du cours d'aujourd'hui. Relis-la : c'est {motore} qui l'a transcrite.",
  'barra2.lavagna-fatta': 'Tableau ajouté aux notes.',
  'barra2.leggo-file': 'Je lis {nome}…',
  'barra2.file-senza-testo': "Je n'arrive pas à lire le texte de ce fichier.",
  'barra2.file-senza-testo-incolla': "Je n'arrive pas à lire le texte de ce fichier : colle-le dans le champ.",
  'barra2.prima-esame': "Ajoute d'abord l'examen, par exemple : « examen analyse 2 le 15 janvier 9 ects ».",
  'barra2.scrivo-carte': "J'écris les cartes…",
  'barra2.file-senza-carte': "Je n'ai pas tiré de cartes de ce fichier.",
  'barra2.riassumo': 'Je résume {nome}… {p} %',
  'barra2.riassunto-titolo': 'Enregistrer le résumé dans Obsidian ?',
  'barra2.riassunto-nota': 'Nouvelle note dans {cartella}, avec le fichier original en pièce jointe.',
  'barra2.riassunto-salvato': 'Résumé enregistré.',
  'barra2.stelle-titolo': "★ À l'exam · {esame}",
  'barra2.ora-un-gioco': 'Maintenant, un jeu',
  'barra2.gioca': 'Jouer',
  'barra2.la-tua-ai': 'Ton IA',
  'barra2.ai-locale-attivo': 'En ce moment, Lode utilise le <b>cerveau local</b> : gratuit, hors ligne, tes notes restent ici.',
  'barra2.ai-locale-da-installare': "Le <b>cerveau local</b> gratuit s'installe depuis « Prépare Lode ».",
  'barra2.ai-chiave-spiegazione': "Si tu veux une IA plus puissante, connecte ta clé : tu paies directement le service, à l'usage (en général quelques centimes par session). Lode ne voit rien et n'encaisse rien ; la clé reste sur cet ordinateur.",
  'barra2.ai-nome-collegata': '{nome} · connectée',
  'barra2.chiave-api': 'Clé API',
  'barra2.collega': 'Connecter',
  'barra2.modello': 'Modèle',
  'barra2.ai-solo-spiegazioni': "Notes et cours restent sur l'ordinateur : ton IA seulement pour les explications et l'oral",
  'barra2.usa-solo-locale': 'Utiliser seulement le cerveau local',
  'barra2.chiave-di': 'Clé {nome}',
  'barra2.incolla-chiave': 'colle la clé',
  'barra2.si-crea-su': 'Elle se crée sur <b>{sito}</b>.',
  'barra2.provo-chiave': "J'essaie la clé…",
  'barra2.ai-collegata': '{nome} connectée.',
  'barra2.ai-modello': 'Modèle {modello}.',
  'barra2.ai-appunti-restano': "Les notes restent sur l'ordinateur.",
  'barra2.ai-usano-tua': "Explications, oral, cartes et mise au propre utilisent ton IA.",
  'barra2.sintesi-ai-collegata': 'IA connectée',
  'barra2.chiave-non-valida': "La clé n'est pas valide.",
  'barra2.servizio-irraggiungibile': "Je n'arrive pas à joindre le service : tu as du réseau ?",
  'barra2.solo-locale-fatto': 'Lode utilise seulement le cerveau local.',
  'barra2.ai-scollegata-sito': "J'ai effacé la clé de cet ordinateur. Dans ton compte {nome}, elle marche encore : si tu n'en as plus besoin, révoque-la là-bas aussi ({sito}).",
  'barra2.ai-scollegata-nome': "J'ai effacé la clé de cet ordinateur. Dans ton compte {nome}, elle marche encore : si tu n'en as plus besoin, révoque-la là-bas aussi.",
  'barra2.ai-scollegata': "J'ai effacé la clé de cet ordinateur. Dans ton compte, elle marche encore : si tu n'en as plus besoin, révoque-la là-bas aussi.",
  'barra2.sintesi-la-tua-ai': 'ton IA',
  'barra2.agg-pronta': 'Lode {versione} est prêt',
  'barra2.agg-si-installa': "Il s'installe tout seul quand tu fermes Lode",
  'barra2.riavvia-ora': 'Redémarrer maintenant',
  'barra2.agg-uscita': 'Lode {versione} est sorti',
  'barra2.agg-scarica-dmg': 'Télécharge le .dmg et glisse Lode dans Applications',
  'barra2.agg-scarica-github': 'Télécharge la nouvelle version sur GitHub',
  'barra2.scarica': 'Télécharger',
  'barra2.agg-spenti': 'Lode {versione} · désactivées : les nouvelles versions sont sur GitHub, sur la page Releases',
  'barra2.agg-scarico': 'Je télécharge Lode {versione} · {p} %',
  'barra2.agg-pronta-riga': "Lode {versione} est prêt · il s'installe tout seul quand tu fermes Lode",
  'barra2.agg-uscita-mac': 'Lode {versione} est sorti · télécharge le .dmg et glisse Lode dans Applications',
  'barra2.agg-uscita-github': 'Lode {versione} est sorti · télécharge-le sur GitHub',
  'barra2.agg-manuale': "Lode {versione} · je te préviens quand une nouvelle version sort (depuis GitHub, toutes les 6 heures)",
  'barra2.agg-automatici': 'Lode {versione} · se met à jour tout seul depuis GitHub (vérification toutes les 6 heures)',
  'barra2.spegni': 'Désactiver',
  'barra2.accendi': 'Activer',
  'barra2.prep-solo-app': "Obsidian et le cerveau local s'installent depuis l'**appli de bureau** de Lode.",
  'barra2.prepara-lode': 'Prépare Lode',
  'barra2.il-tuo-vault': 'Ton coffre',
  'barra2.prep-vault-dett': '{percorso} · accueil, cours, notes de cours, glossaire',
  'barra2.obs-installato': 'Installé et relié au coffre',
  'barra2.obs-da-installare': 'Gratuit pour un usage personnel · installeur officiel depuis GitHub, environ 230 Mo',
  'barra2.installa': 'Installer',
  'barra2.cervello-locale': 'Cerveau local',
  'barra2.cervello-pronto-dett': "{modello} · tourne sur l'ordinateur, sans internet",
  'barra2.cervello-da-installare': 'Ollama + {etichetta}, {perche} · environ {gb} Go',
  'barra2.pronto': 'prêt',
  'barra2.voce': 'Voix',
  'barra2.voce-pronta-dett': '{voce} en local · maintiens {tasti} et parle',
  'barra2.pronta': 'prête',
  'barra2.prepara': 'Préparer',
  'barra2.facoltativa': 'facultative',
  'barra2.tua-ai-collegata-dett': "{nome} connectée · c'est toi qui paies à l'usage, directement au service",
  'barra2.tua-ai-da-collegare': "Claude, ChatGPT, Gemini, Mistral… : plus puissant, à l'usage avec ta clé",
  'barra2.cambia': 'Changer',
  'barra2.sincronizza-computer': 'Synchronise entre tes ordinateurs',
  'barra2.sperimentale': 'expérimental',
  'barra2.sblocca': 'Déverrouiller',
  'barra2.gestisci': 'Gérer',
  'barra2.attiva': 'Activer',
  'barra2.uso-gia-altrove': "J'utilise déjà Lode sur un autre ordinateur",
  'barra2.collega-dett': 'Relie cet ordinateur au coffre que tu as déjà dans le dossier cloud',
  'barra2.aggiornamenti': 'Mises à jour',
  'barra2.prep-nota': "Le cerveau local est gratuit et marche hors ligne : il extrait les définitions, crée des cartes, explique et interroge. Ton IA est un bonus facultatif : Lode ne voit rien et n'encaisse rien.",
  'barra2.detto-mia-ai': 'Mon IA',
  'barra2.detto-sincronizza': 'Synchronise entre les ordinateurs',
  'barra2.scarico-voce': 'Je télécharge {voce}…',
  'barra2.sintesi-prepara': 'prépare Lode',
  'barra2.installare-obsidian': 'Installer Obsidian ?',
  'barra2.da': 'Depuis',
  'barra2.github-obsidian': 'github.com/obsidianmd (officiel)',
  'barra2.peso': 'Taille',
  'barra2.circa-230-mb': 'environ 230 Mo',
  'barra2.dove': 'Où',
  'barra2.applicazioni': 'Applications',
  'barra2.il-tuo-utente': 'ton utilisateur',
  'barra2.obs-nota': "Obsidian est gratuit pour un usage personnel. Il s'ouvre directement sur ton coffre, sur la page d'accueil.",
  'barra2.installare-nome': 'Installer {nome} ?',
  'barra2.installare-cervello': 'Installer le cerveau local ?',
  'barra2.cosa': 'Quoi',
  'barra2.ollama-motore': 'Ollama (moteur) + {nome}',
  'barra2.circa-gb': 'environ {gb} Go',
  'barra2.perche': 'Pourquoi',
  'barra2.cervello-nota': 'Il se télécharge une seule fois. Ensuite, il marche sans internet et sans clé.',
  'barra2.solo-clic': 'Ça se confirme seulement par un clic.',
  'barra2.avviato': 'Lancé.',
  'barra2.continuo-da-solo': 'Tu peux fermer le panneau : je continue tout seul.',
  'barra2.obsidian-pronto': 'Obsidian est prêt',
  'barra2.cervello-pronto': 'Cerveau local prêt',
  'barra2.sync-piede-cifrati': 'Chiffrées, synchronisées avec {servizio}',
  'barra2.sync-piede': 'Synchronisées avec {servizio}',
  'barra2.la-tua-cartella-cloud': 'ton dossier cloud',
  'barra2.dati-restano-qui': 'Les données restent sur cet ordinateur',
  'barra2.portachiavi-mac': 'Le mot de passe est mémorisé sur cet ordinateur (dans le Trousseau).',
  'barra2.portachiavi-windows': 'Le mot de passe est mémorisé sur cet ordinateur (protégé par ton compte Windows).',
  'barra2.portachiavi-sistema': 'Le mot de passe est mémorisé sur cet ordinateur (dans le trousseau du système).',
  'barra2.senza-portachiavi': "Cet ordinateur n'a pas de trousseau sécurisé : Lode te demandera le mot de passe à chaque démarrage.",
  'barra2.sync-solo-app': "La synchro entre ordinateurs est dans l'**appli de bureau** de Lode.",
  'barra2.sync-stato-illeggibile': "Je n'arrive pas à lire l'état de la synchro.",
  'barra2.sync-altro-computer': "Sur l'autre ordinateur, ouvre Lode et choisis « J'utilise déjà Lode sur un autre ordinateur », puis le coffre « {vault} » dans {servizio}.",
  'barra2.la-cartella-cloud': 'le dossier cloud',
  'barra2.sync-non-accesa': "La synchro n'est pas activée : les données de Lode restent sur cet ordinateur.",
  'barra2.sync-titolo-altro': "J'utilise déjà Lode sur un autre ordinateur · expérimental",
  'barra2.sync-titolo': 'Synchronise entre tes ordinateurs · expérimental',
  'barra2.sync-sperimentale': '<b>Expérimental.</b> {testo}',
  'barra2.sync-cartella-cloud': "J'utilise le dossier cloud que tu as déjà : pas de compte, pas de serveur Lode. Je copie le coffre là-bas et je passe à la copie ; l'ancien dossier reste où il est. {prima}",
  'barra2.sync-interrotto': "<b>Le déplacement vers {servizio} s'est interrompu.</b> L'ancien coffre est intact : choisis de nouveau le dossier et je reprends là où je m'étais arrêté.",
  'barra2.cartella-cloud': 'dossier cloud',
  'barra2.sync-interrotto-pw': "Ça avait commencé avec le mot de passe : je te demanderai de l'écrire à nouveau.",
  'barra2.vault-gia-qui': 'le coffre est déjà ici : rien à déplacer',
  'barra2.altra-cartella': 'Un autre dossier…',
  'barra2.altra-cartella-dett': 'Syncthing, un dossier réseau',
  'barra2.nessuna-cartella-cloud': 'Je ne trouve ni iCloud Drive, ni OneDrive, ni Dropbox, ni Google Drive sur cet ordinateur : choisis toi-même le dossier qui se synchronise.',
  'barra2.scegli-vault-cloud': 'Choisis le coffre dans le dossier cloud',
  'barra2.gia-sincronizzato': '{servizio} · déjà synchronisé',
  'barra2.scegli-vault': 'Choisir le coffre…',
  'barra2.scegli-vault-dett': 'le dossier « Lode » dans ton dossier cloud',
  'barra2.vault-resta': 'Le coffre actuel de cet ordinateur reste où il est, intact.',
  'barra2.vault-resta-altro': "Si Lode a déjà ici des examens, des notes ou des cartes, je les mets dans le groupe sous « Données d'un autre premier démarrage » : c'est toi qui les importes, rien ne remplace les données des autres ordinateurs.",
  'barra2.la-cartella-che-scegli': 'le dossier que tu choisis',
  'barra2.sintesi-uso-gia-altrove': "j'utilise déjà Lode ailleurs",
  'barra2.sintesi-sincronizza': 'synchro',
  'barra2.sincronizzare-con': 'Synchroniser avec {servizio} ?',
  'barra2.vault': 'Coffre',
  'barra2.vault-resta-cloud': "reste où il est : il est déjà dans le dossier cloud",
  'barra2.cartella-lode-in': 'un dossier « Lode » dans {servizio}',
  'barra2.prima': 'Avant',
  'barra2.dati-json-cronologia': "l'ancien dati.json reste dans l'historique du service",
  'barra2.vault-adesso-resta': 'le coffre actuel reste où il est, intact',
  'barra2.dati-di-lode': 'Données de Lode',
  'barra2.un-diario-per-computer': 'un journal par ordinateur : pas de conflits, rien ne se perd',
  'barra2.proteggi-con-password': 'Protège les données de Lode avec un mot de passe',
  'barra2.password-almeno-8': 'Mot de passe (au moins 8 caractères)',
  'barra2.password': 'Mot de passe',
  'barra2.ripetila': 'Encore une fois',
  'barra2.ripeti-password': 'Répète le mot de passe',
  'barra2.cifrati-in-chiaro-anche': '<b>Chiffrées :</b> {cifrati}. <b>En clair dans le dossier cloud</b>, même avec le mot de passe :',
  'barra2.sync-nota-password': "Le mot de passe peut aussi s'ajouter après (« Protéger avec un mot de passe »), ou se changer (« Changer le mot de passe »). Sur les autres ordinateurs : « J'utilise déjà Lode sur un autre ordinateur ». {prima}",
  'barra2.spostamento-con-password': "Le déplacement avait commencé avec le mot de passe : écris-le à nouveau.",
  'barra2.almeno-8': 'Au moins 8 caractères.',
  'barra2.password-diverse': 'Les deux mots de passe ne sont pas identiques.',
  'barra2.preparo': 'Je prépare…',
  'barra2.sincronizzato-con': 'Synchronisé avec {servizio}.',
  'barra2.vault-era-gia-cloud': "Le coffre était déjà dans le dossier cloud : à partir de maintenant, chaque ordinateur n'écrit que son propre journal.",
  'barra2.cartella-prima-resta': "L'ancien dossier (« {da} ») reste où il était : supprime-le quand tu veux. Sur les autres ordinateurs : « J'utilise déjà Lode sur un autre ordinateur ».",
  'barra2.vault-gia-in-servizio': 'Dans {servizio}, il y a déjà un coffre Lode synchronisé.',
  'barra2.usa-uso-gia': "Utilise « J'utilise déjà Lode sur un autre ordinateur » pour t'y connecter.",
  'barra2.annullato': 'Annulé.',
  'barra2.niente-cambiato': "Je n'ai rien changé.",
  'barra2.scrivi-password': 'Écris le mot de passe.',
  'barra2.non-ancora': 'Pas encore.',
  'barra2.non-andata-vault-intatto': "Ça n'a pas marché : {errore}. L'ancien coffre est intact.",
  'barra2.collegato-vault-in': 'Connecté au coffre dans {servizio}.',
  'barra2.dati-protetti-password': 'Les données de Lode sont protégées par un mot de passe : écris-le pour les recevoir.',
  'barra2.ricevo-dati': 'Je reçois les données des autres ordinateurs : elles arrivent toutes seules. Lode est déjà utilisable.',
  'barra2.dati-importati-altrove': { one: "Les données que tu avais sur cet ordinateur ({n} enregistrement) sont dans « Données d'un autre premier démarrage », dans l'onglet « Synchro » : importe-les de là. L'ancien fichier reste dans le coffre « {vault} ».", other: "Les données que tu avais sur cet ordinateur ({n} enregistrements) sont dans « Données d'un autre premier démarrage », dans l'onglet « Synchro » : importe-les de là. L'ancien fichier reste dans le coffre « {vault} »." },
  'barra2.cartella-inusabile': "Je n'arrive pas à utiliser ce dossier.",
  'barra2.diario-illeggibile': 'Le journal de Lode sur cet ordinateur est illisible',
  'barra2.diario-illeggibile-nota': "Rien n'a été supprimé : le dossier des données de Lode ne répond pas (disque plein ou en panne ?). Les modifications faites maintenant vont dans un fichier à part.",
  'barra2.riprova': 'Réessayer',
  'barra2.vault-sparito': "Les données de Lode de cet ordinateur sont en sécurité dans son journal. Si tu as déplacé le coffre, choisis le dossier où tu l'as mis.",
  'barra2.trova-vault': 'Retrouver le coffre',
  'barra2.lode-vecchia-campi': { one: "<b>D'une ancienne version de Lode :</b> {n} champ différent de ceux d'aujourd'hui. Ça ne change rien tout seul : la copie du fichier est dans le dossier des données de Lode (sync/copie).", other: "<b>D'une ancienne version de Lode :</b> {n} champs différents de ceux d'aujourd'hui. Ça ne change rien tout seul : la copie du fichier est dans le dossier des données de Lode (sync/copie)." },
  'barra2.aggiunte': { one: "<b>Données d'un autre premier démarrage ou d'une ancienne version de Lode :</b> {n} enregistrement (examens, cartes, sessions…) que le journal n'a pas. Il n'est pas importé tout seul.", other: "<b>Données d'un autre premier démarrage ou d'une ancienne version de Lode :</b> {n} enregistrements (examens, cartes, sessions…) que le journal n'a pas. Ils ne sont pas importés tout seuls." },
  'barra2.importa-aggiunte': 'Importer les ajouts',
  'barra2.password-dati-lode': 'Mot de passe des données de Lode',
  'barra2.intanto-funziona': 'En attendant, Lode marche avec les données de cet ordinateur : les modifications attendent dans le journal. {portachiavi}',
  'barra2.ho-dimenticato-password': "J'ai oublié le mot de passe",
  'barra2.dimentica-password-qui': 'Oublier le mot de passe ici',
  'barra2.cifrati-in-chiaro': '<b>Chiffrées :</b> {cifrati}. <b>En clair dans le dossier cloud :</b>',
  'barra2.cambia-password': 'Changer le mot de passe',
  'barra2.senza-password': 'Sans mot de passe : qui peut lire ton dossier cloud peut aussi lire les données de Lode, tout comme tes notes.',
  'barra2.proteggi-password': 'Protéger avec un mot de passe',
  'barra2.recuperi': "Les modifications que le journal n'a pas pu prendre sont dans {n} fichiers « recupero-…json » (le dernier : « {file} »), dans le dossier des données de Lode : je ne les ai pas jetées.",
  'barra2.recupero': "Les modifications que le journal n'a pas pu prendre sont dans le fichier « {file} », dans le dossier des données de Lode : je ne les ai pas jetées.",
  'barra2.smetti-qui': 'Arrêter sur cet ordinateur',
  'barra2.importati-record': { one: '{n} enregistrement importé.', other: '{n} enregistrements importés.' },
  'barra2.ora-su-tutti': 'Maintenant, ils sont sur tous les ordinateurs.',
  'barra2.non-andata-punto': "Ça n'a pas marché.",
  'barra2.controllo': 'Je vérifie…',
  'barra2.sbloccata': 'Déverrouillée.',
  'barra2.password-ricordata': 'Le mot de passe est mémorisé sur cet ordinateur.',
  'barra2.chiedero-prossimo-avvio': 'Je te le demanderai au prochain démarrage.',
  'barra2.password-nuova-almeno-8': 'Nouveau mot de passe (au moins 8 caractères)',
  'barra2.password-nuova': 'Nouveau mot de passe',
  'barra2.password-nuova-pronta': 'Nouveau mot de passe prêt.',
  'barra2.altri-chiederanno': 'Les autres ordinateurs te le demanderont une fois.',
  'barra2.cambiare-password': 'Changer le mot de passe ?',
  'barra2.rifa-password-nuova': 'Lode refait les données de Lode dans le dossier cloud avec le nouveau mot de passe. {testo}',
  'barra2.scegliere-password-nuova': 'Choisir un nouveau mot de passe ?',
  'barra2.proteggere-password': 'Protéger les données de Lode avec un mot de passe ?',
  'barra2.rifa-cifrati': 'Lode refait les données de Lode dans le dossier cloud, chiffrées avec le mot de passe. Les autres ordinateurs te le demanderont. {testo}',
  'barra2.password-dimenticata': 'Mot de passe oublié sur cet ordinateur.',
  'barra2.chiedero-di-nuovo': 'Je te le demanderai de nouveau.',
  'barra2.smettere-qui': 'Arrêter sur cet ordinateur ?',
  'barra2.vault-copiato-fuori': 'copié dans un dossier en dehors du dossier cloud, que tu choisis',
  'barra2.tutti-dati': "toutes, même celles des autres ordinateurs jusqu'à aujourd'hui",
  'barra2.gli-altri-computer': 'Les autres ordinateurs',
  'barra2.continuano-sincronizzarsi': 'continuent à se synchroniser entre eux',
  'barra2.smesso-qui': 'Arrêté sur cet ordinateur.',
  'barra2.smesso-nota': 'Le coffre est maintenant en dehors du dossier cloud. Pour arrêter partout, fais-le sur chaque ordinateur.',
  'barra2.sintesi-smessa': 'synchro arrêtée ici',
  'barra2.ultima-lezione': 'Dernier cours',
  'barra2.lezione-di': 'Cours de {corso}',
  'barra2.cosa-sa-lode': 'Ce que Lode sait de moi',
  'barra2.vai-a-note': { one: 'Aller à… · {n} note', other: 'Aller à… · {n} notes' },
  'barra2.radice-vault': 'coffre',
  'barra2.oggi': "aujourd'hui",
  'barra2.cerca-nota-segnaposto': 'Cherche une note : cours, date…',
  'barra2.cerca-nota': 'Chercher une note',
  'barra2.nessuna-nota': 'Aucune note trouvée.',
  'barra2.sintesi-cerco': 'je cherche « {q} »',
  'barra2.sintesi-note': 'notes',
  'barra2.niente-appunti-di': 'Je ne trouve pas de notes de **{corso}** ces derniers jours.',
  'barra2.niente-appunti': "Je ne trouve pas de cours avec assez de notes : écris-les dans la section « {sezione} » de la note.",
  'barra2.appunti-serve-ai': "Pour lire les notes, il faut l'IA : installe le **cerveau local** (gratuit, marche hors ligne) depuis « Prépare Lode », ou connecte ton IA : écris « IA ».",
  'barra2.leggo-appunti-di': 'Je lis les notes de {corso}…',
  'barra2.appunti-illeggibili': "Je n'ai pas réussi à lire les notes : {errore}",
  'barra2.nessuna-definizione-nuova': "Je n'ai pas trouvé de nouvelles définitions dans les notes. Essaie de les écrire en entier, même courtes.",
  'barra2.aggiungere-a': 'Ajouter à {corso} · {data} ?',
  'barra2.chiudi-nota': { one: "{n} définition dans la note du cours. Vérifie qu'elle est juste : c'est {motore} qui l'a écrite.", other: "{n} définitions dans la note du cours. Vérifie qu'elles sont justes : c'est {motore} qui les a écrites." },
  'barra2.chiudi-nota-stelle': { one: "{n} définition et {stelle} ★ dans la note du cours. Vérifie que c'est juste : c'est {motore} qui l'a écrit.", other: "{n} définitions et {stelle} ★ dans la note du cours. Vérifie que c'est juste : c'est {motore} qui les a écrites." },
  'barra2.lezione-chiusa': 'Cours clôturé.',
  'barra2.definizioni-pronte': { one: '{n} définition prête pour les jeux.', other: '{n} définitions prêtes pour les jeux.' },
  'barra2.sintesi-definizioni': { one: '{n} définition', other: '{n} définitions' },
  'barra2.appunti-sparsi-oggi': "les notes en vrac d'aujourd'hui",
  'barra2.la-nota-di': 'la note de {corso}',
  'barra2.apro-in-obsidian': "J'ouvre {nome} dans Obsidian.",
  'barra2.apro-se-non-trova': "J'ouvre {nome}. Si Obsidian ne trouve pas le coffre, la première fois fais **Ouvrir un dossier comme coffre** et choisis le dossier « {percorso} » : ensuite, il reste relié.",
  'barra2.aperto-editor': "J'ai ouvert {nome} avec l'éditeur du système. Avec **Obsidian** (gratuit, obsidian.md), le coffre « {percorso} » est déjà prêt : dossiers, modèles, emploi du temps et ta mémoire.",
  'barra2.nota-non-si-apre': "Je n'arrive pas à ouvrir la note : {errore}",
  'barra2.appunti-solo-app': "Les notes dans Obsidian sont dans l'**appli de bureau** de Lode : là, chaque cours devient une note de ton coffre, avec les ★ et les définitions que tu notes depuis la barre.",
  'barra2.gioco-sai-gia-di': "Les définitions de {corso} pour aujourd'hui, tu les sais déjà : elles reviennent quand elles sont sur le point de s'échapper.",
  'barra2.gioco-sai-gia': "Les définitions pour aujourd'hui, tu les sais déjà : elles reviennent quand elles sont sur le point de s'échapper.",
  'barra2.gioco-nessuna-di': 'Pas encore de définition de {corso}. En cours, appuie sur **Définition** (ou écris « déf : terme = définition »), ou écris-les dans Obsidian dans la section « {sezione} » du cours.',
  'barra2.gioco-nessuna': 'Pas encore de définition. En cours, appuie sur **Définition** (ou écris « déf : terme = définition »), ou écris-les dans Obsidian dans la section « {sezione} » du cours.',
  'barra2.gioco-di': 'Jeu · {corso}',
  'barra2.ultime-lezioni': 'derniers cours',
  'barra2.manche-di': '{i} sur {n}',
  'barra2.abbina': 'Associe chaque terme à sa définition.',
  'barra2.chi-sono': 'Qui suis-je ?',
  'barra2.completa': '{termine} : complète la définition.',
  'barra2.parola-mancante': 'Mot manquant',
  'barra2.controlla-invio': 'Vérifier <kbd>Entrée</kbd>',
  'barra2.non-la-so': 'Je ne sais pas',
  'barra2.te-la-ricordi': 'Tu te souviens ?',
  'barra2.mostra-spazio': 'Afficher <kbd>Espace</kbd>',
  'barra2.non-la-sapevo': 'Je ne savais pas <kbd>1</kbd>',
  'barra2.la-sapevo': 'Je savais <kbd>2</kbd>',
  'barra2.tutte-giuste': 'Tout juste. Celles-là restent.',
  'barra2.da-rinforzare': 'À renforcer : {elenco}. Elles reviennent demain.',
  'barra2.secondi': { one: '{n} seconde', other: '{n} secondes' },
  'barra2.minuti': '{n} min',
  'barra2.sintesi-punti': '{punti} sur {tot}',
  'barra2.ancora-una': 'Encore une',
  'barra2.gioca-ancora': 'Rejouer',
  'barra2.sintesi-gioco': 'jeu',
  'barra2.pausa-finita': 'Pause terminée.',
  'barra2.fermato-dopo': 'Arrêté après {tempo}.',
  'barra2.prova-resta-aperta': "L'examen blanc reste ouvert : écris « examen blanc » pour le rendre.",
  'barra2.li-conto': 'Je les compte dans les heures de révision.',
  'barra2.sintesi-timer-fermato': 'minuteur arrêté',
  'barra2.nessun-timer': "Aucun minuteur n'est lancé.",
  'barra2.timer-in-pausa': 'Minuteur en pause.',
  'barra2.scrivi-riprendi': 'Écris « reprends » quand tu reviens.',
  'barra2.si-riparte': "C'est reparti.",
  'barra2.focus-esame-sconosciuto': "Je ne trouve pas **{nome}** dans tes examens. Je lance l'étude libre ? Écris « focus {min} ».",
  'barra2.di-quale-esame': 'Quel examen ?',
  'barra2.idoneita-registrata': '{nome} : validation enregistrée.',
  'barra2.voto-in': '{voto} en {nome}.',
  'barra2.voto-lode-in': '{voto} avec mention (lode) en {nome}.',
  'barra2.nuovo-esame-6-cfu': 'Nouvel examen de 6 crédits : corrige les crédits dans le relevé de notes.',
  'barra2.media-diff': 'Moyenne {media} ({segno}{diff})',
  'barra2.sintesi-voto': '{nome} : {voto}',
  'barra2.idoneita': 'validé',
  'barra2.trenta-e-lode': 'Trenta e lode, la note maximale. Ça se fête.',
  'barra2.bel-colpo': "Bien joué. Souffle aujourd'hui, demain on repart.",
  'barra2.esame-aggiornato': '{nome} mis à jour.',
  'barra2.esame-aggiunto': '{nome} ajouté.',
  'barra2.esame-nota': '{quando} · {cfu} crédits',
  'barra2.esame-nota-cambiali': "{quando} · {cfu} crédits (change-les s'il y en a plus)",
  'barra2.senza-data': 'sans date',
  'barra2.piano-ore': 'Pour y arriver prêt : environ **{h} h par jour** ({tot} h en tout).',
  'barra2.proposte-spente-riaccendi': 'Les suggestions sont désactivées : réactive-les avec « suggestions normales ».',
  'barra2.proposte-da-adesso': "À partir de maintenant, quand tu es sur l'ordinateur et libre, je te propose des jeux, des révisions et des questions sur {nome}.",
  'barra2.proposte-da-adesso-vicino': "À partir de maintenant, quand tu es sur l'ordinateur et libre, je te propose des jeux, des révisions et des questions sur {nome}, de plus en plus souvent à mesure qu'il approche.",
  'barra2.carta-aggiunta': 'Carte ajoutée.',
  'barra2.senza-esame': 'sans examen',
  'barra2.esame-sconosciuto': 'Je ne trouve pas **{nome}** dans tes examens.',
  'barra2.spiego-senza-programma': "Colle d'abord le programme d'un examen (« programme d'analyse 2 ») : ensuite tu m'expliques ses chapitres et je te dis ce que tu as oublié.",
  'barra2.argomento-sconosciuto': 'Je ne trouve pas **{q}** dans les programmes de tes examens.',
  'barra2.esame-non-trovato': "Je ne trouve pas l'examen **{nome}**.",
  'barra2.domande-di-quale-esame': 'Quel examen ? Par exemple : « questions tombées en analyse 2 : … ».',
  'barra2.nella-nota-lezione': 'Dans la note du cours.',
  'barra2.in-orario': "{corso} ajouté à l'emploi du temps.",
  'barra2.aula': 'salle {aula}',
  'barra2.sintesi-in-orario': "{corso} dans l'emploi du temps",
  'barra2.orario-spiegazione': "Quand tu es en cours, la barre le sait : elle s'ouvre sur la saisie rapide (★ à l'exam, définitions, questions) et, chez toi, elle te propose deux minutes de jeu sur ce que tu viens de faire.",
  'barra2.proposte-spente': 'Suggestions désactivées.',
  'barra2.proposte-poche': 'Peu de suggestions.',
  'barra2.proposte-normali': 'Suggestions normales.',
  'barra2.proposte-frequenti': 'Suggestions fréquentes.',
  'barra2.riaccendi-quando-vuoi': 'Tu les réactives quand tu veux.',
  'barra2.proposte-mai-quando': 'Jamais en cours, au travail, en focus ou pendant les heures de silence.',
  'barra2.niente-da-proporre': "Pour l'instant, je n'ai rien à te proposer : ajoute un examen avec sa date, ou note quelques définitions en cours.",
  'barra2.trascrizione-in-pausa': 'Transcription en pause.',
  'barra2.scrivi-riprendi-trascrizione': 'Écris « reprends la transcription » quand ça recommence.',
  'barra2.riprendo-trascrivere': 'Je reprends la transcription.',
  'barra2.err-valutato': 'Projet noté : je ne te montre pas la correction.',
  'barra2.errore-spiegato': 'Erreur expliquée',
  'barra2.correzione-vista': 'correction vue',
  'barra2.copia-errore': "Copie l'erreur depuis le terminal (ou l'IDE) et réécris « explique-moi l'erreur ».",
  'barra2.incolla-errore': "Colle l'erreur après les deux-points : « explique-moi l'erreur : … ».",
  'barra2.nessun-errore-nel-testo': "Dans ce texte, je ne trouve pas d'erreur du compilateur ou du programme. Copie tout, à partir de la ligne avec le nom du fichier, et réessaie.",
  'barra2.segui-valutato': 'Tu suis un projet noté : je ne te montre pas la correction.',
  'barra2.diario-solo-app': "Le journal est dans le coffre : il faut l'**appli de bureau** de Lode.",
  'barra2.progetto-sconosciuto': "Je ne trouve pas de projet qui s'appelle « {nome} ».",
  'barra2.nessun-progetto-segui': 'Je ne suis encore aucun projet. Écris **suis le projet** et choisis le dossier du TP.',
  'barra2.diario-spento-per': "Pour **{progetto}**, le journal est désactivé : je n'écris rien dans le coffre. Réactive-le avec « active le journal de {progetto} ».",
  'barra2.diario-non-si-apre': "Je n'arrive pas à ouvrir le journal : {errore}",
  'barra2.diario-di': 'Journal de {progetto}.',
  'barra2.aperto-editor-sistema': "Ouvert avec l'éditeur du système : avec Obsidian, c'est plus pratique.",
  'barra2.aperto-in-obsidian': '{file} · ouvert dans Obsidian.',
  'barra2.sintesi-diario-di': 'journal de {progetto}',
  'barra2.nessun-progetto': 'Je ne suis encore aucun projet.',
  'barra2.diario-acceso': 'Journal de {nome} activé.',
  'barra2.diario-acceso-nota': "J'écris dans le coffre ce que je vois : ce qui change et les tests. Je ne sais pas qui écrit les lignes.",
  'barra2.diario-spento': 'Journal de {nome} désactivé.',
  'barra2.diario-spento-nota': "À partir de maintenant, je n'écris plus rien de ce projet dans le coffre. Les notes déjà écrites restent : tu peux les enlever depuis Obsidian.",
  'barra2.focus-di-minuti': 'Focus de {min} minutes.',
  'barra2.focus-di-minuti-su': 'Focus de {min} minutes sur {nome}.',
  'barra2.salvare-carte': { one: 'Enregistrer {n} carte ?', other: 'Enregistrer {n} cartes ?' },
  'barra2.salvare-carte-di': { one: 'Enregistrer {n} carte de {nome} ?', other: 'Enregistrer {n} cartes de {nome} ?' },
  'barra2.entrano-ripasso': "Elles entrent dans la révision d'aujourd'hui.",
  'barra2.carte-salvate': { one: '{n} carte enregistrée.', other: '{n} cartes enregistrées.' },
  'barra2.ripassa-ora': 'Réviser maintenant',
  'barra2.sintesi-carte': { one: '{n} carte', other: '{n} cartes' },
  'barra2.aggiungere-esame': 'Ajouter {nome} ?',
  'barra2.esame': 'Examen',
  'barra2.cfu': 'Crédits',
  'barra2.appello': 'Date',
  'barra2.registrare-voto': 'Enregistrer {voto} ?',
  'barra2.registrare-voto-lode': 'Enregistrer {voto} avec mention (lode) ?',
  'barra2.esame-nuovo-6-cfu': '{nome} (nouveau, 6 crédits)',
  'barra2.voto': 'Note',
  'barra2.voto-e-lode': '{voto} avec mention (lode)',
  'barra2.voto-registrato': 'Note enregistrée.',
  'barra2.media': 'Moyenne {media}',
  'barra2.leggo-il-file': 'Je lis le fichier…',
  'barra2.prof-ci-pensa': 'Le prof réfléchit…',
  'barra2.un-attimo': 'Un instant…',
  'barra2.file-senza-carte-locale': "Je n'ai pas tiré de cartes de ce fichier : si c'est un PDF, le modèle local ne le lit pas. Essaie avec une photo des pages ou avec le texte.",
  'barra2.file-illeggibile': "Je n'ai pas réussi à lire le fichier : {errore}",
  'barra2.chiave-non-valida-ricollega': "La clé n'est pas valide : reconnecte-la en écrivant « IA ».",
  'barra2.troppe-richieste': 'Trop de demandes en peu de temps : réessaie dans une minute.',
  'barra2.sovraccarico': '{motore} est surchargé en ce moment : réessaie dans un instant.',
  'barra2.manca-rete': 'On dirait que le réseau manque.',
  'barra2.qualcosa-non-andato': "Quelque chose n'a pas marché : {errore}",
  'barra2.orale-serve-ai-app': "Pour l'interrogation, il faut l'IA : installe le **cerveau local** depuis « Prépare Lode » (gratuit, hors ligne) ou connecte ton IA (écris « IA »). En attendant, tu peux faire la **révision** des cartes.",
  'barra2.orale-serve-ai-web': "Pour l'interrogation, il faut l'IA : ajoute ta clé Claude dans les **Réglages** (ça coûte quelques centimes par session). En attendant, tu peux faire la **révision** des cartes.",
  'barra2.orale-esame-sconosciuto': "Je ne trouve pas **{nome}** : je t'interroge quand même là-dessus.",
  'barra2.su-quale-esame': 'Sur quel examen ?',
  'barra2.aggiungi-prima-esame': "Ajoute d'abord un examen.",
  'barra2.interrogami-su': 'Interroge-moi sur {nome}',
  'barra2.orale-di-contesto': 'Oral · <b>{nome}</b>',
  'barra2.esci': 'Quitter',
  'barra2.sintesi-orale-di': 'oral de {nome}',
  'barra2.domanda-n-di': '**Question {n} sur {max}.** {domanda}',
  'barra2.prof-non-risponde': 'Le prof ne répond pas : {errore}',
  'barra2.prof-ascolta': 'Le prof écoute…',
  'barra2.orale-mancava': 'Il manquait : {cosa}',
  'barra2.era-giusta': "C'était juste",
  'barra2.segnata-giusta': 'Marquée juste',
  'barra2.prof-scrive-voto': 'Le prof écrit la note…',
  'barra2.orale-titolo': { one: 'Oral · {nome} · {n} question', other: 'Oral · {nome} · {n} questions' },
  'barra2.da-ripassare': 'À réviser',
  'barra2.orale-calcolo': "C'est Lode qui calcule la note à partir de tes réponses (juste 3 points, partielle 2).",
  'barra2.orale-calcolo-contestate': { one: "C'est Lode qui calcule la note à partir de tes réponses (juste 3 points, partielle 2), en comptant la réponse que tu as marquée juste.", other: "C'est Lode qui calcule la note à partir de tes réponses (juste 3 points, partielle 2), en comptant les réponses que tu as marquées justes." },
  'barra2.orale-giudizi-locale': "Les avis sont ceux du modèle local : il peut se tromper. C'est un entraînement, pas une prédiction.",
  'barra2.orale-giudizi-ai': "Les avis sont ceux de l'IA. C'est un entraînement, pas une prédiction.",
  'barra2.sintesi-orale-voto': 'oral de {nome} : {voto}',
  'barra2.orale-chiuso': 'Oral terminé.',
  'barra2.ripassa-esitato': 'Révise les questions où tu as hésité.',
  'barra2.agenti-solo-app': "Le pont avec les agents est dans l'**appli de bureau** de Lode.",
  'barra2.ponte-non-risponde': 'Le pont ne répond pas : {errore}',
  'barra2.agente-sconosciuto': 'Je ne sais pas encore me connecter à **{agente}**. Écris « agents » pour voir ceux que je connais.',
  'barra2.agenti-titolo': 'Agents de programmation',
  'barra2.agenti-spiegazione': "Connecte l'agent que tu utilises pour les TP : à la fin de chaque tour, Lode te dit ce qu'il a vraiment touché dans les projets que tu suis, s'il a lancé les tests après la dernière modification et s'il a changé les tests pendant qu'ils échouaient.",
  'barra2.ag-collegato-eventi': { one: 'connecté · {n} événement, le dernier à {ora}', other: 'connecté · {n} événements, le dernier à {ora}' },
  'barra2.ag-collegato-nessuno': "connecté · pas encore d'événement",
  'barra2.ag-trovato': 'trouvé sur cet ordinateur',
  'barra2.ag-non-trovato': 'pas trouvé',
  'barra2.scollega': 'Déconnecter',
  'barra2.agenti-nota': "Lecture seule : Lode ne répond pas aux agents, ne décide rien et n'élargit pas leurs autorisations. Avant d'écrire dans leur configuration, il te montre les lignes exactes. Les événements ne comptent que dans les projets que tu suis (« suis le projet »), les autres sont jetés ; le texte que tu écris à l'agent n'est pas enregistré.",
  'barra2.sintesi-agenti': 'agents',
  'barra2.niente-toccato': "D'accord, je n'ai touché à rien.",
  'barra2.ag-scollegato': '{nome} déconnecté.',
  'barra2.ag-gia-collegato': '{nome} était déjà connecté.',
  'barra2.ag-collegato': '{nome} connecté.',
  'barra2.ag-tolte-righe': "J'ai enlevé seulement mes lignes.",
  'barra2.ag-poi-segui': 'Ensuite, suis le projet du TP (« suis le projet »).',
  'barra2.l-agente': "L'agent",
  'barra2.ag-finito-test-dopo': { one: 'a fini : {n} fichier, tests lancés après la dernière modification', other: 'a fini : {n} fichiers, tests lancés après la dernière modification' },
  'barra2.ag-finito-test-prima': { one: 'a fini : {n} fichier, tests non relancés', other: 'a fini : {n} fichiers, tests non relancés' },
  'barra2.ag-finito-senza-test': { one: 'a fini : {n} fichier, aucun test', other: 'a fini : {n} fichiers, aucun test' },
  'barra2.guarda': 'Voir',
  'barra2.nessun-turno': "Pas encore de tour d'agent dans les projets que tu suis. Écris « agents » pour en connecter un.",
  'barra2.esito-non-noto': 'résultat inconnu',
  'barra2.riuscito': 'réussi',
  'barra2.fallito-codice': 'échoué (code {codice})',
  'barra2.alle': 'à {ora}',
  'barra2.file-toccati': { one: '<b>{n}</b> fichier touché : {elenco}.', other: '<b>{n}</b> fichiers touchés : {elenco}.' },
  'barra2.nessun-file-toccato': '<b>{n}</b> fichier touché.',
  'barra2.comandi': { one: '{n} commande', other: '{n} commandes' },
  'barra2.test-lanciati-dopo': { one: 'tests lancés {n} fois, la dernière <code>{comando}</code> {esito}, après la dernière modification', other: 'tests lancés {n} fois, la dernière <code>{comando}</code> {esito}, après la dernière modification' },
  'barra2.test-lanciati-prima': { one: 'tests lancés {n} fois, la dernière <code>{comando}</code> {esito}, <b>avant</b> la dernière modification', other: 'tests lancés {n} fois, la dernière <code>{comando}</code> {esito}, <b>avant</b> la dernière modification' },
  'barra2.nessun-test-lanciato': 'aucun test lancé',
  'barra2.cosa-cambiato': "Qu'est-ce qui a changé",
  'barra2.prova-tu': 'Teste toi-même',
  'barra2.preparati-discussione': 'Prépare ta soutenance',
  'barra2.parole-agente': "Ce que dit l'agent, ce ne sont que des mots : il a vraiment lancé les tests seulement si tu les vois ici. Les règles sont fixes : si elles ne trouvent rien, ce n'est pas une garantie.",
  'barra2.prova-il-progetto': 'Teste le projet',
  'barra2.sintesi-turno': { one: '{chi} : {n} fichier', other: '{chi} : {n} fichiers' },
};
