// Textes de l'accueil (français) : les étapes obligatoires (prénom, installations) et la config rapide (formation,
// relevé de notes, examens, emploi du temps, habitudes), plus la connexion à un Lode qui existe déjà sur un autre ordinateur.
export default {
  // le cadre
  'benvenuto.tasti-mac': '⌥ Espace',
  'benvenuto.tasti-altri': 'Ctrl ⇧ Espace',
  'benvenuto.avanti': 'Suivant',
  'benvenuto.indietro': 'Retour',
  'benvenuto.salta': 'Passer',
  'benvenuto.obbligatorio': 'Obligatoire',
  'benvenuto.facoltativo': 'Facultatif · config rapide',
  // salut
  'benvenuto.ciao-titolo': "Salut.<br>Moi, c'est Lode.",
  'benvenuto.ciao-sotto': "Je vis dans une petite barre en haut de l'écran. En cours, je ne te laisse rien rater ; chez toi, je t'entraîne sur ce que tu es en train d'oublier, et je range tout dans ton Obsidian.",
  'benvenuto.ciao-nota': "D'abord trois choses indispensables (deux minutes, plus les téléchargements). Ensuite, si tu veux, la config rapide.",
  'benvenuto.altro-computer': "J'utilise déjà Lode sur un autre ordinateur",
  'benvenuto.sperimentale': '(expérimental)',
  'benvenuto.iniziamo': 'On commence',
  // un autre ordinateur
  'benvenuto.scegli-vault-cloud': 'Choisis le coffre de Lode dans ton dossier cloud (iCloud Drive, OneDrive, Dropbox, Google Drive).',
  'benvenuto.scegli-vault': 'Choisir le coffre…',
  'benvenuto.password-dati': "Le mot de passe des données de Lode, si tu en as mis un",
  'benvenuto.collego': 'Connexion…',
  'benvenuto.cartella-no': "Je n'arrive pas à utiliser ce dossier.",
  'benvenuto.ricevo-dati': 'Je reçois les données des autres ordinateurs… Lode est déjà utilisable : elles arrivent toutes seules.',
  'benvenuto.inizia': 'Commencer',
  'benvenuto.password-sbagliata': 'Mot de passe incorrect : réessaie.',
  'benvenuto.password-serve': 'Les données de Lode sont protégées par un mot de passe : écris-le ci-dessus.',
  // prénom
  'benvenuto.nome-titolo': "Comment tu t'appelles ?",
  'benvenuto.nome-sotto': 'Juste pour te dire bonjour. Ça reste sur ton ordinateur.',
  'benvenuto.nome-segnaposto': 'Ton prénom',
  'benvenuto.togli-esempio': "Enlève les données d'exemple de « Giulia » (faux examens, notes, cartes et heures de révision). Ce que tu as ajouté toi-même reste.",
  // installations
  'benvenuto.web-titolo': "La version complète de Lode est dans l'appli.",
  'benvenuto.web-sotto': "Dans le navigateur, tu as le relevé de notes, le minuteur, les révisions et les jeux. Obsidian, l'IA sur l'ordinateur, la voix et la transcription des cours sont dans l'appli de bureau.",
  'benvenuto.installa-titolo': 'On prépare ton ordinateur.',
  'benvenuto.installa-sotto': "Trois installations, une seule fois. Ensuite, Lode marche même sans internet, et rien de ce qui est à toi ne sort de l'ordinateur.",
  'benvenuto.obsidian': 'Obsidian',
  'benvenuto.obsidian-cosa': 'là où vivent tes notes : un coffre déjà prêt',
  'benvenuto.cervello': 'Le cerveau local',
  'benvenuto.cervello-cosa': 'Ollama et Qwen3.5 : il lit tes notes, crée des cartes et des définitions, explique et interroge',
  'benvenuto.voce': 'La voix',
  'benvenuto.voce-cosa': '{voce} : commandes vocales, « Répète » et transcription des cours',
  'benvenuto.peso-gb': '{n} Go',
  'benvenuto.peso-mb': '{n} Mo',
  'benvenuto.installa-nota': "Obsidian est gratuit pour un usage personnel et vient de son site officiel. Le cerveau local est choisi selon la mémoire de l'ordinateur.",
  'benvenuto.installa-tutto': 'Tout installer',
  'benvenuto.gia-installato': 'Déjà installé',
  'benvenuto.modello-pronto': '{modello} est déjà prêt',
  'benvenuto.gia-pronta': 'Déjà prête',
  'benvenuto.voce-pronta': '{voce} est prêt',
  'benvenuto.scarico-voce-pct': 'Je télécharge la voix · {p} %',
  'benvenuto.tutto-pronto': 'Obsidian, le cerveau local et la voix sont prêts.',
  'benvenuto.scarico-obsidian': 'Obsidian',
  'benvenuto.scarico-cervello': 'le cerveau local',
  'benvenuto.scarico-voce': 'la voix',
  'benvenuto.scarico-pct': '{cosa} {p} %',
  'benvenuto.scarico-continua-voce': 'Je télécharge encore : {cosa}. Ça continue tout seul, même fenêtre fermée ; la voix reprend dans la barre dès que tu ouvres Lode.',
  'benvenuto.scarico-continua': 'Je télécharge encore : {cosa}. Ça continue tout seul, même fenêtre fermée.',
  'benvenuto.scarico-solo-voce': 'Je télécharge encore : {cosa}. La voix reprend dans la barre dès que tu ouvres Lode.',
  // config rapide
  'benvenuto.veloce-titolo': '{nome}, tu veux la config rapide ?',
  'benvenuto.veloce-sotto': "Parle-moi de ta fac, de tes examens et de tes horaires : dès demain, Lode sait quand tu es en cours, combien il te manque pour le diplôme et quoi réviser avant chaque examen.",
  'benvenuto.veloce-lista': ['Université et formation', 'Ton relevé de notes, collé depuis le site de ta fac ou écrit à la main', 'Les examens à passer, avec les dates', "L'emploi du temps, même depuis le calendrier de la fac (.ics)", 'Comment et quand tu révises'],
  'benvenuto.veloce-nota': "Tout est facultatif, tout se modifie après. Rien ne part sur internet.",
  'benvenuto.facciamolo': "C'est parti",
  // formation
  'benvenuto.corso-titolo': 'Tu étudies où ?',
  'benvenuto.ateneo': 'Université',
  'benvenuto.ateneo-segnaposto': 'Commence à écrire…',
  'benvenuto.corso': 'Formation',
  'benvenuto.corso-segnaposto': 'Licence informatique',
  'benvenuto.tipo': 'Type',
  'benvenuto.tipo-180': 'Licence · 180 crédits',
  'benvenuto.tipo-120': 'Master · 120 crédits',
  'benvenuto.tipo-300': 'Cursus long · 300 crédits',
  'benvenuto.tipo-360': 'Cursus long · 360 crédits',
  'benvenuto.anno': 'Année',
  'benvenuto.anni': ['1re', '2e', '3e', '4e', '5e', '6e', 'Au-delà'],
  'benvenuto.lode-vale': 'La « lode » vaut',
  'benvenuto.lode-nota': 'Ça dépend du règlement : dans le doute, 30',
  // relevé de notes
  'benvenuto.libretto-titolo': 'Les examens que tu as déjà passés',
  'benvenuto.libretto-sotto': "Ouvre ton relevé de notes sur le site de ta fac (ENT, Esse3…), sélectionne tout, copie et colle ici. Je m'occupe du reste. Ou écris-les un par ligne : « Analyse 1, 6 ECTS, 14 ».",
  'benvenuto.libretto-segnaposto': 'Colle ici ton relevé de notes…',
  'benvenuto.leggi-libretto': 'Lire le relevé',
  'benvenuto.leggo-libretto': 'Je lis le relevé…',
  'benvenuto.leggo': 'Je lis…',
  'benvenuto.esami-trovati': { one: '{n} examen trouvé : vérifie et confirme.', other: '{n} examens trouvés : vérifie et confirme.' },
  'benvenuto.esami-non-trovati': "Je n'ai pas trouvé d'examens : essaie de les écrire un par ligne.",
  'benvenuto.col-esame': 'Examen',
  'benvenuto.col-cfu': 'Crédits',
  'benvenuto.col-voto': 'Note',
  'benvenuto.col-data': 'Date',
  'benvenuto.importa': 'Importer',
  'benvenuto.idoneo': 'validé',
  'benvenuto.voto-lode': '{voto}L',
  // examens à passer
  'benvenuto.esame': 'Examen',
  'benvenuto.cfu': 'Crédits',
  'benvenuto.data-appello': "Date de l'examen",
  'benvenuto.togli': 'Enlever',
  'benvenuto.esami-titolo': 'Les examens à passer',
  'benvenuto.esami-sotto': "Avec la date de l'examen, si tu la connais. À partir de là, Lode calcule combien d'heures il te faut chaque jour et te propose des révisions et des jeux quand tu as un moment.",
  'benvenuto.altro-esame': '+ Un autre examen',
  // emploi du temps
  'benvenuto.orario-riga': '{giorni} · {inizio}–{fine}',
  'benvenuto.orario-riga-aula': '{giorni} · {inizio}–{fine} · salle {aula}',
  'benvenuto.nessuna-lezione': 'Pas encore de cours.',
  'benvenuto.orario-titolo': "L'emploi du temps",
  'benvenuto.orario-sotto': "Comme ça, Lode sait quand tu es en cours : la barre se prépare pour le cours, « Répète » et la transcription sont à une touche, et chez toi, il t'entraîne sur ce que tu viens d'entendre.",
  'benvenuto.scrivila': 'Écris-le comme tu le dirais',
  'benvenuto.frase-segnaposto': 'analyse 2 lundi et mercredi 9h-11h salle 7',
  'benvenuto.aggiungi': 'Ajouter',
  'benvenuto.importa-ics': 'Importer le calendrier (.ics)',
  'benvenuto.incolla-orario': "Ou colle l'emploi du temps depuis le site de la fac",
  'benvenuto.orario-segnaposto': "Colle ici le tableau de l'emploi du temps…",
  'benvenuto.leggi-orario': "Lire l'emploi du temps",
  'benvenuto.frase-aiuto': 'Écris le cours, les jours et les heures : « physique lundi 14h-16h salle B2 ».',
  'benvenuto.lezioni-calendario': { one: '{n} cours depuis le calendrier.', other: '{n} cours depuis le calendrier.' },
  'benvenuto.calendario-vuoto': "Je n'ai pas trouvé de cours hebdomadaires dans le calendrier.",
  'benvenuto.leggo-orario': "Je lis l'emploi du temps…",
  'benvenuto.lezioni-trovate': { one: '{n} cours trouvé.', other: '{n} cours trouvés.' },
  'benvenuto.lezioni-non-trovate': "Je n'ai pas trouvé de cours : essaie de les écrire un par un.",
  // habitudes
  'benvenuto.abitudini-titolo': 'Comment tu révises ?',
  'benvenuto.abitudini-sotto': "Lode te propose des révisions, des jeux et des questions éclair à des moments au hasard de la journée, quand tu es sur l'ordinateur. Dis-moi à quelle fréquence, et quand te laisser tranquille.",
  'benvenuto.quando-meglio': 'Quand tu révises le mieux',
  'benvenuto.mattina': 'Matin',
  'benvenuto.pomeriggio': 'Après-midi',
  'benvenuto.sera': 'Soir',
  'benvenuto.notte': 'Nuit',
  'benvenuto.proposte': 'Suggestions de Lode',
  'benvenuto.scelta-mai': 'Jamais',
  'benvenuto.scelta-poco': 'Peu',
  'benvenuto.scelta-normale': 'Normal',
  'benvenuto.scelta-spesso': 'Beaucoup',
  'benvenuto.proposte-nota': "Plus l'examen approche, plus c'est fréquent. Jamais pendant les cours, le focus ou la nuit.",
  'benvenuto.silenzio-dalle': 'Silence de',
  'benvenuto.silenzio-alle': 'à',
  'benvenuto.focus': 'Focus',
  'benvenuto.minuti': '{n} min',
  'benvenuto.ripeti-in-aula': "En cours, active « Répète » toi-même (la dernière minute et demie, seulement en mémoire). Demande au prof si on peut enregistrer.",
  // fin
  'benvenuto.fine-titolo': "C'est fait, {nome}.",
  'benvenuto.fine-sotto': "Lode vit maintenant en haut de l'écran. Passe dessus pour l'ouvrir, maintiens <b>{tasti}</b> pour lui parler, glisse dessus un PDF ou une photo du tableau.",
  'benvenuto.fine-esami': { one: '{fatti} examen dans le relevé, {dare} à passer', other: '{fatti} examens dans le relevé, {dare} à passer' },
  'benvenuto.fine-esami-prossimo': { one: "{fatti} examen dans le relevé, {dare} à passer · le prochain, c'est {nome}", other: "{fatti} examens dans le relevé, {dare} à passer · le prochain, c'est {nome}" },
  'benvenuto.fine-lezioni': { one: '{n} cours par semaine dans ton emploi du temps', other: '{n} cours par semaine dans ton emploi du temps' },
  'benvenuto.fine-proposte': 'Suggestions : {quante}',
  'benvenuto.quante-mai': 'jamais',
  'benvenuto.quante-poco': 'peu',
  'benvenuto.quante-normale': 'normal',
  'benvenuto.quante-spesso': 'beaucoup',
  'benvenuto.apri-lode': 'Ouvrir Lode',
};
