// Textes de l'appli de bureau (français) : fenêtres du système, menu de l'icône, notifications et messages du
// processus principal (desktop/*.mjs) qui arrivent à l'étudiant.
export default {
  // main.mjs : fenêtres du système
  'desktop.non-ci-sono-riuscito': "Je n'y suis pas arrivé.",
  'desktop.benvenuto-in-lode': 'Bienvenue dans Lode',
  'desktop.dove-tenere-il-vault': 'Où garder le coffre',
  'desktop.usa-questa-cartella': 'Utiliser ce dossier',
  'desktop.non-e-andata': "Ça n'a pas marché.",
  'desktop.vault-con-sincronizzazione': 'Avec la synchro, on change de coffre depuis « Synchronise entre tes ordinateurs »',
  'desktop.vault-con-sincronizzazione-dettaglio': '« Arrêter sur cet ordinateur » sort le coffre du dossier cloud.',
  'desktop.scegli-il-vault': 'Choisis le coffre Obsidian',
  'desktop.usa-questo-vault': 'Utiliser ce coffre',
  'desktop.cartella-non-usabile': "Lode n'arrive pas à utiliser le dossier {cartella}",
  'desktop.cartella-protetta-windows': "Windows le protège sans doute (Sécurité Windows › Protection contre les ransomware › Dispositif d'accès contrôlé aux dossiers) ou l'antivirus bloque Lode. Autorise Lode, ou choisis un autre dossier.",
  'desktop.scegli-altra-cartella': 'Choisir un autre dossier',
  'desktop.riprova': 'Réessayer',
  'desktop.non-ora': 'Pas maintenant',
  'desktop.obsidian-pronto': 'Obsidian est prêt sur ton coffre',
  'desktop.modello-pronto': '{modello} est prêt',
  'desktop.ponte-non-partito': "Le pont avec les agents n'a pas démarré : redémarre Lode.",
  'desktop.agente-togliere': 'Retirer Lode de la configuration de {agente} ?',
  'desktop.agente-collegare': 'Connecter {agente} à Lode ?',
  'desktop.agente-toglie-righe': 'Lode retire seulement ses lignes dans :\n{file}',
  'desktop.agente-aggiunge-righe': 'Lode ajoute seulement ses lignes, sans toucher au reste, dans :\n{file}',
  'desktop.agente-manda-eventi': "{agente} enverra à Lode, sur cet ordinateur, les événements des sessions (fichiers touchés, commandes, fin du tour). Lode ne répond pas et ne décide rien. ",
  'desktop.agente-file-com-era': "Le fichier tel qu'il était reste dans {file}.",
  'desktop.togli': 'Retirer',
  'desktop.collega': 'Connecter',
  'desktop.annulla': 'Annuler',
  // main.mjs : le menu de l'icône
  'desktop.menu-avvisami-versioni': 'Me prévenir des nouvelles versions',
  'desktop.menu-aggiornamenti-automatici': 'Mises à jour automatiques',
  'desktop.menu-riavvia-con': 'Redémarrer avec Lode {versione}',
  'desktop.menu-scarica': 'Télécharger Lode {versione}…',
  'desktop.menu-apri': 'Ouvrir Lode ({tasti})',
  'desktop.tasti-apri-mac': '⌥ Espace',
  'desktop.tasti-apri': 'Ctrl+Maj+Espace',
  'desktop.menu-quadro': "La vue d'ensemble : relevé de notes, examens, révisions",
  'desktop.menu-rifai-configurazione': 'Refaire la configuration…',
  'desktop.menu-apri-vault-obsidian': 'Ouvrir le coffre dans Obsidian',
  'desktop.menu-mostra-vault': 'Afficher le coffre dans le dossier',
  'desktop.menu-altro-vault': 'Utiliser un autre coffre…',
  'desktop.menu-avvio-accensione': "Lancer Lode au démarrage",
  'desktop.menu-icona-mac': 'Icône de Lode dans Applications',
  'desktop.menu-icona-win': 'Icône de Lode dans le menu Démarrer et sur le bureau',
  'desktop.menu-icona-linux': 'Icône de Lode dans le menu des applications',
  'desktop.menu-esci': 'Quitter Lode',
  // sincronizza.mjs : la synchro entre les ordinateurs
  'desktop.sync-file-occupato': 'Un fichier est utilisé par un autre programme : ferme-le et réessaie. Le coffre d\'avant est intact.',
  'desktop.sync-file-occupato-nome': 'Un fichier est utilisé par un autre programme ({file}) : ferme-le et réessaie. Le coffre d\'avant est intact.',
  'desktop.sync-disco-pieno': "Le disque du dossier cloud est plein. Le coffre d'avant est intact.",
  'desktop.sync-permesso': "Lode n'a pas la permission de lire ou d'écrire un fichier. Le coffre d'avant est intact.",
  'desktop.sync-permesso-nome': "Lode n'a pas la permission de lire ou d'écrire un fichier ({file}). Le coffre d'avant est intact.",
  'desktop.sync-copia-diversa': "La copie de {file} n'est pas identique : réessaie. Le coffre d'avant est intact.",
  'desktop.sync-copia-non-riuscita': "La copie du coffre n'a pas marché : réessaie. Le coffre d'avant est intact.",
  'desktop.sync-sto-accendendo': "J'active déjà la synchro : attends que ça finisse.",
  'desktop.sync-cartella-titolo': 'Le dossier qui se synchronise',
  'desktop.sync-sincronizza-qui': 'Synchroniser ici',
  'desktop.sync-spostamento-con-password': 'Le déplacement avait commencé avec le mot de passe : écris-le à nouveau.',
  'desktop.sync-dati-occupati': 'Le fichier des données de Lode est utilisé par un autre programme (un antivirus ?) : réessaie dans un moment.',
  'desktop.sync-diario-illeggibile': "Le journal de Lode sur cet ordinateur est illisible.",
  'desktop.sync-controllo-altro-computer': 'Je vérifie si un autre ordinateur synchronise déjà ce coffre…',
  'desktop.sync-aspetto-dati': "J'attends que les données de Lode arrivent du cloud (le fichier des données n'est pas encore lisible) : réessaie dans un moment.",
  'desktop.sync-altra-password': 'Sur ce coffre, la synchro est déjà activée avec un autre mot de passe : écris celui-là.',
  'desktop.sync-gia-con-password': 'Sur ce coffre, la synchro est déjà activée avec un mot de passe : écris-le.',
  'desktop.sync-non-accendo': "Je n'arrive pas à activer la synchro ici.",
  'desktop.sync-cartella-dentro-vault': "Ce dossier est dans le coffre : choisis-en un en dehors, par exemple le dossier iCloud Drive, OneDrive ou Dropbox.",
  'desktop.sync-dati-non-ancora': "Les données de Lode ne sont pas encore lisibles (dossier inaccessible ?) : réessaie dans un moment.",
  'desktop.sync-copio-vault': 'Je copie le coffre…',
  'desktop.sync-copio-vault-file': { one: 'Je copie le coffre… {n} fichier', other: 'Je copie le coffre… {n} fichiers' },
  'desktop.sync-cifro-pubblico': 'Je chiffre et je publie les données de Lode…',
  'desktop.sync-pubblico': 'Je publie les données de Lode…',
  'desktop.sync-non-creo-dati': "Je n'arrive pas à créer les données de Lode dans le dossier cloud. Le coffre d'avant est intact.",
  'desktop.sync-vault-nel-cloud': 'Le coffre de Lode dans le dossier cloud',
  'desktop.sync-non-e-vault-sincronizzato': "Ce dossier ne contient pas de coffre Lode synchronisé : choisis le dossier « Lode » dans le dossier cloud (sur l'autre ordinateur : « Synchronise entre tes ordinateurs »).",
  'desktop.sync-diario-altro-vault': "Sur cet ordinateur, Lode utilise déjà le journal d'un autre coffre : d'abord « Arrêter sur cet ordinateur ».",
  'desktop.sync-password-sbagliata-di-nuovo': 'Mauvais mot de passe : écris-le à nouveau.',
  'desktop.sync-password-vecchia': "C'est l'ancien mot de passe : il a changé sur un autre ordinateur, écris le nouveau.",
  'desktop.sync-lode-piu-nuova': 'Ce coffre a été protégé par une version plus récente de Lode : mets-la à jour.',
  'desktop.sync-gruppo-manomesso': "Le mot de passe est bon, mais le fichier du groupe dans le dossier cloud a été modifié de l'extérieur : je ne l'utilise pas. Vérifie le dossier cloud.",
  'desktop.sync-gruppo-in-chiaro': "Le groupe dans le dossier cloud n'est pas chiffré : sur l'autre ordinateur, la synchro est sans mot de passe, ou le fichier du groupe a été trafiqué. Si tu n'as pas mis de mot de passe sur l'autre ordinateur, réessaie sans.",
  'desktop.sync-password-sbagliata': 'Mauvais mot de passe.',
  'desktop.sync-adesso-non-si-puo': "Ce n'est pas possible pour l'instant.",
  'desktop.sync-cartella-in-cloud': 'Ce dossier est dans un dossier cloud : pour synchroniser, utilise « Synchronise entre tes ordinateurs ».',
  'desktop.sync-fuori-dal-vault': 'Choisis un dossier en dehors du coffre actuel.',
  'desktop.sync-non-sposto-dati': "Je n'arrive pas à déplacer les données de Lode dans ce dossier. Le coffre d'avant est intact.",
  'desktop.sync-riprova-tra-poco': "Ce n'est pas possible pour l'instant : réessaie dans un moment.",
  'desktop.sync-password-corta': 'Le mot de passe doit avoir au moins 8 caractères.',
  'desktop.sync-diario-illeggibile-riprova': "Le journal de Lode sur cet ordinateur est illisible : d'abord « Réessayer ».",
  'desktop.sync-non-accesa': "Sur cet ordinateur, la synchro n'est pas activée.",
  'desktop.sync-vault-spostato-scegli': "Le coffre n'est plus là où Lode le cherchait : si tu l'as déplacé, utilise « Retrouver le coffre » et choisis le dossier déplacé.",
  'desktop.sync-dove-fuori-cloud': 'Où garder le coffre, en dehors du dossier cloud',
  'desktop.sync-tieni-qui': 'Garder le coffre ici',
  'desktop.sync-fuori-dal-cloud': 'Choisis un dossier en dehors du dossier cloud.',
  'desktop.sync-vault-spostato': "Le coffre n'est plus là où Lode le cherchait : si tu l'as déplacé, utilise « Retrouver le coffre ».",
  'desktop.sync-cambio-in-arrivo': "Les dernières modifications de cet ordinateur ne sont pas encore dans le dossier cloud (un changement arrive des autres ordinateurs) : réessaie dans un moment.",
  'desktop.sync-smetti-serve-password': "Les modifications faites en pause resteraient seulement sur cet ordinateur : écris le mot de passe avant d'arrêter (ou « J'ai oublié le mot de passe »).",
  'desktop.sync-note-non-scaricate': "Certaines notes ne sont pas téléchargées sur cet ordinateur ({note}) : ouvre-les ou télécharge-les depuis le service cloud, puis réessaie.",
  'desktop.sync-note-non-scaricate-altre': "Certaines notes ne sont pas téléchargées sur cet ordinateur ({note} et {n} autres) : ouvre-les ou télécharge-les depuis le service cloud, puis réessaie.",
  'desktop.sync-copio-fuori-cloud': 'Je copie le coffre en dehors du dossier cloud…',
  // progetto.mjs : « suis le projet », le résumé « C'est fait. En clair » et la confirmation des commandes
  'desktop.progetto-elenco': '{primi} et {ultimo}',
  'desktop.progetto-elenco-altre': '{primi} et {n} autres',
  'desktop.progetto-elenco-altri': '{primi} et {n} autres',
  'desktop.progetto-righe-piu-meno': { one: '{n} ligne en plus et {meno} en moins', other: '{n} lignes en plus et {meno} en moins' },
  'desktop.progetto-righe-piu': { one: '{n} ligne en plus', other: '{n} lignes en plus' },
  'desktop.progetto-righe-meno': { one: '{n} ligne en moins', other: '{n} lignes en moins' },
  'desktop.progetto-solo-spazi': 'seulement des espaces ou des retours à la ligne',
  'desktop.progetto-file-nuovo': { one: 'nouveau fichier ({n} ligne)', other: 'nouveau fichier ({n} lignes)' },
  'desktop.progetto-file-tolto': 'supprimé',
  'desktop.progetto-funzioni-nuove': { one: 'nouvelle fonction {elenco}', other: 'nouvelles fonctions {elenco}' },
  'desktop.progetto-funzioni-cambiate': { one: 'modifiée : {elenco}', other: 'modifiées : {elenco}' },
  'desktop.progetto-funzioni-tolte': { one: 'supprimée : {elenco}', other: 'supprimées : {elenco}' },
  'desktop.progetto-file': '{file} : {cosa}.',
  'desktop.progetto-include-nuovi': { one: 'Nouveau : {elenco}.', other: 'Nouveaux : {elenco}.' },
  'desktop.progetto-esito-compila': 'compile',
  'desktop.progetto-esito-non-compila': 'ne compile pas',
  'desktop.progetto-esito-sintassi-a-posto': 'syntaxe correcte',
  'desktop.progetto-esito-errore-di-sintassi': 'erreur de syntaxe',
  'desktop.progetto-esito-make-riuscito': 'make réussi',
  'desktop.progetto-esito-make-non-riuscito': 'make échoué',
  'desktop.progetto-prove-su': { one: '{n} test sur {tot}', other: '{n} tests sur {tot}' },
  'desktop.progetto-prova-non-partita': "le test n'a pas démarré",
  'desktop.progetto-inizio-alle': { one: 'À {ora}, {n} fichier a changé (+{piu} −{meno}).', other: 'À {ora}, {n} fichiers ont changé (+{piu} −{meno}).' },
  'desktop.progetto-inizio-dalle': { one: 'De {da} à {a}, {n} fichier a changé (+{piu} −{meno}).', other: 'De {da} à {a}, {n} fichiers ont changé (+{piu} −{meno}).' },
  'desktop.progetto-provato-si': '**Testé ?** Oui : c\'est le code testé à {ora} ({esito}).',
  'desktop.progetto-provato-no-codice': "**Testé ?** Non, mais ici seuls des fichiers qui ne sont pas du code ont changé.",
  'desktop.progetto-provato-no': "**Testé ?** Non : après la dernière modification ({ora}), personne n'a compilé avec Lode.",
  'desktop.progetto-nota-chi': 'Je ne sais pas qui a écrit ces lignes.',
  'desktop.progetto-altri-file': { one: 'Et {n} autre fichier.', other: 'Et {n} autres fichiers.' },
  'desktop.progetto-nessuna-cartella': "Je n'ai reçu aucun dossier.",
  'desktop.progetto-non-trovo-cartella': 'Je ne trouve pas ce dossier.',
  'desktop.progetto-cartella-non-file': 'Choisis un dossier, pas un fichier.',
  'desktop.progetto-radice-disco': "C'est la racine du disque : choisis le dossier du projet seul (par exemple tp3).",
  'desktop.progetto-tutta-la-home': 'Ce dossier contient tout ton dossier personnel : choisis le dossier du projet seul.',
  'desktop.progetto-e-il-vault': "C'est le coffre de Lode (ou il le contient) : choisis le dossier du projet.",
  'desktop.progetto-dati-di-lode': "C'est le dossier où Lode garde ses données : choisis celui du projet.",
  'desktop.progetto-troppi-progetti': "Je suis déjà {n} projets : arrête d'en suivre un (« arrête de suivre … »), puis réessaie.",
  'desktop.progetto-cartella-illeggibile': "Je n'arrive pas à lire ce dossier.",
  'desktop.progetto-troppi-file': 'Il y a plus de {n} fichiers ici : choisis le dossier du projet seul (par exemple tp3).',
  'desktop.progetto-non-seguo': 'Je ne suis pas ce projet.',
  'desktop.progetto-versione-scaduta': "Cette version n'existe plus : Lode garde les versions pendant 30 jours.",
  'desktop.progetto-file-non-seguito': 'Ce fichier ne fait pas partie de ceux que je suis.',
  'desktop.progetto-file-illeggibile': "Je n'arrive pas à lire le fichier.",
  'desktop.progetto-poi-per-ogni-prova': 'Puis, pour chaque test .in → .out :\n{comandi}',
  'desktop.progetto-senza-prove': "Je ne lance pas le programme : il n'y a pas de tests .in/.out.",
  'desktop.progetto-resto-non-mostro': '(je ne montre pas la suite)',
  'desktop.progetto-smesso-durante-prova': "J'ai arrêté de suivre le projet pendant le test.",
  'desktop.progetto-scegli-cartella': 'Choisis le dossier du projet',
  'desktop.progetto-segui-cartella': 'Suivre ce dossier',
  'desktop.progetto-scegli-di-nuovo': 'Choisis à nouveau le dossier (« suis le projet »).',
  'desktop.progetto-conferma-aperta': "Une fenêtre de confirmation est déjà ouverte : réponds d'abord à celle-là.",
  'desktop.progetto-eseguira': 'Lode exécutera cette commande dans le dossier {cartella}.',
  'desktop.progetto-come-terminale': "C'est comme la lancer depuis le terminal : le programme tourne sur ton ordinateur.",
  'desktop.progetto-esegui-sempre': 'Toujours exécuter pour ce projet',
  // esegui.mjs : tester le code du projet
  'desktop.esegui-riapri': "Si tu viens de l'ajouter au PATH, quitte Lode (depuis le menu) et rouvre-le.",
  'desktop.esegui-manca-c-win': "Je ne trouve pas de compilateur C. Installe MSYS2 (msys2.org), ouvre « MSYS2 UCRT64 » et écris `pacman -S mingw-w64-ucrt-x86_64-gcc` : Lode le trouve tout seul dans C:\\msys64\\ucrt64\\bin. Sinon, WinLibs (winlibs.com) ou WSL. Lode ne télécharge rien à ta place.",
  'desktop.esegui-manca-c-mac': "Je ne trouve pas de compilateur C. Ouvre le Terminal et écris `xcode-select --install` : ça installe le clang d'Apple. Puis réessaie.",
  'desktop.esegui-manca-c-linux': 'Je ne trouve pas de compilateur C. Installe gcc (par exemple `sudo apt install build-essential`), puis réessaie.',
  'desktop.esegui-manca-python-win': 'Je ne trouve pas Python 3. Installe-le depuis python.org (coche « Add python.exe to PATH ») ou depuis le Microsoft Store, puis réessaie.',
  'desktop.esegui-manca-python': 'Je ne trouve pas Python 3. Installe-le (python.org, ou ton gestionnaire de paquets), puis réessaie.',
  'desktop.esegui-manca-java': 'Je ne trouve pas de JDK (javac et java). Installes-en un, par exemple Temurin sur adoptium.net, puis réessaie.',
  'desktop.esegui-manca-make-win': "Il y a un Makefile mais je ne trouve pas make. Avec MSYS2, dans « MSYS2 UCRT64 » : `pacman -S mingw-w64-ucrt-x86_64-make`. Ou enlève le Makefile et Lode compile tout seul les fichiers .c.",
  'desktop.esegui-manca-make': 'Il y a un Makefile mais je ne trouve pas make. Installe-le (sur Mac : `xcode-select --install`), puis réessaie.',
  'desktop.esegui-manca-programma': 'Il manque un programme pour tester le code.',
  'desktop.esegui-senza-prove': 'Je ne trouve pas de tests .in/.out : je compile seulement, je ne lance pas le programme.',
  'desktop.esegui-make-prove': { one: 'Avec le Makefile, je ne lance pas le test .in/.out : je ne sais pas quel programme il crée.', other: 'Avec le Makefile, je ne lance pas les {n} tests .in/.out : je ne sais pas quel programme il crée.' },
  'desktop.esegui-poi-prove': { one: 'puis le test (fichier .in → .out attendu)', other: 'puis les {n} tests (fichiers .in → .out attendus)' },
  'desktop.esegui-poi-prove-in': { one: 'puis le test dans {cartella}/ (fichier .in → .out attendu)', other: 'puis les {n} tests dans {cartella}/ (fichiers .in → .out attendus)' },
  'desktop.esegui-senza-programma': '{prove} ; {n} sans programme clair',
  'desktop.esegui-make-leggi': 'make exécute les commandes écrites dans le Makefile : lis-le avant de confirmer.',
  'desktop.esegui-make-assente': 'Il y a un Makefile mais je ne trouve pas make : je compile moi-même les fichiers .c.',
  'desktop.esegui-niente-codice': 'Je ne trouve pas de code C, Python ou Java à tester dans ce dossier.',
  'desktop.esegui-virgolette': 'Les guillemets ne sont pas fermés.',
  'desktop.esegui-invisibili': 'La commande contient des caractères invisibles (retour à la ligne, contrôle ou sens du texte) : réécris-la à la main.',
  'desktop.esegui-comando-vuoto': 'La commande est vide.',
  'desktop.esegui-comando-illeggibile': 'La commande est illisible.',
  'desktop.esegui-non-trovo-programma': 'Je ne trouve pas le programme « {programma} ».',
  'desktop.esegui-bat': "Je ne lance pas les fichiers .bat et .cmd : écris la commande qu'ils contiennent.",
  'desktop.esegui-compilazione-lenta': "La compilation n'a pas fini en {n} secondes.",
  'desktop.esegui-prova-senza-programma': 'je ne sais pas à quel programme il correspond',
  'desktop.esegui-programma-non-creato': "La commande n'a pas créé le programme à tester.",
  'desktop.esegui-prova-illeggibile': "je n'arrive pas à lire les fichiers du test",
  // moodle.mjs : Moodle en lecture seule
  'desktop.moodle-risponde': 'Moodle répond {stato}',
  'desktop.moodle-errore': 'erreur de Moodle',
  'desktop.moodle-sito-risponde': 'le site répond {stato}',
  'desktop.moodle-non-e-moodle': "ce n'est pas un Moodle, ou le service pour les applis est désactivé",
  'desktop.moodle-non-collegato': "Moodle n'est pas connecté",
  'desktop.moodle-accesso-non-riuscito': 'connexion échouée',
  'desktop.moodle-accedi-a': 'Connecte-toi à {sito}',
  'desktop.moodle-risposta-non-valida': 'réponse de Moodle non valide',
  'desktop.moodle-tempo-scaduto': 'délai dépassé',
  'desktop.moodle-file-non-trovato': 'fichier introuvable',
  'desktop.moodle-file-troppo-grande': 'fichier trop gros',
  'desktop.moodle-file-non-su-moodle': "le fichier n'est pas sur Moodle",
  // installa.mjs : Obsidian et le cerveau local (Ollama)
  'desktop.installa-download-non-riuscito': 'téléchargement échoué ({stato})',
  'desktop.installa-non-firmato': "L'installeur de {nome} n'a pas la signature officielle de {nome}, donc je ne l'ai pas installé. Réessaie plus tard, ou télécharge-le toi-même depuis le site officiel.",
  'desktop.installa-versione-obsidian': "version d'Obsidian inconnue",
  'desktop.installa-scarico-obsidian': 'Je télécharge Obsidian {versione}',
  'desktop.installa-scarico-obsidian-mb': 'Je télécharge Obsidian {versione} · {mb} Mo',
  'desktop.installa-installo-obsidian': "J'installe Obsidian",
  'desktop.installa-obsidian-installato': 'Obsidian {versione} installé',
  'desktop.installa-perche-4b': 'rapide même sans carte graphique : définitions, cartes, jeux et oral',
  'desktop.installa-perche-35b': "le meilleur, et rapide comme un petit modèle, pour les ordinateurs avec beaucoup de mémoire",
  'desktop.installa-perche-9b': "explique bien et tient l'oral",
  'desktop.installa-perche-memoria': 'pour {gb} Go de mémoire : définitions, cartes, jeux et oral',
  'desktop.installa-ollama-non-avviato': "Ollama n'a pas démarré",
  'desktop.installa-ollama-linux': 'Sur Linux, installe Ollama depuis ollama.com avec leur script, puis reviens ici.',
  'desktop.installa-scarico-ollama-mb': 'Je télécharge Ollama · {mb} Mo',
  'desktop.installa-installo-ollama': "J'installe Ollama",
  'desktop.installa-avvio-ollama': 'Je lance Ollama',
  'desktop.installa-ollama-non-risponde': 'Ollama ne répond pas',
  'desktop.installa-scarico-modello': 'Je télécharge {nome} · {fatti} sur {totale} Go',
  'desktop.installa-modello-pronto': '{nome} prêt',
  'desktop.installa-modello-assente': "Le modèle {modello} n'est pas installé",
  'desktop.installa-modello-non-risponde': 'Le modèle local ne répond pas',
  // aggiorna.mjs : les nouvelles versions de Lode
  'desktop.aggiorna-github-risponde': 'GitHub répond {stato}',
  'desktop.aggiorna-non-installato': "La mise à jour ne s'est pas installée. Réessaie, ou ferme Lode : elle s'installe à la fermeture.",
  'desktop.aggiorna-non-installato-perche': "La mise à jour ne s'est pas installée : {motivo}. Réessaie, ou ferme Lode : elle s'installe à la fermeture.",
  'desktop.aggiorna-niente-pronto': "Il n'y a pas de mise à jour prête à installer.",
  'desktop.aggiorna-dove-scaricare': 'Je ne sais pas encore où la télécharger : réessaie dans un moment.',
  // voce-onnx.mjs et voce-onnx-motore.mjs : la voix Parakeet ONNX
  'desktop.voce-modello-illeggibile': "Je n'arrive pas à lire le modèle de la voix : réessaie dans un moment.",
  'desktop.voce-spazio': "Pour la voix Parakeet, il faut environ {serve} Mo libres sur le disque, il y en a {liberi}.",
  'desktop.voce-rete': "Je n'arrive pas à télécharger la voix : vérifie ta connexion et réessaie. ({dettaglio})",
  'desktop.voce-rete-stato': "Je n'arrive pas à télécharger la voix ({stato}) : réessaie plus tard.",
  'desktop.voce-file-troppo-grande': 'Le fichier de la voix est plus gros que prévu.',
  'desktop.voce-interrotto': "Le téléchargement de la voix s'est interrompu : il reprendra d'ici la prochaine fois. ({dettaglio})",
  'desktop.voce-impronta': "Le fichier de la voix « {file} » n'est pas le bon (empreinte SHA256 différente) : je l'ai supprimé.",
  'desktop.voce-addon': 'Le programme de la voix (sherpa-onnx) ne se charge pas sur cet ordinateur.',
  'desktop.voce-modello-rovinato': 'Le modèle de Parakeet ne se charge pas (un fichier est peut-être abîmé).',
  'desktop.voce-pezzo-non-trascritto': "Parakeet n'a pas réussi à transcrire ce morceau.",
  'desktop.voce-motore-chiuso': "Le moteur de la voix s'est fermé d'un coup.",
  'desktop.voce-motore-chiuso-codice': "Le moteur de la voix s'est fermé d'un coup ({codice}).",
  'desktop.voce-motore-non-risponde': 'Le moteur de la voix ne répond pas.',
  // agenti-collegamenti.mjs : la connexion avec les agents de programmation
  'desktop.agenti-claude-eventi': ['prompt', 'modifications et commandes', 'fin du tour', 'notifications'],
  'desktop.agenti-claude-nota': 'Les hooks valent à partir de la prochaine session (ou revois-les dans /hooks).',
  'desktop.agenti-codex-eventi': ['prompt', 'modifications (apply_patch) et commandes', 'fin du tour'],
  'desktop.agenti-codex-nota': "À la prochaine session, Codex te demande d'approuver les nouveaux hooks : fais-le avec /hooks.",
  'desktop.agenti-gemini-eventi': ['prompt', 'outils (fichiers et commandes)', 'fin de la réponse', 'notifications'],
  'desktop.agenti-gemini-nota': 'Valable à partir de la prochaine session de Gemini CLI.',
  'desktop.agenti-cursor-eventi': ['prompt', 'fichiers modifiés', 'commandes', "réponse de l'agent"],
  'desktop.agenti-cursor-nota': "Redémarre Cursor pour qu'il lise les hooks. Cursor ne donne pas le code de sortie des commandes : on voit les tests lancés, pas le résultat.",
  'desktop.agenti-copilot-eventi': ['prompt', 'outils (fichiers et commandes)', 'fin du tour', 'notifications'],
  'desktop.agenti-copilot-nota': "Un seul fichier de Lode dans ~/.copilot/hooks : valable à partir de la prochaine session. Copilot n'envoie pas le dernier message de l'agent.",
  'desktop.agenti-windsurf-eventi': ['prompt', 'code écrit', 'commandes', 'réponse de Cascade'],
  'desktop.agenti-windsurf-nota': 'Valable à partir de la prochaine conversation de Cascade. Windsurf ne donne pas le code de sortie des commandes.',
  'desktop.agenti-qwen-eventi': ['prompt', 'outils (fichiers et commandes)', 'fin du tour', 'notifications'],
  'desktop.agenti-qwen-nota': 'Valable à partir de la prochaine session de Qwen Code.',
  'desktop.agenti-opencode-eventi': ['fichiers modifiés', 'commandes', 'fin du tour'],
  'desktop.agenti-opencode-nota': 'Un plugin de Lode dans ~/.config/opencode/plugins : valable au prochain lancement d\'OpenCode. Il lit, c\'est tout : il ne touche pas aux réponses.',
  'desktop.agenti-kilo-eventi': ['fichiers modifiés', 'commandes', 'fin du tour'],
  'desktop.agenti-kilo-nota': "Le plugin est celui d'OpenCode (Kilo en est un fork) : valable au prochain lancement. Format des événements à vérifier sur ta version.",
  'desktop.agenti-aider-eventi': ['fin de la réponse (sans détails)'],
  'desktop.agenti-aider-nota': "Aider prévient seulement qu'il a fini de répondre, sans dire ce qu'il a touché : les fichiers modifiés, c'est « suis le projet » qui les voit.",
  'desktop.agenti-non-json': "ce n'est pas un objet JSON",
  'desktop.agenti-file-non-di-lode': "il y a déjà un fichier avec ce nom qui n'est pas de Lode",
  'desktop.agenti-notifiche-aider': "les notifications d'Aider sont déjà là : Lode ne les écrase pas",
  'desktop.agenti-file-illeggibile': '{file} est illisible ({motivo}) : je n\'y touche pas. Répare-le ou connecte à la main.',
  'desktop.agenti-altre-righe': { one: 'et {n} autre ligne', other: 'et {n} autres lignes' },
  'desktop.agenti-test-non-rilanciati': "Il dit que les tests passent, mais il ne les a pas relancés après sa dernière modification.",
  'desktop.agenti-test-non-lanciati': "Il dit que les tests passent, mais dans ce tour je ne l'ai pas vu les lancer.",
  'desktop.agenti-test-toccati': "Il a modifié les tests ({file}) pendant qu'ils échouaient : vérifie qu'il ne les a pas rendus plus faciles.",
  // collegamento.mjs : Lode lancé par le code (icône, lancement au démarrage, autorisations du Mac)
  'desktop.permesso-audio-computer': "Lode écoute le son de l'ordinateur seulement quand tu transcris un cours en visio. Le son ne reste jamais sur l'ordinateur : seul le texte va dans la note.",
  'desktop.permesso-microfono': "Lode utilise le micro quand tu lui parles, pour « Répète » en amphi et pour transcrire les cours que tu choisis. Le son ne reste jamais sur l'ordinateur.",
  'desktop.icona-non-creata': "je n'arrive pas à créer {file}",
};
