// Le registre dans le coffre (français) : les lignes du journal du projet, le tableau « Cosa so davvero » et la
// section « Informatica » de Lode/Memoria.md. Les titres des sections (« ## Cosa ho capito », « ## Cosa so davvero », « ## Informatica »),
// les propriétés et les marques %% lode:… %% ne sont PAS ici : ce sont des noms du coffre, que le code retrouve.
export default {
  'diario.concetto-for': 'Boucle for',
  'diario.concetto-while': 'Boucle while',
  'diario.concetto-do-while': 'Boucle do-while',
  'diario.concetto-ritroso': 'Compte à rebours',
  'diario.concetto-array': 'Tableaux',
  'diario.concetto-divisione-intera': 'Division entière',
  'diario.concetto-resto': 'Reste avec les négatifs',
  'diario.concetto-cast': 'Cast en double',
  'diario.concetto-incremento': 'i++ et ++i',
  'diario.concetto-switch': 'switch et break',
  'diario.concetto-cortocircuito': '&& et || en court-circuit',
  'diario.concetto-else-pendente': 'else ambigu (dangling else)',
  'diario.concetto-puntatori': 'Passage par adresse',
  'diario.concetto-parametri': 'Passage par valeur',
  'diario.concetto-visibilita': 'Variables dans les blocs',
  'diario.concetto-char': 'char et codes ASCII',
  'diario.concetto-ricorsione': 'Récursivité',
  'diario.concetto-annidati': 'Boucles imbriquées',
  'diario.concetto-break-continue': 'break et continue',
  'diario.concetto-ternario': 'Opérateur ternaire',
  'diario.concetto-printf': 'printf et formats',
  'diario.elenco-e': '{prima} et {ultimo}',
  'diario.errore-titolo': '« {titolo} »',
  'diario.errore-generico': 'erreur',
  'diario.passo-dove': '« où regarder »',
  'diario.passo-cosa': '« ce que ça veut dire »',
  'diario.passi-visti': { one: 'vu {passi}', other: 'vu {passi}' },
  'diario.funzione-nuova': 'nouvelle : {nome}',
  'diario.funzione-nuova-in': 'nouvelle : {nome} dans {file}',
  'diario.funzione-cambiata': 'modifiée : {nome}',
  'diario.funzione-cambiata-in': 'modifiée : {nome} dans {file}',
  'diario.funzione-tolta': 'supprimée : {nome}',
  'diario.funzione-tolta-in': 'supprimée : {nome} dans {file}',
  'diario.file-nuovo': 'nouveau : {file}',
  'diario.file-tolto': 'supprimé : {file}',
  'diario.cambiati-file': { one: '{n} fichier modifié', other: '{n} fichiers modifiés' },
  'diario.cambiato-codice': 'Code modifié',
  'diario.altre-modifiche': { one: 'et {n} autre modification', other: 'et {n} autres modifications' },
  'diario.chi-ha-scritto': "qui l'a écrit : je ne sais pas",
  'diario.cambiato-durante': 'le code a changé pendant le test',
  'diario.prova-non-compila': 'Test : ✗ ne compile pas',
  'diario.prova-non-compila-errore': 'Test : ✗ ne compile pas, {errore}',
  'diario.prova-non-partita': 'Test : pas lancé',
  'diario.prova-ok': 'Test : ✓ compile · {prove} · {stato}',
  'diario.prove-conto': '{ok}/{tot} tests',
  'diario.nessun-caso': 'aucun cas de test',
  'diario.ma-cambiato': 'mais le code a changé pendant le test',
  'diario.codice-provato': 'code testé',
  'diario.prova-ko': 'Test : ✗ compile · {ok}/{tot} tests',
  'diario.n-prove': { one: '{n} test', other: '{n} tests' },
  'diario.nessuna-prova': 'aucun test',
  'diario.errori-risolti': { one: '{n} erreur corrigée', other: '{n} erreurs corrigées' },
  'diario.n-errori': { one: '{n} erreur', other: '{n} erreurs' },
  'diario.n-risolti': { one: '{n} corrigée', other: '{n} corrigées' },
  'diario.correzioni-viste': 'corrections vues : {n}',
  'diario.oggi': "Aujourd'hui : {parti}",
  'diario.ultima-non-provata': 'dernière modification pas testée',
  'diario.smette': 'Lode arrête de suivre {progetto}',
  'diario.segue': 'Lode suit {progetto}',
  'diario.errore': 'Erreur : {errore}',
  'diario.correzione-vista': 'Correction vue : {errore}',
  'diario.spiegate': 'Expliquées : {spiegate} sur {totale}',
  'diario.spiegate-rivedere': 'Expliquées : {spiegate} sur {totale} ; à revoir : {nomi}',
  'diario.ieri': 'hier',
  'diario.giorni-fa': { one: 'il y a {n} jour', other: 'il y a {n} jours' },
  'diario.stato-da-rifare': 'à refaire',
  'diario.stato-sicuro': 'acquis',
  'diario.stato-mai-fatto': 'jamais fait',
  'diario.diari-dei-progetti': 'Journaux des projets :',
  'diario.tabella-nota': "Les comptes de Lode sur les exercices « Qu'est-ce que ça affiche ? », sans IA. « À refaire » veut dire qu'il est temps de le réviser.",
  'diario.tabella-testa': '| Notion | Exercices | Du premier coup | Dernière fois | État |',
  'diario.nessun-esercizio': "Pas encore d'exercice. Écris « qu'est-ce que ça affiche » dans la barre : 5 questions d'une minute.",
  'diario.errori-frequenti': 'Les erreurs que tu croises le plus : {errori}.',
  'diario.sbagli-spesso': 'Tu te trompes souvent sur : {sbagli}.',
  'diario.memoria-stampa': { one: "« Qu'est-ce que ça affiche ? » : {n} exercice, {giuste} % justes du premier coup.", other: "« Qu'est-ce que ça affiche ? » : {n} exercices, {giuste} % justes du premier coup." },
  'diario.da-rifare': 'À refaire : {argomenti}.',
};
