// « Prêt pour la soutenance » (français) : l'état des fonctions, les points trouvés dans le code et la fiche.
// Les mots qui reconnaissent l'explication de l'étudiant (controlla() dans js/codice/discussione.js) ne sont PAS ici.
export default {
  'discussione.data-breve': '{g}/{m}',
  'discussione.stato-agente': "modifiée pendant que l'agent travaillait · jamais expliquée",
  'discussione.stato-mai': 'jamais expliquée',
  'discussione.stato-cambiata': 'modifiée depuis la dernière fois que tu l\'as expliquée',
  'discussione.stato-rivedere': { one: 'à revoir · tu as sauté un point', other: 'à revoir · tu as sauté {n} points' },
  'discussione.stato-spiegata': 'expliquée le {data}',
  'discussione.spiegata-adesso': "expliquée à l'instant",
  'discussione.punto-parametri-breve': 'les paramètres',
  'discussione.punto-parametri': 'les paramètres ({nomi})',
  'discussione.punto-niente': 'qu\'elle ne reçoit rien',
  'discussione.punto-chiama': 'qu\'elle appelle `{nome}`',
  'discussione.punto-ciclo-breve': 'la boucle',
  'discussione.punto-ciclo': 'qu\'il y a une boucle',
  'discussione.punto-ricorsiva-breve': 'qu\'elle est récursive',
  'discussione.punto-ricorsiva': 'qu\'elle est récursive : elle s\'appelle elle-même',
  'discussione.punto-restituisce-breve': 'ce qu\'elle renvoie',
  'discussione.punto-restituisce-niente': 'qu\'elle ne renvoie rien',
  'discussione.punto-restituisce-valore': 'qu\'elle renvoie une valeur',
  'discussione.punto-restituisce-tipo': 'qu\'elle renvoie un `{tipo}`',
  'discussione.file-non-arrivato': "le fichier n'est pas arrivé",
  'discussione.nota': "Lode ne sait pas qui a écrit les lignes : « pendant que l'agent travaillait » veut dire que le fichier a changé pendant un de ses tours. Lode ne t'explique pas le code : il vérifie seulement que tu sais l'expliquer.",
  'discussione.hai-detto': 'Tu as dit : {punti}.',
  'discussione.nessun-punto': 'Je ne trouve aucun des points que je vois dans le code.',
  'discussione.hai-saltato': 'Tu as sauté : {punti}.',
  'discussione.tutti-i-punti': 'Tu as abordé tous les points que je trouve dans le code.',
  'discussione.la-so-spiegare': 'Je sais l\'expliquer',
  'discussione.proviamo': 'On essaie',
  'discussione.titolo': 'Prêt pour la soutenance',
  'discussione.intro': "Les fonctions modifiées depuis que tu suis le projet. D'abord celles modifiées pendant qu'un agent travaillait et que tu n'as jamais expliquées.",
  'discussione.diario-spento': 'Journal éteint : je ne note rien.',
  'discussione.spiegate': 'Expliquées : {spiegate} sur {totale}',
  'discussione.nessuna-funzione': 'Je ne vois aucune fonction modifiée dans {nome} depuis que tu le suis. Quand elles changent, tu les retrouves ici.',
  'discussione.lingua-sconosciuta': 'Pour ce langage je ne sais pas vérifier : indique toi-même si tu sais l\'expliquer.',
  'discussione.leggo-il-file': 'Je lis le fichier…',
  'discussione.file-lungo': '{file} fait {n} lignes : au-delà de 2000 je ne le lis pas. Indique toi-même si tu sais l\'expliquer.',
  'discussione.non-riesco-leggere': "Je n'arrive pas à lire {file} : {errore}",
  'discussione.non-trovo-piu': 'Je ne trouve plus <code>{nome}</code> dans {file} : tu l\'as peut-être renommée ou supprimée.',
  'discussione.togli': 'Retirer de la liste',
  'discussione.spiegala': "<code>{firma}</code> · {file}, ligne {riga}. Explique-la comme à la soutenance : ce qu'elle reçoit, ce qu'elle renvoie, comment elle marche. Le code, je te le montre après.",
  'discussione.aria-spiegazione': 'Ton explication de {nome}',
  'discussione.ho-finito': "J'ai fini",
  'discussione.alla-buona': "Les points sont repérés par le code, à la louche : il ne dit pas si l'explication est juste.",
};
