// Les erreurs du compilateur et des programmes (js/errori.js), en français.
// Les clés « errori.<entrée>.<champ> » sont les textes de chaque entrée du dictionnaire : etichetta, breve, frase, dove, cosa, concetto.
// Les messages du compilateur cités restent en anglais, comme le compilateur les affiche.
export default {
  'errori.for-punto-e-virgola.etichetta': 'le `for` avec des virgules',
  'errori.for-punto-e-virgola.frase': 'les trois parties du `for` se séparent avec `;`',
  'errori.for-punto-e-virgola.dove': `Regarde le \`for\` {allaRiga} : entre les parenthèses, il faut deux \`;\`.`,
  'errori.for-punto-e-virgola.cosa': 'Le `for` a trois parties : départ, condition et pas, comme dans `for (i = 0; i < n; i++)`. On les sépare avec `;`, pas avec `,`. Avec des virgules, le compilateur ne voit qu\'une seule partie.',
  'errori.for-punto-e-virgola.concetto': 'boucle for',
  'errori.punto-e-virgola.etichetta': 'il manque `;`',
  'errori.punto-e-virgola.breve': 'il manque ;',
  'errori.punto-e-virgola.frase': 'il manque un `;`',
  'errori.punto-e-virgola.dove': `Regarde la fin de la ligne {riga}, celle avant la {riga2} : c'est là qu'il manque le \`;\`. Le compilateur ne s'en rend compte qu'en lisant la ligne suivante.`,
  'errori.punto-e-virgola.dove-2': `Regarde la fin de la ligne {riga}{colonna} : c'est là qu'il manque le \`;\`.`,
  'errori.punto-e-virgola.dove-3': `Regarde la fin de la ligne {riga} et celle de la ligne d'avant : le compilateur ne s'en rend parfois compte qu'à la ligne suivante.`,
  'errori.punto-e-virgola.dove-4': 'Regarde la fin des instructions près de l\'endroit indiqué.',
  'errori.punto-e-virgola.cosa': `En {L}, chaque instruction finit par \`;\`, comme une phrase finit par un point. Sans lui, le compilateur colle l'instruction à la suivante et ne comprend plus ce que tu voulais dire. C'est pour ça que l'erreur est parfois signalée à la ligne suivante.`,
  'errori.punto-e-virgola.concetto': 'fin des instructions',
  'errori.include-mancante.etichetta': 'il manque un `#include`',
  'errori.include-mancante.breve': `#include{h} manquant`,
  'errori.include-mancante.frase-2': 'cette fonction',
  'errori.include-mancante.frase': `pour utiliser {nome}, il manque \`#include <{h}>\``,
  'errori.include-mancante.frase-4': 'cette fonction',
  'errori.include-mancante.frase-3': `pour utiliser {nome}, il manque un \`#include\``,
  'errori.include-mancante.dove-2': ` : il manque celle de \`<{h}>\``,
  'errori.include-mancante.dove': `Regarde en haut du fichier, là où il y a les lignes \`#include\`{h}.`,
  'errori.include-mancante.cosa': 'En C, `bool`, `true` et `false` n\'existent pas de base : ils arrivent avec `{h}`.',
  'errori.include-mancante.cosa-3': 'Ce nom',
  'errori.include-mancante.cosa-4': `, c'est-à-dire \`<{h}>\``,
  'errori.include-mancante.cosa-2': `{nome}, ce n'est pas toi qui l'écris : il est dans la bibliothèque standard du C. Pour l'utiliser, tu dois inclure le fichier qui le décrit (l'en-tête){h}. Sans \`#include\`, le compilateur ne sait ni qu'il existe ni comment l'utiliser.`,
  'errori.include-mancante.cosa-5': ' Avec `math.h`, sous Linux, ajoute aussi `-lm` à la fin de la commande de compilation.',
  'errori.include-mancante.concetto': 'bibliothèques et #include',
  'errori.funzione-non-dichiarata.etichetta': 'fonction non déclarée',
  'errori.funzione-non-dichiarata.breve-2': 'fonction',
  'errori.funzione-non-dichiarata.breve': `{nome} non déclarée`,
  'errori.funzione-non-dichiarata.frase': `tu utilises la fonction {nome} avant de la déclarer`,
  'errori.funzione-non-dichiarata.dove': `Cherche où tu écris la fonction {nome} : si elle est sous la ligne {riga}, le compilateur ne la connaît pas encore à cet endroit. Vérifie aussi que le nom est écrit exactement pareil.`,
  'errori.funzione-non-dichiarata.dove-senza-riga': `Cherche où tu écris la fonction {nome} : si elle est sous la ligne de l'erreur, le compilateur ne la connaît pas encore à cet endroit. Vérifie aussi que le nom est écrit exactement pareil.`,
  'errori.funzione-non-dichiarata.cosa': 'Le compilateur lit le fichier de haut en bas. Si tu appelles une fonction qu\'il n\'a pas encore vue, il ne sait ni quels paramètres elle veut ni ce qu\'elle renvoie : les compilateurs récents s\'arrêtent, les plus anciens devinent et se trompent souvent. Déplace la fonction au-dessus de `main`, ou écris au-dessus de `main` son prototype : la première ligne de la fonction suivie de `;`.',
  'errori.funzione-non-dichiarata.concetto': 'prototypes des fonctions',
  'errori.non-dichiarato.etichetta': 'nom non déclaré',
  'errori.non-dichiarato.breve-2': 'nom',
  'errori.non-dichiarato.breve': `{nome} non déclaré`,
  'errori.non-dichiarato.frase': `tu utilises {nome} mais il n'est pas déclaré`,
  'errori.non-dichiarato.frase-2': 'tu utilises un nom qui n\'est pas déclaré',
  'errori.non-dichiarato.dove': `Le compilateur propose {s} : vérifie si tu voulais écrire ça. `,
  'errori.non-dichiarato.dove-3': 'ce nom',
  'errori.non-dichiarato.dove-2': `Cherche où tu déclares {nome} : il a peut-être un autre nom (une lettre différente, majuscules et minuscules), ou il est déclaré dans un autre bloc \`{ }\`.`,
  'errori.non-dichiarato.cosa': 'La méthode que tu appelles n\'existe pas avec ce nom et ces types d\'arguments. Vérifie comment elle est écrite et qu\'elle est dans la bonne classe. ',
  'errori.non-dichiarato.cosa-2': 'Avant d\'utiliser une variable, tu dois la déclarer, c\'est-à-dire écrire son type et son nom (par exemple `int compte = 0;`). ',
  'errori.non-dichiarato.cosa-3': 'Une variable déclarée dans `{ }` n\'existe que là-dedans : en dehors du bloc, le compilateur ne la voit plus. L\'ordre compte aussi : la déclaration doit être au-dessus de la ligne qui l\'utilise.',
  'errori.non-dichiarato.concetto': 'déclaration et portée des variables',
  'errori.formato.etichetta': 'mauvais format dans printf ou scanf',
  'errori.formato.frase': `le format attend un {atteso} mais tu passes un {dato}`,
  'errori.formato.frase-2': 'le format ne correspond pas à la valeur que tu passes',
  'errori.formato.dove': `Regarde la ligne {riga} : compare chaque \`%\` de la chaîne avec la valeur à la même position.`,
  'errori.formato.dove-senza-riga': `Regarde la ligne indiquée : compare chaque \`%\` de la chaîne avec la valeur à la même position.`,
  'errori.formato.cosa': 'Dans `scanf`, chaque `%` veut l\'adresse d\'une variable du bon type : `%d` → `int`, `%f` → `float`, `%lf` → `double`, `%c` → `char`, `%s` → tableau de `char`. Si le type ne correspond pas, la valeur lue est mal écrite.',
  'errori.formato.cosa-2': ` Pour un {dato} dans \`scanf\`, on utilise {p}.`,
  'errori.formato.cosa-3': '`printf` ne sait pas de quel type sont les valeurs : il fait confiance à la chaîne de format. `%d` est pour les `int`, `%f` pour les `double`, `%c` pour les `char`, `%s` pour les chaînes. Si le format ne correspond pas à la valeur, il affiche des nombres absurdes.',
  'errori.formato.cosa-4': ' Pour un `unsigned long`, on utilise `%lu` ; si c\'est le résultat de `strlen` ou `sizeof` (un `size_t`), on utilise `%zu`.',
  'errori.formato.cosa-5': ` Pour un {dato} dans \`printf\`, on utilise {p}.`,
  'errori.formato.concetto': 'printf, scanf et les formats',
  'errori.scanf-e-commerciale.etichetta': 'il manque `&` dans scanf',
  'errori.scanf-e-commerciale.breve': 'il manque & dans scanf',
  'errori.scanf-e-commerciale.frase': '`scanf` veut l\'adresse de la variable : il manque `&`',
  'errori.scanf-e-commerciale.dove': `Regarde le \`scanf\` {allaRiga} : il y a une variable sans \`&\` devant.`,
  'errori.scanf-e-commerciale.cosa': '`scanf` doit écrire dans ta variable, donc il a besoin de savoir où elle est en mémoire : son adresse, qu\'on obtient avec `&`. On écrit `scanf("%d", &n);`. Les tableaux de `char` (les chaînes) font exception : leur nom est déjà une adresse, donc pas de `&`.',
  'errori.scanf-e-commerciale.concetto': 'scanf et adresses',
  'errori.return-mancante.etichetta': 'il manque le `return`',
  'errori.return-mancante.breve': 'il manque le return',
  'errori.return-mancante.frase-2': `la fonction {nome}`,
  'errori.return-mancante.frase-3': 'la fonction',
  'errori.return-mancante.frase-4': 'dans certains cas ',
  'errori.return-mancante.frase': `{p} arrive {sigla}à la fin sans \`return\``,
  'errori.return-mancante.dove': `Regarde la \`}\` {allaRiga} : c'est la fin de la fonction{p}. Suis chaque chemin possible (chaque \`if\` et \`else\`) et vérifie qu'il finit par un \`return\`.`,
  'errori.return-mancante.cosa-2': ` (ici elle renvoie {tipo})`,
  'errori.return-mancante.cosa': `Une fonction qui n'est pas \`void\`{tipo} promet de renvoyer une valeur. Si elle arrive à la \`}\` finale sans \`return\`, celui qui l'appelle reçoit une valeur au hasard. Ça arrive souvent avec un \`if\` qui a son \`return\` mais pas de \`else\`.`,
  'errori.return-mancante.concetto': 'return dans les fonctions',
  'errori.assegnamento-in-condizione.etichetta': '`=` à la place de `==`',
  'errori.assegnamento-in-condizione.breve': '= à la place de ==',
  'errori.assegnamento-in-condizione.frase': 'dans la condition il y a `=` (affecte) au lieu de `==` (compare)',
  'errori.assegnamento-in-condizione.dove': `Regarde la condition {allaRiga}{colonna}.`,
  'errori.assegnamento-in-condizione.cosa': '`=` met une valeur dans la variable ; `==` vérifie si deux valeurs sont égales. `if (x = 5)` affecte 5 à `x` et c\'est toujours vrai, parce que 5 n\'est pas zéro. Pour comparer, il faut `if (x == 5)`.',
  'errori.assegnamento-in-condizione.concetto': 'affectation et comparaison',
  'errori.confronto-stringhe.etichetta': 'chaînes comparées avec `==`',
  'errori.confronto-stringhe.frase': 'tu compares des chaînes avec `==`',
  'errori.confronto-stringhe.dove': `Regarde la comparaison {allaRiga}.`,
  'errori.confronto-stringhe.cosa': 'En C, `==` entre deux chaînes compare les adresses, pas les lettres : ça donne presque toujours faux même si le texte est le même. Pour comparer le texte, on utilise `strcmp(a, b) == 0`, de `{h}`. Si tu voulais un seul caractère, écris-le entre apostrophes : `\'c\'`.',
  'errori.confronto-stringhe.concetto': 'chaînes en C',
  'errori.puntatore-intero.etichetta': 'comparaison entre pointeur et entier',
  'errori.puntatore-intero.frase': 'tu compares une adresse (un pointeur) avec un nombre ou un caractère',
  'errori.puntatore-intero.dove': `Regarde les deux côtés de la comparaison {allaRiga}.`,
  'errori.puntatore-intero.cosa': 'D\'un côté il y a un pointeur (une adresse, par exemple une chaîne), de l\'autre un nombre ou un caractère. Une erreur typique : `"a"` entre guillemets doubles est une chaîne, `\'a\'` entre apostrophes est un caractère. Pour tester un caractère, écris `s[0] == \'a\'` ; pour comparer deux chaînes, utilise `strcmp`.',
  'errori.puntatore-intero.concetto': 'caractères, chaînes et pointeurs',
  'errori.puntatori-incompatibili.etichetta': 'pointeurs de types différents',
  'errori.puntatori-incompatibili.frase': `tu utilises un {dato} là où il faut un {atteso}`,
  'errori.puntatori-incompatibili.frase-2': 'tu utilises un pointeur d\'un type là où il en faut un d\'un autre',
  'errori.puntatori-incompatibili.dove': `Regarde la ligne {riga} : compare le type de ce que tu passes (ou affectes) avec le type qu'il faut.`,
  'errori.puntatori-incompatibili.dove-senza-riga': `Regarde la ligne indiquée : compare le type de ce que tu passes (ou affectes) avec le type qu'il faut.`,
  'errori.puntatori-incompatibili.cosa': 'Un pointeur porte avec lui le type de ce qu\'il pointe : un `int *` pointe vers des entiers, un `char *` vers des caractères. En utiliser un à la place de l\'autre veut souvent dire que tu t\'es trompé de variable, ou de type dans la déclaration ou dans le paramètre de la fonction.',
  'errori.puntatori-incompatibili.concetto': 'pointeurs',
  'errori.intero-puntatore.etichetta': 'nombre et adresse mélangés',
  'errori.intero-puntatore.frase': 'tu mélanges un nombre et une adresse (un pointeur)',
  'errori.intero-puntatore.dove': `Regarde la ligne {riga} : d'un côté il y a un pointeur, de l'autre une valeur normale.`,
  'errori.intero-puntatore.dove-senza-riga': `Regarde la ligne indiquée : d'un côté il y a un pointeur, de l'autre une valeur normale.`,
  'errori.intero-puntatore.cosa': 'Un pointeur contient une adresse mémoire, pas un nombre quelconque. Si tu veux l\'adresse d\'une variable, écris `&x` ; si tu veux la valeur pointée par un pointeur, écris `*p`.',
  'errori.intero-puntatore.cosa-2': ' Ici le compilateur suggère `&`.',
  'errori.intero-puntatore.cosa-3': ' Ici le compilateur suggère `*`.',
  'errori.intero-puntatore.cosa-4': ' Attention : `"a"` entre guillemets doubles est une chaîne ; un caractère s\'écrit entre apostrophes : `\'a\'`.',
  'errori.intero-puntatore.concetto': 'pointeurs',
  'errori.variabile-non-usata.etichetta': 'variable non utilisée',
  'errori.variabile-non-usata.breve-2': 'variable',
  'errori.variabile-non-usata.breve': `{nome} non utilisée`,
  'errori.variabile-non-usata.frase-2': 'une variable',
  'errori.variabile-non-usata.frase': `{nome} est déclarée mais tu ne l'utilises jamais`,
  'errori.variabile-non-usata.dove': `Regarde la déclaration {allaRiga}.`,
  'errori.variabile-non-usata.cosa': 'C\'est seulement un avertissement : le programme compile quand même. Mais souvent ça veut dire que tu as oublié de l\'utiliser, ou qu\'à sa place tu utilises par erreur une autre variable au nom proche. Si elle ne sert pas, enlève-la.',
  'errori.variabile-non-usata.concetto': 'variables',
  'errori.parametro-non-usato.etichetta': 'paramètre non utilisé',
  'errori.parametro-non-usato.frase': `le paramètre {nome} n'est jamais utilisé`,
  'errori.parametro-non-usato.dove': `Regarde la première ligne de la fonction {allaRiga}.`,
  'errori.parametro-non-usato.cosa': 'La fonction reçoit cette valeur mais ne l\'utilise pas. Parfois c\'est normal (par exemple `argc` et `argv` dans `main`) ; d\'autres fois, ça veut dire qu\'à sa place tu utilises une autre variable.',
  'errori.parametro-non-usato.concetto': 'paramètres des fonctions',
  'errori.non-inizializzata.etichetta': 'variable sans valeur',
  'errori.non-inizializzata.breve-2': 'variable',
  'errori.non-inizializzata.breve': `{nome} sans valeur`,
  'errori.non-inizializzata.frase-2': 'une variable',
  'errori.non-inizializzata.frase': `tu utilises {nome} avant de lui donner une valeur`,
  'errori.non-inizializzata.dove-2': 'cette variable',
  'errori.non-inizializzata.dove-3': ` (ligne {dichiarata})`,
  'errori.non-inizializzata.dove': `Regarde {laRiga}, puis remonte jusqu'à la déclaration de {nome}{dichiarata} : y a-t-il un chemin où elle ne reçoit jamais de valeur ?`,
  'errori.non-inizializzata.cosa': 'En Java, une variable locale doit recevoir une valeur avant d\'être lue, sur chaque chemin possible (même quand un `if` est faux). Donne une valeur de départ dans la déclaration, par exemple `int somme = 0;`.',
  'errori.non-inizializzata.cosa-2': 'Une variable locale qu\'on vient de déclarer contient une valeur au hasard, celle qui traînait en mémoire. Avant de la lire, tu dois lui donner une valeur, par exemple `int somme = 0;`. Ça arrive souvent avec les sommes et les compteurs.',
  'errori.non-inizializzata.concetto': 'initialisation des variables',
  'errori.riferimento-non-definito.etichetta': 'fonction jamais définie (linker)',
  'errori.riferimento-non-definito.breve': 'il manque main',
  'errori.riferimento-non-definito.breve-3': 'fonction',
  'errori.riferimento-non-definito.breve-2': `{nome} non définie`,
  'errori.riferimento-non-definito.frase': 'il manque la fonction `main`',
  'errori.riferimento-non-definito.frase-2': `{nome} est introuvable : il manque \`-lm\` dans la commande`,
  'errori.riferimento-non-definito.frase-4': 'une fonction',
  'errori.riferimento-non-definito.frase-3': `{nome} est utilisée mais je ne trouve pas où elle est écrite`,
  'errori.riferimento-non-definito.dove': 'Vérifie qu\'un des fichiers a `int main(void)` (ou `int main(int argc, char *argv[])`) écrit exactement comme ça, et que ce fichier est dans la commande de compilation.',
  'errori.riferimento-non-definito.dove-2': 'Regarde la commande de compilation : il faut `-lm` à la fin.',
  'errori.riferimento-non-definito.dove-4': 'cette fonction',
  'errori.riferimento-non-definito.dove-3': `Le linker n'indique pas de ligne. Cherche dans le projet le corps de {nome}, c'est-à-dire la version avec les \`{ }\` : le nom doit être identique (majuscules comprises) et le fichier qui la contient doit être dans la commande de compilation.`,
  'errori.riferimento-non-definito.cosa': 'Tout programme C démarre par `main`. S\'il manque, ou s\'il est écrit avec un autre nom (`Main`, `mian`), il n\'y a pas de point de départ. Sous Windows, le message parle parfois de `WinMain` : c\'est le même problème.',
  'errori.riferimento-non-definito.cosa-2': 'Les fonctions de `{h}` sont dans une bibliothèque à part. Sous Linux (et parfois avec MinGW), il faut ajouter `-lm` à la fin de la commande : `gcc main.c -o main -lm`.',
  'errori.riferimento-non-definito.cosa-3': 'La compilation a deux étapes : d\'abord chaque fichier `.c` est traduit tout seul, puis le linker les assemble. Le prototype dit au compilateur que la fonction existe, mais le linker n\'a trouvé son corps nulle part. En général, le nom est écrit différemment, un fichier manque dans la commande, ou la fonction n\'a jamais été écrite.',
  'errori.riferimento-non-definito.concetto': 'compilation et linker',
  'errori.definizione-multipla.etichetta': 'défini deux fois (linker)',
  'errori.definizione-multipla.breve-2': 'nom',
  'errori.definizione-multipla.breve': `{nome} défini deux fois`,
  'errori.definizione-multipla.frase-2': 'un nom',
  'errori.definizione-multipla.frase': `{nome} est défini deux fois dans le programme`,
  'errori.definizione-multipla.dove-2': 'ce nom',
  'errori.definizione-multipla.dove': `Cherche {nome} dans tous les fichiers du projet. Souvent, c'est une variable ou une fonction écrite dans un fichier \`.h\` inclus par plusieurs fichiers \`.c\`, ou un fichier \`.c\` inclus avec \`#include\`.`,
  'errori.definizione-multipla.cosa': 'Chaque fonction et chaque variable globale doit avoir une seule définition dans tout le programme. Dans les fichiers `.h`, on ne met que les prototypes (et les variables avec `extern`) ; les corps des fonctions vont dans les `.c`. Un fichier `.c` ne s\'inclut pas avec `#include`.',
  'errori.definizione-multipla.concetto': 'fichiers .h et .c',
  'errori.tipi-in-conflitto.etichetta': 'déclarations différentes',
  'errori.tipi-in-conflitto.frase-2': 'une fonction',
  'errori.tipi-in-conflitto.frase': `{nome} est déclarée de deux façons différentes`,
  'errori.tipi-in-conflitto.dove-3': ` (ligne {prima})`,
  'errori.tipi-in-conflitto.dove': `Compare la ligne {riga} avec la déclaration précédente{prima} : le type renvoyé et les paramètres doivent être identiques.`,
  'errori.tipi-in-conflitto.dove-senza-riga': `Compare la ligne indiquée avec la déclaration précédente{prima} : le type renvoyé et les paramètres doivent être identiques.`,
  'errori.tipi-in-conflitto.dove-5': 'la fonction',
  'errori.tipi-in-conflitto.dove-4': ` Ici, la première déclaration est implicite : tu as appelé {nome} avant de la déclarer. Mets le prototype au-dessus de \`main\`.`,
  'errori.tipi-in-conflitto.cosa': 'Le prototype (la ligne avec `;`, en général en haut ou dans un `.h`) et la vraie fonction doivent dire la même chose : même type renvoyé, mêmes types de paramètres, dans le même ordre.',
  'errori.tipi-in-conflitto.concetto': 'prototypes des fonctions',
  'errori.argomenti.etichetta': 'mauvais nombre d\'arguments',
  'errori.argomenti.frase': ` ({h} au lieu de {e})`,
  'errori.argomenti.frase-2': `tu passes moins d'arguments que la fonction n'en veut{quanti}`,
  'errori.argomenti.frase-3': `tu passes plus d'arguments que la fonction n'en veut{quanti}`,
  'errori.argomenti.frase-5': 'cette fonction',
  'errori.argomenti.frase-4': `l'appel à {nome} ne correspond pas à ses paramètres`,
  'errori.argomenti.dove-2': ` (ligne {dich})`,
  'errori.argomenti.dove': `Compare l'appel {allaRiga} avec la première ligne de la fonction{nome}{dich} : compte les arguments et regarde leurs types.`,
  'errori.argomenti.cosa': 'Une fonction s\'appelle avec autant d\'arguments qu\'elle a de paramètres, dans le même ordre. Si la fonction est `int somme(int a, int b)`, l\'appel est `somme(x, y)`.',
  'errori.argomenti.concetto': 'paramètres des fonctions',
  'errori.graffa.etichetta': 'accolade manquante',
  'errori.graffa.frase': 'il y a une `}` en trop',
  'errori.graffa.frase-2': 'il manque une `}`',
  'errori.graffa.dove': `Regarde la \`}\` {allaRiga} : elle ferme un bloc qui était déjà fermé. Compte les \`{\` et les \`}\` au-dessus.`,
  'errori.graffa.dove-3': ` (ligne {riga})`,
  'errori.graffa.dove-4': ` La \`{\` restée ouverte est à la ligne {aperta}.`,
  'errori.graffa.dove-2': `Le compilateur ne s'en rend compte qu'à la fin{riga}, mais l'accolade manque avant.{aperta} Compte les \`{\` et les \`}\` de chaque fonction, de chaque \`if\` et de chaque boucle.`,
  'errori.graffa.cosa': 'Chaque `{` ouvre un bloc et chaque `}` le ferme : il doit y en avoir autant. Avec un code bien indenté (chaque bloc un peu décalé à droite), l\'accolade qui manque se voit tout de suite.',
  'errori.graffa.concetto': 'blocs et accolades',
  'errori.parentesi.etichetta': 'parenthèse manquante',
  'errori.parentesi.frase': 'il manque une `)`',
  'errori.parentesi.dove-2': `, colonne {apertaCol}`,
  'errori.parentesi.dove': `La \`(\` restée ouverte est à la ligne {aperta}{apertaCol} : sa \`)\` manque avant l'endroit signalé {allaRiga}.`,
  'errori.parentesi.dove-3': `Regarde la ligne {riga} et compte les \`(\` et les \`)\`.`,
  'errori.parentesi.dove-3-senza-riga': `Regarde la ligne indiquée et compte les \`(\` et les \`)\`.`,
  'errori.parentesi.cosa': 'Chaque `(` doit avoir sa `)`. Dans les longues conditions et les appels imbriqués dans d\'autres appels, c\'est facile d\'en perdre une : compte-les de gauche à droite.',
  'errori.parentesi.concetto': 'parenthèses',
  'errori.espressione-attesa.etichetta': 'il manque une valeur',
  'errori.espressione-attesa.frase': 'le compilateur attendait une valeur et ne l\'a pas trouvée',
  'errori.espressione-attesa.dove': `Regarde {laRiga}{colonna} : il manque quelque chose (un nombre, une variable) ou il y a un symbole en trop. Ça arrive aussi avec des guillemets pas fermés sur la même ligne.`,
  'errori.espressione-attesa.cosa': 'Après un `=`, un opérateur comme `+` ou une virgule, le compilateur attend une valeur. S\'il trouve tout de suite `;`, `)` ou un autre symbole, il s\'arrête.',
  'errori.espressione-attesa.concetto': 'expressions',
  'errori.ridefinizione.etichetta': 'déclaré deux fois',
  'errori.ridefinizione.breve-2': 'nom',
  'errori.ridefinizione.breve': `{nome} déclaré deux fois`,
  'errori.ridefinizione.frase-2': 'un nom',
  'errori.ridefinizione.frase': `{nome} est déclaré deux fois`,
  'errori.ridefinizione.dove': `Les deux déclarations sont à la ligne {prima} et à la ligne {riga}.`,
  'errori.ridefinizione.dove-4': 'ce nom',
  'errori.ridefinizione.dove-2': `Cherche au-dessus de la ligne {riga} une autre déclaration de {nome}.`,
  'errori.ridefinizione.dove-2-senza-riga': `Cherche au-dessus de la ligne indiquée une autre déclaration de {nome}.`,
  'errori.ridefinizione.cosa': 'Dans un même bloc, un nom ne se déclare qu\'une fois. Si tu veux seulement changer la valeur, écris `x = 2;` sans le type devant.',
  'errori.ridefinizione.concetto': 'déclaration des variables',
  'errori.non-array.etichetta': '`[ ]` sur autre chose qu\'un tableau',
  'errori.non-array.frase': 'tu utilises `[ ]` sur quelque chose qui n\'est pas un tableau',
  'errori.non-array.dove': `Regarde les crochets {allaRiga}{colonna}.`,
  'errori.non-array.cosa': 'Les crochets servent à prendre un élément d\'un tableau (ou d\'un pointeur). Une variable simple, comme un `int`, n\'a pas d\'éléments. Tu voulais peut-être utiliser une autre variable, ou la déclarer comme tableau, par exemple `int v[10];`.',
  'errori.non-array.concetto': 'tableaux',
  'errori.freccia-punto.etichetta': '`.` et `->` inversés',
  'errori.freccia-punto.frase': 'avec une structure (pas un pointeur), on utilise `.`, pas `->`',
  'errori.freccia-punto.frase-2': 'avec un pointeur vers une structure, on utilise `->`, pas `.`',
  'errori.freccia-punto.frase-3': 'le champ de la structure est pris de la mauvaise façon',
  'errori.freccia-punto.dove': `Regarde {laRiga}{colonna} : vérifie comment est déclarée la variable avant le point ou la flèche.`,
  'errori.freccia-punto.cosa': 'Si tu as la structure elle-même (`struct nodo n`), le champ se prend avec le point : `n.val`. Si tu as un pointeur vers la structure (`struct nodo *p`), on utilise la flèche : `p->val`, qui veut dire `(*p).val`.',
  'errori.freccia-punto.concetto': 'structures et pointeurs',
  'errori.membro-inesistente.etichetta': 'champ qui n\'existe pas',
  'errori.membro-inesistente.frase-2': 'la structure',
  'errori.membro-inesistente.frase': `{p} n'a pas de champ {m}`,
  'errori.membro-inesistente.frase-3': 'la structure n\'a pas ce champ',
  'errori.membro-inesistente.dove-2': ` avec {m}`,
  'errori.membro-inesistente.dove': `Regarde la définition de la structure{p} et compare les noms des champs{m}.`,
  'errori.membro-inesistente.cosa': 'Les champs d\'une structure sont ceux écrits dans sa définition, avec ces noms exacts. Un nom différent, même d\'une seule lettre, est un autre champ.',
  'errori.membro-inesistente.concetto': 'structures',
  'errori.header-non-trovato.etichetta': 'en-tête introuvable',
  'errori.header-non-trovato.frase-2': 'inclus',
  'errori.header-non-trovato.frase': `je ne trouve pas le fichier {h}`,
  'errori.header-non-trovato.dove': `Regarde la ligne \`#include\` {allaRiga}.`,
  'errori.header-non-trovato.dove-2': ` Tu voulais peut-être {v}.`,
  'errori.header-non-trovato.dove-3': ' `conio.h` n\'existe qu\'avec certains vieux compilateurs pour Windows (Turbo C, Dev-C++) : il ne fait pas partie du C standard.',
  'errori.header-non-trovato.cosa': 'Avec `#include {sistema}`, le compilateur cherche le fichier parmi ceux du système ; avec `#include {progetto}`, il le cherche d\'abord dans le dossier du projet. Si le nom est faux, même d\'une lettre, il ne le trouve pas et s\'arrête tout de suite.',
  'errori.header-non-trovato.concetto': 'bibliothèques et #include',
  'errori.file-sorgente-mancante.etichetta': 'fichier introuvable',
  'errori.file-sorgente-mancante.frase-2': 'indiqué',
  'errori.file-sorgente-mancante.frase': `le compilateur ne trouve pas le fichier {h}`,
  'errori.file-sorgente-mancante.dove': 'Regarde la commande de compilation et les noms des fichiers dans le dossier.',
  'errori.file-sorgente-mancante.cosa': 'La commande cite un fichier qui n\'est pas dans le dossier. Vérifie le nom (majuscules, extension `.c`) et que la commande part du bon dossier.',
  'errori.file-sorgente-mancante.concetto': 'compilation',
  'errori.non-assegnabile.etichetta': 'affectation impossible',
  'errori.non-assegnabile.frase': 'tu ne peux pas copier un tableau (ou une chaîne) avec `=`',
  'errori.non-assegnabile.frase-2': 'à gauche de `=`, il y a quelque chose qui n\'est pas une variable',
  'errori.non-assegnabile.dove': `Regarde ce qui est à gauche de \`=\` {allaRiga}.`,
  'errori.non-assegnabile.cosa': 'Un tableau ne se copie pas avec `=`. Pour une chaîne, utilise `strcpy(destination, "texte");` de `{h}`, ou donne la valeur quand tu la déclares : `char nom[10] = "texte";`.',
  'errori.non-assegnabile.cosa-2': 'À gauche de `=`, il faut un endroit où mettre la valeur : une variable, un élément de tableau, un champ. Pas un calcul comme `a + 1`. Si tu voulais comparer, il faut `==`.',
  'errori.non-assegnabile.concetto': 'affectation',
  'errori.tipo-sconosciuto.etichetta': 'type inconnu',
  'errori.tipo-sconosciuto.frase-2': 'ce nom',
  'errori.tipo-sconosciuto.frase': `{nome} n'est pas un type que le compilateur connaît`,
  'errori.tipo-sconosciuto.dove-2': 'le type',
  'errori.tipo-sconosciuto.dove': `Regarde {laRiga} et cherche au-dessus où tu définis {nome}.`,
  'errori.tipo-sconosciuto.cosa': 'En C, le type `string` n\'existe pas (il existe en C++ et dans d\'autres langages). Une chaîne en C est un tableau de `char` : `char s[50];` ou `char *s`.',
  'errori.tipo-sconosciuto.cosa-2': 'Avant d\'utiliser un type comme `Nodo`, il faut le définir, par exemple avec `typedef struct nodo Nodo;`, au-dessus de la ligne qui l\'utilise. Vérifie aussi les majuscules et les minuscules.',
  'errori.tipo-sconosciuto.concetto': 'types et typedef',
  'errori.virgolette.etichetta': 'chaîne non fermée',
  'errori.virgolette.frase': 'une chaîne n\'est pas fermée : il manque `"`',
  'errori.virgolette.dove': `Regarde {laRiga}{colonna} : la chaîne commence là. Cherche où elle devrait finir.`,
  'errori.virgolette.cosa': 'Une chaîne commence et finit par `"` sur la même ligne. S\'il manque le guillemet de fermeture, le compilateur prend tout le reste de la ligne pour une chaîne et se perd ensuite : c\'est pour ça que les erreurs qui suivent disparaissent souvent toutes seules.',
  'errori.virgolette.concetto': 'chaînes',
  'errori.if-vuoto.etichetta': '`;` après la condition',
  'errori.if-vuoto.frase': `il y a un \`;\` juste après \`{kw}\``,
  'errori.if-vuoto.frase-2': `il y a un \`;\` juste après la condition {if}`,
  'errori.if-vuoto.dove': `Regarde la ligne {riga} : juste après \`{kw}\`, il y a un \`;\`.`,
  'errori.if-vuoto.dove-senza-riga': `Regarde la ligne indiquée : juste après \`{kw}\`, il y a un \`;\`.`,
  'errori.if-vuoto.dove-3': `Regarde la fin de la ligne {riga} : après la \`)\` de la condition, il y a un \`;\`.`,
  'errori.if-vuoto.dove-3-senza-riga': `Regarde la fin de la ligne indiquée : après la \`)\` de la condition, il y a un \`;\`.`,
  'errori.if-vuoto.cosa': 'Le `;` juste après `else` est une instruction vide : le `else` ne commande que celle-là. Le bloc `{ }` en dessous est toujours exécuté, même quand la condition du `if` est vraie.',
  'errori.if-vuoto.cosa-2': 'Le `;` juste après `do` est une instruction vide : la boucle ne répète que celle-là. Le bloc `{ }` en dessous ne fait pas partie de la boucle.',
  'errori.if-vuoto.cosa-3': 'Le `;` juste après `if (...)` est une instruction vide : le `if` ne contrôle que celle-là. Le bloc `{ }` en dessous est toujours exécuté, quelle que soit la condition. Avec `while`, c\'est pire : la boucle peut ne jamais finir.',
  'errori.if-vuoto.concetto': 'if et boucles',
  'errori.confronto-inutile.etichetta': 'instruction qui ne fait rien',
  'errori.confronto-inutile.frase': 'il y a un `==` qui ne fait rien : tu voulais peut-être `=`',
  'errori.confronto-inutile.frase-2': 'cette instruction ne fait rien',
  'errori.confronto-inutile.dove': `Regarde {laRiga}{colonna}.`,
  'errori.confronto-inutile.cosa': 'Une comparaison toute seule (`x == 4;`) calcule vrai ou faux et jette le résultat. Si tu voulais donner une valeur à la variable, il faut un seul `=` : `x = 4;`.',
  'errori.confronto-inutile.cosa-2': 'Un calcul qui n\'est ni rangé dans une variable, ni affiché, ni utilisé dans une condition est jeté. Il manque peut-être un `=` ou un appel de fonction.',
  'errori.confronto-inutile.concetto': 'affectation et comparaison',
  'errori.indirizzo-locale.etichetta': 'adresse d\'une variable locale',
  'errori.indirizzo-locale.frase-2': 'une variable locale',
  'errori.indirizzo-locale.frase': `tu renvoies l'adresse de {nome}, qui disparaît quand la fonction se termine`,
  'errori.indirizzo-locale.dove': `Regarde le \`return\` {allaRiga}.`,
  'errori.indirizzo-locale.cosa': 'Les variables locales ne vivent que pendant l\'exécution de la fonction. Renvoyer leur adresse, c\'est donner à l\'appelant un emplacement mémoire qui n\'existe plus. Si tu dois renvoyer un tableau, crée-le avec `malloc` (et pense ensuite à `free`), ou fais-le passer en paramètre.',
  'errori.indirizzo-locale.concetto': 'mémoire et fonctions',
  'errori.segni-diversi.etichetta': 'nombres signés et non signés',
  'errori.segni-diversi.frase': 'tu compares un nombre signé et un nombre non signé',
  'errori.segni-diversi.dove': `Regarde la comparaison {allaRiga}.`,
  'errori.segni-diversi.cosa': 'Des fonctions comme `strlen` renvoient un nombre non signé (`size_t`). Le comparer à un `int` marche en général, mais si l\'`int` est négatif, la comparaison se trompe. C\'est un avertissement : tu peux déclarer l\'indice en `size_t`, ou ranger la longueur dans un `int` avant la boucle.',
  'errori.segni-diversi.concetto': 'types entiers',
  'errori.return-void.etichetta': '`return` et `void` en conflit',
  'errori.return-void.frase': '`return;` sans valeur dans une fonction qui doit en renvoyer une',
  'errori.return-void.frase-2': 'une fonction `void` ne peut pas renvoyer de valeur',
  'errori.return-void.dove': `Regarde le \`return\` {allaRiga} et la première ligne de la fonction.`,
  'errori.return-void.cosa': '`void` veut dire que la fonction ne renvoie rien : là, on écrit seulement `return;` (ou rien). Si la fonction doit donner un résultat, à la place de `void` il faut le bon type, par exemple `int`, et chaque `return` doit avoir une valeur.',
  'errori.return-void.concetto': 'return dans les fonctions',
  'errori.main-int.etichetta': '`main` pas `int`',
  'errori.main-int.frase': '`main` doit renvoyer `int`',
  'errori.main-int.dove-2': ` (ligne {riga})`,
  'errori.main-int.dove': `Regarde la ligne de \`main\`{riga}.`,
  'errori.main-int.cosa': 'Le standard du C veut `int main(void)`, et à la fin `return 0;` pour dire « tout va bien ». `void main` n\'est accepté que par certains vieux compilateurs.',
  'errori.main-int.concetto': 'la fonction main',
  'errori.fuori-array.etichetta': 'indice hors du tableau',
  'errori.fuori-array.frase': `tu utilises l'indice {i}, mais le tableau ne va pas jusque-là`,
  'errori.fuori-array.frase-2': 'tu utilises un indice hors du tableau',
  'errori.fuori-array.dove-2': ` et la déclaration du tableau à la ligne {riga}`,
  'errori.fuori-array.dove': `Regarde {laRiga}{riga}.`,
  'errori.fuori-array.cosa': 'Un tableau de N éléments a les indices de `0` à `N-1` : avec `int v[5]`, le dernier est `v[4]`, et `v[5]` est déjà en dehors. Ça arrive souvent avec une boucle `for (i = 0; i <= 5; i++)` au lieu de `i < 5`.',
  'errori.fuori-array.concetto': 'tableaux et indices',
  'errori.argomenti-formato.etichetta': 'les `%` et les valeurs ne collent pas',
  'errori.argomenti-formato.frase': 'dans la chaîne, il y a plus de `%` que de valeurs',
  'errori.argomenti-formato.frase-2': 'tu passes plus de valeurs qu\'il n\'y a de `%` dans la chaîne',
  'errori.argomenti-formato.dove': `Regarde la chaîne {allaRiga} et compte les \`%\` et les valeurs après la virgule.`,
  'errori.argomenti-formato.cosa': 'Chaque `%d`, `%f`, `%c`… dans la chaîne de `printf` (ou `scanf`) prend la valeur suivante, dans l\'ordre. Le nombre de `%` et le nombre de valeurs après la chaîne doivent être égaux.',
  'errori.argomenti-formato.concetto': 'printf et les formats',
  'errori.divisione-zero.etichetta': 'division par zéro',
  'errori.divisione-zero.frase': 'tu divises par zéro',
  'errori.divisione-zero.dove': `Regarde la division {allaRiga}.`,
  'errori.divisione-zero.cosa': 'Diviser un entier par zéro n\'a pas de résultat : en général, le programme plante. Avant de diviser, vérifie que le diviseur n\'est pas zéro, par exemple avec `if (n != 0)`.',
  'errori.divisione-zero.concetto': 'division',
  'errori.troppi-inizializzatori.etichetta': 'trop de valeurs dans le tableau',
  'errori.troppi-inizializzatori.frase': 'tu mets plus de valeurs que le tableau ne peut en contenir',
  'errori.troppi-inizializzatori.dove': `Regarde la déclaration {allaRiga} : compare la taille entre \`[ ]\` avec le nombre de valeurs entre \`{ }\`.`,
  'errori.troppi-inizializzatori.cosa': 'Si un tableau a de la place pour 2 valeurs et que tu en écris 3 entre les accolades, la troisième est jetée. Augmente la taille ou enlève des valeurs. Tu peux aussi laisser les crochets vides, `int v[] = {1, 2, 3};`, et le compilateur compte tout seul.',
  'errori.troppi-inizializzatori.concetto': 'tableaux',
  'errori.operandi.etichetta': 'opération impossible entre ces types',
  'errori.operandi.frase': `l'opération ne peut pas se faire entre {a} et {b}`,
  'errori.operandi.frase-2': 'l\'opération ne peut pas se faire entre ces deux types',
  'errori.operandi.dove': `Regarde l'opérateur {allaRiga}{colonna} et les types des deux côtés.`,
  'errori.operandi.cosa': 'Les opérateurs comme `&&`, `+` ou `<` veulent des types précis : `&&` travaille sur des `boolean`, `<` sur des nombres. Les chaînes ne se comparent pas avec `<` : on utilise `compareTo`, et pour l\'égalité `equals`.',
  'errori.operandi.cosa-2': 'Les opérateurs comme `+`, `-` et `<` marchent sur les nombres (et certains sur les pointeurs). Deux structures ne s\'additionnent pas et ne se comparent pas directement : travaille sur leurs champs, par exemple `a.x + b.x`. En C, les chaînes ne se concatènent pas avec `+` : on utilise `strcat`.',
  'errori.operandi.concetto': 'types et opérateurs',
  'errori.carattere-strano.etichetta': 'caractère bizarre dans le code',
  'errori.carattere-strano.frase': 'il y a un caractère bizarre dans le code',
  'errori.carattere-strano.dove': `Regarde {laRiga}{colonna}.`,
  'errori.carattere-strano.cosa': 'Souvent, c\'est un caractère copié depuis un PDF ou une page web : guillemets courbes `“ ”`, apostrophe courbe, espace spéciale ou tiret long. À l\'œil, ils ont l\'air pareils, mais pas pour le compilateur. Réécris la ligne à la main.',
  'errori.carattere-strano.concetto': 'caractères dans le code',
  'errori.non-sicura.etichetta': 'Visual Studio et les fonctions « non sécurisées »',
  'errori.non-sicura.frase-2': 'cette fonction',
  'errori.non-sicura.frase': `Visual Studio refuse {nome} : il la considère comme non sécurisée`,
  'errori.non-sicura.dove': 'Il n\'y a rien de faux dans ton C : c\'est une règle de Visual Studio.',
  'errori.non-sicura.cosa': 'Visual Studio signale `scanf`, `strcpy` et compagnie parce que, mal utilisées, elles peuvent écrire après la fin d\'un tableau. Le C standard les permet et les cours les utilisent. Pour couper l\'avertissement, écris `#define _CRT_SECURE_NO_WARNINGS` tout en haut du fichier, avant les `#include`. Si ton prof préfère `scanf_s`, suis ton prof.',
  'errori.non-sicura.concetto': 'compilateurs différents',
  'errori.ricorsione-infinita.etichetta': 'récursion sans fin',
  'errori.ricorsione-infinita.frase': 'la fonction s\'appelle toujours elle-même : elle ne s\'arrête jamais',
  'errori.ricorsione-infinita.dove': `Regarde la fonction{p} {allaRiga} : cherche le cas de base, c'est-à-dire un \`if\` qui renvoie une valeur sans rappeler la fonction.`,
  'errori.ricorsione-infinita.cosa': 'Une fonction récursive doit avoir un cas de base, et chaque appel doit se rapprocher de ce cas (par exemple avec `n - 1`). Ici, chaque chemin mène à un autre appel : le programme va remplir la mémoire et s\'arrêter.',
  'errori.ricorsione-infinita.concetto': 'récursivité',
  'errori.sintassi.etichetta': 'code écrit d\'une façon que le compilateur ne comprend pas',
  'errori.sintassi.frase': 'le compilateur ne comprend pas comment le code continue ici',
  'errori.sintassi.dove': `Regarde {laRiga} et celle d'avant : souvent le vrai problème est juste au-dessus, par exemple un \`;\` en trop après la première ligne d'une fonction, une \`}\` en plus ou une parenthèse pas fermée.`,
  'errori.sintassi.cosa': 'Le compilateur lit le code en suivant des règles précises, comme la grammaire d\'une langue. Ici, il a trouvé quelque chose qui ne peut pas être à cet endroit. Le message original dit ce qu\'il attendait.',
  'errori.sintassi.concetto': 'syntaxe',
  'errori.java-tipi.etichetta': 'types incompatibles (Java)',
  'errori.java-tipi.frase': `de {dato} à {atteso}, on peut perdre des données`,
  'errori.java-tipi.frase-2': `{dato} ne peut pas s'utiliser là où il faut {atteso}`,
  'errori.java-tipi.frase-3': 'la valeur n\'a pas le type qu\'il faut',
  'errori.java-tipi.dove': `Regarde {laRiga}{colonna} : compare le type de la variable avec celui de la valeur.`,
  'errori.java-tipi.cosa': 'En Java, chaque variable a un type et le compilateur vérifie que les valeurs correspondent. De `double` à `int`, on perd les décimales, donc il faut le dire explicitement avec un cast : `(int) x`. Une `String` ne devient pas un nombre toute seule : on utilise `Integer.parseInt(s)`.',
  'errori.java-tipi.concetto': 'types en Java',
  'errori.java-import.etichetta': 'il manque un `import` (Java)',
  'errori.java-import.frase-2': 'cette classe',
  'errori.java-import.frase': `pour utiliser {nome}, il manque un \`import\``,
  'errori.java-import.dove': 'Regarde en haut du fichier, au-dessus de la classe, là où il y a les lignes `import`.',
  'errori.java-import.cosa-2': 'Cette classe',
  'errori.java-import.cosa-3': `, c'est-à-dire \`import java.util.{nome};\``,
  'errori.java-import.cosa': `{nome} est dans un package de la bibliothèque Java : pour l'utiliser, il faut l'\`import\` en haut du fichier{nome2}. Vérifie aussi les majuscules et les minuscules.`,
  'errori.java-import.concetto': 'import en Java',
  'errori.java-nome-file.etichetta': 'nom du fichier et nom de la classe différents',
  'errori.java-nome-file.frase-2': 'publique',
  'errori.java-nome-file.frase-3': 'Classe',
  'errori.java-nome-file.frase': `la classe {nome} doit être dans le fichier {nome2}`,
  'errori.java-nome-file.dove': 'Regarde le nom du fichier et la ligne `public class`.',
  'errori.java-nome-file.cosa': 'En Java, une classe `public` doit être dans un fichier du même nom, majuscules comprises : `public class Main` va dans `Main.java`. Renomme le fichier ou la classe.',
  'errori.java-nome-file.concetto': 'classes et fichiers en Java',
  'errori.java-statico.etichetta': 'non static utilisé depuis static',
  'errori.java-statico.frase-2': 'ce nom',
  'errori.java-statico.frase': `{nome} n'est pas \`static\`, mais tu l'utilises depuis une méthode \`static\``,
  'errori.java-statico.dove-2': 'ce nom',
  'errori.java-statico.dove': `Regarde {laRiga} et la déclaration de {nome}.`,
  'errori.java-statico.cosa': '`main` est `static` : il appartient à la classe, pas à un objet. De là, tu ne peux utiliser que des méthodes et des variables `static`, ou d\'abord créer un objet avec `new` et utiliser celui-là. Dans les exercices avec une seule classe, il manque souvent `static` à la méthode.',
  'errori.java-statico.concetto': 'static en Java',
  'errori.java-irraggiungibile.etichetta': 'instruction jamais exécutée',
  'errori.java-irraggiungibile.frase': 'cette instruction ne sera jamais exécutée',
  'errori.java-irraggiungibile.dove': `Regarde {laRiga} et la ligne d'avant.`,
  'errori.java-irraggiungibile.cosa': 'Avant cette ligne, il y a un `return`, un `break`, un `continue` ou une boucle qui ne finit pas : à partir de là, le programme n\'arrive jamais ici. Enlève-la ou déplace-la avant.',
  'errori.java-irraggiungibile.concetto': 'flux du programme',
  'errori.java-indice.etichetta': 'indice hors limites (Java)',
  'errori.java-indice.frase': `tu utilises l'indice {i}, mais la longueur est {l}`,
  'errori.java-indice.frase-2': 'tu lis une position que le tableau (ou la chaîne) n\'a pas',
  'errori.java-indice.cosa': 'Les indices partent de 0 : avec une longueur de 5, ils vont de 0 à 4. Vérifie la condition de la boucle : souvent il y a `<=` là où il faut `<`, ou on utilise `length` comme indice.',
  'errori.java-indice.concetto': 'tableaux et indices',
  'errori.java-null.etichetta': 'objet null (Java)',
  'errori.java-null.frase': 'tu utilises un objet qui vaut `null`',
  'errori.java-null.cosa': 'L\'objet n\'a jamais été créé avec `new`, ou une méthode a renvoyé `null`. Les versions récentes de Java écrivent dans le message quelle variable était `null`.',
  'errori.java-null.concetto': 'objets et null',
  'errori.java-divisione-zero.etichetta': 'division par zéro (Java)',
  'errori.java-divisione-zero.frase': 'tu divises un entier par zéro',
  'errori.java-divisione-zero.cosa': 'Diviser un entier par zéro (même avec `%`) n\'a pas de résultat et Java s\'arrête. Avant la division, vérifie le diviseur, par exemple avec `if (n != 0)`.',
  'errori.java-divisione-zero.concetto': 'division',
  'errori.java-input.etichetta': 'entrée qui n\'est pas un nombre (Java)',
  'errori.java-input.frase': `{v} n'est pas un nombre`,
  'errori.java-input.frase-2': 'le programme attendait un nombre et a lu autre chose',
  'errori.java-input.cosa': 'Le programme voulait un nombre et a trouvé autre chose : des lettres, des espaces, une ligne vide, ou une virgule à la place du point. Vérifie ce que tu écris en entrée, ou le fichier `.in` du test.',
  'errori.java-input.concetto': 'entrées',
  'errori.java-stack.etichetta': 'récursion sans fin (Java)',
  'errori.java-stack.frase': 'la méthode s\'appelle elle-même trop de fois',
  'errori.java-stack.cosa': 'Chaque méthode récursive a besoin d\'un cas de base : une condition où elle renvoie une valeur sans se rappeler. Et chaque appel doit se rapprocher du cas de base.',
  'errori.java-stack.concetto': 'récursivité',
  'errori.py-uguale.etichetta': '`=` à la place de `==`',
  'errori.py-uguale.breve': '= à la place de ==',
  'errori.py-uguale.frase': 'dans la condition, il y a `=` au lieu de `==`',
  'errori.py-uguale.dove': `Regarde la condition {allaRiga}.`,
  'errori.py-uguale.cosa': '`=` met une valeur dans une variable ; `==` vérifie si deux valeurs sont égales. Dans une condition (`if`, `elif`, `while`), il faut `==` : `if x == 5:`.',
  'errori.py-uguale.concetto': 'affectation et comparaison',
  'errori.py-due-punti.etichetta': 'il manque les `:`',
  'errori.py-due-punti.frase': 'il manque les `:` à la fin de la ligne',
  'errori.py-due-punti.dove': `Regarde la fin de la ligne {riga}.`,
  'errori.py-due-punti.dove-senza-riga': `Regarde la fin de la ligne indiquée.`,
  'errori.py-due-punti.cosa': 'En Python, `if`, `elif`, `else`, `for`, `while`, `def` et `class` finissent par `:`. Les deux-points disent « maintenant le bloc commence », et le bloc s\'écrit en dessous, indenté.',
  'errori.py-due-punti.concetto': 'blocs en Python',
  'errori.py-parentesi.etichetta': 'parenthèse pas fermée',
  'errori.py-parentesi.frase': `il y a une {c} qui ne ferme rien`,
  'errori.py-parentesi.frase-2': `une {p} n'est pas fermée`,
  'errori.py-parentesi.dove': `Regarde {laRiga} : compte les parenthèses ouvertes et fermées. Si la ligne a l'air juste, regarde celle d'avant.`,
  'errori.py-parentesi.cosa': 'Chaque `(`, `[` et `{` doit avoir sa parenthèse fermante du même type. S\'il en manque une, Python continue de lire les lignes suivantes comme si c\'était la même instruction.',
  'errori.py-parentesi.concetto': 'parenthèses',
  'errori.py-stringa.etichetta': 'chaîne non fermée',
  'errori.py-stringa.frase': 'une chaîne n\'est pas fermée',
  'errori.py-stringa.dove': `Regarde {laRiga} : la chaîne commence là. Cherche où manque le guillemet de fermeture.`,
  'errori.py-stringa.cosa': 'Une chaîne commence et finit par le même type de guillemets, `"` ou `\'`, sur la même ligne. S\'il y a une apostrophe dans le texte, utilise les guillemets doubles : `"l\'année"`.',
  'errori.py-stringa.concetto': 'chaînes',
  'errori.py-print.etichetta': '`print` sans parenthèses',
  'errori.py-print.frase': '`print` veut des parenthèses',
  'errori.py-print.dove': `Regarde {laRiga}.`,
  'errori.py-print.cosa': 'En Python 3, `print` est une fonction : on écrit `print("salut")`. La forme sans parenthèses venait de Python 2, qu\'on trouve encore dans de vieux exemples sur internet.',
  'errori.py-print.concetto': 'fonctions',
  'errori.py-indentazione.etichetta': 'mauvaise indentation',
  'errori.py-indentazione.frase': 'il manque l\'indentation après les deux-points',
  'errori.py-indentazione.frase-2': 'il y a une indentation en trop',
  'errori.py-indentazione.frase-3': 'l\'indentation ne correspond pas aux lignes du dessus',
  'errori.py-indentazione.frase-4': 'tu mélanges tabulations et espaces dans l\'indentation',
  'errori.py-indentazione.frase-5': 'l\'indentation de la ligne est fausse',
  'errori.py-indentazione.dove-2': ` Le \`{kw}\` est à la ligne {l}.`,
  'errori.py-indentazione.dove': `Regarde {laRiga} et celle du dessus : compare les espaces en début de ligne.{kw}`,
  'errori.py-indentazione.cosa': 'En Python, l\'indentation (les espaces en début de ligne) fait partie du code : elle dit quelles lignes sont dans un `if`, un `for` ou une `def`. Après les `:`, la ligne d\'en dessous doit être indentée, et les lignes d\'un même bloc doivent l\'être pareil. Utilise toujours 4 espaces, sans les mélanger avec des tabulations.',
  'errori.py-indentazione.concetto': 'blocs en Python',
  'errori.py-sintassi.etichetta': 'ligne que Python ne sait pas lire',
  'errori.py-sintassi.frase': 'il manque peut-être une virgule',
  'errori.py-sintassi.frase-2': 'Python n\'arrive pas à lire cette ligne',
  'errori.py-sintassi.dove': `Regarde {laRiga} : le signe \`^\` sous la ligne indique où Python a remarqué le problème. Souvent, la vraie erreur est juste avant, parfois à la ligne du dessus (une parenthèse ou un guillemet pas fermé).`,
  'errori.py-sintassi.cosa': 'Entre deux valeurs d\'une liste, d\'un tuple ou des arguments d\'une fonction, il faut une virgule : `[1, 2, 3]`, `print(a, b)`.',
  'errori.py-sintassi.cosa-2': 'Python lit le code en suivant des règles précises, comme la grammaire d\'une langue. Ici, il a trouvé quelque chose qui ne peut pas être à cet endroit. Le message original, après `SyntaxError:`, dit ce qui ne va pas.',
  'errori.py-sintassi.concetto': 'syntaxe',
  'errori.py-nome.etichetta': 'nom qui n\'existe pas',
  'errori.py-nome.breve-2': 'nom',
  'errori.py-nome.breve': `{nome} non défini`,
  'errori.py-nome.frase-2': 'ce nom',
  'errori.py-nome.frase': `{nome} n'existe pas encore quand Python arrive à la ligne {riga}`,
  'errori.py-nome.frase-senza-riga': `{nome} n'existe pas encore quand Python arrive à la ligne indiquée`,
  'errori.py-nome.dove': `Python propose {s} : vérifie si tu voulais écrire ça. `,
  'errori.py-nome.dove-3': 'ce nom',
  'errori.py-nome.dove-2': `Cherche où tu donnes une valeur à {nome} : ça doit être au-dessus de cette ligne et écrit pareil, majuscules comprises. Si c'est une fonction, la \`def\` doit venir avant l'appel.`,
  'errori.py-nome.cosa': 'En Python, un nom n\'existe qu\'une fois que tu lui as donné une valeur (`x = ...`), après sa `def` ou après l\'`import`. Les variables créées dans une fonction n\'existent pas en dehors.',
  'errori.py-nome.cosa-2': ' Attention : en Python, on écrit `True`, `False` et `None`, avec une majuscule.',
  'errori.py-nome.cosa-3': ` Si {nome} devait être un texte, il manque les guillemets : {nome2}.`,
  'errori.py-nome.concetto': 'variables en Python',
  'errori.py-locale.etichetta': 'variable locale sans valeur',
  'errori.py-locale.frase-2': 'une variable',
  'errori.py-locale.frase': `tu utilises {nome} dans la fonction avant de lui donner une valeur`,
  'errori.py-locale.dove-2': 'la variable',
  'errori.py-locale.dove': `Regarde {laRiga} et cherche, dans la même fonction, où tu affectes {nome}.`,
  'errori.py-locale.cosa': 'Si dans une fonction tu affectes une valeur à une variable, pour Python elle devient locale dans toute la fonction, même dans les lignes d\'avant. Du coup, il ne lit plus la variable du même nom qui est dehors. Mieux vaut passer la valeur en paramètre et renvoyer le résultat avec `return`.',
  'errori.py-locale.concetto': 'fonctions et variables locales',
  'errori.py-tipo-concatena.etichetta': 'texte et nombre mélangés',
  'errori.py-tipo-concatena.frase': 'tu mélanges un texte (`str`) et un nombre',
  'errori.py-tipo-concatena.frase-2': `l'opération ne peut pas se faire entre {a} et {b}`,
  'errori.py-tipo-concatena.dove': `Regarde {laRiga} : de quel type est chaque valeur près de l'opérateur ?`,
  'errori.py-tipo-concatena.cosa': 'Pour Python, `"5"` (texte) et `5` (nombre) sont différents. Pour coller du texte et un nombre, convertis le nombre : `"Total : " + str(x)`, ou utilise une f-string : `f"Total : {x}"`. Si la valeur vient de `input()`, rappelle-toi que `input()` renvoie toujours du texte : pour calculer, il faut `int(input())` ou `float(input())`.',
  'errori.py-tipo-concatena.concetto': 'types en Python',
  'errori.py-tipo-indice.etichetta': '`[ ]` mal utilisés',
  'errori.py-tipo-indice.frase': 'l\'indice doit être un nombre entier',
  'errori.py-tipo-indice.frase-2': `une valeur \`{immut}\` ne peut pas être modifiée`,
  'errori.py-tipo-indice.frase-3': 'tu utilises `[ ]` sur une valeur `None`',
  'errori.py-tipo-indice.frase-4': `tu utilises \`[ ]\` sur une valeur de type {p}, qui n'a pas d'éléments`,
  'errori.py-tipo-indice.dove': `Regarde les crochets {allaRiga}.`,
  'errori.py-tipo-indice.cosa': 'Avec `v[i]`, `i` doit être un `int`. S\'il vient de `input()`, c\'est du texte : convertis-le avec `int()`. S\'il vient d\'une division avec `/`, c\'est un `float` : utilise `//`.',
  'errori.py-tipo-indice.cosa-2': 'En Python, les chaînes et les tuples ne se modifient pas : on crée une nouvelle valeur, par exemple `s = "C" + s[1:]`. Si tu as besoin de modifier les éléments, utilise une liste.',
  'errori.py-tipo-indice.cosa-3': 'Les crochets `[ ]` servent pour les listes, les chaînes, les dictionnaires et les tuples. Un nombre n\'a pas d\'éléments. Si le type est `NoneType`, la variable vaut `None` : c\'est souvent le résultat d\'une fonction sans `return`.',
  'errori.py-tipo-indice.concetto': 'listes et indices',
  'errori.py-tipo-argomenti.etichetta': 'mauvais nombre d\'arguments',
  'errori.py-tipo-argomenti.frase-2': 'la fonction',
  'errori.py-tipo-argomenti.frase': `{p} est appelée avec le mauvais nombre d'arguments`,
  'errori.py-tipo-argomenti.dove': `Compare l'appel {allaRiga} avec la ligne \`def\` de la fonction.`,
  'errori.py-tipo-argomenti.cosa': 'Une fonction s\'appelle avec autant d\'arguments qu\'il y a de paramètres dans sa `def`. Dans les méthodes d\'une classe, le premier paramètre est `self` et Python le passe tout seul : s\'il dit « takes 1 positional argument but 2 were given », il manque peut-être `self` dans la `def`.',
  'errori.py-tipo-argomenti.concetto': 'fonctions et paramètres',
  'errori.py-non-iterabile.etichetta': '`for` sur un nombre',
  'errori.py-non-iterabile.frase': `tu essaies de parcourir une valeur de type {p}, qui n'a pas d'éléments`,
  'errori.py-non-iterabile.dove': `Regarde {laRiga} : qu'est-ce qu'il y a après \`in\` ?`,
  'errori.py-non-iterabile.cosa': 'Le `for` parcourt les éléments d\'une liste, d\'une chaîne ou d\'un `range`. Un nombre n\'a pas d\'éléments : pour répéter n fois, on écrit `for i in range(n):`.',
  'errori.py-non-iterabile.concetto': 'boucles for',
  'errori.py-non-chiamabile.etichetta': '`( )` après quelque chose qui n\'est pas une fonction',
  'errori.py-non-chiamabile.frase': `tu mets \`( )\` après une valeur de type {p}, qui n'est pas une fonction`,
  'errori.py-non-chiamabile.dove': `Regarde {laRiga} : qu'est-ce qu'il y a juste avant les parenthèses ?`,
  'errori.py-non-chiamabile.cosa': 'Les parenthèses après un nom veulent dire « appelle cette fonction ». Souvent, une variable a le même nom qu\'une fonction (par exemple `sum = 0` puis `sum(v)`), ou il manque un opérateur : `2(x + 1)` au lieu de `2 * (x + 1)`.',
  'errori.py-non-chiamabile.concetto': 'fonctions',
  'errori.py-tipo.etichetta': 'mauvais type',
  'errori.py-tipo.frase': 'une opération reçoit une valeur du mauvais type',
  'errori.py-tipo.dove': `Regarde {laRiga} : de quel type sont les valeurs utilisées ? Tu peux les afficher avec \`print(type(x))\`.`,
  'errori.py-tipo.cosa': 'Chaque valeur en Python a un type (`int`, `str`, `list`…) et chaque opération n\'accepte que certains types. Le message original dit quels types il a trouvés.',
  'errori.py-tipo.concetto': 'types en Python',
  'errori.py-indice.etichetta': 'position qui n\'existe pas',
  'errori.py-indice.frase': 'tu enlèves un élément d\'une liste vide',
  'errori.py-indice.frase-stringa': 'tu lis une position que la chaîne n\'a pas',
  'errori.py-indice.frase-tupla': 'tu lis une position que le tuple n\'a pas',
  'errori.py-indice.frase-lista': 'tu lis une position que la liste n\'a pas',
  'errori.py-indice.dove': `Regarde {laRiga} : combien vaut l'indice à ce moment-là, et combien y a-t-il d'éléments ?`,
  'errori.py-indice.cosa': 'Une liste de n éléments a les positions de `0` à `n-1` : avec 3 éléments, la dernière est `v[2]`. Ça arrive souvent avec `range(len(v) + 1)` ou avec une boucle qui va un pas trop loin. Une liste vide n\'a aucune position : même `v[0]` est une erreur.',
  'errori.py-indice.concetto': 'listes et indices',
  'errori.py-chiave.etichetta': 'clé qui n\'existe pas',
  'errori.py-chiave.frase': `la clé {k} n'est pas dans le dictionnaire`,
  'errori.py-chiave.frase-2': 'la clé n\'est pas dans le dictionnaire',
  'errori.py-chiave.dove': `Regarde {laRiga} : comment est écrite la clé, et comment sont écrites celles du dictionnaire ?`,
  'errori.py-chiave.cosa': 'Avec `d[k]`, la clé doit déjà exister. Vérifie comment elle est écrite (majuscules, espaces, nombre ou texte). Pour vérifier avant : `if k in d:`. Pour avoir une valeur de secours : `d.get(k, 0)`.',
  'errori.py-chiave.concetto': 'dictionnaires',
  'errori.py-valore.etichetta': 'mauvaise valeur',
  'errori.py-valore.frase': `{v} ne peut pas être transformé en nombre`,
  'errori.py-valore.frase-2': 'il n\'y a pas autant de variables à gauche de `=` que de valeurs',
  'errori.py-valore.frase-3': 'une fonction mathématique reçoit une valeur qu\'elle n\'accepte pas',
  'errori.py-valore.frase-4': 'le type est bon mais pas la valeur',
  'errori.py-valore.dove': `Regarde {laRiga} : quelle valeur arrive vraiment là ? Tu peux l'afficher avec \`print(repr(x))\`.`,
  'errori.py-valore.cosa': '`int()` ne transforme en nombre qu\'un texte fait de chiffres. Des espaces au milieu, des lettres, le texte vide ou un nombre avec une virgule (`"2,5"`) ne passent pas. Pour les décimaux, il faut `float()` et le point : `"2.5"`. Si tu lis depuis `input()` ou un fichier, vérifie ce qui arrive vraiment.',
  'errori.py-valore.cosa-2': 'Avec `a, b = valeurs`, le nombre de variables à gauche doit être égal au nombre de valeurs à droite. Souvent, `split()` renvoie plus (ou moins) de morceaux que ce que tu attendais.',
  'errori.py-valore.cosa-3': 'Des fonctions comme `math.sqrt` et `math.log` n\'acceptent pas tous les nombres : pas de racine d\'un négatif, pas de logarithme de zéro. Vérifie la valeur avant l\'appel.',
  'errori.py-valore.cosa-4': 'La valeur a le bon type mais ne convient pas pour cette opération. Le message original dit quelle valeur posait problème.',
  'errori.py-valore.concetto': 'conversions et entrées',
  'errori.py-divisione-zero.etichetta': 'division par zéro',
  'errori.py-divisione-zero.frase': 'tu divises par zéro',
  'errori.py-divisione-zero.dove': `Regarde {laRiga} : quel diviseur vaut 0 à ce moment-là ? Souvent, c'est le \`len()\` d'une liste vide ou un compteur resté à 0.`,
  'errori.py-divisione-zero.cosa': 'Diviser par zéro n\'a pas de résultat, donc Python s\'arrête. C\'est pareil pour `//` et `%`. Avant la division, vérifie le diviseur : `if n != 0:`.',
  'errori.py-divisione-zero.concetto': 'division',
  'errori.py-attributo.etichetta': 'méthode ou attribut qui n\'existe pas',
  'errori.py-attributo.frase': `la variable vaut \`None\`, donc elle n'a pas {a}`,
  'errori.py-attributo.frase-2': `le module {mod} n'a pas {a}`,
  'errori.py-attributo.frase-3': `une valeur de type {p} n'a pas {a}`,
  'errori.py-attributo.frase-4': 'cette valeur n\'a pas cet attribut',
  'errori.py-attributo.dove': `Regarde {laRiga} : qu'est-ce qu'il y a avant le point, et de quel type c'est ?`,
  'errori.py-attributo.cosa': 'Une valeur `None` vient en général d\'une fonction sans `return`, ou de méthodes comme `v.sort()` qui modifient la liste et renvoient `None` (donc `v = v.sort()` perd la liste).',
  'errori.py-attributo.cosa-2': 'Vérifie comment le nom est écrit. Si ton fichier s\'appelle comme le module (par exemple `random.py` ou `math.py`), Python importe ton fichier à la place du vrai module : renomme-le.',
  'errori.py-attributo.cosa-3': 'Chaque type a ses méthodes : les listes ont `append`, `pop`, `sort` ; les chaînes ont `upper`, `split`, `strip`. Vérifie le nom de la méthode et le type de la variable.',
  'errori.py-attributo.concetto': 'méthodes et types',
  'errori.py-ricorsione.etichetta': 'récursion sans fin',
  'errori.py-ricorsione.frase': 'la fonction s\'appelle elle-même trop de fois',
  'errori.py-ricorsione.dove': `Regarde la fonction{funzione} {allaRiga} : où est le cas de base, et est-ce que chaque appel s'en rapproche ?`,
  'errori.py-ricorsione.cosa': 'Chaque fonction récursive a besoin d\'un cas de base : une condition où elle renvoie une valeur sans se rappeler. Et chaque appel doit se rapprocher du cas de base (par exemple `n - 1`, pas `n + 1`). Python s\'arrête après environ 1000 appels imbriqués.',
  'errori.py-ricorsione.concetto': 'récursivité',
  'errori.py-modulo.etichetta': 'module introuvable',
  'errori.py-modulo.frase': `dans le module {m}, il n'y a pas {nome}`,
  'errori.py-modulo.frase-2': `le module {m} est introuvable`,
  'errori.py-modulo.frase-3': 'un module ne s\'importe pas',
  'errori.py-modulo.dove': `Regarde la ligne \`import\` {allaRiga}.`,
  'errori.py-modulo.cosa': 'Soit le nom est mal écrit, soit le module n\'est pas installé pour ce Python. Les modules externes (par exemple `numpy`) s\'installent avec `python3 -m pip install nom` (sous Windows `py -m pip install nom`). Si le module est un de tes fichiers, il doit être dans le même dossier et s\'appeler `nom.py`.',
  'errori.py-modulo.concetto': 'modules et import',
  'errori.py-file.etichetta': 'fichier introuvable',
  'errori.py-file.frase': `je ne trouve pas le fichier {p}`,
  'errori.py-file.dove': `Regarde le \`open\` {allaRiga}.`,
  'errori.py-file.cosa': 'Python cherche le fichier à partir du dossier d\'où tu lances le programme, pas de celui du script. Vérifie le nom, l\'extension (Windows la cache parfois) et le dossier.',
  'errori.py-file.concetto': 'fichiers',
  'errori.py-input-finito.etichetta': 'entrée terminée',
  'errori.py-input-finito.frase': 'le programme demande une entrée qui n\'arrive pas',
  'errori.py-input-finito.dove': `Regarde le \`input()\` {allaRiga}.`,
  'errori.py-input-finito.cosa': '`input()` attendait une ligne, mais l\'entrée était déjà terminée. Dans les tests avec les fichiers `.in`, vérifie que le fichier a autant de lignes qu\'il y a de `input()`.',
  'errori.py-input-finito.concetto': 'entrées',
  'errori.esec-memoria.etichetta': 'mémoire qui ne lui appartient pas (segmentation fault)',
  'errori.esec-memoria.breve': 'mémoire interdite',
  'errori.esec-memoria.frase': 'le programme a utilisé de la mémoire qui ne lui appartient pas',
  'errori.esec-memoria.cosa': 'Ici, le pointeur valait `NULL`. ',
  'errori.esec-memoria.cosa-2': 'Souvent, c\'est un pointeur `NULL` (`p->next` avec `p` qui vaut `NULL`), un indice hors du tableau ou une récursion sans fin. Le système arrête le programme pour protéger le reste de la mémoire.',
  'errori.esec-memoria.cosa-3': ` Sous Windows, cette erreur a le code {codiceUscita}.`,
  'errori.esec-memoria.concetto': 'pointeurs et mémoire',
  'errori.esec-divisione-zero.etichetta': 'division entière par zéro',
  'errori.esec-divisione-zero.frase': 'le programme a divisé un entier par zéro',
  'errori.esec-divisione-zero.cosa': 'Un entier divisé par zéro (même avec `%`) n\'a pas de résultat et le système arrête le programme. Le nom « floating point exception » est trompeur : ça arrive justement avec les entiers. Vérifie les diviseurs, par exemple un compteur qui vaut encore 0.',
  'errori.esec-divisione-zero.concetto': 'division',
  'errori.esec-stack.etichetta': 'pile des appels pleine (stack overflow)',
  'errori.esec-stack.frase': 'la pile des appels est pleine : peut-être une récursion sans fin',
  'errori.esec-stack.cosa': 'Chaque appel de fonction occupe un peu de mémoire dans la pile (la stack). Une fonction récursive sans cas de base, ou avec un cas de base jamais atteint, la remplit. Un énorme tableau local peut suffire aussi : dans ce cas, utilise `malloc`.',
  'errori.esec-stack.concetto': 'récursivité',
  'errori.esec-fuori-array.etichetta': 'écriture hors d\'un tableau',
  'errori.esec-fuori-array.frase': 'le programme a lu ou écrit hors d\'un tableau',
  'errori.esec-fuori-array.frase-letto': 'le programme a lu hors d\'un tableau',
  'errori.esec-fuori-array.frase-scritto': 'le programme a écrit hors d\'un tableau',
  'errori.esec-fuori-array.cosa': 'Un tableau de N éléments va de `0` à `N-1`. Vérifie les conditions des boucles (`<` et pas `<=`), les chaînes sans place pour le `\'\\0\'` final et les `malloc` avec la bonne taille (`n * sizeof(int)`).',
  'errori.esec-fuori-array.concetto': 'tableaux et indices',
  'errori.esec-heap.etichetta': 'malloc et free mal utilisés',
  'errori.esec-heap.frase': 'la mémoire prise avec `malloc` a été mal utilisée',
  'errori.esec-heap.cosa': 'Ça arrive quand tu libères deux fois la même mémoire (`free` deux fois), quand tu utilises un pointeur après `free`, ou quand tu écris après la fin d\'un bloc pris avec `malloc`. Après `free(p);`, ça aide d\'écrire `p = NULL;`.',
  'errori.esec-heap.concetto': 'mémoire dynamique',
  'errori.esec-memoria-persa.etichetta': 'mémoire jamais libérée',
  'errori.esec-memoria-persa.frase': 'le programme prend de la mémoire avec `malloc` et ne la libère pas',
  'errori.esec-memoria-persa.cosa': 'Chaque `malloc` (ou `calloc`) doit avoir son `free` quand la mémoire ne sert plus. Dans les listes, il faut libérer chaque nœud, un par un, avant de perdre le pointeur.',
  'errori.esec-memoria-persa.concetto': 'mémoire dynamique',
  'errori.esec-non-inizializzata.etichetta': 'valeur jamais initialisée',
  'errori.esec-non-inizializzata.frase': 'le programme utilise une valeur qui n\'a jamais été initialisée',
  'errori.esec-non-inizializzata.cosa': 'Une variable locale (ou la mémoire prise avec `malloc`) contient des valeurs au hasard tant que tu ne lui donnes pas de valeur. Initialise-la avant de la lire.',
  'errori.esec-non-inizializzata.concetto': 'initialisation des variables',
  'errori.esec-asserzione.etichetta': 'assert échouée',
  'errori.esec-asserzione.frase': `une \`assert\` a échoué : {cond} était fausse`,
  'errori.esec-asserzione.frase-2': 'une `assert` a échoué',
  'errori.esec-asserzione.cosa': '`assert(condition)` arrête le programme si la condition est fausse. Celui qui l\'a écrite (toi ou ton prof) dit : « ici, ça doit toujours être vrai ». Le vrai problème est avant : cherche où la valeur est devenue fausse.',
  'errori.esec-asserzione.concetto': 'assert et vérifications',
  'errori.esec-abort.etichetta': 'programme interrompu (abort)',
  'errori.esec-abort.frase': 'le programme s\'est interrompu tout seul (abort)',
  'errori.esec-abort.cosa': 'En général, c\'est la bibliothèque qui le demande quand elle trouve un problème grave : une `assert` échouée, un `free` faux, de la mémoire abîmée. Regarde les lignes affichées juste avant : souvent elles disent pourquoi.',
  'errori.esec-abort.concetto': 'mémoire dynamique',
  'errori.esec-overflow.etichetta': 'entier trop grand',
  'errori.esec-overflow.frase': 'un entier est devenu trop grand',
  'errori.esec-overflow.cosa': 'Un `int` va jusqu\'à 2147483647. Au-delà, le résultat est faux. Ça arrive avec les factorielles et les puissances : utilise `long long` (avec `%lld` dans `printf`), ou vérifie les calculs.',
  'errori.esec-overflow.concetto': 'types entiers',
  'errori.esec-tempo.etichetta': 'délai dépassé',
  'errori.esec-tempo.frase': 'le programme n\'a pas fini à temps',
  'errori.esec-tempo.cosa': 'Il y a peut-être une boucle qui ne finit pas : la condition ne devient jamais fausse, ou la variable de la boucle ne change pas. Ou alors le programme attend une entrée (`scanf`, `input()`) qui n\'arrive pas.',
  'errori.esec-tempo.concetto': 'boucles',
  'errori.esec-segnale.etichetta': 'programme arrêté par le système',
  'errori.esec-segnale.frase': `le programme a été arrêté par le système{segnale}`,
  'errori.esec-segnale.cosa': 'Le système a arrêté le programme pendant qu\'il tournait. Lode ne peut pas en dire plus à partir de ce signal : regarde les dernières lignes affichées et les lignes modifiées récemment.',
  'errori.esec-segnale.concetto': 'exécution',
  // ---- hors du dictionnaire : lieux, comptes, étapes, corrections, fiche ----
  'errori.tempo-scaduto': 'Délai dépassé',
  'errori.segnale': 'Signal {sig}',
  'errori.codice-uscita': `Code de sortie {codice}`,
  'errori.codice-uscita-windows': `Code de sortie {codice} ({codiceUscita})`,
  'errori.altri-errori': { one: 'une autre erreur', other: '{n} autres erreurs' },
  'errori.avvisi': { one: '1 avertissement', other: '{n} avertissements' },
  'errori.conto': 'et {cosa}',
  'errori.conto-errori-e-avvisi': 'et {errori} et {avvisi}',
  'errori.un-nome': 'un nom',
  'errori.alla-riga': 'à la ligne {n}',
  'errori.nel-punto-indicato': 'à l\'endroit indiqué',
  'errori.la-riga': 'la ligne {n}',
  'errori.il-punto-indicato': 'l\'endroit indiqué',
  'errori.colonna': ', colonne {n}',
  'errori.del-if': 'du `if`',
  'errori.del-while': 'du `while`',
  'errori.del-for': 'du `for`',
  'errori.sconosciuto': 'erreur inconnue',
  'errori.errore': 'erreur',
  'errori.nella-funzione': ', dans la fonction {funzione}',
  'errori.di-file': ' de {file}',
  'errori.fermato-alla-riga': 'Le programme s\'est arrêté à la ligne {riga}{file}{funzione}.',
  'errori.poi-guarda-cambiate': ` Ensuite, regarde les lignes modifiées après le dernier test réussi : {righe}.`,
  'errori.guarda-prima-cambiate': `Regarde d'abord les lignes modifiées après le dernier test réussi : {righe}.`,
  'errori.sistema-senza-riga': 'Le système ne donne pas la ligne. Ajoute quelques `printf` pour voir jusqu\'où va le programme ; sur Mac et Linux, tu peux aussi compiler avec `-g -fsanitize=address` pour avoir le fichier et la ligne.',
  'errori.messaggio-senza-riga': 'Le message ne donne pas la ligne : regarde les dernières lignes affichées par le programme.',
  'errori.cambiate-e-altre': { one: '{righe} et {n} autre', other: '{righe} et {n} autres' },
  'errori.correggi-punto': `Ajoute \`;\` à la fin de l'instruction : à la ligne {riga} ou à celle d'avant.`,
  'errori.correggi-punto-senza-riga': 'Ajoute `;` à la fin de l\'instruction.',
  'errori.correggi-punto-fine': `À la fin de la ligne {riga}, ajoute \`;\` :`,
  'errori.correggi-punto-dentro': `À la ligne {riga}, à l'endroit indiqué, ajoute \`;\` :`,
  'errori.correggi-include-in-cima': 'En haut du fichier, avec les autres `#include`, ajoute :',
  'errori.correggi-include-dopo': 'Après la ligne {riga}, ajoute :',
  'errori.correggi-include-primo': 'En haut du fichier, ajoute :',
  'errori.correggi-uguale': 'Dans la condition, remplace `=` par `==`.',
  'errori.correggi-uguale-riga': `À la ligne {riga}, remplace \`=\` par \`==\` :`,
  'errori.correggi-return': `Avant la \`}\` qui ferme {nome}, ajoute un \`return\` avec la bonne valeur pour les cas oubliés. Quelle valeur, c'est toi qui décides : ça dépend de ce que la fonction doit calculer.`,
  'errori.correggi-return-senza-nome': `Avant la \`}\` qui ferme la fonction, ajoute un \`return\` avec la bonne valeur pour les cas oubliés. Quelle valeur, c'est toi qui décides : ça dépend de ce que la fonction doit calculer.`,
  'errori.generico.dove-linker': 'Le linker n\'indique pas de ligne : cherche dans le projet le nom cité dans le message, et vérifie que tous les fichiers `.c` sont dans la commande de compilation.',
  'errori.generico.dove-senza-riga': 'Le message n\'indique pas de ligne : lis le texte original ci-dessous.',
  'errori.generico.dove-python': '{L} s\'est arrêté {allaRiga}{file}. Si tout a l\'air juste là, regarde la ligne d\'avant.',
  'errori.generico.dove': 'Regarde {laRiga}{colonna}{file}. Si tout a l\'air juste là, regarde aussi la ligne d\'avant : souvent, le compilateur ne remarque un problème qu\'après.',
  'errori.generico.eccezione-leggendo': '{eccezione} est le type d\'erreur que {L} a rencontré en lisant le programme. ',
  'errori.generico.eccezione-eseguendo': '{eccezione} est le type d\'erreur que {L} a rencontré en exécutant le programme. ',
  'errori.generico.cosa': 'Lode n\'a pas encore d\'explication pour ce message. Le texte original est ci-dessous : lis les mots entre apostrophes, en général c\'est le nom ou le type qui pose problème.',
  'errori.catena': ' Tu y es arrivé comme ça : {passi}.',
  'errori.catena-passo': 'ligne {riga}{file} ({funzione})',
  'errori.luogo-file-riga': '{file}, ligne {riga}',
  'errori.luogo-riga': 'ligne {riga}',
  'errori.con-eccezione': '{eccezione} : {frase}',
  'errori.intestazione': '**{luogo}** : {frase}',
  'errori.intestazione-eccezione': '**{luogo}** · {frase}',
  'errori.per-diario': '{dove}« {breve} »',
  'errori.non-lo-conosco': 'je ne connais pas encore cette erreur',
  'errori.parola-avviso': 'avertissement',
  'errori.e-un-avviso': `C'est un avertissement : le programme compile quand même, mais tel quel il ne fait sans doute pas ce que tu veux. {cosa}`,
  'errori.passo-dove': 'Où regarder',
  'errori.passo-cosa': 'Ce que ça veut dire',
  'errori.passo-correzione': 'Montre-moi la correction',
  'errori.file-cambiato': 'Le fichier a changé depuis : les numéros de ligne ne correspondent peut-être plus.',
  'errori.tipo-errore': 'Erreur',
  'errori.tipo-avviso': 'Avertissement',
  'errori.tipo-linker': 'Erreur du linker',
  'errori.tipo-esecuzione': 'Il s\'est arrêté',
  'errori.segnaposto-valore': '‹valeur›',
  'errori.correzione-vista': 'correction vue',
  'errori.messaggio-originale': 'Message original',
};
