// Données d'exemple (esempio() dans js/dati.js) et mots affichés par les programmes de «Cosa stampa?». Même forme que it/esempio.js.
export default {
  'esempio.nome': 'Camille',
  'esempio.corso': 'Génie informatique',
  'esempio.esami': ['Analyse 1', 'Algorithmique et programmation', 'Algèbre linéaire', 'Physique 1', 'Anglais B2', 'Programmation orientée objet', 'Analyse 2', 'Bases de données', 'Physique 2'],
  'esempio.aule': ['A102', 'Salle TP 3', 'Amphi A'],
  'esempio.carte': [
    ["Qu'est-ce que le gradient de f(x, y) ?", 'Le vecteur des dérivées partielles (∂f/∂x, ∂f/∂y) : il pointe dans la direction de plus forte croissance.'],
    ['Énonce le théorème de Schwarz', "Si les dérivées secondes croisées sont continues au voisinage d'un point, alors f_xy = f_yx."],
    ['Condition pour un point critique', "Le gradient s'annule : ∇f(x₀) = 0."],
    ['Comment classer un point critique ?', 'Avec la matrice hessienne : définie positive → minimum, définie négative → maximum, indéfinie → point selle.'],
    ["Qu'est-ce qu'une intégrale double sur un domaine élémentaire ?", "Une intégrale itérée : d'abord sur la variable « intérieure », avec des bornes qui dépendent de l'autre, puis sur l'autre."],
    ['Formule de Green-Riemann : énoncé', "L'intégrale curviligne sur ∂D de P dx + Q dy est égale à l'intégrale double sur D de (∂Q/∂x − ∂P/∂y)."],
    ['Forme différentielle exacte : définition', "ω est exacte s'il existe une fonction U (un potentiel) telle que dU = ω."],
    ['Série géométrique : quand converge-t-elle ?', 'Pour |q| < 1, avec pour somme 1/(1 − q).'],
    ["Qu'est-ce qu'une clé primaire ?", "Un ensemble minimal d'attributs qui identifie de façon unique chaque n-uplet d'une relation."],
    ['Différence entre LEFT JOIN et INNER JOIN', "Le LEFT JOIN garde toutes les lignes de la table de gauche, même sans correspondance (avec NULL) ; l'INNER JOIN seulement les couples qui correspondent."],
    ['Que garantit la troisième forme normale ?', "Que chaque attribut non clé dépende de la clé, de toute la clé et de rien d'autre que la clé (pas de dépendance transitive)."],
  ],
  'esempio.domande': ['Pourquoi le théorème de Schwarz exige-t-il que les dérivées croisées soient continues ?'],
  'esempio.stelle': ['La formule de Green-Riemann tombe à chaque examen, avec la démonstration', 'Classer les points critiques avec la hessienne : exercice assuré'],
  'esempio.stelle-basi': ["Normalisation jusqu'à la FNBC : toujours à l'écrit"],
  'esempio.definizioni': [
    ['Gradient', 'Le vecteur des dérivées partielles de f : il pointe dans la direction de plus forte croissance.'],
    ['Point critique', "Un point où le gradient de la fonction s'annule."],
    ['Matrice hessienne', "La matrice carrée des dérivées partielles secondes d'une fonction."],
    ['Point selle', "Un point critique qui n'est ni un maximum ni un minimum local : la hessienne est indéfinie."],
    ['Formule de Green-Riemann', "Elle relie l'intégrale curviligne le long du bord d'un domaine à l'intégrale double sur le domaine."],
    ['Forme différentielle exacte', "Une forme qui admet un potentiel, c'est-à-dire qui est la différentielle d'une fonction."],
  ],
  'esempio.definizioni-basi': [
    ['Clé primaire', "Un ensemble minimal d'attributs qui identifie de façon unique chaque n-uplet."],
    ['Clé étrangère', "Un attribut qui fait référence à la clé primaire d'une autre relation."],
    ['Dépendance fonctionnelle', "Une contrainte selon laquelle la valeur d'un ensemble d'attributs détermine celle d'un autre."],
    ['Forme normale de Boyce-Codd', 'Toute dépendance fonctionnelle non triviale a une super-clé à gauche.'],
  ],
  'esempio.switch-parole': ['un', 'deux', 'trois', 'quatre'],
  'esempio.switch-altro': 'autre',
  'esempio.si': 'oui',
  'esempio.no': 'non',
  'esempio.hai-scritto': 'Tu as écrit `{s}`',
};
