// « Nouveautés », le dictionnaire fixe de la bibliothèque standard (français) : pour chaque entrée, la question d'oral
// et la réponse. Les noms des fonctions et les règles qui les cherchent dans le code restent dans js/codice/glossario.js.
export default {
  'glossario.malloc.domanda': 'Que contient la mémoire que malloc vient de renvoyer ?',
  'glossario.malloc.risposta': "Des valeurs au hasard : malloc ne la met pas à zéro. S'il n'y a plus de mémoire, malloc renvoie NULL, donc on vérifie avant de l'utiliser.",
  'glossario.calloc.domanda': 'Quelle différence entre calloc(n, size) et malloc(n * size) ?',
  'glossario.calloc.risposta': "calloc met tous les octets à zéro, malloc laisse des valeurs au hasard. S'il n'y a plus de mémoire, les deux renvoient NULL.",
  'glossario.realloc.domanda': 'Que fait realloc si elle échoue ?',
  'glossario.realloc.risposta': "Elle renvoie NULL et l'ancien bloc reste valide : il faut le libérer à part. C'est pour ça qu'on écrit p2 = realloc(p, n) et pas p = realloc(p, n).",
  'glossario.free.domanda': 'Que se passe-t-il si tu utilises un pointeur après free ?',
  'glossario.free.risposta': "C'est un comportement indéfini : cette mémoire n'est plus à toi. La libérer deux fois aussi. En revanche, free(NULL) ne fait rien.",
  'glossario.strtok.domanda': "Pourquoi on ne peut pas utiliser strtok sur une chaîne littérale ?",
  'glossario.strtok.risposta': "Parce qu'elle écrit dans la chaîne : à la place de chaque séparateur, elle met '\\0'. À partir du deuxième appel, on passe NULL et strtok repart de l'endroit qu'elle a mémorisé.",
  'glossario.strcpy.domanda': 'Que vérifie strcpy sur la taille de la destination ?',
  'glossario.strcpy.risposta': "Rien : elle copie jusqu'au '\\0' inclus. Si la destination est trop petite, elle écrit après la fin du tableau, et c'est un comportement indéfini.",
  'glossario.strncpy.domanda': "strncpy(d, s, n) met-elle toujours le '\\0' final ?",
  'glossario.strncpy.risposta': "Non : si s a n caractères ou plus, il n'y a aucun '\\0' dans d. Si s est plus courte, elle remplit le reste avec des zéros.",
  'glossario.strcmp.domanda': 'Que renvoie strcmp si les deux chaînes sont égales ?',
  'glossario.strcmp.risposta': '0. Un nombre négatif si la première vient avant, positif si elle vient après : c\'est pour ça que if (strcmp(a, b)) veut dire « elles sont différentes ».',
  'glossario.strlen.domanda': "strlen compte-t-elle aussi le '\\0' final ?",
  'glossario.strlen.risposta': "Non : elle compte les caractères avant le '\\0'. Pour copier la chaîne, il faut strlen(s) + 1 octets.",
  'glossario.strcat.domanda': 'Que faut-il pour que strcat(d, s) marche ?',
  'glossario.strcat.risposta': "d doit déjà contenir une chaîne avec son '\\0' et avoir la place pour les deux, plus le '\\0'. strcat ne vérifie pas la place.",
  'glossario.memcpy.domanda': 'Peut-on utiliser memcpy si la source et la destination se chevauchent ?',
  'glossario.memcpy.risposta': "Non, c'est un comportement indéfini. Dans ce cas, on utilise memmove.",
  'glossario.memset.domanda': 'memset(v, 1, n * sizeof(int)) met-il les int de v à 1 ?',
  'glossario.memset.risposta': 'Non : memset écrit la même valeur dans chaque octet, donc chaque int de 32 bits vaut 16843009. Pour mettre à zéro, par contre, ça marche : memset(v, 0, …).',
  'glossario.sizeof.domanda': 'Combien vaut sizeof(v) si v est un paramètre int v[] ?',
  'glossario.sizeof.risposta': "La taille d'un pointeur, pas du tableau : en paramètre, int v[] est un int *v. C'est pour ça qu'on passe la longueur à part.",
  'glossario.fgets.domanda': 'Que laisse fgets à la fin de la ligne lue ?',
  'glossario.fgets.risposta': "Le retour à la ligne, s'il tenait, puis le '\\0' : avec fgets(s, n, f), elle lit au plus n - 1 caractères. En fin de fichier, elle renvoie NULL.",
  'glossario.scanf.domanda': 'Que renvoie scanf ?',
  'glossario.scanf.risposta': "Le nombre de valeurs lues et affectées, ou EOF si l'entrée se termine avant. Si tu ne le vérifies pas, une lettre à la place d'un nombre passe sans rien dire.",
  'glossario.sscanf.domanda': 'Quelle différence entre scanf et sscanf ?',
  'glossario.sscanf.risposta': "sscanf lit dans une chaîne au lieu de l'entrée. On l'utilise souvent après fgets : d'abord tu lis la ligne entière, puis tu la découpes.",
  'glossario.fopen.domanda': "Que renvoie fopen si le fichier ne s'ouvre pas ?",
  'glossario.fopen.risposta': 'NULL : il faut le vérifier avant de lire ou d\'écrire. Attention : avec "w", un fichier qui existe déjà est vidé tout de suite.',
  'glossario.fclose.domanda': 'Que fait fclose sur un fichier dans lequel tu as écrit ?',
  'glossario.fclose.risposta': "Elle écrit dans le fichier ce qui est encore dans le buffer et libère le FILE. Après fclose, on n'utilise plus ce pointeur.",
  'glossario.fprintf.domanda': 'Quelle différence entre fprintf(stderr, ...) et printf(...) ?',
  'glossario.fprintf.risposta': "printf écrit sur stdout, fprintf sur le flux que tu lui passes. stderr n'a en général pas de buffer et ne finit pas dans le fichier si tu rediriges la sortie avec >.",
  'glossario.atoi.domanda': 'Que renvoie atoi("salut") ?',
  'glossario.atoi.risposta': '0, sans aucun signal d\'erreur : tu ne distingues pas "0" d\'un texte faux. Pour vérifier, on utilise strtol.',
  'glossario.strtol.domanda': 'À quoi sert le deuxième argument de strtol ?',
  'glossario.strtol.risposta': "C'est un char ** où strtol met l'endroit où elle s'est arrêtée : s'il est égal au début, elle n'a lu aucun chiffre. Le troisième argument est la base.",
  'glossario.qsort.domanda': 'Que doit renvoyer la fonction de comparaison de qsort ?',
  'glossario.qsort.risposta': "Un int négatif, nul ou positif si le premier élément va avant, est égal ou va après. Elle reçoit deux const void * à convertir dans le bon type.",
  'glossario.exit.domanda': 'Quelle différence entre exit(1) et return 1 dans main ?',
  'glossario.exit.risposta': "Dans main, ils font la même chose. Mais exit termine le programme depuis n'importe quelle fonction, après avoir vidé et fermé les fichiers ouverts.",
  'glossario.assert.domanda': 'Que fait assert(x) si x est faux ?',
  'glossario.assert.risposta': "Elle écrit sur stderr la condition, le fichier et la ligne, puis arrête le programme avec abort. Avec -DNDEBUG, les assert disparaissent : n'y mets pas de code qui sert.",
  'glossario.static-locale.domanda': 'Que change le fait de déclarer static une variable dans une fonction ?',
  'glossario.static-locale.risposta': "Elle est initialisée une seule fois et garde sa valeur d'un appel à l'autre. Si tu ne l'initialises pas, elle part de 0.",
  'glossario.computeifabsent.domanda': 'Que fait map.computeIfAbsent(k, x -> new ArrayList<>()) ?',
  'glossario.computeifabsent.risposta': "Si k n'y est pas, elle crée la liste, la met dans la map et la renvoie. Si elle y est déjà, elle renvoie celle-là. Comme ça, après, tu peux faire .add sans vérifier.",
  'glossario.getordefault.domanda': "Que renvoie map.getOrDefault(k, 0) si k n'y est pas ?",
  'glossario.getordefault.risposta': "0, et la map ne change pas : k n'est pas ajoutée.",
  'glossario.putifabsent.domanda': 'Que renvoie map.putIfAbsent(k, v) ?',
  'glossario.putifabsent.risposta': "La valeur qui était déjà là, et alors la map ne change pas. Si k n'y était pas, elle met v et renvoie null.",
  'glossario.list-remove.domanda': 'Sur une List<Integer> qui contient [5, 7, 9], que fait list.remove(1) ?',
  'glossario.list-remove.risposta': "Elle enlève l'élément à la position 1, donc 7 : avec un int, c'est remove(int index) qui est choisi. Pour enlever la valeur 1, il faut list.remove(Integer.valueOf(1)).",
  'glossario.equals.domanda': 'Quelle différence entre == et equals sur deux String ?',
  'glossario.equals.risposta': "== vérifie si c'est le même objet, equals s'ils ont les mêmes caractères. Deux chaînes égales peuvent être deux objets différents.",
  'glossario.hashcode.domanda': 'Si tu redéfinis equals, que dois-tu faire avec hashCode ?',
  'glossario.hashcode.risposta': "Le redéfinir aussi : des objets égaux pour equals doivent avoir le même hashCode. Sinon HashMap et HashSet ne les retrouvent pas.",
  'glossario.collections-sort.domanda': 'Collections.sort est-il stable ?',
  'glossario.collections-sort.risposta': "Oui : les éléments égaux pour la comparaison restent dans l'ordre d'avant. Il trie la liste sur place et ne renvoie rien.",
  'glossario.comparator-comparing.domanda': 'Que fait Comparator.comparing(Studente::getVoto).reversed() ?',
  'glossario.comparator-comparing.risposta': 'Il compare les étudiants par note, à l\'envers : de la plus haute à la plus basse. Avec thenComparing, tu ajoutes un deuxième critère à note égale.',
  'glossario.optional.domanda': "Pourquoi on n'appelle pas get() sur un Optional sans vérifier ?",
  'glossario.optional.risposta': "S'il est vide, get() lance NoSuchElementException. On utilise orElse, orElseGet ou isPresent.",
  'glossario.stream.domanda': 'Que se passe-t-il si tu appelles seulement map et filter sur un stream, sans collect ?',
  'glossario.stream.risposta': "Rien : map et filter sont paresseuses. Le travail ne démarre qu'avec une opération terminale comme collect, forEach ou count. Et un stream ne s'utilise qu'une fois.",
  'glossario.stringbuilder.domanda': 'Pourquoi, dans une boucle, on utilise StringBuilder au lieu de s = s + x ?',
  'glossario.stringbuilder.risposta': "Une String ne change jamais : chaque + en crée une nouvelle et recopie tout. StringBuilder ajoute à la fin du même objet, et toString() donne le résultat.",
  'glossario.integer-parseint.domanda': 'Que se passe-t-il avec Integer.parseInt("12a") ?',
  'glossario.integer-parseint.risposta': 'Ça lance NumberFormatException. Même " 12" avec l\'espace la lance : on utilise d\'abord trim().',
  'glossario.scanner-nextint.domanda': 'Pourquoi un nextLine() juste après nextInt() renvoie une ligne vide ?',
  'glossario.scanner-nextint.risposta': 'nextInt lit le nombre mais laisse le retour à la ligne. nextLine lit jusqu\'à ce retour à la ligne et renvoie "". On fait un nextLine() en plus pour le jeter.',
  'glossario.try-with-resources.domanda': 'Que fait try (Scanner in = new Scanner(f)) { ... } ?',
  'glossario.try-with-resources.risposta': "Il ferme tout seul la ressource à la fin du bloc, même si une exception arrive. Ça marche avec les classes qui implémentent AutoCloseable.",
  'glossario.instanceof.domanda': 'Que renvoie x instanceof String si x est null ?',
  'glossario.instanceof.risposta': 'false, sans exception. Depuis Java 16, tu peux écrire x instanceof String s et utiliser s tout de suite.',
  'glossario.arrays-aslist.domanda': 'Que se passe-t-il si tu fais add sur la liste de Arrays.asList ?',
  'glossario.arrays-aslist.risposta': "Ça lance UnsupportedOperationException : la liste a une taille fixe et elle est liée au tableau. set, par contre, marche, et modifie aussi le tableau.",
  'glossario.iterator-remove.domanda': 'Comment enlever des éléments d\'une liste pendant que tu la parcours ?',
  'glossario.iterator-remove.risposta': 'Avec un Iterator et it.remove(), ou avec removeIf. Avec list.remove dans un for-each, tu obtiens en général une ConcurrentModificationException.',
  'glossario.substring.domanda': 'Que renvoie "lecture".substring(1, 4) ?',
  'glossario.substring.risposta': '"ect" : les caractères de la position 1 à la 3. Le deuxième indice est exclu, et la chaîne de départ ne change pas.',
  'glossario.compareto.domanda': 'Que renvoie a.compareTo(b) ?',
  'glossario.compareto.risposta': "Un nombre négatif si a vient avant b, zéro s'ils sont égaux, positif s'il vient après. Pas forcément -1 ou 1 : c'est le signe qui compte.",
  'glossario.list-comprehension.domanda': 'Que construit [x * 2 for x in v if x > 0] ?',
  'glossario.list-comprehension.risposta': "Une nouvelle liste avec le double des seuls éléments positifs de v. C'est un for avec un if et un append écrit sur une ligne ; v ne change pas.",
  'glossario.list-comprehension-annidata.domanda': 'Dans [x for riga in m for x in riga], quel for est le for extérieur ?',
  'glossario.list-comprehension-annidata.risposta': "Le premier : les for se lisent dans l'ordre où tu les écrirais l'un dans l'autre. Le résultat, c'est m aplatie en une seule liste.",
  'glossario.lambda.domanda': 'Que peut contenir une lambda en Python ?',
  'glossario.lambda.risposta': "Une seule expression, qui devient la valeur renvoyée. Pas d'instructions comme return, for ou une affectation normale.",
  'glossario.sorted-con-key.domanda': 'Que fait sorted(v, key=len) ?',
  'glossario.sorted-con-key.risposta': "Elle renvoie une nouvelle liste triée par longueur ; v reste telle quelle. À longueur égale, l'ordre de départ est gardé : le tri est stable.",
  'glossario.enumerate.domanda': 'Que donne enumerate(v) ?',
  'glossario.enumerate.risposta': "Les couples (indice, élément), avec l'indice qui part de 0. Avec enumerate(v, 1), il part de 1.",
  'glossario.zip.domanda': 'Que fait zip si les listes ont des longueurs différentes ?',
  'glossario.zip.risposta': "Elle s'arrête à la plus courte : les éléments en trop sont perdus sans erreur. Depuis Python 3.10, avec strict=True, ça donne une erreur.",
  'glossario.dict-get.domanda': 'Quelle différence entre d[k] et d.get(k) ?',
  'glossario.dict-get.risposta': "d[k] lance KeyError si k manque, d.get(k) renvoie None, ou le deuxième argument si tu le passes. get n'ajoute pas k.",
  'glossario.setdefault.domanda': 'Que fait d.setdefault(k, []) ?',
  'glossario.setdefault.risposta': "Si k manque, elle l'ajoute avec [] et renvoie cette liste. Si k y est déjà, elle renvoie la valeur existante. La [] est créée de toute façon à chaque appel.",
  'glossario.defaultdict.domanda': 'Que se passe-t-il si tu lis une clé absente dans un defaultdict(list) ?',
  'glossario.defaultdict.risposta': "Il la crée avec une liste vide et la renvoie, sans KeyError. Attention : même une simple lecture de d[k] ajoute k.",
  'glossario.counter.domanda': "Que renvoie un Counter pour une clé qu'il n'a jamais vue ?",
  'glossario.counter.risposta': '0, sans KeyError et sans l\'ajouter. most_common(n) donne les n plus fréquentes.',
  'glossario.with-open.domanda': 'Pourquoi on écrit with open(nome) as f ?',
  'glossario.with-open.risposta': "Le fichier se ferme tout seul à la sortie du bloc, même si une exception arrive. Sans with, tu dois appeler f.close().",
  'glossario.yield.domanda': 'Que renvoie une fonction qui contient yield ?',
  'glossario.yield.risposta': "Un générateur. Le corps ne démarre que quand tu demandes la première valeur, avec next ou un for, et il s'arrête à chaque yield. Il ne se parcourt qu'une fois.",
  'glossario.args-e-kwargs.domanda': 'Dans def f(*args, **kwargs), que sont args et kwargs ?',
  'glossario.args-e-kwargs.risposta': 'args est un tuple avec les arguments positionnels en plus, kwargs un dictionnaire avec ceux passés par nom.',
  'glossario.rovescia.domanda': 'Que donne v[::-1] ?',
  'glossario.rovescia.risposta': "Une copie de v à l'envers : ça marche avec les listes, les chaînes et les tuples. v ne change pas.",
  'glossario.is-e-uguale.domanda': 'Quelle différence entre is et == ?',
  'glossario.is-e-uguale.risposta': "== compare les valeurs, is vérifie si c'est le même objet. On utilise is avec None ; avec les nombres et les chaînes, on utilise ==.",
  'glossario.default-mutabile.domanda': 'Pourquoi def f(x, v=[]) est un piège ?',
  'glossario.default-mutabile.risposta': "La liste par défaut est créée une seule fois, quand f est définie : chaque appel voit les modifications des précédents. On écrit v=None et on crée la liste dans la fonction.",
  'glossario.f-string.domanda': 'Qu\'affiche print(f"{x:.2f}") si x vaut 3.14159 ?',
  'glossario.f-string.risposta': '3.14 : après les deux-points, il y a le format, et .2f veut dire deux chiffres après la virgule, arrondis.',
  'glossario.extend.domanda': 'Quelle différence entre v.append(w) et v.extend(w) ?',
  'glossario.extend.risposta': "append ajoute w comme un seul élément, même si c'est une liste. extend ajoute un par un les éléments de w. Les deux modifient v et renvoient None.",
  'glossario.split.domanda': 'Quelle différence entre s.split() et s.split(" ") ?',
  'glossario.split.risposta': 'Sans argument, elle coupe sur n\'importe quel blanc, même plusieurs à la suite, et saute les morceaux vides. Avec " ", chaque espace sépare : deux espaces de suite donnent une chaîne vide.',
  'glossario.da-riga': 'Dans : {file}, ligne {riga}',
};
