// « Je veux faire… » (js/guida.js et le guide dans la barre, js/lode.js) : les fiches du guide pas à pas et les recettes écrites à
// la main pour quand il n'y a pas d'IA. Chaque étape d'une recette est une liste de quatre textes : [titre, ce qu'on fait (2 à 4
// phrases simples), quand c'est fait, un coup de pouce pour qui n'y arrive pas]. Le nombre d'étapes de chaque recette est dans RICETTE de js/guida.js.
export default {
  'guida.serve-per': 'Pour « {cosa} », il te faut :',
  'guida.nessuna-app': "Je n'ai trouvé aucune appli adaptée sur l'ordinateur. Ce n'est pas grave : quand il le faudra, l'étape te dira quoi installer.",
  'guida.apri': 'Ouvrir',
  'guida.apri-tutte': 'Tout ouvrir',
  'guida.aperta': 'Appli ouverte : {app}.',
  'guida.non-aperta': "Je n'ai pas réussi à ouvrir {app}.",
  'guida.cominciamo': 'Allons-y',
  'guida.preparo': 'Je prépare le plan',
  'guida.piano-ai': "Plan écrit avec {motore} : si une étape ne te convient pas, passe-la.",
  'guida.piano-ricetta': "Plan de Lode, sans IA.",
  'guida.piano-generico': "Pour ça, je n'ai pas de recette : je te propose un plan général, à adapter.",
  'guida.piano-ripiego': "L'IA n'a pas donné de plan valable : j'utilise celui de Lode.",
  'guida.passo-di': 'Étape {i} sur {tot}',
  'guida.fatto-quando': 'Terminé quand : {quando}',
  'guida.ti-serve': 'Il te faut : {app}',
  'guida.fatto-avanti': 'Fait, suivant',
  'guida.non-ci-riesco': "Je n'y arrive pas",
  'guida.indietro': 'Retour',
  'guida.basta': 'Stop',
  'guida.un-aiuto': 'Un coup de pouce',
  'guida.piu-piccolo': 'Plus petit, un morceau à la fois :',
  'guida.ci-penso': "Je m'en occupe",
  'guida.fallo-con': 'Fais-le avec {agente}',
  'guida.scegli-cartella': "Choisis d'abord le dossier où travailler.",
  'guida.cartella': 'Choisir le dossier',
  'guida.testo-agente': 'Voici le texte qui arrive à {agente}, dans le dossier « {cartella} ». Tu peux le modifier.',
  'guida.nota-agente': "Une fenêtre du Terminal s'ouvre avec {agente} : il utilise ton abonnement, sans clé. Lis ce qu'il fait avant de dire oui.",
  'guida.agente-aperto': "J'ai ouvert le Terminal avec {agente}.",
  'guida.agente-segue': 'Lode suit le dossier : quand {agente} a fini, je te le dis ici.',
  'guida.agente-errore': "Le Terminal ne s'est pas ouvert : {errore}",
  'guida.agente-finito': '{agente} a fini : vérifie, puis appuie sur Fait.',
  'guida.prompt-agente': "Je fais ceci : {obiettivo}. Maintenant, l'étape est « {passo} » : {cosa} Fais seulement cette étape, explique-moi avec des mots simples ce que tu fais, et arrête-toi à la fin.",
  'guida.fine-titolo': 'Tout est fait !',
  'guida.fine-testo': { one: "{titolo} : {n} étape sur {n}, terminée. Beau travail.", other: '{titolo} : {n} étapes sur {n}, toutes terminées. Beau travail.' },
  'guida.chiusa': 'Guide mis de côté',
  'guida.chiusa-nota': 'Quand tu veux continuer, écris « reprendre le guide ».',
  'guida.ripresa': 'Je reprends là où tu t’étais arrêté.',
  'guida.nessuna': "Tu n'as aucun guide en cours. Essaie d'écrire « je veux faire une présentation ».",
  'guida.proposta-titolo': 'En cours : {titolo}',
  'guida.proposta-testo': 'Tu en es à l\'étape {i} sur {tot}.',
  'guida.proposta-bottone': 'Reprendre',
  'guida.nel-vault': 'La liste des étapes est aussi dans le vault : {nota}.',
  // la note dans le vault (dans la langue du vault)
  'guida.nota-file': 'Pas à pas',
  'guida.nota-intro': 'Le guide de Lode. Lode coche une étape quand tu appuies sur « Fait, suivant » dans la barre.',
  'guida.nota-quando': 'Terminé quand',
  'guida.linguaggio': 'ton langage',

  // les recettes : [titre, quoi, terminé quand, coup de pouce]
  'guida.r-tesi-1': ['Comprends ce qu\'on te demande', 'Relis la consigne ou parle avec ton directeur. Écris en une ligne la question à laquelle ton travail répond. Note la date limite et le nombre de pages demandé.', 'tu as une phrase avec la question et la date de rendu', 'Si tu ne sais pas par où commencer, écris trois questions qui te donnent envie d\'en savoir plus sur le sujet et choisis celle qui a le plus de matière.'],
  'guida.r-tesi-2': ['Rassemble les sources', 'Cherche 5 à 10 sources sérieuses : livres, articles, polycopiés du cours. Garde-les toutes au même endroit, avec l\'auteur et l\'année. Pour chacune, écris deux lignes sur ce qu\'elle t\'apporte.', 'tu as une liste de sources avec deux lignes chacune', 'Pars de la bibliographie d\'un bon article : elle te mène à d\'autres sources déjà choisies par quelqu\'un.'],
  'guida.r-tesi-3': ['Fais le plan', 'Écris les titres des chapitres et, sous chacun, trois ou quatre points. Pas besoin qu\'il soit parfait. Le plan est ta carte : tu le changeras en écrivant.', 'tu as un plan avec les points de chaque chapitre', 'Prends le schéma classique : introduction, ce qu\'on sait déjà, ce que tu as fait, résultats, conclusion.'],
  'guida.r-tesi-4': ['Écris le premier jet', 'Écris un chapitre à la fois, sans corriger. Mieux vaut une page moche qu\'une page vide. Mets les citations tout de suite, pour ne pas les perdre.', 'chaque chapitre a un texte, même moche', 'Fais des séances courtes : « focus 25 » et n\'écris qu\'un paragraphe.'],
  'guida.r-tesi-5': ['Relis et corrige', 'Relis tout à voix haute : les phrases trop longues s\'entendent. Vérifie que chaque chapitre répond à la question de départ. Mets au propre les citations et la bibliographie.', 'tu as tout relu une fois, du début à la fin', 'Imprime ou change de police : sur les mêmes pages, l\'œil saute les erreurs.'],
  'guida.r-tesi-6': ['Rends-le', 'Exporte en PDF et vérifie les pages une par une. Suis les règles du format demandé. Envoie le fichier et garde une copie.', 'le fichier est rendu et tu en as une copie', 'Lis les règles de format du département avant d\'exporter : marges, police, page de titre.'],

  'guida.r-sito-1': ['Décide à quoi sert le site', 'Écris qui va le regarder et ce qu\'il doit y trouver. Fais la liste des pages, par exemple Accueil, À propos, Projets, Contact. Dessine la page principale sur une feuille.', 'tu as la liste des pages et un croquis', 'Regarde trois sites semblables qui te plaisent et note ce qu\'ils ont en commun.'],
  'guida.r-sito-2': ['Prépare le dossier', 'Crée un dossier pour le site et ouvre-le dans l\'éditeur. Dedans, crée index.html et style.css. Écris une page avec juste un titre et ouvre-la dans le navigateur.', 'le navigateur affiche ton titre', 'Dans le fichier index.html, il suffit d\'écrire la balise h1 avec ton nom : enregistre et recharge la page.'],
  'guida.r-sito-3': ['Écris la structure', 'Mets en HTML les parties de la page : en-tête, sections, pied de page. Utilise de vrais titres et paragraphes, pas de style pour l\'instant. Ajoute les autres pages et les liens entre elles.', 'toutes les pages sont là et les liens marchent', 'Une page à la fois : copie index.html, change le texte et relie avec une balise a.'],
  'guida.r-sito-4': ['Donne-lui du style', 'Dans le CSS, choisis une police, deux couleurs et les marges. Fais en sorte que ça se lise bien aussi sur téléphone. Vérifie avec les outils du navigateur.', 'le site se lit bien sur l\'ordinateur et sur le téléphone', 'Pars de quelques règles : font-family, max-width pour le texte, un peu de padding.'],
  'guida.r-sito-5': ['Mets-le en ligne', 'Choisis un service gratuit pour sites statiques, par exemple GitHub Pages ou Netlify. Envoie le dossier et ouvre l\'adresse qu\'on te donne. Montre-le à un ami et demande-lui ce qu\'il ne comprend pas.', 'le site s\'ouvre depuis une adresse publique', 'Avec GitHub Pages : crée un dépôt, envoie les fichiers et active Pages dans les paramètres.'],

  'guida.r-codice-1': ['Comprends le problème', 'Relis la consigne et écris avec des mots ce qui entre et ce qui sort du programme. Prépare deux ou trois exemples avec le bon résultat. Comme ça, tu sauras quand ça marche.', 'tu as deux ou trois exemples d\'entrée et de sortie', 'Fais un tout petit exemple à la main, sur une feuille, étape par étape.'],
  'guida.r-codice-2': ['Prépare l\'environnement', 'Crée un dossier pour le projet et ouvre-le dans l\'éditeur. Vérifie que {linguaggio} fonctionne : écris un programme qui affiche une ligne et lance-le.', 'le programme de test affiche sa ligne', 'Si la commande est introuvable, le programme n\'est pas installé ou n\'est pas dans le PATH : cherche le guide officiel pour ton système.'],
  'guida.r-codice-3': ['Écris la première version', 'Écris en {linguaggio} la version la plus simple qui résout le premier exemple. Pas de cas particuliers pour l\'instant. Lance le programme souvent, après quelques lignes.', 'le premier exemple donne le bon résultat', 'Découpe en petites fonctions : une lit, une calcule, une affiche.'],
  'guida.r-codice-4': ['Teste tous les cas', 'Essaie les autres exemples et les cas limites : vide, un seul élément, grands nombres. Quand quelque chose ne va pas, lis l\'erreur et affiche les valeurs au milieu. Corrige une erreur à la fois.', 'tous les exemples donnent le bon résultat', 'Copie l\'erreur et écris « explique-moi l\'erreur » : je te l\'explique étape par étape.'],
  'guida.r-codice-5': ['Nettoie et rends', 'Donne des noms clairs aux variables et enlève les affichages de test. Ajoute deux lignes qui expliquent comment le lancer. Relis la consigne et vérifie que tu as tout fait.', 'le code est propre et la consigne est respectée', 'Explique le code à voix haute, ligne par ligne : là où tu bloques, il y a quelque chose à arranger.'],

  'guida.r-presentazione-1': ['Décide du message', 'Écris en une phrase ce que ceux qui t\'écoutent doivent retenir. Regarde combien de temps tu as : à peu près une diapo par minute. Choisis trois points, pas plus.', 'tu as la phrase du message et trois points', 'Imagine que tu le racontes à un ami en une minute : ce que tu dis, c\'est le message.'],
  'guida.r-presentazione-2': ['Fais le déroulé', 'Écris un titre pour chaque diapo, dans l\'ordre. D\'abord l\'ouverture, puis les trois points, puis la conclusion. Pas de graphisme pour l\'instant.', 'tu as une liste de titres, un par diapo', 'Prends des post-it ou une liste : déplacer les idées est plus facile avant d\'ouvrir le logiciel.'],
  'guida.r-presentazione-3': ['Remplis les diapos', 'Une idée par diapo, peu de mots, de grandes images. Le texte long, tu le dis, tu ne l\'écris pas. Garde le même style partout.', 'chaque diapo a son contenu', 'Si une diapo a plus de six lignes, coupe-la en deux.'],
  'guida.r-presentazione-4': ['Répète à voix haute', 'Refais toute la présentation avec un chronomètre. Note où tu bloques et où tu es trop long. Coupe ce qui ne sert pas le message.', 'tu l\'as répétée dans le bon temps', 'Enregistre-toi avec le téléphone et réécoute-toi une fois.'],
  'guida.r-presentazione-5': ['Prépare le jour J', 'Exporte aussi en PDF, au cas où le logiciel ne serait pas là. Emporte le fichier sur une clé ou dans le cloud. Prépare une réponse à deux questions probables.', 'tu as le PDF de secours et les deux réponses', 'Arrive quelques minutes avant et teste le projecteur.'],

  'guida.r-video-1': ['Écris ce que tu racontes', 'Décide en une phrase de quoi parle la vidéo et combien de temps elle dure. Écris le déroulé des scènes. Si tu parles, écris le texte et lis-le à voix haute.', 'tu as le déroulé et le texte', 'Une vidéo courte marche mieux : commence par une d\'une minute.'],
  'guida.r-video-2': ['Filme', 'Filme les scènes du déroulé, chacune plusieurs fois. Soigne la lumière et surtout le son : un micro proche compte plus que la caméra. Tiens le téléphone immobile et à l\'horizontale, sauf si c\'est pour les réseaux.', 'toutes les scènes sont filmées', 'Filme dans un endroit calme, avec une fenêtre devant toi et pas derrière.'],
  'guida.r-video-3': ['Monte', 'Importe les fichiers dans le logiciel de montage. Mets les scènes dans l\'ordre et coupe les pauses et les erreurs. Regarde tout une fois sans t\'arrêter.', 'la vidéo se regarde du début à la fin', 'Coupe plus que tu ne penses : une seconde de trop se sent.'],
  'guida.r-video-4': ['Peaufine', 'Règle le volume, ajoute les titres et, si besoin, une musique douce. Utilise une musique libre de droits. Ajoute les sous-titres si quelqu\'un la regardera sans le son.', 'le son, les titres et les sous-titres sont en place', 'Écoute au casque : on entend les sauts de volume.'],
  'guida.r-video-5': ['Exporte et rends', 'Exporte en MP4, 1080p, qui passe presque partout. Regarde le fichier exporté jusqu\'au bout. Mets-le en ligne ou rends-le, et garde le projet.', 'le fichier est rendu et tu l\'as regardé en entier', 'Si le fichier est trop gros, exporte avec un débit plus bas.'],

  'guida.r-dati-1': ['Écris la question', 'Écris en une ligne ce que tu veux découvrir avec les données. Décide quel graphique y répondrait : une évolution, une comparaison, une répartition. Comme ça, tu sais quoi chercher.', 'tu as la question et le type de graphique', 'Complète la phrase : quand une chose change, l\'autre change-t-elle aussi ?'],
  'guida.r-dati-2': ['Prépare les données', 'Ouvre les données dans un tableur. Une ligne par observation, une colonne par variable, avec un nom clair. Enlève les lignes vides et les doublons.', 'le tableau est propre, avec ses en-têtes', 'Travaille sur une copie : garde toujours le fichier d\'origine.'],
  'guida.r-dati-3': ['Regarde les chiffres', 'Calcule pour chaque colonne la moyenne, le minimum et le maximum. Cherche les valeurs bizarres : fautes de frappe ou vrais cas ? Note ce que tu remarques.', 'tu as les chiffres de synthèse et les notes', 'Trie la colonne : les valeurs bizarres se retrouvent en haut ou en bas.'],
  'guida.r-dati-4': ['Fais le graphique', 'Crée le graphique qui répond à la question. Mets le titre, le nom des axes et les unités. Enlève tout ce qui ne sert pas à le lire.', 'le graphique se comprend sans explications', 'Des lignes pour l\'évolution dans le temps, des barres pour comparer, un histogramme pour la répartition.'],
  'guida.r-dati-5': ['Écris ce qu\'il dit', 'Sous le graphique, écris deux ou trois phrases : ce qu\'on voit et ce que ça veut dire. Dis aussi ce que les données ne peuvent pas dire. Enregistre le graphique comme image.', 'tu as le graphique enregistré et les phrases', 'Sépare ce que tu vois de ton explication : d\'abord les faits, puis l\'idée.'],

  'guida.r-esame-1': ['Mets le programme en ordre', 'Prends le programme du cours et colle-le dans Lode avec « programme ». Tu auras la carte des thèmes. Marque ceux que tu connais déjà.', 'le programme est dans Lode', 'Si tu ne trouves pas le programme, regarde la page du cours ou demande à tes camarades.'],
  'guida.r-esame-2': ['Fais un plan', 'Compte les jours qu\'il reste et répartis les thèmes. Garde les derniers jours pour réviser. Mets le plan dans le calendrier.', 'chaque thème a son jour', 'Écris « planning de la semaine » et Lode te montre tes vraies heures libres.'],
  'guida.r-esame-3': ['Étudie un thème par jour', 'Fais des séances courtes avec le minuteur, par exemple « focus 50 ». À la fin de chaque thème, fais des cartes avec ce qu\'il faut retenir. Révise-les chaque jour avec « révise ».', 'tu as étudié tous les thèmes au moins une fois', 'Explique le thème à voix haute comme si tu étais le prof : là où tu bloques, relis.'],
  'guida.r-esame-4': ['Mets-toi à l\'épreuve', 'Fais le « quiz » ou fais-toi poser des questions avec « interroge-moi ». Note les questions ratées et réétudie-les. Recommence jusqu\'à les savoir.', 'tu réponds bien à la plupart des questions', 'Commence par les thèmes que tu connais le moins : c\'est là qu\'on gagne le plus.'],
  'guida.r-esame-5': ['Fais un vrai essai', 'Deux ou trois jours avant, fais l\'« examen blanc » avec un ancien sujet et le vrai temps. Corrige et révise tes erreurs. La veille, dors.', 'tu as fait un sujet entier dans le temps', 'Si tu n\'as pas d\'anciens sujets, demande-les à tes camarades ou sur le groupe du cours.'],

  'guida.r-generico-1': ['Écris le résultat', 'Écris en une phrase à quoi ressemblera la chose terminée. Plus c\'est concret, mieux c\'est. Note aussi pour quand tu en as besoin.', 'tu as la phrase du résultat et la date', 'Imagine que tu la montres à quelqu\'un : que voit-il ?'],
  'guida.r-generico-2': ['Cherche ce qu\'il te faut', 'Fais la liste de ce qu\'il te faut : logiciels, matériel, personnes à contacter. Regarde comment quelqu\'un d\'autre l\'a fait, par exemple dans une vidéo ou un guide.', 'tu as la liste de ce qu\'il te faut', 'Cherche le nom de la chose avec « tutoriel » ou « guide pour débutants ».'],
  'guida.r-generico-3': ['Fais un tout petit premier pas', 'Choisis la plus petite chose que tu peux faire maintenant, en 20 minutes. Fais-la tout de suite, même si elle n\'est pas parfaite. Le reste devient plus facile.', 'tu as fait le premier morceau', 'Si 20 minutes, c\'est beaucoup, fais-en 5 : l\'important, c\'est de commencer.'],
  'guida.r-generico-4': ['Avance et vérifie', 'Découpe le reste en morceaux d\'une séance et fais-les un par un. Après chaque morceau, compare avec le résultat que tu as écrit. Demande un avis avant la fin.', 'le résultat est comme tu l\'avais écrit', 'Si tu bloques, reviens au morceau d\'avant et rends-le plus petit.'],
};
