// Tes notes avec les systèmes autres que l'italien (français) : «combien il me faut», «et si j'ai», crédits, note finale,
// le relevé collé (js/libretto.js, js/lode.js, js/pagina.js, js/benvenuto.js).
export default {
  'libretto.crediti-di': '{fatti} sur {tot} {crediti}',
  'libretto.serve-gia': 'Pour arriver à <b>{obiettivo}</b>, il te suffit de valider ce qui reste.',
  'libretto.serve-media': 'Pour arriver à <b>{obiettivo}</b>, il te faut <b>{voto}</b> de moyenne sur les {cfu} {crediti} qui restent.',
  'libretto.serve-impossibile': '<b>{obiettivo}</b>, ce n\'est plus possible : vise {punta}.',
  'libretto.obiettivo-fuori': 'Avec le système {sistema}, l\'objectif va de {da} à {a}.',
  'libretto.simula-esito': 'Moyenne <b>{media}</b> <span class="{classe}">{delta}</span> · {finale} <b>{valore}</b>',
  'libretto.voto-altro-sistema': "{voto} ({sistema}) : ne compte pas dans ce système",
  'libretto.totali-opzione': '{n} {crediti}',
  'libretto.simula': 'Avec **{voto}** en {nome}, ta moyenne passe de {prima} à **{dopo}** ({delta}) : {finale} **{valore}**.',
  'libretto.simula-primo': 'Avec {voto} en **{nome}**, ta moyenne partirait de **{media}** : {finale} **{valore}**.',
  'libretto.sintesi-media-finale': 'moyenne {media}, {finale} {valore}',
  'libretto.non-valido': 'Avec le système {sistema}, la note {voto} n\'existe pas.',
  'libretto.non-superato': '{voto} en {nome}, ce n\'est pas validé (il faut {sufficienza}) : je ne le note pas.',
  'libretto.nuovo-esame': 'Nouvelle matière à {n} {crediti} : corrige-les dans tes notes.',
  'libretto.formula': 'moyenne pondérée par les {crediti}',
  'libretto.piede-esami': { one: '{n} matière · {cfu} {crediti}', other: '{n} matières · {cfu} {crediti}' },
  'libretto.piede-media': 'moyenne <b>{media}</b> · {finale} <b>{valore}</b>',
  'libretto.campo-voto-nota': 'comme sur ton relevé ({esempio}) ; vide si tu ne l\'as pas encore passé',
  'libretto.voto-non-letto': 'Je n\'arrive pas à lire la note «{voto}» : écris-la comme sur ton relevé, par exemple {esempio}.',
  'libretto.incolla-sotto': 'Ouvre ton relevé de notes sur l\'ENT de ta fac, sélectionne tout, copie et colle ici : une ligne par matière, avec le nom, les crédits et la note. Ou écris-les toi-même, par exemple «{esempio}».',
  'libretto.alla-laurea': '{n} {crediti} avant le diplôme',
  'libretto.campo-crediti': 'Crédits ({crediti})',
  'libretto.libretto-vuoto': 'Aucune matière pour l\'instant. Écris dans la barre <kbd>j\'ai eu {voto} en physique</kbd>.',
  'libretto.riga-esempio': '{nome}, {n} {crediti}, {voto}',
  'libretto.esame-esempio': 'Analyse 1',
};
