// Les questions de « Qu'est-ce que ça affiche ? » (js/codice/modelli.js), en français.
// Clés : modelli.<modèle>.cosa / .concetto / .frase-N (les phrases des mutants, dans l'ordre), modelli.<modèle>.<langage>.… pour
// ce qui change en Python et en Java ; modelli.concetti.* et modelli.errori.* sont les noms des notions et des erreurs.
export default {
  'modelli.hai-scelto': 'Tu as choisi `{s}`',
  'modelli.niente': '(rien)',
  'modelli.concetti.for': 'Boucle for',
  'modelli.concetti.while': 'Boucle while',
  'modelli.concetti.do-while': 'Boucle do-while',
  'modelli.concetti.ritroso': 'Compte à rebours',
  'modelli.concetti.array': 'Tableaux',
  'modelli.concetti.divisione-intera': 'Division entière',
  'modelli.concetti.resto': 'Reste avec les négatifs',
  'modelli.concetti.cast': 'Cast en double',
  'modelli.concetti.incremento': 'i++ et ++i',
  'modelli.concetti.assegnamento': 'Affectations composées (+=)',
  'modelli.concetti.switch': 'switch et break',
  'modelli.concetti.cortocircuito': '&& et || en court-circuit',
  'modelli.concetti.else-pendente': 'else ambigu (dangling else)',
  'modelli.concetti.puntatori': 'Passage par adresse',
  'modelli.concetti.parametri': 'Passage par valeur',
  'modelli.concetti.visibilita': 'Variables dans les blocs',
  'modelli.concetti.char': 'char et codes ASCII',
  'modelli.concetti.ricorsione': 'Récursivité',
  'modelli.concetti.annidati': 'Boucles imbriquées',
  'modelli.concetti.break-continue': 'break et continue',
  'modelli.concetti.ternario': 'Opérateur ternaire',
  'modelli.errori.fuori-di-uno': 'décalage de un',
  'modelli.errori.divisione-intera': 'division entière',
  'modelli.errori.post-vs-pre': 'i++ et ++i',
  'modelli.errori.break-dimenticato': 'break oublié',
  'modelli.errori.copia-del-parametro': 'copie du paramètre',
  'modelli.errori.cortocircuito': 'court-circuit',
  'modelli.errori.resto-col-segno': 'reste avec le signe',
  'modelli.errori.piu-uguale': '+= et =',
  'modelli.errori.maggiore-o-uguale': '> et >=',
  'modelli.errori.indice-valore': 'indice et valeur',
  'modelli.errori.sovrascrittura': 'premier et dernier',
  'modelli.errori.else-pendente': 'else ambigu',
  'modelli.errori.variabile-nascosta': 'variable masquée',
  'modelli.errori.carattere-codice': 'caractère et code',
  'modelli.errori.caso-base': 'cas de base',
  'modelli.errori.passo-del-ciclo': 'quand le pas de la boucle s\'applique',
  'modelli.errori.ricorsione': 'récursivité',
  'modelli.errori.cicli-annidati': 'boucles imbriquées',
  'modelli.errori.break-continue': 'break et continue',
  'modelli.errori.do-while': 'do-while',
  'modelli.errori.ternario': 'ternaire à l\'envers',
  'modelli.errori.scambi-in-fila': 'échanges à la suite',
  'modelli.for-minore.cosa': 'ce for',
  'modelli.for-minore.concetto': 'Avec `i < n`, le dernier tour a i = n - 1 : la valeur n n\'est jamais affichée.',
  'modelli.for-minore.frase': `{hai} : c'est ce que ça afficherait avec \`i <= {b}\`. Ici la boucle s'arrête avant.`,
  'modelli.for-minore.frase-2': `{hai} : c'est comme si \`i++\` s'appliquait avant le premier tour. L'incrément arrive à la fin de chaque tour : le premier tour a i = {a}.`,
  'modelli.for-minore.frase-3': `{hai} : tu t'es arrêté un tour trop tôt. Avec \`i < {b}\`, le dernier tour a i = {b2}.`,
  'modelli.for-passo.cosa': 'ce for',
  'modelli.for-passo.concetto': 'Avec `<=`, la boucle fait aussi le tour où i est égal à la limite.',
  'modelli.for-passo.frase': `{hai} : c'est ce que ça afficherait avec \`i < {b}\`. Avec \`<=\`, {b} est affiché aussi.`,
  'modelli.for-passo.frase-2': `{hai} : \`i += {s}\` ne s'applique pas avant le premier tour. Le premier tour a i = {a}.`,
  'modelli.for-indietro.cosa': 'ce compte à rebours',
  'modelli.for-indietro.concetto': 'La boucle tourne tant que la condition est vraie : avec `i > L`, la valeur L n\'est pas affichée.',
  'modelli.for-indietro.frase': `{hai} : c'est ce que ça afficherait avec \`i >= {l}\`. Avec \`i > {l}\`, le dernier tour a i = {l2}.`,
  'modelli.for-indietro.frase-2': `{hai} : \`i--\` arrive à la fin du tour, pas avant. Le premier tour affiche {n}.`,
  'modelli.for-indietro.frase-3': `{hai} : tu t'es arrêté un tour trop tôt. i = {l} respecte aussi \`i > {l2}\`.`,
  'modelli.while-somma.cosa': 'ce while',
  'modelli.while-somma.concetto': 'Le while sort quand la condition devient fausse : après `while (i < n)`, la variable i vaut n.',
  'modelli.while-somma.frase': `{hai} : c'est ce que ça afficherait avec \`i <= {n}\`. Ici la boucle fait un tour de moins.`,
  'modelli.while-somma.frase-2': `{hai} : c'est comme si \`i++\` venait avant \`s += i\`. Ici s ajoute i, et seulement après i augmente.`,
  'modelli.while-somma.frase-3': `{hai} : après la boucle, i ne vaut pas {n}. Le while sort justement quand i devient {n2}.`,
  'modelli.while-dimezza.cosa': 'ce while',
  'modelli.while-dimezza.concetto': 'Entre deux int, `/` tronque : 7 / 2 donne 3, et en divisant par deux on arrive à 1 sans virgule.',
  'modelli.while-dimezza.frase': `{hai} : c'est ce qui se passerait si n était un double. n est un int : \`n /= 2\` jette la partie après la virgule.`,
  'modelli.while-dimezza.frase-2': `{hai} : c'est ce que ça afficherait avec \`n >= 1\`. La boucle s'arrête dès que n arrive à 1.`,
  'modelli.while-post.cosa': 'ce while avec i++',
  'modelli.while-post.concetto': '`i++ < n` compare l\'ancienne valeur puis incrémente : dans la boucle, i a déjà augmenté.',
  'modelli.while-post.frase': `{hai} : c'est ce que ça afficherait avec \`++i\`. Avec \`i++\`, la comparaison utilise la valeur d'avant.`,
  'modelli.while-post.frase-2': `{hai} : quand printf s'exécute, i a déjà été incrémenté par la comparaison.`,
  'modelli.while-post.frase-3': `{hai} : la dernière comparaison aussi, celle qui est fausse, incrémente i. À la fin, i vaut {n}.`,
  'modelli.array-somma.cosa': 'cette somme',
  'modelli.array-somma.concetto': 'Les indices d\'un tableau de n éléments vont de 0 à n - 1.',
  'modelli.array-somma.frase': `{hai} : tu as sauté \`v[0]\`. Le premier élément a l'indice 0.`,
  'modelli.array-somma.frase-2': `{hai} : tu as oublié le dernier. Avec \`i < {k}\`, le dernier tour lit \`v[{k2}]\`.`,
  'modelli.array-somma.frase-3': `{hai} : c'est le dernier élément, comme s'il y avait \`s = v[i]\`. \`+=\` ajoute, il ne remplace pas.`,
  'modelli.array-massimo.cosa': 'ce maximum',
  'modelli.array-massimo.concetto': 'p est un indice : il compte à partir de 0. Avec `>`, c\'est la première position du maximum qui reste.',
  'modelli.array-massimo.frase': `{hai} : tu as compté les positions à partir de 1. En {linguaggio}, le premier élément a l'indice 0.`,
  'modelli.array-massimo.frase-2': `{hai} : c'est ce que ferait \`>=\`. Avec \`>\`, un maximum égal ne déplace pas p : le premier reste.`,
  'modelli.array-massimo.frase-3': `{hai} : tu as oublié le dernier élément. Lui aussi est comparé.`,
  'modelli.array-ultimo.cosa': 'cette recherche',
  'modelli.array-ultimo.concetto': 'La boucle ne s\'arrête pas quand elle trouve x : p est écrasé et c\'est la dernière position qui reste.',
  'modelli.array-ultimo.frase': `{hai} : c'est la première position. La boucle ne s'arrête pas : chaque fois qu'elle trouve x, elle réécrit p.`,
  'modelli.array-ultimo.frase-2': `{hai} : tu as compté les positions à partir de 1. En {linguaggio}, le premier élément a l'indice 0.`,
  'modelli.array-ultimo.frase-3': `{hai} : c'est la valeur cherchée, pas sa position. p est un indice.`,
  'modelli.media-array.cosa': 'cette moyenne',
  'modelli.media-array.concetto': '`s / n` entre int tronque. `(double)s / n` convertit d\'abord et divise avec la virgule.',
  'modelli.media-array.frase': `{hai} : \`s / {k}\` est une division entre deux int : la partie après la virgule est perdue.`,
  'modelli.media-array.frase-2': `{hai} : le cast \`(double)s\` a lieu avant la division, donc la division garde la virgule.`,
  'modelli.media-array.frase-3': `{hai} : la division entre int n'arrondit pas, elle tronque.`,
  'modelli.divisione-double.cosa': 'cette division',
  'modelli.divisione-double.concetto': 'Le type du résultat ne compte pas : `a / b` entre int tronque même si ça finit dans un double.',
  'modelli.divisione-double.frase': `{hai} : \`a / b\` est calculé entre int, avant d'arriver dans m. Le double reçoit un nombre déjà tronqué.`,
  'modelli.divisione-double.frase-2': `{hai} : la division entre int n'arrondit pas, elle tronque vers zéro.`,
  'modelli.cast-prima-dopo.cosa': 'ces deux casts',
  'modelli.cast-prima-dopo.concetto': '`(double)(s / n)` divise entre int puis convertit. `(double)s / n` convertit puis divise.',
  'modelli.cast-prima-dopo.frase': `{hai} : dans \`(double)(s / n)\`, les parenthèses font diviser d'abord, entre int. Le cast arrive après.`,
  'modelli.cast-prima-dopo.frase-2': `{hai} : dans \`(double)s / n\`, le cast ne porte que sur s, et la division garde la virgule.`,
  'modelli.cast-prima-dopo.frase-3': `{hai} : tu les as inversés. Les parenthèses décident si le cast arrive avant ou après la division.`,
  'modelli.diviso-due.cosa': 'cette division par 2',
  'modelli.diviso-due.concetto': 'Un seul double dans le calcul suffit : `a / 2.0` garde la virgule, `a / 2` non.',
  'modelli.diviso-due.frase': `{hai} : \`a / 2\` est entre deux int : ça tronque et donne un int, que %d affiche sans virgule.`,
  'modelli.diviso-due.frase-2': `{hai} : \`2.0\` est un double, donc \`a / 2.0\` garde la virgule.`,
  'modelli.diviso-due.frase-3': `{hai} : \`a / 2\` n'arrondit pas : ça tronque vers zéro.`,
  'modelli.resto-negativi.cosa': 'ce reste',
  'modelli.resto-negativi.concetto': `En {linguaggio}, la division tronque vers zéro et le reste a le signe du dividende : -7 % 3 donne -1.`,
  'modelli.resto-negativi.frase': `{hai} : c'est ce que fait Python, qui arrondit vers le bas. En {linguaggio}, on tronque vers zéro.`,
  'modelli.resto-negativi.frase-2': `{hai} : en {linguaggio}, le reste n'est pas toujours positif. Il a le signe du dividende, c'est-à-dire de a.`,
  'modelli.resto-negativi.frase-3': `{hai} : la division entre int tronque vers zéro, pas vers le bas.`,
  'modelli.post-pre.cosa': 'ces incréments',
  'modelli.post-pre.concetto': '`x = i--` utilise la valeur d\'avant puis décrémente ; `y = --i` décrémente puis utilise la nouvelle valeur.',
  'modelli.post-pre.concetto-2': '`x = i++` utilise la valeur d\'avant puis incrémente ; `y = ++i` incrémente puis utilise la nouvelle valeur.',
  'modelli.post-pre.frase': `{hai} : avec \`x = i{op}\`, x prend la valeur d'avant, puis i change.`,
  'modelli.post-pre.frase-2': `{hai} : avec \`y = {op}i\`, i change d'abord, puis y prend la nouvelle valeur.`,
  'modelli.post-pre.frase-3': `{hai} : tu les as inversés. L'opérateur après (\`i{op}\`) utilise la valeur d'avant, celui avant (\`{op}i\`) la nouvelle valeur.`,
  'modelli.piu-uguale.cosa': 'ce +=',
  'modelli.piu-uguale.concetto': '`s += x` veut dire `s = s + x` : ça ajoute à la valeur qui était là.',
  'modelli.piu-uguale.frase': `{hai} : c'est seulement le dernier tour, comme s'il y avait \`=\`. \`+=\` ajoute à chaque fois.`,
  'modelli.piu-uguale.frase-2': `{hai} : avec \`<=\`, i = {n} fait aussi son tour.`,
  'modelli.piu-uguale.frase-3': `{hai} : tu as oublié la valeur de départ. s part de {a}.`,
  'modelli.switch.cosa': 'ce switch',
  'modelli.switch.concetto': 'Sans break, l\'exécution tombe dans le case du dessous et continue jusqu\'au premier break ou jusqu\'à la fin.',
  'modelli.switch.frase': `{hai} : c'est comme si chaque case avait son break. Sans break, on continue dans le case du dessous.`,
  'modelli.switch.frase-2': `{hai} : tu as sauté le break. Là, le switch s'arrête.`,
  'modelli.switch.frase-3': `{hai} : default ne s'exécute pas toujours. Il s'exécute si aucun case ne correspond, ou si on y arrive en tombant d'un case sans break.`,
  'modelli.cortocircuito.cosa': 'ce if avec || et &&',
  'modelli.cortocircuito.concetto': 'Si le premier morceau suffit pour décider (vrai avec ||, faux avec &&), le deuxième n\'est pas exécuté.',
  'modelli.cortocircuito.frase': `{hai} : \`++n\` n'est pas exécuté. Avec \`{op}\`, le premier morceau suffit déjà pour décider, et n reste à 0.`,
  'modelli.cortocircuito.frase-3': '|| veut au moins un morceau vrai',
  'modelli.cortocircuito.frase-4': '&& veut les deux morceaux vrais',
  'modelli.cortocircuito.frase-2': `{hai} : tu as lu \`{op}\`. {op2}.`,
  'modelli.else-pendente.cosa': 'ce else',
  'modelli.else-pendente.concetto': 'Le else va avec le if le plus proche qui n\'a pas déjà de else, quelle que soit l\'indentation.',
  'modelli.else-pendente.frase': `{hai} : tu as suivi l'indentation. Mais le else va avec le if le plus proche, \`if (i > {p})\`.`,
  'modelli.else-pendente.frase-2': `{hai} : avec \`i < {n}\`, le dernier tour a i = {n2}.`,
  'modelli.swap-valore.cosa': 'cet échange',
  'modelli.swap-valore.concetto': 'Une fonction reçoit des copies des valeurs : échanger a et b ne touche pas x et y.',
  'modelli.swap-valore.frase': `{hai} : a et b sont des copies de x et y. L'échange reste dans la fonction.`,
  'modelli.swap-valore.frase-2': `{hai} : dans la fonction, l'échange a vraiment lieu. Ce sont les copies qui s'échangent, pas x et y.`,
  'modelli.swap-indirizzo.cosa': 'ces échanges avec les pointeurs',
  'modelli.swap-indirizzo.concetto': 'Avec `&x`, la fonction reçoit l\'adresse : `*a = …` modifie x lui-même. Les échanges ont lieu l\'un après l\'autre.',
  'modelli.swap-indirizzo.frase': `{hai} : ici ce ne sont pas des copies. \`&x\` passe l'adresse, et \`*a\` écrit directement dans x.`,
  'modelli.swap-indirizzo.frase-2': `{hai} : les échanges se font dans l'ordre. D'abord x avec y, puis le nouveau y avec z.`,
  'modelli.swap-indirizzo.frase-3': `{hai} : le deuxième échange voit le y déjà modifié par le premier.`,
  'modelli.valore-e-indirizzo.cosa': 'cette fonction',
  'modelli.valore-e-indirizzo.concetto': 'a est une copie de x ; b est l\'adresse de y : seul `*b = …` modifie la variable de main.',
  'modelli.valore-e-indirizzo.frase': `{hai} : a est une copie de x. Modifier a ne modifie pas x.`,
  'modelli.valore-e-indirizzo.frase-2': `{hai} : b n'est pas une copie, c'est l'adresse de y. \`*b = …\` modifie y.`,
  'modelli.array-in-funzione.cosa': 'ce tableau passé à une fonction',
  'modelli.array-in-funzione.concetto': 'Un tableau est passé par adresse : la fonction modifie a lui-même. Un int, lui, est passé en copie.',
  'modelli.array-in-funzione.frase': `{hai} : un tableau n'est pas copié. La fonction travaille sur les mêmes éléments que a.`,
  'modelli.array-in-funzione.frase-2': `{hai} : n, lui, est une copie. Le \`n--\` de la fonction ne touche pas le n de main.`,
  'modelli.blocco-ombra.cosa': 'ces deux x',
  'modelli.blocco-ombra.concetto': 'Le x déclaré dans le bloc est une autre variable : il masque celui de dehors et disparaît à la }.',
  'modelli.blocco-ombra.frase': `{hai} : \`int x = {b}\` entre les accolades crée un nouveau x. Dehors, x vaut toujours {a}.`,
  'modelli.blocco-ombra.frase-2': `{hai} : dans le bloc, le x le plus proche est celui de l'intérieur. C'est lui que y utilise.`,
  'modelli.char-ascii.cosa': 'ces char',
  'modelli.char-ascii.concetto': 'Un char est un nombre : \'a\' vaut 97. %c affiche la lettre, %d le code. Majuscule = minuscule - 32.',
  'modelli.char-ascii.frase': `{hai} : %d ne donne pas la position dans l'alphabet. Il donne le code ASCII : 'a' vaut 97.`,
  'modelli.char-ascii.frase-2': `{hai} : %d affiche le nombre du caractère, pas la lettre.`,
  'modelli.char-ascii.frase-3': `{hai} : d est un char et %c l'affiche comme une lettre, la majuscule.`,
  'modelli.fattoriale.cosa': 'cette récursion',
  'modelli.fattoriale.concetto': 'fatt(n) = n · fatt(n - 1), et le cas de base arrête la descente à 1.',
  'modelli.fattoriale.frase': `{hai} : c'est fatt({n}). Tu as fait une étape de moins : on multiplie de {n2} jusqu'à 1.`,
  'modelli.fattoriale.frase-2': `{hai} : c'est fatt({n}). Tu as fait une étape de plus : on part de {n2}.`,
  'modelli.fattoriale.frase-3': `{hai} : tu t'es arrêté au premier appel. fatt(n - 1) continue de s'appeler jusqu'au cas de base.`,
  'modelli.somma-cifre.cosa': 'cette récursion',
  'modelli.somma-cifre.concetto': 'n % 10 est le dernier chiffre, n / 10 enlève le dernier chiffre. Le cas de base renvoie le chiffre qui reste.',
  'modelli.somma-cifre.frase': `{hai} : tu as perdu le premier chiffre. Le cas de base renvoie n, pas 0.`,
  'modelli.somma-cifre.frase-2': `{hai} : c'est le nombre de chiffres. Ici chaque appel ajoute \`n % 10\`, le chiffre, pas 1.`,
  'modelli.somma-cifre.frase-3': `{hai} : c'est seulement le dernier chiffre. La valeur de retour s'ajoute à celle de l'appel suivant.`,
  'modelli.ricorsione-ordine.cosa': 'cette récursion',
  'modelli.ricorsione-ordine.concetto': 'printf vient après l\'appel : on affiche au retour, donc du plus petit au plus grand.',
  'modelli.ricorsione-ordine.frase': `{hai} : ce serait le cas avec printf avant l'appel. Ici on affiche au retour.`,
  'modelli.ricorsione-ordine.frase-2': `{hai} : avec n = 0, la fonction sort tout de suite, sans rien afficher.`,
  'modelli.annidati-conta.cosa': 'ces boucles imbriquées',
  'modelli.annidati-conta.concetto': 'La boucle intérieure repart à chaque tour de la boucle extérieure : ici elle tourne i fois, donc 0, 1, 2, …',
  'modelli.annidati-conta.frase': `{hai} : c'est ce que donnerait \`j <= i\`. Avec \`j < i\`, le premier tour (i = 0) ne compte rien.`,
  'modelli.annidati-conta.frase-2': `{hai} : la boucle intérieure ne tourne pas toujours {n} fois : elle tourne i fois.`,
  'modelli.annidati-stelle.cosa': 'ces étoiles',
  'modelli.annidati-stelle.concetto': 'Pour chaque ligne i, la boucle intérieure affiche i symboles, puis `\\n` passe à la ligne.',
  'modelli.annidati-stelle.frase': `{hai} : un symbole de trop par ligne. j part de 0 et avec \`j < i\` fait i tours.`,
  'modelli.annidati-stelle.frase-2': `{hai} : la boucle intérieure dépend de i : elle n'affiche pas toujours {n} symboles.`,
  'modelli.annidati-stelle.frase-3': `{hai} : il manque la dernière ligne. Avec \`i <= {n}\`, la ligne {n} est affichée aussi.`,
  'modelli.break-continue.cosa': 'ce break et ce continue',
  'modelli.break-continue.concetto': `\`continue\` passe au tour suivant ; \`break\` sort de la boucle, et le {l} de ce tour n'arrive pas.`,
  'modelli.break-continue.frase': `{hai} : \`continue\` ne sort pas de la boucle : il saute seulement le tour avec i = {a}.`,
  'modelli.break-continue.frase-2': `{hai} : \`break\` ne saute pas un tour : il sort de la boucle quand i vaut {b}.`,
  'modelli.break-continue.frase-3': `{hai} : le break arrive avant le {l} : {b} n'est pas affiché.`,
  'modelli.do-while.cosa': 'ce do-while',
  'modelli.do-while.concetto': 'Le do-while vérifie la condition à la fin de chaque tour : le corps s\'exécute toujours au moins une fois.',
  'modelli.do-while.frase': `{hai} : c'est ce que ferait un while. Le do-while exécute le corps avant de vérifier.`,
  'modelli.do-while.frase-3': 'Le do-while n\'ajoute pas de tour : il vérifie la condition à la fin de chaque tour.',
  'modelli.do-while.frase-4': 'Après le premier tour, la condition est déjà fausse.',
  'modelli.do-while.frase-2': `{hai} : un tour de trop. {vero}`,
  'modelli.do-while.frase-5': `{hai} : c'est ce que donnerait \`i {op}= {b}\`. Avec \`i {op} {b}\`, quand i arrive à {b}, la boucle s'arrête.`,
  'modelli.do-while.frase-6': `{hai} : tu as affiché i tel qu'il était avant le dernier tour. Le dernier tour modifie i aussi : la vérification vient après.`,
  'modelli.ternario.cosa': 'ces ternaires',
  'modelli.ternario.concetto': '`c ? x : y` vaut x si c est vraie, y si elle est fausse.',
  'modelli.ternario.frase-m-vera': `{hai} : pour m, tu as pris la mauvaise branche. \`a > b\` est vraie, donc c'est ce qui suit \`?\`.`,
  'modelli.ternario.frase-m-falsa': `{hai} : pour m, tu as pris la mauvaise branche. \`a > b\` est fausse, donc c'est ce qui suit \`:\`.`,
  'modelli.ternario.frase-d-vera': `{hai} : pour d, tu as pris la mauvaise branche. \`a < b\` est vraie, donc c'est ce qui suit \`?\`.`,
  'modelli.ternario.frase-d-falsa': `{hai} : pour d, tu as pris la mauvaise branche. \`a < b\` est fausse, donc c'est ce qui suit \`:\`.`,
  'modelli.ternario.frase-7': `{hai} : tu as lu les deux ternaires à l'envers. Vrai → la valeur après \`?\`.`,
  'modelli.for-minore.python.concetto': `\`{b}\` s'arrête avant {b2} : le dernier tour a i = {b3}.`,
  'modelli.for-minore.python.frase': `{hai} : c'est ce qu'afficherait \`{b}\`. range s'arrête avant le deuxième nombre.`,
  'modelli.for-minore.python.frase-2': `{hai} : tu as sauté le premier tour. range part bien de {a}.`,
  'modelli.for-minore.python.frase-3': `{hai} : tu t'es arrêté un tour trop tôt. \`{b}\` va jusqu'à {b2}.`,
  'modelli.for-passo.python.concetto': `\`{s}\` avance de {s2} en {s2} et s'arrête avant {b} : {b2} est affiché aussi.`,
  'modelli.for-passo.python.frase': `{hai} : c'est ce qu'afficherait \`{s}\`. Ici le deuxième nombre est {b}, donc {b2} est affiché aussi.`,
  'modelli.for-passo.python.frase-2': `{hai} : range part de {a}, pas de {s}. Le pas s'ajoute après le premier tour.`,
  'modelli.for-indietro.python.concetto': `\`range({n}, {l}, -1)\` compte à rebours et s'arrête avant {l} : {l} n'est pas affiché.`,
  'modelli.for-indietro.python.frase': `{hai} : tu as aussi affiché {l}. range s'arrête avant : le dernier tour a i = {l2}.`,
  'modelli.for-indietro.python.frase-2': `{hai} : range part bien de {n} : le premier tour affiche {n}.`,
  'modelli.for-indietro.python.frase-3': `{hai} : tu t'es arrêté un tour trop tôt. {l} est affiché aussi.`,
  'modelli.while-somma.python.concetto': 'Le while sort quand la condition devient fausse : après `while i < n`, la variable i vaut n.',
  'modelli.while-somma.python.frase': `{hai} : c'est comme si \`i += 1\` venait avant \`s += i\`. Ici s ajoute i, et seulement après i augmente.`,
  'modelli.while-dimezza.python.concetto': '`//` est la division entière : 7 // 2 donne 3, et en divisant par deux on arrive à 1 sans virgule.',
  'modelli.while-dimezza.python.frase': `{hai} : tu as gardé la virgule, comme le ferait \`n /= 2\`. \`n //= 2\` est la division entière : elle jette la partie après la virgule.`,
  'modelli.array-somma.python.frase': `{hai} : tu as oublié le dernier. \`range({k})\` va jusqu'à {k2} : le dernier tour lit \`v[{k2}]\`.`,
  'modelli.media-array.python.concetto': '`s // n` est la division entière ; en Python, `/` garde toujours la virgule, même entre deux int.',
  'modelli.media-array.python.frase': `{hai} : \`s // {k}\` est la division entière : la partie après la virgule est perdue.`,
  'modelli.media-array.python.frase-2': `{hai} : en Python, \`/\` garde la virgule, il ne tronque pas comme \`//\`.`,
  'modelli.media-array.python.frase-3': `{hai} : \`//\` n'arrondit pas : il va vers le bas.`,
  'modelli.media-array.java.frase': `{hai} : \`s / {k}\` est entre deux int : en Java (comme en C, pas comme en Python), la division reste entière et la partie après la virgule est perdue.`,
  'modelli.divisione-double.java.frase': `{hai} : \`a / b\` est calculé entre int, avant d'arriver dans m. En Java, comme en C, la division entre deux int tronque : le double reçoit un nombre déjà tronqué.`,
  'modelli.diviso-due.python.concetto': 'En Python, `//` est la division entière et `/` garde toujours la virgule, même entre deux int.',
  'modelli.diviso-due.python.frase': `{hai} : \`a // 2\` est la division entière : ça donne un int, sans virgule.`,
  'modelli.diviso-due.python.frase-2': `{hai} : en Python, \`/\` ne tronque pas comme en C ou en Java : \`a / 2\` aussi garde la virgule.`,
  'modelli.diviso-due.python.frase-3': `{hai} : \`a // 2\` n'arrondit pas : ça va vers le bas.`,
  'modelli.resto-negativi.python.concetto': 'En Python, `//` va vers le bas et le reste a le signe du diviseur : -7 // 3 donne -3 et -7 % 3 donne 2.',
  'modelli.resto-negativi.python.frase': `{hai} : c'est ce que font le C et Java, qui tronquent vers zéro. En Python, \`//\` va vers le bas.`,
  'modelli.resto-negativi.python.frase-2': `{hai} : en Python, le reste a le signe du diviseur, c'est-à-dire de b, pas du dividende.`,
  'modelli.resto-negativi.python.frase-3': `{hai} : \`//\` arrondit vers le bas, pas vers zéro.`,
  'modelli.piu-uguale.python.frase': `{hai} : \`range(1, {n})\` va jusqu'à {n2} : i = {n2} fait aussi son tour.`,
  'modelli.swap-valore.python.concetto': 'La fonction reçoit les valeurs : réaffecter a et b dans la fonction ne touche pas x et y.',
  'modelli.swap-valore.python.frase': `{hai} : a et b sont des noms de la fonction. Les réaffecter ne change pas x et y.`,
  'modelli.swap-valore.python.frase-2': `{hai} : dans la fonction, l'échange a vraiment lieu. Ce sont a et b qui s'échangent, pas x et y.`,
  'modelli.array-in-funzione.python.concetto': 'La liste est passée telle quelle à la fonction : `v[n] *= …` modifie a lui-même. n, en revanche, est un nom de la fonction : `n -= 1` ne touche pas le n de dehors.',
  'modelli.array-in-funzione.python.frase': `{hai} : une liste n'est pas copiée. La fonction travaille sur les mêmes éléments que a.`,
  'modelli.array-in-funzione.python.frase-2': `{hai} : n, lui, non. Le \`n -= 1\` de la fonction ne touche pas le n de dehors.`,
  'modelli.array-in-funzione.java.concetto': 'Un tableau est passé par référence : la fonction modifie a lui-même. Un int, lui, est passé en copie.',
  'modelli.somma-cifre.python.concetto': '`n % 10` est le dernier chiffre, `n // 10` enlève le dernier chiffre. Le cas de base renvoie le chiffre qui reste.',
  'modelli.ricorsione-ordine.python.concetto': 'print vient après l\'appel : on affiche au retour, donc du plus petit au plus grand.',
  'modelli.ricorsione-ordine.python.frase': `{hai} : ce serait le cas avec print avant l'appel. Ici on affiche au retour.`,
  'modelli.annidati-conta.python.concetto': 'La boucle intérieure repart à chaque tour de la boucle extérieure : `range(i)` fait i tours, donc 0, 1, 2, …',
  'modelli.annidati-conta.python.frase': `{hai} : c'est ce que donnerait \`range(i + 1)\`. Avec i = 0, \`range(i)\` ne fait aucun tour.`,
  'modelli.annidati-stelle.python.concetto': 'Pour chaque ligne i, la boucle intérieure affiche i symboles, puis `print()` passe à la ligne.',
  'modelli.annidati-stelle.python.frase': `{hai} : un symbole de trop par ligne. \`range(i)\` fait i tours, pas i + 1.`,
  'modelli.annidati-stelle.python.frase-2': `{hai} : il manque la dernière ligne. \`range(1, {n})\` va jusqu'à {n2}.`,
  'modelli.annidati-stelle.java.concetto': 'Pour chaque ligne i, la boucle intérieure affiche i symboles, puis `println()` passe à la ligne.',
};
