// Le plan pour ceux qui travaillent (js/ore.js) : les durées « environ », les lignes de la semaine, ce qui ne rentre pas
// et les choix.
export default {
  'ore.circa-min': 'environ {m} min',
  'ore.circa-ore': { one: 'environ {n} heure', other: 'environ {n} heures' },
  'ore.circa-h': 'environ {h} h',
  'ore.circa-h-min': 'environ {h} h {m}',
  'ore.opzione-cuscinetto': "J'utilise aussi les jours tampons",
  'ore.opzione-un-ripasso': 'Une seule révision pour les nouveaux chapitres, pas deux',
  'ore.opzione-tetto': 'Les jours de travail, je révise 3 heures, pas 2',
  'ore.giorni-brevi': ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
  'ore.libere': '{circa} de libre',
  'ore.niente-ore-libere': 'pas de temps libre',
  'ore.giorno': '{g} {n}',
  'ore.lavoro': 'travail {turni}',
  'ore.voce-tema': "exercice d'annale ({circa})",
  'ore.argomento': 'chapitre',
  'ore.voce-generale': 'révision générale ({circa})',
  'ore.esame': 'Examen',
  'ore.voce-cuscinetto': '{nome} : jour tampon, pour rattraper',
  'ore.oggi-niente': "Aujourd'hui, tu n'as pas de temps libre pour réviser{lav}.",
  'ore.oggi-hai': "Aujourd'hui, tu as {liberi}{lav} : {lista}.",
  'ore.oggi-hai-vuoto': "Aujourd'hui, tu as {liberi}{lav}. Rien de prévu dans le plan aujourd'hui.",
  'ore.per-esame': '{circa} pour {nome}',
  'ore.un-esame': 'un examen',
  'ore.mancano': "Il te reste {circa} à faire avant l'examen de {nome}.",
  'ore.questo-esame': 'cet examen',
  'ore.recuperi': '{testo} · tu rattrapes {circa}',
  'ore.ripiego': "Avec tes heures, tout ne rentre pas. Tu peux m'écrire des jours de révision en plus (« je révise de 9h à 21h ») ou viser la session d'après : c'est toi qui décides.",
  'ore.mancano-ancora': 'Il te manque encore {circa}.',
  'ore.ora-ci-sta': 'Maintenant, ça rentre.',
};
