// Textes de la page sous la barre (français) : salutation, chiffres du parcours, cartes des examens, relevé de notes,
// paquets, fenêtres de l'examen et des réglages, sauvegarde.
export default {
  // salutation et ligne en dessous
  'pagina.saluto-notte': 'Encore debout',
  'pagina.saluto-mattina': 'Bonjour',
  'pagina.saluto-pomeriggio': 'Bon après-midi',
  'pagina.saluto-sera': 'Bonsoir',
  'pagina.saluto-con-nome': '{saluto}, {nome}.',
  'pagina.saluto-senza-nome': '{saluto}.',
  'pagina.sotto-esame': '{nome} {quando}',
  'pagina.sotto-carte': { one: '{n} carte à réviser', other: '{n} cartes à réviser' },
  'pagina.sotto-serie': { one: "{n} jour d'affilée", other: "{n} jours d'affilée" },
  'pagina.sotto-niente': "Rien en attente aujourd'hui.",
  'pagina.sotto-vuoto': 'Ton relevé de notes, ton plan de révision et tes cartes. Tout ici, tout à toi.',
  // en-tête
  'pagina.sottotitolo': "assistant d'étude",
  'pagina.esporta': 'Exporter',
  'pagina.impostazioni': 'Réglages',
  'pagina.suggerimento': 'Passe sur la barre en haut, appuie sur <kbd>/</kbd> pour écrire ou maintiens <kbd>{tasti}</kbd> pour parler.',
  // les chiffres
  'pagina.media-ponderata': 'Moyenne pondérée',
  'pagina.media-dettaglio': { one: 'arithmétique {media} · {n} note', other: 'arithmétique {media} · {n} notes' },
  'pagina.primo-voto': 'note ta première note depuis la barre',
  'pagina.base-laurea': 'Base di laurea (sur 110)',
  'pagina.base-formula': 'moyenne × 110 / 30',
  'pagina.crediti': 'Crédits',
  'pagina.cfu-alla-laurea': '{n} crédits pour le diplôme',
  'pagina.questa-settimana': 'Cette semaine',
  'pagina.minuti-settimana': 'Minutes de révision ces 7 derniers jours',
  'pagina.giorno-ore': '{giorno} : {ore}',
  'pagina.iniziali-giorni': ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
  // examens
  'pagina.prossimi-esami': 'Prochains examens',
  'pagina.nuovo-esame': 'Nouvel examen',
  'pagina.vuoto-scrivi': 'Écris dans la barre en haut :',
  'pagina.vuoto-comando': 'examen analyse 2 le 15 janvier 9 ects',
  'pagina.vuoto-oppure': 'ou {bottone}',
  'pagina.prova-esempio': "essaie avec les données d'exemple",
  'pagina.programma-aggiungi': "+ Programme de l'examen",
  'pagina.giorno-cuscinetto': 'jour tampon',
  'pagina.ripasso-generale': 'révision générale',
  'pagina.niente-di-nuovo': 'rien de nouveau',
  'pagina.programma-pronto': "<b>{pct} % du programme</b> · aujourd'hui : {oggi}",
  'pagina.data-da-decidere': 'Date à fixer',
  'pagina.quando-cfu': '{quando} · {cfu} crédits',
  'pagina.giorni-maiuscolo': { one: 'JOUR', other: 'JOURS' },
  'pagina.ore-studiate': '{fatte} sur {tot} h de révision',
  'pagina.ore-oggi': "<b>{h} h</b> aujourd'hui",
  'pagina.oggi-in-pari': "à jour aujourd'hui",
  'pagina.focus': 'Focus',
  'pagina.ripassa': 'Réviser',
  'pagina.ripassa-n': 'Réviser {n}',
  'pagina.interrogami': 'Interroge-moi',
  'pagina.modifica-segna-voto': 'Modifier · Noter la note',
  // relevé de notes et révision
  'pagina.libretto': 'Relevé de notes',
  'pagina.segna-voto': 'Noter une note',
  'pagina.ripasso': 'Révision',
  'pagina.da-file': 'Depuis un fichier',
  'pagina.libretto-vuoto': "Aucun examen passé. Écris dans la barre <kbd>j'ai eu 15 en physique</kbd>.",
  'pagina.col-esame': 'Examen',
  'pagina.col-cfu': 'Crédits',
  'pagina.col-voto': 'Note',
  'pagina.col-data': 'Date',
  'pagina.idoneo': 'validé',
  'pagina.voto-lode': '{voto}L',
  'pagina.modifica-esame': 'Modifier {nome}',
  'pagina.libretto-esami': '{n} examens · {cfu} crédits',
  'pagina.libretto-media': 'moyenne <b>{media}</b> · base <b>{base}</b>',
  'pagina.mazzi-vuoto': 'Pas encore de cartes. Écris <kbd>carte : question = réponse</kbd> ou glisse un PDF sur la fenêtre.',
  'pagina.esame-tolto': 'Examen retiré',
  'pagina.senza-esame': 'Sans examen',
  'pagina.n-carte': { one: '{n} carte', other: '{n} cartes' },
  'pagina.da-ripassare-oggi': "à réviser aujourd'hui",
  'pagina.piede': 'Lode est open source (MIT). Tes données restent dans ce navigateur : pas de compte, pas de serveur.',
  'pagina.importa-backup': 'Importer une sauvegarde',
  // fenêtre de l'examen
  'pagina.esame-correggi': 'Corrige les infos ou note ta note.',
  'pagina.esame-aiuto': "Tu peux aussi l'écrire dans la barre : « examen physique 2 le 20 février 6 ects ».",
  'pagina.campo-nome': 'Nom',
  'pagina.esempio-esame': 'Analyse 2',
  'pagina.campo-cfu': 'Crédits',
  'pagina.campo-data': 'Date',
  'pagina.campo-data-appello': "Date de l'examen",
  'pagina.campo-voto': 'Note',
  'pagina.campo-voto-nota': "vide si tu ne l'as pas encore passé",
  'pagina.trenta-e-lode': '30 avec mention (lode)',
  'pagina.idoneita': 'Validé sans note',
  'pagina.campo-ore': 'Heures de révision prévues',
  'pagina.campo-ore-nota': 'pour le plan',
  'pagina.ore-segnaposto': '10 × crédits',
  'pagina.elimina': 'Supprimer',
  'pagina.annulla': 'Annuler',
  'pagina.salva': 'Enregistrer',
  'pagina.conferma-elimina': 'Supprimer {nome} ? Ses heures et ses cartes restent, sans examen.',
  'pagina.esame-eliminato': 'Examen supprimé',
  'pagina.salvato': 'Enregistré',
  'pagina.esame-aggiunto': 'Examen ajouté',
  // fenêtre des réglages
  'pagina.impostazioni-aiuto': "Tout reste sur cet ordinateur. La clé de ton IA ne va qu'au service que tu choisis.",
  'pagina.campo-tuo-nome': 'Ton prénom',
  'pagina.esempio-nome': 'Camille',
  'pagina.campo-corso': 'Formation',
  'pagina.esempio-corso': 'Licence informatique',
  'pagina.campo-cfu-laurea': 'Crédits du diplôme',
  'pagina.campo-lode-vale': 'La « lode » vaut',
  'pagina.campo-focus': 'Focus (minutes)',
  'pagina.campo-pausa': 'Pause (minutes)',
  'pagina.rintocco': 'Petit son à la fin du focus',
  'pagina.aspetto-chiaro': 'Thème clair',
  'pagina.campo-ai': 'Ton IA',
  'pagina.campo-ai-nota': "facultative, payée à l'usage : c'est toi qui paies le service",
  'pagina.solo-locale': 'Seulement le cerveau local (gratuit)',
  'pagina.campo-chiave': 'Clé',
  'pagina.campo-chiave-nota': 'elle se crée sur le site du service',
  'pagina.chiave-segnaposto': 'colle la clé',
  'pagina.voce-alta': 'Lire les réponses à voix haute',
  'pagina.ai-attiva': 'IA <b>active</b> : {nome}.',
  'pagina.senza-chiave': "Sans clé, Lode marche quand même : commandes, minuteur, relevé de notes et révisions sont tous en local ; dans l'appli, il y a aussi le cerveau local gratuit.",
  'pagina.cancella-tutto': 'Tout effacer',
  'pagina.conferma-azzera': 'Effacer toutes les données de Lode de ce navigateur ? Mieux vaut les exporter avant.',
  'pagina.dati-cancellati-chiave': 'Données effacées, la clé de {nome} aussi : révoque-la aussi dans ton compte ({sito})',
  'pagina.dati-cancellati': 'Données effacées',
  'pagina.chiave-cancellata': 'Clé de {nome} effacée ici : révoque-la aussi dans ton compte ({sito})',
  'pagina.impostazioni-salvate': 'Réglages enregistrés',
  'pagina.ai-collegata': '{nome} connectée',
  'pagina.ai-collegata-modello': '{nome} connectée · {modello}',
  'pagina.chiave-non-valida': "La clé n'est pas valide",
  'pagina.chiave-non-verificabile': "Je n'arrive pas à vérifier la clé pour l'instant",
  // sauvegarde et données d'exemple
  'pagina.backup-scaricato': 'Sauvegarde téléchargée',
  'pagina.conferma-importa': 'Remplacer les données actuelles par cette sauvegarde ?',
  'pagina.backup-importato': 'Sauvegarde importée',
  'pagina.non-backup': "Ce fichier n'est pas une sauvegarde de Lode",
  'pagina.conferma-esempio': "Charger les données d'exemple à la place des tiennes ?",
  'pagina.esempio-caricato': "Données d'exemple chargées : passe sur la barre en haut",
};
