// « Suis le projet » dans la barre (français) : pastille, fiches « Je suis… ? », « Ce qui change »,
// « C'est fait. En clair », « Testé ? » et « Nouveautés ».
export default {
  'progetto.solo-app': "Suivre un projet, ça ne marche que dans l'appli de bureau de Lode.",
  'progetto.provo': 'je teste…',
  'progetto.file-cambiati': '{n} fich. +{piu} −{meno}',
  'progetto.fatto-non-provato': 'fait · pas testé',
  'progetto.oggi-non-provato': '{nome} : pas testé',
  'progetto.oggi-esito': '{nome} : {breve}',
  'progetto.oggi-sta-cambiando': '{nome} : en cours de modification',
  'progetto.ultima-prova-alle': 'Le dernier test, à {ora}',
  'progetto.vedi': 'Voir',
  'progetto.esito': 'Résultat',
  'progetto.prova': 'Tester',
  'progetto.provato': 'Testé ?',
  'progetto.cosa-e-cambiato': 'Ce qui a changé',
  'progetto.cosa-sta-cambiando': 'Ce qui change',
  'progetto.serve-seguito': "Il faut un projet suivi dans l'appli : écris « suis le projet ».",
  'progetto.non-seguo-nome': 'Je ne suis aucun projet qui s\'appelle « {nome} ».',
  'progetto.non-seguo-niente': 'Je ne suis aucun projet. Écris **suis le projet** et choisis le dossier du TP.',
  'progetto.capito-testo': "Lode regarde les fichiers et vérifie si le code est testé : il n'écrit pas de code à ta place. Si tu utilises un agent ou une IA, c'est ton cours qui décide de ce qui est permis : demande à ton prof. Le journal est un registre pour toi, pas une preuve pour le prof : c'est ce que Lode a vu, et il ne sait pas qui a écrit les lignes. Pour un rendu noté, marque le projet comme \"noté\" : Lode te dira où regarder et ce que veut dire une erreur, mais il ne te montrera pas la correction.",
  'progetto.prima-di-cominciare': 'Avant de commencer',
  'progetto.ho-capito': "J'ai compris",
  'progetto.solo-app-desktop': "Suivre un projet, ça ne marche que dans l'**appli de bureau** de Lode : là, je regarde le dossier de ton TP.",
  'progetto.va-bene-non-seguo': "D'accord, je ne suis aucun projet.",
  'progetto.seguo-gia': 'Je suis déjà **{nome}**.',
  'progetto.seguo-domanda': 'Je suis le projet <b>{nome}</b> ?',
  'progetto.seguo-aria': 'Je suis le projet {nome} ?',
  'progetto.seguo-spiega': "Je regarde les fichiers et je garde les versions dans le dossier de Lode : moi, je n'écris pas dans ton dossier. Les commandes que tu confirmes (make, par exemple), oui, comme depuis le terminal. Je ne sais pas qui écrit les lignes (toi, un agent ou un copier-coller) : je te dis ce qui a changé et si tu l'as testé.",
  'progetto.nota-windows': "Tant que je le suis, Windows ne te laisse pas renommer ni déplacer le dossier : d'abord, écris « arrête de suivre ».",
  'progetto.corso': 'Cours',
  'progetto.nessun-corso': 'Aucun cours',
  'progetto.valutato': 'Projet noté (rendu)',
  'progetto.valutato-spiega': 'Je te dis où regarder, mais pas de correction toute faite',
  'progetto.no-diario': "Ne pas tenir le journal de ce projet",
  'progetto.no-diario-spiega': 'Aucun nom de fichier ni de fonction ne finit dans le coffre',
  'progetto.n-file': { one: '{n} fichier', other: '{n} fichiers' },
  'progetto.segui': 'Suivre',
  'progetto.annulla': 'Annuler',
  'progetto.annullato': 'Annulé.',
  'progetto.non-seguo-niente-nota': 'Je ne suis rien.',
  'progetto.seguo-fatto': 'Je suis le projet {nome}.',
  'progetto.seguo-fatto-nota': 'Je te dis ce qui change et si tu l\'as testé. Je garde les versions dans le dossier de Lode.',
  'progetto.seguo-sintesi': 'je suis {nome}',
  'progetto.smetto-domanda': "J'arrête de suivre <b>{nome}</b> ?",
  'progetto.smetto-spiega': 'Je supprime les copies gardées dans le dossier de Lode. Je ne touche pas à tes fichiers.',
  'progetto.smetti-di-seguire': 'Arrêter de suivre',
  'progetto.continuo-a-seguire': 'Je continue à suivre {nome}.',
  'progetto.non-seguo-piu': 'Je ne suis plus {nome}.',
  'progetto.non-seguo-piu-nota': "Les copies de Lode ont été supprimées. Je n'ai pas touché à tes fichiers.",
  'progetto.smesso-sintesi': 'arrêté : {nome}',
  'progetto.etichetta-nuovo': 'nouveau',
  'progetto.etichetta-tolto': 'supprimé',
  'progetto.etichetta-grande': 'gros fichier : seulement les comptes',
  'progetto.etichetta-spazi': 'seulement des espaces ou des retours à la ligne',
  'progetto.etichetta-cambiato': 'modifié',
  'progetto.diff': 'Diff',
  'progetto.chiudi': 'Fermer',
  'progetto.diff-grande': 'Gros fichier (+{piu} −{meno}) : je ne montre pas le détail.',
  'progetto.diff-solo-spazi': 'Seuls les espaces en fin de ligne ou les retours à la ligne changent.',
  'progetto.diff-aria': 'Modifications de {file}',
  'progetto.diff-tagliato': '… je ne montre pas la suite',
  'progetto.niente-di-diverso': 'Rien de différent.',
  'progetto.niente-di-nuovo': 'Rien de nouveau.',
  'progetto.niente-di-nuovo-dalle': 'Rien de nouveau depuis {ora}.',
  'progetto.nome-dalle': '{nome} depuis {ora}',
  'progetto.prova-adesso': 'Tester maintenant',
  'progetto.visto': 'Vu',
  'progetto.provato-breve': 'testé',
  'progetto.prova-il-progetto': 'Tester le projet',
  'progetto.visto-fatto': 'Vu.',
  'progetto.visto-nota': 'À partir de maintenant, je ne te montre que les nouvelles modifications.',
  'progetto.visto-sintesi': 'vu',
  'progetto.fatto-titolo': "C'est fait. En clair",
  'progetto.vedi-le-modifiche': 'Voir les modifications',
  'progetto.modifiche-tratto': 'Modifications · {da}–{a}',
  'progetto.provato-si': '**Oui** : le code de {nome} est celui testé à {ora} ({breve}).',
  'progetto.provato-no-cambiato': '<b>Non</b> : après le dernier test ({ora}), le code de {nome} a changé.',
  'progetto.provato-no-cambiato-alle': '<b>Non</b> : après le dernier test ({ora}), le code de {nome} a changé, la dernière fois à {ultima}.',
  'progetto.provato-no-mai': "<b>Non</b> : tu n'as pas encore testé {nome} avec Lode.",
  'progetto.provato-nota': 'Je ne sais pas qui a écrit les lignes : je sais seulement si le code actuel est passé par un test.',
  'progetto.comando-manca': 'Pour tester {nome}, il manque {cosa}',
  'progetto.comando-come': 'Comment je teste {nome} ?',
  'progetto.comando-lancia': "Maintenant il y a des tests .in/.out : pour lancer le programme, il me faut un nouveau oui.",
  'progetto.comando-cambiato': "Les fichiers du projet ont changé : la commande d'avant ne suffit plus.",
  'progetto.comando-userei': "Pour tester, j'utiliserais <code>{comando}</code>",
  'progetto.comando-nota': "Je n'exécute que la commande que tu confirmes dans la fenêtre du système, jamais une commande proposée par un agent. Ce n'est pas un bac à sable : le programme tourne sur ton ordinateur, comme depuis le terminal, et peut écrire des fichiers dans ton dossier.",
  'progetto.riprova': 'Réessayer',
  'progetto.usa-questo': 'Utiliser celle-ci',
  'progetto.scrivo-io': "J'écris la commande moi-même",
  'progetto.cambia': 'Changer',
  'progetto.comando-aria': 'Commande pour tester',
  'progetto.usa-questo-comando': 'Utiliser cette commande',
  'progetto.non-eseguo': "Je n'exécute rien.",
  'progetto.non-confermato': "Tu n'as pas confirmé la commande.",
  'progetto.comando-confermato': 'Commande confirmée.',
  'progetto.comando-confermato-nota': "Pour ce projet, je l'utilise toujours, tant que la structure des fichiers ne change pas.",
  'progetto.comando-confermato-sintesi': 'commande confirmée',
  'progetto.uscita-caso': '— test {caso} —',
  'progetto.non-seguo-questo': 'Je ne suis pas ce projet.',
  'progetto.sto-gia-provando': 'Je teste déjà ce projet : un instant.',
  'progetto.niente': 'rien',
  'progetto.riga-vuota': 'une ligne vide',
  'progetto.caso-ok': 'Test {caso}',
  'progetto.caso-ok-codice': 'Test {caso} · passe, mais le programme sort avec le code {codice}',
  'progetto.caso-errore': 'Test {caso} : {errore}',
  'progetto.caso-scaduto': "Test {caso} : pas fini à temps. Une boucle qui ne s'arrête pas, ou le programme attend une autre entrée ?",
  'progetto.caso-troncato': "Test {caso} : il a écrit trop (plus de 200 Ko) et je l'ai arrêté.",
  'progetto.caso-crash': "Test {caso} : le programme s'est arrêté sur une erreur.",
  'progetto.caso-crash-segnale': "Test {caso} : le programme s'est arrêté sur une erreur ({segnale}).",
  'progetto.caso-crash-codice': "Test {caso} : le programme s'est arrêté sur une erreur (code {codice}).",
  'progetto.caso-diverso': 'Test {caso} · ligne {riga} : attendu {atteso}, obtenu {ottenuto}',
  'progetto.sintassi-ok': 'La syntaxe est correcte',
  'progetto.sintassi-errore': 'Erreur de syntaxe',
  'progetto.make-ok': 'make a marché',
  'progetto.make-errore': 'make a échoué',
  'progetto.compila': 'Ça compile',
  'progetto.non-compila': 'Ça ne compile pas',
  'progetto.durata': '{s} s',
  'progetto.esito-passa': { one: '{si}, et le test passe.', other: '{si}, et les {n} tests passent.' },
  'progetto.esito-senza-prove': "{si}. Il n'y a pas de tests .in/.out : je n'ai pas lancé le programme.",
  'progetto.esito-non-passano': { one: '{n} test sur {tot} ne passe pas.', other: '{n} tests sur {tot} ne passent pas.' },
  'progetto.non-compila-frase': '{no}.',
  'progetto.non-compila-file': '{no} : {file}.',
  'progetto.non-compila-file-riga': '{no} : {file}, ligne {riga}.',
  'progetto.non-partita': "Le test n'a pas démarré.",
  'progetto.passano': 'Passent : {nomi}',
  'progetto.saltate': { one: '{n} test sauté : {motivo}.', other: '{n} tests sautés : {motivo}.' },
  'progetto.avvisi': { one: '{n} avertissement du compilateur.', other: '{n} avertissements du compilateur.' },
  'progetto.cambiato-durante': '<b>Le code a changé pendant que je testais : je recommence ?</b>',
  'progetto.rifai': 'Recommencer',
  'progetto.prova-di-nuovo': 'Tester à nouveau',
  'progetto.nota-cose-nuove': "D'après le dictionnaire de Lode : seulement des fonctions de la bibliothèque standard. Il ne voit pas les idées, seulement les noms.",
  'progetto.file-riga': '{file}, ligne {riga}',
  'progetto.domanda-orale': "Question d'oral :",
  'progetto.risposta': 'Réponse',
  'progetto.cose-nuove': 'Nouveautés : {nomi}',
  'progetto.mettila-nel-ripasso': 'Ajouter aux révisions',
  'progetto.la-so-gia': 'Je la connais déjà',
  'progetto.nel-ripasso': 'Dans les révisions.',
  'progetto.la-sai-gia': 'tu la connais déjà',
};
