// Systèmes de notation (français) : noms, crédits, note finale, mentions et classes (js/sistemi.js).
export default {
  'sistemi.scelta': 'Système de notation',
  'sistemi.nome.it': 'Italie · 18–30 cum laude',
  'sistemi.nome.es': 'Espagne · 0–10',
  'sistemi.nome.fr': 'France · 0–20',
  'sistemi.nome.de': 'Allemagne · 1,0–5,0',
  'sistemi.nome.pt': 'Portugal · 0–20',
  'sistemi.nome.br': 'Brésil · 0–10',
  'sistemi.nome.uk': 'Royaume-Uni · 0–100 %',
  'sistemi.nome.us': 'États-Unis · A–F (GPA)',
  'sistemi.crediti.it': 'CFU',
  'sistemi.crediti.es': 'ECTS',
  'sistemi.crediti.fr': 'ECTS',
  'sistemi.crediti.de': 'ECTS',
  'sistemi.crediti.pt': 'ECTS',
  'sistemi.crediti.br': 'crédits',
  'sistemi.crediti.uk': 'crédits',
  'sistemi.crediti.us': 'heures de crédit',
  'sistemi.media': 'Moyenne',
  'sistemi.ponderata': 'Moyenne pondérée',
  'sistemi.aritmetica': 'Moyenne simple',
  'sistemi.finale.it': 'Base de diplôme (sur 110)',
  'sistemi.finale.es': 'Moyenne du relevé (expediente)',
  'sistemi.finale.fr': 'Mention',
  'sistemi.finale.de': 'Note finale (Gesamtnote)',
  'sistemi.finale.pt': 'Moyenne finale',
  'sistemi.finale.br': 'Coefficient de rendement (CR)',
  'sistemi.finale.uk': 'Classe du diplôme',
  'sistemi.finale.us': 'GPA',
  'sistemi.mention.passable': 'Passable',
  'sistemi.mention.assezBien': 'Assez bien',
  'sistemi.mention.bien': 'Bien',
  'sistemi.mention.tresBien': 'Très bien',
  'sistemi.mention.nessuna': 'sans mention',
  'sistemi.classe.first': 'First',
  'sistemi.classe.upperSecond': '2:1 (Upper Second)',
  'sistemi.classe.lowerSecond': '2:2 (Lower Second)',
  'sistemi.classe.third': 'Third',
  'sistemi.classe.fail': 'Ajourné',
  'sistemi.idoneo': 'validé',
  'sistemi.lode': '30 cum laude',
  'sistemi.matricula': 'Matrícula de Honor',
  'sistemi.sufficienza': 'Moyenne : {v}',
  'sistemi.su': '{v}/{max}',
  'sistemi.conMention': '{v}/20 · {mention}',
  'sistemi.conClasse': '{classe} ({v})',
};
