// « Qu'est-ce que ça affiche ? », la fiche des exercices (français).
export default {
  'stampa.titolo': "Qu'est-ce que ça affiche ?",
  'stampa.anteprima': "Qu'est-ce qu'affiche {cosa} ?",
  'stampa.risposta-assente': "Cette réponse n'existe pas.",
  'stampa.hai-scritto-altro': "Tu as écrit `{uscita}` : ce n'est pas ce que ça affiche.",
  'stampa.nessuna-risposta': 'Aucune réponse.',
  'stampa.aria-codice': 'Code {lingua}',
  'stampa.non-riesco': "Aujourd'hui, je n'arrive pas à préparer les questions de {lingua}. Réessaie dans un moment.",
  'stampa.conto': '{i} sur {n}',
  'stampa.scrivi-uscita': 'Écris la sortie exacte',
  'stampa.scegli-uscita': 'Choisis la sortie · touches 1-4',
  'stampa.aria-campo': 'Ce que le programme affiche',
  'stampa.segnaposto': 'Écris ce que ça affiche',
  'stampa.controlla': 'Vérifier <kbd>Entrée</kbd>',
  'stampa.piu-righe': 'Plusieurs lignes ? Sépare-les par une espace.',
  'stampa.aria-risposta': 'Réponse {n} : {uscita}',
  'stampa.giusto': 'Juste · calculé par Lode',
  'stampa.stampa-giusta': 'Ça affiche <code>{uscita}</code>.',
  'stampa.avanti': 'Suivant <kbd>Entrée</kbd>',
  'stampa.com-e-andata': 'Voir le résultat <kbd>Entrée</kbd>',
  'stampa.tutte-giuste': 'Tout juste. Les réponses ont été calculées par Lode.',
  'stampa.da-rinforzare': 'À retravailler : {nomi}. Reviens demain.',
  'stampa.secondi': { one: '{n} seconde', other: '{n} secondes' },
  'stampa.ancora-una': 'Encore une',
  'stampa.sintesi': "Qu'est-ce que ça affiche ? {punti} sur {tot}",
};
