// Textes de la synchro entre ordinateurs (français) : ce qui est chiffré et ce qui reste en clair, la ligne d'état et les
// avertissements (docs/SINCRONIZZAZIONE.md §10.7 et §12). Le README dit la même chose : voir js/sync-testi.js.
export default {
  'sync.cifrati': 'les données de Lode dans le journal (examens, notes, cartes et révisions, sessions, profil, réglages) : pas les pages pour Obsidian que Lode en tire, ci-dessous',
  'sync.in-chiaro': [
    'notes de cours, « Sbobine » (cours retranscrits), fichiers pour Anki, journaux des projets',
    '« Orario.md » avec les salles',
    'les pages que Lode écrit pour Obsidian, tirées justement de ces données : « Esami » (notes, moyenne, crédits et heures de révision par examen), « Memoria » (heures de révision du mois, à quel moment de la journée tu révises, ta série de jours, les définitions ratées et combien de fois), « Home » (le prochain examen, combien de cartes il y a à réviser), « Corsi », « Glossario »',
    'noms, tailles et heures des fichiers (quand tu révises)',
    "combien d'ordinateurs il y a, combien de fichiers chacun écrit et combien d'actions il y a dans chaque fichier (un fichier par jour)",
    "le fichier du groupe (sel et vérification du mot de passe, quand il a été créé et depuis quel ordinateur, l'empreinte de l'ancien dati.json)",
    'quand le mot de passe a changé',
    'le dati.json minimal qui dit de mettre à jour Lode',
  ],
  'sync.sul-computer': "Sur l'ordinateur, le journal de Lode reste en clair, protégé seulement par ton compte système.",
  'sync.cronologia': "Dans l'historique du service cloud, il reste ce qui était passé en clair avant le mot de passe.",
  'sync.dimenticata': "Si tu oublies le mot de passe, tu ne perds rien : chaque ordinateur a ses données sur le disque. Avec « J'ai oublié le mot de passe », tu en choisis un nouveau, et les autres ordinateurs te le demanderont.",
  'sync.nuova-password': 'Choisis un nouveau mot de passe. Les autres ordinateurs te le demanderont. Aucune donnée ne se perd : chaque ordinateur a les siennes sur le disque.',
  'sync.smetti': "Lode va copier le coffre dans un dossier en dehors de {servizio} et utiliser celui-là. Les autres ordinateurs continuent à se synchroniser entre eux. Pour arrêter partout, fais-le sur chaque ordinateur.",
  'sync.la-cartella-cloud': 'le dossier cloud',
  'sync.prima': 'Avant de synchroniser, mets à jour Lode sur tous les ordinateurs.',
  'sync.sperimentale': "C'est nouveau et expérimental : testé à fond avec un simulateur de plusieurs ordinateurs et un cloud capricieux, mais pas encore par beaucoup d'étudiants. Avant de l'activer, Lode garde une copie de tout : ton coffre actuel reste où il est, intact, et les données de Lode vont aussi dans le dossier « copie » des données de Lode. Si quelque chose cloche, raconte-le-nous sur GitHub (Issues de W1kicartel/Lode).",
  // la ligne d'état
  'sync.spenta': 'Désactivée · examens, notes et cartes restent sur cet ordinateur',
  'sync.fermo': 'Le journal de Lode sur cet ordinateur est illisible.',
  'sync.solo-qui': 'Seulement sur cet ordinateur · pas synchronisé',
  'sync.la-tua-cartella': 'ton dossier cloud',
  'sync.stato-password': 'En pause : écris le mot de passe pour synchroniser.',
  'sync.rigenerato-altra': 'Un autre mot de passe a été choisi au même moment sur un autre ordinateur : écris celui-là.',
  'sync.rigenerato': 'Le mot de passe a changé sur un autre ordinateur : écris le nouveau pour synchroniser.',
  'sync.sparito': "Le dossier de Lode dans le coffre n'est plus là : il a été déplacé ou supprimé ?",
  'sync.in-arrivo': 'Je reçois les données des autres ordinateurs… ({dove})',
  'sync.da-migrare': "J'attends les données du cloud…",
  'sync.scrittura': "Le disque est plein (ou on ne peut pas y écrire) : les dernières modifications attendent et je réessaie tout seul.",
  'sync.versione': 'Synchronisé avec {dove} · un autre ordinateur a une version plus récente de Lode : mets-la à jour',
  'sync.in-pari': 'Synchronisé avec {dove}',
  'sync.in-pari-cifrato': 'Synchronisé avec {dove} · chiffré',
  'sync.in-pari-ora': 'Synchronisé avec {dove} · vérifié à {ora}',
  'sync.in-pari-cifrato-ora': 'Synchronisé avec {dove} · chiffré · vérifié à {ora}',
  'sync.altro-stato': 'Synchro : {stato}',
  'sync.in-avvio': 'en cours de démarrage',
  // les avertissements
  'sync.avviso-clone': "Cet ordinateur ressemble à une copie d'un autre : à partir de maintenant, il a un nouveau nom. Rien n'est perdu.",
  'sync.avviso-orologio': "L'horloge d'un autre ordinateur semble très en avance : vérifie la date et l'heure.",
  'sync.avviso-rovinato-mio': "Un fichier de Lode de cet ordinateur dans le dossier cloud était abîmé ou trafiqué : je l'ai mis de côté et je l'ai réparé à partir du journal.",
  'sync.avviso-rovinato-altro': "Un fichier de Lode d'un autre ordinateur est abîmé ou trafiqué : je le saute jusqu'à ce qu'il redevienne lisible.",
  'sync.avviso-scrittura': "Le disque est plein ou on ne peut pas y écrire : les dernières modifications ne sont pas encore dans le journal. Je réessaie à chaque tour et quand tu fermes Lode.",
  'sync.avviso-recupero': "Le journal ne pouvait pas être écrit : les modifications de ce moment-là sont dans un fichier à part, dans le dossier des données de Lode.",
  'sync.avviso-portachiavi': "Le trousseau n'a pas donné le mot de passe de Lode (autorisation refusée, ou Lode mis à jour) : écris-le à nouveau.",
  'sync.avviso-gruppi-doppi': "Dans le dossier cloud, il y a deux groupes Lode, un chiffré et un non : je ne les fusionne pas tout seul.",
  'sync.avviso-lode-vecchia': "Une ancienne version de Lode a écrit des données dans .lode/dati.json : mets-la à jour. Elles n'entrent pas toutes seules : une copie est dans le dossier des données de Lode, et les nouveaux enregistrements s'importent avec « Importer les ajouts ».",
  'sync.avviso-altra-password': 'Un autre mot de passe a été choisi au même moment sur un autre ordinateur : écris celui-là.',
  'sync.avviso-manomesso': "Le fichier du groupe Lode dans le dossier cloud a été modifié de l'extérieur (il ne correspond pas au mot de passe) : je ne l'utilise pas. Vérifie le dossier cloud.",
  'sync.avviso-gruppo-chiaro': "Le fichier du groupe Lode dit « sans mot de passe », mais les données des autres ordinateurs sont chiffrées : il a été trafiqué ? Je ne publie rien tant que ce n'est pas réglé.",
  'sync.avviso-parametri': 'Ce coffre a été protégé par une version plus récente de Lode : mets-la à jour.',
};
