// Textes des pages que Lode écrit dans le coffre pour l'étudiant (français) : Home, Esami, Glossario, les pages des cours et
// la Memoria. Il n'y a pas les noms des notes, dossiers, sections et clés que le code relit : ceux-là restent tels quels dans
// le code (ils deviendront la table NOMI).
export default {
  // la mémoire
  'vault.prop-gioco': 'jeux',
  'vault.prop-ripasso': 'révision des cartes',
  'vault.prop-stelle': 'relire les ★',
  'vault.prop-orale': 'questions éclair',
  'vault.prop-focus': 'focus',
  'vault.prop-stampa': "qu'est-ce que ça affiche",
  'vault.prop-voce': '{nome} ({si} sur {tot})',
  'vault.memoria-proposte': 'Parmi les suggestions de Lode, tu acceptes surtout : {elenco}.',
  'vault.memoria-titolo': 'Ce que je sais de toi',
  'vault.memoria-commento': "Cette note, c'est Lode qui l'écrit. Tu peux la lire et aussi la corriger : je lis la section « {sezione} » chaque fois que j'utilise l'IA.",
  'vault.titolo-in-breve': 'En bref',
  'vault.memoria-lezioni': { one: '{n} cours annoté', other: '{n} cours annotés' },
  'vault.memoria-definizioni': { one: '{n} définition', other: '{n} définitions' },
  'vault.memoria-in-breve': '{lezioni}, {definizioni} : **{sicure} maîtrisées**, {deboli} à renforcer, {mai} pas encore jouées.',
  'vault.memoria-serie': { one: "Série de révision : {n} jour d'affilée. Ce mois-ci : {h} h.", other: "Série de révision : {n} jours d'affilée. Ce mois-ci : {h} h." },
  'vault.memoria-fascia': 'Tu révises surtout **{fascia}**.',
  'vault.fascia-mattina': 'le matin',
  'vault.fascia-pomeriggio': "l'après-midi",
  'vault.fascia-sera': 'le soir',
  'vault.titolo-da-rinforzare': 'À renforcer',
  'vault.sbagliata': { one: 'ratée {n} fois sur {tot}', other: 'ratée {n} fois sur {tot}' },
  'vault.niente-per-ora': "Rien, pour l'instant.",
  'vault.titolo-sicure': 'Maîtrisées',
  'vault.sicure-vuoto': 'Aucune pour le moment : fais quelques parties.',
  'vault.ancora-nessuna': 'Aucune pour le moment.',
  'vault.note-commento': "Écris ici comment tu veux être aidé : « explique-moi avec des exemples concrets », « je suis dyslexique, des phrases courtes », « l'oral d'analyse est avec Martin, très théorique ».",
  // Home
  'vault.home-carte': '{n} cartes à réviser',
  'vault.alias-memoria': 'Ce que Lode sait de moi',
  'vault.alias-benvenuto': 'Comment ça marche',
  'vault.titolo-oggi': "Aujourd'hui",
  'vault.aula': 'salle {aula}',
  'vault.niente-lezioni-oggi': "Pas de cours aujourd'hui.",
  'vault.titolo-corsi': 'Cours',
  'vault.n-lezioni': { one: '{n} cours', other: '{n} cours' },
  'vault.idoneo': 'validé',
  'vault.voto-e-lode': '{voto} avec mention (e lode)',
  'vault.appello': 'examen le {data}',
  'vault.corsi-vuoto': "Ajoute ton emploi du temps depuis la barre : « cours analyse 2 lundi 9h-11h salle 7 ».",
  'vault.titolo-ultime-lezioni': 'Derniers cours',
  'vault.definizioni-n': '{n} définitions',
  'vault.titolo-carriera': 'Parcours',
  'vault.carriera': 'Moyenne **{media}** · « base di laurea » **{base}**/110 · {cfu} sur {tot} crédits → {esami}',
  // Esami
  'vault.titolo-prossimi-appelli': 'Prochains examens',
  'vault.tabella-appelli': '| Examen | Date | Dans | Crédits | Heures de révision |',
  'vault.ore-di': '{fatte} sur {tot} h',
  'vault.nessun-appello': 'Aucun examen noté.',
  'vault.senza-data': 'Sans date : {elenco}.',
  'vault.titolo-libretto': 'Relevé de notes',
  'vault.tabella-libretto': '| Examen | Crédits | Note | Date |',
  'vault.voto-l': '{voto}L',
  'vault.libretto-piede': 'Moyenne pondérée **{media}** · « base di laurea » **{base}**/110 · {cfu} sur {tot} crédits',
  'vault.libretto-vuoto': 'Aucun examen passé pour le moment.',
  // Glossario
  'vault.n-definizioni': { one: '{n} définition', other: '{n} définitions' },
  'vault.da-rinforzare': '*à renforcer*',
  'vault.glossario-vuoto': 'Les définitions des cours apparaissent ici, par ordre alphabétique, classées par cours.',
  // la page du cours
  'vault.corso-cfu': '**{cfu} crédits**',
  'vault.corso-voto': 'note {voto}',
  'vault.corso-voto-lode': 'note {voto} avec mention (e lode)',
  'vault.corso-appello': 'examen **{data}** (dans {n} jours) · {fatte} sur {tot} h de révision',
  'vault.corso-lezioni': 'Cours : {elenco}',
  'vault.orario-voce': '{giorni} {inizio}–{fine}',
  'vault.orario-voce-aula': '{giorni} {inizio}–{fine} salle {aula}',
  'vault.lezioni-vuoto': "Aucun pour le moment : le premier apparaît quand tu notes quelque chose en cours.",
};
