// Noms du vault (js/nomi.js), français : dossiers, notes, sections et mots que Lode écrit dans un vault neuf et relit.
export default {
  // cartelle (create una volta, alla nascita del vault: poi restano quelle)
  'vaultnomi.cartella-lezioni': 'Cours',
  'vaultnomi.cartella-corsi': 'Matières',
  'vaultnomi.cartella-sbobine': 'Transcriptions',
  'vaultnomi.cartella-anki': 'Anki',
  'vaultnomi.cartella-allegati': 'Pièces jointes',
  'vaultnomi.cartella-materiali': 'Supports',
  'vaultnomi.cartella-progetti': 'Projets',
  'vaultnomi.cartella-modelli': 'Modèles',
  'vaultnomi.cartella-inbox': 'Inbox',
  // i «corsi» che Lode inventa quando non ce n'è uno (diventano cartelle e note)
  'vaultnomi.corso-sparsi': 'Notes en vrac',
  'vaultnomi.corso-videolezioni': 'Cours en vidéo',
  'vaultnomi.corso-varie': 'Divers',
  // note (senza «.md»)
  'vaultnomi.nota-home': 'Accueil',
  'vaultnomi.nota-orario': 'Emploi du temps',
  'vaultnomi.nota-esami': 'Examens',
  'vaultnomi.nota-glossario': 'Glossaire',
  'vaultnomi.nota-benvenuto': 'Bienvenue',
  'vaultnomi.nota-memoria': 'Mémoire',
  'vaultnomi.nota-tasca': 'Révision de poche',
  'vaultnomi.modello-lezione': 'Cours',
  'vaultnomi.modello-esame': 'Examen',
  'vaultnomi.modello-ripasso': 'Révision',
  // titoli delle sezioni che Lode scrive e rilegge
  'vaultnomi.sezione-appunti': 'Notes',
  'vaultnomi.sezione-stella': '★ Pour l\'examen',
  'vaultnomi.sezione-definizioni': 'Définitions',
  'vaultnomi.sezione-domande': 'Questions pour le prof',
  'vaultnomi.sezione-trascrizione': 'Transcription',
  'vaultnomi.sezione-riordinati': 'Notes remises au propre par Lode',
  'vaultnomi.titolo-note-per-lode': 'Notes pour Lode',
  'vaultnomi.titolo-cosa-ho-capito': 'Ce que j\'ai compris',
  'vaultnomi.titolo-cosa-so-davvero': 'Ce que je sais vraiment',
  'vaultnomi.titolo-informatica': 'Informatique',
  'vaultnomi.titolo-ripasso-in-tasca': 'Révision de poche',
  'vaultnomi.titolo-orario': 'Emploi du temps des cours',
  'vaultnomi.titolo-lezioni': 'Cours',
  'vaultnomi.titolo-stelle-ultime': '★ Pour l\'examen, les dernières',
  // il ripasso in tasca: il titolo della risposta e le due caselle (il giro le rilegge)
  'vaultnomi.parola-risposta': 'Réponse',
  'vaultnomi.parola-sapevo': 'je savais',
  'vaultnomi.parola-non-sapevo': 'je ne savais pas',
  // la nota dell'orario: colonne, giorni (domenica per primo) e la riga che spiega
  'vaultnomi.orario-colonne': ['Cours', 'Jours', 'Début', 'Fin', 'Salle'],
  'vaultnomi.giorni-brevi': ['dim', 'lun', 'mar', 'mer', 'jeu', 'ven', 'sam'],
  'vaultnomi.orario-spiega': 'Lode le lit pour savoir quand tu es en cours. Tu peux le modifier ici ou depuis la barre (« cours analyse 2 lundi et mercredi 9-11 salle 7 »).',
  // i commenti dentro le note nuove
  'vaultnomi.commento-definizioni': 'Une par ligne : - **Terme** : définition. Lode en fait des jeux de mémoire et des cartes.',
  'vaultnomi.commento-corso': 'Écris au-dessus ou en dessous : l\'encadré de Lode (cours, ★, examen) se met à jour tout seul et Lode ne touche pas au reste.',
  'vaultnomi.commento-cosa-ho-capito': 'Cette partie est à toi : Lode n\'y touche jamais. Ce que tu as compris aujourd\'hui, ce qui t\'échappe encore.',
  'vaultnomi.segnalibro-memoria': 'Ce que Lode sait de moi',
  // i modelli di Obsidian e le note che nascono col vault
  'vaultnomi.esame-programma': 'Programme',
  'vaultnomi.esame-domande': 'Questions qui tombent toujours',
  'vaultnomi.esame-domande-commento': 'Celles que tu entends des autres ou que tu trouves dans les anciens sujets. Lode s\'en sert pour t\'interroger.',
  'vaultnomi.esame-esercizi': 'Exercices types',
  'vaultnomi.esame-manca': 'Ce qui me manque',
  'vaultnomi.ripasso-tre-righe': 'En trois lignes',
  'vaultnomi.ripasso-commento-definizioni': '- **Terme** : définition. Elles finissent dans les jeux de Lode.',
  'vaultnomi.ripasso-collegamenti': 'Liens',
  'vaultnomi.ripasso-commento-collegamenti': 'Les cours et les notions liés : [[...]]',
  'vaultnomi.memoria-titolo': 'Ce que je sais de toi',
  'vaultnomi.memoria-commento': 'Lode écrit cette note après chaque jeu. La section « {sezione} » reste à toi : je la lis chaque fois que j\'utilise l\'IA.',
  'vaultnomi.memoria-in-breve': 'En bref',
  'vaultnomi.memoria-ancora-niente': 'Rien pour l\'instant : note quelques définitions en cours et joue une partie.',
  'vaultnomi.memoria-note-commento': 'Écris ici comment tu veux être aidé : « explique-moi avec des exemples concrets », « des phrases courtes », « l\'oral d\'Analyse est très théorique ».',
  'vaultnomi.benvenuto-firma': 'a été préparé par **Lode**',
  'vaultnomi.benvenuto-testo': '# Bienvenue dans ton vault\n\nCe vault {firma}, l\'assistant qui vit en haut de l\'écran. C\'est un vault Obsidian normal : les notes sont à toi, en Markdown, et restent sur cet ordinateur.\n\n## Comment ils travaillent ensemble\n- **En cours** Lode sait quand tu es en cours (grâce à l\'[[{orario}]]) et garde la note du cours prête dans `{lezioni}/<matière>/`. Depuis la barre, tu notes à la volée :\n  - **{stella}** (⌃⌥S) : ce que le prof a dit qu\'il demandera ;\n  - **Définition** (⌃⌥D) : « terme : définition » ;\n  - **Question** (⌃⌥Q) : à poser au prof.\n- **Tes notes**, tu les écris ici, dans Obsidian, comme d\'habitude. Les définitions que tu mets dans la section « {definizioni} » (`- **Terme** : définition`) ou écrites comme `Terme :: définition`, Lode les trouve tout seul.\n- **À la maison** la barre te propose deux minutes de jeu sur les définitions du dernier cours, juste quand elles sont sur le point de s\'envoler.\n- **[[{memoria}]]** (dans `{lode}/`) c\'est ce que Lode a appris de toi : définitions sûres, à renforcer, ta façon d\'étudier. Dans la section « {notePerLode} » tu peux lui dire comment tu veux être aidé.\n\n## Raccourcis\n| | Mac | Windows |\n|---|---|---|\n| Ouvrir Lode et écrire | ⌥ Espace | Ctrl ⇧ Espace |\n| {stella} | ⌃⌥ S | Ctrl Alt S |\n| Définition | ⌃⌥ D | Ctrl Alt D |\n| Question pour le prof | ⌃⌥ Q | Ctrl Alt Q |\n| Jeu de mémoire | ⌃⌥ G | Ctrl Alt G |\n',
  // frasi della barra che citano un nome del vault: il nome arriva dal vault, non dalla lingua della barra
  'vaultnomi.frase-orario-nel-vault': 'L\'emploi du temps est aussi dans le vault, dans « {nota} » : tu peux le modifier depuis Obsidian.',
  'vaultnomi.frase-nella-cartella': 'C\'est dans le dossier {cartella} du vault.',
  'vaultnomi.frase-riordinati-nota': 'Elles vont dans la note, dans « {sezione} », sous la transcription (qui reste). C\'est {motore} qui les a écrites : relis-les.',
};
